Docs(page)にタグを追加
fjordllc/bootcamp pull request #1718
Opened 2020-07-16 23:52 UTC by sasabo-git

2020-07-17 00:10 UTC, sasabo-git commented
@machida さん
デザインをお願いします🙇‍♂️🙏

2020-07-17 01:41 UTC, machida commented
@sasabo-git 実装ありがとうございます！！デザイン了解ですー

2020-07-21 02:27 UTC, komagata commented
![47f894df82180df872afb848553d391d](https://user-images.githubusercontent.com/16577/88005787-1abd0a80-cb45-11ea-8bff-223445df3c0f.png)

こういう感じにするgemかnpm導入したいっすね。

2020-07-21 11:03 UTC, sasabo-git commented
> こういう感じにするgemかnpm導入したいっすね。

@komagata さん
@machida さんからも同様の要望をうかがっています。
https://github.com/fjordllc/bootcamp/issues/1704#issuecomment-659117935

このIssueでやりきりましょうか？それとも別Issueにしますか？

2020-07-22 06:52 UTC, komagata commented
@sasabo-git 別Issueで大丈夫です〜。

2020-07-22 08:04 UTC, sasabo-git commented
@komagata さん
デザイン前に先にコードレビューをお願いします🙇‍♂️🙏

2020-07-28 02:20 UTC, komagata commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
ここって何をしようとしていますか？

ライブラリで対応してたりしないですかね。そうでない場合もTag自身にValidationを設定したりできないですかね？

2020-07-28 02:21 UTC, komagata commented on app/views/pages/_page_list_item.slim
> +      = raw page.tag_list.map { |t| link_to t, pages_tag_path(t) }.join(", ")
これってviewに書いてあるeachだけで表現できないですかね？

もしくはこういう処理をするとしたらviewの中に直接書くのではなく、decoratorやview helperを使いたいです。

2020-07-28 02:24 UTC, komagata commented on app/views/pages/index.html.slim
> +          - @pages.each do |page|
Pageモデルのインスタンスに対応するviewをそれぞれ表示する場合は下記のようにかけますがそれだと変になっちゃいますかね。

できればデフォルトのルールに従ったpartial名にしたいです。

```slim
= render @pages
```

もしくは

```slim
= render partial: "pages/page", collection: @pages, as: :page
```

2020-07-28 02:27 UTC, komagata commented on test/system/pages_test.rb
> +    fill_in "page[title]", with: "tagのテスト"
formを使うときはなるべくwithinで絞りたいです。

https://github.com/fjordllc/bootcamp/blob/master/test/system/courses_test.rb#L15

2020-07-30 02:17 UTC, machida commented
@sasabo-git デザイン入れましたー

2020-07-31 09:39 UTC, sasabo-git commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
> ここって何をしようとしていますか？

タグに空白文字が含まれないようにしています。(ho geのような文字の間に空白があるタグ）

> ライブラリで対応してたりしないですかね。

ライブラリはtagの前後の空白文字は取り除いてくれますが、文字の間の空白は取り除いてくれないようです。

> Tag自身にValidationを設定したりできないですかね？

すみません、質問がよく分かりませんでした😢
gemにモンキーパッチを当ててtagのnameをValidationして対応するということでしょうか？
https://github.com/mbleigh/acts-as-taggable-on/blob/950c01072b7ab6227d74dc0d0b112f0135281fc2/lib/acts_as_taggable_on/tag.rb#L10

2020-07-31 10:15 UTC, sasabo-git commented on app/views/pages/_page_list_item.slim
> +      = raw page.tag_list.map { |t| link_to t, pages_tag_path(t) }.join(", ")
> viewに書いてあるeachだけで表現

こういう理解で良いでしょうか？
``` slim
- page.tag_list.each do |tag|
  = link_to tag, pages_tag_path(tag)
```

2020-07-31 10:34 UTC, sasabo-git commented on app/views/pages/index.html.slim
> +          - @pages.each do |page|
なるほど、たしかにそちらの方が良さそうですね。
ご指摘の箇所については今回変更は加えていないのですが、私の方で変更して良いですか？（もともと`render "page_list_item", page: page`でした）
`_page_list_item.slim`を`_page.slim`にリネームしようと思っています。

2020-07-31 11:04 UTC, sasabo-git commented on test/system/pages_test.rb
> +    fill_in "page[title]", with: "tagのテスト"
了解しました。修正します。

2020-08-02 17:14 UTC, komagata commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
### 空白について

空白以外の文字がdelimiterの場合、空白は必要ではないですかね？（その辺りの議論が必要かも）

### Validationについて

これ系のgemにはよくありますが、自身でTagクラスを定義することでTagクラスの実装を設定できるようになっていることが多いのでそちらの方法でできないかなという意味です。

これをgemのモンキーパッチと呼ぶか、gem自身が提供している拡張方法と呼ぶのかは分かりませんが。

2020-08-02 17:17 UTC, komagata commented on app/views/pages/_page_list_item.slim
> +      = raw page.tag_list.map { |t| link_to t, pages_tag_path(t) }.join(", ")
viewでプログラム的にjoinして文字列を組み立てるのはなるべく避けたい（viewは見た目の通り表示される感じがメリットなので）という感じです。

2020-08-02 17:18 UTC, komagata commented on app/views/pages/index.html.slim
> +          - @pages.each do |page|
いいとおもいます。

2020-08-04 00:15 UTC, sasabo-git commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
なるほど。ありがとうございます。delimiterをカンマから空白に変更する場合を考えると空白が必要になる場合が出てきますね。空白が文字の間にある場合は最悪ユーザーが修正できるので空白は許容できる気もしてきました。
@komagata さん、@machida さん
https://github.com/fjordllc/bootcamp/issues/1704#issuecomment-659117092
↑この要件どうしましょうか？
私はカンマをdelimiterとして、タグとして許容しないのは「単独スペース」「単独カンマ」「文中のカンマ」で「文中のスペース」は許容で良いと思ってきました。
🆖  「 」 「,」 「ho,ge」(この場合hoとgeがタグとして登録される)
🆗  「ho ge」（この場合ho geがタグとして登録される）

2020-08-04 00:16 UTC, sasabo-git commented on app/views/pages/_page_list_item.slim
> +      = raw page.tag_list.map { |t| link_to t, pages_tag_path(t) }.join(", ")
ありがとうございます。了解しました。修正してみます。

2020-08-04 02:26 UTC, sasabo-git commented on app/views/pages/_page_list_item.slim
> +      = raw page.tag_list.map { |t| link_to t, pages_tag_path(t) }.join(", ")
decoratorを使って修正しました。確認をお願いします。

2020-08-04 02:28 UTC, sasabo-git commented on app/views/pages/index.html.slim
> +          - @pages.each do |page|
修正しましたので確認をお願いします。

2020-08-04 02:29 UTC, sasabo-git commented on app/views/pages/index.html.slim
> +          - @pages.each do |page|
修正しましたので確認をお願いします。

2020-08-04 02:29 UTC, sasabo-git commented on test/system/pages_test.rb
> +    fill_in "page[title]", with: "tagのテスト"
修正しました。確認をお願いします。

2020-08-04 06:12 UTC, komagata commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
> [#1704 (comment)](https://github.com/fjordllc/bootcamp/issues/1704#issuecomment-659117092)
> ↑この要件どうしましょうか？

@sasabo-git すみません、こういう要件があったことを知らずに今までやりとりしてしまっていました。

@machida タグにスペースはあってもいい（使えた方がいい）ように思いますがいかがでしょうか。
acts-as-taggable-onでもデフォルトでスペースがあっても問題ないように作られているのはそういう判断かなと思います。（カンマがdelimiterなのでカンマは入らないようになっている）
（カンマの方は）

2020-08-05 03:38 UTC, komagata commented on app/views/pages/_page_list_item.slim
> +    - if page.tag_list.present?
<img width="282" alt="スクリーンショット 2020-08-05 12 36 26" src="https://user-images.githubusercontent.com/16577/89369218-6f04e480-d718-11ea-8e78-538590fda9d4.png">

Tagが一つもないとこう言う見た目になるので何か工夫したいですね。

@machida どんな見た目にするのがいいですかね？

2020-08-07 02:25 UTC, sasabo-git commented on app/views/pages/_page.slim
> +            = page.tag_list_links("</li><li class='thread-list-item-tags__item'>")
なるほどです。`tag_list`ではなくて`tags`が使えたんですね。修正しましたので確認をお願いします。

2020-08-09 05:16 UTC, komagata commented on app/views/pages/_page.slim
> +            = page.tag_list_links("</li><li class='thread-list-item-tags__item'>")
すみません、上記の僕のコメントでも伝わりづらいっすね。

レビュー時に元から「tagsメソッドがあるのでこれを使って欲しい」と思ったわけではなく、

rails使ってる人の感覚としては、

- 今回の使い方は一般的・代表的な使い方（一番ありそうな使い方）
- 文字列を連結しないとできないような作りにはなってないはずだ（と思う）。gemの作者やユーザーが見逃すはずはない。
- 何かもっとスマートな方法が用意されてるはず。

って感じなので、

gemの公式ドキュメントや、ネット上の使っている記事をもうちょっと調べてみてください

という感じです。

2020-08-09 05:22 UTC, komagata commented on app/views/pages/index.html.slim
> +                  = link_to tag, pages_tag_path(tag.to_s), class: "page-tags-nav__item-link"
すみません、コードを動かして確かめたわけではないですが、tagがオブジェクトだとしたら`tag.name`みたいなメソッドがありそうで、そちらの方がいいかも？

2020-08-09 05:22 UTC, komagata commented on app/views/pages/show.html.slim
> +            = raw @page.tag_list.map { |t| link_to t, pages_tag_path(t) }.join(", ")
こちらもtagsメソッドで書き換えてみてください〜

2020-08-10 02:51 UTC, sasabo-git commented
> コンフリクトがおきているので修正お願いします〜

大変失礼しました🙇‍♂️修正しました。

2020-08-10 02:54 UTC, sasabo-git commented on app/views/pages/_page_list_item.slim
> +    - if page.tag_list.present?
Tagが１つもないときはTagsを表示させないように変更してみましたがいかがでしょうか？

タグが１つもないとき
![スクリーンショット 2020-08-10 10 06 21](https://user-images.githubusercontent.com/60720255/89748788-fd55dd80-daff-11ea-9aff-7db5aa213c26.png)

タグがあるとき
![スクリーンショット 2020-08-10 10 53 43](https://user-images.githubusercontent.com/60720255/89748808-12327100-db00-11ea-90ad-f281f3e87c26.png)

2020-08-10 02:55 UTC, sasabo-git commented on app/views/pages/_page.slim
> +            = page.tag_list_links("</li><li class='thread-list-item-tags__item'>")
なるほどです。承知しました！今後はもっと良く書けないか調べるように心がけます！

2020-08-10 02:58 UTC, sasabo-git commented on app/views/pages/index.html.slim
> +                  = link_to tag, pages_tag_path(tag.to_s), class: "page-tags-nav__item-link"
ご指摘ありがとうございます。修正しました。
https://github.com/fjordllc/bootcamp/blob/906e2073778494eb280c35ccf9767d792b76dee8/app/views/pages/index.html.slim#L39

2020-08-10 03:02 UTC, sasabo-git commented on app/views/pages/show.html.slim
> +            = raw @page.tag_list.map { |t| link_to t, pages_tag_path(t) }.join(", ")
tagsメソッドを使って修正しました。
https://github.com/fjordllc/bootcamp/blob/906e2073778494eb280c35ccf9767d792b76dee8/app/views/pages/show.html.slim#L33-L39

2020-08-12 06:11 UTC, komagata commented on app/views/pages/_form.html.slim
> +        #js-tags-input(data-tags-initial-value="#{page.tag_list.join(",")}" data-tags-param-name="page[tag_list]")
これってgemの機能であるかも？なかったらDecoratorで実装したいです。（すごく自然に実装できると思います）

2020-08-12 06:12 UTC, komagata commented on app/views/pages/index.html.slim
> +              | Tags
カタカナのタグとTagsという表記が混在しているので統一したいです。

2020-08-12 06:12 UTC, komagata commented on test/system/pages_test.rb
> +    within "form[name=page]" do
👍

2020-08-12 14:39 UTC, mh-mobile commented on app/views/pages/_form.html.slim
> +        #js-tags-input(data-tags-initial-value="#{page.tag_list.join(",")}" data-tags-param-name="page[tag_list]")
この部分は、自分がタグUIのnpm導入で実装したコード(#js-tags-inputの部分)で、タグ補完機能のPRでもパラメータの変更が入っているので、自分の方でやりましょうか？

[https://github.com/fjordllc/bootcamp/pull/1756/files#diff-d339d526cd549e27f034facda617de57R21](https://github.com/fjordllc/bootcamp/pull/1756/files#diff-d339d526cd549e27f034facda617de57R21)

おそらく、PageモデルのDecoratorになると思いますが。

2020-08-12 23:41 UTC, sasabo-git commented on app/views/pages/_form.html.slim
> +        #js-tags-input(data-tags-initial-value="#{page.tag_list.join(",")}" data-tags-param-name="page[tag_list]")
@komagata さん
@mh-mobile さんのお言葉に甘えて、お願いしても良いでしょうか？

2020-08-13 00:43 UTC, sasabo-git commented on app/views/pages/index.html.slim
> +              | Tags
Tagsからタグ一覧に表記を変更しました。
https://github.com/fjordllc/bootcamp/blob/1f4d5e9d33235377fb6f5dfb649733e37e11e660/app/views/pages/index.html.slim#L32-L33

2020-08-18 08:19 UTC, komagata commented on app/views/pages/_form.html.slim
> +        #js-tags-input(data-tags-initial-value="#{page.tag_list.join(",")}" data-tags-param-name="page[tag_list]")
@sasabo-git はい、いいと思います。

@mh-mobile すみません、お願いいたします。ありがとうございます！

2020-08-18 08:34 UTC, machida commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
@komagata @sasabo-git 

今後、textarea内に特定のタグ一覧へのリンクを簡単に貼りたい、という要望が発生した際、「#xxxxx」と書くだけで、その文字が自動でリンクになる、という実装に決まったら、スペースがあるとその機能が実装できなくなる、ということが発生しそうな気がしました。ただ、その機能が必要になるかは今の時点では謎です。

ただ、タグにスペースが入ることを許すのはそこまでユーザーにメリットは無さそうなのと、上記のような便利機能を今後実装する可能性はあるので、「スペースは許さない」を取りたいです。

2020-08-18 12:31 UTC, mh-mobile commented on app/views/pages/_form.html.slim
> +        #js-tags-input(data-tags-initial-value="#{page.tag_list.join(",")}" data-tags-param-name="page[tag_list]")
@komagata 

こちら以下のPRで対応いたいsました。

[タグの補完機能の追加 #1756](https://github.com/fjordllc/bootcamp/pull/1756/commits/4f6f50f8c10780c9265a42b32d67048768581409)

2020-08-19 05:36 UTC, sasabo-git commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
メモ：8/19進捗ミーティングで「スペースは許さない」方向で進めることになった。

2020-08-28 07:10 UTC, sasabo-git commented on app/models/page.rb
> +    if tag_list.any? { |tag| tag =~ /\A(?=.*\s+|.*　+).*\z/ }
@komagata さん
concernモジュールを使ってタグのバリデーションをするように変更しました。確認をお願いします🙏

2020-08-30 08:45 UTC, komagata requested changes

2020-08-30 08:45 UTC, komagata commented on app/models/page.rb
> +  validate :tag_list_validation
concernにこう言うのも含めることができるはずです〜

2020-08-30 10:51 UTC, sasabo-git commented on app/models/page.rb
> +  validate :tag_list_validation
なるほどです！
修正しましたのでご確認をお願いします🙏

2020-08-30 11:28 UTC, komagata requested changes

2020-08-30 11:28 UTC, komagata commented on app/javascript/tags-input.vue
> +
すみません、これ別のPRのから入ってきたものかもですが、この空行いらないので修正いただければありがたいです。

2020-08-30 13:10 UTC, sasabo-git commented on app/javascript/tags-input.vue
> +
空行を削除しました〜

2020-08-30 18:10 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-08-30 18:11 UTC, merged