本名は管理者のみが見れるようにしたい
fjordllc/bootcamp pull request #1723
Opened 2020-07-17 06:52 UTC by tetishi

#1657

就職活動していることが会社にばれたくない人もいるため。

2020-07-17 08:40 UTC, tetishi commented
以下のように本名は管理者のみが見れるようにしました。

## 管理者以外のユーザー（本名は表示されません）
![kimuraのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87764903-15647500-c852-11ea-8bbc-ee7f6a230183.png)

![ユーザー一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87764988-3200ad00-c852-11ea-864f-a4fe65c604d9.png)

## 管理者（本名が表示されます）
![hajimeのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87765130-670cff80-c852-11ea-9908-03efdb8fbe22.png)

![ユーザー一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87765219-860b9180-c852-11ea-9a3c-3acd2c0d830f.png)

2020-07-17 08:47 UTC, tetishi commented
@komagata 
こちらのように参加登録フォームの本名を入力する欄に以下のように文言を追加しました。
大丈夫かどうか確認よろしくお願いいたします。
![フィヨルドブートキャンプ参加登録___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87767059-0af7aa80-c855-11ea-86fc-6a3fca06d637.png)

2020-07-17 08:57 UTC, komagata commented on app/views/reports/show.html.slim
> +            = link_to @report.user, class: "thread-header__author" do
代わりにlogin_nameを入れておきたいです〜

2020-07-17 09:03 UTC, JunichiIto commented
そもそも論になってしまいますが、本名は管理者（と本人？）だけしか見えてないことを画面上で視覚的にアピールしておかないと、管理者がうっかり本名で呼びかけたりすることがあるかもしれません。（コメント欄やオンラインイベント等で）

今のメンターはこの仕様変更を機に気を付けるかもしれませんが、あとから参加したメンターはそういうルールだと気づかないケースもあるでしょうし。

このあたりの議論はされていますか？

2020-07-17 09:05 UTC, tetishi commented on app/views/reports/show.html.slim
> +            = link_to @report.user, class: "thread-header__author" do
承知しました。

2020-07-17 09:50 UTC, tetishi commented
@JunichiIto 
@komagata 
> そもそも論になってしまいますが、本名は管理者（と本人？）だけしか見えてないことを画面上で視覚的にアピールしておかないと、管理者がうっかり本名で呼びかけたりすることがあるかもしれません。（コメント欄やオンラインイベント等で）

なるほど。確かにうっかり本名を呼びかけてしまう対策として、本名は管理者だけしか見えてないことを画面上で視覚的にアピールすることは重要ですね。

管理者で、ページにユーザーの本名が表示されている場合、本名の横に（就職活動していることが会社にばれたくない人のために本名は管理者のみ見ることが出来ます）と文言を追記してもよろしいでしょうか？

2020-07-17 10:29 UTC, JunichiIto commented
> 管理者で、ページにユーザーの本名が表示されている場合、本名の横に（就職活動していることが会社にばれたくない人のために本名は管理者のみ見ることが出来ます）と文言を追記してもよろしいでしょうか？

ちょっと説明文が長いかも。
本当はアイコン的なもので説明できたらいいんだけど、そんなアイコンもなさそうなので「メンターのみに表示」ぐらいかなー？

2020-07-17 11:15 UTC, tetishi commented
@JunichiIto 
@komagata 
> 本当はアイコン的なもので説明できたらいいんだけど、そんなアイコンもなさそうなので「メンターのみに表示」ぐらいかなー？

承知いたしました。
ユーザーが管理者の時、表示される本名の横に`（メンターのみに表示）`と追記しました。
以下のような感じで大丈夫でしょうか？
![kimuraのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87780533-e1954980-c869-11ea-88ed-a3fc5daf9a24.png)


![ユーザー一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87780493-cde9e300-c869-11ea-8478-ab8b81dd8353.png)

2020-07-17 11:21 UTC, yokki12 commented
Slackで見かけたので書き込みます！

私は就職活動のためにフィヨルドに参加しているわけではありませんが、正直言ってユーザー一覧ページに本名が出ていることには抵抗感を感じていました。これまでは比較的クローズドな感じだったので、まあ仕方ないかと思っていたのですが、最近ますます参加者が増えてきて、自分を知っている人、入ってこないで〜〜！！
と思っています笑

今後本名表示は管理者のみになるということであれば、特にこれ以上申し上げることはないですが、理由は人それぞれですということをお伝えしたかった次第です。

>フィヨルドブートキャンプの学習WebアプリのIssueもオープンソースのようにわいわい議論できたらいいなー、と思いました。

machidaさんがこうおっしゃっていたので、意見を述べてみました。
これはIssueじゃないよとか、状況を理解できてない発言だったら、すみません！

2020-07-17 11:50 UTC, tetishi commented
@yokki12 
コメントありがとうございます！

> 私は就職活動のためにフィヨルドに参加しているわけではありませんが、正直言ってユーザー一覧ページに本名が出ていることには抵抗感を感じていました。

そうだったんですね。@yokki12さんのように本名が出ていることに抵抗を感じている方の助けになると思うと、このIssueに取り組む意義をより一層実感することが出来ます！

2020-07-18 00:03 UTC, JunichiIto commented
すいません、これまた「こういう場合（ユースケース）はどうなんだろう？」と思ったことがあるんですが、たとえばフィヨルドでは毎月オンラインミートアップを開催しています。

ブートキャンプ上では "s4na" というユーザーIDで活動している人がいたとします。
この人が自己紹介で「こんにちは、○谷です。ユーザーIDは"s4na"です」と語ったとき、そこで初めて聞いた本名だと「○谷」という名前はすぐ忘れてしまいそうだなーと思いました。
あと、メンターだけなぜか「ちょっと、○谷さーん」という呼びかけたりすると、他の生徒の人たちは「○谷さんって誰？」ってなりそうです。

それにユーザーIDはおうおうにして読み方がわからないものが多いです。
"s4na"だと、僕の中では「えすふぉー、な」さんとしか読めません。
僕のユーザーIDである"jnchito"だって、普通の人は「ジェイエヌシーエイチアイティーオー」としか読めないでしょう。
（本当はJunichi Itoの省略形なのですが）

本名がわかっていれば、"s4na"の代わりに「○谷さん」、"jnchito"の代わりに「伊藤さん」と呼ぶことができます。

結局、何が言いたいのかというと、本名がバレたくない人がいれば、その人だけオプトアウトするのがベストではないか、ということです。
本名がバレても構わない人まで一律で隠してしまうと、上で挙げたように生徒間やメンター・生徒間のコミュニケーション効率が悪くなりそうな気がします。

というわけで、僕の提案としては、

- 本名の表示・非表示はユーザー自身が選択できるようにする
- 既存のユーザーはいったんデフォルトで「本名表示」にして、必要に応じて設定画面で変更してもらうよう、アナウンスする

というのはどうかなー、と思ったんですが、どうでしょう？（ちゃぶ台返しみたいな提案になってしまいますが💦）

2020-07-18 00:14 UTC, JunichiIto commented
あと、これはどこまでがんばるかは悩ましいところなのですが、ユーザー情報を返すAPIがあるので、そのAPIのレスポンスを見ると本名がバレる、という可能性があります。（現状ではusers API経由で本名が確認可能）

https://github.com/fjordllc/bootcamp/blob/master/config/routes.rb#L25

本名がバレないことがMUSTなのであれば、APIとそれを利用するコードの修正も必要になりそうです。

2020-07-18 08:48 UTC, machida commented
@tetishi @komagata 
このIssueはデザインを入れるので、終わったらmachidaに連絡お願いします。

@komagata

これは運用に大きく関わるので、

- リリース後の本名の取り扱いについてメンター全員と共有
- リリースの前にお知らせからBoot Camp関係者全員にアナウンス

をしてからのリリースをしたいと思います。なので、リリースのタイミングは慎重にお願いします🙏

2020-07-18 14:48 UTC, tetishi commented
@JunichiIto 

> 本名がバレても構わない人まで一律で隠してしまうと、上で挙げたように生徒間やメンター・生徒間のコミュニケーション効率が悪くなりそうな気がします。

確かにその通りですね！
以下の提案してくださった２つについて取り組んでいきます。

* 本名の表示・非表示はユーザー自身が選択できるようにする
* 既存のユーザーはいったんデフォルトで「本名表示」にして、必要に応じて設定画面で変更してもらうよう、アナウンスする

> あと、これはどこまでがんばるかは悩ましいところなのですが、ユーザー情報を返すAPIがあるので、そのAPIのレスポンスを見ると本名がバレる、という可能性があります。（現状ではusers API経由で本名が確認可能）

うーん、なるほど。悩ましいですね🤔

@komagata 
こちらAPIのレスポンスを見ると本名がバレることについて、今回のIssueで対処する必要はありますでしょうか？

2020-07-18 14:49 UTC, tetishi commented
@machida 
承知いたしました。
終わり次第、デザイン依頼いたします。

2020-07-19 05:01 UTC, tetishi commented
@komagata 
@JunichiIto 

本名の表示・非表示を選択できるチェックボックスを以下のようにフリガナ欄の下に追加しようと考えております。大丈夫でしょうか？
![登録情報変更___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/44915479/87867462-d9ebb700-c9c7-11ea-8d08-2aad7dde9d87.png)

2020-07-19 09:28 UTC, tetishi commented
@JunichiIto 
@komagata 

管理者側のページでは、ユーザーが本名を表示、非表示にしているに関わらず、全てのユーザーの本名が表示されます。なので管理者がどのユーザーが本名を非表示にしているかを知るために、本名非表示のユーザーの本名の横に（非表示）と追記する感じで良いでしょうか？

2020-07-19 14:40 UTC, komagata commented
@tetishi 

> 登録情報変更のページで本名の表示・非表示を選択できるチェックボックスを以下のようにフリガナ欄の下に追加しようと考えております。大丈夫でしょうか？

機能だけでなく、全ての議論が完了するまでリリースできないので一旦開発をストップしていただければと思います。

2020-07-19 14:44 UTC, komagata commented
難しいですね。

UIの問題だけでなく、根本的に本名を知っている人に対して本名で呼んでしまうことを防ぐというのは何か考えないと今のままでは防げないように思います。

スクールとしての方針に関わることだと思うんですが、今のところパッと思いつかないです。もう少し考えたいと思います。

2020-07-20 04:08 UTC, tetishi commented
@komagata 

承知いたしました。
一旦開発をストップいたします。

2020-07-29 08:33 UTC, machida commented
@komagata 

![image](https://user-images.githubusercontent.com/168265/88776143-8e53bd00-d1c0-11ea-8cc1-91c7c21290f4.png)

---

表示のルールはこのようにしたいと思います。

### 本名公開、ニックネーム無し

本名を表示する

### 本名公開、ニックネームあり

ニックネームだけを表示する

### 本名非公開、ニックネームあり

ニックネームだけを表示する

2020-07-30 01:45 UTC, JunichiIto commented
@machida "本名公開、ニックネームあり"のときは、「本名とニックネームを表示」にしないんですか？（今のUIと同じ）

2020-07-30 02:15 UTC, machida commented
@JunichiIto @komagata 

すいません🙇‍♂️ わかりにくかったので、再度整理しました。

---

## 基本的な表示

基本的にはニックネームを表示し、もしニックネームがない場合は本名を表示しようと思います。
（基本的な名前表示を「A」としました。）

## ユーザー個別ページの「名前」の項目

ユーザー個別ページに「名前」という項目を追加し、本名公開の場合はそこに本名が表示されるようにしたいと思います。
本名非公開の場合は、その項目の部分に「非公開」と表示したいと思います。
（ユーザー個別ページに追加する「名前」という項目を「B」としました。）
「B」はユーザーの個別ページでのみ表示します。

## hover時に表示されるユーザーの名前

ユーザーアイコンやユーザー個別ページへのリンクを hover にしたときに、ユーザーの名前が表示されるようになっているのですが、その表示のルールも「A」と同じにします。

---

<img width="522" alt="貼り付けた画像_2020_07_30_11_10" src="https://user-images.githubusercontent.com/168265/88872538-5b0f3d80-d255-11ea-940d-7a9d02727e89.png">


## A

- 本名公開、ニックネーム無し... 本名を表示する
- 本名公開、ニックネームあり... ニックネームを表示する
- 本名非公開、ニックネームあり... ニックネームを表示する

## B

- 本名公開、ニックネーム無し... 本名を表示する
- 本名公開、ニックネームあり... 本名を表示する
- 本名非公開、ニックネームあり... 「名前非公開」と表示する

2020-07-30 02:44 UTC, JunichiIto commented
@machida なるほど、よくわかりました。それならOKそうです〜。

2020-07-30 02:53 UTC, machida commented
@JunichiIto ご確認ありがとうございます🙏

2020-07-30 04:59 UTC, komagata commented
@machida @JunichiIto 現在は本名必須ないので大丈夫ですが、これの変更を入れて今後匿名OK（本名で呼んではいけない人がいる）となった場合はメンター（管理者含め）は間違って本名で少しでも呼んでしまったら問題になると思います。

今、毎週スクラムのミーティングをやって、毎月ミートアップをやっている身としての感覚から言うと、この進むと（システム or 制度上のなんらかの取り組みをしない場合）そういった場面で本名で呼んでしまうことが避けられないように思います。

例えばですが、本名NGな人は本名は入力しない（メンターがシステム上では知りようがない状態）にするのはいかがでしょうか。

2020-07-30 05:01 UTC, komagata commented
@machida @JunichiIto 現在は本名必須ないので大丈夫ですが、これの変更を入れて今後匿名OK（本名で呼んではいけない人がいる）となった場合はメンター（管理者含め）は間違って本名で少しでも呼んでしまったら問題になると思います。

今、毎週スクラムのミーティングをやって、毎月ミートアップをやっている身としての感覚から言うと、この進むと（システム or 制度上のなんらかの取り組みをしない場合）そういった場面で本名で呼んでしまうことが避けられないように思います。

例えばですが、本名NGな人は本名は入力しない（メンターがシステム上では知りようがない状態）にするのはいかがでしょうか。

2020-07-30 05:08 UTC, JunichiIto commented
本名入力、生徒さん本人が非公開を希望するなら僕はなしでも困らないですが、そもそも本名を入力してもらわないと困る場面って何かあるんでしょうか？
（もしくは今までに本名がわかって良かった、って思ったときとか）

必要になるとしたら生徒さんがブートキャンプ絡みで何か犯罪を犯して警察に連絡するときとかでしょうか・・・。

2020-07-30 05:31 UTC, komagata commented
@JunichiIto 就職活動の時（企業への紹介業務の時）ですね。

人によって違うよりは全員ニックネームのみにしちゃうと言うのもいいかもしれません。

2020-07-30 05:36 UTC, JunichiIto commented
> 就職活動の時（企業への紹介業務の時）ですね。

なるほどー。それはそのタイミングで聞けば問題なさそうですねえ。

> 人によって違うよりは全員ニックネームのみにしちゃうと言うのもいいかもしれません

たしかに、ニックネームをどうぞ。特になければ本名で、みたいな形の方がシンプルで良いかもしれませんね。
ただ、ニックネームは読み方がすぐわかるものにしてほしい・・・。

2020-07-30 05:39 UTC, machida commented
@komagata @JunichiIto 

> 必要になるとしたら生徒さんがブートキャンプ絡みで何か犯罪を犯して警察に連絡するときとかでしょうか・・・。

はい、そういったときと、クレジットカード関係で何かあったときのことに名前を知らないと何か起きた際に本人を追うことが困難になるのを回避することを想定していました。もう一点は就活の際に、ブートキャンプを受講した人と企業に紹介する人が同一人物である、ということの証明のためにも本名の登録は必要かと考えていました。

上記の仕様では、本名はUIから見ることは不可能なので間違えって本名を呼ぶことは不可能にしていますので、問題は起きないと思います。入力した本名を見るには、admin権限でユーザーの登録情報の編集画面に入らないと見ることはできません。

今までブートキャンプで考えると、本名を無しにしても問題は発生しないと思います。なので、本名は必須でなくていいかと思います。

2020-07-30 05:48 UTC, machida commented
@komagata @JunichiIto 

このようにしたいと思いますが、いかがでしょう？

![image](https://user-images.githubusercontent.com/168265/88885526-a7697600-d273-11ea-9c12-9c7722b4183c.png)

---

変更前

![image](https://user-images.githubusercontent.com/168265/88885577-bc460980-d273-11ea-9673-43902e70de79.png)

2020-07-30 05:55 UTC, JunichiIto commented
> クレジットカード関係で何かあったときのことに名前を知らないと何か起きた際に本人を追うことが困難になるのを回避する

これはたしかにありそうだなー、とも思いました。
が、頻繁に起こる話でもないでしょうし、金銭面のリスクと本名バレのリスクのどっちを取るか、という話かもしれませんね。

変更後のUI、（データ移行がうまくできるんかな？という疑問はあるけど）良いと思います〜！

2020-07-31 04:08 UTC, komagata commented
@machida 

> クレジットカード関係で何かあったとき

そっか、そういう観点で本名取ってたってありましたね。

思い出してみると、確か、インターンシップの頃は弊社のサービスの開発に参加するのと、オフィスの鍵を渡しているので何かトラブルがあった時に本人を確実に特定できるように本名を取ってたのがあったと思います。

オフィスに来ることもなくなった今、本名は全員なくてもいいかもですね〜

2020-08-10 14:14 UTC, machida commented
@komagata 


では、このこのパターンで行きたいと思います。

リリース時の作業

- データ移行として名前とふりがなが姓・名別れてるのをくっつける作業が発生
- 本名を入れなくていい、というお知らせ

![image](https://user-images.githubusercontent.com/168265/89792069-09bd5300-db5f-11ea-99fb-938efa673d9b.png)

2020-08-12 04:57 UTC, komagata commented
@machida このやり方賛成です。

2020-08-18 10:23 UTC, JunichiIto commented
メモ：
お知らせやDocsの新着通知がSlackに飛んできたときも本名が表示されてるっぽいので、ここも修正が必要になりそうです。

<img width="262" alt="Screen Shot 2020-08-18 at 19 21 44" src="https://user-images.githubusercontent.com/1148320/90502044-3ccb9c00-e188-11ea-8d84-38ae50fc261a.png">

2020-08-19 00:03 UTC, machida commented
リリースまでのやることリスト

- [ ] データ移行として名前とふりがなが姓・名別れてるのをくっつける作業が発生
- [ ] 本名を入れなくていい、というお知らせ
- [ ] お知らせやDocsの新着通知がSlackに飛んできたときも本名が表示されてるので修正

2020-09-07 07:35 UTC, komagata commented
@machida @gogutan 

こういうのはどうでしょうか？

- カラム名：`name`、日本語での表示：名前（ニックネームも可）
- カラム名：`name_kana`、日本語での表示：名前（カナ）

2020-09-12 19:16 UTC, gogutan commented
> @machida @gogutan
> 
> こういうのはどうでしょうか？
> 
> * カラム名：`name`、日本語での表示：名前（ニックネームも可）
> * カラム名：`name_kana`、日本語での表示：名前（カナ）
> 
> データ移行は
> 
> * 旧`last_name` + " " + `first_name`を`name`カラムに入れる。
> * 旧`kana_last_name` + " " + `kana_first_name`を`name_kana`カラムに入れる。

@komagata 
こちらの方針に沿ってデータ移行のためのPRを作成しました。また、PRのdescriptionを修正しました。
#1877と合わせてご確認をお願いします。🙇‍♂️

2020-09-13 01:18 UTC, komagata requested changes

2020-09-13 01:18 UTC, komagata commented on lib/tasks/temporary/concat_name.rake
> +namespace :concat_name do
`bootcamp:oneshot`というネームスペースで一時的なタスクを定義しているのでそちらを使っていただければ〜

2020-09-13 07:54 UTC, gogutan commented on lib/tasks/temporary/concat_name.rake
> +namespace :concat_name do
@komagata 
レビューありがとうございました！`bootcamp:oneshot`ネームスペースに移動しました。
このタスクは、マージ後に任意のタイミングで実行することを想定しています。
タスク実行の度に、全ユーザー分の`name`と`name_kana`に上書き保存します。
（タスク実行後に新規登録したユーザー、及び名前を変更したユーザーに対応するため）
ご確認をお願いします。🙇‍♂️

2020-09-14 02:46 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-23 09:10 UTC, bluerabbit commented on db/migrate/20200911102141_add_name_and_name_kana_to_users.rb
> +    add_column :users, :name_kana, :string, null: false, default: ""
複数カラムを追加する場合は`change_table`の`bulk: true`を使いましょう。1回のSQL文で複数カラム追加できます。

```ruby
    change_table : users, bulk: true do |t|
      t. string : name, null: false, default: ""
      t. string : name_kana, null: false, default: ""
    end
```

2020-09-23 16:33 UTC, gogutan commented on db/migrate/20200911102141_add_name_and_name_kana_to_users.rb
> +    add_column :users, :name_kana, :string, null: false, default: ""
ご指摘ありがとうございます！1つのALTER TABLE文にまとめられるんですね。
マイグレーションファイルを修正しました。

2020-09-24 07:17 UTC, merged