[Draft]Q&AのQをページ遷移なしで編集できるように変更
fjordllc/bootcamp pull request #1740
Opened 2020-07-28 04:15 UTC by sasabo-git

0728 ペアプロでコードを確認してもらうため暫定版をプッシュ

2020-08-01 10:32 UTC, sasabo-git commented
@machida さん　こちらデザインをお願いします。

2020-08-13 01:25 UTC, sasabo-git commented
@komagata さん
こちらデザイン前に一度レビューをお願いします。（8/12ミーティングでデザイン前にレビューしてOKなことをmachidaさんに確認済みです。）

2020-11-04 05:33 UTC, komagata commented
:memo: @komagata がリベースして整える。

2020-11-18 07:11 UTC, komagata commented
@machida リベースしました〜

2020-11-18 07:50 UTC, machida commented
@komagata ありがとうございます！

2020-11-26 07:13 UTC, machida commented
@komagata すいません、rebaseしていただいた後から Q&A が表示されなくなってしまいました。ご確認お願いします。

2020-11-26 08:12 UTC, komagata commented
@machida 了解です

2020-11-26 08:31 UTC, komagata commented
@machida ちょっとJSのコードの大部分が古い仕組みに依存した書き方になっているので僕の方で大幅に書き換えます。

2021-03-17 20:20 UTC, hituzi-no-sippo commented
## 進捗報告

一部問題がありますが、表示&編集はできるようになりました。

![genjo](https://user-images.githubusercontent.com/43565959/111532392-f5060500-87a8-11eb-98ed-5a3583add62e.gif)


### 発生している問題

#### プラクティス選択ができない

プラクティス選択で利用するAPIが複数category( 8dc38b8c )対応できておらず、引数エラーが発生します。一先ず、エラー部分を削除して、後から対応することにしました。

![select_practice](https://user-images.githubusercontent.com/43565959/111532439-0222f400-87a9-11eb-93f8-2747c1fb9cac.gif)

### 説明文を変更しないとプレビューが何も表示

`TextareaInitializer.initialize` が実行される際、説明文(テキストエリア)の値が空(`''`)だからです。
説明文はREST APIで、非同期で取得しており、取得前に `TextareaInitializer.initialize` が実行されます。
REST APIで説明文を取得するのではなく、 `props` 経由で渡せば、問題解決できると考えています。REST APIで説明文を取得後に `TextareaInitializer.initialize` を呼べるか試してみますが、30分やっても無理そうなら諦めます。

![preview](https://user-images.githubusercontent.com/43565959/111532939-90977580-87a9-11eb-88df-8a06737cd50b.gif)


### タグ編集がない

実装してないだけです。 `question_tags.vue` を利用します。

## 作業手順

<details><div>

1. `git pull --rebase origin main` してコンフリクトを解消
2. 表示されないことを確認
3. コンソールを見て、vue側でエラーが発生しているのを確認して、修正していく
markdownの機能を1つに統一した際()、変更された感じがします。
4. `app/views/questions/show.html.slim` にslim側が残っていたので削除

### "3. コンソールを見て、vue側でエラーが発生しているのを確認して、修正していく" の詳細

1. `const emoji = new TextareaAutocomplteEmoji()` と `const mention = new TextareaAutocomplteMention()` でエラーが発生していたので一時削除
  最終的にいらないことが判明しました。
2. `./markdown-textarea.vue` がない
  11月のrebase前であると思われるcommit(931375b127ad2fa685222df040b08f6bbe6846bc)では存在していました。"[画像drop時にtextareaをauto resizeするようにした](https://github.com/fjordllc/bootcamp/commit/ef35d0fc3ce2b90727bd7a712e9917d46033e4a0)"で削除されました。
3. textareaとmarkdownを修正
   "[markdownの機能を1つに統一した](https://github.com/fjordllc/bootcamp/commit/cf75c621dd9dd39bea9a2a3b7994d085fb626fcc)" を参考にしました。
4. REST APIエラー
   プラクティス取得のAPIで、複数コース対応ができていないのが原因でした。後でから対応するので一旦エラーを発生しないように修正しました。
5. 完了

</div>
</details>

2021-03-19 08:04 UTC, hituzi-no-sippo commented
## 進捗報告

昨日は少ししか進めませんでした。

### 実装内容

* watachボタンをjsから呼ばす、vueから直接呼ぶように変更
* プラクティスの表示位置を変更
  最新にあわせました
  ![0318](https://user-images.githubusercontent.com/43565959/111749133-b8372c80-88d4-11eb-94d0-2a54647a5466.png)
* 時刻表示を作成日から更新日へ変更
  time tag(`<time>`)も追加しました。
* Tag編集の追加
  初期値が非同期(REST API)で取得するため、エラーが発生する問題に苦戦していました。
  今は `props` 経由で渡せば実装できそうと考えています。

### 新しく発見した問題

* Admin or 作成ユーザーではないと表示されない
  REST APIが最新の仕様に対応しておらず、エラーが発生していました。

### 解決できていない問題一覧

数字は解決する順番です。

1. Tag編集の追加
  `props` 経由で初期値を渡せば実装できそうです。
1. プレビューの表示がおかしい
  `props` 経由で質問の説明の初期値を渡せば修正できそうです。
1. Admin or作成ユーザーではないと表示されない
  REST APIを最新の仕様に対応する。
1. プラクティスが選択できない
  REST APIを最新の仕様に対応する。

### 補足

上の問題が一通り終わったら、リファクタリングします。

データの取得まわり、特に初期(変更前の)値のデータの取得方法が気になっています。
初期値ですがview => Vueへprops経由で渡せるのに、REST APIで取得しているところがいくつかあります。`props` 経由で取得できるのに、REST APIで取得する必要があるのかと考えています。

## 作業中に発見したmainで発生するbug

質問ページのTag追加が正常に動作していません。
再現手順やバグの原因と推測されるコードは検討がついています。
この後、issueと記載します。

2021-03-19 12:32 UTC, hituzi-no-sippo commented
今日の進捗はありません。
用事があり作業する時間がとれませんでした。
明日は午前中から集中してできそうなので、結構進められると考えています。

2021-03-21 13:02 UTC, hituzi-no-sippo commented
一通り問題は解決して、実装も終わりました。
明日、最終確認してレビュー依頼する予定です 😄

2021-03-22 00:31 UTC, hituzi-no-sippo commented
issue
#1446 に対応

## 概要

Q&Aの詳細ページを画面遷移なしで編集できるようにする。

### Viewの変更部分のgif

#### 実装前

<details>

![before](https://user-images.githubusercontent.com/43565959/111926655-150f2e80-8af1-11eb-8a41-88cdb663755d.gif)

</details>

#### 実装後

<details open><summary>編集</summary>

![after](https://user-images.githubusercontent.com/43565959/111926638-045eb880-8af1-11eb-9a18-7c43fe457574.gif)

</details>

<details open><summary>削除</summary>

![delete](https://user-images.githubusercontent.com/43565959/111926661-193b4c00-8af1-11eb-80f4-a6ed171c7795.gif)

</details>

<details open><summary>ベストアンサー</summary>

![best_answer](https://user-images.githubusercontent.com/43565959/111926667-1f312d00-8af1-11eb-9b56-fc4b195e3bf9.gif)

</details>

<details open><summary>タグ編集</summary>

![tag_edit](https://user-images.githubusercontent.com/43565959/111926679-29532b80-8af1-11eb-8495-65c5b85dce1f.gif)

</details>

<details open><summary>emoji</summary>

![emoji](https://user-images.githubusercontent.com/43565959/111926683-2e17df80-8af1-11eb-8f1d-4cf466731aa7.gif)

</details>

<details open><summary>Raw</summary>

![raw](https://user-images.githubusercontent.com/43565959/111926694-353eed80-8af1-11eb-8dec-a34b0e2ed1f9.gif)


</details>


## 追加する理由

画面遷移なしだと便利だから

2021-03-22 00:44 UTC, hituzi-no-sippo commented on app/javascript/question_tags.vue
> +      return value.map(value => {
`question_tags.vue` が次のように `view => javascript(question_tags.js)` 経由ではなく、

```ruby
.thread__tags
  #js-question-tags(
    data-tags-initial-value="#{@question.tag_list.join(',')}"
    data-tags-param-name='question[tag_list]'
    data-question-id="#{@question.id}"
    data-question-user-id="#{@question.user_id}"
    data-current-user-id="#{current_user.id}"
    data-admin-login="#{current_user.mentor? || current_user.admin?}")
```

Vue(`question-detail.vue`)から直接呼び出しており `tagsInitialValue` が文字列から配列に変更されたので、 `split` はいらなくなりました。

`question_tags.vue` を呼んでいるコード

```javascript

.thread__tags
  tags(
    :tagsInitialValue="question.tag_list",
    :questionId="question.id",
    tagsParamName="question[tag_list]",
    :editAble="editAble"
  )
```

2021-03-22 00:51 UTC, hituzi-no-sippo commented on app/javascript/question.vue
> +  .container(v-if="question === null")
質問の詳細情報をREST APIで取得するまでcomponentは表示しません。
こうしないと、タグ編集やプレビュー表示に問題が発生します。

2021-03-22 00:52 UTC, hituzi-no-sippo commented on app/javascript/question.vue
> +      v-if="currentUser !== null",
`.container(v-if="question === null")` と同じです。

2021-03-22 00:55 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +        })
fetchしたデータを加工しているので `fetchPractices` という名前は完璧ではないと感じています。
10分程考えて、他にいい名前が思いつかなかったので `fetchPractices` のままにしました。
他にいい名前があったら教えてください。

2021-03-22 00:56 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                      .select-practices(v-if="practices === null")
プラクティス一覧をREST APIから取得するまで、プラクティス一覧を表示しません。

2021-03-22 00:58 UTC, hituzi-no-sippo commented on app/javascript/question_tags.vue
> +      return value.map(value => {
`question_tags.vue` が次のように `view => javascript(question_tags.js)` 経由ではなく、

```ruby
.thread__tags
  #js-question-tags(
    data-tags-initial-value="#{@question.tag_list.join(',')}"
    data-tags-param-name='question[tag_list]'
    data-question-id="#{@question.id}"
    data-question-user-id="#{@question.user_id}"
    data-current-user-id="#{current_user.id}"
    data-admin-login="#{current_user.mentor? || current_user.admin?}")
```

Vue(`question-detail.vue`)から直接呼び出しており `tagsInitialValue` が文字列から配列に変更されたので、 `split` はいらなくなりました。

`question_tags.vue` を呼んでいるコード

```javascript

.thread__tags
  tags(
    :tagsInitialValue="question.tag_list",
    :questionId="question.id",
    tagsParamName="question[tag_list]",
    :editAble="editAble"
  )
```

2021-03-22 01:07 UTC, hituzi-no-sippo commented
@gallardo16 
お手隙の際にレビューよろしくお願い致します 🙏

2021-03-25 10:53 UTC, gallardo16 reviewed
遅くなりました。申し訳ありません🙇‍♂️
何点かコメントさせていただきました。

あと全体的に以下の2点が気になりました。
- `methods`、`computed`プロパティにおいて、書き方が統一されていない
- 「更新」と「削除」の際、フラッシュメッセージの表示がない


ご確認よろしくお願いします🙏

2021-03-25 10:53 UTC, gallardo16 commented on app/javascript/question-detail.vue
> +                    | 内容修正
インデントがズレていると思います〜

2021-03-25 10:53 UTC, gallardo16 commented on app/javascript/question-detail.vue
> +                  | 削除
細かいですけど「削除する」です〜

デザイナーの担当になることですが、「削除ボタン」を目立たないものに出来るかなと思いました。(クラスを少し変えるだけでいけそうなので)

2021-03-25 10:53 UTC, gallardo16 commented on app/javascript/question-detail.vue
> +                            :value="practice.id"
`key`属性ではないですか？

2021-03-25 10:53 UTC, gallardo16 commented on app/javascript/question-detail.vue
> +                    v-bind:class="{ 'is-active': isActive('question') }",
`v-bind`をここと下のいくつか省略できると思いました。

2021-03-25 11:06 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                    v-bind:class="{ 'is-active': isActive('question') }",
> * `methods`、`computed`プロパティにおいて、書き方が統一されていない

これどの辺りでしょうか ❔ 
今いちピンとこないです。

他のコメントは後ほど返信します～ 😄

2021-03-25 11:07 UTC, hituzi-no-sippo commented
> 遅くなりました。申し訳ありません🙇‍♂️
> 何点かコメントさせていただきました。
> 
> あと全体的に以下の2点が気になりました。
> 
> * `methods`、`computed`プロパティにおいて、書き方が統一されていない
> * 「更新」と「削除」の際、フラッシュメッセージの表示がない
> 
> ご確認よろしくお願いします🙏

レビューありがとうございます～ 😄 

> * `methods`、`computed`プロパティにおいて、書き方が統一されていない
これどの辺りでしょうか ❔ ちょっとピンとこないです。

他のコメントは後ほど返信します～ 😃

2021-03-25 11:45 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                            :value="practice.id"
`:value` の値が `edited.practiceId` の値になるので必要ですね。
ただ、`key` 属性は追加し忘れなので追加しておきます～ 😄 

参考資料
[フォーム入力バインディング — Vue\.js](https://jp.vuejs.org/v2/guide/forms.html#%E9%81%B8%E6%8A%9E)

2021-03-25 11:46 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                  | 削除
1番最初の8月のデザインのままになっていました。
指摘ありがとうございます。
修正します 😄

2021-03-25 13:35 UTC, gallardo16 commented
>methods、computedプロパティにおいて、書き方が統一されていない
これどの辺りでしょうか ❔ ちょっとピンとこないです。

ごめんなさい、あらためて読んでみたら完全に言葉たらずでした。
methods、computedプロパティ内で`function`を含めた書き方と、そうで無いものがあり、何か意図があるのかなと気になりました。(例えば以下の2つで異なる)

[question-detail.vue/R176](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR176)

[question-detail.vue/R215](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR215)
```
 fetchPractices(userId) {...

 isActive: function (tab) {...
```

2021-03-25 19:42 UTC, hituzi-no-sippo commented
> > methods、computedプロパティにおいて、書き方が統一されていない
> > これどの辺りでしょうか ❔ ちょっとピンとこないです。
> 
> ごめんなさい、あらためて読んでみたら完全に言葉たらずでした。
> methods、computedプロパティ内で`function`を含めた書き方と、そうで無いものがあり、何か意図があるのかなと気になりました。(例えば以下の2つで異なる)
> 
> [question-detail.vue/R176](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR176)
> 
> [question-detail.vue/R215](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR215)
> 
> ```
>  fetchPractices(userId) {...
> 
>  isActive: function (tab) {...
> ```

説明ありがとうございます。自分でも気づきませんでした。特に理由ないので統一します～ 😄 

> [question-detail.vue/R176](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR176)
> 
> [question-detail.vue/R215](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR215)

GitHubにはpermalinkという機能があり、これを利用すれば、コードが表示されるリンクを作成できるので便利です。

例

https://github.com/fjordllc/bootcamp/blob/2fe998de6186d872e262e02a2c50aeb0bf2d8686/app/javascript/question-detail.vue#L176

[コードスニペットへのパーマリンクを作成する \- GitHub Docs](https://docs.github.com/ja/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet)

2021-03-26 00:47 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                    v-bind:class="{ 'is-active': isActive('question') }",
71b2979 で削除しました～

2021-03-26 00:48 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                            :value="practice.id"
00587cb で追加しました～ 😄

2021-03-26 00:51 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                  | 削除
808aade で最新版の表示に変更しました。

2021-03-26 00:51 UTC, hituzi-no-sippo commented on app/javascript/question-detail.vue
> +                    | 内容修正
8fb0274 で修正しました～ 😄

2021-03-26 01:23 UTC, hituzi-no-sippo commented
> > methods、computedプロパティにおいて、書き方が統一されていない
> > これどの辺りでしょうか ❔ ちょっとピンとこないです。
> 
> ごめんなさい、あらためて読んでみたら完全に言葉たらずでした。
> methods、computedプロパティ内で`function`を含めた書き方と、そうで無いものがあり、何か意図があるのかなと気になりました。(例えば以下の2つで異なる)
> 
> [question-detail.vue/R176](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR176)
> 
> [question-detail.vue/R215](https://github.com/fjordllc/bootcamp/pull/1740/files#diff-5eac1424930b2396cc0d588cc4abc1a49094fc992129b48ae4677d3169592e4aR215)
> 
> ```
>  fetchPractices(userId) {...
> 
>  isActive: function (tab) {...
> ```

ba35ef0 で修正しました～

2021-03-26 01:39 UTC, hituzi-no-sippo commented
> 「更新」と「削除」の際、フラッシュメッセージの表示がない
 
## 更新

54c407b で更新ボタンの下にメッセージを表示するようにしました。

![changed](https://user-images.githubusercontent.com/43565959/112564283-561f7f80-8e1e-11eb-84fc-0ed723ac4a74.gif)


dddf166 で編集前と後の値が、同じ場合REST APIを実行しないようにしました。REST APIを実行しないときも更新メッセージは表示します。表示しないと利用者が更新されたか不安になるからです。

![has_not_changed](https://user-images.githubusercontent.com/43565959/112564297-5cadf700-8e1e-11eb-90c8-64a114b08dea.gif)

## 削除

 79b69ec で削除のメッセージを表示しました。

質問削除のREST APIを利用していましたが、利用しないようにしました。削除は必ず画面遷移が発生しているので、REST APIを利用する必要がないからです。REST APIを利用せず、現在のリリースバージョンと同様 `/questions/${question.id}` へのリンクを利用しています。

https://github.com/fjordllc/bootcamp/blob/d1c7fa08f75551e597655ac7fe16483cb8ac62fa/app/javascript/question-edit.vue#L62-L71

![delete](https://user-images.githubusercontent.com/43565959/112564647-fe354880-8e1e-11eb-974b-565420e32a72.gif)

質問削除のREST APIはここでしか、利用してなかったので削除しました。

2021-03-26 04:34 UTC, hituzi-no-sippo commented
* プラクティス一覧取得( 3f2b5f1 )
* 質問の詳細取得( 4957b27 )
* 質問の編集(33f2b18)

のREST APIのテストを追加しました。
これで、再びレビューお願いしま～す 😄

2021-03-29 08:15 UTC, gallardo16 approved these changes
修正確認しました。OKだと思います🙆‍♂️

>GitHubにはpermalinkという機能があり、これを利用すれば、コードが表示されるリンクを作成できるので便利です。

これ便利ですね！情報ありがとうございます🙇‍♂️

2021-03-29 09:22 UTC, hituzi-no-sippo commented
@gallardo16 
レビューありがとうございます 😄 

@komagata 
コンフリクトに気付かず、レビューリクエストしてしまいました 🙇 
コンフリクト解消したら、またコメントします。
明日の夜までには解消できる予定です。

2021-03-30 12:19 UTC, hituzi-no-sippo commented on app/javascript/question-edit.vue
> +      })
```javascript
      return Object.entries(this.edited).some(([key, val]) => {
        val = this[key]
      })
```
にすると、 `this.edited` に `val` の値は格納されないので、  `this.edited[key] = this[key]` にしています。

2021-03-30 12:21 UTC, hituzi-no-sippo commented on app/javascript/question-edit.vue
> +        description: this.question.description,
`description: this.question.description` にしないと、説明文のプレビューが、説明文を変更しないと正しく表示されない問題が発生します。

2021-03-30 12:24 UTC, hituzi-no-sippo commented on app/javascript/answers.vue
> +          this.$emit('solveQuestion', answer)
`makeToBestAnswer` と `solveQuestion` で名前が違う理由は、視点の違いです。
`makeToBestAnswer` は回答側、 `solveQuestion` は質問側から見た動作です。

2021-03-30 12:30 UTC, hituzi-no-sippo commented
@gallardo16 
コードが結構変更されたので、 @komagata さんにレビューしてもらう前に、もう1回レビューしていただけないでしょうか 🙇 



新たに追加されたコミットは 7bd0070 ~ 9c5a3e5 までです。
次の4つのVueファイルしか変更されていません。

* `question.vue`
* `question-edit.vue`
* `answers.vue`
* `answer.vue`


やったことは大きく合せて次の4つです。

## `question-edit.vue` で `props` のobjectの参照元を変更していたので、変更しないように修正

objectのpropsの値の参照元を変更していたいので、変更しないように 541e1aa で修正しました。

今までは次のようにしていました。

```javascript
  props: {
    initialQuestion: { type: Object, required: true },
    currentUser: { type: Object, required: true },
  },
  // 関係ない行なので省略
  this.question = this.initialQuestion
  // 関係ない行なので省略
  // updateQuestionの一部分
  ['title', 'description'].forEach(key => {
    this.question[key] = this.edited[key]
  })
```

これだと、 `this.question[key] = this.edited[key]` で `initialQuestion` 内の参照元の値を変更してしまいます。

## 回答数を表示

2282fee で質問のタイトルの横に回答数を表示するようにしました。コメントの作成・削除で自動的に数は変更されます。

<details open><summary>コメント追加</summary>

![comment_count](https://user-images.githubusercontent.com/43565959/112986351-59a76380-919c-11eb-9b55-d7c7640576de.gif)

</details>

<details open><summary>コメント削除</summary>

![delete_comment](https://user-images.githubusercontent.com/43565959/112986369-5e6c1780-919c-11eb-827e-f81c9855e11c.gif)

</details>


## 問題の解決状態を動的に変更

ベストアンサーを決めたり、取り消したら、自動で解決 or 未解決に変更されるように d600716 で実装しました。

<details open><summary>ベストアンサー</summary>

![best_answer](https://user-images.githubusercontent.com/43565959/112986484-83f92100-919c-11eb-9d5b-243217d1d4bb.gif)


</details>

<details open><summary>ベストアンサー削除</summary>

![delete_best_answer](https://user-images.githubusercontent.com/43565959/112986547-97a48780-919c-11eb-8abf-324d3e1749e5.gif)

</details>


## 編集のボタンの色を最新版に更新

3be64ea で変更しました。

<details open><summary>画像<summary>

![button](https://user-images.githubusercontent.com/43565959/112986638-b60a8300-919c-11eb-925b-6d9098ced180.png)

</details>

2021-04-01 04:45 UTC, machida commented
@komagata @gallardo16
デザイン入れましたー
レビューが通ったらマージでお願いします

2021-04-01 07:38 UTC, gallardo16 approved these changes
変更確認いたしました。OKだと思います🙇‍♂️

2021-04-02 10:35 UTC, hituzi-no-sippo commented
@gallardo16
レビューありがとうございます。

@komagata 
レビューお願いします 🙏

2021-04-03 16:38 UTC, komagata requested changes
conflictの解消お願いします。

2021-04-04 00:31 UTC, hituzi-no-sippo commented
@komagata 
conflict解消しました～ 😄

2021-04-07 04:57 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-07 04:58 UTC, komagata commented
@machida お手隙の時にデザインをお願いします〜

2021-04-07 06:03 UTC, hituzi-no-sippo commented
@komagata 
レビューありがとうございます 😄 

@machida 
"[ページ遷移無しの質問編集にデザイン by machida · Pull Request \#2531 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/2531)"をマージ後に変更したデザイン部分は "回答数表示の更新(38cbf66)"のみという認識です。
"[質問回答数の表示を変更 by machida · Pull Request \#2535 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/2535/files)"を見ながら自分で更新しました。

---

上にあるgifが全てデザイン適用前だったので、デザイン適用後の最新版のgifを貼っておきます。

<details open><summary>更新</summary>

![update](https://user-images.githubusercontent.com/43565959/113817837-ec09c180-97b1-11eb-9fdb-538cb387ee89.gif)

</details>

<details open><summary>markdownを利用した質問</summary>

![markdown](https://user-images.githubusercontent.com/43565959/113817894-004dbe80-97b2-11eb-9858-faa02b3bbf9a.gif)

</details>

<details open><summary>回答まわり</summary>

![answer](https://user-images.githubusercontent.com/43565959/113817944-0cd21700-97b2-11eb-98d2-05c388054f23.gif)


</details>

2021-04-07 08:23 UTC, machida commented
@hituzi-no-sippo 説明とデザインの反映ありがとうございます！！

@komagata こちらデザイン完了していますー

2021-04-07 11:31 UTC, komagata commented
@hituzi-no-sippo 新しい画像ありがとうございます！

@machida ありがとうございます！

ではマージします〜

2021-04-07 11:31 UTC, merged