学習時間平均をDB保存
fjordllc/bootcamp pull request #1741
Opened 2020-07-28 12:50 UTC by sdk-quadra

2020-07-29 00:12 UTC, bluerabbit commented on app/views/practices/_practice.html.slim
> +      - learning_minute_statistic = LearningMinuteStatistic.find_by(practice_id: practice.id)
`LearningMinuteStatistic.find_by(practice_id: practice.id)`しなくても`practice.learning_minute_statistic`で取れませんか？

2020-07-29 06:52 UTC, komagata commented
今の進め方で問題ありませんが、基本的に「平均時間からプラクティスの目安完了時間を出すのは現実的か？」を知るためという目的なので、持続性のないやり方でも構いません。（一回わかればOK）

2020-07-29 09:25 UTC, sdk-quadra commented on app/views/practices/_practice.html.slim
> +      - learning_minute_statistic = LearningMinuteStatistic.find_by(practice_id: practice.id)
ほんまですね😅わざわざややこしい書き方してました。
ありがとうございます。

2020-08-05 01:27 UTC, sdk-quadra commented
完了しましたので、reviewをお願いできますでしょうか？
@komagata

2020-08-05 03:14 UTC, komagata commented on lib/tasks/learning_minute.rake
> +namespace :learning_minute do
railsや他のツールのtaskと混ざらないようにbootcampのnamespaceのしたに書きたいです。

https://github.com/fjordllc/bootcamp/blob/master/lib/tasks/bootcamp.rake

2020-08-05 03:15 UTC, komagata commented on lib/tasks/learning_minute.rake
> +  def practice_learning_minute_per_user(practice)
基本的には`xxx.task`ファイルにはtaskだけを書いて、メソッドはmodelなどに整理して書きたいです。

2020-08-06 07:14 UTC, sdk-quadra commented on lib/tasks/learning_minute.rake
> +namespace :learning_minute do
なるほど、こちらに入れました。

2020-08-06 07:16 UTC, sdk-quadra commented on lib/tasks/learning_minute.rake
> +  def practice_learning_minute_per_user(practice)
確かにそうですね、modelに移行しました。
@komagata

2020-08-09 05:33 UTC, komagata commented on app/models/practice.rb
> +  def find_or_initialize(practice_id, average, median)
`find_or_initialize`って確か元々あるのでoverrideする形になっちゃうと他の人に対する罠っぽくなっちゃうかもです。

別の似てない名前にした方が良さそうです。

2020-08-24 03:56 UTC, sdk-quadra commented on app/models/practice.rb
> +  def find_or_initialize(practice_id, average, median)
そうですね、`save_statistic`にしてみました。
@komagata

2020-08-24 06:01 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-08-24 06:02 UTC, komagata requested changes
CIが落ちてるようです。

2020-08-25 05:28 UTC, sdk-quadra commented
* CIのエラー"Some checks were not successful"で色々調べたんですが、対策のほとんどがPR出し直す、squashするでしたので`squash`して`push --force-with-lease`しました。

@komagata

2020-08-25 13:53 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

CIが落ちてる時の対応方法は、リンクからCIサービス（CircleCI）のページに行ってリビルドするって感じです。

2020-08-25 13:53 UTC, merged

2020-08-25 22:27 UTC, sdk-quadra commented
* それはcircleCI上の"Rerun"の事でしょうか？

![89465775-a07bbf80-d7ad-11ea-837c-5b263aa6048c](https://user-images.githubusercontent.com/39234092/91233248-bf95bd80-e76b-11ea-8c02-358d2acdafad.png)

* まず最初に"Rerun Workflow from Failed" を2回しました。
    * 上の行の赤い「x」はそのままで変わりませんでした。
* 同じように一応"Rerun Workflow from Start"と"Rerun Job with SSH"も2回ずつしました。
    * 上の行の赤い「x」はそのままで変わりませんでした。
<img width="600" alt="20191011090215" src="https://user-images.githubusercontent.com/39234092/91233465-38951500-e76c-11ea-8728-ce9ec2b3472a.png">

(※画像はネット上から拝借)

@komagata

2020-08-26 04:07 UTC, komagata commented
> それはcircleCI上の"Rerun"の事でしょうか？

はいそうです。
タイミングによって失敗するテストもあるのです。

2020-08-26 10:51 UTC, sdk-quadra commented
そうだったんですね..

CIの「Some checks were not successful」の解決策を探したんですがほとんど見つからなくてかなり時間を掛けてしまいました。

最終的に以下のリンクで見つけたsquashをした感じです。
https://gitter.im/boostorg/hana/archives/2015/12/10?at=566a03517eae7fe80e604ee5

6回連続で落ちる事もあると分かりました。

@komagata

2020-08-26 11:39 UTC, komagata commented
上記はTravisCIに関するチャット（gitter）の記述のようですね。

下記を参考にするのが良いかもです。

[まさかPushデバッグしてないよね？ よく使うCircleCIのデバッグ方法 \- VTRyo Blog](https://blog.vtryo.me/entry/circleci-debug-method)