コメントと同時に確認済みにするボタンを用意する
fjordllc/bootcamp pull request #1752
Opened 2020-08-05 03:37 UTC by sdk-quadra

2020-08-09 00:27 UTC, sdk-quadra commented
reviewをお願い致します。
@komagata

2020-08-09 08:11 UTC, komagata commented on app/javascript/comments.vue
> +      admin_login: ''
booleanが良さそうです。

2020-08-09 08:16 UTC, komagata commented on app/views/products/show.html.slim
> +        #js-admin-login
管理者としてログインしているかの情報が必要であればcommentコンポーネントに直接渡すか、html headerの中にグローバルでJSで記述して取得するのかどちらかにしたいです。

このやり方ですといろんなんところにこういう記述を散りばめる必要が出てきてしまいそうです。

2020-08-25 14:00 UTC, komagata requested changes

2020-08-26 01:45 UTC, sdk-quadra commented on app/javascript/comments.vue
> +    comment_and_check() {
これよくやってしまいます。
修正しました!

@komagata

2020-08-26 03:17 UTC, komagata requested changes

2020-08-26 03:17 UTC, komagata commented on test/system/api/check/reports_test.rb
> +    assert_text "確認済"
これだと確認の部分だけでコメントされたことはテストできていないように思います。

2020-08-26 06:52 UTC, sdk-quadra commented on test/system/api/check/reports_test.rb
> +    assert_text "確認済"
comment and checkと銘打っているなのでそうすべきでしたね。

`assert_text "日報でcomment+確認OKにするtest"`

を追記してみました。

@komagata

2020-08-26 11:37 UTC, komagata commented on test/system/api/check/reports_test.rb
> +    assert_text "確認済"
assert_textにはXHRリクエストを待つような処理が確かなかったと思うので、コメントが投稿される前に確認が走って、タイミングによってテストが通ったり・通らなかったりするようになってないか少し心配になりました。

その辺りを調べてみていただけるとありがたいです。

2020-08-31 08:51 UTC, sdk-quadra commented on test/system/api/check/reports_test.rb
> +    assert_text "確認済"
> assert_textにはXHRリクエストを待つような処理が確かなかったと思うので、コメントが投稿される前に確認が走って、タイミングによってテストが通ったり・通らなかったりするようになってないか少し心配になりました。

調べたんですが、capybaraのドキュメントで見つけられなかったので、
https://github.com/teamcapybara/capybara/blob/master/README.md#asynchronous-javascript-ajax-and-friends

`until`と`settimeout`を使ったやり方でやってみました。

あと、[/app/javascript/comments.vue](https://github.com/fjordllc/bootcamp/blob/431984be95afc63907017e684f98728bc218e82e/app/javascript/comments.vue#L15)の15行目の
`:class="[roleClass, daimyoClass]"`の出力が`is-undefined`になっていたので

[/app/views/application/_current_user.html.erb](https://github.com/fjordllc/bootcamp/pull/1752/files#diff-9b3c10412b885fd4ff616287800c70feL2)
の `:role`の部分を書き換えたんですが、合ってますでしょうか？
	
（自分の今回のissueにも関係ある為書き換えました）

@komagata

2020-08-31 18:14 UTC, komagata requested changes

2020-08-31 18:14 UTC, komagata commented on test/application_system_test_case.rb
> +  def wait_for_ajax(text)
古い記事だとこういうのがたくさん出てきちゃうんですが、Capybaraの主要なメソッドにはこういう機能が備わっているのでこういうハックはなるべく使わないようにしたいです。

下記の発表はその辺りのことが載っているので参考になると思います。

[ちょうどよい Rails E2E テスト/enough\-good\-rails\-e2e\-test \- Speaker Deck](https://speakerdeck.com/moro/enough-good-rails-e2e-test)

2020-08-31 18:15 UTC, komagata commented on test/system/api/check/reports_test.rb
> +    assert_text "確認済"
assert_textではなくて、findとかclick_buttonとかそういうメソッドはXHRリクエストを待つ機能が備わってるはずです。
もう少し調べてみてください〜

2020-09-03 02:56 UTC, sdk-quadra commented on test/system/api/check/reports_test.rb
> +    assert_text "確認済"
すみません、以前の発言に間違いがありました。

> 調べたんですが、capybaraのドキュメントで見つけられなかったので、

これですが、`assert_text`はdefaultで2秒待つという記述がありました。
https://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FNode%2FMatchers:assert_text

なので以前の記述に戻したんですが、この認識で合っていますでしょうか？

@komagata

2020-09-03 02:57 UTC, sdk-quadra commented on test/application_system_test_case.rb
> +  def wait_for_ajax(text)
ありがとうございます。拝見します。

2020-09-03 05:08 UTC, komagata reviewed
確認しました、OKですー🙆‍♂️

2020-09-03 05:08 UTC, komagata commented on test/system/api/check/reports_test.rb
> +    assert_text "確認済"
assert_textも待ってくれるんですね、でしたら問題ございません。

2020-09-03 05:08 UTC, komagata approved these changes

2020-09-03 05:08 UTC, merged