practiceに所要時間の項目が欲しい
fjordllc/bootcamp pull request #1854
Opened 2020-09-01 09:49 UTC by sdk-quadra

2020-09-03 08:35 UTC, machida commented
@sdk-quadra すいません、これって開発環境で数字を出すのって何かコマンド打つんでしたっけ？

2020-09-03 08:52 UTC, sdk-quadra commented
> @sdk-quadra すいません、これって開発環境で数字を出すのって何かコマンド打つんでしたっけ？

* 学習時間記入した日報を適当に投稿して、
* `$ rake bootcamp:statistics:save_learning_minute_statistics`すると
* DB `learning_minute_statistics` に数字が入ります!

@machida

2020-09-04 07:20 UTC, machida commented
@sdk-quadra ありがとうございます！了解ですー
READMEに書いておきますー

2020-09-07 08:54 UTC, sdk-quadra commented
> @sdk-quadra ありがとうございます！了解ですー
> READMEに書いておきますー

ありがとうございます！

@machida

2020-09-08 06:34 UTC, komagata requested changes

2020-09-08 06:34 UTC, komagata commented on app/views/practices/show.html.slim
> +              ' 所要時間: #{convert_to_ceiled_hour(learning_minute_statistic.median)}
```suggestion
              | 所要時間: #{convert_to_ceiled_hour(learning_minute_statistic.median)}
```

2020-09-08 06:34 UTC, komagata commented on app/views/practices/show.html.slim
> +                ' (過去に完了した人の中央値を表示しています)
```suggestion
                | (過去に完了した人の中央値を表示しています)
```

2020-09-10 10:52 UTC, sdk-quadra commented
* 1ページ内で複数のmodalを設置すると予想してjsを書きました
* 学習時間中央値がseedで入るようにfixturesを書きました
* 町田さんが↑で

> READMEに書いておきますー

とおっしゃってくれたんですが、
rails db:seedした時に動くように
`Rake::Task["bootcamp:statistics:save_learning_minute_statistics"].execute`
を書いたんですが、これはやっていいでしょうか？

@komagata

2020-09-10 10:54 UTC, sdk-quadra commented on app/views/practices/show.html.slim
> +                ' (過去に完了した人の中央値を表示しています)
スペースを入れるならcssでという事ですね、了解です!

2020-09-12 09:05 UTC, komagata commented
> rails db:seedした時に動くように
Rake::Task["bootcamp:statistics:save_learning_minute_statistics"].execute
を書いたんですが、これはいいでしょうか？

ありがとうございます。

2020-09-12 09:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-12 09:07 UTC, komagata commented
@sdk-quadra (CC: @machida) こちらはデザインは完了してる状態でしょうか

2020-09-16 01:59 UTC, sdk-quadra commented
> @sdk-quadra (CC: @machida) こちらはデザインは完了してる状態でしょうか

一旦マージして、後ほどmachidaさんがデザインを入れて下さる、という認識で合ってますでしょうか？
@machida

2020-09-16 02:15 UTC, machida commented
@sdk-quadra はい！一旦マージお願いしますー

2020-09-16 02:16 UTC, machida commented
後ほど、集計についてのもう少し詳しい文章を追加した上で整えたいと思います。

2020-09-16 03:13 UTC, merged