イベント一覧に参加者、補欠者の数字を表示
fjordllc/bootcamp pull request #1864
Opened 2020-09-03 12:55 UTC by gogutan

ref #1769

<img width="671" alt="イベント___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/92116921-6db9fb00-ee2f-11ea-96c3-f6402f616d5a.png">

- commentsと同様にusersを`preload`しました。

- 参加者数、補欠者数ともに条件によって異なるため、Eventモデルに`#participants_count`と`#waitlist_count`を追加しました。なお追加したメソッド内では`users.size`を用いて、usersがロード済の場合にSQL文を発行しないようにしました。
参考：https://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-size

- 暫定的にコメント用のCSSを適用しました。

以上、ご確認お願いします。🙏

2020-09-03 15:54 UTC, komagata requested changes

2020-09-03 15:54 UTC, komagata commented on app/controllers/events_controller.rb
> +                   .preload(:comments, :users)
細かく制御するんだったらいいですが、基本的には`includes`の方がいいかもです。（`where`の条件に必要な場合は`eager_load`して、不要であればpreloadしてくれる）

[ActiveRecordのjoinsとpreloadとincludesとeager\_loadの違い \- Qiita](https://qiita.com/k0kubun/items/80c5a5494f53bb88dc58)

2020-09-04 08:09 UTC, gogutan commented on app/controllers/events_controller.rb
>    end
@komagata 
レビューありがとうございました！
`includes`に置き換えて動作確認しました。
もう1度ご確認お願いします。🙏

2020-09-05 04:11 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-05 04:11 UTC, merged