企業の個別ページ（会社情報・ユーザー・日報・提出物）を作成
fjordllc/bootcamp pull request #1869
Opened 2020-09-07 03:18 UTC by gogutan

### ユーザープロフィール

<img width="473" alt="komagataのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/92344372-4306c580-f101-11ea-9e18-a34865afebe6.png">

### 会社情報(`/companies/123`)

<img width="1135" alt="FJORD__LLCの会社情報___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/92344521-a3960280-f101-11ea-9e9e-e5e45b417b99.png">

### ユーザー(`/companies/123/users`)

<img width="1131" alt="FJORD__LLC所属ユーザー___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/92344539-b3154b80-f101-11ea-93fb-20c6f2ec764a.png">

### 日報(`/companies/123/reports`)

<img width="1134" alt="FJORD__LLC所属ユーザーの日報___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/92344627-ece65200-f101-11ea-8a3e-91e109e8cb7f.png">

### 提出物(`/companies/123/products`)

<img width="1133" alt="FJORD__LLC所属ユーザーの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/50437473/92344631-f079d900-f101-11ea-90f5-01918009ec36.png">

- **企業の方が、企業所属ユーザーの動向を確認する**ために上記のページを作成しました。企業一覧を表示する`/companies`ページは、このPRでは作成していません。（`/companies`を作るとしたら、`/admin/companies`をベースに少し修正する必要があるかな？と考えています）

- 会社情報ページのCSSは未作成です。（@machidaさん、後ほど相談させてください🙏）

以上、ご確認お願いします。🙇‍♂️

2020-09-08 06:32 UTC, komagata requested changes

2020-09-08 06:32 UTC, komagata commented on app/controllers/companies/products_controller.rb
> +    end
もし1つしか表示するページがないのであったらbefore_actionを使う方式でない方が分かりやすいかもです。

例えば、なるべく重い処理はしたくないので持ってくるデータは少なくしたいのですが、before_actionだと見逃し易く分かりづらくなっちゃうかもです。

2020-09-08 17:54 UTC, gogutan commented on app/controllers/companies/products_controller.rb
>    end
@komagata
レビューありがとうございました🙇‍♂️
今回はページが1つしか存在しないので、処理を全てindexメソッド内に記述しました。（だいぶコードが短くなりました）
他のコントローラーも同様です、もう1度ご確認お願いします。🙏

2020-09-09 01:35 UTC, komagata commented on app/controllers/companies/products_controller.rb
>    end
OKです〜！

これ話すと長くなるんですが、railsのscaffoldが生成するset_xxxのコード自体良くないのではないかという意見（を持った派閥）があります。

```ruby
before_action :set_foo

def show
end

def set_foo
  @foo = Foo.find(params[:id])
end
```

ではなくて

```ruby
def show
  @foo = find_foo
end

def find_foo
  Foo.find(params[:id])
end
```

こちらの方が良いのではないかという意見です。

前者は`set_foo`に副作用がある点とbefore_actionという複数のactionが在った場合に実行順番に依存する処理がある点がプログラミングの原則として良くない点です。

before_actionのように差し込まれる処理というのはメインのメソッドで主としてやりたいこと意外にすべきで、`FoosController`の`show`だったら`@foo`の設定というのは主としてやりたいことだからです。

僕も後者の方が良いと思っていて、そういうPRがRailsに作られたこともありますがDHHに却下されたようです。（すみません、詳しくは調べられていません）

確かにbefore_actionが複数になり、その実行順番に依存が発生してくると何が起こるか予想するのが難しくなる場合がしばしばあります。（bootcampでも[ProductsController](https://github.com/fjordllc/bootcamp/blob/master/app/controllers/products_controller.rb)がそうなってる）

なのでメソッドが1この場合は共通化する必要がないのでなるべくそっちの方に寄せたいという気持ちがあります。

2020-09-09 01:46 UTC, komagata requested changes

2020-09-09 01:46 UTC, komagata commented on app/views/companies/products/index.html.slim
> +  = render "companies/page_tabs", company: @company
これって`_tabs.html.slim`ってファイルはすでに在ったりしますかね？
もしなければより簡潔な名前・表現にしたいなと思います。

2020-09-09 02:08 UTC, gogutan commented on app/controllers/companies/products_controller.rb
>    end
なるほど、`find_foo`のようなメソッドを用意すれば、処理の共通化をしつつもインスタンス変数への代入は`show`メソッドの中で行えて🙆‍♂️、ということなんですね。初めてRailsアプリに触れた時、「`set_foo`周りは何かまどろっこしく感じるけど、アプリが大きくなるとこの方が都合がいいのかなあ」と思いましたが、これは議論のある点だとわかり大変参考になりました。
今回は`set_foo`を用いるメリットがないので、before_actionは`require_login`のみとすることでしっくりきました、ありがとうございました！🙇‍♂️

2020-09-09 02:18 UTC, gogutan commented on app/views/companies/products/index.html.slim
> +  = render "companies/page_tabs", company: @company
`users`と`applications`のビューにも同様に`_page_tabs.html.slim`ファイルがあり、今回はそれらに合わせました。リネームするなら全てまとめて、という感じでしょうか？

2020-09-13 06:56 UTC, gogutan commented on app/views/companies/products/index.html.slim
> +  = render "companies/page_tabs", company: @company
@komagata 
すみません、こちらメンション抜けていました。
今回は他のビューと合わせ、ファイル名を`_page_tabs.html.slim`としましたが、このままで問題ありませんでしょうか。ご確認お願いします。🙇‍♂️

2020-09-13 07:45 UTC, komagata requested changes

2020-09-13 07:45 UTC, komagata commented on app/views/companies/products/index.html.slim
> +  = render "companies/page_tabs", company: @company
@gogutan どちらにしろ最終的には僕が全ファイルリネームする感じになると思いますので、リネームしていただけるとありがたいです〜

2020-09-15 13:03 UTC, gogutan commented on app/views/companies/products/index.html.slim
> +  = render "companies/tabs", company: @company
@komagata 
パーシャル名を`_tabs.html.slim`にリネームしました。ご確認お願いします。🙏

2020-09-16 02:14 UTC, machida approved these changes
@gogutan 
デザイン入れましたー

2020-09-16 02:45 UTC, gogutan commented
@machida 
ありがとうございます、動かしてみましたがカッコ良くなりました！✨
追加したシステムテストで、クラス名指定のところが落ちちゃったみたいなので、そこだけ私の方で修正して最後 @komagata さんに見ていただきマージ、で良いでしょうか？

2020-09-16 03:17 UTC, komagata requested changes
テストが落ちているようなので修正お願いします。
cssについて問題があればmachidaさんと相談してみてください。

2020-09-16 09:02 UTC, gogutan commented
@komagata 
こちらテストケースを修正し、ビルドできたのでご確認お願いします🙏

2020-09-17 04:44 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-17 04:44 UTC, merged