お知らせの通知対象のデフォルトを「現役生のみ」に変更
fjordllc/bootcamp pull request #1885
Opened 2020-09-16 07:59 UTC by lamp7600

お知らせの新規作成ページを一部変更しました。通知ターゲットのデフォルトを「全員にお知らせ」から「現役生にのみ」にしました。

![image](https://user-images.githubusercontent.com/60137763/93308676-87027480-f83d-11ea-8eb2-d92b1e11db9c.png)

2020-09-17 04:41 UTC, komagata commented
上のworkflowがxということはテストが落ちているのでテストが通るようにしてみてください。

基本的にはここと関係ない場所だと思うのでCircleCIに入って再度テストを実行すればテストが通ると思います。

2020-09-17 04:42 UTC, komagata requested changes

2020-09-17 04:42 UTC, komagata commented on app/views/announcements/_form.html.slim
> +            = f.radio_button :target, "students", checked: true
これだと強制的にここがONになっちゃいそうで怖いのでcontrollerの方で初期値を設定したいですね。

2020-09-17 12:49 UTC, lamp7600 commented on app/views/announcements/_form.html.slim
> +            = f.radio_button :target, "students", checked: true
@komagata 普通にテストが落ちているのですが、自分が行った変更がなぜこのような結果になってしまうのか分かりませんでした。

```
Failure:
Notification::AnnouncementsTest#test_all_menber_recieve_a_notification_when_announcement_posted [/home/circleci/repo/test/system/notification/announcements_test.rb:25]:
Expected: "komagataさんからお知らせです。"
  Actual: "komagataさんからコメントが届きました。"

rails test test/system/notification/announcements_test.rb:13
```

2020-09-17 23:53 UTC, bluerabbit commented on app/views/announcements/_form.html.slim
> +            = f.radio_button :target, "students", checked: true
CircleCIじゃないローカルのmac（?）でも同じエラーになりますか？

2020-09-18 01:56 UTC, lamp7600 commented on app/views/announcements/_form.html.slim
> +            = f.radio_button :target, "students", checked: true
@bluerabbit
はい。昨日の段階ではエラーになりました。最新のmasterブランチを自分の作業ブランチにマージしてもやはり同じ所でテストが落ちました。

2020-09-18 02:00 UTC, komagata commented on app/views/announcements/_form.html.slim
> +            = f.radio_button :target, "students", checked: true
今のmasterのテストは通ってるようなのでそれを取り込んでやってみてください〜

2020-09-18 05:55 UTC, lamp7600 commented
@komagata やはり同じ所でテストが通りません😭

2020-09-19 04:56 UTC, komagata commented
@lamp7600 このブランチにマージしてるとこのブランチに何か問題があった場合にその影響を受けると思うので他のブランチを新たに作ってみてください〜

2020-09-19 06:39 UTC, lamp7600 commented
@komagata 了解です。このブランチとこのPRをいったん削除してから新しいブランチを作ってまたPRを出せばいいでしょうか？

2020-09-20 07:18 UTC, komagata commented
@lamp7600 はい、まずその前に、ローカルでまっさらな状態からmasterからブランチを作ってそこでテストが動くかどうか確かめてみてください〜

2020-09-20 09:39 UTC, lamp7600 commented
@komagata いろいろ試してみました。CIや僕のローカル環境のせいではなく単純に与えた変更（`checked: true`の場所を1つずらす）による結果だと思います。

####  ローカルでまっさらな状態からmasterからブランチを作ってそこでテストが動くか
動く。

#### ローカルでさっき動いた上のブランチで変更を加えて動くか
動かない。
```
Failure:
Notification::AnnouncementsTest#test_all_menber_recieve_a_notification_when_announcement_posted [/test/system/notification/announcements_test.rb:25]:
Expected: "komagataさんからお知らせです。"
  Actual: "komagataさんからコメントが届きました。"

rails test test/system/notification/announcements_test.rb:13
```

2020-09-21 07:09 UTC, closed without merging

2020-09-21 10:18 UTC, komagata commented
@lamp7600 なるほど、でしたら仕様の変更に追従するようにテストの変更をお願いします。