Add tag to questions
fjordllc/bootcamp pull request #1896
Opened 2020-09-18 04:02 UTC by HiroVodka

2020-09-18 07:01 UTC, HiroVodka commented
@komagata ご確認お願いします〜🙇‍♂️🙇‍♂️

2020-09-19 05:03 UTC, komagata requested changes

2020-09-19 05:03 UTC, komagata commented on .circleci/config.yml
> -      - run:
これが削除されているのは何故でしょう？

2020-09-20 01:49 UTC, HiroVodka commented
@komagata 再度masterをmergeしました！ご確認お願いします🙇‍♂️

2020-09-20 07:22 UTC, komagata commented
@rono23 masterの内容を自分のブランチに反映する場合にrebaseを使うのが主流なのでそっちでやってみてください。そうすればmergeコミットはできないはずで、このPRにこのPRで必要なcommitだけになります。

2020-09-20 07:27 UTC, rono23 commented
@komagata s/rono23/HiroVodka/

2020-09-21 05:42 UTC, HiroVodka commented
@komagata push済みの```最新のmasterをmerge```というcommitをgit resetした後にrebaseすれば良いでしょうか？

2020-09-21 10:16 UTC, komagata commented
@HiroVodka はい。多分いけると思います。

2020-09-21 14:38 UTC, HiroVodka commented
@komagata mergeコミットのログを削除しました！
ご確認お願いします🙇‍♂️

2020-09-22 05:57 UTC, komagata requested changes

2020-09-22 05:57 UTC, komagata commented on app/decorators/question_decorator.rb
> +    render partial: "tags_input", locals: { taggable_model: self }
名前的に、commentable, searchableなどmodelのインスタンスが入ってる変数に使ってるのでこちらも合わせてtaggable（tag付け可能）という名前でいいような気がします。

2020-09-22 07:27 UTC, HiroVodka commented on app/decorators/question_decorator.rb
> +    render partial: "tags_input", locals: { taggable_model: self }
修正しました〜
ご確認お願いします🙇‍♂️

2020-09-23 03:39 UTC, komagata requested changes

2020-09-23 03:39 UTC, komagata commented on app/decorators/question_decorator.rb
> +    render partial: "tags_input", locals: { taggable_model: self }
すいません、今頃なんですが、`render "partial"`の部分はDecoratorを使うまでもなさそうなので直接書いて良さそうです。既存の箇所がほとんどそのまま書いているので。

2020-09-24 04:54 UTC, komagata requested changes

2020-09-24 04:54 UTC, komagata commented on app/views/questions/_form.html.slim
> +            = render partial: "tags_input", locals: { taggable_model: @question }
以前に書きましたが、taggableにするのはどうでしょうか？

2020-09-26 14:39 UTC, HiroVodka commented on app/views/questions/_form.html.slim
> +            = render partial: "tags_input", locals: { taggable_model: @question }
@komagata 修正しました〜
後、Pageの同じ場所も同様に修正しました！
ご確認お願いします〜

2020-09-26 17:01 UTC, komagata requested changes

2020-09-26 17:01 UTC, komagata commented on app/views/questions/_form.html.slim
> +            = render partial: "taggable", locals: { taggable_model: @question }
この行の`taggable_model`を`taggable`にした方が良いのではないかという意味です〜

2020-09-26 17:01 UTC, komagata commented on app/views/pages/_form.html.slim
> +        = render partial: "taggable", locals: { taggable_model: @page }
この行のtaggable_modelをtaggableにした方が良いのではないかという意味です〜

2020-09-29 08:28 UTC, HiroVodka commented
@komagata 修正したのでご確認お願いします〜🙇‍♂️

2020-09-29 12:10 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-30 05:19 UTC, komagata commented
📝 @machida デザインお願いします〜

2020-09-30 16:59 UTC, machida commented
@komagata @HiroVodka デザイン入れました！masterからrebaseしてるので、手元で立ち上げるときは注意してください🙏

2020-09-30 17:07 UTC, machida commented
ちょっと気になったのが、

questions を全て見て、付けられたタグを一覧で出してますが、その見ている questons が、選択されたタブと同じように、

-  未解決の questions
- 解決済 questions
- 全ての questions

を見てました。

つまり、

- 未解決のタブを選択しているときは、未解決の questions を見て、そこに付いているタグを出している。
- 解決済のタブを選択しているときは、解決済の questions を見て、そこに付いているタグを出している。
- 全てのタブを選択しているときは、全ての questions を見て、そこに付いているタグを出している。

例えば、

ある未解決の question に「ああああ」というタグが付けられたとします。
「ああああ」というタグが付けられた question は、未解決の questions にしかありません。

なので、

- 未解決のタブを選択しているときは、「ああああ」というタグが表示される。
- 解決済のタブを選択しているときは、「ああああ」というタグが表示されない。なぜなら、解決済の questions には、「ああああ」というタグが付けられた question は存在しないから。
- 全てのタブを選択しているときは、「ああああ」というタグが表示される。

...というのが気になりました。
まぁ、これは別Issueでどう対応するのかも含めて検討したいと思います。

2020-09-30 22:53 UTC, HiroVodka commented
@machida デザインありがとうございます〜🙇‍♂️

2020-10-01 05:07 UTC, komagata commented
@HiroVodka @machida タグについてはどのページで表示されていても全部出すようにしたいですね。

2020-10-02 14:01 UTC, HiroVodka commented
@komagata 承知しました〜！
そのように変更します🙋‍♂️

2020-10-04 06:19 UTC, HiroVodka commented
@komagata @machida 
自分の手元で確認したところ全てのページで全てのタグが表示されていました〜
未解決の質問↓
![image](https://user-images.githubusercontent.com/58872020/95008342-0d97be00-0654-11eb-99e0-6045bc86f797.png)

解決済みの質問↓
![image](https://user-images.githubusercontent.com/58872020/95008395-9151aa80-0654-11eb-9e90-1873a9a9919d.png)

全ての質問↓
![image](https://user-images.githubusercontent.com/58872020/95008361-31f39a80-0654-11eb-928f-8ea8c44215dc.png)

2020-10-05 14:22 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-05 14:22 UTC, merged

2020-10-07 00:51 UTC, HiroVodka commented
@komagata こちら本番だと、タグ一覧が動いていないみたいなので修正します🙇‍♂️