メンション通知メールにメンションが含まれる本文が表示されるようにした
fjordllc/bootcamp pull request #1897
Opened 2020-09-18 04:02 UTC by shibaaaa

ref #1726 
## 提出物本文中にメンションがあった場合
### 提出物
[![image](https://user-images.githubusercontent.com/56685224/93553735-c2708080-f9ae-11ea-9834-444d2df386ce.png)](https://user-images.githubusercontent.com/56685224/93553735-c2708080-f9ae-11ea-9834-444d2df386ce.png)

### メール
[![image](https://user-images.githubusercontent.com/56685224/93550968-a0bfcb00-f9a7-11ea-8418-5e05db3b8cc5.png)](https://user-images.githubusercontent.com/56685224/93550968-a0bfcb00-f9a7-11ea-8418-5e05db3b8cc5.png)

## コメントにメンションがあった場合
### コメント
[![image](https://user-images.githubusercontent.com/56685224/93553771-dd42f500-f9ae-11ea-9600-d784caaa1649.png)](https://user-images.githubusercontent.com/56685224/93553771-dd42f500-f9ae-11ea-9600-d784caaa1649.png)

### メール
[![image](https://user-images.githubusercontent.com/56685224/93551034-c8169800-f9a7-11ea-8226-3dab38f73a6d.png)](https://user-images.githubusercontent.com/56685224/93551034-c8169800-f9a7-11ea-8226-3dab38f73a6d.png)

## 日報本文内にメンションがあった場合
### 日報
[![image](https://user-images.githubusercontent.com/56685224/93553648-7e7d7b80-f9ae-11ea-943f-81999b7277a2.png)](https://user-images.githubusercontent.com/56685224/93553648-7e7d7b80-f9ae-11ea-943f-81999b7277a2.png)
### メール
[![image](https://user-images.githubusercontent.com/56685224/93553687-97862c80-f9ae-11ea-9398-94a0460b20db.png)](https://user-images.githubusercontent.com/56685224/93553687-97862c80-f9ae-11ea-9398-94a0460b20db.png)

2020-09-19 04:55 UTC, komagata requested changes

2020-09-19 04:55 UTC, komagata commented on app/views/notification_mailer/mentioned.html.slim
> +  -if @mentionable.body
https://github.com/fjordllc/bootcamp/blob/d2ce3e9ba07adb5fb67108a02f3988f02577f676/app/models/concerns/mentioner.rb#L17

これがあるからifなしでいけないですかね？もしいけなかったら`commentable`モジュールなどを参考にしてbody, descriptionどちらでもいけるように修正したいです。

2020-09-19 05:40 UTC, shibaaaa commented on app/views/notification_mailer/mentioned.html.slim
> +  -if @mentionable.body
@komagata 
こちら`commentable`モジュールを参考に、`mentioner`モジュールの`body`メソッドを変更致しました。
その後メール本文にメンション内容が反映されることを確認できましたので、またレビューをお願い致します🙇‍♂️

2020-09-19 23:34 UTC, JunichiIto commented
@shibaaaa ついでにメールの件名も改善をお願いしたいです！
「○○さんの「ほほげする」の提出物で△△さんからメンションがありました」とかですかね〜？

2020-09-20 02:10 UTC, shibaaaa commented
@JunichiIto 
> 「○○さんの「ほほげする」の提出物で△△さんからメンションがありました」とかですかね〜？

上記のイメージでメールの件名の改善に取り組んでみます💪

2020-09-20 11:35 UTC, shibaaaa commented
@komagata (CC: @JunichiIto )
通知メールの件名にメンションの詳細を表示させるよう実装いたしました。
レビューをお願い致します🙇‍♂️

2020-09-20 11:40 UTC, JunichiIto commented
@JunichiIto コードのチェックはできていませんが、スクショを見る限りはバッチリだと思います！！（超嬉しい😍）

2020-09-21 10:15 UTC, komagata commented
@JunichiIto 出来上がったコードを見て、メンションの対象モデルごとにオリジナルのメッセージにするとモデルが増えるたびにかき分けないといけないので、要求を満たせる別の文章に変えれるといいかなと思うんですが、どういうメッセージあれば許容できるなどありますでしょうか？

2020-09-21 11:31 UTC, JunichiIto commented
@komagata 具体的には`where_mention`や`target_of_comment`で条件分岐が発生するのが問題、ということでしょうか？
caseやhashで分岐させる代わりに、ReportやProductといった各クラスで共通のメソッドを用意してポリモーフィズムを活用すれば、もう少し複雑さを減らせるような気がするんですが、どうでしょうか？

イメージ的にはこんな感じです。

```ruby
class Product
  def hogehoge
    "#{self.user.login_name}さんの「#{self.practice[:title]}」の提出物"
  end
end

class Report
  def hogehoge
    "#{self.user.login_name}さんの日報「#{self[:title]}」"
  end
end

subject = "[bootcamp] #{@mentionable.hogehoge}で#{@mentionable.sender.login_name}さんからメンションがありました。"
```

2020-09-22 02:30 UTC, shibaaaa commented
@JunichiIto 
誠に僭越ながら、僕がこの実装をする上で考えたことを申し上げます。
> ReportやProductといった各クラスで共通のメソッドを用意してポリモーフィズムを活用

僕もこの方法をとるべきか非常に悩みました。しかし、`mentioner`モジュールと同じ階層にある、`watchable`モジュールや`commentable`モジュールを参考にすると、モジュール内で通知メールの文面を整える分岐処理が書かれていました。
https://github.com/fjordllc/bootcamp/blob/07e221d718975f4e7a23ecd9185a396d80b79429/app/models/concerns/watchable.rb#L16-L28
https://github.com/fjordllc/bootcamp/blob/07e221d718975f4e7a23ecd9185a396d80b79429/app/models/concerns/commentable.rb#L13-L29

その上で、メンションの通知メールの文面をモデルによって分岐させるコードを`mentioner`モジュールに書きました。
もしこれらの処理をポリモーフィズムで実装するのでしたら、別PRにて各モジュールのリファクタリングが必要なのではないかと考えています。
以上、大変恐縮ですがご参考になれば幸いです🙇‍♂️

2020-09-22 06:01 UTC, komagata commented
@JunichiIto 元の要件として何が問題だったのかを聞いた上で仕様を考えることができればなと思っております。その上で対象のクラスが増えるたびに通知のための追記が増えなくなるような方法がないかなーと思っております。

2020-09-22 11:47 UTC, imaharu commented on app/models/concerns/mentioner.rb
>    end
初コメントで要領わかってないのとドメイン知識なく言ってるので、無視してOKです〜

各モデルに、適当なメソッド名を定義してたら、caseを利用せずに実装できたりしないですかね？

イメージ

```ruby
class Product
  def hoge
    "#{user.login_name}さんの「#{practice[:title]}」の提出物"
  end
end

class Report
  def hoge
    "#{user.login_name}さんの日報「#{[:title]}」"
  end
end

class Comment
  def hoge
    target_of_comment(self.commentable.class, self.commentable) + "へのコメント"
  end

  private 
  def target_of_comment(commentable_class, commentable)
    ...
  end
end

module Mentioner
  def where_mention
    self.hoge
  end
end
```

2020-09-22 22:52 UTC, JunichiIto commented
@komagata 
> 元の要件として何が問題だったのか

以下、現状のメンションの通知メールに関する僕の認識です。

-------------

今はメンションがあったことしかメールで通知されない。
誰が何についてメンションしたのかわからない。
そのため、「このメンションへ」をクリックしないと内容が確認できない。

<img width="711" alt="Screen Shot 2020-09-23 at 7 34 36" src="https://user-images.githubusercontent.com/1148320/93945150-548ed500-fd71-11ea-9d30-1890753cfa18.png">


メンションへをクリックするのはワンクリックぶん手間が増える。
状況によってはログインを要求されたりするので、その場合はさらに手間が増える。
スマホで見ている場合はメーラーでリンクをクリック→ブラウザの選択→ブラウザの表示→メーラーに戻る、といった操作も必要になることがある。

メンションにアクセスすることで、通知が既読になる。
とりあえず目は通すが、返信はあとで書こう、と思ったりした場合は通知はなるべく未読のままにしておきたい。（未読の通知を一種のTODOリストとして管理したい）
通知メールだけ読めば内容を把握できる、という場合はそれが可能だが、メンションの通知メールではそれができない。

「Aさんがコメントしました」という通知はコンテキストがある程度はっきりしている。
なぜなら多くの場合、自分がメンターとしてすでにコメントした日報や提出物にコメントが返ってきたからだ。

しかしメンションはコンテキストがハッキリしない。
自分がコメントした日報や提出物以外からでも突然誰かからメンションされることはあるからだ。
よってどうしても内容を確認せざるを得なくなる。
その場合にブートキャンプへアクセスしたり、ログイン情報を入力したりするのは手間である。

単純に他の通知メールとUXが異なるというのも気持ちが悪い。
なぜメンションだけ「メンションがありました」としか教えてくれないんだ？？という一貫性のなさがユーザーとしてしっくりこない。

以上のことから、メンションの通知メールも、誰が、誰のどの日報や提出物やQ&Aなどで、どんな内容をメンションしてきたのか、メールで確認できるようにしたい。

-------------

僕の認識をできる限り言語化してみました。よろしくお願いします〜。

2020-09-23 01:42 UTC, shibaaaa commented
@komagata 
大変恐縮なんですが、メンションの通知メールのロジックを@JunichiIto さんや@imaharu さんの仰るような実装方法にし、また別issueとして`watchable`モジュールや`commentable`モジュールのリファクタリングを行うというのはいかがでしょうか？
@komagata さんの仰るように、`watchable`モジュールや`commentable`モジュールもモデルが増えるたびにかき分けないといけない実装になっているので、これを機にリファクタリングすることで後々の負担を減らせるのではないかと考えています。

何卒ご検討頂けますと幸いです。

2020-09-23 03:53 UTC, komagata commented
@JunichiIto 

要求の部分の詳細ありがとうございます。よくわかりました。

> 具体的にはwhere_mentionやtarget_of_commentで条件分岐が発生するのが問題、ということでしょうか？

分岐が発生するのが問題、ということではないです。

対象が増えるたびに追記しないといけないという状態が問題（避けられないかな〜）という感じです。（なのでメソッドを上書きする方法でも同様です）

直近でgogutanさんのIssueでそういう場所にクラス名を追加しないと動かなくなる箇所があってそこがわかりづらい場所で苦戦していたので。

ある程度共有のパターンを作るなどして必ず固有の文言を追加せずいけないかなと思っていました。

僕は良い代案が思いつかないので今のままで大丈夫です。

CC: @shibaaaa

2020-09-24 08:26 UTC, shibaaaa commented
@komagata 

こちらのPRでの実装はどのように致しましょうか？💦
僕が実装させて頂きました、通知メールの文言でよろしいのでしょうか？
コードの見直しが必要であれば対応致します🙇‍♂️

2020-09-25 06:04 UTC, komagata commented
@shibaaaa 現状でいいのでレビューします〜

2020-09-25 06:05 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-25 06:05 UTC, merged

2020-09-25 06:08 UTC, shibaaaa commented
@komagata 
レビュー頂きありがとうございます！