お知らせの通知ターゲットの初期値を現役生のみへ変更
fjordllc/bootcamp pull request #1906
Opened 2020-09-21 07:11 UTC by lamp7600

![image](https://user-images.githubusercontent.com/60137763/93740244-14bad700-fc25-11ea-9dff-7a6787d9fb4e.png)

2020-09-21 10:21 UTC, komagata requested changes

2020-09-21 10:21 UTC, komagata commented on app/controllers/announcements_controller.rb
> +    @announcement = Announcement.new(target: "students")
👍

2020-09-21 10:21 UTC, komagata commented on db/schema.rb
> +    t.integer "target", default: 1, null: false
ここは何故変わっているんでしょう？

2020-09-21 10:37 UTC, lamp7600 commented on db/schema.rb
> +    t.integer "target", default: 1, null: false
@komagata すいません。`schema.rb`を変えればデータベースの構造が変わるというとんでもない勘違いをしておりました。このファイルは自分でいじるものではないですね。マイグレーションファイルを作ってデフォルトを現役生のみに変更しようと思います。

2020-09-21 12:20 UTC, lamp7600 commented on db/schema.rb
> +    t.integer "target", default: 1, null: false
@komagata 修正しました。よろしくお願いします。

2020-09-22 05:52 UTC, komagata requested changes

2020-09-22 05:52 UTC, komagata commented on db/schema.rb
> +    t.integer "target", default: 1, null: false
Ruby上で設定できていればDBのデフォルトは変えなくてもいいと思います。

この仕様は変わりそうで、DB的には0じゃなくて1がデフォルトの方が想定しづらくびっくりするので0にしとくのが良さそうなため。

2020-09-22 07:02 UTC, lamp7600 commented
@komagata 修正しました。ご確認お願いします🙏

2020-09-23 03:37 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-23 03:37 UTC, merged