ユーザーの最終アクセス日時をプロフィール画面に表示したい
fjordllc/bootcamp pull request #1911
Opened 2020-09-23 07:15 UTC by takopom

#1893 の作業です。

2020-09-25 04:48 UTC, takopom commented
@machida 
機能の実装が終わりましたので、以下の箇所のデザインをお願いしたいと思っております。

- ユーザープロフィール
    - 最終ログイン日時のclassに`is-important`がある場合の見た目
- ユーザー一覧
    - 「1ヶ月ログインがありません」テキストの見た目
        - このテキスト部分に、`users-item__active-message`というクラス名を仮で設定しました

「1ヶ月以上ログインのないユーザー一覧」については、「3日連続😢のユーザー」と同じ表示になるようにしました。

ご確認よろしくお願いいたします🙇‍♀️

2020-10-04 20:21 UTC, takopom commented
作業ブランチの内容が古くなってしまったため、最新のmasterを反映しました。

2020-10-04 20:22 UTC, takopom commented
@machida デザインをお願いできると幸いです。よろしくお願いいたします🙇‍♀️

2020-10-07 04:12 UTC, machida commented
@takopom すいません、遅くなりました🙇‍♂️
デザイン入れました！！

2020-10-07 04:12 UTC, machida commented
@komagata レビューお願いします🙏

2020-10-07 04:27 UTC, komagata requested changes

2020-10-07 04:27 UTC, komagata commented on app/views/users/_inactive_users.html.slim
> +- if users.any? { |user| !user.active? }
ここDB側で絞り込みたいですね。

2020-10-07 14:39 UTC, takopom commented
@machida こちらの「メンターだけが見れる情報」についてご確認です🙇‍♀️

<img width="300" alt="user_profile" src="https://user-images.githubusercontent.com/2003287/95341761-94b59200-08f1-11eb-8b76-3c74cd4f8072.png">

「就職を希望しない、office_worker…」といった情報は、管理者のみが見れる（メンターは見れない）ようになっていました。

管理者の場合は、添付画像のようにすべての情報を表示し、
メンターの場合は「最終ログイン日時」のみを表示する、ということで合っているでしょうか？

それとも、管理者orメンターならば、添付画像のように表示する形でしょうか。

2020-10-07 14:42 UTC, takopom commented on app/views/users/_inactive_users.html.slim
> +- if users.any? { |user| !user.active? }
@komagata ご指摘ありがとうございます！💦　修正しましたので、ご確認いただけると幸いです🙇‍♀️

2020-10-07 15:11 UTC, machida commented
@takopom 
すいません、僕の勘違いでした。
管理者のみが見れる（メンターは見れない）ではなく、メンターも管理者も見れると思ってました。
こちら、今回の対応で、この枠と枠の中の内容全てを、管理者もメンターも見れるようにしていただきたいです🙏

2020-10-07 15:16 UTC, takopom commented
@machida ご確認ありがとうございます！
「管理者もメンターも見れる」ようにいたします！🙆‍♀️

2020-10-09 13:52 UTC, takopom commented
@machida ロールが「研修生」の場合の表示について、ご確認です。
現在は「研修生」の場合は、「メンターだけが見れる情報」にあたる内容は、表示されないようになっていました。

添付画像は、1ヶ月以上ログインしていない研修生と現役生が並んだ状態です。
研修生の場合も、「メンターだけが見れる情報」として、最終ログイン日時だけは表示した方がよいかな？と思い、試しに表示してみましたが、いかがでしょうか。
<img width="400" alt="スクリーンショット 2020-10-09 22 46 37" src="https://user-images.githubusercontent.com/2003287/95591135-de34e700-0a81-11eb-9e79-39d2eecc886a.png">
ご確認いただけると幸いです🙏

2020-10-22 23:50 UTC, takopom commented
@komagata @machida こちらのIssue、長らく時間をかけてしまい申し訳ありません💦
少し気になった箇所を修正し、最新のmasterを反映いたしました。
再度レビューしていただけると幸いです🙇‍♀️

2020-10-23 12:39 UTC, machida commented
@takopom いえいえ、ご対応ありがとうございますー！！

2020-10-24 05:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-24 05:55 UTC, merged

2020-11-18 05:00 UTC, komagata commented
@takopom こちら、本番環境で動作することを確認しました。