メンターメモを提出物個別ページにも表示できるようにした
fjordllc/bootcamp pull request #1914
Opened 2020-09-24 03:05 UTC by shibaaaa

ref #1903 
## 概要
- プラクティス詳細ページに表示しているメンターメモを提出物個別ページでも表示するように変更しました。
- こちらのレビュー完了後に #1904 に対応するため、メンターメモが空でも表示するように変更しました。
## プラクティス詳細画面
<img width="773" alt="OS_X_Mountain_Lionをクリーンインストールする___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/56685224/94096034-102d3300-fe5e-11ea-90f9-14eb37b65167.png">

## 上記プラクティスの提出物個別ページ
<img width="932" alt="OS_X_Mountain_Lionをクリーンインストールするの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/56685224/94096119-3d79e100-fe5e-11ea-98fb-f183f1b4a8f7.png">

2020-09-24 03:07 UTC, shibaaaa commented
@machida 
こちらデザインをお願い致します🙇‍♂️

2020-09-24 04:02 UTC, machida commented
@shibaaaa デザインいれましたー！！

2020-09-24 04:03 UTC, machida commented
メンターメモ、スマホのときは非表示です。

2020-09-24 04:14 UTC, shibaaaa commented
@machida 
迅速なご対応を頂きありがとうございます！

2020-09-24 04:18 UTC, shibaaaa commented
@komagata 
こちらレビューをお願い致します🙇‍♂️

2020-09-24 04:29 UTC, komagata requested changes
簡単なポイントなのでちょっとしたテストがあると良いかもです。

2020-09-24 07:48 UTC, shibaaaa commented
@komagata 
> 簡単なポイントなのでちょっとしたテストがあると良いかもです。

こちらテストを追記いたしました。
またレビューをお願い致します🙇‍♂️

2020-09-25 05:31 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-25 05:31 UTC, komagata commented on test/system/practices_test.rb
> +    assert_text "メンター向けのメモの内容です"
👍

2020-09-25 05:31 UTC, merged

2020-09-25 08:08 UTC, shibaaaa commented
@komagata @machida 
こちら本番環境でご確認をお願い致します🙇‍♂️

2020-09-26 16:30 UTC, komagata commented
@shibaaaa 本番環境で動作することを確認しました。