docsの最終編集者を表示する
fjordllc/bootcamp pull request #1917
Opened 2020-09-24 05:26 UTC by lamp7600

## docsの最終編集者を表示する

![本当のタイトルです___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/60137763/94104263-9a32c700-fe71-11ea-900c-c39c74a6468a.png)

## 誰でも削除と編集ができるようにボタンを追加
![Docs___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/60137763/94104388-dfef8f80-fe71-11ea-83d2-edc29fc877c3.png)

2020-09-24 07:00 UTC, machida commented
@lamp7600 docsも含めて一覧ページ（index）には削除リンクを出さない方針にしました。削除は個別ページ（show）だけで行きたいと思います。そのcommit を入れておきました。

pushの前に

```
git pull --rebase origin add_last_updated_user_to_docs 
```

をお願いします。

2020-09-24 07:09 UTC, lamp7600 commented
@machida 了解です！ありがとうございます！

2020-09-24 07:58 UTC, machida commented
@lamp7600 また少しデザイン入れましたー

2020-09-24 08:05 UTC, lamp7600 commented
@machida ありがとうございます！

2020-09-24 08:08 UTC, lamp7600 commented
@machida 編集がされていない投稿はこのように表示されているのですが大丈夫でしょうか？
![image](https://user-images.githubusercontent.com/60137763/94118365-6adb8480-fe88-11ea-9941-c3c4baa0d12f.png)

2020-09-25 03:10 UTC, machida commented
@lamp7600 なるほどー、最終更新がない場合は、そのdocを作った日と、その作者を表示お願いしたいです🙏

2020-09-25 03:11 UTC, machida commented
@lamp7600 
あとすいません🙇‍♂️
一つ追加で、削除はご操作を防ぐために、オリジナルの作者と管理者だけに表示するようお願いします🙏

2020-09-25 03:38 UTC, lamp7600 commented
@machida 
> 最終更新がない場合は、そのdocを作った日と、その作者を表示

添付画像が今の仕様なのですが、新規作成しても最終稿ｓん
![image](https://user-images.githubusercontent.com/60137763/94223833-d9255300-ff2b-11ea-979a-5391c937c15d.png)

2020-09-25 04:59 UTC, machida commented
@lamp7600 

> 新規作成: 2020年09月25日(金) 12:36 by ユーザー名

はい！これでお願いしたいですー！！
「新規作成」と表示するの気が利いててすごくいいです！！

2020-09-25 06:58 UTC, lamp7600 commented
@machida 修正しました！再度デザインのご確認をお願いします🙏

2020-09-25 08:40 UTC, machida approved these changes
デザイン確認しました！！

2020-09-26 16:45 UTC, komagata requested changes

2020-09-26 16:45 UTC, komagata commented on db/migrate/20200924020027_add_last_updated_user_to_pages.rb
> +    add_column :pages, :last_updated_user_id, :bigint
migrationが解釈された上でschema.rbで`bigint`になっているカラムはあるけどmigrationファイル内で明示的に`bigint`を指定してるものはないのでここは他に合わせて`integer`がいいと思います。

2020-09-27 07:08 UTC, lamp7600 commented
@komagata 修正しました。よろしくお願いします🙏

2020-09-27 11:41 UTC, komagata approved these changes
conflictしているので修正お願いします〜

2020-09-27 13:53 UTC, lamp7600 commented
@komagata conflictを解消しました。

2020-09-29 11:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-29 11:53 UTC, merged