日報をコピーした時にflashを追加
fjordllc/bootcamp pull request #1925
Opened 2020-09-25 05:33 UTC by lamp7600

![image](https://user-images.githubusercontent.com/60137763/94230037-08dc5700-ff3c-11ea-9322-a5ff03b60647.png)

2020-09-25 05:36 UTC, bluerabbit commented on app/controllers/reports_controller.rb
> +    redirect_to new_report_path(id: params[:id])
```suggestion
    redirect_to new_report_path(id: params[:id]), notice: "日報をコピーしました"
```

2020-09-25 06:15 UTC, lamp7600 commented on app/controllers/reports_controller.rb
> +    redirect_to new_report_path(id: params[:id])
@bluerabbit ありがとうございます！修正しました！

@komagata CIが通りましたのでご確認お願いします🙏

2020-09-25 06:23 UTC, komagata commented
GitHubの機能を使ってレビュー依頼をお願いします〜

2020-09-26 16:25 UTC, komagata requested changes

2020-09-26 16:25 UTC, komagata commented on app/controllers/reports_controller.rb
> +  def copy
CRUD以外のactionを増やすのはよくなさそうなのでnewのアクションをそのまま使って、`/reports/new?id=123`みたいにid渡されたらコピーというのはどうでしょうか。

2020-09-27 02:46 UTC, lamp7600 commented on app/controllers/reports_controller.rb
> +  def copy
@komagata もともとIDが渡されたらコピーとなるコードでした。それで最初はif節の最後でflashを渡したのですが、これだとリロードしてもフラッシュが表示されてしまいます。この問題を解決する方法が分からず`copy`アクションを作って実装しました。

`app/controllers/reports_controller.rb`
```ruby
  def new
    @report = Report.new(reported_on: Date.current)
    @report.learning_times.build()

    if params[:id]
      report              = current_user.reports.find(params[:id])
      @report.title       = report.title
      @report.reported_on = Date.current
      @report.emotion = report.emotion
      @report.description = report.description
      @report.practices   = report.practices
      # リロードしてもflashが表示されてしまう
      # flash.now[:notice] = "日報をコピーしました" 
    end
  end

  def copy
    redirect_to new_report_path(id: params[:id]), notice: "日報をコピーしました。"
  end
```

2020-09-27 11:37 UTC, komagata commented on app/controllers/reports_controller.rb
> +  def copy
リロードしてそのflashが表示されてもコピー的な処理は行われてるのでそのままで大丈夫です〜

2020-09-27 14:17 UTC, lamp7600 commented
@komagata 修正しました。ご確認お願いします🙏

2020-09-29 11:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-29 11:55 UTC, merged