卒業生は全ての提出物を見ることができる仕様に変更
fjordllc/bootcamp pull request #1941
Opened 2020-09-28 03:55 UTC by lamp7600

2020-09-29 12:02 UTC, komagata commented on app/controllers/products_controller.rb
> +      return if current_user.graduated_on?
なるべく下記のような既存の仕組みを使って欲しいです〜

https://github.com/fjordllc/bootcamp/blob/24de47bb0423be74c49880e6810ea7c7e815abf8/app/policies/product_policy.rb#L11

2020-09-29 15:52 UTC, lamp7600 commented
@komagata 修正しました。よろしくお願いします🙏

2020-10-01 05:01 UTC, komagata reviewed
テストが欲しいっすね

2020-10-02 02:53 UTC, lamp7600 commented
@komagata テストを追加しました。ご確認お願いします🙏

2020-10-02 12:00 UTC, komagata requested changes

2020-10-02 12:00 UTC, komagata commented on test/system/products_test.rb
> +
この変更点はなんでしょう？

2020-10-02 12:00 UTC, komagata commented on test/system/products_test.rb
> +  test "graduate can see a product" do
graduateだと動詞なので主語になるのはおかしいかも？

2020-10-02 12:03 UTC, lamp7600 commented on test/system/products_test.rb
> +
@komagata 
なぜかここだけに空行がなかったので追加しました。

2020-10-02 12:06 UTC, lamp7600 commented on test/system/products_test.rb
> +  test "graduate can see a product" do
@komagata graduateには卒業生という名詞の意味もあったので使いました。

2020-10-02 12:08 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-02 12:08 UTC, komagata commented on test/system/products_test.rb
> +  test "graduate can see a product" do
なるほど、でしたらOKです〜

2020-10-02 12:09 UTC, merged

2020-10-02 12:15 UTC, lamp7600 commented
@komagata ありがとうございました！