プラクティスに最終更新日時と最終更新者を表示
fjordllc/bootcamp pull request #1942
Opened 2020-09-28 07:22 UTC by lamp7600

2020-09-28 07:48 UTC, lamp7600 commented
@machida デザインをお願いします🙏

2020-09-30 16:38 UTC, machida approved these changes

2020-09-30 16:41 UTC, machida commented
@lamp7600 デザイン入れました！masterをrebaseしてるので、手元で動かすときは、手元のこのブランチを削除した上で `git fetch origin` をするなどお願いしますー

2020-10-01 01:38 UTC, lamp7600 commented
@machida デザインありがとうございます！

2020-10-01 01:53 UTC, lamp7600 commented
@komagata こちらよろしくお願いします🙇‍♂️

2020-10-01 05:11 UTC, komagata requested changes
conflictの解消お願いします

2020-10-01 10:54 UTC, lamp7600 commented
@komagata 修正しました。よろしくお願いします。

2020-10-02 11:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-05 08:14 UTC, lamp7600 commented
@komagata　こちら三日前にOKをいただいたのですがまだマージされていないのには理由があるのでしょうか？

2020-10-05 14:26 UTC, komagata requested changes
おかしなmergeコミットが入っているので修正お願いします〜

2020-10-05 14:27 UTC, komagata commented
> こちら三日前にOKをいただいたのですがまだマージされていないのには理由があるのでしょうか？

すみません、忘れていただけだと思います。

2020-10-05 14:57 UTC, lamp7600 commented
@komagata 今日のマージコミットですよね？今日みたらコンフリクトが起こっていたので修正しました。

2020-10-06 08:08 UTC, komagata commented
@lamp7600 ここの下の二つがおかしいと思うので修正お願いします。

<img width="657" alt="スクリーンショット 2020-10-06 17 07 18" src="https://user-images.githubusercontent.com/16577/95175430-7028bf80-07f6-11eb-93f5-a946d25aae35.png">

2020-10-06 09:33 UTC, lamp7600 commented
@komagata かなり試行錯誤したのですが、どうやって修正すればいいのか分かりません。GitHub上で修正したからなのか、git resetもrevertもできません。

2020-10-06 10:58 UTC, lamp7600 commented
@komagata 修正しました。

2020-10-07 04:23 UTC, komagata commented
@lamp7600 このPRでの変更点（masterとの差分）だけのcommitになるはずで、merge commitはできないはずなので見直してみてください。

2020-10-07 06:54 UTC, lamp7600 commented
@komagata `master`を`rebase`しました。ご確認お願いします🙏

2020-10-07 07:01 UTC, komagata requested changes

2020-10-07 07:01 UTC, komagata commented on db/schema.rb
> +    t.integer "last_updated_user_id"
ここが変わってて、schema.rbのバージョンが変わってないと整合性が取れないように思います。

2020-10-07 07:27 UTC, lamp7600 commented
@komagata 
現状としては、`schema.rb`は以下の通りです。

```ruby 
# 最新(master)
ActiveRecord::Schema.define(version: 2020_09_30_121031) 
# このPRでは本来こうだったがコンフリクトの解消のため9/30日のversionに変更
ActiveRecord::Schema.define(version: 2020_09_28_051558) 
```



`rails db:migration:status`の結果は全て`up`になっており、問題ないように思いますが、自分の解釈は間違っているでしょうか？
```
up     20200928051558  Add last updated user to practices
up     20200930121031  Add wip to events
```

2020-10-07 07:53 UTC, komagata commented
@lamp7600 基本schame.rbしかみないので、そのバージョンが変わってなければ何も怒らないと思います。
ローカルで最新の状態でrake db:resetしても何も変わらないですかね？

2020-10-07 08:17 UTC, lamp7600 commented
@komagata 
> ローカルで最新の状態でrake db:resetしても何も変わらないですかね？

はい。何も変更はありませんでした。

2020-10-07 12:25 UTC, komagata approved these changes
僕の方で修正しておきました。マージします。

2020-10-07 12:46 UTC, merged