提出物をWIP状態から提出すると、ステータスが「提出」に変更されない、アドバイザーに通知されない
fjordllc/bootcamp pull request #1947
Opened 2020-09-29 01:36 UTC by takopom

2020-09-29 12:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-29 12:06 UTC, komagata commented on db/migrate/20200927200349_add_published_at_to_products.rb
> +    add_column :products, :published_at, :datetime
👍

2020-09-29 12:06 UTC, komagata requested changes
conflictの解消お願いします〜

2020-09-29 23:48 UTC, takopom commented
@komagata コンフリクト解消しました。ご確認をお願いいたします🙇‍♀️

2020-10-01 05:01 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-01 05:01 UTC, merged

2020-12-23 05:57 UTC, takopom commented
@komagata お手隙の際に、本番環境での動作確認をお願いいたします🙇‍♀️

2020-12-23 08:24 UTC, komagata commented
@takopom 下記の提出物をWIPで作り、提出状態にしましたが、新しく作ったアドバイザー（komagata-test10）で通知が来ていませんでした。

https://bootcamp.fjord.jp/products/6094

ただ、これは僕の見逃しで大変申し訳ないんですが、アドバイザーには提出物の通知は不要でした。
（アドバイザーは就職先企業の方が卒業見込みの生徒の成果物を見るためのアカウントなので）

2020-12-24 05:35 UTC, takopom commented
@komagata ご確認いただきありがとうございます！🙏
通知が来ていなかったとのことで、ひとつご確認させてください💦

提出物は「研修生のユーザー」であることが条件になっており、この点はいかがでしたでしょうか👀
https://github.com/fjordllc/bootcamp/blob/master/app/models/product_callbacks.rb#L13

> アドバイザーには提出物の通知は不要でした
> （アドバイザーは就職先企業の方が卒業見込みの生徒の成果物を見るためのアカウントなので）

なるほど…！！アドバイザーの役割をただいま理解しました😅
通知が来ないように別Issueで対応した方がよいでしょうか？

2020-12-27 10:52 UTC, komagata commented
> 提出物は「研修生のユーザー」であることが条件になっており、この点はいかがでしたでしょうか👀

あ、これは研修生でやってませんでした〜

> 通知が来ないように別Issueで対応した方がよいでしょうか？

別のIssueで今後対応したいと思うので現状はこちらで大丈夫です〜

2020-12-28 00:22 UTC, takopom commented
> 別のIssueで今後対応

承知いたしました！🙆‍♀️

研修生でのご確認、お手隙の際にお願いいたします🙏

2021-01-27 00:12 UTC, takopom commented
@komagata こちら、本番環境にて
・研修生ユーザーが提出物をWIP→提出で、アドバイザーに通知が届くこと
をご確認いただきたいです🙏 度々すみませんが、よろしくお願いします💦

2021-02-01 08:04 UTC, komagata commented
@takopom 大変申し訳ありません、確認します。

2021-02-01 08:33 UTC, komagata commented
@takopom WIP→提出でアドバイザーに通知がいくことを確認しました。
遅くなってしまって大変申し訳ありません。

2021-02-01 23:57 UTC, takopom commented
@komagata とんでもないです！💦 ご確認いただきありがとうございます🙏✨