誰でもイベントを作成できるようにする
fjordllc/bootcamp pull request #1963
Opened 2020-10-01 07:36 UTC by lamp7600

## 誰でもイベントを作成できるが公開は管理者しかできない
![image](https://user-images.githubusercontent.com/60137763/94780501-7f2cfd80-0403-11eb-826c-4ed262431e28.png)

## WIP機能の実装
![image](https://user-images.githubusercontent.com/60137763/94780527-8eac4680-0403-11eb-9418-783548b7ce5d.png)
![image](https://user-images.githubusercontent.com/60137763/94780745-e3e85800-0403-11eb-8978-ec34291ce1e9.png)

## 管理者にはWIPと公開のボタンがある
![image](https://user-images.githubusercontent.com/60137763/94780925-1c883180-0404-11eb-90e1-bee17f856b48.png)

![image](https://user-images.githubusercontent.com/60137763/94780850-067a7100-0404-11eb-98e3-9c376d94e695.png)

2020-10-02 11:54 UTC, komagata requested changes

2020-10-02 11:54 UTC, komagata commented on test/system/events_test.rb
この辺りのテストが欲しいですね。（Issueの仕様に該当するもの）

2020-10-02 15:25 UTC, lamp7600 commented on test/system/events_test.rb
@komagata テストを追加しました。よろしくお願いします。

2020-10-05 07:58 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-05 07:58 UTC, komagata commented on test/system/events_test.rb
> +    assert_text "イベントをWIPとして保存しました。"
👍

2020-10-05 07:58 UTC, merged