Q&Aの個別ページ上でタグの編集ができるようにした
fjordllc/bootcamp pull request #1971
Opened 2020-10-06 03:42 UTC by shibaaaa

ref #1910 

## 概要
- Q&Aの個別ページ上でタグの編集ができるようにしました。
- 「編集ボタン」が表示されるのは管理者・メンター・質問したユーザーのみです。
- タグ入力フォームは既存のapp/javascript/tags-input.vueを流用しています。

## ローカルでの画面

![](http://g.recordit.co/AxcbTQ2RAs.gif)

2020-10-06 03:44 UTC, shibaaaa commented
@machida 
こちらデザインをお願いします🙇‍♂️

2020-10-07 03:13 UTC, machida commented
@shibaaaa @komagata 

こちらのPRのデザインに関しては、

https://github.com/fjordllc/bootcamp/pull/1970

このPRとUIが同じなので、#1970 がマージされてから着手したいと思います。
なので、

1. #1970 を先にレビュー。レビューが通ったらマージ。
1. このPR（#1971）をデザインがまだの状態でレビュー。
1. レビューが通ったら #1970 が含まれてるmasterをrebase。
1. rebaseしたものに町田がデザインを入れる。
1. そしてマージ。

という流れでお願いしたいです🙏

2020-10-07 04:46 UTC, shibaaaa commented
@machida 
承知致しました！

2020-10-07 05:26 UTC, shibaaaa commented
✍️2020/10/7 MTGにてこちらのPRについて下記の通りとなりました
- デザインを待たずに駒形さんへレビューを頂く
- レビュー完了後は町田さんへ作業を引き継ぐ

2020-10-07 09:02 UTC, shibaaaa commented
@komagata (CC: @machida )
こちら最新のmasterをrebaseしました。
レビューをお願い致します🙇‍♂️

2020-10-08 12:14 UTC, komagata requested changes

2020-10-08 12:14 UTC, komagata commented on app/controllers/api/questions_controller.rb
> +      @question = Question.find(params[:id])
これだと他人のQ＆Aタグも編集できちゃうかもです。

2020-10-08 12:21 UTC, shibaaaa commented on app/controllers/api/questions_controller.rb
> +      @question = Question.find(params[:id])
@komagata 
なるほど、そうですね💦
こちらは以下を参考に修正します。
https://github.com/fjordllc/bootcamp/blob/dfd41bc562a5d0f366fa7798aa70ed75b328685b/app/controllers/api/comments_controller.rb#L45-L47

2020-10-08 13:40 UTC, shibaaaa commented on app/controllers/api/questions_controller.rb
> +      @question = Question.find(params[:id])
@komagata 
こちら修正致しました。
またレビューの程、よろしくお願い致します🙇‍♂️

2020-10-12 08:50 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-12 08:53 UTC, shibaaaa commented
@komagata 
レビュー頂きありがとうございます！

@machida 
こちらレビューをOK頂きましたので、デザイン等今後のご対応をよろしくお願い致します🙇‍♂️

2020-10-30 06:23 UTC, machida commented
@komagata デザイン完了しましたー

2020-10-30 07:08 UTC, shibaaaa commented
@machida 
デザインありがとうございます！
class名変更に伴いテストが落ちるようになっていたので修正致しました🙏

2020-11-04 03:42 UTC, machida commented
@shibaaaa 対応ありがとうございます！！

2020-11-04 03:43 UTC, machida commented
@komagata @shibaaaa では、こちらマージしてしまいますー🎉

2020-11-04 03:43 UTC, merged

2020-11-04 05:11 UTC, shibaaaa commented
@komagata @machida 
こちら本番環境で動作確認できました！