同期一覧ページが欲しい
fjordllc/bootcamp pull request #1975
Opened 2020-10-07 00:06 UTC by takopom

#1876 の作業です。

2020-10-13 13:14 UTC, komagata requested changes

2020-10-13 13:14 UTC, komagata commented on app/controllers/user_generations_controller.rb
> +    def generation_start_date(generation)
この辺は、`User`モデルにまとめるか、新しく`Generation`とか作るかどっちかにしてもモデルにまとめるのが良さそうです〜

2020-10-13 13:21 UTC, takopom commented on app/controllers/user_generations_controller.rb
> +    def generation_start_date(generation)
@komagata ご確認ありがとうございます！自分でも気掛かりだった箇所でした💦 修正いたします。

2020-10-15 09:07 UTC, komagata requested changes

2020-10-15 09:07 UTC, komagata commented on app/models/generation.rb
> +  def self.start_date(generation)
Generationクラスがgenerationの数字を持つってのはしっくりくる感じなのでインスタンスメソッドにするのがいいかもです。

```ruby
generation = Generation.new(24)
puts generation.start_date
puts generation.users
```

みたいな感じで。

2020-10-15 23:53 UTC, takopom commented on app/models/generation.rb
> +  def self.start_date(generation)
@komagata なるほど…！！とてもしっくりきました。ご助言ありがとうございます🙏 そのようにしてみます。

2020-10-19 15:12 UTC, takopom commented on app/models/generation.rb
> +  def self.start_date(generation)
@komagata 修正しました。再度レビューしていただけると幸いです🙇‍♀️

2020-10-21 08:13 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-21 08:13 UTC, komagata commented on app/models/generation.rb
> +  def initialize(number)
👍

2020-10-21 08:13 UTC, merged

2020-10-21 17:26 UTC, takopom commented on app/models/generation.rb
> +  def initialize(number)
@komagata ご確認ありがとうございました！🙏✨