作品ページのユーザー名リンクの遷移先をプロフィールページに修正
fjordllc/bootcamp pull request #1985
Opened 2020-10-07 13:25 UTC by hogucc

2020-10-07 14:19 UTC, hogucc commented
@komagata レビューをお願いいたします🙇‍♀️

2020-10-08 12:11 UTC, komagata requested changes

2020-10-08 12:11 UTC, komagata commented on test/system/works_test.rb
> +    assert_link "kimura", href: "/users/991528156"
このIDって毎回同じってわけではないので実際の値を書いてしまうとまずいかもです

2020-10-09 03:51 UTC, hogucc commented on test/system/works_test.rb
> +    assert_link "kimura", href: "/users/991528156"
ご確認ありがとうございます。
固定値ではなく、`"/users/#{users(:kimura).id}"`に修正しました。

2020-10-12 08:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-12 08:52 UTC, merged