フォローしたユーザーの日報が投稿されたら通知される機能を追加
fjordllc/bootcamp pull request #2015
Opened 2020-10-17 15:32 UTC by ima1zumi

# 概要
フォローしたユーザーの日報が投稿されたら通知される機能を追加した。
ref: https://github.com/fjordllc/bootcamp/issues/1902

# やったこと
- ユーザーページ ( `/users/:id` )に「日報をフォローする」「フォロー解除する」ボタンを追加
- 自分のユーザーページに「フォロー一覧を見る」ボタンを追加
- ユーザー一覧ページ ( `/users` ) に「日報をフォローする」「フォロー解除する」ボタンを追加
- ユーザー一覧ページのパラメータに `followings` を追加し、フォローしているユーザー一覧を見られるようにした
- ユーザー一覧ページのサブタイトルを絞り込みパラメータに合わせるようにした
    - ユーザー一覧 (9) より 現役生 (9) のほうがわかりやすいと思ったため
- ユーザー一覧ページの絞り込みがゼロ件だった場合にメッセージを表示するようにした
    - 質問・雑談タイムで machida さんからメッセージがあったほうがいいとアドバイスいただいたため
- フォロー中のユーザーの日報が投稿されると、通知が送られるようにした
- フォロー中のユーザーの日報が投稿された後、Watch中 にするようにした

# やらなかったこと
- フォローされたこと、フォロー解除されたことが分かる機能
    - フォロー・フォロー解除で通知は送られないことを要件としたため
- 誰が誰をフォローしているか分かる機能
    - 分からないようにすることを要件としたため
- 上記の内容を分かりやすくする機能
    - 現状どこにもその内容は書いていないので、Merge後にdocsを書く予定

# スクリーンショット（町田さん確認前）
## ユーザーページ ( `/users/:id` )に「日報をフォローする」「フォロー解除する」ボタンを追加
### before
<img src="https://user-images.githubusercontent.com/52617472/96346830-dbb53b80-10d8-11eb-8125-11059197a257.png" width=300px>

### after
<img src="https://user-images.githubusercontent.com/52617472/96343993-0604fa00-10d5-11eb-8f9f-10c5e22d6752.png" width=300px>

## ユーザーページ ( `/users/:current_user.id` ) に「フォロー一覧を見る」ボタンを追加
### before
<img src="https://user-images.githubusercontent.com/52617472/96346559-57ae8400-10d7-11eb-8c60-b07843692a16.png" width=300px>

### after
<img src="https://user-images.githubusercontent.com/52617472/96344303-1d43e780-10d5-11eb-84ae-4e7f4fe448ca.png" width=300px>

## ユーザー一覧ページ ( `/users` ) に「日報をフォローする」「フォロー解除する」ボタンを追加
### before
![image](https://user-images.githubusercontent.com/52617472/96346595-9a705c00-10d7-11eb-966a-ae41acf41db5.png)

### after
![image](https://user-images.githubusercontent.com/52617472/96344717-3b114c80-10d5-11eb-985f-77e6ab253a8e.png)

## ユーザー一覧ページのサブタイトルを絞り込みパラメータに合わせるようにした
### before
<img src="https://user-images.githubusercontent.com/52617472/96346758-68132e80-10d8-11eb-8b20-6a3108460cb6.png" width=200px>

### after
<img src="https://user-images.githubusercontent.com/52617472/96345703-8e839a80-10d5-11eb-9d09-d1e19c3c1a2a.png" width=200px>

## ユーザー一覧ページのパラメータに `followings` を追加し、フォローしているユーザー一覧を見られるようにした
### before
![image](https://user-images.githubusercontent.com/52617472/96346659-fc30c600-10d7-11eb-81e1-74864d2eb818.png)

### after
![image](https://user-images.githubusercontent.com/52617472/96345494-7b70ca80-10d5-11eb-8260-ed768f50a107.png)

## ユーザー一覧ページの絞り込みがゼロ件だった場合にメッセージを表示するようにした
### before
![image](https://user-images.githubusercontent.com/52617472/96346677-110d5980-10d8-11eb-8d25-481c6024dbff.png)

### after
![image](https://user-images.githubusercontent.com/52617472/96346274-bc68df00-10d5-11eb-8447-b7078bddd2eb.png)

## フォロー中のユーザーの日報が投稿されると、通知が送られるようにした
<img src="https://user-images.githubusercontent.com/52617472/96346306-f1753180-10d5-11eb-82a5-78067fa3ac97.png" width=300px>

![image](https://user-images.githubusercontent.com/52617472/96346333-28e3de00-10d6-11eb-893f-3146358114d3.png)

## フォロー中のユーザーの日報が投稿された後、Watch中 にするようにした
<img src="https://user-images.githubusercontent.com/52617472/96346352-4fa21480-10d6-11eb-9e17-0a257877e20e.png" width=300px>

<img src="https://user-images.githubusercontent.com/52617472/96346378-706a6a00-10d6-11eb-8a15-e91f8dcf960a.png" width=300px>

![image](https://user-images.githubusercontent.com/52617472/96346388-81b37680-10d6-11eb-9e4e-6893d64ba9f1.png)

2020-10-17 15:39 UTC, ima1zumi commented
@machida 
仮でデザイン入れています。ご確認お願いします 🙏

2020-10-30 08:21 UTC, machida approved these changes
@ima1zumi @komagata デザイン入れました！！

- [x] リリース前にフォロー機能の詳細をここに書く https://bootcamp.fjord.jp/pages/303
- [ ] リリース後にお知らせからフォロー機能の告知をする

をしたいと思います。

2020-10-30 08:21 UTC, machida commented
コンフリクト修正します。

2020-10-30 08:24 UTC, machida commented
@komagata 一通り作業が完了したので、レビューお願いします。

2020-10-30 11:58 UTC, ima1zumi commented
@machida 
デザインありがとうございます！！ 😍 

@komagata 
テスト落ちてるので修正します〜

2020-10-30 14:08 UTC, ima1zumi commented
@komagata 
テスト修正しました 😄  レビューお願いします。

2020-11-01 10:26 UTC, komagata requested changes

2020-11-01 10:26 UTC, komagata commented on app/models/report_callbacks.rb
> +    end
これはやってること、コード量も変わってないのでメソッドを作らなくてもいいと思います〜

2020-11-07 13:54 UTC, ima1zumi commented on app/models/report_callbacks.rb
> +    end
修正しました〜 https://github.com/fjordllc/bootcamp/pull/2015/commits/1a3be8a771422aeebed4559a1a1a8b85fea44926

2020-11-08 06:23 UTC, komagata requested changes

2020-11-08 06:23 UTC, komagata commented on test/fixtures/followings.yml
> +following_01:
他のfixturesは01とかじゃなくて1だったと思うので（2桁が最大とは限らないので）、合わせた方が良さそうです〜

2020-11-08 06:23 UTC, komagata commented on test/models/following_test.rb
> +  test "should be valid" do
これらはActiveRecordの機能のテストになるので、独自のメソッドがモデルになければテストなくて大丈夫です。

2020-11-08 06:23 UTC, komagata commented on test/models/user_test.rb
> +  test "#follow" do
👍

2020-11-08 12:30 UTC, ima1zumi commented on test/models/following_test.rb
> +  test "should be valid" do
そうですね 💦  削除しました。

2020-11-08 12:30 UTC, ima1zumi commented on test/fixtures/followings.yml
> +following_01:
修正しました。

2020-11-09 07:41 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-09 07:41 UTC, merged