誰でもお知らせを作成できるようにする
fjordllc/bootcamp pull request #2016
Opened 2020-10-17 15:43 UTC by KishiKyousuke

ref #1957 

## 概要
### WIPの実装
- WIP機能を実装しました
- WIPのボタン下部に公開までの手順を記述しました（要デザイン）

受講生の画面
![image](https://user-images.githubusercontent.com/59789739/96347008-dc9a9d00-10d9-11eb-84a2-328101da466f.png)

メンターの画面
![image](https://user-images.githubusercontent.com/59789739/96347154-a578bb80-10da-11eb-886d-0fa9a775f453.png)

2020-10-17 15:53 UTC, KishiKyousuke commented
@machida 
WIPボタン下部の公開手順のデザインをよろしくお願いいたします🙇🏻‍♂️

2020-10-30 05:26 UTC, machida commented
![image](https://user-images.githubusercontent.com/168265/97662887-8d7e4000-1abb-11eb-925d-465f71f785ef.png)

デザイン入れました！

2020-10-30 06:20 UTC, KishiKyousuke commented
@komagata 
レビューをお願いいたします❗

2020-11-01 10:19 UTC, komagata requested changes
既存のお知らせを更新すると必ず通知が飛んでしまう状況だと思うので、既存のお知らせにpublished_atの値を入れるようなrake taskを作る必要があると思います。

2020-11-01 10:19 UTC, komagata commented on app/models/announcement_callbacks.rb
> +    if announce.wip == false && announce.published_at.nil?
rubyの式は必ずtrue, falseどちらかの値を取るので条件式にtrue, falseが来ることはないのでぱっと見違和感を感じちゃいます。

2020-11-02 06:52 UTC, KishiKyousuke commented
@komagata 
ご指摘ありがとうございます❗
既存のお知らせのpublished_atカラムが空になってしまう点に関しては完全に盲点でした…💦
条件式の書き方についても、単純に`!announce.wip`とすればいいだけですね😅
修正いたします❗

2020-11-02 08:59 UTC, KishiKyousuke commented
@komagata 
rakeタスクの置き場に関してですが、以下のファイルの`namespace :oneshot`下に書くべきでしょうか❓

https://github.com/fjordllc/bootcamp/blob/defb51251b9d018dca2d66417f341d88bf0b108b/lib/tasks/bootcamp.rake#L11

またoneshotのrakeタスクの実行タイミングはどの様になっているのでしょうか❓
今回作成するタスクは一度実行してしまえばOKだと思いますが、そういったタスクは手動で実行されているのでしょうか❓
お教えいただけると幸いです❗

2020-11-03 11:41 UTC, komagata commented
@KishiKyousuke `bootcamp:oneshot:cloudbuild`というタスクをCloud Buildから手動で実行しますのでこの名前でタスクを作ってください。

https://github.com/fjordllc/bootcamp/blob/master/cloudbuild-task.yaml#L26

2020-11-03 15:39 UTC, KishiKyousuke commented
@komagata 
該当箇所の修正及び、Rakeタスクの追加を行いました。
レビューをお願いいたします❗🙇🏻‍♂️

2020-11-04 00:13 UTC, bluerabbit commented on db/migrate/20201016130005_add_columns_to_announcements.rb
> +    add_column :announcements, :published_at, :datetime
下記のように書くとmigration時間が短縮できます。

```ruby
  change_table :announcements, bulk: true do |t|
    t.boolean :wip, default: false, null: false
    t.datetime :published_at
  end
```

https://www.google.com/search?q=migration+bulk+rails

次のrubocopで下記の設定をするとチェックできます。
https://www.rubydoc.info/gems/rubocop/0.61.1/RuboCop/Cop/Rails/BulkChangeTable

2020-11-04 00:14 UTC, bluerabbit commented on lib/tasks/bootcamp.rake
> +      Announcement.where(published_at: nil, wip: false).update_all(published_at: Time.current)
```suggestion
      Announcement.where(published_at: nil, wip: false).update_all(published_at: Time.current, updated_at: Time.current)
```

update_allはupdated_atが自動で更新されないので手動で設定する必要があります。

2020-11-04 04:51 UTC, komagata commented on lib/tasks/bootcamp.rake
> +      Announcement.where(published_at: nil, wip: false).update_all(published_at: Time.current)
@bluerabbit おお、確かにですね。ただ今回はupdated_atが更新されない方が都合がいいのでこのままで良さそうです。

2020-11-04 05:13 UTC, bluerabbit commented on lib/tasks/bootcamp.rake
> +    task :cloudbuild do
https://github.com/fjordllc/bootcamp/pull/2016/files#diff-d95b45bc08a0e95b77326b739f8fb94bf1e4cd7b18949e676437ff2796e65ea3R37-R42

ココ消さないといけないです。

2020-11-04 05:55 UTC, KishiKyousuke commented on lib/tasks/bootcamp.rake
> +    task :cloudbuild do
こちらは同名のタスクを２つ作るのではなく、上の`:cloudbuild`タスクの中にそのまま実行したいコードを書くという形で良いということでしょうか❓

2020-11-04 05:58 UTC, komagata commented on lib/tasks/bootcamp.rake
> +    task :cloudbuild do
はい、そうなります。

2020-11-04 07:54 UTC, KishiKyousuke commented
@komagata 
Rakeタスクの定義場所を修正いたしました。
ご確認をよろしくお願いいたします❗

2020-11-04 11:46 UTC, KishiKyousuke commented
@komagata
ご指摘いただいた点を修正いたしました。
ご確認よろしくお願いいたします🙇🏻‍♂️

2020-11-26 07:14 UTC, machida commented
@KishiKyousuke コンフリクトの解消をお願いしますー

2020-11-27 02:27 UTC, KishiKyousuke commented
@machida @komagata 
コンフリクトの解消を行いました。
ご確認よろしくお願いいたします❗

2020-11-30 10:46 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-30 10:46 UTC, merged

2020-12-02 05:15 UTC, KishiKyousuke commented
Slackに通知が行ってしまっているので修正いたします。