Q&A内のコメント欄でも大名エンジニア参加生のアイコンが黄緑色になるように実装
fjordllc/bootcamp pull request #2028
Opened 2020-10-20 07:53 UTC by KishiKyousuke

ref #2006 

# 概要

2020-10-20 08:36 UTC, KishiKyousuke commented
@komagata @machida 
レビューをお願いいたします❗🙇🏻‍♂️

2020-10-21 08:19 UTC, komagata requested changes

2020-10-21 08:19 UTC, komagata commented on app/javascript/answer.vue
> +    roleClass: function() {
なぜここ名前を変えたんでしょう？（機能は変わってないようなので）

2020-10-21 08:19 UTC, komagata commented on db/schema.rb
> +    t.boolean "wip", default: false, null: false
migrationファイルがないのにschemaファイルだけ変更されているのはおかしいように思います。

2020-10-21 08:29 UTC, KishiKyousuke commented on app/javascript/answer.vue
> +    roleClass: function() {
https://github.com/fjordllc/bootcamp/blob/243d367ad8cc2f45183db16740943c214d6d8994/app/javascript/comment.vue#L8
同様の実装が記述されている`comment.vue`のメソッド名に合わせました。
メソッド名は変更しないほうがよろしいでしょうか❓

2020-10-21 08:30 UTC, KishiKyousuke commented on db/schema.rb
> +    t.boolean "wip", default: false, null: false
@komagata
こちら修正いたします❗
ご指摘ありがとうございます🙇🏻‍♂️

2020-10-21 13:40 UTC, komagata requested changes

2020-10-21 13:40 UTC, komagata commented on app/javascript/answer.vue
> +    roleClass: function() {
理由がわかれば大丈夫です。

computedメソッドはキャッシュされるので処理が早く、引数を持たないならcomputedメソッドの方が望ましいです。

2020-10-22 02:39 UTC, KishiKyousuke commented
@komagata 
不要なコードが含まれていたため、修正いたしました。
ご確認よろしくお願いいたします🙇🏻‍♂️

2020-10-24 05:42 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-24 05:42 UTC, merged