企業一覧ページを作成
fjordllc/bootcamp pull request #2074
Opened 2020-11-06 16:37 UTC by masuyama13

Ref: #2049

## 概要

企業一覧ページを作成し、ヘッダーのMenuに「企業一覧」リンクを追加しました。
ページャーはつけていません。

## 表示（デザイン未）

<img width="910" alt="Skitch_2020-11-07_at_1_27_28" src="https://user-images.githubusercontent.com/58389623/98391182-a6798900-2099-11eb-88cf-1e48adc3a6b8.png">

2020-11-07 03:12 UTC, masuyama13 commented
@komagata デザイン前ですが、先にレビューをお願いします。

2020-11-08 06:17 UTC, komagata requested changes

2020-11-08 06:17 UTC, komagata commented on app/views/companies/_company.html.slim
> +      - if company.website.present?
```suggestion
      - if company.website?
```

2020-11-08 15:52 UTC, masuyama13 commented on app/views/companies/_company.html.slim
> +      - if company.website.present?
クエリメソッド知りませんでした！:eyes:
ありがとうございます。
if文の位置がおかしかったので、あわせて修正しました。

2020-11-09 07:49 UTC, komagata requested changes

2020-11-09 07:49 UTC, komagata commented on config/routes.rb
>    resources :companies, only: %i(show) do
これって`resources :companies, only: %i(show index) do`じゃダメですかね？

2020-11-09 16:57 UTC, masuyama13 commented on config/routes.rb
>    resources :companies, only: %i(show) do
問題なかったので修正しました！

2020-11-10 05:22 UTC, komagata requested changes

2020-11-10 05:22 UTC, komagata commented on app/views/companies/_company.html.slim
> +            = link_to company_path(company.id) do
```suggestion
            = link_to company do
```

2020-11-10 05:22 UTC, komagata commented on app/views/companies/_company.html.slim
> +              = link_to company.name, company_path(company.id)
```suggestion
              = link_to company.name, company
```

2020-11-10 15:47 UTC, masuyama13 commented on app/views/companies/_company.html.slim
> +            = link_to company_path(company.id) do
修正しました。

2020-11-10 15:47 UTC, masuyama13 commented on app/views/companies/_company.html.slim
> +              = link_to company.name, company_path(company.id)
ありがとうございます。
修正しました。

2020-11-15 12:50 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-15 13:37 UTC, masuyama13 commented
ありがとうございます！

@machida 
こちら、デザインをよろしくお願いします:pray:
今は企業詳細ページのプロフィール（companies/profile）と同じデザインにしてあります。

2020-11-25 07:23 UTC, machida commented
@masuyama13 デザイン入れましたー

2020-11-27 14:38 UTC, masuyama13 commented
@machida 
確認が遅くなりすみません。
デザインありがとうございます！
テストを修正します。

2020-11-29 12:03 UTC, masuyama13 commented
@komagata 
テストを修正しましたので、マージお願いします。

2020-11-30 10:43 UTC, merged

2020-11-30 10:43 UTC, komagata commented
@masuyama13 マージしました〜