userモデルにメール配信停止用TOKENのカラムを追加
fjordllc/bootcamp pull request #2078
Opened 2020-11-09 07:18 UTC by hogucc

2020-11-09 08:43 UTC, hogucc commented
@komagata 
コードレビュー前に確認したいことがあり、ご連絡させていただきました。
回答次第ではコードが大幅に変更になる可能性があるので今のタイミングで質問させていただいていますが、コードを見たほうが判断しやすいということであれば、その旨ご連絡いただければと思います🙇‍♀️

1. メール配信停止のURLのHTTPメソッド
メール配信停止のリクエストはUserテーブルのmail_notificationカラムを更新するのでPATCHでリクエストしようとしていました。
が、メールに含まれるリンクは通常GETのリクエストしか送信できないことがわかりました。
更新のリクエストでGETというのは違和感あるのですが、代替手段が思い浮かびませんでした...
GETでリクエストして問題ないか駒形さんのご意見を伺いたいです。
以下、参考にしたRailsガイドのURLです。
https://railsguides.jp/action_mailer_basics.html#%E5%90%8D%E5%89%8D%E4%BB%98%E3%81%8D%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%A7url%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B

1. Userテーブルのunsubscribe_email_tokenカラムの値追加
Userテーブルにメール配信停止のリンクで使用するunsubscribe_email_tokenカラムを追加しました。
このカラムに値を追加するためのrake taskを作成したのですが、タスクを実行するタイミングに悩んでいます。
いまはapplication_controllerのbefore_actionでタスクを実行するように実装しています。
が、これだとアクションを実行するたびにUserテーブルの全レコードを参照するので影響範囲が広く、無駄な参照が発生します。
メールを送る直前での実行も考えたのですが、複数人が同時にメールを送る処理を実行した場合は後勝ちになって先に送ったほうのリンクが機能しなくなると思い、やめました。
最適なタイミングが思い浮かばず悩んでおり、駒形さんのご意見を伺いたいです。

2020-11-10 05:16 UTC, komagata commented
@hogucc 

> 1

メールからのリンクなのでGETでやっちゃっていいと思います。

> 2

rake taskとして実装して、デプロイ時に手動で実行（僕がやります）でいいと思います。

rake taskの実装方法を下記に書いておきました〜。

[Rake Taskの実装方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/Rake-Task%E3%81%AE%E5%AE%9F%E8%A3%85%E6%96%B9%E6%B3%95)

2020-11-10 05:40 UTC, hogucc commented
@komagata 
> メールからのリンクなのでGETでやっちゃっていいと思います。
承知しました！

> rake taskとして実装して、デプロイ時に手動で実行（僕がやります）でいいと思います。
デプロイ時に手動実行とのこと、承知しました。Wikiへの実装方法の記載ありがとうございます！
今の実装だと新規のnamespaceを切ってしまったので、`bootcamp:oneshot:cloudbuild`の中に処理を書きます。
これから新規作成されるユーザーに対してはUserControllerのcreateアクション実行時にtokenを発行してカラムに保存する必要があると考えていますが、その認識で合っていますか？

2020-11-11 06:19 UTC, komagata commented
@hogucc はい、認識あっています。ただ、bootcampではcallbackを多用してるのでcallbackでtokenを作成するようにするのが良さそうです。

2020-11-11 07:14 UTC, hogucc commented
@komagata 
承知しました！callbackで実装します。

2020-11-11 13:42 UTC, hogucc commented
@komagata 
デザイン前ですが、先にコードレビューをお願いいたします🙇‍♀️
現時点でschema.rbがmasterとconflictしているのですが、conflict時の運用等何か決まりありますでしょうか？
特に無ければ修正を行います。

2020-11-12 00:24 UTC, bluerabbit commented on app/controllers/mail_notification_controller.rb
> +    user = User.where(unsubscribe_email_token: params[:token]).first
```suggestion
    user = User.find_by(unsubscribe_email_token: params[:token])
```

と書けますね

2020-11-12 03:16 UTC, komagata commented
@hogucc 

> conflict時の運用等何か決まりありますでしょうか？

特にないので修正しちゃって大丈夫です。

2020-11-12 10:32 UTC, hogucc commented on app/controllers/mail_notification_controller.rb
> +    user = User.where(unsubscribe_email_token: params[:token]).first
@bluerabbit 
ご確認ありがとうございます！find_byに修正しました。
userがnilの場合は、以下commitにてログインページへリダイレクトするように修正しました。
b865b5b

2020-11-13 03:07 UTC, komagata requested changes
最新のmasterを取り込むのにmergeコミットができてしまっているので、できないようにrebaseを使うようにしてください〜。

2020-11-14 14:16 UTC, hogucc commented
@komagata 
masterブランチとの差異が多く、rebase後にpushしたら変更履歴が大量発生したのと、commitログがおかしい（ユーザー一覧に企業のロゴマークをつけるのコミットがコミット番号は別で二つ発生している）のですが、こちら別のブランチをmasterから作ってPR出し直したほうが良いでしょうか？💦

2020-11-16 05:25 UTC, komagata commented
@hogucc conflictの修正お願いします。

2020-11-16 07:52 UTC, hogucc commented
@komagata 
すみません、ローカルのmasterブランチが最新になっていなかったせいで余計なconflictが発生していたようです💦
conflictは解消しましたので、改めてレビューをお願いいたします🙇‍♀️

2020-11-17 13:49 UTC, komagata requested changes

2020-11-17 13:49 UTC, komagata commented on app/controllers/mail_notification_controller.rb
> +    render :show
一般的にupdateは何も表示しないのでどこかにredirectするのが良いと思います。

2020-11-17 13:49 UTC, komagata commented on app/views/notification_mailer/_notification_mailer_template.html.erb
> +              <%= link_to "メールでの通知オフはこちらから", user_mail_notification_url(@user, token: @user.unsubscribe_email_token), style: "color:#4638a0; font-family: sans-serif; font-size:14px; font-weight:bold;
:+1:

2020-11-17 13:49 UTC, komagata commented on lib/tasks/bootcamp.rake
> +      User.find_each do |user|
1つの処理で複数SQLを発行することになるのでTransactionを使った方が良さそうです。

2020-11-18 00:34 UTC, bluerabbit commented on app/controllers/mail_notification_controller.rb
> +    render :show
PRGパターンというのがあります

PostしたらRedirectでGetしましょうという話です。
ブラウザリロード(F5)で二重登録とかしてしまうのを避けるためです

ぐぐったらコレがヒットしました。参考までに
https://qiita.com/furi/items/a32c106e9d7c4418fc9d

2020-11-18 04:02 UTC, hogucc commented on app/controllers/mail_notification_controller.rb
> +    render :show
@bluerabbit 
参考情報ありがとうございます！
おっしゃるとおり二重登録を防ぐためにはRedirectでGetしないとだめですね💦 修正します！

2020-11-18 06:09 UTC, hogucc commented on app/controllers/mail_notification_controller.rb
> +    render :show
トップページにリダイレクトするように修正しました
04b13db

2020-11-18 06:09 UTC, hogucc commented on lib/tasks/bootcamp.rake
> +      User.find_each do |user|
Transactionを使うように修正しました。
d433aaf

2020-11-18 06:16 UTC, hogucc commented
@komagata 
ご指摘点の修正を行いました。
加えて、メール配信停止処理でユーザー情報が取得できなかったときに画面に表示するメッセージを「ログインしてください」から「メール配信停止にはTOKENが必要です。」に変更しました。
（ログインしている場合でもTOKENが設定されていないとユーザー情報が取得できない為）
以下コミットにて修正しています。
e3db889

再度レビューお願いいたします🙇‍♀️

2020-11-22 11:11 UTC, komagata requested changes

2020-11-22 11:11 UTC, komagata commented on app/controllers/mail_notification_controller.rb
> +    end
絶対違うわけではないですが、returnを使わなくて済むように if … else … end で書いた方がいいかもです。

2020-11-22 11:11 UTC, komagata commented on lib/tasks/bootcamp.rake
> +        User.find_each do |user|
unsubscribe_email_tokenがnilのものだけをとってくればifが要らなくなりそうです。

2020-11-24 04:43 UTC, hogucc commented on app/controllers/mail_notification_controller.rb
> +    end
if … else … endに修正しました
f50b118

2020-11-24 04:48 UTC, hogucc commented on lib/tasks/bootcamp.rake
> +        User.find_each do |user|
unsubscribe_email_tokenがnilのデータを取得するように修正し、data-migrate gemに移行しました。
3523622
f66e594

2020-11-24 08:56 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-24 08:56 UTC, komagata commented on db/data/20201124023746_add_unsubscribe_email_token.rb
> +class AddUnsubscribeEmailToken < ActiveRecord::Migration[6.0]
👍

2020-11-24 10:01 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-24 10:01 UTC, merged

2020-11-24 10:38 UTC, komagata commented
@hogucc data-migrateが下記のエラーで落ちているようです。おそらくsaveをvalidationなしでやるようにすればいいと思います。

こちらのPRはすでにマージ済みなので別PRで修正いただけるとありがたいです！

```
Already have image: asia.gcr.io/bootcamp-224405/bootcamp:d6694bfc48323cade1b89c100084beca2503d58b
Database 'bootcamp_production' already exists
== Schema =====================================================================
== 20201104093315 AddUnsubscribeEmailTokenToUsers: migrating ==================
-- add_column(:users, :unsubscribe_email_token, :string)
   -> 55.3300s
== 20201104093315 AddUnsubscribeEmailTokenToUsers: migrated (55.3301s) ========

== Data =======================================================================
== 20201124023746 AddUnsubscribeEmailToken: migrating =========================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

バリデーションに失敗しました: 名前（カナ）を入力してください, 職業を入力してください, 利用OSを入力してください, プログラミング経験を入力してください
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/validations.rb:53:in `save!'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:318:in `block in save!'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:318:in `save!'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/suppressor.rb:48:in `save!'
/workspace/db/data/20201124023746_add_unsubscribe_email_token.rb:8:in `block (2 levels) in up'
```

2020-11-24 12:14 UTC, hogucc commented
@komagata 
承知しました！後ほどPRを作成します。