ユーザー一覧にページング処理を追加 #2066
fjordllc/bootcamp pull request #2090
Opened 2020-11-11 10:19 UTC by Chi-rr

ref: #2066
usersの各ページにページング処理を追加しました。
20件でページングしています。

2020-11-12 03:07 UTC, komagata requested changes

2020-11-12 03:07 UTC, komagata commented on app/controllers/users_controller.rb
> +        .page(params[:page]).per(20)
magic numberになってしまうので定数か何かを使いたいですね。

2020-11-12 11:09 UTC, Chi-rr commented on app/controllers/users_controller.rb
> +        .page(params[:page]).per(20)
@komagata 
ご指摘いただいた箇所の修正(fe18354)、また
ページング処理後のユーザー数の取得ができていなかったので対応しました(1300b94)

ご確認よろしくお願いします！

2020-11-13 03:09 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-13 03:09 UTC, merged