メンター・アドバイザーでないユーザーは就活中のユーザーのタブを非表示に変更
fjordllc/bootcamp pull request #2093
Opened 2020-11-12 07:22 UTC by MashioSano

#2080  の作業です。
メンター・アドバイザーでないユーザーは就活中のユーザーのタブを非表示に変更しました。

変更前
<img width="1084" alt="スクリーンショット 2020-11-12 16 17 34" src="https://user-images.githubusercontent.com/52710925/98907806-c4fcdb80-2502-11eb-8cc2-2cbc1d5ee799.png">

変更後
<img width="1089" alt="スクリーンショット 2020-11-12 16 16 29" src="https://user-images.githubusercontent.com/52710925/98907782-bc0c0a00-2502-11eb-9238-ccd715857e0c.png">

2020-11-13 03:03 UTC, komagata requested changes

2020-11-13 03:03 UTC, komagata commented on app/views/users/_nav.html.slim
> +        - %w(student_and_trainee followings job_seeking mentor graduate adviser trainee all).each do |target|
やりたいことは就活中のユーザータブを非表示ですが、無関係の重複コードが多いようなのでそこを改善したいですね。

2020-11-13 08:09 UTC, MashioSano commented on app/views/users/_nav.html.slim
> +        - %w(student_and_trainee followings job_seeking mentor graduate adviser trainee all).each do |target|
@komagata 
重複していたコードをまとめました。
ご確認のほどよろしくお願いいたします。🙇‍♂️

2020-11-15 12:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-15 12:52 UTC, merged