日報・提出物・イベントnoWatch
fjordllc/bootcamp pull request #2104
Opened 2020-11-14 13:37 UTC by masuyama13

2020-11-22 10:52 UTC, komagata requested changes

2020-11-22 10:52 UTC, komagata commented on app/models/comment_callbacks.rb
> +      if comment.sender != comment.receiver
これだとWatchしてなくてもコメント通知が来るということにならないですかね？

2020-11-22 10:52 UTC, komagata commented on lib/tasks/bootcamp.rake
> +      Report.includes(:user, :watches).each do |report|
中途半端に実行されて止まった場合困るのでTransactionを使った方が良さそうです。

2020-11-22 15:51 UTC, masuyama13 commented on lib/tasks/bootcamp.rake
>        pages.each { |page| page.update(published_at: page.updated_at) }
@komagata 

> 中途半端に実行されて止まった場合困るのでTransactionを使った方が良さそうです。

ありがとうございます。トランザクションを入れます。
1点教えてください。
この rake task は一度だけ実行するものだと思うので、pullで取り込んだ部分（51〜52行目）は私が削除してよいのでしょうか？

2020-11-22 17:41 UTC, komagata commented on lib/tasks/bootcamp.rake
>        pages.each { |page| page.update(published_at: page.updated_at) }
@masuyama13 はい、もう不要な部分は削除してください。

2020-11-23 10:06 UTC, masuyama13 commented on app/models/comment_callbacks.rb
> +      if comment.sender != comment.receiver
@komagata 
はい。
コメント先が日報、提出物、イベント（Report, Product, Eventクラス）以外の場合は、これまで通りコメント通知がくるようにしています。
お知らせ（Announcementクラス）とDocs（Pageクラス）はWatchができないためです。
コードの変更を最小限にしようとしてこのような書き方にしていました。

Watch可能かどうかで分岐していることがわかりやすいように、書き直してみました。

2020-11-24 08:45 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-24 08:45 UTC, komagata commented on app/models/comment_callbacks.rb
> +      if comment.sender != comment.receiver
なるほどですね！

2020-11-24 08:45 UTC, merged

2020-11-24 09:51 UTC, komagata commented on lib/tasks/bootcamp.rake
> +      ActiveRecord::Base.transaction do
@masuyama13 ここの実行が14分以上かかっててタイムアウトしているようです。もう一度実行してみます。

2020-11-24 10:40 UTC, komagata commented on lib/tasks/bootcamp.rake
> +      ActiveRecord::Base.transaction do
@masuyama13 再度実行してみても20分ほどかかりタイムアウトしているようです。

現状のコードですとreportのレコード数分(20633回)SQLが発行されていて遅いのでBULK INSERTを試してみてください。

このPRはマージ済なので別PRを作成していただけるとありがたいです。

2020-11-24 10:50 UTC, masuyama13 commented on lib/tasks/bootcamp.rake
> +      ActiveRecord::Base.transaction do
@komagata 
承知しました！