ユーザーハッシュタグ機能
fjordllc/bootcamp pull request #2128
Opened 2020-11-18 06:59 UTC by takopom

Ref: #1979

2020-12-01 16:52 UTC, takopom commented
@komagata ユーザ一覧に競合があったので修正しました💦レビューをお願いいたします🙇‍♀️

2020-12-02 06:05 UTC, takopom commented
@komagata @ima1zumi 先ほどのMTGでお話があった、レビューを駒形さん以外のどなたかにお願いする流れを、このPRで行わせていただいてもよいでしょうか？👀　もしよろしければ、お願いしたいと思います。

2020-12-02 06:11 UTC, ima1zumi commented
@takopom 
早速ありがとうございます！確認します 😄

2020-12-02 06:17 UTC, takopom commented
@ima1zumi こちらこそ、引き受けてくださってありがとうございます🙏✨　よろしくお願いいたします！

2020-12-08 14:53 UTC, ima1zumi requested changes
確認しました〜遅くなってすみません 🙇‍♂️

`app/javascript/tags.vue` は `users_tag.vue` だけから使われる想定でしょうか？
もしそうであれば、user 向けに作ってあることが分かる名前になっているといいかな？と思いました。

2020-12-08 15:11 UTC, ima1zumi commented
このPRに限った話ではないのですが 🤔 
レビューしていて、タグ系の vue で重複が多くなってきているのが気になりました。
`uses_tags.vue` の `<style>` などは他の `*_tags.vue` と共通化できそうです。

スコープ外なので修正は必要ない（やるなら別でissue立てたりPR作ったりしたほうがよさそう）のですが、気になったのでコメントだけ残しておきます。

2020-12-09 00:35 UTC, takopom commented
@ima1zumi ご確認ありがとうございます！🙏✨

> app/javascript/tags.vue は users_tag.vue だけから使われる想定でしょうか？

> タグ系の vue で重複が多くなってきているのが気になりました。

今回ユーザータグを実装してみて、他のタグ系とほぼ同じ実装になることがわかったので、ユーザータグ以外からも共通して使える部品を用意したいと思い`tags.vue`を作りました。

> やるなら別でissue立てたりPR作ったりしたほうがよさそう

そうですね…！！このPRではユーザータグにのみフォーカスして、別で共通化対応する流れの方がよかったですね。
共通化したい気持ちがこのPRに混ざってしまいました💦

2020-12-09 00:38 UTC, takopom commented on app/controllers/users_controller.rb
> +        .preload(:course)
ご指摘ありがとうございます！確認して修正いたします。

2020-12-09 00:48 UTC, takopom commented on app/models/user.rb
> +    in_school.unretired
> scope の名前を変えるか、もしくはこれくらい短ければ scope に切らなくてもいい

この2点でとても悩んだ箇所でした…！！やっぱり迷いが実装に表れますね💦

> 現役生だけの絞り込み

現役の生徒だけでなくメンターも含めたいと思ったことと、
コントローラー側にSQLに関する記述が出すぎるかな？と少し気になったので、
今回新しく`scope`を切ったのでした。

いずれにせよ、名前はいけてないですね…！考え直します！

2020-12-09 03:03 UTC, ima1zumi commented
> @ima1zumi ご確認ありがとうございます！🙏✨
> 
> > app/javascript/tags.vue は users_tag.vue だけから使われる想定でしょうか？
> 
> > タグ系の vue で重複が多くなってきているのが気になりました。
> 
> 今回ユーザータグを実装してみて、他のタグ系とほぼ同じ実装になることがわかったので、ユーザータグ以外からも共通して使える部品を用意したいと思い`tags.vue`を作りました。
> 
> > やるなら別でissue立てたりPR作ったりしたほうがよさそう
> 
> そうですね…！！このPRではユーザータグにのみフォーカスして、別で共通化対応する流れの方がよかったですね。
> 共通化したい気持ちがこのPRに混ざってしまいました💦

なるほど！！そういう意図であれば、無理に消したり名前変えたりする必要はないと思います。ありがとうございます 😄

2020-12-11 03:09 UTC, takopom commented on app/controllers/users_controller.rb
> +        .preload(:course)
こちら対応いたしました！🙇‍♀️

2020-12-11 03:11 UTC, takopom commented on app/models/user.rb
> +    in_school.unretired
`scope`に切らない方向で修正しました。短いので不要だったと思いました…！
ご確認いただけると幸いです。

2020-12-11 03:13 UTC, takopom commented
@ima1zumi 再度レビューしていただけると幸いです。よろしくお願いいたします🙏

2020-12-11 04:43 UTC, ima1zumi reviewed
ありがとうございます！修正いただいた箇所確認しました 🙆‍♂️ 
1点追加で、

https://github.com/fjordllc/bootcamp/blob/5f48296b9f6323324d3b438629a02d13a8d2bede/app/controllers/users_controller.rb#L36

ここにも `:taggings` を追加していただきたいです！
`/users` でアクセスするとここを通るのですが、その際に `tag` の情報も取ってくるので `preload` に含んでおくとよいと思ったためです。

ちなみに N+1 が発生しているかどうかは、development 環境で起動したときに左下に出てくるメッセージで分かります（Bullet というgemが出しています）
N+1になっていそうなクエリがあると出力されているみたいです。
![image](https://user-images.githubusercontent.com/52617472/101862912-7fd9d100-3bb6-11eb-8412-72f48c2349a7.png)

2020-12-11 06:39 UTC, takopom commented
ご確認ありがとうございます！抜けていた箇所にも追加しました💦
フォロー中の一覧でも発生していたため、そちらにも追加しました。

> ちなみに N+1 が発生しているかどうかは、development 環境で起動したときに左下に出てくるメッセージで分かります（Bullet というgemが出しています）

この表示はそのような意味があったのですね…！！情報ありがとうございます！🙏

2020-12-11 06:49 UTC, ima1zumi approved these changes

2020-12-11 06:50 UTC, ima1zumi commented
ありがとうございます〜！確認しました！

2020-12-11 07:14 UTC, takopom commented
@ima1zumi ご確認ありがとうございました！✨
@komagata レビューをお願いいたします！🙏

2020-12-11 08:39 UTC, komagata approved these changes
tag部分を共通化できたのが素晴らしいっすね。OKですー！

2020-12-12 01:47 UTC, takopom commented
@machida デザインをお願いいたします！🙇‍♀️

2021-01-04 05:42 UTC, machida commented
@takopom デザイン入れましたー ちょっとだけなのですが、全体的に他のコンテンツのtagもいじったので、念のため確認していただきたいです🙏

2021-01-04 07:04 UTC, takopom commented
@machida デザインのご対応ありがとうございます！🙏✨

> 他のコンテンツのtag

Q&AとDocsについて、タグ表示に問題が無いことを確認いたしました。

2021-01-05 06:20 UTC, komagata commented
@takopom テストが落ちてるみたいです〜

2021-01-06 00:35 UTC, takopom commented
@komagata 最新のmasterを反映し、テストが通るようになりました！🙇‍♀️

2021-01-06 06:41 UTC, komagata commented
> Merge branch 'master' into user-tags

不要なマージコミットができているようです。rebaseすればマージコミットはできないので修正お願いします〜

2021-01-07 06:59 UTC, takopom commented
@komagata ご指摘ありがとうございました💦　rebaseしました！ご確認お願いいたします🙇‍♀️

2021-01-07 10:54 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-07 10:54 UTC, merged