期の一覧ページを追加
fjordllc/bootcamp pull request #2129
Opened 2020-11-20 05:18 UTC by hogucc

Ref: #2050

## 概要
右上のメニューに期の一覧ページへのリンクを追加し、そこから期の一覧ページに遷移できるようにする。

## 実装した機能
メニューに「期生別一覧」のリンクを追加しました。
<img width="407" alt="machidaのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/49110287/99761768-49baab80-2b3a-11eb-86f3-b35197ce3849.png">

上記リンクをクリックすると、期生別一覧ページに遷移します。「◯期生」のリンクをクリックすると、◯期のユーザー一覧画面へ遷移します。
※ 現時点ではデザイン未対応です
![image](https://user-images.githubusercontent.com/49110287/99761951-bcc42200-2b3a-11eb-8484-d9867e566290.png)

2020-11-20 05:34 UTC, hogucc commented
@machida 
期の一覧ページの仮実装を行いましたので、ページに表示する内容などの認識合わせをさせてください🙇‍♀️
現時点での画面イメージはPRのdescriptionのとおりです。

1. 期の一覧ページのリンク位置と文言
メニューの「ダッシュボード」の下に「期生別一覧」という名前で期の一覧ページへのリンクを追加しました。
リンクの位置はひとまず「ダッシュボード」の下にしていますが、別の場所にした方が良いでしょうか。
また、リンク名に悩んで「期生別一覧」という名前にしていますが、他に良い名前が思いつきませんでした💦
machidaさんからもご意見いただきたいです🙏

1. 期の一覧ページに表示する内容
いまは「◯期生」という文言と期の開始日・終了日、期のユーザーのアイコンを表示しています。
他に表示したい情報などありますか。

2020-11-25 06:09 UTC, hogucc commented
> @machida
> 期の一覧ページの仮実装を行いましたので、ページに表示する内容などの認識合わせをさせてください🙇‍♀️
> 現時点での画面イメージはPRのdescriptionのとおりです。
> 
> 1. 期の一覧ページのリンク位置と文言
>    メニューの「ダッシュボード」の下に「期生別一覧」という名前で期の一覧ページへのリンクを追加しました。
>    リンクの位置はひとまず「ダッシュボード」の下にしていますが、別の場所にした方が良いでしょうか。
>    また、リンク名に悩んで「期生別一覧」という名前にしていますが、他に良い名前が思いつきませんでした💦
>    machidaさんからもご意見いただきたいです🙏
> 2. 期の一覧ページに表示する内容
>    いまは「◯期生」という文言と期の開始日・終了日、期のユーザーのアイコンを表示しています。
>    他に表示したい情報などありますか。

上記内容+αを振り返りミーティングで会話したので、内容をメモします。

- 上記1、2については今の内容で問題ない
    - ユーザーのアイコンを表示しているが、本番環境での表示速度の低下が懸念される。一旦表示する方向で実装して、本番環境にマージ後に表示速度を確認する
- ユーザーページに期の一覧を表示するかどうか
    - 機能が大きくなるので、このPRではユーザーページに表示しない

2020-11-25 06:20 UTC, hogucc commented
@machida 
こちらデザインをお願いいたします🙇‍♀️

2020-11-26 06:28 UTC, machida commented
@hogucc @komagata こちらデザイン入れましたー

2020-11-26 06:30 UTC, hogucc commented
@machida 
デザインのご対応ありがとうございます！

@komagata 
コードレビューをお願いいたします🙇‍♀️

2020-11-26 08:11 UTC, komagata requested changes

2020-11-26 08:11 UTC, komagata commented on app/controllers/generations_controller.rb
> +    def max_generation_number
Generationクラスでやって方がいい処理かも

2020-11-26 09:50 UTC, hogucc commented on app/controllers/generations_controller.rb
> +    def max_generation_number
@komagata 
max_generation_numberメソッドをGenerationクラスに移動しました！
Generationクラスのインスタンスは一つの期を表しているイメージだったので、インスタンスメソッドだと違和感があり、クラスメソッドにしています。

2020-11-27 06:53 UTC, komagata requested changes

2020-11-27 06:53 UTC, komagata commented on app/controllers/generations_controller.rb
> +    @generations = (1..Generation.max_generation_number).map { |n| Generation.new(n) }
この内容自体Generationクラスに移すとControllerがスリムになるのでいいかもです。
ある程度汎用的な処理なので他で使うこともありそうなので。

2020-11-27 14:27 UTC, hogucc commented on app/controllers/generations_controller.rb
> +    @generations = (1..Generation.max_generation_number).map { |n| Generation.new(n) }
たしかにgenerationsの取得そのものがmodelに書いたほうが良さそうなロジックですね。
modelにgenerationsメソッドを作成して、controllerでこのメソッドを呼び出すように修正しました！
b5e6485

2020-11-30 10:36 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-30 10:36 UTC, merged

2020-11-30 11:04 UTC, hogucc commented
@komagata 
ご確認ありがとうございました！
ユーザーのアイコンが表示されるのでページの表示速度が遅くならないか心配してましたが、いま本番環境で確認したところ特に遅く感じなかったので大丈夫そうです！