Docsをプラクティスに紐付けられるように変更
fjordllc/bootcamp pull request #2146
Opened 2020-11-25 04:29 UTC by MashioSano

#2057  の作業です。

## 仕様
- Docsにプラクティスを1つ紐づられる
- プラクティスの指定は必須ではない

## Gif
![DocにPracticeを紐付け mov](https://user-images.githubusercontent.com/52710925/100181622-0a1b0780-2f1e-11eb-8daf-3bd535fb57f4.gif)

2020-11-25 08:21 UTC, komagata approved these changes
入力フォームのところは「関連プラクティス」とかの方がいいかも

2020-11-25 09:11 UTC, MashioSano commented
@komagata 
> 入力フォームのところは「関連プラクティス」とかの方がいいかも

フォームのラベルと選択ボックスの文言を「プラクティス」から「関連プラクティス」に変更しました。
ご確認ほどよろしくお願いいたします🙇🏻‍♂️
<img width="751" alt="スクリーンショット 2020-11-25 17 26 56" src="https://user-images.githubusercontent.com/52710925/100205979-1f595b80-2f49-11eb-9b02-1a683f1b23e1.png">

2020-11-26 07:42 UTC, komagata requested changes

2020-11-26 07:42 UTC, komagata commented on app/controllers/pages_controller.rb
> +                 .includes([:comments, :practice])
```suggestion
                 .includes(:comments, :practice)
```

ここってこうじゃダメでしたっけ？

2020-11-26 13:13 UTC, MashioSano commented on app/controllers/pages_controller.rb
> +                 .includes([:comments, :practice])
@komagata 
<code>.includes(:comments, :practice)</code>で同じように動くことを確認し修正しました。
ご確認のほどよろしくお願いいたします🙇🏻‍♂️

2020-11-27 07:13 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-27 07:13 UTC, merged