他人のプラクティスの進捗をチェックボックスで表示/非表示に切り替えられるようにした
fjordllc/bootcamp pull request #2152
Opened 2020-11-25 11:18 UTC by Chi-rr

#2047 のissueに対応。

【仕様】
プラクティスの一覧上部に、他人の進捗を非表示にできるチェックボックスを配置しました。

【背景】
現在各プラクティスごとに、そのプラクティスを着手しているユーザーのアイコンが表示されており
他人の進捗が可視化されておりました。
そこでチェックボックスを利用して「非表示」の選択も可能にしました。

2020-11-25 11:29 UTC, Chi-rr commented
@machida 
プラクティス一覧に載せるチェックボックス周りのデザインを、よろしくお願いいたします🤲

2020-11-26 05:36 UTC, machida commented
@Chi-rr 
すいません、Classの付け方についてレビューしますー

2020-11-26 05:41 UTC, machida commented on app/views/courses/practices/index.html.slim
>      .categories-items
`.categories-items` この slim に `js-` の付く class を付けてほしいです。

理由は、

- `.categories-items` の class名が将来的に変わるかもしれない
- `.categories-items` の他にも同じ動きが必要になるかもしれない

の二点からです。
なので、`.js-users-visibility` というclassをここに付けていただきたいです。

```slim
.page-body.js-users-visibility
  .container
    .categories-items
```

このように複数classを付けていただきたいです🙏

そうすればどの場所であれ、`.js-users-visibility` をつければ同じ動きが再現できるからです。

2020-11-26 05:43 UTC, machida commented on app/javascript/checkBox.js
> +        const categoriesItems = value.closest('.categories-items')
この書き方だと、`.categories-items` にしか使えないので、セレクタは `.js-` が付くclassでお願いしたいです。

2020-11-26 05:46 UTC, machida commented on app/javascript/checkBox.js
> +          value.closest('.categories-items').classList.remove('js-is-hidden-users')
逆に、こっちは `.js-` のclassでなくていいです。
状態の変化なので、`.is-hidden-users` という class でお願いします。
show （is-shown）の状態がデフォルト、hidden（is-hidden）がイレギュラーな扱いにしたいと思います。
なので、`.js-is-show-users` のclassの付加・削除はしなくて大丈夫です。
`.is-hidden-users`だけ付加・削除するようにお願いします🙏

2020-11-26 05:51 UTC, machida commented on app/javascript/checkBox.js
>    document.querySelectorAll('input').forEach((e) => {
input も `.js-` を付けた class名を付けて明示的にしたいです。`.js-users-visibility__trigger` にするとわかりやすいかな。そうすることで、新たに別のinputが増えてもjsを修正する必要がなくなります。なるべくデザイン変更に影響されないようにしたいと思います。

2020-11-27 15:30 UTC, Chi-rr commented
@machida 
レビューいただきありがとうございます！🙇‍♀️

ご指摘いただいた点を元に主に改善したのは
- `.js-users-visibility`クラスを、.page-bodyの階層に追加
- `.js-users-visibility__trigger`クラスを、inputに追加
- `.js-users-visibility__trigger`クラスが追加されたinputは
  - checked === false(=非表示)の場合は`.is-hidden-users`クラスを`.js-users-visibility`と同じ階層に追加
  - checked === true(=表示)の場合は`.is-hidden-users`クラスを削除する(=このクラスがない状態は、すなわちis-show-users)
  - デフォルトのユーザー表示状態の場合(is-show-users)特にクラスは追加されない

上記のように、再利用可能になるように修正してみました🙌

【質問】
- 最初[issue](https://github.com/fjordllc/bootcamp/issues/2047)には以下のような記述がありました。
>チェックボックスの値によって、categories-items に、is-show-users、is-hidden-users の class が付くようにする。

今回の修正にて
- チェックボックスの値によってclassが追加されるのは、`.page-body.js-users-visibility`です
- `is-show-users`はデフォルト状態としたため、このclassは無くなりました

以上2点について今回の修正に問題はなかったでしょうか？？
ご確認のほど、よろしくお願いいたします！

2020-11-30 03:13 UTC, machida commented
@Chi-rr ご対応ありがとうございます！この対応でバッチリですー！！もし、もっとHTML的にこうしたらやりやすいなどが、僕がデザインを入れる時点で見つかったら修正・連絡させていただきますー

2020-11-30 03:14 UTC, machida approved these changes

2020-11-30 06:50 UTC, Chi-rr commented
> @Chi-rr ご対応ありがとうございます！この対応でバッチリですー！！もし、もっとHTML的にこうしたらやりやすいなどが、僕がデザインを入れる時点で見つかったら修正・連絡させていただきますー

ご確認ありがとうございます！！
承知いたしました！よろしくお願いします🤲

2020-12-16 04:55 UTC, machida commented
@Chi-rr デザイン入れましたが、もう少しこの機能の説明文章を詳しく書きます。時間がなかった。。。もう少しだけ待ってください🙏

2020-12-16 06:51 UTC, machida commented
@Chi-rr すいません、お待たせしました。デザイン完了しました！！

2020-12-16 06:52 UTC, machida commented
コンフリクト修正しますー

2020-12-16 07:09 UTC, machida approved these changes

2020-12-16 14:06 UTC, machida commented
@komagata デザイン入れました！レビューお願いします🙏

2020-12-18 02:52 UTC, komagata commented
@machida デザインありがとうございます！

@Chi-rr 僕以外の方に最初レビューしてもらってください〜

2020-12-20 09:46 UTC, Chi-rr commented
@ima1zumi 
お疲れさまです！ima1zumi さんに立てていただいたissue(#2047)を担当しました！
いつでも大丈夫なので、またお手すきの際にレビューいただきたいです🙇‍♀️

2020-12-22 10:16 UTC, ima1zumi requested changes

2020-12-22 10:16 UTC, ima1zumi commented on app/javascript/checkBox.js
> +    const hasJsClass = e.hasClass('js-users-visibility__trigger')
`hasJsClass` という名前は少し抽象的な気がします 🤔 
コードを見てなんの変数か分かるくらいに具体的な名前をつけておいたほうがいいかなと思います〜

2020-12-22 10:16 UTC, ima1zumi commented on app/javascript/checkBox.js
> +    if (localStorage.getItem('hidden-users') === 'on' && hasJsClass) {
好みかな〜と思うので取り込むかどうかはおまかせしますが、 
みんなの進捗を `ON` にすると`hidden-users` は `remove` されるので、`hidden-users` の存在チェックだけでもいいかなと思ったりしました。

```js
if (localStorage.getItem('hidden-users') && hasJsClass) {
```

2020-12-29 02:50 UTC, Chi-rr commented on app/javascript/checkBox.js
> +    } else if (e.checked === true && !hasJsClass) {
各々修正してみました！
参考リンクまでありがとうございます🤲

2020-12-29 02:52 UTC, Chi-rr commented on app/javascript/checkBox.js
> +    const hasJsClass = e.hasClass('js-users-visibility__trigger')
ご指摘ありがとうございます！確かにですね
そのまま`jsUsersVisibilityTriggerClass`に修正してみたのですが、どうでしょうか🤔

2020-12-29 02:58 UTC, Chi-rr commented on app/javascript/checkBox.js
> +    if (localStorage.getItem('hidden-users') === 'on' && hasJsClass) {
hidden-usersモードon、だとわかりやすいかなと思っていましたが
有無で問うのでも良いなと思ったのでこちらで修正してみました😄

2020-12-29 03:20 UTC, Chi-rr commented on app/javascript/checkBox.js
>    document.querySelectorAll('input').forEach((e) => {
@ima1zumi 
>そのままでいいのでしょうか？

こちらforEachしている点についてでしょうか・・？👀

2020-12-29 14:34 UTC, ima1zumi commented on app/javascript/checkBox.js
>    document.querySelectorAll('input').forEach((e) => {
@Chi-rr 
いえ、machidaさんのコメントについてです 😄 

> input も .js- を付けた class名を付けて明示的にしたいです。.js-users-visibility__trigger にするとわかりやすいかな。そうすることで、新たに別のinputが増えてもjsを修正する必要がなくなります。なるべくデザイン変更に影響されないようにしたいと思います。

こちらは対応済でしょうか？

2020-12-29 14:44 UTC, ima1zumi reviewed
修正内容は良さそうですが、コミットメッセージの情報量が少ないのが気になりました…！
意味ごとにコミットを分けたほうが後から見たときに分かりやすいかと思います！
参考：[コミットメッセージの書き方\. 適切な情報を残そう \| by risacan \| Medium](https://medium.com/@risacan/%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9-64aeadd92057)

2020-12-30 01:22 UTC, Chi-rr commented on app/javascript/checkBox.js
>    document.querySelectorAll('input').forEach((e) => {
@ima1zumi 
ご確認ありがとうございます！対応済です〜🙆‍♀️
https://github.com/fjordllc/bootcamp/blob/c7cfa2750dc75bc185c75c50cd2c781892314e03/app/views/courses/practices/index.html.slim#L31

以下のように利用しております！

>- `.js-users-visibility__trigger`クラスが追加されたinputは
>    - input.checked === false(=非表示)の場合は.is-hidden-usersクラスを.js-users-visibilityと同じ階層に追加
>    - input.checked === true(=表示)の場合は.is-hidden-usersクラスを削除する

2020-12-30 01:23 UTC, Chi-rr commented
> 修正内容は良さそうですが、コミットメッセージの情報量が少ないのが気になりました…！
> 意味ごとにコミットを分けたほうが後から見たときに分かりやすいかと思います！
> 参考：[コミットメッセージの書き方. 適切な情報を残そう | by risacan | Medium](https://medium.com/@risacan/%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9-64aeadd92057)

2020-12-30 01:25 UTC, Chi-rr commented
@ima1zumi 
参考サイトありがとうございます！
修正してみました！ご確認よろしくお願いします🤲

2021-01-01 13:21 UTC, ima1zumi approved these changes
確認しました！良さそうです 🙆‍♂️  ありがとうございます！！

2021-01-01 13:21 UTC, ima1zumi commented on app/javascript/checkBox.js
>    document.querySelectorAll('input').forEach((e) => {
ありがとうございます！！

2021-01-05 01:42 UTC, Chi-rr commented
@komagata 
レビューよろしくお願いします🤲

2021-01-06 06:11 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-06 06:11 UTC, merged