ユーザーのプロフィールにメンターしか表示・編集できないメモを作成する
fjordllc/bootcamp pull request #2175
Opened 2020-11-30 13:27 UTC by Chi-rr

2020-12-01 09:08 UTC, komagata commented
> タスク分解

これでいいと思います〜

> DB設計

1でいいと思います。

2020-12-12 11:35 UTC, Chi-rr commented on app/views/api/users/_user.json.jbuilder
> +json.(user, :id, :login_name, :url, :role, :icon_title, :memo)
@komagata 
メンターのみ閲覧可能なメモデータ(memo)につきまして、
`app/views/api/users/_user.json.jbuilder `で条件分岐してしまってよいでしょうか？

2020-12-14 01:24 UTC, komagata commented on app/views/api/users/_user.json.jbuilder
> +json.(user, :id, :login_name, :url, :role, :icon_title, :memo)
@Chi-rr はい

2020-12-28 06:47 UTC, Chi-rr commented
@machida さん
## Vueのデザインについて
[提出物ページでメンターメモをページ遷移なしで編集できるようにした](https://github.com/fjordllc/bootcamp/pull/1948)の[app/javascript/mentor_memo.vue ](https://github.com/fjordllc/bootcamp/pull/1948/files#diff-735566de3976f6e45ae1b36168ec3e1a11a85ccb19883c719fb7676fc99ea4a7)元に、[app/javascript/user_mentor_memo.vue](https://github.com/fjordllc/bootcamp/pull/2175/files#diff-dfac91d6f40869fada6f5b3f26f7770c4bd4c157fa4ed9e82a2fde860169accb)の仮デザインを入れています。

ご確認のほどよろしくお願いいたします🤲

<img width="428" alt="スクリーンショット 2020-12-28 15 43 00" src="https://user-images.githubusercontent.com/52053239/103194578-70cb8080-4923-11eb-8ccb-6ea4d0946a0d.png">

2021-01-01 13:48 UTC, imaharu commented on app/models/user.rb
> +  end
userオブジェクトからインスタンスメソッドを呼び出しているので、 引数として user_id を渡す必要ない気がしました

```ruby
# controller.rb
def update
  @user = User.find(params[:id])
  if @user.update_user_mentor_memo(user_params)
    head :ok
  else
    head :bad_request
  end
end
```

```ruby
# model
def update_user_mentor_memo(user_params)
  ActiveRecord::Base.transaction do
    # self.class とかしてみるといいかも
   record_timestamps = false
   update!(user_params)
  end
end
```

みたいな感じでいけるはずです

2021-01-01 13:49 UTC, imaharu commented on app/models/user.rb
> +  end
もっと改良するなら、 update_user_mentor_memo メソッドの関心は、memoカラムを更新することなので
明示的に、memoだけを渡すとかの方が良さそうです。 user_paramsだと、呼び出し元まで確認しないと何を渡しているのか、理解できないので、引数名を `new_memo` にしてみました

```ruby
def update
  @user = User.find(params[:id])
  if @user.update_user_mentor_memo(user_params[:memo]) # 動くか試してない
    head :ok
  else
    head :bad_request
  end
end
```

```ruby
def update_user_mentor_memo(new_memo)
  ActiveRecord::Base.transaction do
   record_timestamps = false
   update!(memo: new_memo)
  end
end
```

2021-01-01 13:56 UTC, imaharu commented on app/javascript/user_mentor_memo.vue
> +    })
単純な疑問なんです

# 前提
- JavaScriptのお作法詳しくないです...
-  `console.warn` は 開発者ツールに標準エラーを出力するものだと認識してる

# 疑問
一般ユーザーは、開発者ツールを開くことはないので、 `cosole.warn` する理由がよくわかってないです。
お作法的なのなら、それでいいんですが、何か理由を知っていれば教えてほしいです

2021-01-01 14:24 UTC, imaharu commented on app/views/api/users/_user.json.jbuilder
> +end
以下を参考にすると、見栄えよくなったり...？

https://github.com/fjordllc/bootcamp/pull/2223#discussion_r550416233

2021-01-01 14:27 UTC, imaharu commented
見えてはいけないものが見えてしまうのは、恐怖なので、
メンターと管理者以外がリクエストした時に、レスポンスに memoが含まれないテストほしいですね...

2021-01-01 14:28 UTC, imaharu commented on app/models/user.rb
> +      user.record_timestamps = false
`record_timestamps = false` が、必要な理由ってなんでしたっけ...

そして、要件としてホントに必要なんでしたっけ？

2021-01-03 06:07 UTC, Chi-rr commented on app/javascript/user_mentor_memo.vue
> +    })
@imaharu
レビューありがとうございます！！

`cosole.warn`はお作法ではないと思われます👀
本来であれば、エラー時の対応をもっと具体的に書くと良い箇所(例えばダイアログを表示するなど)であり、
現状では「開発者ツールにエラー表示するだけ」の処理しかしていない状況です。

今回はbootcamp内で同じ処理をしている箇所に倣い、こちらの記述に留めました🤔

2021-01-03 06:10 UTC, Chi-rr commented on app/models/user.rb
> +      user.record_timestamps = false
@imaharu
>record_timestamps = false が、必要な理由ってなんでしたっけ...

  memoカラムをメンターが保存した際に、userのupdated_at値が変更されてしまうのを防ぐために利用しています。
  
>そして、要件としてホントに必要なんでしたっけ？ 

    必要だと考えています🤔 
    
理由としては  

- updated_at値が変更されると、ユーザーの「最終ログイン日時」が変更されてしまうため
- それを踏まえ、ユーザー自身以外がupdated_at値を変更すべきではないと考えるため 

です。imaharuさんはどう思われますか？🤔

2021-01-03 06:25 UTC, imaharu commented on app/models/user.rb
> +      user.record_timestamps = false
> updated_at値が変更されると、ユーザーの「最終ログイン日時」が変更されてしまうため

なるほど、 `updated_at` が「最終ログイン日時」に利用されているんですね...

知りませんでした

> imaharuさんはどう思われますか？


最終ログイン日時を `updated_at` から判定するロジック自体を見直した方がいいと思いますが
一旦リファクタリングをIssueを作成して、 `update_user_mentor_memo` 付近にIssueリンクを貼るとかですね....

2021-01-03 08:40 UTC, imaharu commented
@Chi-rr バックエンド 部分は、問題ない気がします
フロントは、詳しくないのでレビューしてないです

他の生徒さんに、レビュー依頼を投げておいてください〜

2021-01-04 01:18 UTC, bluerabbit commented on app/models/user.rb
> +      user.record_timestamps = false
> `record_timestamps = false` が、必要な理由ってなんでしたっけ...

@Chi-rr 理由をコメントで書いておきましょう

2021-01-05 02:48 UTC, Chi-rr commented on app/models/user.rb
> +      user.record_timestamps = false
@bluerabbit 
ありがとうございます！コメント追加いたしました！

2021-01-05 02:51 UTC, Chi-rr commented
@imaharu 
> @Chi-rr バックエンド 部分は、問題ない気がします
> フロントは、詳しくないのでレビューしてないです
> 
> 他の生徒さんにも、バックエンド 、フロント含めレビュー依頼を投げておいてください〜 (バックエンドのレビューを含めているのは、僕がブートキャンプのドメインや開発方針に詳しくないからです)

レビューありがとうございました！
最終ログイン日時の件、また相談してみます。
machidaさんにデザインをお願いしているので、また終わり次第、
他の方にもレビューお願いしてみます🤲

2021-01-05 03:14 UTC, Chi-rr commented on app/models/user.rb
> +  end
62f804a にて修正

2021-01-05 03:14 UTC, Chi-rr commented on app/views/api/users/_user.json.jbuilder
> +end
cab6007 にて修正

2021-01-05 05:46 UTC, imaharu commented on app/models/user.rb
> +    # memoカラムをメンターor管理者が保存した際に、userのupdated_at値が変更されてしまうのを防ぐ
このコメントは、 `self.record_timestamps = false` と等価なので情報量が増えてない気がします

最終ログイン日時の件について、言及すべきかと

2021-01-05 06:08 UTC, Chi-rr commented on app/models/user.rb
> +    # memoカラムをメンターor管理者が保存した際に、userのupdated_at値が変更されてしまうのを防ぐ
@imaharu
ありがとうございます🙌
コメント、whyを追加してみました！

> ユーザーの「最終ログイン日時」にupdated_at値が利用されるため
   メンターor管理者によるmemoカラムのupdateの際は、updated_at値の変更を防ぐ

2021-01-06 06:04 UTC, komagata commented on app/models/user.rb
> +      user.record_timestamps = false
@ima1zumi 

Issue作ってみました。

https://github.com/fjordllc/bootcamp/issues/2231

これってどうすると良いっていうイメージですかね？

2021-01-06 06:12 UTC, komagata commented
@Chi-rr Draft状態ですとレビュー依頼状態にならないのでDraft外してください〜

2021-01-06 06:21 UTC, Chi-rr commented
@komagata 
最終ログイン日時の件、issue対応ありがとうございます🙇‍♀️
Draft外しました🤲

デザインが最後になりましたので、生徒の方にレビュー依頼していきます！💪

2021-01-06 06:46 UTC, imaharu commented on app/models/user.rb
> +      user.record_timestamps = false
`last_logged_in_at` のようなカラムを作成し、ログイン時に、`last_logged_in_at`を更新するイメージでした。

特に、課題感ないなら、全然 `updated_at` で 「最終ログイン日時」を判定するのでいいと思いました〜

2021-01-06 06:52 UTC, Chi-rr commented
@hogucc 
レビューをお願いしたいです！よろしくお願いします🤲

2021-01-06 06:55 UTC, hogucc commented
@Chi-rr 
承知しました〜！後ほどレビューさせていただきます👍

2021-01-06 09:27 UTC, hogucc requested changes

2021-01-06 09:28 UTC, hogucc commented
@Chi-rr 
レビューしました〜！
ご確認お願いします🙏

2021-01-07 03:17 UTC, Chi-rr commented on db/migrate/20201205060029_add_memo_to_users.rb
> +    add_column :users, :memo, :text
@hogucc 
ご指摘ありがとうございます！
こちら、提出物ページのメンターメモと統一したカラム名「memo」にする
という方針で進めることを、事前にkomagataさんに確認いたしました〜🙆‍♀️

2021-01-07 03:35 UTC, Chi-rr commented on test/system/user/memos_test.rb
> +end
ded18aa にて対応

2021-01-07 03:35 UTC, Chi-rr commented on test/models/user_test.rb
> +    travel_to Time.zone.local(2020, 1, 1, 0, 0, 0) do
fe95aab にて対応

2021-01-07 03:36 UTC, Chi-rr commented
@hogucc 
レビューありがとうございます！
修正いたしましたので、またお手すきの際にご確認よろしくお願いします🤲

2021-01-07 06:14 UTC, hogucc commented on db/migrate/20201205060029_add_memo_to_users.rb
> +    add_column :users, :memo, :text
@Chi-rr 
承知しました〜komagataさんと合意済みであれば修正しなくて大丈夫です！

2021-01-07 06:15 UTC, hogucc approved these changes

2021-01-07 06:16 UTC, hogucc commented
@Chi-rr 
修正ありがとうございます！
指摘内容が反映されていることを確認しました！LGTMです👍
komagataさんへのレビュー依頼をお願いします🙏

2021-01-07 06:29 UTC, Chi-rr commented
@komagata 
お手すきの際に、レビューをお願いしたいです！
よろしくお願いいたします🤲

2021-01-07 10:52 UTC, komagata commented
@Chi-rr この辺り、コミットメッセージや粒度を整理した方が良いかもです〜

<img width="404" alt="スクリーンショット 2021-01-07 19 50 20" src="https://user-images.githubusercontent.com/16577/103884355-cc66ec80-5121-11eb-87c3-b0d3819f5839.png”>

参考: [俺の考えるコミットメッセージの書き方 \- komagataのブログ](https://docs.komagata.org/5744)

2021-01-07 12:49 UTC, Chi-rr commented
@komagata 
レビューありがとうございます！

> @Chi-rr この辺り、コミットメッセージや粒度を整理した方が良いかもです〜

こちら参考に貼っていただいたブログ内で紹介されている[コミットメッセージの書き方](https://medium.com/@risacan/-64aeadd92057)を参考に、
コミットメッセージの3行目に詳細を記述しておりました！

こちらの内容を、パッと見てわかる1行目に修正すると良さそうでしょうか？🤲

<img width="471" alt="スクリーンショット 2021-01-07 21 22 40" src="https://user-images.githubusercontent.com/52053239/103894031-a3e6ee80-5131-11eb-8d32-68e03bf99965.png">

2021-01-08 03:29 UTC, imaharu approved these changes

2021-01-08 04:58 UTC, komagata commented
> こちらの内容を、パッと見てわかる1行目に修正すると良さそうでしょうか？🤲

はい。深く入り込まないと１行目以外は読まないのでぱっと見で分かった方が良いと思います〜

2021-01-08 05:54 UTC, Chi-rr commented
@komagata 
コミットメッセージ修正してみました！ご確認お願いいたします🤲

2021-01-08 09:36 UTC, ima1zumi commented on test/system/user/memos_test.rb
> +  test 'No one but mentor or administrator can see memorandom' do
横からすみません。
メンターメモは絶対に見えてはいけない情報だと思うので、admin, mentor 以外のすべてのロールで見れないことを確認する網羅的なテストを書いたほうがいい気がしました。
また、komagata さんは admin かつ mentor なので mentor だけの人のテストがあってもいいかなと思います。

2021-01-12 14:36 UTC, Chi-rr commented on test/system/user/memos_test.rb
> +  test 'No one but mentor or administrator can see memorandom' do
@ima1zumi @hogucc 
ご指摘ありがとうございます！！
テスト、追加いたしました！ fad135c
またお手すきの際に、ご確認よろしくお願いします🙇‍♀️

2021-01-13 05:46 UTC, komagata commented on app/models/user.rb
> +      user.record_timestamps = false
@imaharu なるほど、ありがとうございます！

2021-01-13 05:51 UTC, komagata requested changes
他のJSON APIでもmemoがメンター以外に見ることがないようになっているか念のために確認してみてください〜

2021-01-13 05:51 UTC, komagata commented on app/views/api/users/_user.json.jbuilder
> +columns << :memo if mentor_login? || admin_login?
👍

2021-01-13 05:51 UTC, komagata commented on db/migrate/20201205060029_add_memo_to_users.rb
> +    add_column :users, :memo, :text
普段は`memo`でいいかもですが、このカラムはユーザー本人に万が一にもみられちゃまずい要注意カラムなので`mentor_memo`という名前にして注意すべきということがわかるようにした方がいいかもですね。

2021-01-14 07:05 UTC, Chi-rr commented on db/migrate/20201205060029_add_memo_to_users.rb
> +    add_column :users, :memo, :text
@komagata 
承知いたしました！
`memo`→`mentor_memo`に変更いたします。
51e0f0a にて対応しました。

2021-01-14 10:03 UTC, komagata commented on app/javascript/user_mentor_memo.js
> +  const userMentorMemo = document.querySelector('#js-user-mentor-memo')
```suggestion
  const selector = '#js-user-mentor-memo'
  const userMentorMemo = document.querySelector(selector)
```

みたいにすると下の方と共通化できていいかもです〜

2021-01-14 12:30 UTC, Chi-rr commented
@komagata 
レビューありがとうございます！！
> 他のJSON APIでもmemoがメンター以外に見ることがないようになっているか念のために確認してみてください〜

こちらですが、他のJSON API利用画面で、userを返す場合レスポンスにmemo(mentor_memo)が入っていないか確認する、ということでしょうか？

どこで何を確認できれば「確認」になるのか、作業イメージを教えていただけますと幸いです🙇‍♀️🙇‍♀️

2021-01-14 13:46 UTC, Chi-rr commented on app/javascript/user_mentor_memo.js
> +  const userMentorMemo = document.querySelector('#js-user-mentor-memo')
@komagata 
ご確認ありがとうございます！
f0d031b にて対応いたしました！

2021-01-15 13:44 UTC, komagata commented
@Chi-rr 

> どこで何を確認できれば「確認」になるのか、作業イメージを教えていただけますと幸いです🙇‍♀️🙇‍♀️

APIの出力（JSON）で一般ユーザーがmentor_memoを見れるようになっていないか、コードとブラウザでの出力両方の面で確認して欲しいです。

APIは画面に表示されてなくてもcurlなどでHTTPでアクセスできてしまうので。（URLにAPIのURLを入れれば確認できるはずです）

2021-01-19 05:33 UTC, Chi-rr commented
@komagata 
ありがとうございます！
> APIの出力（JSON）で一般ユーザーがmentor_memoを見れるようになっていないか、コードとブラウザでの出力両方の面で確認して欲しいです。
> 
> APIは画面に表示されてなくてもcurlなどでHTTPでアクセスできてしまうので。（URLにAPIのURLを入れれば確認できるはずです）

以下のvueが呼び出されているページで、一般ユーザーの場合にmentor_memoカラムが
レスポンスに含まれていないことを確認いたしました🙆‍♀️
- recent_reports.vue
- comments.vue
- answers.vue
- user_mentor_memo.vue

2021-01-20 06:01 UTC, komagata commented
@Chi-rr 確認ありがとうございます。コンフリクトの修正お願いします〜

2021-01-20 12:50 UTC, Chi-rr commented
@komagata 
コンフリクト修正いたしました！
ご確認よろしくお願いします！(デザイン依頼、これからです🤲)

2021-01-22 09:14 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-22 15:46 UTC, Chi-rr commented
@machida さん
レビューの修正が完了いたしましたので、デザインをお願いします！🤲

## 現在のデザインについて
[提出物ページでメンターメモをページ遷移なしで編集できるようにした](https://github.com/fjordllc/bootcamp/pull/1948)の[app/javascript/mentor_memo.vue ](https://github.com/fjordllc/bootcamp/pull/1948/files#diff-735566de3976f6e45ae1b36168ec3e1a11a85ccb19883c719fb7676fc99ea4a7)元に、[app/javascript/user_mentor_memo.vue](https://github.com/fjordllc/bootcamp/pull/2175/files#diff-dfac91d6f40869fada6f5b3f26f7770c4bd4c157fa4ed9e82a2fde860169accb)の仮デザインを入れています。

ご確認のほどよろしくお願いいたします🤲

![localhost_3000_users_991528156__2_](https://user-images.githubusercontent.com/52053239/105181722-82452880-5b6f-11eb-9070-36603c78f5a0.png)

2021-02-10 14:34 UTC, komagata commented
@Chi-rr 追記ありがとうございます！

2021-05-19 17:23 UTC, machida commented
https://github.com/fjordllc/bootcamp/pull/2495 これをマージしたらテストが通るので、一旦テストが落ちてるのは放置。

2021-06-16 13:46 UTC, machida commented
@komagata コンフリクト解消お願いします🙏

2021-06-16 14:09 UTC, machida commented
@komagata コンフリクト解消しましたー。こちらご確認いただきたいです🙏

2021-06-17 03:22 UTC, komagata commented
@machida かしこまりました〜

> methodがかぶってしまっているところの修正をお願いしたいです🙏

これって厳密にはどこのことでしょう？
（すみません、センシティブな部分なので念のためで聞いております）

2021-06-17 05:27 UTC, machida commented
@komagata
すいません、こちらになりますー

![image](https://user-images.githubusercontent.com/168265/122336475-e41b8a00-cf77-11eb-84d7-dd963fd084c4.png)

- app/controllers/api/users_controller.rb
    - update
- app/controllers/api/users_controller.rb
    - user_params

こちらにmainブランチとこのブランチに変更があって、どうマージしていいかわからず、両方が残っている状態です。
こちらのマージをお願いしたいです🙏

2021-06-29 05:36 UTC, komagata commented
[![Image from Gyazo](https://i.gyazo.com/fb953ab11b858d4991777f2d39fb97b8.png)](https://gyazo.com/fb953ab11b858d4991777f2d39fb97b8)

@machida 編集はボタン（編集する方法）は必要ですが、メンターメモの内容が何もない時の表示を何か考えた方が良いかな〜と見てて思いました。いかがですかね〜

2021-06-29 14:02 UTC, merged