WIPでSlackに通知が飛んでしまう不具合を修正
fjordllc/bootcamp pull request #2180
Opened 2020-12-02 08:33 UTC by KishiKyousuke

ref #2016 
# 概要
## 目的
#2016 のPRマージ後、WIPの状態で保存した場合でも、Slackのgeneralチャンネルに通知が送られてしまうというバグが発生したため修正いたしました。

 ## 変更箇所
- `announcements_controller.rb`に定義されていたSlack通知のメソッド`notify_to_slack`を、`announcement_callbacks.rb`へ移動しました。

- 移動に伴って`notify_to_slack`メソッド内のURL構築のコードを変更しました。`page_callbacks.rb`を参考にしています。

- `announcement_callbacks.rb`の`after_create`および`after_update`メソッド内に、`notfy_to_slack`メソッドを追記しました。

2020-12-04 02:38 UTC, KishiKyousuke commented
@masuyama13 
お疲れさまです❗レビュー依頼をさせて頂きました❗
お時間があるときにご確認頂けるとありがたいです😊
よろしくおねがいします✨

2020-12-04 08:16 UTC, masuyama13 requested changes

2020-12-04 08:16 UTC, masuyama13 commented on app/controllers/announcements_controller.rb
> +        @announcement.update_attribute(:published_at, Time.current)
コントローラの仕事を減らすこととコードの重複をなくすために、`published_at`に値を入れる処理はコールバックにしてはどうでしょうか〜？
参考：https://github.com/fjordllc/bootcamp/blob/master/app/models/product_callbacks.rb#L24

2020-12-04 08:31 UTC, KishiKyousuke commented on app/controllers/announcements_controller.rb
> +        @announcement.update_attribute(:published_at, Time.current)
@masuyama13 
レビューありがとうございます❗
もしかしたら自分の環境だけかもしれないんですが、`announcement_callbacks.rb`にpublished_atに値を入れる処理を置いてしまうと`if !@announcement.wip? && @announcement.published_at.nil?`の評価より先にコールバック処理が行われてしまって、初投稿の場合でもpublished_atに値が入ってしまうんですよね…😓

2020-12-04 08:35 UTC, masuyama13 commented on app/controllers/announcements_controller.rb
> +        @announcement.update_attribute(:published_at, Time.current)
@KishiKyousuke 
そうなのですか!?😲
それは失礼しました！
`after_save`に書いてもそうなりますか？

2020-12-04 10:18 UTC, KishiKyousuke commented on app/controllers/announcements_controller.rb
> +        @announcement.update_attribute(:published_at, Time.current)
@masuyama13 
`after_update`を`after_save`に変更して、コールバック内でpublished_atの格納処理を行うように変更して試してみましたが、挙動は特に変わらないですね…😢（無限ループを回避するように`update_attribute`を`update_column`に変更して試しました）

2020-12-04 15:57 UTC, masuyama13 commented on app/controllers/announcements_controller.rb
> +        @announcement.update_attribute(:published_at, Time.current)
@KishiKyousuke 
なるほど〜
Productと同じようにはできないのですね。
ではLGTMとさせてください🙏

2020-12-04 15:58 UTC, masuyama13 approved these changes

2020-12-06 02:43 UTC, KishiKyousuke commented
@komagata 
レビューをお願いいたします❗
@masuyama13 さんとのやり取りにもあるように、コールバックの呼ばれるタイミングの都合上`published_at`の格納処理をコントローラに置かざるを得ない状況になっています😓
もし他の解決方法があれば、アドバイスを頂けると幸いです✨

2020-12-07 02:28 UTC, komagata requested changes

2020-12-07 02:28 UTC, komagata commented on app/controllers/announcements_controller.rb
> +        @announcement.update_attribute(:published_at, Time.current)
callbackはたくさんあるんですが、RailsGuideを参照してどれがどのタイミングで動くのか調べるといいかもです〜

2020-12-08 02:24 UTC, KishiKyousuke commented on app/controllers/announcements_controller.rb
> +        @announcement.update_attribute(:published_at, Time.current)
@komagata 
`after_save`や`after_update`とはまた別のコールバックを使えば、コントローラ内のif文`if !@announcement.wip? && @announcement.published_at.nil?`の条件分岐より後にコールバックを呼ぶことができると言うことでしょうか❓
コールバックの呼ばれる順番的に、`after_save`より後に呼ばれるコールバックとなると`after_commit`のみになると思います❗️

2020-12-09 06:51 UTC, KishiKyousuke commented
## ○エラーコード
```
E

Error:
AnnouncementsTest#test_show_pagination:
URI::InvalidURIError: bad URI(is not URI?): nil
    app/models/user.rb:427:in `avatar_url'
    app/models/announcement_callbacks.rb:43:in `notify_to_slack'
    app/models/announcement_callbacks.rb:7:in `after_create'
    test/system/announcements_test.rb:23:in `block (2 levels) in <class:AnnouncementsTest>'
    test/system/announcements_test.rb:22:in `times'
    test/system/announcements_test.rb:22:in `block in <class:AnnouncementsTest>'
```

## ○エラーとなった箇所
https://github.com/fjordllc/bootcamp/blob/c01ebbcd3b6121644eccd5c617f643538f8ac858/app/models/user.rb#L425-L431

## ○落ちているテスト
https://github.com/fjordllc/bootcamp/blob/c01ebbcd3b6121644eccd5c617f643538f8ac858/test/system/announcements_test.rb#L18-L27

## ○推測される原因
notify_to_slackをコントローラからモデルに移行した事によって`url_for`が使えなくなり、linkの生成方法を他のモデルを参考に変更した。その結果、テスト環境で`Announcement`をcreateしたときに`avatar.variant(resize: AVATAR_SIZE).service_url`がnilになってしまっている？

**変更後**
https://github.com/fjordllc/bootcamp/blob/c01ebbcd3b6121644eccd5c617f643538f8ac858/app/models/announcement_callbacks.rb#L36-L49

**変更前**
https://github.com/fjordllc/bootcamp/blob/e9659309a00a35c8ed23519e0af38fc74bf4f033/app/controllers/announcements_controller.rb#L54-L65

2020-12-09 06:52 UTC, KishiKyousuke commented
@komagata 
notify_to_slackをモデルに移行した際に発生するエラーについてまとめました。
アドバイスを頂けると幸いです！

2020-12-14 01:39 UTC, komagata commented
@KishiKyousuke これってCircleCIの時だけ起きるエラーですかね？

実際にエラーになっている箇所のデバッグをしてみるといいと思います〜！

2020-12-14 04:05 UTC, KishiKyousuke commented
@komagata 
ローカルで実行するシステムテストでも落ちますね😅
もう少しデバッグしてみます❗

2020-12-14 04:48 UTC, komagata commented
@KishiKyousuke binding.pryやbindin.irbでどこでエラーが出ているのかを実行をストップさせて確かめてみてください。

callbackがどのタイミングで動いているのか、avatarの画像処理がいつ動いているのかを念頭において調べてみてください〜

2020-12-14 04:49 UTC, komagata commented
またconflictしてる部分を修正お願いします〜

2020-12-14 05:33 UTC, KishiKyousuke commented
@komagata 
ありがとうございます❗

RubyMineのデバッグツールでエラーが起きた場所を順を追ってみていくと、やはり`user.rb`の`avatar.variant(resize: AVATAR_SIZE).service_url`の`service_url`が`bad URI(is not URI?): nil`を返しています。

```ruby
avatar.variant(resize: AVATAR_SIZE)
=> #<ActiveStorage::Variant:0x00007fc3018859e8 @blob=#<ActiveStorage::Blob id: 181, key: "xx6toiw0imwakf4buy3b9zyl5nca", filename: "komagata.jpg", content_type: "image/png", metadata: {"identified"=>true, "width"=>88, "height"=>88, "analyzed"=>true}, byte_size: 8227, checksum: "Ps5cHDCmCMFh/QE/Ew+1wQ==", created_at: "2020-12-14 05:08:13">, @variation=#<ActiveStorage::Variation:0x00007fc3018859c0 @transformations={:resize=>"88x88>"}>>

avatar.variant(resize: AVATAR_SIZE).service_url
=> bad URI(is not URI?): nil
```

この`service_url`というメソッドを調べてみると、S3などのオンラインストレージ内に保存した画像を、認証情報を付与したURLを使って一時的に使用できるようにするためのメソッドのようです。

(@u1tnkさんからのコメント)
>s3とかサービス側のURLという意味じゃないかなと思います。
s3とかで使うとpublicなURLもできますが、privateで外から見えないけど、認証情報をURLに付与して30分とか見えるURLとかも発行できるので、それを指して一時的なURLと言っているとんじゃないかと。
https://s3-ap-northeast-1.amazonaws.com/bucket/path/to.text?key=xxxxxxxxx みたいなやつです(パラメータ名は適当)

また、変更前のコードだと`show pagination`テストでは`notify_to_slack`が呼ばれていないということもわかりました💦
`notify_to_slack`をコールバックに移動させた結果、`show pagination`テストの`Announcement.create`で`notify_to_slack`が呼ばれるようになっていました。

そこで質問ですが、`service_url`というメソッドはテスト環境でも問題なく動くメソッドなのでしょうか？

2020-12-15 04:58 UTC, komagata commented
@KishiKyousuke bootcampの設定ではActiveStorageはローカルストレージに保存するようになっていて動くはずです〜

https://github.com/fjordllc/bootcamp/blob/master/config/storage.yml#L2

2020-12-17 01:34 UTC, KishiKyousuke commented
@komagata 
`announcements_test.rb`の`show pagination`テストで、createの前に`ActiveStorage::Current.host`の設定を行い、直接DBにレコードを登録した際にもservice_urlが正常に動作するように変更しました。
ご確認よろしくお願いいたします！

2020-12-18 02:54 UTC, komagata requested changes

2020-12-18 02:54 UTC, komagata commented on test/system/announcements_test.rb
> +    ActiveStorage::Current.host = 'http://lcoalhost:3000'
これって設定ファイルで指定できそうな気がするんですが、できないですかね？

2020-12-18 06:49 UTC, KishiKyousuke commented on test/system/announcements_test.rb
> +    ActiveStorage::Current.host = 'http://lcoalhost:3000'
test環境の設定ファイル内にも同様の書き方でhostを設定できたのですが、announcements以外の一部のシステムテストが落ちてしまいますね💦

2020-12-21 07:01 UTC, komagata requested changes

2020-12-21 07:01 UTC, komagata commented on test/system/announcements_test.rb
> +    ActiveStorage::Current.host = 'http://lcoalhost:3000'
無理だとしてももうちょっとその原因を探ってみてからにしたいっすね。

2020-12-22 08:53 UTC, KishiKyousuke commented on test/system/announcements_test.rb
> +    ActiveStorage::Current.host = 'http://lcoalhost:3000'
ご指摘いただいたように、`config/test.rb`内に`ActiveStorage::Current.host = 'http://lcoalhost:3000'`を移動させて何度かCircleCIを回してみましたが、全て問題なく動きました。
ただ、ローカルで`./bin/test`を実行すると、テストが通るときもあれば`ActiveStorage::FileNotFoundError`が1〜2箇所発生して落ちてしまうことがあるなどまだ問題がありそうです😓
もう少し原因を探ってみます。

2021-01-06 01:13 UTC, KishiKyousuke commented
@komagata 
別環境（別のMac）で試してみたところ、同様のエラーは確認されませんでした。
また、同じマシンでもiTerm上でテストを実行するとエラーが起きなかったため、私のRubyMineの設定が原因だということがわかりました。
その他修正点がなければマージをお願いいたします🙇🏻‍♂️

2021-01-06 06:44 UTC, komagata commented on test/system/announcements_test.rb
> +    ActiveStorage::Current.host = 'http://lcoalhost:3000'
これってその表記を移動させてという意味ではなくて、`config.xxxx.host = ‘http://localhost:3000'`みたいな書き方が設定ファイルでできるのではないかって感じです〜

2021-01-06 08:02 UTC, KishiKyousuke commented on test/system/announcements_test.rb
> +    ActiveStorage::Current.host = 'http://lcoalhost:3000'
@komagata 
私の調べる限りでは、ActiveStorage::Current.hostを設定ファイルで指定する方法は見つけられませんでした。
servise_urlなどで生成されるURLのホストを指定したいという質問はいくつか見かけましたが、controllerのbefore_actionで指定する方法や、ActiveStorage::Current.setを利用してcontroller外で指定する方法を勧める回答がほとんどでした。
設定ファイルではなくテスト内でActiveStorage::Current.hostを直接指定する方法はあまり好ましくないということでしょうか。

**ruby on rails apiでの説明**
[ActiveStorage::SetCurrent](https://edgeapi.rubyonrails.org/classes/ActiveStorage/SetCurrent.html)
**ActiveStorage::Current.hostが設定される処理**
[rails/set\_current\.rb at master · rails/rails](https://github.com/rails/rails/blob/master/activestorage/app/controllers/concerns/active_storage/set_current.rb )
**ActiveStorage::Current.hostの設定に関するQ&A**
[ActiveStorage with Rails API · Issue \#32500 · rails/rails](https://github.com/rails/rails/issues/32500)
[ruby on rails \- Setting ActiveStorage host \- Stack Overflow](https://stackoverflow.com/questions/55600389/setting-activestorage-host)

2021-01-07 10:37 UTC, komagata commented on test/system/announcements_test.rb
> +    ActiveStorage::Current.host = 'http://lcoalhost:3000'
@KishiKyousuke これの設定が必要だとすると、ActiveStorageを使うほとんど全てのテストで必要だと思うので、もっと一般的な設定方法がありそうだな〜と思った感じです。

ある程度調べてないかもとのことなのでOKです〜！

2021-01-07 10:38 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-07 10:38 UTC, merged