日報をチェックしたらリアルタイムで右側の最新の日報もチェックされた状態にする
fjordllc/bootcamp pull request #2192
Opened 2020-12-10 16:54 UTC by MashioSano

#2179  の作業です
日報を確認したらリアルタイムで右側の最新の日報にチェックマークがつくようにしました。
コメントの投稿と同時に日報を確認する場合も、同様にチェックマークがつきます。
日報の確認を取り消すとリアルタイムで右側の最新の日報のチェックマークが外れます。

## GIF動画
[![Image from Gyazo](https://i.gyazo.com/4e868db43ac00b1635929450057f911e.gif)](https://gyazo.com/4e868db43ac00b1635929450057f911e)

## 実装方法
日報の確認ボタンのコンポーネント(Check)と、右側に表示されている最新の日報のコンポーネント(RecentReports)の連携にVuexを使用しました。
理由としては、日報の確認ボタンのコンポーネント(Check)と、確認スタンプのコンポーネント(CheckStamp)がVuexで連携しているからです。
### コードの説明
ストアで管理するステートに<code>checkableId</code>を追加します。
これによりストア全体で現在の日報のIDを管理できます。
https://github.com/fjordllc/bootcamp/blob/abb6db0f6cddb73471c3cfabb207ebabf92043a8/app/javascript/check-store.js#L6-L12
確認ボタン押下によりCheckが作成されたらステートのcheckIdに値が入り、確認を取り消すとcheckIdにはnullが入ります。
https://github.com/fjordllc/bootcamp/blob/abb6db0f6cddb73471c3cfabb207ebabf92043a8/app/javascript/check-store.js#L42-L57
この性質を利用してrecent_reports.vue内でwatchを使ってcheckIdの変更を監視し、checkIdの値が変更される度にreportsを更新するようにしました。
checkIdに値が入っていれば、最新のレポートの配列からreportIdにマッチするreportのcheckをtrueに変更し配列を返します。
checkIdに値が入っていなければ、最新のレポートの配列からreportIdにマッチするreportのcheckをfalseに変更し配列を返します。
https://github.com/fjordllc/bootcamp/blob/abb6db0f6cddb73471c3cfabb207ebabf92043a8/app/javascript/recent_reports.vue#L38-L62

2020-12-11 08:35 UTC, komagata reviewed
checkableIdだけだと提出物のチェックに関連した何かの機能が入ったとき数字がぶつからないですかね？

2020-12-14 08:58 UTC, MashioSano commented
@komagata 
ステートに<code>checkableType</code>を追加し、<code>checkableType</code>がReportの時にのみ、日報の配列を更新するようにしました。
https://github.com/fjordllc/bootcamp/blob/3e09ea197d788b607f7173a846fe2050ab24fac5/app/javascript/recent_reports.vue#L52-L64

2020-12-15 04:59 UTC, komagata commented
僕以外の誰かにレビュー依頼してみてください〜

2020-12-15 07:45 UTC, MashioSano commented
@hogucc 
コードレビューお願いします!🙏

2020-12-15 07:50 UTC, hogucc commented
@MashioSano 
承知しました〜！レビュー終わり次第ご連絡します！

2020-12-15 10:45 UTC, hogucc requested changes

2020-12-15 10:45 UTC, hogucc commented on app/javascript/recent_reports.vue
> +    checkId (checkId, oldId) {
引数の`oldId`が使われていないように見えるので、不要であれば削除お願いします🙏

2020-12-15 10:45 UTC, hogucc commented on app/javascript/recent_report.vue
> +    .recent-reports-item__checked(v-if="report.check == true")
`'true'`から`true`への書き換えであればboolean値による判定になるので、
`v-if="report.check"`と書いた方がシンプルかなと思いました！

2020-12-15 10:45 UTC, hogucc commented on app/javascript/recent_reports.vue
> +    updateCheckValue(reportId, checkId, {check = true}){
引数の`checkId`が使われていないように見えるので、不要であれば削除お願いします🙏

2020-12-15 10:48 UTC, hogucc commented
@MashioSano 
レビューしました！コメントを記載しているのでご確認お願いいたします🙏

2020-12-15 15:53 UTC, MashioSano commented
@hogucc 
レビューありがとうございます!
ご指摘いただいた3点を修正しました。
ご確認のほどよろしくお願いいたします🙏

2020-12-16 00:34 UTC, hogucc approved these changes

2020-12-16 00:36 UTC, hogucc commented
@MashioSano 
修正されていることを確認しました！LGTMです👍

2020-12-16 01:57 UTC, MashioSano commented
@hogucc  
ご確認ありがとうございます！

@komagata 
こちらコードレビューお願いします!

2020-12-21 06:38 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-12-21 06:38 UTC, merged