提出物のチェックを担当するメンターを設定できるようにした
fjordllc/bootcamp pull request #2199
Opened 2020-12-15 08:15 UTC by hogucc

Ref #2073 

## 概要
メンターが増えたことで提出物のチェックがバッティングする可能性が出てきた。
バッティングを防ぐために提出物を確認するメンターを設定できるようにする。

## やったこと
- 提出物一覧に以下の表示を追加
  - 提出物の担当者名
  - 提出物に担当者が設定されていない場合：「私が見ます」ボタン
  - 提出物に自分（ログインユーザー）が設定されている場合：「担当から外れる」ボタン
- 確認が完了した提出物には上記ボタンおよび担当者名は表示されない

![image](https://user-images.githubusercontent.com/49110287/102186413-f0a22580-3ef5-11eb-9105-29f9ffb9655b.png)

- 提出物一覧に「自分の担当」タブを追加
  - ログインユーザーがレビューを担当している提出物が一覧表示される
  - 確認が完了した提出物はこの一覧には表示されない

![image](https://user-images.githubusercontent.com/49110287/102187151-fb10ef00-3ef6-11eb-86d0-7c3101ceb81c.png)

- 「私が見ます」ボタンを押したとき、すでに他の誰かがその提出物の担当者になっていたら通知される

<img width="846" alt="localhost_3000_の内容_と_提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/49110287/102188512-b8501680-3ef8-11eb-8049-37eee46c70fb.png">

2020-12-15 14:03 UTC, hogucc commented
@machida 
「私が見ます」ボタン・「担当から外れる」ボタンと担当者名のデザインをお願いいたします🙇‍♀️

2021-01-06 06:05 UTC, hogucc commented
@takopom 
こちらコードレビューをお願いいたします🙇‍♀️
（デザイン待ちだったのですが、今日の計画ミーティングで先にコードレビューしてもらうという話をmachidaさんとしました）

2021-01-06 06:33 UTC, takopom commented
@hogucc 承知しました！確認いたします〜！🙆‍♀️

2021-01-10 01:33 UTC, takopom requested changes
遅くなりすみません🙇‍♀️💦 確認いたしました！

2021-01-12 15:45 UTC, takopom commented on app/models/product.rb
> +    self.checker_id = checker_id ? nil : current_user_id
@hogucc こちら、私の着目が局所的すぎたかもと後から思いました💦
担当者を適切な値で保存する、今の形は自然なように思えてきました。すみません…！！

2021-01-12 23:49 UTC, hogucc commented on app/controllers/api/products/checker_controller.rb
> +      render status: :bad_request, json: { errorMessage: 'すでに他のメンターが担当者になっています。' }
以下コミットにて修正しました。
927b549

たしかに`message`という名前はエラーメッセージかどうかちょっとわかりづらいですね...
名称に迷いましたが、他のAPIと統一したかったので`message`に修正しました。

2021-01-12 23:53 UTC, hogucc commented on app/models/product.rb
> +    self.checker_id = checker_id ? nil : current_user_id
命名ってすごく難しいですよね...
takopomさんがご指摘されている内容もよくわかるので一度直してみたのですが、なんとなくsaveのほうが自然のような気もしてもとに戻しました💦

2021-01-12 23:56 UTC, hogucc commented on test/system/products_test.rb
> +    assert_text '管理者・アドバイザー・メンターとしてログインしてください'
これは自分が仕様を確認できてなかった部分なので後ほどmachidaさんとkomagataさんに確認してみます！
確認結果次第でまたコードレビューしていただくことになると思うので、結果はこちらに連絡します〜

2021-01-13 04:27 UTC, machida commented
@hogucc デザイン入れましたー。今テスト走らせてます。ちょこっと見た目の表示の仕方を変更したので、テスト落ちたら修正しますー

2021-01-13 04:56 UTC, machida commented
@hogucc テスト通りましたー

2021-01-13 10:15 UTC, hogucc commented
@machida 
デザインいただきありがとうございます！

2021-01-13 14:52 UTC, hogucc commented
@machida @komagata 
> アドバイザーでは担当者設定ができず、「自分の担当」ページは常に空の場合の表示になることが気になったのですが、もし仕様ということでしたら問題ございません〜！

上記のtakopomさんのコメントがきっかけで提出物一覧を閲覧できるユーザーの範囲を確認していたのですが、「自分の担当」タブ以外にも「未返信」「未チェック」タブの閲覧範囲が気になったので認識合わせさせてください。
以下の内容を簡単にまとめると、各タブの閲覧制御は実装されているのですが、実際にはその制御が効いていない状態になっています。
自分の認識は「あるべき姿」のところに書いたとおりですが、もし認識違いなどあればご意見いただきたいです（自分が実装する前から以下のような動きになっていたので、意図した動きかどうか知りたいです）。
認識違いがなければ、この内容で修正します。
「自分の担当」タブに関わってくる話なので、新しくissueは立てずにこのPR上で修正するつもりです。

## 現在の実装での挙動と問題点
- 提出物一覧（https://bootcamp.fjord.jp/products） にアクセス
    - ログインユーザーがadmin：「すべて」「未チェック」「未返信」「自分の担当」の各タブが表示され、タブごとに提出物一覧が表示される
    - ログインユーザーがアドバイザー、メンター：タブは表示されず、すべての提出物が一覧表示される。ただし、「未返信」「未チェック」「自分の担当」タブのURLにダイレクトアクセスされた場合は、アドバイザー、メンターでもすべてのタブが表示されている
- 画面左のグローバルナビゲーションの提出物リンクをクリック
    - どのユーザーでログインした場合でも未返信の提出物一覧（http://localhost:3000/products/not_responded） に遷移する
        - 上記のとおり**ログインユーザーによるタブの表示・非表示を制御しているが、グローバルナビゲーションのリンクは遷移先が未返信の提出物一覧なので、アドバイザー、メンターに対してもすべてのタブは表示されている**

## あるべき姿
- タブを表示させるのはログインユーザーがadminとメンターのときだけ、それ以外は非表示にする（既存の実装ではadminユーザーだけタブを表示しているが、メンターにも表示する）。
- グローバルナビゲーションの提出物リンクをクリックしたときの遷移先は下表のとおり

    |ログインユーザー|遷移先|
    | --- | --- |
    |admin・メンター | 未返信の提出物一覧（http://localhost:3000/products/not_responded）|
    | 上記以外 | すべての提出物一覧（https://bootcamp.fjord.jp/products） |

- 「未返信」「未チェック」「自分の担当」タブの内容は秘匿情報ではないのでadmin・メンター以外のユーザーが「未返信」「未チェック」「自分の担当」タブへダイレクトアクセスした場合のアクセス制限までは行わない

2021-01-14 09:58 UTC, komagata commented
@hogucc 提出物を見て良いのは admin, mentor, adviserで、左の提出物リンクも表示するのはそれだけにしたいって感じです〜

2021-01-14 10:18 UTC, hogucc commented
@komagata 
提出物そのものの閲覧権限というよりは、adviserが「未返信」「未チェック」「自分の担当」タブが見えている状態になっていることが問題かどうかを気にしていました。うまく伝えられなくて申し訳ないです💦

コードで説明すると、以下の行でadminの場合はタブを表示するように制御がかかっているので、admin以外はタブを見せたくないように見えたのですが、
https://github.com/fjordllc/bootcamp/blob/master/app/views/products/index.html.slim#L9

左の提出物リンクではユーザーの種類に関わらず「未返信」のタブが遷移先になっていて、そこには何も表示制御がかかっていなかったので、上に挙げたコードと矛盾した仕様に見えたのが気になりました。
https://github.com/fjordllc/bootcamp/blob/master/app/views/application/_global_nav.slim#L34

2021-01-15 13:42 UTC, komagata commented
@hogucc 

> adviserが「未返信」「未チェック」「自分の担当」タブが見えている状態になっていることが問題かどうかを気にしていました。

「未返信」「未チェック」「自分の担当」タブはadmin, mentorだけが見えるようにお願いします〜

2021-01-17 13:59 UTC, hogucc commented on test/system/products_test.rb
> +    assert_text '管理者・アドバイザー・メンターとしてログインしてください'
@takopom 
仕様を確認したところ、アドバイザーに対しては提出物一覧のタブは表示しないとのことだったのですが、既存のコードでそうなっていない箇所があったので修正しました（既存の仕様の詳細は別コメントの「現在の実装での挙動と問題点」のところにまとめています）。
137632e
9996694

なので、アドバイザーに対しては「自分の担当」ページは表示されなくなっています。
「自分の担当」ページのURLにダイレクトアクセスすればアドバイザーでも表示はされますが、機密情報ではないため、ダイレクトアクセスに対する制限までは行っていないです。

2021-01-18 00:39 UTC, takopom commented on test/system/products_test.rb
> +    assert_text '管理者・アドバイザー・メンターとしてログインしてください'
仕様のご確認ありがとうございます！🙏
やや気軽にコメントしてしまったと思いましたが💦、詳細を把握できました。ありがとうございます✨

> アドバイザーに対しては「自分の担当」ページは表示されなくなっています。

確認いたしました〜！🙆‍♀️

アドバイザーの場合は「未チェック」などのリンクが表示されないテストも追加されていて、とても良いと思いました！😊

2021-01-18 00:42 UTC, takopom approved these changes
確認いたしました〜！🙆‍♀️

2021-01-18 01:19 UTC, hogucc commented
@takopom 
レビューいただきありがとうございました😊

@komagata 
コードレビューをお願いいたします🙇‍♀️

2021-01-18 02:14 UTC, komagata requested changes

2021-01-18 02:14 UTC, komagata commented on app/javascript/productChecker.js
> +  const checkers = document.querySelectorAll('.js-checker')
この`.js-checker`を変数にして下の方に出てくるのと今日つかするといいかもっすね。

2021-01-18 02:14 UTC, komagata commented on test/models/product_test.rb
> +  end
`#save_checker`のテストも欲しいかも？

2021-01-18 07:22 UTC, hogucc commented on app/javascript/productChecker.js
> +  const checkers = document.querySelectorAll('.js-checker')
8bb5eb2 のコミットで修正しました！

2021-01-18 07:23 UTC, hogucc commented on test/models/product_test.rb
> +  end
2d8a665 のコミットでテスト追加しました！

2021-01-18 07:25 UTC, hogucc commented
@komagata 
ご指摘点を修正しました！再度レビューをお願いいたします🙇‍♀️

2021-01-20 05:58 UTC, komagata requested changes

2021-01-20 05:58 UTC, komagata commented on app/javascript/productChecker.js
> +import Vue from 'vue'
JSのファイル名、他のファイルは全てCamelCaseは使ってないのでsnake_caseとかにしたいっすね

2021-01-20 13:59 UTC, hogucc commented on app/javascript/productChecker.js
> +import Vue from 'vue'
productChecker.jsとproductChecker.vueのファイル名をスネークケースに修正しました！

0675e1b

2021-01-22 09:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-22 09:17 UTC, merged

2021-02-12 23:58 UTC, JunichiIto commented
@hogucc 反応が遅くなってしまいましたが、担当メンター設定機能、めちゃくちゃ重宝してます！！
最近はメンターが増えてきて「提出物のチェックがかぶってしまいそう」という心配が大きくなってきてたのですが、この機能のおかげでめちゃくちゃ精神衛生ポイントがアップしました！
どうもありがとうございました〜！😄

![sc](https://user-images.githubusercontent.com/1148320/107834473-9af4d700-6dd9-11eb-995c-601526380351.png)

2021-02-13 02:12 UTC, hogucc commented
@JunichiIto 
ご連絡ありがとうございます！役に立っていそうで良かったです〜😄
生徒側からだと一覧が見れないので機能しているか気にしていたのですが、スクショも載せていただいたので実際使われていることがわかって嬉しいです✨