カテゴリーをドラッグ&ドロップで並び替えられるようにした
fjordllc/bootcamp pull request #2208
Opened 2020-12-21 13:54 UTC by masuyama13

Ref: #2082 

## 概要

- カテゴリー一覧ページをVue.js化
- ドラッグ&ドロップでカテゴリーを並び替えられるようにした
- カテゴリー削除もページ遷移なしでできるようにした

## 変更後

![fjord-dnd](https://user-images.githubusercontent.com/58389623/102784005-1db37400-43df-11eb-9ac2-9a94336d1e59.gif)

## 変更前

<img width="913" alt="Screen Shot 2020-12-21 at 22 53 19" src="https://user-images.githubusercontent.com/58389623/102784187-5eab8880-43df-11eb-8f1b-b6470ebfaa02.png">

2020-12-22 08:09 UTC, masuyama13 commented
:memo: 雑談タイム
- コードレビューが終わってから、machidaさんにデザインをお願いする

2020-12-23 07:58 UTC, masuyama13 commented
@MashioSano 
コードレビューをお願いします:bow:

2020-12-24 09:31 UTC, MashioSano commented
@masuyama13 
返信遅くなってすいません!

今からみます!

2020-12-24 16:37 UTC, MashioSano requested changes
お待たせしました〜!
Vueを使ったドラッグ＆ドロップすごいですね!
カテゴリーの削除も非同期で実装されているのもいいですね!
個人的にこれってどういう意味だろう?と気になったこと、変数名などの細かな部分についてコメントしました。

その他2点気になることを書かせていただきます!
1.  <code>Unpermitted parameters: :category_id, :format</code>が出る
リモートブランチをチェックアウトして、開発環境(私のMac)でも動作確認を行い、正常に動いていることを確認しました。
ドラッグ&ドロップした後に以下のようなログが出ていることを確認しました。
```
Started PATCH "/api/categories/115012799/position.json" for ::1 at 2020-12-25 00:13:23 +0900
Processing by API::Categories::PositionController#update as JSON
  Parameters: {"position"=>2, "category_id"=>"115012799"}
Unpermitted parameters: :category_id, :format
Completed 204 No Content in 56ms (ActiveRecord: 14.0ms | Allocations: 6573)
```
masuyamaさんの開発環境でもこのように表示されますでしょうか?
意図的に<code>Unpermitted parameters</code>を発生させているのでしたら、その理由を知りたいです!

2. ドラッグ&ドロップのテストが書かれていない
 このプルリクエストの主な変更である、ドラッグ&ドロップのテストが書かれていないのが気になりました。

2020-12-25 03:09 UTC, masuyama13 commented
@MashioSano 
レビューありがとうございます！
`Unpermitted parameters`は見落としていました。確認します。
テストは、Vue.Draggableというライブラリの機能をテストする必要はないと思い、書きませんでした。

2020-12-25 03:10 UTC, masuyama13 commented on app/controllers/api/categories/position_controller.rb
> +      head :no_content
PUT/PATCHは、更新したリソースをレスポンスに入れて200(OK)のステータスコードを返すことが多いと思いますが、今回は並び替えだけなのでリソースを返すのに違和感を感じました。
なので、レスポンスボディを空にしてボディが空であることを示す204(No Content)としました。
『Webを支える技術』という本を参考にしました。
[204 No Content \- HTTP \| MDN](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/204)

2020-12-25 03:11 UTC, masuyama13 commented on app/javascript/categories.vue
> +    end (e) {
`e`は`event`です。
`event`を`e`と書くのは一般的だと思っていたのですが、`event`でも問題ないので修正します。

2020-12-25 03:11 UTC, masuyama13 commented on app/javascript/categories.vue
> +      beforeDragging: '',
修正します〜

2020-12-25 03:12 UTC, masuyama13 commented on app/controllers/api/categories_controller.rb
> +      head :no_content
updateと同様、返すリソースがないので204(No Content)にしました。

2020-12-25 03:13 UTC, masuyama13 commented on app/javascript/categories.vue
> +        draggable.admin-table__items(v-model="categories", handle='.grab', tag="tbody", @start="start", @end="end")
`draggable`要素はデフォルトでは`div`としてレンダリングされます。
今回はtableの中で`draggable`を使用しており、`div`ではなく`tbody`として表示させるためにこの記述をしています。
https://github.com/SortableJS/Vue.Draggable#tag

2020-12-25 04:23 UTC, maedana commented
ちょうど最近本業でこの辺やっていたので、ただの余談ですが、Vue.Draggable のレールに外れたことがやりたくなったときは
https://www.npmjs.com/package/vue-drag-drop
ならHTML Drag and Drop APIの薄いラッパーとしてVueから扱いやすいかもです。

あとiPadなどタッチデバイス対応が必要な際はたぶん標準だと対応してないので、こういうのも併用しないと駄目かもです。
https://github.com/timruffles/mobile-drag-drop

2020-12-25 05:19 UTC, MashioSano commented
@maedana 
コメントありがとうございます!
このプルリクエストでmasuyamaさんが、ドラッグ＆ドロップをスマホ＆タブレット対応されるかは置いておいて、
私のスマホからドラッグ＆ドロップできるか試してみました。
ドラッグ＆ドロップはできますが、並び替えられないことを確認しました。
https://user-images.githubusercontent.com/52710925/103120064-7756bf80-46b9-11eb-8842-420f3fe64187.MP4
こちらの動画はChormeで検証していますが、Safariでも同じような挙動になります。

ドラッグ＆ドロップ時のログ
```
Started PATCH "/api/categories/undefined/position.json" for 192.168.1.8 at 2020-12-25 14:11:43 +0900
Processing by API::Categories::PositionController#update as JSON
  Parameters: {"position"=>2, "category_id"=>"undefined"}
Completed 404 Not Found in 41ms (ActiveRecord: 3.4ms | Allocations: 2189)


  
ActiveRecord::RecordNotFound (Couldn't find Category with 'id'=undefined):
  
app/controllers/api/categories/position_controller.rb:5:in `update'
```

環境
iPhone7 iOS14.2
Chrome バージョン: 87.0.4280.77
Safari バージョン: 14.0.1

2020-12-25 06:22 UTC, MashioSano commented on app/controllers/api/categories/position_controller.rb
> +      head :no_content
なるほどです!👍

2020-12-25 06:31 UTC, MashioSano commented on app/javascript/categories.vue
> +        draggable.admin-table__items(v-model="categories", handle='.grab', tag="tbody", @start="start", @end="end")
なるほどです!理解しました!

2020-12-25 08:00 UTC, MashioSano commented
@masuyama13 
> テストは、Vue.Draggableというライブラリの機能をテストする必要はないと思い、書きませんでした。

なるほどです!
私の方ではテストなしでもOKとさせていただきますが、念のためkomagataさんにもテストがなくても大丈夫か確認していただけると助かります!

2020-12-27 10:53 UTC, komagata commented
D＆Dすごくテストむずそうなのでやらなくて大丈夫です〜

2020-12-27 13:51 UTC, masuyama13 commented
@komagata 
コメントありがとうございます。
タッチデバイス対応は、このPRでやった方がよろしいでしょうか？

2020-12-28 03:51 UTC, komagata commented
@masuyama13 はい。
デプロイの単位で考えて今回は変更なので今まではスマホで並び替えができる状態だったのでそれを失わずにデプロイできる必要があります。

2020-12-28 03:59 UTC, masuyama13 commented
@komagata 
承知しました！

2020-12-28 13:17 UTC, masuyama13 commented
@MashioSano 
修正したのでご確認よろしくお願いします！
`wrap_parameters`を使用することで`Unpermitted parameters:`の警告を消しました。
`dragstart`はタッチに対応していなかったので、Vue.Draggableのイベントだけを使用するようにしました。

2020-12-29 15:16 UTC, MashioSano approved these changes
確認しました!LGTMです!🎊

2020-12-30 00:41 UTC, masuyama13 commented
@MashioSano 
ありがとうございます😄

@komagata 
デザイン前ですが、コードレビューをお願いします。

2020-12-31 08:04 UTC, komagata requested changes

2021-01-04 11:29 UTC, masuyama13 commented
@komagata 
修正しましたので再度ご確認お願いします。
（この後machidaさんにデザインをお願いする予定です）

2021-01-05 06:23 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-05 06:23 UTC, komagata commented on app/javascript/categories.vue
> +          // position値は1から始まるため、インデックス番号 + 1
こういうちょっとしたコメントいいですね。

全体に不要なコメントを書きまくってるとよくないですが、ちょこっと注意が必要なところにこのようにコメントしておくのは見る人にとって非常にいいと思います！（コスパがいい）

2021-01-05 08:19 UTC, masuyama13 commented on app/javascript/categories.vue
> +          // position値は1から始まるため、インデックス番号 + 1
ありがとうございます！😄

2021-01-05 08:26 UTC, masuyama13 commented
@machida 
こちらコードレビューが終わりましたので、デザインをお願いします:pray:
お願いしたいのは「並び順」の部分で、仮でFontAwesomeのアイコンを入れてあります。

2021-01-13 02:40 UTC, machida commented
@masuyama13 お待たせしました！デザイン入れましたー confrict だけ修正お願いします🙏

2021-01-13 04:25 UTC, masuyama13 commented
@machida 
デザインありがとうございます！

@komagata 
コンフリクト解消しましたので、マージをお願いします。

2021-01-13 05:59 UTC, komagata requested changes

2021-01-13 05:59 UTC, komagata commented on app/assets/stylesheets/atoms/_a-grab.sass
> +  cursor: grab
すみません、今見つけたのですが、最終行に改行がないようです〜

2021-01-13 10:39 UTC, masuyama13 commented
@komagata 
すみませんでした！
改行を追加しましたのでご確認よろしくお願いします:bow:

2021-01-14 08:59 UTC, masuyama13 commented
@komagata 
今他の作業をしていて気づいたのですが、現在の本番環境でCategoryのposition値が連番になっていなかった場合に、わかりにくいバグが発生しそうです。
なので、position値を順番通りに入れ直すPR（これから作成します）を先にマージする必要があると思うのですが、そのようにさせていただいてもよろしいでしょうか？

2021-01-14 09:07 UTC, masuyama13 commented
@komagata 
現在のposition値を入れ直すのではなく、今回実装したロジックを変更することでも対応できる気がするので、少し時間をください。

2021-01-14 10:06 UTC, komagata commented
@masuyama13 了解です。もしそちらの方がやりやすいのであれば一旦別PRでpositionデータを修正するもの大丈夫です〜

2021-01-15 01:48 UTC, masuyama13 commented
@komagata 
ありがとうございます！
acts as listでは基本的に連番を想定しているので、連番にさせていただきたいと思います:pray:
data-migrate gemを使って別PRを作成します。

2021-01-15 13:46 UTC, komagata commented
@masuyama13 

> acts as listでは基本的に連番を想定しているので

これって本当ですか？（効率よく並び替えるために連番じゃない実装になってるライブラリをよく見るので）

2021-01-15 14:31 UTC, masuyama13 commented
@komagata 
はい。
根拠は、acts as listのREADMEの、既存モデルにacts as listを追加する場合のコードが、positionにindex(+1)を代入していることです。

> ```rb
> class AddPositionToTodoItem < ActiveRecord::Migration
>   def change
>     add_column :todo_items, :position, :integer
>     TodoItem.order(:updated_at).each.with_index(1) do |todo_item, index|
>       todo_item.update_column :position, index
>     end
>   end
> end
> ```
> [brendon/acts\_as\_list: An ActiveRecord plugin for managing lists\.](https://github.com/brendon/acts_as_list#adding-acts_as_list-to-an-existing-model)

実際に動かしてみたのですが、Categoryを新規登録すると、末尾の項目のposition値`+1`が入ります。
また、連番になっているときに中間の項目を削除すると、削除した項目以降のposition値が`-1`されます。
以上のことから、position値は連番が適切と考えました。

2021-01-18 01:59 UTC, komagata commented
@masuyama13 なるほどです〜

2021-01-18 11:58 UTC, masuyama13 commented
@komagata 
データ移行のPRを先にマージしていただきありがとうございました。
こちら、コンフリクト解消しましたので、問題なければマージをお願いします:bow:

2021-01-20 05:59 UTC, komagata requested changes

2021-01-20 05:59 UTC, komagata commented on app/assets/stylesheets/atoms/_a-grab.sass
> +
不要な空行があるみたいです

2021-01-21 02:52 UTC, masuyama13 commented on app/assets/stylesheets/atoms/_a-grab.sass
> +
何度も申し訳ありませんでした🙇
修正しましたのでご確認よろしくお願いします🙏

2021-01-22 09:18 UTC, komagata commented
@masuyama13 コンフリクトの修正お願いします〜

2021-01-22 13:39 UTC, masuyama13 commented
@komagata 
コンフリクト解消しました。

2021-01-25 04:35 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-25 04:35 UTC, merged