期生別一覧を新しい期順に並ぶようにした
fjordllc/bootcamp pull request #2243
Opened 2021-01-09 16:49 UTC by gallardo16

issue: https://github.com/fjordllc/bootcamp/issues/2177 に対応

今までは1期生から並ぶ昇順になっていましたが、新しい期から並ぶ降順に並び替えました。

2021-01-13 05:55 UTC, komagata commented
@gallardo16 スクラムに参加している僕以外の誰かにレビュー依頼してみてください〜（その後僕にお願いします。）

2021-01-13 07:12 UTC, gallardo16 commented
@komagata 
わかりました。依頼してみます〜

2021-01-13 08:14 UTC, gallardo16 commented
@hogucc 
お疲れ様です。
コードレビューをお願いします🙇‍♂️

2021-01-13 10:20 UTC, hogucc commented
@gallardo16 
承知しました〜！レビュー完了したらまた連絡します！
少々お待ちください🙇‍♀️

2021-01-13 14:01 UTC, hogucc requested changes

2021-01-13 14:07 UTC, hogucc commented
@gallardo16 
レビューさせていただきました！ご確認お願いいたします🙇‍♀️
あと以下コミットのコミットメッセージが英語になっていますが、bootcampのリポジトリでは日本語でコミットメッセージを書いているので日本語に修正をお願いします🙏
c486180

2021-01-14 16:53 UTC, gallardo16 commented on app/controllers/generations_controller.rb
> +    @generations = Generation.descending_order_generations
@hogucc 

修正しました！
詳細を書いていただきありがとうございます🙏

2021-01-14 16:57 UTC, gallardo16 commented
@hogucc 

レビューありがとうございます🙏
ご指摘していただいた、メソッド化について、コミットメッセージについて修正しました✍️
ご確認のほどよろしくお願いします〜！

2021-01-15 00:04 UTC, hogucc approved these changes

2021-01-15 00:23 UTC, hogucc commented
@gallardo16 
修正いただきありがとうございます！
LGTMです👍

コードはOKなのですが、コミットログが少し気になりました。
d190713 の変更を取り消すために e69e186 のコミットを積んでいると思うのですが、やっていることは a810289 のコミットと変わらないので、 a810289 のコミットだけで良さそうと思いました〜
もし不要であればlocalで d190713 と e69e186 のコミットを削除してforce pushするのが良さそうです。
実施するかの判断はおまかせします〜

私のレビューとしては完了なので、komagataさんへレビュー依頼お願いします🙏

2021-01-15 08:30 UTC, gallardo16 commented
@komagata 
レビューよろしくお願いします。

>コードはOKなのですが、コミットログが少し気になりました。
d190713 の変更を取り消すために e69e186 のコミットを積んでいると思うのですが、やっていることは a810289 のコミットと変わらないので、 a810289 のコミットだけで良さそうと思いました〜
もし不要であればlocalで d190713 と e69e186 のコミットを削除してforce pushするのが良さそうです。
実施するかの判断はおまかせします〜

@hoguccさんに上記についてご指摘いただきました。この件についてはレビューの流れを把握できるようにするため、残すことにしました。よろしくお願いします🙇‍♂️

2021-01-15 13:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-15 13:55 UTC, merged