プロフィールの自己紹介を入力必須にする
fjordllc/bootcamp pull request #2249
Opened 2021-01-12 17:24 UTC by gallardo16

## issue
 https://github.com/fjordllc/bootcamp/issues/2140 に対応

## 目的
自己紹介文もないと、その人の人となりがわからず、どういう素性の人がどういう目的で参加してきたのか不明で少し不安になるから。

## やったこと
- 自己紹介にバリデーションを追加
- 入力必須の赤アスタリスクを表示
- 自己紹介を空欄で作成、更新した場合のテストを作成

2021-01-18 09:49 UTC, gallardo16 commented
@MashioSano 

お疲れ様です〜
コードレビューをよろしくお願いいたします🙇‍♂️

2021-01-20 01:25 UTC, MashioSano requested changes
お待たせしました!
一点気になった点をコメントしました。
ご確認のほどよろしくお願いします!

2021-01-20 01:25 UTC, MashioSano commented on test/system/sign_up_test.rb
> +  end
<code>WebMock.disable_net_connect!</code>、<code>WebMock.allow_net_connect!</code>の記述をコメントアウトして、ローカルでヘッドレスブラウザー・普通のブラウザーでテストしてみたところ通ったので、この記述は必要か気になりました!👀
WebMockついて勉強不足で、なぜこの記述が必要なのか理解できていないので、gallardo16さんがもしご存知でしたらコメントしていただけると助かります!

2021-01-23 14:29 UTC, gallardo16 commented on test/system/sign_up_test.rb
> +  end
レビューありがとうございます🙇‍♂️

`WebMock.allow_net_connect!`は、スタブ登録していないAPI(クレカ情報の`fill_stripe_element`ヘルパー)へ、実際にリクエストするため、
`WebMock.disable_net_connect!`は、WebMockによってリクエストが弾かれないように、`localhost`と`chromedriver.storage`を`allow`で設定しているからだと思いました。
すみません、私も勉強不足で見当違いかもしれないです...

2021-01-25 13:53 UTC, MashioSano approved these changes
確認しました OKです!

2021-01-26 03:56 UTC, gallardo16 commented
@komagata 
コードレビューをお願いします！

2021-02-01 07:30 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-01 07:30 UTC, merged