「今日の気分」の並び順を変更
fjordllc/bootcamp pull request #2251
Opened 2021-01-13 03:02 UTC by Chi-rr

## issue
#2157 に対応

## 目的
- 「soso(0)・sad(-)・happy(+)」の並び順を、 より自然な「sad(-)・soso(±0)・happy(+)」に変更する。
<img width="331" alt="スクリーンショット 2021-01-13 11 57 35" src="https://user-images.githubusercontent.com/52053239/104400935-8fbe4980-5596-11eb-8e41-1fe7aca42216.png">

## やったこと
- 並び順をsad/soso/happyに変更
<img width="339" alt="スクリーンショット 2021-01-13 11 57 18" src="https://user-images.githubusercontent.com/52053239/104400938-92b93a00-5596-11eb-9e4d-794c645e9eec.png">

- 並び順変更に付随するreports.ymlのemotionも修正

2021-01-13 03:17 UTC, Chi-rr commented
@gallardo16 
お疲れさまです！
もしよければレビューを依頼したいのですが、お願いできますでしょうか？🤲

2021-01-13 03:41 UTC, gallardo16 commented
@Chi-rr 
お疲れ様です！
了解しました。確認いたします👀

2021-01-13 08:06 UTC, gallardo16 approved these changes
確認しました。大丈夫だと思います〜🙆‍♂️

2021-01-13 08:25 UTC, Chi-rr commented
@gallardo16 
ご確認ありがとうございます！！

2021-01-13 08:26 UTC, Chi-rr commented
@komagata 
レビューよろしくお願いいたします🤲

2021-01-14 09:50 UTC, komagata requested changes

2021-01-14 09:50 UTC, komagata commented on app/models/report.rb
> +    soso: 1,
ここ変えちゃうと既存のデータがおかしくなっちゃうかもです〜

2021-01-15 02:03 UTC, Chi-rr commented on app/models/report.rb
> +    soso: 1,
@komagata 
修正いたしました🙇‍♀️ 2b00e36
ご確認お願いいたします🙌

2021-01-15 13:48 UTC, komagata commented on test/fixtures/reports.yml
> +  emotion: 0
これらってなぜ変更されてますか？

2021-01-15 15:18 UTC, Chi-rr commented on app/models/report.rb
> +    soso: 1,
@komagata 
すみません！こちらで修正いたしました！ 2b00e36
よろしくお願いいたします💪

2021-01-15 15:19 UTC, Chi-rr commented on test/fixtures/reports.yml
> +  emotion: 0
@komagata 
こちら修正漏れです、遅くなりました🙇‍♀️ 
3f8bdf2
(※レビューの流れを残すため、修正の修正コミットですが作成してみました🙌)
>これらってなぜ変更されてますか？

2de7e40 のコミット(enumの数値変更)に付随して、変更が必要と思っていましたが、
2de7e40 → 2b00e36 のコミット(enumの定義順序の変更)に修正したため、こちらの変更は不要になりました🙏

2021-01-18 02:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-18 02:00 UTC, merged