通知一覧をVue.jsで非同期にした
fjordllc/bootcamp pull request #2260
Opened 2021-01-16 05:58 UTC by MashioSano

ref #2201

テストはまだ書いてません。

2021-01-20 01:43 UTC, MashioSano commented
@masuyama13 
お疲れ様です!お手隙の際にコードレビューお願いします🙇🏻‍♂️
ページャーのライブラリの細かい使い方まではプルリクエストの説明に書いていないので、気になる点がありましたらコメントしていただけると助かります🙂

2021-01-20 06:33 UTC, hogucc commented
@machida 
こちらのPRと私が対応中の[提出物一覧（全て）をVue.jsで非同期にしたいissue](https://github.com/fjordllc/bootcamp/issues/2178)に関連する話について質問させてください。

①
文字だけだと伝わりづらいので、以下の動画を見ていただきたいのですが、提出物一覧の「未チェック」タブをクリックしたときに「未チェックの提出物を一括で開く」ボタンが先に表示され、後から遅れてその他の情報が表示されます。
この現象はこのPRでSanoさんが対応されている通知一覧でも発生しています。
[![Image from Gyazo](https://i.gyazo.com/fd85f6e5934786c27c8ac90470680927.gif)](https://gyazo.com/fd85f6e5934786c27c8ac90470680927)

以前のスクラムのミーティングのときにページの読み込み時は画面を灰色にする等の処理を入れたいという話しがありましたが、それは別のissueで対応という認識で合っていますか？

②
上の質問の答えが別issueで対応だった場合ですが、暫定対処はしたほうが良いですか？
対処法はまだ漠然としかイメージできていないですが、「未チェックの提出物を一括で開く」ボタン以外の要素が描画されるタイミングで、ボタンも描画されるようにVue.js側で調整することはできそう、と考えています。
ただ、別issueの対応時には暫定対応で追加したコードは不要になる可能性が高いので、もし上記の表示の遅延が大きく問題にならないのであれば暫定対処は不要ではないかと思ったのですが、いかがでしょうか。

2021-01-20 06:41 UTC, MashioSano commented
@masuyama13 
すいません。
コードレビューをお願いしたのですが、上記のhoguccさんのコメントにある通り、 まだ確定していない部分があるので、コードレビューを一度中断していただけないでしょうか。このPRで上記の内容を私が対応することになると、最終的にrebaseしてforcepushすることになるので、今masuyamaさんが見ているコードと、最終的なコードの状態が変わる可能性があります。
レビューできる状態になったらコメントします。
よろしくお願いします。🙇🏻‍♂️

2021-01-20 08:53 UTC, masuyama13 commented
@MashioSano 承知しました〜

2021-01-27 03:56 UTC, machida commented
@hogucc @MashioSano 
返信遅れてすいません🙇‍♂️

> 別のissueで対応という認識で合っていますか？

はい、別のissueで対応にしたいと思います。

> 暫定対処はしたほうが良いですか？

もし、可能でしたら、読み込んでる間に表示するDOMを作っていただき、読み込み中... のような文字を出すようにしていただきたいですー

2021-01-31 14:18 UTC, MashioSano commented
@masuyama13 
コードレビューお願いします！

2021-02-01 09:01 UTC, masuyama13 commented
@MashioSano 
今見ているのですがもう少し時間がかかりそうです😓
明日にはレビューできるようにしたいと思います！

2021-02-02 04:44 UTC, masuyama13 commented on app/javascript/notification.vue
> +          .thread-list-item__header-icon.is-unread(v-if='notification.read==false')
`v-if='notification.read === false'`だと問題ありそうですかね？

2021-02-02 04:45 UTC, masuyama13 commented on app/javascript/notification.vue
> +        time.thread-list-item-meta__created-at(datetime="#{notification.created_at.to_datetime}") {{ notification.created_at }}
`#{notification.created_at.to_datetime}`の部分は修正漏れな気がします〜

2021-02-02 04:46 UTC, masuyama13 commented on app/javascript/notifications.js
> +          mentorLogin: mentorLogin === 'true'
たとえば`isMentor`のような、真偽値であることがわかりやすい名前がつけられるといいかなと思いました。

2021-02-02 04:46 UTC, masuyama13 commented on app/javascript/notifications.vue
> +      notification(v-for="(notification, index) in notifications"
`index`は使用されていないので削除してもよさそうです。

2021-02-02 04:47 UTC, masuyama13 commented on app/javascript/notifications.vue
> +      unconfirmed-links-open-button(v-if='mentorLogin && isUnreadPage' :label="'未読の通知を一括で開く'")
`label="未読の通知を一括で開く"`ではだめなんでしたっけ？

2021-02-02 04:48 UTC, masuyama13 commented on app/javascript/notifications.vue
> +    window.onpopstate=function(){
JavaScriptのコード部分で`=`や`if`、`()`、`{}`の前後など、スペースが入っているところと入っていないところがあるので、ある程度統一したほうがいいかもしれません。

2021-02-02 04:51 UTC, masuyama13 commented on app/javascript/notifications.vue
> +      return location.pathname.includes('unread') ? true : false
`includes`の返り値は真偽値なので、以下のように書けそうです。
```suggestion
      return location.pathname.includes('unread')
```

2021-02-02 04:51 UTC, masuyama13 commented on app/javascript/notifications.vue
> +      if (this.currentPage!=1){
JavaScriptでは暗黙的な型変換をしない`!==`の方が推奨されていると思っています。
手元で動かしてみたところ`!==`でも問題なさそうですが、`!=`を使う必要性があれば知りたいです。

2021-02-02 04:52 UTC, masuyama13 commented on config/routes.rb
> +    resources :notifications, only: %i(index) do
27〜29行目がなんかおかしくなってるみたいです。

2021-02-02 04:54 UTC, masuyama13 commented on test/system/notification/unread_test.rb
> +                        user: users(:hatsuno), sender: users(:machida))
改行を入れるのであれば、項目1つごとに改行して頭を揃えた方が見やすそうです（notifications_testも）。

2021-02-02 04:54 UTC, masuyama13 commented on test/system/notifications_test.rb
> +    30.times do |n|
`30`回である理由がよくわかりませんでした。必要最小限の21でいいような気がします。

2021-02-02 04:57 UTC, masuyama13 requested changes
きちんと動くことを確認できました〜
コード読ませていただいてとても勉強になりました！
レビューさせてもらってありがとうございます😀
通知がない場合に「通知はありません」と表示するようになっているのもいいですね👍

（コード以外の気になったこと）
- PRの説明文の「ページャーについて > 3.」のところのメソッド名が今のコードと違っているようです
- views/notifications/_notification.html.slim は削除してもいいのかなと思いました

2021-02-02 09:09 UTC, MashioSano commented
@masuyama13 
細かいところまで丁寧に見ていただいて嬉しいです!
ちょっと就職活動で忙しいので、土日で修正したいと思いますー
よろしくお願いします🙇

2021-02-06 17:47 UTC, MashioSano commented
@masuyama13 
大変お持たせしました！
コメントで指摘していただいた点を修正しました。
レビュー前と一点変わっている点があるので、そこも併せて見ていただけるとー 🙏 
https://github.com/fjordllc/bootcamp/pull/2260/commits/1a0091f0e9b694c76f8624c4b9286c2f003c7eca

CIが落ちてますが、このPRで変更したファイルが原因ではなさそうです。

2021-02-07 06:20 UTC, masuyama13 requested changes
おつかれさまです😀
1点だけコメントしたのでご確認お願いします。

2021-02-07 06:20 UTC, masuyama13 commented on config/routes.rb
> +    resources :categories, only: %i(index)
27行目は今回の差分ではない気がします〜👀

2021-02-07 06:51 UTC, MashioSano commented on config/routes.rb
> +    resources :categories, only: %i(index)
@masuyama13 
修正しましたー！

2021-02-07 08:12 UTC, masuyama13 approved these changes
@MashioSano 
確認しました！
LGTMです😄✨

2021-02-07 08:14 UTC, MashioSano commented
@komagata 
コードレビューお願いします！！

2021-02-10 07:43 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-10 07:43 UTC, komagata commented on app/javascript/notifications_bell.js
> +
notifications_bellいい名前だと思います！

2021-02-10 07:46 UTC, komagata commented
@MashioSano ちょっと今ブランチ戦略が変わっているところで、リリースする内容がたくさんありちょっと怖いのでこちら来週にリリースしたいと思います〜

2021-02-10 16:25 UTC, MashioSano commented
@komagata 
承知しました!
このPRで修正したファイルの中で、デザインに影響するファイルが幾つかあり、町田さんの修正が入ると思います。
修正が完了になり次第メンションさせていただきますー
よろしくお願いします！

2021-02-17 08:32 UTC, machida commented
@MashioSano cc @komagata 
ページャーの位置のずれは、
https://github.com/fjordllc/bootcamp/pull/2362
こちらのPRで解消しました。なので、これをマージした上でこのPRがマージされれば位置のずれが発生しなくなりますー

2021-02-17 08:37 UTC, machida commented
@MashioSano @komagata

デザイン確認しました！ページャーの位置以外は問題ありませんでした。
LGTMですー

2021-02-17 11:12 UTC, MashioSano commented
@machida 
デザインありがとうございます！
今週のリリースに間に合わせたかったのですが、返信が遅れてしまいました。

> これをマージした上でこのPRがマージされれば位置のずれが発生しなくなりますー

念のため確認させてください。
#2260 をマージして、その後に#2362 をマージするという認識であってますでしょうか。

2021-02-17 14:07 UTC, hogucc commented
@machida 
すみません、Sanoさんのコメントの補足ですが、ページャーのデザインについては[提出物一覧をVue.jsで非同期にした #2280 ](https://github.com/fjordllc/bootcamp/pull/2280)と[日報一覧(全体・未チェック)をVue.jsで非同期にした #2286](https://github.com/fjordllc/bootcamp/pull/2286)でもこのPRと同じ対応をしているので、
#2260、#2280、#2286 をmasterにマージした後に#2362 をmasterにマージする、という認識なのですが合っていますか？

2021-02-22 05:41 UTC, machida commented
@MashioSano @hogucc @komagata 返信遅れてすいません🙏
はい！
https://github.com/fjordllc/bootcamp/pull/2362
こちらを取り込んだmasterをrebaseして、デザイン崩れが解消されているか確認してマージ、もしくはその逆という流れにしたいと思います。
#2362 は CSSだけの変更なので、取り込んでしまいました。
#2260、#2280、#2286 それぞれ rebase してデザイン崩れが解消されているか、僕の方で確認してしまいますー

さのさん、メンションありがとうございます🙏

2021-02-22 05:59 UTC, machida commented
@MashioSano @komagata 

ページャーにずれがないのを確認しました。
これでマージお願いします🙏

![image](https://user-images.githubusercontent.com/168265/108668357-6f32c900-751e-11eb-85ee-590cfd409218.png)

![image](https://user-images.githubusercontent.com/168265/108668367-7659d700-751e-11eb-8fcc-e1ce5044a685.png)

![image](https://user-images.githubusercontent.com/168265/108668386-81146c00-751e-11eb-9df7-76070c0678f8.png)

![image](https://user-images.githubusercontent.com/168265/108668390-870a4d00-751e-11eb-8e47-9bb191996cb2.png)

2021-02-22 09:52 UTC, MashioSano commented
@machida @komagata 
対応ありがとうございます！
テストが落ちてしまってるようなので、明日対応したいと思いますー

2021-02-22 23:19 UTC, MashioSano commented
@komagata @machida 
テストが落ちていたので修正しましたー
マージお願いします 🙏

2021-02-23 07:47 UTC, komagata requested changes

2021-02-23 07:47 UTC, komagata commented on app/controllers/api/notifications/unread_controller.rb
> +class API::Notifications::UnreadController < API::BaseController
すいません、他のレビューで気づいた点をひとつ。

下記のようなAPIのテストがあるとよりよりかもです。

https://github.com/fjordllc/bootcamp/blob/master/test/integration/api/practices_test.rb

2021-02-23 10:19 UTC, MashioSano commented on app/controllers/api/notifications/unread_controller.rb
> +class API::Notifications::UnreadController < API::BaseController
@komagata 
APIのテストを書きましたので確認お願いします！ 🙏

2021-02-24 01:13 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-24 01:13 UTC, komagata commented on test/integration/api/notifications_test.rb
> +  test 'GET /api/notifications.json' do
👍

2021-02-24 01:13 UTC, merged