プラクティスをドラッグ&ドロップで並び替えられるようにした
fjordllc/bootcamp pull request #2264
Opened 2021-01-18 10:43 UTC by masuyama13

Ref: #2083 #2211 

## 概要

- 管理者のプラクティス一覧ページ上部に「プラクティス並べ替え」ボタンを追加
- プラクティス並べ替えページを新規作成し、ドラッグ&ドロップで並べ替えられるようにしました

2021-01-27 03:45 UTC, masuyama13 commented
@universato 
コードレビューをお願いします🙇

2021-01-27 13:21 UTC, universato commented
@masuyama13
これ、とても難しそうですね
試してみたのですが、大きく2点気になったことがあります。
-  移動させたあとに、リロードボタンを押すと、ちゃんと移動できてないことがある。
- 「プラクティス並び替え」ボタンを押した後に、ページ切り替えできない

1点目のメインの機能が高頻度で正常に動いてないと思うのですが、それはどうなのでしょう。

2021-01-28 00:36 UTC, masuyama13 commented
@universato 
fixturesをいじったせいだと思うのですが、DBリセットしてから動かしてもだめですかね？

2021-01-28 04:38 UTC, universato commented
ありがとうございます。DBリセットしたら、出来ました。
時間がかかるかもしれませんが、コード拝見していきます。
ところで、本番でリセットすることはないと思うのですが、これって手元でDBリセット以外の方法ってとれないのでしょうか。(data-migrate gemのREADME.mdを見て適当に`rails db:migrate:with_data`等すると途中でエラーがでてしまいます)

2021-01-28 04:59 UTC, masuyama13 commented
@universato 
はい、本番では`rake db:migrate:with_data`が実行されるようになっています（[DBのデータをmigrateする方法 · fjordllc/bootcamp Wiki](https://github.com/fjordllc/bootcamp/wiki/DB%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92migrate%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)）。
おっしゃるとおりローカルだとDBの状態が違うのでエラーが発生します。リセット以外の方法としては、`up`メソッドの中身をRailsコンソールから実行することで動かすことはできます。

2021-01-29 11:51 UTC, universato reviewed
ちゃんと動いていて、自分が言えることは些細なことかなという感じでした。
OKだと思います!

2021-01-30 21:34 UTC, universato commented on app/javascript/categories-practice.vue
> +      categoryId: this.id,
ちょっと見返してたら、気がついたことがあったので、コメントします。
Vueで、このあたりの`id`は使われてないようなので、消した方がいいだろうと思いました。
同じく、元をたどってJSやビューのファイルの`data-category-id`等も不要そうです。

2021-01-31 14:39 UTC, masuyama13 commented on app/javascript/categories-practice.vue
> +      categoryId: this.id,
ありがとうございます！
修正します。

2021-02-01 00:56 UTC, masuyama13 commented on db/data/20210118060304_add_position_to_categories_practices.rb
> +      Practice.all.find_each do |practice|
おっしゃる通りです。修正しました😀

2021-02-01 02:00 UTC, masuyama13 commented
@komagata 
コードレビューをお願いします。
（コードレビュー終了後、デザイン依頼予定です）

2021-02-02 04:16 UTC, komagata requested changes

2021-02-02 04:16 UTC, komagata commented on app/controllers/api/categories_practices/position_controller.rb
> +  wrap_parameters :categories_practice
👍

2021-02-02 04:16 UTC, komagata commented on app/javascript/categories-practice.vue
> +      combinations: JSON.parse(this.categoriesPractices),
コンポーネントを別のところでも使う時などを考えるとコンポーネントをマウントする方のファイルでJSONパースして、パース済みのをコンポーネントに渡すのがいいかも？

2021-02-02 04:16 UTC, komagata commented on config/routes.rb
> +    get "practices_sort", to: "courses/practices_sort#index"
下記のような感じで`courses/practices/sort`とかの方がいいかもです。
getだけの場合もなるべくresourceやresourcesを使った方がいい感じです。

[DHHはどのようにRailsのコントローラを書くのか \| POSTD](https://postd.cc/how-dhh-organizes-his-rails-controllers/)

2021-02-02 04:16 UTC, komagata commented on test/system/course/practices_sort_test.rb
> +  test '管理者がプラクティス並び替えページにアクセスする' do
他のsystem testもテスト名は英語だと思うのでできれば英語で統一したい感じです〜

2021-02-08 13:26 UTC, masuyama13 commented
@komagata 
レビューいただいた点について修正しましたので、再度ご確認よろしくお願いします🙇
（この後デザイン依頼予定です）

2021-02-08 15:39 UTC, komagata commented
@masuyama13 テストを再実行したら通りました〜

2021-02-08 15:42 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-08 15:42 UTC, komagata commented on app/javascript/categories-practice.js
> +            categoriesPractices: JSON.parse(categoriesPractices),
👍

2021-02-08 15:42 UTC, komagata commented
@masuyama13 次の水曜日ミーティングの後にマージしてリリースしたいと思います〜

2021-02-09 00:37 UTC, masuyama13 commented
@komagata 
ご確認ありがとうございます！
デザインがまだなので、後日改めてマージ依頼させてください😀

@machida 
こちら、デザインをお願いします🙏

2021-02-09 03:15 UTC, machida commented
@masuyama13 難しいやつ、対応ありがとうございました！！デザインやりますー💪

2021-02-09 04:01 UTC, machida commented
@komagata デザイン入れましたー コンフリクトがなかったので、PRの向け先を develop にしました。

2021-02-10 07:27 UTC, komagata commented
マージします〜

2021-02-10 07:27 UTC, merged