右カラムの最新の日報の表示数を20件にする
fjordllc/bootcamp pull request #2278
Opened 2021-01-26 06:15 UTC by gallardo16

## issue
https://github.com/fjordllc/bootcamp/issues/2150 に対応

## やったこと
実装前は最新の日報の表示数が10件でしたが、20件に修正しました。

2021-02-01 07:33 UTC, komagata commented
@gallardo16 CIが落ちているようです。
多分時々落ちるテストっぽいので再実行すれば治りそうです。CircleCIに入ってReturnとかReRunをやってみてください。

2021-02-01 08:10 UTC, gallardo16 commented
@komagata 
コメントありがとうございます。
落ちたテストはこのイシューの実装が原因でしたので、修正しました。

2021-02-01 08:26 UTC, gallardo16 commented
@masuyama13 
お疲れ様です〜
お手隙の際にコードレビューお願いします🙏

2021-02-02 04:18 UTC, komagata requested changes

2021-02-02 04:18 UTC, komagata commented on test/system/api/check/reports_test.rb
> +    assert page.all('.recent-reports-item')[0].has_css?('.recent-reports-item__checked')
これって10件が20件になっただけなのになんでここのテストに変更が必要になっちゃったんでしょう？

2021-02-02 06:03 UTC, gallardo16 commented on test/system/api/check/reports_test.rb
> +    assert page.all('.recent-reports-item')[0].has_css?('.recent-reports-item__checked')
@komagata 
すみません、説明不足でした。
#### チェックがあることを確認するテスト(59行目)について

20件に増やしたことにより、追加で表示されるようになった10件の日報の中に確認済(既にチェックされた状態)の日報も表示されるようになり、正確さを欠くテストになったためです。(下の画像は66行目のテスト失敗のスクショですが、既にチェックされた日報が表示されるようになったことが確認できます。)
修正前のテストのままだと、追加で表示されるようになった日報もテストの対象になります。そのため、範囲を絞るように修正しました。

#### チェックがないことを確認するテスト(66行目)について

こちらも上記のテストと同様な理由で、20件に増やしたことで通らないテストになったためです。
(下のスクショはVueの関係で、「確認を取り消したのにチェックがある」という失敗したときのものです)

![image](https://user-images.githubusercontent.com/62986803/106556060-1b0d7800-6562-11eb-9a09-a0b7ce8f880c.png)

2021-02-02 08:00 UTC, masuyama13 commented
@gallardo16 
すみません、レビュー依頼に今気がつきました！
私が気になった点としては @komagata さんと同じです。
申し訳ないのですが、ちょっと私が今週時間が取れなさそうなのと、komagata さんがすでにレビューしてくださっているので、私は外してもらった方がいいのかもしれません😅

2021-02-03 08:38 UTC, gallardo16 commented
@komagata 

@masuyama13 さんにレビューを頼んだのですが、既に駒形さんからレビューをいただいているような状態なので、マスヤマさん(または他の生徒)からのレビューはいただかなくてよろしいですか？

2021-02-03 23:27 UTC, bluerabbit commented on test/system/api/check/reports_test.rb
> +    assert page.all('.recent-reports-item')[0].has_no_css?('.recent-reports-item__checked')
```suggestion
    assert page.first('.recent-reports-item').has_no_css?('.recent-reports-item__checked')
```

か

```ruby
  assert page.has_no_css?('.recent-reports-item:first-child .recent-reports-item__checked')
```

に書き換えても良さそうです。(後者の構文は試してみないと自身無い)

2021-02-04 08:11 UTC, gallardo16 commented on test/system/api/check/reports_test.rb
> +    assert page.all('.recent-reports-item')[0].has_no_css?('.recent-reports-item__checked')
ご指摘ありがとうございます。
後者でも通りました。

2021-02-04 10:00 UTC, komagata commented on test/system/api/check/reports_test.rb
> +    assert page.all('.recent-reports-item')[0].has_css?('.recent-reports-item__checked')
@gallardo16 なるほどです〜

2021-02-04 10:01 UTC, komagata commented
@gallardo16 @masuyama13 すいません、僕は先にレビューしちゃったからですよね。
今回は僕のレビューだけとしちゃいましょう〜。

2021-02-04 10:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-04 10:07 UTC, merged