提出物一覧をVue.jsで非同期にした
fjordllc/bootcamp pull request #2280
Opened 2021-01-27 03:09 UTC by hogucc

ref #2178 

## 概要
提出物一覧の全て、未チェック、未返信、自分の担当タブをVue.jsで非同期に読み込むようにした

## やったこと
- 提出物一覧の全て、未チェック、未返信、自分の担当タブの読み込みをVue.jsで非同期化
- ページャーを[vuejs-paginate](https://github.com/lokyoung/vuejs-paginate)を用いて実装
  - products.vueのページャー関連の処理は[通知一覧をVue.jsで非同期にしたPR](https://github.com/fjordllc/bootcamp/pull/2260)と実装内容を合わせています。
- product_checker.vueをproduct.vueの子コンポーネントに変更

2021-01-31 14:39 UTC, hogucc commented
@Chi-rr 
お手すきの際にコードレビューをお願いいたします🙇‍♀️
（※ コードレビューは運用上、現在システム開発に参加されている生徒の方にお願いすることになっています。が、今回は特別にご本人からレビュワーの経験を積みたいというお話があったので、レビューを担当していただくことになりました。）

2021-02-08 00:55 UTC, hogucc commented
@Chi-rr こちらできれば今週の水曜日までにレビューいただけると助かります💦難しい場合もご連絡いただけるとありがたいです🙏

2021-02-08 01:18 UTC, Chi-rr commented
@hogucc 
遅くなってしまい申し訳ありません🙇‍♀️🙇‍♀️
本日中に確認させていただきます🙌

2021-02-08 14:51 UTC, Chi-rr reviewed
遅くなってしまい申し訳ありません🙇‍♀️レビューいたしました！
全体的に良さそうで、少し気になった点にコメントさせていただきました🤲
またご確認いただけると幸いです！

2021-02-08 14:51 UTC, Chi-rr commented on app/javascript/product.vue
> +          .thread-list-item-meta__comment-count-value （{{product.comments.size}}）
こちらだけスペースが無いかもです！
```suggestion
          .thread-list-item-meta__comment-count-value （{{ product.comments.size }}）
```

2021-02-08 14:51 UTC, Chi-rr commented on app/javascript/products.vue
> +        product(v-for="(product, index) in products"
index利用されていなさそうなので、削除できますかね？？
```suggestion
        product(v-for="product in products"
```

2021-02-08 14:51 UTC, Chi-rr commented on app/javascript/products.vue
> +        });
`c`はどういう変数でしたでしょうか？
`product`や`p`でもわかりやすいかなと思いました！

2021-02-08 14:51 UTC, Chi-rr commented on app/javascript/products.vue
> +    }
こちらの`location.href = location.href`は、vuejs-paginateの実装上必要なんでしたっけ？👀

2021-02-08 14:51 UTC, Chi-rr commented on test/system/product/not_responded_test.rb
> +require 'minitest/mock'
こちらってなぜrequireしているんでしょうか？？👀

2021-02-10 01:10 UTC, hogucc commented on app/javascript/products.vue
> +        product(v-for="(product, index) in products"
削除しました！

fb44480

2021-02-10 01:11 UTC, hogucc commented on app/javascript/products.vue
> +        });
`product`に修正しました！

1b04a9f

2021-02-10 01:13 UTC, hogucc commented on test/system/product/not_responded_test.rb
> +require 'minitest/mock'
元々products_test.rbにあったテストを別ファイルに分けたときに、そのままコピーしていたのを消し忘れてました💦
削除しました！

f24dcb6

2021-02-10 01:41 UTC, hogucc commented on app/javascript/products.vue
> +    }
はい、そうです！ページャーの2ページ目以降がクリックされたときはpushStateではURLの履歴を追加しているのですが、pushStateはページの読み込みまでは行いません。なので、ブラウザの戻る・進むボタンを押したときにURLは切り替わるけど、ページが遷移しない状態になります。そこで戻る・進むが押されたことをwindow.onpopstateイベントで検知して、現在のページへ画面遷移する（`location.href = location.href`）ようにしています。
もっと他に良い書き方あるのかもと悩んだのですが、bootcampの他のファイルでも`location.href = location.href`を使っているところがあったので、この書き方を選択しました。

2021-02-10 01:47 UTC, hogucc commented
@Chi-rr 
レビューいただきありがとうございます！
ご指摘点を修正しましたので、お手すきの際にご確認お願いいたします。

またご指摘以外で以下の点を修正しました。どちらも[通知一覧をVue.jsで非同期にした](https://github.com/fjordllc/bootcamp/pull/2260)PRとコードを統一するために行った修正です。
こちらも合わせてご確認お願いいたします🙏

87cce12
5118755

2021-02-10 03:41 UTC, Chi-rr commented on app/javascript/products.vue
> +    }
>pushStateはページの読み込みまでは行いません。なので、ブラウザの戻る・進むボタンを押したときにURLは切り替わるけど、ページが遷移しない状態になります。

>戻る・進むが押されたことをwindow.onpopstateイベントで検知して、現在のページへ画面遷移する（location.href = location.href）ようにしています。

なるほどです〜👀 勉強になります🙏

2021-02-10 03:52 UTC, Chi-rr approved these changes
@hogucc 
修正ありがとうございます！
追加分合わせて確認いたしました！LGTMです🙆‍♀️

2021-02-10 08:08 UTC, hogucc commented
@Chi-rr 
ご確認ありがとうございました✨

@machida 
ページャーを作り変えたので以前のページャーの見た目と同じにするために、_pagination.sassとproducts.vueにスタイルの定義を追加したのですが、定義場所や内容に問題がないかご確認いただけないでしょうか。
CSSの追加になるので、machidaさんに確認いただいたほうが良いと思い、ご連絡しました。

※ 以下のPRでも同様の修正をしています。
- [通知一覧をVue.jsで非同期にした](https://github.com/fjordllc/bootcamp/pull/2260/files)
- [日報一覧(全体・未チェック)をVue.jsで非同期にした](https://github.com/fjordllc/bootcamp/pull/2286/files)

2021-02-10 16:19 UTC, MashioSano commented
@machida  @hogucc 
hogucc さんの説明にいくつか補足させていただきますー
まず、デザインに影響のあるファイルは2つあります。
1つ目は、_pagination.sassです。
_pagination.sassは1月ほど前、雑談部屋で私が町田さんの指示を受けながら修正したファイルになります。
町田さんのアドバイス通りに記述したので間違いはないと思われますが、念のため確認していただけると助かります。

2つ目は、products.vue(もしくはnotifications.vue, reports.vue)です。
ここの<style>内に仮のデザインを入れています。
https://github.com/fjordllc/bootcamp/blob/5118755bbd1f9d7c619a50fd5c51830bf23f388a/app/javascript/products.vue#L174-L182
<code>.pager-disable</code>は無効なページャーのボタンにつけるクラスになります。
https://github.com/fjordllc/bootcamp/blob/5118755bbd1f9d7c619a50fd5c51830bf23f388a/app/javascript/products.vue#L16-L19
kaminariのページャーのボタンに寄せるためには、クリックできないボタンは表示させないようにしたかったので、この仮デザインを作成しました。
<code>outline: none; </code>ですが、これがないとページャーのボタンをクリックした後に、ボタンに青い枠が表示されるため、記述しました。

また私とuniversatoさんのPRでは、<code>is-top</code>,  <code>is-bottom</code>クラスを外しています。
https://github.com/fjordllc/bootcamp/blob/6e0df0f219495a9845680d4c3d62bb363079d975/app/javascript/notifications.vue#L2-L6
雑談部屋で指示を受けながらファイルを修正した際に、<code>is-top</code>,  <code>is-bottom</code>は共通化させたいので、外しておいてくださいと言われた記憶があります。(PRの説明にすぐに書いておくべきでした...)
以上補足になりますー
お手隙の際に確認していただけると助かります！

2021-02-11 01:40 UTC, hogucc commented
@MashioSano 
情報共有ありがとうございます！
`is-top`, `is-bottom`クラスは後ほど私も外します！

2021-02-12 09:54 UTC, hogucc commented
> @machida
ページャーを作り変えたので以前のページャーの見た目と同じにするために、_pagination.sassとproducts.vueにスタイルの定義を追加したのですが、定義場所や内容に問題がないかご確認いただけないでしょうか。
CSSの追加になるので、machidaさんに確認いただいたほうが良いと思い、ご連絡しました。

@machida 
リマインドさせていただきます🙏
上記のコメントでCSSのレビューを依頼いたしましたので、お手すきの際にご確認いただければと思います🙇‍♀️
補足として、デザインに影響あるファイルについてSanoさんがこのPR上でmachidaさん宛にコメントをくださっているのでそちらも併せてご確認いただけると助かります！

2021-02-12 11:26 UTC, machida commented
@hogucc ご連絡ありがとうございますー！確認します🙋‍♂️

2021-02-18 02:07 UTC, machida commented
@hogucc @komagata 

こちら確認しました！
LGTMですー

今回、ページャーのスタイルをいじってて、不要なリンクを非表示から、disabled な見た目にして、クリックができない、にしたほうが、ページャーのレイアウトの変更が発生しなくて使い心地がよくなるので（特にSPAの場合）、そのようにしました。このPRの提出物一覧ではそのようにしたのですが、別のページでは従来の表示になるので、それは別PRで動作を統一していきたいと思います。

2021-02-18 06:40 UTC, hogucc commented
@machida 

> 今回、ページャーのスタイルをいじってて、不要なリンクを非表示から、disabled な見た目にして、クリックができない、にしたほうが、ページャーのレイアウトの変更が発生しなくて使い心地がよくなるので（特にSPAの場合）、そのようにしました。このPRの提出物一覧ではそのようにしたのですが、別のページでは従来の表示になるので、それは別PRで動作を統一していきたいと思います。

承知しました！ご対応ありがとうございます！

@komagata 
お手すきの際にコードレビューをお願いいたします🙇‍♀️

2021-02-22 06:08 UTC, machida commented
@hogucc @komagata masterをrebaseして、ページャーのズレが解消されているのを確認しました！こちらでマージお願いします🙏

![image](https://user-images.githubusercontent.com/168265/108669036-9b027e80-751f-11eb-9671-05a7a6e8e743.png)

![image](https://user-images.githubusercontent.com/168265/108669061-a5247d00-751f-11eb-8fe3-649a3b3f94fd.png)

![image](https://user-images.githubusercontent.com/168265/108669078-ac4b8b00-751f-11eb-80ae-0ec25121106e.png)

![image](https://user-images.githubusercontent.com/168265/108669100-b3729900-751f-11eb-8e1f-e0be704d9676.png)

2021-02-22 10:13 UTC, hogucc commented
@machida 
ご対応ありがとうございます✨

@komagata 
こちらコードレビューをお願いいたします🙇‍♀️

2021-02-23 07:46 UTC, komagata requested changes

2021-02-23 07:46 UTC, komagata commented on app/controllers/api/products/not_responded_controller.rb
> +class API::Products::NotRespondedController < ApplicationController
https://github.com/fjordllc/bootcamp/blob/master/test/integration/api/practices_test.rb

こういう感じのAPIのテストがあるといいかもです。

2021-02-27 14:04 UTC, hogucc commented on app/controllers/api/products/not_responded_controller.rb
> +class API::Products::NotRespondedController < ApplicationController
@komagata 
以下のコミットでテストを追加しました！ご確認お願いいたします🙏
227c93f

また、テストを追加した際に、APIのコントローラーがAPI::BaseControllerを継承していないことに気づいて修正しました。
55e860e

2021-03-01 15:01 UTC, komagata commented on app/controllers/api/products/not_responded_controller.rb
> +class API::Products::NotRespondedController < ApplicationController
> また、テストを追加した際に、APIのコントローラーがAPI::BaseControllerを継承していないことに気づいて修正しました。

ありがとうございます！

2021-03-01 15:04 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

APIのテストいい感じです、ありがとうございます〜

2021-03-01 15:04 UTC, merged

2021-03-02 23:28 UTC, JunichiIto commented on app/controllers/api/products/not_responded_controller.rb
> +    @products = Product.not_responded_products.list.page(params[:page])
@hogucc @komagata 
https://github.com/fjordllc/bootcamp/issues/2398 の調査をしていて気づいたんですが、今の実装だとたぶん提出日順ではなくcreated_at順に並びますね。（詳しく見てませんがVue.js側でソートとかしてないですよね？）

https://github.com/fjordllc/bootcamp/blob/master/app/models/product.rb#L69

https://github.com/fjordllc/bootcamp/blob/master/app/models/product.rb#L38

そもそも論になりますが、データを絞り込むscopeと並び順を指定するscopeは別々にしておかないと、ユースケースが限定されて再利用性が低くなります。
なので、今のscopeの設計から見直した方がいいように思いました。

2021-03-03 03:32 UTC, hogucc commented on app/controllers/api/products/not_responded_controller.rb
> +    @products = Product.not_responded_products.list.page(params[:page])
@JunichiIto 
cc: @komagata 
Vue.js側でのソートは特に行っていないので、created_at順に並びますね💦
scopeも再検討するのがよさそうです。

そもそも「自分の担当」タブができたいまタブの構成自体が運用と合っていない気がするので、そこから考え直したほうが良さそうと思いました。
[メンターが割り振られてない提出物をわかりやすくしてほしい · Issue #2005](https://github.com/fjordllc/bootcamp/issues/2005)