日報の一覧(全体・未チェック)をVue.js化
fjordllc/bootcamp pull request #2286
Opened 2021-02-01 19:25 UTC by universato

Issue #2148 

[vuejs-paginate](https://github.com/lokyoung/vuejs-paginate)を用い、日報の一覧(メンターの未チェックページ含む)をVue.js化させました。

2021-02-03 00:01 UTC, universato commented
@gallardo16 

他の通知や提出物の一覧のVue.jsの非同期化のPRは一覧の非同期化をしてない方がレビューしているので、
可能であればガヤルドさんにレビューをお願いしたいです。よろしくお願いします!

2021-02-03 08:24 UTC, gallardo16 commented
@universato 

了解です！
時間がかかるかもしれませんが、レビューさせていただきます🙏

2021-02-12 10:01 UTC, gallardo16 commented
@universato 
レビューに時間がかかってしまい申し訳ありません。

一点気になることがあります。
日報一覧ページにおいて、個々の日報にあるコメントのユーザアイコンをクリックしてもエラーになってしまい、ユーザーページに遷移しません。もしかしたら、私が色々試しで変更したからかもしれないです。
お願いします🙏

2021-02-12 12:37 UTC, universato commented
@gallardo16
ご連絡ありがとうございます。
量多いし、時間かかるかもしれないので、今回みたいに五月雨式だと嬉しいです。

コメントのユーザーアイコンのリンクを修正した上で([diff](https://github.com/fjordllc/bootcamp/compare/bc0d2024585923859692302a7b5ba1eb8e576be0..228fd5c759b3f4a6b94310afb492844f4bc6cc88))、
未チェックの日報の一覧の方にコメントが表示されてなかったので、表示させました。

ご確認よろしくお願いします。

2021-02-12 13:46 UTC, gallardo16 commented
@universato 
確認できました！修正ありがとうございます。
>量多いし、時間かかるかもしれないので、今回みたいに五月雨式だと嬉しいです。

了解しました！その都度コメントさせて頂きます。

ついでに質問があります。
Vuexの`store`が`import`されてますが、必要なのか気になりました。
よろしくお願いします🙏

2021-02-13 00:47 UTC, universato commented
`store`は不要だったので、削除しました!

2021-02-13 08:35 UTC, gallardo16 commented
@universato 
コメント数が表示されていないかもです。ご確認よろしくお願いします🙏

- コメント数が表示されていない
![image](https://user-images.githubusercontent.com/62986803/107845739-4a08d100-6e21-11eb-8109-08a7d3d67fec.png)
---
- 実際はコメント数が表示される

![image](https://user-images.githubusercontent.com/62986803/107845752-5bea7400-6e21-11eb-9d3d-6230557c5774.png)

2021-02-13 08:55 UTC, gallardo16 reviewed
すみません、最後に細かい点をまとめてコメントしました。
全体的にVueファイルのscriptタグ内で、最後のプロパティ(要素)の後にもコンマがあるのが気になりました。
ご確認よろしくお願いします🙏

2021-02-13 10:07 UTC, universato commented on app/javascript/report.vue
> +          comment-user-icon(v-for="(comment, index) in report.comments" :key="comment.id" :comment="comment")
`index`を削除し、スタイルも少し変更しました。

2021-02-13 10:07 UTC, universato commented on app/javascript/unconfirmed_link.vue
> +    openUnonfirmedItems(){
修正しました

2021-02-13 10:13 UTC, universato commented
> コメント数が表示されていないかもです。ご確認よろしくお願いします🙏

ありがとうございます。コメント数を表示させました。

> 全体的にVueファイルのscriptタグ内で、最後のプロパティ(要素)の後にもコンマがあるのが気になりました。

これは意図的ですが、(絶対に変更する必要があるとは思ってないものの)`script`タグ内の方はとりあえず削除しました。
末尾のカンマは、何か要素を追加したときに余計な差分をださないためにつけていて、`reports`の`data`は消すと差分が目立つと思ったので、そのままです。

2021-02-13 10:56 UTC, gallardo16 commented
確認しました！カンマの件はそういう意図があったのですね！

すみませんあと一点だけありました。
コメント数を指摘した際の画像をみて気づいたのですが、日報一覧の個々の日報おいて、
「日報作成ユーザー名、日報作成日」と「コメント数、コメントユーザーアイコン...」の表示が逆だと思いました。
よろしくお願いします🙏

2021-02-13 11:17 UTC, universato commented
@gallardo16
> 「日報作成ユーザー名、日報作成日」と「コメント数、コメントユーザーアイコン...」の表示が逆だと思いました。

全く気がつきませんでした。修正しました。
よく見ていただいて、ありがとうございます💪🏼

2021-02-13 12:30 UTC, gallardo16 commented on app/javascript/report.vue
> +  .thread-list-item
WIPか否かのクラスの条件式がないので、一覧画面でWIP提出時の日報タイトルの色が変わりません。

2021-02-13 13:20 UTC, universato commented on app/javascript/report.vue
> +  .thread-list-item
修正しました

2021-02-14 02:35 UTC, gallardo16 commented on app/javascript/report.vue
> +            a.thread-list-item__title-link.js-unconfirmed-link(:href="report.url") {{ report.user.daimyo ? '★' + report.title : report.title }}
`itemprop`属性が抜けていますが、いらないんでしょうか？

2021-02-14 04:57 UTC, universato commented on app/javascript/report.vue
> +            a.thread-list-item__title-link.js-unconfirmed-link(:href="report.url") {{ report.user.daimyo ? '★' + report.title : report.title }}
使われてないと考え、既にある`itemprop`の方を削除することにしました

2021-02-14 07:41 UTC, gallardo16 commented
修正確認しました！LGTMです✨🙆‍♂️
迅速に対応していただきありがとうございました。

2021-02-16 04:40 UTC, universato commented
@komagata
レビューお願いいたします

2021-02-16 21:41 UTC, komagata commented on app/views/api/reports/index.json.jbuilder
> +json.reports @reports do |report|
余裕があればAPI系のテストがあると良いかもです。

既存のAPIのテスト（一部しかないですが）は`test/integration/api/*_test.rb`にあります。
これらのようにざっくりな感じで大丈夫です。

2021-02-17 12:52 UTC, universato commented on app/views/api/reports/index.json.jbuilder
> +json.reports @reports do |report|
`test/integration/api/users_test.rb`を真似して、テストを追加しました。

2021-02-22 06:43 UTC, machida commented
お、なんかミスったぽい
戻しますー

2021-02-22 07:07 UTC, machida commented
@komagata @universato 

ページャーのデザイン崩れが修正されているのを確認しました！！

![image](https://user-images.githubusercontent.com/168265/108673950-db65fa80-7527-11eb-996d-fffbe4d3ae13.png)

![image](https://user-images.githubusercontent.com/168265/108673976-e587f900-7527-11eb-9a0c-0f8b0d7b1b84.png)

![image](https://user-images.githubusercontent.com/168265/108673999-ede03400-7527-11eb-982a-ed4971e96cd6.png)

![image](https://user-images.githubusercontent.com/168265/108674017-f6386f00-7527-11eb-8d23-02b507665b90.png)

2021-02-23 07:43 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-23 07:44 UTC, komagata commented
@machida こちらはデザイン的には完了ですか？

2021-03-05 21:20 UTC, universato commented
@komagata

すみません、現行の取り出し方に合わせた方がいいと思い、現行の既存メソッド`comentted_users`を用いる形で3行ほどリファクタリングしました。

2021-03-06 16:30 UTC, komagata commented
@universato コンフリクトの解消お願いします〜

2021-03-08 20:40 UTC, universato commented
@komagata 
コンフリクト、解消しました。よろしくお願いします。

2021-03-09 07:11 UTC, komagata requested changes

2021-03-09 07:11 UTC, komagata commented on app/controllers/api/reports_controller.rb
> +    @search_words = params[:word]&.squish&.split(/[[:blank:]]/)&.uniq
文字検索のAPIってどこで使うんでしたっけ？

2021-03-09 07:11 UTC, komagata commented on app/views/api/reports/index.json.jbuilder
> +    json.comments do
コメントなどある程度共通なものはpartialで共通化しちゃうのがいいかも

2021-03-09 07:11 UTC, komagata commented on test/integration/api/reports_test.rb
> +    get api_reports_path(format: :json),
👍

2021-03-09 09:17 UTC, universato commented on app/controllers/api/reports_controller.rb
> +    @search_words = params[:word]&.squish&.split(/[[:blank:]]/)&.uniq
URLの直接入力で使います。特に検索窓のようなものはないという認識です。

2021-03-09 20:19 UTC, universato commented on app/controllers/api/reports_controller.rb
> +    @search_words = params[:word]&.squish&.split(/[[:blank:]]/)&.uniq
プラクティスで絞るとwordクエリがでるのでURLを注意深く見た人は機能に気がついたかもしれませんが、
日報で絞ってワード検索できれば十分で、実際のところこの単語検索は使われていないと思うので削除しました。
> 1db6d65

2021-03-10 04:39 UTC, komagata requested changes

2021-03-10 04:39 UTC, komagata commented on app/views/api/reports/_report.json.jbuilder
> +json.id report.id
👍

2021-03-10 04:39 UTC, komagata commented on app/views/api/reports/_comments.jbuilder
> +json.hasAnyComments comments.present?
partialとしてはコメントがつくもの全部（提出物とかお知らせとか）に共通に使えると思うので、別のディレクトリにおくのがいいかもです〜

2021-03-10 10:53 UTC, universato commented on app/views/api/reports/_comments.jbuilder
> +json.hasAnyComments comments.present?
@komagata 変更したのでご確認よろしくお願いします。 > cffc83f

2021-03-11 06:45 UTC, komagata requested changes
コンフリクトの解消をお願いします〜

2021-03-11 11:14 UTC, universato commented
@komagata 
コンフリクト解消しました。ご確認よろしくお願いします。

2021-03-13 03:10 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

長いIssueお疲れ様です！

2021-03-13 03:10 UTC, komagata commented on app/views/api/reports/index.json.jbuilder
> +    json.partial! "api/users/user", user: report.user
👍

2021-03-13 03:10 UTC, komagata commented on app/views/api/reports/unchecked/index.json.jbuilder
> +  json.partial! "api/comments/user_icons", comments: report.comments
👍

2021-03-13 03:10 UTC, komagata commented on test/integration/api/reports_test.rb
> +  fixtures :reports
👍

2021-03-13 03:10 UTC, merged