右カラムの最新の日報のチェックのアイコンを変更
fjordllc/bootcamp pull request #2299
Opened 2021-02-04 16:29 UTC by machida

取り急ぎ、右カラムのチェックのデザインをメンターがチェックしたものとわかるように変更しました。右カラムにタイムライン的なものを出すなど、右カラムの使い方の変更は別で考えていきたいと思います。

![image](https://user-images.githubusercontent.com/168265/106923493-781b5080-6751-11eb-9acd-6e274c2d0438.png)

2021-02-08 10:32 UTC, komagata commented
@machida 多分こちらmasterからブランチを作ってdevelopにPRを送ってるので差分が大きくなっちゃってるじょうたいかもです。

2021-02-08 10:33 UTC, komagata requested changes
@machida 多分こちらmasterからブランチを作ってdevelopにPRを送ってるので差分が大きくなっちゃってるじょうたいかもです。

2021-02-10 14:32 UTC, machida commented
@komagata 変更部分のコミットだけpickしたものに差し替えましたー

2021-03-16 12:58 UTC, komagata approved these changes
ありがとうございます！

2021-03-16 12:59 UTC, merged