提出物個別ページのメンターメモが画面にくっついてくるようにした
fjordllc/bootcamp pull request #2300
Opened 2021-02-04 16:44 UTC by machida

提出物個別ページのメンターメモ、直近の日報が画面にくっついてくるようにしました。
全体が見れるように、メンターメモ、直近の日報にはそれぞれ画面をはみ出したときに上下のスクロールが表示されるようにしてあります。

<img width="1118" alt="貼り付けた画像_2021_02_05_1_42" src="https://user-images.githubusercontent.com/168265/106925402-68047080-6753-11eb-94cb-93fbe176d718.png">

<img width="871" alt="貼り付けた画像_2021_02_05_1_43" src="https://user-images.githubusercontent.com/168265/106925610-96824b80-6753-11eb-9a75-1285a363e1e4.png">

2021-02-08 10:35 UTC, komagata requested changes

2021-02-08 10:35 UTC, komagata commented on app/assets/stylesheets/blocks/side/_side-tabs.sass
> +  +position(sticky, top 3.125rem)
最終行に改行がない状態かもです

2021-02-08 10:35 UTC, komagata commented
@machida 修正ありがとうございます！！

2021-02-10 06:11 UTC, machida commented on app/assets/stylesheets/blocks/side/_side-tabs.sass
> +  +position(sticky, top 3.125rem)
@komagata 修正しました！

2021-02-10 07:46 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-10 07:46 UTC, merged