滅多に使わないネガティブなリアクションを消す
fjordllc/bootcamp pull request #2310
Opened 2021-02-09 03:26 UTC by harukus

# issue
issue: #2214 に対応
# やること
<img width="222" alt="スクリーンショット 2021-02-09 12 21 30" src="https://user-images.githubusercontent.com/52342576/107311268-5f07fc00-6ad1-11eb-9a72-8ab5f22bedfb.png">
日報等で使用するリアクションボタンの「👎」と「:confused:」を「🙏」と「🙌」に置き換える。

2021-02-11 03:17 UTC, MashioSano reviewed
<code>app/models/reaction.rb</code>の変更内容は良いと思いますー！
ファイルの変更がないコミットが含まれているのが気になりましたー
https://github.com/fjordllc/bootcamp/pull/2310/commits/6f4fbbfa93e086cb9f516f88135215e2e44b2f8a

2021-02-11 06:58 UTC, harukus commented
@MashioSano 
確認ありがとうございます！
変更のないコミットの件ですが、こちらの[チーム開発の作業手順](https://bootcamp.fjord.jp/pages/305)に「何もしていない空のコミットをする」とあるのでこのようにしてあります。
もし必要ないものでしたら教えていただけると幸いです:bow:
<img width="728" alt="スクリーンショット 2021-02-11 15 51 33" src="https://user-images.githubusercontent.com/52342576/107609048-1c852180-6c81-11eb-948c-0df318d513cb.png">

2021-02-11 07:20 UTC, MashioSano approved these changes
チーム開発の作業手順に書いてあったんですね！
すいません 見落としていました🙇‍♂️
LGTMです！

2021-02-11 07:24 UTC, harukus commented
いえいえ！ありがとうございます:smile:

2021-02-11 09:53 UTC, komagata commented
@harukus @MashioSano すみません、ドキュメントのかかれ方がよくなかったかもしれません。

空のPRを初めに作ると言うのは良い習慣（既に着手したとわかるので）ではありますが、やらなきゃいけないものってわけではないです。

該当のドキュメントを修正しておきました〜

2021-02-11 09:55 UTC, komagata commented
@harukus 下記に書いたようにgit flow（masterからブランチを作って開発する方式）に変更したのでこちらのPRの向き先をmasterに変更しました。（旧ルールの通りにdevelopに向かっているPRを修正して回っています）

https://fjord.slack.com/archives/C02NXNUGP/p1613036557170100

ローカルの内容と差があるとぶつかるかもしれませんが、ローカルでもmasterからrebaseしてやると治ると思います。

2021-02-11 09:55 UTC, harukus commented
@komagata 
なるほどです！ありがとうございます！

2021-02-11 09:57 UTC, komagata requested changes

2021-02-11 09:57 UTC, komagata commented on app/models/reaction.rb
> +    raised_hands: 1,
本番環境には過去のデータがあるので、こうするとthumsdownしたはずがraised_handsしたことになっちゃうので、別の番号として登録した方が良さそうです〜。prayも同じくです。

2021-02-12 09:21 UTC, harukus commented on app/models/reaction.rb
> +    raised_hands: 1,
ごめんなさい、全然分からないので質問させてください。
この番号って何の番号でしょうか。

2021-02-12 09:25 UTC, JunichiIto commented on app/models/reaction.rb
> +    raised_hands: 1,
DBに保存されるenumの値ですね。Railsのenumに関してはこちらを参照。
https://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

使用例としては

```ruby
class Conversation < ActiveRecord::Base
  enum status: { active: 0, archived: 1 }
end
```

と同じパターンだと思います〜。

2021-02-13 03:50 UTC, harukus commented on app/models/reaction.rb
> +    raised_hands: 1,
@JunichiIto 
ありがとうございます。
schema.rbのreactionsテーブルを見たら`kind`というカラムがあり、ここに数字が入るということがわかりました:bow:

2021-02-13 07:11 UTC, harukus commented
@komagata 
- ネガティブな絵文字の非表示についてですが、今回の変更で押したことさえも見ることができなくなっています。

**変更前：**
<img width="600" alt="スクリーンショット 2021-02-13 15 15 47" src="https://user-images.githubusercontent.com/52342576/107844262-4b340100-6e15-11eb-9436-25025a40e7da.png">

**変更後：**
<img width="600" alt="スクリーンショット 2021-02-13 15 16 10" src="https://user-images.githubusercontent.com/52342576/107844266-4ec78800-6e15-11eb-9ff6-ffa6060fa9c8.png">
パネルにはポジティブなものだけにしつつ、押したリアクションは残しておく、という方法がわかりませんでした:bow:

2021-02-13 16:05 UTC, komagata commented
> パネルにはポジティブなものだけにしつつ、押したリアクションは残しておく、という方法がわかりませんでした🙇

消したネガティブなものは残さなくて大丈夫です〜

2021-02-14 07:46 UTC, harukus commented
@komagata 
なるほどです。ありがとうございます:bow:
改めてレビューお願いいたします。

2021-02-16 02:58 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-16 02:58 UTC, merged