担当していないのに自分の担当タブが表示される
fjordllc/bootcamp pull request #2315
Opened 2021-02-10 08:01 UTC by gallardo16

2021-02-11 06:53 UTC, gallardo16 commented
@machida
「0 の場合は目立たない見た目」のデザインをよろしくお願いいたします🙇‍♂️

2021-02-11 10:02 UTC, komagata commented
@gallardo16 下記に書いたようにgit flow（masterからブランチを作って開発する方式）に変更したのでこちらのPRの向き先をmasterに変更しました。（旧ルールの通りにdevelopに向かっているPRを修正して回っています）

https://fjord.slack.com/archives/C02NXNUGP/p1613036557170100

ローカルの内容と差があるとぶつかるかもしれませんが、ローカルでもmasterからrebaseしてやると治ると思います。

2021-02-11 10:03 UTC, komagata commented
このブランチはmaster向きにしても全然変わりませんでしたね〜🙆‍♂️

2021-02-11 10:04 UTC, machida commented
デザインの変更は別Issueで対応になりました。

2021-02-11 10:08 UTC, komagata commented
:memo: https://fjord.slack.com/archives/C02NXNUGP/p1613037657173400

2021-02-11 11:00 UTC, komagata commented
@gallardo16 上記の通りですので、レビュー依頼をどなたかにお願いします〜

2021-02-12 04:58 UTC, gallardo16 commented
@machida @komagata 
了解です！

@hogucc 
お手隙の際にコードレビューをお願いいたします🙏

2021-02-12 05:33 UTC, hogucc commented
@gallardo16 
> お手隙の際にコードレビューをお願いいたします🙏

承知しました！今日はちょっと私用で難しいかもですが、遅くても明日には確認できると思いますので少々お待ちください🙏

2021-02-13 06:52 UTC, hogucc commented
@gallardo16 
コード確認しました！LGTMです👍

コードは大丈夫なのですが、コミットメッセージの書き方が少し気になりました！
今回の分は修正しなくて大丈夫なのですが、今後コミットメッセージを書くときの参考情報として以下の記事を載せておきます〜
[コミットメッセージの書き方. 適切な情報を残そう | by risacan | Medium](https://medium.com/@risacan/%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9-64aeadd92057)

コミットメッセージを適切に書くことは未来の自分を助けることにも繋がるので、もしよかったら読んでみてください！
今回の場合だと、`05519f8`のコミットメッセージはどんなバグを修正したのかがコミットメッセージから伝わると良さそうと思いました！（`53b20bd`のkomagataさんのコミットメッセージとほぼ一緒になりそうですが😅）

2021-02-13 07:16 UTC, gallardo16 commented
@hogucc 
レビューありがとうございます！
確かにコミットメッセージが大雑把でした。今後は、他の人(自分も含めて)が見てもわかりやすいように改善していきます〜
参考リンクもありがとうございます🙇‍♂️

@komagata 
コードレビューをよろしくお願いいたします。

2021-02-13 16:08 UTC, komagata requested changes

2021-02-13 16:08 UTC, komagata commented on app/models/product_callbacks.rb
> +    Cache.delete_self_assigned_product_count(product.checker_id)
これってこっち（下記）に書いたからいらないかも？（ちょっと確かめてみてください〜）

https://github.com/fjordllc/bootcamp/pull/2315/files#diff-aa055f17937e9bfdcdd1b8bd3fe76c7cb960c967747b519f0fc1c04c3253dafaR99

2021-02-14 06:48 UTC, hogucc approved these changes

2021-02-14 07:36 UTC, gallardo16 commented on app/models/product_callbacks.rb
> +    Cache.delete_self_assigned_product_count(product.checker_id)
確かめた結果、不要だったので削除しました。

2021-02-16 02:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-16 02:52 UTC, merged