登録者の多いユーザータグ一覧を作成
fjordllc/bootcamp pull request #2324
Opened 2021-02-10 17:27 UTC by universato

2021-02-11 00:53 UTC, universato commented
@tam-03 

(デザイン面を除いて)機能面を中心にレビューをお願いしたいです。

【留意点】
デザインが入ってないので、選択して反転させないので文字が非常に見えにくいです。(反転させても見にくいが。)
HTMLのクラスが`.recent-reports`になっているところがありますが、machidaさんがデザインを入れるタイミングで変更してもらう予定です。自分がクラスを変更してCSSにも変更を加えると、変更点がわかりにくくなると考えたため、`.recent-reports`のままにしています。

また、最初はDBにユーザータグがないと思いますので、ご自身で追加されるか、DBリセットする等が必要です。

2021-02-11 05:07 UTC, tam-03 commented
@universato 

無知ですみません。。教えて頂きたいのですが、
この機能の動きを見たい場合は、`popular-tags`こちらのブランチに移動してから、動きを見たりテストを実行してみたりという事を行えば良いのでしょうか？😢

お手数お掛けして申し訳ございません。

2021-02-11 05:19 UTC, universato commented
@tam-03 

質問ありがとうございます

[Githubで特定のpull requestをローカルに持ってくる \- Qiita](https://qiita.com/tarr1124/items/d807887418671adbc46f)
「PR ローカルに」で調べてでてきた、この記事を参考にするとできるかと思います。

```sh
git fetch origin pull/2324/head:popular-tags
git checkout popular-tags
```

2021-02-11 05:35 UTC, tam-03 commented
@universato 
ご丁寧にありがとうございます！🙇🏻‍♂️
ちゃんと動きました！
早速レビューに取り掛かります。ありがとうございます。

2021-02-11 10:04 UTC, komagata commented
@universato 下記に書いたようにgit flow（masterからブランチを作って開発する方式）に変更したのでこちらのPRの向き先をmasterに変更しました。（旧ルールの通りにdevelopに向かっているPRを修正して回っています）

https://fjord.slack.com/archives/C02NXNUGP/p1613036557170100

ローカルの内容と差があるとぶつかるかもしれませんが、ローカルでもmasterからrebaseしてやると治ると思います。

（このブランチではほとんど変わりませんでした🙆‍♂️）

2021-02-12 04:26 UTC, tam-03 reviewed
@universato 
お待たせしました！
レビューですが、良いと思いました！問題ないと思います！

2021-02-12 04:43 UTC, tam-03 approved these changes
@universato 
すみません、[Approve]にします！

2021-02-16 03:46 UTC, universato commented
@komagata

デザイン等が入ってなく非常に見にくいですが、ご確認よろしくお願いします。

【注意点】HTMLのクラスが`.recent-reports`になっているところがありますが、machidaさんがデザインを入れるタイミングで変更してもらおうと考えています。自分がクラスを変更してCSSにも変更を加えると、変更点がわかりにくくなると考えたため、`.recent-reports`のままになっています。

2021-02-16 21:36 UTC, komagata requested changes

2021-02-16 21:36 UTC, komagata commented on test/fixtures/acts_as_taggable_on/taggings.yml
> +komagata_tag_cat:
development環境・staging環境で確認できるようにseedにもタグのデータ入れていただけるとありがたいです〜

`db/seed.rb`で読み込んでいて、`db/fixtures/*.yml`にデータを置いています。

2021-02-17 22:31 UTC, universato commented on test/fixtures/acts_as_taggable_on/taggings.yml
> +komagata_tag_cat:
seedデータとtestデータは違ったのですね、上手いこと共通化させてるのかと変に勘違いしてました。
seedデータも追加して、seedデータに合わせる形でほんの少しtestデータも追加しました。

2021-02-17 23:24 UTC, universato commented
gem ActsAsTaggableOn の`most_used`で取得したタグに紐付くtagging_countという数は、Userに限らず使われている数であったため、タグの取得方法を修正しました。

2021-02-18 06:01 UTC, machida commented
@universato 

デザインを入れたPRをこのPRに向けて出しました。
https://github.com/fjordllc/bootcamp/pull/2366
こちらのマージお願いしますー

2021-02-18 11:58 UTC, universato commented
デザインをマージして、暫定的に件数を最新の日報と合わせる形で20件にしました。

2021-02-23 07:38 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

長いIssueお疲れ様です〜

2021-02-23 07:38 UTC, merged