開発環境でお知らせやDocを作成した際に、通知ターゲット数分のメール確認用タブが開かれるのを改善したい
fjordllc/bootcamp pull request #2326
Opened 2021-02-11 03:35 UTC by tam-03

lssue #2181

---
## 概要

既存の`letter_opener` gemを、`letter_opener_web`gemに変え、複数のメール確認を1つのタブで管理する。

2021-02-11 04:37 UTC, tam-03 commented
@gallardo16 

お疲れ様です！
こちらのレビューをよろしくお願い致します。🙇🏻‍♂️

もし変な事をしていたら遠慮なくおっしゃって頂けると助かります。。
お手数ですがよろしくお願い致します。

2021-02-11 10:05 UTC, komagata commented
@tam-03 下記に書いたようにgit flow（masterからブランチを作って開発する方式）に変更したのでこちらのPRの向き先をmasterに変更しました。（旧ルールの通りにdevelopに向かっているPRを修正して回っています）

https://fjord.slack.com/archives/C02NXNUGP/p1613036557170100

ローカルの内容と差があるとぶつかるかもしれませんが、ローカルでもmasterからrebaseしてやると治ると思います。

（このブランチではほとんど変わりませんでした🙆‍♂️）

2021-02-12 04:24 UTC, gallardo16 approved these changes
確認しました！OKだと思います〜

2021-02-12 04:28 UTC, tam-03 commented
@gallardo16 
ご確認ありがとうございます！🙇🏻‍♂️

2021-02-12 04:51 UTC, tam-03 commented
@komagata 
こちらのレビューをよろしくお願いします🙇🏻‍♂️

2021-02-12 10:04 UTC, komagata requested changes

2021-02-12 10:04 UTC, komagata commented on config/routes.rb
> +  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
MountableEngine系のやつはちょっと特別なのでわかりやすいように上の方とか下の方とかにまとめて書いておいた方が良いかもと思いました。

2021-02-12 10:23 UTC, tam-03 commented on config/routes.rb
> +  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
かしこまりました！
一番下にコードを置きました。一応動作も確認して問題なく動きました！

2021-02-12 11:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-12 11:07 UTC, merged