「今日の気分」を入力必須にした
fjordllc/bootcamp pull request #2352
Opened 2021-02-14 14:46 UTC by gallardo16

## issue
https://github.com/fjordllc/bootcamp/issues/2158 に対応

## 概要
「今日の気分」を入力しない場合、プロフィールのニコニコカレンダーを見たときに日報を提出しているのか、提出はしているが「今日の気分」だけ未入力なのか判断が付かない。
1クリックで済む作業なので入力必須として対応。また、デフォルト設定でhappy(笑顔)にした。

## やったこと
- マイグレーションでNotNullとDefaultを追加

2021-02-16 09:08 UTC, gallardo16 commented
@tam-03 
お手隙の際に、コードレビューをよろしくお願いします🙇‍♂️

2021-02-17 03:53 UTC, tam-03 approved these changes
@gallardo16 
お待たせしました！確認しました！
問題ないと思います！🙇🏻‍♂️

2021-02-17 09:06 UTC, gallardo16 commented
@tam-03 
ご確認ありがとうございます！

@komagata 
コードレビューをお願いいたします！

2021-02-23 07:36 UTC, komagata requested changes

2021-02-23 07:36 UTC, komagata commented on db/migrate/20210214134753_change_emotion_to_notnull_in_reports.rb
> +    change_column :reports, :emotion, :integer, default: 2, null: false
これ、既存のデータ（今日の気分が未入力）があるのでエラーになっちゃうと思います。
DB的には制約を加えなくていいと思います〜

2021-02-28 05:43 UTC, gallardo16 commented on db/migrate/20210214134753_change_emotion_to_notnull_in_reports.rb
> +    change_column :reports, :emotion, :integer, default: 2, null: false
@komagata 
修正しました。
ご確認よろしくお願いします🙇‍♂️

2021-03-01 15:07 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-01 15:07 UTC, komagata commented on app/models/report.rb
> +  after_initialize :set_default_emotion, if: :new_record?
👍

2021-03-01 15:07 UTC, merged