Watch中一覧が欲しい
fjordllc/bootcamp pull request #2363
Opened 2021-02-17 07:39 UTC by harukus

# issue
#2301 に対応
# やること
watch中一覧のページを作成する

2021-02-18 01:53 UTC, harukus commented
@komagata 
watch一覧のページを作る際、コントローラーを作成しました。
この後はリンクを作ってwatch一覧ページを作成しようと思うのですが、この方針であっていますか:eyes:
確認お願いいたします:bow:

2021-02-21 23:19 UTC, komagata commented on config/routes.rb
> +  resources :watches, only: %i(index)
👍

2021-02-21 23:19 UTC, komagata commented on app/controllers/watches_controller.rb
> +class WatchesController < ApplicationController
この調子でいいと思います！

2021-02-21 23:20 UTC, harukus commented on app/controllers/watches_controller.rb
> +class WatchesController < ApplicationController
@komagata 
ありがとうございます！

2021-02-22 06:02 UTC, harukus commented
@komagata 
今現在、Menuに「Watch中一覧ページ」を作成し、そこでWatchしているもののタイトルを表示させてリンクを作成しました。
このあとは何を作成すれば良いでしょうか。教えていただけると嬉しいです:bow:
（ユーザーのアイコンが表示や日付、ページャーが表示できていないと思っています、、＞＜）
<img width="274" alt="スクリーンショット 2021-02-22 14 43 48" src="https://user-images.githubusercontent.com/52342576/108668138-e9168280-751d-11eb-8c8e-04f56d3609c5.png">
<img width="300" alt="スクリーンショット 2021-02-22 14 44 07" src="https://user-images.githubusercontent.com/52342576/108668146-ecaa0980-751d-11eb-98ee-ab1e096c80cd.png">

2021-02-22 07:16 UTC, komagata commented
@harukus 最初はページャー無しでリリースしちゃいましょうか。

@machida 他には何を表示するといいですかね？Watchしてる日報の投稿者の顔とかかな？（意味あるか微妙）

2021-02-22 07:31 UTC, harukus commented
@komagata @machida 
検索結果のページを参考に続きを作ってみます！

2021-02-27 05:14 UTC, harukus commented
@Yu-kichi 
お手隙でレビューお願いします:bow:

2021-02-27 15:41 UTC, Yu-kichi requested changes
@harukus 
まだ全て見れていませんが、とりあえず全体として3点気になる点がありました！
1. 「不要なコントローラのテストの削除」や「first commit」など空commitはない方がいいのかな〜と思いました。
2.  自分の環境にpullして試したところ、提出物をwatchするとエラーになってしまいました。

[![Image from Gyazo](https://i.gyazo.com/b1ba9b5e3c69893eb05790f17e845816.gif)](https://gyazo.com/b1ba9b5e3c69893eb05790f17e845816)

3.yamada 2020年01月01日(3)の日報をwatchしたところ、
画像のように全て日付けが2021年02月04日(木) 21:23で表示されています。

<img width="918" alt="スクリーンショット 2021-02-28 0 29 08" src="https://user-images.githubusercontent.com/64201542/109391752-10c17c80-795c-11eb-80b0-3c47bb9c45c9.png">

以上3点確認お願いしますー🙏

2021-02-27 15:41 UTC, Yu-kichi commented on config/routes.rb
> +
細かいですけどここの空行はなくてもいいのかなと思いました。

2021-03-02 04:27 UTC, harukus commented
@komagata @machida 
watch一覧ページ内での日報の日付の表示について質問があります。
@Yu-kichi さんがレビューしてくださった内容の3番目のものに関係することです。
現在、検索結果の表示を参考にしています。

1. こちらの2020年6月1日の日報を検索し表示すると
<img width="300" alt="スクリーンショット 2021-03-02 13 18 02" src="https://user-images.githubusercontent.com/52342576/109596670-0e2c7600-7b5a-11eb-8847-56c69b1ee3f1.png">
2. 検索結果にはupdated_atの日付が表示されます。

  （app/views/searchables/_searchable.html.slimファイルにもこのよう表記するコード有り）
<img width="400" alt="スクリーンショット 2021-03-02 13 18 09" src="https://user-images.githubusercontent.com/52342576/109596685-12f12a00-7b5a-11eb-9a52-121d1d368dbb.png">


watch一覧ページ内では日報は`2020年06月01日の日報`のような表記にした方が良いでしょうか？？:eyes:

2021-03-02 13:04 UTC, komagata commented
@harukus なるほど〜

検索結果と同じ問題だと思いますが、日付の部分は何を出すかと書いてあるわけじゃないので、created_at, updated_at, published_atなど色々ありてどれを出すのがいいのか迷いますね。

どれを出すのがいいですかね〜？ > @machida 

もしくはWatch一覧なのでWatchした日を出すのもいいですが、その場合だと他と同じ見た目だと混乱するので別の見た目の方がいいかも？

2021-03-03 17:15 UTC, machida commented
@komagata @harukus 
そうですね〜、独自の日時を表示すると混乱しそうですね。
基本的には published_at がいいですね。
published_at を持っていないものがあったら、created_at にしたいと思います。

2021-03-04 03:03 UTC, harukus commented
@machida 
ありがとうございます！
machidaさんのおっしゃる通り「published_at を持っていないものがあったら、created_at」という実装をしてみました。
<img width="306" alt="スクリーンショット_2021-03-04_11_08_31" src="https://user-images.githubusercontent.com/52342576/109904055-fed73500-7cdf-11eb-9824-89fd3bb64f03.png">

QA、提出物、イベントに関しては違和感が無いと思います。
日報に関してですが本日3月4日（09:00頃）に3月1日分の日報を書いてみたら上記の表示になりました。
（reporsのpublished_atが何を指すかがわかりませんでした:bow:）
このままもう一度生徒の方にレビューを依頼した方がいいでしょうか？？

日報の時は「●月●日の日報」と表示させた方がいいと思いましたが、komagataさんのおっしゃる通り「他と同じ見た目だと混乱する」かもしれないと思いました😥

2021-03-04 04:35 UTC, machida commented
@harukus ありがとうございます！そうですね、確かに日報だけはXXXの日報の表記がいいですね。それでお願いしたいです🙏 何度もすいません🙇‍♂️

2021-03-06 01:20 UTC, harukus commented
@machida 
日報のみ学習日を表示して、それ以外は更新日または作成日を表するようにしました！
<img width="500" alt="スクリーンショット 2021-03-05 22 12 13" src="https://user-images.githubusercontent.com/52342576/110190149-31f70100-7e65-11eb-8c9e-8d97496647ea.png">

この後は、生徒の方にレビュー依頼をして、そのあとmachidaさん、そしてkomagataさんにレビューをしてもらうと言う流れであっていますでしょうか？？

2021-03-08 07:30 UTC, harukus commented
@Yu-kichi 
改めてお手隙の際レビューお願いいたします:bow:

2021-03-08 13:36 UTC, Yu-kichi reviewed
>「不要なコントローラのテストの削除」や「first commit」など空commitはない方がいいのかな〜と思いました。

まず前回の「不要なコントローラのテストの削除」は空commitではなかったです。間違えてすいません🙇‍♂️
動作確認しましたが動きはバッチリで、全体的に綺麗に書けていると思いました。😆👍

細かいところですが少し修正した方が良さそうな点を書いておきましたので、確認お願い致しますー🙏

2021-03-08 13:36 UTC, Yu-kichi commented on test/system/watchings_test.rb
> +  setup { login_user 'machida', 'testtest' }
管理者である必要がない場合には一般ユーザーを使う方が良いとkomagataさんが指摘しているのを見たので、変更した方がいいかな〜と思います。

2021-03-08 13:36 UTC, Yu-kichi commented on app/helpers/watch_helper.rb
> +    if watches.watchable_type == 'Report'
面倒な条件がへルパーメソッドとしてわかりやすく書けていて参考になります！👍

2021-03-08 13:36 UTC, Yu-kichi commented on app/views/application/_header_links.html.slim
> +              li.header-dropdown__item
インデントがずれているように見えます〜。

2021-03-08 13:36 UTC, Yu-kichi commented on app/views/watches/index.html.slim
> +      .thread-list-item(class="is-#{document.class.to_s.tableize.singularize}")
この辺も多くのところでインデントがずれちゃっているのかな〜と思います。

2021-03-09 15:47 UTC, Yu-kichi commented on app/controllers/watches_controller.rb
> +    user_watching = current_user.watches.order(created_at: :desc)
<img width="717" alt="スクリーンショット 2021-03-10 0 25 49" src="https://user-images.githubusercontent.com/64201542/110495656-0eb7a480-8138-11eb-9b22-b5ce2dac9fda.png">
watchした順に並ぶので日付がバラバラになっているように見えるのが少し気になりましたが、こういう仕様であるなら問題ないと思います〜。(watchした順で並べていることが明示されていた方がユーザーがわかりやすくていいかも？)

一応検索結果は次のように日付順になるように作られていましたので、もし変更するのであれば参考になるかもしれません。
https://github.com/fjordllc/bootcamp/commit/65fc7991534b3b3ad7f1d91d396b2783d2c369f0

2021-03-10 04:05 UTC, harukus commented on test/system/watchings_test.rb
> +  setup { login_user 'machida', 'testtest' }
なるほど！ありがとうございます！

2021-03-10 04:08 UTC, harukus commented on app/controllers/watches_controller.rb
> +    user_watching = current_user.watches.order(created_at: :desc)
確かに検索結果は日付順ですね〜
そこまで気づいていませんでした。教えていただきありがとうございます。
本日のミーティングで質問しようと思います！

2021-03-10 06:03 UTC, harukus commented on app/views/application/_header_links.html.slim
> +              li.header-dropdown__item
修正いたしました！

2021-03-10 06:08 UTC, harukus commented on app/views/watches/index.html.slim
> +      .thread-list-item(class="is-#{document.class.to_s.tableize.singularize}")
インデントを半角スペース2で統一しました！

2021-03-10 06:14 UTC, harukus commented on app/controllers/watches_controller.rb
> +    user_watching = current_user.watches.order(created_at: :desc)
ミーティングで聞いたところ、Yu-kichi さんのおっしゃる通り「watchした順で並べられている方が使いやすそう」となりました。
ですので、並べ方はこの仕様のまま行きます👍

2021-03-10 07:26 UTC, harukus commented
@Yu-kichi お手すきの際に改めてレビューお願いいたします:bow:

2021-03-10 11:55 UTC, Yu-kichi commented on app/controllers/watches_controller.rb
> +    user_watching = current_user.watches.order(created_at: :desc)
了解です👍
確認ありがとうございます〜！

2021-03-10 11:58 UTC, Yu-kichi approved these changes

2021-03-10 12:00 UTC, Yu-kichi commented
@harukus 
確認しました！最初に比べて格段に良くなったと思います👍
お疲れ様でした〜LGTMです😊

2021-03-10 12:59 UTC, harukus commented
@Yu-kichi 丁寧なレビューをありがとうございました！

2021-03-10 13:45 UTC, harukus commented
@komagata レビューお願いいたします:bow:

2021-03-11 06:50 UTC, komagata requested changes

2021-03-11 06:50 UTC, komagata commented on app/controllers/watches_controller.rb
> +    @watches = user_watching.page(params[:page]).per(25)
25がマジックナンバーになってるので定数か変数か何かに一旦入れた方が良いかもです〜

[マジックナンバーとは \- Google Search](https://www.google.com/search?q=%E3%83%9E%E3%82%B8%E3%83%83%E3%82%AF%E3%83%8A%E3%83%B3%E3%83%90%E3%83%BC%E3%81%A8%E3%81%AF&oq=%E3%83%9E%E3%82%B8%E3%83%83%E3%82%AF%E3%83%8A%E3%83%B3%E3%83%90%E3%83%BC%E3%81%A8%E3%81%AF&aqs=chrome..69i57j0l2j0i30l6j0i5i30.2291j0j7&sourceid=chrome&ie=UTF-8)

2021-03-11 06:50 UTC, komagata commented on app/helpers/watch_helper.rb
> +module WatchHelper
日報にコメントしたようにWatchableのconcernに処理を書いた方がいいかもです〜

2021-03-11 06:50 UTC, komagata commented on test/system/watchings_test.rb
> +  test 'show_watch' do
この辺りのテスト名の付け方を他のsystemテストを参考にして合わせてみてください〜

2021-03-12 07:06 UTC, harukus commented on app/controllers/watches_controller.rb
> +    @watches = user_watching.page(params[:page]).per(25)
かしこまりました！

2021-03-13 03:16 UTC, komagata requested changes
コンフリクトしてる部分の修正お願いします〜
（コンフリクトは誰かのミスってわけではなく、日常的に発生するものですのでコンフリクトの解消は日常業務なので心配しないで大丈夫です〜）

2021-03-14 01:50 UTC, harukus commented
@komagata 改めてレビューお願いいたします:bow:

2021-03-14 03:54 UTC, komagata requested changes

2021-03-14 03:54 UTC, komagata commented on app/models/concerns/watchable.rb
> +    elsif watchable.has_attribute?(:published_at) && watchable.published_at
```suggestion
    elsif watchable.has_attribute?(:published_at) && watchable.published_at?
```

存在確認をするのであればこう書いた方が意図がわかりやすいかも？です〜

2021-03-14 03:54 UTC, komagata commented on app/models/concerns/watchable.rb
> +  def filter_product
filter_productは実装の中身の話（実装者から見た視点でつけた名前）なので、使う人にとっての目線で名前をつけるのがいいかもです。

例えばtimeメソッドを使う人からの目線はこんな感じです。

```ruby
.time = @watchable.time
```

filter_productを使う人の目線から見たらこういう感じの名前の方がわかりやすいと思います。

```ruby
.body = @watchable.body
```

（この名前がいいかどうかは考える必要がありますが。）

2021-03-14 07:02 UTC, harukus commented on app/models/concerns/watchable.rb
> +    elsif watchable.has_attribute?(:published_at) && watchable.published_at
確かにそうですね:eyes:変更します。

2021-03-14 12:48 UTC, harukus commented on app/models/concerns/watchable.rb
> +  def filter_product
@komagata 
今回は`detail`メソッドという名前にしました。
というのも、questionモデルのviewで`@question.description`という質問の中身(descriptionカラム)を表示する、コードがあります。そしてquestionモデルも`include Watchable`をしています。
ここでメソッド名`filter_product`を`description`にすると、　先ほどのviewでの`@question.description`がWatchableの`description`メソッドとして解釈されるためです。
`body`もカラム名として使用されているので避けましたが、いかがでしょうか:eyes:

2021-03-15 06:34 UTC, harukus commented
@komagata 
レビューお願いいたします:bow:

2021-03-16 03:44 UTC, komagata commented on app/models/concerns/watchable.rb
> +  def filter_product
@harukus 

> ここでメソッド名filter_productをdescriptionにすると、
> 先ほどのviewでの@question.descriptionがWatchableのdescriptionメソッドとして解釈されるためです。

これって何か問題ありますかね？

https://github.com/fjordllc/bootcamp/blob/main/app/models/concerns/commentable.rb#L22

commentableやその他の場所でも似たような意味を持つカラムを共通に扱えるようにしていて、titleやbodyのようなカラム名と同じ名前を使っています。（その方が自然に使えるため）できれば他と合わせるとみる人にとって負担が少なくなります。そういう感じでやるのはどうですかね？

2021-03-17 11:01 UTC, harukus commented on app/models/concerns/watchable.rb
> +  def filter_product
@komagata 
ごめんなさい:bow:`self[:description]`このような書き方が思いつきませんでした。

2021-03-18 07:20 UTC, harukus commented
@komagata
メソッド名変更いたしました。レビューお願いいたします:bow:

2021-03-21 15:21 UTC, komagata commented on app/models/concerns/watchable.rb
> +    if class_name == 'Product'
これってwatchableなクラス全てに可能性があると思うんですが、Product以外のクラスは大丈夫ですかね？

2021-03-22 06:48 UTC, harukus commented on app/models/concerns/watchable.rb
> +    if class_name == 'Product'
今の所、watchできる物の中(`Report`,`Question`,`Event`,`Product`)でProductクラスのみ、内容を表示するカラム名が`body`となっています。
しかし未来のことも考えて(?)、Productクラスかどうかで判別するのではなく、`description`カラムが存在するかどうかで判断するようにしました！(メソッド名が`description`のため)

2021-03-22 10:33 UTC, harukus commented
@komagata 
改めてレビューお願いいたします:bow:

2021-03-23 13:29 UTC, komagata commented on app/models/concerns/watchable.rb
> +    if class_name == 'Product'
なるほどですね。一つだけだったらそのままでも大丈夫です。

ただ、他のconcernと同じような判別方法に合わせた方がいいかもです。
https://github.com/fjordllc/bootcamp/blob/main/app/models/concerns/commentable.rb#L22-L29

2021-03-24 06:10 UTC, harukus commented on app/models/concerns/watchable.rb
> +    if class_name == 'Product'
なるほどです！
修正しました。確認お願いいたします！:bow:

2021-03-27 05:49 UTC, komagata requested changes

2021-03-27 05:49 UTC, komagata commented on app/controllers/watches_controller.rb
> +    user_watching = current_user.watches.order(created_at: :desc).map(&:watchable)
SQLだけで取得した方が圧倒的に処理が早いはずなので、なるべくActiveRecordの機能で撮りたいですね。

2021-03-27 05:49 UTC, komagata commented on app/models/concerns/watchable.rb
> +  def class_name
`class.name`でいいかも？
だとするとメソッドにしてもあまり変化がないので不要かもです。

2021-03-29 08:28 UTC, harukus commented on app/models/concerns/watchable.rb
> +  def class_name
確かにそうですね！削除しました🙆‍♀️

2021-03-30 13:11 UTC, harukus commented
@komagata 
改めてレビューお願いします！

@machida 
デザインがあるものなのでmachidaさんをassignさせていただきました🙇‍♀️

2021-03-31 04:39 UTC, machida commented
@harukus デザイン了解ですー🙋‍♂️

2021-03-31 05:22 UTC, machida commented
@harukus https://github.com/fjordllc/bootcamp/pull/2523 デザイン入れましたー

2021-03-31 05:27 UTC, machida commented
@harukus 
https://github.com/fjordllc/bootcamp/pull/2523 デザインのPR作りました。

2021-03-31 14:30 UTC, machida commented
@harukus 
mainブランチとのコンフリクトが出てしまいました。
rebase する際に、下の方を選択（上を消す）してください🙏

<img width="741" alt="貼り付けた画像_2021_03_31_23_28" src="https://user-images.githubusercontent.com/168265/113161127-0eaf4e00-9279-11eb-90d7-9ce3f608ce00.png">

2021-03-31 14:32 UTC, harukus commented
@machida 了解しました！明日やってみます🙇‍♂️

2021年3月31日(水) 23:31 machida ***@***.***>:

> @harukus <https://github.com/harukus>
> mainブランチとのコンフリクトが出てしまいました。
> rebase する際に、下の方を選択（上を消す）してください🙏
>
> [image: 貼り付けた画像_2021_03_31_23_28]
> <https://user-images.githubusercontent.com/168265/113161127-0eaf4e00-9279-11eb-90d7-9ce3f608ce00.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fjordllc/bootcamp/pull/2363#issuecomment-811114449>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMPK6MBJ5U4O6P7V7WP4FR3TGMW2XANCNFSM4XX3GLKQ>
> .
>

2021-04-02 12:23 UTC, harukus commented
@komagata
すみません、`.map(&:watchable)` をまだ使っているので`.map(&:watchable)` を使わない実装で考えて見ます、、！💪

2021-04-03 07:50 UTC, harukus commented on app/controllers/watches_controller.rb
> +    user_watching = current_user.watches.order(created_at: :desc).map(&:watchable)
@komagata 
`map(&:watchable)`を使用しない方法で修正しました。確認お願いいたします。:bow:

2021-04-10 04:41 UTC, harukus commented
@komagata 
a50e369 にてwatchableの処理をviewファイルに移動させました:bow:
確認お願いいたします。

2021-04-14 05:34 UTC, komagata requested changes

2021-04-14 05:34 UTC, komagata commented on app/views/watches/index.html.slim
> +- @watches.each do |watch|
https://docs.komagata.org/5465

こういう感じにすると一時変数などが減ってわかりやすくなるかもです〜

2021-04-15 06:21 UTC, harukus commented
@komagata 修正いたしました。確認お願いいたします。

2021-04-15 14:27 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-15 14:27 UTC, merged

2021-04-16 07:32 UTC, harukus commented
@komagata 
ありがとうございます、、、！！！