作業開始
fjordllc/bootcamp pull request #2364
Opened 2021-02-17 08:23 UTC by Yu-kichi

#2313 に対応

2021-02-17 09:47 UTC, Yu-kichi commented
@machida 
お疲れ様です
isuue#2313 の件ですが上記のように実装すればいいのかな〜と考えました。

お手隙の際にコメントいただければ助かります。
確認お願い致します🙏

2021-02-18 06:08 UTC, machida commented
@Yu-kichi

> 実装方法(見込み)

Flash は使わずに、viewファイルに、

```
- if まだ自分がおわってないとき
    div
        p プラクティスを完了するまで他の人の提出物は見れません。
```

と、書くようにお願いします。
見た目のデザインはこちらで行いますー

あと、プラクティスが完了していないと、それぞれの提出物の個別ページに行くためのリンクがクリックできないようにする予定ですが、それの対応も僕の方でやります。なので、上記の注意文を表示するところまでやりましたら僕が作業を引き継ぐのでメンションお願いします🙏

2021-02-21 15:24 UTC, Yu-kichi commented
@gallardo16
お疲れ様です！
夜遅くすいません。
お手隙の際にレビューお願いいたします！🙏

2021-02-21 23:16 UTC, komagata commented
@Yu-kichi スクショを多用されていて、自分のローカルで動かす前にどういう内容かわかりやすくてとってもいいですね！！

2021-02-22 06:55 UTC, gallardo16 requested changes
一点気になったのでコメントしました〜
ご確認よろしくお願いします。

2021-02-22 06:55 UTC, gallardo16 commented on app/views/practices/products/index.html.slim
> +- if current_user.student? && (@my_product.nil? || @my_product.checks.empty?)
ログインユーザーが研修生の場合はメッセージが表示されず、その提出物を提出していない卒業生は表示されてしまうかもです。

2021-02-23 09:18 UTC, Yu-kichi commented
komagataさん
コメントありがとうございます！
文字だけだとうまく伝えられる気がしないので、今後もなるべくスクショ使っていくようにします！😊

2021-02-23 09:56 UTC, Yu-kichi commented on app/views/practices/products/index.html.slim
> +- if current_user.student? && (@my_product.nil? || @my_product.checks.empty?)
@gallardo16
レビューありがとうございます🙏

>ログインユーザーが研修生の場合はメッセージが表示されず、その提出物を提出していない卒業生は表示されてしまうかもです。

見落としていましたすいません！😓
提出物に関しては現状次の場合にflashメッセージを表示させている事を確認しました。
そのため提出不要のプラクティスについては表示させないようにしました。

``` ruby
/bootcamp/app/controllers/products_controller.rb
 before_action :check_permission!, only: %i[show]
...
  def check_permission!
    return if policy(find_product).show? || find_practice&.open_product?

    redirect_to root_path, alert: 'プラクティスを完了するまで他の人の提出物は見れません。'
  end
```

またshow?のメソッドを見ると、次のように卒業生の場合には提出物を提出していなくても他人の提出物が見れる仕様になっていたため、その条件に合わせて卒業生はメッセージが表示されないようにしました。
``` ruby
/bootcamp/app/policies/product_policy.rb
  def show?
    user.admin? ||
      user.mentor? ||
      user.adviser? ||
      user == product.user ||
      user.graduated_on? ||
      product.practice.completed?(user) ||
      product.completed?(user)
  end
```

以下より student_or_trainee?メソッドにして研修生を含めるように変更しました。
``` ruby
/bootcamp/app/models/user.rb
 def student_or_trainee?
    !staff? && !retired? && !graduated?
  end
```

お手数ですが
お手隙の際に再レビューお願い致します🙏

2021-02-24 04:33 UTC, gallardo16 commented
@Yu-kichi 
修正を確認しました。OKだと思います🙆‍♂️
すみません、提出不要の提出物の件は見落としていました。

2021-02-24 04:33 UTC, gallardo16 approved these changes

2021-02-24 05:19 UTC, komagata commented
@Yu-kichi @gallardo16 さんのレビューがOKであればGitHubの機能を使って僕にレビュー依頼をお願いします〜

2021-02-24 10:27 UTC, Yu-kichi commented
@gallardo16 
レビューありがとうございます😊
>すみません、提出不要の提出物の件は見落としていました。

いえいえ助かりましたー🙏

2021-02-25 06:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-02-25 06:19 UTC, merged

2021-02-25 15:07 UTC, Yu-kichi commented
@machida
komagataさんのレビューが通りましたので引き継ぎお願い致します〜🙏

2021-02-26 02:04 UTC, komagata commented
@machida @Yu-kichi あ、完了だとおもってデザイン前にマージしちゃいました、すみません！

2021-03-02 13:04 UTC, Yu-kichi commented
@machida
こちら自分の作成は終わりましたので引き継ぎお願いします。
デザインをお願いする手順を間違え、すでにレビューは終わり、一度mergedされています。。
申し訳ございませんが、よろしくお願いいたします。🙇‍♂️