未返信の提出物一覧に日付ごとの区切り線を入れた
fjordllc/bootcamp pull request #2367
Opened 2021-02-19 05:48 UTC by gallardo16

## issue
https://github.com/fjordllc/bootcamp/issues/2252 に対応

## 概要
前提として、提出された提出物は7日以内にメンターが返信することがルールになっています。
未返信の提出物一覧において、提出されてから何日経過したか一目でわかるように区切り線を入れました。

## 実装した機能
- 区切り線は、「5日経過」,「6日経過」,「7日以上経過」のラベル3つ。
- それぞれの該当日に提出物がない場合は表示されない。

---

- 今日が2/19の場合(デザイン前)
![image](https://user-images.githubusercontent.com/62986803/108461888-eec25d00-72be-11eb-986d-dd73beba8718.png)

##

2021-02-27 07:57 UTC, gallardo16 commented
@harukus 
お手隙の際にコードレビューをよろしくお願いします🙏

2021-02-28 08:04 UTC, harukus commented
明日の15時以降にレビュー致します:bow:
遅くなり申し訳ありません:bow:

2021-02-28 13:19 UTC, gallardo16 commented
@harukus 
こちらこそ休日にお願いしてしまって申し訳ありません。
急いでいるわけではないので、ゆっくりでも大丈夫です👍
レビューよろしくお願いします。

2021-03-01 07:48 UTC, harukus reviewed
@gallardo16 
ありがとうございます:bow:
メソッド名について一つ書きました。
確認お願いいたします！

2021-03-01 07:48 UTC, harukus commented on app/views/products/not_responded/index.html.slim
> +            - if mentor_login?
　`- if mentor_login?`
を追加したのは提出物の確認はメンターさんのみなのでメンターさん以外の人は見る必要性がないから追加した、という認識であってますか？

2021-03-01 07:48 UTC, harukus commented on app/models/product.rb
> +  end
`submitted_specific_day_ago?`や`submitted_before_specific_day_ago?`のメソッド名が分かりにくいかなと思いました。
前者は「ちょうど◯日」と表しているので`submitted_just_specific_days`（投稿してちょうどO日経過）と書けるかなと思います！
後者は「◯日以上経過」なので`over`を使った`submitted_over_specific_days`を使うと直感的だと思います。

2021-03-01 15:13 UTC, komagata commented on app/models/product.rb
> +  end
素晴らしいレビュー・議論！

2021-03-01 21:06 UTC, JunichiIto commented on app/models/product.rb
> +  end
さすが[Q&A](https://bootcamp.fjord.jp/questions/803)でちゃんと質問してただけある！

2021-03-02 05:59 UTC, machida commented
@gallardo16 

すいません、提出物一覧ページに移動したらエラーになってしまいました。
こちらって今対応中でしょうか？

![image](https://user-images.githubusercontent.com/168265/109605015-d3c9d580-7b67-11eb-9040-478f02a40188.png)

2021-03-02 06:24 UTC, gallardo16 commented
@machida 

ご連絡ありがとうございます。
私の方では、そのエラーをローカル環境で確認できなかったので、対応はしてないです。
ただテスト実行時、`published_at`カラムが空だったために同じエラーが出たので、当該カラムが空の可能性があると思いました。
ご確認よろしくお願いいたします。

2021-03-02 06:45 UTC, gallardo16 commented
@machida 

すみません、そもそも
こちらのPRがマージされたことで全体的な書き換えが必要になったかもしれません。
https://github.com/fjordllc/bootcamp/pull/2280

2021-03-02 13:06 UTC, komagata commented
@gallardo16 そうか、すみません、そこちょうど作業部分がぶつかってしましたね・・・。
大幅に書き換える必要が出ちゃいましたすみません🙇‍♂️

2021-03-02 13:21 UTC, gallardo16 commented
@komagata 
コメントありがとうございます。
すみません、こちらが完全に非同期化のこと忘れていました。
そもそも追加したコード量が少ないので、そこまで問題はないかも知れません。

2021-03-02 13:31 UTC, hogucc commented
@gallardo16 @komagata 
私も #2280 対応中に気づかず申し訳ないです〜🙇‍♀️
#2280 で大きく変わっているのは提出物関連のコントローラーをAPI化したのと、`app/views/products/index.html.slim`の`.page-body`のあたりになるので、いまのdiffを見る限りは大きく作り変える必要はなさそうと思います〜！

2021-03-23 05:40 UTC, gallardo16 commented on app/javascript/product.vue
> +    .foo(v-if="notResponded")
デザイン前により仮に`foo`としています。

2021-03-23 05:48 UTC, gallardo16 commented on app/views/products/not_responded/index.html.slim
> +            - if mentor_login?
実装方法変更のため、このレビューは停止

>`- if mentor_login?`
を追加したのは提出物の確認はメンターさんのみなのでメンターさん以外の人は見る必要性がないから追加した

一応その意図でした。

2021-03-23 05:51 UTC, gallardo16 commented on app/models/product.rb
> +  end
指摘していただいた名称の方が読みやすいため、メソッド名とcontrollerのインスタンス変数名など全体的に変更しました。

2021-03-23 05:55 UTC, gallardo16 commented
@harukus 
大変お待たせしました🙏
レビューありがとうございました。指摘していただいた点を修正しました。
新しくVue.jsの方に実装を移行しましたので再度レビューよろしくお願いいたします。

2021-04-01 20:18 UTC, harukus commented
@gallardo16 
10日間も気がつかず大変申し訳ありませんでした。
以後このようなことが内容に気をつけます:bow:
本当にごめんなさい。
これから仕事があるため、レビューはもう少し待っていただけますでしょうか。
とりあえずレビューのアサインだけさせていただきます。
本当にごめんなさい:bow:

2021-04-02 06:35 UTC, gallardo16 commented
@harukus 
全然大丈夫ですよ！
こちらが再レビューを依頼するまで期間があいてしまったのもいけないので〜
レビューよろしくお願いします🙇‍♂️

2021-04-03 06:46 UTC, harukus approved these changes
今は提出されてから5日、6日、、となっていますが、これがもし3日に変更するとなった時コードの書き換えが大変かなぁと思ったのですが、良い書き換えが思いつきませんでした🤔
手元で動作確認もできました！いいと思いますー🙆‍♀️お待たせしました:bow:

2021-04-06 06:56 UTC, gallardo16 commented
@harukus 
ご確認ありがとうございます🙇‍♂️

@machida 
こちらデザインをよろしくお願いいたします。

2021-04-27 05:45 UTC, machida commented
@gallardo16 デザイン入れました！！

2021-04-27 05:47 UTC, machida approved these changes

2021-05-11 16:23 UTC, machida commented
@gallardo16 
すいません、こちらのコンフリクト解消をお願いします🙏

2021-05-11 16:25 UTC, machida commented
@komagata
こちら、
https://github.com/fjordllc/bootcamp/pull/2679
このPRといろいろぶつかりそうなので、可能でしたら早めにマージしてしまいたいです。

2021-05-12 04:49 UTC, sinsoku commented on app/assets/stylesheets/blocks/thread/_thread-list-item.sass
> +    border-color: #b50f38
`is-5-days` などのクラス名だとマジックナンバー的で、パッと分かりづらいと思いました。
例えば `.reply-warning`, `.reply-alert`, `.reply-deadline` のような意味のある名前にした方が良いかなと思いました。（あくまで例なので、他に良い名前あればそれで）

あと、仕様的な話ですが、個人的には5〜6日（warning）と7日（alert）の2種類のラベルで十分じゃないかなとは思いました。

2021-05-12 04:59 UTC, sinsoku commented on app/views/api/products/not_responded/index.json.jbuilder
> +json.latest_product_submitted_over_7days @latest_product_submitted_over_7days
各productのjsonに `published_at` が既に含まれているので、jsonに新しいキーを追加する必要は無いかなと思いました。
jsの実装だけで実現できそう。

```js
isLatestProductSubmittedJust5days() {
  // this.product.published_at を使って計算できるのでは？
},
```

2021-05-12 06:18 UTC, gallardo16 commented on app/views/api/products/not_responded/index.json.jbuilder
> +json.latest_product_submitted_over_7days @latest_product_submitted_over_7days
レビューありがとうございます。
修正してみます💪

2021-06-17 07:36 UTC, gallardo16 commented on app/views/api/products/not_responded/index.json.jbuilder
> +json.latest_product_submitted_over_7days @latest_product_submitted_over_7days
@sinsoku

すみません、提案していただいた形に修正しようとしたのですが、やり方がわかりませんでした。
返信が遅くなってしまいましたが、よろしくお願いいたします。

2021-06-22 07:10 UTC, komagata commented on app/views/api/products/not_responded/index.json.jbuilder
> +json.latest_product_submitted_over_7days @latest_product_submitted_over_7days
:memo: これ、JSでもできますが、他のIssueでも使うのでRuby側で実装されている方が便利かもです。

2021-06-22 07:12 UTC, komagata commented on app/assets/stylesheets/blocks/thread/_thread-list-item.sass
> +    border-color: #b50f38
@machida こちら、いかがでしょう〜

2021-06-23 13:03 UTC, machida commented on app/assets/stylesheets/blocks/thread/_thread-list-item.sass
> +    border-color: #b50f38
@sinsoku

確かに！！そういえば、そこまで考えてませんでしたー
ネーミングもいいですね！！ピッタリなのでこのまま使わせていただきたいと思います🙇‍♂️

2021-06-23 13:15 UTC, machida commented
@gallardo16 

class名をこのように変更しましたー

```sass
  &.is-reply-warning
    background-color: $warning
    border-color: #d09a0e
  &.is-reply-alert
    background-color: #ff7500
    color: $reversal-text
    border-color: #d06305
  &.is-reply-deadline
    background-color: $danger
    color: $reversal-text
    border-color: #b50f38
```

2021-06-24 01:53 UTC, komagata requested changes
mainからのマージコミットができてるようなので修正してみてください〜

2021-06-29 05:07 UTC, gallardo16 commented
@komagata 
すみませんお待たせしました。
コードレビューをよろしくお願いいたします🙇‍♂️

2021-06-29 08:22 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-29 08:22 UTC, komagata commented on test/fixtures/products.yml
> +product1: # 自分のコメントあり(2つ)
コメントついてるとわかりやすいですね。

2021-06-29 08:23 UTC, komagata requested changes
mainからのマージコミットができてるみたいなので修正してみてください〜

2021-06-30 07:56 UTC, gallardo16 commented
@komagata 

修正しました。よろしくお願いします🙏

2021-06-30 14:17 UTC, komagata requested changes
CommitsのタブでこのPRのコミットを全て見てみてください〜
いくつもマージコミットがあるようです。

https://github.com/fjordllc/bootcamp/pull/2367/commits

2021-07-02 11:51 UTC, gallardo16 commented
@komagata 
すみません、誤解していました。
修正の仕方について質問なのですが、マージコミットは`git revert`で修正した方がよろしいのでしょうか？？

2021-07-02 14:47 UTC, machida commented
@gallardo16 
git rebase -i で必要なコミット以外を消してから、git pull --rebase origin main でもいいかもですー。

もしくは、別ブランチ作って、そっちに必要なコミットだけをcherry-pickですかねー。

もしうまく行かなかったら、質問タイムの時間に別部屋に移動して一緒に作業しましょう。

2021-07-03 00:42 UTC, gallardo16 commented
@machida 
ありがとうございます🙇‍♂️
一回やってみます💪

2021-07-05 04:20 UTC, gallardo16 commented
@machida 
cherry-pickで修正することができました。
ありがとうございました🙇‍♂️

@komagata 
https://github.com/fjordllc/bootcamp/pull/2923
別のプルリクを作成する形で修正しました。
ご確認よろしくお願いいたします🙇‍♂️

2021-07-05 12:09 UTC, komagata commented
@gallardo16 このPRはCloseして別のPRを採用するって意味であっていますかね？
もう一つのPRの方にコメントいたしました。
このPRが必要ない感じでしたらCloseしちゃってください〜

2021-07-06 08:51 UTC, gallardo16 commented
@komagata 
>このPRはCloseして別のPRを採用するって意味であっていますかね？

はい、その意味であってます。

Closeします。

2021-07-06 08:51 UTC, closed without merging