Q＆AのQとAの両方でメンションが聞いてない
fjordllc/bootcamp pull request #2386
Opened 2021-02-26 02:35 UTC by tam-03

issue #2361
バグの修正

2021-03-02 04:14 UTC, tam-03 commented
@Yu-kichi さん！お手数ですが、こちらのレビューをよろしくお願い致します！🙇🏻‍♂️

2021-03-02 12:56 UTC, Yu-kichi commented
@tam-03
レビュー依頼ありがとうございます！😆
ただすいません、今週少し仕事が忙しくなりそうなので数日かかるかもしれません🙏

2021-03-02 13:04 UTC, tam-03 commented
@Yu-kichi 
いえ！ご連絡をありがとうございます🙇🏻‍♂️
お手すきの際にご確認をよろしくお願いします！

2021-03-03 12:37 UTC, Yu-kichi approved these changes
```mentionable_as :description```についての説明があってわかりやすかったです！
```letter_opener_web```を使ってメールの確認もしていた点もよかったです！
LGTMですー😊👍

2021-03-03 13:28 UTC, tam-03 commented
@Yu-kichi 
お忙しい所ありがとうございます！

@komagata 
こちらのレビューをよろしくお願いします🙇🏻‍♂️

2021-03-05 12:50 UTC, komagata requested changes

2021-03-05 12:50 UTC, komagata commented on test/system/mention/answers_test.rb
> +      login_user 'komagata', 'testtest'
komagataは管理者ユーザーで特別なので、管理者権限が必要ないテストの場合、なるべく一般的なユーザー（kimuraなど他のユーザー）でやるのがいいかもです〜

2021-03-05 12:50 UTC, komagata commented on app/models/question.rb
> +  mentionable_as :description
👍

2021-03-05 14:49 UTC, tam-03 commented on test/system/mention/answers_test.rb
> +      login_user 'komagata', 'testtest'
@komagata 

「kimura」に変更しました！🙇🏻‍♂️

2021-03-06 16:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-06 16:17 UTC, komagata commented on test/system/mention/answers_test.rb
> +      login_user 'kimura', 'testtest'
👍

2021-03-06 16:17 UTC, merged