プロフィールにdiscordのidを追加する
fjordllc/bootcamp pull request #2390
Opened 2021-02-27 04:37 UTC by Yu-kichi

issue#2247に対応

### 概要

### 理由

###スクショ

2021-02-27 07:46 UTC, Yu-kichi commented
@komagata
仕様確認するために3点質問させてください。🙇‍♂️
前提としてslackアカウントと同様の取り扱いをするものとして実装すればいいのかな〜と考えています。
1. slackアカウントと同様に未設定の場合、discordアカウント未設定の表示ができるようにする。
2. 表示場所はslackアカウントの下に置こうとしていますがよろしいでしょうか？
3. Userのカラムに"slack_participation"というものがありますが、それに合わせてdiscord_participationもカラムに追加すべきでしょうか？
追加すべきであればslack_participationと同様になるように実装する方針でよろしいでしょうか？

上記コメントや画像と合わせて確認いただけると助かります。
お願いいたしますー🙏

2021-03-01 15:16 UTC, komagata commented
> slackアカウントと同様に未設定の場合、discordアカウント未設定の表示ができるようにする。

「discordアカウント未設定の表示」これは何を指していますか？

> 表示場所はslackアカウントの下に置こうとしていますがよろしいでしょうか？

はい、大丈夫です〜

> Userのカラムに"slack_participation"というものがありますが、それに合わせてdiscord_participationもカラムに追加すべきでしょうか？

まずは不要です〜

2021-03-01 15:37 UTC, Yu-kichi commented
@komagata 
回答ありがとうございます！😆
>slackアカウントと同様に未設定の場合、discordアカウント未設定の表示ができるようにする。
「discordアカウント未設定の表示」これは何を指していますか？

言葉足らずですいません。🙇‍♂️
下の図の赤枠のようにslack未設定と同様の扱い(アカウントを登録していればそのidが表示される)で、discordアカウント未設定の表示を入れるように作りましたが、この仕様でよいかの確認がしたかったです？
<img width="368" alt="komagataのプロフィール___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/64201542/109519105-45653d80-7aee-11eb-9cdd-7257988f67e8.png">

確認お願いいたします！

2021-03-02 12:57 UTC, komagata commented
@Yu-kichi なるほどです。上記のような感じで大丈夫です〜

2021-03-02 13:07 UTC, Yu-kichi commented
@komagata 
確認ありがとうございます！
ではこのまま進めたいと思います！😆

2021-03-04 11:18 UTC, Yu-kichi commented on app/views/users/_profile.html.slim
> +        .users-item-names__slack
見た目を整えるためusers-item-names__slackといった名前をそのまま使っていますが、この点どうするかはmachidaさんにお願いしたいと思っています。

2021-03-04 11:26 UTC, Yu-kichi commented
@SeijiNumata
お疲れ様ですー
お手隙の際にレビューをお願い致しますー🙏

2021-03-05 05:50 UTC, SeijiNumata commented
@Yu-kichi 
レビュー依頼ありがとうございます！承知いたしました！😊
土日を利用して見てみます。少々お待ちください！

2021-03-06 06:47 UTC, SeijiNumata reviewed
@Yu-kichi 
レビューしたのでご確認お願いします！

「View側での変更点のスクショ」という項目が、仕様追加で何をしたのか分かりやすくてとても良いと思いました👍

全体的に自信がないので見当違いのことを言っていたら申し訳ないです🙇‍♂️
その際はお気軽にご指摘いただければと思います。
よろしくお願いします！

2021-03-06 06:47 UTC, SeijiNumata commented on app/views/users/_profile.html.slim
> +        .users-item-names__slack
承知です👍
教えていただいてありがとうございます！
積極的にこういうのは書いていった方がいいですね。勉強になります。

2021-03-06 06:47 UTC, SeijiNumata commented on app/views/users/_user.html.slim
> +                    i.fab.fa-discord
すみません、分からないところがあったので質問させて頂きたいです。
`i`というのはどういう意味なのでしょうか？
fabiconを使う時は、クラスの前に`i`と宣言する　という認識であっていますか？

2021-03-06 07:38 UTC, Yu-kichi commented on app/views/users/_user.html.slim
> +                    i.fab.fa-discord
このfabiconはfontawesomeを使用したので、fontawesome推奨のi要素を使用したというのが理由になります。

>fabiconを使う時は、クラスの前にiと宣言する　という認識であっていますか？

推奨ということで使用しているだけで、iをem等に変えても一応表示上は同じようになりそうです。
他のfabiconではi以外の要素を使っているのもあるかもしれないですー。
参考：https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

i要素自体は参考のように興味深いテキスト要素という意味です。
参考[<i>: 興味深いテキスト要素](https://developer.mozilla.org/ja/docs/Web/HTML/Element/i)

i要素自体の意味は僕も調べるまでわかってなかった(推奨ということでそのまま使ってた。。)ので勉強になりました。
ありがとうございますー👍

2021-03-06 07:38 UTC, Yu-kichi commented on app/helpers/required_fields_helper.rb
> +  end
①に関しては自分の確認ミスです、見つけてくださりありがとうございます。修正したいと思います！！😂

②に関してはそのまま```messages << link_to('Discordアカウントを登録してください。', edit_current_user_path, class: 'card-list__item-link is-discord'.to_s.html_safe)```を追加しようとするとrequired_fieldsのメソッドが長くなり、rubocopに引っかかるため、required_snsメソッドを作り致し方なく分割しました。

一応commitメッセージにも書いておきましたが、ちょっとわかりづらくてすいません〜。🙏

2021-03-06 15:25 UTC, SeijiNumata commented on app/helpers/required_fields_helper.rb
> +  end
> ②に関してはそのままmessages << link_to('Discordアカウントを登録してください。', edit_current_user_path, class: 'card-list__item-link is-discord'.to_s.html_safe)を追加しようとするとrequired_fieldsのメソッドが長くなり、rubocopに引っかかるため、required_snsメソッドを作り致し方なく分割しました。

なるほどです〜
2行目のコミットメッセージまで読めていませんでした💦
教えて頂きありがとうございます〜

2021-03-06 15:26 UTC, SeijiNumata commented on app/views/users/_user.html.slim
> +                    i.fab.fa-discord
なるほど理解しました〜大変勉強になります！
自分で見つけられなかったので、公式のURLを貼っていただけるとはとても有り難いです。
ありがとうございます！！

2021-03-07 08:57 UTC, Yu-kichi commented on app/helpers/required_fields_helper.rb
> +  end
@SeijiNumata
①の修正が終わりましたので、お手隙の際に再レビューお願い致します🙏

以下一部重複になりますが簡単に経緯を書きました。
required_fieldsに追加して書こうとすると、Metrics/PerceivedComplexity(条件分岐が複雑すぎる)でlintが通らないため、メソッドを分割しました。
またlintを通すためにガード節で書いています。

```
messages << required_github

def required_github
  return if current_user.github_account?

  link_to('GitHubアカウントを登録してください。', edit_current_user_path, class: 'card-list__item-link is-github'.to_s.html_safe)
end

messages.compact
```
上記のように書いた方がわかりやすいかな〜と少し悩みました。(compactしなくてはいけないのが気になるのでやめました。)

2021-03-10 06:58 UTC, SeijiNumata reviewed
@Yu-kichi 
時間がかかってしまってすみません〜

修正お疲れ様です。
確認しました、LGTMです!!

2021-03-10 06:58 UTC, SeijiNumata commented on app/helpers/required_fields_helper.rb
> +  end
なるほどです〜
今の書き方で良いと思いますよ！
見やすくなっていると思います。

2021-03-10 11:22 UTC, Yu-kichi commented
@SeijiNumata 
レビューありがとうございます〜助かりました👍

@machida 
discordのid追加に伴いいくつかviewの修正をしています。
```
 .users-item-names__slack
    .users-item-names__slack-label
```

また上記のように一部slackのクラスを流用しているので、デザインのご確認をお願いした方がいいかなと思いました。
よろしくお願い致します！🙏

2021-03-11 06:57 UTC, komagata requested changes

2021-03-11 06:57 UTC, komagata commented on app/helpers/required_fields_helper.rb
> +      required_github(messages)
これってmessageをメソッドに渡して何にも返り値を受け取ってないので、本当にmessagesが変更されてるか怖い書き方かも？と思いました。

配列の場合は「値渡し」になってても結果大丈夫ですが、ちょっとセンシティブな作りになっているのでこの辺り他の作りにした方がいいかも？と思いました。

またこのぐらい構造化するのであればhelperじゃなくてクラスにしちゃってもいいかな〜と思いました。

[ruby 引数 参照渡し \- Google Search](https://www.google.com/search?q=ruby+%E5%BC%95%E6%95%B0+%E5%8F%82%E7%85%A7%E6%B8%A1%E3%81%97&oq=ruby+%E5%BC%95%E6%95%B0%E3%80%80%E5%8F%82%E7%85%A7%E6%B8%A1%E3%81%97&aqs=chrome..69i57j0i8i30l2j69i64.16403j0j7&sourceid=chrome&ie=UTF-8)

2021-03-13 11:43 UTC, Yu-kichi commented
@komagata
コメントありがとうございます🙏
>またこのぐらい構造化するのであればhelperじゃなくてクラスにしちゃってもいいかな〜と思いました。

すいませんクラスにするというのが具体的にどういうことかわかりませんでした。。
controllerやmodelで書いていくということでしょうか？
教えて頂けると助かります🙇‍♂️

2021-03-14 03:48 UTC, komagata commented
@Yu-kichi オブジェクト指向プログラミングを思い出して、model（クラス）を作るって感じです。

例えば`RequiredField`ってクラスを作るとか。（ちょっとこの名前が適切かどうか微妙ですが・・・）

2021-03-14 14:23 UTC, Yu-kichi commented
@komagata
回答ありがとうございます😊
modelだとhelperメソッドが使えないのでどこか他の場所に書くべきかもしれない〜と思って質問しました。

動作するようにmodelに書いてみましたが、あまり自信はありません。。
再レビューお願い致します🙏

2021-03-16 04:38 UTC, komagata commented
@Yu-kichi 全部クラスメソッドですとクラスにする意味があまりない感じです。
元のコードを見てみると、ある程度のデータ構造（つまり状態をもつ）ことがわかるのでそれをオブジェクト指向の考え方でクラスにする感じです。（データ構造をインスタンス・プロパティに落とし込む）

ちょっと動かしてないのでそのままじゃ動かないと思いますが、こういう感じのイメージです。

**model:**

```ruby
class RequiredField
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :description, :string
  attribute :github_account, :string
  attribute :discord_account, :string

  validates :description, presence: true
  validates :github_account, presence: true
  validates :discord_account, presence: true
end
```

**controller:**

```ruby

@required_field = RequiredField.new(
  description: current_user.description,
  github_account: current_user.github_account,
  discord_account: current_user.discord_account
)
```

**view:**

```slim
- unless @required_field.valid?
  h3 エラー
  ul
    - @required_field.errors.each do |error|
      li = error.message
```

2021-03-23 01:14 UTC, machida commented
@Yu-kichi 

> discordのid追加に伴いいくつかviewの修正をしています。

こちら、最後にデザインを調整しておきますー
ちょうど、SNS関係のところでいじりたいところがあったので、ついでにブラッシュアップしておきますー

2021-03-23 12:29 UTC, Yu-kichi commented
@komagata 
```
  include ActiveModel::Model
  include ActiveModel::Attributes
```
こちらを使ったmodelの書き方があることを教えていただき大変参考になりました！
いただいたサンプルをもとにテストが通るように作成しましたが、まだ不適切な部分はあるかと思います。。
大変遅くなり申し訳ございませんが、再レビューお願い致します。🙏

2021-03-23 12:47 UTC, Yu-kichi commented on app/views/application/_required_field.html.slim
> +          = link_to t(message.to_s) << 'を登録してください。', edit_current_user_path, class: "card-list__item-link is-#{message}"
@komagata
下のようにfull_messagesを使った場合には下記のようなymlの書き方で、
翻訳ができることを確認しました。
```
@required_fields.errors.full_messages.each do |message|
　= message
```

```
  activemodel:
    models:
      required_field:
    attributes:
      required_field:
        discord_account: Discordアカウント
```

しかし、テストを作成するときにHTMLのクラス名を動的に作成しようとしたため```@required_fields.errors```の書き方を使っています。

ただ、@required_fields.errorsの場合うまい翻訳の書き方がわからず、ymlの書き方が良くなのかなと不安に思っています。。

2021-03-23 13:39 UTC, komagata requested changes

2021-03-23 13:39 UTC, komagata commented on app/views/application/_required_field.html.slim
> +          = link_to t(message.to_s) << 'を登録してください。', edit_current_user_path, class: "card-list__item-link is-#{message}"
ActiveModelのエラメッセージの翻訳を使って「を登録してください」ってところもViewに書かずにいけるといいですね！

2021-03-24 07:25 UTC, Yu-kichi commented
@komagata 
コメントありがとうございます！
>ActiveModelのエラメッセージの翻訳を使って「を登録してください」ってところもViewに書かずにいけるといいですね！

model側でエラーメッセージを変更し、viewに書かないようにしてみました。
お手隙の際に再レビューお願い致します。🙏

2021-03-27 06:25 UTC, komagata requested changes

2021-03-27 06:25 UTC, komagata commented on app/views/users/_user.html.slim
> +            - if user.discord_account.present?
```suggestion
            - if user.discord_account?
```

こっちでいいかも？

2021-03-27 06:25 UTC, komagata commented on app/views/application/_required_field.html.slim
> +        - @required_fields.errors.each do |attribute, message|
スマートになりましたね👍

2021-03-27 07:43 UTC, Yu-kichi commented on app/views/users/_user.html.slim
> +            - if user.discord_account.present?
@komagata
21行目で.present?が使用されていたのでこちらに合わせて使用していました。
```
 - if user.slack_account.present?
```

同様に不要だと思うのでこちらも合わせて修正しました〜！

修正しましたので再レビューお願い致します。🙇‍♂️

2021-03-28 04:14 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-28 04:14 UTC, merged

2021-03-28 07:33 UTC, Yu-kichi commented
@machida 
こちらkomagataさんのレビューが終わりましたのでデザインをお願い致します🙏