「前の日報」リンクが、直近の日付でないバグの修正
fjordllc/bootcamp pull request #2429
Opened 2021-03-08 20:48 UTC by universato

Issue #2406

早めに直してもらいため、PRだします。

`previous`メソッドが`next`メソッドの対になるよう、順序の指定カラムを報告対象日(`reported_on`)に修正しました。

また、これに合わせてテストを追加したため、日報の件数が25件を越し、
1ページ目にあって日報が2ページにいき、順番のテストで日報が見つからず失敗するものがでたため、
簡易的にテスト対象の日報を変更しています。

2021-03-09 07:12 UTC, komagata requested changes

2021-03-09 07:12 UTC, komagata commented on app/models/report.rb
> +          .order(reported_on: 'DESC')
```suggestion
          .order(reported_on: :desc)
```

シンボル使う方がいいかもです〜

2021-03-09 20:10 UTC, universato commented on app/models/report.rb
> +          .order(reported_on: 'DESC')
シンボルにしました

2021-03-10 04:33 UTC, komagata approved these changes
修正ありがとうございます！

2021-03-10 04:34 UTC, merged