初日報の更新のたびに通知やメールが飛ぶ不具合の修正
fjordllc/bootcamp pull request #2444
Opened 2021-03-13 10:49 UTC by SeijiNumata

初日報の更新のたびに通知やメールが飛ぶ
#2205

2021-03-22 08:43 UTC, SeijiNumata commented
@hituzi-no-sippo 
こちらもし宜しければ、お時間ある時にレビューして頂けると嬉しいです。🙇‍♂️
よろしくお願いいたします

2021-03-22 09:18 UTC, hituzi-no-sippo commented
わかりました 😄 
1点確認なんですが、テストは作成していないのですか?

2021-03-22 09:39 UTC, SeijiNumata commented
@hituzi-no-sippo 
すみません、テスト作成していなかったので、テスト作成してからもう改めてレビュー依頼をします。
教えていただきありがとうございます。
よろしくお願いします。

2021-03-22 11:42 UTC, hituzi-no-sippo commented
@SeijiNumata 
今日間違って自分の方でも初めての日報か確認する機能を実装してしまいました 😅
実装後で参考になるかわかりませんが、一応ここに貼っておきます。
[WIPの日報を作成・更新した際、メンション通知とフォロワーへの通知をしないように修正](https://github.com/fjordllc/bootcamp/pull/2480/commits/5230ae25f66587b5dae91ca9d65b8150f6a0dac3)
@SeijiNumataさんが質問した[スクラム開発で、メンション関係のテストが通せない](https://bootcamp.fjord.jp/questions/850#answer_2597)と同じ現象などが発生して、テストは全て通ってないです。

2021-03-22 14:05 UTC, SeijiNumata commented
@hituzi-no-sippo 
ありがとうございます〜、参考にさせて頂きました。どこまで修正するかの定義って難しいな。と感じました。
個人的な意見としては、初めて提出した時にメンション飛ばすかどうかは別issueで対応しても良いような気がしました。

テスト記述したのでレビューお願いします！🙇‍♂️

2021-03-22 16:34 UTC, SeijiNumata commented
@hituzi-no-sippo 
ありがとうございます〜、参考にさせて頂きました。どこまで修正するかの定義って難しいな。と感じました。
個人的には、WIPでメンションを送らないようにする修正のみをして、２回目の提出でメンションを飛ばすかどうかは別issueで対応しても良いような気がしました。(詳しい事情を知らないので頓珍漢なことを言っているかもしれません。)
メンションの機能はgemに頼ってる部分もあるので、ハマるポイントが多そうです。(私がハマっただけかもしれないですが)

すみません、テスト記述したのでレビューお願いします🙇‍♂️

2021-03-23 03:54 UTC, hituzi-no-sippo commented
了解です 😄 
明日の22時までにはレビューする予定です。

2021-03-23 09:12 UTC, hituzi-no-sippo commented
レビュー開始します
終わったら再びコメントします。

2021-03-23 10:37 UTC, hituzi-no-sippo reviewed
レビュー終わりました~ 😄

2021-03-23 10:37 UTC, hituzi-no-sippo commented on test/system/notification/reports_test.rb
> +    assert_equal 'muryouさんがはじめての日報を書きました！',
```ruby
author_name = 'muryo'
message = "#{author_name}さんがはじめての日報を書きました！"
# なんかの処理
assert_equal message, notification_message
# なんかの処理
assert_no_text message
```

のように、値に意味がある部分は変数にしたほうが、コードが書きやすく読みやすいと思います～

2021-03-23 10:37 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.wip == false && report.user.reports.count == 1 && report.published_at.nil?
`!report.wip?` ではなく `report.wip == false` にした理由ってありますか ❓

2021-03-23 10:37 UTC, hituzi-no-sippo commented on test/system/notification/reports_test.rb
> +    click_link 'test title'
この `click_link 'test title'` もこのままだと、何をやっているかパッと見わからないので

```ruby
first_report_title = 'test title'
# 何かの処理
fill_in('report[title]', with: first_report_title)
# 何かの処理
click_link first_report_tilte
```

にするか、作成した初日報のidを取得して、 `visit report_path(first_report_id)` の方がわかりやすいと思います～ 😄

2021-03-23 12:06 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    create_notification_to_followers(report)
> send_notification_*** と create_notification_*** に統一するのではなく、別々にした理由はなんですか ❓

すみません、「２つのメソッドをなぜ１つにしなかったか」ということでしょうか？
その理由は、処理が大きく２つあるように見えたので、分けたという次第です。

> また、 notify_*** でも意味はわかると思います～

修正しました、ありがとうございます〜

2021-03-23 12:12 UTC, SeijiNumata commented on app/controllers/reports_controller.rb
> -    @report.published_at = Date.current
`@report.published_at = Date.current` の値を`Time.current` に変更した理由は、published_atがdatetimeを返すためです。

2021-03-23 12:12 UTC, SeijiNumata commented on app/controllers/reports_controller.rb
> -    @report.published_at = Date.current
コメントしました！
ありがとうございます〜

2021-03-23 12:12 UTC, SeijiNumata commented on app/controllers/reports_controller.rb
>      @noticeable = true
確かにそうですね〜
若干このissueと関係のないリファクタになってしまうので、触らなかったです。
修正いたしました。

2021-03-23 12:13 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    create_notification_to_followers(report)
> すみません、「２つのメソッドをなぜ１つにしなかったか」ということでしょうか？

いえ、こちらこそ言葉足らずですみません 🙇 
 `send_notification_to_company_adivisers` と `send_notification_to_company_adivisers` のように、最初の動詞を統一せず、`send` と `create` 別々にした理由が気になるということです～

2021-03-23 12:14 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.wip == false && report.user.reports.count == 1 && report.published_at.nil?
特にないです。
`!report.wip?`に修正しました。

2021-03-23 12:18 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +    assert_equal 'muryouさんがはじめての日報を書きました！',
なるほど〜勉強になります。
ありがとうございます。

2021-03-23 13:50 UTC, SeijiNumata reviewed
@hituzi-no-sippo 
丁寧にみてくださり本当にありがとうございます！🙇‍♂️
修正しました、よろしくお願いします！

追記：テストが落ちているので、まだレビュー待ってほしいです。

2021-03-23 13:50 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    create_notification_to_followers(report)
言われてみればその通りです。
気が付きませんでした、ありがとうございます😄

2021-03-23 13:50 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +  test '初日報の2回目のWIPではない提出で、初めての日報の通知を飛ばさない' do
確かにそうですね！ありがとうございます！

2021-03-23 13:50 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +    click_link 'test title'
こちらも修正しました、ありがとうございます。

2021-03-24 04:42 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    update_published_at(report) if !report.wip? && report.published_at.nil?
`send_first_report_notification(report)`は`after_create`、`after_update`で行わないとタイミングの問題で通知関連のテストが落ちてしまいます。
その他の部分は参考にさせていただき修正いたしました！
ありがとうございます！！

2021-03-24 04:45 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    return if !report.user.trainee? || !report.user.company_id?
こちら特に理由がなかったので、含めないように修正いたしました！

2021-03-24 08:54 UTC, SeijiNumata commented
@hituzi-no-sippo 
ありがとうございます！！
こちら修正させていただきました！

お時間ある時に、もう一度ご確認いただけると幸いです。
よろしくお願いいたします。

2021-03-24 12:35 UTC, hituzi-no-sippo commented
> @hituzi-no-sippo
> ありがとうございます！！
> こちら修正させていただきました！
> 
> お時間ある時に、もう一度ご確認いただけると幸いです。
> よろしくお願いいたします。🙇‍♂️

今週土曜の夜までにはレビューします 😄

2021-03-25 07:18 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    update_published_at(report) if !report.wip? && report.published_at.nil?
> send_first_report_notification(report)はafter_create、after_updateで行わないとタイミングの問題で通知関連のテストが落ちてしまいます。
この問題の原因はわかりますか ❔

2021-03-25 07:21 UTC, hituzi-no-sippo commented on app/controllers/reports_controller.rb
>      @noticeable = true
> @report.wip == falseになった後も、trueを返す必要があるようなので、 @noticableは必要そうです。
なぜ、 `true` を返す必要があるか説明できたら教えてください 😄 
あと、 `@noticable` はインスタンス変数である必要はあるのでしょうか?

2021-03-25 07:41 UTC, hituzi-no-sippo reviewed
レビュー終わりました 😄 
前回のレビューで気づけない部分がありすみません 🙇 
質問があるので、回答お願いします～

2021-03-25 07:41 UTC, hituzi-no-sippo commented on test/system/notification/reports_test.rb
> +    login_user 'muryou', 'testtest'
ここの `muryo` も変数  `author_name` を参照したほうが読みやすいと感じます～。

2021-03-25 07:41 UTC, hituzi-no-sippo commented on test/system/notification/reports_test.rb
> +    login_user 'yamada', 'testtest'
`yamda` は通知を受信したか確認するユーザーのようなので、 `receiver_user = 'yamada'` のようにして、 `login_user receiver_user, 'testtest'` と記載したほうが分かりやすいと感じます 😄

2021-03-25 07:41 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +  end
前回のはレビューで気づけなくてすみません 😭 

https://github.com/fjordllc/bootcamp/blob/84b2e27419127332ee98f4e7e370993a2dfaa089/app/controllers/reports_controller.rb#L160-L164

ここと全く一緒の判定していますが、別々にしている意味があったら教えてください ❔

"[初めて日報を提出した時だけ、メンション通知とフォロワー、アドバイザーへ通知するように修正](https://github.com/fjordllc/bootcamp/pull/2480)"で、modelに関数を作成して、その関数を利用するように私は書きました。

2021-03-25 07:41 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
>      Cache.delete_unchecked_report_count
前回のレビューで気づけませんでした。
`Cache.delete_unchecked_report_count` を `after_create` や `after_update` に別々にしている理由はなんですか ❔ 
`after_save` に `Cache.delete_unchecked_report_count` 書けば、両方ともいらないと考えています。

2021-03-26 12:26 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +    login_user 'muryou', 'testtest'
修正いたしました！
ありがとうございます！

2021-03-26 12:26 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +    login_user 'yamada', 'testtest'
勉強になります。
ありがとうござとうございます。

2021-03-26 12:27 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +  end
意味は特になかったです！

> "初めて日報を提出した時だけ、メンション通知とフォロワー、アドバイザーへ通知するように修正"で、modelに関数を作成して、その関数を利用するように私は書きました。

なるほど！　
参照先と同じように書きました！
勉強になります、ありがとうございます！

2021-03-26 12:28 UTC, SeijiNumata commented on app/models/report_callbacks.rb
>      Cache.delete_unchecked_report_count
確かにそうですね、全然気がつけませんでした。ありがとうございます！

2021-03-26 12:48 UTC, SeijiNumata commented
@hituzi-no-sippo 
丁寧に見ていただいて本当にありがとうございます。
こちらこそ抜けているところが気がつけずに申し訳ありません。

修正したので再度ご確認いただけると嬉しいです！
よろしくお願いいたします😄

2021-03-26 14:50 UTC, SeijiNumata reviewed
@hituzi-no-sippo 
レビューありがとうございます！修正しました。

`@noticeable`のリファクタリングの件だけ、うまくできませんでした。😭
詳細はコメントいたしました。

ご確認よろしくお願いします。

2021-03-26 14:50 UTC, SeijiNumata commented on app/controllers/reports_controller.rb
>      @noticeable = true
> なぜ、 true を返す必要があるか説明できたら教えてください 😄

すみません、よく考えたらわかりませんでした。
試しにここを 
```ruby
def check_noticeable
  @report.published_at.nil? && !@report.wip
end
```
のようにしても、確かに処理は同じはずですね。デバッグして確かめました。

テストが落ちてしまうことが問題で、
`test/system/reports_test.rb:412 test_WIPで保存した日報を初めて提出した時にだけslackに通知がいく`と、　
`test/system/reports_test.rb:434 test_最初の日報を提出した時にだけslackに通知がいく` で落ちてしまいます。

デバッグしてみたのですが、どちらも原因が分からないです。
テストでは`assert_no_match 'kensyu さんが日報を提出しました'`とログを比較しているようなのですが、なぜ上記のようにするとログが書き込まれてしまうのか分かりません。

@hituzi-no-sippo さんは原因が分かりますか？

> あと、 `@noticable` がインスタンス変数である理由はなんですか ❔

すみません、上記と同様にこれの理由も分かりませんでした。
上記の書き方で良いと思うのですが、それだとテストが落ちてしまいます。

2021-03-26 19:12 UTC, hituzi-no-sippo commented on app/controllers/reports_controller.rb
>      @noticeable = true
> テストではassert_no_match 'kensyu さんが日報を提出しました'とログを比較しているようなのですが、なぜ上記のようにするとログが書き込まれてしまうのか分かりません。
>
> @hituzi-no-sippo さんは原因が分かりますか？

https://github.com/fjordllc/bootcamp/blob/504adf003daf1ab80002f2655c4ebbb7d9b36119/app/controllers/reports_controller.rb#L51-L53

この `@report.save` のときに `after_save` の `update_published_at(report) if report.first_public?` が実行されて、 `@report.save` 前後で `published_at` の値が変更されるからだと考えています。

そのため、私は次のように書きました 😄 

https://github.com/fjordllc/bootcamp/blob/c044ed7544b661869f378f7aaa1bc2a929135733/app/controllers/reports_controller.rb#L51-L61

> あと、 @noticable がインスタンス変数である理由はなんですか ❔
>
> すみません、上記と同様にこれの理由も分かりませんでした。

上述したコードのようにローカル変数に値を渡してもいいのではないでしょうか ❓ 

> そもそもこのスラックに日報を通知する機能ってブートキャンプのアプリ使ってて見たことがないのですが、使われているのでしょうか？

コミュニケーションツールがdiscordに移行しているので、
[slackの通知を削除 by Yu\-kichi · Pull Request \#2488 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/2488)で削除しますね。
ただ、日報の初提出時にdiscordへ通知を送信する機能を実装するかもしれませんね。

2021-03-26 19:13 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    update_published_at(report) if !report.wip? && report.published_at.nil?
これの回答もできればお願いします～

2021-03-28 04:23 UTC, SeijiNumata commented
@hituzi-no-sippo 
返信ありがとうございます！
修正いたしました。

mainとのコンフリクト を修正したところ、修正部分がかなり被っていて、差分がかなり消えました。

よろしくお願いします。

2021-03-28 04:24 UTC, SeijiNumata commented on app/controllers/reports_controller.rb
>      @noticeable = true
なるほど、理解いたしました。ありがとうございます。
mainに`@noticeable`の変更がマージされていたため、私が修正する必要は無くなったようです。
よろしくお願いします。

2021-03-28 07:30 UTC, hituzi-no-sippo requested changes
レビュー終りました～ 😄

2021-03-28 07:30 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
> send_first_report_notification(report)はafter_create、after_updateで行わないとタイミングの問題で通知関連のテストが落ちてしまいます。

この問題の原因わかりますか ❔
できれば、これ解決して `notify_users` 内に入れたいですね。

前まで気づきませんでしたが、 これも  `notify_***` に関数名変更した方がいいと感じます～ 😄

2021-03-28 07:30 UTC, hituzi-no-sippo commented on test/system/notification/reports_test.rb
> +  end
`assert_notify_only_at_first_published_of_report` を利用しない理由はなんですか ❓ 
今気づいたんですけど、これって誰かが  `fixtures` に `muryou` の日報を作成したら、このテスト失敗しますよね ❔ テスト内容に `muryo` のレポートを全て削除する処理を入れて、対策した方がいいと感じます。

2021-03-28 13:21 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
> この問題の原因わかりますか ❔
できれば、これ解決して notify_users 内に入れたいですね。

調べて見たところ、原因はpublished_atが定義される前に通知を送る必要があったからでした。
上記理由で`notify_users`に含めることはできませんでしたが、`after_save`にまとめることはできました。

> 前まで気づきませんでしたが、 これも notify_*** に関数名変更した方がいいと感じます～ 😄

修正いたしました、ありがとうございます！😄

2021-03-28 13:21 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    update_published_at(report) if !report.wip? && report.published_at.nil?
すみません、見落としました。
https://github.com/fjordllc/bootcamp/pull/2444#discussion_r602878975 にコメントいたしました。
ご確認お願いします。

2021-03-28 13:25 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +  end
> assert_notify_only_at_first_published_of_report を利用しない理由はなんですか ❓

すみません、私のミスです。テストが変更されていたことに気がつけませんでした。
`assert_notify_only_at_first_published_of_report`を使ったテストに修正いたしました。

> テスト内容に muryo のレポートを全て削除する処理を入れる(他のテストに影響ある可能性あり) or コメントを書いておくなどして対策した方がいいと感じます。

その通りですね、コメントを入れて対策いたしました。
ありがとうございます😄

2021-03-28 16:22 UTC, SeijiNumata commented
@hituzi-no-sippo 
レビューありがとうございます！😄
修正いたしました、ご確認お願いします！🙇‍♂️

2021-03-28 19:20 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
> 原因はpublished_atが定義される前に通知を送る必要があったからでした。

どのような理由で `published_atが定義される前に通知を送る必要` があるのですか ❓ 軽くコードを見ましたが、そのような箇所発見できませんでした。

2021-03-28 19:25 UTC, hituzi-no-sippo reviewed
コメントしました。確認おねがいします～ 😄

2021-03-28 19:25 UTC, hituzi-no-sippo commented on test/supports/notification_helper.rb
> +  end
なぜ、`test '初日報は初めて公開した時だけ通知する' do` に直接 ` "#{writer_login_name}さんがはじめての日報を書きました！"` を書かず、この関数を作成したのですか ❔

2021-03-28 19:25 UTC, hituzi-no-sippo commented on test/system/notification/reports_test.rb
> +    # muryouが初の日報提出である必要があります。muryouの日報はtest/fixtureには作成しないでください。
コメント後に気づきましたが、ここでユーザー作成して、そのユーザーを利用するのが1番良いかもしれません。
ユーザー作成が無理でも、日報を書いていない専用のユーザーをfixtureに作成するのもありだと思います。

2021-03-29 14:21 UTC, SeijiNumata commented on test/supports/notification_helper.rb
> +  end
周囲のテストと書き方を合わせたのですが、必要なかったですかね？

2021-03-29 16:33 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +    # muryouが初の日報提出である必要があります。muryouの日報はtest/fixtureには作成しないでください。
ユーザー作成が難しかったため、日報を書いていない専用のユーザーをfixtureに作成しました。
ありがとうございます。

2021-03-29 16:59 UTC, SeijiNumata commented
@hituzi-no-sippo 
レビューありがとうございます！
修正いたしましたのでご確認お願いします。

2021-03-29 17:00 UTC, SeijiNumata commented on test/system/users_test.rb
> +      login_user 'nipponashi', 'testtest'
ユーザーを追加したことで、このテストを修正しないと落ちてしまうため修正しました。

2021-03-29 18:49 UTC, hituzi-no-sippo reviewed
@SeijiNumata 
コメントしました～

こちらの[コメント](https://github.com/fjordllc/bootcamp/pull/2444#discussion_r602920367)の回答も忘れずお願いします～ 😄

2021-03-29 18:49 UTC, hituzi-no-sippo commented on db/fixtures/users.yml
> +nipponashi: # 日報を投稿していないユーザー
`nipponashi`  `u` 抜いているのはわざとできですか ❔

2021-03-29 18:49 UTC, hituzi-no-sippo commented on test/fixtures/users.yml
> +  login_name: nipponashi
こちらも `u` 抜いているのはわざとですか ❔

2021-03-29 18:49 UTC, hituzi-no-sippo commented on test/system/notification/reports_test.rb
> +    mention_target_login_name = 'kimura'
前回のレビュー時点で気づけず、すみません 🙇 
ここの変数名はなぜ `mention_target_login_name` なのですか ❔

2021-03-30 11:44 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
提出の２回目以降に送らないように、`notify_first_report`をする時は`first_public? `(つまり`!WIP`かつ`published_atがnil`の時)という条件を利用しているためです。

https://github.com/fjordllc/bootcamp/blob/d91f45fb8c1560f30c84404f098b3aa1898efc3c/app/models/report_callbacks.rb#L4-L14

2021-03-30 11:45 UTC, SeijiNumata commented on db/fixtures/users.yml
> +nipponashi: # 日報を投稿していないユーザー
わざとだったのですが、言われてみるとおかしい気がしたので修正しました。

2021-03-30 11:46 UTC, SeijiNumata commented on test/fixtures/users.yml
> +  login_name: nipponashi
わざとだったのですが、言われてみるとおかしい気がしたので修正しました。

2021-03-30 11:46 UTC, SeijiNumata commented on db/fixtures/users.yml
> +  twitter_account: nipponashi
修正しました！
ありがとうございます！

2021-03-30 11:47 UTC, SeijiNumata commented on test/system/notification/reports_test.rb
> +    mention_target_login_name = 'kimura'
確かに、ここの変数名の付け方ちょっと不自然でした。
`check_notification_login_name `と変更いたしました。

2021-03-30 12:39 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
> 提出の２回目以降に送らないように、notify_first_reportをする時はfirst_public? (つまり!WIPかつpublished_atがnilの時)という条件を利用しているためです。

すみません。この説明を読んでも、 `notify_users` 内に含めることができない理由がわかりません。

`notify_users` は `return unless report.first_public?` があるので、2回目以降の提出では実行されません。そのため、`notify_users` に `notify_first_report` を追加しても問題ないと考えています。
`notify_first_report` 内の処理は `published_at` が `nil` かどうかで変更されるのでしょうか ❓ コードを読んでも、そのような箇所は見つけることができませんでした。

2021-03-31 02:41 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
すみません、私が勘違いしていました。

> `notify_users` は `return unless report.first_public?` があるので、2回目以降の提出では実行されません。そのため、`notify_users` に `notify_first_report` を追加しても問題ないと考えています。

その通りです。
`notify_first_report` に`notify_first_report` を追加するとテストが落ちていたのですが、やり直したら緑になりました。

`notify_first_report` に追加したのでご確認お願いします。

2021-03-31 02:43 UTC, SeijiNumata commented
@hituzi-no-sippo 
レビューありがとうございます！！
修正いたしました！　https://github.com/fjordllc/bootcamp/pull/2444#discussion_r604555327 も返しました。

ご確認お願いします！

2021-03-31 04:05 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
> `notify_first_report` に `notify_first_report` を追加するとテストが落ちていたのですが、やり直したら緑になりました。問題ありませんでした。

このやり直ししたときコードは全く一緒だったのでしょうか ❓

2021-03-31 08:00 UTC, SeijiNumata commented on test/supports/notification_helper.rb
> +  end
なるほどです、ここでしか使っていないので修正しました！

2021-04-02 19:37 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
これの回答お願いします～ 😄

2021-04-13 10:58 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
コードは同じだったはずです〜
全部緑になる時と同じ環境で、たまにテストが落ちてしまうことがあります。
原因は分かりません。

2021-04-13 13:07 UTC, SeijiNumata commented
@hituzi-no-sippo 
https://github.com/fjordllc/bootcamp/pull/2444#discussion_r612342550
コメント返しました。
ご確認お願いします。

2021-04-14 01:13 UTC, hituzi-no-sippo approved these changes
1点、自分では判断できない箇所があり、そこは駒形さんに聞いてみてください。
それ以外はOKだと思います。
長期間お疲れさまでした～ 😄

2021-04-14 01:13 UTC, hituzi-no-sippo commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
> 全部緑になる時と同じ環境で、たまにテストが落ちてしまうことがあります。
> 原因は分かりません。

これって今も発生しているのでしょうか ❓ 
私ではこの問題をそのままにしても良いか判断できないので、駒形さんに判断を仰いでみてください。
今も発生するなら、テストが落ちたときのログをメモったほうがいいと思います。

2021-04-16 09:12 UTC, SeijiNumata commented on app/models/report_callbacks.rb
> +    send_first_report_notification(report) if report.first? && report.first_public?
今のところ発生していないのですが、何回もやれば落ちるかもしれないです。

> 今も発生するなら、テストが落ちたときのログをメモったほうがいいと思います。

承知しました。ありがとうございます。

2021-04-16 09:19 UTC, SeijiNumata commented
@hituzi-no-sippo 
こちらこそ、長い間丁寧にレビューしていただき本当にありがとうございました。
非常に勉強になりました。
テストが落ちてしまう問題は駒形さんに伺ってみます。

@komagata 
こちらレビューをお願いいたします。

https://github.com/fjordllc/bootcamp/pull/2444#discussion_r612870214 で話に上がったのですが、
落ちたテストを再度もう一度実行するだけで緑になったことがありました。(原因は分からないです。)
その問題について、一旦このプルリクでは対応しなくても大丈夫でしょうか？

2021-04-16 19:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

テストはmainの方で治ってるので大丈夫です〜

2021-04-16 19:55 UTC, merged

2021-04-19 07:47 UTC, SeijiNumata commented
@komagata 
確認とマージありがとうございます！

テストの件承知いたしました！