お知らせ一覧をVue.js化したい
fjordllc/bootcamp pull request #2450
Opened 2021-03-14 04:55 UTC by tam-03

#2410

2021-03-16 03:36 UTC, komagata commented
@tam-03 通知一覧や日報一覧、提出物一覧などが既にVue.js化されていますのでそちらを参考にするとやりやすいと思います〜

2021-03-16 20:29 UTC, tam-03 commented
@harukus 
こちらのレビューをお願いしてもよろしいでしょうか？🙋‍♂️
もし忙しければ、お手数ですが開発メンバーのどなたかにレビューを回して下さい！🙇🏻‍♂️

2021-03-17 04:21 UTC, harukus commented
@tam-03 
かしこまりました。本日中にレビューいたします！🙆‍♀️

2021-03-17 06:28 UTC, tam-03 commented
@harukus 
レビュー中でしたらすみません。空のコミットの削除を忘れていたので削除しました🙇🏻‍♂️

2021-03-17 12:48 UTC, harukus commented
ごめんなさい、もう少し時間かかりそうです:bow:

2021-03-18 08:46 UTC, harukus requested changes
手元で動作確認できました！とてもVue.jsだと表示がスムーズで良いですよね
コードがあまり分からなかったのですが（時間をかけたのにごめんなさい）、１点ありますので確認お願いいたします:bow:

2021-03-18 08:46 UTC, harukus commented on app/views/api/announcements/_announcement.json.jbuilder
> +json.newURL new_announcement_path(id: announcement)
他がスネークケースで統一されているので`newURL`もスネークケースにした方が良いと思いました！

2021-03-18 13:35 UTC, tam-03 commented on app/views/api/announcements/_announcement.json.jbuilder
> +json.newURL new_announcement_path(id: announcement)
修正しました！🙋‍♂️

2021-03-18 13:36 UTC, tam-03 commented
@harukus 
いえ！お忙しい中ありがとうございます🙇🏻‍♂️
修正致しましたので、再度ご確認をよろしくお願いいたします！🙋‍♂️

2021-03-18 20:25 UTC, harukus approved these changes
確認できました！
レビューリクエストされていなかったので、私自身でしてしまいました:eyes:
（合っているのかわかりませんが:bow:）

2021-03-19 01:45 UTC, tam-03 commented
@harukus 
あ！失礼しました😅
ありがとうございます！

@komagata 
こちら、レビューをよろしくお願い致します🙋‍♂️

2021-03-21 15:30 UTC, komagata requested changes

2021-03-21 15:30 UTC, komagata commented on app/javascript/announcements.vue
> +  created () {
`created ()`

このスペースがあるメソッドとないメソッドとあるのでどちらかに統一した方が良さそうです〜

2021-03-21 15:30 UTC, komagata commented on app/views/api/announcements/_announcement.json.jbuilder
> +if announcement.published_at
```suggestion
if announcement.published_at?
```

2021-03-21 16:52 UTC, tam-03 commented on app/javascript/announcements.vue
> +  created () {
スペースありに統一しました！

2021-03-21 16:53 UTC, tam-03 commented on app/views/api/announcements/_announcement.json.jbuilder
> +if announcement.published_at
修正しました！

2021-03-22 04:33 UTC, komagata requested changes

2021-03-22 04:33 UTC, komagata commented on app/javascript/announcements.vue
> +  created () {
他のプログラムと統一した方が良さそうです。
例えばcomment.vueではスペースなしでした。

2021-03-22 05:47 UTC, tam-03 commented
@komagata 
スペースをアリに統一しました！🙋‍♂️

2021-03-23 13:27 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-23 13:27 UTC, merged