ドットがあるタグのリンクと検索を修正
fjordllc/bootcamp pull request #2452
Opened 2021-03-15 06:25 UTC by hituzi-no-sippo

編集中

issue
#2448 #2350 に対応

## 概要

ドットがあるタグのリンクではエラー、検索ではドット以降の文字が検索文字に含まれていない。

### Viewの変更部分のgif

## 修正理由

* リンク: エラーが発生
* 検索: 検索結果が違うため

## ついでに追加した機能

全角スペースを入力した際、アラートを表示するようにした。

2021-03-15 07:59 UTC, hituzi-no-sippo commented
@tam-03 
お手隙の際にレビューよろしくお願い致します 🙏

2021-03-16 14:57 UTC, tam-03 approved these changes
@hituzi-no-sippo 
遅くなりすみません😅
コメントやbefore/afterがあってレビューしやすかったです！🙇🏻‍♂️
レビューをお願いする際の勉強にもなりました！

完了です〜🙆‍♂️

2021-03-16 20:29 UTC, hituzi-no-sippo commented
@tam-03 
レビューありがとうございます 😄 

> 遅くなりすみません😅

気にしてないので大丈夫です～

@komagata 
レビューよろしくおねがいします 🙏

2021-03-17 03:10 UTC, komagata requested changes

2021-03-17 03:10 UTC, komagata commented on app/javascript/tags.vue
> +      const { text } = obj.tag
ある程度の量の同じ内容が複数箇所にあるので共通化したいですね。

2021-03-17 03:10 UTC, komagata commented on test/system/current_user_test.rb
> +  include TagHelper
includeしたものはここから下に限らず使えちゃうと思うので、includeはまとめて上の方に書いた方がいいかもです。

2021-03-17 12:41 UTC, hituzi-no-sippo commented on test/system/current_user_test.rb
> +  include TagHelper
わかりました 😄 
次のように書いて  `include` の位置を変更します。

```ruby
class CurrentUserTest < ApplicationSystemTestCase
  include TagHelper
  setup { login_user 'komagata', 'testtest' }
```

2021-03-17 12:45 UTC, hituzi-no-sippo commented on app/javascript/tags.vue
> +      const { text } = obj.tag
[ミックスイン](https://jp.vuejs.org/v2/guide/mixins.html)を利用して、共通化できないかやってみます 😃

2021-03-22 02:49 UTC, hituzi-no-sippo commented on test/system/current_user_test.rb
> +  include TagHelper
e7b9d10 で修正しました 😄

2021-03-22 02:49 UTC, hituzi-no-sippo commented on app/javascript/tags.vue
> +      const { text } = obj.tag
ミックスインを利用して b7eba2f で共通化しました 😃

2021-03-22 02:50 UTC, hituzi-no-sippo commented
@komagata 
フィードバック部分を修正しました。
確認おねがいします 🙏

2021-03-23 13:26 UTC, komagata commented on app/javascript/mixins/check-tag.js
> +export default {
これまでmixinsという分け方がなかったのであれば周りに合わせてディレクトリを作らず普通にファイルをおきたい感じがしました。

2021-03-23 22:07 UTC, hituzi-no-sippo commented on app/javascript/mixins/check-tag.js
> +export default {
`mixins` という分け方がなかったので、他のjsファイルと同じように `app/javacript` 直下に配置するように 544d58b で変更しました。

2021-03-23 22:09 UTC, hituzi-no-sippo commented
@komagata
フィードバック修正しました 😄 
ご確認よろしくおねがいします 🙇

2021-03-27 06:05 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-27 06:05 UTC, merged