お知らせのAPIで一般ユーザーの「公開」を制限
fjordllc/bootcamp pull request #2470
Opened 2021-03-18 08:18 UTC by tam-03

#2469 
---

2021-03-19 14:16 UTC, tam-03 commented
@hisaotoriyama 
お疲れ様です。こちらのレビューをお願いしてもよろしいでしょうか？🙋‍♂️

APIという点や、バグが分かりづらい、という事もあるので不明な点があればこのPR上でメンションを頂ければと思います！🙇🏻‍♂️

もしお忙しければ、お手数ですが開発メンバーにレビューを回して下さい。

2021-03-20 03:54 UTC, hisaotoriyama reviewed
@tam-03 
お疲れ様です。丁寧に対応されていて読みやすいと思いました。少しコメントさせてもらいました。よろしくお願いいたします。

2021-03-20 03:54 UTC, hisaotoriyama commented on test/integration/api/announcements_test.rb
> +            }
管理者でないkimuraさんである以上、"wip"がTrueであろうとそれ以外であろうと結果はbad_requestになるので"wip":trueを削除したものと理解しました。

2021-03-20 03:54 UTC, hisaotoriyama commented on test/integration/api/announcements_test.rb
> +              description: 'patchのテストです'
上記と異なり、"wip":trueのケースもテストする必要はないのでしたでしょうか。こちらの理解不足で伺うのかもしれませんがご教示ください。

2021-03-20 05:57 UTC, tam-03 commented on app/controllers/api/announcements_controller.rb
> +    if !current_user.admin? && announcement_params['wip'] != true
おっしゃる通りです！🙆‍♂️

2021-03-20 05:57 UTC, tam-03 commented on test/integration/api/announcements_test.rb
> +            }
こちらなのですが、test側で、`wip: true(真偽値)`でテストをしても文字列の`"true"`に変換されてしまって、`bad_request`になってしまうんです。。

管理者でないkimuraさん(一般ユーザー)でも、「公開」と「削除」だけが出来ないので、`"wip": true`であれば「編集」は出来るのですが、それをテストしようとしても、test側で文字列に変換されて`bad_request`になるので、例えば、

testのparamsで、`"wip": true`(真偽値)
```
{
  "title": "テスト",
  "description": "patchのテストです",
  "wip": true
}
```

この様に意図して送っても、testのparamsから送られているリクエストは、

```
{
  "title": "テスト",
  "description": "patchのテストです",
  "wip": "true"
}
```

こうなって、実際は`"wip": "true"`で文字列になってしまいます。

なので、「テストで一般ユーザーが編集出来る事を確認するテストが書けなかった」という理由です。。

試しにparamsの`wip: 〇〇`に、真偽値を返す様な`==`等を入れてみたりしたのですが、上手くいかず、諦めて、逆に「`"wip": false`だと編集できない事を確認」するtestのみにして、「APIを使い編集できる事を確認するのは管理者ユーザー(komagata)で確認」する事にしました。

---

ちなみに、paramsに`wip`の指定がなければ、announcementsモデルの仕様で、デフォルトで`wip: false`となります。
`db/schema.rb`
```ruby
create_table "announcements", force: :cascade do |t|
    t.string "title", null: false
    t.text "description", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "user_id"
    t.integer "target", default: 0, null: false
    t.boolean "wip", default: false, null: false
    t.datetime "published_at"
    t.index ["user_id"], name: "index_announcements_on_user_id"
  end
```

2021-03-20 05:57 UTC, tam-03 commented on test/integration/api/announcements_test.rb
> +              description: 'patchのテストです'
こちらも上記の理由からテストしていません💦

2021-03-20 13:08 UTC, hisaotoriyama reviewed
@tam-03 
遅くなりましたが質問の形で恐縮ですが返信させていただきました。Test難しいですね。お疲れ様です。

2021-03-20 13:08 UTC, hisaotoriyama commented on test/integration/api/announcements_test.rb
> +            }
了解しました。前回は問題を誤解していました。失礼しました。wip: true(真偽値)でテストをしても文字列の"true"に変換されてしまうので、wip: true(真偽値)のテストはできなかった。一方でwip:false(真偽値）の場合は確認したことも理解しました。
最後に一つだけ質問させてください。testではwip:false(真偽値）も文字列で読んでいる可能性があるのでしょうか。つまり
```ruby
{
  title: 'test',
  description: 'patchのテストです', 
  wip: false
}
```
を入れてもwip:falseは文字列として読まれて、wip:true(真偽値）ではないと解釈されているということですよね？違ったらごめんなさい。

2021-03-20 13:08 UTC, hisaotoriyama commented on test/integration/api/announcements_test.rb
> +              description: 'patchのテストです'
かしこまりました。

2021-03-21 06:11 UTC, tam-03 commented on test/integration/api/announcements_test.rb
> +            }
おっしゃる通りです！

2021-03-21 06:22 UTC, hisaotoriyama commented on test/integration/api/announcements_test.rb
> +            }
了解しました。👍

2021-03-21 06:22 UTC, hisaotoriyama commented
@tam-03 
ご説明ありがとうございました。私のPreReviewは完了といたします。

2021-03-21 06:29 UTC, tam-03 commented
@hisaotoriyama 
レビューをありがとうございました！🙇🏻‍♂️

@komagata 
こちらのレビューをよろしくお願い致します🙇🏻‍♂️

2021-03-21 15:36 UTC, komagata requested changes

2021-03-21 15:36 UTC, komagata commented on app/controllers/api/announcements_controller.rb
> +    if !current_user.admin? && announcement_params['wip'] != true
`true`と比較してるのが気になりました。

rubyの式は必ずtrue/falseどちらかに評価されるので基本的にtrue/falseと条件式で比較することはないです。

またparamsには文字列としてのtrueではなく本物のTrue/Falseが入ってるのかどうかちょっと気になりました。

2021-03-22 08:56 UTC, tam-03 commented
@komagata 
条件式の上の方にコメントを追加しました！🙋‍♂️

2021-03-23 13:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-23 13:06 UTC, komagata commented on app/controllers/api/announcements_controller.rb
> +    # boolean型のtrueの時のみ「更新」が出来る様、明示的にtureを書き込んでいます。
👍

2021-03-23 13:06 UTC, komagata commented
確認しました、OKですー🙆‍♂️

2021-03-23 13:06 UTC, merged