お知らせは誰でも編集できるようにしたい
fjordllc/bootcamp pull request #2479
Opened 2021-03-22 09:12 UTC by SeijiNumata

https://github.com/fjordllc/bootcamp/issues/2412

2021-03-22 14:45 UTC, SeijiNumata commented on test/system/announcements_test.rb
> +  end
テストって必要ですかね？
テストが増えると変更があった時に、修正量も比例して増えて保守性が悪くなるので、書けばいいって問題ではないと思うのですが、、、
このテストも小さい修正なので不要な気がして、どこまでテストを書くべきかの基準がよく分からず迷っています。

2021-03-23 01:18 UTC, machida commented
@SeijiNumata 

すいません、ちょっとこちらの仕様について思うところが出てきたので、仕様の変更をお願いしたいです🙇‍♂️

これがリリースされると、お知らせを全員が編集できてしまう、これは意図通りなのでOKなのですが、なんかみんな編集できてしまうことがバグかと勘違いしそうな気がして。。。

なので、一般ユーザーも編集できるが、編集できるのは WIP の状態のお知らせだけにする、というのはどうか、と考えました。公開ができるのもメンターだけなので、そっちのほうがわかりやすいし、バグだと思われる勘違いが起きないんじゃないか、と。

急な変更で申し訳ないのですが、この仕様にした場合、作業の工数が大きく変わりそうでしたらポイントを振り直したいと思います。

2021-03-23 04:20 UTC, SeijiNumata commented
@machida 
> 一般ユーザーも編集できるが、編集できるのは WIP の状態のお知らせだけにする

仕様の変更承知しました。大きく工数変わらないと思うので、ポイントはこのままで大丈夫です。

一点確認です。
既存の仕様通り、【一般ユーザーであっても、その人がお知らせの**作成者**である場合は、提出済み、WIP共に「コピー、削除」もできる】という仕様のままでよろしいでしょうか？

***
確認のため、以下に仕様をまとめておきます。

既存仕様
|      | 管理者             | 一般ユーザー | 一般ユーザーのお知らせ作成者 | 
| ---- | ------------------ | ------------ | ---------------------------- | 
| WIP  | 編集、削除、コピー | ✖︎         | 編集、削除、コピー           | 
| 提出 | 編集、削除、コピー | ✖︎         | 編集、削除、コピー           | 

変更あと
|      | 管理者             | 一般ユーザー | 一般ユーザーのお知らせ作成者 | 
| ---- | ------------------ | ------------ | ---------------------------- | 
| WIP  | 編集、削除、コピー | 編集         | 編集、削除、コピー           | 
| 提出 | 編集、削除、コピー | ✖︎         | 編集、削除、コピー           | 


よろしくお願いいたします。

2021-03-24 05:32 UTC, machida commented
@SeijiNumata 

> 既存の仕様通り、【一般ユーザーであっても、その人がお知らせの作成者である場合は、提出済み、WIP共に「コピー、削除」もできる】という仕様のままでよろしいでしょうか？

すいません、そこ抜けてました。
はい！既存の仕様通りでお願いします。

仕様のまとめ、ありがとうございます！！
それでお願いします🙏

2021-03-24 08:47 UTC, SeijiNumata commented
@machida 
承知いたしました!!

2021-03-24 09:20 UTC, SeijiNumata commented
@gallardo16 
もしよろしければ、レビューして頂けると嬉しいのですがご都合いかがでしょうか？
よろしくお願いいたします。🙇‍♂️

2021-03-24 12:10 UTC, gallardo16 commented
@SeijiNumata 
了解です！レビューさせていただきます😄

2021-03-24 14:36 UTC, SeijiNumata commented
@gallardo16 
ありがとうございます〜
一部クラスが適用されていないミスがあったので修正しました。
また、テストが落ちていたので、やり直しています。

テストが緑になるようになったらもう一度報告をいたしますので、しばしお待ちください。
お手数おかけして申し訳ありません。🙇‍♂️

2021-03-24 15:13 UTC, SeijiNumata commented
@gallardo16
テスト通りました。
レビューして大丈夫です。

2021-03-25 14:00 UTC, gallardo16 reviewed
一点だけコメントしました。
あとこのissueのカバー範囲では無いかもしれませんが、「コピー」は誰でもどのお知らせから出来たら便利かなとも思いました。
ご確認お願いします🙇‍♂️

2021-03-25 14:00 UTC, gallardo16 commented on app/views/announcements/_announcement.html.slim
> +           -if @announcement.wip || admin_login?
「一般ユーザー」が自分で作成した、公開されている(WIPではない)お知らせを「内容修正」出来ないと思いました。

2021-03-25 14:34 UTC, SeijiNumata commented on app/views/announcements/_announcement.html.slim
> +           -if @announcement.wip || admin_login?
本当ですね、気がつけませんでした。
ありがとうございます。修正いたしました。

2021-03-25 14:45 UTC, SeijiNumata commented
@gallardo16 
レビューありがとうございます！🙏
修正いたしました！

> あとこのissueのカバー範囲では無いかもしれませんが、「コピー」は誰でもどのお知らせから出来たら便利かなとも思いました。

確かにそうかもしれないです。
machidaさんに提案してみるので、レビューバックは少々お待ちください🙇‍♂️

 @machida さん、【「コピー」は誰でもどのお知らせからできるようにする】という提案があるのですが、いかがいたしますか？
お知らせはリリースノートなどはフォーマットが決まっているので、結構現実的にコピー機能は使われると思われます。
デメリットは、コピーだけできるのは不思議な感じもあるので、もしかしたらバグかと思われるかもしれないです。

***
既存仕様
|      | 管理者             | 一般ユーザー | 一般ユーザーのお知らせ作成者 | 
| ---- | ------------------ | ------------ | ---------------------------- | 
| WIP  | 編集、削除、コピー | ✖︎         | 編集、削除、コピー           | 
| 提出 | 編集、削除、コピー | ✖︎         | 編集、削除、コピー           | 

変更あと
|      | 管理者             | 一般ユーザー | 一般ユーザーのお知らせ作成者 | 
| ---- | ------------------ | ------------ | ---------------------------- | 
| WIP  | 編集、削除、コピー | 編集         | 編集、削除、コピー           | 
| 提出 | 編集、削除、コピー | ✖︎         | 編集、削除、コピー           | 

今回の提案
|      | 管理者             | 一般ユーザー | 一般ユーザーのお知らせ作成者 | 
| ---- | ------------------ | ------------ | ---------------------------- | 
| WIP  | 編集、削除、コピー | 編集 ,コピー       | 編集、削除、コピー           | 
| 提出 | 編集、削除、コピー | コピー       | 編集、削除、コピー           | 

よろしくお願いします。🙇‍♂️

2021-03-25 16:40 UTC, machida commented
@SeijiNumata 連絡ありがとうございます！！なるほど、コピーは使いそうな気がしました。コピーはできるようにしたいと思いますー。ただ、ちょっと見せ方を自分で作ったお知らせ以外のときのコピーだけデザインの方でいじりたいと思います。

2021-03-26 06:42 UTC, gallardo16 commented
「コピー」の件、対応してくださりありがとうございます🙇‍♂️

修正を確認しました。OKだと思います！
あとは「コピー」の実装を待ち、コードレビューしたいと思います。

2021-03-27 15:49 UTC, SeijiNumata commented
@gallardo16 

> 「コピー」の件、対応してくださりありがとうございます🙇‍♂️

こちらこそ提案いただきありがとうございます。

> 修正を確認しました。OKだと思います！
あとは「コピー」の実装を待ち、コードレビューしたいと思います。

確認いただきありがとうございます！

コピーの件に対応できるように修正しました。
https://github.com/fjordllc/bootcamp/pull/2479#issue-597826276 の表のようになっているはずです。

よろしくお願いいたします。🙇‍♂️

2021-03-29 08:00 UTC, gallardo16 commented
>コピーの件に対応できるように修正しました。

「コピーの件」の実装を確認しました。OKだと思います！
色々な注文に対応していただきありがとうございました🙇‍♂️

2021-03-29 14:16 UTC, SeijiNumata commented
@gallardo16 
とんでもないです！
こちらこそレビューしてくださいありがとうございます〜！

@komagata 
レビューお願いいたします！🙇‍♂️

2021-04-03 16:21 UTC, komagata requested changes
conflictの解消をお願いします。

2021-04-12 06:06 UTC, SeijiNumata commented
@komagata 
conflictを解消しました。
ご確認お願いします。

2021-04-14 05:55 UTC, komagata requested changes

2021-04-14 05:55 UTC, komagata commented on app/views/announcements/_announcement.html.slim
> +           -if @announcement.wip || admin_login? || @announcement.user_id == current_user.id
```suggestion
           - if @announcement.wip || admin_login? || @announcement.user_id == current_user.id
```

2021-04-14 05:55 UTC, komagata commented on db/fixtures/announcements.yml
> +
```suggestion
```

2021-04-14 05:55 UTC, komagata commented on test/system/announcements_test.rb
> +  test '一般のユーザーは提出済みのお知らせを編集できない' do
基本的に他の部分もテスト名は英語なので英語に合わせるようにお願いしたいです〜

2021-04-16 09:28 UTC, SeijiNumata commented on test/system/announcements_test.rb
> +  test '一般のユーザーは提出済みのお知らせを編集できない' do
承知いたしました。
テスト名を全て英語に修正いたしました。

2021-04-16 11:44 UTC, SeijiNumata commented
@komagata 
レビューありがとうございます！
修正いたしましたのでご確認お願いいたします。

2021-04-16 19:58 UTC, komagata requested changes

2021-04-16 19:58 UTC, komagata commented on app/views/announcements/_announcement.html.slim
> +           - if @announcement.wip || admin_login? || @announcement.user_id == current_user.id
インデントがおかしいようです〜

2021-04-19 08:22 UTC, SeijiNumata commented on app/views/announcements/_announcement.html.slim
> +           - if @announcement.wip || admin_login? || @announcement.user_id == current_user.id
修正しましたがあまり自信ないです。

24行目が半角スペース一個だったのを２つに修正いたしました。
また他の部分のインデントもおかしかったため修正いたしました。

ご確認よろしくお願いします。

2021-04-19 08:22 UTC, SeijiNumata commented
@komagata 
修正しました、ご確認お願いします

2021-04-19 08:23 UTC, SeijiNumata commented
@komagata 
修正いたしました。ご確認お願いいたします。

https://github.com/fjordllc/bootcamp/pull/2479#discussion_r615640420 
修正に関して自信がない部分をコメントいたしました。

2021-04-20 05:28 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-20 05:28 UTC, merged

2021-04-21 03:33 UTC, SeijiNumata commented
ありがとうございます〜