slackの通知を削除
fjordllc/bootcamp pull request #2488
Opened 2021-03-24 07:33 UTC by Yu-kichi

#2459
のisuueに対応

### 概要

2021-03-25 07:03 UTC, Yu-kichi commented
@hituzi-no-sippo
お疲れ様です〜お手隙の際にレビューをお願い致します！🙏

2021-03-25 08:05 UTC, hituzi-no-sippo requested changes
1点修正したほうが良さそうな部分を見つけましたので、確認お願いします 🙇 
他はOKだと思いますー 👍 

コードではないですが、PRの説明で2点気になりました。

> 削除であるためテストは作成していませんが、参考のため質問を投稿した時のログを一部抜粋しておきます。

この質問の詳細が見れるなら、そのリンクを記載してくれたほうがいいと感じました～

ログの比較を記載していますが、どう違うのか簡単な説明があると、レビュワーの人の負担が軽くなると思います～
多分ですけど、 `[ActiveJob] [NoticeSlackJob] ...` がなくなったんですよね ❔

2021-03-25 09:38 UTC, Yu-kichi commented
@hituzi-no-sippo 
素早いレビューありがとうございます😆

>この質問の詳細が見れるなら、そのリンクを記載してくれたほうがいいと感じました～

ログを表示させるために適当に開発環境で作成しただけなので、リンクを貼っても共有できないかもです。
そのためスクショだけ表示させておきます〜。

> ログの比較を記載していますが、どう違うのか簡単な説明があると、レビュワーの人の負担が軽くなると思います～
多分ですけど、 [ActiveJob] [NoticeSlackJob] ... がなくなったんですよね ❔

すいませんその通りです。🙇‍♂️
どの部分に変更があったか簡単に説明を加えておきました。
そもそもログ部分については紛らわしいのであれば、消しちゃった方がいいかも？？

>ここの @noticeable ですが、削除したこのcreateとupdateのif文でしか利用されていません。
そのため、 @noticeable というインスタンス変数の宣言部分を削除したほうがいいと思います～ 😄

見落としていました、ありがとうございます！！🙏

修正しましたのでお手隙の際に再レビューお願い致します🙏

2021-03-25 09:46 UTC, hituzi-no-sippo approved these changes
OKです～ 😄

2021-03-25 09:46 UTC, hituzi-no-sippo commented on app/controllers/reports_controller.rb
> -    @noticeable = true
👍

2021-03-25 10:09 UTC, Yu-kichi commented
@hituzi-no-sippo

>あぁ、私勘違いしていました。質問というのは、駒形さんなどのメンターに悩んだ部分を聞いて質問したという認識でした。

あ〜Q&Aと書いておけば良かったですね、ごめんなさい〜😅
レビューありがとうございました！😆

@komagata
お疲れ様です〜レビューお願い致します🙏

2021-03-27 06:09 UTC, komagata requested changes

2021-03-27 06:09 UTC, komagata commented on config/initializers/sorcery.rb
> +  # What providers are supported by this app, i.e. [:twitter, :facebook, :github, :linkedin, :xing, :google, :liveid, :salesforce, ] .
ここはslack通知と関係ない部分なので削除しなくて良いと思います。

2021-03-27 11:44 UTC, Yu-kichi commented on config/initializers/sorcery.rb
> +  # What providers are supported by this app, i.e. [:twitter, :facebook, :github, :linkedin, :xing, :google, :liveid, :salesforce, ] .
今後使わないくなるしいいかな〜と先走って消してしまいました。😓
戻しておきます！

2021-03-27 11:44 UTC, Yu-kichi commented
@komagata

修正しましたので再レビューお願い致します〜🙇‍♂️

2021-03-28 04:16 UTC, komagata requested changes
conflictしてる部分の修正をお願いします〜

2021-03-28 14:49 UTC, Yu-kichi commented
@komagata
conflictに気づいていませんでした。。🙇‍♂️
修正しましたので再レビューお願い致します〜🙏

2021-03-30 01:08 UTC, Yu-kichi commented
@komagata 
修正しましたのでお手隙の際に再レビューお願い致します🙏

2021-03-30 02:09 UTC, hituzi-no-sippo reviewed
自分のレビュー終わってますが、コンフリクト前と後比較して気になった箇所があったので、コメントしました。

2021-03-30 02:09 UTC, hituzi-no-sippo commented on app/controllers/reports_controller.rb
> +
これって必要なんですか ❔ 
どこも参照していないように見えます。

2021-03-30 05:25 UTC, Yu-kichi commented on app/controllers/reports_controller.rb
> +
@hituzi-no-sippo
すいません見落としていました🙏
指摘していただき助かりました！ありがとうございます😆

2021-04-03 16:20 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-03 16:20 UTC, merged