メンターにしか見えない情報をワンクリックで隠したい
fjordllc/bootcamp pull request #2495
Opened 2021-03-26 10:12 UTC by harukus

# issue
#2069 に対応。
PR #2175 の続きの作業

# やること

2021-03-31 12:58 UTC, machida commented
@harukus PR先もrebaseしておきましたー

2021-03-31 12:59 UTC, machida commented
@harukus 最後、このPRが完了したら、

git pull --rebase origin add-mentor-memo-to-user-profile 

をやっておいてくださいー

2021-03-31 14:03 UTC, machida commented
@harukus
テストが通ってないですが、
https://github.com/fjordllc/bootcamp/pull/2175
こちらでその対応をしたので、

git pull --rebase origin add-mentor-memo-to-user-profile

これをすると通るようになりますー

2021-04-01 02:15 UTC, harukus commented
@machida 
ありがとうございます！今`git pull --rebase origin add-mentor-memo-to-user-profile`をしました！

2021-04-01 02:21 UTC, machida commented
@harukus ありがとうございますー commit が綺麗になった！
すいません、別のところでテストが通らなかったのですが、一旦このブランチの作業が終わってマージした後に対応したいと思いますー（もし今回の作業にも関わるところだったらお願いするかもです。対応はマージした後に考えましょう）

2021-04-01 02:23 UTC, harukus commented
@machida 
私の作業したところでLintが通りませんでした！ですので原因究明中です😭

2021-04-01 02:31 UTC, machida commented
@harukus これ、ESLint の方の問題かも。

---

@hituzi-no-sippo @komagata 

このエラーの解決策ってわかりますでしょうか？

![image](https://user-images.githubusercontent.com/168265/113235204-9f1f7a00-92dd-11eb-99ad-55d11f43d7d6.png)

```
#!/bin/bash -eo pipefail
bundle exec slim-lint app/views -c config/slim_lint.yml
bin/yarn eslint app/javascript

yarn run v1.22.5
$ /home/circleci/repo/node_modules/.bin/eslint app/javascript

/home/circleci/repo/app/javascript/mentor-mode.js
  8:23  error  Parsing error: Unexpected token .

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

2021-04-01 04:01 UTC, hituzi-no-sippo commented
現状の開発環境のeslintでは [`?.` という算術演算子](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining)を、算術演算子と認識できないのが原因です。
ecmaVersion(JavaScriptのバージョンみたいなもの)を2020に上げればOKです。
ただ、今のeslintはecmaVersionの2020に対応していないので、メジャーバージョンを更新する必要があります。

対応するようにした際の変更点

```diff
diff --git a/.eslintrc b/.eslintrc
index 60521907..1e4a299e 100644
--- a/.eslintrc
+++ b/.eslintrc
@@ -9,5 +9,8 @@
     "FileReader": true,
     "Event": true,
     "FormData": true
+  },
+  "parserOptions": {
+    "ecmaVersion": 2020
   }
 }
diff --git a/package.json b/package.json
index e8722d7f..8d232cbd 100644
--- a/package.json
+++ b/package.json
@@ -8,7 +8,7 @@
     "css-loader": "^5.0.1",
     "escape-html": "^1.0.3",
     "escape-string-regexp": "^2.0.0",
-    "eslint": "^5.7.0",
+    "eslint": "^6.7.2",
     "eslint-config-standard": "^12.0.0",
     "eslint-plugin-import": "^2.14.0",
     "eslint-plugin-node": "^7.0.1",
diff --git a/yarn.lock b/yarn.lock
# 長いので省略
```

ただ、`jsMentorModeClass?.classList.add('is-only-mentor')` だと [no-unused-expressions](https://eslint.org/docs/rules/no-unused-expressions#disallow-unused-expressions-no-unused-expressions) というエラーが発生します。 `?.` は代入などで利用し、式で利用するなとeslint側で怒られます。

---

それで、どうすればいいという話ですが、私なら `?.` を利用しない書き方に変更します。
eslintの更新が面倒& `?.` を利用しなくても読めるコードが書けるのが理由です。

`jsMentorModeClass?.classList.add('is-only-mentor')` の `?.` を使わないようにしたコード

```javascript
if (jsMentorModeClass !== null) {
  jsMentorModeClass.classList.add('is-only-mentor')
}
```

2021-04-01 04:35 UTC, machida commented
@hituzi-no-sippo 
なるほど、わかりやすい説明ありがとうございます！！

- eslint のメジャーバージョンを更新する
- メジャーバージョンを更新した上で lint が通るように js を書き換える

この対応が良さそうですね！
これ、別 Issue を作りますー

----

@harukus 

ということなので、一旦 lint が通らない、はこの PR では無視して作業を進めていただけたらと思います。

2021-04-01 04:46 UTC, harukus commented
@hituzi-no-sippo 
説明ありがとうございます:bow:
@machida 
issue作成ありがとうございます:bow:

>一旦 lint が通らない、はこの PR では無視して

あとはこのPRはCIが通ればレビュー依頼をしようと思っているのですが、CI通っていなくてもレビュー依頼をした方がいいのでしょうか？🤔
それとも#2534がマージされ次第、CIを通してレビュー依頼をする、という形の方がいいのでしょうか:bow:

2021-04-01 04:48 UTC, machida commented
@harukus お、作業は完了してたのですね！では、lint が通るためのPRを急ぎますー

2021-04-01 05:07 UTC, harukus commented
@machida 
ありがとうございます:bow:

2021-04-01 05:49 UTC, machida commented
@harukus ちょっとlint の update の PR のテスト通過に時間がかかっています。
手が止まってしまうので 別の Issue をやりますか。

2021-04-01 05:50 UTC, harukus commented
@machida 
ありがとうございます。お願いいたします🙏

2021-04-01 08:25 UTC, machida commented
@harukus 

おまたせしましたー

まずは、rebase  をして、
git pull --rebase origin add-mentor-memo-to-user-profile

その後で、これを マージしてください
https://github.com/fjordllc/bootcamp/pull/2536

その後、テストを通すために、hitsuji-no-shippo さんのアドバイスの通りに、修正をお願いします。

アドバイス
↓

----

それで、どうすればいいという話ですが、私なら `?.` を利用しない書き方に変更します。
理由としては [no-unused-expressions](https://eslint.org/docs/rules/no-unused-expressions#disallow-unused-expressions-no-unused-expressions)が発生し、 `?.` を利用する場面ではないと思うからです。 [no-unused-expressions](https://eslint.org/docs/rules/no-unused-expressions#disallow-unused-expressions-no-unused-expressions)を理解しきれてないので、間違っている可能性はあります。

`jsMentorModeClass?.classList.add('is-only-mentor')` の `?.` を使わないようにしたコード

```javascript
if (jsMentorModeClass !== null) {
  jsMentorModeClass.classList.add('is-only-mentor')
}
```

2021-04-01 09:42 UTC, harukus commented
@machida 
かしこまりました！説明ありがとうございます:bow:
rebaseした後に#2536 でMergeボタンを押しました！
この後コードをhitsuji-no-shippo さんのアドバイスの通りに変更いたします。

2021-04-01 09:57 UTC, machida commented
@harukus はいー、これでテストが通るはず🙏

2021-04-01 11:39 UTC, harukus commented
@machida 
cb6a682の時点ではGitHub上でマージしたにも関わらず、手元でpullせずforce pushしてしまったため#2536の内容が入っていません（ごめんなさい、、、🙏）
その後に#2536をマージしたのですが、そのCIがうまくいきません、、、。色々落ちているので一つ一つ原因を探してみます。

2021-04-01 18:09 UTC, machida commented
このPRのIssue
https://github.com/fjordllc/bootcamp/issues/2311

<img width="1448" alt="貼り付けた画像_2021_02_10_16_59" src="https://user-images.githubusercontent.com/168265/107481390-6e667280-6bc1-11eb-895d-003111d00df8.png">

- ここが on になったら、bodyタグ に `is-mentor-mode` という class が追加される
- off になったら、bodyタグ に付与された  `is-mentor-mode` という class は削除される
- ページを遷移しても  `is-mentor-mode` という class の有り無し、on off の状態は維持される
- on off の状態は ローカルストレージで保存

2021-04-02 08:33 UTC, harukus commented
@machida 
`app/views/application/_header.html.slim`ファイルの13行目を
`- if current_user.admin?`となっていたのですが`- if current_user.mentor?`に変更しています:bow:
理由：メンターさん(yamada)なのにメンターモードが表示されなかったため。

2021-04-03 13:29 UTC, harukus commented
@hisaotoriyama 
お時間があればお手隙でレビューをお願いいたします:bow:
もし時間を取ることが難しい場合は気軽にお伝えください◎

2021-04-04 00:28 UTC, hisaotoriyama commented
@harukus 
おはようございます。すごく関心があるテーマなので時間をいただき自分も勉強しながらでよろしければぜひレビューさせてください。

2021-04-04 06:40 UTC, hisaotoriyama reviewed
@harukus 
レビューというか自分の学習・理解のための質問になってしまったかもしれませんが、何卒よろしくお願いします（なかなか進んでいないのですがちょうどhttps://github.com/fjordllc/bootcamp/issues/2027　をやる必要があっためすごい勉強になります）

2021-04-04 06:40 UTC, hisaotoriyama commented on app/javascript/user_mentor_memo.vue
> +.is-memo.is-only-mentor
変更箇所としてはこの行に、.is-only-mentorをつけたのが唯一の変更と理解します。正しいですか？
（これをつけておいて上述app/assets/stylesheets/helpers/_state.sassで条件分けをしているものと理解しています。）

2021-04-04 06:40 UTC, hisaotoriyama commented on app/javascript/mentor-mode.js
> +    if (jsMentorModeClass !== null) {
このif条件設定が必要な理由も教えてください。

2021-04-04 07:18 UTC, harukus commented on app/javascript/mentor-mode.js
> +  if (!checkboxMentorMode) return
こちらはメンターモードが使用できる人のみに現れるクラスとなっています!
(`app/views/application/_header.html.slim`の13行目以降より)
そのため現役受講生や卒業生などは表示されません。
```
if (checkboxMentorMode){...
```
と書けるのですがネストが深くなる且つ`checkboxMentorMode`を持たない時はすぐ抜けられるように上記のように書いてあります！

2021-04-04 07:21 UTC, harukus commented on app/javascript/user_mentor_memo.vue
> +      credentials: "same-origin",
こちらのファイルのdiffをしっかりと確認せずにcommitしてしまいました。
そしてこちらのファイルは主にmachidaさんが作ってくださいましたので
machidaさんに聞いてもよろしいでしょうか、、？
@machida 
よろしくお願いいたします:bow:

2021-04-04 07:22 UTC, harukus commented on app/assets/stylesheets/helpers/_state.sass
> +.is-only-mentor
まさにその通りです！！！

2021-04-04 07:22 UTC, harukus commented on app/javascript/user_mentor_memo.vue
> +.is-memo.is-only-mentor
はい、その通りです！！！

2021-04-04 07:48 UTC, hisaotoriyama commented on app/javascript/mentor-mode.js
> +  if (!checkboxMentorMode) return
御意です。明快ですね。

2021-04-04 08:04 UTC, harukus reviewed
コメントの方法を色々間違えてしまってたくさん通知がいってしまったかもしれません。
確認お願いいたします！

2021-04-04 08:04 UTC, harukus commented on app/javascript/mentor-mode.js
> +      localStorage.removeItem('mentor-mode')
`removeItem()`メソッドはキー名を渡すため、キー名を中に書いています。ということでよろしいでしょうか？？🤔
参考：[Storage\.removeItem\(\) \- Web API \| MDN](https://developer.mozilla.org/ja/docs/Web/API/Storage/removeItem)

また直感的でわかりにくいかと思いますがメンターモードがonの時はlocalstorageには何も入っていなく、offの時に[mentor-mode : off]とlocalstorageに入るようになっています。
理由としましては、2つあります。
1つ目はこちらのPR #2152 を参考にしたため、似たようなコードになっています。
2つ目はlocalstorageに[mentor-mode: on]と[mentor-mode: off]と切り替えると
６行目のコードが
```
if (localStorage.getItem('mentor-mode') === 'off') {...
または
if (localStorage.getItem('mentor-mode') === 'on') {
```
に書き換えたり、
```
localStorage.setItem('mentor-mode', 'on')
```
というコードがが増えるため、です。


では、なぜ、6行目の一番最初の条件式が`localStorage.getItem('mentor-mode')`(つまりメンターモードがオフの状態)かを説明いたします。

まず、逆の状態を考えます。localstorageが[ mentor-mode : on ]の時、メンターモードがオンの状態であるとします。
一番最初にログインする時はみなさんlocalstorageには何も入っていない状態です。そしてメンターモードのチェックはデフォルトでONになるようになっています。
(`app/views/application/_header.html.slim`の21行目より)
そうすると下の画像のようなことが起こります。
[![Image from Gyazo](https://i.gyazo.com/4c3e20e345a4e6b59f65d08f192ff4ad.gif)](https://gyazo.com/4c3e20e345a4e6b59f65d08f192ff4ad)
（localstorageに何も入っていないのにメンターモードがONになっている）
こういう経緯より一番最初の条件式が`localStorage.getItem('mentor-mode')`となっています。

ややこしい且つ色々余計な説明をしてしまったかもしれませんが何か不明点や疑問点があればおっしゃってください！

2021-04-04 09:41 UTC, hisaotoriyama reviewed
@harukus 
すごく勉強させていただいております。今一度お付き合いください！

2021-04-04 09:41 UTC, hisaotoriyama commented on app/javascript/mentor-mode.js
> +      localStorage.removeItem('mentor-mode')
> (前段）
> というコードがが増えるため、です。

についてはすごくよくわかりました。本当に感謝です。😄

> では、なぜ、6行目の一番最初の条件式がlocalStorage.getItem('mentor-mode')(つまりメンターモードがオフの状態)かを説明いたします。

についてきちんと理解したいので教えてください。整理がつかずすいません🙇‍♂️

> 一番最初にログインする時はみなさんlocalstorageには何も入っていない状態です。

なのでlocalStorage.getItem('mentor-mode')は何も入っていなかったのでfalseなので、
```
else {
    checkboxMentorMode.checked = true
    jsMentorModeClass.classList.add('is-mentor-mode')
  }
```
がまず適用される。そこでチェックを入れると
```
 checkboxMentorMode.addEventListener('click', () => {
    if (checkboxMentorMode.checked) {
      localStorage.removeItem('mentor-mode')
      jsMentorModeClass.classList.add('is-mentor-mode')
    } else {
      localStorage.setItem('mentor-mode', 'off')
      jsMentorModeClass.classList.remove('is-mentor-mode')
    }
  })
```
ここの
```
else {
      localStorage.setItem('mentor-mode', 'off')
      jsMentorModeClass.classList.remove('is-mentor-mode')
    }
```
が適用される、という流れは正しいでしょうか。（一度ここで切ります）

2021-04-04 10:23 UTC, harukus reviewed
ややこしいコードにしてしまって非常に申し訳ないと思っています😭
直感的なコードを思いついたので書いてみました、、、！
ぜひご意見くださると嬉しいです！
そして分かりづらいところがあれば何でも言ってください！
ではよろしくお願いいたします。

2021-04-04 10:23 UTC, harukus commented on app/javascript/mentor-mode.js
> +      localStorage.removeItem('mentor-mode')
私も頭のなかがこんがらがってきました、、、。

>なのでlocalStorage.getItem('mentor-mode')は何も入っていなかったのでfalseなので、
>else {
>    checkboxMentorMode.checked = true
>    jsMentorModeClass.classList.add('is-mentor-mode')
>  }
>がまず適用される。

はい！あっています！
そして最後までの流れもあっています！
つまり１度メンターモードの切り替えをすればlocalstorageは期待に沿った動きをする、ということですね。


そして以下のような書き方をすればlocalstorargeには[mentor-mode : on]のような設定で最初から期待通りの実装ができることに気がつきました🤔
```
document.addEventListener('DOMContentLoaded', () => {
  const localStorage = window.localStorage
  const checkboxMentorMode = document.querySelector('.js-mentor-mode__trigger')
  const jsMentorModeClass = document.body
  if (!checkboxMentorMode) return
  if (localStorage.getItem('mentor-mode')) {
    checkboxMentorMode.checked = true
    jsMentorModeClass.classList.add('is-mentor-mode')
  } else {
    checkboxMentorMode.checked = false
    jsMentorModeClass.classList.remove('is-mentor-mode')
  }
  checkboxMentorMode.addEventListener('click', () => {
    if (checkboxMentorMode.checked) {
      localStorage.setItem('mentor-mode', 'on')
      jsMentorModeClass.classList.add('is-mentor-mode')
    } else {
      localStorage.removeItem('mentor-mode')
      jsMentorModeClass.classList.remove('is-mentor-mode')
    }
  })
})
```
このような書き方の方が直感的ですかね🤔どう思いますか？？

2021-04-04 10:23 UTC, harukus commented on app/javascript/mentor-mode.js
> +    if (jsMentorModeClass !== null) {
私もよくあります！難しいですね😓

2021-04-04 10:23 UTC, harukus commented on app/javascript/mentor-mode.js
> +  if (!checkboxMentorMode) return
はい！そういうことだと思います！
なので、もし他のslimファイル等に`.js-mentor-mode__trigger`クラスがあればapp/javascript/mentor-mode.jsのeventListnerが反応する、ということになります、、！

2021-04-04 11:51 UTC, hisaotoriyama commented on app/javascript/mentor-mode.js
> +  if (!checkboxMentorMode) return
なので、、、という更なる具体例ご提示、感謝申し上げます。😄

2021-04-04 12:06 UTC, hisaotoriyama reviewed
@harukus 
早速コメントありがとうございます。引き続きよろしくお願いいたします。

2021-04-04 12:06 UTC, hisaotoriyama commented on app/javascript/mentor-mode.js
> +      localStorage.removeItem('mentor-mode')
これすごくいいかもしれないですう。つまりmentor-modeが0n：チェックマーク、add('is-mentor-mode')の組み合わせですものね。すごくいい整理ありがとうございます。変更されたら僕も再度確認してみます。👍😃

2021-04-04 22:27 UTC, hisaotoriyama commented
@harukus おはようございます。稼働の確認してみましたが問題ないです。修正内容は良いと思いました！今町田さんに教えていただきたい点はありますがそれを除いて問題ないと思いますが、どうしましょうかね。

2021-04-05 01:32 UTC, harukus commented
@hisaotoriyama 
おはようございます。
今修正したものだとメンターさんに関するテストでたくさん失敗してしまうことに気づきました。

今修正したものだとlocalstorageに`mentor-mode`がなければメンターモードのチェックをオフにする、という仕様になっています。
(GIF参照)
[![Image from Gyazo](https://i.gyazo.com/97937987d932e60d15f6ea069eede049.gif)](https://gyazo.com/97937987d932e60d15f6ea069eede049)

このようにすると、メンターモードがオフのままテストをすることになるのでほとんどのテストに失敗してしまいます。。。
ですので一番最初のコードに戻そうと思います。。

町田さんへの質問は質問タイムで聞けたら聞いてみます💪

2021-04-05 07:10 UTC, harukus commented on app/javascript/user_mentor_memo.vue
> +      credentials: "same-origin",
@hisaotoriyama 
こちらよくよく見てみるとdiffとの差は`'`か`"`かどうかだけだと思うのですが、そういうことではなく、なぜここにあるか、ということが知りたいということでしょうか🤔
昨日質問の意図をしっかり理解せずすみませんでした:bow:

2021-04-05 08:56 UTC, hisaotoriyama commented on app/javascript/user_mentor_memo.vue
> +      credentials: "same-origin",
@harukus 
僕も今改めてみましたが勘違いしていたようです。
>diffとの差は`'`か`"`かどうかだけ

でした。お騒がせしてしまいすいません。🙇‍♂️

2021-04-05 08:57 UTC, hisaotoriyama commented on app/javascript/mentor-mode.js
> +    if (jsMentorModeClass !== null) {
🙇‍♂️

2021-04-05 08:58 UTC, hisaotoriyama reviewed
@harukus 
かしこまりました。元どおりにされたこと了解しました。本当に長らくありがとうございました。
レビューは終わりとさせてください。

2021-04-06 00:09 UTC, harukus commented
@hisaotoriyama 
こちらこそコードレビューありがとうございました！
hisaoさんの聞き方は無駄がなくスマートかつ分かりやすいので私も学べたことがありました👍
またよろしくお願いいたします:bow:

2021-04-06 00:11 UTC, harukus commented
@komagata 
hisaotoriyamaさんにレビューしていただき完了しました。
レビューお願いいたします。

2021-04-07 05:08 UTC, komagata requested changes

2021-04-07 05:08 UTC, komagata commented on app/javascript/user_mentor_memo.vue
> +.is-memo.is-only-mentor
上の行とインデントレベルが同じになっているので一段下げた方がいいかもです〜

2021-04-07 05:08 UTC, komagata commented on app/javascript/user_mentor_memo.vue
> +    TextareaInitializer.initialize("#js-user-mentor-memo");
これらたくさんシングルクォートが変えられた部分がありますが、lintを通すためとかでしょうか？

2021-04-07 05:08 UTC, komagata commented on test/system/user/memos_test.rb
> +    assert page.has_content? 'メンター向けユーザーメモ'
`assert page.has_content?`

これと同じようなことができるassertionがあった気がします〜

2021-04-07 06:16 UTC, harukus commented on app/javascript/user_mentor_memo.vue
> +    TextareaInitializer.initialize("#js-user-mentor-memo");
いえ、VSCodeでの自動整形されてしまいました。
修正いたしました！

2021-04-07 06:44 UTC, harukus commented on test/system/user/memos_test.rb
> +    assert page.has_content? 'メンター向けユーザーメモ'
`page.assert_text`を使用しました〜！

2021-04-07 08:04 UTC, harukus commented
@komagata 
改めてレビューお願いいたします:bow:

先日mainをrebaseしたことに今日気づき、先ほど改めて`add-mentor-memo-to-user-profile`をrebaseしました:bow:

2021-04-07 11:40 UTC, komagata requested changes
conflictの修正もお願いします〜

2021-04-07 11:40 UTC, komagata commented on .eslintrc
> +    "ecmaVersion": 2020
ここはなぜ追加されているんでしょう？

2021-04-08 05:15 UTC, harukus commented on .eslintrc
> +    "ecmaVersion": 2020
`.eslintrc`ファイルが追加されていたことを確認できていませんでした😰
なのでなぜ追加されているかはわかりません、、、:bow:ごめんなさい:bow:

2021-04-08 05:15 UTC, harukus commented
@komagata 
コンフリクト解消できていますでしょうか:bow:
確認お願いいたします:bow:

2021-04-08 05:52 UTC, ima1zumi commented on .eslintrc
> +    "ecmaVersion": 2020
この流れですかね？ https://github.com/fjordllc/bootcamp/pull/2495#issuecomment-811620879

2021-04-08 05:58 UTC, harukus commented on .eslintrc
> +    "ecmaVersion": 2020
@ima1zumi 
そこですね、、。:bow:ごめんなさい、ありがとうございます:bow:

2021-04-09 04:00 UTC, komagata requested changes

2021-04-09 04:00 UTC, komagata commented on .eslintrc
> +    "ecmaVersion": 2020
@harukus 不要であれば削除しちゃってください〜
Files changedには意図したものだけが差分として表示される状態にするようにお願いします〜

2021-04-09 04:04 UTC, machida commented on .eslintrc
> +    "ecmaVersion": 2020
@harukus @komagata 
今回それを入れた経緯は、今回の機能追加にそのecma versionを指定しないとlintで引っかかるjsの書き方が含まれているのが理由です。もし、jsの書き換えがあり、

- そのecma version指定がなくてもlintで引っかからないようであれば削除
- そのecma version指定がないとlintが通らないのであれば追加

でお願いしたいです。

2021-04-09 04:07 UTC, machida commented on .eslintrc
> +    "ecmaVersion": 2020
@harukus 
まぁ、要するに、その行を削除してもテストが通るなら削除しちゃってください、ということですー

2021-04-10 06:54 UTC, harukus commented
@komagata 
ecma version指定がなくてもlintで引っかからなかったので削除いたしました。確認お願いいたします:bow:

2021-04-14 05:37 UTC, komagata requested changes

2021-04-14 05:37 UTC, komagata commented on test/system/admin/mentor_mode_test.rb
> +  test 'student don`t show mentor-user-memo' do
これ don t の間にバッククォートが入っちゃてるようです〜

2021-04-14 05:37 UTC, komagata commented on test/system/user/memos_test.rb
> +    page.assert_text('メンター向けユーザーメモ')
```suggestion
    assert_text 'メンター向けユーザーメモ'
```

2021-04-14 08:08 UTC, harukus commented on test/system/admin/mentor_mode_test.rb
> +  test 'student don`t show mentor-user-memo' do
修正しました！

2021-04-15 01:46 UTC, komagata requested changes

2021-04-15 01:46 UTC, komagata commented on test/system/admin/mentor_mode_test.rb
> +  test 'student do not show mentor-user-memo' do
文字列中にシングルクォートを使いたい場合はエスケープするか、文字列を囲う文字を`"`にすれば大丈夫です〜

2021-04-15 01:46 UTC, komagata commented on package.json
> +    "eslint": "^6.7.2",
ここが変わっているのは何故でしょう？（意図していなかったら変えないようにしてみてください）

2021-04-15 05:48 UTC, harukus commented on test/system/admin/mentor_mode_test.rb
> +  test 'student do not show mentor-user-memo' do
ありがとうございます:bow:修正しました。

2021-04-15 13:23 UTC, harukus commented on test/system/user/memos_test.rb
> +    page.assert_text('メンター向けユーザーメモ')
修正しました:bow:

2021-04-15 13:24 UTC, harukus commented on package.json
> +    "eslint": "^6.7.2",
修正しました:bow:

2021-04-15 13:24 UTC, harukus commented
@komagata 
修正いたしました:bow:確認お願いいたします:bow:

2021-04-16 19:51 UTC, komagata requested changes
変更ファイルがCSS以外にも大量にありますが全部意図している変更でしょうか？

もしかしたら最新のmainに追従すると変わるかもしれません。

2021-04-20 05:33 UTC, komagata commented
<img width="289" alt="スクリーンショット 2021-04-20 14 32 56" src="https://user-images.githubusercontent.com/16577/115342486-53c60080-a1e5-11eb-9a08-86b90623c604.png">

コミットメッセージの先頭に全角の空白が入っちゃってるかもです〜

2021-04-20 05:35 UTC, harukus commented
@komagata 
本当ですね！修正します。

2021-04-22 00:30 UTC, harukus commented
@komagata 
改めて確認お願いいたします。

2021-04-26 06:51 UTC, komagata requested changes

2021-04-26 06:51 UTC, komagata commented on app/javascript/mentor-mode.js
> +  const checkboxMentorMode = document.querySelector('.js-mentor-mode__trigger')
不必要に変数名が長いので全体が読みづらくなっているように思います。

例えば、このスクリプトの中だけだったらこの変数は`checkbox`とかでもいいように思います。
`jsMentorModeClass`もちょっとそぐわない？ような気がするので`body`とかの方がわかりやすいように思います。

2021-04-28 00:40 UTC, harukus commented on app/javascript/mentor-mode.js
> +  const checkboxMentorMode = document.querySelector('.js-mentor-mode__trigger')
そうですね:eyes:
変更しました！

2021-04-28 10:32 UTC, komagata reviewed
すごく些細な点についてコメントいたしました〜

2021-04-28 10:32 UTC, komagata commented on app/javascript/mentor-mode.js
> +  if (!checkbox) return
ガード節の後は1行開けるとガード節であることを強調できるのでいいかもです。

2021-04-29 04:09 UTC, harukus commented on app/javascript/mentor-mode.js
> +  if (!checkbox) return
なるほどです！かしこまりました！
修正しました！

2021-05-20 02:18 UTC, machida commented
@harukus 
こちら、rebase しておきましたー。

@komagata @harukus 
一旦、komagataさんのレビューが通ったら、
https://github.com/fjordllc/bootcamp/pull/2175 
こちらのブランチにマージして確認をしたいのですがいかがでしょうか？

2021-05-21 05:11 UTC, komagata commented
@machida 

> 一旦、komagataさんのレビューが通ったら、
> #2175
> こちらのブランチにマージして確認をしたいのですがいかがでしょうか？

いいと思います〜

2021-05-21 05:12 UTC, machida commented
@komagata ありがとうございます！では、approveになったらマージして、次にマージ先のブランチで確認作業を行います。

@harukus マージ後で不具合が見つかったら、次はマージ先のブランチで作業を続けましょう。

2021-05-21 05:26 UTC, komagata commented
@machida @harukus これって今誰にボールが渡ってる状態ですかね？
僕のレビュー待ちかな？

2021-05-21 05:26 UTC, machida commented
@komagata レビューお願いします🙏

2021-05-21 05:31 UTC, komagata requested changes

2021-05-21 05:31 UTC, komagata commented on app/javascript/user-secret-attributes.vue
> +  v-if='currentUser.mentor && user.student_or_trainee'
これメンターか管理者であることだけチェックすればいいような気がするんですが、なんで`student_or_trainee`であることをチェックしてるんでしょ？

2021-05-21 05:32 UTC, komagata approved these changes
いくつかきになる点ありますが、それは`add-mentor-memo-to-user-profile`の方の部分なのでこちらはOKです〜

2021-05-21 05:33 UTC, komagata commented
@machida @harukus マージしてしまします〜

2021-05-21 05:33 UTC, merged

2021-05-21 05:33 UTC, machida commented
ありがとうございます！

2021-05-21 09:19 UTC, harukus commented
@machida @komagata 
ありがとうございます🙇‍♂️