提出物のページでローディング中を表示させる
fjordllc/bootcamp pull request #2496
Opened 2021-03-26 13:36 UTC by Yu-kichi

#2465
のisuueに対応

### 概要

2021-04-01 09:14 UTC, Yu-kichi commented
@alto-I
お疲れ様です！
お手隙の際にレビューをお願い致します〜。🙏

2021-04-07 14:13 UTC, alto-I commented
@Yu-kichi 
すいません自分の通知の設定ミスで見逃していました😱
なるべく早くレビュー取り掛かりたいと思います！

2021-04-07 14:34 UTC, Yu-kichi commented
@alto-I
いえいえ特に急いでないのでゆっくりで大丈夫ですよ〜👍😊

2021-04-10 23:33 UTC, alto-I approved these changes
@Yu-kichi 
レビュー遅くなってすいません！問題ないと思います！💪

2021-04-10 23:33 UTC, alto-I commented on app/javascript/comments.vue
> +    .comments(v-if="loaded === false && commentableType === 'Product'")
ちゃんと日報のコメントには「ロード中」がでなかったので、実装どおりになっていていいと思いました！😄

2021-04-11 07:00 UTC, Yu-kichi commented
@alto-I
レビューありがとうございました〜！😊

@komagata 
お手隙の際にレビューお願いいたします。🙏

2021-04-14 05:44 UTC, komagata approved these changes
実装はOKです〜

2021-04-14 05:45 UTC, komagata commented
@machida これってBootcampアプリ全体として、ロード中にするか、プレースフォルダを表示するかどっちがいいですかね〜

2021-05-12 12:51 UTC, machida commented
@komagata placeholder をやってみたいですねー。ちょっと時間がかかるかもですが、このPRで placeholder の仕組みを sass で実装してみたいと思います。

2021-05-13 10:58 UTC, komagata commented
@machida ありがとうございます！！

2021-05-18 03:03 UTC, machida commented
@Yu-kichi @komagata placeholder のデザインを入れましたー

2021-05-18 03:06 UTC, machida commented on app/javascript/comments.vue
> +  .thread-comment
@Yu-kichi (cc @komagata )


リファクタのお願いがあります。

同じ内容で .thread-comment を3回繰り返しているので、partialにして、それを3回繰り返す、という形にしたいです。

partialにしたい理由は3回繰り返しているの他に、他のページでもこのパーツを使いたい（コメント読み込みのplaceholderとして）、という理由もあります。なので、それを考慮した名前、ファイルの場所にしていただきたいです。

2021-05-18 03:06 UTC, machida requested changes
リファクタをお願いします🙏

2021-05-18 07:16 UTC, Yu-kichi commented
@komagata @machida
こちら修正しましたのでお手隙の際に確認お願いいたします。🙏

2021-05-19 02:24 UTC, machida approved these changes
@Yu-kichi ご対応ありがとうございますー🙏

2021-05-19 09:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-19 09:52 UTC, komagata commented
@machida こちらってもうマージしちゃって大丈夫ですかね？

2021-05-19 13:27 UTC, merged