ユーザー個別ページに自分が投稿した質問一覧を表示
fjordllc/bootcamp pull request #2501
Opened 2021-03-27 07:00 UTC by hisaotoriyama

# Issue
## #1955
# Detail
## ユーザー個別ページに自分が投稿した質問一覧を表示するもの。自分がした質問を見返したいと思った時に容易に探すことを狙うもの。

![スクリーンショット 2021-03-27 15 58 18](https://user-images.githubusercontent.com/39847087/112712867-7716cc00-8f15-11eb-9ad8-98696e7d3973.png)

2021-03-28 04:39 UTC, hisaotoriyama commented
@SeijiNumata 
お疲れ様です。もしもお時間がおありでしたらレビューをお願いできませんでしょうか。
特に急ぎませんので無理なくご検討ください。

2021-03-28 13:27 UTC, SeijiNumata commented
@hisaotoriyama 
お疲れ様です。

承知いたしました！
１週間ほどで見れると思いますので、レビューいたしますね！

よろしくお願いします🙇‍♂️

2021-03-28 22:44 UTC, hisaotoriyama commented
@SeijiNumata 
こちらも平日はゆっくり稼働できないので1週間でありがたいです。是非よろしくお願いします。

2021-03-29 14:27 UTC, SeijiNumata reviewed
@hisaotoriyama
時間ができたので確認しました！

一件だけテストについて小さな指摘と質問をしたので、その部分以外は全て良いと思います。🙆‍♂️
ご確認よろしくお願いします。🙇‍♂️

2021-03-30 09:00 UTC, hisaotoriyama commented on test/fixtures/questions.yml
> +  title: 質問のタブわからない
@SeijiNumata 
ご多忙のところレビューを早速いただきありがとうございます。
日本語変でしたね。質問のタブの作り方に変更しました
またご質問の点は、自分でテストデータを作ってテストしてみたいと思ったものです。余計なことをしていたらすいません。

2021-03-30 09:07 UTC, SeijiNumata commented on test/fixtures/questions.yml
> +  title: 質問のタブわからない
@hisaotoriyama 
修正ありがとうございます！😄

> またご質問の点は、自分でテストデータを作ってテストしてみたいと思ったものです。余計なことをしていたらすいません。

なるほどです〜。良いと思います！
LGTMなので駒形さんにレビュー依頼お願いします！

2021-03-30 09:53 UTC, hisaotoriyama commented on test/fixtures/questions.yml
> +  title: 質問のタブわからない
@SeijiNumata 
ご確認いただきありがとうございます。😃

@komagata 
お手隙の時で結構ですのでレビューお願いいたします。🙏

2021-04-03 16:22 UTC, komagata commented
@hisaotoriyama レビュー依頼する前にDraftのPRをReady for reviewの状態にしてください〜（やり方も調べてみてください〜）

2021-04-03 22:43 UTC, hisaotoriyama commented
@komagata 
review requestさせていただきました。よろしくお願いいたします

2021-04-06 07:01 UTC, komagata requested changes
<img width="372" alt="スクリーンショット 2021-04-06 16 00 02" src="https://user-images.githubusercontent.com/16577/113671319-29f2e100-96f1-11eb-9169-18e0dbe8cdfd.png">

コミットメッセージが適切でないかもです。下記を参考に修正してみてください〜

[俺の考えるコミットメッセージの書き方 \- komagataのブログ](https://docs.komagata.org/5744)

2021-04-08 09:57 UTC, hisaotoriyama commented
@komagata 
拝承しました。ご指導ありがとうございます。対応いたします。

2021-04-09 13:37 UTC, hisaotoriyama commented
@komagata 
コミットメントメッセージが全て残るので大事であることわかりました。失礼しました。
Local環境で
自分のプロフィールに質問タブ作る　→　不変（そのまま）
テスト後　　　　　　　　　　　　　→　CIで判明した不要スペース削除
テスト導入　　　　　　　　　　　　→　自動テストのプログラミング追加
Rubocop修正　　　　　　　　　　　→　自動テストのプログラミングの不要スペース削除
テストケースのタイトルの変更　　　→　自動テストquestion9の日本語修正
と変更したのですが、origin のfeature/tab_of_questionsに反映させたく、
git push --force origin feature/tab_of_questions
で良いことを念のために確認させてください。

2021-04-14 05:20 UTC, komagata commented
@hisaotoriyama 自由に過去のコミットを修正したあとpushで大丈夫です。

しかし`--force`ではなく`--force-with-lease`を常に使うようにしてください〜

[git push \-f をやめて \-\-force\-with\-lease を使おう \- Qiita](https://qiita.com/wMETAw/items/5f47dcc7cf57af8e449f)

2021-04-15 12:40 UTC, hisaotoriyama commented
@komagata 
ご指導ありがとうございます。これに基づきコミットメッセージ変更しました。
ご確認よろしくお願いいたします。

2021-04-16 19:48 UTC, komagata requested changes

2021-04-16 19:48 UTC, komagata commented on test/fixtures/questions.yml
> +  description: タブをテストする①
気にしすぎかもですが①などは機種依存文字なのでできれば単に1とかにしたいです〜

2021-04-16 19:48 UTC, komagata commented on app/controllers/users/questions_controller.rb
> +  def user
このメソッドはどこから呼ばれていますか？

2021-04-18 01:21 UTC, hisaotoriyama reviewed
＠komagata
体調良くなられていますか？
ご確認よろしくお願いします。

2021-04-18 01:21 UTC, hisaotoriyama commented on app/controllers/users/questions_controller.rb
> +  def user
16行目user.questions.order(created_at: :desc)のuserと理解しています。
@userが存在していれば@userがメソッドの戻り値として返され、@userが存在していなければUser.find(params[:user_id])が戻り値として返されると思っています。
他のを見て参考としてこれを入れました。

2021-04-18 01:22 UTC, hisaotoriyama commented on test/fixtures/questions.yml
> +  description: タブをテストする①
おっしゃる通りです。

2021-04-19 08:35 UTC, komagata requested changes

2021-04-19 08:35 UTC, komagata commented on app/controllers/users/questions_controller.rb
> +  def user
全体が不要に複雑になっているかもです。
例えば`index`しかactionが必要ないのであれば下記みたいな感じでもいいかもです。

```ruby
class Users::QuestionsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @questions = @user.questions.order(created_at: :desc)
  end
end
```

2021-04-19 08:35 UTC, komagata commented on app/javascript/reports_with_no_practice_time.js
> +document.addEventListener('DOMContentLoaded', () => {
これって何に使っているコードでしょう？

2021-04-26 14:15 UTC, hisaotoriyama reviewed
@komagata 
遅くなりました。２点修正いたしました。

2021-04-26 20:07 UTC, merged