担当になるボタンを表示するページでサイズを選択できるようにしたい #2504
fjordllc/bootcamp pull request #2510
Opened 2021-03-29 16:17 UTC by SeijiNumata

https://github.com/fjordllc/bootcamp/issues/2483
に対応

## 概要
メンターでログインしたとき、

提出物一覧、

<img width="851" alt="貼り付けた画像_2021_03_24_12_29" src="https://user-images.githubusercontent.com/168265/112250355-90f9aa00-8c9c-11eb-9459-7961b60057c6.png">

提出物個別、

<img width="896" alt="貼り付けた画像_2021_03_24_12_30" src="https://user-images.githubusercontent.com/168265/112250461-c1d9df00-8c9c-11eb-831a-b5a2538e9d23.png">

両方に担当になるボタンがありますが、機能は同じですが、サイズが違います。

現在、提出物個別のときに、サイズをCSSで無理やり大きくしているが、この対応をやめる。

-----

提出物一覧のときのボタンは、`is-sm` というclassが付いている。

<img width="677" alt="貼り付けた画像_2021_03_24_12_33" src="https://user-images.githubusercontent.com/168265/112250680-2b59ed80-8c9d-11eb-8929-1f72e9b132de.png">

提出物個別のときも、`is-sm` というclassが付いていますが、この `is-sm` を `is-md` に変更すると、サイズをCSSで無理やり大きくする必要がなくなります。

<img width="609" alt="貼り付けた画像_2021_03_24_12_34" src="https://user-images.githubusercontent.com/168265/112250786-5e03e600-8c9d-11eb-99af-f44da654d0fb.png">

----

なので、

- 提出物一覧のときのボタンは、`is-sm` というclassが付く
- 提出物個別のときのボタンは、`is-md` というclassが付く

ようにする。

***

## 実装方針
「担当する」ボタンが表示されるまでの流れ
提出物一覧は
views/product/index.html.slim→js-products→products.vue→product.vue→product-checker.vue
提出物個別は
views/product/show.html.slim→js-check→check.vue→product-checker
という流れである。

よって、check.vueで受け渡して、product.vueでは受け渡さないものをproduct-checkerに渡して、その真偽値でクラスを変更する。
この場合`checkableType`が当てはまるため、それを利用します。
`checkableType`をcheck.vueからproduct-checkerに渡します。
`checkableType`が存在する時は個別ページなので`is-md`を適用し、存在しない時は一覧ページなので`is-sm`を適用します。

2021-03-29 16:49 UTC, SeijiNumata commented
@Yu-kichi 
お疲れ様です。
もしもお時間がおありでしたらレビューをお願いできませんでしょうか。
特に急ぎませんので無理なくご検討ください。🙇‍♂️

2021-03-30 07:02 UTC, Yu-kichi approved these changes
レビュー依頼ありがとうございます！😆
実装方針の説明がわかりやすくて参考になりました！！

cssのクラスに画像のようにis-mdがついてることも確認できました！

<img width="1362" alt="OS_X_Mountain_Lionをクリーンインストールするの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/64201542/112946117-1cc57780-9170-11eb-8e3b-9c42accaf44a.png">

全体的にわかりやすくてよかったです😊

2021-03-30 09:24 UTC, SeijiNumata commented on app/javascript/product_checker.vue
> +    button(v-if="!checkerId || checkerId == currentUserId" :class="['a-button', 'is-block', id ? 'is-warning' : 'is-secondary' ,checkableType? 'is-md' : 'is-sm']" @click="check")
本当ですね、ありがとうございます！
修正いたしました。

2021-03-30 09:28 UTC, SeijiNumata commented
@Yu-kichi 
レビューしていただきましてありがとうございます！！
すみません、説明欄に実装結果のスクショを貼っておくべきでした💦

インデントの件を修正したので、駒形さんにレビュー依頼してみます！

@komagata 
こちらレビューをお願いいたします。🙇‍♂️

2021-04-03 16:27 UTC, komagata requested changes

2021-04-03 16:27 UTC, komagata commented on app/javascript/check.vue
> +        product-checker(v-show="checkableType === 'Product' && checkId === null", :checkerId="checkerId", :checkerName="checkerName", :currentUserId="currentUserId", :productId="checkableId",:checkab
```suggestion
        product-checker(v-show="checkableType === 'Product' && checkId === null", :checkerId="checkerId", :checkerName="checkerName", :currentUserId="currentUserId", :productId="checkableId", :checkableType="checkableType")
```

2021-04-03 16:27 UTC, komagata commented on app/javascript/product_checker.vue
> +    button(v-if="!checkerId || checkerId == currentUserId" :class="['a-button', 'is-block', id ? 'is-warning' : 'is-secondary' ,checkableType? 'is-md' : 'is-sm']" @click="check")
```suggestion
    button(v-if="!checkerId || checkerId == currentUserId" :class="['a-button', 'is-block', id ? 'is-warning' : 'is-secondary', checkableType? 'is-md' : 'is-sm']" @click="check")
```

2021-04-03 16:27 UTC, komagata commented on app/javascript/product_checker.vue
> +  props: ['checkerId', 'checkerName', 'currentUserId', 'productId','checkableType'],
```suggestion
  props: ['checkerId', 'checkerName', 'currentUserId', 'productId', 'checkableType'],
```

2021-04-13 09:16 UTC, SeijiNumata commented
@komagata 
レビューありがとうございます！
修正いたしましたのでご確認お願いします🙇‍♂️

2021-04-14 05:58 UTC, komagata commented
@SeijiNumata File ChangedのページにこのIssueと関係のない差分があるようなので、確認して修正お願いします〜

2021-04-16 11:45 UTC, SeijiNumata commented
@komagata 
レビューありがとうございます！
関係のないファイルを削除し、修正いたしましたのでご確認お願いいたします。

2021-04-16 19:59 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-16 19:59 UTC, komagata commented
@machida すみません、ねんのためmachidaさんにも確認していただければありがたいです〜

2021-04-19 06:23 UTC, SeijiNumata commented
@komagata 
ご確認ありがとうございます！
OKの出た後に、またコンフリクト していたので修正しました。

@machida 
ねんのためご確認をお願いいたします。

2021-04-19 07:14 UTC, SeijiNumata commented
@komagata 
確認ありがとうございます！
OKをもらった後にコンフリクト (jsファイルのLintの仕様変更も含める)していたので修正いたしました。

念のためもう一度ご確認いただければと思います。

@machida 
https://github.com/fjordllc/bootcamp/pull/2510#issuecomment-821529693
すみません、念のためこちらのプルリクのご確認をよろしくお願いいたします。

2021-04-20 05:25 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-29 14:40 UTC, machida commented
@komagata これ、別の修正でデグレしてしまったのか、機能がされてませんでした。一旦これは取り下げて、別の方法で実装した方が良さそうです。

2021-04-29 14:41 UTC, machida requested changes
こちら、
`checkableType ? "is-md" : "is-sm" では 機能しなかったので、別の方法で実装し直すのが良さそうです。

2021-04-29 14:46 UTC, machida commented
@komagata こちら、一旦駒形さんにアサインさせていただきましたー

2021-04-29 14:52 UTC, machida commented
一覧ページでは `is-sm` というサイズ。

<img width="812" alt="貼り付けた画像_2021_04_29_23_47" src="https://user-images.githubusercontent.com/168265/116570439-3e6b7780-a945-11eb-8256-33362e36ad55.png">

提出物個別ページでは `is-md` というサイズ。

<img width="802" alt="貼り付けた画像_2021_04_29_23_50" src="https://user-images.githubusercontent.com/168265/116571116-c18ccd80-a945-11eb-8bb9-490bace9a63d.png">

これを、一覧だから is-sm、個別だから is-md という出し分けで実装するのではなく、このコンポーネントを使う際に、buttonSize のような引数で、is-sm や is-md などを渡せるようにしたいです。

2021-04-30 00:04 UTC, Yu-kichi commented
@komagata @machida

こちらですがlintを入れた関係で必須になったpropsの記述がなかったのが原因かな〜と思います。
足してあげると問題なく機能しました。
別の方法で実装するかの判断はお任せしますが、一応報告しておきます〜。🙏

```
app/javascript/product_checker.vue
...
export default {
  props: {
    checkerId: { type: Number, required: false, default: null },
    checkerName: { type: String, required: false, default: null },
    currentUserId: { type: String, required: true },
    productId: { type: Number, required: true },
    checkableType: {type: String,}#ここを入れてあげることで機能した。 required: trueはあるとバグる。
  },
```

2021-05-03 07:42 UTC, komagata commented
@machida @Yu-kichi 調査ありがとうございます。
こちら確認します〜。（yu-kichiさんの言ってる通りかな〜と思います）

2021-06-02 15:31 UTC, SeijiNumata commented
@machida 
こちらデグレードを修正しました。
一旦やりやすい方法で修正してしまったのですが、https://github.com/fjordllc/bootcamp/pull/2510#issuecomment-829304846
こちらのコメントにあるような引数を渡す方法で実装し直した方が良いのでしょうか？

2021-06-02 15:37 UTC, machida commented
@SeijiNumata 引数を渡す方法は、またそれが必要な時になったら別Issueにしたいと思いますー。今回はこれでOKですー🙆‍♂️

2021-06-02 15:45 UTC, SeijiNumata commented
@machida 
承知いたしました。ありがとうございます！

@komagata 
一度駒形さんからOKが出ていますが、その後に別の修正と重なりデグレードを起こしたため修正しました。
もう一度レビューをよろしくお願いします🙇🏻

2021-06-03 04:26 UTC, komagata approved these changes
再度の修正ありがとうございます。
OKです〜！

2021-06-03 04:26 UTC, merged

2021-06-03 08:23 UTC, SeijiNumata commented
@komagata 
申し訳ありません。
プログラミングが久々すぎて、修正をpushし忘れるというミスをしました。

気がついた経緯ですが、ステージング環境で確認したところ変更が適用されていません。
ローカルでこのブランチにチェックアウトしたところ、
```
❯ git checkout feature/change_class__assign_button_product_show_page
Switched to branch 'feature/change_class__assign_button_product_show_page'
Your branch is ahead of 'origin/feature/change_class__assign_button_product_show_page' by 403 commits.
  (use "git push" to publish your local commits)
```
と言われています。
試しに403commit戻ってみて、リモートと同じ環境で再度実行したところ、うまく動いていないことが確認できました。
リモートのコミット履歴も、自分の修正が上書きされていませんでした。

この場合、新しくブランチを切ってプルリクを作り直して、PUSHし直すのが良いのでしょうか？
お手数おかけしてしまい申し訳ないです。

よろしくお願いします。

2021-06-03 10:41 UTC, komagata commented
@SeijiNumata 新しくブランチをきってPRの作成をお願いします〜

2021-06-03 12:55 UTC, SeijiNumata commented
@komagata 
承知いたしました。

https://github.com/fjordllc/bootcamp/pull/2776
新しいブランチで上記のプルリクを再度作成いたしました！