プラクティス一覧をvue.jsで表示できるようにした
fjordllc/bootcamp pull request #2537
Opened 2021-04-01 11:51 UTC by Yu-kichi

#2490
のissueに対応

### 概要

2021-04-24 02:00 UTC, Yu-kichi commented
@harukus 
お疲れ様です〜
お手隙の際にレビューをお願いしてもよろしいでしょうか🙏
よろしくお願い致します🙇‍♂️

2021-04-24 02:17 UTC, Yu-kichi commented on app/javascript/courses-practice.vue
> +  .m-user-icons(v-if='practices.started_students.length')
javascriptは0がfalseになるので.lengthで判定しています。
ただもっといい書き方があるかもと迷いながら書いています。

2021-04-27 01:34 UTC, harukus commented
@Yu-kichi 
 遅くなって非常に申し訳ありません。
自分では全く分からず時間がかかりすぎるので他の方にレビューを頼んでいただけると助かります:bow:
返事が遅くなってしまい、本当にごめんなさい:bow:

2021-04-27 01:58 UTC, Yu-kichi commented
@harukus

いえいえ特に急いでいた訳ではないのでお気になさらないで大丈夫ですよ〜😅
了解です〜！では他の方にお願いしてみますね〜👍

2021-04-27 02:08 UTC, Yu-kichi commented
@yamadaab 
お疲れ様です〜
お手隙の際にレビューをお願いしてもよろしいでしょうか🙏
お忙しければ他の方にレビューを回していただいても大丈夫です〜👍

2021-04-27 03:23 UTC, yamadaab commented
@Yu-kichi 
畏まりました！自分のキャパで問題ないか確認してみます！

2021-04-27 08:46 UTC, Yu-kichi commented
@yamadaab 

ありがとうございます！😊
日報にもまとめたので少しは読みやすくなるかもです〜。
[【271日目】プラクティス一覧をvue\\\.jsで表示できるようにしたまとめ1](https://bootcamp.fjord.jp/reports/29619)

2021-04-27 10:11 UTC, yamadaab reviewed
一つだけ命名が気になりました。ご確認下さい。
動作確認をしたところ問題はありませんでした。

日報もありがとうございました。おかげで助かりました。
もっと良いレビューをしたかったのですが、すみません自分の実力不足でした。🙇‍♂️
.lengthに関しても自分も使っていたと思います。

2021-04-27 13:20 UTC, Yu-kichi commented on app/javascript/courses-practices.js
> +import CorusesPractices from './courses-practices.vue'
@yamadaab

すいませんスペルミスです！修正しておきました！

>日報もありがとうございました。おかげで助かりました。
もっと良いレビューをしたかったのですが、すみません自分の実力不足でした。🙇‍♂️
.lengthに関しても自分も使っていたと思います。

いえいえ〜とんでもないです😳
レビューありがとうございます😊🙏

2021-04-27 13:24 UTC, Yu-kichi commented
@komagata

お手隙の際にレビューお願い致します〜🙏

2021-04-28 04:03 UTC, yamadaab approved these changes

2021-04-28 10:41 UTC, komagata requested changes

2021-04-28 10:41 UTC, komagata commented on app/controllers/api/courses/practices_controller.rb
> +    return unless current_user.retired_on?
まあ、これはAPIにはなくてもいいかな〜と思います。

2021-04-28 10:41 UTC, komagata commented on app/controllers/api/courses/practices_controller.rb
> +    @categories = @course.categories
PracticeのAPIに平均時間を持たせるのはナイスだと思います！

2021-04-28 10:41 UTC, komagata commented on app/javascript/practice-user-icon.vue
> +<template lang="pug">
ユーザーアイコン部分のコンポーネント化いいですね！

2021-04-28 10:41 UTC, komagata commented on app/views/api/courses/practices/_categories.json.jbuilder
> +    json.started_students practice.started_students.each do |user|
ここは他でも出てきそうなのでpartial化しちゃってもいいかもです。

2021-04-29 23:17 UTC, Yu-kichi commented on app/controllers/api/courses/practices_controller.rb
> +    return unless current_user.retired_on?
少し悩みましたがそうですよね！戻しておきます！

2021-04-29 23:19 UTC, Yu-kichi commented on app/views/api/courses/practices/_categories.json.jbuilder
> +    json.started_students practice.started_students.each do |user|
了解です！少し考えましたがpracticesのところに入れておきます。

2021-04-29 23:20 UTC, Yu-kichi commented
@komagata 

レビューありがとうございます😆
修正しましたので再レビューお願いいたします！🙏

2021-04-29 23:23 UTC, Yu-kichi commented
@harukus 

一応まだレビュー依頼中の状態になってしまっているので、問題なければapproveにしてください〜🙏

2021-04-29 23:58 UTC, harukus approved these changes
遅くなりました🙇‍♂️

2021-05-03 07:57 UTC, komagata requested changes

2021-05-03 07:57 UTC, komagata commented on app/controllers/courses/practices_controller.rb
> +    redirect_to retire_path
これもなくていいかもです〜（これ、他のところに移行期のためにあったコードだったので）

2021-05-03 07:57 UTC, komagata commented on app/views/api/practices/_started_students.json.jbuilder
> +end
最終行に改行がないようです〜

2021-05-03 13:14 UTC, Yu-kichi commented on app/controllers/courses/practices_controller.rb
> +    redirect_to retire_path
了解です！

2021-05-03 13:16 UTC, Yu-kichi commented
@komagata 
再修正しました！確認お願い致します！

2021-05-03 16:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-03 16:06 UTC, merged

2021-05-04 04:51 UTC, Yu-kichi commented
@komagata 
確認ありがとうございます！！😆

2021-05-06 11:40 UTC, Yu-kichi commented
@komagata
すいませんステージング環境で確認したところバグを発見しました。🙇‍♂️

### 確認した現象
「学習の準備」などプラクティスの説明文が表示されない
正確にいうとpタグの部分が表示されない。
<img width="1106" alt="スクリーンショット 2021-05-06 20 24 06" src="https://user-images.githubusercontent.com/64201542/117291322-cbfd1900-aea9-11eb-9172-27fe98d6d011.png">

### 原因
作成した次の部分がステージング環境では機能していないため、display: block;が機能しておらずpタグの部分が表示できていません。
scopedを外すと機能してくれそうな気がしますが、どう解決したら良いかはわかっていません。。
```
app/javascript/courses-practices.vue

<style scoped>
.js-markdown-view.js-target-blank.is-long-text {
  display: block;
}
</style>
```

ステージング環境の該当部分
<img width="582" alt="スクリーンショット 2021-05-06 20 27 57" src="https://user-images.githubusercontent.com/64201542/117291339-d3bcbd80-aea9-11eb-9b84-93fed8722a28.png">

確認の上、対応方法のご指示お願いいたします🙇‍♂️