タグで絞ったユーザー一覧でのフォロー説明を非表示にする
fjordllc/bootcamp pull request #2542
Opened 2021-04-02 02:25 UTC by misosoup160

issue #2485

タグで絞ったユーザー一覧では、フォロー説明が表示されないように修正しました。

<img width="1025" alt="ユーザー一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/66161651/113373269-706cd680-93a5-11eb-8220-7cc24cd222a4.png">
<img width="1028" alt="ユーザー一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/66161651/113373478-db1e1200-93a5-11eb-9591-d9272a5a38a4.png">

2021-04-03 01:37 UTC, misosoup160 commented
@gallardo16
お手隙の時にレビューお願いできますでしょうか🙏

2021-04-04 08:27 UTC, gallardo16 approved these changes
確認しました。OKだと思います🙆‍♂️

2021-04-04 08:56 UTC, misosoup160 commented
@gallardo16
ありがとうございました！

@komagata
レビューよろしくお願いします🙏

2021-04-07 04:59 UTC, komagata requested changes

2021-04-07 04:59 UTC, komagata commented on app/views/users/index.html.slim
> +          | #{ link_to 'くわしくはこちら', '/pages/303' }
```suggestion
          = link_to 'くわしくはこちら', '/pages/303'
```

2021-04-07 05:00 UTC, komagata commented on app/views/users/index.html.slim
> +          | #{ link_to 'くわしくはこちら', '/pages/303' }
こちら文字列埋め込みは必要ないかもなのでこっちの方がいいかもです〜

2021-04-08 04:33 UTC, misosoup160 commented on app/views/users/index.html.slim
> +          | #{ link_to 'くわしくはこちら', '/pages/303' }
了解です！修正しました🙏

2021-04-09 04:01 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-09 04:01 UTC, merged