まだ何もプラクティスを着手・完了していない受講生のダッシュボードに表示するエリアがほしい。
fjordllc/bootcamp pull request #2555
Opened 2021-04-05 03:01 UTC by harukus

# issue
#2486 に対応

2021-04-05 07:24 UTC, harukus commented
こちらはデザインが重要なPRなのでmachidaさんからデザインをいただいたら受講生の方へレビュー依頼→komagataさんへレビュー依頼とする予定です。

@machida 
デザインお願いいたします🙏

2021-04-27 03:36 UTC, machida commented
@harukus デザイン入れましたー

@yamadaab レビューお願いします🙏

2021-04-27 03:36 UTC, machida approved these changes

2021-04-27 06:05 UTC, yamadaab commented on app/views/home/_welcome_message.html.slim
> +              | 学習が進まなくて辛い、新しいことを知って嬉しい、プログラミングができるようになって楽しい、仕事が忙しくて学習に時間が取れなくて悲しい、プログラマーとして就職できるのか不安...これから学習を進めていく上で色んな気持ちになるかと思いますが、気持ちをチャットや日報を使ってアウトプットしていきましょう。辛いことに対しては親身に相談に乗ってくたり、アドバイスをしてくれたり
> 親身に相談に乗ってくたり
コードと関係ないのですが脱字かなと思いました。

2021-04-28 01:52 UTC, harukus commented
@yamadaab 
確認ありがとうございます:bow:
修正しました！
今一度確認お願いいたします。

2021-04-28 03:07 UTC, yamadaab approved these changes

2021-04-28 03:09 UTC, yamadaab commented
@harukus 
ご確認、修正ありがとうございます!
大丈夫だと思います😄

2021-04-28 03:58 UTC, harukus commented
@yamadaab 
ありがとうございます:bow:

2021-04-28 03:58 UTC, harukus commented
@komagata 
レビューお願いいたします:bow:

2021-04-28 10:35 UTC, komagata requested changes

2021-04-28 10:35 UTC, komagata commented on app/views/home/_welcome_message.html.slim
> +              | 卒業までは長期戦です。学習が思うように進まず辛いと感じ、モチベーションが続かないときが来るかもしれません。そのときに、一人で黙々とその苦しみから脱しようとすると、プログラミング学習自体が辛いものだと感じてしまいます。わからないことがあったら質問するのは当たり前ですが、それだけではなく、自分の気持ちをアウトプットする場としてコミュニティを使うのがオススメです。
```suggestion
              | 卒業までは長期戦です。学習が思うように進まず辛いと感じ、
              | モチベーションが続かないときが来るかもしれません。
              | そのときに、一人で黙々とその苦しみから脱しようとすると、
              | プログラミング学習自体が辛いものだと感じてしまいます。
              | わからないことがあったら質問するのは当たり前ですが、それだけではなく、
              | 自分の気持ちをアウトプットする場としてコミュニティを使うのがオススメです。
```

1行で長い文章はこういう感じで改行するとHTML的には同じですがソースコードが見やすくなるので良いかもです〜

2021-04-28 10:35 UTC, komagata commented on test/system/users_test.rb
> +  test 'not show weclome message' do
```suggestion
  test 'not show welcome message' do
```

2021-04-28 10:35 UTC, komagata commented on test/system/users_test.rb
> +  test 'show weclome message' do
```suggestion
  test 'show welcome message' do
```

2021-04-28 11:51 UTC, harukus commented on app/views/home/_welcome_message.html.slim
> +              | 卒業までは長期戦です。学習が思うように進まず辛いと感じ、モチベーションが続かないときが来るかもしれません。そのときに、一人で黙々とその苦しみから脱しようとすると、プログラミング学習自体が辛いものだと感じてしまいます。わからないことがあったら質問するのは当たり前ですが、それだけではなく、自分の気持ちをアウトプットする場としてコミュニティを使うのがオススメです。
@komagata 
なるほどです:eyes:
そのほかの長い文章も改行して修正してみました!

2021-04-28 11:57 UTC, komagata requested changes

2021-04-28 11:57 UTC, komagata commented on test/system/users_test.rb
> +    wait_for_vuejs
これは不要かもです〜

2021-04-29 04:05 UTC, harukus commented on test/system/users_test.rb
> +    wait_for_vuejs
こちらはプラクティスに着手したらダッシュボードにメッセージが表示されなくなるテストだったのですが、
そうではなくてログインしなければ表示されない、というテストの方が好ましいということでしょうか:bow:

2021-04-29 15:02 UTC, komagata requested changes

2021-04-29 15:02 UTC, komagata commented on test/system/users_test.rb
> +    wait_for_vuejs
いえ、ここにはvue.jsが関係ないので`wait_for_vuejs`は不要ではないかという意味です〜

2021-05-01 06:34 UTC, harukus commented on test/system/users_test.rb
> +    wait_for_vuejs
なるほどです！
確かに必要ないですね。
`wait_for_vuejs`がないと時折テストが落ちてしまいます＞＜こういう場合はどのようにしたら良いでしょうか:bow:

2021-05-03 08:45 UTC, komagata commented on test/system/users_test.rb
> +    wait_for_vuejs
@harukus あ〜、これだめなんですね、すみません、僕の間違いでした。
これ`wait_for_vuejs`入れちゃって大丈夫です。

2021-05-03 08:45 UTC, komagata approved these changes

2021-05-03 08:45 UTC, merged

2021-05-04 00:34 UTC, harukus commented on test/system/users_test.rb
> +    wait_for_vuejs
確認ありがとうございます！