グローバルナビにヘルプのリンクを追加
fjordllc/bootcamp pull request #2566
Opened 2021-04-06 12:23 UTC by alto-I

## Issue

[ヘルプへのリンクがほしい \#2487](https://github.com/fjordllc/bootcamp/issues/2487)

## やること

`global_nav`の以下の部分helpのリンクを追加したい。

<img src="https://tva1.sinaimg.cn/large/008eGmZEgy1gp8yyte3fpj30eu10s761.jpg" alt="image-20210405175514277"/>

2021-04-06 22:10 UTC, alto-I commented
@hituzi-no-sippo 
お手数ですが、こちらのissueレビューお願いできますでしょうか🙇

2021-04-06 23:16 UTC, hituzi-no-sippo requested changes
## エラーが発生して、ヘルプページが表示できません

ヘルプページのデータがDBに存在しないのが理由だと推測しています。

## エラー内容

### ブラウザのgif

![fail](https://user-images.githubusercontent.com/43565959/113787683-72a0ad80-9776-11eb-8e44-8ed375fdbd04.gif)

### termianlのログ

```shell
Processing by PagesController#show as HTML
  Parameters: {"id"=>"334"}
Completed 404 Not Found in 26ms (ActiveRecord: 11.3ms | Allocations: 5820)



ActiveRecord::RecordNotFound (Couldn't find Page with 'id'=334):

app/controllers/pages_controller.rb:58:in `set_page'
```

## 操作手順

1. feature/added_help_links_to_global_navigation をcheckout
2. `rails db:reset`
3. `ralis s`
4. ログイン
5. ヘルプをクリック
6. エラーが発生する

## やってほしいこと

* 上記のエラー修正
  私の操作手順が間違っていたら、正しい操作手順を教えてください 🙏 
* `link_to '/pages/334', class: "global-nav-links__link #{current_link(%r{^pages/334})}"` への質問の回答と修正案の検討
* テストの追加
* ヘルプのリンクをクリックした後の画面のスクリーンショット
  今のPRの説明文だと、どのような画面が表示されたら正解なのか分かりません～

2021-04-07 01:27 UTC, machida commented
@alto-I @hituzi-no-sippo 

このIssueについての今後の計画をシェアさせていただきますー。
これ、最初にこのIssueに書いておくべきでした🙇‍♂️

## 今回のIssue

一旦ヘルプを置くとどうなるかの検証をするためのIssueになります。
実験的にナビゲーションに置き、そこのリンク先に見て欲しページへのリンクを貼る予定です。
すぐに実装できるように、一旦は `/pages/334` でリリースをします。

## 次のステップ

今回のIssueは1st Issueなので、グローバルナビにリンクを置くだけにとどめ、別のIssueで 開発環境でも `/pages/334`  にアクセスができるように seed データを用意してもらい、必要があればそこへアクセスできるかのテストも用意していこうと思います。

## その次のステップ

グローバルナビにリンクが pages/334 へのリンクがあるのはキモいので、新しい model を作り、`/pages/334`  から help/index に差し替えたいと思います。

2021-04-07 11:30 UTC, alto-I commented
@hituzi-no-sippo 
丁寧なレビューのご確認ありがとうございます！😄

@machida 
isuueの補足説明ありがとうございます！😭

## ヘルプのリンクのページがエラーになる問題
これはmachidaさんのコメントのあるとおり、とりあえずこのままのリンクでお願いします！
自分としても何も説明せずレビューを投げてしまい申し訳なかったです🙇

## 質問の回答
> 質問
なぜ #{current_link(%r{^pages/334}) のように %r を利用しているのでしょうか ❓
他の部分は全て #{current_link(/^questions/)} のように %r を利用しない書き方で書いており、統一しない理由はありますか ❔

これはrubocopの設定で正規表現の対象に`/`を入れると`%r`の仕様を推奨するようになっているようです。一度`//`でやってみたところlintが通らず以下のエラーを吐きました。
~~~
% bundle exec slim-lint app/views -c config/slim_lint.yml
app/views/application/_global_nav.slim:61 [W] RuboCop: Style/RegexpLiteral: Use `%r` around regular expression.
~~~

rubocopの設定
[rubocop/default\.yml at master · rubocop/rubocop](https://github.com/rubocop/rubocop/blob/master/config/default.yml#L4322)
~~~ruby
Style/RegexpLiteral:
  Description: 'Use / or %r around regular expressions.'
  StyleGuide: '#percent-r'
  Enabled: true
  VersionAdded: '0.9'
  VersionChanged: '0.30'
  EnforcedStyle: slashes
  # slashes: Always use slashes.
  # percent_r: Always use `%r`.
  # mixed: Use slashes on single-line regexes, and `%r` on multi-line regexes.
  SupportedStyles:
    - slashes
    - percent_r
    - mixed
  # If `false`, the cop will always recommend using `%r` if one or more slashes
  # are found in the regexp string.
  AllowInnerSlashes: false
~~~

## 修正案について
> 修正案
/pages/334 だと、"ヘルプページのURLなのか?" と疑問に感じました、できるのであれば、ヘルプページと明確にわかるようにコードを修正した方がいいと思います～ 😄

修正案までいただきありがとうございます！こちらもmachidaさんのコメントのとおり、現状このままとさせていただきます🙇

## テストについて
開発環境ではリンクが飛ばないので、テストをどう書いていいか戸惑っています…

2021-04-07 11:30 UTC, komagata commented
@alto-I このIssueにテストはなくて大丈夫です〜

2021-04-07 11:38 UTC, alto-I commented
@machida 
こちら順番が前後してしまって申し訳ないのですが、デザインのほうをお願いできますでしょうか🙇
現状ヘルプのアイコンに以下を使用しています。
[Hands Helping Icon \| Font Awesome](https://fontawesome.com/icons/hands-helping)
![image](https://user-images.githubusercontent.com/68221700/113860425-fbecca00-97e0-11eb-85a5-7a164e0ae6da.png)

2021-04-07 11:38 UTC, alto-I commented
> @alto-I このIssueにテストはなくて大丈夫です〜

了解です！

2021-04-08 00:19 UTC, hituzi-no-sippo approved these changes
町田さんの今後の計画を読みました。
これでOKだと思います～ 😄 

>> 質問
>> なぜ #{current_link(%r{^pages/334}) のように %r を利用しているのでしょうか ❓
>> 他の部分は全て #{current_link(/^questions/)} のように %r を利用しない書き方で書いており、統一しない理由はありますか ❔
>
> これはrubocopの設定で正規表現の対象に/を入れると%rの仕様を推奨するようになっているようです。一度//でやってみたところlintが通らず以下のエラーを吐きました。

あぁ、"lintを通すため正規表現を/から%rへ修正"(febd8721d4a2a2a038e1b15f2ad9811718e25bd9) の部分ですね。すみません、見落としていました 🙇 
`pages/334` は他のパスと違い `/` があり、 %rの記法ではないと `\/` のようにエスケープ文字必要だからrubocopから警告が発生しているみたいですね。それなら、ここだけ%r記法でも問題ないと思います～

2021-04-08 03:50 UTC, alto-I commented
@hituzi-no-sippo 
レビューありがとうございました！
レビュー詳しく書いていただき書き方などとても参考になります😄

2021-04-08 04:14 UTC, machida commented
@alto-I 
デザイン了解ですー

@hituzi-no-sippo 
計画ご確認ありがとうございますー

2021-04-08 06:18 UTC, machida commented
@komagata デザイン入れましたー レビューお願いします🙏

2021-04-09 04:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-09 04:00 UTC, merged

2021-04-09 22:31 UTC, alto-I commented
@komagata 
ご確認ありがとうございます！