期一覧ページに2020年12月31日開始者のアイコンが表示されない
fjordllc/bootcamp pull request #2620
Opened 2021-04-18 08:15 UTC by alto-I

issue #2598

2021-04-18 13:07 UTC, alto-I commented
@misosoup160 
こちらのPRお手隙の際にレビューよろしくお願いします！😄

2021-04-18 19:34 UTC, komagata commented
@alto-I レビュー依頼するときはDraftでない状態（Ready for review）にしてからにしてください〜

2021-04-18 23:20 UTC, alto-I commented
@komagata 
そうでした😥
ご指摘ありがとうございます！😄

2021-04-19 02:49 UTC, misosoup160 approved these changes
確認しました！
最終日を時刻までとることでバグがなおるんですね。
変数名もわかりやすくなってとても良いと思いました〜👍

2021-04-19 03:23 UTC, alto-I commented
@misosoup160 
レビューありがとうございます！

@komagata 
レビューよろしくお願いします！🙇

2021-04-20 05:23 UTC, komagata requested changes

2021-04-20 05:23 UTC, komagata commented on app/models/generation.rb
> +  def start_of_fisrt_day
fisrt -> firstかも？

また、`start_date` からメソッド名が変わったのはなぜでしょう？
すみません、start_of_first_dayの意味がちょっとわからないかもです。

2021-04-20 08:10 UTC, alto-I reviewed
@komagata 
指摘された点を修正したので、再度ご確認をよろしくお願いします！

2021-04-20 08:19 UTC, alto-I commented on app/models/generation.rb
> +  def start_of_fisrt_day
タイポですね。すいません😭

`start_of_first_day`にしたのは、元々`start_date`が日付までの情報(例:2014/3/1)しか持っておらず、それがバグの原因でした。バグの解消するために時刻まで取得(例:2014/3/1 0:00:00)するようにしたので、メソッド名もその期の最初の日の0時からという意味合いを持たせたくてメソッド名を変更しました。

2021-04-21 07:10 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-21 07:10 UTC, komagata commented on app/models/generation.rb
> +  START_YEAR = 2013
👍

2021-04-21 07:10 UTC, merged

2021-04-21 08:18 UTC, alto-I commented on app/models/generation.rb
> +  START_YEAR = 2013
😄

2021-04-21 08:18 UTC, alto-I commented
ご確認ありがとうございます！