タグ一覧ページを作る
fjordllc/bootcamp pull request #2641
Opened 2021-04-27 00:26 UTC by misosoup160

2021-04-27 01:10 UTC, misosoup160 commented
@harukus 
お手隙の時にこちらレビューお願いできますでしょうか🙏

2021-04-27 02:16 UTC, misosoup160 commented on app/controllers/users/tags_controller.rb
> +  end
`tag.users`のようなことがやりたかったのですが、tagの管理はgemの方にあるので、helper_methodで書いてみました。

2021-04-27 02:16 UTC, misosoup160 commented on app/views/users/_lg_page_tabs.html.slim
>            | 期生別
`current_page_tab_or_not` の方だと、users/tagsというurlに対応できないので`users_current_page_tab_or_not` というメソッドを新しくヘルパーに作りました。

2021-04-28 02:16 UTC, harukus reviewed
質問もあります！確認お願いいたします:bow:

2021-04-28 02:16 UTC, harukus commented on app/views/tags/_tag.html.slim
> +          | #{tag.taggings_count}
これらのコードは登録者数上位3位のtagに対してクラスをふっていると思うのですが、デザインはこれからとのことだったのでここに何かしらデザインが入るという認識でよろしいでしょうか？

2021-04-28 02:26 UTC, misosoup160 commented on app/controllers/users/tags_controller.rb
> +    @max_counts = @tags.limit(3).map(&:taggings_count).uniq
確かにそうですね！数字が入る変数名を調べてみたらこんなの出てきました。数字を分離しないで書くと良いみたいです。これでちょっと書き直してみます〜🙏
https://techracho.bpsinc.jp/hachi8833/2017_02_13/35364#3-03

2021-04-28 02:28 UTC, misosoup160 commented on app/views/tags/_tag.html.slim
> +          | #{tag.taggings_count}
そうです！町田さんが考えてくださっていると思います。
なので、クラスがついている位置などもとりあえずの場所になっています〜。

2021-04-28 02:46 UTC, harukus commented on app/views/tags/_tag.html.slim
> +          | #{tag.taggings_count}
かしこまりました！

2021-04-28 04:00 UTC, harukus approved these changes
確認できました！OKだと思います🙆‍♀️

2021-04-28 04:14 UTC, misosoup160 commented
@harukus 
ありがとうございます🙏

@komagata 
こちらお手隙の時にレビューお願いします🙏

2021-04-28 10:45 UTC, komagata requested changes

2021-04-28 10:45 UTC, komagata commented on app/controllers/users/tags_controller.rb
> +  def users_tagged_with(tag_name)
`users_`とprefixが付いてるのであればまさにUserモデルに書いた方が良いと思います〜

2021-04-29 06:27 UTC, misosoup160 commented on app/controllers/users/tags_controller.rb
> +  def users_tagged_with(tag_name)
ちょっと名前が思いつかず微妙かもしれませんがUserモデルに移動しました。こういうことであってますか？

2021-05-03 07:29 UTC, komagata requested changes

2021-05-03 07:29 UTC, komagata commented on app/views/users/_popular_tags.html.slim
> +    =link_to 'もっとみる', users_tags_path, class: 'recent-reports__to-index'
```suggestion
    = link_to 'もっとみる', users_tags_path, class: 'recent-reports__to-index'
```

2021-05-03 10:27 UTC, misosoup160 commented on app/views/users/_popular_tags.html.slim
> +    =link_to 'もっとみる', users_tags_path, class: 'recent-reports__to-index'
修正しました！

2021-05-03 10:29 UTC, misosoup160 commented
@komagata @machida 
harukusさんが指摘してくださって変更した変数名が #2636 でのコードでも変更しないといけないところがあるので、あとでmainを取り込んで修正しようと思っています。町田さんの作業とのタイミングとかどうでしょうか。

2021-05-03 15:59 UTC, komagata commented
@misosoup160 

> 町田さんの作業とのタイミングとかどうでしょうか。

これはどう言った意味でしょうか？

2021-05-09 00:30 UTC, misosoup160 commented
@komagata
私の勘違いで修正するところは特にありませんでした。すいません🙏
ただ、タグの人数に、リタイアしたユーザーが登録していた数が含まれてしまっているようですので、そこを修正しました。　0f9ae70
確認お願いします。
他に修正箇所なければ町田さんにデザインを引き継ぎたいと思います。

2021-05-09 01:07 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-10 00:41 UTC, misosoup160 commented
#2666 によるコンフリクト解消しましたー。

2021-05-12 05:35 UTC, machida approved these changes

2021-05-12 05:36 UTC, machida commented
@misosoup160 @komagata デザイン入れましたー

2021-05-12 06:56 UTC, machida commented
@misosoup160 @komagata 
レビュー通ってるのでマージしますー

2021-05-12 06:56 UTC, merged