解決済みのQ&Aのソート順(並び)を解決日時順か新規コメントの作成日時順にする
fjordllc/bootcamp pull request #2645
Opened 2021-04-27 23:44 UTC by harukus

## issue
#2135

2021-04-28 11:41 UTC, harukus commented
@alto-I 
お手隙でコードレビューお願いいたします:bow:

2021-04-30 03:23 UTC, alto-I approved these changes
@harukus 
コード問題ないと思います！

一つ気になったのですが、issueの時点でもう仕様が新規コメント作成日時順になっているのであればPR名もそれに合わせてもいいような気がしました！
（issue名と同一にするなどの決まりがあるなら、このままでもいいと思います！）

2021-05-01 06:38 UTC, harukus commented
@alto-I 
確かにそうですね！
変更しました！

2021-05-01 06:45 UTC, alto-I commented
他は問題ないと思います！

2021-05-01 06:58 UTC, harukus commented
@alto-I 
ありがとうございます:bow:

@komagata 
レビューよろしくお願いいたします:bow:

2021-05-03 15:56 UTC, komagata requested changes

2021-05-03 15:56 UTC, komagata commented on app/views/questions/index.html.slim
> +      - if @tags.any?
👍

2021-05-03 15:56 UTC, komagata commented on app/models/question.rb
> +  scope :solved, -> { where(id: CorrectAnswer.pluck(:question_id)) }
ここってなんで変更されていますか？
CorrectAnswerを全部持ってくると後々データが増えていったときに膨大な量になっちゃうかも？

2021-05-04 01:53 UTC, harukus commented on app/models/question.rb
> +  scope :solved, -> { where(id: CorrectAnswer.pluck(:question_id)) }
`joins(:correct_answer)`をすると解決済みの質問に対して一つのcorrerct_answerしか取得できなくなってしまい、また`includes(:answers)`をしても解決済みのanswerしか取得できないため、CorrectAnswerテーブルからQuestion_idを取得し解決されているかどうかを判別するようにしました。

>CorrectAnswerを全部持ってくると後々データが増えていったときに膨大な量になっちゃうかも？

確かにそうかもしれません、、
コンソールで試したのですが、膨大な量になるというのは下記の`IN`の中の数字が増えてしまうということでしょうか🤔
irb(main):006:0> Question.where(id: CorrectAnswer.pluck(:question_id)).to_sql
=> "SELECT \"questions\".* FROM \"questions\" WHERE \"questions\".\"id\" IN (1006638408, 997052767)"
irb(main):007:0> Question.joins(:correct_answer).to_sql
=> "SELECT \"questions\".* FROM \"questions\" INNER JOIN \"answers\" ON \"answers\".\"question_id\" = \"questions\".\"id\" AND \"answers\".\"type\" = 'CorrectAnswer'"

2021-05-09 00:40 UTC, komagata commented on app/models/question.rb
> +  scope :solved, -> { where(id: CorrectAnswer.pluck(:question_id)) }
> joins(:correct_answer)をすると解決済みの質問に対して一つのcorrerct_answerしか取得できなくなってしまい、またincludes(:answers)をしても解決済みのanswerしか取得できないため、CorrectAnswerテーブルからQuestion_idを取得し解決されているかどうかを判別するようにしました。

なるほどです。

> コンソールで試したのですが、膨大な量になるというのは下記のINの中の数字が増えてしまうということでしょうか🤔

はい、そうです。

2021-05-09 00:41 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-09 00:41 UTC, merged

2021-05-09 01:49 UTC, harukus commented on app/models/question.rb
> +  scope :solved, -> { where(id: CorrectAnswer.pluck(:question_id)) }
確認ありがとうございます:bow: