検索結果一覧をVue.jsで非同期にする
fjordllc/bootcamp pull request #2664
Opened 2021-05-05 01:48 UTC by alto-I

issue #2571

2021-05-11 23:49 UTC, alto-I commented
@misosoup160 
こちらのPRお手隙の際にレビューお願いできないでしょうか🙇

2021-05-14 02:38 UTC, misosoup160 reviewed
レビューしてみました！
手元での動作確認もして全体的に問題ないと思います。
あとは、私の方にもコメントくださってたので、気がついたのですが、_sarchable.html.slimは消せるかな？と思いました。間違っていたらすいません🙏

2021-05-14 02:38 UTC, misosoup160 commented on app/views/api/searchables/index.json.jbuilder
> +json.total_pages @searchables.page(1).total_pages
`.page(1)`のところはコントローラーの`@searchables` のインスタンス変数へ入れるところで指定しているのでいらないかな？と思いました。

2021-05-14 02:38 UTC, misosoup160 commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.summury md_summury(filtered_message(searchable), 90)[3..-5]
`[3..-5]`は何かな？と思ったんですが、pタグの除去なんですね👍

2021-05-14 02:38 UTC, misosoup160 commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.updated_at_date_time searchable.updated_at.to_datetime
多分これはどっちでもいいと思うんですが、Vue側でday.jsを使って変換する方法もあるかなと思いました。
たまたま私がそのissueをやっただけなので、参考までに🙏
dayjsで検索するとanswer.vueとかで使われてます。

2021-05-14 02:38 UTC, misosoup160 commented on app/javascript/searchable.vue
> +            :href='userUrl'
respond_to?の書き換えなるほど！と思いました👍

2021-05-15 06:07 UTC, alto-I commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.updated_at_date_time searchable.updated_at.to_datetime
day.js参考になりましたありがとうございます！

どちらがいいかって考えた時、rails側で変換して渡しちゃったほうがコードの記述量減るからいいかなって思ったのですがどっちがいいか悩ましいですね🤔
とりあえずこのままにしてみます！

2021-05-15 06:07 UTC, alto-I commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.summury md_summury(filtered_message(searchable), 90)[3..-5]
すいません説明があれば良かったですね😅

2021-05-15 06:08 UTC, alto-I commented on app/views/api/searchables/index.json.jbuilder
> +json.total_pages @searchables.page(1).total_pages
ご指摘ありがとうございます！`page(1)`を除去しました！

2021-05-15 09:24 UTC, alto-I commented
@misosoup160 
> あとは、私の方にもコメントくださってたので、気がついたのですが、_sarchable.html.slimは消せるかな？と思いました。間違っていたらすいません🙏

すいません完全にブーメランですね😅
`_sarchable.html.slim`は消去しましたので再度ご確認をよろしくお願いします🙇

あと`searchable.vue`のtemplate部分が元のファイルのタグが変わった影響でこちらも変更しましたが、こちらはmachidaさんに確認してもらおうと思っています。

2021-05-15 11:34 UTC, misosoup160 approved these changes
確認しました！良いと思います〜🙆

2021-05-15 11:59 UTC, alto-I commented
@misosoup160 
ご確認ありがとうございます！

@machida
こちらお手隙の時にデザインご確認お願いできないしょうか🙇

2021-05-18 02:07 UTC, machida commented
@alto-I デザイン入れました！！ユーザーの色が設定されてなかったので、それだけ追加しました。

2021-05-18 02:08 UTC, machida commented
@komagata こちらレビューお願いしますー🙏

2021-05-18 09:19 UTC, alto-I commented
@machida 
デザイン確認ありがとうございます！😄

@komagata 
レビューよろしくお願いします！😄

2021-05-19 07:09 UTC, komagata requested changes

2021-05-19 07:09 UTC, komagata commented on app/javascript/searchables.vue
> +    |
この行ってなんでしょう？

2021-05-19 07:09 UTC, komagata commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.updated_at_date_time searchable.updated_at.to_datetime
REST APIとしてはあのページの表示に使われるためだけに存在するわけではないので、日付データはAPIとして一般的な形がいいと思います。

つまりVue側で変換するのがいいかなと思います。

2021-05-19 12:39 UTC, alto-I commented on app/javascript/searchables.vue
> +    |
すいません不要な行でしたので削除しました！

2021-05-19 12:41 UTC, alto-I commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.updated_at_date_time searchable.updated_at.to_datetime
day.jsを導入し、vue側で変換するように修正しました！

~~~javascript
    updatedAt() {
      return dayjs(this.searchable.updated_at).format(
        'YYYY年MM月DD日(dd) HH:mm'
      )
    }
~~~

2021-05-20 09:13 UTC, alto-I commented on app/javascript/searchable.vue
> +      )
dayjsを導入してこちらで時刻を変換するように修正しました！

2021-05-21 05:20 UTC, komagata commented
@alto-I 不要なmergeコミットがいくつか入っているようです〜
（mainとの差分だけになるはずです）

2021-05-22 00:46 UTC, alto-I commented
@komagata 
すいません色々試行錯誤していたのですが、このブランチを適正な状態に修正できそうにないのでもう一度ブランチを作り直してPRを作成してもいいでしょうか…？

2021-05-22 01:52 UTC, machida commented
@alto-I @komagata 
一旦別ブランチ作るでいいと思いますー
うまくいかなかったら質問タイムで一緒にやってみましょう

2021-05-22 01:57 UTC, alto-I commented
@machida 
返信ありがとうございます！一旦別ブランチで作り作業を進めます！

2021-05-23 10:03 UTC, alto-I commented
一旦このPRはcloseします。新しいPRは #2728 です。

2021-05-23 10:03 UTC, closed without merging