Vue.jsで表示する際にプラクティスの説明文が表示できるようにする
fjordllc/bootcamp pull request #2668
Opened 2021-05-06 12:39 UTC by Yu-kichi

2021-05-07 08:36 UTC, Yu-kichi commented on app/javascript/courses-practices.vue
> +          if (element) {
この部分はisuueとは直接は関係ありませんが、elementが空白の場合に警告文が出てしまうため修正したいと考えました。

2021-05-07 08:37 UTC, Yu-kichi commented
@komagata 
お手隙の際にレビューをお願いいたします🙏

2021-05-09 00:54 UTC, komagata commented on app/javascript/courses-practices.vue
> +          .js-markdown-view.js-target-blank.is-long-text(:style='styleObject')
これって最初から`display: 'block'`なのであればstyleをcssファイルに書く方法で対応できないですかね？

2021-05-09 15:17 UTC, Yu-kichi commented on app/javascript/courses-practices.vue
> +          .js-markdown-view.js-target-blank.is-long-text(:style='styleObject')
確かにわざわざvueで書く必要ないですね😅
cssで書きます！

2021-05-09 15:17 UTC, Yu-kichi commented
@komagata
再修正しました！お手隙の際に確認お願い致します🙏

2021-05-10 00:35 UTC, komagata requested changes

2021-05-10 00:35 UTC, komagata commented on app/assets/stylesheets/blocks/practice/_categories.sass
> +  .js-markdown-view.js-target-blank.is-long-text
これらのクラスは他でも使われているものだと思うので、新しくクラスを割り当てた方がいいかもです。

2021-05-10 08:21 UTC, Yu-kichi commented on app/assets/stylesheets/blocks/practice/_categories.sass
> +  .js-markdown-view.js-target-blank.is-long-text
すいません見落としていました、修正します！

2021-05-10 08:22 UTC, Yu-kichi commented
@komagata 
再修正しましたので、確認お願いいたします🙇‍♂️

2021-05-10 08:25 UTC, komagata commented on app/javascript/courses-practices.vue
> +          .js-markdown-view.js-target-blank.is-long-text.is-practices-description
`is-xxx`って状態を示すとか何か命名ルールがあった気がします。

@machida これってなんでしたっけ？

2021-05-12 07:00 UTC, machida commented on app/javascript/courses-practices.vue
> +          .js-markdown-view.js-target-blank.is-long-text.is-practices-description
@komagata `is-xxx` 何かの xxxバージョンという、何かを継承しつつ xxxバージョンのときだけ一部書き換えのときに使っていますー

@Yu-kichi 
`is-practices-description` のときは display: block にするようになってますが、これって、これをしないと display: block にならないですか？

2021-05-12 08:09 UTC, machida commented
こちら僕見てみますー🙋‍♂️

2021-05-12 08:11 UTC, Yu-kichi commented on app/javascript/courses-practices.vue
> +          .js-markdown-view.js-target-blank.is-long-text.is-practices-description
@machida 
Vue.jsにする前の状態ではこのように書かれていて、こちらの場合ではdisplay: blockが反映されていました。
```
                .categories-item__description
                  - if current_user.admin?
                    .categories-item__edit
                      = link_to edit_admin_category_path(category, course_id: @course.id), class: 'categories-item__edit-link' do
                        i.fas.fa-pen
                  .js-markdown-view.js-target-blank.is-long-text
                    = category.description
```

ただvue.jsにするとこれだけでは反映されないので新しく ```display: block```を設定しなければならないのかな〜と判断しました。

2021-05-12 08:55 UTC, machida commented
@Yu-kichi すいません、途中なのですが、プラクティス一覧画面category.descriptionをmarkdownで出せるようになったら完了になります。こちら引き継いでもらっていいでしょうか？

2021-05-12 12:29 UTC, Yu-kichi commented
@machida
MarkdownInitializerを使っていなかったのが原因だったのですね😳
こちら引き継ぎさせていただきます！
ありがとうございます🙏

2021-05-12 12:49 UTC, machida commented
@Yu-kichi 中途半端な状態ですいません🙏 よろしくお願いします

2021-05-12 13:29 UTC, komagata commented
@Yu-kichi こちら明日のリリースに必要な感じだと思いますが、いかがでしょうか？

2021-05-12 13:35 UTC, Yu-kichi commented
@komagata

再修正しましたので確認お願いいたします！🙏

2021-05-13 02:04 UTC, machida commented
@komagata 確認、rebase やっておきますー

2021-05-13 02:22 UTC, machida commented
@komagata 動作、内容確認しました！！テスト通ったらマージをお願いします🙏

2021-05-13 03:54 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-13 03:54 UTC, komagata commented on app/javascript/courses-practices.vue
> +    markdownDescription: function () {
👍

2021-05-13 03:54 UTC, merged

2021-05-13 04:58 UTC, Yu-kichi commented
@machida
すいません不要な部分を見落としていました。修正していただきありがとうございます🙇‍♂️

@komagata 
確認ありがとうございます！🙏