解決済みQAの表示件数にばらつきがある
fjordllc/bootcamp pull request #2697
Opened 2021-05-15 02:18 UTC by harukus

## issue

2021-05-19 06:50 UTC, harukus commented
@komagata 
こちら修正が完了したのですが、この場合は生徒の方にレビューを依頼した方がいいのでしょうか？？

2021-05-20 06:30 UTC, machida commented
@yamadaab こちらレビューお願いできますでしょうか🙏

2021-05-20 07:41 UTC, yamadaab commented
> @yamadaab こちらレビューお願いできますでしょうか🙏

畏まりました！

2021-05-20 08:03 UTC, yamadaab approved these changes

2021-05-20 08:03 UTC, yamadaab commented
@machida @harukus 
レビュー完了しました。問題ないと思います！

2021-05-20 08:04 UTC, machida commented
@yamadaab レビューありがとうございます🙏

@komagata レビューお願いしますー🙏

2021-05-21 05:17 UTC, komagata requested changes
バグの修正なのでテストが欲しいですね。

2021-05-21 09:17 UTC, harukus commented
@komagata かしこまりました！

2021-06-01 07:33 UTC, komagata commented
q = Questio.save(....)
q.anser = Anser.create()

2021-07-09 04:00 UTC, harukus commented
@komagata ごめんなさい、komagataさんが修正してくださったコミットを消してしまいました🙇‍♀️もう一度pushしてもらえますか🙇‍♀️申し訳ないです🙏

2021-07-10 17:32 UTC, komagata commented
@harukus すみません、僕のローカルに残ってないので下記の情報から再現していただければと思います〜

```
~/dev/src/github.com/fjordllc/bootcamp bug/Problems-number-of-displays ⇣⇡
❯ g d HEAD~~
diff --git a/app/controllers/questions_controller.rb b/app/controllers/questions_controller.rb
index 97d293e5..af433541 100644
--- a/app/controllers/questions_controller.rb
+++ b/app/controllers/questions_controller.rb
@@ -21,13 +21,8 @@ class QuestionsController < ApplicationController
     @tags = questions.all_tags
     questions = params[:practice_id].present? ? questions.where(practice_id: params[:practice_id]) : questions
     questions = questions.tagged_with(params[:tag]) if params[:tag]
-    questions =
-      if params[:solved].present?
-        questions.includes(:answers).order('answers.updated_at DESC')
-      else
-        questions.order(updated_at: :desc, id: :desc)
-      end
-    @questions = questions.preload(%i[practice answers]).with_avatar.page(params[:page])
+    questions = questions.includes(:practice, :answers).order(updated_at: :desc, id: :desc)
+    @questions = questions.with_avatar.page(params[:page])
     @questions_property = questions_property
   end
 
diff --git a/app/models/answer.rb b/app/models/answer.rb
index 4fd4d9bf..7184041d 100644
--- a/app/models/answer.rb
+++ b/app/models/answer.rb
@@ -6,7 +6,7 @@ class Answer < ApplicationRecord
   include Mentioner
 
   belongs_to :user, touch: true
-  belongs_to :question
+  belongs_to :question, touch: true
   alias sender user
 
   after_create AnswerCallbacks.new
```

2021-07-15 00:46 UTC, harukus commented
@komagata ありがとうございます🙇‍♀️参考にします🙏

2021-07-15 02:43 UTC, harukus commented
@komagata 
ごめんなさい、mainのリベースでこんがらがってしまったので新しくPRを作り直しました。申し訳ありません。
新しいPR #2981

2021-07-15 02:43 UTC, closed without merging