検索結果一覧をVue.jsで非同期にする
fjordllc/bootcamp pull request #2728
Opened 2021-05-22 07:29 UTC by alto-I

2021-05-23 10:05 UTC, alto-I commented
@komagata 
こちらご確認をお願いいたします🙇

2021-05-24 06:40 UTC, komagata commented
@alto-I まずは生徒の方のどなたかにレビュー依頼をおねがい致します〜

2021-05-24 09:21 UTC, alto-I commented
@yamadaab 
こちらお手隙の際レビューお願いします🙇

2021-05-25 02:16 UTC, yamadaab approved these changes

2021-05-25 02:18 UTC, yamadaab commented
@alto-I 
遅くなりました。
問題なく動作していることを確認しました！
コードも問題ないかと思います！

2021-05-25 03:29 UTC, alto-I commented
@yamadaab 
全然遅くないです！むしろ早いです😄
レビューありがとうございました！

@komagata 
こちらレビューよろしくお願いします！😄

2021-05-25 13:27 UTC, komagata requested changes

2021-05-25 13:27 UTC, komagata commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.summury md_summury(filtered_message(searchable), 90)[3..-5]
`[3..-5]`これってどういう処理でしょう？
名前をつけるためにメソッドなどにした方がいいかも

2021-05-26 20:44 UTC, alto-I commented on app/views/api/searchables/_searchable.json.jbuilder
> +json.summury md_summury(filtered_message(searchable), 90)[3..-5]
@komagata

`[3..-5]`は

~~~ruby
def md_summury(comment, word_count)
  summury = strip_tags(md2html(comment)).gsub(/[\r\n]/, '')
  simple_format(truncate(summury, length: word_count))
end
~~~

上記メソッドの`simple_format`で出てきた`<p>...</p>`を消すために使っていました。`md_summury`のままapiでvue側に渡してしまうと、pタグがそのまま画面上に出力されてしまったため、`[3..-5]`で一度消しvue側でpタグを付ける処理をしていました。

### 修正後

`app/helpers/application_helper.rb`に新たに以下のメソッドを定義し、apiでvue側に渡すようにしました。

~~~ruby
  def summury(comment, word_count)
    summury = strip_tags(md2html(comment)).gsub(/[\r\n]/, '')
    truncate(summury, length: word_count)
  end
~~~

`app/views/api/searchables/_searchable.json.jbuilder`

~~~ruby
json.summury summury(filtered_message(searchable), 90)
~~~

2021-05-26 20:45 UTC, alto-I commented
@komagata 
修正した部分のご確認よろしくお願いします！

2021-05-28 14:12 UTC, komagata requested changes

2021-05-28 14:12 UTC, komagata commented on app/helpers/application_helper.rb
> +  def summury(comment, word_count)
application_helperは全てのViewで使えるグローバル関数的な感じになってしまうので、summaryという名前は意味が大き過ぎるかもです。（他にsummaryという名前が必要になった時にぶつかってしまう）

2021-06-04 22:28 UTC, alto-I commented on app/helpers/application_helper.rb
> +  end
メソッド名を`summury`から`searcher_summury`に変更しました！

2021-06-09 04:27 UTC, komagata requested changes

2021-06-09 04:27 UTC, komagata commented on app/helpers/application_helper.rb
> +  def searcher_summury(comment, word_count)
`searcher_summary`だと検索する人（的な何か）のサマリーって意味になるので`searchable_summary`とか`searched_summary`とかの方がいいかも？

x) summury
o) summary

2021-06-12 08:35 UTC, alto-I commented on app/helpers/application_helper.rb
> +  def searcher_summury(comment, word_count)
ご指摘ありがとうございます！
`searcher_summury`から`searchable_summary`にメソッド名を変更しました。

また`summury`になっている部分がいくつかあったので、`summary`に修正しました。
~~~
% rg summury
app/helpers/application_helper.rb
15:  def md_summury(comment, word_count)
16:    summury = strip_tags(md2html(comment)).gsub(/[\r\n]/, '')
17:    simple_format(truncate(summury, length: word_count))

app/views/works/_work.html.slim
14:          = md_summury(work.description, 140)

app/views/users/comments/_comment.html.slim
18:    .thread-list-item__summury
19:      = md_summury(comment.description, 90)

app/views/watches/_watch.html.slim
13:        .thread-list-item__summury
14:          = md_summury(watchable.body, 90)

app/assets/stylesheets/blocks/thread/_thread-list-item.sass
125:.thread-list-item__summury

app/javascript/searchable.vue
13:        .thread-list-item__summury
~~~

2021-06-12 11:01 UTC, alto-I commented
@komagata 
修正しましたので再度ご確認をよろしくお願いします！

2021-06-14 05:44 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

マージしますので。
ステージング環境でしっかり目に確認してみてください〜

2021-06-14 05:44 UTC, komagata commented on app/controllers/api/searchables_controller.rb
> +  before_action :require_login
https://github.com/fjordllc/bootcamp/blob/main/app/controllers/api/base_controller.rb#L4

これを継承してるので要らないかもです。

2021-06-14 11:12 UTC, alto-I commented on app/controllers/api/searchables_controller.rb
> +  before_action :require_login
すいません`API::BaseController`にあるのを見落としていました。
`before_action :require_login`を削除しました！

2021-06-14 11:18 UTC, alto-I commented
@komagata 
再度ご確認をよろしくお願いします！
あとやる前に確認するべきでしたが`summury`と表記していた部分は別issue立てて修正すべきだったでしょうか？😥
もしその方がよろしければ、ここでは修正せずに別issue立てて修正しようと思います！

2021-06-14 11:18 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

マージしますので、ステージングにデプロイされたらしつこめに動作確認してみてください〜

2021-06-14 11:18 UTC, komagata commented on app/controllers/api/searchables_controller.rb
> +  def document_type_param
👍

2021-06-14 11:18 UTC, merged