初日報がsadだったときに3日連続sadのユーザーに表示されるバグを修正
fjordllc/bootcamp pull request #2729
Opened 2021-05-23 07:39 UTC by obregonia1

2021-05-23 08:08 UTC, obregonia1 commented
@sutehuna 
お手隙の際にレビューよろしくお願いします🙇‍♂️

2021-05-24 00:07 UTC, JunichiIto commented on app/models/user.rb
> +    three_days_reports.size == 3 && three_days_reports.all?(&:sad?)
再発防止のため、モデルのテストも書いてほしいな〜と思いました。

2021-05-24 04:01 UTC, obregonia1 commented on app/models/user.rb
> +    three_days_reports.size == 3 && three_days_reports.all?(&:sad?)
了解しました！
元々あったテストに追加しました✍️

2021-05-24 06:36 UTC, JunichiIto approved these changes
良いと思いますー。

2021-05-24 06:36 UTC, JunichiIto commented on test/models/user_test.rb
> -    4.times do |i|
なぜ3じゃなくて4だったのか気になる・・・。

2021-05-24 07:17 UTC, obregonia1 commented on test/models/user_test.rb
> -    4.times do |i|
同じこと思いました😅

2021-05-25 06:27 UTC, sutehuna commented
@obregonia1 
解説ありがとうございます。私の環境でも動くので問題はなさそうです。

ただ、私がわからないのは、sad?メソッドがどこで定義されているかということです。たぶん、コードには定義されていませんよね？
enumは列挙型なので、これが直接メソッド定義の振る舞いをするかというと多分違うはずです。
どこかで動的にメソッド定義のようなことが行われていると思うのですが…？

おそらく私がわかっていないだけなのでレビューはOKにしますね。

2021-05-25 06:29 UTC, sutehuna approved these changes

2021-05-25 06:57 UTC, obregonia1 commented
@sutehuna 
> sad?メソッドがどこで定義されているか

すいません、言葉足らずで分かりにくかったですね。。。
enumを定義することによって`ActiveRecord :: Enum`モジュールが`sad?`メソッドを生成してくれているものだと認識していますー。

@komagata 
お手隙の際にレビューよろしくお願いします🙇‍♂️
あと、上記のenumについての認識は間違っていないでしょうか？

2021-05-25 06:58 UTC, obregonia1 commented
@JunichiIto 
確認ありがとうございます😄

2021-05-25 07:11 UTC, sutehuna commented
@obregonia1 
確認できました。
enumを定義すると自動的にメソッドが追加されるんですね。
勉強になりました、ありがとうございます。

2021-05-25 13:31 UTC, komagata requested changes

2021-05-25 13:31 UTC, komagata commented on test/models/user_test.rb
> +    )
上の方の元のコードも同様ですが、

```
foo = Foo.new()
foo.save!
```
だったら
```
Foo.create!()
```
でいいかもです〜

2021-05-26 00:39 UTC, obregonia1 commented
@komagata 
指摘された点と少しコードを修正しました。
確認よろしくお願いします🙇‍♂️

2021-05-26 05:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-26 05:00 UTC, merged

2021-05-27 02:32 UTC, obregonia1 commented
@komagata 
こちらでは本番環境での確認ができないのでよろしくお願いします🙇‍♂️

2021-05-27 08:08 UTC, universato commented
モデルで書かれる`enum`はRubyのコードの機能としてみたときメソッドですね。
Railsが独自の文法(DSL)ぽくしているのでわかりにくいですが、メソッドでして見ることができれば、内部で何かさせるんだろうなというのが理解しやすい気がします。
`enum`は、動的に`sad?`などのメソッドを作ることもするメソッドです。
あまり流通してない言葉ですが、「クラスマクロ」と呼ばれるタイプのメソッドだと思います。

[ActiveRecord::Enum](https://api.rubyonrails.org/v6.1.3/classes/ActiveRecord/Enum.html#method-i-enum)
Railsの公式ドキュメントのところで`show`や`github`をクリックすれば、`enum`の定義を見ることができます。
 ざっとしか見てないですが、`enum`メソッド内で呼ばれる`define_enum_methods`の中で動的に`sad?`が定義されるのでしょう。

```ruby
        define_enum_methods(name, value_method_name, value, enum_scopes)
```
↓
https://github.com/rails/rails/blob/5aaaa1630ae9a71b3c3ecc4dc46074d678c08d67/activerecord/lib/active_record/enum.rb#L234-L237
```ruby
          def define_enum_methods(name, value_method_name, value, enum_scopes)
            # def active?() status_for_database == 0 end
            klass.send(:detect_enum_conflict!, name, "#{value_method_name}?")
            define_method("#{value_method_name}?") { public_send(:"#{name}_for_database") == value }
```