提出物の個別ページにユーザーのIDだけでなく名前を出したい
fjordllc/bootcamp pull request #2757
Opened 2021-05-31 06:20 UTC by kasai441

Issue
#2745

2021-06-01 00:25 UTC, kasai441 commented
@obregonia1 
レビュー依頼お願いしたいのですが、このようなお願いの仕方で良いでしょうか。
テストファイルを新たに作っているところと、命名の感じが良いかどうかが気になっています。

2021-06-01 02:20 UTC, obregonia1 commented
![image](https://user-images.githubusercontent.com/75117116/120256532-55e1ab80-c2c9-11eb-9a1a-01affccc7f68.png)
Reviewersの項目にアカウント名が出ているので大丈夫です👍

ユーザーのIDだと数字になってしまうので`login_name`と`full_name`みたいに書いた方がわかりと思います。
あとテストファイルを新しく作っていますが、このファイルに追加するようなテストケースはなさそうなので`test/system/products_test.rb`に追加で書いた方がいいかなと思いましたー。

2021-06-01 02:41 UTC, kasai441 commented
> Reviewersの項目にアカウント名が出ているので大丈夫です👍

ありがとうございます！

> ユーザーのIDだと数字になってしまうので`login_name`と`full_name`みたいに書いた方がわかりと思います。

これはPRやissueの題名のことでしょうか？プルリクは直しますが、issueのほうも揃えて直すべき（そもそも直せる）でしょうか。

> あとテストファイルを新しく作っていますが、このファイルに追加するようなテストケースはなさそうなので
`test/system/products_test.rb`に追加で書いた方がいいかなと思いましたー。

分かりました！

修正したのち再度ご連絡する感じで良いですか。

2021-06-01 03:07 UTC, obregonia1 commented
> これはPRやissueの題名のことでしょうか？プルリクは直しますが、issueのほうも揃えて直すべき（そもそも直せる）でしょうか。

言葉足らずですいません💦
テスト名について言及したのですが、PRの方も変えた方がいいかもしれないですね！(issueは変えなくてもいいかなと思います)
細かいことですが、PRのタイトルは具体的な作業内容を書くものなので、〜したいではなく、〜したとかの方がいいと思います。

> 修正したのち再度ご連絡する感じで良いですか。

コメント頂けたら再度確認しますー！

2021-06-01 05:39 UTC, kasai441 commented
@obregonia1 
変更したところ反映されて、CIも通ったようなので、レビューお願いしますー

2021-06-01 06:27 UTC, obregonia1 approved these changes
確認しました！OKだと思います😄

2021-06-01 06:34 UTC, kasai441 commented
@obregonia1 
素早い対応ありがとうございます！

@komagata
こちら、チームリーダーレビューお願いします。

2021-06-03 04:20 UTC, komagata requested changes

2021-06-03 04:20 UTC, komagata commented on app/views/products/show.html.slim
> +                        = "#{@product.user.login_name} (#{@product.user.name})"
いろんなところで使いそうなのでdecoratorで実装するといいかもですね。

- [amatsuda/active\_decorator: ORM agnostic truly Object\-Oriented view helper for Rails 4, 5, and 6](https://github.com/amatsuda/active_decorator)
- [Decoratorの役割とDraperについて \- Qiita](https://qiita.com/jonson29/items/00077b54bb91ed74fdb8)
- [Rails Viewの表示のためにDecoratorを用意してHelperとModelを助ける \- Qiita](https://qiita.com/shizuma/items/ce9e863e9c94e88e0a57)

2021-06-04 03:36 UTC, komagata requested changes
decoratorにメソッドを作った時は対応するテストも欲しいです〜

2021-06-04 03:36 UTC, komagata commented on app/decorators/user_decorator.rb
> +  def login_and_full_name
長いので何か一言で示せるメソッド名が付けれるといいな〜と思います。

```ruby
@user.xxxx
```

とメソッドを呼んだ時にわかりやすい字面で。

2021-06-07 01:38 UTC, kasai441 commented
@komagata 
名前変更してテスト加えました。
名前はいくつか考えたのですがどうでしょうか。他に以下のような候補があります。
all_name
large_name
whole_name
entire_name
both_names

2021-06-09 04:48 UTC, komagata approved these changes

2021-06-09 04:48 UTC, komagata commented on app/decorators/user_decorator.rb
> +  def long_name
僕もいい名前パッと思いつかなかったんですが、`long_name`いいかもですね！

2021-06-09 04:48 UTC, merged