参考書籍に必読かどうかのチェックボックスと説明のテキストエリアを追加
fjordllc/bootcamp pull request #2771
Opened 2021-06-02 12:40 UTC by gozasoro

ref: #2755

2021-06-07 17:47 UTC, gozasoro commented
@obregonia1 こちらお手隙の際にレビューをお願いいたします！

2021-06-07 23:43 UTC, obregonia1 reviewed
確認しました！
問題なさそうですが一点だけコメントしております✍️

2021-06-07 23:43 UTC, obregonia1 commented on app/models/reference_book.rb
> +  validates :must_read, inclusion: { in: [true, false] }
`schema.rb`で`t.boolean "must_read", default: false, null: false`としてるので`presence: true`で良さそうかなと思ったんですが`inclusion`にしている理由はありますか？

2021-06-08 12:55 UTC, obregonia1 commented on app/models/reference_book.rb
> +  validates :must_read, inclusion: { in: [true, false] }
なるほどー！それならよさ候です🙆‍♂️

2021-06-08 14:05 UTC, gozasoro commented on app/models/reference_book.rb
> +  validates :must_read, inclusion: { in: [true, false] }
ありがとうございますー！

2021-06-08 14:06 UTC, gozasoro commented
@machida こちらレビューをいただいたのでデザインをお願いいたします！

2021-06-21 06:54 UTC, machida commented
@gozasoro デザイン入れましたー


![image](https://user-images.githubusercontent.com/168265/122719245-e6981f80-d2a8-11eb-952b-255cc47aeb45.png)


![image](https://user-images.githubusercontent.com/168265/122719133-bf415280-d2a8-11eb-8297-5c077e92e897.png)


![image](https://user-images.githubusercontent.com/168265/122719075-aa64bf00-d2a8-11eb-9314-8e30b736126a.png)

2021-06-21 06:54 UTC, machida commented
@komagata レビューお願いします🙏

2021-06-22 02:56 UTC, komagata requested changes
テストが落ちてるみたいです〜

2021-06-29 06:30 UTC, machida commented
mainをrebaseしました。
只今テスト待ち。

2021-06-29 11:06 UTC, machida commented
@komagata テスト修正しましたー

2021-06-29 12:00 UTC, komagata requested changes

2021-06-29 12:00 UTC, komagata commented on app/views/practices/show.html.slim
> +                          | 円（税込）
`number_to_currency`を使うのが良さそうです〜

2021-06-29 23:03 UTC, gozasoro commented
@machida @komagata 今週は開発プラクティスにほぼ取り組めていない状態でした💦mainのrebaseとテスト修正、ありがとうございます🙏`number_to_currency`で金額表示するようにしたので確認をお願いいたします

2021-06-30 11:53 UTC, komagata requested changes
このページのCommitsタブを見てみると、色々なマージコミットができているようです。
PRはmainとの差分なので基本的にはマージコミットはないはずですので修正してみてください〜

2021-07-05 15:20 UTC, gozasoro commented
PRで作成した部分のみで新しくブランチを作成したので、こちらはcloseしたいと思います。

2021-07-05 15:20 UTC, closed without merging