管理者権限でユーザータグを編集できない
fjordllc/bootcamp pull request #2772
Opened 2021-06-02 14:07 UTC by SeijiNumata

#2670 に対応

2021-06-02 15:36 UTC, SeijiNumata commented
@gozasoro 
お世話になっております。
こちら差し支えなければレビューをして頂けると嬉しいのですが、ご都合いかがでしょうか？
特に急いでないのでゆっくりで大丈夫です！

2021-06-03 04:27 UTC, komagata commented
@SeijiNumata 仕事でも単なる通常業務として行うので

「レビューお願いします〜」

ぐらいで、あまり気を使わなくても大丈夫ですよ〜

2021-06-03 04:34 UTC, SeijiNumata commented
@komagata 
承知しました！
ありがとうございます！

2021-06-04 12:04 UTC, gozasoro approved these changes
@SeijiNumata 確認できました！大丈夫だとおもいます〜！

2021-06-04 12:21 UTC, SeijiNumata commented
@gozasoro 
ありがとうございます！

@komagata 
受講生からレビューのOKをいただきましたので、レビューをお願いいたします！

2021-06-09 04:23 UTC, komagata requested changes
バグの修正時なのでテストを追加いただけるとありがたいです〜

（バグ修正前は通らないが、修正後は通るテスト）

2021-06-12 09:24 UTC, SeijiNumata commented
@komagata 
管理者権限でタグを追加するテストを追加しました！

ご確認よろしくお願いします！

１点相談なのですが、branch nameの先頭に`feature/`をつけるのを忘れていたことに気がつきました。
申し訳ありません。
こちら`feature/`をつけると新しくブランチを作り直すことになると思いますが、いかがいたしましょうか？

2021-06-14 05:41 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-14 05:41 UTC, komagata commented
@SeijiNumata 

> こちらfeature/をつけると新しくブランチを作り直すことになると思いますが、いかがいたしましょうか？

次からつけてくれれば大丈夫です〜

2021-06-14 05:41 UTC, merged

2021-06-14 08:04 UTC, SeijiNumata commented
承知いたしました。
次から`feature/`をつけてブランチを作成するように気をつけます。
ありがとうございます！