Q&A個別ページで回答数がローディングのときは 0 ではなく、ロード中アイコンを出して欲しい
fjordllc/bootcamp pull request #2775
Opened 2021-06-03 11:21 UTC by SeijiNumata

#2773

2021-06-03 11:59 UTC, SeijiNumata commented on app/javascript/question.vue
> +      answerCount: null
ここをnullにしておかないと、ロードが終わった後に一瞬0という文字が出てしまうためnullに設定しました。
他に影響が出ていないことを動作確認済みです。

2021-06-03 12:12 UTC, SeijiNumata commented
@alto-I 
こちらお時間ある時にレビュー頂けますと嬉しいです！

よろしくお願いいたします！

2021-06-04 12:54 UTC, alto-I reviewed
@SeijiNumata 
レビューしました！1点だけ気になる部分があったのでお願いします😄

2021-06-04 12:54 UTC, alto-I commented on app/javascript/question-edit.vue
> +        .a-count-badge__value(v-else,:class='answerCount === 0 ? "is-zero" : ""')
`v-else,`のあとスペースがあったほうがいいと思います！

2021-06-05 15:33 UTC, SeijiNumata commented on app/javascript/question-edit.vue
> +        .a-count-badge__value(v-else,:class='answerCount === 0 ? "is-zero" : ""')
@alto-I 
本当ですね、ありがとございます！

2021-06-05 22:56 UTC, alto-I approved these changes
@SeijiNumata 
修正ありがとうございました！大丈夫だと思います😄

2021-06-11 22:22 UTC, SeijiNumata commented
@alto-I 
ありがとうございます！

@komagata 
こちらレビューをお願いいたします！

2021-06-14 05:40 UTC, komagata requested changes

2021-06-14 05:40 UTC, komagata commented on app/javascript/question-edit.vue
> +        .a-count-badge__value(v-else, :class='answerCount === 0 ? "is-zero" : ""')
v-else`,`
これって必要なんでしたっけ？

2021-06-14 05:40 UTC, komagata commented on app/javascript/question.vue
> +      answerCount: null
`answerCount: { type: Number, required: true },`
この定義に反するので何か他の方法で対応したいっすね。

2021-06-14 11:55 UTC, SeijiNumata commented on app/javascript/question-edit.vue
> +        .a-count-badge__value(v-else, :class='answerCount === 0 ? "is-zero" : ""')
ご指摘ありがとうございます。
必要ありませんでしたので削除いたしました！

2021-06-15 15:55 UTC, SeijiNumata reviewed
@komagata 
レビューありがとうございます！！
修正致しましたので、再度ご確認お願いいたします。🙇🏻

2021-06-18 05:10 UTC, komagata requested changes

2021-06-18 05:10 UTC, komagata commented on app/javascript/question-edit.vue
> +    answerCount: { type: Number, required:false },
実装の都合ではなく、回答数のカウントは必須だと思うのでtrueにしたいですね。

読み込みが終わるまではこの表示部分を隠しておけば良いかもです〜

2021-06-18 08:58 UTC, SeijiNumata commented on app/javascript/question-edit.vue
> +    answerCount: { type: Number, required:false },
読み込みが終わる判定タイミングを考え直しました！
うまくいくようになりました〜
ありがとうございます！

2021-06-22 02:39 UTC, komagata requested changes

2021-06-22 02:39 UTC, komagata commented on app/javascript/question-edit.vue
> +    updatedAnswerCount: { type: Boolean, required: true },
Booleanだとわかるように、JSだったら`isCountUpdated`などの名前にした方がいいかもです〜
（rubyだったら`updated?`）

2021-06-22 08:19 UTC, SeijiNumata commented on app/javascript/question-edit.vue
> +    updatedAnswerCount: { type: Boolean, required: true },
なるほどです〜JSだったら「is〇〇」でBooleanってことになるんですね！
勉強になります！修正いたしました！

2021-06-24 01:44 UTC, komagata requested changes

2021-06-24 01:44 UTC, komagata commented on app/javascript/question-edit.vue
> +      practices: null,
```suggestion
      practices: null
```

2021-06-24 01:44 UTC, komagata commented on app/javascript/question.vue
> +      :isAnswerCountUpdated='isAnswerCountUpdated'
```suggestion
      :isAnswerCountUpdated='isAnswerCountUpdated',
```

2021-06-26 02:02 UTC, SeijiNumata commented
@komagata 
ご確認ありがとうございます！
修正いたしましたので再度レビューをお願いいたします！

2021-06-28 05:15 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-28 05:15 UTC, merged

2021-06-29 17:27 UTC, SeijiNumata commented
@komagata 
すみません。
町田さんにデザインを見てもらうことになっていたのですが、マージしてしまって大丈夫でしょうか？
レビューをお願いする順番を間違えていたら申し訳ないです。

@machida 
メンションをつけておきます。

2021-06-30 02:06 UTC, machida commented
@SeijiNumata おっと、こちらデザインを別PRでおくりますー

2021-06-30 03:29 UTC, SeijiNumata commented
@machida 
承知いたしました。
ありがとうございます！