日報にブックマーク機能を実装
fjordllc/bootcamp pull request #2789
Opened 2021-06-05 09:25 UTC by alto-I

issue: #2658

2021-06-12 05:18 UTC, alto-I commented
@SeijiNumata 
こちらお手隙の際レビューお願いできないでしょうか🙇

2021-06-12 16:43 UTC, SeijiNumata reviewed
確認しました！
とても良いと思います！
一点だけ質問しましたのでご確認ください！
よろしくお願いいたします🙇🏻

2021-06-13 09:47 UTC, alto-I commented on app/javascript/bookmark.vue
> +            time.a-date(:datetime='bookmark.reportedOn', pubdate='pubdate')
ご指摘ありがとうございます！
廃止されているのを知りませんでした😅

2021-06-13 09:48 UTC, alto-I commented
@SeijiNumata 
ご指摘受けた点修正しましたので、再度ご確認お願いします！😄

2021-06-14 08:06 UTC, SeijiNumata commented
@alto-I 
確認しました！
OKです！修正ありがとうございました！🙇🏻

2021-06-14 10:44 UTC, alto-I commented
@SeijiNumata 
ご確認ありがとうございました！勉強になりました😄

2021-06-14 12:50 UTC, alto-I commented
@komagata 
こちらレビューよろしくお願いします！😄

2021-06-15 04:43 UTC, komagata requested changes

2021-06-15 04:43 UTC, komagata commented on app/controllers/api/bookmarks_controller.rb
> +    return unless params[:bookmarkable_id] && params[:bookmarkable_type]
この場合、APIはどういうレスポンスを返すかんじですかね？
Railsのエラーが出ないようにしたいっすね。

2021-06-15 04:43 UTC, komagata commented on app/controllers/api/bookmarks_controller.rb
> +    @bookmark.save!
```suggestion
    @bookmark = Bookmark.create!(
      user: current_user,
      bookmarkable: bookmarkable
    )
```

2021-06-23 09:01 UTC, alto-I commented on app/controllers/api/bookmarks_controller.rb
> +    return unless params[:bookmarkable_id] && params[:bookmarkable_type]
@komagata
お返事遅くなってすいません！
この場合は、`bookmarkable_id` と `bookmarkable_type`に対応したブックマーク情報を返すようになっています。ブックマークしてあればその日報の情報、してなければ`bookmarks`以下が空のJSONを返します。

返すAPIの例

~~~json
{"bookmarks":
  [
    {"id":1046770788,
    "modelName":"Report",
    "modelNameI18n":"日報",
    "author":"Komagata Masaki",
    "authorUrl":"http://localhost:3000/users/459775584",
    "url":"http://localhost:3000/reports/701335546",
    "title":"作業週1日目",
    "reportedOn":"2017年01月01日"
    }
  ]
}
~~~

日報の個別ページでブックマークしているかの判定に使っています。

この部分は自分でも少し気になっていたのですが`index`の部分は

- ブックマーク一覧の取得
- 日報のページでのブックマークしているかの確認

の二つで使用しており、役割を二つ持たせている状態になっています。

ここは別のコントローラーを用意して分けた方がいいでしょうか？

2021-06-24 01:50 UTC, komagata commented on app/controllers/api/bookmarks_controller.rb
> +    return unless params[:bookmarkable_id] && params[:bookmarkable_type]
UI上の二つの場所から使われていることは全く問題ないです〜。
考え方としてはUIとは全く切り離して考えて、このサービスの `/api/bookmarks.json`というAPIとしてどういう動き・データを返すのが相応しいかというのだけを考えれば良い感じです〜
（RESTの観点）

2021-06-24 01:51 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-24 01:51 UTC, komagata commented
@alto-I @machida  こちらデザインは必要ですかね？まだマージはしないでおきます〜

2021-06-28 02:47 UTC, alto-I commented
@komagata 
ご確認ありがとうございます！
RESTの観点を自分がまだちゃんと理解できていない部分がありましたので復習します 💪

2021-06-28 02:49 UTC, alto-I commented
@machida @komagata 
こちら一度質問タイムでmachidaさんにデザインの大まかな部分は伺っているのですが、念の為ご確認をお願いしたいです🙇

2021-06-28 05:26 UTC, komagata commented
@alto-I 

> こちら一度質問タイムでmachidaさんにデザインの大まかな部分は伺っているのですが、念の為ご確認をお願いしたいです🙇

こちらどう言う意味でしょうか？
僕に対しての内容ですかね？僕が確認すべきはどんな点になりますか？

2021-06-29 03:43 UTC, alto-I commented
@komagata 

> @alto-I
> 
> > こちら一度質問タイムでmachidaさんにデザインの大まかな部分は伺っているのですが、念の為ご確認をお願いしたいです🙇
> 
> こちらどう言う意味でしょうか？
> 僕に対しての内容ですかね？僕が確認すべきはどんな点になりますか？

すいません、こちらmachidaさんにデザインの確認をして欲しいという意味で書きました。わかりづらくて申し訳ありません🙇

@machida 
デザインのご確認よろしくお願いします！🙇

2021-06-29 09:18 UTC, machida commented
@alto-I デザイン了解ですー🙆‍♂️

2021-06-30 14:05 UTC, machida commented
デザイン入れました。
テスト待ち。

2021-07-01 15:55 UTC, machida commented
テストが通りましたのでマージしますー

2021-07-01 15:55 UTC, merged

2021-07-04 08:29 UTC, alto-I commented
@machida 
デザインご確認&マージありがとうございます！