docsにslugを付けてアクセスできるように
fjordllc/bootcamp pull request #2799
Opened 2021-06-08 13:56 UTC by gozasoro

ref: #2751

2021-06-08 16:15 UTC, gozasoro commented
@SeijiNumata こちらお手隙の際にレビューをお願いいたしますー！

2021-06-09 07:29 UTC, SeijiNumata reviewed
@gozasoro 

レビューしました！ご確認よろしくお願いします🙇🏻
全体的に自信がないので、間違えていたら教えていただけると嬉しいです！

2021-06-09 07:29 UTC, SeijiNumata commented on app/controllers/pages_controller.rb
> +    @page = Page.find_by(slug: params[:slug_or_id]) || Page.find(params[:slug_or_id])
find_byはfindも兼ねるので、`@page = Page.find_by(slug: params[:slug_or_id])`だけでいいような気もしたのですが、いかがでしょうか〜(自信はないです)

https://qiita.com/tsuchinoko_run/items/f3926caaec461cfa1ca3

2021-06-09 07:29 UTC, SeijiNumata commented on db/schema.rb
>      t.index ["practice_id"], name: "index_reference_books_on_practice_id"
不要なコードが含まれているようです〜

2021-06-09 07:29 UTC, SeijiNumata commented on app/models/page.rb
> +    self.slug = nil if slug && slug.empty?
` self.slug = nil if slug.empty?`だけで良いと思ったのですが、いかがでしょうか〜 (これも自信ないです。)

slugが何か入っていた場合⇨　slug="○○"でtrue
slugが空白だった場合⇨ 　slug=""でtrue
よって、slugは毎回trueとなるためです。

2021-06-09 16:47 UTC, gozasoro commented on app/controllers/pages_controller.rb
> +    @page = Page.find_by(slug: params[:slug_or_id]) || Page.find(params[:slug_or_id])
`@page = Page.find_by(slug: params[:slug_or_id])`では`slug`をキーに検索している（`id`では検索できていない）ので、`slug`が登録されていないときに`Page.find(params[:slug_or_id])`で`id`からマッチするものを探しています！
リンクの記事では`id`で検索するときは`find_by`でもできるよ〜ってことかなと自分は思いました（`find_by`だとマッチしなかったときに例外が発生しないので`id`の方では`find`を使っています）！

2021-06-09 16:47 UTC, gozasoro commented on db/schema.rb
>      t.index ["practice_id"], name: "index_reference_books_on_practice_id"
前回PRのコードが混ざっちゃってました、ありがとうございます💦

2021-06-09 16:47 UTC, gozasoro commented on app/models/page.rb
> +    self.slug = nil if slug && slug.empty?
https://github.com/fjordllc/bootcamp/blob/1dbb7335c4f220c0e4a9e5f4cbd43ecd7620820d/app/models/page.rb#L17-L18
https://github.com/fjordllc/bootcamp/blob/1dbb7335c4f220c0e4a9e5f4cbd43ecd7620820d/app/models/page_callbacks.rb#L4-L12
ページを`create`または`update`した後に呼び出される`page_callbacks.rb`内のメソッドでもう一度`page.save`され、このタイミングで`slug == nil`になる場合があるため、`self.slug = nil if slug && slug.empty?`としています！

2021-06-09 17:23 UTC, gozasoro commented
@SeijiNumata コメントと修正をさせていただいたので、お手隙の際に再度レビューをお願いいたします〜！

2021-06-09 17:29 UTC, SeijiNumata commented on app/controllers/pages_controller.rb
> +    @page = Page.find_by(slug: params[:slug_or_id]) || Page.find(params[:slug_or_id])
すみません、find_byでもIDで検索できると勘違いしていました！

記事を読み直したら書いてありました😅　頓珍漢なことを言ってしまってすみません🙇🏻
勉強になりました。ありがとうございます！！

2021-06-09 17:34 UTC, SeijiNumata commented on app/models/page.rb
> +    self.slug = nil if slug && slug.empty?
すみません、このコードの意味やっと理解できました！
勉強になります！ありがとうございます！🙇🏻

2021-06-09 17:42 UTC, SeijiNumata commented
@gozasoro 
ありがとうございます！
指摘箇所は全てOKです！(自分の理解不足な点が多かったですが、解説していただき理解できました。ありがとうございます。)

`git pull origin main` してみたところ、`schema.rb`がコンフリクトしているようなので修正した方がよいかもしれないです！

2021-06-09 18:24 UTC, gozasoro commented on app/models/page.rb
> +    self.slug = nil if slug && slug.empty?
slug=""の判定は`true`で合ってる気がします！

2021-06-09 18:26 UTC, gozasoro commented
@SeijiNumata わー！コンフリクトしてますね💧修正しました！お願いいたしますー！

2021-06-09 18:41 UTC, SeijiNumata commented
@gozasoro 
修正ありがとうございました！
LGTMです！　駒形さんにレビュー依頼をお願いいたします！

2021-06-10 13:43 UTC, gozasoro commented
@SeijiNumata レビューありがとうございました！

@komagata こちらお手隙の際にレビューをお願いいたします！

2021-06-10 14:35 UTC, sinsoku commented on app/models/page.rb
> +  validates :slug, length: { maximum: 200 }, format: { with: /\A[a-z][a-z0-9_-]*\z/ }, uniqueness: true, allow_nil: true
`slug: "foo"` と `slug: "Foo"` を登録した場合、どうなるでしょうか？
`case_sensitive` をどう取り扱うかはuniqueness制約のときに注意が要るため、確認をお願いします！

2021-06-10 14:38 UTC, sinsoku commented on app/models/page.rb
> +  validates :slug, length: { maximum: 200 }, format: { with: /\A[a-z][a-z0-9_-]*\z/ }, uniqueness: true, allow_nil: true
と思ったら、正規表現が小文字だけでした。（見逃してました 👀 ）
それなら問題なさそうです。

2021-06-10 14:45 UTC, sinsoku commented on app/controllers/pages_controller.rb
> +    @page = Page.find_by(slug: params[:slug_or_id]) || Page.find(params[:slug_or_id])
slugはアルファベットから始まるので、以下のように書くと `find_by` でまとめられそうかなと思いました。

```suggestion
    attr_name = params[:slug_or_id]).start_with?(/[a-z]/) ? :slug : :id
    @page = Page.find_by(attr_name => params[:slug_or_id])
```

`Page.find_by(...) || Page.find(...)` だとSQLが2回発行される事があるため、それよりも常に1回のSQLが発行される書き方の方がパフォーマンスが良いです。

2021-06-14 04:59 UTC, komagata requested changes

2021-06-14 04:59 UTC, komagata commented on app/controllers/pages_controller.rb
> +    @page = Page.find_by(slug: params[:slug_or_id]) || Page.find(params[:slug_or_id])
他でも使いそうなのと、どういうことをやってるのかの説明も兼ねてPageクラスのメソッドにするとスマートかもです〜

2021-06-14 04:59 UTC, komagata commented on db/migrate/20210607171344_add_slug_column_to_pages.rb
> +    add_index :pages, :slug, unique: true
👍

2021-06-30 00:52 UTC, gozasoro commented
@komagata 修正したので確認をお願いします！Pageクラスのメソッドにする際、メソッド名を`find_by_○○`にするとrailsの動的に生成されるメソッド名と被ってしまうため`search_by`にしました。
https://rubydoc.info/gems/rubocop/0.47.1/RuboCop/Cop/Rails/DynamicFindBy

2021-07-01 04:37 UTC, komagata requested changes

2021-07-01 04:37 UTC, komagata commented on app/controllers/pages_controller.rb
> +    @page = Page.search_by_slug_or_id(params[:slug_or_id])
`find_by_slug_or_id`だとしても他のプログラマーにとっては思った通りの感じで動くのでむしろRailsのメソッドに似てる方が良いような気がします〜

search_xxxxは`LIKE`検索をするメソッドで使いがちな用語な気もするので。

2021-07-05 15:47 UTC, gozasoro commented on app/controllers/pages_controller.rb
> +    @page = Page.search_by_slug_or_id(params[:slug_or_id])
@komagata `find_by_○○`で`set_page`しようとするとrubocopのパターンに引っかかってしまうんですよね...
どうすればいいでしょうか？
https://rubydoc.info/gems/rubocop/0.47.1/RuboCop/Cop/Rails/DynamicFindBy

2021-07-07 13:26 UTC, komagata commented on app/controllers/pages_controller.rb
> +    @page = Page.search_by_slug_or_id(params[:slug_or_id])
@gozasoro なるほどです、ではそのままで大丈夫です〜

2021-07-08 03:17 UTC, komagata requested changes

2021-07-08 03:17 UTC, komagata commented on app/views/pages/show.html.slim
> +                    | #{@page.slug}
```suggestion
                    = @page.slug
```

2021-07-10 17:26 UTC, komagata requested changes
マージコミットができているようなので修正お願いします～

2021-07-11 16:06 UTC, gozasoro commented
@komagata `schema.db`がmainとコンフリクトしており、githubのwebページ上でコンフリクトを解消したため自動でマージコミットができてしまったみたいです（`ActiveRecord::Schema.define`の部分だけコンフリクトになってしまう）。
![image](https://user-images.githubusercontent.com/62997922/125199777-cacddb00-e2a2-11eb-9cc0-62e8d787b8cc.png)
先ほどマージコミットを修正してコンフリクトを解消する前の状態になったのですが、`schema.rb`のコンフリクトはどのように解消すればいいのでしょうか？
（mainと同じ`ActiveRecord::Schema.define`にしたところテストが落ちてしまったので元にもどしました）

2021-07-11 16:09 UTC, gozasoro commented on app/controllers/pages_controller.rb
> +    @page = Page.find_by(slug: params[:slug_or_id]) || Page.find(params[:slug_or_id])
> slugはアルファベットから始まるので、以下のように書くと `find_by` でまとめられそうかなと思いました。
> 
> `Page.find_by(...) || Page.find(...)` だとSQLが2回発行される事があるため、それよりも常に1回のSQLが発行される書き方の方がパフォーマンスが良いです。

@sinsoku わー！見逃してました💧参考になります！ありがとうございます！

2021-07-12 06:39 UTC, komagata commented
@gozasoro 新しい方を採用する必要があります。

2021-07-12 10:24 UTC, gozasoro commented
@komagata 現在のPRでは新しい方になっているので、確認をお願いしますー！

2021-07-13 13:44 UTC, komagata requested changes

2021-07-13 13:44 UTC, komagata commented on app/models/page.rb
> +    self.slug = nil if slug && slug.empty?
すみません、この場所僕もちょっと意味がわかってないです。
なんでnilを入れる必要があるんでしょう？

2021-07-13 17:22 UTC, gozasoro commented on app/models/page.rb
> +    self.slug = nil if slug && slug.empty?
@komagata slugカラムのバリデーションで`uniqueness: true`を付けています。`slug`を指定せずPageを作成or更新した際に`slug=""`となり、他のページでもslugを指定せずに作成・更新した場合に空文字が被ってしまいuniquenessバリデーションエラーとなってしまいます。そのため、指定しなかった場合は`nil`が入るようにしています（`allow_nil: true`としているため`nil`の場合はuniquenessに引っかからない）。

2021-07-14 14:15 UTC, komagata commented on app/models/page.rb
> +    self.slug = nil if slug && slug.empty?
@gozasoro なるほど、uniquenessのためですか、了解です〜

2021-07-14 14:16 UTC, merged

2021-07-14 14:21 UTC, gozasoro commented
ありがとうございますー！