Admin画面のカテゴリー一覧に一覧にページャーをつける
fjordllc/bootcamp pull request #2825
Opened 2021-06-11 04:32 UTC by Daichi831

issue #2808
# 概要
adminのカテゴリー一覧ページにページャーを付けました。
- 変更前
![image](https://user-images.githubusercontent.com/62867257/121630934-141ae700-cab9-11eb-8ddf-a41ca2186eb1.png)

- 変更後

![image](https://user-images.githubusercontent.com/62867257/121631102-6c51e900-cab9-11eb-91b8-cef454c324fe.png)

2021-06-11 04:34 UTC, Daichi831 commented
@kasai441 
こちらお時間があるときにレビューを宜しくお願いします🙇‍♂️

2021-06-11 08:05 UTC, kasai441 requested changes
上下にページャーが出ていることを確認しました！

ただ、データ数に応じてページャーが出ているかを確認するために、``test/system/announcements_test.rb``のshow paginationのような、テストを書いた方がいいと思いました。

2021-06-11 08:43 UTC, Daichi831 commented
@kasai441 
レビューありがとうございます！
確認のテストを追加し失敗と成功を確認しました！

2021-06-13 06:16 UTC, Daichi831 commented
@kasai441 
修正終わりましたので、お時間あるときに再レビューをお願いします🙇

2021-06-14 00:46 UTC, kasai441 approved these changes
確認しました〜OKですー

2021-06-14 00:46 UTC, kasai441 commented on test/system/admin/categories_test.rb
> +    26.times do
自分の手元でも確かめましたが、外部キーの絡みでCategory.delete_allができないみたいですね。ただし、ここは既存のデータが何個入っていても、25より多くデータを追加すればかならず上下にページャーが出ることが確かめられているのでOKっぽいですね！

2021-06-14 00:50 UTC, Daichi831 commented on test/system/admin/categories_test.rb
> +    26.times do
そうですね！
25個よりデータが多い場合に上下にページャーが確認できれば良いと思い、その部分は無くしました！

2021-06-14 00:51 UTC, Daichi831 commented
@komagata 
こちら確認を宜しくお願いします🙇‍♂️

2021-06-14 11:14 UTC, komagata commented
@Daichi831 これ、並び替えがおかしくなりそうなので、カテゴリーにはページャーつけない方がいいかもです。
僕が間違ったせいで無駄な作業をやらせてしまってすみません🙇‍♂️

2021-06-14 15:01 UTC, Daichi831 commented
@komagata 
承知しました！
こちらのPRはクローズすればよろしいでしょうか？

2021-06-15 04:45 UTC, komagata commented
@Daichi831 はい、すみません、こちらでCloseしておきます〜

2021-06-15 04:45 UTC, closed without merging

2021-06-15 04:50 UTC, Daichi831 commented
@komagata 
ありがとうございます〜