イベント個別ページのユーザーIDの後ろにユーザー名を追加
fjordllc/bootcamp pull request #2834
Opened 2021-06-14 04:49 UTC by yana-gi

issue: #2802

## 概要
イベント個別ページのユーザーIDの後ろにユーザー名も表示されるよう変更しました。

変更前
![スクリーンショット 2021-06-14 11 16 26](https://user-images.githubusercontent.com/67262644/121840379-0b275100-cd17-11eb-8fba-92ec6d3cac0c.png)

変更後
![スクリーンショット 2021-06-14 11 16 52](https://user-images.githubusercontent.com/67262644/121840363-02367f80-cd17-11eb-8d76-87f8b431e757.png)

2021-06-14 05:34 UTC, yana-gi commented
@alto-I 
こちらお手隙の際にレビューお願いします🙏

2021-06-14 10:54 UTC, alto-I approved these changes
@yana-gi 
確認しました！問題ないと思います！😄

2021-06-14 10:54 UTC, alto-I commented on test/system/events_test.rb
> +  end
テストもちゃんと追加していてgoodだと思います😊

2021-06-14 23:49 UTC, yana-gi commented
@alto-I
ご確認ありがとうございますー😊

@komagata 
こちらレビューお願いします🙏

2021-06-15 04:47 UTC, komagata requested changes

2021-06-15 04:47 UTC, komagata commented on test/system/events_test.rb
> +    visit event_path(event)
```suggestion
    login_user 'kimura', 'testtest'
    visit event_path(events(:event2))
```

一箇所でしか使ってなかったらこれでいいかもです〜

2021-06-15 08:04 UTC, yana-gi commented on test/system/events_test.rb
> +    visit event_path(event)
確かにそうですね！
「Commit suggestion」ボタンでCommitしたんですが、CIが通っていれば問題ないですかね……？

2021-06-16 05:03 UTC, yana-gi commented
@komagata 
こちら修正問題ないようでしたらマージお願いしますー🙏

2021-06-18 05:11 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-18 05:11 UTC, merged