メンターの提出物一覧の「未チェック」を「未完了」に変更
fjordllc/bootcamp pull request #2835
Opened 2021-06-14 06:46 UTC by Daichi831

issue #2811 

# 概要
管理者の提出物一覧の「未チェック」を「未完了」変更しました。
「未チェック」となっているボタンの箇所も同時に変更しました。
## 変更前
![image](https://user-images.githubusercontent.com/62867257/121849513-60b72a00-cd26-11eb-8cb8-8326b23fd9ee.png)
![image](https://user-images.githubusercontent.com/62867257/121849580-775d8100-cd26-11eb-91b7-217963a7a689.png)
![image](https://user-images.githubusercontent.com/62867257/121849625-85ab9d00-cd26-11eb-8f99-c9f26480b6b3.png)

## 変更後

![image](https://user-images.githubusercontent.com/62867257/121849443-4aa96980-cd26-11eb-96d5-f3a3dfddc8e2.png)
![image](https://user-images.githubusercontent.com/62867257/121849831-d3c0a080-cd26-11eb-81d5-7c57af21b73e.png)
![image](https://user-images.githubusercontent.com/62867257/121849879-e20ebc80-cd26-11eb-8a5b-dabb667690aa.png)

2021-06-15 00:50 UTC, Daichi831 commented
@gozasoro 
お時間あるときにレビューをお願いします！🙇‍♂️

2021-06-23 11:16 UTC, gozasoro requested changes
@Daichi831 遅くなってすみません！
レビューさせていただいたので、ご確認いただければと思いますー！

2021-06-23 11:26 UTC, Daichi831 commented on test/system/product/unchecked_test.rb
> +  end
そうですね！
「未チェックを未完了に名前変更した」
というより
「未完了と表示」
といったテスト名がいいですね！
show incompleteみたいなシンプルな名前にしてみようかと思います〜

2021-06-24 04:56 UTC, Daichi831 commented
@gozasoro 
こちら際レビューをお願いします！🙇‍♂️

2021-06-24 10:04 UTC, gozasoro approved these changes
確認しました！OKだと思います〜！

2021-06-24 10:34 UTC, Daichi831 commented
ありがとうございます😊

2021-06-25 05:08 UTC, Daichi831 commented
@komagata 
こちらレビューを宜しくお願いします🙇

2021-06-28 05:12 UTC, komagata requested changes
conflictの修正をお願いします〜

2021-06-28 10:19 UTC, Daichi831 commented
@komagata 
コンフリクト解消してみました！
確認、宜しくお願いします🙇‍♂️

2021-06-29 08:17 UTC, komagata requested changes

2021-06-29 08:17 UTC, komagata commented on test/system/product/unchecked_test.rb
> +    visit '/products'
```suggestion
    visit_with_auth '/products', 'advijirou'
```

すみません、この辺りもこっちでお願いします〜

2021-06-29 11:07 UTC, Daichi831 commented
こちら修正しました！
確認、宜しくお願いします！🙇‍♂️

2021-06-29 12:02 UTC, komagata requested changes

2021-06-29 12:02 UTC, komagata commented on test/system/product/unchecked_test.rb
> +    visit_with_auth 'products/unchecked', 'komagata'
```suggestion
    visit_with_auth '/products/unchecked', 'komagata'
```

2021-06-29 14:38 UTC, Daichi831 commented on test/system/product/unchecked_test.rb
> +    visit_with_auth 'products/unchecked', 'komagata'
何度もすみません🙇
こちら修正しました！

2021-06-30 11:49 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-30 11:49 UTC, merged