日報に確認とコメントがあった場合の通知の文言を変更
fjordllc/bootcamp pull request #2836
Opened 2021-06-14 07:01 UTC by obregonia1

2021-06-15 04:30 UTC, obregonia1 commented
@SeijiNumata 
こちらレビューお願いします！
コントローラーの記述が増えて汚くなってしまったのでアドバイスあればよろしくお願いします🙇‍♂️

2021-06-15 07:14 UTC, obregonia1 commented on app/controllers/api/notifications/unread_controller.rb
> +      notification.update(message: new_message, kind: 'check_and_comment', created_at: latest_notification + 3)
確認の通知の種類を `check_and_comment` にし、通知があったパスの最後の通知の作成日時を取得した値に3秒足して(これをしておかないと `unreads` メソッドで2つの通知を取得してしまうため)更新しています。

2021-06-15 09:10 UTC, SeijiNumata reviewed
@obregonia1 
確認しました！
コントローラーの記述が増えた問題は、下の方にprivateでメソッドを作ってあげてそこに書いてあげると綺麗になりそうです。

その他１点コメントしたのでご確認お願いします！

2021-06-15 16:19 UTC, ima1zumi commented on app/controllers/api/notifications/unread_controller.rb
> +      notification.update(message: new_message, kind: 'check_and_comment', created_at: latest_notification + 3)
こんにちは。別件で `Notification` を調査していて、openになっているPRがあったのでちょっとお邪魔します 💨 
このPRに至るまでの経緯は把握していないので、とんちんかんなことを言っていたら教えて下さい :pray:

通知の文言を変更するために `Notification` を `update` するのはちょっと危険かなと思います。

「確認」と「コメント」という `Notification` が何か変更されたわけではないのに `Notification` を `update` してしまうと、
あとからもともとの「確認」「コメント」というレコードが欲しくなった場合に取得する方法がなく、とても困ってしまいます。
また、この場合は「確認」か「コメント」どちらかだけが `update` されて、 もう片方の `kind` はそのままになるのは違和感があります。

ここで実現したいのは特定のパターンで表示するメッセージを変更することであって、`Notification` のDBのレコードを更新することではないのかな？と思いました。
表示する何かを変更したい場合は DB のレコードには手を入れないで、 DB からとってきた後のデータを書き換えたほうが安全かなと思います。

なので一旦必要な `Notification` を取得して、そのあとで表示するメッセージを変更したりするほうがDBに変更が入らなくてよいと思いました。:)
もしくは 「確認OKにする」のボタンが押された場合は `kind` を `check_and_comment` とする `Notification` を `create` するとか（ただのアイデアです）

2021-06-16 02:35 UTC, obregonia1 commented on app/controllers/api/notifications/unread_controller.rb
> +      notification.update(message: new_message, kind: 'check_and_comment', created_at: latest_notification + 3)
@ima1zumi 
コメントありがとうございます

> あとからもともとの「確認」「コメント」というレコードが欲しくなった場合に取得する方法がなく、とても困ってしまいます。
ここで実現したいのは特定のパターンで表示するメッセージを変更することであって、Notification のDBのレコードを更新することではないのかな？と思いました。

確かにそうですね。
自分の中でもあんまり納得できる実装ではなかったので、一度実装方針を駒形さんに質問してみようと思います！

2021-07-09 02:28 UTC, obregonia1 commented
@SeijiNumata 
仕様の変更があり、対応しましたので再度レビューよろしくお願いします。

2021-07-10 20:08 UTC, SeijiNumata commented
@obregonia1 
確認いたしました！
LGTMです！　駒形さんへレビュー依頼をお願いいたします🙇🏻

2021-07-10 23:22 UTC, obregonia1 commented
@SeijiNumata 
レビューありがとうございます！

@komagata 
こちらレビューよろしくお願いします！

2021-07-12 06:28 UTC, komagata requested changes

2021-07-12 06:28 UTC, komagata commented on test/system/notifications_test.rb
> +    visit "/reports/#{report}"
```suggestion
    visit_with_auth "/reports/#{report}", 'komagata'
```

2021-07-12 22:30 UTC, obregonia1 commented on test/system/notifications_test.rb
> +    visit "/reports/#{report}"
@komagata 
ヘルパーメソッドを修正したので再度確認お願いします。

2021-07-13 13:46 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-07-13 13:46 UTC, merged