Admin画面のユーザー一覧にページャーを付ける
fjordllc/bootcamp pull request #2847
Opened 2021-06-15 09:18 UTC by yana-gi

issue: #2807

## 概要
Admin画面のユーザー一覧にページャーを付けました。
どのターゲット（現役生・卒業生など）の画面でもページャーが表示されることを目視で確認済です。

![貼り付けた画像_2021_06_15_18_10](https://user-images.githubusercontent.com/67262644/122026308-09d45200-ce05-11eb-9940-29d91c6fbb29.png)

ユーザー画面下部にある「全員のメアド」には全ページのユーザーのメアドの一覧を表示させるようにしました。
（全員のメアドを表示させること、`@emails`のデータ取得を行う必要があることはkomagataさんとmachidaさんに確認済みです）

![貼り付けた画像_2021_06_15_18_11](https://user-images.githubusercontent.com/67262644/122026603-561f9200-ce05-11eb-98a6-420fdb324df5.png)

2021-06-15 13:42 UTC, yana-gi commented
@obregonia1 
こちらお手隙の際にレビューお願いします〜🙏

2021-06-15 23:29 UTC, obregonia1 reviewed
レビューしました！
一点だけコメントしています:memo:
テストユーザーの作成いい感じにできてますね👍

2021-06-15 23:29 UTC, obregonia1 commented on app/controllers/admin/users_controller.rb
> +    @emails = User.with_attached_avatar
`with_attached_avatar` は必要なさそうですねー。

2021-06-16 05:56 UTC, yana-gi commented on app/controllers/admin/users_controller.rb
> +    @emails = User.with_attached_avatar
確かにメアドの項目だけ取得しているのでアイコン画像はいらないですね！
ご指摘ありがとうございます🙏 修正しました〜

2021-06-16 06:25 UTC, yana-gi commented
@komagata 
こちらレビューお願い致します🙏

2021-06-16 06:30 UTC, obregonia1 commented on app/controllers/admin/users_controller.rb
> +    @emails = User.with_attached_avatar
修正ありがとうございますー！
いいと思います👍

2021-06-16 06:33 UTC, obregonia1 approved these changes

2021-06-18 05:15 UTC, komagata requested changes
管理画面ではブラウザの検索機能を使ってユーザーを見つけているので１ページ100件ぐらいの表示にしていただけるとありがたいです〜

2021-06-21 11:40 UTC, yana-gi commented
@komagata 
100件にする旨承知しました！

テストの仕方について確認させてください。
現在ページャーを表示するために26個のユーザーデータを作成しています。
1ページ100件の表示にするとなると、テストも101個以上のユーザーデータを作成することになりますが、テストの負荷や処理的に問題ないでしょうか？

2021-06-22 02:57 UTC, komagata commented
@yana-gi 問題ないです〜

2021-06-22 03:48 UTC, yana-gi commented
＠komagata

2021-06-24 01:39 UTC, komagata requested changes

2021-06-24 01:39 UTC, komagata commented on app/controllers/admin/users_controller.rb
> +                  .pluck(:email)
```suggestion
    @emails = User.users_role(@target).pluck(:email)
```

みたいな感じでいいと思います〜

2021-06-24 01:51 UTC, yana-gi commented on app/controllers/admin/users_controller.rb
> +                  .pluck(:email)
preloadもorder_by_countsも不要だったんですね。suggestion反映しました〜🙏

2021-06-24 02:07 UTC, yana-gi commented
@komagata 
こちら再度ご確認お願いします〜！

2021-06-28 05:07 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-28 05:07 UTC, merged