watch一覧でwatch解除できるようにする
fjordllc/bootcamp pull request #2848
Opened 2021-06-15 11:43 UTC by SeijiNumata

2021-06-15 12:38 UTC, SeijiNumata commented
@machida 

機能が全て完成したのですが、デザイン的に現在の状態で受講生、駒形さんにレビュー依頼をしていいか教えていただければ幸いです！

特にwatchを外すボタン等、如何でしょうか？
watchを外すボタンは詳細ページのwatchボタンと同じ部品を使っていて、一覧の時だけ「watch中」⇨「watchを外す」と文言を変更しています！

[![imagefromgyazo](https://gyazo.com/b709376a929d14db316d049d7a78132c.gif)](https://gyazo.com/b709376a929d14db316d049d7a78132c.gif)

2021-06-16 17:09 UTC, SeijiNumata commented
@obregonia1 
こちらよろしければレビューをお願いしたいです！
量が多かったのでwatch一覧をvueにしたところで、一旦駒形さんに見せてOKを頂いております。

五月雨式でもまとめてでも大丈夫ですので、よろしくお願いいたします！

2021-06-17 12:32 UTC, obregonia1 reviewed
レビューしました！
細かい部分ばかりですがコメントしてますー:memo:
あまり自信がない部分もコメントしているので、こちらが間違えていれば指摘お願いします🙏
余談ですが、補足がとても丁寧に書かれていてとてもいいと思いました！

2021-06-17 13:06 UTC, SeijiNumata commented on app/javascript/watches.vue
> +    nav.pagination
本当にそうですね。
忘れていました、ありがとうございます。

2021-06-17 13:07 UTC, SeijiNumata commented on app/javascript/watches.vue
> +      input(type='checkbox',v-model="checked")
ありがとうございます。修正しました。

2021-06-17 13:07 UTC, SeijiNumata commented on app/javascript/watches.vue
> +      checked:false,
ありがとうございます。修正しました。

2021-06-17 13:08 UTC, SeijiNumata commented on app/views/api/watches/_watch.json.jbuilder
> +json.summury searchable_summary(filtered_message(watch.watchable), 90)
気がついて下さりありがとうございます。
スペルミスでした。修正しました。

2021-06-17 13:08 UTC, SeijiNumata commented on app/javascript/watch.vue
> +            p {{ watch.summury }}
ありがとうございます。修正しました。

2021-06-17 13:08 UTC, SeijiNumata commented on test/integration/api/watchers_test.rb
> +# frozen_string_literal: true
確かにそうですね。ご指摘ありがとうございます。
修正しました。

2021-06-17 13:08 UTC, SeijiNumata commented on test/system/watchings_test.rb
> +    wait_for_vuejs
本当にそうですね。修正しました。

2021-06-17 13:09 UTC, SeijiNumata commented on app/controllers/api/watches/toggle_controller.rb
> +      watchable: params[:watchable_type].constantize.find_by(id: params[:watchable_id])
確かにそうでした。周りくどいことしてたのですが意味なかったです。
ありがとうございます。

2021-06-17 13:09 UTC, SeijiNumata commented on app/javascript/watch.vue
> +.thread-list-item(:class='[isWatchClassName]')
本当ですね、ありがとうございます。

2021-06-17 13:09 UTC, SeijiNumata commented on app/javascript/watch-toggle.vue
> +    watchIndexId: { type:Number, required: false, default:0 }
修正しました。ありがとうございます。

2021-06-17 13:24 UTC, SeijiNumata reviewed
@obregonia1 
レビューありがとうございます！
細かいところすごく抜けていたので、指摘していただき大変助かりました。

補足欄褒めていただきありがとうございます！

修正いたしましたので、お手数おかけしますが再度ご確認いただけると助かります。

よろしくお願いいたいます。🙇🏻

2021-06-17 13:24 UTC, SeijiNumata commented on app/javascript/watch-toggle.vue
> +          this.$emit('update-index', this.message)
こちらデバッグの時に使用していたものが残ってしまいました。
ありがとうございます。

2021-06-17 13:24 UTC, SeijiNumata commented on app/javascript/watch-toggle.vue
> +    push() {
その通りだと思います！
buttonClickに修正いたしました。

2021-06-17 13:24 UTC, SeijiNumata commented on app/controllers/api/watches_controller.rb
>    private
必要ありませんでした。
削除いたしました。

2021-06-17 13:24 UTC, SeijiNumata commented on app/javascript/watch.vue
> +    watchUser(){
試行錯誤していた時に残ってしまったものでした。
ありがとうございます。

2021-06-17 22:38 UTC, obregonia1 commented on app/javascript/watch-toggle.vue
> +          this.$emit('update-index', this.message)
なるほどー！ありがとうございます🙏

2021-06-17 22:56 UTC, obregonia1 commented on app/javascript/watches.vue
> +      input(type='checkbox',v-model="checked")
ここはv-modelの直前のスペースがないですー。

ちなみに最後のカンマはどちらでもいいと思うのですが、
```
foo = a,
         b
```
のように並んでいる場合だと、属性や要素が増えた時にdiffが
```
foo = a,
+       b,
+       c
```
ではなく
```
foo = a,
         b,
+       c,
```
のようにdiffの表示が減るというメリットがあるので今回の場合は必要なさそうです。

2021-06-17 22:56 UTC, obregonia1 commented on app/javascript/watches.vue
> +      checked:false,
ここもfalseの直前のスペースですね。

2021-06-17 23:16 UTC, obregonia1 approved these changes

2021-06-17 23:26 UTC, obregonia1 approved these changes
確認しました！OKだと思います🙆‍♂️
何箇所か見落としていた箇所があったようですが、修正されていましたね👏
ちなみにインデントは「行頭」に空白やスペースやタブ文字を挿入するという意味なので一応伝えておきます:memo:
PRの作り方含めて勉強になりました！ありがとうございましたー！

2021-06-18 08:21 UTC, SeijiNumata commented
@obregonia1 
ご確認ありがとうございます！非常に勉強になりました！
そうなんですね、インデントの意味を勘違いしていました！教えていただきありがとうございます！

@komagata 
こちら受講生の方からOKを頂きましたので、ご確認お願いいたします。

2021-06-22 02:35 UTC, komagata requested changes
テストが通っていないようです〜

2021-06-22 08:36 UTC, SeijiNumata commented
@komagata 
再実行したら全て通りました！
ご確認よろしくお願いいたします！

2021-06-24 01:45 UTC, komagata requested changes
コミットにマージコミットがたくさんできているようなので、修正してみてください〜

2021-06-26 12:08 UTC, SeijiNumata commented
@komagata 
コミットを修正しました〜
ご確認お願いします！

2021-06-28 05:21 UTC, komagata requested changes

2021-06-28 05:21 UTC, komagata commented on app/controllers/api/watches/toggle_controller.rb
> +    @watch.save!
```suggestion
    @watch = Watch.create!(
      user: current_user,
      watchable: watchable
    )
```

こう書くのと同じかもです〜

2021-06-28 05:21 UTC, komagata commented on app/javascript/watches.vue
> +    },
```suggestion
    }
```

2021-06-28 05:21 UTC, komagata commented on app/views/api/watches/index.json.jbuilder
> +    json.partial! "api/watches/watch", watch: watch
```suggestion
    json.partial! 'api/watches/watch', watch: watch
```

2021-06-28 05:21 UTC, komagata commented on db/fixtures/watches.yml
> +
```suggestion
<% 2.upto(10).do |i| do %>
report<%= i %>_watch_kimura:
   user: kimura
   watchable: report<%= i %> (Report)

<% end %>
```

2021-06-29 08:19 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-29 08:19 UTC, merged

2021-06-29 17:13 UTC, SeijiNumata commented
ありがとうございます！！