Q＆Aと日報一覧の自分の所属しているコースに紐付いているプラクティスだけが表示されるように
fjordllc/bootcamp pull request #2855
Opened 2021-06-16 02:46 UTC by kasai441

Issue
#1943

以下確認ポイントになりますー(Q&Aと日報一覧それぞれ)
画面はIssueのスクショを参照ください。

- セレクトボックスの内容がプラクティス一覧と一致
- テストではコースごとに絞り込んだプラクティスの数のみ検査（順序は見ない）
- users_helperにコースに紐づくプラクティスを返すメソッドを追加しています←各場所が適切ですか？？

2021-06-18 07:17 UTC, kasai441 commented
Ruby / test (2.6)が通っていませんが、
https://discord.com/channels/715806612824260640/809595476847493192/855309490361991248
discordにて駒形さんが無視していいとのことなのでレビューに進みます。

2021-06-18 07:18 UTC, kasai441 commented
@Daichi831 
こちらお時間あればレビューお願いできますか

2021-06-18 07:22 UTC, Daichi831 commented
@kasai441 
了解しました！
今日中には確認できると思います！

2021-06-18 21:13 UTC, Daichi831 commented
すみません、昨日中と言っておきながら今日中になりそうです🙇

2021-06-19 04:24 UTC, Daichi831 commented
おお〜日報一覧とQ&Aに自分のプラクティスだけが表示されるようになったんですね！

僕の環境でも確認しました！okだと思います！
> users_helperにコースに紐づくプラクティスを返すメソッドを追加しています←コードの書く場所が適切でしょうか？？

ユーザーに紐付いたプラクティスを返すメソッドなのでusers_helperでも大丈夫かな！と思いました！

1点質問なのですがユーザーに紐付いたプラクティスが表示されているか確認したところ、プラクティスのカテゴリーの順番は合っているのですがカテゴリー内の順番が少しずれている？箇所がありましたがkasaiさんの環境では順番通りになっている感じでしょうか💦
![image](https://user-images.githubusercontent.com/62867257/122630778-4784f380-d101-11eb-8a2f-f1049281ffb8.png)
![image](https://user-images.githubusercontent.com/62867257/122630787-5ec3e100-d101-11eb-9092-3066eda8ad12.png)

2021-06-19 04:37 UTC, Daichi831 approved these changes

2021-06-20 12:20 UTC, sinsoku commented on app/helpers/users_helper.rb
> +    user.course.categories.order(:position).map(&:practices).flatten
[flat_map](https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/collect_concat.html) の方が少し短くなる ⛳ 

```suggestion
    user.course.categories.order(:position).flat_map(&:practices)
```

2021-06-21 01:40 UTC, kasai441 commented
> 1点質問なのですがユーザーに紐付いたプラクティスが表示されているか確認したところ、プラクティスのカテゴリーの順番は合っているのですがカテゴリー内の順番が少しずれている？箇所がありましたがkasaiさんの環境では順番通りになっている感じでしょうか💦

レビューありがとうございます！

こちらの環境ではプラクティスの順番もあっているようです。少し気になるのでスクショをとったURLをおしえてもらえますか。

2021-06-21 01:55 UTC, kasai441 commented
あと、ブラウザとOS, rubyとrailsのバージョンなども軽く知りたいです。

こちらのローカル
ブラウザ: Chrome
OS: Mac
ruby: 2.6.6
rails: 6.1.3.2

2021-06-21 02:09 UTC, Daichi831 commented
こちらのローカルは
ブラウザ: Chrome
OS: Mac
ruby: 2.6.6
rails: 6.1.3.2
です〜

すみません！順番合ってました！
ローカルで2画面で別々のユーザーで確認していたのですがそれがおかしかったみたいです...

2021-06-21 02:13 UTC, kasai441 commented
> すみません！順番合ってました！
> ローカルで2画面で別々のユーザーで確認していたのですがそれがおかしかったみたいです...

さっそくありがとうございますー。よかったです😀

2021-06-21 02:14 UTC, Daichi831 commented
お手数おかけしました🙇‍♂️

2021-06-22 00:41 UTC, kasai441 commented
@komagata 
こちら、コードレビューお願いしますー

2021-06-22 03:00 UTC, komagata requested changes

2021-06-22 03:00 UTC, komagata commented on app/helpers/users_helper.rb
> +  def user_practices(user)
この内容だったらUserモデルに実装した方がいいかもです〜

2021-06-22 05:55 UTC, kasai441 commented on app/helpers/users_helper.rb
> +  def user_practices(user)
> この内容だったらUserモデルに実装した方がいいかもです〜

@komagata 
変更しましたー、モデルなので名前とロジックをシンプルにしましたがいかがでしょうか

2021-06-24 01:42 UTC, komagata requested changes

2021-06-24 01:42 UTC, komagata commented on app/models/user.rb
> +    course.categories.order(:position).flat_map(&:practices)
flat_mapだとruby側での処理になるので、SQL側の処理だけでデータを持ってきた方が早いので試してみてください〜。

（いきなりrubyで書かずに、SQLでどう書けばいいのかpsqlなどで試してからそれをActiveRecordでの書き方に変えるといいかもです〜）

2021-06-25 02:45 UTC, kasai441 commented
@komagata 
テーブルの関連付けを利用してSQLだけで絞り込み＆順番をつけることができました。
discordで質問して聞いたのですが、下記のように明示的にjoinをつけるほうが好ましい場合もあるとのことでした。（返ってくる結果は同じ）
```ruby
course.practices.joins(:categories).order('categories.position', 'practices.position')
```
この場合、SQLが少し複雑になるので、私はjoinをつけない形で実装しましたがいかがでしょうか。

2021-06-28 05:10 UTC, komagata commented
@kasai441 DBからデータを取ってくる速度を測って、同じだったらjoins書かなくてもいいと思います。
joinsを書いた方が速いならそちらにしたいです。

2021-06-28 06:43 UTC, kasai441 commented
@komagata 
joinなしの方が早そうです。下記のコードをrails consoleで５、６回実行しましたが同じような結果となりました。
```ruby
require 'benchmark'

course = User.first.course

Benchmark.bm 10 do |r|
  r.report "joinあり" do
    course.practices.joins(:categories).order('categories.position', 'practices.position')
  end
  r.report "joinなし" do
    course.practices.order('categories.position', 'practices.position')
  end
end
```

```
                 user     system      total        real
joinあり       0.000913   0.000023   0.000936 (  0.000935)
joinなし       0.000276   0.000025   0.000301 (  0.000301)
```

2021-06-28 06:53 UTC, kasai441 commented
試行回数を増やしてやり直しました。これも５、６回実行しましたが、わずかにjoinなしの方が早い、ほぼ同じという感じです。
```ruby
require 'benchmark'

course = User.first.course

num_iteration = 10000

Benchmark.bm 10 do |r|
  r.report "joinあり" do
    num_iteration.times do
      course.practices.joins(:categories).order('categories.position', 'practices.position')
    end
  end
  r.report "joinなし" do
    num_iteration.times do
      course.practices.order('categories.position', 'practices.position')
    end
  end
end
```

```
                 user     system      total        real
joinあり       2.552252   0.013602   2.565854 (  2.594010)
joinなし       2.505438   0.016112   2.521550 (  2.553610)
```

2021-06-29 08:12 UTC, komagata commented
@kasai441 ありがとうございます。ではjoinなしでお願いします〜

2021-07-06 01:12 UTC, kasai441 commented
@komagata 
こちら、修正おわって放置してしまっていたので、レビュー確認おねがいしますー

2021-07-08 03:40 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-07-08 03:40 UTC, merged