ユーザーのdescriptionがnilの場合「*自己紹介文はありません*」と挿入する
fjordllc/bootcamp pull request #2859
Opened 2021-06-18 00:54 UTC by Daichi831

issue #2798 
# 概要
現在ユーザーの中には自己紹介欄がnilの方がいます。
以前はnilの許可されていましたが現在はバリデーションで許可されていないためnilの方には「*自己紹介文はありません*」という文言を挿入するようにしました。

自己紹介欄がnilのユーザーを作成しrake taskを実行すると「*自己紹介文はありません*」というデータが挿入されることを確認しました！
![貼り付けた画像_2021_06_18_9_52](https://user-images.githubusercontent.com/62867257/122489659-1d590600-d01b-11eb-937d-9b03eaed8458.png)

2021-06-18 02:25 UTC, Daichi831 commented
@harukus
すみません、こちらお時間があるときにレビューをよろしくお願いします🙇

2021-06-19 00:40 UTC, harukus approved these changes
自分はOKだと思いますー🙆‍♀️
質問なのですがなぜ`each`を使用せず`find_each`を使っているのか聞きたいです🙇‍♀️

2021-06-19 03:40 UTC, Daichi831 commented
find_eachだと1000件ずつ処理を行うらしくデータが多いときはfind_eachの方が良いのかな〜と思いました！
先輩方で同じような処理を書いているときにもfind_eachを使用してたのでこちらを採用しました💦

2021-06-20 12:10 UTC, sinsoku commented on db/data/20210616072230_add_empty_string_to_nil_description.rb
> +    end
[update_all](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update_all) を使えばSQL 1回で済むため、高速に処理が終わらせることができます。
今回のように単に値を挿入するだけであれば、 `update_all` でも問題ないかなと思いました。

```suggestion
    now = Time.current
    User.where(description: nil).update_all(description: '自己紹介文はありません。', updated_at: now)
```

## update_all の注意点

update_all はモデルのバリデーションやコールバック処理を実行しません。

> It does not instantiate the involved models and it does not trigger Active Record callbacks or validations.
> APIドキュメントから引用

ActiveRecord が `updated_at` を更新する処理も動かないため、上記のコード例でも自分で設定しています。

2021-06-21 02:15 UTC, Daichi831 commented
update_allを使うとSQL1回ですむんですね！
確かに今回は値を挿入するだけなのでこちら修正してみます！

2021-06-21 02:40 UTC, Daichi831 commented on db/data/20210616072230_add_empty_string_to_nil_description.rb
> +    end
update_allを使って書き直してみましたがupdate_allを使っているとrubocopに引っかかってしまうみたいです💦

2021-06-22 03:51 UTC, harukus commented
> ありがとうございます😊
> find_eachだと1000件ずつ処理を行うらしくデータが多いときはfind_eachの方が良いのかな〜と思いました！
> 先輩方で同じような処理を書いているときにもfind_eachを使用してたのでこちらを採用しました💦

なるほどです！ありがとうございます！！

2021-06-23 00:45 UTC, Daichi831 commented
@komagata
こちらレビューを宜しくお願いします🙇

2021-06-24 01:37 UTC, komagata requested changes

2021-06-24 01:37 UTC, komagata commented on db/data/20210616072230_add_empty_string_to_nil_description.rb
> +        user.save!
```suggestion
      user.update!(description: '') if user.description.nil?
```

空文字`''`を入れるようにお願いします〜

2021-06-24 01:52 UTC, machida commented on db/data/20210616072230_add_empty_string_to_nil_description.rb
> +        user.save!
@komagata 

> 空文字''を入れるようにお願いします〜

空文字だとバリデーションに通らないことがわかったので、`自己紹介文はありません。` に変更してもらいました。
https://github.com/fjordllc/bootcamp/issues/2798#issuecomment-863007186

2021-06-24 01:55 UTC, komagata commented on db/data/20210616072230_add_empty_string_to_nil_description.rb
> +        user.save!
@Daichi831 @machida なるほど、すみません、そちらの文言のままで大丈夫です〜

2021-06-24 04:50 UTC, Daichi831 commented on db/data/20210616072230_add_empty_string_to_nil_description.rb
> +        user.save!
承知しました！
再度レビューをお願いします！

2021-06-28 05:08 UTC, komagata requested changes

2021-06-28 05:08 UTC, komagata commented on db/data/20210616072230_add_empty_string_to_nil_description.rb
> +        user.save!
@Daichi831 文言はそのままで大丈夫ですが、コードの方の修正はお願いいたします〜

2021-06-28 06:32 UTC, Daichi831 commented
@komagata 
修正しました！確認お願いします！

2021-06-29 07:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-29 07:00 UTC, merged