イベント一覧ページで投稿者の名前が表示されるようにした
fjordllc/bootcamp pull request #2869
Opened 2021-06-21 07:02 UTC by Daichi831

issue #2804 

# 概要
イベント一覧ページにイベント投稿者の名前が表示されるようにしました！

## 変更前
![image](https://user-images.githubusercontent.com/62867257/122719691-8655ad80-d2a9-11eb-9ff1-1e12f8e1d9b5.png)

## 変更後
![貼り付けた画像_2021_06_21_16_00](https://user-images.githubusercontent.com/62867257/122720075-f7956080-d2a9-11eb-8efd-b641918693c2.png)

2021-06-21 09:33 UTC, Daichi831 commented
@udaikue 
こちらお時間あるときにレビューをお願いします！🙇‍♂️

2021-06-21 12:12 UTC, udaikue approved these changes
良いと思います！テストがちゃんと書かれてて素晴らしいです✨

2021-06-28 03:18 UTC, Daichi831 commented
@komagata 
こちらレビューを宜しくお願いします🙇

2021-06-28 05:28 UTC, komagata requested changes

2021-06-28 05:28 UTC, komagata commented on app/views/events/_events.html.slim
> +            | #{event.user.long_name}
```suggestion
            = event.user.long_name
```

2021-06-28 05:28 UTC, komagata commented on app/views/events/_events.html.slim
> +            span
このspanって必要なやつですか？

2021-06-28 06:21 UTC, Daichi831 commented on app/views/events/_events.html.slim
> +            span
すみません、不要だったので削除しました！

2021-06-28 06:22 UTC, Daichi831 commented on app/views/events/_events.html.slim
> +            | #{event.user.long_name}
こちら書き直してみました！

2021-06-28 06:34 UTC, Daichi831 commented
@komagata 
修正しましたので確認をお願いします！

2021-06-29 08:08 UTC, komagata requested changes

2021-06-29 10:27 UTC, Daichi831 commented on test/system/events_test.rb
> +    assert_text 'komagata (Komagata Masaki)'
すみません💦
個別ページのテストと一緒に書いていたので個別ページと一覧ページのテストに分けました！
内容もミーティングの際にお話しされた書き方に変更しました！

2021-06-29 11:00 UTC, Daichi831 commented
こちら修正しました！
確認、宜しくお願いします！🙇‍♂️

2021-06-29 11:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-29 11:52 UTC, merged