ユーザ登録時に入力したタグを保存されないバグ修正
fjordllc/bootcamp pull request #2876
Opened 2021-06-24 00:55 UTC by kasai441

Issue #2865

![image](https://user-images.githubusercontent.com/50036730/123185983-1bd38600-d4d2-11eb-91f3-2464362cc393.png)

controllerを直したところ動作しました。

2021-06-28 01:36 UTC, kasai441 commented
## VCRとstripeの調査
https://bootcamp.fjord.jp/reports/33391

stripeではテスト初回時に飛ばされるリクエストでstripe側にEmailが登録されてしまうので、同じEmailで同じテストを2度目に行うと重複エラーとなります。

そのため、1度目に飛ばしたリクエストとレスポンスをyamlファイルに保存できるVCRというライブラリを使用します。2回目以降のテストは実際にリクエストを飛ばさず、yamlファイルの内容を反映します。そのため、テストに付随するyamlファイルもGitで管理する必要があります。

## VCRの一度のみ書き込み設定
現状ではsign_up_testのVCRではデフォルト設定で、実行のたびにyamlファイルが追記される設定になっているようです。そのため各ローカルで開発者がテスト実行するとyamlが変更され混乱の要因になると思われます。

この対策として、一度yamlファイルが作成されたら追記を行わない設定を行いました。

[VCRを使って開発中にあほみたいにリクエストを飛ばさないようにする \- かずおの開発ブログ\(主にRuby\)](https://kazuooooo.hatenablog.com/entry/2015/12/05/225708)
[VCRのmatch\_requests\_onを変更する \- Qiita](https://qiita.com/ledsun/items/5494df3f93f5fb0b765b)

記事に書かれている通り:bodyを設定しても同じリクエストと判定されない、というエラーが返ってきます。そこで、:methodと:urlのみ設定したところ、判定が甘くなり、ymlに追記せずに再利用することができるようになりました。
```ruby
VCR.use_cassette 'sign_up/tag', record: :once, match_requests_on: %i[method uri] do
    ...
end
```

2021-06-28 01:40 UTC, kasai441 commented
@obregonia1 

レビューを是非お願いしたいのですがいかがでしょうか。

2021-06-29 02:24 UTC, obregonia1 approved these changes
レビューしました！OKだと思います🙆‍♂️

2021-06-29 02:28 UTC, kasai441 commented
@obregonia1 
ありがとうございますー
@komagata 
レビューお願いします。
VCRの設定について、既存のsign_up_testと少し違うので特にここについてご確認お願いします。（詳しくは上のコメント）

2021-06-29 11:49 UTC, komagata requested changes

2021-06-29 11:49 UTC, komagata commented on test/system/sign_up_test.rb
> +      visit user_path(user)
```suggestion
      visit_with_auth user_path(user), 'taguo'
```

すみません、ミーティングで話したこちらでお願いできれば〜

2021-06-30 02:04 UTC, kasai441 commented
@komagata 
変更反映しましたー

2021-07-01 04:45 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-07-01 04:45 UTC, merged

2021-07-05 07:04 UTC, kasai441 commented
@komagata 
本番環境での確認がこちらではむずかしいため、お願いします...!

2021-07-08 03:07 UTC, komagata commented
@kasai441 本番環境でタグ登録済みの新規ユーザーが見られたのでそれを持って確認とさせていただければと思います〜。