ニコニコカレンダーをvue.jsにし、月ごとの表示にして、ページャーを付けた
fjordllc/bootcamp pull request #2886
Opened 2021-06-26 05:44 UTC by obregonia1

2021-06-26 06:21 UTC, obregonia1 commented
@kasai441 
こちらレビューよろしくお願いしますー🙏

2021-06-28 05:35 UTC, kasai441 commented
@obregonia1 
了解しましたー

2021-06-30 10:36 UTC, obregonia1 commented
@kasai441
Lintを通し忘れていたので少し修正しています🙏

2021-07-01 06:54 UTC, kasai441 reviewed
@obregonia1 

レビュー完了しました。カレンダーちゃんと動くのですごいですね！問題ないかと思いますー

細かい点ばかりコメントしています。Vue.jsもJSも不明な点が多く、間違った指摘となっているかもしれませんが、感想レベルでご覧ください。

- コメント以外で気になった点

カレンダーをめくってリンクから日報に遷移した後、ブラウザバックすると最新の月に戻ってしまうのは、ユーザビリティが低そうです。が、少し調べた感じでは、これを直すのは難しそうなので、今後の拡張案として言及するだけに留めておきます。

2021-07-01 06:59 UTC, kasai441 commented
すみません、一点追記です。
テストのlogin_userはvisit_with_authに差し替えとなっています。

2021-07-03 01:29 UTC, obregonia1 commented on app/decorators/user_decorator.rb
> -    reports_date_and_emotion = self.reports_date_and_emotion(CALENDAR_TERM)
見落としてました。ありがとうございます！

2021-07-03 01:29 UTC, obregonia1 commented on app/decorators/user_decorator.rb
> -    [*blanks, *reports_date_and_emotion].each_slice(DAYS_IN_WEEK)
こちらも見落としてましたー。

2021-07-03 02:00 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +      this.calendarSquares.forEach(function (date, i, ary) {
確かにそうですね。変更しました。

2021-07-03 02:02 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +        }
なるほど、勉強になります:memo:

2021-07-03 02:28 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +            Number(report.reported_on.split('-')[2]) === date))) {
確かに読みにくいですね！resultの代入を分け、日報の日付を取得するメソッドを追加しました。

2021-07-04 08:15 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +      let weekIndex = 1
これは全く気付いてなかったので助かります！
提案してくれたコードだと変数の意味合いが変わってしまいそうなので`$nextTick`で実装しました。

2021-07-04 08:18 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +    calendarWeeksAry() {
確かにそうですね〜。変更しました。

2021-07-04 08:40 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +    calendarSquares() {
nullを含めた配列だったのでカレンダーのマスの意味合いをでsquareにしてたんですが、dateの方がわかりやすそうですね。

2021-07-04 08:42 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +                  img.niconico-calendar__emotion-image(
今の仕様だとemotionがnullの日報は作れないので特に対応しなくてもいいかなと思いました。

2021-07-04 08:55 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +      | ロード中
これも気付いていませんでした。
日報がない場合の文言を表示するようにしました。

2021-07-04 09:16 UTC, obregonia1 commented
@kasai441 
> カレンダーをめくってリンクから日報に遷移した後、ブラウザバックすると最新の月に戻ってしまう

この仕様も未確認でした。これは特に要件にはなかったので新たにIssueを立てておこうと思います！
指摘された点修正したので再度レビューよろしくお願いします🙇‍♂️

2021-07-05 01:04 UTC, kasai441 reviewed
変更点確認、動作確認しましたー、OKですー
``$nextTick``だと、可読性もよくていいですね！

2021-07-05 01:19 UTC, obregonia1 commented
@kasai441 
ありがとうございます！
approveされていないみたいなのでよろしくお願いします🙇‍♂️

@komagata 
こちらレビューよろしくお願いします🙇‍♂️

2021-07-05 01:21 UTC, kasai441 approved these changes

2021-07-05 12:05 UTC, komagata requested changes
conflictの修正お願いします〜

2021-07-05 23:49 UTC, obregonia1 commented
@komagata 
conflict解消したのですが、町田さんにデザイン依頼し忘れていたので先にデザインをお願いしようと思います。

@machida 
`app/javascript/niconico_calendar.vue`のデザインよろしくお願いします🙇‍♂️

2021-07-05 23:50 UTC, obregonia1 commented on app/javascript/niconico_calendar.vue
> +          ) >
@machida 
デザイン必要な部分です。

2021-07-13 08:53 UTC, machida commented
@komagata @obregonia1 デザイン入れましたー

2021-07-13 09:19 UTC, obregonia1 commented
@machida 
ありがとうございます！

@komagata 
こちらレビューよろしくお願いします！

2021-07-13 13:56 UTC, komagata requested changes

2021-07-13 13:56 UTC, komagata commented on app/javascript/niconico_calendar.js
> +  const niconicoCalendar = document.getElementById('js-niconico_calendar')
15行目とselectorが2回書かれているので変数に入れて共通化すると良さそうです〜

2021-07-13 13:56 UTC, komagata commented on app/javascript/niconico_calendar.vue
> +</style>
不要なら削除しちゃってください〜

2021-07-13 22:34 UTC, obregonia1 commented
@komagata 
指摘された点修正したので再度確認お願いしますー。

2021-07-14 14:19 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-07-14 14:19 UTC, merged

2021-07-14 22:44 UTC, obregonia1 commented
@komagata 
ありがとうございます！
これでチーム開発で割り振られたIssue全て完了になりました🙌
とても勉強になりました〜✍️

2021-07-15 05:07 UTC, komagata commented
@obregonia1 おおお〜、おめでとうございます！お疲れ様でした〜！！