ユーザーアイコンをhoverしたときに名前も表示させるよう変更
fjordllc/bootcamp pull request #2888
Opened 2021-06-27 13:27 UTC by udaikue

issue #2806

ユーザーアイコンをhoverしたときに、ユーザーIDに加えて名前も表示させるように変更しました。

## 変更前
<img width="429" alt="スクリーンショット 2021-06-27 22 23 41" src="https://user-images.githubusercontent.com/58643754/123546272-dbf0f500-d796-11eb-84b9-550a238280cb.png">

## 変更後
<img width="426" alt="スクリーンショット 2021-06-27 21 53 59" src="https://user-images.githubusercontent.com/58643754/123546281-e612f380-d796-11eb-8766-a40e69868f12.png">

2021-06-27 22:59 UTC, udaikue commented
@gallardo16 お時間あるときにレビューをお願いします🙏

2021-06-28 00:48 UTC, gallardo16 approved these changes
確認致しました。OKだと思います🙆‍♂️

2021-06-28 09:33 UTC, udaikue commented
@gallardo16 ありがとうございました！

@komagata こちらレビューをお願いします🙏

2021-06-29 08:15 UTC, komagata requested changes

2021-06-29 08:15 UTC, komagata commented on app/decorators/user_decorator.rb
> +                                   .join(': ')
名前の場所で表示されてるのと同じフォーマットの方がいいかもと思いました〜

`komagata (Masaki Komagata)`みたいな。

2021-06-29 14:39 UTC, udaikue commented on app/decorators/user_decorator.rb
> +                                   .join(': ')
@komagata たしかにその方がいいと思い修正しました。再度ご確認お願いします🙏

2021-06-30 11:51 UTC, komagata requested changes

2021-06-30 11:51 UTC, komagata commented on app/decorators/user_decorator.rb
> +    #                                .join(': ')
過去のコードは全てgitで残っているので、コメントアウトして残すといったことは不要なので削除しちゃってください〜

2021-06-30 11:51 UTC, merged

2021-06-30 12:35 UTC, udaikue commented on app/decorators/user_decorator.rb
> +    #                                .join(': ')
@komagata すみません削除し忘れておりました🙇