ユーザータグの詳細で「このタグを自分から外す」ボタンの導入
fjordllc/bootcamp pull request #2892
Opened 2021-06-28 06:22 UTC by kasai441

Issue #2778

2021-07-01 07:52 UTC, kasai441 commented
@yana-gi 
こちら、レビューお願いできるでしょうか？

2021-07-05 02:15 UTC, yana-gi reviewed
レビュー遅くなってしまいすみません……！
1点だけ気になったところがあったので質問させていただきました。

コードとは関係ないですが、PullRequestのコメントにissue番号だけでなく概要や変更前後のスクリーンショットがあるとレビューする側としてはありがたいです！
レビューする側が助かるだけではなく、書いておくとリリースノートに流用できるのでkasai441さんも便利になると思います〜

2021-07-05 02:15 UTC, yana-gi commented on config/routes.rb
> -
ここの改行を削除した理由などあれば知りたいです！

2021-07-05 02:29 UTC, kasai441 commented on config/routes.rb
> -
色々いじっているうちに消してしまったもので、特に理由はありませんー

2021-07-05 02:29 UTC, kasai441 commented
概要欄直しましたー

2021-07-05 02:51 UTC, yana-gi commented on config/routes.rb
> -
であれば削除する前の状態に戻したほうがいいと思います！

2021-07-05 02:57 UTC, kasai441 commented
@yana-gi 
直しましたー

2021-07-05 07:13 UTC, yana-gi approved these changes
@kasai441 
コードとPRの修正ありがとうございます！
大丈夫だと思います〜👍

2021-07-05 07:14 UTC, kasai441 commented
@yana-gi 
ありがとうございますー🙏
@komagata 
こちらレビューをお願いしますー🙇🏻‍♂️

2021-07-05 12:12 UTC, komagata requested changes

2021-07-05 12:12 UTC, komagata commented on test/system/user/tags_test.rb
> +    %i[cat shinjuku_rb neovim_v_zero_five_zero _net_framework may_j_].each do |key|
systemテストにおけるvisit（ページ遷移）はmodelテストの何十倍もコストがかかるので、必要でなければ最小限のデータで試していただけるとありがたいです〜。

2021-07-06 01:09 UTC, kasai441 commented
@komagata 
テストの内容、コンパクトにしましたー

2021-07-08 03:39 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-07-08 03:39 UTC, komagata commented
@machida こちらデザインの確認お願いします〜

2021-07-13 08:07 UTC, machida commented
こちらデザイン入れたので、テストが通ったらマージしますー

2021-07-13 15:23 UTC, merged

2021-07-13 15:24 UTC, machida commented
@kasai441 マージしました🎉