すべてのユーザーがQ&Aのタグを編集できるように変更
fjordllc/bootcamp pull request #2893
Opened 2021-06-28 07:35 UTC by udaikue

issue #2149

質問者本人かadminでなければQ&Aのタグ編集ができなかったのを、すべてのユーザーが編集できるように変更しました。

## 変更前
![テストの質問___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/58643754/123597440-4f921100-d82e-11eb-8aa6-b26ea3a22756.png)

## 変更後
![テストの質問___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/58643754/123597653-91bb5280-d82e-11eb-8dbc-c8abe211390a.png)

2021-06-28 09:28 UTC, udaikue commented
@harukus お手すきのときにレビューをお願いします🙏

2021-06-30 07:42 UTC, harukus commented
@udaikue 
かしこまりました！もう少しお待ちください！

2021-06-30 07:57 UTC, harukus requested changes
こちら手元で`ログインユーザー：kimura`で試したところ、リロードすると保存したタグが消えてしまいます。
ちなみにadminで編集した場合はしっかりと保存されていました！
ご確認ください！
↓GIF`ログインユーザー：kimura`
[![Image from Gyazo](https://i.gyazo.com/31dbdc2e7629bc5b99b21e8c2628e413.gif)](https://gyazo.com/31dbdc2e7629bc5b99b21e8c2628e413)

2021-07-06 00:21 UTC, udaikue commented
@harukus ご確認&ご指摘ありがとうございます!!失礼しました。。

@machida お聞きしたいのですが、手元でadminで試してみたところ、リロードするとタグが保存されませんでした。
(harukusさんはadminだと保存されている、とのことですが)

![f9eb194e2aecffe9e61b349e516debb6](https://user-images.githubusercontent.com/58643754/124525576-be78f680-de3a-11eb-8ba5-ff12530a0825.gif)

user: komagataでログインした状態です。
![Cursor_と_未解決の質問一覧___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/58643754/124525589-c9cc2200-de3a-11eb-910c-74ea62928abd.png)

何かやり方が間違っていますか...?

2021-07-06 01:01 UTC, machida commented
@udaikue お、これはやり方がまちがってるのではなくバグっぽいですね。

2021-07-06 01:03 UTC, machida commented
@harukus @udaikue こちらadminでも保存されてないのかもしれないです。本番で試してみますー

2021-07-06 01:51 UTC, udaikue commented
@machida 早速ありがとうございます！お願いしますー

2021-07-06 01:59 UTC, machida commented
@udaikue @harukus 本番ではAdminでタグを編集して保存されてました！！

@udaikue
一度サーバをストップして、yarn install してから立ち上げて同じ動作をやっていただけますでしょうか？
もしかしたら解決するかも。

2021-07-06 02:39 UTC, obregonia1 commented
@udaikue 
おそらくタグが保存されない理由は2つほどありますね。
- 一般ユーザーでタグを保存してみるとブラウザのコンソールでエラーを吐いているのでこれを参考にするといいと思います。
- タグを保存する際に、「文字を入力 -> 保存するをクリック」すると見かけ上は保存されていますが、リロードして消えてしまうことからわかるようにDBには保存されていません。これは「文字を入力 -> エンターキーを押下 -> 保存するをクリック」で保存すると解決できます。
「文字を入力 -> 保存するをクリック」すると見た目上保存されているのはあまりよくない仕様だと思いますが、少し対応するのが大変そうなので別のIssueを立ててもいいと思います。

2021-07-06 02:54 UTC, machida commented
@obregonia1 なるほど！入力後エンターキーを押さなくても保存を押すとタグに見えてしまうという別のバグがありましたか！！調査ありがとうか🙏

2021-07-06 04:31 UTC, harukus commented
@machida 確認ありがとうございます🙇‍♀️
@obregonia1 色々調査ありがとうございます！！

2021-07-06 04:40 UTC, udaikue commented
@obregonia1 ありがとうございます！！
たしかに、Enterを押してから保存するとAdminでちゃんと保存できました。

@machid とりあえず私は、一般ユーザーでもAdminと同じようにリロードしてもDBに保存されるように修正を進める感じでよろしいですか??

2021-07-06 05:01 UTC, machida commented
@udaikue いえ、このバグは保存されないのがバグではなく、保存ボタンを押すとタグの見た目になってしまうところがバグなので、これは別Issueで対応したいと思いますー なので、ここは今回のIssueの範囲外としてくださいー

2021-07-06 06:46 UTC, udaikue commented
@machida 承知しましたー！このPRはこのままkomagataさんにレビュー依頼して良いですか??

2021-07-06 08:58 UTC, obregonia1 commented
@udaikue 
まだ全てのユーザーが編集できるようにはなっていないみたいですー。

> 一般ユーザーでタグを保存してみるとブラウザのコンソールでエラーを吐いているのでこれを参考にするといいと思います。

このエラーがヒントになっているので確認してみて下さい👍

2021-07-06 09:43 UTC, udaikue commented
@obregonia1 ありがとうございます!!💪

2021-07-07 14:05 UTC, komagata commented
@udaikue これ、APIの方が誰でも編集できるようになってなかったりしないっすかね？

2021-07-08 12:34 UTC, machida commented
@udaikue すいません、メンションに返信してませんでした。エンターを押さなくても保存ボタンを押すとタグの見た目になってしまうは、別のIssueで対応するので、adminとQを登録したユーザーしかタグを編集できなくなってるので、それ以外のユーザーもタグが編集できるようにapiの修正だけお願いできたらと思いますー

2021-07-10 08:19 UTC, udaikue commented
@komagata ありがとうございます。修正に関して質問タイムで質問して、内容をここに書こうと思いましたが長くなってしまったので日報に書きました。

@harukus 保存できるようになったかと思いますので、お手すきのときに再度レビューお願いします！！

2021-07-15 03:19 UTC, harukus approved these changes
@udaikue  Enterボタンでの保存確認できました！遅くなってごめんなさい🙇‍♀️

2021-07-15 13:08 UTC, udaikue commented
@harukus いえいえ、ご確認ありがとうございます!!

@komagata こちらレビューをお願いします!!

2021-07-19 06:33 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-19 06:33 UTC, merged