プラクティスページから「質問する」を押したときは、対象のプラクティスが選択された状態で質問するページが開く
fjordllc/bootcamp pull request #2924
Opened 2021-07-04 16:23 UTC by Daichi831

2021-07-05 09:16 UTC, Daichi831 commented
@obregonia1 
こちらお時間あるときにレビューをお願いします！🙇‍♂️

2021-07-05 09:46 UTC, obregonia1 commented on test/system/questions_test.rb
> +  test 'select practice title when question create page' do
when以降が「質問がページを作成したとき」になっているので変えた方がいいと思います。

2021-07-05 09:47 UTC, obregonia1 approved these changes
確認しました！いいと思います👍
一点だけコメントしているので確認よろしくお願いしますー。

2021-07-05 10:33 UTC, Daichi831 commented on test/system/questions_test.rb
> +  test 'select practice title when question create page' do
ありがとうございます！
確かに変だったので「プラクティスページで質問ボタンを押したとき」に変更しました！

2021-07-05 11:50 UTC, obregonia1 commented on test/system/questions_test.rb
> +  test 'select practice title when question create page' do
スペルは`button`ですねー。

2021-07-05 12:01 UTC, Daichi831 commented on test/system/questions_test.rb
> +  test 'select practice title when question create page' do
すみません！
ありがとうございます！

2021-07-06 07:02 UTC, Daichi831 commented
@komagata 
こちら確認をよろしくお願いします！🙇‍♂️

2021-07-08 03:48 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-07-08 03:48 UTC, komagata requested changes
@Daichi831 すみません、コンフリクトの解消お願いします〜

2021-07-08 11:37 UTC, Daichi831 commented
@komagata
こちらコンフリクトの解消と修正したテストの追加をしました！
宜しくお願いします🙇

2021-07-10 17:24 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-10 17:24 UTC, merged