markdownでユーザーアイコンを表示できるように
fjordllc/bootcamp pull request #2958
Opened 2021-07-11 12:41 UTC by gozasoro

ref: #2427

2021-07-11 13:32 UTC, gozasoro commented
@komagata @machida tributeの補完機能でtriggerを`:@`に設定すると、絵文字のtriggerの`:`と被ってしまい、うまく動作しない状態です。
（`:`で打ち始めると絵文字一覧の中から検索を始めてしまい、`:@`だと`Not Found`になってしまう。tributeに渡すcollectionの順番を変えるとユーザーはうまくいっても絵文字が`Not Found`になる。）

![image](https://user-images.githubusercontent.com/62997922/125196786-1037db80-e296-11eb-8bde-773819573993.png)

対応としては
- triggerを別のものにかえる
- 絵文字の補完機能で読み込んでいる絵文字一覧のjsonに
  `mention.fetchValues()`で取得したjsonをDeepコピー→@付きのユーザー名一覧を作ったjsonをマージ
  絵文字補完機能の中でユーザー名を補完する

のどちらかかなと考えています。アドバイスをいただけますでしょうか？🙏

2021-07-12 06:38 UTC, komagata commented
@gozasoro 「絵文字の一種を増やす」でお願いします。

詳細な実装方法についてはお任せします。

2021-07-12 10:25 UTC, gozasoro commented
@komagata 了解しました！

2021-07-13 19:47 UTC, gozasoro commented
@Daichi831 こちらお手隙の際にレビューをお願いいたします！

2021-07-14 11:45 UTC, Daichi831 commented
承知しました！
少々お待ちください！

2021-07-14 23:57 UTC, Daichi831 approved these changes
おお！絵文字のようにアイコンが表示できるんですね！
すごいです〜
僕の環境でも動作確認できました〜okだと思います！

`markdown-it`というライブラリでhtmlに変換できるんですね！
僕も動作を理解するために確認のコメントをしてますが間違いがあったら教えて欲しいです！

2021-07-15 00:23 UTC, Daichi831 commented on app/javascript/textarea-autocomplte-emoji.js
> +        if (item.original.isUser) return `<span class='emoji'>${escapeHtml(item.original.login_name)}</span>`
> ユーザーアイコンのユーザー名候補表示の際にはスッキリさせるためにlogin_nameのみ出るように

コメント欄でメンションをする場合はlogin_nameだけでなくユーザー名も出ているのでユーザー名も一緒に出しても良いのかな〜とも思いました！

2021-07-15 01:03 UTC, Daichi831 commented on app/javascript/textarea-initializer.js
> +      emoji.addUserData(json)
ここで`/api/mention_users`で取ってきたjsonデータを`addUserData`メソッドを用いて`TextareaAutocomplteEmoji`に追加してるんですね〜

2021-07-15 01:07 UTC, Daichi831 commented on app/javascript/textarea-autocomplte-emoji.js
> +    }).concat(this.userValues)
ここでアイコンと絵文字のデータを結合してるんですね！

2021-07-15 01:15 UTC, Daichi831 commented on app/javascript/user-icon-renderer.js
> +      element.src = this.urls[loginName]
なるほど！`user-icon-renderer.js`というモジュールを作ってここでlogin_nameに対応したurlを取得してるんですね！

2021-07-15 12:32 UTC, gozasoro commented on app/javascript/textarea-autocomplte-emoji.js
> +        if (item.original.isUser) return `<span class='emoji'>${escapeHtml(item.original.login_name)}</span>`
ユーザー名も表示するようにしました、ありがとうございます！

2021-07-15 12:45 UTC, gozasoro commented
@Daichi831 レビューありがとうございました！

@komagata こちらレビューをお願いいたします！（デザインはまだ入れてもらってないです！）

2021-07-19 06:32 UTC, komagata requested changes

2021-07-19 06:32 UTC, komagata commented on app/controllers/api/user_icon_urls_controller.rb
> +      user_icon_urls.store(user.login_name, user.avatar.attached? ? rails_storage_proxy_url(user.avatar) : '')
ここでstoreせずに、index.json.jbuilderの中で表示するのがいいかも？

2021-07-20 18:50 UTC, gozasoro commented
@komagata jbuilderを使って表示するように修正しました（テストも作りました）！確認をお願いします！

あと、テスト作成中に気付いたのですが、apiのテストでは`create_token`メソッドを呼び出してtokenを以下の流れで取得、tokenをヘッダーに含めてユーザーログインをしています。
https://github.com/fjordllc/bootcamp/blob/56cb8fd6d1b0a27caaa16ed4ad82d84baa3de002/test/integration/api/users_test.rb#L8-L16
https://github.com/fjordllc/bootcamp/blob/56cb8fd6d1b0a27caaa16ed4ad82d84baa3de002/test/supports/api_helper.rb#L4-L7
`session_controller.rb`の`login_and_issue_token`にて`auto_login`メソッドが呼び出され`session[:user_id]`に`user.id.to_s`がセットされることで（sessionを使ったログインになる）、`headers: { 'Authorization' => "Bearer #{token}" }`の一文がなくても既にログイン判定になっています。
https://github.com/fjordllc/bootcamp/blob/56cb8fd6d1b0a27caaa16ed4ad82d84baa3de002/app/controllers/api/session_controller.rb#L8

```
          def login_and_issue_token(*credentials)
            return unless (user = user_class.authenticate(*credentials))


            @current_user = user
            auto_login(@current_user)
            user_class.issue_token(id: @current_user.id, email: @current_user.email)
          end
```
https://github.com/hayfever/sorcery-jwt/blob/84371efcaaadead2a5a2564ea385eb0c3186f23b/lib/sorcery/controller/submodules/jwt.rb#L23-L29

```
      def auto_login(user, _should_remember = false)
        session[:user_id] = user.id.to_s
        @current_user = user
      end
```
https://github.com/Sorcery/sorcery/blob/6fdc703416b3ff8d05708b05d5a8228ab39032a5/lib/sorcery/controller.rb#L116-L119

`session_controller.rb`で`auto_login`を使ったログインの部分は削り、以下みたいな感じでtokenのみ返すようにすると、tokenを使ったログイン？ができるのかな〜と思ったのですが、どうでしょうか？💦
```
  def create
    user = User.authenticate(params[:login_name], params[:password])
    if user
      token = User.issue_token(id: user.id, email: user.email)
      render json: { token: token }
    else
      head :bad_request
    end
  end
```

2021-07-21 14:24 UTC, komagata commented
@gozasoro たしかにですね、そちらで修正お願いできればありがたいです～

2021-07-21 16:36 UTC, gozasoro commented
@komagata 修正しました！確認をお願いいたします！

2021-07-22 06:13 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-22 06:14 UTC, merged

2021-07-22 10:31 UTC, gozasoro commented
@komagata ありがとうございますー！

@machida こちらデザインをお願いいたします！