【メンター向け機能】提出物の担当者にアイコンが出るようにする
fjordllc/bootcamp pull request #2980
Opened 2021-07-14 18:01 UTC by Daichi831

issue #2274

2021-07-15 09:41 UTC, Daichi831 commented
@yana-gi 
こちらお時間あるときにレビューをよろしくお願いします！🙇‍♂️

2021-07-18 02:30 UTC, yana-gi approved these changes
遅くなってしまいすみません！
見ました〜大丈夫だと思います🙆‍♂️

2021-07-18 21:57 UTC, Daichi831 commented
@yana-gi 
ありがとうございます！

@komagata 
こちら確認をよろしくお願いします🙇

2021-07-19 06:45 UTC, komagata requested changes

2021-07-19 06:45 UTC, komagata commented on app/javascript/product_checker.vue
> +    checkableType: {type: String,},
```suggestion
    checkableType: { type: String },
```

2021-07-19 06:45 UTC, komagata commented
こちら、machidaさんにデザイン依頼してみてください～

2021-07-19 08:44 UTC, Daichi831 commented
承知しました！
ありがとうございます！

2021-07-19 08:49 UTC, Daichi831 commented
@machida 
すみません！こちらのデザインをお願いしたいです〜🙇‍♂️

2021-07-19 11:46 UTC, machida commented
@Daichi831 デザイン了解ですー

2021-07-20 05:55 UTC, machida commented
@Daichi831 デザイン入れましたー

提出物個別ページの方がアイコン出ていませんでした。

<img width="860" alt="貼り付けた画像_2021_07_20_14_55" src="https://user-images.githubusercontent.com/168265/126268932-a1f35eb9-9de8-40ae-af0e-a9bda8632456.png">

2021-07-21 09:37 UTC, Daichi831 commented
@machida 
デザインありがとうございます！
個別ページでも表示されるようにしました！

2021-07-21 09:37 UTC, Daichi831 commented
@komagata 
こちら確認をよろしくお願いします！🙇‍♂️

2021-07-21 14:27 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-21 14:27 UTC, merged