ダッシュボードに自分のニコニコカレンダーを表示
fjordllc/bootcamp pull request #3003
Opened 2021-07-19 07:06 UTC by FUGA0618

ref: [#2965](https://github.com/fjordllc/bootcamp/issues/2965)

## やったこと
- ダッシュボードにも自分のニコニコカレンダーが表示されるようにしました(現役生のみ)。
- ニコニコカレンダーの表示に関するテストを追加しました。

## 変更前
<img width="1237" alt="スクリーンショット 2021-07-19 16 04 28" src="https://user-images.githubusercontent.com/58870882/126117199-a09fb98a-94e2-440a-a93b-f183c2549dc1.png">

## 変更後
<img width="1237" alt="スクリーンショット 2021-07-19 15 59 49" src="https://user-images.githubusercontent.com/58870882/126117334-9bdb04df-f010-4758-9b3d-86a670a0dc75.png">

2021-07-19 07:24 UTC, FUGA0618 commented
@rikuba こちらのレビューお願いいたします🙏

2021-07-19 11:46 UTC, rikuba approved these changes
確認しました。LGTMです!

2021-07-19 12:46 UTC, FUGA0618 commented
@rikuba レビューありがとうございました🙏
@komagata こちらのレビューお願いいたします🙏

2021-07-20 06:41 UTC, komagata requested changes

2021-07-20 12:20 UTC, FUGA0618 commented on test/system/home_test.rb
> +  test '現役生の場合にニコニコカレンダーが表示されているか' do
テスト名を英語に修正しました！

2021-07-20 12:24 UTC, FUGA0618 commented
@komagata 修正しましたので再度レビューお願いいたします🙏

2021-07-21 07:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-21 13:21 UTC, merged