ユーザー > 質問一覧 に質問がない場合の表示を変更
fjordllc/bootcamp pull request #3004
Opened 2021-07-20 00:46 UTC by rjtt17

2021-07-20 13:44 UTC, rjtt17 commented
@FUGA0618 お時間ある際にレビューお願いいたします🙏

2021-07-20 14:09 UTC, FUGA0618 requested changes
@rjtt17 
レビューしました！
細かいところですが1点だけコメントしてますのでご確認お願いいたします🙏

2021-07-20 14:09 UTC, FUGA0618 commented on app/views/users/questions/index.html.slim
> +        | 質問はまだありません。
細かいですが、インデント入れた方が良いと思いました！

2021-07-20 14:40 UTC, rjtt17 commented on app/views/users/questions/index.html.slim
> +        | 質問はまだありません。
細かいところまで、チェック頂きとても助かります🙇‍♂️
```|```の前にインデント入れました~

2021-07-20 14:42 UTC, rjtt17 commented
@FUGA0618 
早速レビュー頂きありがとうございました！
修正したので、お手数お掛け致しますが再度ご確認して頂けないでしょうか？
よろしくお願い致します🙏

2021-07-20 14:57 UTC, FUGA0618 approved these changes

2021-07-20 14:58 UTC, FUGA0618 commented
@rjtt17 
修正ありがとうございます🙏
LGTMです👍

2021-07-20 23:48 UTC, rjtt17 commented
@FUGA0618  レビューありがとうございました🙇‍♂️
@komagata お時間ある際にレビューお願いいたします🙏

2021-07-21 14:24 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-21 14:24 UTC, merged