WIPの日報に「この日報は提出済です」メッセージが表示されないようにした
fjordllc/bootcamp pull request #3016
Opened 2021-07-22 11:49 UTC by udaikue

issue #2934

2021-07-23 02:19 UTC, udaikue commented
@FUGA0618 お手すきのときにレビューをお願いします🙏

2021-07-23 08:46 UTC, FUGA0618 approved these changes
@udaikue 
実装お疲れさまです！
WIPに戻した時にメッセージが表示されないことを確認しました。
LGTMです👍

2点ほどコメントしましたが、どちらも本質的な話ではないのでApproveします🙆🏻‍♂️

2021-07-23 08:46 UTC, FUGA0618 commented on test/system/reports_test.rb
> +    assert_text '日報を保存しました。'
新しく日報を作成するテストはすでにあるので、ここであえてテストする必要はなさそうに思いました！
すでにfixtureで投稿済みになっている日報を使って、WIPにした時の挙動だけテストする形の方が、テストのコストを抑えられるかなと👍

2021-07-23 08:46 UTC, FUGA0618 commented on app/views/reports/_form.html.slim
> +      - if !@report.wip? && (params[:action] != 'new')
ここの条件式ですが、

```ruby
unless @report.wip? && params[:action] != 'new'
```

とした方が、`@report.wip?`に否定演算子が不要になり、2つ目の条件式も`()`が不要になるのでいいかなと思いました😊

2021-07-24 23:46 UTC, udaikue commented
@FUGA0618 レビュー&指摘ありがとうございます✨修正しました〜

@komagata こちらレビューをお願いします!!

2021-07-26 06:51 UTC, komagata requested changes

2021-07-26 06:51 UTC, komagata commented on app/views/reports/_form.html.slim
> +      - unless @report.wip? || params[:action] == 'new'
これ新規作成時にValidationエラーが出てるときは`params[:action]`が`create`とかになってたりしないですかね？（その時おかしくなる？）

また、unless + orを使うと人間が直感的に条件を理解しづらくなるのでなるべくif + 否定(!)がいいかもです～

2021-07-26 08:32 UTC, FUGA0618 commented on app/views/reports/_form.html.slim
> +      - unless @report.wip? || params[:action] == 'new'
@udaikue 僕が余計なレビューしたせいですみません🙇‍♂️

2021-07-26 14:23 UTC, udaikue commented on app/views/reports/_form.html.slim
> +      - unless @report.wip? || params[:action] == 'new'
@FUGA0618 とんでもないですー。勉強になりました😄

@komagata 

> Validationエラー

「この日報は〜」のメッセージのことですか？
日報作成ボタンを押したときの`params[:action]`は`new`でしたが、そういうことではないですか??

unlessは修正しました！

2021-07-27 04:54 UTC, komagata commented on app/views/reports/_form.html.slim
> +      - unless @report.wip? || params[:action] == 'new'
@udaikue 

> 「この日報は〜」のメッセージのことですか？

いえ、「タイトルを入力してください」などのメッセージのことです。

日報作成時にエラーが出ると、新規作成ページ（newのview）を表示していますが、HTTPのリクエストとしては

```
POST /reports
```

になっているので、actionが`create`になるんじゃないかな～という意味です～

2021-07-28 11:40 UTC, udaikue commented on app/views/reports/_form.html.slim
> +      - unless @report.wip? || params[:action] == 'new'
@komagata 解説していただきありがとうございます🙏理解できました！

修正しましたので、再度ご確認お願いします。

2021-07-28 16:24 UTC, komagata commented
commitメッセージが似た内容が続いていたり、コンテクストがわからなかったりするものがあるので、下記を参考にしてまとめる・修正するなどお願いします～

[コミットメッセージの書き方](https://medium.com/@risacan/%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9-64aeadd92057)
（先頭を絵文字にする部分は参考にしなくて大丈夫です）

![image](https://user-images.githubusercontent.com/16577/127359646-9b5ac2cd-4655-48fb-9c6d-896d9c5b27b7.png)

2021-07-29 02:58 UTC, udaikue commented
@komagata ありがとうございます〜。commitめちゃくちゃでした、すみません💦

どう整理するか考えたところ、四角で囲ったところはcommitメッセージを修正したい、矢印の箇所は修正して戻したので不要になりました。

![WIPの日報の編集画面に「この日報は提出済です」メッセージが表示されないようにした_by_udaikue_·_Pull_Request__3016_·_fjordllc_bootcamp](https://user-images.githubusercontent.com/58643754/127424369-1636c017-93d7-4e70-b5d7-3bbbb720a004.png)

一番古い不要なcommitの前のcommitの状態まで戻ってやり直すのが早いかと思いそのようにしました。
何か問題あれば教えてください。

2021-07-30 14:30 UTC, komagata commented
@udaikue こういう場合、squashするのがいいと思います。くっつける過程でコミットメッセージも変更できますので。

[Gitの複数コミットをrebaseとsquashでまとめる方法 \| iwb\.jp](https://iwb.jp/git-commit-rebase-squash/)

2021-07-31 00:31 UTC, udaikue commented
@komagata ありがとうございます。

squash、こういうときに使うんですね✨たしかにこちらのほうが簡単でよかったですね。。

2021-07-31 09:24 UTC, komagata commented
@udaikue こちらは僕がレビューしてもOKな状態でしょうか～

2021-07-31 09:34 UTC, udaikue commented
@komagata はい！お願いいたします🙏

2021-08-01 06:03 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-08-01 06:03 UTC, merged