[WIP]提出物個別ページにユーザーメモを表示
fjordllc/bootcamp pull request #3017
Opened 2021-07-22 13:06 UTC by FUGA0618

ref: [#2967](https://github.com/fjordllc/bootcamp/issues/2967)

2021-07-24 13:33 UTC, FUGA0618 commented
@yana-gi こちらのレビューお願いいたします🙏

2021-07-27 04:45 UTC, yana-gi reviewed
レビューお待たせしてしまって申し訳ないです🙏

コード見ました！
Vue.jsはあまり自信がないのですが、自分的には問題ないように見えました！
テストも網羅されていますし、メソッド名からどんなテストを行っているか分かりやすいです👏

仕様について2点気になったことがあるので確認お願いします🙏

## メンターメモからプラクティスメモの名称変更
メンターメモからプラクティスメモに名称変更を行っているようですが、こちらはミーティングなどで決定されたのでしょうか。
もしそうであれば、issueのコメント欄にこの旨をメモ程度で構わないので書いていただけると嬉しいです〜
自分含めた別時間のミーティングに参加しているメンバーにも情報共有できるので！

## 再読み込み時のモーダル表示
プラクティスメモとユーザーメモで以下の操作を行った時に挙動が違うようです。

- 編集する
- 保存ボタンを押す
- 更新ボタンを押す

プラクティスメモでは保存したのにも関わらず更新ボタンを押すと「このサイトを再読み込みしますか？」という表示がでます。

![memo for mentors](https://user-images.githubusercontent.com/67262644/127096429-a7e73d2d-2756-4763-a393-79cb8456dd56.png)

反対にユーザーメモは編集中でも保存をした後でもこのモーダルが表示されません。

どちらかの仕様に統一するか、もしくは両方とも編集中のみこのモーダルを表示させるか、仕様を検討した方が良さそうと思いました。
元の機能のプラクティスメモ（メンターメモ）の仕様にも関わってくるところなので、もしかしたら今回のissue外の問題かもしれません……！

2021-07-27 12:42 UTC, FUGA0618 commented
@yana-gi 
丁寧なレビューありがとうございます🙏

> メンターメモからプラクティスメモに名称変更を行っているようですが、こちらはミーティングなどで決定されたのでしょうか。

こちらは特にミーティングなどで決定したわけではなく、issueにmachidaさんが貼ってくださった画像にそのように書いてあったため、変更したものです。
明文化はされていなかったようなので、machidaさんのコメントを編集して名称変更についても明記する形にしました😊

> 再読み込み時のモーダル表示

編集後の再読み込みは自分では想定していなかったのでフィードバック助かります🙇🏻‍♂️
おっしゃってる挙動が僕の環境でも再現しました。

いろいろと挙動を確認してみたのですが、原因がわからずです…。
こちらの対応を今回のスコープに含めるかどうか、 @komagata さんのご意見を伺いたいと思います。

2021-07-28 01:57 UTC, yana-gi approved these changes
@FUGA0618 
> こちらは特にミーティングなどで決定したわけではなく、issueにmachidaさんが貼ってくださった画像にそのように書いてあったため、変更したものです。
明文化はされていなかったようなので、machidaさんのコメントを編集して名称変更についても明記する形にしました😊

画像見落としてましたすみません……！
コメント編集ありがとうございます！（issue作成者以外もコメントを編集できることを初めて知りました👀）

> 再読み込み時のモーダル表示

細かい指摘をしてしまい申し訳ないです……！
自分はApproveしておくので、komagataさんに確認お願いします🙏

2021-07-28 07:39 UTC, FUGA0618 commented
@yana-gi 
Approveありがとうございます！

> （issue作成者以外もコメントを編集できることを初めて知りました👀）

僕も知らなかったのですが、「できるかな〜？」と思ってやってみたらできたのでそのまま編集してしまいました😁

> 細かい指摘をしてしまい申し訳ないです……！
自分はApproveしておくので、komagataさんに確認お願いします🙏

自分では気付けなかったところなので、ありがたかいです！
ありがとうございます🙏

komagataさんに確認したところ、「**プラクティスメモ単体で起こっている挙動なのであれば、別issueとして対応する方が良い**」というお話だったので、別でissueを立てました。

[メンター用の提出物ページでプラクティスメモを編集・保存してリロードした時の挙動に差異がある · Issue \#3044 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/3044)

2021-07-28 07:40 UTC, FUGA0618 commented
@komagata こちらのレビューお願いいたします🙏

2021-07-28 16:08 UTC, komagata requested changes
conflictの解消お願いします～（GitHubのコンフリクトの機能を使うとマージになっちゃうので手元での解消が良いです～）

2021-07-30 10:37 UTC, FUGA0618 commented
@komagata 
コンフリクトの解消をしました。
改めてレビューお願いいたします🙏

2021-07-30 14:24 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-08-01 06:02 UTC, merged

2021-08-06 20:38 UTC, komagata commented
@FUGA0618 本番環境で動作することを確認しました。

2021-08-07 01:33 UTC, FUGA0618 commented
@komagata 
ご確認ありがとうございます！
issueはcloseします。