プロフィールに分報のURLを登録できるようにする
fjordllc/bootcamp pull request #3020
Opened 2021-07-23 14:24 UTC by rikuba

Ref: #2898

2021-07-23 15:09 UTC, rikuba commented
@komagata 

このPRについて2点ご確認したいことがあります。

1. データベースに分報URLを保存するにあたり、`users`テーブルに追加するカラムの名前は`times_url`で問題ないでしょうか

   1. [またSlackでtimesを始めてしまった｜ばんくし｜note](https://note.com/vaaaaanquish/n/ncc512cf0e263) の次の一文を参考にしました
      > 分報、times、timelineなど、様々な呼び方を各社がしているが、要は社内チャットにおけるTwitterである（ここでは最も一般的だと思われるtimesに統一する）。

2. プロフィールページ`/users/:id`において、分報へのリンクはどのように表示すべきでしょうか
   （このPRでは暫定的にDiscord IDのすぐ後に置いています）

   <img src="https://user-images.githubusercontent.com/350435/126801501-7b06966a-fabc-4ab6-877b-c06ceca10917.png" width="553" height="578">

2021-07-26 06:07 UTC, komagata commented
@rikuba 

> 1

はい、大丈夫です～

> 2

それで大丈夫です～（細かいデザインは @machida さんがやってくれるとおもいます～）

2021-07-26 06:24 UTC, rikuba commented
@komagata 
ご返信ありがとうございます。
承知しました! 見た目についてはmachidaさんにお願いしたいと思います。

2021-07-26 08:39 UTC, rikuba commented
@FUGA0618 
こちらのPRのレビューをお願いいたします🙏

2021-07-26 13:34 UTC, rikuba commented
最新のmainにrebaseしました。

2021-07-27 14:34 UTC, FUGA0618 reviewed
@rikuba 
実装お疲れ様です！
分報にプロフィールから飛べると便利ですね👍

2点ほど質問があります。
- テストの部分にコメントした件について
- バリデーションを設定していない理由
    - facebookのURLもバリデーションがないのでそれにならったのかな？とも思いましたが、個人的にはあった方が良いかなと思ったため
    - 「`https://discord.gg/`で始まる」くらいの条件で良さそう？

2021-07-28 04:39 UTC, rikuba commented on test/system/users_test.rb
> +    kimura.update!(times_url: 'https://discord.gg/kimura-times')
`/current_user/edit`に遷移してフォーム入力すると、`users_test.rb`で`current_user`リソースをテストすることになってしまうような気がして、`update!`で直接更新していました。

ただ、ご指摘を受けて考えてみると、システムテストはブラウザ操作でできることだけで完結すべきな気もしてきました🤔
Fu-gaさんはいかが思われますか?

2021-07-28 04:40 UTC, rikuba commented
@FUGA0618 

レビューありがとうございます🙏
バリデーションの件、ご指摘の通り最低限のチェックはしておいた方がいいと思うので追加しました!

2021-07-28 07:54 UTC, FUGA0618 commented on test/system/users_test.rb
> +    kimura.update!(times_url: 'https://discord.gg/kimura-times')
ご回答ありがとうございます！

> システムテストはブラウザ操作でできることだけで完結すべき

僕も同じように思いました😀
テスト上でフォーム入力や登録処理を動かすことで、ユーザーが想定通りのブラウザ操作で分報URLを登録できる(またはできない)ことが担保できるのではないかと思います👍

とはいえ僕もシステムテストがどうあるべきかは自信ないですし、rikubaさんが実装してくださったやり方がセオリーかもしれないので、 @komagata さんに確認してみるのが良いかもしれないです。

2021-07-28 07:56 UTC, FUGA0618 commented
@rikuba 
バリデーションの追加、ありがとうございます！
テストまで追加してくださって素晴らしいと思いました👏

システムテストの件は @komagata さんのご意見を伺うとして、僕のレビューはApproveしますね🙆🏻‍♂️
お疲れさまです！

2021-07-28 07:57 UTC, FUGA0618 approved these changes

2021-07-28 08:11 UTC, rikuba commented
@FUGA0618 
ご返信ありがとうございます!
システムテストについては確認のためにひとまずこのままの状態でkomagataさんにレビューをお願いしようと思います。
テストコードを含めしっかりチェックしていただきありがとうございました!😃

@komagata 
こちらのPRのレビューをお願いいたします🙏

2021-07-28 16:17 UTC, komagata requested changes

2021-07-28 16:17 UTC, komagata commented on test/models/user_test.rb
> +  test 'times_url' do
👍

2021-07-28 16:17 UTC, komagata commented on test/system/users_test.rb
> +    kimura.update!(times_url: 'https://discord.gg/kimura-times')
@rikuba @FUGA0618 

テストの主眼以外の部分はどのように操作しても大丈夫です。（システムテストだからといってブラウザで全てやらなくてもよい）

このテストの主眼である*show times link on user page*とは関係ない部分なのでデータの修正はActiveRecrodでやってもよいとおもいます。

もしブラウザ操作で分報URLを登録できることをテストしたいのであれば、別のテストでやるべきです。

また、ブラウザ操作は非常に遅い処理なので、メインとなる場合以外なるべくやりたくないという事情もあります。

2021-07-28 16:17 UTC, komagata commented on test/system/users_test.rb
> +    wait_for_vuejs
これはいらないかも？

2021-07-28 16:17 UTC, komagata commented on test/system/users_test.rb
> +    wait_for_vuejs
これもVue.jsで何か処理を行った後でなければいらないかもです。

2021-07-28 23:12 UTC, rikuba commented on test/system/users_test.rb
> +    kimura.update!(times_url: 'https://discord.gg/kimura-times')
@komagata

コメントありがとうございます!
テストの考え方について参考になります。テストの主眼かどうかという基準を持つようにします✍️

システムテストのあり方について考えるきっかけをくださった @FUGA0618 さんもありとうございます!

2021-07-28 23:13 UTC, rikuba commented on test/system/users_test.rb
> +    wait_for_vuejs
Vue.jsが使われているページで必ず呼び出すものと勘違いしておりました💦
削除しておきます。

2021-07-28 23:15 UTC, rikuba commented
@komagata 

最新のmainへのrebaseと、コードの修正を施しました。
ご確認のほどよろしくお願いいたします🙏

2021-07-29 13:52 UTC, FUGA0618 commented on test/system/users_test.rb
> +    kimura.update!(times_url: 'https://discord.gg/kimura-times')
@komagata @rikuba 
ありがとうございます！
テストの主眼とブラウザ操作の遅さとの兼ね合いというところ、今後意識したいと思います。
勉強になりました！！

2021-07-30 14:21 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-30 14:21 UTC, merged