[WIP]【メンター向け機能】提出物に未アサインタブを追加
fjordllc/bootcamp pull request #3027
Opened 2021-07-26 00:39 UTC by FUGA0618

ref: [#3021](https://github.com/fjordllc/bootcamp/issues/3021)

## やったこと
メンター用の提出物一覧ページのタブに「未アサイン」タブを追加しました。

### 変更前
<img width="712" alt="スクリーンショット 2021-07-26 9 38 57" src="https://user-images.githubusercontent.com/58870882/126918937-8daed929-16b8-490c-973e-e2c21e5e982c.png">

### 変更後
<img width="712" alt="スクリーンショット 2021-07-26 9 35 57" src="https://user-images.githubusercontent.com/58870882/126918890-c99b4367-36c0-464f-9a8d-81c2887c4470.png">

## 「未アサイン」タブの仕様
- まだ担当メンターが決まっていない、かつ未完了の提出物一覧が表示される
- 一覧には現在の未返信と同じように、提出日から 5日目、6日目、7日目を表す帯が表示される
- 「未アサイン」のタブには、まだ担当メンターが決まっていない、かつ未完了の提出物の数が表示される

2021-07-28 09:28 UTC, FUGA0618 commented
@gallardo16 こちらのレビューお願いできますでしょうか🙏

2021-08-02 05:19 UTC, gallardo16 approved these changes
ごめんなさい、返信が遅れました🙇‍♂️
OKだと思います！

2021-08-02 11:06 UTC, FUGA0618 commented
@gallardo16 
いえいえとんでもないですー！
レビューありがとうございました🙏

@komagata 
レビューお願いいたします🙏

2021-08-08 21:49 UTC, komagata requested changes

2021-08-08 21:49 UTC, komagata commented on app/javascript/products.vue
> +            location.pathname === '/products/unassigned'
`/products/unassigned?read=false`みたいにパラメーターが追加されたときに動きがおかしくなったりは大丈夫でしょうか～？

2021-08-09 01:11 UTC, FUGA0618 commented on app/javascript/products.vue
> +            location.pathname === '/products/unassigned'
https://github.com/fjordllc/bootcamp/pull/3067#discussion_r683447617
こちらでやりとりさせてもらったのと同様に、クエリパラメーターが追加されても大丈夫そうです🙆🏻‍♂️
念のため動作確認もしましたが挙動は変わらずでした。

2021-08-09 01:12 UTC, FUGA0618 commented
@komagata 
テストに重複箇所があったので修正し、コメントに返信しましたのでご確認お願いいたします🙏

2021-08-10 16:53 UTC, komagata requested changes

2021-08-10 16:53 UTC, komagata commented on test/system/products_test.rb
> +    assignee_buttons.first(3).each(&:click)
3つめというのは必然性がなく、今後のレイアウト変更などで変わりやすいのですぐにテストがうごかなくなっちゃいそうなので、他の条件にしたいですね。（hashとarrayの違いのように。hashは名前でしていするので順番がかわっても問題ない）
タブにその名前を表すidやclassがついているのは問題ない（あったほうが良い）ので追加でつけちゃっても大丈夫です。

2021-08-11 00:53 UTC, FUGA0618 commented on test/system/products_test.rb
> +    assignee_buttons.first(3).each(&:click)
3回「担当する」ボタンを押す必要はなさそうです😅

- 未アサインタブにidをつける
- 未アサインタブ内のカウンターにidをつける
- 「担当する」ボタンのクリックを1回だけしてカウンターが変化していることを検証する

という形に修正しました🙆🏻‍♂️

2021-08-11 00:54 UTC, FUGA0618 commented
@komagata テストの修正をしましたのでご確認お願いいたします🙏

2021-08-13 07:29 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-08-13 07:29 UTC, merged