Docsページの上部にコメント数を表示
fjordllc/bootcamp pull request #3034
Opened 2021-07-26 21:34 UTC by rikuba

Ref: #2659

2021-07-26 22:12 UTC, rikuba commented
@makiichikawa 
こちらのPRのレビューをお願いいたします🙏

2021-07-27 01:22 UTC, makiichikawa commented
@rikuba 
再読み込み後、コメント数が正しく出ていました。良いと思います！
テストも追加されており、素晴らしいと思いました〜

2021-07-27 04:42 UTC, rikuba commented
@makiichikawa 

動作をご確認いただいた上でのレビュー、ありがとうございます!

こちら Pull Request に承認 (Approve) を付けていただけますと幸いです🙏

- [GitHubでのコードレビューが爆速になる新機能review requestsの使い方 - Qiita](https://qiita.com/tonkotsuboy_com/items/cb64223737aff286111a#%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E4%BE%9D%E9%A0%BC%E3%82%92%E5%8F%97%E3%81%91%E3%81%9F%E5%81%B4)

2021-07-27 04:50 UTC, makiichikawa approved these changes
@rikuba 
レビュアー初で慣れておらず、すみません。。
承認ボタン押します。

2021-07-27 06:58 UTC, rikuba commented
@makiichikawa 
承認ありがとうございます!

@komagata 
こちらのPRのレビューをお願いいたします🙏

2021-07-28 13:56 UTC, komagata commented on app/views/pages/show.html.slim
> +              | #{@page.comments.size}
```suggestion
              = @page.comments.size
```

2021-07-28 13:56 UTC, komagata commented on app/views/pages/show.html.slim
> +    a#comments.a-anchor
これってなんでしょう？

2021-07-28 14:07 UTC, rikuba commented on app/views/pages/show.html.slim
> +    a#comments.a-anchor
コメント数をクリックした時のジャンプ先のアンカーとして用意しました。

https://github.com/fjordllc/bootcamp/blob/9a5595daec28cc21e71af1403a70a09a7653dd19/app/views/pages/show.html.slim#L22

Railsで`js-`プレフィックスの付いたID（`#js-comments`）を参照するのは好ましくないと思い、既存のQ&Aのコードを参考に書きました。

https://github.com/fjordllc/bootcamp/blob/0e2b92f0e819258fc64f44e2a4e6b2a4831b4958/app/javascript/question.vue#L14

2021-07-28 14:10 UTC, rikuba commented on app/views/pages/show.html.slim
> +              | #{@page.comments.size}
ありがとうございます。修正します💦

2021-07-28 16:30 UTC, komagata requested changes

2021-07-28 16:30 UTC, komagata commented on app/views/pages/show.html.slim
> +    a#comments.a-anchor
目的の対象が`#js-comments`と同じでよいなら、新しいdivを使いするのではなくそのdivにidかclassを追加するでよいかもです～

2021-07-29 00:04 UTC, rikuba commented on app/views/pages/show.html.slim
> +    a#comments.a-anchor
ありがとうございます。

HTMLについて調べてみたのですが、同じ要素に複数のIDを付ける方法は無いようでした。
既存の`<div>`に`name`属性を付けると動作はしたのですが、HTMLとしては不正となってしまうようです😓

[(X)HTML5 validation results (validator.nu)](https://html5.validator.nu/)
<img src="https://user-images.githubusercontent.com/350435/127411291-e8768df9-a082-46c5-9df2-c9c3d37d3096.png" width="400" height="300">

アンカー用の`<a>`要素を追加するよりは、リンク先として`#js-comments`を指定した方がよいでしょうか?

2021-07-30 14:22 UTC, komagata commented on app/views/pages/show.html.slim
> +    a#comments.a-anchor
なるほど、２つもIDつけられないですね。すみません、僕が間違っていたので現状で大丈夫です～

2021-07-30 14:22 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-07-30 15:33 UTC, rikuba commented
最新のmainにrebaseしました。

@komagata 
レビューありがとうございました😃

@machida 
こちらのデザインをお願いできますでしょうか🙏
（現状はQ&AのHTMLを流用しています）

2021-07-31 01:23 UTC, machida commented
@rikuba デザイン了解ですー

2021-08-04 17:12 UTC, merged