【メンター向け機能】左メニューの提出物ボタンに表示される数を未アサインの提出物数に変更
fjordllc/bootcamp pull request #3067
Opened 2021-07-30 13:41 UTC by FUGA0618

ref: [#3048](https://github.com/fjordllc/bootcamp/issues/3048)

「[【メンター向け機能】提出物に未アサインタブを追加 by FUGA0618 · Pull Request \#3027 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/3027)」が前提となるPRなので、向き先をそちらにしています。

## やったこと
左側メニューの「提出物」ボタンに表示されている提出物数は、現状ですと「未返信の提出物数」ですが、「**未アサインの提出物数**」に変更しています（メンターのみ表示される）。

<img width="797" alt="スクリーンショット 2021-07-30 21 49 12" src="https://user-images.githubusercontent.com/58870882/127661597-54a474f2-1780-46d5-8a33-c2f708bc5a47.png">

2021-07-30 14:13 UTC, FUGA0618 commented
@rjtt17 こちらのレビューお願いいたします🙏

2021-08-01 23:24 UTC, rjtt17 approved these changes
@FUGA0618 確認しました〜
LGTMだと思います👍

2021-08-02 11:06 UTC, FUGA0618 commented
@rjtt17 レビューありがとうございました🙏
@komagata レビューお願いいたします🙏

2021-08-03 17:13 UTC, komagata requested changes

2021-08-03 17:13 UTC, komagata commented on app/javascript/products.vue
> +            location.pathname === '/products/unassigned'
これは既存の問題でもあるのですが`/products/unassigned?read=true`で既読を表すなどパラメーターが追加されたときにおかしくなるので新しいクエリパラメーターが追加されても正常に動くようにしたいな～と思いました。

2021-08-03 17:13 UTC, komagata commented on app/models/cache.rb
> +    def delete_unassigned_product_count
👍

2021-08-03 17:13 UTC, komagata commented on test/system/products_test.rb
> +    assignee_buttons.first(3).each(&:click)
順番や個数に依存すると壊れやすいテストになってしまうので、こういう場合はhtmlにidやclassをいい感じに追加しちゃったほうがいいとおもいます～

2021-08-05 13:22 UTC, FUGA0618 commented on app/javascript/products.vue
> +            location.pathname === '/products/unassigned'
ご指摘を受けて、`location.pathname.includes('not_responded')`で判定する実装を検討しました。
ですが、よくよく`location.pathname`について確認してみたら、このメソッドはpath部分のみを返すもので、クエリパラメーターがあっても含まれないようです。
<img width="561" alt="スクリーンショット 2021-08-05 20 13 32" src="https://user-images.githubusercontent.com/58870882/128341424-d75aeb46-30b7-4b0c-91b5-3493a48bc6d5.png">

ですので、今後クエリパラメーターが追加された場合でも動作に影響はないかなと思ったのですがいかがでしょうか。
仰っている意味を勘違いしていたりしたらご指摘ください🙇🏻‍♂️

2021-08-05 13:24 UTC, FUGA0618 commented on test/system/products_test.rb
> +    assignee_buttons.first(3).each(&:click)
こちらのテストで何をしたいのか改めて考えてみたところ、

- 未アサインタブにカウンターが表示されているか
- 「担当する」ボタンがクリックされた後、カウンターの表示が変化しているか

という点をテストしたいので、個数をテストに含める必要はないと思いました。
個数に依存しない形で、操作の前後でカウンターが変化しているかを確認するテスト内容に修正しました。

2021-08-05 13:25 UTC, FUGA0618 commented
@komagata 改めてレビューお願いできますでしょうか🙏

2021-08-08 21:51 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-08-08 21:51 UTC, merged