「未返信の提出物」のページングを削除
fjordllc/bootcamp pull request #3075
Opened 2021-08-01 11:26 UTC by rikuba

Ref: #2998

2021-08-01 12:34 UTC, rikuba commented
@Daichi831 
こちらのPRのレビューをお願いいたします🙏

2021-08-02 11:24 UTC, Daichi831 approved these changes
確認しました！
okだと思います！

2021-08-02 11:29 UTC, rikuba commented
@Daichi831 
レビューありがとうございました!

@komagata 
こちらのレビューをお願いいたします🙏

2021-08-03 17:16 UTC, komagata requested changes
Vueの方でページングのコンポーネントとか使っていると思うのでそちらを削除したいです～

2021-08-04 00:33 UTC, rikuba commented
@komagata 

現在、提出部一覧はどのタブも共通で[products.vue](https://github.com/fjordllc/bootcamp/blob/main/app/javascript/products.vue)コンポーネントが使用されています。

https://github.com/fjordllc/bootcamp/blob/64a69a06bb69a8eaa1de14b86ee2b7e1a9599a26/app/views/products/not_responded/index.html.slim#L12

https://github.com/fjordllc/bootcamp/blob/64a69a06bb69a8eaa1de14b86ee2b7e1a9599a26/app/javascript/products.js#L2-L5

「未返信」タブでは`v-if`で要素自体は常にレンダリングされないようになっていますが、`nav.pagination`自体をなくした`products-without-paging.vue`といったコンポーネントを作った方がよいでしょうか🤔

https://github.com/fjordllc/bootcamp/blob/64a69a06bb69a8eaa1de14b86ee2b7e1a9599a26/app/javascript/products.vue#L12-L13

https://github.com/fjordllc/bootcamp/blob/740ac906fdb08f0765cc652b431030c59698c479/app/views/api/products/not_responded/index.json.jbuilder#L6

2021-08-08 21:23 UTC, komagata commented
@rikuba なるほど、でしたら仕方ないですね。コレで大丈夫です～

2021-08-08 21:24 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-08-08 21:24 UTC, merged