プラクティスに関連する日報が存在しない場合にアイコンを追加
fjordllc/bootcamp pull request #3087
Opened 2021-08-04 15:42 UTC by sota-onozuka

# やったこと

プラクティスに関連する日報が存在しない場合に「日報が存在しません。」の前にアイコンを表示するようにしました。
スタイルをa-empty～のものからo-empty～～のものに変えています
before: 
![image](https://user-images.githubusercontent.com/63279587/128210571-d995dae7-86a2-455d-ae76-59f5059b573b.png)

after: 
![image](https://user-images.githubusercontent.com/63279587/128208627-113a4f3b-3911-4180-a9ac-86df748b4f8d.png)

タスク: https://github.com/fjordllc/bootcamp/issues/3053

# 見てほしいこと

1. 表示の確認: 上記画像のように、きちんとアイコンが表示されているか ( http://localhost:3000/practices/841731997/reports )で確認できると思います
2. 使用しているスタイルの指定は適切か

2021-08-04 16:09 UTC, machida requested changes

2021-08-04 16:09 UTC, machida commented on app/views/practices/reports/index.html.slim
> +      .o-empty-message
この部分のマークアップを以下のように他の共通するものと同じマークアップにしてください。

```slim
.o-empty-message
  .o-empty-message__icon
    i.far.fa-sad-tear
  .o-empty-message__text
    | 日報はまだありません。
```

![image](https://user-images.githubusercontent.com/168265/128215253-3cd1435e-afd5-4177-9ef2-55fbdc99eb85.png)

2021-08-04 16:09 UTC, machida commented on app/assets/stylesheets/blocks/page/_o-empty-message.sass
> +  margin-bottom: 1rem
これを追加すると、これを使っている全てに影響してしまうので削除してください。

2021-08-04 16:10 UTC, machida commented
@sota-onozuka 指摘箇所の修正をお願いしますー

2021-08-04 17:12 UTC, machida commented
<img width="305" alt="貼り付けた画像_2021_08_05_2_10" src="https://user-images.githubusercontent.com/168265/128224470-3db802ed-71b7-4b79-a0d8-8930e0e2f455.png">

インデントがおかしいです。以下のようにお願いします。

```slim
.o-empty-message
  .o-empty-message__icon
    i.far.fa-sad-tear
  .o-empty-message__text
    | 日報はまだありません。
```

2021-08-05 01:42 UTC, machida approved these changes

2021-08-05 01:43 UTC, machida commented
@sota-onozuka
では、受講生にレビューを依頼し、それが通ったら駒形さんにレビューを依頼する、というのをお願いします。

2021-08-07 02:06 UTC, sota-onozuka commented
@masamune17 お手すきの際にレビューをお願いいたします！確認していただきたいことは上記の通りですが、不明瞭な点あれば遠慮なくご質問ください！

2021-08-07 09:34 UTC, masamune17 commented
@sota-onozuka 少々お時間をいただきます🙇
8/9(月)までにレビューいたします！！

2021-08-07 16:02 UTC, masamune17 approved these changes
@sota-onozuka 確認いたしました、問題ないと思います！！

2021-08-08 00:15 UTC, sota-onozuka commented
@masamune17  ありがとうございます。
@komagata  お手数ですが、お手すきの際にレビューをお願いいたします。

2021-09-01 10:55 UTC, masamune17 commented
@komagata さんこちらレビューをお願いいたします。

2021-09-04 04:56 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-04 04:56 UTC, merged