登録時にユーザーがコースを選択できるようにする
fjordllc/bootcamp pull request #3093
Opened 2021-08-05 05:17 UTC by udaikue

issue #2812

2021-08-13 23:42 UTC, udaikue commented
@machida こちらレビュー前にデザインをお願いできますでしょうか🙏

2021-08-14 09:43 UTC, machida commented
@udaikue cc @komagata 
セレクトタグだと、ユーザーはどんな選択肢があるかわからないのと、それぞれの選択肢の内容の説明が見れないので、選択をすることが困難です。なので、ラジオボタンで表示して、コース名だけでなく、説明も表示するようにしたいですー

2021-08-14 23:44 UTC, udaikue commented
@machida 承知しましたー。修正します💪

2021-08-18 05:18 UTC, machida commented
@udaikue (cc @komagata )
会員登録にコース選択を表示しなくなりそうなので、一旦会員登録のページはストップでお願いしますー

2021-08-18 08:26 UTC, udaikue commented
@machida 承知しましたー！表示・非表示の設定ができるようにするのみですね。

2021-08-18 15:05 UTC, machida commented
@udaikue 
コース一覧ページでは、非表示のコースは admin だけが見れるように修正をお願いします🙏

2021-08-22 13:24 UTC, udaikue commented
@machida 修正しましたので、再度ご確認をお願いします🙏

2021-08-25 06:04 UTC, machida commented
@udaikue 確認しました！ありがとうございます。デザインも入れましたー

2021-09-08 13:57 UTC, machida commented
@udaikue 修正しましたー コンフリクト解消したので、このPRをいじるときは、

```
git pull --rebase origin feature/users-can-select-a-course
```

をやってから作業をお願いします。

2021-09-08 15:07 UTC, machida commented
@udaikue おっと、DOM構造が変わったせいかテストが落ちてしまいました。こちら修正をお願いします🙏

2021-09-11 02:44 UTC, udaikue commented
@machida ありがとうございました！

@makiichikawa お手すきのときにレビューをお願いします〜🙏

2021-09-11 03:25 UTC, sinsoku commented on app/views/courses/_course.html.slim
> +                = course.title
`span` が両方にあるので、if文の外に書いた方がシンプルかなと思いました。

```suggestion
            - if admin_login? && !course.open_course
              .courses-item__title-icon.is-closed
                | 非表示
            span.courses-item__title-label
              = course.title
```

2021-09-11 03:59 UTC, udaikue commented on app/views/courses/_course.html.slim
> +                = course.title
@sinsoku ありがとうございます！その通りでした！修正しました✨

2021-09-11 06:18 UTC, makiichikawa approved these changes
@udaikue 
確認しました、問題ないと思います！

2021-09-11 06:27 UTC, udaikue commented
@makiichikawa 早々に確認していただきありがとうございます〜✨

@komagata こちらレビューをお願いいたします！

2021-09-13 17:53 UTC, komagata requested changes

2021-09-13 17:53 UTC, komagata commented on db/migrate/20210805050956_add_open_course_to_courses.rb
> +    add_column :courses, :open_course, :boolean, default: false, null: false
クラス名は名詞（主語）でメソッド名が動詞になり、

主語#動詞

の形になるので、Course#open_courseだと「頭痛が痛い」のように意味が重複してしまいます。
他の名前を考えてみてください〜

2021-09-16 07:05 UTC, udaikue commented on db/migrate/20210805050956_add_open_course_to_courses.rb
> +    add_column :courses, :open_course, :boolean, default: false, null: false
@komagata そうですね...😅名前を修正しました。

再度ご確認お願いします！

2021-09-21 05:44 UTC, komagata requested changes

2021-09-21 05:44 UTC, komagata commented on db/migrate/20210805050956_add_open_course_to_courses.rb
> +    add_column :courses, :open_course, :boolean, default: false, null: false
こちら修正されていないみたいです〜

2021-09-23 02:24 UTC, udaikue commented
@komagata 修正しましたので、再度ご確認お願いします🙏

2021-09-23 05:12 UTC, komagata requested changes

2021-09-23 05:12 UTC, komagata commented on db/migrate/20210923012348_add_is_opened_to_courses.rb
> +    add_column :courses, :is_opened, :boolean, default: false, null: false
is_xxxxはrubyだとあまり使わないので`open`とかが良いかもです〜

2021-09-23 12:11 UTC, udaikue commented
@komagata そうなんですね、openに変更しました。ご確認お願いします！

2021-09-25 13:20 UTC, komagata approved these changes
openってメソッドが一般的にたくさんあるのでどっかでその名前とぶつかりそうでちょっと怖い気がしますが、ま〜大丈夫だと思うのでOKです〜！

2021-09-25 13:20 UTC, merged

2021-09-26 04:36 UTC, sinsoku commented
@komagata @udaikue 
[Kernel.#open](https://docs.ruby-lang.org/ja/latest/method/Kernel/m/open.html) と被るため、移行が簡単であれば別の名前にした方が良かったりしません？
Rails 6.0では直っていますが、過去にRails本体でも [rails/rails#34098](https://github.com/rails/rails/issues/34098) のようなIssueがあったこともあり、少し怖いなと思いました。
コースの表示・非表示なら `published` や `enabled` のような名前に変えるのはどうかなと。

2021-09-28 17:37 UTC, komagata commented
@udaikue @sinsoku さんがおっしゃってるのを見ると確かに怖いので別のIssueで修正できたらありがたいです〜

2021-09-28 23:12 UTC, udaikue commented
@komagata (CC: @sinsoku )

#3326でIssueを作成してみましたのでご確認いただければと思います〜🧎

2021-09-29 12:55 UTC, komagata commented
@udaikue ありがとうござます！