お知らせページの上部にコメント数を表示
fjordllc/bootcamp pull request #3108
Opened 2021-08-08 09:02 UTC by makiichikawa

2021-08-09 02:00 UTC, makiichikawa commented
@rikuba 
こちらのレビューお願いできますでしょうか？？よろしくお願いいたします🙇🏼‍♂️

2021-08-09 06:07 UTC, rikuba requested changes
@makiichikawa 
一点だけ細かいところですがコメントしました!
動作・表示については全く問題ないと思います🙆‍♂️

2021-08-09 12:44 UTC, makiichikawa commented on app/views/announcements/_announcement.html.slim
> +                |）
@rikuba 
> パイプの後ろにスペースを入れると22行目とテキストの開始位置が一致してよさそうです。

ご指摘ありがとうございます！確かに、22 行目の平仄が揃っておりませんでした。
修正しましたので、ご確認のほどよろしくお願いいたします🙇🏼‍♂️

2021-08-09 12:58 UTC, rikuba approved these changes
@makiichikawa 
修正確認しました! LGTMです🙆‍♂️

2021-08-10 00:23 UTC, makiichikawa commented
@rikuba 
レビューありがとうございました！

@komagata 
こちらのレビューお願いいたします🙇🏼‍♂️

2021-08-10 16:56 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

@machida さんにデザイン依頼をお願いします～

2021-08-10 23:37 UTC, makiichikawa commented
@komagata 
レビューありがとうございました！

@machida 
こちらのデザインお願いできますでしょうか？よろしくお願いします🙇🏼‍♂️

2021-08-11 11:49 UTC, machida commented
マージしますー🎉

2021-08-11 11:49 UTC, merged