通知一覧をカテゴリ別に表示した
fjordllc/bootcamp pull request #3110
Opened 2021-08-09 05:18 UTC by yana-gi

ref: #2997

wip

2021-08-09 10:41 UTC, yana-gi commented
@cafedomancer 
よろしければレビューお願いします〜🙏

2021-08-11 13:26 UTC, cafedomancer commented on app/models/notification.rb
> +  }
全体としてはこうなっているといいのかなあ。

```ruby
where(kind: to_kinds(target))
where(kind: target_to_kinds(target))
```

2021-08-14 06:41 UTC, yana-gi commented
@cafedomancer 
細かく見ていただいてありがとうございます！
所用で数日ほど修正する時間が取れそうにないため、少々お時間いただきます🙏

2021-08-20 11:34 UTC, yana-gi commented on app/controllers/api/notifications_controller.rb
> +    @query = params[:query]
`target`と`query`をインスタンス変数からローカル変数に変更しました。

2021-08-20 11:34 UTC, yana-gi commented on app/controllers/api/notifications_controller.rb
> +    @notifications = @notifications.category(@target) if @target != :all
`cateogry` に `:all`を受け取れるようにしたため、後置ifを削除しました。

2021-08-20 11:34 UTC, yana-gi commented on app/controllers/api/notifications_controller.rb
> +    @target = params[:target].blank? ? :all : params[:target].to_sym
提案していただいたようにぼっち演算子を使った処理に修正しました。
targetを指定していない場合は`nil`ではなく空文字が返ってくるため、`presence`をつけました。

2021-08-20 11:34 UTC, yana-gi commented on app/models/notification.rb
> +  scope :category, lambda { |target|
`by_category`に名称変更し、`:all`を受け取れるようにしました。

2021-08-20 11:34 UTC, yana-gi commented on app/views/notifications/_tabs.html.slim
> +      - %w[all announcement mention comment check watching following_report].each do |target|
`notification.rb`に`CATEGORY_LIST`を追加し、ビューで参照するよう修正しました。

2021-08-20 11:35 UTC, yana-gi commented on app/controllers/api/notifications_controller.rb
> +                     end.order(created_at: :desc).page(params[:page])
`by_category`と同じように`notification.rb`に`by_read_status`を追加し、未読・既読の判定をモデル側で行うようにしました。

2021-08-20 11:35 UTC, yana-gi commented on app/models/notification.rb
> +    end
`notification.rb`に`TARGET_TO_KINDS`というハッシュを定義し、`target`と`kind`でマッピングを行えるようにしました。

2021-08-20 11:36 UTC, yana-gi commented on app/models/notification.rb
> +  }
上のコメントに書いたように、`notification.rb`に`TARGET_TO_KINDS`というハッシュを定義し、`target`と`kind`でマッピングを行えるようにしました。
そのためcase文をやめて`TARGET_TO_KINDS[target]`でマッピングを行うようにしました。

メソッドではなくハッシュに指定したのは、`TARGET_TO_KINDS.keys`でターゲットの一覧を取得できるようにしたためです。

2021-08-20 11:36 UTC, yana-gi commented
@cafedomancer 
レビューいただいた内容を修正したので、お時間あるときにご確認お願いします。
遅くなってしまいすみません……！

レビュー後のコミットは`@target取得処理修正 bdb7969`になります。

targetとkindのマッピング処理が自信がないので特に見ていただけると嬉しいです🙏

2021-08-23 01:20 UTC, cafedomancer reviewed
@yana-gi いくつかコメントしました！ `target=all` の部分に変更が入る場合はも model や view のコードにも変更が入りそうなので、そちらはその部分が決まってから見たいと思います。

2021-08-23 01:20 UTC, cafedomancer commented on app/controllers/api/notifications_controller.rb
> +    target = params[:target].presence&.to_sym || :all
`target=all` のところって指定しないといけない理由ってなにかあるんですっけ...？ `target` が指定されていない場合は all になるようにすればいいのかなと思ったのですが... (以下のような感じ) 。指定しないといけない理由がもしあれば教えてください！

`/notifications` すべて
`/notifications?query=unread` すべてかつ未読

2021-08-23 01:20 UTC, cafedomancer commented on app/controllers/api/notifications_controller.rb
> +    query = params[:query]
`by_read_status` で notifications を引いているので、specific にしておくならここは `query` じゃなくて `status` or `read_status` っぽい気がしました。`unread` 以外にも将来的にいろいろクエリできるようにしておきたいので `query` にしておくとかであれば `query` でもありかなと思います。issue で相談済みの設計部分っぽそうなので必要に応じて issue でやり取りしていただけると 🙏

2021-08-23 01:20 UTC, cafedomancer commented on app/models/notification.rb
> +  TARGET_TO_KINDS = {
ハッシュが扱っている集合は targets と kinds なので `TARGETS_TO_KINDS` でも良いかもしれません。あと `by_category` で使っているので `CATEGORIES_TO_KINDS` のほうが具体的な名前でよいかもしれません。

2021-08-23 01:20 UTC, cafedomancer commented on app/models/notification.rb
> +  }
```suggestion
  scope :by_category, lambda { |category|
    category ? where(kind: CATEGORIES_TO_KINDS[category]) : all
  }
```

2021-08-23 01:24 UTC, cafedomancer commented on app/views/notifications/_tabs.html.slim
> +          = link_to t("notification.#{target}"), notifications_path(query: 'unread', target: target), class: (@target == target.to_s ? ['is-active'] : []) << 'page-tabs__item-link'
class の指定が複雑なので以下のようにすると良いかもです。strip したほうがキレイになるけどなくても問題なく動くのでなくてもよいです！

```suggestion
          = link_to t("notification.#{target}"), notifications_path(query: 'unread', target: target), class: "page-tabs__item-link #{'is-active' if @target == target.to_s}".strip
```

2021-08-23 01:26 UTC, cafedomancer commented on app/views/notifications/_tabs.html.slim
> +          = link_to t("notification.#{target}"), notifications_path(query: 'unread', target: target), class: (@target == target.to_s ? ['is-active'] : []) << 'page-tabs__item-link'
(別解) こんなのでよいかも。

```suggestion
          = link_to t("notification.#{target}"), notifications_path(query: 'unread', target: target), class: [@target == target.to_s ? 'is-active' : nil, 'page-tabs__item-link']
```

2021-08-23 06:03 UTC, yana-gi commented on app/controllers/api/notifications_controller.rb
> +    target = params[:target].presence&.to_sym || :all
### 前提
現在のコードも`/notifications`のように`target`が指定されていない場合、通知は全て表示されるようになっています。

### 指定しないといけない理由
通知一覧のタブのリンクでは`target=xxx`を指定しています。
「全て」タブは`target=all`の指定をしなくても`/notifications?query=unread`で全件表示することが可能ですが、「全て」タブだけtargetを指定しない実装はすぐには思いつかない（できても複雑になりそう）なので`target=all`で指定しています。
(参考 : `/app/views/notifications/_tabs.html.slim`)

この状態で仮に`target`が何も指定されなかった場合に`:all`ではなく`nil`を格納する場合、
https://github.com/fjordllc/bootcamp/pull/3110#discussion_r693595290 で提示していただいたコードだと
`target=all`のときにエラーになるのではないかと思っています。

そのため、「全て」のタブだけ`target=xxx`を指定しない実装(`/notifications?query=unread`)ができない限りは`target`が指定されない場合は`:all`を代入する必要があると思っています。

--- 

質問の意図が汲み取れていなかったり回答が分かりにくかったらすみません……！
他にいい案などあれば教えて頂きたいです🙏

2021-08-23 06:04 UTC, yana-gi commented on app/controllers/api/notifications_controller.rb
> +    query = params[:query]
確かにそうですね！
現在komagataさんにissueで`query`と`status`どちらにするか確認中です。

2021-08-23 06:04 UTC, yana-gi commented on app/models/notification.rb
> +  TARGET_TO_KINDS = {
`CATEGORIES_TO_KINDS`に修正しました。

2021-08-23 06:04 UTC, yana-gi commented on app/models/notification.rb
> +  }
targetをcategoryに変更しました。
allの部分の変更に関してはhttps://github.com/fjordllc/bootcamp/pull/3110#discussion_r693682738 のため保留中です

2021-08-23 06:04 UTC, yana-gi commented on app/views/notifications/_tabs.html.slim
> +          = link_to t("notification.#{target}"), notifications_path(query: 'unread', target: target), class: (@target == target.to_s ? ['is-active'] : []) << 'page-tabs__item-link'
こちらの方がスッキリしますね！修正しました。

2021-08-23 06:06 UTC, yana-gi commented
@cafedomancer 
コメントありがとうございます！
コメントに回答しましたので確認していただければと思います🙏

2021-08-23 06:58 UTC, cafedomancer commented on app/controllers/api/notifications_controller.rb
> +    target = params[:target].presence&.to_sym || :all
いえわかりました！ 気になったところとしては status (旧 query) と category (旧 target) の全件取得の場合の指定方法に非対称性が生じている点です。ここは以下 2 つのマトリクスで表示方法が決まるので、いずれかもしくは両方が all の場合はそれらの指定方法は同じになっていたほうが、あとからこの部分の実装を読む人にとっては仕様を理解しやすくなるかなと思いました。

* status
  * (all) <- 全件の場合は all の指定なし
  * unread
* category
  * all <- 全件の場合は all の指定あり
  * announcement
  * mention
  * ...

そうする場合は all アリ・all ナシのどちらかに寄せる作業が必要になると思います。既存のコードに同じような処理を行っている実装がもしあるのであればそちらの実装に揃えておくのが良いかもしれません。以下は all ナシを選択した場合の実装です！

***

まず model の部分は all のときは nil を渡して scope 内で分岐するようにしました。nil じゃないときは where で、nil のときは all で通知を取ってくるようになっています。`CATEGORY_LIST` はコメントアウトしています。

```ruby
# app/models/notification.rb

# CATEGORY_LIST = [:all] + CATEGORIES_TO_KINDS.keys

scope :by_category, lambda { |category|
  category ? where(kind: CATEGORIES_TO_KINDS[category]) : all
}
```

view のほうでは all をまとめて処理するのは難しいので、そこは諦めて all を特別なケースとしてそのまま書いてみました。all を扱う必要がなくなったので `CATEGORY_LIST` だったところは代わりに `CATEGORIES_TO_KINDS.keys` を使うようにしています。

```slim
/ app/views/notifications/_tabs.html.slim

li.page-tabs__item
  = link_to t('notofication.all'), notifications_path(status: 'unread'), class: ...
- Notification::CATEGORIES_TO_KINDS.keys.each do |category|
  li.page-tabs__item
    = link_to t("notification.#{category)"), notifications_path(status: 'unread', category: category), class: ...
```

***

別の実装として、query string で all は扱わないけど view での処理はまとめたい、みたいな実装も考えてみました。こちらは表示用の category を `CATEGORIES` もしくは `CATEGORIES_FOR_DISPLAY` みたいな名前で用意して、そこに all を入れています。scope の部分は ☝️ の実装と変わらずです。

```ruby
# app/models/notification.rb

CATEGORIES_TO_KINDS = {
  ...
}
CATEGORIES = [:all] + CATEGORIES_TO_KINDS.keys # CATEGORIES_FOR_DISPLAY とかでもよいかも

scope :by_category, lambda { |category|
  category ? where(kind: CATEGORIES_TO_KINDS[category]) : all
}
```

view のほうでは model で定義した `CATEGORIES` を使って link を生成しています。ただ all のときは query string に category を指定しないみたいな分岐がどうしても入っちゃうような気がします。

```slim
/ app/views/notifications/_tabs.html.slim

li.page-tabs__item
  = link_to t('notofication.all'), notifications_path(status: 'unread'), class: ...
- Notification::CATEGORIES.each do |category|
  li.page-tabs__item
    - if category == :all
      = link_to t("notification.#{category)"), notifications_path(status: 'unread'), class: ...
    - else
      = link_to t("notification.#{category)"), notifications_path(status: 'unread', category: category), class: ...
```

2021-08-23 07:59 UTC, yana-gi commented on app/controllers/api/notifications_controller.rb
> +    target = params[:target].presence&.to_sym || :all
>  気になったところとしては status (旧 query) と category (旧 target) の全件取得の場合の指定方法に非対称性が生じている点です。ここは以下 2 つのマトリクスで表示方法が決まるので、いずれかもしくは両方が all の場合はそれらの指定方法は同じになっていたほうが、あとからこの部分の実装を読む人にとっては仕様を理解しやすくなるかなと思いました。

なるほど……！確かにstatusとcategoryでallの扱いを揃えた方が分かりやすいですね。
今回はallナシで実装しようと思います。

またクエリパラメータの`target`も`category`にした方が分かりやすいですね。
`query`の件と合わせてissueの方でkomagataさんに変更したい旨伝えておきます。

komagataさんから確認が取れ次第レビュー修正します！

2021-08-30 05:18 UTC, yana-gi commented
@cafedomancer 
毎度連絡が遅くなってしまいすみません。

以下の点を修正しました。
- `category`を使っていた変数を`target`に統一
- `query`を`status`に変更
- `target=all`の指定を廃止

修正に問題無いようであれば、変数名を途中で何度か変えたためコミットログが汚い状態になってしまったのでコミットを整理しようと思っています。

ご確認お願いします🙏

2021-08-30 05:22 UTC, cafedomancer commented
お、OK です！ 見てみます！

2021-08-30 10:24 UTC, cafedomancer requested changes
@yana-gi 大枠は OK そうです！ `query` -> `status` の修正漏れと、テストケースで 1 件確認してもらいたいものがあるので、それぞれ目を通してもらえると 🙏

2021-08-30 10:24 UTC, cafedomancer commented on app/javascript/notifications.vue
> +      default: 'all'
ここにまだ `all` が残っていそう？

2021-08-30 10:24 UTC, cafedomancer commented on app/javascript/notifications_bell.vue
> +        a.header-dropdown__footer-link(href='/notifications?query=unread') 全ての未読通知
`query` -> `status` にしたので `status` っぽそう？

```suggestion
        a.header-dropdown__footer-link(href='/notifications?status=unread') 全ての未読通知
```

2021-08-30 10:24 UTC, cafedomancer commented on app/javascript/notifications_bell.vue
> +    fetch(`/api/notifications.json?query=unread`, {
L34 と同様。
```suggestion
    fetch(`/api/notifications.json?status=unread`, {
```

2021-08-30 10:24 UTC, cafedomancer commented on app/views/notifications/_tabs.html.slim
> +      - Notification::TARGETS_TO_KINDS.each_key do |target|
おお `each_key` なんてあるんですね！ 💡

2021-08-30 10:24 UTC, cafedomancer commented on test/integration/api/notifications_test.rb
> +    get api_notifications_path(query: 'unread', format: :json)
`query` -> `status` にしたので `status` っぽそう？

```suggestion
    get api_notifications_path(query: 'unread', format: :json)
```

2021-08-30 10:24 UTC, cafedomancer commented on test/integration/api/notifications_test.rb
> +    get api_notifications_path(query: 'unread', format: :json),
L17 と同様。

2021-08-30 10:24 UTC, cafedomancer commented on test/system/answers_test.rb
> +    visit_with_auth '/notifications?query=unread', 'kimura'
`query` -> `status` にしたので `status` っぽそう？ テストが通っているのは `query=unread` だとこのパラメータの処理は controller にないので、単純にすべての通知が出るので assertion にも引っかからないって感じですかね。それ自体は挙動として特に問題ないような気がするので、`status=unread` にしたときにテストがちゃんと通っていれば OK な気がします。

```suggestion
    visit_with_auth '/notifications?status=unread', 'kimura'
```

2021-08-30 10:24 UTC, cafedomancer commented on test/system/answers_test.rb
> +    visit_with_auth '/notifications?query=unread', 'komagata'
L84 と同様。

2021-08-30 10:24 UTC, cafedomancer commented on test/system/answers_test.rb
> +    visit_with_auth '/notifications?query=unread', 'sotugyou'
L92 と同様。

2021-08-30 10:24 UTC, cafedomancer commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread', 'yamada'
`query` -> `status` にしたので `status` っぽそう？

```suggestion
    visit_with_auth '/notifications?status=unread', 'yamada'
```

2021-08-30 10:24 UTC, cafedomancer commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread', 'hatsuno'
L53 と同様。

```suggestion
    visit_with_auth '/notifications?status=unread', 'hatsuno'
```

2021-08-30 10:24 UTC, cafedomancer commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread', 'hatsuno'
L53 と同様。

```suggestion
    visit_with_auth '/notifications?status=unread', 'hatsuno'
```

2021-08-30 10:24 UTC, cafedomancer commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread', 'komagata'
L53 と同様。

```suggestion
    visit_with_auth '/notifications?status=unread', 'komagata'
```

2021-08-30 10:24 UTC, cafedomancer commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread&target=announcement', 'komagata'
L53 と同様。

```suggestion
    visit_with_auth '/notifications?status=unread&target=announcement', 'komagata'
```

2021-08-30 10:24 UTC, cafedomancer commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread', 'yamada'
このテストケースは「未読の通知ページに既読の通知が表示されないこと」をテストしているテストケースだと思うので、CI が通っちゃっているのはなにか変かもしれません。確認してもらえると良いかも。

2021-08-30 10:29 UTC, cafedomancer commented on test/system/notifications_test.rb
> +  test 'show listing notification that target is all ' do
スペースが余分に入っていそう。

```suggestion
  test 'show listing notification that target is all' do
```

2021-08-30 10:46 UTC, cafedomancer commented on test/system/notifications_test.rb
> +  end
ここのテストケースでテストしていることがよく分からず…。title の assertion があるようですが、未読の通知があると title が変わったりするんでしょうか？

2021-08-30 10:46 UTC, cafedomancer commented on test/system/notifications_test.rb
> +  end
「未読の通知を一括で開くボタン」は未読ページにあるものだと思うので、`query=unread` の状態でテストが通っているのはなにか変かもしれません。と思ってコードを見てみたのですが、`notifications.vue` の `isUnreadPage()` の判定が甘いのかもしれませんね。`query=status` でも `status=unread` でも `true` が返って来るように見えます。`location.include('status=unread')` のようにするか、`URLSearchParams` を使ってもう少し厳密なチェックにするかしたほうが良いかもしれません。https://developer.mozilla.org/en-US/docs/Web/API/Location/search

```javascript
// 雰囲気的にはたぶんこんな感じ。雰囲気なので動かないところがあるかも。
isUnreadPage() {
  const params = new URLSearchParams(location.search);
  return params.get('status') !== null && params.get('status') === 'unread'
}
````

2021-08-30 10:49 UTC, cafedomancer commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread', 'yamada'
あーこれももしかしたら https://github.com/fjordllc/bootcamp/pull/3110/files#r698380992 の関係でテストが通っちゃっているのかも？

2021-08-31 09:27 UTC, yana-gi commented on app/javascript/notifications.vue
> +      default: 'all'
`default: 'all'`を削除しました。

2021-08-31 09:28 UTC, yana-gi commented on app/javascript/notifications_bell.vue
> +        a.header-dropdown__footer-link(href='/notifications?query=unread') 全ての未読通知
`query`となっていたところをすべて`status`に修正しました。
以降のコメントは全て修正しています。（コメントいただいたものは折り畳んでいます）

2021-08-31 09:28 UTC, yana-gi commented on app/views/notifications/_tabs.html.slim
> +      - Notification::TARGETS_TO_KINDS.each_key do |target|
lintに提案してもらいました！便利ですよね〜

2021-08-31 09:28 UTC, yana-gi commented on test/system/answers_test.rb
> +    visit_with_auth '/notifications?query=unread', 'kimura'
https://github.com/fjordllc/bootcamp/pull/3110/files#r698380992 にも記載しましたが、提示していただいたコードで解決しました！

2021-08-31 09:28 UTC, yana-gi commented on test/system/notifications_test.rb
> +    visit_with_auth '/notifications?query=unread', 'yamada'
https://github.com/fjordllc/bootcamp/pull/3110/files#r698380992 にも記載しましたが、提示していただいたコードで解決しました！

2021-08-31 09:28 UTC, yana-gi commented on test/system/notifications_test.rb
> +  test 'show listing notification that target is all ' do
コメント先にも記載しましたが、提示していただいたコードで解決しました！

2021-08-31 09:28 UTC, yana-gi commented on test/system/notifications_test.rb
> +  end
修正しました。

2021-08-31 09:30 UTC, yana-gi commented on test/system/notifications_test.rb
> +  test 'show listing notification that target is all ' do
修正しました。

2021-08-31 09:33 UTC, yana-gi commented on test/system/notifications_test.rb
> +  end
こちらのテストは削除した`test/system/notification/unread_test.rb`のテストを踏襲したものです。
https://github.com/fjordllc/bootcamp/pull/3110/files#diff-44a388008b79af3f90c410dcec5d64176a4f3c339d8dc1dffd976807034fe2f7L5-L9

URLが表示できるかのテストだと認識しています。

2021-08-31 09:35 UTC, yana-gi commented on test/system/notifications_test.rb
> +  end
例示していただいたコードで修正したところ、
`query=status`では未読一覧で表示されないことを確認しました。
例示いただき助かりました！

2021-08-31 09:36 UTC, yana-gi commented
`query`から`status`への修正が大幅に漏れしてしまいすみません……！
コミットログが整理できてないせいだと思ったのでコミット修正も含めて修正しましたのでご確認お願いしますー！

2021-08-31 09:39 UTC, cafedomancer commented
お疲れさまです！見ます〜 👀

2021-08-31 11:30 UTC, cafedomancer commented on test/system/notifications_test.rb
> +  end
なるほどわかりました！

2021-08-31 11:34 UTC, cafedomancer approved these changes
LGTM! レビューが長引いてしまって申し訳ないなと思う一方で、より良い設計やコードにしていただけたと思うので、その点は良かったなと思いました！

2021-09-01 01:39 UTC, yana-gi commented
@cafedomancer 
とても丁寧に見ていただいて感謝しかないです……！
見違えるほどコードが良くなりましたし、とても勉強になりました😄
ありがとうございました〜！

@komagata 
こちらレビューお願いします🙏

2021-09-04 04:45 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-04 04:46 UTC, komagata commented
@machida こちら、デザイン面をご確認いただければ〜

2021-09-06 07:38 UTC, machida commented
了解ですー！！

2021-09-06 08:02 UTC, machida commented
@yana-gi 

おまたせしました！
デザイン入れましたー

![image](https://user-images.githubusercontent.com/168265/132182011-34772248-dd4a-4582-a729-e6e0529b267d.png)

2021-09-07 01:37 UTC, yana-gi commented
@machida 
デザイン入れありがとうございますー！
画面もコードも確認しました。
自分では特に修正する点がないのでマージお願いします🙆‍♂️

2021-09-07 06:19 UTC, merged

2021-09-07 06:19 UTC, komagata commented
@yana-gi マージしました〜