提出物に提出者最終コメント日時とメンター最終コメント日時を追加する
fjordllc/bootcamp pull request #3111
Opened 2021-08-10 04:56 UTC by Daichi831

2021-08-11 08:54 UTC, machida commented
📝 
メンターか本人どちらか最終のコメントだけを出すように変更になった

2021-08-19 08:56 UTC, Daichi831 commented
@yamadaab 
こちらお時間あるときにレビューをよろしくお願いします！🙇‍♂️

2021-08-22 22:51 UTC, yamadaab commented
> @yamadaab
> こちらお時間あるときにレビューをよろしくお願いします！🙇‍♂️

確認が遅れて申し訳ありません。本日中にレビュー致します🙇‍♂️

2021-08-23 00:39 UTC, yamadaab approved these changes

2021-08-23 00:40 UTC, yamadaab commented
@Daichi831 

遅くなりすみません。大丈夫だと思います！

2021-08-23 04:35 UTC, Daichi831 commented
@yamadaab 
お忙しい中、ありがとうございます😭

@komagata 
こちら確認をよろしくお願いします🙇

2021-08-23 14:02 UTC, komagata commented
@Daichi831 すみません、僕としては、二つのカラムを追加するのは、一覧の表示を早くするのに必要なのでお願いしたいと思っていました。

ですので、見た目上の表示を増やすというのは考えていませんでした。

こちらは @machida さんと話してそうなった感じですかね？

2021-08-24 03:24 UTC, Daichi831 commented
@komagata 
先々週のミーティングの際にカラムを2つとも表示させていたのですが、情報量が多くなってしまうとのことでメンターか提出者のどちらか最新を出すようになりました。
駒形さんとしては表示までは考えていなかったということでしょうか？

2021-08-24 06:10 UTC, Daichi831 commented
最終コメント日時の表示はそのままで進めることになりました。

2021-08-24 07:00 UTC, Daichi831 commented
@machida 
こちらデザインをよろしくお願いします！🙇‍♂️

2021-09-06 06:48 UTC, machida commented
@Daichi831 @komagata デザイン入れました。提出物個別ページには最終コメントを出さないようにしましたー。
テストが通ったらマージしますー

2021-09-06 08:34 UTC, machida commented
テスト通ったのでマージしますー

2021-09-06 08:35 UTC, machida commented
あ、まだレビューが通ってなかった。

@komagata レビューお願いします。
表示はほとんど同じで、最後のコメント日時のデータを今回作ったものを使うようにしました。

2021-09-06 10:25 UTC, komagata requested changes

2021-09-06 10:25 UTC, komagata commented on app/models/comment_callbacks.rb
> +    # 最新日時を上書きする
コメントを入れるのであれば同じ意味のメソッドとしてしまうのがわかりやすいかもです〜

2021-09-06 11:09 UTC, Daichi831 commented on app/models/comment_callbacks.rb
> +    # 最新日時を上書きする
こちら最終日時のリセット部分はメソッドにしました〜

2021-09-06 12:40 UTC, Daichi831 commented
@machida 
ありがとうございます😊
＠komagata
こちら確認をよろしくお願いします🙇

2021-09-08 11:25 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-08 11:25 UTC, merged