ブックマークをプロフィールのメニューからタブ内へ移動
fjordllc/bootcamp pull request #3124
Opened 2021-08-11 15:42 UTC by sota-onozuka

# やったこと
#2909  プロフィールをクリックした際に表示されるブックマークを、ダッシュボード内のタブに移動しました。
合わせて、URLも/bookmarksから/current_user/bookmarksに変更しました。

before
![129057774-4620822e-b51f-4034-b4cc-dbfe6e8c74ef](https://user-images.githubusercontent.com/63279587/129059884-2409f286-071a-448a-9af4-b59bbd292ac9.png)

after
![129057890-df19bb91-79ad-415c-9e6d-ae7c02e46cb5](https://user-images.githubusercontent.com/63279587/129059902-f45508f1-2ad1-454c-b04d-48bdb7765b5a.png)

![129058134-3af0447f-2092-4ee3-8b2f-6a4d9e7eef20](https://user-images.githubusercontent.com/63279587/129059918-0979b205-dae4-4658-882a-26b6b9239c42.png)

# 確認してほしい事
- 機能の確認
1. ダッシュボード内にブックマークタグが存在するか
2. プロフィールのアイコンクリック時のメニューバーから、ブックマークが削除されているか
3. ダッシュボードのブックマークタブをクリック時、ブックマークがきちんと表示されるか
4. ダッシュボードのブックマークタブをクリック時、URLが/current_user/bookmarksで始まるルーティングになっているか

- コードの確認
おかしなコードが存在しないか

2021-09-04 04:50 UTC, komagata requested changes

2021-09-04 04:50 UTC, komagata commented on app/controllers/current_user/bookmarks_controller.rb
> +  end
このメソッドがどこからも使われてないかも？

2021-09-04 04:50 UTC, komagata commented on app/controllers/current_user/bookmarks_controller.rb
> +  def set_user
indexメソッドしかないのであれば別途メソッドを定義せず、

```
def index
  @user = current_user
end
```

でいいかも？

2021-09-04 11:57 UTC, masamune17 commented on app/controllers/current_user/bookmarks_controller.rb
> +  end
使用されていなかったので削除いたしました。

2021-09-04 12:00 UTC, masamune17 commented on app/controllers/current_user/bookmarks_controller.rb
> +  def set_user
別途メソッドを定義せず、変数をindexメソッド内で宣言するように変更いたしました。

2021-09-04 13:22 UTC, masamune17 commented
@komagata さんご指摘箇所を修正いたしました
こちらレビューをお願いいたします

2021-09-05 04:55 UTC, komagata requested changes

2021-09-05 04:55 UTC, komagata commented on app/controllers/current_user/bookmarks_controller.rb
> +    @user = current_user
👍

2021-09-05 04:55 UTC, komagata commented on app/views/home/_page_tabs.html.slim
> +      - if !user.staff? || user.bookmarks.present?
スタッフじゃないって条件はなんであるんでしたっけ？

2021-09-05 08:33 UTC, masamune17 commented on app/views/home/_page_tabs.html.slim
> +      - if !user.staff? || user.bookmarks.present?
[同じような処理](https://github.com/fjordllc/bootcamp/blob/main/app/views/home/_page_tabs.html.slim)をしている過去の機能を参考にスタッフじゃないという条件をつけていました。

しかし、ファイルのコミットを遡って確認した結果、`自分の日報`のタブが一番最初に機能として追加され、その際に`スタッフじゃない場合`という条件が付与されていて、その後それに倣って`自分の提出物`、`自分のWatch中`も同じ条件で実装していたようです。

したがって、機能的に考えた場合`自分の日報`と`自分の提出物`には`スタッフじゃない場合`という条件があって妥当ですが、`自分のWatch中`と`自分のブックマーク`には不必要な条件ですので条件を削除したいと思います。

今回のissueの範疇を超えますが、`自分のWatch中`の条件式も変更してよろしいのでしょうか？

2021-09-06 10:17 UTC, komagata commented on app/views/home/_page_tabs.html.slim
> +      - if !user.staff? || user.bookmarks.present?
@masamune17 git blameでその行を実装した人と連絡をとって理由を聞いたりしてみてください〜

2021-09-08 19:02 UTC, masamune17 commented on app/views/home/_page_tabs.html.slim
> +      - if !user.staff? || user.bookmarks.present?
@komagata
連絡をとって理由を確認いたしました。
Watchしている物がない場合は、`管理者、メンター、アドバイザー`の方にタブを表示する必要が不要だと判断されたそうです。

一理あるのでこのisuueでも`スタッフじゃない`という条件をつけるようにします。

2021-09-13 06:47 UTC, masamune17 commented
@komagata さんご指摘箇所を修正いたしました
こちらレビューをお願いいたします

2021-09-13 18:15 UTC, komagata commented on app/views/home/_page_tabs.html.slim
> +      - if !user.staff? || user.bookmarks.present?
@masamune17 なるほど〜。ブックマーク機能はスタッフかどうか関係ない機能なので、その条件は外しちゃってください〜

2021-09-14 05:50 UTC, masamune17 commented on app/views/home/_page_tabs.html.slim
> +      - if !user.staff? || user.bookmarks.present?
@komagata ダッシュボードにブックマークタブを表示する条件から、`スタッフじゃない`という条件を削除いたしました。

2021-09-21 05:37 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-21 05:37 UTC, merged