管理者だけでなくメンターもプラクティスの編集をできるように変更
fjordllc/bootcamp pull request #3132
Opened 2021-08-14 09:02 UTC by makiichikawa

ref #3052

メンターがプラクティスを修正できるように対応いたしました。

## 対応内容

1. プラクティス個別ページの編集ボタンをメンターでも表示できるようにした
##### 変更前
![PC性能の見方を知る___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/57123982/129440779-01ecac31-de78-4864-9bf2-18a03ea4af56.png)

##### 変更後
![PC性能の見方を知る___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/57123982/129440787-99a3c319-a803-4716-bc5e-81d4a5d4f0e5.png)

2. 編集、更新処理前のログインチェックを管理者またはメンターでログインしているかに変更

2021-08-15 00:23 UTC, makiichikawa commented
@gentamura 
こちらのレビューお願いできますでしょうか？
お盆休み明けにお手すきの際にお願いできればと思っております🙇🏼‍♂️

2021-08-15 02:58 UTC, gentamura commented
[nits] 要件外ですが、同じ領域の部分なので、 `current_user.mentor? || current_user.admin?`  を `current_user.admin_or_mentor?`すると良いなーと思いました！

https://github.com/fjordllc/bootcamp/blob/fa03f73db498d943841b62147bb381a103449858/app/views/practices/show.html.slim#L138-L155

2021-08-15 02:58 UTC, gentamura approved these changes
LGTM w/ nits 👌

2021-08-15 05:43 UTC, makiichikawa commented
@gentamura 
レビューありがとうございました。
メンター向けメモの枠と管理者メニューの表示条件が一緒になったという点では、要件外ではないのかなと思い、修正しました。
ご指摘いただき、ありがとうございました🙇🏼‍♂️

@komagata 
こちらのレビューお願いできますでしょうか。よろしくお願いいたします🙇🏼‍♂️

2021-08-16 16:10 UTC, komagata requested changes

2021-08-16 16:10 UTC, komagata commented on test/system/practices_test.rb
> +    visit "/products/#{product.id}"
最後のassertの後にvisitでページ移動しても意味ないかも？

2021-08-17 13:53 UTC, makiichikawa commented on test/system/practices_test.rb
> +    visit "/products/#{product.id}"
@komagata 

プラクティスのページをvisitして、タイトルが更新されているか確認するように変更しました。
お手数をおかけしますが、再度確認お願いいたします🙇🏼‍♂️

2021-09-08 13:49 UTC, komagata approved these changes
確認漏れていて申し訳ないです。確認しました、OKですー🙆‍♂️

2021-09-08 13:49 UTC, merged