分報URLとしてチャンネルURLを登録できるようにする
fjordllc/bootcamp pull request #3139
Opened 2021-08-16 16:37 UTC by rikuba

Ref: #3101

## 変更点

現在、分報URLにはDiscordの招待URLを登録することになっています。招待URLは、OS環境やDiscordアプリのインストール状況等によってはチャンネルを直接開けないため、分報URLとしてチャンネルURLを登録できるように変更しました。チャンネルURLの場合、常にアプリではなくブラウザでチャンネルが開かれます。

また、登録情報変更ページに分報URLの取得方法の説明も追加しました。チャンネルURLではなくメッセージURLの取得方法の説明になっていますが、`CurrentUserController`にメッセージURLをチャンネルURLに変換する処理を追加したため、メッセージURLを入力してもチャンネルURLがデータベースに保存されるようになっています。DiscordアプリにおいてチャンネルURLを直接コピーする方法が（おそらく）無いことから、このような形を採っています。

既に招待URLを登録されているユーザが居られるため、招待URLのバリデーションも残しています。Discord APIを用いて既存の招待URLをチャンネルURLに変換しようと考えていましたが（[日報](https://bootcamp.fjord.jp/reports/36211)）、ローカルのテスト実行でレートリミットに達したため、本番環境で行うのは難しいと思い断念しました。

### 参考：各URLの例

<dl>
<dt>招待URL
<dd><code>https://discord.gg/UXUFbKXnXU</code>
<dt>チャンネルURL
<dd><code>https://discord.com/channels/715806612824260640/867709982786191360</code>
<dt>メッセージURL
<dd><code>https://discord.com/channels/715806612824260640/867709982786191360/872058000209248257</code>
</dl>

2021-08-17 04:53 UTC, rikuba commented
@komagata

レビューの前ですが、このPRの方針について相談させてください🙏

Discord APIを使って`times_url`をデータマイグレーションすることで、招待URLからチャンネルURLに完全に移行しようと考えておりましたが、[レートリミット](https://discord.com/developers/docs/topics/rate-limits)の関係で難しいことが分かりました（ローカル環境でテストしたところ、50件程度で24時間待ちになりました）。

そのため、このPRではチャンネルURLと招待URLのどちらでも設定できる状態にして、プレースホルダーやヘルプでチャンネルURLの登録を促す形に変更しました。

<details>
<summary>ヘルプのスクリーンショット</summary>
<img src="https://user-images.githubusercontent.com/350435/129600916-311579b5-9dd9-4fa7-b494-b7247b78707d.png">
</details>

このような方針で問題がないか、ご意見いただけますと幸いです🙇‍♂️

2021-08-18 14:52 UTC, komagata commented
@rikuba 

> そのため、このPRではチャンネルURLと招待URLのどちらでも設定できる状態にして、プレースホルダーやヘルプでチャンネルURLの登録を促す形に変更しました。

こちらでいいとおもいます。

こちら、@machida さんはいかがでしょうか？

2021-08-24 10:02 UTC, rikuba commented
@komagata 

ありがとうございます。
現行の状態で検討しようと思います。

@machida 

こちらのPRの実装方針についてご確認いただけますと幸いです。

2021-09-03 11:56 UTC, machida commented
@rikuba @komagata 
それでいいと思いますー。
もし、招待URLのままのユーザーがいたら、Adminではそれがわかる状態にしてもらえると（Admin管理画面からなどで）、Adminが手動で修正ができるので助かりそうですー。

2021-09-04 07:14 UTC, rikuba commented
@machida @komagata 
ご確認ありがとうございます!

> 招待URLのままのユーザーがいたら、Adminではそれがわかる状態に

この点に関しまして、Admin管理画面のユーザー一覧のDiscord列に文言を追加するような形で問題ないでしょうか。

実装イメージ
![/admin/users.png](https://user-images.githubusercontent.com/350435/132086106-be8c0b3c-056a-4965-9420-51d97f27f795.png)

2021-09-04 12:10 UTC, machida commented
@rikuba 提案ありがとうございます！それでお願いしますー👍

2021-09-05 05:57 UTC, rikuba commented
@cafedomancer 
このPRのレビューをお願いできますでしょうか🙏

2021-09-06 07:17 UTC, cafedomancer reviewed
質問いくつかあるので回答おねがいします！

2021-09-06 10:58 UTC, rikuba commented on app/models/user_callbacks.rb
> +    user.times_url = match[0] if match
分報URLとしてメッセージURLが入力されたときのことを考慮して、チャンネルURLの形になるように変換しています。

<dl>
<dt>メッセージURL
<dd>https://discord.com/channels/715806612824260640/867709982786191360/872058000209248257
<dt>チャンネルURL
<dd>https://discord.com/channels/715806612824260640/867709982786191360
</dl>

Discord、ユーザが直接チャンネルURLを取得する方法がないようなので、簡単に取得できるメッセージURLの入力を促す形にしています。

<details>
<summary>スクリーンショット</summary>
<img src="https://user-images.githubusercontent.com/350435/129600916-311579b5-9dd9-4fa7-b494-b7247b78707d.png">
</details>

もっといい方法があればとは思うのですが🤔

2021-09-06 10:58 UTC, rikuba commented on app/helpers/users_helper.rb
> +  def user_discord_invite_url?(user)
UserDecoratorに移しました!

2021-09-06 10:58 UTC, rikuba commented on app/helpers/users_helper.rb
> +    user.times_url&.start_with?('https://discord.gg/') || false
`false`を直接書くのは違和感があったのでdouble-bangにしました!

2021-09-06 10:58 UTC, rikuba commented on db/fixtures/users.yml
> -  times_url: https://discord.gg/daimyo-times
#3020 で`times_url`のテストデータを追加したのですが、テストで使用するのは一部なのに追加しすぎてしまい、分報に仕様変更があったときに修正するのが大変だと思ったため削除しました😓

2021-09-06 11:01 UTC, rikuba commented
@cafedomancer 
レビューありがとうございます!
質問の回答と、コードの修正を行いました。
また、管理画面のユーザー一覧のテストが抜けていたため、1つテストを追加しております🙇‍♂️

2021-09-08 02:58 UTC, cafedomancer commented on app/models/user_callbacks.rb
> +    user.times_url = match[0] if match
あーなるほど。いまの正規表現だとどういう URL が入ってくるかという全体像を把握するのが難しいので、キャプチャと数量詞を使ってメッセージ URL が入ってきてかつその URL のメッセージ ID を落とすことを表現してあげたほうが分かりやすくなるかなと思いました。

```ruby
%r{\A(https://discord.com/channels/\d+/\d+)(?:/\d+)?\z}
```

![image](https://user-images.githubusercontent.com/7645585/132438751-9b48e7da-bda9-4f9b-9b7f-906055582240.png)

https://regexper.com/#%2F%5E%28https%3A%5C%2F%5C%2Fdiscord%5C.com%5C%2Fchannels%5C%2F%5Cd%2B%5C%2F%5Cd%2B%29%28%3F%3A%5C%2F%5Cd%2B%29%3F%24%2F

キャプチャの取得は match でも slice でも好きな方法で良いと思います！

```ruby
pp 'https://discord.com/channels/715806612824260640/867709982786191360/872058000209248257'.match(%r{\A(https://discord.com/channels/\d+/\d+)(?:/\d+)?\z}).captures.first
pp 'https://discord.com/channels/715806612824260640/867709982786191360'.match(%r{\A(https://discord.com/channels/\d+/\d+)(?:/\d+)?\z}).captures.first

pp 'https://discord.com/channels/715806612824260640/867709982786191360/872058000209248257'.slice(%r{\A(https://discord.com/channels/\d+/\d+)(?:/\d+)?\z}, 1)
pp 'https://discord.com/channels/715806612824260640/867709982786191360'.slice(%r{\A(https://discord.com/channels/\d+/\d+)(?:/\d+)?\z}, 1)
```

2021-09-08 03:01 UTC, cafedomancer commented on db/fixtures/users.yml
> -  times_url: https://discord.gg/daimyo-times
あーなるほど。わかりました！

2021-09-08 03:03 UTC, cafedomancer commented on app/models/user_callbacks.rb
> +    match = user.times_url&.match(%r{\Ahttps://discord.com/channels/\d+/\d+})
もしかして discord.com のドットもエスケープしておかないといけない...？パッと分からなかったのでちょっと調べてみてください！

2021-09-08 03:06 UTC, cafedomancer commented on app/decorators/user_decorator.rb
> +  end
ここのテストもあると安心かなと思いました。must ではないのでやれたらやるという感じでだいじょぶです！

2021-09-08 03:13 UTC, cafedomancer commented on test/models/user_test.rb
> +  test 'times_url is channel url even if message url is passed' do
メッセージ URL が指定された場合は times_url はチャンネル URL に変換される、みたいな感じでどうでしょうか。times_url is channel url だと変換処理が行われることがちょっと伝わりにくいなと思ったからです。

times_url should be converted to a channel url if a message url is specified
times_url is converted to a channel ulr if a message url is specified

2021-09-08 03:17 UTC, cafedomancer reviewed
@rikuba 正規表現のところについてコメントしているので確認をおねがいします〜！あとは nits なので修正はおまかせします 🙏

2021-09-08 13:47 UTC, rikuba commented on app/models/user_callbacks.rb
> +    user.times_url = match[0] if match
想定する入力の全体像を把握しやすい正規表現にするというのは意識していませんでした。
後から見たときに意図が分かりやすそうです! 正規表現を書き換えました。

(今回は`match`を使いましたが、String#sliceと正規表現の組み合わせは知らなかったので覚えておきます✍️
ありがとうございます)

2021-09-08 13:47 UTC, rikuba commented on app/models/user_callbacks.rb
> +    match = user.times_url&.match(%r{\Ahttps://discord.com/channels/\d+/\d+})
ご指摘ありがとうございます。エスケープ抜けていました😓

2021-09-08 13:47 UTC, rikuba commented on app/decorators/user_decorator.rb
> +  end
`UserDecoratorTest`に`discord_invite_url?`のテストを追加しました!

2021-09-08 13:48 UTC, rikuba commented on test/models/user_test.rb
> +  test 'times_url is channel url even if message url is passed' do
「変換(convert)」を交えた方が意図が分かりやすくなりますね。
最初の案を採使わせていただきました。ありがとうございます!

2021-09-08 13:49 UTC, rikuba commented
@cafedomancer 
再レビューありがとうございます!
ご指摘いただいた点を修正しました。お手隙の時にご確認お願い致します🙏

2021-09-08 23:38 UTC, cafedomancer commented on app/models/user_callbacks.rb
> +    match = user.times_url&.match(%r{\A(https://discord\.com/channels/\d+/\d+)(?:/\d+)?\Z})
行末のマッチはスモールゼット `\z` ですかね？改行が入る可能性があり、それを無視したいのではればラージゼット `\Z` でも良いのですが...。ユースケースに適している方を選んでいて、タイポでないということであれば全然 OK です 🙆 

```suggestion
    match = user.times_url&.match(%r{\A(https://discord\.com/channels/\d+/\d+)(?:/\d+)?\z})
```

2021-09-08 23:49 UTC, cafedomancer commented on app/models/user.rb
> +              with: %r{\Ahttps://discord\.(?:com|gg)/},
最初に指摘し忘れちゃったというか https://github.com/fjordllc/bootcamp/pull/3139/files#r704846931 のコメントを書いていて気付いたのですが、この正規表現だと空白ありの URL にもマッチしてしまいそうですね。.com と .gg 以降の文字列も含めて行末までマッチさせておいたほうが安心かなと思いました。空白を含んでいるのがダメだからたぶんラージエス `\S` を使うと良いんですかね？使われる文字列が限られているならスモールダブリュー `\w` (`[a-zA-Z0-9_]`) とか文字クラスを明示するのでも良いと思います。改行は入っていてはいけないので行末のマッチはスモールゼット `\z` ですかね。念のためテストも追加しておいてもらえるとより安心です 🙇 

```suggestion
              with: %r{\Ahttps://discord\.(?:com|gg)\S+\z/},
```

![image](https://user-images.githubusercontent.com/7645585/132599951-0215f0a1-18a9-4fc8-b905-7f1ed6030cc9.png)

```suggestion
              with: %r{\Ahttps://discord\.(?:com|gg)\w+\z/},
```

![image](https://user-images.githubusercontent.com/7645585/132599971-809194c2-cba5-4718-9939-3ad85b6d1a22.png)

```suggestion
              with: %r{\Ahttps://discord\.(?:com|gg)[a-zA-Z]+\z/},
```

![image](https://user-images.githubusercontent.com/7645585/132600007-17f04ad1-bcd3-4d03-be72-63d0dc83136b.png)

ホスト名の後ろにスラッシュが入るのが確実であればそれも入れてしまってもいいかなと思います。

```suggestion
              with: %r{\Ahttps://discord\.(?:com|gg)/\w+\z/},
```

![image](https://user-images.githubusercontent.com/7645585/132600062-9f6405fc-5211-476b-89a0-74a9908dd714.png)

2021-09-08 23:50 UTC, cafedomancer commented on app/models/user_callbacks.rb
> +    match = user.times_url&.match(%r{\A(https://discord\.com/channels/\d+/\d+)(?:/\d+)?\Z})
https://github.com/fjordllc/bootcamp/pull/3139/files#r704850760 で改行を含まないようにスモールゼット `\z` を使うのであればこちらもスモールゼット `\z` にしておくのが良いですかね。

2021-09-08 23:51 UTC, cafedomancer reviewed
@rikuba 何度もすみません...！正規表現のところで調整が必要な箇所がまた出てきたので確認してもらいたいです 🙏

2021-09-12 02:50 UTC, rikuba commented on app/models/user_callbacks.rb
> +    match = user.times_url&.match(%r{\A(https://discord\.com/channels/\d+/\d+)(?:/\d+)?\Z})
`\A`との対応で`\Z`を使ってしまっていました🤯
どちらも`\z`に修正しました。

2021-09-12 02:50 UTC, rikuba commented on app/models/user.rb
> +              with: %r{\Ahttps://discord\.(?:com|gg)/},
comの場合（チャンネルURL／メッセージURL）とggの場合（招待URL）でパスの形式が異なるため、分岐させる形の正規表現になりました。
末尾改行の有無と、末尾スラッシュの有無の[テスト](https://github.com/fjordllc/bootcamp/pull/3139/commits/bd39e049b83685c8e104ec0041336e76a3c6338e#diff-91bef9fda3c55514e23a4a8edba948f68aad59b57951adcff0b11e9ea9159854)を追加しました。
![image](https://user-images.githubusercontent.com/350435/132969623-468938c7-5aba-424b-9d3a-a6ca2e64b4e8.png)

2021-09-12 02:50 UTC, rikuba commented
@cafedomancer 
しっかりチェックしていただきありがとうございます!
正規表現を修正しました。お手数ですが改めてご確認のほどお願いいたします。

2021-09-13 03:01 UTC, cafedomancer commented
見ます〜 👀

2021-09-13 03:12 UTC, cafedomancer approved these changes
よさそうです〜 🙆

2021-09-13 03:58 UTC, rikuba commented
@cafedomancer 
レビューありがとうございました!

@komagata 
こちらのレビューをお願いいたします🙏

2021-09-13 18:12 UTC, komagata commented
@rikuba これって、以前の間違ってたURLを機械的に正しいURLに直すことはできますか？

2021-09-14 00:52 UTC, rikuba commented
@komagata

以下のようなコードで招待URLからチャンネルURLを機械的に取得できます（Discordの[Invite Resource API](https://discord.com/developers/docs/resources/invite)を使っています）。

```ruby
require 'json'
require 'net/http'
require 'uri'

def fetch_channel_url(invite_url)
  match = invite_url.match(%r{\Ahttps://discord.gg/(\w+)})
  return if match.nil?

  invite_code = match[1]
  uri = URI("https://discord.com/api/invites/#{invite_code}")
  res = Net::HTTP.get_response(uri)
  # p res.class
  #   取得できた場合 Net::HTTPSuccess
  #   無効な招待URLの場合 Net::HTTPNotFound
  #   レートリミットに達した場合 Net::HTTPTooManyRequests
  return unless res.is_a?(Net::HTTPSuccess)

  data = JSON.parse(res.body)
  "https://discord.com/channels/#{data['guild']['id']}/#{data['channel']['id']}"
end

p fetch_channel_url('https://discord.gg/UXUFbKXnXU')
# => "https://discord.com/channels/715806612824260640/867709982786191360"
# 無効な招待URLの場合/レートリミットに引っかかった場合 => nil
```

手元で1秒`sleep`を挟んでループ処理してみたのですが、`Authorization`ヘッダの有無にかかわらず、およそ50件で1日あたりのレートリミットに達する（`Too Many Requests`が返る）ようです。

本番環境ではこれに引っかかるのではないかと危惧していたのですが、今ユーザー一覧から分報URLを登録しているユーザー数をカウントしてみると、おそらく30人程度(?)なので、1日分のレートリミットでも足りるかもしれません。

2021-09-14 04:33 UTC, komagata commented
@rikuba なるほど、ご説明ありがとうございます。（機械的にはできないと僕が思い込んでいました）

機械的に変換できるのであれば、Rakeタスクやdata migrationなどで一括して古いデータを変換してしまいたいですね。（そしてそのコードをこのPRに含めたい）

2021-09-15 05:09 UTC, rikuba commented
@komagata 

data-migrationファイルを追加しました。
また、データ変換のテスト用に`komagata`のユーザーデータにkomagataさんの、`muryou`のユーザーデータに私rikubaの招待URLを追加しました。

`db:reset`した上で以下のコマンドを実行すると、それぞれのユーザーデータの`times_url`がチャンネルURLに変換されます。

```sh
$ rake data:migrate:up VERSION=20210915021559
```

data-migrationファイルにつきまして、実行時間が長くなるのは良くないと思い、ループごとに`sleep`は挟んでいません。Invite Resource APIは短い時間でのレートリミットは設けられていないようですので、順次アクセスであれば`sleep`を挟まなくても問題ないと判断しました。

---

お手隙の際に、実装方法等に問題がないかご確認のほどお願いいたします🙇‍♂️

2021-09-16 10:50 UTC, rikuba commented
MEMO: 昨日のミーティングで、データマイグレーションで既存の分報URLを変換し、デプロイ後はすべて分報URL=チャンネルURLの状態にする方針になりました。validationなどコードを修正します。

2021-09-17 05:01 UTC, rikuba commented
@komagata

データマイグレーションの追加と、データの移行が完了することを前提としたコード修正を行いました。

- `User#times_url`のvalidationをチャンネルURLのみを受け入れるように変更
- 管理画面のユーザー一覧で、招待URLを登録しているユーザを判別できるようにする機能（[コメント#912925010](https://github.com/fjordllc/bootcamp/pull/3139#issuecomment-912925010)）を削除

---

分報URLを登録しているユーザー数ですが、フィヨルドブートキャンプ内でブラウザの開発者ツールから以下のコードを実行して確認しています。現時点で26人でした。

```javascript
users = await (async (delay) => {
  let page = 1;
  let totalPages = 0;
  let users = [];
  do {
    console.log(`Page ${page}`);
    const data = await fetch(`/api/users?target=all&page=${page}`).then((res) => res.json());
    totalPages = data.totalPages;
    users = users.concat(data.users);
    await delay(1000);
  } while (page++ < 2);
  return users;
})(
  (ms) => new Promise((resolve) => setTimeout(resolve, ms))
);

users.filter((user) => user.times_url).length; //=> 26
```

分報URLを登録しているユーザーの中で、期限付きの招待URLを登録していて、既にその招待URLが無効になっている方が複数居られました。その場合、`times_url`は`nil`になるようにしています。

---

このままkomagataさんにレビューをお願いしてよろしいでしょうか。

2021-09-18 14:05 UTC, sinsoku commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +      user.update!(times_url: channel_url)
処理が複雑なのでUserクラスのメソッドにした後、テストコードを追加した方が良いと思いました。
あと、  [reset_column_information](https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-reset_column_information) を呼んでおいた方が良いです。
参考: [migration の中で model を触ったら必ず reset_column_information する](https://blog.onk.ninja/2017/10/18/use_reset_column_information)

おそらく、こんな感じのマイグレーションになる。

```ruby
def up
  User.where.not(times_url: nil).find_each do |user|
    user.convert_to_channel_url!
  end

  User.reset_column_information
end
```

2021-09-18 14:55 UTC, rikuba commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +      user.update!(times_url: channel_url)
@sinsoku 

レビューありがとうございます!

> 処理が複雑なのでUserクラスのメソッドにした後、テストコードを追加した方が良いと思いました。

「招待URLをチャンネルURLに変換する処理」はマイグレーション後は使う機会がないため、Userモデルにメソッドを残すのはよくないのかなと思いました。

後のPRでそのメソッドを削除するという手もありますが、そうすると存在しないメソッドを呼んでいるマイグレーションファイルが残ることになるので、やはりマイグレーション内で完結させた方がよいのかなと思うのですが、いかがでしょうか。

ただ、いずれにせよテストは用意すべきですね😓

> あと、 reset_column_information を呼んでおいた方が良いです。

全く意識していなかったので、参考リンクも併せて勉強になりました。ありがとうございます!

2021-09-18 15:34 UTC, sinsoku commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +      user.update!(times_url: channel_url)
@rikuba 
マイグレーションの中の処理に対してテストを書けそうであれば、今のままでも良いかも。
モデルのメソッドにするのを提案したのは、この方がテストしやすそうかなーと思ったからなので。

2021-09-18 15:38 UTC, sinsoku commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +      user.update!(times_url: channel_url)
すみません、 `db/migrate` と勘違いしていました。
data migration だと、実行中にカラムの追加・削除が起きないため `reset_column_information` は不要そうです。

2021-09-19 06:41 UTC, rikuba commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +      user.update!(times_url: channel_url)
@sinsoku 

ご返信ありがとうございます!
メソッド化の提案の意図、`reset_column_information`が必要な場面について理解いたしました。

今回は実装はそのままで、マイグレーションに対するテストを追加しました。
お手すきの際にご確認いただけますでしょうか🙏

2021-09-20 02:30 UTC, sinsoku commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +      user.update!(times_url: channel_url)
良さそうです！

2021-09-20 03:20 UTC, rikuba commented
@sinsoku
レビューありがとうございました!

@komagata 
データマイグレーションの追加と、それに伴うコード修正を行いました。
お手すきの際にレビューお願いいたします🙏

2021-09-21 06:28 UTC, komagata requested changes

2021-09-21 06:28 UTC, komagata commented on app/models/user.rb
> +  def times_url=(url)
これは今回一回だけ必要な処理だと思います。
それが今後ずっとtimes_urlの代入にあると事故が起こりそうなのでdata migrate時だけにしたいっすね。

コードを読む他人にとって、setterの上書きは特に自然に見えちゃうので副作用があるということを予想するのが難しいので気をつける必要があります〜。

2021-09-23 05:00 UTC, komagata commented on app/models/user.rb
> +  def times_url=(url)
times_urlの代入処理を上書きしているということは、このアプリのどこからでもこの処理が走るということになります。

全然関係ないページ・処理の時にもこの変換が入ることになりますが、代入する方は「代入したい」ということしか考えていないため、裏でこういう処理が走っていることを想像するのは非常に難しいので思わぬ罠になります。

常に必要になる処理以外はControllerなどそのページ・処理だけで行った方が良いと思います。

2021-09-23 13:37 UTC, rikuba commented on app/models/user.rb
> +  def times_url=(url)
@komagata 

> 間違った形（メッセージURL）を今後も入力お願いするようになっているという意味でしょうか？

はい。ユーザーの入力のしやすさを優先してそのような形になっておりました。

> だとしたら最終的な正しい形（チャンネルURL？）を促す形にしたいです。

承知いたしました。ヘルプの文面にチャンネルURLへ書き換える手順を書き足しました。

> 代入する方は「代入したい」ということしか考えていないため、裏でこういう処理が走っていることを想像するのは非常に難しいので思わぬ罠になります。

ご説明ありがとうございます。setterの上書きの問題点について理解いたしました。他の開発者の方が触ったときの視点が欠けていたと思います。Model側ではなくController側で変換処理を行うようにコードを修正しました。

ヘルプの文面や、Controllerでの変換処理の書き方に問題がないかご確認いただけますでしょうか🙏
（メッセージURLをそのまま入力する方を想定して変換処理を残していますが、必要ないというご判断があれば変換処理は削除いたします）

2021-09-25 13:31 UTC, komagata commented on app/models/user.rb
> +  def times_url=(url)
@rikuba 

> はい。ユーザーの入力のしやすさを優先してそのような形になっておりました。

なるほど、裏での変換はかなりトリッキーなやり方になってしまうのでできれば、ユーザーにそのまま入力させたいですね。
ユーザーがチャンネルのURLを知る方法は、今のやり方よりわかりやすいスマートなやり方は有名なサービスとしては用意している気がします。（無いとおかしい気がする）

> スクリーンショット

ちょっとトリッキーな方法ですね。
普通にブラウザでDiscordを開いてチャンネルにアクセスすればURLがわからないですかね？

> ヘルプの文面や、Controllerでの変換処理の書き方に問題がないかご確認いただけますでしょうか🙏
（メッセージURLをそのまま入力する方を想定して変換処理を残していますが、必要ないというご判断があれば変換処理は削除いたします）

チャンネルURLをそのまま入力するようにして、ヘルプの文面を修正もお願いしたいです〜

2021-09-26 04:20 UTC, rikuba commented on app/models/user.rb
> +  def times_url=(url)
@komagata 

> ユーザーがチャンネルのURLを知る方法は、今のやり方よりわかりやすいスマートなやり方は有名なサービスとしては用意している気がします。（無いとおかしい気がする）

Slackではチャンネルのコンテキストメニューに「リンクのコピー」という項目があるのですが、Discordでは「招待」がそれに該当するのかなと思いました。

> 普通にブラウザでDiscordを開いてチャンネルにアクセスすればURLがわからないですかね？

アプリからURLを取得する方法ばかり考えていて、ブラウザで確認してもらう方法を考えていませんでした。
ブラウザでチャンネルを開いた上でURLを確認してもらう方が直接的ですね💦

> チャンネルURLをそのまま入力するようにして、ヘルプの文面を修正もお願いしたいです〜

メッセージURLに関する処理を削除して、ヘルプの文面も修正しました。

<details>
<summary>スクリーンショット</summary>
<img width="680" alt="スクリーンショット 2021-09-26 12 56 20" src="https://user-images.githubusercontent.com/350435/134793040-c8b77c60-a4d3-40a8-a874-917bd3cc62d6.png">
</details>

度々で申し訳ありません。改めてご確認のほどお願いいたします。

2021-09-28 17:36 UTC, komagata requested changes

2021-09-28 17:36 UTC, komagata commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +require 'uri'
この辺って全て無いと動かないんでしたっけ？

2021-09-28 17:36 UTC, komagata commented on test/db/data/convert_invite_url_of_times_url_to_channel_url_test.rb
> +require Rails.root.join('db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url')
migrationのプログラムを直接テストしなくて大丈夫です。
modelなどのメソッドに切り出して、それをテストする方がスマートなのでそちらでお願いしたいです。

2021-09-29 05:19 UTC, rikuba commented on db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url.rb
> +require 'uri'
必要ありませんでした💦
削除しました。

2021-09-29 05:19 UTC, rikuba commented on test/db/data/convert_invite_url_of_times_url_to_channel_url_test.rb
> +require Rails.root.join('db/data/20210915021559_convert_invite_url_of_times_url_to_channel_url')
承知いたしました。
[sinsokuさんのコメント](https://github.com/fjordllc/bootcamp/pull/3139#discussion_r711594729)を参考にUserモデルにメソッドを実装し、そのメソッドに対してテストを行うように変更しました。

2021-09-29 05:19 UTC, rikuba commented
@komagata
ご指摘いただいた点を修正しました。
ご確認のほどお願いいたします🙏

2021-09-29 12:57 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-29 13:33 UTC, merged

2021-09-29 15:31 UTC, rikuba commented
@komagata 

レビューありがとうございました🙇‍♂️

staging環境でデータマイグレーション以外の機能を確認しました。データマイグレーションはproductionでのみ実行されるため動作を確認できないのですが、リリースブランチにチェックを付けて問題ないでしょうか。

<details>
<summary>チェックリスト</summary>

- [ ] hajimeの分報URLがデータマイグレーションによってチャンネルURLに更新されること
- [x] ユーザーが分報URLとしてチャンネルURLを登録できること
- [x] ユーザーが分報URLとして招待URLを登録できないこと
- [x] ユーザーが分報URLとして無関係なURLを登録できないこと
- [x] ユーザーが分報URLを空にできること
- [x] 管理者がユーザーの分報URLとしてチャンネルURLを登録できること
- [x] 管理者がユーザーの分報URLとして招待URLを登録できないこと
- [x] 管理者がユーザーの分報URLとして無関係なURLを登録できないこと
- [x] 管理者がユーザーの分報URLを空にできること
- [x] 分報リンクからブラウザでDiscordの該当チャンネルが開かれること

</details>

2021-10-01 14:03 UTC, komagata commented
@rikuba はい、問題ございません〜