イベントの日にダッシュボードに出したい(再作成)
fjordllc/bootcamp pull request #3163
Opened 2021-08-20 03:35 UTC by yamadaab

イベントの日にダッシュボードに出したい #2650

以下の項目を対応しました。

イベント前日と当日にダッシュボードに表示したい。
「閉じる」ボタンを押すと非表示にしたい。（cookieなどで非表示にしたことを記憶したい）
実装を確認する方法

rails db:seedを行ってからログインをして下さい。テストとして表示するイベントの日付はDate.currentで設定しております。(詳細は/bootcamp/db/fixtures/events.ymlをご確認下さい。)
　Date.currentの日付はrails db:seedを行った日から更新されないので、自身のPCの日付とズレてしまい表示されなくなることにご注意下さい。。
テストで確認する場合
HEADED=1 rails test (test/system/home_test.rbのパス):66のテストを実行するとテスト用のイベントが表示されているのを確認できます。
修正点

「本日」と「明日」のイベントをhome_controllersで取得します。
homeのViewファイル(index.html.slim)にて表示を行います。
表示されたイベントは「閉じる」を押すことで表示されなくなります。同時にcookieに「confirmed_event_ids」というファイルを作成し、「閉じる」を押したイベントのidを配列として保存します。
この機能をapp/javascript/incoming-events.jsで行っています。

2021-08-20 04:16 UTC, yamadaab commented
すみません。バグは直ったのですが、以前のブランチに問題があり、新しく以下にプリクエストを作成しました。
問題なければ、こちらにて確認よろしくお願い致します。

以前のプルリク
イベントの日にダッシュボードに出したい(再作成) #2970

2021-08-22 05:59 UTC, komagata commented
@yamadaab lintが続くなど、コミットメッセージが不適切なようなので、メッセージやコミットの粒度を整理してみてください〜

2021-08-22 10:59 UTC, yamadaab commented
> @yamadaab lintが続くなど、コミットメッセージが不適切なようなので、メッセージやコミットの粒度を整理してみてください〜

すみません。lintで連続して上手くいかなったのですが、そのままにしてしまいました。修正します。🙇‍♂️

2021-08-24 03:45 UTC, yamadaab commented
@komagata 
コミット「lint」が３つ続いていた状態を一つにまとめました🙇‍♂️

2021-09-01 06:30 UTC, yamadaab commented on app/javascript/incoming-events.js
> +      document.querySelector('#event.thread-list-item.incoming-events').remove()
失礼しました。他の修正と混同してしまいました。`.incoming-events`だけで対応できました。

2021-09-01 06:30 UTC, yamadaab commented on app/javascript/incoming-events.js
> +        const updatedEventIds = originalEventIds.substr(unnecessaryCharacters) // Keyである"confirmed_event_ids="の20文字を除きidであるvalue値のみを取得
こちら、`updateEventIds`という関数を作成してまとめてみました。

2021-09-01 06:48 UTC, yamadaab commented
> 絶対NGというわけじゃないですが、コミットメッセージが「lint」だけだとぶっきら棒すぎるので別の表現の方がいいかもです。

失礼しました。🙇‍♂️
「lintが通るように修正しました」というタイトルに変更しました。

2021-09-01 14:12 UTC, sinsoku commented on test/system/home_test.rb
> +    travel_to Time.zone.local(2017, 0o4, 0o1, 10, 0, 0o0) do
`0o` は8進数を使うときにつけると便利ですが、普段は使わない方が分かりやすいと思います。参考: [リテラル](https://docs.ruby-lang.org/ja/latest/doc/spec=2fliteral.html)

10進数で書く場合は `0o` をつけなければ良いです。

```suggestion
    travel_to Time.zone.local(2017, 4, 1, 10, 0, 0) do
```

2021-09-03 02:55 UTC, yamadaab commented on test/system/home_test.rb
> +    travel_to Time.zone.local(2017, 0o4, 0o1, 10, 0, 0o0) do
@sinsoku 
アドバイスありがとうございます！！🙇‍♂️
参考にした所と同じ形式にしたものと思います。🙇‍♂️
ご指摘頂いたところも注意して進めたいと思います！(^^

@komagata 
レビュー依頼後にすみません🙇‍♂️
こちらも変更しておりますので、併せてよろしくお願い致します🙇‍♂️

2021-09-04 04:51 UTC, komagata requested changes
conflictの修正お願い致します〜

2021-09-16 04:23 UTC, yamadaab commented
@komagata 
お疲れ様です。遅くなりすみませんでした。
コンフリクトの修正が終わりました。
ご確認よろしくお願い致します🙇‍♂️

2021-09-21 05:40 UTC, komagata commented on app/javascript/incoming-events.js
> +    const secondsFor30days = 2592000
一旦constにしてるのいいですね！

2021-09-21 05:41 UTC, komagata commented
@machida こちらデザインお願いします〜

2021-09-22 14:13 UTC, machida approved these changes

2021-10-01 13:47 UTC, komagata commented
@yamadaab @machida 

<img width="1432" alt="スクリーンショット 2021-10-01 22 45 48" src="https://user-images.githubusercontent.com/16577/135630685-0f404d22-90af-4770-bba7-ee57ce67ef13.png">

ローカルで確認したところ、上記の様に表示されていました。両方が「明日」と表示されているのはおかしいかもです。

また、今日・明日と表示を切り替えるところのロジックはdecoratorかhelperでやるとスマートかもです〜

2021-10-04 14:10 UTC, yamadaab commented
@komagata 
すみません。コンフリクトを修正した際に誤ったのか、seedデータの両方ともdate.tommorowになっていました🙇‍♂️
seedデータと、helperの件、対応しましたのでご確認お願い致します🙇‍♂️

2021-10-05 11:38 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-10-05 11:38 UTC, merged