質問があるプラクティスには、質問タブのところに質問の件数を表示
fjordllc/bootcamp pull request #3172
Opened 2021-08-20 23:26 UTC by masamune17

issue #1589

2021-08-21 02:50 UTC, masamune17 commented
@makiichikawa さんこちらのレビューお願いいたします🙏

2021-08-21 06:56 UTC, makiichikawa approved these changes
@masamune17 

確認しました〜問題ありませんでした👍

2021-08-22 00:32 UTC, masamune17 commented
@makiichikawa さんご確認ありがとうございます！！

@komagata さんこちらレビューをお願いいたします。

2021-08-22 12:40 UTC, komagata requested changes

2021-08-22 12:40 UTC, komagata commented on app/views/application/_page_tab.html.slim
> +- length = @practice.questions.length
一旦変数に入れている意味がないかも？

2021-08-22 12:40 UTC, komagata commented on app/views/application/_page_tab.html.slim
> +- num_of_questions = tab[:display_name] == '質問' ? "(#{length})" : ''
これであればifを使って表示・非表示を制御するのがシンプルかもです。

基本的にviewでrubyの代入などを使った複雑な処理を書くのはNGな感じで、ほんのちょっとしたのだったら構わないけど、少しでも複雑なことをやるんであればModel, ViewHelper, Decoratorなどを使って整理する感じです。

この場合はViewHelperを使うまでもなくViewnの中だけでifを使ってシンプルに書けそうです。

2021-08-23 09:27 UTC, masamune17 commented on app/views/application/_page_tab.html.slim
> +- length = @practice.questions.length
無用な変数を削除しました

2021-08-23 09:28 UTC, masamune17 commented on app/views/application/_page_tab.html.slim
> +- num_of_questions = tab[:display_name] == '質問' ? "(#{length})" : ''
単純なif文を使用して表示を切り替えるように変更しました

2021-08-23 10:16 UTC, masamune17 commented
@komagata さんご指摘箇所を修正いたしました
こちらレビューをお願いいたします

2021-08-23 14:08 UTC, komagata commented
「ブランチ作成」という変更（コードの変更）はないので、コミットメッセージを修正いただけるとありがたいです〜

2021-08-23 14:09 UTC, komagata commented
また、それまでの紆余曲折がないとしたらこのPRは１コミットぐらいで済むと思うので、コミットを整理してみてください〜

2021-08-24 02:55 UTC, masamune17 commented
@komagata さんPRを１コミットにまとめました
こちらレビューをお願いいたします

2021-09-06 08:08 UTC, machida commented
了解ですー！

2021-09-06 08:37 UTC, machida approved these changes

2021-09-06 08:38 UTC, machida commented
テスト通ったらマージします。
変更箇所が多いですが、サイトの中全体的な色の変更が発生したからなので、システムとは関係ないです。

2021-09-07 01:15 UTC, merged