書籍貸出に関する機能の削除
fjordllc/bootcamp pull request #3176
Opened 2021-08-22 10:37 UTC by makiichikawa

ref #3123

2021-08-22 14:11 UTC, makiichikawa commented
@cafedomancer 
こちらのレビューお願いできますでしょうか？？🙇🏼‍♂️

2021-08-23 02:26 UTC, cafedomancer approved these changes

2021-08-23 06:04 UTC, makiichikawa commented
@cafedomancer 
レビューありがとうございました🙇🏼‍♂️

@komagata 
こちらのレビューお願いできますでしょうか？🙇🏼‍♂️

2021-08-23 14:04 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

たくさん削除ありがとございました！

2021-08-23 14:04 UTC, komagata requested changes
conflictの解消お願いします〜

2021-08-24 11:57 UTC, makiichikawa commented
@komagata 
こちらのコンフリクト解消ですが、私の方で実施でしょうか？
self-requestedと書かれており、躊躇しております。

![書籍貸出に関する機能の削除_by_makiichikawa_·_Pull_Request__3176_·_fjordllc_bootcamp](https://user-images.githubusercontent.com/57123982/130612229-d642b56c-f3d1-42ea-b31e-6a18dba93eeb.png)

2021-09-03 15:09 UTC, machida commented
@komagata @makiichikawa 

すいません、遅くなりました。
不要なファイルを削除しました🙏

2021-09-06 08:39 UTC, machida commented
マージしますー

2021-09-06 08:39 UTC, merged

2021-09-06 08:50 UTC, makiichikawa commented
@machida 

CSSの削除とマージの対応ありがとうございました🙇🏼‍♂️