Feature/vuejs events
fjordllc/bootcamp pull request #3181
Opened 2021-08-23 14:27 UTC by rikuba

Ref: #2815

2021-08-24 07:41 UTC, rikuba commented
@konaga-k 
お手すきの際にこのPRのレビューをお願いいたします🙏

2021-08-24 10:06 UTC, konaga-k commented
木曜以降の確認になっちゃうかもしれません💦

2021-08-24 10:19 UTC, rikuba commented
@konaga-k 了解です!🙏

2021-08-28 02:54 UTC, konaga-k reviewed
@rikuba 
レビューが遅くなりすみません
動作確認した限りは問題ありませんでした👍
一点質問したので回答お願いします🙏

2021-08-28 02:54 UTC, konaga-k commented on app/views/api/events/_event.json.jbuilder
> +  json.long_name event.user.long_name
`api/users/user` に `long_name` が定義されていなくて、このjbuilderでだけ必要になるんですね
大元の `api/users/user` に追加しようにもほとんどの箇所で不要なプロパティになってしまうので、定義箇所はここで良いと思います👍

2021-08-28 02:54 UTC, konaga-k commented on app/javascript/events.vue
> +      this.getEventsPerPage()
ここの処理って[92行目](https://github.com/fjordllc/bootcamp/pull/3181/files#diff-1b1b59459a91443cf8f3ba4adec44f4e23a81bb27075207f3bfb14f915879165R92)のあとに呼び出されるんですよね
自分の理解が足りてないんですが、[84行目](https://github.com/fjordllc/bootcamp/pull/3181/files#diff-1b1b59459a91443cf8f3ba4adec44f4e23a81bb27075207f3bfb14f915879165R84)で `this.getEventsPerPage()` を呼んだあと、ここでも同じ呼び出しをしている理由って何なんでしょうか？

2021-08-28 07:44 UTC, rikuba commented on app/javascript/events.vue
> +      this.getEventsPerPage()
`popstate`イベントですが、`pushState`メソッドが呼び出された後ではなく、ブラウザが履歴エントリを遷移（戻る・進む）したときに発火されます（[WindowEventHandlers.onpopstate - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/WindowEventHandlers/onpopstate)の<q>メモ</q>欄）。

ページネーションでページを切り替えた後、ブラウザで「戻る」「進む」を押したときを想定した処理となります。提出部一覧の先行実装を参考にしました。

https://github.com/fjordllc/bootcamp/blob/52bdb909713c7f54ea8a1b6777e11b3c2036794e/app/javascript/reports.vue#L76-L79

2021-08-28 07:46 UTC, rikuba commented
@konaga-k 
レビューありがとうございます🙇‍♂️
ご質問の点についてコメントいたしました。

2021-08-28 09:13 UTC, konaga-k commented on app/javascript/events.vue
> +      this.getEventsPerPage()
なるほど、popstateイベントの条件を分かってなかったです
勉強になりました🙏

2021-08-28 09:13 UTC, konaga-k approved these changes
自分が見た限りは問題なさそうです！
![LGTM](https://image.lgtmoon.dev/102895)

2021-08-28 12:36 UTC, rikuba commented
@konaga-k 
お忙しいところレビューありがとうございました!🙇‍♂️

@komagata 
こちらのPRのレビューをお願いいたします🙏

2021-08-30 08:10 UTC, komagata requested changes

2021-08-30 08:10 UTC, komagata commented on app/views/api/events/_event.json.jbuilder
> +  json.partial! "api/users/user", user: event.user
long_nameは最終的には全ての場所で使うようになると思うので、api/user/userに入れちゃっていいと思います〜

2021-08-31 12:10 UTC, rikuba commented
@komagata 
レビューありがとうございます!
api/users/userの方に`long_name`を追加する形に修正しました。
ご確認のほどお願いいたします。

2021-09-04 04:42 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-04 04:42 UTC, komagata commented on app/views/api/events/_event.json.jbuilder
> +json.user event.user, partial: "api/users/user", as: :user
jbuilderでこういうふうにpartial使えるって知りませんでした！

2021-09-04 04:42 UTC, merged