プラクティスの進捗を % でなく、完了プラクティスの個数 / プラクティス全体の個数 として表示する
fjordllc/bootcamp pull request #3191
Opened 2021-08-25 14:21 UTC by rjtt17

issue: [3150](https://github.com/fjordllc/bootcamp/issues/3150)

2021-08-30 04:38 UTC, rjtt17 commented
@konaga-k  お時間ある際にレビューお願いいたします🙏

2021-08-30 10:57 UTC, konaga-k reviewed
@rjtt17 
- 動作確認はOKです
- NITSの箇所は修正お願いします
- MAYの箇所はこのPRで直すべきか迷うので対応おまかせします。対応していいか分からなかったら、お手数ですが駒形さんに確認してください

2021-08-30 10:57 UTC, konaga-k commented on app/views/api/users/_list_user.json.jbuilder
> +json.(user, :id, :login_name, :name, :discord_account, :description, :github_account, :twitter_account, :facebook_url, :blog_url, :times_url, :job_seeker, :free, :job, :os, :experience, :email, :role
[NITS] 細かいですが、`,:cached_completed_percentage`の`,`と`:`の間に半角スペースを入れておいたほうがいいと思います🙏

2021-08-30 10:57 UTC, konaga-k commented on app/decorators/user_decorator.rb
> +  end
[感想] 進捗度ってキャッシュしておいたほうが良いんですね
文脈はわからないですが、[過去に専用のPRを出して対応している](https://github.com/fjordllc/bootcamp/pull/1791)くらいなので必要な処理なんだなあという理解です

2021-08-30 10:57 UTC, konaga-k commented on test/models/user_test.rb
> +    user.completed_practices << practices(:practice52)
[MAY] [practice52](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/practices.yml#L328) だと `include_progress: false`になっているので、計算から除外されている理由が `unrelated cource` であるためなのか、 `include_progress: false` であるためなのか判定できない気がします
`include_progress: true` かつ `users(:komagata)` のコースに含まれない [practice51](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/practices.yml#L322) あたりを採用した方が良さそうです
そうなると、 [completed_percentage](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/models/user_test.rb#L89) の方も修正したほうが良さそうですね
既存テストをいじってしまうという意味で、このPRの範囲を越えている気もするので対応おまかせします

2021-08-30 13:07 UTC, konaga-k commented
あとdescriptionに貼ってある変更前/変更後の画像なのですが、同じ進捗率に揃えてもらいたいです🙏
（60%と30/50のような感じ）

2021-08-30 13:20 UTC, rjtt17 commented
レビューありがとうございました🙇‍♂️ 修正していきます！

2021-09-01 11:45 UTC, rjtt17 commented on app/decorators/user_decorator.rb
> +  end
キャシュ使った方がいいか分からなかったのと使い方が怪しかったので、こちらのメソッドを削除しました〜

2021-09-01 11:46 UTC, rjtt17 commented on app/views/api/users/_list_user.json.jbuilder
> +json.(user, :id, :login_name, :name, :discord_account, :description, :github_account, :twitter_account, :facebook_url, :blog_url, :times_url, :job_seeker, :free, :job, :os, :experience, :email, :role
教えて頂きありがとうございました🙇‍♂️ 修正しました！

2021-09-01 11:51 UTC, rjtt17 commented on test/models/user_test.rb
> +    user.completed_practices << practices(:practice52)
こちらについて、ご指摘いただいた通り、判定できていないと思うので、修正いたしました！
[practice51](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/practices.yml#L322)だと[practice5](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/practices.yml#L44)と同様のcourse1に属するプラクティスになってしまい、```unrelated cource```ではないので、[practice52](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/practices.yml#L328)の```include_progress: false```を削除しました。

2021-09-01 11:52 UTC, rjtt17 commented
@konaga-k お時間ある際に再度レビューお願いいたします🙏

2021-09-01 12:27 UTC, konaga-k requested changes
@rjtt17 
コメント返しました〜
SHOULDは対応お願いします
MAYは引き続き対応するかお任せします（既存のテストの変更になるため）

2021-09-01 12:27 UTC, konaga-k commented on test/models/user_test.rb
> +    user.completed_practices << practices(:practice52)
すみません、courseをちゃんと追いきれていませんでした🙇
確かにcource1に入っちゃうのでpractice51は不適切ですね、失礼しました

practice52のfixturesですが、以下の理由から容易に変更しづらいかなと思います〜
- practice52を使用している他のテストがあった場合、条件が意図せず変更されてしまう可能性がある（今回はそういうテストはないみたいですが）
- fixturesのデータはseedで実行される[開発用データ](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/db/fixtures/practices.yml#L431-L438)に寄せてあるようなので、fixturesを変えると一貫性が保てなくなる

以上を踏まえて、以下のように変更お願いします🙏
- [SHOULD] practice52のfixturesは元に戻す
- [MAY] テストではpractice52ではなく[practice55](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/practices.yml#L348)を採用する。修正する場合は[completed_percentage](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/models/user_test.rb#L89) の方も修正する

practice55なら `include_progress: true` かつ、 [category20](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/categories_practices.yml#L273) -> [cource2にのみ所属](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/courses_categories.yml#L97) -> [users(:komagata)のコースではない](https://github.com/fjordllc/bootcamp/blob/feature/change-practices-progress/test/fixtures/users.yml#L14) になるので条件を満たせると思います( `last_updated_user: komagata` なのがやや微妙かもですが)
自分の言っていることが間違っていたら指摘お願いします🙇

2021-09-01 12:27 UTC, konaga-k commented on app/decorators/user_decorator.rb
> +  end
自分もキャッシュを使うべきかはわからなくて申し訳ないんですが、パーセントの進捗度はキャッシュしていたことを考えると、分数の進捗度もキャッシュしたほうが良い可能性はありますね
後に @komagata さんにレビューしてもらうと思うんですが、[パーセントの進捗度キャッシュ](https://github.com/fjordllc/bootcamp/pull/1791)を実装していたみたいなので、どういう背景でキャッシュしているのか含めて、分数のキャッシュが必要か確認してみるといいと思います
（レビュータイミングでコメントしてもらえることを期待して駒形さんにメンションを付けてみる）

2021-09-03 13:07 UTC, rjtt17 commented
@konaga-k 
コメントいただいた部分について、修正致しました！
お手すきの際に再度ご確認お願いします🙇‍♂️

■修正内容の詳細は以下です。
> [SHOULD] practice52のfixturesは元に戻す
practice52のfixturesは元に戻しました。

> [MAY] テストではpractice52ではなくpractice55を採用する。その場合はcompleted_percentage の方も修正する
二つのテストとも practice55を採用し、修正しました。

2021-09-04 03:09 UTC, konaga-k approved these changes
OKです〜
![LGTM](https://image.lgtmoon.dev/129460)

2021-09-04 04:55 UTC, komagata requested changes

2021-09-04 04:55 UTC, komagata commented on app/models/user.rb
>    def completed_percentage
パーセントが不要ならこのメソッド自体不要かも？

2021-09-06 04:05 UTC, konaga-k commented on app/models/user.rb
>    def completed_percentage
ピンク色のプログレスバーを表示する計算で必要だと思ってたんですがどうでしょう

@rjtt17 
実はいらなかったりします？

2021-09-06 04:28 UTC, rjtt17 commented on app/models/user.rb
>    def completed_percentage
@komagata 
CC: @konaga-k 
ご確認ありがとうございました🙇‍♂️
プログレスバーを表示している、[app/views/users/practices/_completed_practices_progress.html.slim ](https://github.com/fjordllc/bootcamp/pull/3191/files#diff-24dca987c97360b5738f31e87bd115789d0112ccc2363d1f1d795c900d0aa18fL5)や[app/javascript/user-practice-progress.vue ](https://github.com/fjordllc/bootcamp/pull/3191/files#diff-eaf08299db4f4ecc012032aec428f52f480e045ac50a79762e330b4fd5fd9c4dL13)等でパーセント使っているので、残しておいたのですが、不要でしょうか？

2021-09-06 10:21 UTC, komagata commented on app/models/user.rb
>    def completed_percentage
@rjtt17 そちらを見逃していました。それだったら問題ございません〜

2021-09-06 10:21 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-06 10:21 UTC, merged

2021-09-06 11:51 UTC, rjtt17 commented on app/models/user.rb
>    def completed_percentage
@komagata ご確認ありがとうございました🙇‍♂️