涙マークの日報が2回続いた場合は通知が欲しい
fjordllc/bootcamp pull request #3224
Opened 2021-09-04 08:30 UTC by gentamura

ref: #1894

2021-09-07 01:04 UTC, gentamura commented
@konaga-k お手すきでレビューお願いします:pray:

2021-09-07 11:54 UTC, konaga-k reviewed
@gentamura 
動作確認はOKです
いくつかコメントしているので、修正またはコメントをお願いします🙏

---
サイト内通知とメール通知について、結果がどうなるか一目で分かると嬉しいので、
通知されたときのスクショを貼っておいてほしいです〜
レビュアーが動作確認で何をチェックすればいいのかの参考にもなります
イメージはこんな感じです
https://github.com/fjordllc/bootcamp/pull/3082

2021-09-07 11:54 UTC, konaga-k commented on app/models/user.rb
> +    two_days_reports.size == 2 && two_days_reports.all?(&:sad?)
2日連続ではない、かつ2回連続のsadの場合 → 通知される
3回連続のsadの場合 →通知される
👍

2021-09-07 11:54 UTC, konaga-k commented on app/views/users/_sad_emotion_report.html.slim
> +        | 2日連続
[NITS] 2日ではなく2回の方が正確だと思います

2021-09-07 11:54 UTC, konaga-k commented on app/mailers/notification_mailer.rb
> +    @notification = @user.notifications.find_by(path: "/reports/#{@report.id}")
他の送信メソッドで `@notification` を宣言しているのは、おそらくメールに記載するリンクのパス生成に使っているんだと思います
https://github.com/fjordllc/bootcamp/blob/087c308da73596cc4f92fe999410920211fb6b00/app/views/notification_mailer/submitted.html.slim#L1

今回は `link_url: report_url(@report)` にしてるので、このままだとおそらく `@notification` は要らないですよね？（動かした感じ無くても大丈夫そうでした）
https://github.com/fjordllc/bootcamp/blob/087c308da73596cc4f92fe999410920211fb6b00/app/views/notification_mailer/twice_sad_report.html.slim#L1

- [Q] `link_url: notification_url(@notification)` にしていない理由ってありますか？
- [MUST] `link_url: report_url` を使うようにする、かつ `@notification` を使う場所が無いのであれば、 `@notification` の宣言は削除しておいてほしいです〜

2021-09-07 11:54 UTC, konaga-k commented on app/models/notification_facade.rb
> +  def self.twice_sad_report(report, receiver)
[IMO]
将来万が一通知の閾値が変わった場合（二回連続sad -> 三回連続sad）、twice_sad_reportは全部改名しないといけなくなりますね
何か変更されにくい良い名前があればいいんですが難しいですね…

通知条件のメソッドから名前を借りて、depressed_reportにするのは微妙でしょうか？ 
https://github.com/fjordllc/bootcamp/blob/087c308da73596cc4f92fe999410920211fb6b00/app/models/user.rb#L525-L528

（depressedがuserの状態を表すメソッド名なので、depressed_reportという形でreportに掛けるのは違和感があるかもしれない）

必須対応ではないので、名前がしっくりこなければ現状維持でよいです

2021-09-08 02:37 UTC, gentamura commented on app/models/notification_facade.rb
> +  def self.twice_sad_report(report, receiver)
`consecutive_sad_report` に変更しました:+1: （`consecutive`についてはsorceryでもメソッド名で利用されていたので、連続を表すには良さそうかなと。）
d3911fbb086440fdc53ad247a078459545b7ed68

また閾値を定数で管理するように変更しました
16d4787e86e8e3062946774dea639a5af49e60f4

2021-09-08 02:38 UTC, gentamura commented
@konaga-k ご指摘箇所も含めて修正したので、お手すきで再確認お願いします:pray:

2021-09-08 10:18 UTC, konaga-k commented on app/mailers/notification_mailer.rb
> +    @notification = @user.notifications.find_by(path: "/reports/#{@report.id}")
なるほど、開発環境で確認するとややこしいですね💦
修正ありがとうございます

2021-09-08 10:20 UTC, konaga-k commented on app/models/notification_facade.rb
> +  def self.twice_sad_report(report, receiver)
`consecutive` いい名前ですね！
定数化も良いと思います！

2021-09-08 10:21 UTC, konaga-k approved these changes
@gentamura 
修正ありがとうございます！
![LGTM](https://image.lgtmoon.dev/94365)

2021-09-08 10:54 UTC, gentamura commented
@komagata お手すきでreviewお願いします:pray:

2021-09-08 11:35 UTC, komagata requested changes

2021-09-08 11:35 UTC, komagata commented on app/models/user.rb
> +  DEPRESSED_SIZE = 2
👍

2021-09-08 11:35 UTC, komagata commented on test/system/notification/reports_test.rb
> +  test 'sadアイコンの日報を2回続けて提出した場合、メンターに通知する' do
他の部分はテスト名は基本的に英語を使っているのでそちらに合わせていただけるとありがたいです〜
（現状日本語のテスト名を使ってしまっているところはレビューで漏れているところで、後々直したいと思っております。）

2021-09-12 05:13 UTC, gentamura commented on test/system/notification/reports_test.rb
> +  test 'sadアイコンの日報を2回続けて提出した場合、メンターに通知する' do
@komagata こちら修正しました！ 2db22168263d2a5277e850c0d4437b4887d36cb0

2021-09-13 18:06 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-13 18:06 UTC, merged