日報フォロー機能のコメント通知を切り替えられるようにする
fjordllc/bootcamp pull request #3227
Opened 2021-09-05 10:24 UTC by yana-gi

ref: https://github.com/fjordllc/bootcamp/issues/3007

## 概要
フォローするユーザーごとに日報を自動Watchにするか・しないかを選択できるようにする。

現在はデフォルトでフォローしたユーザーの日報が自動でWatchされる。
自動でWatchしない設定を追加し、フォロー時に選択できるようにする。

イメージ図
![image](https://user-images.githubusercontent.com/67262644/132123180-bea28691-644f-4a92-8b57-4123f7458179.png)

## やること
- [x] DB
    - [x] カラム追加
- [ ] コントローラー・モデル
  - [x] 新しくフォローできるようにする(create)
  - [x] コメントあり/なしを切り替えできるようにする(update)
  - [ ] index一覧(一覧)
- [ ] ビュー・Vue.js
  - [ ] 新しくフォローできるようにする(create)
  - [ ] コメントあり/なしを切り替えできるようにする(update)
  - [ ] index一覧でコメントあり/なしを切り替える
- [ ] テスト作成

2021-09-13 09:39 UTC, yana-gi commented
@machida
こちらテスト作成前ですが、デザインを入れていただくことは可能でしょうか。
現行の機能で参考できるものがなくHTML部分も仮実装になってしまっているため、この段階でデザインを入れて頂けると助かります！
デザイン待ちの間にもテスト作成などの作業はあるので、急ぎではありません〜

`following.vue`に仮でCSSを入れていますが、すべて削除してしまって構いません。
CSSで参考にした記事 : https://qiita.com/zackey2/items/55a004bcc5198d25f500

デザインを入れてほしいファイル
- `app/javascript/following.vue`
- `app/views/users/_followings_nav.html.slim`

2021-09-14 08:15 UTC, yana-gi commented
@machida 
本日のミーティングで指摘いただいた点修正しました。
- フォローボタンの表示を変更
- usersの「フォロー中」の階層を1段階あげた

usersの「フォロー中」の階層を1段階あげた件ですが、「フォロー中」タブのデザイン(アクティブ状態)は未対応のため、machidaさんの方で対応頂けないでしょうか。

上のコメントの件と合わせて対応お願いします🙏

2021-09-17 03:26 UTC, machida commented
@yana-gi すいません、遅くなりました🙇‍♂️ デザイン入れましたー

2021-09-17 03:29 UTC, machida commented
@yana-gi 最新のmainを取り込んだので、

```
$ git pull --rebase origin feature/enable_choose_type_of_follow
```

をやってから作業の続きお願いしますー

2021-09-18 10:00 UTC, yana-gi commented
@machida 
ありがとうございますー！確認します！

2021-09-19 06:11 UTC, yana-gi commented
@machida 
デザイン確認しました！
手元で確認したところ何点か確認していただきたい点があります〜
確認中でもシステムテストは着手できるので、お手隙の際に対応頂ければと思います！

## 相談したいこと
### 説明文の表示
入れていただいたデザインでは説明文が選択中のステータスでは非表示になっているようです。
![image](https://user-images.githubusercontent.com/67262644/133917194-bba9bfb5-9c62-4bb4-9e7f-2ea0afd1fc71.png)
個人的には選択中でも説明文を表示した方がステータスの違いを比較しやすいと感じています。
GitHubのWatch機能もそのような仕様になっているようです。
![image](https://user-images.githubusercontent.com/67262644/133917249-a91495a0-a757-4eed-959d-1478c56a1c69.png)
この件に関してmachidaさんの意見をお伺いしたいです！

## 修正を依頼したいこと
### タブのアクティブ状態
`/users?target=followings`表示時のタブが「全て」がアクティブ状態になっています。
「フォロー中」タブをアクティブ状態にして頂きたいです。
![image](https://user-images.githubusercontent.com/67262644/133917128-00364898-80df-4eba-b2f1-947431f60fa7.png)
`/users?target=followings`を`/users/followings`にする必要があればおっしゃってください〜！

### 通知の表示が崩れている
通知ベルのバッヂとアイコンの大きさが崩れているようです。
![image](https://user-images.githubusercontent.com/67262644/133917182-4bc3274b-4240-481a-b70a-7d92fe9dafd6.png)


ご確認お願いします🙏

2021-09-21 08:27 UTC, yana-gi commented
📝MTGメモ
デザインの修正依頼はレビューが完了してから。
レビューが終わったらmachidaさんにメンションする。

2021-09-21 09:08 UTC, yana-gi commented
@konaga-k 
こちらレビューお願いできますでしょうか〜

現在テストが通っていませんが、自分の変更内容とは別の問題で落ちていることを確認済です。
解決次第テストを再実行する予定です。

2021-09-21 09:11 UTC, konaga-k commented
明日以降確認します〜

2021-09-21 13:38 UTC, konaga-k requested changes
@yana-gi 
結局今日レビューしました

これかなり大変なissueですね…
お疲れ様です😭

- 動作確認はOKです
- コードレビューしたので対応もしくはコメントお願いします。IMOは個人的な意見なので、合わなかったら対応しなくても構わないです。色々書いてますが、致命的におかしなところはないと思います
- Railsのコードはひと通り見ましたが、Vue.jsは不慣れなためあんまりちゃんと見れてないです💦

2021-09-21 13:38 UTC, konaga-k commented on app/models/user.rb
> +  end
【MUST】
これはトランザクションを張るべき処理だと思います
- どこまで説明したらいいか分からなくて冗長な説明になってます。よく分からないことがあれば聞いてください
- トランザクションは難しく、自分も自信がないです

---
複数の保存処理をまとめて行うとき、その処理の一部のみが実行され、残りが実行されない、という状況を避けたいことがあります
このような場合には保存処理を `transaction` で括り、完全に実行されるか、更新処理が起こる前の状態に戻る（ロールバックする）か、どちらかになるようにします

参考：https://qiita.com/tomokiyao/items/8697b523a0a5b9cf0bec

今回の場合、以下の二つの保存処理は途中で実行が止まると良くない種類のものに思えます

- ユーザーをフォローする
- ユーザーをwatchする、もしくはwatchを外す

ということで、この一連の処理をtransactionで囲いたいわけです
（ユーザーをwatchする、もしくはwatchを外す処理が失敗することはないだろうと踏んで、一々transactionで囲わないこともあるみたいですが、ここらへんの塩梅は全然わからない）

---
で、どうやってtransactionを書くんだという話ですが、以下のようにすればいいと思います

```suggestion
  def follow(other_user, watch)
    all_success = true
    ActiveRecord::Base.transaction do
      all_success &= following << other_user # ①
      all_success &= change_watching(other_user, watch) # ①
      unless all_success # ②
        raise ActiveRecord::Rollback
      end
    end
    all_success # ③
  end
```

参考: https://speakerdeck.com/jnchito/number-rubykansai-2018-01-13?slide=43

①どこかの保存処理に失敗すると、all_successはfalseになります。そうでなければtrueのままです
②保存処理に失敗していると、 `ActiveRecord::Rollback` という例外がraiseされ、ロールバックが発生します。transactionブロックによって例外はrescueされ、処理が続行します
③戻り値のall_successは保存が成功していればtrueに、失敗していればfalseになります

これでロールバックを可能にしつつ、 `true/false` を返すメソッドが書けていると思います

2021-09-21 13:38 UTC, konaga-k commented on app/models/user.rb
> +  def follow(other_user, watch)
【MUST】
これだけだと第二引数が何の属性なのか呼び出し側から分からない（特に[テストコード](https://github.com/fjordllc/bootcamp/pull/3227/files#diff-91bef9fda3c55514e23a4a8edba948f68aad59b57951adcff0b11e9ea9159854R290)）ので以下のようにキーワード引数を使用してほしいです

```suggestion
  def follow(other_user, watch:)
```

呼び出し側からはこのように記述します

```ruby
current_user.follow(user, watch: watch)
```

2021-09-21 13:38 UTC, konaga-k commented on app/models/user.rb
> +    following_row.update!(watch: watch)
【MUST】
コントローラーから呼ばれる保存処理には `true/false` を返すことを期待したいです
以下のように条件分岐に使うからですね

```ruby
if current_user.change_watching(user, watch)
  head :no_content
else
  head :bad_request
end
```

`update!` だと失敗したときに例外を投げてしまうので、 `update` に変更してください〜

2021-09-21 13:38 UTC, konaga-k commented on app/models/user.rb
> +    following_row = Following.find_by(follower_id: self, followed_id: other_user)
【感想】
なんで `following` じゃなくて `following_row` なんだと思ったんですが、 `following` が `has_many` で使われているからですね…
今更 `has_many` の方を変えるのは大変なので、ここは仕方ない感じですね
（そのうち `has_many` の名前が負債になる気がする…）

2021-09-21 13:38 UTC, konaga-k commented on app/controllers/api/users_controller.rb
>          User.where(id: followings)
【MUST】
`following_list` という名前でidを返すのは違和感があるのでなんとかしたいですね
userのまとまりを直接返した方がスッキリすると思います

```suggestion
        current_user.following_list(watch: @watch)
```

`following_list` メソッドの中身はこんな感じでどうでしょう

```ruby
def following_list(watch: '')
  if %w[true false].include?(watch)
    following.includes(:passive_relationships).where(followings: { watch: watch })
  else
    following
  end
end
```

2021-09-21 13:38 UTC, konaga-k commented on app/models/user.rb
> +  def auto_watching?(other_user)
【IMO】
`auto_` がなくても意味が通りそうなので、自分なら `watching?(other_user)` にします
好みの範囲だと思います

2021-09-21 13:38 UTC, konaga-k commented on app/models/user.rb
> +    following?(other_user) ? Following.find_by(follower_id: self, followed_id: other_user).watch : false
【IMO】
booleanのカラムがあると `#{カラム名}?` というメソッドが生えるので、以下のように書き換えられます
外から見てbooleanを返すのが直感的に分かるので、自分はこちらのほうが好みです

```suggestion
    following?(other_user) ? Following.find_by(follower_id: self, followed_id: other_user).watch? : false
```

2021-09-21 13:38 UTC, konaga-k commented on app/views/users/_followings_nav.html.slim
> +          = link_to t("watch.#{watch}"), users_path(target: @target, watch: watch), class: (@watch == watch ? ['is-active'] : []) << 'tab-nav__item-link'
【MUST】
このファイルは使ってないみたいなんですが、削除しちゃだめですかね？

2021-09-21 13:38 UTC, konaga-k commented on db/migrate/20210905061726_add_watch_to_followings.rb
> +    add_column :followings, :watch, :boolean, default: true, null: false
既存のフォロー情報は現行と同じでコメント通知ありになるんですね
👍

2021-09-21 14:05 UTC, konaga-k commented on app/models/user.rb
> +  end
どちらもfollowingモデルの更新だから、わざわざトランザクションを使わないでも、更新を1回だけ行うようにしたほうがいいのかなあ……

```ruby
following.create(followed: other_user, watch: watch)
```
（動くか確かめてないのであくまでイメージ）
でも `change_watching` メソッドが使い回せないのが嫌なのか……

とりあえずは上に書いたようなトランザクションで囲むスタイルで良いと思います

2021-09-21 14:12 UTC, konaga-k commented on app/models/user.rb
> +  end
すみません、方針代わって申し訳ないんですが、やっぱりこっちのほうが良いと思います

```suggestion
  def follow(other_user, watch)
    active_relationships.create(followed_id: other_user.id, watch: watch)
  end
```
参考: https://railsguides.jp/association_basics.html#has-manyで追加されるメソッド
`collection.create(attributes = {})` を使っています

transactionを書いちゃうと大仰ですし、テストも面倒になりますしね…（ロールバックされることを確認したほうがいいので）
`change_watching` は使えなくなってしまいますが、あまり大きな処理は書いてないですし、無理に使わなくてもいいかなと

2021-09-22 03:16 UTC, konaga-k commented on db/migrate/20210905061726_add_watch_to_followings.rb
> +    add_column :followings, :watch, :boolean, default: true, null: false
あ〜すみません、 `add_column + default` するときに対象レコード数が多すぎるとサービスが止まりかねないという話があるようです
https://kinosuke.hatenablog.jp/entry/2019/11/01/211440

followingsテーブルの既存レコード数が何行程度か、また本番環境で動かしたときにサービス継続に影響しないか、
駒形さんへのレビューリクエスト時に確認依頼したほうがいいと思います

2021-09-22 06:50 UTC, yana-gi commented on app/models/user.rb
> +  end
`active_relationships.create`を使えば1回の処理で済むんですね、なるほど……！
`User#follow`の書き方がずっと納得いっていなかったのでスッキリしました。

transactionについても今まで意識していなかったので勉強になります！
説明とても分かりやすいです〜ありがとうございます🙏

2021-09-22 06:50 UTC, yana-gi commented on app/models/user.rb
> +  def follow(other_user, watch)
確かにそうですね！
`User#follow`にキーワード引数`watch`を設定しました。

2021-09-22 06:51 UTC, yana-gi commented on app/models/user.rb
> +    following_row.update!(watch: watch)
`update`に変更しました。

2021-09-22 06:51 UTC, yana-gi commented on app/models/user.rb
> +    following_row = Following.find_by(follower_id: self, followed_id: other_user)
issue登録ありがとうございます！
自分も `following_row ` の命名を考える際に`following`の命名が気になっていたのでありがたいです🙏

2021-09-22 06:51 UTC, yana-gi commented on app/controllers/api/users_controller.rb
>          User.where(id: followings)
> following_list という名前でidを返すのは違和感があるのでなんとかしたいですね
userのまとまりを直接返した方がスッキリすると思います

確かにそうですね！
提案していただいた`following_list`で修正しました。
`following.includes(:passive_relationships).where(followings: { watch: watch })`は自分には思い付かなかったので参考になりました！

`app/controllers/api/users_controller.rb`だけでなく
`app/controllers/users_controller.rb`の方も修正しました。

2021-09-22 06:51 UTC, yana-gi commented on app/models/user.rb
> +  def auto_watching?(other_user)
他の`watch`の名前では`auto_`を使っていなかったため、統一させるために`watching?(other_user)`にしました

2021-09-22 06:51 UTC, yana-gi commented on app/models/user.rb
> +    following?(other_user) ? Following.find_by(follower_id: self, followed_id: other_user).watch : false
確かにこちらの方が`watch`という属性がbooleanであることが分かりやすいですね。
修正しました。

2021-09-22 06:51 UTC, yana-gi commented on app/views/users/_followings_nav.html.slim
> +          = link_to t("watch.#{watch}"), users_path(target: @target, watch: watch), class: (@watch == watch ? ['is-active'] : []) << 'tab-nav__item-link'
消し忘れていたので削除しました。
指摘ありがとうございます！

2021-09-22 06:51 UTC, yana-gi commented on db/migrate/20210905061726_add_watch_to_followings.rb
> +    add_column :followings, :watch, :boolean, default: true, null: false
最近もリリース時にmigrationに時間がかかったケースがあったので確認した方が良さそうですね👀

> 本番環境でのfollowingsテーブルの既存レコード数が何行程度か、また本番環境でmigrationを実行したときにサービス継続に影響しないか、

komagataさんに確認取ってみます〜

2021-09-22 06:55 UTC, yana-gi commented
@konaga-k 
レビューありがとうございます！
細かく見ていただいてとても助かります😄 

指摘いただいた点を修正しました。
migrationの件はkomagataさんに確認次第対応する予定です〜

2021-09-22 08:09 UTC, yana-gi commented on db/migrate/20210905061726_add_watch_to_followings.rb
> +    add_column :followings, :watch, :boolean, default: true, null: false
komagataさんに確認したところ、そこまでデータ数がある訳ではないのでこのままの対応で問題ないとのことでした。

`add_column + default`は今後も気をつけたいと思います〜勉強になりました！
komagataさんも「いい指摘」と仰っていました😄

2021-09-22 08:12 UTC, yana-gi commented
@konaga-k 
migrationの件は対応不要とのことでした。
修正点の確認お願いします〜🙏

2021-09-22 10:58 UTC, konaga-k approved these changes
@yana-gi 
OKです〜👌

2021-09-22 11:25 UTC, yana-gi commented
@konaga-k 
レビューありがとうございました〜！

@komagata 
こちらレビューお願いします。
レビュー後にmachidaさんにデザインを修正してもらうため一旦マージしないで頂きたいです🙏

2021-09-23 05:08 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-23 06:01 UTC, yana-gi commented
@komagata 
確認ありがとうございます😄

@machida 
デザイン修正をお願いします！
こちら確認いただければと思います〜
https://github.com/fjordllc/bootcamp/pull/3227#issuecomment-922421384

2021-09-27 04:39 UTC, machida commented
@yana-gi
すいません、説明文が消えてしまうところ、勘違いしてました。修正しましたー。
通知のデザイン崩れもありがとうございます！！思いっきりファイルを消してしまってました。。。（危なかった、、、🙏）
コンフリクトを解消したので、

```
git pull --rebase origin feature/enable_choose_type_of_follow
```

をお願いしますー

---

一点気になったのですが、フォロー状態を切り替えるとき、赤い枠で囲った部分をクリックしたら、detail タグの open 属性が削除されて detail が close になると便利かと思いました。

<img width="377" alt="貼り付けた画像_2021_09_27_13_37" src="https://user-images.githubusercontent.com/168265/134846185-a85fa7ce-95b5-4285-868e-728442b61981.png">

もし、こちら手間がかかりそうでしたら、これでリリースして別 Issue で対応でも大丈夫ですー

2021-09-28 06:51 UTC, yana-gi commented
@machida 
ミーティングで言ったようにタブの修正を行いました。
変更内容に問題がなければマージお願いします🙏

2021-09-30 02:38 UTC, machida commented
@yana-gi お待たせしました！！確認しました。
OKですー
マージしますー🎉

2021-09-30 02:38 UTC, merged

2021-09-30 03:07 UTC, yana-gi commented
@machida 
ありがとうございますー！