担当提出物に未返信の絞り込み機能を実装
fjordllc/bootcamp pull request #3241
Opened 2021-09-07 10:24 UTC by makiichikawa

ref #3022 

## やったこと
担当している提出物について、未返信の提出物を抽出して画面表示するように変更しました。
"自分の担当"のタブに表示される数字についても、未返信の提出物の個数に変更しました。

##### 絞り込み機能の実装

#####

2021-09-07 14:01 UTC, makiichikawa commented
@yamadaab 
こちらのレビューお願いできますでしょうか??🙏

2021-09-08 01:25 UTC, yamadaab commented
> @yamadaab
> こちらのレビューお願いできますでしょうか??🙏

2021-09-08 03:36 UTC, makiichikawa commented
@yamadaab 
レビューいただきありがとうございました🙇🏼‍♂️

@komagata 
こちらレビューお願いいたします🙇🏼‍♂️

2021-09-08 11:31 UTC, komagata requested changes

2021-09-08 11:31 UTC, komagata commented on app/controllers/api/products/self_assigned_controller.rb
> +                  Product.self_assigned_product(current_user.id).unchecked.list.page(params[:page])
このあたり1行が長くなっているので改行をいくつか入れるといいかもです〜

2021-09-09 03:30 UTC, makiichikawa commented on app/controllers/api/products/self_assigned_controller.rb
> +                  Product.self_assigned_product(current_user.id).unchecked.list.page(params[:page])
@komagata 

修正いたしました！
確認お願いたします。

2021-09-13 17:48 UTC, komagata requested changes
conflictの解消お願い致します〜

2021-09-14 02:34 UTC, makiichikawa commented
@komagata 

conflictの解消をしました。
mainを取り込み、稼働を確認したのですが、
メンターモードオンにしても、”自分の担当タブ”が表示されない事象が発生しました。

今回コンフリクトの対象ファイルはproduct.rbなので、コンフリクト解消で発生した事象だとは考えにくく、
どのように解決すればよいかわからない状態です。

お手数おかけしますが、確認のほどよろしくお願いいたします。

2021-09-14 04:36 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-14 04:37 UTC, komagata commented
コードの方はOKです。

@machida デザイン面の確認お願い致します〜。

2021-09-16 01:24 UTC, machida commented
了解ですー🙋‍♂️

2021-09-16 08:50 UTC, machida commented
@makiichikawa デザイン入れましたー テスト通ったらマージします

2021-09-17 01:08 UTC, merged