新規登録ページで利用規約とアンチハラスメントポリシーにチェックを入れないと参加できない制御を実装
fjordllc/bootcamp pull request #3245
Opened 2021-09-08 07:41 UTC by gentamura

ref: #3235

2021-09-08 09:02 UTC, gentamura commented on test/system/sign_up_test.rb
> +    VCR.use_cassette 'sign_up/valid-card', record: :once, match_requests_on: %i[method uri] do
👇 を参考に実装
https://github.com/fjordllc/bootcamp/pull/2876#issuecomment-869272204

2021-09-08 10:12 UTC, gentamura commented
@makiichikawa お手すきでコードビューお願いします:pray:

@machida デザイン部分、ご指摘あればお願いします:pray:

2021-09-08 14:34 UTC, machida approved these changes
@gentamura 
ちょこっとだけデザインを調整させていただきましたー

2021-09-09 00:28 UTC, makiichikawa approved these changes
確認しました、OKだと思います🙆‍♀️

2021-09-12 05:06 UTC, gentamura commented
@komagata こちらレビューお願いします:pray:

2021-09-13 18:04 UTC, komagata requested changes

2021-09-14 05:30 UTC, gentamura commented on app/assets/stylesheets/blocks/form/_form-actions.sass
> +  margin-bottom: .5rem;
@komagata 削除しました:pray:
6fa08e0

2021-09-21 04:43 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-21 04:43 UTC, merged