提出物に最終コメント日時を追加
fjordllc/bootcamp pull request #3264
Opened 2021-09-12 08:41 UTC by gentamura

ref: #3038

2021-09-12 11:29 UTC, gentamura commented
@rjtt17 お手すきでレビューお願いします:pray:

2021-09-15 12:06 UTC, rjtt17 approved these changes
@gentamura  
ソースコードと動作確認（commented_at カラムを追加確認とrakeタスク実行）して問題ないと思います〜
LGTMです🙇‍♂️

2021-09-15 12:28 UTC, rjtt17 commented
rakeタスクの場所ですが、以前のこちらのPR[add_last_commentをtaskに移動 #3275](https://github.com/fjordllc/bootcamp/pull/3275/files)で``` bootcamp.rake```に書かれていたので、rakeタスクの書く場所についてだけ少し気になりました。

2021-09-16 04:23 UTC, gentamura commented
@komagata お手すきでreviewお願いします:pray:

2021-09-21 04:46 UTC, komagata requested changes

2021-09-21 04:46 UTC, komagata commented on app/models/comment_callbacks.rb
> +    comment.commentable.save!
```suggestion
    comment.commentable.update!(commented_at: comment.updated_at)
```

とかでいいかもです〜

2021-09-21 04:46 UTC, komagata commented on lib/tasks/issues/issue3038/add_commented_at_in_products.rake
> +namespace :issues do
data migrationの仕組みがあるのでデータ変更はそちらでお願いします〜

[ilyakatz/data-migrate: Migrate and update data alongside your database structure.](https://github.com/ilyakatz/data-migrate)

2021-09-28 04:57 UTC, gentamura commented on lib/tasks/issues/issue3038/add_commented_at_in_products.rake
> +namespace :issues do
Fixed fa40ccf :+1:

2021-09-28 04:58 UTC, gentamura commented
@komagata 指摘部分修正しました:+1: 確認お願いします:pray:

2021-09-28 17:54 UTC, komagata commented on db/data/20210928044140_add_commented_at_in_products.rb
> +class AddCommentedAtInProducts < ActiveRecord::Migration[6.1]
二度手間になってしまってすみません、この間、最終メンターコメント日時を既存の提出物に入れるmigrationをやった時実行に8時間ぐらいかかってリリースが失敗するということがありました。

ですので、できれば下記にtaskとして実装していただければ助かります。

https://github.com/fjordllc/bootcamp/blob/63cf311cb7b932defafb263dd02e76a344f4c3b0/lib/tasks/bootcamp.rake#L30

この名前のtaskはCloud Buildから単体で実行できるようにしていて、制限時間を12時間にしているためです。

2021-09-30 05:16 UTC, gentamura commented on db/data/20210928044140_add_commented_at_in_products.rb
> +class AddCommentedAtInProducts < ActiveRecord::Migration[6.1]
@komagata こちら対応しました！確認お願いします:pray: 6056c53

2021-10-01 14:07 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-10-01 14:08 UTC, merged