ダッシュボード画面にアクセス時のN+1を改善
fjordllc/bootcamp pull request #3314
Opened 2021-09-26 06:41 UTC by gentamura

ref: #3276

2021-09-28 01:30 UTC, gentamura commented on app/controllers/api/notifications_controller.rb
> +                                 .includes(sender: [:company])
bulletのwarningsを解消

2021-09-28 01:30 UTC, gentamura commented on app/controllers/api/reports/recents_controller.rb
> +               .includes(:checks, user: [{ avatar_attachment: :blob }, :company])
bulletのwarningsを解消

2021-09-28 01:31 UTC, gentamura commented on app/controllers/home_controller.rb
> +    @inactive_students_and_trainees = users.inactive_students_and_trainees
active storageを対象にbulletのwarningsがでていたので、`with_attach_avatar`で解消

2021-09-28 01:31 UTC, gentamura commented on app/controllers/home_controller.rb
> +    users = User.with_attached_avatar
active storageを対象にbulletのwarningsがでていたので、`with_attach_avatar`で解消

2021-09-28 02:04 UTC, gentamura commented
@konaga-k ちょっと重たいですがお手すきでReviewお願いします:pray:

2021-09-28 03:19 UTC, konaga-k commented
@gentamura 
タスクが積もってるので土曜日以降の返事になりそうです〜
（急ぎなら別の人にレビューリクエストしてもらえると）

2021-09-28 04:28 UTC, gentamura commented
@yana-gi お手すきでReviewいただけると助かります:pray:

2021-09-28 07:44 UTC, yana-gi commented
@gentamura 
こちらレビュー着手しても問題ないでしょうか？
今日のMTGを踏まえ修正予定であれば待ちます〜🙋‍♂️

2021-09-28 07:50 UTC, gentamura commented
@yana-gi 一旦、そのままレビューしてもらえると助かりますー🙏

2021-09-28 08:04 UTC, yana-gi commented
@gentamura
了解です〜！

2021-09-28 10:53 UTC, yana-gi reviewed
一通り見ました！
SQL作成からrailsのコードに落とし込むまで大変だったかと思います。お疲れ様でした🍵

テストに関して1点コメントしましたので確認お願いします！

データ取得周りは動作確認までしかちゃんと見れていないです。すみません……！
SQLですが、[ウィンドウ関数](https://www.postgresql.jp/docs/9.2/tutorial-window.html)が使えそうと思いました。自分で色々試してみたのですがいいSQLの組み立てが思いつかず……。gentamuraさんの方でもウィンドウ関数で検討されてみてもよさそうです（既に検討済みだったらすみません）

参考 (ユーザーごとに日報を新しい順で取得するSQL)
```sql
SELECT 
  user_id,
  reported_on,
  RANK() OVER (PARTITION BY user_id ORDER BY reported_on DESC) as latest_rank 
FROM reports;
```
```
  user_id  | reported_on | latest_rank 
-----------+-------------+-------------
  46191349 | 2020-06-01  |           1
  46191349 | 2020-01-01  |           2
  46191349 | 2017-01-01  |           3
  46191349 | 2000-01-01  |           4
  46191349 | 1900-01-01  |           5
 253826460 | 2021-09-18  |           1
 253826460 | 2021-09-17  |           2
 253826460 | 2021-08-19  |           3
 253826460 | 2021-08-18  |           4
```

2021-09-28 10:53 UTC, yana-gi commented on test/models/user_test.rb
> +  end
`users(:komagata, :hatsuno, :kensyu)` の3ユーザーそれぞれがどんな日報データを持っているのかテストコード上では不明のため、テストで何をやっているのか分かりにくくと感じました。
`test/fixtures/reports.yml`を見れば分かることですが、参照しなくても分かるようにユーザーそれぞれに変数名をつけると親切そうです。
（参考 : https://github.com/fjordllc/bootcamp/pull/3314/files#diff-91bef9fda3c55514e23a4a8edba948f68aad59b57951adcff0b11e9ea9159854R158-R159 ）

また`ids`のユーザーには`students_and_trainees` && `!depressed?` なユーザーをテストユーザーを含むとより安心なテストになると思いました〜

2021-09-30 07:11 UTC, gentamura commented on test/models/user_test.rb
> +  end
@yana-gi こちら修正しました〜:pray: 0131147fa03103193d6331e6fe248282874d1ef1

2021-09-30 07:21 UTC, gentamura commented
@yana-gi 
Reviewありがとうございます〜 :pray:

> データ取得周りは動作確認までしかちゃんと見れていないです。すみません……！ SQLですが、[ウィンドウ関数](https://www.postgresql.jp/docs/9.2/tutorial-window.html)が使えそうと思いました。自分で色々試してみたのですがいいSQLの組み立てが思いつかず……。gentamuraさんの方でもウィンドウ関数で検討されてみてもよさそうです（既に検討済みだったらすみません）

自分もRank関数は試したんですが、対象の間に `emotion != sad` があると、その対象外を除いてRankがシリアルに表示されるため、希望通り拾えなく断念しました🙃 

test部分更新したので、改めて確認お願いします:pray:

2021-09-30 08:52 UTC, yana-gi reviewed
> 自分もRank関数は試したんですが、対象の間に emotion != sad があると、その対象外を除いてRankがシリアルに表示されるため、希望通り拾えなく断念しました🙃

そうだったんですね、いやあお疲れ様でした……🙃

テストの修正ありがとうございます！
1点だけちょっと気になったので追加でコメントしました。確認お願いします〜🙏

2021-09-30 08:52 UTC, yana-gi commented on test/models/user_test.rb
> +    users = User.where(id: ids)
```suggestion
    users = [no_depressed_user, first_depressed_user, second_depressed_user]
```

`User.where(id: ids)`でusersを取得する必要がある理由があれば知りたいです！
なければ配列に入れてしまった方がコードがスッキリすると思いました〜

2021-10-01 07:52 UTC, gentamura commented on test/models/user_test.rb
> +    users = User.where(id: ids)
@yana-gi こちらは `User.depressed_reprots` のなかで `ids`メソッドをつかっているので、`ActiveRecord::Relation` として渡したいため、`users`を取得していますー :+1:

2021-10-01 08:06 UTC, yana-gi commented on test/models/user_test.rb
> +    users = User.where(id: ids)
なるほど……！勉強になりました〜ありがとうございます😄

2021-10-01 08:06 UTC, yana-gi approved these changes
@gentamura 
確認ありがとうございます！approveしました〜🙆‍♂️

2021-10-01 08:25 UTC, gentamura commented
@komagata お手すきでレビューお願いします:pray:

2021-10-01 14:09 UTC, komagata reviewed
merge commitが含まれていますが、こちらは必須のものでしょうか？

2021-10-02 07:29 UTC, gentamura commented
@komagata f388c48 はconflictの解消でマージしています。includesの指定自体は同じ内容だったのでmainブランチ側を生かしましたー。

2021-10-04 06:39 UTC, komagata commented
@gentamura このプロジェクトでは他のブランチを取り込むときrebaseで取り込んで、マージコミットができないような形でお願いしているのでそっちのやり方でお願いしたいです〜

2021-10-05 01:41 UTC, gentamura commented
@komagata コンフリクト解消しましたので、改めて確認お願いします:pray:

2021-10-05 11:44 UTC, komagata requested changes

2021-10-05 11:44 UTC, komagata commented on app/models/user.rb
> +    def depressed_reports_on_first(users, max_reported_on)
privateになってるメソッドがテストしたくなる場合（テストがないと心配なぐらい複雑になってる場合）、クラスに抜き出すべきシグナルという話があります。

また、同じ名詞がメソッドに複数出てきた時もクラスに抜き出すべきシグナルになります。

[[RubyTips] 頻出名詞をクラスに抜き出す - komagataのブログ](https://docs.komagata.org/5733)

クラスに抜き出して設計してみると良さそうです〜。

2023-07-26 05:05 UTC, closed without merging