ダッシュボードの「1ヶ月以上ログインのないユーザー」を降順ソートで表示
fjordllc/bootcamp pull request #3325
Opened 2021-09-28 11:39 UTC by kaiyu-tech

- ダッシュボードの「1ヶ月以上ログインのないユーザー」を降順ソートで表示する

※ 修正前
![image](https://user-images.githubusercontent.com/73627898/135078879-5659daab-30e0-4f7d-92ab-d4cb61db1ca3.png)

※ 修正後イメージ
![image](https://user-images.githubusercontent.com/73627898/135078906-b4a2fc9f-2bfb-4771-8a70-09ad017ead24.png)

- Userテーブルの`updated_at`が最終ログイン日時として扱われているので、`updated_at`を降順ソートする

2021-09-28 12:00 UTC, kaiyu-tech commented
@haruguchi-yuma お手すきの際にこちらのレビューお願いいたします🙏

2021-09-29 23:56 UTC, haruguchi-yuma reviewed
@kaiyu-tech 
OKだと思います！LGTM💪

2021-09-30 00:06 UTC, kaiyu-tech commented
@haruguchi-yuma ありがとうございます！

@komagata お手すきの際にこちらのレビューをお願いいたします🙏

2021-10-01 14:04 UTC, komagata requested changes

2021-10-01 14:04 UTC, komagata commented on app/models/user.rb
> +    ).order(updated_at: :desc)
このスコープを使っている他のプログラムに影響があるかもしれないので、ここでソートを変更しない方が良いかもです〜

2021-10-01 18:29 UTC, kaiyu-tech commented on app/models/user.rb
> +    ).order(updated_at: :desc)
データのソートをするタイミングを使用する直前に変更しました。
この対応でよかったでしょうか？ご確認お願いします🙏

2021-10-02 01:01 UTC, kaiyu-tech commented
@komagata 修正いたしましたので再レビューをお願いいたします🙏

2021-10-04 06:37 UTC, komagata requested changes

2021-10-04 06:37 UTC, komagata commented on app/views/home/index.html.slim
> +            = render 'users/inactive_users', users: User.inactive_students_and_trainees.order(updated_at: :desc)
ちょっと長くなるのでcontrollerで処理した方が良いかもです〜

2021-10-04 07:04 UTC, kaiyu-tech commented on app/views/home/index.html.slim
> +            = render 'users/inactive_users', users: User.inactive_students_and_trainees.order(updated_at: :desc)
並び替え処理をコントローラーに移動しました。
この対応でよかったでしょうか？

2021-10-04 07:04 UTC, kaiyu-tech commented
@komagata 修正いたしましたので再レビューをお願いいたします🙏

2021-10-04 07:07 UTC, komagata requested changes

2021-10-04 07:07 UTC, komagata commented on app/controllers/home_controller.rb
> +        @ordered_inactive_students_and_trainees = User.inactive_students_and_trainees.order(updated_at: :desc)
変数名が長いので@inactive_studentsぐらいでいい気がします〜

2021-10-04 07:14 UTC, kaiyu-tech commented on app/controllers/home_controller.rb
> +        @ordered_inactive_students_and_trainees = User.inactive_students_and_trainees.order(updated_at: :desc)
変数名を短縮しました！
これでよろしいでしょうか？

2021-10-04 07:23 UTC, kaiyu-tech commented
@komagata 修正いたしましたので再レビューをお願いいたします🙏

2021-10-04 10:12 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-10-04 10:12 UTC, komagata commented on app/controllers/home_controller.rb
> +        @inactive_students = User.inactive_students_and_trainees.order(updated_at: :desc)
👍

2021-10-04 10:12 UTC, merged