[メンター向け]進捗が遅れている方を確認できるようにする
fjordllc/bootcamp pull request #3352
Opened 2021-10-05 12:19 UTC by kaiyu-tech

ref #3344

![image](https://user-images.githubusercontent.com/73627898/136013097-14bbc691-cc64-4b67-b7cb-addb27f8b8a9.png)

- メンターだけが見れるページを /mentorに作る。（/adminと似た作りにする）
- プラクティスを最後に完了してから二週間以上経っている人を表示する。
- プラクティスを最後に完了してからの経過時間が大きい順に表示する。

2021-10-19 05:06 UTC, machida commented
変更ファイルが多いので、レビューで見るところをピックアップしておきます。

app/controllers/mentor/home_controller.rb
app/controllers/mentor_controller.rb
app/views/mentor/home/index.html.slim
app/controllers/api/mentor_controller.rb
app/javascript/packs/application.js
app/javascript/worried-user.vue
app/javascript/worried-users.js
app/javascript/worried-users.vue
app/views/api/mentor/index.json.jbuilder
app/views/mentor/home/index.html.slim
config/routes.rb
db/fixtures/products.yml

2021-10-19 15:24 UTC, konaga-k requested changes
@kaiyu-tech 
事情がわからないんですが、このPRに関係ない https://github.com/fjordllc/bootcamp/pull/3198/ の差分が入ってますね
https://github.com/fjordllc/bootcamp/pull/3198/ はもうmainブランチにマージされているので、 `git pull --rebase origin main` してから一旦force pushしたら、GitHub上からいい感じに差分の表示が消えませんかね？
指摘事項の修正前に一度試してもらえるといいかなと思います

---
【MUST】は修正しておいてください〜
【IMO】は好みでやってもらえれば
【Q】は単なる質問です

このissueの難易度が高いのと、指摘している自分も自信がない箇所があるので、メンターにペアプロの申込なりレビュー依頼なりしてもいいと思います
自分がこのissueの担当者だったら、誰かメンターの人を捕まえて、☆を付けた部分は相談しながら進めると思います

---
あとdescriptionに貼るイメージ画像は、ワイヤーフレームではなく実ページのスクリーンショットにしておいてください〜
![image](https://user-images.githubusercontent.com/54785890/137952802-022ac1fb-f83f-42c0-943f-d39c4d81f268.png)

2021-10-19 16:42 UTC, machida commented
@kaiyu-tech 中途半端なところまででちゃんと連絡してなくてすいません🙇‍♂️ デザイン入れましたー

2021-10-19 23:33 UTC, kaiyu-tech commented
@konaga-k
ボリュームがあって大変な中、細かなところまでレビューをありがとうございます🙇‍♂️
私が理解できて回答しやすいところから順番に返させていただきますので、お手数おかけしますがお手隙の際に再確認していただければ助かります！

@machida 
これはもしかして私が、デザインが途中の段階なのに取り込んでしまったのでしょうか💦
詳細については、ふりかえりミーティングで質問させていただこうと思います！

2021-10-20 02:24 UTC, machida commented
@kaiyu-tech いえいえ、デザインはこの状態で大丈夫ですー 今後この画面に機能追加が色々されていきそうなので、それに伴いデザインも色々変わりそうです

2021-10-30 15:42 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-10-30 15:42 UTC, merged