プラクティスと参考書籍を多対多の関係に修正と機能追加
fjordllc/bootcamp pull request #3426
Opened 2021-10-20 14:48 UTC by rjtt17

issue: #[3000](https://github.com/fjordllc/bootcamp/issues/3000)

以下を実装しました

- プラクティスと参考書籍を多対多の関係に修正
- 参考書籍CRUD機能追加
- プラクティスの追加・修正画面で登録されている参考書籍を選択して登録する機能追加
- 既存データ移行のためdata migrationのファイルを作成

---

**変更点**

+ 参考書籍のCRUD機能

![image](https://user-images.githubusercontent.com/52092916/139562741-3e8c0302-0aa9-40c4-8f5a-c325c7b75400.png)

![image](https://user-images.githubusercontent.com/52092916/139562762-75ba3b90-3ad2-447c-b7b3-040ec43dbfda.png)

+ プラクティスの追加・修正画面で登録されている参考書籍を選んで登録できる機能
![image](https://user-images.githubusercontent.com/52092916/139562787-04f7bc8b-244f-4d07-9477-5ccf89ed8f7c.png)

2021-10-31 01:18 UTC, rjtt17 commented
@IkumaTadokoro 
お手隙の際にレビューをして頂けないでしょうか？🙏

2021-11-01 08:22 UTC, IkumaTadokoro reviewed
遅くなりましたが、レビューさせていただきました👀
ご確認よろしくお願いいたします🙇‍♂️

2021-11-01 08:22 UTC, IkumaTadokoro commented on test/system/books_test.rb
> +    assert_no_text '参考書籍 作成'
![badge](https://img.shields.io/badge/review-ask-blue.svg)
3c23e6f96f926abd0505890ae01a6d18fde5ae1c で町田さんが参考書籍作成ページのタイトルを、`参考書籍 作成`から、`参考書籍作成`に変更されているので、メンターであろうとなかろうと通ってしまうアサーションではないでしょうか？🤔

2021-11-03 01:21 UTC, rjtt17 commented on app/views/practices/_practices_book_fields.html.slim
> +        = f.select(:book_id, Book.all.collect { |book| [book.title, book.id] }, { include_blank: true }, { class: 'js-select2' })
参考等教えて頂きありがとうございました！こちらについて、一旦このままの仕様に致します〜

2021-11-03 01:23 UTC, rjtt17 commented on db/fixtures/practices_books.yml
> +  practice: paractice1
typo教えて頂きありがとうございました🙏
```test/fixtures```について、テスト内容に影響があるので助かりました！

2021-11-03 01:24 UTC, rjtt17 commented on app/views/books/index.html.slim
> +              = link_to new_book_path, class: 'a-button is-md is-secondary is-block' do
教えて頂きありがとうございました🙏
インデントのスペースについて2つに合わせました！

2021-11-03 01:27 UTC, rjtt17 commented on test/system/books_test.rb
> +    assert_no_text '参考書籍 作成'
```assert_no_text '参考書籍 作成'```のテストについて、意味がなかったので、削除しました！

2021-11-03 01:29 UTC, rjtt17 commented
@IkumaTadokoro
お忙しい中、レビューありがとうございました🙇‍♂️
修正しましたので、再度レビューをして頂けないでしょうか？🙏

2021-11-04 02:21 UTC, IkumaTadokoro commented
@rjtt17 

お疲れ様です！修正いただきありがとうございました！
再度動作含めて確認しましたが大丈夫そうです〜😊

2021-11-04 03:21 UTC, rjtt17 commented
@IkumaTadokoro
お忙しい中、再度レビューありがとうございました🙇‍♂️
pending reviewerになっているので、レビュー依頼をApproveして頂けないでしょうか？🙏

2021-11-04 03:27 UTC, IkumaTadokoro approved these changes
> pending reviewerになっているので、レビュー依頼をApproveして頂けないでしょうか？🙏

失礼しました！💦これで大丈夫でしょうか？

2021-11-04 04:05 UTC, rjtt17 commented
> > pending reviewerになっているので、レビュー依頼をApproveして頂けないでしょうか？🙏
> 
> 失礼しました！💦これで大丈夫でしょうか？
@IkumaTadokoro
お忙しい中、お手数をお掛けしました🙇‍♂️
Approveありがとうございます！

2021-11-04 11:48 UTC, rjtt17 commented
@komagata
お手隙に際にレビューをお願いいたします🙇‍♂️
また、本番で参考書でテータ移行で（data migrationに時間がかかる等）問題が起きないかの観点も確認して頂けないでしょうか。

2021-11-04 12:43 UTC, komagata requested changes

2021-11-04 12:43 UTC, komagata commented on app/javascript/packs/application.js
> +require('../reference-books-form-add.js')
reference_bookという名前を廃してbookを使えるようにしたので全般的にreference_bookという単語は使わないように統一したい感じです〜

2021-11-04 12:43 UTC, komagata commented on app/javascript/reference-books-form-add.js
> +    $('.js-select2').select2({
sprocketsを廃止してwebpackに統一するために最後に残った二つのライブラリ（select2とcocoon）を置き換える作業を別件で長い間進めております。

Q&Aのプラクティス絞り込みのところでselect2の代わりのライブラリが使われているはずなのでそちらを参考にしてselect2を使わない実装にして見てください〜

2021-11-04 13:15 UTC, konaga-k commented on app/javascript/reference-books-form-add.js
> +    $('.js-select2').select2({
@rjtt17 
よかったら参考にどうぞ〜（自分が実装したところへの言及を見かけたのでコメント）
https://github.com/fjordllc/bootcamp/pull/3204

2021-11-04 13:26 UTC, rjtt17 commented on app/javascript/reference-books-form-add.js
> +    $('.js-select2').select2({
@konaga-k 
ありがとうございます〜！参考にしてみます！

2021-11-05 15:11 UTC, komagata commented on app/javascript/reference-books-form-add.js
> +    $('.js-select2').select2({
> @rjtt17
> よかったら参考にどうぞ〜（自分が実装したところへの言及を見かけたのでコメント）
> #3204

情報ありがとうございます〜！

2021-12-01 13:11 UTC, komagata commented
@rjtt17 こちらいかがでしょうか〜

2021-12-01 13:50 UTC, rjtt17 commented
@komagata 
時間がかかってしまい申し訳ございません🙇‍♂️
修正をしようとしているのですが、上手くいかず煮詰まってしまっているので、
来週までに自力で考えてみて難しい場合は、質問タイムかペアプロを利用させて頂き進めいて行きたいと思います！

2021-12-01 15:46 UTC, machida commented
@rjtt17 全然申し訳なくないですよー 😄 ハマったときこそ、ペアプロなどを依頼しまくったりしてフィヨルドブートキャンプをフル活用してくださいー！！

2021-12-03 10:30 UTC, komagata commented
@rjtt17 了解です〜、お気軽にペアプロなど依頼相談してくださいね〜！

2021-12-03 14:32 UTC, rjtt17 commented
@machida @komagata ありがとうございます！来週まで挑戦してみて難しそうであれば、質問タイムかペアプロで相談させて頂きます〜

2021-12-08 11:56 UTC, rjtt17 commented
@machida @komagata
もう少しで、糸口がつかめそうなので、今週末まで取り組む時間を下さい🙏

2021-12-15 12:47 UTC, rjtt17 commented
@machida @komagata
やはり、難しそうなのでDiscordチャネルでペアプロ・モブプロについてお願いさせて頂きました！
お時間がかかってしまい、大変申し訳ありません。

2021-12-21 07:16 UTC, komagata commented
@rjtt17 いえいえ、全く問題ございませんよ〜！

2021-12-22 13:05 UTC, rjtt17 commented
@machida @komagata
先週の日曜日に@ShotaTsuru とペアプロさせて頂き、詰まっている部分についてある程度解消できました！
来週までPRを修正できるよう進めます。よろしくお願いします🙇‍♂️

2021-12-23 01:44 UTC, machida commented
@rjtt17
おお、良かったですー！！
状況をまめにチャットで連絡いただけると助かります🙏

2022-01-31 00:28 UTC, rjtt17 commented on app/javascript/packs/application.js
> +require('../reference-books-form-add.js')
```reference-books-form-add.js``` について、削除しました〜

2022-01-31 00:31 UTC, rjtt17 commented
@komagata 
時間がかかってしまし大変申し訳ありません。select2で実装した選択肢をmultiselectでの実装に変更致しました〜
お手すきの際に、再度レビューして頂けないでしょうか？🙇‍♂️

よろしくお願い致します。

2022-01-31 16:07 UTC, komagata requested changes

2022-01-31 16:07 UTC, komagata commented on app/javascript/book-select.vue
> +  },
dataは定義的なものを置くところだと思うので、dataを設定するのはmountedとかcreatedとかでやるのがいいと思います〜

2022-01-31 16:07 UTC, komagata commented on app/views/practices/_practices_book_fields.html.slim
> +        - books = Book.all.collect { |book| [book.id, book.title] }
viewのこういう処理はViewHelper（helper）に書くといいかもです〜

2022-01-31 16:07 UTC, komagata commented on test/system/books_test.rb
> +    click_on '内容を保存'
他のテストのようにで複数入力あるformはなるべくwithinでまとめたいですね〜

2022-02-02 12:36 UTC, rjtt17 commented
お忙しい中、レビューありがとうございます🙇‍♂️ 
修正を進めていきます〜

2022-02-23 13:45 UTC, rjtt17 commented on app/views/practices/_practices_book_fields.html.slim
> +        - books = Book.all.collect { |book| [book.id, book.title] }
教えて頂きありがとうございます！ViewHelper ([app/helpers/practices_helper.rb](https://github.com/fjordllc/bootcamp/pull/3426/files#diff-00651d368110cbb03a077e7907d9464b33caee9ab9d8044db066ef170da5befb)) に書くように変更しました〜

2022-02-23 13:47 UTC, rjtt17 commented on app/javascript/book-select.vue
> +  },
教えて頂きありがとうございます！
```created```で処理するように変更いたしました〜

2022-02-23 13:51 UTC, rjtt17 commented on test/system/books_test.rb
> +    click_on '内容を保存'
教えて頂きありがとうございます！
複数入力あるformをwithinでまとめるように修正しました〜
(https://github.com/fjordllc/bootcamp/pull/3426/commits/95f4fe41005b41cc7a739738cb1d26695abc3787)

2022-02-23 13:53 UTC, rjtt17 commented
@komagata
ご指摘頂いた3点について、修正致しました〜
お手すきの際に、再度レビューして頂けないでしょうか？🙇‍♂️

よろしくお願い致します。

2022-02-26 16:45 UTC, komagata reviewed
conflictの修正お願い致します〜

2022-02-28 13:32 UTC, rjtt17 commented
> conflictの修正お願い致します〜

@komagata 
conflictの解消を致しました〜！
お手隙の際に、ご確認お願い致します🙇‍♂️

2022-03-01 05:34 UTC, komagata requested changes

2022-03-01 05:34 UTC, komagata commented on app/javascript/book-select.vue
> +</style>
すみません、この部分、BootcampではCSSはruby側でコンパイルしていて、この部分を動かすにはCSSをJS側で動かす必要があり、この部分のためだけにビルドが遅くなるのを避けたいのでできればコンポーネントではなくCSSファイルの方でデザイン指定していただけるとありがたいです〜

（今後これを使えるようにするかもですが、しばらく後の話になっちゃいそうです〜）

2022-03-01 05:34 UTC, komagata commented on db/fixtures/books.yml
> +book2:
```suggestion
  description: Rubyを始める人にピッタリの本です！

book2:
```

2022-03-01 05:34 UTC, komagata commented on test/fixtures/books.yml
> +book2:
```suggestion
  description: Rubyを始める人にピッタリの本です！

book2:
```

2022-03-09 13:03 UTC, rjtt17 commented
レビューありがとうございます🙇‍♂️　修正していきます〜

2022-03-31 14:29 UTC, rjtt17 commented
> @rjtt17 こちら大丈夫でしょうか？もし、詰まっていたらペアプロなどを活用してみてくださいー

@machida ご心配頂きありがとうございます！ もう少しやって、難しい場合は、ペアプロ活用させて頂きます〜

2022-05-25 07:46 UTC, machida commented
@rjtt17 こちら大丈夫でしょうか？もし、詰まっていたらペアプロなどを活用してみてくださいー

2022-05-27 08:43 UTC, machida commented
@rjtt17 こちら状況いかがでしょうか？一報いただけると助かります。

2022-05-27 11:00 UTC, rjtt17 commented
@machida 
ご連絡が遅くなり、申し訳ありません！
ご指摘頂いた修正は完了したのですが、コンフリクトが多くて、コンフリクト解消中です。
今日夜に、コンフリクト解消作業をして、今週末までに再度pushできるように致します。本当に申し訳ありません。

2022-05-29 15:23 UTC, rjtt17 commented on db/fixtures/books.yml
> +book2:
ご指摘いただきありがとうございます！
book2の前に行を追加しました〜

2022-05-29 15:23 UTC, rjtt17 commented on test/fixtures/books.yml
> +book2:
ご指摘いただきありがとうございます！
book2の前に行を追加しました〜

2022-05-29 15:28 UTC, rjtt17 commented
@komagata
CC： @machida
大変遅くなり申し訳ありません。
ご指摘頂いた部分の修正が完了したのでお手すきの際に、再度レビューして頂けないでしょうか？🙇‍♂️

2022-05-30 05:36 UTC, machida commented
@rjtt17 ご連絡ありがとうございます！

2022-05-30 17:54 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-05-30 17:54 UTC, komagata commented on db/data/20211018115935_convert_book_to_practices_book.rb
> +class ConvertBookToPracticesBook < ActiveRecord::Migration[6.1]
👍

2022-05-30 17:54 UTC, merged

2022-05-30 17:55 UTC, komagata commented
@rjtt17 ご連絡ありがとうございます！
PR助かります〜！

2022-06-01 10:58 UTC, rjtt17 commented
@komagata 
ご連絡が遅くなり申し訳ありません。PRのご確認ありがとうございました🙇‍♂️
[Release 2022-05-30 18:02:40](https://github.com/fjordllc/bootcamp/pull/4906)についてステージングを確認して、自分のPR自体の動作は問題ないのですが、おそらく自分の今回のPRの影響で他の方のテストが落ちていると思うので、今回のステージングのマージをリバートして頂くことは可能でしょうか？🙏

https://discord.com/channels/715806612824260640/809595476847493192/981349137360519218

2022-06-01 11:58 UTC, komagata commented
@rjtt17 リバートは基本的に緊急事態にしかやらないので、急いでるわけではないのでまだ大丈夫です〜

2022-06-01 12:45 UTC, rjtt17 commented
@komagata 
ご回答ありがとうございました。承知しました！先ずは、修正方法を調査します！