Docにブックマーク機能を追加
fjordllc/bootcamp pull request #3466
Opened 2021-10-28 05:15 UTC by IkumaTadokoro

## 概要

- refs: #3233 
- Docsにブックマーク機能を追加する

## やったこと

- DocsページにBookmarkボタンを追加
    - UIおよびBookmark処理自体は既存のものを使用。
    - 既にBookmark導入済み機能同様、ブックマーク一覧での参照、編集が可能。
- ブックマークボタンレンダリング部分の重複している条件式を削除
    - https://github.com/fjordllc/bootcamp/pull/3466/files#diff-99e5cb3d3e0c7e383b0ae71851491a608b0981d6b038a68a98ebe2bffe521fd2L10
    - なくても動作することを確認したので、本PRで削除しました。

## UIの変更

### 変更前

![image](https://user-images.githubusercontent.com/61409641/139190562-f5d37a32-0939-402c-b633-4518f5a4d095.png)

### 変更後

![image](https://user-images.githubusercontent.com/61409641/139190195-afa55172-9d89-4703-8e7a-54d4453f3924.png)

2021-11-01 13:26 UTC, kawase-k commented
@IkumaTadokoro さん
ご連絡遅くなり申し訳ございません🙏
先ほど確認したところ、いいと思います🎉

テストを書かれているのがすばらしくて、特にBookmarkのシステムテストは色々なパターンで使われていると思うのでファイル分割されて作られているもの勉強になりました！

> ブックマークボタンレンダリング部分の重複している条件式を削除

こちらも問題なそうです👌
お疲れさまでした！！

参考にしたIssueとPR
- https://github.com/fjordllc/bootcamp/issues/3232
- https://github.com/fjordllc/bootcamp/pull/3257

2021-11-02 04:59 UTC, IkumaTadokoro commented
@kawase-k 
レビューいただきありがとうございました🙇‍♂️

2021-11-02 05:00 UTC, IkumaTadokoro commented
@komagata 
お手数ですが、こちらレビューお願いいたします〜🙇‍♂️

2021-11-03 15:16 UTC, komagata requested changes
ブックマークした時にtoastの通知も出る部分もお願いします〜

2021-11-04 03:32 UTC, IkumaTadokoro commented
@komagata 

> ブックマークした時にtoastの通知も出る部分もお願いします〜

システムテストにtoastのメッセージ確認を追加する、ということであっておりますでしょうか？🙇‍♂️

2021-11-04 05:26 UTC, komagata commented
@IkumaTadokoro いえ、toastの実装自体がされてないかと勘違いしておりました。実装されているのであればOKです〜

2021-11-04 05:26 UTC, merged