ユーザーのステータスが卒業になったら運営のチャットに通知されるようにしました
fjordllc/bootcamp pull request #3471
Opened 2021-10-29 11:07 UTC by kawase-k

- Issue #3368 

## 前提
今回のIssueは開発環境と本番環境で実装する内容が変わってくるため、変更分をそのままマージすることができません。
なのでレビューで動作確認をする際は下でまとめた確認方法の手順を行っていただく必要があります。

## 確認方法
1. 手元に本ブランチを持ってくる
1. `dotenv-rails`というgemをインストールする
参考：[Railsで使える環境変数を管理できるgem(dotenv-rails)や.envの導入方法 - Qiita](https://qiita.com/ryosuketter/items/ceb592dc6b23a20e51b5)

```ruby
# Gemfile
gem 'dotenv-rails' # 1番下に追加しました
```
```
% bundle install
```

3. .envファイルをbootcapmディレクトリ直下に作成する

```
% touch .env
```

4. 自分用のDiscordサーバーを作成する
参考：[Discord – サーバーの作り方と削除する方法 - 設定Lab](https://setup-lab.net/discord-server-creation-delete/#:~:text=Discord%E3%81%AE%E3%83%9B%E3%83%BC%E3%83%A0%E3%81%A7%E3%80%8C%2B%E3%80%8D,%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%8C%E4%BD%9C%E6%88%90%E3%81%95%E3%82%8C%E3%81%BE%E3%81%99%E3%80%82)
5. 4.で作成したサーバーのウェブフックURLをコピーしておく

![Image from Gyazo](https://gyazo.com/55a12eb8a8f25b7a906e34694ae278b5.gif)

6. コピーしたウェブフックURLを環境変数として使いたいので、作成した.envファイルには下の内容を追記する

```env
DISCORD_TEST_WEBHOOK_URL = コピーしたウェブフックURL
```

7. app/model/chat_norifier.rbのmessageメソッドの記述を変更する

```ruby
# app/model/chat_norifier.rb
class ChatNotifier
  def self.message(
    message,
    username: 'ピヨルド',
    webhook_url: ENV['DISCORD_NOTICE_WEBHOOK_URL']
  )

-   if Rails.env.production?
+   if Rails.env.development?
      Discord::Notifier.message(message, username: username, url: webhook_url)
    else
      Rails.logger.info 'Message to Discord.'
    end
  end
..
```

Rails.env.development?にすることでtrueの分岐を実行することができます。
参考：[【Rails】 envメソッドで環境を確認する方法と各コマンドの指定方法 - Pikawaka](https://pikawaka.com/rails/env)

8. 動作確認をする

- 管理画面で現役生の卒業ボタンをクリックする
  - ![image](https://user-images.githubusercontent.com/74460623/139433203-1bb60cfb-be46-46c8-9725-964b827e4141.png)
- 自分で作成したDiscordチャンネルに通知がくるのを確認する
  - <img width="350" alt="スクリーンショット 2021-10-29 12 16 57" src="https://user-images.githubusercontent.com/74460623/139433464-a0e10dd1-90d3-4cca-9038-7476a0ada24e.png">

以上で確認は終わりになります。
不明な点がございましたらお手数おかけしますがご連絡のほどよろしくお願いいたします🙇‍♂️

2021-10-31 12:44 UTC, mami-inuzuka commented
@kawase-k お疲れ様です！！こちら確認いたしました✨
大変わかりやすくまとめてくださりありがとうございます🙇🏻‍♂️
そして動作確認も問題ありませんでした👌良さそうだと思います😊
（環境変数の扱いなども勉強になりました🙏！）

一点質問なのですが、今回使用した`dotenv-rails`はローカル環境での確認用に使うものであって本番では何か別の方法で環境変数が管理されている感じなのでしょうか？💡
最終的にどうやって実際の値が本番環境に反映されることになるんだろうと気になり質問させていただきました🙏
（そこのあたりよくわかっておらず恐縮です🙇🏻‍♂️）

2021-11-01 14:20 UTC, kawase-k commented
@mami-inuzuka さん
レビューありがとうございます🙇‍♂️

> 一点質問なのですが、今回使用したdotenv-railsはローカル環境での確認用に使うものであって本番では何か別の方法で環境変数が管理されている感じなのでしょうか？💡

`dotenv-rails`についてはその認識で使っていました。
本来はこういった共同開発でも環境変数を共存させて使うためのgemっぽいですが、本Issueの完了要件では自分のDiscordチャンネルに通知されるようになっていればOKだったのであまり深く考えていませんでした…。

本番環境での通知方法についてですが、僕が知る限りですと今回下のファイルで設定した環境変数にFBCの運営チャットまでの値を代入することで通知が飛ぶようになっているそうです〜。
参考：https://github.com/fjordllc/bootcamp/issues/3368#issuecomment-947662676

https://github.com/fjordllc/bootcamp/blob/20a273a844febd70d2c4ae9f4835d35d86615f49/app/controllers/graduation_controller.rb#L23-L28

管理されているか不確かなのですが、以下のファイルが関連してそうな気がしました！
`/bootcamp/cloudbuild.yaml`の77,78行目と112,113行目

当てずっぽうなところもありましたがコメントさせていただきました😅
よろしくお願いいたします🙏

2021-11-01 14:41 UTC, kawase-k commented
メモ: レビュー依頼の時はDraft Pull RequestではなくPull Requestにしないといけないので先ほど変更しました

2021-11-01 14:53 UTC, kawase-k commented
@komagata さん
こちらレビューお願いいたします🙇‍♂️

チームメンバーへのレビュー依頼のときは、こちらのhttps://github.com/fjordllc/bootcamp/pull/3471#issue-769140221 手順を作業していただいた上で通知の確認をするようにお願いしていました。

成果としては、
- 自分で作成したDiscordチャンネルに通知されるようになりました
- 用意したチャンネルまでは環境変数を使って通知されるようになっています

お聞きしたいことがあるのですが、
- 本番環境では環境変数はどういった仕組みで定義されていて使えるようになっているのでしょうか？

お手数おかけしますがご確認のほどよろしくお願いいたします🙏

2021-11-01 15:26 UTC, komagata commented
@kawase-k 

> 本番環境では環境変数はどういった仕組みで定義されていて使えるようになっているのでしょうか？

Bootcampの本番アプリはGoogle Cloud PlatformのCloud Buildというのでデプロイしています。
Cloud Buildでは環境変数を設定できるので、本番だけ別の環境変数を設定できるようになっています。

2021-11-01 15:27 UTC, komagata requested changes

2021-11-01 15:27 UTC, komagata commented on app/controllers/graduation_controller.rb
> +      webhook_url: ENV['DISCORD_TEST_WEBHOOK_URL']
本物の環境変数の名前にして見てください〜
本番環境ではその名前の環境変数に本物の値を設定するようにこちらの方でやります〜。

2021-11-02 00:40 UTC, kawase-k commented on app/controllers/graduation_controller.rb
> +      webhook_url: ENV['DISCORD_TEST_WEBHOOK_URL']
こちら卒業通知用として環境変数の名前をつけてみました。
再度ご確認のほどよろしくお願いいたします🙇‍♂️

2021-11-02 00:41 UTC, kawase-k commented
@komagata さん
ご教示いただきありがとうございます🙏

GCPといったデプロイ方法があるんですね。
ひとまずHerokuみたいなもの？と理解しました！

> Cloud Buildでは環境変数を設定できるので、本番だけ別の環境変数を設定できるようになっています。

そういうことだったんですね、勉強になります！！
デプロイ方法の仕組みついて知れてよかったです😆

2021-11-02 04:22 UTC, komagata commented
@kawase-k GCPはサービス・プラットフォームの名前です。AWSと同じですね。

その中に、Cloud BuildやCloud Runといったさまざまなサービスがあります。
AWSで言うとEC2やS3があるみたいな感じです。

2021-11-02 05:35 UTC, mami-inuzuka commented
かわせさん、こまがたさんありがとうございます！！

本番環境において環境変数の設定はCloud Build側で行っているんですね！
どこから読み込むかが異なっているだけでソースコードには本番で使用するのと同じ変数を記述すればいいということを理解しました！😊

勉強になりました🙏😊

2021-11-02 06:14 UTC, komagata commented
:memo: komagataのレビュー待ち

2021-11-03 15:35 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-03 15:35 UTC, merged