プラクティス個別ページの日報タブに数字を出すを実装
fjordllc/bootcamp pull request #3481
Opened 2021-10-31 08:48 UTC by ShotaTsuru

# What
プラクティス個別ページの日報タブに数字を出すを実装

2021-10-31 23:56 UTC, ShotaTsuru commented
@Ichiyo14 お手数ですがお時間のある時レビューお願い致します！

2021-11-01 11:05 UTC, Ichiyo14 commented
@ShotaTsuru 
右サイドにあるAssigneeへ @ShotaTsuru さんを割り当ててください。下記の赤い枠のところです！
<img width="457" alt="スクリーンショット 2021-11-01 19 50 17" src="https://user-images.githubusercontent.com/78020405/139661269-d8857eb3-159d-454c-ba6e-0c0a1ba446ed.png">
最上段のコメントにissueのリンクを記述していただくといいかもです！ 他のプルリクを参考にしてみてください🙏
上記コメントの部分の修正をよろしくお願いしますー。

2021-11-02 08:26 UTC, ShotaTsuru commented
承知致しました！ありがとうございます！

2021-11-04 13:08 UTC, Ichiyo14 requested changes

2021-11-05 02:45 UTC, ShotaTsuru commented on app/views/application/_page_tab.html.slim
> -      = tab[:display_name] + " （#{@practice.pages.length}）"
こちらpushする際のconfrictをremote上でいじってしまったことで発生しておりました。。
修正かけましたので大変お手数ですがご確認お願い致します！

2021-11-05 03:03 UTC, Ichiyo14 approved these changes

2021-11-05 03:06 UTC, Ichiyo14 commented
@ShotaTsuru 
確認しました！
良いと思います！

2021-11-05 06:59 UTC, ShotaTsuru commented
ありがとうございます！
@komagata 
メンバーレビューが終わりましたので、リーダーレビューお願い致します。

2021-11-05 16:18 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-05 16:18 UTC, merged