企業別のユーザー一覧で、「研修生」「全て」の区分けを実装
fjordllc/bootcamp pull request #3524
Opened 2021-11-05 14:59 UTC by Ichiyo14

issue: [\#3183](https://github.com/fjordllc/bootcamp/issues/3183)

2021-11-06 02:50 UTC, Ichiyo14 commented
@ShotaTsuru 
お時間がある時にレビューをお願いします🙏

2021-11-09 09:55 UTC, ShotaTsuru commented
@Ichiyo14 今現在レビューできる状態にないので申し訳ありあせんが、他の方にアサインいただいてもよろしいでしょうか？

2021-11-09 10:13 UTC, Ichiyo14 commented
@ShotaTsuru 
了解しましたー！

2021-11-15 01:22 UTC, mami-inuzuka commented on app/controllers/companies/users_controller.rb
> +        User.tagged_with(params[:tag])
@Ichiyo14 私の理解不足で申し訳ないのですが、企業別のユーザー一覧で現役生か全てを表示する上で、パラメータにtagが入るケースってどういう場合なんでしょうか？💡🙇🏻‍♂️
`if params[:tag]`がどういう時に必要になるのかがわからなかったので教えていただけると嬉しいです🙇🏻‍♂️

2021-11-15 01:23 UTC, mami-inuzuka commented
@Ichiyo14 こちらレビュー大変遅くなりすみません🙇🏻‍♂️
一件コメントさせていただいたのでご確認お願いします😊🙏

2021-11-15 10:18 UTC, Ichiyo14 commented on app/controllers/companies/users_controller.rb
> +        User.tagged_with(params[:tag])
@mami-inuzuka 
参考にしたコードの削除し忘れでした🙇‍♂️
必要ないコードでしたので削除しました！

2021-11-15 22:40 UTC, mami-inuzuka commented on app/controllers/companies/users_controller.rb
> +        User.tagged_with(params[:tag])
@Ichiyo14 なるほど！修正ありがとうございます！！✨それでは私からのレビューは以上です😊🙏

2021-11-17 09:33 UTC, Ichiyo14 commented
@mami-inuzuka 
レビューありがとうございました！

@komagata 
こちらのレビューをお願いします🙏

2021-11-17 18:09 UTC, komagata requested changes

2021-11-17 18:09 UTC, komagata commented on app/views/companies/users/index.html.slim
> +          - targets = %w[student_and_trainee all]
この内容が二箇所に書いてあると変更や追加があった時ミスしやすいのでこの情報一箇所で管理するようにしたいですね！

2021-11-18 03:17 UTC, Ichiyo14 commented on app/views/companies/users/index.html.slim
> +          - targets = %w[student_and_trainee all]
@komagata 
確認なのですが、``app/views/companies/users/index.html.slim``の１１行目のように、テンプレートファイルに切り分けて、管理した方がよいということでしょうか？
それとも、``この内容``というのは別のコードを指しているのしょうか？

2021-11-18 04:13 UTC, Ichiyo14 commented on app/views/companies/users/index.html.slim
> +          - targets = %w[student_and_trainee all]
@komagata
確認なのですが、app/views/companies/users/index.html.slimの１１行目のように、テンプレートファイルに切り分けて、管理した方がよいということでしょうか？
それとも、この内容というのは別のコードを指しているのしょうか？

2021-11-18 05:52 UTC, komagata requested changes

2021-11-18 05:52 UTC, komagata commented on app/views/companies/users/index.html.slim
> +          - targets = %w[student_and_trainee all]
app/controllers/companies/users_controller.rbの19行目にあるデータとここにあるデータが二重管理になっているという意味です〜

2021-11-18 09:36 UTC, Ichiyo14 commented on app/views/companies/users/index.html.slim
> +          - targets = %w[student_and_trainee all]
@komagata 
修正しました！ ご確認お願いします🙏

2021-11-21 16:50 UTC, komagata requested changes

2021-11-21 16:50 UTC, komagata commented on app/controllers/companies/users_controller.rb
> +    @targets = %w[student_and_trainee all]
意味として変数ではないので、Controllerの定数にするといいかもです〜

2021-11-22 10:15 UTC, Ichiyo14 commented on app/controllers/companies/users_controller.rb
> +    @targets = %w[student_and_trainee all]
@komagata 
定数に変更しました！ ご確認お願いします！

2021-11-22 15:25 UTC, komagata requested changes
このPRにmargeコミットができてしまっているようです。
mergeコミットができないようにコミットを修正してみてください〜

2021-11-23 06:59 UTC, Ichiyo14 commented
@komagata 
コミットを修正しました！ ご確認お願いします！

2021-11-24 13:44 UTC, komagata requested changes

2021-11-24 13:44 UTC, komagata commented on app/views/companies/users/index.html.slim
> +          - targets = %w[student_and_trainee all]
targetになりうるものを定義してある感じなので元は定数にすると良いかもです〜

2021-11-24 22:20 UTC, Ichiyo14 commented
@komagata 
rebaseがうまくいっていなかったようで、修正漏れが出てしまっていたみたいでした💦
何度も申し訳ないのですが、修正をしましたのでご確認をお願いします🙏

2021-11-26 09:39 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-26 09:39 UTC, komagata commented on app/controllers/companies/users_controller.rb
> +  TARGETS = %w[student_and_trainee all].freeze
👍

2021-11-26 09:39 UTC, merged