プラクティス一覧画面にアクセス時のN+1を解消
fjordllc/bootcamp pull request #3526
Opened 2021-11-06 14:29 UTC by shibaaaa

## Description

プラクティス一覧画面に遷移時、practicesテーブルにカテゴリーの数分クエリが発行されていたので、一回のクエリで済むように修正しました。
practicesテーブルからstatusがcompleteのものをカウントし、category_idでグルーピングするように変更しています。

2021-11-07 02:46 UTC, shibaaaa commented on app/models/user.rb
> -    category.practices.size == completed_practices_size(category)
修正前はここでcategoryごとに`completed_practices_size(category)`を呼んでいたため、categoryの数分practicesテーブルへクエリが発行されていました

2021-11-11 07:18 UTC, komagata requested changes

2021-11-11 07:18 UTC, komagata commented on app/models/user.rb
> +  def completed_practices_hash
hashというデータ構造の名前がUserモデルのメソッドとして出てくるのはUserモデルを使う側から見るとカプセル化ができてない感じなので、別の設計をしたい感じがします〜。

2021-11-11 09:59 UTC, shibaaaa commented on app/models/user.rb
> +  def completed_practices_hash
@komagata 
こちら対応しました、ご確認お願いします:pray:
https://github.com/fjordllc/bootcamp/pull/3526/commits/9dd01ab1ed6e6828f40dfbda064884528e782134

2021-11-11 10:55 UTC, komagata approved these changes
確認しました、ありがとうございます〜！

2021-11-11 10:55 UTC, merged