カテゴリ別の通知既読ボタンを追加
fjordllc/bootcamp pull request #3534
Opened 2021-11-08 12:10 UTC by IkumaTadokoro

## 目的

- refs: #3247 

## やったこと

- 「全て」を除く、通知ページのタブに「〇〇の通知を既読にする」ボタンを実装

## UIの変更

**※デザイン依頼中**

### 変更前

### 変更後

2021-11-08 12:45 UTC, IkumaTadokoro commented
@machida 
お手数ですが、こちらカテゴリ別の既読ボタンにデザインをお願いいたします🙇‍♂️
（DraftPRで作るつもりが、本PRになってしまいました）

現状は、とりあえず以下画像の位置に、「全て既読にする」ボタンと同じクラスで配置しています。
![image](https://user-images.githubusercontent.com/61409641/140744194-454d3d92-3968-4285-bd56-4ecb1d3814dc.png)

2021-11-09 03:05 UTC, machida commented
デザイン了解ですー！！

2021-11-09 06:59 UTC, IkumaTadokoro commented
@haruguchi-yuma 
お手数ですが、こちらレビューお願いいたします〜🙇‍♂️
特にシステムテストのテストケースが充足しているかを見ていただきたいです！

2021-11-10 11:48 UTC, haruguchi-yuma reviewed
@IkumaTadokoro 
レビューしてみたんですが、全体的に自信はないです😅なので、気づいたことはあれこれコメントしたんですが、一緒に考えていけたらなと思います！

テストはこれで大丈夫な気がします！
ご確認ください！

2021-11-10 11:48 UTC, haruguchi-yuma commented on app/controllers/notifications/categorymarks_controller.rb
> +    @notifications.update(read: true, updated_at: Time.current)
`@notifications`というインスタンス変数なんですが、viewで使わなさそうなので、ローカル変数でもいい気がします。どうでしょうか？🤔

7行目でなぜ`updated_at`を明示的に記述しているのか分かりませんでした。教えていただけたらありがたいです🙇

2021-11-10 11:48 UTC, haruguchi-yuma commented on app/controllers/notifications/categorymarks_controller.rb
> +    redirect_to notifications_path(target: target), notice: '既読にしました'
ここは仕様の確認なんですが、通知を既読にするボタンを押したあとは「未読」「すべて」のタブは「すべて」へ遷移するで大丈夫ですかね？😃

何回か実際に試してみたんですが、「未読」タブにリダイレクトした方が、確かに未読になったことが伝わりやすいのかなぁなんて思ったんですが。（もし既に相談済みであれば無視してください🙏）

2021-11-10 11:48 UTC, haruguchi-yuma commented on app/controllers/notifications/categorymarks_controller.rb
> +    @notifications = current_user.notifications.by_target(target)
`@notifications`に「既読・未読」に関わらず種類別ですべてのレコードが入ってしまっているので`update`した時にレコードの数だけSQL文が発行されている感じでした。本番環境のデータだと結構件数が多い気がするので`unreads`などで未読に絞った方が良いのかなと思いました。（あんまり自信ないですが、、😅）

2021-11-11 00:11 UTC, IkumaTadokoro commented on app/controllers/notifications/categorymarks_controller.rb
> +    @notifications.update(read: true, updated_at: Time.current)
> @notificationsというインスタンス変数なんですが、viewで使わなさそうなので、ローカル変数でもいい気がします。どうでしょうか？🤔

ご指摘の通りです！ 6a8dbf04cae62acdc9cfd980844c2701f8bd81d5 で修正しました！

> 7行目でなぜupdated_atを明示的に記述しているのか分かりませんでした。

「全ての通知を既読にする」ボタンと合わせて指定していたのですが、Rails側で`updated_at`は補完されるので不要でした。 a1b4ca87ed15019198bd9af3c484f4407fa348d0 で修正しました！

2021-11-11 00:14 UTC, IkumaTadokoro commented on app/controllers/notifications/categorymarks_controller.rb
> +    @notifications = current_user.notifications.by_target(target)
ありがとうございます😊
対象としては未読のデータのみにするのが適切かと思うので、カテゴリ別で絞った後に`unreads`のスコープを適用するよう、 742cba4cfafddcd3fe592aff9245b5fd1f47692f で修正いたしました！

2021-11-11 00:46 UTC, IkumaTadokoro commented on app/controllers/notifications/categorymarks_controller.rb
> +    redirect_to notifications_path(target: target), notice: '既読にしました'
この点相談できていませんでした！ご指摘いただきありがとうございます🙏

既に実装済みの「全て既読にする」ボタンは、ボタンを押した後に「全て」タブに遷移していたため、それに合わせた実装にしたのですが、確かに「未読」に遷移した方がクリアされた感はありますね🤔

---

@komagata @machida 

相談させていただきたいのですが、「#{カテゴリ}の通知を既読にする」を押した後に、以下どちらのタブに遷移したほうが良いでしょうか？
1. 「未読」タブに遷移する
2. 「全て」タブに遷移する

![image](https://user-images.githubusercontent.com/61409641/141216527-0d0ca5d6-e19b-49ac-b523-1afce395c018.png)

2021-11-11 07:33 UTC, komagata commented on app/controllers/notifications/categorymarks_controller.rb
> +    redirect_to notifications_path(target: target), notice: '既読にしました'
@IkumaTadokoro 

> 2.「全て」タブに遷移する

なるほど、未読は常にゼロのはずなので２が良さそうっすね〜

2021-11-11 07:53 UTC, IkumaTadokoro commented on app/controllers/notifications/categorymarks_controller.rb
> +    redirect_to notifications_path(target: target), notice: '既読にしました'
@komagata 

ご確認いただきありがとうございます！承知いたしました〜。

2021-11-11 07:55 UTC, IkumaTadokoro commented
@haruguchi-yuma 
レビューいただきありがとうございました！
ご指摘いただいた箇所修正いたしましたので、再度ご確認いただければ🙇‍♂️
（最新のmainを取り込んだのでforce-pushしました。）

2021-11-12 06:54 UTC, haruguchi-yuma commented on app/controllers/notifications/categorymarks_controller.rb
> +    @notifications.update(read: true, updated_at: Time.current)
了解ですー！ローカル変数の件と`update_at`の件の両方の修正確認しました！

2021-11-12 06:55 UTC, haruguchi-yuma commented on app/controllers/notifications/categorymarks_controller.rb
> +    @notifications = current_user.notifications.by_target(target)
OKです！確認しました！

2021-11-12 06:56 UTC, haruguchi-yuma commented
@IkumaTadokoro 
レビューの修正を確認しました！大丈夫だと思います💪

2021-11-12 07:09 UTC, IkumaTadokoro commented
@haruguchi-yuma 
ご確認いただきありがとうございました！
レビューとても参考になりました🙆‍♂️

2021-11-18 01:51 UTC, machida commented
@IkumaTadokoro デザイン入れましたー

![image](https://user-images.githubusercontent.com/168265/142336603-0979c69e-feb3-4723-8599-6c5099b774bc.png)

2021-11-18 03:56 UTC, IkumaTadokoro commented
@machida 
デザイン追加いただきありがとうございました！！

2021-11-18 03:57 UTC, IkumaTadokoro commented
@komagata 
お手数ですが、こちらレビューお願いいたします〜🙇‍♂️

2021-11-18 05:50 UTC, komagata requested changes

2021-11-18 05:50 UTC, komagata commented on app/controllers/notifications/categorymarks_controller.rb
> +class Notifications::CategorymarksController < ApplicationController
`Categorymarks`という名前、直訳ではなく英語として意味がわかりやすい名前にしたいっすね。

2021-11-19 03:40 UTC, IkumaTadokoro commented on app/controllers/notifications/categorymarks_controller.rb
> +class Notifications::CategorymarksController < ApplicationController
`ReadCategory`だとどうでしょうか？（もしくは`ReadByCategory`）

全件既読にするControllerに`Notifications::AllmarksController`があるので、そことの差異で`Category`は入れたいかな〜と思っています。

2021-11-21 16:45 UTC, komagata requested changes

2021-11-21 16:45 UTC, komagata commented on app/controllers/notifications/categorymarks_controller.rb
> +class Notifications::CategorymarksController < ApplicationController
@IkumaTadokoro ReadByCategoryいいと思います〜

2021-11-22 05:48 UTC, IkumaTadokoro commented on app/controllers/notifications/categorymarks_controller.rb
> +class Notifications::CategorymarksController < ApplicationController
ありがとうございます！
9bf76ffea5e9099399729eebd5a4c5d57891c3cc にて、`ReadByCategory`に名称修正いたしました。

2021-11-22 05:48 UTC, IkumaTadokoro commented
@komagata 
修正しましたので、再度ご確認よろしくお願いいたします。

2021-11-22 08:20 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-22 09:34 UTC, merged