受講者が管理者とプライベートな相談を行うためのクローズドな掲示板ページを作成
fjordllc/bootcamp pull request #3585
Opened 2021-11-17 11:34 UTC by mami-inuzuka

2021-11-17 14:44 UTC, mami-inuzuka commented
@haruguchi-yuma 
こちらのレビューよろしくお願いします🙏！
（分割してPRを立てていくため機能としては未完なのですが、まず**① #3503：相談部屋の一覧、個別ページを作成** の内容についてレビューをお願いいたします🙇🏻‍♂️）

2021-11-18 06:39 UTC, haruguchi-yuma reviewed
確認しました！
コードが簡潔でわかりやすかったです〜！👏

コードの提案と、気になるところが1点ずつあったのでご確認ください！🙇‍♂️

2021-11-18 06:39 UTC, haruguchi-yuma commented on app/controllers/users/talk_controller.rb
> +    return unless !current_user.admin? && params[:user_id].to_i != current_user.id
ここの条件式がかなり複雑なので、
`return if current_user.admin? || User.find(params[:user_id].to_i == current_user.id`などはいかがでしょうか？

2021-11-18 06:39 UTC, haruguchi-yuma commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
他のルーティングには`as`オプションが付いてるんですが、合わせた方がいいんですかね？🤔
ちょっと自分では判断できませんでした、、、

2021-11-18 09:04 UTC, mami-inuzuka commented on app/controllers/users/talk_controller.rb
> +    return unless !current_user.admin? && params[:user_id].to_i != current_user.id
確かに！否定の否定になっていて複雑になってしまっているのでご提案いただいた式で修正します！！ありがとうございます😊🙏！

2021-11-18 09:20 UTC, mami-inuzuka commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
@haruguchi-yuma `as`を指定するときはPrefixを変えたい時だけなのかなと思い、今回特に記述する必要はないのかなと思ったのですが確かに他のルーティングも一見不要そうに見えるけど`as`の指定があるところがあるので何か勘違いしているかもしれないです...

@komagata 
上記の件なのですが、
下記のルーティングにおいて`as`の指定はあってもなくてもどれも同じPrefixを使うことができると思うのですが`as`の指定があるのは何か理由があるのでしょうか？
```
    get "portfolio" => "users/works#index", as: :portfolio
    patch "graduation", to: "graduation#update", as: :graduation
    get "mail_notification", to: "mail_notification#update", as: :mail_notification
```

2021-11-18 10:11 UTC, haruguchi-yuma commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
@mami-inuzuka 
確かに、`as`指定するの必要なさそうなんですよねー。他のコードがどのような意図で`as`ついているのかわからなかったので、気になります！

2021-11-21 16:48 UTC, komagata commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
@mami-inuzuka asが何のためにあるのか調べてみてください〜
prefixをつけたい時だけに限らないです。

2021-11-22 07:14 UTC, mami-inuzuka commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
質問タイムで会話した内容メモ：

* `as`を使うときはPrefixを書き換えたいとき（Helperを書き換えたいとき）という認識であっている
* portfolioやguraduationに関してもasは無くても大丈夫だがおそらく明示的に書いているだけだと思う（特にルールはない）
* そもそもgetやpatchは使わずにresource(s)で書くことを優先する

2021-11-22 08:17 UTC, mami-inuzuka commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
@haruguchi-yuma こちらの件質問タイムで疑問点解消できました！（上記のメモの内容です）
resourceを使って書き直したので再レビューお願いいたします😊🙏

2021-11-23 04:47 UTC, haruguchi-yuma commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
@mami-inuzuka 
変更部分確認しましたー！OKです👍

2021-11-24 02:33 UTC, mami-inuzuka commented on config/routes/users.rb
> +    get "talk" => "users/talk#show"
確認ありがとうございます！！✨

2021-11-24 03:25 UTC, mami-inuzuka commented
@komagata こちらのレビューよろしくお願いします😊

2021-11-24 13:51 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

talkの部分が日報などのページのようにvue.jsでなくてもいいかな？と思ったぐらいです〜。

2021-11-24 15:01 UTC, mami-inuzuka commented
@komagata ご確認ありがとうございます！

>talkの部分が日報などのページのようにvue.jsでなくてもいいかな？と思ったぐらいです〜。

ここは次のissue（ **[相談部屋]相談部屋にコメントを投稿出来るようにしたい #3504** ）
に絡んでくる部分かと思うのでそこの実装方法を考える際にVue.jsにすべきかしなくても良いか考えてみようと思います😊

2021-11-24 15:01 UTC, mami-inuzuka commented
こちらで**① 相談部屋の一覧、個別ページを作成  #3503**は完了とし②に進ませていただきます😊🙏

2021-12-08 07:54 UTC, mami-inuzuka commented
次の[issue](https://github.com/fjordllc/bootcamp/issues/3504) に取り組む際に問題が発生し、仕様変更をおこなったのでメモ

## 変更内容
* 相談部屋個別ページのURLを`/users/user_id/talk` としていたのを `/talks/talk_id` に変更する

## 変更背景
* コメントが作成された際にコールバック処理としてコメントがきたことをお知らせする処理が行われるが（`came_comment`）、その際にコメントへのリンクパスが`polymorphic_path`で生成されている
* `polymorphic_path`で生成されるパスは基本的には`リソース名_path`となるが、今回`talk_path`が生成されてしまうが、実際には`/users/user_id/talk` というURLに対応するURLヘルパーは`user_talk_path` となるためエラーが起きていた


```ruby
  def self.came_comment(comment, receiver, message)
    Notification.create!(
      kind: 0,
      user: receiver,
      sender: comment.sender,
      path: Rails.application.routes.url_helpers.polymorphic_path(comment.commentable),
      message: message,
      read: false
    )
  end
```

## 必要な作業
- [ ] ルーティングの修正
    - [ ] routes.rb
    - [ ] routes/users.rb
- [ ] 不要になったビューの削除
    - [ ] users/talk/show.html.slim
- [ ] 必要なビューの作成
    - [ ] talks/show.html.slim
- [ ] vueと新しく作成したビューファイルの連携
- [ ] talkの作成
    - [ ] 新規ユーザー
        - [ ] ユーザー作成時にコールバック処理としてtalkを作成するようにする
    - [ ] 既存ユーザー
        - [ ] 開発環境：seedで用意する
        - [ ] 本番環境：デプロイ時に各ユーザーにtalkが作成されるスクリプトを用意する（データマイグレーション）

2021-12-15 08:52 UTC, haruguchi-yuma commented
@mami-inuzuka 
遅くなりました！
変更分を確認しましたが問題なさそうです😊
data-migrateの使い方や、1対1の関連付けでnewメソッドの代わりにが`build_xxx`が使えるなど勉強になりました〜！

2021-12-15 10:43 UTC, mami-inuzuka commented
@haruguchi-yuma スクラム開発ご卒業後の依頼にも関わらず対応してくださりありがとうございました🙇🏻‍♂️

2021-12-15 10:43 UTC, mami-inuzuka commented
@komagata 
**★再レビューのお願い🙇🏻‍♂️**

**① 相談部屋の一覧、個別ページを作成 #3503** の内容についての実装は以前レビューしていただき完了のステータスとなっていたのですが、次のissueに進んだ際に以前質問タイムでご相談させていただいた、
polymorphic path関連でエラーが発生してしまったため、その対処として追加実装を行いました。
詳細はこちらです（https://github.com/fjordllc/bootcamp/pull/3585#issuecomment-988579311）

そのため再レビューを依頼させていただきました。よろしくお願いします🙇🏻‍♂️

2021-12-20 02:08 UTC, komagata commented on app/controllers/talks_controller.rb
> +    @user = current_user.admin? ? @talk.user : current_user
これはなぜadminとそれ以外でリダイレクト先が違うんでしょう？

2021-12-20 02:13 UTC, mami-inuzuka commented on app/controllers/talks_controller.rb
> +    @user = current_user.admin? ? @talk.user : current_user
@komagata レビューありがとうございます🙇🏻‍♂️
adminの場合は全ての相談部屋ページを閲覧することができるようにし、それ以外のユーザーは他の方の相談部屋を閲覧することができないようにするためです😊

2021-12-21 18:00 UTC, komagata requested changes

2021-12-21 18:00 UTC, komagata commented on app/controllers/talks_controller.rb
> +    @user = current_user.admin? ? @talk.user : current_user
@mami-inuzuka なるほどですね。
でしたらshowのメインの目的じゃないのてメソッドにしてbefore_actionで呼び出すとわかりやすくなるかもです〜。

2021-12-22 02:08 UTC, mami-inuzuka commented on app/controllers/talks_controller.rb
> +    @user = current_user.admin? ? @talk.user : current_user
@komagata なるほど承知しました！！before_actionを使用して修正してみたので再レビューよろしくお願いします🙇🏻‍♂️

2021-12-26 06:04 UTC, komagata requested changes

2021-12-26 06:04 UTC, komagata commented on app/models/user_callbacks.rb
> +    user.save
この場合、エラーが起きたときにエラーが起きたことがわからずスルーされちゃうかもなので
`save!`と使った方が良いかもです〜。

2021-12-26 07:16 UTC, mami-inuzuka commented on app/models/user_callbacks.rb
> +    user.save
@komagata レビューありがとうございます！修正いたしましたのでご確認お願いします。

2021-12-27 23:13 UTC, komagata requested changes

2021-12-27 23:13 UTC, komagata commented on db/data/20211213092226_build_talk_to_all_users.rb
> +      user.build_talk.save!
`user.task.create!`みたいな感じで書けた気がします〜

2021-12-27 23:48 UTC, mami-inuzuka commented on db/data/20211213092226_build_talk_to_all_users.rb
> +      user.build_talk.save!
@komagata UserとTalkは1対1の関係なので、`build_association`か`create_association`/`create_association!`が使えるメソッドかなと思うのですがいかがでしょうか？（https://railsdoc.com/page/has_one）

また、[app/models/user_callbacks.rb ](https://github.com/fjordllc/bootcamp/pull/3585/files/146877e221e3ee47329c7bfba904733ee272107d#diff-de40e863492b66783c5f7c3bcc35d0dfff4d7776e4f04a9bf0c82ad0459fe9b7R8)では`build_association`を用いています。

2021-12-28 02:00 UTC, komagata requested changes

2021-12-28 02:00 UTC, komagata commented on db/data/20211213092226_build_talk_to_all_users.rb
> +      user.build_talk.save!
ではcreate_association!でお願いします〜（

build_xxxはインスタンスを作るだけ、create_xxxはDBに保存するので、目的は後者だと思うので。

2021-12-28 02:32 UTC, mami-inuzuka commented on db/data/20211213092226_build_talk_to_all_users.rb
> +      user.build_talk.save!
@komagata 承知しました！こちら修正致しましたのでご確認お願いします🙏

2021-12-28 08:52 UTC, komagata requested changes

2021-12-28 08:52 UTC, komagata commented on app/models/user_callbacks.rb
> +    user.build_talk
こちらも前回書いたところと同じだと思いますので修正お願いします〜

2021-12-28 15:25 UTC, mami-inuzuka commented on app/models/user_callbacks.rb
> +    user.build_talk
@komagata こちらの対応漏れておりすみません🙇🏻‍♂️修正しましたのでご確認お願いいたします。

2021-12-29 06:11 UTC, komagata requested changes

2021-12-29 06:11 UTC, komagata commented on app/javascript/talks.vue
> +
この空白はいらないかもです〜

2021-12-29 06:46 UTC, mami-inuzuka commented on app/javascript/talks.vue
> +
@komagata 12行目の空行のことであっていますでしょうか？ちなみに、こちら他のvueファイルを確認すると空白があるものもたくさんありますが空白を無しにするのが正しいということでしょうか？💡

2021-12-31 04:31 UTC, komagata commented on app/javascript/talks.vue
> +
@mami-inuzuka 最近、空白を入れる人がちょこちょこ出てきているのですが、元々は全てのコードで空白は無しだったのでできればそちらに合わせて行きたいです〜

2021-12-31 04:33 UTC, mami-inuzuka commented on app/javascript/talks.vue
> +
@komagata 承知しました！削除いたしましたのでご確認お願いします😊🙏

2021-12-31 05:15 UTC, komagata requested changes
conflictの修正をお願いします〜

2022-01-14 15:24 UTC, mami-inuzuka commented on db/data_schema.rb
> +DataMigrate::Data.define(version: 20_220_114_203_650)
@komagata [Discordのこちらで質問させていただいたコンフリクト解消の件](https://discord.com/channels/715806612824260640/809595476847493192/931438324902674483)ですが、梅本さんと岡嵜さんに一緒にコンフリクトを解消していただき解決しました🙇🏻‍♂️

一点確認ですが、本番でのデータマイグレーションは追加されたファイルを一つずつバージョンを指定しながら実行している認識で合っていますか？💡（例えば今回私が追加したマイグレーションファイルは`20220114203650_build_talk_to_all_users.rb`なので、`rake db:migrate:up VERSION=20220114203650`を本番環境で実行していただくようなイメージです）

一緒にコンフリクトを解消していただく中で疑問が上がったので念の為確認させていただきました。

2022-01-14 15:27 UTC, mami-inuzuka commented
> conflictの修正をお願いします〜

全ての分割されたPRがこちらのブランチにマージされたので、conflictの解消を行いました。
ご確認よろしくお願いいたします😊🙏

2022-01-15 03:58 UTC, komagata requested changes

2022-01-15 03:58 UTC, komagata commented on app/javascript/packs/application.js
> +import '../worried-users.js'
ちょっと自信がないのですが、先にどのライブラリがimportされたかで動きに違いが出ないかがちょっと心配に思いました〜

2022-01-15 03:58 UTC, komagata commented on test/system/talks_test.rb
> +  test '管理者以外がコメントした場合未返信タブに相談部屋が表示される' do
テストの名前を英語でお願いします〜

2022-01-18 02:05 UTC, mami-inuzuka commented on test/system/talks_test.rb
> +  test '管理者以外がコメントした場合未返信タブに相談部屋が表示される' do
修正漏れ失礼しました🙇🏻‍♂️英語で記述しました！

2022-01-18 02:05 UTC, mami-inuzuka commented on app/javascript/packs/application.js
> +import '../worried-users.js'
こちらVSCodeの設定でアルファベット順になってしまっていたみたいです🙇🏻‍♂️元の状態に戻した上で必要なファイルのみimportいたしました。

2022-01-18 02:06 UTC, mami-inuzuka commented
@komagata 変更リクエストをいただいた箇所２点修正完了しましたのでご確認よろしくお願いいたします🙇🏻‍♂️

2022-01-18 05:10 UTC, komagata requested changes

2022-01-18 05:10 UTC, komagata commented on db/data_schema.rb
> +DataMigrate::Data.define(version: 20_220_114_203_650)
@mami-inuzuka 

> 一点確認ですが、本番でのデータマイグレーションは追加されたファイルを一つずつバージョンを指定しながら実行している認識で合っていますか？

NOです。

単に`rails data:migrate`が実行されるようになっています。（詳細はdata_migrateのREADMEを見るとわかるかと思います〜）

実装を厳密に見たわけでは無いですが、普通のmigrationもdata migrationも最後に実行したものより新しいものがあると自動的に全部実行される感じだと思います。

- https://github.com/fjordllc/bootcamp/blob/main/cloudbuild.yaml#L30
- https://github.com/fjordllc/bootcamp/blob/main/lib/tasks/bootcamp.rake#L20

2022-01-18 05:10 UTC, komagata commented on test/system/talks_test.rb
> +class PagesTest < ApplicationSystemTestCase
```suggestion
class TalksTest < ApplicationSystemTestCase
```

2022-01-18 05:10 UTC, komagata commented on test/system/notification/talk_test.rb
> +class Notification::AnswersTest < ApplicationSystemTestCase
```suggestion
class Notification::TalksTest < ApplicationSystemTestCase
```

2022-01-18 07:18 UTC, mami-inuzuka commented
@komagata 先ほどは質問タイムで`data-migrate`についての回答ありがとうございました😊

そして何度もすみません🙇🏻‍♂️再度変更リクエストをいただいた箇所２点修正完了しましたのでご確認よろしくお願いいたします🙇🏻‍♂️

2022-01-18 14:21 UTC, komagata requested changes
こちらについてはいかがでしょうか

- https://github.com/fjordllc/bootcamp/pull/3585#discussion_r786419457
- https://github.com/fjordllc/bootcamp/pull/3585#discussion_r786419594

2022-01-18 23:37 UTC, mami-inuzuka commented
@komagata すみません🙇🏻‍♂️pushをし忘れておりました🙇🏻‍♂️
下記２点について修正しpushしましたのでご確認よろしくお願いします。

- https://github.com/fjordllc/bootcamp/pull/3585#discussion_r786419457
- https://github.com/fjordllc/bootcamp/pull/3585#discussion_r786419594

2022-01-19 00:54 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-19 00:54 UTC, mami-inuzuka commented
長期にわたりレビューしていただきありがとうございました🙇🏻‍♂️！！

2022-01-19 00:55 UTC, komagata commented
@machida このブランチがマージできる状態になりました。大きめな追加なので念の為デザイン面を確認しただければありがたいです〜

2022-01-19 02:56 UTC, machida commented
@komagata 了解です！確認します。これをリリースする前に https://github.com/fjordllc/bootcamp/issues/3682 をお願いします。

2022-01-24 04:47 UTC, komagata commented
@machida #3682をやったのでこちらマージします〜（リリースされるのは次のリリースになります）

2022-01-24 04:47 UTC, merged

2022-01-24 09:01 UTC, machida commented
@komagata ありがとうございます！！確認しました。これでリリースお願いします。

2022-01-28 12:49 UTC, mami-inuzuka commented
# 本番環境で確認していただきたいこと

## 表示
- [ ] 左端の相談メニューをクリックすると相談部屋一覧が表示される

## タブ 
- [ ] 未返信タブに犬塚の相談部屋が表示されている
- [ ] 犬塚の相談部屋でコメントをするとコメントをすると、未返信タブから犬塚の相談部屋が消える（こちらでコメントができることの確認も兼ねます）

## 通知 
- [ ] 犬塚からのコメント通知が駒形さん/まちださんに届いている