Feature/display batches announcement tab notification page
fjordllc/bootcamp pull request #3589
Opened 2021-11-19 00:06 UTC by yoshitaku-jp

2021-11-19 11:51 UTC, yoshitaku-jp commented on app/views/notifications/_tabs.html.slim
> +          - if target.to_s == 'announcement'
test

2021-11-21 16:59 UTC, komagata requested changes

2021-11-21 16:59 UTC, komagata commented on app/views/notifications/_tabs.html.slim
> +          - if target.to_s == 'announcement'
@yoshitaku-jp ViewHelperなどを作ってうまくViewからifがない形にでできると一番いいかもですね〜。
ちょっと考えてみてください〜

2021-11-29 14:15 UTC, yoshitaku-jp commented
@kawase-k さん
ほぼ同じPRをレビューしていらっしゃったので、こちらもレビューをお願いできますでしょうか:bow:
PR #3590

2021-11-30 02:30 UTC, kawase-k commented on app/models/cache.rb
> +    end
このメソッドは定義されているだけで他で呼び出しされていない気がしたのですが、どういう意図があったのかご教示いただけないでしょうか？🙇‍♂️ (キャッシュについてよく分かっておらず申し訳ありません🙏 )

2021-11-30 02:30 UTC, kawase-k commented on app/models/cache.rb
> +    end
こちらも71行目でお聞きした内容と同じになります。

2021-11-30 02:46 UTC, kawase-k commented
@yoshitaku-jp さん
先ほど確認させていただきました！
気になった点についてコメントさせていただいたので再度ご確認お願いいたします🙏

また1点認識合わせしたいのですが、PRをDraftで作成されているのはこの後にデザインを町田さんにお願いするからでしょうか？

2021-11-30 13:39 UTC, yoshitaku-jp commented
@kawase-k さん
確認ありがとうございます！

deleteですが…正直同じファイルに書かれていたものを参考にし、似たように書いただけになります:bow:
現時点で使っていないので削除しても良いのかなとも思います。

>また1点認識合わせしたいのですが、PRをDraftで作成されているのはこの後にデザインを町田さんにお願いするからでしょうか？
はい！そのようになります！

2021-12-02 00:00 UTC, yoshitaku-jp commented
@kawase-k さん
こちらレビュー依頼を出していましたが一回取り下げさせてください:bow:
理由としましては、
- delete部分を実行するためのcallback実装が足りていないこと
- その部分を実装している方が居てその完成を待ち、私がマージしてから再度このPRに取り掛かる段取りになったこと
になります。
これは12/01のふりかえり会にて komagata さんと認識合わせ済みです。
そのため、一回レビューを取り下げさせていただければと思います！

2021-12-02 04:25 UTC, kawase-k commented
@yoshitaku-jp さん
ご連絡遅くなり申し訳ございません🙏

1つ前でお聞きしていたDraftでPRを作成されている件、承知しました。
デザインが入る予定なのですね👌

そして一旦レビューを取り下げる件、承知しました！！

> delete部分を実行するためのcallback実装が足りていないこと

理解しました！

> その部分を実装している方が居てその完成を待ち、私がマージしてから再度このPRに取り掛かる段取りになったこと
になります。

実装されてるPRは https://github.com/fjordllc/bootcamp/pull/3642 のことでしょうか？
(詳細を知っておきたいので質問させていただきました🙇‍♂️ )

> これは12/01のふりかえり会にて komagata さんと認識合わせ済みです。

共有いただきありがとうございます！
引き続きよろしくお願いいたします🙇‍♂️

2021-12-02 06:17 UTC, yoshitaku-jp commented
@kawase-k 
>実装されてるPRは #3642 のことでしょうか？
おっしゃるとおりです！（隠したみたいになってすみません:bow:）

おそらく実業務ですと相手方の変更を私のPRに取り込み私の実装も並行してすすめるのだと思いますが、Git操作でこんがらがってしまうのを避けるために今回は私が一時停止するという形をとっています！
よろしくお願いいたします！

2022-05-25 07:47 UTC, machida commented
こちらクローズしますー

2022-05-25 07:47 UTC, closed without merging