管理者ではないメンターのテストユーザーを追加
fjordllc/bootcamp pull request #3602
Opened 2021-11-20 11:03 UTC by ShotaTsuru

# What
管理者では無いメンターのテストユーザーを追加

2021-11-20 11:13 UTC, ShotaTsuru commented
[管理者ではないメンターのテストユーザーがほしい · Issue \#3575 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/3575)

2021-11-20 11:40 UTC, ShotaTsuru commented
@mami-inuzuka 
お手隙の時にレビューお願い致します🙇‍♂️

2021-11-24 04:00 UTC, mami-inuzuka commented on db/fixtures/users.yml
> +  facebook_url:
@ShotaTsuru facebook_urlとblog_urlは設定しない場合値を空にする、で大丈夫ですか？💡
（他にこれらの値が設定されていないユーザーがいなかったため念のため確認です😊🙏）

2021-11-24 04:01 UTC, mami-inuzuka commented
@ShotaTsuru 
お疲れ様です！一件だけコメントさせていただきました。ご確認よろしくお願いします😊🙏

2021-11-24 10:55 UTC, ShotaTsuru commented on db/fixtures/users.yml
> +  facebook_url:
@mami-inuzuka
はい！空にしているのは意図的にしておりました！🙇‍♂️

2021-11-24 15:05 UTC, mami-inuzuka commented on db/fixtures/users.yml
> +  facebook_url:
@ShotaTsuru あ🙇🏻‍♂️こちらは私の知識不足で確認させていただいた次第なのですが、値を指定しない場合空にするので文法的に問題がないのであれば大丈夫です！🙆‍♀️（それで問題なければLGTMでお願いします👍）

2021-11-25 05:45 UTC, ShotaTsuru commented
@komagata 
お手数ですがレビューお願い致します！🙇‍♂️

2021-11-26 10:17 UTC, komagata requested changes
conflictの修正お願いします〜

2021-12-01 12:30 UTC, ShotaTsuru commented
@komagata
こちらのコメントに今さっき気がつきました申し訳ありません！！
直ちにコンフリクト修正いたしました。

2021-12-03 10:24 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-03 10:24 UTC, merged