テストデータに長方形のユーザーアイコンを登録したユーザーを追加
fjordllc/bootcamp pull request #3622
Opened 2021-11-25 04:30 UTC by taka61

書き途中です。

2021-11-25 09:05 UTC, taka61 commented
@yoshitaku-jp 
お手数ですが、お時間のある際にこちらのレビューをお願いします!🙏

2021-11-27 00:09 UTC, yoshitaku-jp commented
@taka61 さん
遅くなってすみません！

私の方で上記ユーザを、ユーザ一覧から見つけることができませんでした。。。ログインもできず…
push忘れなどありませんでしょうか？また、再現方法も載せていただくことは可能でしょうか？

私の方でおこなったことは
1. PRブランチに移動
2. bin/setupを実行
3. rails sを実行

![image](https://user-images.githubusercontent.com/15277293/143661909-26eee858-a6ee-406e-81da-9b71a0225f5f.png)

2021-11-27 08:26 UTC, taka61 commented
@yoshitaku-jp さん
確認頂きありがとうございます!

「ユーザ一覧から見つける」に関しては以下の手順で確認をお願いします。

1. PRブランチに移動後、`rails db:seed`を実行するとDBの内容が開発環境に反映されます。
2. `rails s`で起動し、ユーザー一覧から新しく追加した`tatenoicon`ユーザーが見つけられると思います。
(説明が分かりづらい場合、[日報](https://bootcamp.fjord.jp/reports/42881)の方が分かりやすいかもしれないのでこちらをご確認下さい🙏)

「ログイン」に関しては確認したところ私の方でも出来なかった為、解決し次第再度改めて手順を載せさせて頂きます💦
よろしくお願いします🙏

2021-11-27 15:07 UTC, yoshitaku-jp commented
@taka61 さん
すみません！`rails db:seed`していませんでした！`bin/setup`の中でやっていると思っていました:bow: 
こちらの手順も簡単ですが明記しておいてよかったです…！

そして、無事にユーザを見つけることができました！大丈夫だと思います！

![image](https://user-images.githubusercontent.com/15277293/143686571-e5601b6d-ca2c-4a16-9e86-7afce17c956d.png)

![image](https://user-images.githubusercontent.com/15277293/143686729-b7c2a321-b14e-41a4-ad38-0bda674e58b6.png)

2021-11-27 15:08 UTC, yoshitaku-jp approved these changes

2021-11-29 02:48 UTC, taka61 commented
@yoshitaku-jp さん

>無事にユーザを見つけることができました！

ユーザー一覧に反映されていたようで良かったです〜🙏

また「ログイン」に関してですが、
ユーザ名：tatenoicon
パスワード：testtest
でログイン出来ましたので、こちらで試してみて下さい!

<img width="387" alt="スクリーンショット 2021-11-29 11 43 15" src="https://user-images.githubusercontent.com/80372144/143800676-d33e52f6-5506-4ac8-aa25-7e6d47933da7.png">

<img width="1115" alt="スクリーンショット 2021-11-29 11 24 35" src="https://user-images.githubusercontent.com/80372144/143800803-5210e285-9162-4852-a877-3cde9d337012.png">

2021-11-29 13:51 UTC, yoshitaku-jp commented
@taka61 さん
私の方でもログイン確認できました！大丈夫です！

2021-12-02 06:05 UTC, taka61 commented
@yoshitaku-jp さん
確認いただきありがとうございました!🙏

@komagata さん
チームメンバーのレビューを通過しましたので、お時間ある際にこちらのレビューをお願いします!

2021-12-03 10:32 UTC, komagata requested changes
conflictの修正をお願いします〜

2021-12-04 02:43 UTC, taka61 commented
@komagata さん
コンフリクト解消しました！
ご確認をお願いします🙏

2021-12-04 18:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-04 18:55 UTC, merged