自分の日報をエクスポートできるようにしました
fjordllc/bootcamp pull request #3633
Opened 2021-11-28 15:29 UTC by kawase-k

wip

2021-11-28 16:34 UTC, kawase-k commented
@machida さん
お手すきの際にエクスポートボタンのデザインお願いいたします🙇‍♂️
現在はダッシュボードの自分の日報画面に仮ボタンを設置している状況です。
上に加えて申し訳ないのですが、チームメンバーへのレビューは同時進行してお願いして問題ないでしょうか？

お手数おかけしますがご確認のほどよろしくお願いいたします🙏

2021-11-30 08:33 UTC, machida commented
@kawase-k デザイン入れましたー

2021-11-30 22:16 UTC, kawase-k commented
@machida さん
先ほどデザインが適用されていることを確認しました！
ご対応いただきありがとうございます🙏

2021-12-01 02:40 UTC, kawase-k commented
@taka61 さん
お手すきの際にこちらのレビューをお願いいたします🙇‍♂️

2021-12-02 03:29 UTC, taka61 commented on app/controllers/current_user/reports_controller.rb
> +          file.puts
@kawase-kさん
開発環境での動作・コード確認しました〜！
問題ないと思います🙆‍♀️

1点ただ気になっただけなのですが、
```
file.puts("# #{report.title}")
file.puts
file.puts(report.description)
```
44行目の`file.puts`はどのような動作を行うのでしょうか?
削除した場合挙動に問題が生じますでしょうか?

2021-12-02 05:32 UTC, kawase-k commented on app/controllers/current_user/reports_controller.rb
> +          file.puts
@taka61 さん
ご確認いただきありがとうございます🙏
問題なさそうでよかったです〜！

> 44行目のfile.putsはどのような動作を行うのでしょうか?
削除した場合挙動に問題が生じるのでしょうか?

説明不足で申し訳ございません🙇‍♂️
これはタイトルと日報の内容が判別しやすいように改行を挟んでいるだけのようです！
挙動に問題が生じるわけではないので、駒形さんからのレビューでご指摘があるようでしたら削除するように対応します。

2021-12-02 06:29 UTC, taka61 commented on app/controllers/current_user/reports_controller.rb
> +          file.puts
@kawase-k さん
>これはタイトルと日報の内容が判別しやすいように改行を挟んでいるだけのようです！

改行のためのコードだったんですね〜
タイトルと本文間に改行がある方がたしかに見やすいですね！
ご確認頂きありがとうございます🙏


私の方からは以上です！LGTMでお願いします🙆‍♀️

2021-12-02 10:55 UTC, kawase-k commented on app/controllers/current_user/reports_controller.rb
> +          file.puts
@taka61 さん
レビューありがとうございました🙆‍♂️

2021-12-02 10:57 UTC, kawase-k commented
@komagata さん
お手すきの際にこちらのレビューをお願いいたします🙇‍♂️

2021-12-02 11:02 UTC, kawase-k commented
memo: 
文字化け問題については、Rails6からデフォルトでエンコードされるようになったのでそのまま`send_data`メソッドを呼び出しても大丈夫。

参考：[Rails 6ではsend_data/send_fileメソッド呼び出し時にERB::Util.url_encodeは不要です - Qiita](https://qiita.com/jnchito/items/7644e244e2face186523)

2021-12-03 10:34 UTC, komagata commented
@kawase-k 

> 文字化け問題については、Rails6からデフォルトでエンコードされるようになったのでそのままsend_dataメソッドを呼び出しても大丈夫。

なるほどですね〜僕の知識古かったです🤭

2021-12-03 11:39 UTC, komagata requested changes

2021-12-03 11:39 UTC, komagata commented on Gemfile
> +gem 'rubyzip'
全ての環境で読み込みgemは周りに合わせてこの辺りに入れていただければありがたいです〜

https://github.com/fjordllc/bootcamp/blob/4b072567a4f73c2cea9ddbff573990ba1c44f948/Gemfile#L8-L53

2021-12-03 11:39 UTC, komagata commented on app/controllers/current_user/reports_controller.rb
> +  def create_reports_md(reports)
Controllerでは基本的に込み入った処理はするべきではないのでModelの方でまとめていただけるとありがいです〜

2021-12-07 05:14 UTC, kawase-k commented on Gemfile
> +gem 'rubyzip'
https://github.com/fjordllc/bootcamp/pull/3633/commits/908396bc6ad34340865b3d87a27c5edda1184828 で対応しました。

2021-12-07 05:14 UTC, kawase-k commented on app/controllers/current_user/reports_controller.rb
> +  def create_reports_md(reports)
https://github.com/fjordllc/bootcamp/pull/3633/commits/618c836c6999690c29c17453b1f139051c5d1a02 で対応しました。

2021-12-07 05:16 UTC, kawase-k commented
@komagata さん
修正してみましたのでお手すきの際にこちらの再レビューをお願いします🙇‍♂️

2021-12-08 14:24 UTC, komagata requested changes

2021-12-08 14:24 UTC, komagata commented on app/models/report_exporter.rb
> +  def create
create -> create_reports_mdだと別メソッドにしてる意味がないかもです〜。

また、ReportExporterがcreateしてるのはreportやzipファイルでReportExporterをcreateしているわけじゃないのでこの名前だと分かりづらいかもです。

例えば今ざっとこういうの考えてみました。

- ReportExporter
  - #export
- ReportExporter::ZipFile
  - @path
  - #save_as_file!
- Report
  - #to_markdown
  - #save_as_markdown!

この通り作る必要は全くありませんが、参考に考えてみてください〜

2021-12-16 06:39 UTC, kotakawase commented on app/models/report_exporter.rb
> +  def create
@komagata さん
上記で教えていただいたクラス設計のところでお聞きしたいことがあります🙏

- ReportExporterはモジュールで定義されていてその中にZipFileクラスを書いているものだと理解したのですがこの解釈は合っているでしょうか？（名前空間として利用しているようなイメージ）

```ruby
# app/models/report_exporter.rb
module ReportExporter
  def export
    # エクスポートする処理
  end

  class ZipFile
    def initialize
      @path
    end

    def save_as_file!
      # Zipファイルを保存する処理
    end
  end
end
```

2021-12-20 16:02 UTC, kotakawase commented on app/models/report_exporter.rb
> +  def create
上の質問はDiscordで駒形さんから回答済み。
> ReportExporterもクラスのイメージです。ただ、そのまんまではなく、こういう感じでオブジェクト指向で設計してみてくださいという感じです〜

2021-12-20 16:03 UTC, kotakawase commented
@komagata さん
再度修正してみましたのでお手すきの際にレビューをお願いいたします🙇‍♂️

2021-12-21 18:06 UTC, komagata requested changes

2021-12-21 18:06 UTC, komagata commented on app/controllers/current_user/reports_controller.rb
> +  require 'zip'
requireは一番上（magic commentよりはした）に書くのが一般的なのでそちらの方がいいかもです〜

2021-12-21 18:06 UTC, komagata commented on app/controllers/current_user/reports_controller.rb
> +  require 'zip'
このファイルで`zip`は不要かも？（modelの方で必要かも）

2021-12-22 05:00 UTC, kotakawase commented on app/controllers/current_user/reports_controller.rb
> +  require 'zip'
@komagata さん
こちら修正してみましたのでご確認お願いいたします🙇‍♂️

2021-12-22 12:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-22 12:53 UTC, merged