タグ一括編集機能をタグ別Q&Aページに追加する
fjordllc/bootcamp pull request #3639
Opened 2021-11-30 04:30 UTC by IkumaTadokoro

## 目的

- Refs: #3576 

## やったこと

- タグ別のQ&Aページにタグ編集ボタンを追加
    - ボタンは管理者のみに表示される
    - モーダルフォームを表示し、タグを表示できるようにする
    - タグ更新後はトースト通知を表示する
- タグ編集用のAPIを作成
    - Q&Aだけでなく、ユーザー、Docsに紐づく同名のタグの名前をすべて更新する
    - 同名タグが存在する場合にはタグのリレーションを付け替える

## UI

※デザイン適用前

## 申し送り事項

- questionsのシステムテストが膨れてきたため、タグに関するテストを`question/tags_test`に移管し、新規テストもそちらに記載しました。

2021-11-30 04:58 UTC, IkumaTadokoro commented
@machida 
タグ編集機能を作成いたしました。
最低限必要な要素は配置したつもりですが、仕様として不足している部分があればお伝えください！
特に問題なければデザインをお願いいたします🙇‍♂️

---

**タグ編集ボタン（管理者のみ表示）**

![image](https://user-images.githubusercontent.com/61409641/143987821-d777783d-aa4a-486e-bb71-2a3a52633486.png)

**モーダルウィンドウ（「キャンセル」or 外枠クリックで閉じる）**

![image](https://user-images.githubusercontent.com/61409641/143987873-ad727050-d2bf-4465-ae7b-e16e5ac7b04d.png)

2021-11-30 08:36 UTC, machida commented
対応ありがとうございます！！
デザイン入れますー💪

2021-12-01 05:52 UTC, machida commented
@IkumaTadokoro 
デザイン入れましたー

2021-12-01 08:41 UTC, IkumaTadokoro commented on app/javascript/tag-edit-button.vue
> +  .a-button.is-sm.is-secondary.is-block(@click.prevent='openModal')
@machida 
デザイン実装いただきありがとうございました！
一点確認なのですが、「タグ名変更」のこの要素、`button`タグはなしでしょうか？
（HTML的にボタンなので必要かなと思ったのと、E2Eテスト的にもbuttonの方が嬉しいので...）

もし`button`が必要であれば、こちらで追加いたします🙏

2021-12-01 14:25 UTC, machida commented on app/javascript/tag-edit-button.vue
> +  .a-button.is-sm.is-secondary.is-block(@click.prevent='openModal')
@IkumaTadokoro 
あー、ごめんなさい、buttonタグを消してしまいましたが、あった方がいいですー
書き足しお願いしたいです🙏

2021-12-01 14:52 UTC, IkumaTadokoro commented on app/javascript/tag-edit-button.vue
> +  .a-button.is-sm.is-secondary.is-block(@click.prevent='openModal')
@machida 
ご確認いただきありがとうございます！
1c14d9e089dcfe5e7cc2695add050917f00eb36c にて`button`タグを書き足しさせていただきました😄

2021-12-01 15:11 UTC, IkumaTadokoro commented
@yoshitaku-jp 
お手数ですが、こちらレビューお願いいたします〜🙇‍♂️

2021-12-06 09:18 UTC, yoshitaku-jp commented
@IkumaTadokoro さん
遅くなってすみません！大丈夫だと思います！LGTMです！

2021-12-06 09:19 UTC, yoshitaku-jp approved these changes

2021-12-06 09:31 UTC, yoshitaku-jp commented
@IkumaTadokoro さん
承認したあとにすみません。。

>タグ更新後はトースト通知を表示する

こちらが終わったあとに「新しいタグ名」の一覧に画面遷移することは不要でしょうか？
タグ名更新が完了したあとに、画面が古いタグ名の一覧画面に居続けることが少し引っかかりました。

2021-12-06 10:52 UTC, IkumaTadokoro commented
@yoshitaku-jp 
コメントいただきありがとうございます！確認します👍

@machida 
仕様の確認をさせていただきです。
現在、タグ更新後は画面遷移せずそのままのページに留まっているのですが、認識相違ないでしょうか？
お手数ですがご確認よろしくお願いいたします🙇‍♂️

2021-12-08 07:07 UTC, IkumaTadokoro commented
@yoshitaku-jp 

ご指摘いただいた部分について修正いたしましたので、再度レビューお願いいたします🙇‍♂️

町田さんに仕様確認し、画面遷移処理を d7ae347029d72168309f206963283d1c0bfd5696 で追加致しました。（URIのエンコードに関する参考PR：https://github.com/fjordllc/bootcamp/pull/3606 ）
変更後の挙動については、本PR記載の「UI」を差し替えましたので、そちらでご確認ください。

2021-12-08 14:41 UTC, yoshitaku-jp commented
@IkumaTadokoro さん
修正ありがとうございます！
遷移についても確認ができました！LGTMです！

2021-12-08 14:41 UTC, yoshitaku-jp approved these changes

2021-12-09 00:31 UTC, IkumaTadokoro commented
@yoshitaku-jp 
ご確認いただきありがとうございました〜😊

@komagata 
お手数ですが、こちらレビューお願いいたします〜🙇‍♂️

2021-12-13 02:45 UTC, komagata commented on app/javascript/tag-edit-modal.vue
> +
他に合わせてこういう場所の空行はない方がいいかも？と思いました〜

2021-12-13 05:08 UTC, IkumaTadokoro commented on app/javascript/tag-edit-modal.vue
> +
ありがとうございます！ 71f49e851aa1bd92b098298c93221d26475f24b4 にて修正いたしました！

2021-12-13 05:09 UTC, IkumaTadokoro commented
@komagata 
コメントいただいた箇所を修正いたしましたので、お手数ですが再度レビューお願いいたします🙇‍♂️

2021-12-14 20:17 UTC, komagata requested changes
コンフリクトの修正お願いします〜

2021-12-14 23:35 UTC, IkumaTadokoro commented
コンフリクト修正いたしました（最新のmainに合わせて、JSの読み込みもESM形式に修正済みです）！
再度ご確認お願いいたします🙏

2021-12-21 07:15 UTC, komagata requested changes

2021-12-21 07:15 UTC, komagata commented on app/controllers/api/tags_controller.rb
> +      head :ok if update_target.update(tag_id: same_name_tag.id) && destroy_target.destroy_all
ここでやりたいこと（やってること）をメソッド化してメソッド名で表すとわかりやすくなるかもです。

2021-12-21 07:15 UTC, komagata commented on test/system/question/tags_test.rb
> +# frozen_string_literal: true
別ファイルに抜き出したのがいいですね👍

2021-12-21 10:43 UTC, IkumaTadokoro commented on app/controllers/api/tags_controller.rb
> +      head :ok if update_target.update(tag_id: same_name_tag.id) && destroy_target.destroy_all
同名タグの更新処理を 906065476999455cd52e769e3ca5781be4068420 でメソッドに抽出しました！

2021-12-21 10:44 UTC, IkumaTadokoro commented
@komagata 
レビューいただいた箇所を修正いたしましたので、お手数ですが再度レビューをお願いいたします〜🙇‍♂️

2021-12-22 00:22 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-22 00:22 UTC, merged