Feature/delete cached values after the value increase or decrease
fjordllc/bootcamp pull request #3690
Opened 2021-12-07 08:45 UTC by AudioStakes

# 目的

Refs: #3638

# 調査したこと

## #3638 に記載の再現手順を行なっても表示件数が変わらない原因

### 「未完了」タブのバッジ

未完了の提出物が確認済み（完了）に更新されたときに、未完了の提出物件数のキャッシュが削除されていないこと

### 「自分の担当」タブのバッジ

「自分の担当」かつ「未返信」の提出物が返信済みの状態になったとき（担当者がコメントしたとき）に、「自分の担当」かつ「未返信」の件数のキャッシュが削除されていないこと

## キャッシュが削除されるべき（キャッシュされている件数が変わる）タイミング

#3638 に記載の再現手順以外にも、キャッシュが削除されていないケースがないか確認するために調査した。

**凡例**
☆: #3638 の再現手順
★: #3638 の再現手順以外のキャッシュが削除されないケース（この PR での対応に含めた）

### 未完了の提出物件数のキャッシュ

※ 「未完了」タブのバッジに表示される件数のキャッシュ

- 未完了の提出物が作成されたとき
- 未完了の提出物が削除されたとき
- ☆未完了の提出物が確認済み（完了）に更新されたとき
- ★確認済み（完了）の提出物が未完了に更新されたとき

### 「自分の担当」かつ「未返信」の提出物件数のキャッシュ

※ 「自分の担当」タブのバッジに表示される件数のキャッシュ

- ★「担当がいない」かつ「未返信」の提出物の担当になったとき
- ★「自分の担当」かつ「未返信」の提出物の担当を外れたとき
- 自分が担当する提出物が「返信済み」から「未返信」になったとき
    - ☆未返信の提出物に担当者がコメントしたとき
    - ★返信済みの提出物の最新コメント（担当者のコメント）が削除され、担当者以外のユーザーのコメントが最新となったとき
- 自分が担当する提出物が「未返信」から「返信済み」になったとき
    - ★返信済みの提出物に担当者以外のユーザーがコメントしたとき
    - ★未返信の提出物の最新コメント（担当者以外のユーザーのコメント）が削除され、担当者のコメントが最新となったとき

# やったこと

（まとめ中）

2022-01-06 04:55 UTC, AudioStakes commented
@unstoppa61e 
ご都合の良いときに、こちらのレビューをお願いします！

動作確認をする際に事前準備（詳細は Description に記載しました）が必要であることや、キャッシュを削除する条件の説明量が多いことが影響して、レビューしてもらうのに時間がかかってしまうかもしれません。

もし不明点がありましたらお気軽に質問してください。よろしくお願いします🙏

2022-01-07 06:17 UTC, unstoppa61e requested changes
こちらの PR、偉大ですね…。
僕がちょうどキャッシュのことについて学びたかったところだったので、レビューさせて頂けてありがたかったです🙏
指摘させて頂いたのは、本質的でないものがほとんど全てです。
そういうものにつきましては、どうぞ取捨選択なさった上でご修正くださいませ。

2022-01-07 07:03 UTC, AudioStakes commented on test/models/caches/unchecked_product_count_test.rb
> +  test 'increase the cached value of unchecked product count by 1 after create a product' do
なるほど、たしかにそのように書いた方が読みやすいと思いました！他のテストケースについても、添削していただいてありがとうございますー🙏

2022-01-07 07:30 UTC, AudioStakes commented on app/models/comment.rb
> +  end
> commentsが 0 件の場合もtrueになってしまいませんでしょうか？

僕の理解では commentsが 0 件という場合は存在しないのかな、と考えています。というのも、このメソッドは Comment モデルのインスタンスメソッドであるため、ある Comment インスタンスがこのメソッドを使うときは少なくともそのインスタンス1件の comments が存在すると思うためです。どうでしょうか？

2022-01-07 08:15 UTC, unstoppa61e commented on app/models/comment.rb
> +  end
仰る通りですね、失礼致しました🙏
お教えくださってありがとうございました！😄

2022-01-07 11:24 UTC, unstoppa61e approved these changes
@AudioStakes 
確認させて頂きました！😄 💪

2022-01-11 00:16 UTC, AudioStakes commented
@unstoppa61e 
ご確認、ありがとうございます！

@komagata
ご都合の良いときに、こちらのレビューをよろしくお願いいたします🙏

2022-01-14 03:30 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-14 03:30 UTC, komagata commented on app/models/product.rb
> +    is_replied_by_checker_previous != is_replied_by_checker_current
わかりやすい名前の変数に一旦入れることでわかりやすくなってますね！

2022-01-14 04:09 UTC, merged