日報で、ニコニコカレンダーがsadのときにコメント0で確認ボタンを押すと警告がでるように追加する
fjordllc/bootcamp pull request #3721
Opened 2021-12-09 03:12 UTC by nga20167304

Isssue: #3674
## 概要
日報で、ニコニコカレンダーがsadのときにコメント0で確認ボタンを押すと警告がでないので、警告を追加する。
## 変更前
警告がでない。
## 変更後
<img width="1437" alt="スクリーンショット 2021-12-09 10 05 22" src="https://user-images.githubusercontent.com/38340962/145327600-eaaade78-30de-4d90-8232-ca58c0df6065.png">

2021-12-09 09:22 UTC, nga20167304 commented
@yoshitaku-jp さん、
お手数ですが、お時間のある際にこちらのレビューをお願いします!🙏

2021-12-12 23:48 UTC, yoshitaku-jp commented
@nga20167304 さん
こちら確認できました！大丈夫です！

2021-12-12 23:49 UTC, yoshitaku-jp approved these changes

2021-12-13 01:26 UTC, nga20167304 commented
@yoshitaku-jp さん
確認いただきありがとうございます。

2021-12-13 01:27 UTC, nga20167304 commented
@komagata さん
yoshitaku-jp さんに確認されたので、こちらのレビューお願いします。

2021-12-13 03:21 UTC, komagata commented on app/javascript/check.vue
> +      return sadEmotion !== undefined ? 1 : 0
booleanを返す方がいいかも？

2021-12-13 07:26 UTC, nga20167304 commented
@komagata さん
修正したので、再レビューお願い致します。:pray:

2021-12-14 20:29 UTC, komagata requested changes

2021-12-14 20:29 UTC, komagata commented on app/javascript/check.vue
> +      return sadEmotion !== undefined
<img width="293" alt="スクリーンショット 2021-12-15 5 28 40" src="https://user-images.githubusercontent.com/16577/146074611-095e69ca-7d78-4c54-8523-0ad377cb8a8c.png">

document#querySelectorはマッチしないとき`null`を返します。
そして`null`と`undefined`は別のものなのでこれだと間違ってるかも？

2021-12-15 01:23 UTC, nga20167304 commented on app/javascript/check.vue
> +      return sadEmotion !== undefined
はい、了解です！
勉強になりました！ありがとうございます。

2021-12-15 04:26 UTC, nga20167304 commented
@komagata さん、
修正したので、ご確認お願い致します。:bow:

2021-12-20 00:56 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-20 00:59 UTC, nga20167304 commented
@komagata さん
確認いただきありがとうございます。

2021-12-21 17:57 UTC, merged