welcomeのフッタのcopyrightの年の表示を「2012-現在の年」に変更
fjordllc/bootcamp pull request #3727
Opened 2021-12-09 15:07 UTC by Paru871

ref:[#3653](https://github.com/fjordllc/bootcamp/issues/3653)

## 概要
/welcome ページのフッタのCopyright年の表示を変更
スタートを2012として右側は動的に今の年とする

## 修正前
![スクリーンショット 2021-12-09 23 16 11](https://user-images.githubusercontent.com/82434093/145421410-efe1dfce-ee75-45b9-850f-95a17f30bceb.png)

## 修正後
![スクリーンショット 2021-12-10 0 01 27](https://user-images.githubusercontent.com/82434093/145421456-b4a1ec75-8c80-4373-b5ae-98eb8cabee90.png)

2021-12-09 15:46 UTC, Paru871 commented
@naomichi-h 
お疲れさまです！お手数をおかけしますが、レビューをお願いいたします🙏

2021-12-13 07:00 UTC, naomichi-h commented
@Paru871 
確認しました！動作は問題ないです！バッチリです😄細かいところの一点だけ確認お願いします！

修正前のものは、`Fjord Inc. 2021`と、Fjord Inc. と年の間にスペースがあるので、今回もそれに習って
`Fjord Inc. 2012 - 2021`となるように、Fjord Inc. と年の間にスペースを設けた方が良いかな？と思いました。

2021-12-13 08:33 UTC, Paru871 commented
@naomichi-h 
さっそくレビューいただきましてありがとうございました！

> 修正前のものは、`Fjord Inc. 2021`と、Fjord Inc. と年の間にスペースがあるので、今回もそれに習って `Fjord Inc. 2012 - 2021`となるように、Fjord Inc. と年の間にスペースを設けた方が良いかな？と思いました。

確かに！その通りだと思いました。
教えていただいたところを直して再度pushしました。

![2021-12-13 16 51 27](https://user-images.githubusercontent.com/82434093/145778215-b2ced564-fea5-4e6d-bba8-e4d2f8b2d0cc.png)

お手数をおかけしますが、再度レビューいただけますでしょうか。
よろしくお願いいたします！

2021-12-13 08:51 UTC, naomichi-h commented
@Paru871 
確認しました！大丈夫ですー👍

2021-12-13 10:41 UTC, Paru871 commented
@naomichi-h 
この度はありがとうございました！初めてのIssueのためいろいろ手際が悪くて申し訳ありませんでした。
今後ともどうぞよろしくお願いいたします🙏

2021-12-13 10:44 UTC, Paru871 commented
@komagata さん
お疲れさまです。メンバーのレビューが終了しましたので、ご確認をよろしくお願いいたします。

2021-12-14 20:36 UTC, komagata requested changes

2021-12-14 20:36 UTC, komagata commented on app/views/welcome/_welcome_footer.html.slim
> +        | Fjord Inc. 2012 - #{Time.zone.today.year}
- 時間は必要じゃないのでDateクラスの方が良さそう
- `Date.zone.today`は`Date.current`と同じなので後者が良さそう

なので、

```suggestion
        | Fjord Inc. 2012 - #{Date.current.year}
```

でいいかもです〜

2021-12-15 11:18 UTC, Paru871 commented on app/views/welcome/_welcome_footer.html.slim
> +        | Fjord Inc. 2012 - #{Time.zone.today.year}
確かにTimeよりもDateが良いと思いましたので提案いただいたものを使うことにします。

2021-12-15 11:33 UTC, Paru871 commented
@komagata さん
修正が完了しましたので、再度レビューをお願いいたします。（レビュー依頼方法を前回失敗して申し訳ありませんー今回は大丈夫だと思います！）
9c4ead737f46f2690277a6f129acf33fd2011ef3

2021-12-21 07:16 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-21 07:16 UTC, merged

2021-12-22 04:23 UTC, Paru871 commented
@komagata さん、ありがとうございました。
記念すべき初マージ！感動しております〜🥲

2021-12-22 06:56 UTC, komagata commented
@Paru871 初マージおめでとうございます〜🎉