入会時のアンケートに『フィヨルドブートキャンプを卒業したらやりたいこと』の項目を追加する
fjordllc/bootcamp pull request #3778
Opened 2021-12-15 08:22 UTC by R-Tsukada

2021-12-16 07:14 UTC, R-Tsukada commented
@ShotaTsuru 
お手隙の際にレビューをお願いします🙇‍♂️

2021-12-18 00:18 UTC, ShotaTsuru commented
@R-Tsukada すみません！気づくの遅れました🙇‍♂️🙇‍♂️🙇‍♂️
今日中にレビューします！！

2021-12-18 00:46 UTC, ShotaTsuru approved these changes
登録・変更・表示全て動作確認できました！コードも問題ないかと思います。LGTMです🙇‍♂️
遅れて申し訳ありません！！

2021-12-18 01:08 UTC, R-Tsukada commented
@ShotaTsuru 
> 遅れて申し訳ありません！！

全然大丈夫です！
レビューありがとうございました！

2021-12-18 01:10 UTC, R-Tsukada commented
@komagata 
こちらのレビューをお願いします🙇‍♂️

レビューが終わったらmachidaさんにデザインを修正していただく予定になっています。

2021-12-21 17:56 UTC, komagata requested changes

2021-12-21 17:56 UTC, komagata commented on app/views/users/form/_after_graduation_hope.html.slim
> +      | 例: 『�ITジェンダーギャップ問題を解決するアプリケーションを作る事業にエンジニアとして携わる』
ここ文字化けしてるみたいです〜

2021-12-21 17:56 UTC, komagata commented on app/views/users/_user_secret_attributes.html.slim
> +        - if !user.after_graduation_hope.nil?
```suggestion
        - if user.after_graduation_hope?
```

でいいかも？

2021-12-22 01:44 UTC, R-Tsukada commented
@komagata 
ご確認ありがとうございます🙇‍♂️
修正しましたので、改めてご確認をお願いします！

2021-12-22 06:55 UTC, komagata requested changes

2021-12-22 06:55 UTC, komagata commented on app/views/home/index.html.slim
> +          - if current_user.after_graduation_hope.presence
```suggestion
          - if current_user.after_graduation_hope?
```

2021-12-22 12:14 UTC, R-Tsukada commented on app/views/home/index.html.slim
> +          - if current_user.after_graduation_hope.presence
修正しました🙇‍♂️
ご確認をお願いします！

2021-12-24 06:46 UTC, komagata requested changes
conflictの修正お願いします〜

2021-12-25 13:56 UTC, R-Tsukada commented
@komagata 
> conflictの修正お願いします〜

すみません、見落としていました🙇‍♂️
conflict修正しましたので、ご確認をお願いします。

2021-12-26 06:50 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-26 06:50 UTC, komagata commented
@machida こちら、デザインと文言の確認お願い致します〜

2021-12-26 08:15 UTC, R-Tsukada commented
ご確認ありがとうございます🙇‍♂️！

machida さん
デザインよろしくお願いします🙏

2022-01-17 04:20 UTC, machida commented
@R-Tsukada デザイン入れました！！再度確認したらマージします

2022-01-24 09:03 UTC, machida commented
テストが通ったのでマージしますー

2022-01-24 09:03 UTC, merged