discord・メール・サイト内通知を実装
fjordllc/bootcamp pull request #3779
Opened 2021-12-16 01:53 UTC by taka61

途中です

2021-12-16 04:43 UTC, taka61 commented
@unstoppa61e さん
お手数ですが、お時間のある際にこちらのレビューをお願いします!🙏

2021-12-17 00:08 UTC, unstoppa61e commented
@taka61 
手順 10 にて http://127.0.0.1:3000/scheduler/daily にアクセスしたところ、Discord、Bootcamp アプリ、メールの３方向からの通知が全て届きました。
見落としている可能性のある点がございましたら、ご指摘頂けると助かります。

2021-12-17 03:59 UTC, taka61 commented
@unstoppa61e さん
マイグレーションファイルに問題があったようです…！
お手数お掛けし、申し訳ないです💦

一度DBの内容をリセットした後に、新たに追加したファイルの取り込みを行なって頂きたいと思います。
以下が手順となります。

<手順>
1. DBのリセットを行う
参考：[ActiveSrorageインストール後のrails db:migrateでエラーが出ることについて
](https://bootcamp.fjord.jp/questions/967)
`rails db:drop db:create db:migrate db:seed`

2. マイグレーションファイルをダウンさせる
 `bundle exec rake db:migrate:down VERSION=20211216021804`

3. `20211216021804_add_retired_notification_to_users.rb `ファイルがdownになっているか確認 
`rake db:migrate:status`

4. downになっていることが確認できたらファイルを削除する
 `rm -rf db/migrate/20211216021804_add_retired_notification_to_users.rb`

5. 該当のファイルが削除され、元に戻った状態でデータベースを更新する。
`rails db:migrate`
これでmainブランチと同じ状態に戻ると思います!

6. リモートブランチの変更を取り込み
`git pull --rebase origin feature/notify-admin-of-retirements-after-3months`

7. 新しいマイグレーションファイルを実行
`bundle exec rake db:migrate:up VERSION=20211217025508`

8. data-migrate gemで作成したファイルを実行
`rake data:migrate:up VERSION=20211217030634`

9. 以上で問題は修正できていると思いますので…
`rails s`でサーバー立ち上げ→komagataでログインして頂き、再度`10`の手順から確認を再開して頂ければと思います。

度々動作手順長くなってしまいすみません😭
お手数をおかけししますが、よろしくお願いします🙏

2021-12-17 04:57 UTC, unstoppa61e commented
@taka61 
こちらは全然大丈夫です！😄 
そのためのレビュアーですので！👍

手順 13 まで進んだのですが、メールとサイト内通知は受け取れたものの、Discord 通知が来ませんでした。
ぴーさんのお手元ではいかがでしょうか？
ご確認の上、お気付きの点がおありでしたらお知らせくださいませ（もし、こちらの操作等に落ち度がありましたらごめんなさい）。

2021-12-17 05:54 UTC, taka61 commented
@unstoppa61e さん
>こちらは全然大丈夫です！😄

そう言って頂けると助かります…💦

> メールとサイト内通知は受け取れたものの、Discord 通知が来ませんでした。
ぴーさんのお手元ではいかがでしょうか？

私の方ではDiscordでの通知が確認出来ています〜👀

<img width="534" alt="スクリーンショット 2021-12-17 14 35 29" src="https://user-images.githubusercontent.com/80372144/146494729-fafb5cc6-e528-4b69-acd0-7b20e895907e.png">


考えられることとして
1. `dotenv-rails`というgem の追記場所に問題がある
※以前gemの追記場所を一番最後の行に付け足したところ、正常に作動しませんでした。
 `group :development do. `の場所に書かないといけないようです。

2.  `.env`ファイルに問題がある
(ご参考までに私の`.env`ファイルになります)

<img width="556" alt="スクリーンショット 2021-12-17 14 43 15" src="https://user-images.githubusercontent.com/80372144/146495261-96421274-38e6-4432-8bb7-0f2142abeec5.png">

```
DISCORD_TEST_WEBHOOK_URL = https://discord.com/api/webhooks/917981261245612052/k3UF103si_T4M1fpoXEPnzphWIA59MCbDVjptQVZYhuTBdHi8Jlhdqwi-f_9cfE5_trD
```

3. `app/model/chat_notifier.rb`の`10行目`が
`if Rails.env.production?` → `if Rails.env.development?` へ変更されていない

4. `app/models/user.rb `の `318行目`が ` ENV['DISCORD_ADMIN_WEBHOOK_URL']` → `ENV['DISCORD_TEST_WEBHOOK_URL'] `へ変更されていない

##
以上がDiscordでの動作確認が出来ない理由として考えられるものなのですが、これを元にもう一度設定を見直して頂けますでしょうか？
動作が確認出来なかった場合は教えて下さい😣🙏
宜しくお願いします!

2021-12-17 06:17 UTC, unstoppa61e commented
@taka61 
`git pull --rebase origin feature/notify-admin-of-retirements-after-3months`を行った時に、今回変更した箇所が元に戻っていたのが原因だった様子です🙏
引き続き確認を進めさせて頂きます。

2021-12-17 07:53 UTC, unstoppa61e reviewed
難しい内容を実装なさっていて、凄いです…！
こちらも勉強させて頂きました🙏
レビュー内容、ご参考頂けると幸いです😄

2021-12-17 10:04 UTC, unstoppa61e commented
あと、各種のテストが必要かと思います…！

2021-12-17 19:38 UTC, unstoppa61e commented on app/views/notification_mailer/retired_after_three_months.html.erb
> +     https://bootcamp.fjord.jp/users/<%= @sender.id %>
それと、「3か月」という期間は変更の可能性がありますので、変更があっても問題ないよう、「3か月」という期間に依存しないファイル名の方が良いかもしれません(ただの一意見ですので、取り入れて頂かなくても全く構いません)。

2021-12-20 07:24 UTC, komagata commented on app/controllers/scheduler/daily_controller.rb
> +      if retired_user.retired_on <= Date.current - 3.months && retired_user.retired_notification == false
:memo: この1行をuserのメソッドとして纏めてはどうかという意味とのこと

2021-12-21 05:37 UTC, taka61 commented on app/mailers/notification_mailer.rb
> +    subject = "[bootcamp] #{@sender.login_name}さんが退会して3ヶ月経過しました。"
@unstoppa61e さん
> こちらの退会の文言と同一のものが違う場所でも使用されていますが、変更が必要になった場合の修正が大変なので、ja.ymlにまとめて、I18n.tを通して使うと良いと思います（手元で試したところ、全て置き換えられました）。

この点に関して1点確認があります~!
`app/mailers/notification_mailer.rb`の`106`行目
`app/models/user.rb`の`313`行目の2箇所を指しているという認識で合っていますか👀?

2021-12-23 08:24 UTC, taka61 commented on app/views/notification_mailer/retired_after_three_months.html.erb
> +     https://bootcamp.fjord.jp/users/<%= @sender.id %>
ファイル名はメソッド名と対応する形でメール文の読み込みを行なっていたため、`three_months_after_retirement.rb`への変更で留めています。
よろしくお願いします🙏

2021-12-23 08:26 UTC, taka61 commented on app/models/notification.rb
> +      message: "#{sender.login_name}さんが退会して3ヶ月経過しました。Discord ID【#{sender.discord_account}】・ユーザーページ【https://bootcamp.fjord.jp/users/#{sender.id}】",
提案いただいた
>Discord ID: XXXX, ユーザーページ: YYYY

表記に変更しました~

2021-12-23 08:26 UTC, taka61 commented on app/models/notification_facade.rb
> +    return unless receiver.mail_notification? && !receiver.retired_on?
提案ありがとうございます!
`retired?`メソッドに変更しました。

2021-12-23 08:26 UTC, taka61 commented on db/migrate/20211216021804_add_retired_notification_to_users.rb
> +      retired_user.update!(retired_notification: true) if retired_user.retired_on <= Date.current.prev_month(n = 3)
>ここだけ、`Date.current.prev_month(n = 3)`というように`prev_month`を使っているのには、何か意味があるでしょうか？

これは修正前の表記（古いファイル）で、既にこの部分は修正されていたと思います🙆‍♀️

2021-12-23 08:27 UTC, taka61 commented on app/mailers/notification_mailer.rb
> +    subject = "[bootcamp] #{@sender.login_name}さんが退会して3ヶ月経過しました。"
文面・翻訳の提案ありがとうございます!
またファイルの詳細の追記もありがとうございます。
`ja.yml`に`「○○さんが退会してから3カ月が経過しました。」`の部分をまとめました。

2021-12-23 08:27 UTC, taka61 commented on app/models/notification.rb
> +      kind: 9,
提案ありがとうございます!
`kind`の後に直接数値が続いている部分は書き直しました。

2021-12-23 08:27 UTC, taka61 commented on app/mailers/notification_mailer.rb
> +    @notification = @user.notifications.find_by(path: "/users/#{@sender.id}")
>  @user = @receiver

の部分を削除すると私の手元ではメールの送信が止まってしまった為、この部分は置き換えたままにさせて頂きます。
よろしくお願いします🙏

2021-12-23 08:28 UTC, taka61 commented on app/mailers/notification_mailer.rb
> +  def retired_after_three_months
`retired_after_three_months`だと3ヶ月後に退職と取れて紛らわしかったですね…
提案いただいた`three_months_after_retirement`に変更しました。

2021-12-23 08:28 UTC, taka61 commented on app/controllers/scheduler/daily_controller.rb
> +      if retired_user.retired_on <= Date.current - 3.months && retired_user.retired_notification == false
`user.rb`にてメソッド化しました〜
提案ありがとうございます!

2021-12-23 08:30 UTC, taka61 commented on app/models/user.rb
> +            Discord ID
>"Discord ID" の行の先頭にインデントが大きくある

すみません、こちらの意味があまり分からずもしかしたら修正出来ていないかもしれません…！
（一応修正したつもりです）
表示が引き続き気になりましたら教えて下さい🙏

2021-12-24 03:59 UTC, unstoppa61e commented on app/mailers/notification_mailer.rb
> +    @notification = @user.notifications.find_by(path: "/users/#{@sender.id}")
```ruby
  def three_months_after_retirement
    @user = @receiver
    @notification = @user.notifications.find_by(path: "/users/#{@sender.id}")
    mail(to: @user.email, subject: default_i18n_subject(user: @sender.login_name.to_s))
  end
```
から
```ruby
  def three_months_after_retirement
    @notification = @receiver.notifications.find_by(path: "/users/#{@sender.id}")
    mail(to: @receiver.email, subject: default_i18n_subject(user: @sender.login_name.to_s))
  end
```
に書き換えられたのに動かなかったということでしょうか？
もしかすると、`@user`が残ったままになっていませんでしたでしょうか？

2021-12-24 04:31 UTC, unstoppa61e reviewed
Discord の文面のインデントは、修正されていませんでした。
以下の部分です。
![スクリーンショット 2021-12-24 13 23 52](https://user-images.githubusercontent.com/46347198/147316311-8a99b30e-856f-4198-ac9a-226dcfd0cb55.png)
それと、確認手順のままで実行すると、デフォルトで退会している２名からの通知が飛んできてしまう状態になっていますので、そちらを更新して頂けますようお願い致します。

2021-12-24 04:31 UTC, unstoppa61e commented on app/models/user.rb
> +            webhook_url: ENV['DISCORD_TEST_WEBHOOK_URL']
最初に拝見した際は`ENV['DISCORD_ADMIN_WEBHOOK_URL']`でした。
その後で開発環境で動かされて、そのままになってしまっているのではないかと思います。

2021-12-24 12:29 UTC, taka61 commented on app/models/user.rb
> +            webhook_url: ENV['DISCORD_TEST_WEBHOOK_URL']
>Discord の文面のインデントは、修正されていませんでした。

インデント部分修正しましたので、再度確認をお願いします!

>それと、確認手順のままで実行すると、デフォルトで退会している２名からの通知が飛んできてしまう状態になっていますので、そちらを更新して頂けますようお願い致します。

1. DBのリセットを行う
`rails db:drop db:create db:migrate db:seed`

2. data-migrate gemで作成したファイルを実行
`rake data:migrate:up VERSION=20211217030634`

上記の手順で再度確認をお願いします🙏
`db/migrate/20211223071408_add_retired_notification_to_users.rb`を実行することで、
既存の退会後3カ月経過済みユーザーの`retired_notification`が`true`になり、
デフォルトで退会している2名からの通知は来ないはずです。
(問題が続いたら教えて下さい~!)

2021-12-24 12:33 UTC, taka61 commented on app/mailers/notification_mailer.rb
> +    @notification = @user.notifications.find_by(path: "/users/#{@sender.id}")
一部の`@user`が残ったままになっていました…。
ご丁寧に説明頂きありがとうございます🙏🙏
修正しました!

2021-12-24 22:18 UTC, unstoppa61e approved these changes
気付いた点が１点ありましたので、コメントさせて頂きました。
精一杯レビューしたつもりですが、もしも駒形さんのレビューで「この修正は要らなかったね」ということが判明してしまったらごめんなさい🙏

2021-12-24 22:18 UTC, unstoppa61e commented on app/models/user.rb
> +  def retired_three_months_ago_and_not_send_notification?(retired_user)
`not_send_notification`ですと、メソッド名からは処理が推測しにくいかも、と思いました。
（`notification_not_sent`とかでしょうかね…？）

2021-12-24 22:20 UTC, unstoppa61e commented on app/models/user.rb
> +            webhook_url: ENV['DISCORD_TEST_WEBHOOK_URL']
> インデント部分修正しましたので、再度確認をお願いします!

修正されていることを確認しました👍
> そちらを更新して頂けますようお願い致します。

`VERSION=XXXXXXXX`のタイムスタンプが変更されているので、次に動作確認なさる方のために、このページの一番上の「確認手順」を更新して頂きたい、という意味でした…！（こちらで更新しておきました）

2021-12-26 08:19 UTC, taka61 commented on app/models/user.rb
> +            webhook_url: ENV['DISCORD_TEST_WEBHOOK_URL']
こちら勘違いしていました…💦更新して頂きありがとうございます🙏🙏

2021-12-26 08:24 UTC, taka61 commented on app/models/user.rb
> +  def retired_three_months_ago_and_not_send_notification?(retired_user)
`retired_user`を主語と考え`retired three months ago`・`not send notification`というメソッドにしたのですが、
分かりにくかったかもしれません🤔
提案頂いた`notification_not_sent`に変更しました!
ありがとうございます🙆‍♀️

2021-12-26 08:35 UTC, taka61 commented
@unstoppa61e さん

度々レビューありがとうございます！
ご指摘いただいた箇所を修正しましたので再度ご確認をよろしくお願いいたします！

2021-12-26 22:18 UTC, unstoppa61e commented on app/models/user.rb
> +  end
こちらのメソッド、クラスメソッドになっているのですが、`retired?`などと同様のインスタンスメソッドにしてあげた方が良いかな、と思います（このメソッドを追加なさったタイミングで気付けたら良かったです、すみません🙏）。
現状ですと、
```ruby
user1. retired_three_months_ago_and_notification_not_sent?(user1)
```
と、対象ユーザーを２回書く形になっていますが、それが、
```ruby
user1. retired_three_months_ago_and_notification_not_sent?
```
だけで済むようにしてあげると良いかと思います！

2021-12-27 02:00 UTC, taka61 commented on app/models/user.rb
> +  end
確認頂きありがとうございます😀
`retired_three_months_ago_and_notification_not_sent?`メソッドは
`356`行目に書いているのでメソッド自体はインスタンスメソッドになっていると思います！
ただマコトさんが仰っていた通り、インスタンスメソッドなので引数は不要でした💦ご指摘ありがとうございます！
引数を削除し、対象ユーザーを1回書く形へ変更しました。
再度ご確認をお願いします🙏🙏

2021-12-28 00:37 UTC, unstoppa61e approved these changes
Approve させて頂いております！👍
長くなってしまい、すみませんでした。
大変お疲れ様でした。
ありがとうございました！🙏

2021-12-28 00:37 UTC, unstoppa61e commented on db/migrate/20211223071408_add_retired_notification_to_users.rb
> +    add_column :users, :retired_notification, :boolean, default: false, null: false
追加しているカラム名、`retired_notification`は、違う意味だと想像しやすいかもしれないと思いました（退会通知を行うユーザーとそうでないユーザーが存在する、などのような）。
「退会通知を実施済み」ということを意味するのであれば、もし僕であれば`notified_retirement`などにするかな、と思いました。

2021-12-28 00:37 UTC, unstoppa61e commented on app/models/user.rb
> +  end
インスタンスメソッドではあったとのこと、失礼致しました🙇‍♂️
確認させて頂きました、LGTM です！

2021-12-28 02:38 UTC, taka61 commented on db/migrate/20211223071408_add_retired_notification_to_users.rb
> +    add_column :users, :retired_notification, :boolean, default: false, null: false
今回の場合はただの退会通知ではなく「退会通知を実施済み」という意味なので`notified_retirement`の方が適切ですね。提案ありがとうございます!
`notified_retirement`へ変更しました🙆‍♀️

2021-12-28 02:43 UTC, taka61 commented
@unstoppa61e さん
お疲れ様です！
長い間お時間取って頂き、たくさんのレビューありがとうございました🙇‍♀️🙇‍♀️
とても勉強になりました😀🙌

@komagata さん
チームメンバーのレビューを通過しましたので、お時間ある際にこちらのレビューをお願いします😀

2021-12-28 08:57 UTC, komagata requested changes

2021-12-28 08:57 UTC, komagata commented on test/system/notification/after_retirement.rb
> +    login_user 'komagata', 'testtest'
7行目で既にkomagataでログインしているのでこの行は不要かと思います〜

2022-01-05 05:15 UTC, taka61 commented on test/system/notification/after_retirement.rb
> +    login_user 'komagata', 'testtest'
確認頂きありがとうございます！

9行目の`login_user 'komagata', 'testtest'`を削除し、
ホーム画面に遷移する形へ変更しました。
（`/scheduler/daily`に留まったままでは通知を開くことができないため、ホーム画面へ遷移しています）

再度ご確認を宜しくお願いします🙏

2022-01-05 05:32 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-05 05:32 UTC, merged