メール通知のバグを修正
fjordllc/bootcamp pull request #3785
Opened 2021-12-16 07:02 UTC by taka61

2021-12-16 08:11 UTC, taka61 commented
@nga20167304 さん
お手数ですが、お時間のある際にこちらのレビューをお願いします!🙏

2021-12-16 10:14 UTC, nga20167304 approved these changes
確認しました！

2021-12-16 12:46 UTC, nga20167304 commented on app/controllers/retirement_controller.rb
> +  def notify_to_admins(current_user)
@taka61 さん、
Approvedしましたが、その後、もう一度考えて、以下のコードがいかがでしょうか。
```suggestion
  def notify_to_admins
```

2021-12-16 12:46 UTC, nga20167304 commented on app/controllers/retirement_controller.rb
> +      notify_to_admins(user)
これだけいかがでしょうか。
```suggestion
      notify_to_admins
```

2021-12-17 02:03 UTC, taka61 commented
@nga20167304 さん
レビュー頂きありがとうございます〜！
たしかに引数を削除しても問題なく動作しますね!ご指摘ありがとうございます😀
頂いた箇所を修正しましたので、再度ご確認のほどよろしくお願いします🙏

2021-12-17 02:17 UTC, nga20167304 commented
@taka61 さん
確認しました！LGTMです！

2021-12-17 04:03 UTC, taka61 commented
@nga20167304 さん
確認・レビュー頂きありがとうございました😀🙏

@komagata さん
チームメンバーのレビューを通過しましたので、お時間ある際にこちらのレビューをお願いします!

2021-12-21 17:48 UTC, komagata requested changes

2021-12-21 17:48 UTC, komagata commented on app/controllers/retirement_controller.rb
> +      NotificationFacade.retired(current_user, admin_user)
確か`NotificationFacade.retired`ってのは**サイト内通知**と**メール**を両方飛ばすためにあったと思います。

なのでこちらだけあればいいと思います〜。

2021-12-24 01:11 UTC, taka61 commented on app/controllers/retirement_controller.rb
> +      NotificationFacade.retired(current_user, admin_user)
@komagata さん
`NotificationFacade.retired`で両方の機能があったんですね!👀
指摘頂いた箇所を修正しました。
お手数ですが、再度ご確認をお願いします🙏

2021-12-26 06:17 UTC, komagata commented on app/controllers/retirement_controller.rb
> +      NotificationFacade.retired(current_user, admin_user)
@taka61 こちら、修正後に両方の通知が飛んでることの確認はできていますでしょうか

2021-12-26 07:09 UTC, taka61 commented on app/controllers/retirement_controller.rb
> +      NotificationFacade.retired(current_user, admin_user)
@komagata さん
サイト内・メール両方で通知を受け取っていることを確認しています！

2021-12-26 07:10 UTC, komagata commented on app/controllers/retirement_controller.rb
> +      NotificationFacade.retired(current_user, admin_user)
@taka61 なるほどです〜

2021-12-26 07:10 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-26 07:10 UTC, merged