ダッシュボード > 自分の日報 を Vue.js 化
fjordllc/bootcamp pull request #3818
Opened 2021-12-20 08:52 UTC by unstoppa61e

- issue: #3762 
- 併せて、`Promise`を`.then`でつないであった部分を`async`/`await`方式に書き換えました。

2021-12-21 03:25 UTC, unstoppa61e commented
@IkumaTadokoro 
こちらのレビューをお願いしたいです🙏
なお、気になっている点としましては、今回作成したファイルの１つである`app/views/api/current_user/reports/index.json.jbuilder`は、既存の`app/views/api/reports/index.json.builder`と全く同じであるため、DRY にする方法がある可能性もあるかと思いつつも、解決策が思い浮かびませんでした。

2021-12-21 07:02 UTC, IkumaTadokoro approved these changes
確認しました〜！LGTMです🦀 

---

> app/views/api/current_user/reports/index.json.jbuilderは、既存のapp/views/api/reports/index.json.builderと全く同じであるため、DRY にする方法がある可能性もあるかと思いつつも、解決策が思い浮かびませんでした。

パッと思いつく方法だと次の2つとかでしょうか。

1. `CurrentUser::ReportsController`で`render`でreports側のjbuilderを指定する
1. `reports/index.json.builder`をパーシャルにして、`reports/index`側からも`current_user/index`側からもパーシャルを呼び出す処理（`json.partial!`）だけ記述する

自分も全く同じビューを使うケースに遭遇したことがないので、どういう風にするのがいいのかが悩ましいですね（2回しか重複していないので、まだDRYにするかは検討しない、という選択肢もあるかも）。

2021-12-21 07:12 UTC, unstoppa61e commented
@IkumaTadokoro 
早速のレビュー、ありがとうございます！
そして、何より、実装案を２つもお教えくださり、ありがとうございました！😭（実は、「レビューは、解決策を知っていらっしゃいそうな方にお願いしたいから…ikuma-t さん！」という経緯でした😁 ）
お教えくださった方法、試させて頂きます！🙏

2021-12-21 07:19 UTC, IkumaTadokoro commented
@unstoppa61e 
どっちの方法がいいか気になったので、質問タイムでkomagataさんに聞いてみました。

## 共通化すべきか

共通化することによる悪影響はないので、共通化していいと思う。

## 共通化の方法

先にコメントした2つの方法が考えられる。

- 1の方法は（パーシャル含め）余計なファイルが増えない、処理が早そう。
- 2の方法はパーシャルが`reports`のように定義されると想定され、他のPGからも呼び出す際に中身が想定しやすい

どちらでもいいけど強いて選ぶなら1かな〜というところでした。ご参考までに。

2021-12-21 07:24 UTC, unstoppa61e commented
@IkumaTadokoro 
質問タイムに入っていらっしゃるのをお見掛けしていたのですが、なんとこの件についてお聞きくださったとは…！（「ikuma-t さんでも質問があるんだな…！」と思っておりました😅 ）
ぜひ共通化したいと思っていましたので、指針がはっきりして、とても助かりました！　ありがとうございました！🙏

2021-12-22 04:10 UTC, unstoppa61e commented
@IkumaTadokoro 
お教え頂いた方法で実装できました。
改めて、ありがとうございました！

@komagata 
こちらのレビュー、どうぞお願い致します🙏

2021-12-22 12:51 UTC, komagata commented on app/controllers/api/current_user/reports_controller.rb
> +  def index
既存の日報のAPIがあればそれにuser_idで絞り込めるようにすれば１つで行けるかもと思いました〜

2021-12-23 02:24 UTC, unstoppa61e commented on app/controllers/api/current_user/reports_controller.rb
> +  def index
@komagata 
レビュー、ありがとうございます！
アドバイスをくださった内容ですが、どのようにすれば実現できるかが分かりませんでした。
「１つで行けるかも」というのは、こちらのコントローラーを削除し、ルーティングで既存のコントローラーに通せば良いという意味でしょうか？
すみませんが、もう少し手順をお教え頂いてもよろしいでしょうか？🙏

2021-12-25 02:09 UTC, komagata requested changes

2021-12-25 02:09 UTC, komagata commented on app/controllers/api/current_user/reports_controller.rb
> +  def index
@unstoppa61e 既存の日報APIに機能追加（user_idで絞り込む機能）すれば、こちらのAPIは不要になるかもという意味です〜

実装の詳細については考えてみてください〜

2021-12-25 06:24 UTC, unstoppa61e commented on app/controllers/api/current_user/reports_controller.rb
> +  def index
@komagata 
お返事、ありがとうございました。
ご指示頂いた通り、こちらの API を削除し、既存の API に一本化することができました。
ご確認のほど、お願い致します。

2021-12-26 06:40 UTC, komagata commented
@unstoppa61e Mergeコミットができているようなので見直してみてください〜

2022-01-04 08:38 UTC, unstoppa61e commented
@komagata 
おかげさまで、マージコミットを解消できました。ありがとうございました。
こちらのレビュー、どうぞお願い致します🙏

2022-01-05 05:23 UTC, komagata commented
`/api/reports.json?user_id=1234`みたいな感じがいいかもです〜。

`?current_user=true`というのはなるべく避けたいのと（特に文字列としてのtrue）、汎用的にしたいからです〜

2022-01-13 02:39 UTC, unstoppa61e commented
@komagata 
ご指摘頂きました点を修正致しましたので、改めてのレビューのほど、どうぞお願い致します🙏
なお、修正点の概要は次の通りです。
1. クエリパラメータの汎用化（`current_user=true`→`user_id=XXXX`）
1. `app/javascript/user-recent-reports.vue`を削除し、API を一本化（質問タイムにてご提案頂いた部分です）

2022-01-14 03:49 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-14 03:49 UTC, merged