提出物・日報のユーザーメモタブにユーザー情報2種類を表示
fjordllc/bootcamp pull request #3821
Opened 2021-12-20 15:41 UTC by Paru871

ref:[#3741](https://github.com/fjordllc/bootcamp/issues/3741)

## 概要
メンターでログインした時だけ見れる提出物・日報のユーザーメモタブにユーザー非公開情報・公開情報の２種類を表示させる

## 修正前
![スクリーンショット 2021-12-21 0 19 36](https://user-images.githubusercontent.com/82434093/146793546-b99d393f-728b-43be-bb6f-6395a3fd61d4.png)
![スクリーンショット 2021-12-21 0 19 52](https://user-images.githubusercontent.com/82434093/146793565-aa5c98db-aa78-442c-847c-3538db770479.png)
## 修正後
![スクリーンショット 2021-12-20 23 10 46](https://user-images.githubusercontent.com/82434093/146793613-85e8d7a5-93d8-4de9-a22a-316e3d28156a.png)
![スクリーンショット 2021-12-20 23 10 26](https://user-images.githubusercontent.com/82434093/146793628-acbde27c-10a9-4eae-898e-8141fec71ab9.png)
とりあえず必要な２種類の一覧を表示させています。

2021-12-20 15:59 UTC, Paru871 commented
@machida 町田さん、お疲れさまです。
お手隙の際にデザインをお願いいたします🙇‍♀️

2021-12-21 01:57 UTC, machida commented
@Paru871 了解ですー🙋‍♂️

2022-01-04 06:30 UTC, machida commented
@Paru871 すいません、遅くなりました🙇‍♂️ デザイン入れましたー

2022-01-04 11:59 UTC, Paru871 commented
> @Paru871 すいません、遅くなりました🙇‍♂️ デザイン入れましたー

@machida 
年末年始のお忙しいなか、ありがとうございましたー。
上記のスクリーンショットでデザインしていただいたとおり表示されていますでしょうか？
このあと、メンバーさんへのレビュー依頼に進みます。
引き続きがんばります💪

2022-01-04 12:08 UTC, Paru871 commented
@napple29 さん、お疲れさまです。
お手数をおかけしますが、お手隙の際にレビューをよろしくお願いいたします🙏🙇🏻‍♀️

2022-01-04 13:37 UTC, Paru871 commented
@napple29 
お忙しいなか早速にご確認くださりありがとうございました🙏

@komagata 
チームメンバーのレビューで確認をいただきました。
お手すきの際にレビューをよろしくお願いいたします🙇‍♀️

2022-01-05 05:25 UTC, komagata requested changes
conflictの修正お願いします〜

2022-01-06 01:58 UTC, Paru871 commented
@machidaさん、お疲れさまです。
現在、ローカル環境のディレクトリを作り直して、今回行っていただいたデザイン変更の部分をFile Changedのページを見ながら手入力で変更して、本来の動きと表示を見ようとしています。
その際に、今回対象の「ユーザーメモ」タブではなく、提出物の「プラクティスメモ」タブに何も表示されなくなっていることに気づきました。
## mainでの表示
![スクリーンショット 2022-01-06 10 39 37](https://user-images.githubusercontent.com/82434093/148314973-47578f74-0e58-4fb6-8b1d-70b140725c72.png)
## 今回の変更を適用後の表示
![スクリーンショット 2022-01-06 10 37 30](https://user-images.githubusercontent.com/82434093/148315007-cb3b5814-feed-492a-b138-76ed9bfd6969.png)
こちら、町田さんの環境ではいかがでしょうか。
お時間のあるときにご確認お願いできますでしょうか🙏
よろしくお願いします🙇🏻‍♀️

※作り直したテスト用のブランチではその他は特に問題はないようですので、あとはコンフリクトが解消できればうまくいくのではないかなと思っています。

2022-01-06 06:14 UTC, Paru871 commented
@napple29 さん、お疲れさまです。
approveをいただいたあとで大変申し訳ありませんが、デザイン部分とテストに修正を加えたのとコンフリクトを修正したため、お手すきの際に再度ご確認をお願いできますでしょうか。よろしくお願いします🙇🏻‍♀️🙏

2022-01-06 06:35 UTC, napple29 commented
@Paru871 
コンフリクト解消お疲れ様でした✨私の方でもローカル環境での動作とテストを確認しました。
OKだと思います！

2022-01-06 06:52 UTC, Paru871 commented
@napple29 
早速再レビューしてくださってありがとうございました🙏
何度もお手数をおかけして申し訳ありませんでした。

@komagata 
コンフリクトの解消とテストOK,チームメンバーの再レビューが終わりました。
お手すきの際に再度レビューをよろしくお願いいたします🙇🏻‍♀️

2022-01-08 03:10 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-08 03:10 UTC, merged