就職希望者にのみ就職イベントを表示
fjordllc/bootcamp pull request #3858
Opened 2021-12-24 04:38 UTC by taka61

途中です

2021-12-24 04:41 UTC, taka61 commented on app/controllers/home_controller.rb
> -        @announcements = Announcement.with_avatar
`index` メソッドの中が20行を超え、Rubocopより`too many lines`の指摘があったため、`10`-`13`行を1行にまとめています。

2021-12-24 05:02 UTC, taka61 commented
@naomichi-h  さん
お手数ですが、お時間のある際にこちらのレビューをお願いします!🙏

2022-01-04 05:39 UTC, naomichi-h commented
@taka61 新年あけましておめでとうございます☀️
おまたせしました！基本的にLGTMです！
本当にこまかいところだけコメントしたので、確認をお願いいたします！

2022-01-04 05:40 UTC, naomichi-h commented on app/controllers/home_controller.rb
> +        @events_except_job_hunting_coming_soon = @events_coming_soon.where.not(job_hunting: true)
変数名が、`events_coming_soon_except_job_hunting`の方が、意味を取りやすいかな？と思ったのですが、いかがでしょう？(ちなみにgoogle翻訳で「就活を除くもうすぐ始まるイベント」を英語翻訳すると、「Events that will start soon except job hunting」となります)

2022-01-05 04:46 UTC, taka61 commented on app/controllers/home_controller.rb
> +        @events_except_job_hunting_coming_soon = @events_coming_soon.where.not(job_hunting: true)
確認頂きありがとうございます🙏
変数名は`events_coming_soon_except_job_hunting`の方が明確で分かりやすいですね！

>(ちなみにgoogle翻訳で「就活を除くもうすぐ始まるイベント」を英語翻訳すると、「Events that will start soon except job hunting」となります)

関係代名詞の`that`を使用した変数名をあまり見たことがないので、ご提案頂いた`events_coming_soon_except_job_hunting`の方を使わせて頂きたいと思います〜😀

お手数ですが再度ご確認の程、よろしくお願いします。

2022-01-05 11:01 UTC, naomichi-h commented
@taka61 確認しましたー！okです！

2022-01-06 00:26 UTC, taka61 commented
@naomichi-hさん
再度確認・レビュー頂きありがとうございました〜😀🙏

@komagata さん
チームメンバーのレビューを通過しましたので、お時間ある際にこちらのレビューをお願いします!

2022-01-08 03:06 UTC, komagata requested changes

2022-01-08 03:06 UTC, komagata commented on app/controllers/home_controller.rb
> -        @announcements = Announcement.with_avatar
@taka61 controllerの１メソッドの複雑度が高いことが根本的な問題点なので、controllerの別メソッドにまとめるか、別のモデルに設計し直したいですね。

2022-01-08 07:43 UTC, taka61 commented
@komagata さん
ご確認頂きありがとうございます!
ダッシュボードでのイベント表示に関わる部分を`display_events_on_dashboard`でメソッド化しまとめました。
修正いたしましたので、再度ご確認をお願いします!🙏

2022-01-09 01:18 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-09 01:18 UTC, merged