相談部屋にコメント機能をつける
fjordllc/bootcamp pull request #3875
Opened 2021-12-26 07:33 UTC by mami-inuzuka

issue： #3504 

# 要件
* 相談部屋でコメントをできるようにする
* 相談部屋でコメントがあった場合に通知をする
    * ユーザー：自分以外の人が自分の相談部屋でコメントをしたら通知が飛ぶ。
    * 管理者：自分以外の人がどこかの相談部屋でコメントをしたら通知が飛ぶ。
* ユーザーページのコメント一覧には相談部屋でのコメントを表示しない

# UI

# 確認手順
## 準備
* `feature/add-comment-function-to-talk-room`ブランチを手元に持ってくる

## ユーザーがコメントした場合
1. `kimura`でログインする
1. `http://localhost:3000/talks/1054575302`にアクセスする（グローバルナビゲーションの相談タブをクリックでもOK）
1. コメントをする
1. `komagata`でログインする
1. 通知が来ていることを確認

## 管理者がコメントした場合
1. `komagata`でログインする
1. `http://localhost:3000/talks/1054575302`にアクセスする
1. コメントをする
1. `kimura`でログインする
1. 通知が来ていることを確認

2021-12-28 02:59 UTC, mami-inuzuka commented
@napple29 こちらお手数ですがレビューをよろしくお願いいたします🙇🏻‍♂️
年末年始でお休みされているかと思いますので年明けで大丈夫です！
よろしくお願いします。

2021-12-28 06:35 UTC, napple29 commented
@mami-inuzuka 
お疲れ様です！レビュー依頼ありがとうございます。
示していただいた確認手順通りに作業を行ったのですが、
>ユーザーがコメントした場合
kimuraでログインする

の段階で
![image](https://user-images.githubusercontent.com/82350582/147535808-5de90de8-7749-45c5-b231-2d5502ff1942.png)

2021-12-28 06:40 UTC, mami-inuzuka commented
@napple29 すみません！！おそらく前回のissueで作成したデータマイグレーションファイル実行する必要がありそうです🙇🏻‍♂️
下記を実行した上で再度同じ操作をしてみていただけますでしょうか...?🙇🏻‍♂️
`rake data:migrate:up VERSION=20211213092226`

2021-12-28 06:43 UTC, napple29 commented
@mami-inuzuka 
ありがとうございます！できました🥲✨
レビューしますので少々お待ちください🙇🏻‍♀️

2021-12-28 06:44 UTC, mami-inuzuka commented
@napple29 よかったです>< 指示が漏れており大変失礼しました🙇🏻‍♂️！！
今日はこの後作業ができそうになく、レビューは急ぎませんのでお手隙でよろしくお願いいたします😊🙏

2021-12-28 07:41 UTC, napple29 commented
@mami-inuzuka 
確認しました！新機能の作成本当にお疲れ様です🙏🏻
実装内容は問題ないと思いました✨

一点提案ですが、通知の際に相談部屋へのコメントとわかるように「〜さんから相談部屋にコメントが届きました。」等とした方が良いかなと思いました！

2021-12-28 07:50 UTC, mami-inuzuka commented
@napple29 
早速レビューしていただきありがとうございます🙇🏻‍♂️
そしてご提案もありがとうございます✨
コメントの件は私も気になりまちださんと駒形さんにご相談したのですが、今回のissueでは対応せず、別issueで対応することになりました😊🙏（ [会話はこちらです](https://github.com/fjordllc/bootcamp/issues/3504#issuecomment-1001105856) ) 

なのでもし今後アサインされることがありましたらその際はよろしくお願いします😊笑！

2021-12-28 07:55 UTC, napple29 approved these changes
そうだったのですね！すみません、見逃してました😢🙏🏻
はい、もしそうなったらお待ちしてます！✨私からはLGTMです🙆🏻‍♀️

2021-12-28 07:56 UTC, mami-inuzuka commented
@napple29 いえいえとんでもないです！！！レビューありがとうございました✨😊

2021-12-28 07:57 UTC, mami-inuzuka commented
@komagata こちらチームメンバーのレビューを通りましたのでレビューよろしくお願いします😊（お休み明けで大丈夫です！）

2021-12-29 05:51 UTC, komagata requested changes

2021-12-29 05:51 UTC, komagata commented on test/system/notification/talk_test.rb
> +    page.all('.a-form-tabs__tab.js-tabs__tab')[1].click
```suggestion
    all('.a-form-tabs__tab.js-tabs__tab')[1].click
```

2021-12-29 07:21 UTC, mami-inuzuka commented on test/system/notification/talk_test.rb
> +    page.all('.a-form-tabs__tab.js-tabs__tab')[1].click
@komagata 改めてCapybaraのメソッドを調べてみており、要素を見つけたい時は `page.all('selector')` とすると理解したのですがこちらのコードの変更提案は「pageは省略できるから省略してね」ということでしょうか？💡（参考：https://rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FFinders:all）

調べてみたのですがいまいち情報が見つからなかったため教えていただけると嬉しいです🙇🏻‍♂️

2021-12-31 04:35 UTC, komagata commented on test/system/notification/talk_test.rb
> +    page.all('.a-form-tabs__tab.js-tabs__tab')[1].click
@mami-inuzuka 

> 「pageは省略できるから省略してね」ということでしょうか？💡

はい。

他にもいろんなメソッドで（firstとかfindとか）pageは省略できるので特に強調する意図がなければ外した方が良いと思います〜

2021-12-31 04:43 UTC, mami-inuzuka commented on test/system/notification/talk_test.rb
> +    page.all('.a-form-tabs__tab.js-tabs__tab')[1].click
@komagata なるほど、承知しました！！🙆‍♀️
修正しましたのでご確認よろしくお願いいたします。

2021-12-31 05:16 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-31 05:16 UTC, merged

2021-12-31 05:18 UTC, mami-inuzuka commented
レビューありがとうございました😊✨