Markdown で チェックリストを作成する
fjordllc/bootcamp pull request #3882
Opened 2021-12-28 08:11 UTC by vinhactindi

Issue #1400

2022-01-01 08:05 UTC, sinsoku commented on app/controllers/api/markdown_tasks_controller.rb
> +    taskable = taskable_type.camelcase.constantize.find(taskable_id)
taskable_type はコードを読む限り `Announcement`, `Page`, `Report` の3つしか入らないので、camelcase メソッドを使う必要がないような気がしました。
もし無くても問題ないなら、使わない方が良いかなと思います。

```ruby
taskable = taskable_type.constantize.find(taskable_id)
```

あと、ユーザーは `params` に任意の値を使うことが可能なので、この値を `constantize` するのは少し危険です。
念の為、値を検証するコードを書いておくと安全です。

```ruby
raise BadRequest unless %w(Announcement Page Report).include?(taskable_type)
```

## 具体的な攻撃方法

ブラウザの開発者コンソールで `/api/markdown_tasks.json?taskable_type=${type}` の通信は簡単に分かる。
この `type` の部分を任意のクラス名（例えば Admin）に書き換えると、そのクラスの `find` を実行できてしまう。

```
taskable_type = params[:taskable_type] # 攻撃者が "Admin" を入れる
taskable = taskable_type.camelcase.constantize.find(taskable_id) # Admin.find(taskable_id) と同じ
```

この例だと NotFound のエラーになるだけで済みますが、こんな感じで任意のクラスのfindを呼べるので危ないです。
bootcampの利用者に攻撃する人はいないとは思いますが、コードは堅牢に書いておくべきだと思うのでコメントしておきます。

2022-01-04 08:00 UTC, vinhactindi commented on app/controllers/api/markdown_tasks_controller.rb
> +    taskable = taskable_type.camelcase.constantize.find(taskable_id)
@sinsoku 
明けましておめでとうございます！ご確認ありがとうございます。✨
なるほどですね。以上のようなコードに修正しましたので、`constantize` のメソッドはそのままでいいでしょうね！

```ruby
raise ActionController::BadRequest.new, 'Unsupported taskable type' unless %w[Announcement Answer Comment Page Report].include?(taskable_type)
```

2022-01-04 09:02 UTC, sinsoku commented on app/controllers/api/markdown_tasks_controller.rb
> +    taskable = taskable_type.camelcase.constantize.find(taskable_id)
unlessでチェックしているので `constantize` はそのままで良さそうです。

あと、クラス名がそのまま入ってそうなので `camelcase` は要らなそうです。

```diff
- taskable = taskable_type.camelcase.constantize.find(taskable_id)
+ taskable = taskable_type.constantize.find(taskable_id)
```

2022-01-04 09:32 UTC, vinhactindi commented on app/controllers/api/markdown_tasks_controller.rb
> +    taskable = taskable_type.camelcase.constantize.find(taskable_id)
@sinsoku 
ありがとうございます！修正しましたので、再度ご確認お願いいたします。🙇‍♂️

2022-01-04 10:48 UTC, sinsoku commented on app/controllers/api/markdown_tasks_controller.rb
> +    taskable = taskable_type.camelcase.constantize.find(taskable_id)
良さそうです！

2022-01-04 13:23 UTC, vinhactindi commented
@sinsoku 
ご確認ありがとうございます！🙏

@komagata 
明けましておめでとうございます！
sinsokuさんに確認されましたが、レビューするには別のメンバーが必要ですか？

2022-01-05 03:25 UTC, vinhactindi commented
@unstoppa61e さん
明けましておめでとうございます！
お手数ですが、お時間のある時にこちらでレビューお願いいたします🙏

2022-01-05 03:42 UTC, unstoppa61e commented
@vinhactindi さん
明けましておめでとうございます！
僕は既にヴィンさんのレビューを一度やらせて頂いています。
- #3763 

そのため、まだ頼んだことがない方にご依頼頂いた方が、レビューの機会が広がって良いかと思いますが、いかがでしょうか？
（ご存じかもしれませんが、[プラクティスのページ](https://bootcamp.fjord.jp/courses/1/practices) の一番上に「みんなの進捗」というスイッチがあり、そちらを ON にして頂くと、「開発に参加して PR を送りマージする」プラクティスに取り組んでいるメンバーが表示されるようになります。）

2022-01-05 03:53 UTC, vinhactindi commented
@unstoppa61e さん
なるほど、指摘ありがとうございます！別の方に聞いてみたいと思います　🙇‍♂️

2022-01-05 03:57 UTC, vinhactindi commented
@mami-inuzuka さん
明けましておめでとうございます！ヴィンと申します。
お手数ですが、お時間のある時にこちらでレビューお願いいたします✨

2022-01-07 02:06 UTC, mami-inuzuka requested changes
@vinhactindi  お疲れ様です！犬塚と申します😊

実装方法非常に勉強になりました🙇🏻‍♂️！！
一点だけ誤字をコメントしてありますので修正よろしくお願いいたします🙏😊

2022-01-07 02:06 UTC, mami-inuzuka commented on app/javascript/markdown-it-task-lists-initializer.js
> +          title: 'チェクボクスを変更しました！',
チェクボクス  → チェックボックス
に修正をお願いします😊🙏

2022-01-07 08:44 UTC, vinhactindi commented
@mami-inuzuka 
ご指摘ありがとうございます！✨
なるほど、チェックボックスですね。以前から「チェクボクス」と思います。
再度ご確認お願いいたします🙏

2022-01-07 08:46 UTC, mami-inuzuka approved these changes
@vinhactindi 確認しました！LGTMです🎉

2022-01-07 09:05 UTC, vinhactindi commented
@mami-inuzuka 
ご確認ありがとうございます！🙇‍♂️

@komagata 
犬塚さんに確認されましたので、
お手数ですが、時間のあるの時こちらでレビューお願いいたします！🙏

2022-01-08 03:22 UTC, komagata approved these changes
難しいIssueありがとうございます！
素晴らしいです〜！

2022-01-08 03:22 UTC, komagata commented on app/models/concerns/taskable.rb
> +  def taskable?(other_user)
👍

2022-01-08 03:22 UTC, merged