相談部屋に返信/未返信タブをつける
fjordllc/bootcamp pull request #3890
Opened 2021-12-31 08:10 UTC by mami-inuzuka

2022-01-04 09:17 UTC, mami-inuzuka commented
@taka61 明けましておめでとうございます🎍😊こちらのレビューよろしくお願いします🙏！

2022-01-06 02:40 UTC, taka61 commented
@mami-inuzuka さん
明けましておめでとうございます〜🎍

コード・動作確認できました！問題ないと思います🙆‍♀️
新機能の実装方法とても勉強になりました！

1点だけ確認なのですが、昨日のMTGでも上がっていた「管理者の場合、自分のコメントでも通知が来る」に関しては
本題の「相談部屋に返信/未返信タブをつける」からは逸れるため、また別Issueで対応ということでしょうか👀？
<img width="267" alt="スクリーンショット 2022-01-06 10 06 02" src="https://user-images.githubusercontent.com/80372144/148317445-d1b3e855-d243-46f3-bf66-2eb3b8a71883.png">

2022-01-06 05:37 UTC, mami-inuzuka commented
@taka61 早速レビューありがとうございます！！
通知周りを実装したのはひとつ前のPRだったのですが、もう既にマージされてしまっているのでこちらのPR上で対応したいなと思います！なので大変お手数なのですが、後ほど修正のコミットを行いますので追加分のみ再度レビューをいただいてもよろしいでしょうか？🙇🏻‍♂️

（仕様についてまちださんに確認したいことがあるので確認取れ次第追加実装します！）

2022-01-06 05:50 UTC, mami-inuzuka commented
@machida 
**★相談部屋の通知機能についてご相談です！**

現在、管理者が相談部屋でコメントを行った際に自分がしたコメントの通知が届くようになってしまっているため修正を行いたいと思っています。その上で仕様のご相談です。

現状の通知は下記のようになっているのですが、下記 **（★相談）** の部分をどうするのが良いか悩んでいます。

* ①とある相談部屋で相談部屋の持ち主がコメントした場合
    * → 管理者全員に通知がいく
    * → 相談部屋の持ち主には通知が行かない
* ②とある相談部屋で管理者がコメントした場合
    * → 管理者全員に通知がいく **（★相談）**
    * → 相談部屋の持ち主に通知がいく

<br>
<br>
考えられる対応としては、下記どちらかかなと思っているのですがどちらが都合良いでしょうか？

<br>

* a. 管理者がコメントをした場合、管理者には通知を送らない
* b. 管理者がコメントをした場合、**自分以外の管理者には**通知を送る

例えば駒形さんがどこかの相談部屋でコメントをしたときにまちださんはそのことを知れたほうがいいのであれば【 b 】、知れなくても問題ないのであれば【 a 】なのかなと思っていますが、どちらが良いでしょうか？

2022-01-06 05:59 UTC, machida commented
相談ありがとうございます！！
ここは一旦、何が起きているかを把握するようにしたいので、現時点では 【 b 】でお願いします🙏
今後規模が大きくなったら担当をアサインするなどの機能が必要になりそうな予感がしてたりするのですが、今の時点では b でいきたいと思いますー

2022-01-06 05:59 UTC, mami-inuzuka commented
早速ありがとうございます🙇🏻‍♂️！
承知しました！それでは【 b 】で進めさせていただきます😊

2022-01-06 06:22 UTC, mami-inuzuka commented
@taka61 
こちら（https://github.com/fjordllc/bootcamp/pull/3890#issuecomment-1006299373） でお伝えした追加実装分コミットしてpushしたので再度ご確認お願いします🙇🏻‍♂️お手数おかけしてすみません><🙏

2022-01-07 02:07 UTC, taka61 commented
@mami-inuzuka さん
通知部分に関してご確認・修正頂きありがとうございます！
変更部分確認しました〜！問題ないと思います、LGTMです🙆‍♀️

2022-01-07 02:08 UTC, taka61 approved these changes

2022-01-07 02:31 UTC, mami-inuzuka commented
@taka61 ありがとうございます！！！✨

@komagata チームメンバーのレビューを通ったのでレビューよろしくお願いします😊🙏

2022-01-08 03:13 UTC, komagata commented on app/models/comment.rb
> +  after_create Comment::AfterCreateCallbacks.new
このクラス分けの場合、callbackは一個なので`AfterCreateCallback`でいいかもです〜

2022-01-08 04:43 UTC, mami-inuzuka commented on app/models/comment.rb
> +  after_create Comment::AfterCreateCallbacks.new
@komagata 確かにそうですね🙇🏻‍♂️ご指摘ありがとうございます！修正いたしましたので再確認よろしくお願いします😊🙏

2022-01-09 01:16 UTC, komagata commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
この行ってなんで今回追加されたんでしたっけ？

2022-01-09 03:40 UTC, mami-inuzuka commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
@komagata [こちらのコミット（talksテーブルにunrepliedカラムを追加）](https://github.com/fjordllc/bootcamp/pull/3890/commits/6969d841468485907ce12a9c1bf43580f5ec6a99)で追加した行になるのですが、自動的に挿入されているものなのでなぜ追加されたのかがわからず、このコミットで変更した内容を再現してみました。

再現してみたところ、
talksテーブルにunrepliedカラムを追加するために下記の内容のマイグレーションファイルを作成し、その後`rails db:migrate` を実行した際に該当の行が追加されました。
```ruby
class AddUnrepliedToTalks < ActiveRecord::Migration[6.1]
  def change
    add_column :talks, :unreplied, :boolean, default: false, null: false
  end
end
```
`rails db:migrate` の実行で自動的に追加されたものなのでそのままコミットしてしまったのですが、なぜこの行が追加されるのかまではわかっていない状況です。

`rails db:migrate` の実行でなぜこの行が追加されるのか調査した方が良いでしょうか？（少し調べたのですが情報があまり出てこなかったため、もし調査の必要がある場合メンターの方に質問してみようかと思います🙇🏻‍♂️）

2022-01-11 07:07 UTC, mami-inuzuka commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
（質問タイムで駒形さんと会話済み）

メモ：
* `data-migrate`というgemでrake taskを実行した際に`data_migrations`テーブルが追加される
* 今回追記されたのはそれに関する記述
    * 参考：https://github.com/ilyakatz/data-migrate/issues/105
    * 参考：https://github.com/ilyakatz/data-migrate#installation
* 今回このマイグレーションファイルを実行した際になぜ該当の行が追記されたのかまではわからないが、過去に同様の実装を行った際に同じようなコードは追加されていないため今回削除して対応する

2022-01-11 07:08 UTC, mami-inuzuka commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
@komagata 質問タイムで会話させていただきましたが、該当の行を不要と判断し削除しましたのでご確認お願いいたします😊🙏

2022-01-14 04:12 UTC, komagata requested changes

2022-01-14 04:12 UTC, komagata commented on test/system/notification/talk_test.rb
> +  test '誰かが相談部屋でコメントをした際に管理者は通知を受け取る' do
すみません、できればテストのタイトルは英語で統一したい感じです。
既存のコードにいくつか日本語のテストが混入しちゃってますが、後々直していきたいと思っています。

2022-01-14 04:41 UTC, mami-inuzuka commented on test/system/notification/talk_test.rb
> +  test '誰かが相談部屋でコメントをした際に管理者は通知を受け取る' do
@komagata 承知しました！こちら英語で書き直しましたので再確認よろしくお願いします！😊

2022-01-14 06:07 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-14 06:07 UTC, merged

2022-01-14 06:31 UTC, mami-inuzuka commented
ありがとうございます✨