app/views/users/_user.html.slimの削除
fjordllc/bootcamp pull request #3917
Opened 2022-01-07 04:23 UTC by naomichi-h

issue: #3814

2022-01-07 08:02 UTC, naomichi-h commented
@unstoppa61e
こちらのレビューをお願いしてもよろしいでしょうか？🙋‍♂️
もし忙しければ、お手数ですが開発メンバーのどなたかにレビューを回して下さい！🙇🏻‍♂️

2022-01-07 08:12 UTC, unstoppa61e commented
@naomichi-h 
こんにちは！
僕は naomichi-h さんのレビューを既に一度やらせて頂いておりました。
- #3798 

もし、naomichi-h さんがまだレビューを頼んだことのない方が、現在システム開発に取り組んでいるメンバーの中にいらっしゃるのであれば、その方にご依頼頂いた方がレビューの機会が広がって良いかと思いますが、いかがでしょうか…？
もし、既に一通り頼みきったということでしたら、僕の方でやらせて頂きますので、再度お知らせくださいませ🙏

2022-01-07 08:25 UTC, naomichi-h commented
はい。すでに一通りの方に依頼をしておりますので、よろしくお願いいたします。

2022-01-08 00:24 UTC, unstoppa61e reviewed
動作確認、大丈夫でした！👍
気付いた点を数点コメントさせて頂きましたので、適宜ご参照頂ければ幸いです🙏

2022-01-08 00:24 UTC, unstoppa61e commented on db/fixtures/users.yml
> +  created_at: "2014-01-01 00:00:02"
```suggestion
<% 1.upto(22) do |i| %>
marumarushain<%= i %>:
  login_name: marumarushain<%= i %>
  email: marumarushain<%= i %>@fjord.jp
  crypted_password: $2a$10$n/xv4/1luueN6plzm2OyDezWlZFyGHjQEf4hwAW1r3k.lCm0frPK. # testtest
  salt: zW3kQ9ubsxQQtzzzs4ap
  name: marumarushain<%= i %>
  name_kana: マルマル シャイン<%= i %>
  twitter_account:
  facebook_url:
  blog_url:
  company: company1
  description: マルマル企業の社員<%= i %>
  course: course1
  job: office_worker
  os: mac
  experience: rails
  organization: 株式会社フィヨルド
  admin: true
  mentor: true
  github_collaborator: true
  unsubscribe_email_token: MnC-Dv3HrNLs7WmfE975qA
  updated_at: "2014-01-01 00:00:02"
  created_at: "2014-01-01 00:00:02"
<% end %>
```
- ループでまとめてあげた方が、可読性やメンテナンスの容易さが向上するかと思います。
- `gmail.com`のような実在するドメインは、万が一の事故を防ぐため、使用を避けた方が無難かと思いました。
- こちらのデータを追加なさった目的が分かりませんでした（ページネーションの確認でしょうか）。目的によっては、テストを作成した方が目的に適っているかもしれないと思いました（駒形さんにご確認頂くのが良いかと思います）。

2022-01-08 03:18 UTC, komagata commented on app/javascript/generation-users.vue
> +        (this.params.watch ? `&watch=${this.params.watch}` : '')
rubyではどっちでもいいかもです〜。

2022-01-08 09:17 UTC, naomichi-h commented on app/controllers/api/generations_controller.rb
> +    @users = Generation.new(@generation).users.page(params[:page]).per(PAGER_NUMBER)
ここはたしかにそうですね！ローカル変数に変更します。

2022-01-08 09:20 UTC, naomichi-h commented on app/javascript/company-users.vue
> +      .row.is-gutter-width-32(v-else-if='users.length !== 0')
削ってしまっても動作的にはかわらないのですが、`!==0`と明示的にした方が意図が読み取りやすいかと思います。好みの問題かもしれませんが...。

2022-01-08 09:21 UTC, naomichi-h commented on app/javascript/company-users.vue
> +    },
ここは、アプリ全体としての可読性と、安定性の担保を考えて、他ファイル(users.vue)のコードを流用しています。たしかに`async/await`を使って書き換えると、このファイル自体の可読性はよくなるのですが...。可読性を向上させる目的であれば、別issueを立てて、そこで類似システムを扱っているファイル全般をリファクタリングする。とやったほうがアプリ全体の可読性と安定性を保てるかなと思うのですが、いかがでしょう？

2022-01-08 09:24 UTC, naomichi-h commented on app/javascript/company-users.vue
> +          this.currentTag = json.tag
私はcurrentがついていた方が、明示的で意図がわかりやすく感じますね...。

2022-01-08 09:26 UTC, naomichi-h commented on app/javascript/generation-users.vue
> +    },
ここも同上です。もし全体の可読性や安定性の担保を考えないなら、`async/await`方式のほうが可読性は良いと私も思います。

2022-01-08 09:28 UTC, naomichi-h commented on db/fixtures/users.yml
> +  created_at: "2014-01-01 00:00:02"
- これはページネーションの確認のために追加しました。
- たしかにループでまとめるべきですね！
- たしかに必要でなければ実在するドメインはさけるべきですね...。
- テストを作成するべきか駒形さんに確認したいと思います。

2022-01-08 10:16 UTC, naomichi-h commented on db/fixtures/users.yml
> +  created_at: "2014-01-01 00:00:02"
@komagata 
お疲れ様です。
user一覧のページネーションの確認をしたいのですが、この場合、どうするべきでしょうか？

1. テストを作成し、テストで確認すべき。
2. テストは不要。seedにデータを入れて直接確認できればok(現在の実装)
3. テスト、seedともに必要
4. その他

seedにデータがあれば今後デモするときに便利なのと、他のページネーションのあるQ&Aやユーザー一覧でページネーションに関するtestをしていないことから、2.で実装しました。
見解をいただけると幸いです。よろしくお願いいたします。

2022-01-08 10:16 UTC, naomichi-h commented
@unstoppa61e 
細かく見てくださり、ありがとうございます...!ものすごい勉強になります。
返信をしましたので、再度確認をお願いします✨
もし、判断をしかねる内容であれば、駒形さんに確認しますので、その旨を書いていただければと思います。

2022-01-08 22:31 UTC, unstoppa61e commented on app/javascript/company-users.vue
> +    },
> アプリ全体としての可読性と、安定性の担保

僕個人としては、naomichi-h さんが仰るように全体との関連を考えたとしても、このファイルの可読性を上げることにはメリットしかないように感じてしまっていました。
ただ、naomichi-h さんのお考えをお聞かせくださったおかげで、違う考え方もあるのだと勉強になりました。ありがとうございます！🙏
> 別issueを立てて、そこで類似システムを扱っているファイル全般をリファクタリングする

こちらはちょうど、Issue を立てていたところでした！👍
- #3919 
- #3920

2022-01-08 22:42 UTC, unstoppa61e commented on app/javascript/company-users.vue
> +          this.currentTag = json.tag
`currentUser` 以外の `Target` `Tag` `Page` にも `current` が付いていると、`currentUser` の特別さが埋もれてしまう可能性はあるかと思います。
ただ、naomichi-h さんが仰っている通り、読み手の主観によるところだと思いますので、全然大丈夫です👍

2022-01-08 22:48 UTC, unstoppa61e approved these changes
@naomichi-h 
確認させて頂きました👍
勉強させて頂き、ありがとうございました😄

2022-01-09 01:24 UTC, komagata commented on db/fixtures/users.yml
> +  created_at: "2014-01-01 00:00:02"
@naomichi-h 

2

です〜

ただご指摘受けているようにseedはeachで書くのがいいかもです。

ページネーションのテストをする必要がなければテスト環境のfixtureはいらないです。（不要なfixtureがあるとテストが遅くなるので）

development環境のseedが欲しい理由は、デザイン確認と、よくある形にしておくことで他の開発者も含めて使い勝手の確認や不具合の発見が容易になるからです〜

2022-01-09 06:56 UTC, naomichi-h commented on app/javascript/company-users.vue
> +    },
おお、issue立てまで...！すごい...ありがとうございます！

2022-01-09 07:57 UTC, naomichi-h commented
@unstoppa61e こちらこそありがとうございました！！

@komagata こちらお手隙の際にレビューをお願いいたします🙇‍♂️

2022-01-12 12:53 UTC, komagata commented on app/controllers/api/companies/users_controller.rb
> +  TARGETS = %w[all student_and_trainee graduate adviser mentor].freeze
定数とbefore_actionの定義は同じような場所に固めて書いた方がいいかもです〜
（定数・before_action・定数のサンドイッチの順番になっていると何か意味があるのかな？と思っちゃうかもなので）

2022-01-12 12:53 UTC, komagata commented on app/views/api/generations/_user.json.jbuilder
> +json.(user, :id, :login_name, :name, :discord_account, :description, :github_account, :twitter_account, :facebook_url, :blog_url, :times_url, :job_seeker, :free, :job, :os, :experience, :email, :role
このファイルって`_user.json.jbuilder`や他のものと共通にできたりしないですかね？

2022-01-15 12:24 UTC, naomichi-h commented on app/controllers/api/companies/users_controller.rb
> +  TARGETS = %w[all student_and_trainee graduate adviser mentor].freeze
before_action、定数の順に固めて書き直しました！

2022-01-15 12:30 UTC, naomichi-h commented on app/views/api/generations/_user.json.jbuilder
> +json.(user, :id, :login_name, :name, :discord_account, :description, :github_account, :twitter_account, :facebook_url, :blog_url, :times_url, :job_seeker, :free, :job, :os, :experience, :email, :role
`app/views/api/generations/_user.json.jbuilder`と`app/views/api/companies/_user.json.jbuilder`を`app/views/api/users/_list_user.json.jbuilder`と共通にしました！

2022-01-15 12:31 UTC, naomichi-h commented
@komagata ご指摘いただいた箇所の修正を行いましたので、確認をお願いいたします🙏

2022-01-17 09:15 UTC, komagata commented on app/javascript/company-users.vue
> +    window.onpopstate = function () {
Arrow Functionの方がいいかも？

2022-01-17 10:11 UTC, naomichi-h commented on app/javascript/company-users.vue
> +    window.onpopstate = function () {
見落としていました😓修正します！

https://github.com/fjordllc/bootcamp/blob/8b08111919265b4b465b62d3c45d637483cf8e0c/app/javascript/generation-users.vue#L74
も同様の箇所がありましたので、こちらも修正します！

2022-01-17 10:47 UTC, naomichi-h commented
@komagata コメントいただいた箇所の修正を行いましたので、確認をお願いいたします🙏

2022-01-18 04:50 UTC, komagata commented on app/javascript/generation-users.vue
> +import User from './user.vue'
ちょっと試してないんですが、下記だと動かなかったりしますかね？

```suggestion
import User from 'user.vue'
```

2022-01-18 07:50 UTC, naomichi-h commented on app/javascript/generation-users.vue
> +import User from './user.vue'
試してみたところ、`./`無しでも問題なく動きました。(`.vue`ファイルだけでなく`.js`ファイルも)
本PRで変更したファイルから不要な`./`を削除してpushしました。

一つ質問なのですが、こういう動作には不要な`./`はpathに含めないほうが良かったりするのでしょうか？
少し調べてみた感じだと、「プロジェクトに依る」という意見が多かったので...。

もし動作に不要な`./`は含めない方が良いのであれば、別issueを立てて対応しようと思います。

2022-01-18 07:51 UTC, naomichi-h commented
@komagata コメントいただいた箇所に返信しましたので、確認をお願いいたします🙏

2022-01-18 14:23 UTC, komagata commented on app/javascript/generation-users.vue
> +import User from './user.vue'
@naomichi-h 不要なのでつけなくて大丈夫です。
今回の変更した行については`./`つけないようにして、今回触ってない行について別Issueを立てていただければありがたいです〜

2022-01-19 04:13 UTC, naomichi-h commented on app/javascript/generation-users.vue
> +import User from './user.vue'
@komagata 不要な`./`についてのissue立てました！https://github.com/fjordllc/bootcamp/issues/3997
今回変更した行について、`./`をつけないように修正しましたので、確認をよろしくお願いいたします🙏

2022-01-24 04:49 UTC, komagata reviewed
conflictの修正お願いします〜

2022-01-27 03:16 UTC, naomichi-h commented
@komagata conflictの修正完了いたしました。確認よろしくお願いいたします🙏

2022-01-29 04:13 UTC, komagata requested changes

2022-01-29 04:13 UTC, komagata commented on app/controllers/api/companies/users_controller.rb
> +# frozen_string_literal: true
UserのAPIに企業で絞り込む機能を追加する形の方が良いかもです。

`/api/users.json?company_id=1234`みたいな形。

2022-01-29 14:35 UTC, naomichi-h commented on app/controllers/api/companies/users_controller.rb
> +# frozen_string_literal: true
UserのAPIに企業で絞り込む機能を追加する形に変更しました！

少し`api/users_controller.rb`をいじったのですが、意図は以下の通りです。
`api/users_controller.rb:31`：企業のユーザー一覧のみ、retiredがtrueのユーザー(研修が終わっているユーザー)も表示されるようにするため。
`api/users_controller.rb:49`：企業のユーザー一覧のみ、一般ユーザーでもtarget=allを有効にするため。

これらの仕様は`system/company/users_test.rb`に倣っています。

2022-01-29 14:36 UTC, naomichi-h commented
@komagata ご提案いただいた方針で修正し、コメントしましたので、ご確認お願いいたします🙏

2022-01-31 15:19 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-31 15:19 UTC, merged

2022-01-31 18:07 UTC, naomichi-h commented
@komagata ありがとうございますー！！