タグ登録時、先頭のシャープないしハッシュ記号を無視するようにした
fjordllc/bootcamp pull request #3921
Opened 2022-01-08 02:21 UTC by unstoppa61e

## issue
- #3202 
## 概要
- タグ名の入力時、ハッシュタグ類（`#`/`＃`/`♯`）で始まっている場合には、その記号が無視される旨を表示するようにしました。
- そのままの状態でタグ名が確定された場合、該当文字を取り除いた状態でタグが登録されるようにしました。

## 動作確認の手順
1. 任意のユーザーでログイン
1. 自分のプロフィール画面へ移動
1. 「タグ編集」をクリック
1. ハッシュタグ類を先頭に入力した場合（例：`#test`）、入力ボックスの真下に「先頭の記号は無視されます」という文言が表示されることを確認
1. エンターキーを押下すると、ハッシュタグ類が取り除かれた状態でタグ名が確定されていることを確認
1. ハッシュタグ類１文字のみ（例：`#`）を入力し、エンターキーを押下
1. 今度は何も登録されないことを確認
## スクリーンショット
![スクリーンショット 2022-01-08 11 19 32](https://user-images.githubusercontent.com/46347198/148627929-5313cf22-f18f-4d4d-a3c7-8261e45a62a5.png)

2022-01-08 04:38 UTC, unstoppa61e commented
@napple29 
こんにちは！
こちらのレビューをお願いしたいです。
どうぞよろしくお願いします🙏

2022-01-08 05:20 UTC, napple29 reviewed
確認しました！実装方法とても勉強になりました✨

一点仕様の面で気になることがありました。ユーザーが新規で参加登録するときや、登録情報の変更をするときもタグを編集すると思うのですが、その場合にもいわゆるハッシュタグ様の記号が入力された場合に「先頭の記号は無視されます」の文言が表示されても良いのかなと思いました。その他の動作はOKでした！

また、先ほど私の早とちりで一点コメントしてしまったのですが、自己解決しました🙏🏻通知が入ってしまっていたらすみません、、🙇🏻‍♀️

2022-01-08 08:33 UTC, unstoppa61e commented
@napple29 
ご指摘頂いた点、見逃してしまっていたため、とても助かりました。ありがとうございます🙏
参加登録 / 登録情報変更 / Q&Aでの質問作成、それぞれでも同様の文言が表示されるように変更しました。
ちなみに、記述の重複を避けたかったのですが、タグ登録のロジックがプロフィール画面とその他とで異なるようで、できませんでした。
改めてのご確認のほど、どうぞお願い致します🙏

2022-01-08 12:18 UTC, napple29 approved these changes
確認しました！修正していただきありがとうございます🙆🏻‍♀️
私からはOKです✨

2022-01-08 22:55 UTC, unstoppa61e commented
@napple29 
改めてのご確認、ありがとうございました🙏

@komagata 
こちらのご確認、どうぞお願い致します🙏
（デザインは machida さんがやってくださるとのことです）

2022-01-09 01:26 UTC, komagata requested changes

2022-01-09 01:26 UTC, komagata commented on app/javascript/tags-input.vue
> +    tagNameHeadIsSharpOrOctothorpe() {
これ重複してるのでmixinにした方がいいかもです〜

2022-01-10 01:43 UTC, unstoppa61e commented
@komagata 
こういう場合の共通化にはmixinを使えば良いのだと知り、勉強になりました。
お教えくださりありがとうございました🙏
修正させて頂きましたので、改めてのご確認、どうぞお願い致します。

2022-01-14 03:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-14 04:08 UTC, merged