プラクティスページ表示時に着手中プラクティスがない場合、最上段の未着手プラクティスのカテゴリーを表示する
fjordllc/bootcamp pull request #3924
Opened 2022-01-08 13:49 UTC by Paru871

ref: [プラクティス一覧ページにて、着手中のプラクティスがない場合、次に手を付けるべきプラクティスのカテゴリーが自動で表示されない · Issue \#3783](https://github.com/fjordllc/bootcamp/issues/3783)

## 概要
- プラクティスページを開いた際にどのカテゴリーを自動的に表示するかを変更します。
- 現在は着手中プラクティスの所属カテゴリーを表示する設定のみで、「着手中」が「提出」や「完了」に変わるとページの最上段が表示されています。
- 今回、着手中プラクティスがない場合は「最上段の未着手のプラクティス」が所属するカテゴリーまでスクロールしてから表示されるように変更しました。

## 変更前
プラクティスページ表示時、着手中がない場合は「ページの最上段」が表示される
![スクリーンショット 2022-01-08 22 31 47](https://user-images.githubusercontent.com/82434093/148646608-4cb3d232-eecc-4766-9ef8-03e8867c2b0d.png)

## 変更後
プラクティスページ表示時、「最上段の未着手のプラクティスが所属するカテゴリー」までスクロールして表示
![スクリーンショット 2022-01-08 22 32 08](https://user-images.githubusercontent.com/82434093/148646620-2db778c9-925d-4c56-bf0d-9868987c5031.png)

2022-01-08 14:33 UTC, Paru871 commented
@R-Tsukada 
お疲れさまです。お手すきの際にレビューをよろしくお願いいたします🙏🙇🏻‍♀️✨

2022-01-09 12:53 UTC, R-Tsukada reviewed
確認しました！LGTMだと思います🎉

2022-01-09 13:33 UTC, Paru871 commented
@R-Tsukada 
早速にレビューいただきありがとうございました！
（レビューをapproveにしていただけますと助かります～🙏😊)

2022-01-09 13:34 UTC, Paru871 commented
@komagata 
チームメンバーのレビューのOKをいただきましたので、お手すきの際にレビューをお願いいたします🙏🙇‍♀️

2022-01-09 13:36 UTC, R-Tsukada approved these changes

2022-01-14 03:44 UTC, komagata commented on app/helpers/layout_helper.rb
> +  def category_having_unstarted_practice
current_userを前提としているならmodelのメソッドでいいかもです。
もしくは、Viewでしか使わないようなものならdecoratorでもいいかもです。

2022-01-14 03:47 UTC, komagata commented
lint実行など、同じようなコミットログが続いているところがあるので、後から見た人がわかりやすい粒度のコミットにまとめると良いと思います〜。

[【初心者向け】「コミットの粒度がわからない問題」の模範解答を考えてみた - Qiita](https://qiita.com/jnchito/items/40e0c7d32fde352607be)

2022-01-14 05:06 UTC, Paru871 commented on app/helpers/layout_helper.rb
> +  def category_having_unstarted_practice
@komagata 
ありがとうございます！
記述する場所を迷ったのですが、active_practiceの記述にならって書いてみました。
今回のアドバイスを受けてUserモデルに移動しました。(active_practiceも一緒に移動しました)

2022-01-14 05:08 UTC, Paru871 commented
@komagata 
レビューいただきありがとうございました。
コミットの粒度についても勉強になりました。リベースを行って同じようなコミットをまとめました。
お手数ですが、再度レビューをよろしくお願いします🙇🏻‍♀️

2022-01-14 06:08 UTC, komagata requested changes

2022-01-14 06:08 UTC, komagata commented on app/models/user.rb
> +  def unstarted_practices
modelのメソッドは対応するテストが欲しいっすね

2022-01-15 10:16 UTC, Paru871 commented on app/models/user.rb
> +  def unstarted_practices
@komagata 
modelにメソッドを書いたらテストが必要なのを忘れていました！大変失礼しました🙇🏻‍♀️
テストを追加するのと同時にコードの見直しも行いました。
再度チェックをお願いいたします🙏

2022-01-17 09:05 UTC, komagata requested changes

2022-01-17 09:05 UTC, komagata commented on app/models/user.rb
> +    active_practices.first.categories.first
active_practiesが0個だったときにエラーが出ちゃうかも？

2022-01-17 09:05 UTC, komagata commented on app/models/user.rb
> +  def category_having_unstarted_practice
こちらも`unstarted_practices`が0この場合エラーが出ちゃうかもです〜

2022-01-17 12:17 UTC, Paru871 commented on app/models/user.rb
> +    active_practices.first.categories.first
@komagata 
丁寧に見てくださってありがとうございます🙏
active_practicesがあるとき(0ではないとき)にこのメソッドが呼ばれますのでエラーは出ないと思います。
しかし、1行しかないメソッドで読みにくいため修正を行いました。

2022-01-17 12:18 UTC, Paru871 commented on app/models/user.rb
> +  def category_having_unstarted_practice
@komagata 
丁寧に見てくださってありがとうございます🙏
こちらも同じく、`unstarted_practices`があるとき(0ではないとき)にこのメソッドが呼ばれますのでエラーは出ないと思います。
しかし、1行しかないメソッドで読みにくいため修正を行いました。

2022-01-17 12:23 UTC, Paru871 commented
@komagata 
お忙しいなか何度もお手数をおかけして申し訳ありません🙇🏻‍♀️
再度レビューをお願いいたします！

2022-01-18 04:54 UTC, komagata commented on app/models/user.rb
> +    active_practices.first.categories.first
@Paru871 それは今回のシチュエーションでは`active_practices`あるときに呼ばれるからという意味ですかね？
だとすると、メソッドを一度作ったら今後いろんな人が利用することになるので、いろんなシチュエーションで使われることを考えて作るのがいいと思います。今回の場合でしたら、そう言った場合にはエラーを発生させるのではなく`nil`を返すのがいいと思います。（`category_having_active_practice`という名前のものが指すものが無いという感じなので）

2022-01-18 10:56 UTC, Paru871 commented
@komagata 
質問タイムで教えていただいたことを反映させて修正を行いました。
お忙しいなか申し訳ございませんが再度チェックいただきたく、よろしくお願いいたします！

2022-01-18 14:26 UTC, komagata requested changes

2022-01-18 14:26 UTC, komagata commented on app/models/user.rb
> +  def category_having_unstarted_practice
@Paru871 この状態だと`active_practice`がnilの時に

「`categories`というメソッドが見つからない」

というエラーが出るように思います〜
試してみていただけるとわかるかもです。

2022-01-19 03:31 UTC, Paru871 commented
@komagata 
何度も同じことを教えていただいてしまい申し訳ありません🙇🏻‍♀️
自分でも試してみましたら書いていただいた通りのエラーが出ました。
rubocopの指摘を間違って受け取っていたようでしたので、再度1行に戻してぼっち演算子を付加しました。
よろしくお願いいたします🙏

2022-01-21 07:54 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-21 15:11 UTC, Paru871 commented
@komagata 
何度も教えていただきありがとうございました🙏大変勉強になりましたー🙇🏻‍♀️

2022-01-24 04:57 UTC, merged