イベントのコピーが行われるよう修正
fjordllc/bootcamp pull request #3976
Opened 2022-01-14 13:42 UTC by napple29

#3879 

すでに存在するイベントページにて、「コピー」ボタンを押してもイベントがコピーされないバグを修正しました

2022-01-15 11:48 UTC, napple29 commented
@ot0m1 
お疲れ様です！お時間のある時にこちらのレビューをお願いしたいです！
よろしくお願いします🙇🏻‍♀️

2022-01-15 13:45 UTC, ot0m1 reviewed
@napple29
LGTMです！

なるほどイベントの作成もコピーも同じく`new`で行われるわけなんですね〜。

2022-01-16 05:39 UTC, napple29 commented
@ot0m1 
ありがとうございます〜！
そうなんです、私もこのIssueで初めて知りました🤔！

@komagata 
チームメンバーのレビューを追加したので、レビューをお願いします🙇🏻‍♀️

2022-01-17 09:19 UTC, komagata commented on app/controllers/events_controller.rb
> +    flash.now[:notice] = 'イベントをコピーしました。'
これをメソッドにしてやりたいことの名前をつけると分かりやすくなるかもです〜

2022-01-18 00:39 UTC, napple29 commented
@komagata 
レビューありがとうございます！
修正しましたので、ご確認をお願いします🙇🏻‍♀️

2022-01-18 05:02 UTC, komagata requested changes
バグ修正のIssueなので、バグ修正前は失敗して、バグ修正後は成功するテストの追加をお願いできればありがたいです〜

2022-01-19 03:02 UTC, napple29 commented
@komagata 
レビューありがとうございます！指摘をいただいたテストを追加しましたので、ご確認をお願いします🙇🏻‍♀️

2022-01-21 07:52 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-24 04:48 UTC, merged