Feature/change user can have multiple roles
fjordllc/bootcamp pull request #3979
Opened 2022-01-16 11:31 UTC by naomichi-h

issue: #3930

2022-01-18 01:45 UTC, naomichi-h commented
@machida PRのdescriptionに載せたスクリーンショットの場所(複数roleを持つユーザーの、ユーザー詳細画面の区分欄)のみ見た目が変わっています。お手すきのときに確認お願いいたします🙇‍♂️

2022-01-18 06:44 UTC, machida commented
@naomichi-h 複数入るようにマークアップを変更しましたー

2022-01-18 07:12 UTC, naomichi-h commented
@machida 対応ありがとうございます！

@AudioStakes こちらのレビューをお願いできますでしょうか？
よろしくお願いします🙏

2022-01-20 05:24 UTC, AudioStakes commented
@naomichi-h 
レビュー依頼ありがとうございます😄
一つ気になったことがありますので、教えてくださいー🙏

## 複数の role を持つ User の class 属性の設定方法について

現在の PR の変更においては、たとえば次のように `user.role[0]` が設定されています。

https://github.com/fjordllc/bootcamp/blob/38733b2602de6c47d10d1d4ee83971b886666778/app/views/application/_active_users.html.slim#L6

これについて、`user.role[0]` 以外（つまり `user.role[1]`, `user.role[2]`, ...）を設定しなくて良いのかどうか、僕の方では判断がつきませんでした。

そのため、class 属性に設定する role は「どれか1つのみ」もしくは「複数の role すべて」のどちらなのか教えてもらいたいです。

また、それぞれの場合について、以下の質問があります

### 「どれか1つのみ」の場合

その1つの role は常に一定に（常に同じ role が選ばれるように）する必要がありますか？
たとえば、「卒業生」と「アドバイザー」の role を持つユーザーに設定する class 属性は、常に「アドバイザー」（もしくは「卒業生」）か、「卒業生」と「アドバイザー」のどちらでもよいのか、どちらでしょうか。

### 「複数の role すべて」の場合

お互いに干渉し合う role（たとえば CSS で指定されている色が異なる、など）の場合、どの role を優先するのでしょうか（そのような規則がすでにあるのでしょうか）？

2022-01-20 12:41 UTC, naomichi-h commented
@AudioStakes 質問ありがとうございます🙇‍♂️

> class 属性に設定する role は「どれか1つのみ」もしくは「複数の role すべて」のどちらなのか教えてもらいたいです。

どれか一つのみです❗️

本PRでは、今回の変更による影響を最小限に抑えるため、「ユーザー詳細の区分欄以外は全て、変更前と同じroleが出力される」ことを目指しています。

つまり、複数のroleをもつユーザーに設定するclass属性は、「変更前の`User#role`のコードで選ばれるroleと同じ」にしています。

変更前の`User#role`のコードはdetectを使用しているため、複数roleの条件に該当するuserであっても、「最初に条件に当てはまったroleのみ」持つようになっていました。

今回、userが複数roleを持てるように変更をしたのですが、`user.role[0]`は、「最初に条件に当てはまったrole」であり、変更前の`User#role`の結果と同値になります。

`user.role[0]`のみを使用し、`user.role[1]`や`user.role[2]`を使用していないのはこのためです。

2022-01-21 04:51 UTC, AudioStakes commented
@naomichi-h 
なるほど、わかりやすく説明していただいてありがとうございます！
今の実装が期待される振る舞いになっているのだな、と理解できました。
基本的にOKだと思うものの、改善できそうなところを見つけたので、後ほどコメントします🙏

2022-01-21 07:21 UTC, AudioStakes reviewed
修正内容について確認しました！
期待どおりの振る舞いになっていますので、基本的には OK です👍

改善できそうなところはコメントしましたので、ご確認お願いしますー

修正する場合は修正後に改めてレビュー依頼をお願いします🙏

2022-01-21 07:21 UTC, AudioStakes commented on app/decorators/user_decorator.rb
>    end
2つほど改善できそうなところがあったのでコメントしますー
どちらも「必ず修正してほしい」という意図はありません。もし改善されていると実感できるようであれば、修正してみてもらえたらと思いますー🙏

### 改善案1

`UserDecorator#role` の返り値について、修正前後で「最初に条件に当てはまった role 」から「条件に当てはまる role すべて」に変わっていますね。
この変更に伴って、修正が必要となる View 関連のファイルが多々生じている（すなわち影響範囲が大きい）ため、 `UserDecorator#role` の返り値は変えない方が（修正前後で同じにした方が）よいかもしれません。

代替案として、`UserDecorator#role` はそのままにして、「条件に当てはまる role すべて」を返す `UserDecorator#roles` を追加するという案があります。
`UserDecorator#roles` の処理の中身は、今の修正後の `UserDecorator#role` そのままです。
次のようなイメージです。

```ruby
module UserDecorator

~省略~

  def role
    roles = [
      { role: :admin, value: admin },
      { role: :mentor, value: mentor },
      { role: :adviser, value: adviser },
      { role: :trainee, value: trainee },
      { role: :graduate, value: graduated_on },
      { role: :student, value: true }
    ]
    roles.detect { |v| v[:value] }[:role]
  end

  def roles
    roles = [
      { role: :admin, value: admin },
      { role: :mentor, value: mentor },
      { role: :adviser, value: adviser },
      { role: :trainee, value: trainee },
      { role: :graduate, value: graduated_on }
    ]
    if student? && !graduated?
      [:student]
    else
      roles.select { |v| v[:value] }.map { |h| h[:role] }
    end
  end

~省略~

end
```

`UserDecorator#roles`  を追加した後に、次の `app/views/users/_metas.html.slim` の  `user.role.each` を `user.roles.each` に変更することで、ユーザー詳細画面の区分欄には今の修正後のとおり複数の role を表示できます。

https://github.com/fjordllc/bootcamp/blob/38733b2602de6c47d10d1d4ee83971b886666778/app/views/users/_metas.html.slim#L68-L70

これにより、それ以外（ユーザー詳細画面の区分欄以外）は View まわりのコードを修正しなくて済むようになるので、このような実装にしてもよさそうですー

### 改善案2

初めて `UserDecorator#role` の処理を見たとき、どんな値が返ってくるか少し考える必要がありました。
※ 同様に、`UserDecorator#role` に基づいて実装された `UserDecorator#roles` も少し考えました。

そのため、`UserDecorator#role` （と `UserDecorator#roles`） の返り値を想像しやすくできるかもしれません。

僕の改善案としては、以下のようにすると返す値が少しわかりやすくなるかもしれないなと思いました。
※ 個人的にはもっとわかりやすくできるように思えているものの、あまり良い案が浮かびませんでした😅

```ruby
  def role
    return :admin if admin?
    return :mentor if mentor?
    return :adviser if adviser?
    return :trainee if trainee?
    return :graduate if graduated_on?
    :student
  end

  def roles
    roles = []

    roles << :admin if admin?
    roles << :mentor if mentor?
    roles << :adviser if adviser?
    roles << :trainee if trainee?
    roles << :graduate if graduated_on?
    roles << :student if roles.empty?

    roles
  end
```

もしより良い案がありましたら、そちらを選んでもらえたらと思いますー👍

2022-01-22 01:45 UTC, AudioStakes commented on app/decorators/user_decorator.rb
>    end
改善できそうなところをもう1つ見つけたので、お伝えしますー🙏

### 改善案3

複数の role を持つユーザーを例に考えると、既存の `UserDecorator#role` が返す値は「複数の role の中で最も優先順位の高い role 」と捉えることができると思います。
それを表すために、メソッド名を`UserDecorator#primary_role` に変更すると良いかもしれません。

この変更により `UserDecorator#role` を使っている箇所のメソッド名を変更する必要が生じるものの、 role の用途に応じて `user.primary_role` と `user.roles` を使い分けしやすくなり、コードの読み手にもその意図が伝わりやすくなると思うので、このような実装にしても良さそうですー

2022-01-22 16:51 UTC, naomichi-h commented
@AudioStakes たくさんの改善案ありがとうございます😊

たしかに！と思う部分が多数あったため、全面的に取り入れ、以下のように修正しました。
- UserDecorator#rolesを追加
- UserDecorator#rolesを提案されたものに変更（実は僕も最初、UserDecorator#roleの処理がわかりづらいなと感じました。)
- UserDecorator#roleをUserDecorator#primary_roleとし、中身を`roles.first`に変更

お手数ですが、確認をお願いいたします🙏

2022-01-24 05:12 UTC, AudioStakes reviewed
@naomichi-h 
ありがとうございます、修正内容を確認しました！
関数名について気づいたことをコメントしましたので、ご確認お願いしますー🙏
それ以外はOKです👍

---

追記

この PR の Assignees に、 naomichi さんがアサインされていないようですー

2022-01-24 05:12 UTC, AudioStakes commented on app/javascript/comments.vue
>      }
関数 `roleAdmin` と `roleAdviser` はどちらも Boolean 型の値( `true` or `false` )を返していますね。
そのような関数には `isHoge` や `hasFuga` のように命名することが多いです。

```suggestion
    isAdmin: function () {
      return this.currentUser.roles.includes('admin')
    },
    isAdviser: function () {
      return this.currentUser.roles.includes('adviser')
    }
```

参考資料を見つけられなかったので、代わりに bootcamp アプリ内のコードを例に示しますと以下のような関数があります

https://github.com/fjordllc/bootcamp/blob/400969fadf45b7baf1a2bf022390afb142f0582e/app/javascript/reports.vue#L75-L77
https://github.com/fjordllc/bootcamp/blob/400969fadf45b7baf1a2bf022390afb142f0582e/app/javascript/answers.vue#L97-L99

こちら、一括で置換して対応できると思いますので、修正をお願いできますでしょうか🙏

2022-01-27 03:12 UTC, naomichi-h commented on app/javascript/comments.vue
>      }
@AudioStakes 
> 関数 roleAdmin と roleAdviser はどちらも Boolean 型の値( true or false )を返していますね。
そのような関数には isHoge や hasFuga のように命名することが多いです。

おお〜、そうなのですね！ありがとうございます😊いや本当に勉強になります✨
提案いただいた内容で修正しましたので、確認をよろしくお願いいたします🙏

2022-01-27 05:46 UTC, AudioStakes approved these changes
@naomichi-h 
確認しました、OKですー👍
修正対象のファイル数が多くて修正に手間がかかったかもしれませんが、改善案を取り入れていただきありがとうございます😄

2022-01-27 07:54 UTC, naomichi-h commented
@AudioStakes こちらこそ、多くの修正をみていただいてありがとうございました 😊 @AudioStakes さんにお願いしてよかったです✨

@komagata こちらチームメンバーのレビュー通過しましたので、お手隙のときに確認をよろしくお願いいたします🙇‍♂️

2022-01-29 04:25 UTC, komagata requested changes

2022-01-29 04:25 UTC, komagata commented on app/javascript/comments.vue
> +      return this.currentUser.roles.includes('adviser')
共通の処理はmixinにすると良いかもです〜

2022-01-29 05:44 UTC, naomichi-h commented on app/javascript/comments.vue
> +    },
共通の処理をまとめました！

2022-01-29 05:55 UTC, naomichi-h commented on app/javascript/comments.vue
> +      return this.currentUser.roles.includes('adviser')
二つの処理をisRole()としてまとめました！

2022-01-29 05:55 UTC, naomichi-h commented
@komagata 修正を行いましたので、ご確認お願いいたします🙏

2022-01-31 15:09 UTC, komagata commented on app/javascript/comments.vue
> +      return this.currentUser.roles.includes('adviser')
@naomichi-h mixinはVue.jsの仕組みとして存在するmixinのことです〜

2022-01-31 20:29 UTC, naomichi-h commented on app/models/notification.rb
> +  private_class_method :product_update
rubocopで
```
Lint/IneffectiveAccessModifier: private (on line 265) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
```
と警告が出てエラーとなったため、https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Lint/IneffectiveAccessModifier
を参考に修正しました。

2022-01-31 20:56 UTC, naomichi-h commented on app/models/notification.rb
>    def self.product_update(product, receiver)
rubocopにて
```
Lint/IneffectiveAccessModifier: private (on line 265) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
```
と警告が出ていたため、該当メソッドをprivate外に出しました。
(警告通りに`private_class_method`などを使って該当メソッドをprivate化してしまうと、NoMethodErrorが発生し、`products_test:23`でエラーになってしまうためです。)

2022-01-31 21:08 UTC, naomichi-h commented on app/javascript/comments.vue
> +      return this.currentUser.roles.includes('adviser')
完全に勘違いしていました...😓
mixin使ってメソッドをファイルに分離しました！

2022-01-31 21:10 UTC, naomichi-h commented
@komagata 修正とコメントをしましたので、確認のほどよろしくお願いいたします🙏

2022-02-01 04:19 UTC, komagata commented on app/javascript/is-role.js
> +export default {
mixin名がis-roleだとこのメソッド一つ限定になっちゃうのでroleとか広い意味の方がいいかもです〜

2022-02-01 05:13 UTC, naomichi-h commented on app/javascript/is-role.js
> +export default {
なるほど、たしかに今後role関係のメソッドを切り出したりすることを考えると、広い意味の方が良いですね😄
mixin名をroleに変更します！

2022-02-01 07:06 UTC, naomichi-h commented on app/models/notification.rb
>    def self.product_update(product, receiver)
https://github.com/fjordllc/bootcamp/pull/4103
の内容をpullしました！(修正方法は同様)

2022-02-01 07:35 UTC, naomichi-h commented
@komagata 修正とコメントをしましたので、確認のほどよろしくお願いいたします🙏

2022-02-01 12:21 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-01 12:21 UTC, merged

2022-02-01 13:52 UTC, naomichi-h commented
@komagata これがチーム開発最後のマージとなりました✨ ありがとうございました！！

2022-02-02 05:39 UTC, komagata commented
@naomichi-h うお〜、お疲れ様です〜！開発ありがとうございました〜！！