管理者が各ユーザーの日報をエクスポートできるように変更
fjordllc/bootcamp pull request #3998
Opened 2022-01-19 12:21 UTC by yoshitaku-jp

issue #3913

2022-01-30 02:15 UTC, yoshitaku-jp commented
@R-Tsukada さん
お時間あるときのこちらのレビューをお願いできますでしょうか:pray:

2022-01-30 04:11 UTC, R-Tsukada commented
@yoshitaku-jp 
レビュー依頼ありがとうございます！
動作確認できました！コードも問題ないと思います。

ただテストを追加した方がいいと思うのですが、いかがでしょうか？
Rspecを使った記事なのですが、もしかしたら参考になるかもです。全然使えなかったらすみません🙏
[Rspecでダウンロードされたかテストする方法](https://qiita.com/ihatov08/items/c568725d88f09a438138)

2022-01-30 23:25 UTC, yoshitaku-jp commented
@R-Tsukada 
ありがとうございます！

テスト…そうですよね。ダウンロード機能はすでに実装されていて、こちらで担保できていると思っていました:pray:
お伝えしていなくてすみません。こちらでどうでしょうか。
https://github.com/fjordllc/bootcamp/blob/feature/reports-export-for-admin/test/models/report_exporter_test.rb

表示側は入れたほうがいいと思ったので導入しました！ありがとうございます！
https://github.com/fjordllc/bootcamp/pull/3998/commits/e95ad370088a129310d36dff8ee23cf0802aa0ea

2022-01-31 00:42 UTC, R-Tsukada approved these changes
> テスト…そうですよね。ダウンロード機能はすでに実装されていて、こちらで担保できていると思っていました🙏

すみません、僕が調べきれてなかったです💦
このテストで大丈夫そうですね！

> 表示側は入れたほうがいいと思ったので導入しました！

ありがとうございます！

LGTMだと思います！

2022-01-31 15:40 UTC, komagata requested changes

2022-01-31 15:40 UTC, komagata commented on app/controllers/users_controller.rb
> +    respond_to do |format|
https://github.com/fjordllc/bootcamp/blob/b2c2d491091cf8aa3b796c6d03c0804243d07115/app/controllers/current_user/reports_controller.rb#L11-L18

こちらでも同じ処理やっているので共通化したいですね。
管理者と本人だけダウンロードできるようにしたexport用のURLを用意して、そちらへリンクを貼るのはいかがでしょうか。

2022-02-04 14:05 UTC, yoshitaku-jp commented on app/controllers/users_controller.rb
> +    respond_to do |format|
@komagata 
こちら了解しました。

共通化した処理は[users/reports_controller](https://github.com/fjordllc/bootcamp/blob/main/app/controllers/users/reports_controller.rb)のindexに作成するのがいいでしょうか？

2022-02-05 07:49 UTC, komagata commented on app/controllers/users_controller.rb
> +    respond_to do |format|
@yoshitaku-jp そうですね、users/reports_controllerのindexが良さそうです〜

2022-02-05 07:49 UTC, komagata commented on test/system/users_test.rb
> +    visit_with_auth "/users/#{kimura.id}", 'komagata'
```suggestion
    visit_with_auth "/users/#{users(:kimura).id}", 'komagata'
```

何度か使ってるわけではないのでこれでいいかもです〜

2022-02-08 09:28 UTC, yoshitaku-jp commented
@komagata 
こちら修正しました。確認いただいてもいいでしょうか

2022-02-09 05:58 UTC, komagata commented
@yoshitaku-jp マージコミットができてしまっているようなので修正してみてください〜

2022-02-09 23:53 UTC, yoshitaku-jp commented
@komagata 
マージコミット修正いたしました！

2022-02-14 06:05 UTC, komagata commented on app/controllers/users/reports_controller.rb
> +  def index
管理者と本人だけがエクスポートできるようになっている必要があると思うのでうのですが、こちらは大丈夫でしょうか？

2022-02-20 23:51 UTC, yoshitaku-jp commented
@komagata 
こちら相談部屋の機能を参考に修正してみました。いかがでしょうか

2022-02-21 16:00 UTC, komagata commented on app/controllers/users/reports_controller.rb
> +    redirect_to root_path, alert: '自分以外の日報はダウンロードすることができません'
ここにアクセスしても本人と管理者以外はダウンロードできないことを確かめるテストが欲しいかもです〜

2022-02-24 04:58 UTC, yoshitaku-jp commented
@komagata 
こちらテストケースを追加しました！
https://github.com/fjordllc/bootcamp/pull/3998/commits/ec5a2f23dec5285dba353cdba2e578ea1c6885c1

2022-02-26 16:50 UTC, merged