sadがついた日報の提出時にヘルプへ誘導するモーダルを表示
fjordllc/bootcamp pull request #4006
Opened 2022-01-21 05:55 UTC by kaisumi

# Issue: #3996 
## 機能
sadがついた日報を提出する→日報の内容を表示する画面（show）にリダイレクト→モーダルが表示される。
![image](https://user-images.githubusercontent.com/39044468/150473795-b3e52a74-6cf7-41d3-8a4d-f3a5f0bf8241.png)

2022-01-21 07:29 UTC, kaisumi commented
@machida お疲れ様です。
先日ご相談していたsad日報でモーダル表示する件について、コードを書きました！
デザインをよろしくお願いいたします 😄

2022-01-24 08:12 UTC, machida commented
了解ですー！！

2022-01-30 08:32 UTC, sinsoku commented on app/controllers/reports_controller.rb
> +    { notify_qa: report.wip? ? false : report.sad? }
三項演算子を使うより、 `&&` で繋げた方が読みやすいかなと思いました。
（ただ、これは個人の好みかも）

```suggestion
    { notify_qa: !report.wip? && report.sad? }
```

2022-01-30 22:31 UTC, kaisumi commented on app/controllers/reports_controller.rb
> +    { notify_qa: report.wip? ? false : report.sad? }
@sinsoku コメントありがとうございます。おっしゃる通り条件式の方がスッキリしますね。変更しました 😄

2022-01-31 06:56 UTC, machida commented
@kaisumi お待たせしました！！デザイン、そのままでほぼOKでしたー。少しだけ手を加えました。受講生にレビューお願いします🙏

2022-01-31 07:04 UTC, kaisumi commented
@machida 
デザインありがとうございました 😄

2022-02-01 06:11 UTC, kaisumi commented
@Aseiide お疲れ様です！こちらお手隙の時にレビューお願いします 🙇

2022-02-05 06:40 UTC, Aseiide commented on app/controllers/reports_controller.rb
> +    { notify_qa: !report.wip? && report.sad? }
ここの`notify_qa`というのはどういう意味でつけましたか?
このめドッドでtrueかfalseが返るのは理解できたのですが、単語の意味が分からなかったので

2022-02-05 06:41 UTC, Aseiide reviewed
レビュー遅くなりまして申し訳有りません。
1点だけコメントしました。
よろしくお願いします。
@kaisumi

2022-02-06 23:24 UTC, kaisumi commented on app/controllers/reports_controller.rb
> +    { notify_qa: !report.wip? && report.sad? }
@Aseiide コメントありがとうございます 😄 notify_qaは「Q&Aをお知らせする」という意味でつけました。アドレスバーに表示され、ユーザーからも見える文字列なので、ユーザーに表示される内容とだいたい一致するようにしてあります。

2022-02-07 01:55 UTC, Aseiide reviewed
@kaisumi 
1件コメントしました。よろしくお願いいたします！

2022-02-07 01:55 UTC, Aseiide commented on app/controllers/reports_controller.rb
> +    { notify_qa: !report.wip? && report.sad? }
@kaisumi 
Q&Aへの誘導、というよりはヘルプページへの誘導なので、`notify_help`とか`indicate_help`とかのほうが則してるかなと思いました。
`notify_qa`だと`/questions`に飛ぶのかなと勘違いしそうになりました。

2022-02-07 02:23 UTC, kaisumi reviewed
コメントありがとうございました！おっしゃる通りQ&Aとヘルプを混同していました。修正したので、確認をよろしくお願いします。

2022-02-07 05:37 UTC, Aseiide reviewed
@kaisumi 
1件コメントしました。よろしくお願いします。

2022-02-07 05:37 UTC, Aseiide commented on app/views/reports/show.html.slim
> +    = render '/shared/modal', id: 'modal-notify-qa', title: '🍵 今日も学習お疲れ様でした！', auto_show: true
おそらく修正漏れだと思うのですが、`id: 'modal-notify-help'`に変更した方が良さそうです。

2022-02-07 06:03 UTC, kaisumi commented on app/views/reports/show.html.slim
> +    = render '/shared/modal', id: 'modal-notify-qa', title: '🍵 今日も学習お疲れ様でした！', auto_show: true
@Aseiide 修正漏れ失礼しました 🤕 修正したのでご確認をお願いしますー

2022-02-07 06:08 UTC, Aseiide approved these changes
LGTMです！
![lgtm](https://user-images.githubusercontent.com/45246171/152733713-ca75045a-6377-4e15-a246-9041237a853a.png)

2022-02-07 06:10 UTC, kaisumi commented
@Aseiide レビューありがとうございました！

@komagata お疲れ様です！お手すきの時にこちらレビューをお願いします 🙇

2022-02-09 05:44 UTC, komagata requested changes

2022-02-09 05:44 UTC, komagata commented on app/controllers/reports_controller.rb
> +      redirect_to redirect_url(@report, params_hash(@report)), notice: notice_message(@report)
次のページでだけ有効な内容というのが`flash`を使って実装できるのでそちらを使う方がURLに影響しないので良いかもです〜

2022-02-09 05:49 UTC, kaisumi commented on app/controllers/reports_controller.rb
> +      redirect_to redirect_url(@report, params_hash(@report)), notice: notice_message(@report)
@komagata コメントありがとうございます！
flashで、ということは以下の緑のflashで表示したようなイメージですか？
https://github.com/fjordllc/bootcamp/issues/3996#issuecomment-1016970568

2022-02-09 07:06 UTC, komagata commented on app/controllers/reports_controller.rb
> +      redirect_to redirect_url(@report, params_hash(@report)), notice: notice_message(@report)
@kaisumi その見た目部品としての`flash`ではなく、railsのメソッドとしての`flash`です〜。（次のページまでライフタイムのある変数）

2022-02-09 07:08 UTC, kaisumi commented on app/controllers/reports_controller.rb
> +      redirect_to redirect_url(@report, params_hash(@report)), notice: notice_message(@report)
@komagata railsメソッドですか！失礼しました、実装してみます 👍

2022-02-10 13:06 UTC, kaisumi commented
@komagata お疲れ様です。こちら修正してみました。レビューをよろしくお願いします 🙇

2022-02-15 02:57 UTC, komagata commented
@kaisumi mainブランチや他のブランチはテスト通っているようです、そこの差分から調査してみてください〜

2022-02-16 00:25 UTC, kaisumi commented
@komagata mainを取り込み、それに伴って生じた不具合箇所を修正しました。
ご確認をよろしくお願いします 🙏

2022-02-16 03:57 UTC, komagata commented on test/system/emotions_test.rb
> +  test 'create a report with the sad emotion' do
テストとテストは1行開けた方がいいかもです〜

2022-02-16 04:24 UTC, kaisumi commented
@komagata 
コメントありがとうございます。改行追加しました。ご確認をお願いいたします 🙏

2022-02-16 05:54 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-16 05:54 UTC, merged