[WIP]通知ページの全てのタブに未読数を表示する
fjordllc/bootcamp pull request #4027
Opened 2022-01-24 09:23 UTC by Aseiide

- #3907

2022-01-25 03:48 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +    visit_with_auth '/notifications', 'sotugyou'
アカウントをsotugyouにしているのは通知が存在するのがsotugyouだったためです。

2022-01-25 03:48 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +    visit_with_auth '/notifications', 'machida'
アカウントをmachidaにしているのは、テスト時点で通知が存在しないアカウントがmachidaだったためです

2022-01-25 03:50 UTC, Aseiide commented
@naomichi-h 
こちら、レビューお願いいたします。できる限りdescriptionで説明しているつもりなのですが、わからない点がございましたらメンションください。

2022-01-25 04:50 UTC, naomichi-h commented
@Aseiide レビュー依頼ありがとうございます。
現在動作確認中で、`muryou`アカウントに関しては再現できたのですが、`senpai`アカウントに関しては、スクリーンショットと同じ通知画面になりませんでした。
descriptionにある、「Senpaiアカウントでも確認済」に関して、具体的にどういった手順で確認を行ったのか教えていただけますか？

2022-01-25 05:35 UTC, Aseiide commented
@naomichi-h 
早速の対応、ありがとうございます。出先なので夕方までには再現手順を追記します。
少しお待ち下さい！

2022-01-25 05:56 UTC, Aseiide commented
@naomichi-h 
PRのDescriptionに再現手順追記いたしました。
以下、Descriptionと同じ文面です


**1/25 14:53追記**
以下に再現手順を示します。

1. anyloginを使って`senpai`アカウントでログイン
2. 通知ページ`/notifications`にアクセス
3. ↑のスクリーンショットと同じ画面で、各タブに未読数が表示されていることが確認できると思います。

よろしくお願いいたします。

2022-01-25 06:04 UTC, naomichi-h commented
@Aseiide `rails db:seed`してから追記していただいた再現手順を試したのですが、同じ画面にならないですね...。
一度、`rails db:seed`してから同じ画面になるか試していただけませんか？

2022-01-25 06:12 UTC, Aseiide commented
@naomichi-h 
承知しました。 `rails db:seed` からやってみます。
1点思い当たる点としては、動作確認をするために、わざと通知が飛ぶようにする必要がありました。
自分が試したのは、いろいろなアカウントでログインして`senpai`にメンションやコメントを飛ばすという手段を取っていました。テストデータなどは作っていなかったです。
なので、`senpai`アカウントに関しては自分の環境だけでしか再現できていないのかもしれないです、、

2022-01-25 06:16 UTC, Aseiide commented
@naomichi-h 
自分も`bin/rails db:seed` を実行してから`senpai`にログインしたところ、通知が1に戻っていました。
通知が溜まっているアカウントがなく、一つのアカウントだけで動作確認をするのは良くないかなーと思い他のアカウントでの動作確認を試みたのですが、このような場合ってどのようにしたら良いでしょうか？

2022-01-25 06:18 UTC, naomichi-h commented on test/system/notification/tabs_badges_test.rb
> +  test 'タブに未読数が表示されていること' do
現状のテストでは、「各タブのバッジが動作しているか」を確かめるには不十分かと思われます。
また、テスト名は、他のテストに習い、英語で書くのがよいと思います。
テストの方針ですが、それぞれのタブについてテストを書くのはいかがでしょうか？

例としては、コメントタブであれば、
```ruby
test 'show comment badge count' do

    visit_with_auth '/notifications', 'sotugyou'

    assert_selector "ul.page-tabs__items li.page-tabs__item:nth-child(4) a.page-tabs__item-link div.page-tabs__item-count ", text: "1"

end

test 'not show comment badge count' do

    visit_with_auth '/notifications', 'machida'

    assert_no_selector "ul.page-tabs__items li.page-tabs__item:nth-child(4) a.page-tabs__item-link div.page-tabs__item-count "

end
```

のような感じです。
また、バッジの増減は、以下のような`モデル.create`を間に挟めば簡単に表現できるので、これを使えば、適したuserを作成しなくても、その他のタブのテストができると思います。

```ruby
    Notification.create(
      kind: 7,
      user: @komagata,
      sender: @kimura,
      message: "#{@kimura.login_name}さんがはじめての日報を書きました！",
      link: "/reports/#{report.id}",
      read: false
    )
```

2022-01-25 06:24 UTC, naomichi-h commented on test/system/notification/tabs_badges_test.rb
> +  test 'タブに未読数が表示されていること' do
@Aseiide 
> 自分もbin/rails db:seed を実行してからsenpaiにログインしたところ、通知が1に戻っていました。
通知が溜まっているアカウントがなく、一つのアカウントだけで動作確認をするのは良くないかなーと思い他のアカウントでの動作確認を試みたのですが、このような場合ってどのようにしたら良いでしょうか？

確認のためのテストデータが欲しいのであれば、seedファイルを書くのが一つの方法だと思います。
`bootcamp`では、`db/fixtures`内にまとめられています。

testに関してコメントしましたので、確認をお願いいたします。

2022-01-25 06:25 UTC, naomichi-h commented
@Aseiide 
> 自分もbin/rails db:seed を実行してからsenpaiにログインしたところ、通知が1に戻っていました。
通知が溜まっているアカウントがなく、一つのアカウントだけで動作確認をするのは良くないかなーと思い他のアカウントでの動作確認を試みたのですが、このような場合ってどのようにしたら良いでしょうか？

確認のためのテストデータが欲しいのであれば、seedファイルを書くのが一つの方法だと思います。
`bootcamp`では、`db/fixtures`内にまとめられています。

testに関してコメントしましたので、確認をお願いいたします。

2022-01-25 06:38 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +  test 'タブに未読数が表示されていること' do
> テスト名は、他のテストに習い、英語で書くのがよいと思います。

そうですね、こちらは英語に変更して対応します。

> テストの方針ですが、それぞれのタブについてテストを書くのはいかがでしょうか？

自分がそれぞれのタブに関するテストを書かなかったのは、そこまでしてテストする必要があるか疑問だったからです。
それぞれのタブについて、通知あり/なしで2通りあり、それがタブ7個分なので14個(現実的ではないですが、仮に全てのパターンに対応するなら2^7=128通り)似たようなテストが並ぶほどまでテストせずとも、ある1個の要素のあるなしがわかればテストとしては十分ではないかと考えたからです。
自分はチーム開発に入ったばかりなので、チーム全体としてどういう方針なのかわからず、テスト対象を1個だけとしました。
実装として未読のバッジが実装されているのがQ&Aや通知マークなどありましたが、テストが存在せず、どのようにしたらよいかわからずレビューをお願いしたという経緯でした。


> また、バッジの増減は、以下のようなモデル.createを間に挟めば簡単に表現できるので、これを使えば、適したuserを作成しなくても、その他のタブのテストができると思います。

自分がbootcampのリポジトリを把握していないのですが、この次に書いてある`Notification.create`は`fixtures`に書くということですかね？
どのファイルに書けばよいかわからなかったので教えていただけると嬉しいです。

2022-01-25 06:54 UTC, naomichi-h commented on test/system/notification/tabs_badges_test.rb
> +  test 'タブに未読数が表示されていること' do
なるほどです。テストとして十分かどうか、そもそもテストが必要なのかは、私では判断できかねますので、一度駒形さんに伺ってみてはいかがでしょうか。

提案した`Notidication.create`はテスト内に書く内容です。
https://github.com/fjordllc/bootcamp/blob/fbbf4c1f0c3d65dd832487873d89307a012697f0/test/system/reports_test.rb#L449
にあるような記述です。

2022-01-25 07:03 UTC, Aseiide commented
@naomichi-h 

レビューに手間を取らせてしまってすみません、、。

> テストとして十分かどうか、そもそもテストが必要なのかは、私では判断できかねますので、一度駒形さんに伺ってみてはいかがでしょうか。

テストに関しては、次のレビューでkomagataさんに聞いて指示を仰ぎたいと思います。

次のような流れで行きたいと思います

- テストの内容が日本語になっているので英語に修正
- 改めてnaomichiさんにレビュー依頼
- naomichiさんのレビューをパスしたらkomagataさんにレビュー依頼

今日中に修正ができるか微妙で、明日までには修正してレビュー依頼送らせてください。もう少しだけレビューにお付き合いくださいませ。このような流れで大丈夫でしょうか？

2022-01-25 07:13 UTC, naomichi-h commented
@Aseiide いえいえ、全然問題ないですよ！
そうですね。まず最初に、discordか、もしくはここにメンションで駒形さんにtestについての指針を伺うのが良いと思います。
その後はその流れで良いかと思います〜。

2022-01-25 09:09 UTC, Aseiide commented
@komagata 
テストの方針について相談です。
現段階では、タブの未読数が表示されるか/されないか という簡単なテストにとどめてあるのですが、7個の全てのタブについて、表示されるか/されないか テストを書いたほうが良いでしょうか?

2022-01-26 05:16 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +  test 'unreads count are displayed on the tab' do
テスト内容の表記を英語にしました

2022-01-26 05:16 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +  test 'unreads count are not displayed on the tab' do
テスト内容の表記を英語にしました

2022-01-26 05:16 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +class Notification::TabsBadgesTest < ApplicationSystemTestCase
他のテストからコピペしたときにクラス名が間違っていたので修正しました

2022-01-26 05:18 UTC, Aseiide commented
@naomichi-h 
以下2点修正しましたのでレビューお願いいたします。

- [ ] テスト内容を日本語から英語に変える
- [ ] テストのクラス名が間違っていた

2022-01-26 05:38 UTC, komagata commented
@Aseiide 

> 現段階では、タブの1つについて未読数が表示されるか/されないか という簡単なテストにとどめてあるのですが、7個の全てのタブについて、表示されるか/されないか テストを書いたほうが良いでしょうか?

YESです。

2022-01-26 05:43 UTC, Aseiide commented
@komagata 
了解です。7個のタブすべてについてテストを書き直します。

2022-01-26 05:49 UTC, naomichi-h commented
@Aseiide テストを書き終えたらまたお声かけください〜

2022-01-26 09:05 UTC, Aseiide commented
残りのタスク

- [ ] watch中の未読数ありのテストを書く
- [ ] フォロー中の未読数ありのテストを書く
- [ ] テスト内容が日本語なのを英語に直す
- [ ] コンフリクトを解消する

2022-01-30 04:50 UTC, Aseiide commented
memo
コンフリクトしているので明日ペアプロ予定

2022-01-31 12:37 UTC, Aseiide commented
@naomichi-h 

# 現状の実装

![スクリーンショット_2022-01-31_19_03_29](https://user-images.githubusercontent.com/45246171/151793504-408d832b-ac87-4de3-9d84-dd2effdc599d.png)

PR #3642 が先にマージされたことによって`_tabs.html.slim`でコンフリクトを起こしていたので本日解消いたしました。
現状の実装としては、メンションタブについては、キャッシュを使って全件数と未読を表示しています。こちらは @AudioStakes さんによってPR#3642 で実装済です。

「全て」と「メンション」タブ以外については、このPRで実装しており、キャッシュは使っていません。
キャッシュを使っていない点については、MTG時に共有済です。

# レビューしてほしい点

実装する過程で新たにレビューしてほしい点がありましたので意見を頂きたいです。
テストファイルについてです。
自分は`test/system/notification/tabs_badges_test.rb`というファイルを新たに作ってテストを書いたのですが、[test/system/notifications_test.rb](https://github.com/fjordllc/bootcamp/blob/main/test/system/notifications_test.rb)というテストファイルがありました。
どっちに書くのが良いかわからなかったのでアドバイスいただけると嬉しいです。


レビューお願いいたします。

2022-01-31 14:24 UTC, naomichi-h commented on test/system/notification/tabs_badges_test.rb
> +  test 'unread badges are displayed' do
現状のテストでは、「同一ユーザーのステータスが変化したときに、バッジが変化するかどうか」がテストできていないので、タブのバッジ機能を十分テストできていないのかなと思います。

また、assert_selectorにはHTMLのタグを渡して場所を指定するのではなく、classを渡したほうが場所が明確になり、テストがエラーになった際の作業がやりやすくなると思います。

私は、バッジの増を`モデル.create`を使用して確認し、減は未読の項目をクリックして確認するテストを追加した方が良いと思いますが、あくまでも提案なので、他に方法があればそちらでも良いと思います。

2022-01-31 14:26 UTC, naomichi-h commented on test/system/notification/tabs_badges_test.rb
> +  test 'unread badges are displayed' do
現状のテストでは、「同一ユーザーのステータスが変化したときに、バッジが変化するかどうか」がテストできていないので、タブのバッジ機能を十分テストできていないのかなと思います。

また、assert_selectorにはHTMLのタグを渡して場所を指定するのではなく、classを渡したほうが場所が明確になり、テストがエラーになった際の作業がやりやすくなると思います。

私は、バッジの増を`モデル.create`を使用して確認し、減は未読の項目をクリックして確認するテストを追加した方が良いと思いますが、あくまでも提案なので、他に方法があればそちらでも良いと思います。

2022-01-31 14:27 UTC, naomichi-h commented
@Aseiide コメントしましたので確認おねがいいたします🙏
テストを書く場所については、今の実装で良いと思います。

2022-01-31 15:33 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +  test 'unread badges are displayed' do
@naomichi-h  レビューありがとうございます。

> 現状のテストでは、「同一ユーザーのステータスが変化したときに、バッジが変化するかどうか」がテストできていない

それぞれのテストで、ログインするユーザーが違うということですかね?
自分もテストを書いていて気になっていた点ではあるので、`sotugyou`に合わせてバッジ無しのテストを書き直したいと思います。その際は未読の項目をクリックして確認する方法を取りたいと思います。

> assert_selectorにはHTMLのタグを渡して場所を指定するのではなく、classを渡したほうが場所が明確になり、テストがエラーになった際の作業がやりやすくなると思います。

今のテストコードで、どの場所をテストしているか分かりづらい、というのは自分も思っていました。
7つのタブには全て同じclassが付与されています。`class="page-tabs__item-count a-notification-count"`
全て同じclassなので、classを渡した場合、「各タブについて個別にテストする」ということができなくなると思って今の書き方にしています。
自分の知識不足なのですが、同名のclassでも別々にテストする方法があるということでしょうか?
この点わからなかったのでご教示いただけると幸いです。

2022-01-31 18:04 UTC, naomichi-h commented on test/system/notification/tabs_badges_test.rb
> +  test 'unread badges are displayed' do
> それぞれのテストで、ログインするユーザーが違うということですかね?

「ログインしているユーザーのステータスが変化したときに、ちゃんとバッジが予期している仕様どおりに**変化するかどうか？**」がテストされていないことを問題にしています。

例えば、https://github.com/fjordllc/bootcamp/blob/4d0eaae4e74fdf2607806eb369b24f06a3a5f7a5/test/system/notifications_test.rb#L174
では、通知バッジが増えるかどうかをテストしていますし、
https://github.com/fjordllc/bootcamp/blob/4d0eaae4e74fdf2607806eb369b24f06a3a5f7a5/test/system/notifications_test.rb#L358
では、通知バッジが消えるかどうかをテストしています。

今回のテストにも、こういったテストが必要かなと思います。

> 自分の知識不足なのですが、同名のclassでも別々にテストする方法があるということでしょうか?

https://github.com/fjordllc/bootcamp/blob/4d0eaae4e74fdf2607806eb369b24f06a3a5f7a5/test/system/reports_test.rb#L345
にあるような感じで別々に指定できないですかね？

2022-01-31 23:48 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +  test 'unread badges are displayed' do
@naomichi-h ありがとうございます。頂いたご指摘をもとにテストについては書き直します。

2022-02-02 12:30 UTC, Aseiide commented
@naomichi-h 
通知を増やす処理と既読にして要素がないか、ということを検証するように変更しました。
各タブを指定している、`assert_selector` `assert_no_selector` はいろいろ書き方を試してみたのですが、自分では今の書き方以外でパスする書き方がわかりませんでした、申し訳ないです。

レビューお願いいたします。

2022-02-03 05:51 UTC, naomichi-h commented
@Aseiide testの動作はokだと思いますー。記述方法についてコメントしたので、よかったら参考にしてみてください。
あくまでも提案ですので、現状の書き方で問題ないと思われるなら僕のレビューはokとして、駒形さんのレビューにうつってくださいー。

2022-02-03 05:52 UTC, naomichi-h commented on test/system/notification/tabs_badges_test.rb
> +    end
```suggestion
    within all('.page-tabs__item')[0] do
      assert_selector '.page-tabs__item-count'
    end

    within all('.page-tabs__item')[1] do
      assert_selector '.page-tabs__item-count'
    end

    within all('.page-tabs__item')[2] do
      assert_selector '.page-tabs__item-count'
    end

    within all('.page-tabs__item')[3] do
      assert_selector '.page-tabs__item-count'
    end

    within all('.page-tabs__item')[4] do
      assert_selector '.page-tabs__item-count'
    end

    within all('.page-tabs__item')[5] do
      assert_selector '.page-tabs__item-count'
    end

    within all('.page-tabs__item')[6] do
      assert_selector '.page-tabs__item-count'
    end
```

とするのはどうでしょう？[伊藤さんのこの記事](https://qiita.com/jnchito/items/7bd131d99c28f21834dd)を参考に書いてみました。
`unread badges are not displayed`の方も同様にして書けます。

2022-02-04 08:00 UTC, Aseiide commented
@naomichi-h 
ご提案のように、テストのマッチャを書き換えました。
こちらの方がスッキリして読みやすいですね。
レビューお願いいたします。

2022-02-04 10:08 UTC, naomichi-h commented
@Aseiide 確認しました。okですー。

2022-02-04 11:24 UTC, Aseiide commented
@komagata 
こちらお手すきでレビューお願いします。

2022-02-05 07:43 UTC, komagata requested changes

2022-02-05 07:43 UTC, komagata commented on app/views/notifications/_tabs.html.slim
> +              - if current_user.notifications.by_target(target).unreads.latest_of_each_link.size.positive?
長いので分かりやすい名前をつけてViewHelperに追い出した方がいいかもですね。

2022-02-05 07:43 UTC, komagata commented on test/system/notification/tabs_badges_test.rb
> +  test 'unread badges are displayed' do
上に1行開けた方がいいかも？

2022-02-05 07:43 UTC, komagata commented on test/system/notification/tabs_badges_test.rb
> +    within all('.page-tabs__item')[0] do
allを使わずfirstを使い、CSS Selectorに`:nth-child(0)`などを使った方がいいかもです〜。

allと[0]だと指定した要素が見つからないというエラーではなくて、配列の要素が見つからないというエラーになるからです。

もしくは、タブのHTMLの方に分かりやすいIDかクラスをつけるのもいいかもです〜

2022-02-06 08:16 UTC, Aseiide commented on app/views/notifications/_tabs.html.slim
> +              - if current_user.notifications.by_target(target).unreads.latest_of_each_link.size.positive?
@komagata 
2点確認したいのですが、
- 「ViewHelperに追い出した方がいい」とのことですが、こちらは`app/helpers/notification_helper`のような形で新しくファイルを作って良いでしょうか?
- 切り出すとしたら、`current_user.notifications.by_target(target).unreads.latest_of_each_link.size.positive?`を`ensure_notifications? `(メソッド名は仮で付けました)のような形で丸ごと短くする、というふうに考えたのですが、この方針でよいでしょうか?

よろしくお願いします。

2022-02-07 07:23 UTC, Aseiide commented on app/views/notifications/_tabs.html.slim
> +              - if current_user.notifications.by_target(target).unreads.latest_of_each_link.size.positive?
質問タイムメモ
- `app/helpers`にヘルパーファイルを作ってOK
- `current_user.notifications.by_target(target).unreads.latest_of_each_link.size.positive?`このメソッドごとヘルパーに切り出す

2022-02-08 13:40 UTC, Aseiide commented on app/views/notifications/_tabs.html.slim
> +              - if ensure_notifications?(target)
メソッドが長かったので`app/helpers/notification_helper.rb`に切り出しました。

2022-02-08 13:47 UTC, Aseiide reviewed
@komagata 
レビューありがとうございます。
- システムテストの修正
- メソッドのヘルパーへの切り出し
2点対応しましたのでレビューお願いいたします。

2022-02-08 13:47 UTC, Aseiide commented on test/system/notification/tabs_badges_test.rb
> +      find('div', text: '10')
`first` と `find` を使って対象の要素があるかどうかを検証するようにしました

2022-02-09 07:02 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-09 07:02 UTC, merged