お試し延長 開始・終了機能を作成
fjordllc/bootcamp pull request #4030
Opened 2022-01-25 05:27 UTC by napple29

#3910

2022-01-26 08:46 UTC, napple29 commented
@maeda-seina 
お疲れ様です！ご都合の良い時にこちらのレビューをお願いしたいです。よろしくお願いします🙇🏻‍♀️✨

2022-01-27 04:50 UTC, maeda-seina reviewed
@napple29 さん
細かく丁寧にコミットされていて、変更意図がわかりやすかったです！🙇‍♂️
また、issue・PRに「あえて変更していないところ」の記述がわかりやすく書かれていてとても
PRに載せていただいている変更箇所は実際に手を動かして確認したところオッケーだと思いました！
細かいところにはなりますが、何点かコメントしておりますので、ご確認のほどよろしくお願いいたします。
（命名の部分につきましては、変更しなくてよさそうと判断されたらそのままにしておいてください🙏 ）

2022-01-27 04:50 UTC, maeda-seina commented on test/models/campaign_test.rb
> +    earlier_campaign = campaigns(:campaign1)
こちらの、`later_campaign`と`earlier_campaign`の変数の命名についてなんですが、laterは「後の」という意味があり、earilerは「以前の」という意味があるので、どちらが前のキャンペーンで、どちらが後のキャンペーンなのか少しわかりづらい気がしました。
現在開催されているものが、`:campaign1`で、過去に開催されたものが`:campaign2`ということで、少し考えたところ現在のものが`latest_campaign`とか`current_campaign`、過去のものが`past_campaign`とかが直感的にわかりやすいかもしれない？と思いました！

2022-01-27 05:59 UTC, napple29 commented on app/views/admin/campaigns/edit.html.slim
> +              | お試し延長編集
ありがとうございます！気づいてなかったです！！修正しました☺️

2022-01-27 06:00 UTC, napple29 commented on test/models/campaign_test.rb
> +    earlier_campaign = campaigns(:campaign1)
参考になります、、🙏🏻修正しました！

2022-01-27 06:00 UTC, napple29 commented
@maeda-seina 
お疲れ様です！レビューしていただきありがとうございます🙇🏻‍♀️
修正したのでお時間のある時にご確認をお願いします〜！

2022-01-27 06:14 UTC, maeda-seina commented
@napple29 さん

確認させて頂きました！👍 
レビューさせてもらい、とても勉強になりました！😊 🙏

2022-01-27 07:02 UTC, napple29 commented
@maeda-seina 
こちらこそありがとうございました〜😊✨

@komagata
お疲れ様です。チームメンバーのレビューを通過しましたので、ご都合の良い時にレビューをお願いします！

2022-01-29 04:22 UTC, komagata requested changes

2022-01-29 04:22 UTC, komagata commented on test/fixtures/campaigns.yml
> +  start_at: <%= Time.zone.today %>
```suggestion
  start_at: <%= Time.current %>
```

こちらの方がスマートかもです〜

2022-01-29 04:22 UTC, komagata commented on test/system/admin/campaigns_test.rb
> +    wd = %w[日 月 火 水 木 金 土]
複数回出てくるのであればテストクラスの定数にしちゃった方がいいかもです〜

2022-01-30 08:42 UTC, sinsoku commented on app/models/campaign.rb
> +  end
Rails 7から日付の比較に `ComparisonValidator` を使えるようになるので、コメントを残しておきたいなと思いました。
こうしておけば、Rails 7に上げた後に気づいた人が直してくれるかなと思うので。

```ruby
  # TODO: Rails 7に更新後、 `ComparisonValidator` を使うように直す。
  # refs: https://github.com/rails/rails/pull/40095
  # validates :end_at, greater_than: :start_at
  with_options if: -> { start_at && end_at } do
    validate :end_at_be_greater_than_start_at
  end
```

2022-01-31 06:32 UTC, napple29 commented on test/fixtures/campaigns.yml
> +  start_at: <%= Time.zone.today %>
教えていただきありがとうございます！こちら、修正が複数箇所あったので全て修正しました！

2022-01-31 06:34 UTC, napple29 commented on app/models/campaign.rb
> +  end
@sinsoku 
ありがとうございます！！教えていただいた通り、コメントで追記させていただきました！勉強になりました🙇🏻‍♀️

2022-01-31 06:36 UTC, napple29 commented
@komagata 
レビューありがとうございました！
指摘していただいた箇所を修正しました。また、それに伴い一部テストを修正しましたのでご確認をお願いします🙇🏻‍♀️

2022-01-31 15:43 UTC, komagata reviewed
conflictの修正お願いします〜

2022-02-01 12:54 UTC, napple29 commented
@komagata 
お疲れ様です！コンフリクトを解消しましたので、ご確認をお願いします🙇🏻‍♀️

2022-02-02 05:37 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-02 05:37 UTC, komagata commented on app/models/campaign.rb
> +  end
> Rails 7から日付の比較に ComparisonValidator を使えるようになるので、

ヘェ〜知らなかった😲

2022-02-02 05:38 UTC, komagata commented
@machida コードレビューはOKです。デザイン面の確認お願いできれば〜

2022-02-02 07:34 UTC, napple29 commented
@komagata 
こちらがチーム開発最後のIssueだったので無事レビューが通ってホッとしています😊ありがとうございました！！

2022-02-02 07:56 UTC, napple29 commented
@machida 
お疲れ様です！Issueを引き継いでいただき、ありがとうございます！

レビューを無事終えられましたので、デザインをお願いします☺️✨
以下が該当のファイルです。よろしくお願いします🙇🏻‍♀️

***
念の為管理画面のデザインの確認をお願いしたいです。
```
管理画面の入力欄
app/views/admin/campaigns/_form.html.slim

一覧画面
app/views/admin/campaigns/index.html.slim
```

以下は現状だと該当部分をif文でキャンペーン適用中か分岐させて表示が変更されるようになっています。
```
ウェルカムメッセージ
app/views/home/_welcome_message.html.slim

参加登録画面　一番上の部分
app/views/users/new.html.slim

参加登録画面　クレジットカード入力欄下の日数
app/views/card/_notice.html.slim 

料金ページ
app/views/welcome/pricing.html.slim
```
↓また、関連がありそうなファイルです。
```
トップページのキャンペーン広告（※今回変更を入れていないのでPRのFile Changedには入っていません）
app/views/welcome/_campaign.html.slim
```

2022-02-02 08:15 UTC, machida commented
デザイン入れていきますー

2022-02-03 08:43 UTC, machida commented
@komagata こちら、デザインを入れつつ機能を追加していきたいので、一旦マージをしてしまいたいですー

https://github.com/fjordllc/bootcamp/issues/4130
こういう機能を入れていきたいと思います。

2022-02-03 14:42 UTC, merged