日報のプレビュー機能のテストを追加
fjordllc/bootcamp pull request #4051
Opened 2022-01-26 08:17 UTC by maeda-seina

## issue
- #3969 

## 概要
日報の不具合が再発しないようにテストを追加する。

## 不具合について
- [[解決済]🙇‍♂️ 日報編集画面で不具合が発生しています | FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/announcements/603)

## やったこと
「日報にMarkdownを入力すると、プレビューにHTMLで表示されている。」というシステムテストを追加しました。

2022-01-27 06:17 UTC, maeda-seina commented
@kaisumi さん

お疲れ様です！
ご都合の良い時にこちらのレビューお願い致します🙏

@komagata さん @machida さん

textareaのサイズが自動で変更されるか確認するというテスト作成の方は別issueに切り出しておきました!!🙇‍♂️
- #4057

2022-01-28 07:46 UTC, kaisumi commented on test/system/reports_test.rb
> +    visit_with_auth '/reports/new', 'kimura'
コードレビュー初めてなもので、何か粗相があったらすみません 🙇 
この件、新規作成時が治っても編集時に治ってないとかコピー作成時に治ってないとかあった気がするので、網羅したほうがいいのかな、と思います。

2022-01-28 07:52 UTC, kaisumi requested changes
お疲れ様です😄 
コメントを追加したのでご確認をお願いします 🙇

2022-01-28 07:52 UTC, kaisumi commented on test/system/reports_test.rb
> +    visit_with_auth '/reports/new', 'kimura'
コードレビュー初めてなもので、何か粗相があったらすみません 🙇
この件、新規作成時が治っても編集時に治ってないとかコピー作成時に治ってないとかあった気がするので、網羅したほうがいいのかな、と思います。

2022-01-28 16:59 UTC, maeda-seina commented on test/system/reports_test.rb
> +    visit_with_auth '/reports/new', 'kimura'
@kaisumi さん
お疲れ様です。
レビューありがとうございます！
> この件、新規作成時が治っても編集時に治ってないとかコピー作成時に治ってないとかあった気がするので、網羅したほうがいいのかな、と思います。

[日報編集画面で不具合が発生しています](https://bootcamp.fjord.jp/announcements/603)
上記の記事に「編集画面で不具合が発生している」と記載されているのを失念しておりました🙇‍♂️ 教えて頂きありがとうございます!!
修正いたしましたので、ご都合の良い時にご確認の程よろしくお願い致します🙏

2022-01-29 04:40 UTC, kaisumi commented
@maeda-seina 確認しました！良さそうです。ご対応ありがとうございました。
すみません、以下のボタンを押していただかないと私の方でApproveできないようでして・・・
![image](https://user-images.githubusercontent.com/39044468/151647479-7f6613ce-9c6c-4fd4-917b-99038bbed228.png)
お手数お掛けし恐縮ですが、よろしくお願いしますm(_ _)m

2022-01-29 12:59 UTC, maeda-seina commented
@kaisumi さん

ご確認ありがとうございます！
> すみません、以下のボタンを押していただかないと私の方でApproveできないようでして・・・

お手数おかけして申し訳ありません！
了解いたしました。押しましたので、よろしくお願い致します🙇‍♂️

2022-01-29 13:22 UTC, kaisumi approved these changes
お手数お掛けしました 🙇

2022-01-29 13:24 UTC, maeda-seina commented
@komagata さん

お疲れ様です。
ご都合の良いときに、こちらのレビューよろしくお願い致します🙏

2022-01-31 15:16 UTC, merged