ユーザー > 日報 のページのタイトルを変更
fjordllc/bootcamp pull request #4061
Opened 2022-01-27 15:34 UTC by chung3011

[#3705](https://github.com/fjordllc/bootcamp/issues/3705)
ユーザー > 日報のページのタイトルを変更しました。

## 変更前
<img width="1167" alt="Screen Shot 2022-01-27 at 22 33 03" src="https://user-images.githubusercontent.com/34033366/151390717-e75b5c7d-5261-495a-9163-76017a1efde0.png">

## 変更後
<img width="1163" alt="Screen Shot 2022-01-27 at 22 33 39" src="https://user-images.githubusercontent.com/34033366/151390824-2fde68eb-3fff-487f-99a5-9bdd538e8ee2.png">

## テスト
<img width="480" alt="Screen Shot 2022-01-27 at 22 34 15" src="https://user-images.githubusercontent.com/34033366/151390937-13d6dc5d-790e-47d6-b925-49692d2538d9.png">

2022-01-29 04:34 UTC, komagata commented
@chung3011 まず他の生徒の方にレビュー依頼して、OKでしたら改めて僕にレビュー依頼する流れになっていますので、お願いします〜。

2022-01-31 12:04 UTC, Saki-htr reviewed
レビューしました! LGTMです〜

2022-02-01 04:34 UTC, komagata commented
@chung3011 相手が気付きづらいのでレビュー依頼する時は、メンションをつけてコメントでも依頼お願いします〜

2022-02-01 06:11 UTC, chung3011 commented
> @chung3011 相手が気付きづらいのでレビュー依頼する時は、メンションをつけてコメントでも依頼お願いします〜

2022-02-01 06:14 UTC, chung3011 commented
@komagata 、お疲れさまです。
チェックをお願いいたしますー🙏

2022-02-01 10:34 UTC, Saki-htr requested changes
@chung3011 
すみません、一度レビュー通してしまったのですが、Lintとテストが通っていないようですので、そちらのご対応をお願いいたします〜🙏

@komagata 
誤ってレビューリクエストを送ってしまいましたので、review ready になるまでお待ちいただけますと幸いです。よろしくお願いいたします🙏

2022-02-02 13:16 UTC, chung3011 commented
Reopen PR

2022-02-05 00:06 UTC, Saki-htr reviewed
@chung3011 さん
お疲れさまです〜
こちらのプルリクエストですが、2/2(水)の振返りミーティングでの作業で、Lintとテストが通ったので、レビューさせていただきます🙏   

コードと動作確認をしたところ大丈夫でした!
ブランチ名は、ブートキャンプのルールですと`feature/change-user-reports-title`なのですが、ミーティングでkomagataさんが「今回はこちらで大丈夫」と仰っていたので、OKです〜🙆‍♀️

ブランチ名のルールはこちらの[チーム開発の作業手順](https://bootcamp.fjord.jp/pages/305#-3)に載っていますので、よろしければ参考になさってください〜☺️

![image](https://user-images.githubusercontent.com/58052292/152618287-71235d5a-0938-4ac5-8ca8-97bbd7a933e1.png)

2022-02-05 13:30 UTC, chung3011 commented
@komagataさん、お疲れさまです。
チェックをお願いいたしますー🙏

2022-02-08 12:19 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-08 12:21 UTC, komagata commented
@Saki-htr レビューOKでしたらReviewのステータスを変更お願いします〜（レビューワーに設定された人全員がOKにならないとマージできないので〜）

2022-02-08 12:56 UTC, Saki-htr approved these changes

2022-02-08 12:58 UTC, Saki-htr commented
@komagata 
すみません、ただいまReviewのステータスを`Approve changes`に変更いたしました。
ご確認をお願いいたします🙏

2022-02-09 07:00 UTC, merged