practice-selectでsubmitのhrefを編集
fjordllc/bootcamp pull request #4063
Opened 2022-01-28 05:11 UTC by chung3011

[#3306](https://github.com/fjordllc/bootcamp/issues/3306)
Q&A一覧の「全ての質問」タブでプラクティスによる絞り込みをすると、「未解決」タブに遷移してしまう問題

practice-selectでsubmitのhrefを編集した。

2022-02-01 06:10 UTC, chung3011 commented
@Saki-htr さん、お疲れさまです。
チェックをお願いいたしますー🙏

2022-02-01 15:28 UTC, Saki-htr commented
@chung3011 さん

お疲れ様です〜
申し訳ないのですが、もう一つレビュー依頼してくださっている[ユーザー > 日報 のページのタイトルを変更 by chung3011 · Pull Request \#4061 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4061) のissueを、もう一度レビューさせていただくことになりましたので、こちらのissueは別の方に依頼していただけると、ありがたいです〜🙏
せっかく依頼してくださったのに、すみません🙇‍♀️💦

2022-02-01 15:45 UTC, chung3011 commented
@ot0m1さん、お疲れさまです。
チェックをお願いいたしますー🙏

2022-02-02 04:15 UTC, ot0m1 commented
@chung3011 
ブランチ名が命名規則に沿っていないようです。以下をご確認いただき修正をお願いいたします🙏
https://bootcamp.fjord.jp/pages/305#-3

また、このプルリクの概要説明にもう少し情報やスクショがあったほうがよいのではないかなと思いました。
今回は簡単な修正でしたが、「何のために」「何を考えて」「何をしたのか」が見やすく明確になっていると、的確にレビューしてもらえたり、後で他の人が見た際にも理解しやすくてスムーズだと思います。あとは、リリース後にリリースノートを書く際にも役に立ちます。
理想はこちらのプルリクだと思っています。↓↓↓
[相談部屋に返信/未返信タブをつける by mami\-inuzuka · Pull Request \#3890 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/3890)

2022-02-02 04:52 UTC, ot0m1 reviewed
@chung3011 
ブランチ名が命名規則に沿っていないようです。以下をご確認いただき修正をお願いいたします🙏
https://bootcamp.fjord.jp/pages/305#-3

また、このプルリクの概要説明にもう少し情報やスクショがあったほうがよいのではないかなと思いました。
今回は簡単な修正でしたが、「何のために」「何を考えて」「何をしたのか」が見やすく明確になっていると、的確にレビューしてもらえたり、後で他の人が見た際にも理解しやすくてスムーズだと思います。あとは、リリース後にリリースノートを書く際にも役に立ちます。
理想はこちらのプルリクだと思っています。↓↓↓
[相談部屋に返信/未返信タブをつける by mami\-inuzuka · Pull Request \#3890 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/3890)

2022-02-05 14:03 UTC, chung3011 commented
@ot0m1さん、お疲れさまです。
レビューありがとうございました。

次回はブランチの命名に注意します。
プルリクの概要説明にgifを追加しました。

もう一度ご確認お願い致しますー🙏

2022-02-06 04:50 UTC, ot0m1 commented
@chung3011 
LGTMです！

なお、現在 http://localhost:3000/questions のページで以下のような Vue のエラーが発生しているようでした。
このブランチ以外でも発生しているようでしたので、[別途バグ報告のissue](https://github.com/fjordllc/bootcamp/issues/4150)を立てております。

![スクリーンショット 2022-02-06 13 41 19](https://user-images.githubusercontent.com/6190966/152668015-826a1202-0204-49e6-8b4c-77af46fe9e01.png)

2022-02-06 07:39 UTC, chung3011 commented
@komagataさん、お疲れさまです。
チェックをお願いいたしますー🙏

2022-02-09 04:48 UTC, komagata requested changes
バグの修正Issueなので、テストが欲しいですね。

2022-03-16 14:03 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-16 14:03 UTC, merged