adminのroleだけを持ったテストユーザー名の変更
fjordllc/bootcamp pull request #4083
Opened 2022-01-29 13:05 UTC by garammasala29

2022-01-31 07:58 UTC, garammasala29 commented
@kaisumi さん
お疲れ様です。ご都合の良い時にこちらのレビューをお願いしたいです🙏
難しいようでしたら、Discordの方に連絡していただければと思います🙇‍♂️
よろしくお願いします！

2022-01-31 22:58 UTC, kaisumi requested changes
@garammasala29 お疲れ様です！
test/fixtures/users.yml内に以下のように記載されているので、talks.ymlにも追記した方がいいかと思います。
![image](https://user-images.githubusercontent.com/39044468/151886773-01496440-988e-47f3-a88e-bf633a1ca737.png)
その他は良さそうでした 😄

2022-02-01 15:02 UTC, garammasala29 commented
@kaisumi さん
お疲れ様です。レビューありがとうございました！
ご指摘いただいた通り、``test/fixtures/users.yml``へのユーザー追記を行いました。
自分の確認ミスでお手数おかけしてすみません💦
再度、お手隙の際にご確認のほど、よろしくお願いします🙏

2022-02-01 23:38 UTC, kaisumi approved these changes
@garammasala29 良さそうですー！ご対応ありがとうございました 🙇

2022-02-02 00:42 UTC, garammasala29 commented
@kaisumi さん
ご確認ありがとうございました😄

2022-02-02 00:43 UTC, garammasala29 commented
@komagata さん
お疲れ様です！こちらお手隙の際にレビューをお願いします 🙇

2022-02-02 05:44 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-02 05:44 UTC, merged