管理者でログイン時にユーザー一覧の各ユーザーに相談部屋へのリンクを表示
fjordllc/bootcamp pull request #4084
Opened 2022-01-29 13:34 UTC by Paru871

## Issue
- #4069
 
## 概要
管理者でログインしたときのみ、ユーザー一覧ページのそれぞれのユーザーの枠内に相談部屋へのリンクを表示させる変更作業を行いました。

## 変更確認方法
1. ブランチ `feature/add-link-to-talk-on-user-list-only-mentor`をローカルに取り込む
2. `$ rails s` でローカル環境を立ち上げる
3. テスト用ユーザー(管理者ロールを持っている'komagata''machida'のどちらか)でログインする
4. 左側のナビゲーションバーから「ユーザー」をクリックしてユーザー一覧ページを開きます。
5. それぞれのユーザーの枠内に「相談部屋」の文字と、それぞれの相談部屋へのリンクが付加されていることをご確認ください。

## 変更【前】(「相談部屋」へのリンクが表示されていなかった)のスクショ
![image](https://user-images.githubusercontent.com/82434093/151663068-d77b8a94-462a-4811-85bb-f21947bbc545.png)

## 変更【後】(「相談部屋」へのリンクが表示されている)のスクショ(デザイン適用前の暫定版)
![image](https://user-images.githubusercontent.com/82434093/151663060-4a13905c-67cc-464b-929d-2c34f3e65ea7.png)

2022-01-29 14:40 UTC, Paru871 commented
@machida 
お疲れさまです。管理者にログイン時にユーザー一覧ページの各ユーザーの枠内にそれぞれの「相談部屋」へのリンクを置きました。お手すきの際にデザインをつけていただきたく、よろしくお願いします🙏
(架空のcssのクラス`users-item__linkto_talk.is-only-admin`を書いてみましたので、適切な表記に変更もお願いします。)

2022-01-31 04:26 UTC, machida commented
@Paru871 ありがとうございます！これでOKですー デザイン入れます💪

2022-01-31 04:40 UTC, machida commented
@Paru871 デザイン入れましたー
僕の環境のせいかもしれないのですが、ローカルでユーザー一覧が表示されなかったので、何か問題が起きてるかもしれないです。なので、画面で確認できていないのですが、デザインは多分ちゃんと入ってると思いますー

2022-01-31 13:10 UTC, Paru871 commented
@machida 
今回も早速にかっこいいデザインをつけてくださりありがとうございました🙇🏻‍♀️
私のローカル環境ではユーザー一覧画面が表示されて、デザインが付いた新しい「相談部屋」のボタンが表示されています。
(description欄の変更後のスクショにてご確認ください。)
それでは次のステップのチームメンバーレビューに進みます。ありがとうございます！

2022-01-31 13:13 UTC, Paru871 commented
@maeda-seina 
お疲れさまです！
お手すきの際にこちらのレビューをいただきたく、よろしくお願いします🙏

2022-02-01 23:23 UTC, maeda-seina approved these changes
@Paru871 さん
レビュー依頼ありがとうございます。
動作確認できました！丁寧に記述いただいていて、わかりやすかったです〜!!
LGTMです！👍

2022-02-02 00:11 UTC, Paru871 commented
@maeda-seina 
早速にご確認くださりありがとうございました！OKをいただけて安心しました〜😊
今後ともよろしくお願いします🙏🏻

2022-02-02 00:13 UTC, Paru871 commented
@komagata 
お疲れさまです。チームメンバーさんのレビューのOKをいただきました。
お手すきの際にレビューをよろしくお願いします🙇‍♀️

2022-02-02 05:43 UTC, komagata requested changes

2022-02-02 05:43 UTC, komagata commented on app/views/api/users/_list_user.json.jbuilder
> +json.talkurl talk_path(user.talk)
camelcaseの名前にした方がいいかもです〜。（名前が判別しづらいので）

2022-02-02 08:09 UTC, Paru871 commented
@komagata 
レビューありがとうございます！
キャメルケースを忘れてしまい、失礼しました。
間違えた2箇所をキャメルケース`talkUrl`に修正しましたので、再度チェックいただきたくよろしくお願いします🙏

2022-02-03 08:28 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-03 08:28 UTC, merged

2022-02-18 12:22 UTC, Paru871 commented
@komagata @machida 
お疲れさまです。
こちらは管理者向けの機能のため、本番環境で変更のご確認をお願いできますでしょうか。

【確認手順とチェックしていただきたいこと】
- 左側のナビゲーションバーから「ユーザー」をクリックしてユーザー一覧ページを開きます。
- それぞれのユーザーの枠内に「相談部屋」の文字と、それぞれの相談部屋へのリンクが付加されていることをご確認ください。

よろしくお願いします🙏