相談部屋一覧のローディング中にプレースホルダを表示
fjordllc/bootcamp pull request #4111
Opened 2022-02-01 14:56 UTC by ot0m1

ref: #4091

2022-02-01 16:07 UTC, ot0m1 commented
@Saki-htr 
レビューお願いいたします🙏

2022-02-05 02:43 UTC, Saki-htr requested changes
@ot0m1 さん
お疲れさまです〜! お待たせしてすみません🙏

動作確認したところ、私の環境では、以下の動画のように、
1. 相談部屋をクリックすると「ロード中」と表示される
2. その後プレースホルダが表示されず、相談部屋一覧が表示される

となりました。

[![Image from Gyazo](https://i.gyazo.com/9e6fff07d49da218718654404ebff50d.gif)](https://gyazo.com/9e6fff07d49da218718654404ebff50d)

## ご確認いただきたい箇所が2点あります🙏
### 1点目

プレースホルダが表示されていないようですので、ご確認いただけましたら幸いです〜。

### 2点目

少し気になったのですが、この「ロード中」は画面に表示するものなのでしょうか？？
[\[相談部屋\] 相談部屋一覧のローディング中にプレースホルダを表示したい。 · Issue \#4091 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/4091)でmachidaさんが、「日報一覧の読込中と同じものを表示するようにお願いします」と仰っていて、日報一覧(http://localhost:3000/reports) では、「ロード中」と表示されておらず、プレースホルダーのみ表示されるので、気になりました〜
もし「ロード中」を表示しないようでしたら、そちらも合わせてご確認いただけましたら幸いです🙏
よろしくお願いいたします🙇‍♀️

2022-02-05 03:19 UTC, ot0m1 commented
@Saki-htr 
ブランチを取り込んでいただいた上でプレースホルダが表示されず`ロード中`という表示がされるようでしたら、Vueなどのキャシュが残っている可能性があります。
僕もこのブランチ対応中に行った変更が反映されずに困ったことがありました。
以下を試していただけますでしょうか。

- Chrome のゲストモードなどでローカルホストに接続する（ブラウザのキャッシュではなさそうですが一応）
- `app/javascript/talks.vue` の[`未返信の相談部屋はありません`の文字](https://github.com/fjordllc/bootcamp/pull/4111/files#diff-4e5fed80b4a2b6150d01620b514ef1d0eba4357b4192dab0367ae559390fc085L6)を一旦適当な文字列に変更してファイルを保存する
    - プレースホルダを確認できたら変更した文字は戻す

2022-02-05 15:07 UTC, Saki-htr reviewed
@ot0m1 さん
お疲れさまです。
動作確認を無事に行えました。
最初私の方できちんと動作確認ができておらず、申し訳ありませんでした🙏💦

コードと動作確認ともにLGTMなのですが、
今の状態で`feature/show-placeholders-while-loading-consultation-room-list`にチェックアウトしてrailsを起動しようとすると、`sorcery-jwt`というgem関連のエラーが起きてしまいます。
こちらのエラーは[sorcery\-jwtをアップデート by komagata · Pull Request \#4116 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/4116/files)で対応済で、すでに`main`にマージされているため、`main`を取り込んでいただければこのエラーは解消されます。

お手数をおかけして申し訳ないのですが、最新の`main`を取り込んでもう一度`push`していただけましたら幸いです。
よろしくお願いいたします🙏

2022-02-09 11:31 UTC, ot0m1 commented
@Saki-htr ご確認ありがとうございました！
@komagata 最新の main を取り込んでおりますのでレビューお願いいたします。

2022-02-09 14:10 UTC, Saki-htr approved these changes

2022-02-09 14:14 UTC, Saki-htr commented
@ot0m1 さん
mainを取り込んでくださって、ありがとうございます!
ただいま確認したところ、大丈夫でした。
Reviewのステータスを`Approve changes`にしましたので、よろしくお願いいたします〜:pray:

2022-02-14 06:02 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-14 06:02 UTC, merged