卒業生に通知がいかないように修正 & テストの修正
fjordllc/bootcamp pull request #4141
Opened 2022-02-04 14:01 UTC by maeda-seina

## issue

- #3981 

## 修正PR

- #4012 

## 概要

#4012 のPRに不備があり、卒業生に「はじめての日報を書きました！」通知がいってしまっていたのでその修正。

## 変更内容

`app/models/notification_facade.rb:78`の`if receiver.student_or_trainee?`の`student_or_trainee`メソッドでは卒業生も対象になってしまっていたので、そちらのメソッドを`student_or_trainee_or_retired?`に変更しました。
また、`test/system/reports_test.rb:6`の卒業生のテストが機能していなかったため、機能させるために`wait_for_vuejs`メソッドを追加しておきました。

2022-02-04 14:22 UTC, maeda-seina commented
@haruguchi-yuma さん
お疲れ様です！
お時間ある時に、こちらのレビューお願い致します🙇‍♂️

2022-02-05 07:47 UTC, haruguchi-yuma approved these changes
問題ないと思いました。OKです〜！:tada:

今回の変更点ではないんですが、テストの部分で日報を作るところがありますが、`title`と`description`が意味のあるものだとテストが読みやすかなーと思いました！

```ruby
test 'the first daily report notification is sent only to current students and mentors' do
    report = users(:muryou).reports.create!(
      title: 'test title',  #ここ
      description: 'test',　#ここ
      reported_on: Date.current
    )
...
```
本質的な部分ではないので変更はどちらでも結構です〜！

2022-02-05 11:41 UTC, ima1zumi commented on app/models/notification_facade.rb
> +    Notification.first_report(report, receiver) if receiver.student_or_trainee_or_retired? || receiver.admin_or_mentor?
これだとリタイアしたユーザーも通知の対象になってしまうので
卒業生ではない人 かつ student または trainee または admin または advisor を対象にすると良さそうです 😄

2022-02-05 15:51 UTC, maeda-seina commented on app/models/notification_facade.rb
> +    Notification.first_report(report, receiver) if receiver.student_or_trainee_or_retired? || receiver.admin_or_mentor?
@ima1zumi さん
レビューして頂きありがとうございます！😊
ご指摘してもらった通り、リタイアしたユーザーへの通知を考慮できていませんでした😅
教えていただいた内容で通知対象を修正をしたいと思います！

2022-02-05 15:51 UTC, maeda-seina commented
@haruguchi-yuma さん
レビューして頂き、ありがとうございます!!
おっしゃる通りだと思いましたので、テストのtitleとdescriptionを修正しようと思います！🙇‍♂️ 😄

2022-02-05 16:10 UTC, maeda-seina commented
@haruguchi-yuma さん、@ima1zumi さん
お手数おかけしますが、再度レビューのほどよろしくお願い致します🙇‍♂️

2022-02-06 05:26 UTC, haruguchi-yuma commented on app/models/notification_facade.rb
> +    Notification.first_report(report, receiver) if receiver.student_or_trainee_or_retired? || receiver.admin_or_mentor?
メールのこと考えるの忘れてました。確かにリタイヤした人に通知行くのはダメですね、、🥲

2022-02-06 05:35 UTC, haruguchi-yuma commented
リタイヤしたユーザの視点でいくとこの条件でも条件式全体が`true`になってしまうような気がします。😭
以下`rails console`の結果です。studentかどうかの判定ににリタイヤしたユーザがヒットしてしまうので、、、

```ruby
 retired_user.name
=> "辞目 辞目夫"
 retired_user.student?
=> true
retired_user.student_or_trainee?
=> true
 retired_user.student_or_trainee_or_retired?
=> true
```

明示的に`!retired?`という条件を加えるのがいいかも？

2022-02-06 06:11 UTC, maeda-seina commented
@haruguchi-yuma さん
再度レビューして頂き、ありがとうございます！！
> リタイヤしたユーザの視点でいくとこの条件でも条件式全体がtrueになってしまうような気がします。😭

ほんとうですね...😅（何度も申し訳ないです🙏）
`!retired?`を条件に加えて修正させて頂きます!!🙏

2022-02-07 14:09 UTC, maeda-seina commented
@haruguchi-yuma さん
お疲れ様です。
お手数お掛けしますが、再度レビューのほどよろしくお願い致します🙇‍♂️

`app/models/notification_facade.rb`の`receiver.student_or_trainee? && !receiver.graduated? && !receiver.retired?`の部分を`current_student?`というメソッド名で切り出しました。
`current_student?`メソッドにはuser.rbにある既存のメソッドを使用せずに、カラムを使用して定義しています。

また、`app/views/application/_header.html.slim`の7行目で`student_or_trainee?`メソッドが使用されていましたが、`student_or_trainee? `メソッドの中身は`student? || trainee?` となっており、`student?`メソッドには卒業生も含まれているため、卒業生でログインしてもヘッダー部分には卒業生ロールが表示されていませんでした。
なので、`current_student?`メソッドを使用して、卒業生ロールが表示されるよう修正をしました。

![image](https://user-images.githubusercontent.com/66904873/152788638-de587541-ec98-48d0-b057-c53b6c495efb.png)

2022-02-07 23:27 UTC, haruguchi-yuma commented
@maeda-seina 
確認しました〜！メソッド定義するという判断もナイスだと思います。僕の方からはOKです:rocket:

2022-02-08 02:38 UTC, maeda-seina commented
@haruguchi-yuma さん
何度もレビューしていただき、ありがとうございました😊

@komagata さん
お疲れ様です！
お時間ある時に、こちらのレビューお願い致します🙇‍♂️

2022-02-09 05:10 UTC, komagata commented
@maeda-seina 

> なので、current_student?メソッドを使用して、卒業生ロールが表示されるよう修正をしました。

ありがとうございます〜👍

2022-02-09 05:14 UTC, komagata requested changes

2022-02-09 05:14 UTC, komagata commented on test/system/notification/reports_test.rb
> +    wait_for_vuejs
これ、中身は単なるsleepなので、できれば使いたくない感じなんですよね。
vue.jsで表示しているものが表示されるまで待つような処理をきちんと書きたい感じがします。

理由はsleepだと不要な場合でも必ずその秒数待つのでテストが遅くなるのと、重さなどでその秒数を単に超えるとエラーになり、flakyなテストになっちゃうからです。

2022-02-09 07:57 UTC, maeda-seina commented on test/system/notification/reports_test.rb
> +    wait_for_vuejs
@komagata さん
了解いたしました！
前教えていただきた、findメソッドを使ってテスト作成できるかやってみます！💪

2022-02-09 14:02 UTC, maeda-seina commented
@komagata さん
お疲れ様です。
再度レビューのほどよろしくお願い致します🙏
（先日komagataさんに教えて頂いたコードを参考にテストコードの修正を行いました。）

参考
https://github.com/fjordllc/bootcamp/blob/main/test/system/comments_test.rb#L52
https://github.com/fjordllc/bootcamp/blob/main/app/javascript/comments.vue

2022-02-14 06:02 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-14 06:02 UTC, merged