日報のテキストエリアの高さが自動で大きくなることを確認するテストを追加
fjordllc/bootcamp pull request #4143
Opened 2022-02-05 08:13 UTC by R-Tsukada

[#issue4057](https://github.com/fjordllc/bootcamp/issues/4057)
### 概要
日報のテキストエリアの高さが、文字数に応じて自動で大きくなることを確認するテストを追加しました。
以前に日報がnew以外のときにmarkdownが効かなくなったことがあるようなので（[こちらのPR](https://github.com/fjordllc/bootcamp/pull/3964))、新規作成時と編集時のテストを追加しています。

2022-02-05 08:34 UTC, R-Tsukada commented
@eatplaynap 
お手隙の際にコードレビューをお願いします🙏

2022-02-07 11:59 UTC, eatplaynap requested changes
@R-Tsukada 
実装お疲れさまです〜！テストコードをちゃんと読んだことがなかったのでとても勉強になりました！
テストの内容は問題なさそうですが、テスト名はハイフン無しに変更した方が統一感があってよさそうだと思いました😄
コメントに自分だったらこういうテスト名にするかな…と考えてみましたが、ご参考にされるかはおまかせします！！

2022-02-07 11:59 UTC, eatplaynap commented on test/system/reports_test.rb
> +  test 'textarea-of-new-report-automatically-resize' do
`'textarea-of-new-report-automatically-resize'` ですが、他のテスト名はハイフン区切りではないので、統一してハイフンなしのほうがいいかな？と思いました〜🙌
ちなみに自分だったら`'automatically resizes textarea of a new report'` という名前がわかりやすいかなって思います😄

2022-02-07 11:59 UTC, eatplaynap commented on test/system/reports_test.rb
> +  test 'textarea-of-edit-report-automatically-resize' do
こちらも同様にハイフンなしのほうが統一感があってよさそうです！
同じように自分だったら`'automatically resizes textarea of an edit report'`とかにするかもです〜😄

2022-02-08 07:45 UTC, R-Tsukada commented on test/system/reports_test.rb
> +  test 'textarea-of-new-report-automatically-resize' do
なぜかハイフンをつけてしまっていました🙏ご指摘ありがとうございます。
テスト名の提案もありがとうございます！英語弱いので助かります！

2022-02-08 07:46 UTC, R-Tsukada commented on test/system/reports_test.rb
> +  test 'textarea-of-edit-report-automatically-resize' do
修正と提案ありがとうございます🙏

2022-02-08 07:46 UTC, R-Tsukada commented
@eatplaynap 
レビューありがとうございます！
提案していただいた内容を修正しましたので、ご確認をお願いします🙏

2022-02-09 05:50 UTC, eatplaynap commented
@R-Tsukada 
修正ありがとうございます！LGTMです〜:+1:

2022-02-09 05:59 UTC, R-Tsukada commented
@eatplaynap 
確認ありがとうございます！
レビューをapproveにしてもらいたいです🙏

2022-02-09 06:00 UTC, R-Tsukada commented
@komagata 
チームメンバーのレビューが通りましたので、ご確認をお願いします🙏

2022-02-09 07:09 UTC, komagata approved these changes
まさにこんな感じのテストができると良いな〜と思ってました。
ありがとうございます〜！

2022-02-09 07:09 UTC, merged

2022-02-09 07:33 UTC, eatplaynap commented
@R-Tsukada 
すみません、komagataさんに確認したところ、mergeされてしまったのでapproveに変更できないみたいです😭
以後気をつけます🙏！！