ユーザーの検索結果に、管理者でログインしたときだけそのユーザーの相談部屋へのリンクを表示
fjordllc/bootcamp pull request #4147
Opened 2022-02-05 12:59 UTC by ot0m1

ref: #4068

# 要件
ユーザーの検索結果に、管理者でログインしたときだけそのユーザーの相談部屋へのリンクを表示する。

# 画面イメージ

# 確認方法
1. `` ブランチをローカルに持ってくる（参考：https://qiita.com/great084/items/ad74dd064a2c2bc47cff ）
```
git fetch origin pull/{このプルリクエストのid}/head:{任意のブランチ名}
git checkout {上記でfetchした任意のブランチ名}
```
2. のアカウントでログイン
3. （ http://localhost:3000/ ）にアクセスしてが表示されていることを確認

2022-02-14 12:29 UTC, ot0m1 commented
@haruguchi-yuma お疲れ様ですレビューお願いいたします。
一部通らないテストがあったので、 https://github.com/fjordllc/bootcamp/pull/4203 を先取って取り込んでいます。

2022-02-16 13:12 UTC, haruguchi-yuma reviewed
レビュー遅くなりました！数点コメントしたのでご確認ください:bow:

全体的なところで1点。
相談部屋のリンクが表示される、されないは重要なことだと思いますのでテストがあってもいいのかなぁ〜と思いました！

よろしくお願いします🙏

2022-02-16 13:12 UTC, haruguchi-yuma commented on app/helpers/search_helper.rb
> +  end
おそらく`talk?`メソッドは`boolean`を戻り値にしたいと思うんですが`&&`の右辺まで評価が進むと相談部屋オブジェクトが戻り値になるのでちょっと驚きがある気がします！

こんな感じはどうでしょうか？という提案です。またSQL叩かなくて済むというメリットもあります。

```ruby
def talk?
  searchable.instance_of?(User) && searchable.talk.present?
end
```

2022-02-16 13:12 UTC, haruguchi-yuma commented on app/helpers/search_helper.rb
> +  end
Viewに関することというよりはインスタンスに依存するコードなのでモデルに書いた方がいい気がするのですが、自信はないです😅

2022-02-16 15:08 UTC, haruguchi-yuma commented on app/helpers/search_helper.rb
> +  end
もしくは、現状`talk_id`というメソッドを使うところが他になさそうなのでjbuilderの方に直接
```ruby
if talk?(searchable) && display_talk?(searchable)
  json.talk_id searchable.talk.id
end
```
と記述してもいいかもしれません。

2022-02-19 11:13 UTC, ot0m1 commented on app/helpers/search_helper.rb
> +  end
> 右辺まで評価が進むと相談部屋オブジェクトが戻り値になるのでちょっと驚きがある

確かにその通りですね🙏 修正しました。

2022-02-19 11:15 UTC, ot0m1 commented on app/helpers/search_helper.rb
> +  end
`talk_id` というメソッド名がご指摘いただいたようなコードを読んでいてのひっかかりポイントになっているのかなと考え、メソッド名の変更で対応しました。

2022-02-19 11:17 UTC, ot0m1 commented
@haruguchi-yuma レビューありがとうございました🙏
ご指摘いただいた箇所と、また自分でもクエリ発行箇所の多さが気になったのでその他の部分も変更し、テストを追加いたしました。再レビューお願いいたします。

2022-02-21 05:55 UTC, komagata requested changes

2022-02-21 05:55 UTC, komagata commented on app/helpers/search_helper.rb
> +  def talk?(searchable)
対応するhelperのテストがあるといいかもです〜

2022-02-21 13:10 UTC, haruguchi-yuma commented on app/helpers/search_helper.rb
> +  end
@ot0m1 
返事遅くなりました！

伝え方が悪くて申し訳ないです😅

メソッド名が引っかかっているというよりは`helper`メソッドは見た目の部分に関することを記述すると思うので`talk_id`を取得するようなコード（SQLを叩くコード）はここに記述しない方がいいのでは？という疑問から発言しました。

２つ目のコメントは`talk_id`を返すメソッドにそこまで汎用性がなさそうなのでjbuiderの方に記述すればメソッドを定義しなくても済むのかなぁと思ってコメントさせてもらいました！

2022-02-22 11:35 UTC, ot0m1 commented on app/helpers/search_helper.rb
> +  end
User は talk というカラムを持っていないのでメソッドにして `Talk.find_by(user_id: searchable.id).id` を実行しないと思い込んでいた（そのため https://github.com/fjordllc/bootcamp/pull/4147#discussion_r810479208 みたいなコメントをしている）ので、ご指摘の通りに修正いたしました。

モデルで `belongs_to :user`、 `has_one :talk, dependent: :destroy` という宣言が行われていたのを把握しておらず、ずれた方向でリファクタリングを進めてしまっておりました🙏

2022-02-22 11:49 UTC, ot0m1 commented on app/helpers/search_helper.rb
> +  def talk?(searchable)
ヘルパーテストを追加するみたいな考えが全くありませんでした🙏
追加しました。

2022-02-22 11:56 UTC, ot0m1 commented
@haruguchi-yuma 諸々修正いたしました。何度もすいませんがレビューお願いいたします〜🙏

2022-02-25 06:46 UTC, haruguchi-yuma reviewed
返信遅れてしまってごめんなさい:bow:
テストについて1点だけコメントしました。その他の変更については大丈夫だと思います！

2022-02-25 06:46 UTC, haruguchi-yuma commented on test/helpers/search_hepler.rb
> +  end
`false`の場合もテストしておいた方がいいのかもしれません。

2022-02-25 11:16 UTC, ot0m1 commented on test/helpers/search_hepler.rb
> +  end
追加しました。

2022-02-25 11:17 UTC, ot0m1 commented
@haruguchi-yuma テストに `false` のケースを追加しました。再度レビューお願いいたします。

2022-02-27 06:19 UTC, haruguchi-yuma approved these changes
レスポンス遅くて申し訳ないです！
確認しました〜。OKです！🙆

2022-02-27 13:32 UTC, ot0m1 commented
@haruguchi-yuma レビューありがとうございました。
@komagata レビューお願いいたします。

2022-02-28 06:16 UTC, komagata requested changes

2022-02-28 06:16 UTC, komagata commented on test/helpers/search_hepler.rb
> +class  SearchHelperTest < ActionView::TestCase
```suggestion
class SearchHelperTest < ActionView::TestCase
```

2022-03-01 11:37 UTC, ot0m1 commented
@komagata 
すごい初歩的な確認漏れをしておりました🙏
修正しましたので再度レビューお願いいたします。

2022-03-01 18:12 UTC, komagata requested changes

2022-03-01 18:12 UTC, komagata commented on test/helpers/search_hepler.rb
> +  test 'does it return correct boolean value in talk' do
「talkかどうかを返す」みたいな内容でいいと思います〜。

2022-03-02 15:48 UTC, ot0m1 commented on test/helpers/search_hepler.rb
> +  test 'does it return correct boolean value in talk' do
テスト名変更しました。

2022-03-02 15:48 UTC, ot0m1 commented
@komagata レビューいただいた点を修正しました。再レビューお願いいたします。

2022-03-03 11:40 UTC, komagata requested changes

2022-03-03 11:40 UTC, komagata commented on test/helpers/search_hepler.rb
> +    assert_equal true, talk?(user)
trueかどうかのチェックは`assert`メソッドがいいと思います。

2022-03-03 13:45 UTC, ot0m1 commented on test/helpers/search_hepler.rb
> +    assert_equal true, talk?(user)
アサーションの種類について全然把握していませんでした🙇‍♂️

[Rails テスティングガイド](https://railsguides.jp/testing.html#%E5%88%A9%E7%94%A8%E5%8F%AF%E8%83%BD%E3%81%AA%E3%82%A2%E3%82%B5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3)を見て assert と assert_not を用いるのが良いことを理解しました。

2022-03-03 13:45 UTC, ot0m1 commented
@komagata 何度もレビューありがとうございます〜🙏  ご指摘いただいた点を修正いたしました。ご確認お願いいたします。

2022-03-06 18:30 UTC, komagata requested changes

2022-03-06 18:30 UTC, komagata commented on test/helpers/search_hepler.rb
> +    assert true, talk?(user)
assertは引数を一つとるはずです〜

2022-03-07 01:02 UTC, ot0m1 commented on test/helpers/search_hepler.rb
> +    assert true, talk?(user)
ドキュメントを理解できていませんでした😭修正しました。

2022-03-07 01:03 UTC, ot0m1 commented
@komagata 何度もレビューお手数おかけします🙏 再度レビューお願いいたします。

2022-03-07 14:03 UTC, komagata commented on test/helpers/search_hepler.rb
> +    assert_not talk?(user)
複数回使う必要がないのであれば代入せずこのようにするとスマートかもです〜

```suggestion
    assert talk?(users(:kimura))
    assert_not talk?(users(:taikai3))
```

2022-03-08 10:44 UTC, ot0m1 commented on test/helpers/search_hepler.rb
> +    assert_not talk?(user)
ご指摘の通り冗長な変数宣言だと思いましたので修正いたしました。

2022-03-08 11:13 UTC, ot0m1 commented
@komagata 再レビューお願いいたします🙏

2022-03-10 04:03 UTC, komagata commented on test/system/searchables_test.rb
> +  test 'check that link to talk room is displayed properly' do
- 管理者で相談部屋へのリンクが表示される
- 管理者以外で相談部屋へのリンクが表示されない

こちらは二つのテストケースに分けた方がテストのタイトルと合わせてわかりやすいかもです〜

2022-03-10 11:49 UTC, ot0m1 commented on test/system/searchables_test.rb
> +  test 'check that link to talk room is displayed properly' do
確かに…🙏  分割しました。

2022-03-10 11:50 UTC, ot0m1 commented
@komagata 再レビューお願いいたします。

2022-03-10 14:34 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-10 14:34 UTC, merged