Feature/add wip function to qa page
fjordllc/bootcamp pull request #4157
Opened 2022-02-06 14:50 UTC by Paru871

2022-02-09 02:40 UTC, Paru871 commented
@machida
お疲れさまです。時間がかなりかかってしまいましたがQ&AページのWIP機能付加の作業が終わりました。
新しく表示する内容はdescription欄のスクリーンショットにてご案内しました。
お手すきの際に、表示項目の内容と場所のチェックとデザインをつけていただきたく、よろしくお願いします🙏

※質問一覧ページの公開済の質問については日時2つのあとにコメント数が入るためかなり長くなりますので、質問者の名前の下に置きました。1質問1段ずつ表示が増えていますのでその分ページが長くなってしまっています。その影響等も見ていただけましたら幸いです。

2022-02-15 03:58 UTC, machida commented
@Paru871 遅くなってすいません。デザインほぼOKでしたー ちょっとだけ修正しました。レビューをお願いしますー

最新の main を rebase したので、pull --rebase origin feature/add-wip-function-to-qa-page をお願いします🙏

2022-02-15 04:02 UTC, Paru871 commented
@machida 
お忙しいなかさっそくデザインのチェックをしてくださりありがとうございました🙏
確認させていただき、メンバーさんへのレビューに進みます。

2022-02-15 05:26 UTC, Paru871 commented
@eatplaynap 
お疲れさまです。お手すきの際にレビューをよろしくお願いします🙏

2022-02-23 06:12 UTC, eatplaynap commented
既存の質問と新規で登録される質問の両方のケースを考慮されていそうに見えました。
新規の質問は値が適切に設定されるように見えました。
理想としては、wipがfalseのときは、published_atに値が入っているのが望ましいと思いますが、現在、既存の質問は下記のような状態になっているようです。
- published_at に値が入っていない
- wip がfalse

既存の質問のデータの状態を考慮してコードを書いているため、いろいろなところが複雑になっていそうだと思いました。
既存の質問にはpulished_atをつめてしまえばこの考慮が必要なくなり、コードの複雑性が取り除けるためもっといいコードになりそうだと思いました。
もしよいと思っていただければ、変更をご検討ください。
変更するとコードが大きく変わってしまいそうなので、変更後に再度レビューさせていただければと思います。

2022-02-24 01:59 UTC, eatplaynap requested changes

2022-02-24 01:59 UTC, eatplaynap commented on test/system/notification/questions_test.rb
> +  test 'Do not notify if create question as WIP' do
テスト名、少しわかりづらいかもなので自分だったらこう書くかな〜と思った名前を書いていきます！
`should not notify when a WIP question was created`

2022-02-24 01:59 UTC, eatplaynap commented on test/system/notification/questions_test.rb
> +  test 'Do not notify if update question as WIP' do
`should not notify when a WIP question was updated`

2022-02-24 01:59 UTC, eatplaynap commented on test/system/notification/questions_test.rb
> +  test 'notify if update question as WIP to published' do
`notify when a WIP question with modification was updated to be published`

もしくは`send notification when a WIP question was updated and ready to be published`が個人的には分かりやすいかもと思ったのですが、テスト名としては冗長なのでよくないかもです🤔

2022-02-24 01:59 UTC, eatplaynap commented on test/system/notification/questions_test.rb
> +  test 'notify if update question as WIP to published without modification' do
`notify when a WIP question without modification was updated to be published`

2022-02-27 11:51 UTC, Paru871 commented on test/system/questions_test.rb
> +    assert_selector '.thread-list-item-meta__item'
ありがとうございます！
こちらのテストではQ&A一覧ページにwip保存した質問が表示されているかどうかの確認をしたかったのですが、わかりにくかったため他の方法に修正しました。

2022-02-27 11:53 UTC, Paru871 commented on test/system/questions_test.rb
> +    Question.create(title: 'WIPtest', description: 'WIPtest', user: user, wip: true)
なるほど、`user.questions.create`の書き方を初めて知りました！
テストは全面的に書き直しましたのでこの部分は削除してしまったのですが、新しいテストでこの書き方を採用させていただきました。ありがとうございます！

2022-02-27 11:53 UTC, Paru871 commented on test/system/questions_test.rb
> +  test 'create question as WIP with blank description to fail create' do
こちらは不要なテストでしたので削除いたしました。ありがとうございます！

2022-02-27 11:56 UTC, Paru871 commented on test/system/questions_test.rb
> +    visit_with_auth new_question_path, 'kimura'
ありがとうございます！
ルーティングの書き方を統一するという視点がありませんでした。
テストファイルの今までの記述方法に合わせてルーティングの書き方を統一してテストを作成し直しました。

2022-02-27 11:57 UTC, Paru871 commented on test/system/questions_test.rb
> +  test 'update a question as wip to published' do
英語がめちゃくちゃでお恥ずかしい限りです😰
教えていただいたテスト名を採用させていただき、テストを全面的に作成し直しました。
英語を教えてくださってありがとうございます！

2022-02-27 11:58 UTC, Paru871 commented on test/system/questions_test.rb
> +      fill_in 'question[title]', with: updated_question[:title]
書いてくださったとおり、変数に入れる意味が全くありませんでした。
文字列で直接書く方法に変更しました。ありがとうございます！

2022-02-27 12:00 UTC, Paru871 commented on test/system/questions_test.rb
> +    question.reload
他のテストを参考に作成していたところこのような記述を見たので「これを書いておくといいのかな？」くらいの気持ちで使ってしまいました。失礼しました。
使う必要がありませんでしたので削除をして、テストを全面的に書き直しました。
ありがとうございます！

2022-02-27 12:02 UTC, Paru871 commented on test/system/questions_test.rb
> +  test 'update a question as published to wip' do
英語で正確に内容が伝わるテスト名を教えていただけて本当にありがたいです。
そのまま採用させていただき、テストを書き直しました。ありがとうございます！

2022-02-27 12:03 UTC, Paru871 commented on test/system/questions_test.rb
> +      fill_in 'question[title]', with: updated_question[:title]
こちらも変数は不要でした。直接値を書く方法に変更しました。
ありがとうございます！

2022-02-27 12:05 UTC, Paru871 commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :description, :user_id, :resolve, :practice_id, :tag_list, :wip)
大事な部分を気づいてくださってありがとうございます！
こちらは他のWIP機能の書き方を参考にして書き加えたのですが、不要になったのに削除するのを忘れていました。
削除の修正を行いました。

2022-02-27 12:07 UTC, Paru871 commented on app/javascript/question.vue
> +  :class='question.has_correct_answer ? "is-solved" : question.wip ? "is-wip" : ""'
ありがとうございます。確かに三項演算子のネストではわかりにくいですよね。
computedに条件分岐を記載してメソッドにする方法に修正しました。

2022-02-27 12:10 UTC, Paru871 commented on app/javascript/question-page.vue
> +      @do-reload='doReload'
ありがとうございます！
この上の行で関数の指定が続いていたので、 `v-on`の呼び出しも関数の形にしたほうがいいのかと思ってしまいました。
直接fetchQuestion関数を呼び出す方法に修正しました。

2022-02-27 12:14 UTC, Paru871 commented on app/models/question.rb
> +  def first_public?
こちらは質問が作成及び更新された際に、メンターさんへ通知を送るのに「これが初めての本公開かどうか(いきなり公開・wipから公開)」を調べるためにメソッドを作りました。
わかりにくかったため、メソッド名を`will_be_published?`に変更しました。ありがとうございます！

2022-02-27 12:16 UTC, Paru871 commented on test/fixtures/questions.yml
> +  wip: false
ありがとうございます！確かに書いてくださったとおりだと思いました。
wip中のテスト用データがなかったので1件追加し、その他は既存のテスト用データを使う方法に変更しました。

2022-02-27 12:19 UTC, Paru871 commented on app/models/question_callbacks.rb
> +    send_notification_to_mentors(question)
ありがとうございます！
callbacksファイルの内容を見直すと同時に、データマイグレーションで既存の質問全てに対してcreated_atをpublished_atに一括で埋め込む方法に変更しましたので、今後は既存の質問の更新時に通知が送られることはなくなりました。その確認のテストも追加しました。

2022-02-27 12:30 UTC, Paru871 commented on test/system/questions_test.rb
> +  end
テストが必要なケース全部を挙げてくださってありがとうございました。
新しい`test/system/questions_test.rb`では、下記の行で対応してテストを全面的に書き直しました。
- WIPの質問を作って新規登録する・・・L270
- WIPの質問を編集してWIPとして登録する・・・L280
- WIPの質問を編集して公開中として登録する・・・L292
- 公開中の質問を編集してWIPとして登録する・・・L304
- Q&A一覧ページにWIPの質問を表示する・・・L316

2022-02-27 12:40 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  end
こちらもテストが必要なケースをすべて挙げてくださってありがとうございました！
テストの全面書き直しを行いました。新しい`test/system/notification/questions_test.rb`では下記の行で対応しました。
- before WIP
    - 1 [更新] 公開 -> 公開 expect to 通知きてほしくない・・・L53
    - 2 [更新] 公開 -> WIP expect to 通知きてほしくない・・・L70
- after WIP
    - 3 [作成] (無) -> WIP expect to 通知きてほしくない・・・L87
    - 4 [作成] (無) -> 公開 expect to 通知きてほしい・・・L103
    - 5 [更新] WIP -> WIP expect to 通知きてほしくない・・・L119
    - 6 [更新] WIP -> 公開 expect to 通知きてほしい・・・内容変更ありで更新L143、内容変更なしで更新L167
    - 7 [更新] 公開 -> WIP expect to 通知きてほしくない・・・内容変更ありで更新L187、内容変更なしで更新L213
    - 8 [更新] 公開 -> 公開 expect to 通知きてほしくない・・・L235
   
※上記の6番と7番は、状態がWIP -> 公開、公開 -> WIPと公開状態が変化するため、内容変更があり/なしの2種類のテストを書きました。

2022-02-27 12:41 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'Do not notify if create question as WIP' do
英語のテスト名を考えてくださってありがとうございました！
ものすごくテストしたい内容にぴったりな英語だと思いましたのでそのまま採用させていただきました。

2022-02-27 12:43 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'Do not notify if update question as WIP' do
英語のテスト名を考えてくださってありがとうございました！
テストしたい内容にぴったりな英語だと思いましたのでそのまま採用させていただきました。

2022-02-27 12:45 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'notify if update question as WIP to published' do
こちらも英語のテスト名を2通りも考えてくださってありがとうございます！
他のテスト名に合わせて短い方を使わせていただくことにしました。

2022-02-27 12:45 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'notify if update question as WIP to published without modification' do
英語のテスト名を考えてくださってありがとうございました！
テストしたい内容にぴったりな英語だと思いましたのでそのまま採用させていただきました。

2022-02-27 12:55 UTC, Paru871 commented
@eatplaynap 
このたびはお忙しいなか、プルリクのたくさんの変更部分について細かい部分までご覧いただき、とても丁寧なレビューをくださいましてありがとうございました。
たくさんのコメントでご指摘くださったことを1つずつ対応し、修正作業を行いました。

> 理想としては、wipがfalseのときは、published_atに値が入っているのが望ましいと思ったのですが、現在、既存の質問は下記のような状態になっているようです。
> 
> published_at に値が入っていない
> wip がfalse
> 既存の質問のデータの状態を考慮してコードを書いていることが原因で、いろいろなところが複雑になっていそうな感じがしました！
> 既存の質問にはpulished_atをつめてしまえばこの考慮が必要なくなり、コードの複雑性が取り除けるためもっとよいコードになりそうだと思います🥺

上記は書いてくださったとおりだと思いましたので、既存の質問すべてのpublished_atにcreated_atのタイムスタンプを埋め込むデータマイグレーションのファイルを作成しました。
これによって複雑な状態の切り分けの多くが必要なくなって、かなりシンプルになったと思います。

現在、CIテストが通らないようですので、テストを通過できましたら再レビューのお願いを改めて送らせていただきます。
取り急ぎ、がっちりとレビューしていただいたお礼をお伝えしたいと思いました。ありがとうございました！

2022-02-28 12:59 UTC, Paru871 commented
@eatplaynap 
お疲れさまです。レビューいただいた後の修正に時間がかかり申し訳ありません！
いただいたコメントそれぞれにリプライさせていただきましたが、ご指摘いただいた点は全て書いてくださったとおりだと思いましたので、修正を行いました。

大きく変更したことを下記にまとめました。

-----

## 今回の大きな変更点

- 最初にデータマイグレーションを行う方法に変更しました。
	- `db/data/20220226162158_copy_timestamp_created_at_to_published_at_for_questions.rb`を作成し、本番環境の既に公開済の質問の`published_at`には`created_at`を埋め込んでおく
	- これによって、`published_at`が`nil`の場合は下記の2通りのどちらかになるため、条件分岐の複雑さが軽減されました。
		- まだ公開したことがないWIP中
		- いきなり公開
	- 開発環境及びステージング環境用データとテスト用データにはfixtures/ymlファイルのデータそれぞれに `created_at`と同日の`published_at`を指定することで対応しました。 

- `published_at`のタイムスタンプ代入と保存のタイミングを変更しました。
	- (変更前 callbacksで設定)質問をcreateまたはupdate後に`！wip && published_at.nil'のとき、`published_at`に現在時刻を代入してsave
	- (変更後 modelで設定)質問をcreateまたはupdate前に`！wip && published_at.nil'のとき、`published_at`に現在時刻を代入してからcreateまたはupdate

- テストを全面的に作成し直しました。(3ファイル)
	- test/models/question_test.rb
		- modelに追加したメソッド2つについての単体テスト(privateメソッドですがテスト作成しました。)
	- test/system/questions_test.rb
		- WIPの質問を作って新規登録する・・・L270
		- WIPの質問を編集してWIPとして登録する・・・L280
		- WIPの質問を編集して公開中として登録する・・・L292
		- 公開中の質問を編集してWIPとして登録する・・・L304
		- Q&A一覧ページにWIPの質問を表示する・・・L316
	- test/system/notification/questions_test.rb
		- before WIP
    		- 1 [更新] 公開 -> 公開 expect to 通知きてほしくない・・・L53
    		- 2 [更新] 公開 -> WIP expect to 通知きてほしくない・・・L70
		- after WIP
    		- 3 [作成] (無) -> WIP expect to 通知きてほしくない・・・L87
    		- 4 [作成] (無) -> 公開 expect to 通知きてほしい・・・L103
    		- 5 [更新] WIP -> WIP expect to 通知きてほしくない・・・L119
    		- 6 [更新] WIP -> 公開 expect to 通知きてほしい・・・内容変更ありで更新L143、内容変更なしで更新L167
    		- 7 [更新] 公開 -> WIP expect to 通知きてほしくない・・・内容変更ありで更新L187、内容変更なしで更新L213
    		- 8 [更新] 公開 -> 公開 expect to 通知きてほしくない・・・L235
   
        - ※上記の6番と7番は、状態がWIP -> 公開、公開 -> WIPと公開状態が変化するため、内容変更があり/なしの2種類のテストを書きました。

- 記述方法が正しいか確認していただきたいこと(正常に動作することとテストが通ることは確認済です)
`app/models/question_callbacks.rb`内の5行目、
```
return unless question.saved_change_to_attribute?(:published_at, from: nil)
```
この変更点リストの2つめに書きました、「`published_at`のタイムスタンプ代入と保存のタイミングを変更」によって、通知を飛ばすcallbacks内の条件の設定を変更する必要があったため、上記のように `saved_change_to_attribute?`を使って直前の保存時に`published_at`が`nil`から変更があったかどうかのメソッドを使用することにしました。
[ActiveRecord::AttributeMethods::Dirty](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Dirty.html#method-i-saved_change_to_attribute-3F)
これで正しいかどうかをご一緒にチェックしていただけましたら助かります。

-----

変更点は以上です。
またお手数をおかけしてしまいますが再度レビューいただきたく、どうぞよろしくお願いします🙏

2022-03-04 10:39 UTC, Paru871 commented
@eatplaynap
本日、1つ不具合を見つけたので追加で修正を行いました。
こちらも併せてご確認とレビューいただけましたら助かります！
よろしくお願いいたします🙇‍♀️

### 修正したこと
質問一覧ページのユーザー名をクリックしてもリンクが張られていないのでプロフィールページが開かないため、修正してリンクを張った
### 修正ファイル
- `app/javascript/question.vue`
- `test/system/questions_test.rb` ・・・L305(このテスト名は「ユーザープロフィールへのリンクがあることを確認」という意味にしたいので`exist`を使ったのですがおかしい気がします。適切な英語を教えてください〜🙏)

### 修正前
![profile_link1](https://user-images.githubusercontent.com/82434093/156747184-2442623f-514e-49c2-8958-12655494d97c.png)
### 修正後
![profile_link2](https://user-images.githubusercontent.com/82434093/156747216-56511fd8-9876-497f-84cc-413295a86499.png)

2022-03-08 06:45 UTC, eatplaynap commented
@Paru871 
修正お疲れさまです！レビュー返信遅れてすみません🙏
以下一緒にペアプロしてすべて確認OKです！細かいところだけ修正依頼出させていただきましたのでご確認お願いします〜！

- 最初にデータマイグレーションを行う方法に変更しました。(変更理由:通知を送る条件分岐が複雑すぎるため)

- `published_at`のタイムスタンプ代入と保存のタイミングを変更しました。(変更理由:コールバックafter_save内でsaveが使用されていて循環のリスクがあるため)

- テストを全面的に作成し直しました。(3ファイル)

- 記述方法が正しいか確認していただきたいこと(正常に動作することとテストが通ることは確認済です)

2022-03-08 06:46 UTC, eatplaynap requested changes

2022-03-08 06:46 UTC, eatplaynap commented on test/models/question_test.rb
> +end
このモデルのテストはいらなそう？

2022-03-08 08:26 UTC, Paru871 commented on test/system/questions_test.rb
> +    within('.form') do
ありがとうございます！formタグを指定する方法に修正しました。

2022-03-08 08:26 UTC, Paru871 commented on test/system/questions_test.rb
> +  end
ありがとうございます！ページ遷移が無事にできることを確認するテストに修正しました。
テスト名の英語も考えてくださってありがとうございました。

2022-03-08 08:27 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +    within('.form') do
ありがとうございます！formタグを指定する方法に修正しました。

2022-03-08 08:27 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +    within('.form') do
ありがとうございます！formタグを指定する方法に修正しました。

2022-03-08 08:28 UTC, Paru871 commented on app/javascript/question.vue
> +    isClass() {
ありがとうございます。questionClassをメソッド名にさせていただきました！

2022-03-08 08:28 UTC, Paru871 commented on app/javascript/question.vue
> +        return ``
ありがとうございます。シングルクォートに修正しました。

2022-03-08 08:29 UTC, Paru871 commented on app/views/api/questions/_question.json.jbuilder
> +  json.published_at l(question.created_at)
ありがとうございます。データマイグレーションがあるのでcreated_atを埋め込む必要はありませんでした。
修正しました！

2022-03-08 08:30 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +      fill_in('question[description]', with: 'WIP本文')
ありがとうございます！カッコを取り除きました。

2022-03-08 08:30 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'notify when a published question was created' do
テスト名の英語を修正してくださってありがとうございます！

2022-03-08 08:30 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'should not notify when a WIP question was created' do
テスト名の英語を修正してくださってありがとうございます！

2022-03-08 08:31 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +    within('.form') do
ありがとうございます。formタグを使ってカッコを除去しました。

2022-03-08 08:31 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'notify when a WIP question with modification was updated to be published' do
テスト名の英語を考えてくださってありがとうございました。

2022-03-08 08:31 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +    within('.form') do
ありがとうございます。formタグを使ってカッコを除去しました。

2022-03-08 08:31 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'notify when a WIP question without modification was updated to be published' do
テスト名の英語を考えてくださってありがとうございました。

2022-03-08 08:32 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +    within('.form') do
ありがとうございます。formタグを使ってカッコを除去しました。

2022-03-08 08:32 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'should not notify when a published question with modification was updated to be WIP' do
テスト名の英語を考えてくださってありがとうございました。

2022-03-08 08:32 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +    within('.form') do
ありがとうございます。formタグを使ってカッコを除去しました。

2022-03-08 08:32 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +  test 'should not notify when a published question without modification was updated to be WIP' do
テスト名の英語を考えてくださってありがとうございました。

2022-03-08 08:32 UTC, Paru871 commented on test/system/notification/questions_test.rb
> +    within('.form') do
ありがとうございます。formタグを使ってカッコを除去しました。

2022-03-08 08:33 UTC, Paru871 commented on test/models/question_test.rb
> +end
privateメソッドでしたのでモデルのテストは不要でした。ファイル全体を削除しました。ありがとうございます！

2022-03-08 08:46 UTC, Paru871 commented
@eatplaynap 
お疲れさまです。再度のレビューをいただきましてありがとうございました。
本日いただいたポイントを全て修正しましたので、ご確認をなにとぞよろしくお願いいたします🙏

2022-03-09 08:24 UTC, eatplaynap approved these changes
@Paru871
修正ありがとうございました〜！細かいところも対応いただきすごく良いコードになったと思います😄LGTMです💪
個人的にレビューの方法だけでなく、Vueが絡んだ新規機能の追加の概要、テストケースの考え方、よい命名についてなどたくさん学ぶことがあり、ご依頼いただいて本当に勉強になりありがたかったです🙏

2022-03-09 08:54 UTC, Paru871 commented
@eatplaynap 
この度は長期間に渡って細かい部分まで丁寧にチェックとレビューをしてくださって本当にありがとうございました。
私にとってもこの修正の作業で学ぶことがたくさんあり、このIssueにトライさせていただいて本当に良かったと思っています。
今後ともどうぞよろしくお願いいたします。

2022-03-09 08:55 UTC, Paru871 commented
@komagata 
お疲れさまです。
チームメンバーさんのレビューのOKをいただきましたので、お手すきの際にチェックをよろしくお願いいたします🙇🏻‍♀️

2022-03-10 14:10 UTC, komagata commented on app/javascript/question-edit.vue
> +    updateQuestion({ wip }) {
この引数はなぜ単に`updateQuestion(wip)`ではなくhashに入れてるんですかね？

2022-03-11 11:57 UTC, Paru871 commented on app/javascript/question-edit.vue
> +    updateQuestion({ wip }) {
@komagata 
さっそくレビューいただきありがとうございます！

この部分はもともとはwipにするかしないかのbooleanを渡すために下記のように記述していました。
```
//呼び出し元(wipのbooleanを渡す)
updateQuestion(true)
updateQuestion(false)

//関数
updateQuestion(wip) {
```

しかし、呼び出し元でwipのbooleanを渡すだけだと何を渡しているのか分かりにくくなってしまうため、rubyのキーワード引数のようにわかりやすく引数を渡したいと考え、JavaScriptのオブジェクトを使って受け渡しすることで「何を渡しているのか」のわかりやすさが実現できました。

```
//呼び出し元(オブジェクトの形式で渡す)
updateQuestion({ wip: true })
updateQuestion({ wip: false })

//関数
updateQuestion({ wip }) {
```

とはいえ、ここでupdateQuestion関数に渡すものはwip以外になく何を渡すのかは自明であるため、updateQuestionの引数はオブジェクトではなく単なるbooleanが良いという判断もありだと考えています。
もしもオブジェクトを使った引数に違和感があるようでしたらbooleanに修正いたします。
よろしくお願いします🙏

2022-03-14 16:09 UTC, Paru871 commented on app/javascript/question-edit.vue
> +    updateQuestion({ wip }) {
@komagata 
かしこまりました。
updateQuestion関数の引数をbooleanに変更しました。
お手数をおかけしますが、再度ご確認をお願いいたします。

2022-03-15 03:23 UTC, komagata commented on app/views/api/questions/_question.json.jbuilder
> +  json.published_at_date_time question.published_at.to_datetime
APIは特定のページのためだけにある訳ではなく、極力汎用的である方が良いので、published_atがわかればJSの方で求められるのでAPIとして用意しなくても良いと思います。

また、日付のフォーマットも極力ロケールによらないプレーンなデータにしておいて、JS側（UI側）で見る人に合わせた内容に変換するのがいいと思います〜。

2022-03-15 11:14 UTC, Paru871 commented on app/views/api/questions/_question.json.jbuilder
> +  json.published_at_date_time question.published_at.to_datetime
@komagata 
修正ポイントを教えてくださりありがとうございます！
日時に関するデータはできる限りプレーンなデータのままJSに渡して、Vue側で表示する際の日付のフォーマットを設定する方法に変更しました。

1点質問なのですが、書いてくださった、

> published_atがわかればJSの方で求められるので

この部分の内容の理解がしっかりとはできませんでした。

こちらは上記の「できる限りプレーンなデータのままJSに渡して、Vue側で表示する際の日付のフォーマットを設定する」という対策でカバーできていますでしょうか？
お手数をおかけしますが、教えていただけましたら助かります🙏

引き続き、ご確認のほどどうぞよろしくお願いいたします。

2022-03-15 20:32 UTC, komagata commented on app/views/api/questions/_question.json.jbuilder
> +  json.published_at_date_time question.published_at.to_datetime
@Paru871 

> この部分の内容の理解がしっかりとはできませんでした。

APIの中で`l`メソッドに渡していますが、localeによって日付の表示を変えたりといったことや、timezoneによる時差などはJavascript（UIの部分）で計算して表示した方がいいという意味です〜

2022-03-15 20:33 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-15 20:33 UTC, merged

2022-03-16 01:07 UTC, Paru871 commented on app/views/api/questions/_question.json.jbuilder
> +  json.published_at_date_time question.published_at.to_datetime
@komagata 
なるほど！ご教示くださりありがとうございました。
よく理解できました。
今後、意識していきます。

2022-03-16 01:09 UTC, Paru871 commented
@komagata 
ご確認とマージいただきましてありがとうございました。このたびはたくさん学びのチャンスをいただき、感謝してもしきれません。
今後も成長できるよう頑張っていきます。引き続きよろしくお願いいたします。