メンターでログインしたときだけ「日報個別ページにXX日ぶりの日報です」と表示する
fjordllc/bootcamp pull request #4170
Opened 2022-02-07 16:09 UTC by garammasala29

2022-02-08 03:52 UTC, garammasala29 commented
@machida さん
お疲れ様です。お手隙の際に、こちらのデザインをお願いしたいです。
「XX日ぶりの日報です」に i`s-important`というclassを付けていますので、必要の際にはご活用いただけたらと思います🙏

2022-02-16 10:46 UTC, machida commented
遅くなってすいません🙇‍♂️ デザイン入れますー

2022-02-17 04:26 UTC, garammasala29 commented
@machida さん
デザインありがとうございました！
括弧を使った三項演算子は今後自分でも使ってみたいと思います😄

2022-02-17 12:22 UTC, garammasala29 commented
@machida さん
先ほどはご連絡失礼いたしました🙇‍♂️お忙しい中、デザインしていただき、ありがとうございます🙏
仕様変更とテストの件、了解いたしました！

2022-02-17 14:42 UTC, garammasala29 commented
@aim2bpg さん
お疲れ様です。お手隙の際にこちらのレビューをお願いしたいです🙏
不明点などがありましたら、何なりとお申し付けください。

2022-02-17 20:53 UTC, aim2bpg commented on .rubocop.yml
> +    - app/models/report.rb
ここは、「実装時に考慮したこと」記載の理由で追加されたのですね。初めて見る記述で勉強になりました😄
> Reportクラスの行数が多くなりrubocopが通らなかったので、他モデルと同様に無効化しています

2022-02-17 23:21 UTC, aim2bpg reviewed
@garammasala29 さん、おつかれさまです。
確認しました。コメントしましたので何点か確認させてください〜🙏

2022-02-17 23:51 UTC, aim2bpg reviewed
コメント追記しました〜ご確認お願いいたしますー🙏

2022-02-17 23:51 UTC, aim2bpg commented on app/models/report.rb
> +  end
[問題なし]ここのメソッドチェーンは他のと違って縦並びにしないのですね〜。後学のために基準をご教示くださいー🙏

2022-02-17 23:51 UTC, aim2bpg commented on app/models/report.rb
> +  end
[要確認]こちらの手元でも検算して合っていることを確認しましたー😄
```
❯ rails c
Loading development environment (Radiff.to_i               
irb(main):001:0> dt1 = DateTime.new(2020,  1, 1,  0,  0,  0)
irb(main):002:0> dt2 = DateTime.new(2020,  6, 1,  0,  0,  0)
irb(main):003:0* ## ２つのDateTimeオブジェクトの差分を表示
irb(main):004:0> diff = dt2 - dt1
irb(main):005:0* ## 日付・時間・分・秒の差をそれぞれ表示
irb(main):006:0> p "日付の差=%d" % diff.to_i
"日付の差=152"
=> "日付の差=152"
```
![image](https://user-images.githubusercontent.com/58363353/154589625-dfca98a1-7f33-4501-aca6-a6765604e2f5.png)

ちなみに、「概要」に書かれている
> wip以外の日報で間隔を計算しているので、最新日報がwipの場合や前回の日報がwipだった場合なども対応できるようにしています。

は、どのように確認されましたでしょうか〜？もしくは、テストがあるとそこから読み取れるかと思いましたー。目視確認だとリファクタリングや関連する修正が入ったときにデグレードしてないかまた目視で確認する必要が出てきそうです🥲

2022-02-17 23:51 UTC, aim2bpg commented on app/views/reports/show.html.slim
> +- if mentor_login? && !@report.first? && @report.latest?
[要確認]「概要」に書かれている
> (10日以上日報が書かれていなかった場合は赤、それ以外の場合は緑で表示)

ですが、境界値の9日と10日で確認されましたでしょうか〜？ソースコードを見てOKと判断されていないかと思ってお聞きしていますー🤔

2022-02-17 23:51 UTC, aim2bpg commented on app/views/reports/show.html.slim
> -- if flash[:notify_help]
[要確認]ここは、「実装時に考慮したこと」記載の町田さん変更分ですね〜。
> sadをつけた日報を提出した際のモーダルを表示するコードが削除されましたので、それに合わせてテストも一部修正しています

なぜ削除することになったのかがPRから読み取れなかった(過去Issueも軽く探した)のですが、書いておかれませんか〜？

2022-02-18 12:51 UTC, machida commented on app/views/reports/show.html.slim
> +- if mentor_login? && !@report.first? && @report.latest?
@aim2bpg おおー、ありがとうございます！！これ、デザイン確認のために消してたのを戻すのを忘れてました！！ここ指摘していただき助かります🙏 修正しますー

2022-02-18 13:04 UTC, machida commented
@garammasala29
すいません！ @aim2bpg さんの指摘で気づいたのですが、間違えて sad のときのモーダルを消してしまってました🙇‍♂️
これに合わせてテストを修正頂いてたのですが、消すこと自体が間違いだったので、テストも戻しておきました。
別のブランチでの作業を間違えてこっちに入れてしまってました🙇‍♂️

2022-02-18 13:14 UTC, garammasala29 commented
@machida さん
かしこまりました！経緯がわかって安心しました😄

@aim2bpg さん
自分の担当のissueなのに確認が遅れ、お手数おかけしてすみません🙏
修正しましたら再度連絡させていただきます。

2022-02-18 14:05 UTC, aim2bpg commented on app/views/reports/show.html.slim
> -- if flash[:notify_help]
@machida さん
そういうことですね、理解できました。ありがとうございますー

2022-02-19 12:19 UTC, garammasala29 reviewed
@aim2bpg さん
お疲れ様です。お忙しい中、レビューしていただきありがとうございます🙏
修正致しましたので、お手隙の際に再度レビューをお願いします！

2022-02-19 12:19 UTC, garammasala29 commented on app/models/report.rb
> +  end
短い文なので1行でいいかと、特に意図していませんでした💦
他のコードを揃えた方が見やすさにも繋がると思うので、変更しました。[49f187b](https://github.com/fjordllc/bootcamp/pull/4170/commits/49f187b4fa3652f0c7da235d53fb30bbbf9e9206)

2022-02-19 12:19 UTC, garammasala29 commented on app/views/reports/show.html.slim
> +- if mentor_login? && !@report.first? && @report.latest?
[25ebbfb](https://github.com/fjordllc/bootcamp/pull/4170/commits/25ebbfb22745abbe513828d002fcf5d8957d5ad4)でテストを作成し、境界値と色の確認ができるようにしました。
目視での確認もできるよう画像の差し替えも行いました。

2022-02-19 12:19 UTC, garammasala29 commented on app/models/report.rb
> +  end
modelでのテストが作られていなかったので、[be91ce6](https://github.com/fjordllc/bootcamp/pull/4170/commits/be91ce6d4f0ac2a8c3662987b9a9716b35b39ced)で作成しました。

2022-02-19 13:31 UTC, aim2bpg commented on test/system/reports_test.rb
> +    assert_selector '.a-page-notice.is-only-mentor', text: '9日ぶりの日報です'
こちら、赤字になっても検出されないようです。「10日ぶりの行」で`.is-danger`を消してやってみるとPassになるかと思います。これは、`.is-danger`の上位階層の`.a-page-notice.is-only-mentor`としていることで、`.is-danger`の有無に関わらず、`true`となるようです。下記ではいかがでしょうか〜？

```suggestion
    assert_no_selector '.a-page-notice.is-only-mentor.is-danger', text: '9日ぶりの日報です'
```

2022-02-19 13:35 UTC, aim2bpg commented on app/views/reports/show.html.slim
> +- if mentor_login? && !@report.first? && @report.latest?
[問題なし]セレクターでテストできるのですねー。勉強になりました〜。画像も確認いたしましたー👍

2022-02-19 13:45 UTC, aim2bpg commented on test/fixtures/reports.yml
> +    最新から10ぶりの日報です
[要確認]こちら、単位の「日」を追記ください〜

2022-02-19 13:50 UTC, aim2bpg commented on test/fixtures/reports.yml
> +    最新から10ぶりの日報です
[要確認]こちら、単位の「日」を追記ください〜

```suggestion
  title: 10日ぶりの日報
  description: |-
    最新から10日ぶりの日報です
```

2022-02-19 14:17 UTC, aim2bpg commented on test/fixtures/reports.yml
> +    最新から10ぶりの日報です
[要確認]こちら、文言を見直された方が良いかもです。「9日ぶり」と書くと、最新から9日後かと思うかもですねー
```suggestion
  title: 最新から9日前の日報
  emotion: 1
  description: |-
    最新から9日前の日報でwipにしています
    今日の気分がなしでwipから投稿ができないので、emotionを設定
  reported_on: <%= Time.now - 10.day %>
  wip: true

report34:
  user: kananashi
  title: 最新から10日前の日報
  description: |-
    最新から10日前の日報です
```

2022-02-19 14:23 UTC, aim2bpg commented on app/models/report.rb
> +  end
[問題なし]テストから確認内容の意図が読み取れましたー👍

2022-02-19 14:25 UTC, aim2bpg commented on test/models/report_test.rb
> +    assert_equal reports(:report32).interval, 10
第1引数と第2引数が逆転しているようです。[こちら](https://railsguides.jp/testing.html#%E5%88%A9%E7%94%A8%E5%8F%AF%E8%83%BD%E3%81%AA%E3%82%A2%E3%82%B5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3)をご覧ください。
```suggestion
    assert_equal 10, reports(:report32).interval
```

2022-02-19 14:37 UTC, aim2bpg commented
@garammasala29 さん、ご対応ありがとうございます。
テストが入って意図がわかりやすくなりました。もう少しお付き合いを...。

以下、3点ご確認ください。（レビュー機能に慣れておらず、コメントがバラになってしまい、すみません🙏）
- [systemテスト](https://github.com/fjordllc/bootcamp/pull/4170#pullrequestreview-887925620)
- [fixtures](https://github.com/fjordllc/bootcamp/pull/4170#pullrequestreview-887929269)
- [modelテスト](https://github.com/fjordllc/bootcamp/pull/4170#pullrequestreview-887929962)

2022-02-19 14:41 UTC, aim2bpg commented on app/models/report.rb
> +  end
他のに揃えられたのですね、承知しましたー

2022-02-20 09:44 UTC, garammasala29 commented on test/models/report_test.rb
> +    assert_equal reports(:report32).interval, 10
最初に期待値でした。確認不足ですみません。修正しています:[4eb4256](https://github.com/fjordllc/bootcamp/pull/4170/commits/4eb4256b1689c842f0266bbf5165a2a717f7baa1)

2022-02-20 09:46 UTC, garammasala29 commented on test/fixtures/reports.yml
> +    最新から10ぶりの日報です
10`日`も抜けていました、失礼いたしました。分かりやすい文言に変更しています。[76ec174](https://github.com/fjordllc/bootcamp/pull/4170/commits/76ec17432af260bbaca83b38ae727ebe5c65221d)

2022-02-20 09:51 UTC, garammasala29 commented on test/system/reports_test.rb
> +    assert_selector '.a-page-notice.is-only-mentor', text: '9日ぶりの日報です'
> .is-dangerの上位階層の.a-page-notice.is-only-mentorとしていることで、.is-dangerの有無に関わらず、trueとなるようです。

そちらの点の確認が漏れていました💦改善策までありがとうございます🙏
[5c9d298](https://github.com/fjordllc/bootcamp/pull/4170/commits/5c9d298df497faf7d4d172f5544ecf9e34c1f5d4)で修正しています。

2022-02-20 09:54 UTC, garammasala29 commented
@aim2bpg さん
お忙しい中、早速の再レビューありがとうございました。
gitの取り込みで失敗してしまい、差分が見にくくなっています。すみません🙇‍♂️
お手隙の際にご確認のほどよろしくお願いします🙏

2022-02-20 11:54 UTC, aim2bpg approved these changes
@garammasala29 さん、ご対応ありがとうございます。
私はOKです🙆‍♀️　チームリーダーレビューに進めてください👍

2022-02-20 13:21 UTC, garammasala29 commented
@aim2bpg さん
何往復もレビューしていただき、本当にありがとうございました！
大変学ぶところの多いものでした。根拠をもったコードを意識していきます💪
今後もよろしくお願いします🙏

2022-02-20 13:22 UTC, garammasala29 commented
@komagata さん
お疲れ様です。お手隙の際にこちらのレビューをお願いいたします🙏

2022-02-21 15:54 UTC, komagata requested changes

2022-02-21 15:54 UTC, komagata commented on app/models/report.rb
> +  def latest?
間違えやすい似た機能が二種類あると思います。

1. 全Reportの中の最新
2. 同じユーザーのReportの中の最新

このメソッドの名前の`Report#latest?`だと前者を想像するのが自然だと思います。
ですので、このメソッドは後者なので間違えないようにしておいた方がいいかもです〜。

2022-02-21 15:54 UTC, komagata commented on app/models/report.rb
> +  def not_wip_previous
上記のメソッドと同じ問題があるかもです〜

2022-02-22 13:13 UTC, garammasala29 commented
@komagata さん
お疲れ様です。メソッド名の変更を行いました。ご確認お願いします🙏

2022-02-26 16:34 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-26 16:34 UTC, merged