rack-dev-markというgemを追加し開発環境での作業時に目印が出るようにした
fjordllc/bootcamp pull request #4174
Opened 2022-02-08 05:27 UTC by eatplaynap

## issue
- #4035 

## 概要
[rack-dev-mark](https://github.com/dtaniwaki/rack-dev-mark)というgemを入れて、どの環境でbootpcampアプリが動いているのかを表示できるようにしました。

## 変更確認方法
1. ブランチ`feature/add-rack-dev-mark-gem`をローカルに取り込む
2. `$ rails s`でローカル環境を立ち上げる
3. テスト用ユーザーでログイン

## 変更前

## 変更後

2022-02-08 06:36 UTC, eatplaynap commented
@aim2bpg 
お疲れさまです！お手すきのときににレビューお願いいたします:pray:

2022-02-08 15:07 UTC, aim2bpg commented
@eatplaynap さん、Issue対応おつかれさまです。

`development`が表示されることを確認しました。OKです🙆‍♀️
チームリーダーレビューに進めてください〜。

本番環境で`development`が表示されないことの確認としては、以下のように理解しました👍
今回の変更は開発環境にしか及ばない。よって、本番環境で`development`が表示されることはない。
[設定ファイル\(config\) \| Railsドキュメント](https://railsdoc.com/config)

2022-02-08 15:19 UTC, aim2bpg reviewed
コメントする場所を間違えたかもです🙏
OKです🙆

2022-02-08 23:12 UTC, aim2bpg approved these changes
Approveを選択しないと承認されないのですね〜🙏
今、Approveしました。

2022-02-09 01:56 UTC, aim2bpg commented
追伸というか独り言...です。
ステージング環境で確認される際は、`development`ではなく、`staging`と表示されることが期待値かな〜と思いました😄

2022-02-09 02:14 UTC, cafedomancer commented
> 念のため、ステージング環境のstaging表示も本Issueのスコープかは確認された方が良いかもしれません🙏

目的は本番環境での誤操作を防ぐことなので、できれば development, staging のそれぞれで出ているとうれしいです！

2022-02-09 02:17 UTC, cafedomancer commented
あとデフォルトの ribbon の位置だと既存の UI パーツとかぶってしまうので、なにもなさそうな左下か右下に出しておくとよいかもしれません。

2022-02-09 03:03 UTC, aim2bpg reviewed
下記を追記するイメージですかね。（間違ってたら、すみません。。）
一旦、状態を再レビューに変更しました🙏

config/environments/test.rb
```
  config.rack_dev_mark.enable = true
```

config/application.rb
```
module MyApp
  class Application < Rails::Application
    config.rack_dev_mark.theme = [:title, Rack::DevMark::Theme::GithubForkRibbon.new(position: 'right-bottom')]
  end
end
```

参照元：https://github.com/dtaniwaki/rack-dev-mark/blob/master/THEME.md

2022-02-09 04:54 UTC, aim2bpg requested changes
レビュー前の状態に戻すには、Request Changesするのですね。
今、レビュー前の状態に戻しました🙏
（初めてなものでたびたび、すみません🔰 ）

2022-02-09 05:17 UTC, eatplaynap commented
@aim2bpg 
レビューありがとうございます〜！たくさんコメントくださってうれしいので全然気になさらないでください！
そして修正方法までご提案ありがとうございます:pray:
自分でもちょっと調べて、実装できたらまた再レビュー依頼しますね〜😄

@cafedomancer 
コメントありがとうございます！下記対応します！！
- 右下に配置させる
- development, staging のそれぞれで出ていることの確認

2022-02-09 07:47 UTC, eatplaynap commented
@aim2bpg @cafedomancer 
本日の開発ミーティングでステージング環境のstaging表示について@komagataさんと@machidaさんに相談したところ、現在のブートキャンプアプリではステージング環境と本番環境を区別する仕組みがないので、ステージング環境のstaging表示は本Issueでは対応しなくてよいそうです😅
そのため右下にリボンを配置させるご指摘のみ対応させていただきます🙏

2022-02-13 23:54 UTC, eatplaynap commented
@aim2bpg 
お疲れさまです！
「右下にリボンを配置させる」設定をしたので再レビューお願いします:pray:
↓のissueの影響でテストは落ちています😅

- #4201

2022-02-14 01:28 UTC, aim2bpg requested changes
@eatplaynap さん、おつかれさまです。
インデントで悩ましいところがありました。ご確認をお願いします🙏

なお、表示の方はバッチリでした。
左上よりも右下の方が邪魔にならなくていい感じだと思いました😄
![image](https://user-images.githubusercontent.com/58363353/153785224-230adaad-79c4-4598-8e1b-7f8a1cf5d0c3.png)

2022-02-14 01:28 UTC, aim2bpg commented on config/application.rb
> +    config.active_storage.resolve_model_to_route = :rails_storage_proxy
ここは、
- デバッグで手を入れた際に意図せず変わってしまったものか
- インデントが修正されたものか
のどちらでしょうか🤔
どちらにしても今回は修正せずに、後者は別Issueを立てて修正すべきかとも思いました。
駒形さんにお聞きした方が良いかもですね〜。

本ファイルや他のファイルを見てみると、Rails new後の追加設定に対して、インデントをスペース1つ分ズラしているという意図を感じますが、単純にズレているのに気付けていないだけかもしれません。

2022-02-14 01:28 UTC, aim2bpg commented on config/environments/development.rb
> +  config.rack_dev_mark.theme = [:title, Rack::DevMark::Theme::GithubForkRibbon.new(position: 'right-bottom')]
ここは今回追加したものなので、インデントはこのままでも良いかと思いました😄

2022-02-14 02:03 UTC, eatplaynap commented on config/application.rb
> +    config.active_storage.resolve_model_to_route = :rails_storage_proxy
@aim2bpg 
これはズレているのは単純なミスだと考え、ついでなので修正してしまいました🤔

@komagata 
この行のインデントが下がっているのは意図されたものでしょうか？
意図されていなかった場合、今回は修正せずに別issueを立てるべきでしょうか？

2022-02-15 04:28 UTC, eatplaynap commented
@aim2bpg 
インデントの件は本Issueでは修正せずに元の状態のままにしました〜！
再レビューお願いいたします:pray:

2022-02-15 04:30 UTC, aim2bpg approved these changes
@eatplaynap さん
確認しました。OKですー🙆🏻

2022-02-15 04:32 UTC, eatplaynap commented
@komagata 
チームメンバーのレビューOKが出たのでお手すきの際ご確認お願いします:pray:

2022-02-16 03:44 UTC, komagata requested changes

2022-02-16 03:44 UTC, komagata commented on config/environments/development.rb
> +  config.rack_dev_mark.theme = [:title, Rack::DevMark::Theme::GithubForkRibbon.new(position: 'right-bottom')]
@eatplaynap こちら他の部分を書いた時点でインデント間違っていたので修正お願いできるとありがたいです〜。

2022-02-16 05:46 UTC, eatplaynap commented
@komagata 
レビューありがとうございます！[config/environments/development.rb](https://github.com/fjordllc/bootcamp/pull/4174/files/c9d90e96a781fc1a7f4f6310a97540ec0953172b#diff-d3c4b3f41072daa416f1920511e9b2e26caea8c5cec0a14cb9508589a4dafa47)と[config/application.rb](https://github.com/fjordllc/bootcamp/pull/4174/files/c9d90e96a781fc1a7f4f6310a97540ec0953172b#diff-c1fd91cb1911a0512578b99f657554526f3e1421decdb9e908712beab57e10f9)のインデントを修正しました！

2022-02-16 05:56 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-16 05:56 UTC, merged