アドバイザーでログインしているときに自社の研修生には「自社研修生」が表示されていること
fjordllc/bootcamp pull request #4176
Opened 2022-02-08 09:36 UTC by yoshitaku-jp

#2992

2022-02-11 02:57 UTC, yoshitaku-jp commented
@Saki-htr 
確認点2を追加させていただきました:pray:
こちらも確認いただいていいでしょうか。

確認点1同様に、ユーザ**一覧**画面においても、自社研修生の場合に「自社研修生」と表示されているかの確認になります！

2022-02-13 05:15 UTC, Saki-htr requested changes
@yoshitaku-jp 
お待たせしてすみません🙇‍♀️
動作確認を行ったところ、確認点2はOKでした。
しかし、確認点1が、所属企業が異なる研修生にも「自社研修生」と表示されていましたので、ご確認いただけますと幸いです。
よろしくお願いいたします🙏

2022-02-13 05:15 UTC, Saki-htr commented on app/views/users/show.html.slim
> +                        = '自社研修生'
@yoshitaku-jp

`senpai`でログインして動作確認したところ、
 - `kensyu`のユーザー詳細画面に「自社研修生」が表示されました。
- しかし、所属企業が異なる研修生(大名三郎)のユーザー詳細画面を見ると、所属企業が異なるので、「フォローする」ボタンが表示されるはずが、こちらも「自社研修生」が表示されていました。

http://127.0.0.1:3000/users/651524103
<img width="524" alt="image" src="https://user-images.githubusercontent.com/58052292/153739635-630362d8-738c-47e8-b7db-08135c441795.png">


おそらく、こちらの表示条件の分岐のコードに原因があるかと思いますので、ご確認をお願いいたします〜🙏

2022-02-17 02:44 UTC, yoshitaku-jp commented
@Saki-htr 
確認ありがとうございました！
ご指摘していただいた部分を修正しました！
再度確認いただけますでしょうか🙇‍♂️

2022-02-23 22:40 UTC, Saki-htr reviewed
@yoshitaku-jp さん
お待たせして申し訳ありません🙏
再レビューさせていただいたところ、動作確認の方はOKでした✨
コードで気になった所を3点コメントさせていただきましたので、ご確認をお願いいたします。

コメントの意味が分かりづらい等ありましたら、こちらのPRでも、私の日報や分報チャンネルでも、お気軽にコメントいただけますと幸いです🙇‍♀️
よろしくお願いいたします〜

2022-02-23 22:40 UTC, Saki-htr commented on test/system/users_test.rb
> +  test 'show Students' do
テストパターンが、同じ会社のアドバイザー(`senpai`)が研修生(`kensyu`)を見たパターンだけでなく、
- studentが研修生を見るパターン
- アドバイザーがstudentを見るパターン
- 研修生が自分のページを見るパターン
- senpaiが`/users?target=trainee`を見るパターン

と様々なケースを想定して書かれていて、素晴らしいと思いました😊

一点気になったのですが、この`Student`の頭文字は小文字でも良さそうだと思いました。
何か意図がありましたら、教えていただけるとありがたいです〜🙏

2022-02-24 08:26 UTC, yoshitaku-jp commented on test/system/users_test.rb
> +  test 'show Students' do
こちら特に意図はなかったです:pray:

対応しました！ https://github.com/fjordllc/bootcamp/pull/4176/commits/66c0c508c23e9b4c863ac9721c3f30b59e3b3932

2022-02-24 09:00 UTC, yoshitaku-jp commented on app/views/users/show.html.slim
> +                  - elsif current_user != @user
個人的に条件部は明示的に表現されている方がいいかなと思い、そのような書き方をしていました！
条件漏れのケースも拾えるかと思うので、`else`に変更しました！

https://github.com/fjordllc/bootcamp/pull/4176/commits/be66c3fe942aa9e92bb963640739aed7c50dcb3f

2022-02-24 09:00 UTC, yoshitaku-jp commented on app/views/users/show.html.slim
> +                  - elsif current_user != @user && current_user.adviser? == true && current_user.company_id == @user.company_id
こちらおっしゃるとおりです…！

こちらで対応しました！
https://github.com/fjordllc/bootcamp/pull/4176/commits/f1958ed401125679f7d5c54efe0692c50019a6a0

2022-02-24 09:03 UTC, yoshitaku-jp commented
@Saki-htr 
コードレビューありがとうございました！とても勉強になりました！
対応しましたのでご確認をお願いできればと思います！

2022-02-24 21:37 UTC, Saki-htr commented on app/views/users/show.html.slim
> +                  - elsif current_user != @user
ご変更ありがとうございます🙏

> 個人的に条件部は明示的に表現されている方がいいかなと思い、そのような書き方をしていました！

たしかに`else`よりも明示されている方が、どういう条件だと「フォローする」ボタンが表示されているか分かりやすいですね〜

2022-02-24 21:41 UTC, Saki-htr commented on app/views/users/show.html.slim
> +                  - elsif current_user != @user && current_user.adviser? == true && current_user.company_id == @user.company_id
ご変更ありがとうございます☺️
コミット番号を記載していただいたので、すぐに差分が分かってありがたいです✨
私も自分のissueで再レビュー依頼する時は、真似させていただこうと思いました!

2022-02-24 21:41 UTC, Saki-htr approved these changes

2022-02-24 21:50 UTC, Saki-htr commented
@yoshitaku-jp さん
早速ご確認くださりありがとうございます!
変更してくださった所を確認いたしました。私の方ではレビューOKとさせていただきます🙆‍♀️

[issue](https://github.com/fjordllc/bootcamp/issues/2992)も拝見しましたが、issueを立てた方にヒアリングされたり、machidaさんと仕様について細かくやり取りされていて素晴らしいと思いました👏👏

よしたくさんのPRで、初めてVueやjbuilderに触れたのでとても勉強になりました! 
チーム開発最後のissue、お疲れさまでした☺️

2022-02-24 23:36 UTC, yoshitaku-jp commented
@machida 
こちらメンバのレビューが完了しましたので、デザインをお願いできますでしょうか:bow:

2022-03-04 04:06 UTC, machida approved these changes

2022-03-04 04:07 UTC, machida commented
@yoshitaku-jp 

デザイン入れました！最新の main を取り込んだので、手元でコードを触る際は

git rebse origin feature/show-trainee-for-advisors

をお願いします。

2022-03-04 04:08 UTC, machida commented
@komagata デザイン入れたのでレビューをお願いしますー🙏

2022-03-07 07:19 UTC, komagata requested changes

2022-03-07 07:19 UTC, komagata commented on app/views/users/show.html.slim
> +                  - elsif current_user != @user && current_user.adviser? == true && current_user.company_id == @user.company_id && @user.trainee == true
rubyの式は必ずtrueかfalseで評価できるので、基本的に条件式に`true`や`false`と書かれるシチュエーションはないはずなので修正してみてください〜（ごく稀に必要なシチュエーションはある）

2022-03-10 18:12 UTC, komagata reviewed
conflictの修正をお願いします〜

2022-03-11 00:16 UTC, yoshitaku-jp commented
@komagata 
コンフリクトも修正しました！

2022-03-14 07:08 UTC, komagata commented on app/javascript/user.vue
> +              v-if='currentUser.id != user.id && currentUser.adviser == true && user.company && currentUser.company_id == user.company.id'
条件文なのでtrueとの比較は不要かもです〜

2022-03-14 22:57 UTC, yoshitaku-jp commented
@komagata 
Vueの方も対応しました！:bow:

2022-03-15 03:32 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-15 03:32 UTC, merged