管理者でログインしたときだけ、相談部屋の個別ページにユーザーメモと、ユーザー公開情報、非公開情報を表示
fjordllc/bootcamp pull request #4210
Opened 2022-02-12 10:07 UTC by ot0m1

ref: #4070

2022-02-14 12:31 UTC, ot0m1 commented
@eatplaynap お疲れ様ですレビューお願いいたします。
一部通らないテストがあったので、 https://github.com/fjordllc/bootcamp/pull/4203 を先取って取り込んでいます。

2022-02-17 06:45 UTC, eatplaynap requested changes
実装おつかれさまです😄レビューおまたせしました！
数点気になった点があったので、ご確認ください:pray:

- `komagata`でログイン後、概要コメントに書いてくださったURL(http://localhost:3000/talks/26490054 )にアクセスしようとしたらエラーになってしまったので、別のURLを表記したほうがよさそうです！
![image](https://user-images.githubusercontent.com/63531341/154419859-89b6dc31-fc71-4339-9752-b35ee83dc500.png)
- 実装前の状態がどうだったのか、一言説明があったほうがわかりやすいかも？と思いました。
- テストの名前は小文字始まりで統一した方がよさそうです！
- テスト内で、`wait_for_vuejs`というsleep状態のメソッドを呼んでいる理由が分からなかったので教えてください:pray:

2022-02-17 06:45 UTC, eatplaynap commented on test/system/talks_test.rb
> +    wait_for_vuejs
この`wait_for_vuejs`メソッドは定義元(`test/application_system_test_case.rb`)を見るとsleep状態になっているようですが、ここで呼んでいる理由が知りたいです！

(このメソッドをコメントアウトして手元でテストを通したところ、PASSしたのでもしかしたら必要ないのかな〜と…！)

2022-02-17 06:45 UTC, eatplaynap commented on test/system/talks_test.rb
> +    wait_for_vuejs
ここも`wait_for_vuejs`ですね！

2022-02-17 06:45 UTC, eatplaynap commented on test/system/talks_test.rb
> +    wait_for_vuejs
ここにも`wait_for_vuejs`！全部で3個ですかね？

2022-02-17 06:45 UTC, eatplaynap commented on test/system/talks_test.rb
> +  test 'Is the public information and private information displayed correctly' do
とっても細かいことなのですが、
- 他のテストはすべて小文字始まりなので小文字始まりのほうがよさそう
- public informationとprivate informationの2つなので、isよりareのほうがよさそう
- theはどちらのinformationにも付ける、またはどちらにも付けないに統一した方がよさそう

ちなみに私だったら`are both public information and private information displayed correctly`というテスト名にするかな〜と思いました…参考までに！

2022-02-17 06:45 UTC, eatplaynap commented on test/system/talks_test.rb
> +    wait_for_vuejs
あ、ここにもいた！全部で4つですね〜

2022-02-18 13:40 UTC, ot0m1 commented on test/system/talks_test.rb
> +  test 'Is the public information and private information displayed correctly' do
おっしゃる通りだと考えますのでご指摘の通りに変更しました。

2022-02-18 13:45 UTC, ot0m1 commented
> komagataでログイン後、概要コメントに書いてくださったURL(http://localhost:3000/talks/26490054[](https://user-images.githubusercontent.com/63531341/154419859-89b6dc31-fc71-4339-9752-b35ee83dc500.png) )にアクセスしようとしたらエラーになってしまったので、別のURLを表記したほうがよさそうです！

これは僕の環境ではエラーになりませんでした。キャッシュとかが関係あるんですかね？
ひとまず URL を削除するようにしました。

> 実装前の状態がどうだったのか、一言説明があったほうがわかりやすいかも？と思いました。

スクショを追加しました。

2022-02-21 12:32 UTC, eatplaynap commented on test/system/talks_test.rb
> +    wait_for_vuejs
他の方にも聞いてみたところ、仰るとおり、ないとVueのテストがうまくいかないことがあるので入れていると伺いました…！PASSするのであればいらないのかなって思います😄

2022-02-21 12:34 UTC, eatplaynap approved these changes
@ot0m1 
ご返信おまたせしました！指摘させていただいた内容とりいれてくださってありがとうございます！
とくにdescriptionに追加情報を入れていただいて、とてもわかりやすくなりました！LGTMです:+1:

2022-02-21 13:31 UTC, ot0m1 commented
@eatplaynap レビューありがとうございました。
@komagata レビューお願いいたします。

2022-02-21 16:32 UTC, komagata requested changes
conflictの修正をお願いします〜

2022-02-22 12:26 UTC, ot0m1 commented
@komagata コンフリクト解消いたしました。再度レビューお願いいたします🙏

2022-02-26 16:32 UTC, komagata requested changes

2022-02-26 16:32 UTC, komagata commented on test/system/talks_test.rb
> +  test 'are both public information and private information displayed correctly' do
疑問文だとすると`?`が必要なのと、「〜ということをテストする」みたいな書式にするのが良いと思います〜

2022-02-27 00:57 UTC, ot0m1 commented on test/system/talks_test.rb
> +  test 'are both public information and private information displayed correctly' do
疑問形ではないように変更しました。
なお、そのまま「〜ということをテストする」という日本語を英訳すると「Test that ~」となり、テストしていることは明らかなこと、他の箇所のテストのメソッド名と乖離が出る（他の箇所のテストのメソッド名は Test that ~ から始まっていない）ことから、Make sure ~ にしています。

2022-02-28 07:11 UTC, komagata commented on test/system/talks_test.rb
> +  test 'are both public information and private information displayed correctly' do
@komagata すみません、僕の書き方分かりづらかったですね。
「テストする」という部分は`test`メソッドが表現しているのでテスト名は「〜ということ」だけでいいという意味です〜。

2022-02-28 07:13 UTC, komagata requested changes

2022-02-28 07:13 UTC, komagata commented on test/system/talks_test.rb
> +  test 'make sure that both public and private information is displayed correctly' do
Both public and private information is displayed.

とかでいいと思います〜

2022-02-28 11:31 UTC, ot0m1 commented on test/system/talks_test.rb
> +  test 'make sure that both public and private information is displayed correctly' do
提案いただいたものがもっとも妥当だと自分も考えましたのでその通りに変更いたしました🙏

2022-02-28 11:32 UTC, ot0m1 commented
@komagata レビューいただいた点を修正いたしました。再レビューお願いいたします。

2022-03-01 05:27 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-01 05:27 UTC, komagata commented
@ot0m1 町田さんにデザインの依頼をお願いします〜

2022-03-07 08:44 UTC, machida commented
@ot0m1 お待たせしました！！こちら対応しましたー

2022-03-07 08:44 UTC, machida commented
コンフリクト解消してマージしておきますー

2022-03-07 10:28 UTC, merged

2022-03-08 10:41 UTC, ot0m1 commented
ご対応ありがとうございました〜！