ページのページネーションをクリックしたら次のページの先頭に飛ぶ
fjordllc/bootcamp pull request #4217
Opened 2022-02-13 17:01 UTC by chung3011

[#2677](https://github.com/fjordllc/bootcamp/issues/2677)
## 要件
Vue.jsで表示されるページのページネーションをクリックしたら次のページの先頭に飛ぶようにする。
## 変更前
![image](https://user-images.githubusercontent.com/34033366/153765548-00b32952-82f4-4f6d-b497-c1091fed9198.png)
## 変更後
![image](https://user-images.githubusercontent.com/34033366/153765564-400c4b95-1c4a-4640-9cec-9d2811d6d032.png)
## 確認手順
- `feature/move-to-top-of-page-when-click-pagination`ブランチを手元に持ってくる。
- ページネーションがあるページを確認する。
`http://localhost:3000/reports`、`http://localhost:3000/products`、`http://localhost:3000/users`、等。

2022-02-13 17:29 UTC, chung3011 commented
@Saki-htr さん、このPRをチェックしていただけませんか？

2022-02-16 12:33 UTC, Saki-htr commented
@chung3011 さん
レビュー依頼ありがとうございます🙆‍♀️
ページネーションがあるページがたくさん有り、チェックに漏れがあると怖いので、変更したページをすべて教えていただけると助かります🙏
お手数ですが、よろしくお願いいたします〜

2022-02-20 22:00 UTC, Saki-htr requested changes
@chung3011 さん
お待たせしてすみません🙇‍♀️
いくつか気になる点がありましたので、コメントさせていただきました〜。

また、descriptionに書いてくださった確認するページ一覧に漏れがあったり、書いていただいたURLと実際に変更したファイルが異なったりしていたのですが、レビュワーの方が、よりスムーズにレビューを行えるように、次回から気をつけていただけると良いかなと思いました〜

2022-02-21 01:01 UTC, chung3011 commented on app/javascript/users.vue
> +      window.scrollTo(0, 0)
すみませんが、サーバーを再度実行していただけませんか？私はもう一度`http://localhost:3000/users`をアクセスすると、その問題がありませんでした。

2022-02-21 01:25 UTC, chung3011 commented on app/javascript/admin_companies.vue
> +      window.scrollTo(0, 0)
descriptionを更新しました。

2022-02-21 01:26 UTC, chung3011 commented on app/javascript/bookmarks.vue
> +      window.scrollTo(0, 0)
descriptionを更新しました。

2022-02-21 01:26 UTC, chung3011 commented on app/javascript/generation-users.vue
> +      window.scrollTo(0, 0)
descriptionを更新しました。

2022-02-21 03:49 UTC, chung3011 commented on app/javascript/watches.vue
> +      window.scrollTo(0, 0)
私はもう一度`http://localhost:3000/current_user/watches`をアクセスすると、その問題がありませんでした。
sotugyouさんとしてログインします。
![Screen Recording 2022-02-21 at 10 45 45](https://user-images.githubusercontent.com/34033366/154885985-a0a4d022-a8a9-4b36-a9ad-d0d089b886c5.gif)
。

2022-02-21 12:12 UTC, Saki-htr commented on app/javascript/watches.vue
> +      window.scrollTo(0, 0)
@chung3011 さん
再度確認させていただいたところ、問題なく動作しました！
私の環境でうまくいかなかった原因は、私がテストデータを増やすために`db/fixtures/watches.yml` の内容を変更していたことが原因でした。
お手数をおかけして、申し訳ありませんでした🙏

2022-02-21 12:36 UTC, Saki-htr commented on app/javascript/users.vue
> +      window.scrollTo(0, 0)
@chung3011 さん
調べたところ、@chung3011 さんの環境で成功し、私の環境で挙動がおかしくなる原因が分かりました。

## 原因
現在、最新のmainを`git pull --rebase origin main`で取り込んだ状態で、ユーザー一覧ページ( http://localhost:3000/users )を表示しようとすると、エラーが起こる状態になっています。(詳しい状況・解決方法はParuさんが[こちらのチャット](https://discord.com/channels/715806612824260640/809595476847493192/944230528553472111)で説明してくださっています。)おそらく、chungさんのローカルの`feature/move-to-top-of-page-when-click-pagination`ブランチはこのエラーが起こるよりも前の状態なので、動作に問題が起こらなかったのだと思います。
komagataさんにレビュー依頼する際に、この事をお伝えしておくといいと思います〜☺️

## レビューOKです🙆‍♀️
上記の問題を解消して動作確認を行ったところ、問題なく動きました！
私の勘違いで誤ったレビューをしてしまい、申し訳ありませんでした🙇‍♀️
私の方では、レビューOKとさせていただきます〜

2022-02-21 12:37 UTC, Saki-htr approved these changes

2022-02-27 14:20 UTC, chung3011 commented
@komagataさん、このPRをチェックしていただけませんか？

2022-02-28 07:46 UTC, komagata reviewed
可能かわからないのですが、ページャーのコンポーネントで一括で対応できたりしないですかね？

2022-03-13 13:34 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-13 13:34 UTC, merged