メンターモードがonの時だけメンター向けメモが表示されるよう修正
fjordllc/bootcamp pull request #4227
Opened 2022-02-15 06:18 UTC by clio209

issue #4218

プラクティスの個別ページの、「メンター向けメモ」「管理者・メンター用メニュー」が、メンターモード「ON」の場合だけ表示されるように修正しました。

### 変更前
![Terminalの基礎を覚える___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/154003563-29bca19d-9d4d-48e3-82c2-4490dffb1999.png)

### 変更後
![Terminalの基礎を覚える___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/154002679-974c4358-c932-4711-a70b-83214584d7de.png)

2022-02-15 08:58 UTC, clio209 commented
@aim2bpg いつもアドバイスありたとうございます！レビュー依頼させていただきました。お時間ある時に見ていただければ幸いです。

2022-02-15 20:37 UTC, aim2bpg commented
@clio209 さん、レビュー依頼ありがとうございます〜。
ちょっと今のIssueをPRしてから着手したいと思いますので、本日中には着手できるかと思います。

2022-02-16 05:12 UTC, aim2bpg approved these changes
@clio209 さん
私はOKです🙆‍♀️　チームリーダーレビューに進めてください。

1点、テストがあった方が、後々どのユーザーがOKだったかという意図がコードに残せて明確になりますし、テスト駆動開発の観点では良かったのかなと思いました。今回のケースではマストではない気もしましたので、チームリーダーのご判断にお任せしたいと思います🙏
ご参考までに、#3409 #2916 ではテスト追加しているようです。

2022-02-16 14:10 UTC, clio209 commented
@aim2bpg さん
お忙しい中、レビューありがとうございます！#2916と類似することもありますし、せっかくなので、テストを追加してみたいと思います！

2022-02-16 21:21 UTC, aim2bpg reviewed
テスト追加されるとのことで、承知しました👍
修正完了しましたら、ご連絡くださいー

2022-02-16 21:24 UTC, aim2bpg requested changes
一旦、Request changes の状態にしますねー

2022-02-17 11:12 UTC, clio209 commented
@aim2bpg  さん 
お疲れ様です。テストを追加しました。（テストの駆動は確認しました）お時間ある時にご確認いただけますと幸いです。

2022-02-17 12:19 UTC, aim2bpg approved these changes
@clio209 さん、修正ありがとうございます。
テストの追加内容を確認しました。OKですー🙆‍♀️

一応、こちらの手元でもちゃんとテストが機能していることを「`assert_no_text`→`assert_text`に変更→期待通りFail」で確認しました〜。

2022-02-17 21:58 UTC, clio209 commented
@aim2bpg さん　レビューありがとうございます！！

2022-03-10 08:56 UTC, clio209 commented
@komagata お疲れ様です。再メンションさせていただきます。
お忙しいところ恐れ入りますが、ご都合の良い時にレビュー頂ければ幸いです 🙇

2022-03-10 18:11 UTC, komagata reviewed
conflictの修正をお願いします〜

2022-03-11 05:08 UTC, clio209 commented on test/system/practices_test.rb
> +  test 'show/hide mentor-memo' do
@komagata レビュー有難うございます。コンフリクト解消を行ってみまして、上記の`-`表記も修正致しました。
これで大丈夫でしょうか・・？　以上、よろしくお願いいたします〜。

2022-03-14 07:08 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-14 07:09 UTC, merged