キャンペーン名を動的に表示する
fjordllc/bootcamp pull request #4228
Opened 2022-02-15 13:58 UTC by ot0m1

ref: #4130

2022-02-16 04:57 UTC, ot0m1 commented
お試し期間の動的な変更は https://github.com/fjordllc/bootcamp/pull/4232 で進められているので、このプルリクエストではキャンペーン名とキャンペーン期間のみの動的な変更を行う。

2022-02-16 05:43 UTC, aim2bpg commented
@ot0m1 さん、おつかれさまです。
> このプルリクエストではキャンペーン名とキャンペーン期間のみの動的な変更を行う。

キャンペーン期間の方は、#4196 で自分の方で対応予定です。

PRにメンションがあったので、覗いてみたらキャンペーン期間の言及があり
被ってはいけないな〜と思いましたので、一応、ご連絡させていただきました。。🙇🏻‍♂️

2022-02-16 10:03 UTC, ot0m1 commented
@aim2bpg 
なんと〜キャンペーン期間の実装もされていたんですね。
ではキャンペーン名だけの取得にします🙏 ご連絡ありがとうございました。

2022-02-16 11:02 UTC, ot0m1 commented
@aim2bpg こちらShimokawaさんに見ていただくのが色々良さそうなのでレビュー依頼させていただきます〜🙏 よろしくお願いします。

2022-02-16 12:42 UTC, aim2bpg approved these changes
@ot0m1 さん
確認しました、OKですー🙆‍♀️

テストが頭をよぎりましたが、タイトルは目立つし、仮に間違っていても影響は少なそうです。キャンペーン入れた後には大体確認するでしょうから問題なさそうだと思いました👍

↓手元の確認結果
![image](https://user-images.githubusercontent.com/58363353/154266916-8b56a9eb-73b0-44fb-976a-5e2d1d4e9285.png)

2022-02-20 17:59 UTC, komagata commented on app/models/campaign.rb
> +  def self.current_title
クラスメソッドが複数になったら`class << self`でまとめるのがいいかもです。

あと、これは @ot0m1 さんが書いたところじゃないですが、`today_is_campaign?`って英語的に間違ってるので変えたいですね〜

2022-02-22 10:47 UTC, ot0m1 commented on app/models/campaign.rb
> +  def self.current_title
クラスメソッドのまとめ & `today_is_campaign?` の修正を行いました。
`is_today_campaign?` だと Rubocop にメソッド名の修正を推奨されるので、Rubocop にサジェストされる `today_campaign?` にしています。

2022-03-03 14:02 UTC, aim2bpg commented
@komagata さん、@ot0m1 さん、おつかれさまです〜
こちらのPR、結構修正が入っており、並行して進めている自分の方のPRとコンフリクトを起こすものと思われます。

もし、可能であれば、先にこちらのPRを早めにmainにマージしていただき、自分の方のPRでコンフリクトを解決したいと考えております。何卒ご配慮のほど、お願い申し上げます🙇🏻‍♂️

2022-03-03 14:24 UTC, ot0m1 commented
@aim2bpg お待たせしております🙏
@komagata https://github.com/fjordllc/bootcamp/pull/4228#discussion_r815328544 こちらご確認お願いいたします🙇‍♂️

2022-03-05 13:37 UTC, komagata commented
@ot0m1 

> https://github.com/fjordllc/bootcamp/pull/4228#discussion_r815328544 こちらご確認お願いいたします

こちら私が質問しているように見えるのですが、それに対して「確認お願いします」というのは何をすればいい感じでしょうか〜

2022-03-05 14:05 UTC, aim2bpg commented
@komagata さん、自分にも

> これってメソッドの定義はどこでかわっていますか？（今回のdiffの中に見当たらないので）

23行目でかわっています〜

![image](https://user-images.githubusercontent.com/58363353/156886713-11a76329-8352-4160-b591-65f35675c7a9.png)

2022-03-05 23:59 UTC, ot0m1 commented
@komagata 

![スクリーンショット 2022-03-06 8 58 37](https://user-images.githubusercontent.com/6190966/156903639-6c907f17-1cd2-40a4-8891-fa1972a6315f.png)

で質問されているのを、

![スクリーンショット 2022-03-06 8 59 05](https://user-images.githubusercontent.com/6190966/156903646-4214e1b2-78d7-4171-81a6-7d4c11180066.png)

と回答したので、それをご確認いただきたいという意味です。

2022-03-07 13:56 UTC, komagata commented
@ot0m1 なるほどです、僕が見逃しておりました〜。

2022-03-07 13:58 UTC, komagata requested changes

2022-03-07 13:58 UTC, komagata commented on app/models/campaign.rb
> +      return if recently_campaign.nil?
この`if`は不要かもと思いました〜。

2022-03-08 12:29 UTC, ot0m1 commented
@komagata レビューいただいた点修正いたしました。再レビューお願いいたします。

2022-03-10 04:06 UTC, komagata commented on app/models/campaign.rb
> -      return if recently_campaign.nil?
すみません、こちら僕が読み間違っていました。

引数の無いreturnなんですね。だとしたら不要では無いかと思います。すみません。
（`if recently_campaign.nil?`をreturnしてるのかと読み間違えちゃっていました。）

2022-03-10 11:57 UTC, ot0m1 commented
@komagata 

https://github.com/fjordllc/bootcamp/pull/4228#discussion_r823329320 にコメント追加できないのでこちらで回答します。

> たしかに current_title 内で return unless today_campaign? で判断しているので、today_campaign? では return で抜ける必要がないと考え、この行を削除しました。

上記のような回答をしていましたが、`today_campaign?`は `current_title` メソッド以外の箇所でも呼ばれているので必要そうでしたので、`return if recently_campaign.nil?` を復活させました。

2022-03-10 14:35 UTC, komagata approved these changes
読み間違えてややこしくしてしまってすみませんでした〜。
確認しました、OKですー🙆‍♂️

2022-03-10 14:35 UTC, merged