[WIP]sadがついた日報にコメントを書いて『確認OKにする』ボタンを押した際に『今日の気分は「sad」ですが、コメント無しで確認しますか？』が表示される
fjordllc/bootcamp pull request #4239
Opened 2022-02-16 14:00 UTC by Aseiide

- #3941

2022-02-17 03:18 UTC, Aseiide commented
@Saki-htr  こちらのレビューお願いいたします！

2022-02-17 06:50 UTC, Saki-htr commented
@Aseiide さん
すみません、現在手持ちのレビューが3つあるため、別の方にご依頼いただけるとありがたいです🙏
せっかくご依頼くださったのに申し訳ありません🙇‍♀️💦

2022-02-17 07:39 UTC, Aseiide commented
@Saki-htr 承知しました！

@Paru871  レビューお願いできますか??

2022-02-17 15:25 UTC, Paru871 approved these changes
@Aseiide 
お疲れさまです。このたびはレビューのご依頼いただきありがとうございました。
私も同じように環境を作って、私だったらどう修正するだろうかと考えながらコードを拝見しました。
コメント投稿と確認チェックが同時に行われる際のコメントが既にある/ないの確認のタイミングを思ったとおりに動かすのが難しいですね。そしてcomments.vueにもcheckメソッドを作っておくというのはかなり工夫されたのだなという激闘ぶりが伝わってきました。
実装内容・挙動ともに不審な点はなく全く問題ないと思いましたので、私の方からはOKとさせていただきます👍

※テストについて1点確認していただきたいことがありましたので、別途コメントしました。
(確認・ご対応いただき次第、次の駒形さんのレビューに進んでください。)

よろしくお願いします😄

2022-02-18 02:50 UTC, Aseiide commented on test/system/api/check/reports_test.rb
> +    wait_for_vuejs
@Paru871 
`wait_for_vuejs`を削除しても正常に動作しました。レビューありがとうございます！

2022-02-18 04:51 UTC, Aseiide commented
@komagata 
お手すきでレビューお願いいたします。

2022-02-20 18:44 UTC, komagata commented on app/javascript/comments.vue
> -      check.click()
これってなぜこの方法から、自前でPOSTする方法に変更したんでしょう？

2022-02-21 13:02 UTC, Aseiide reviewed
@komagata 
コメントいただいた部分について、返信しました。ご確認お願いします

2022-02-21 13:02 UTC, Aseiide commented on app/javascript/comments.vue
> -      check.click()
「確認OKにする」ボタンには、「日報を確認」する機能が必要で、ポップアップは必要ない。
「日報を確認」ボタンには、「日報を確認」する機能と、ポップアップの両方必要。

「日報を確認」するというメソッド(機能)は`check.vue`に存在し、`comments.vue`からは呼べないと思いました。
なぜなら、親子関係にないためです。
なので、「日報を確認」する機能に該当する部分(変更後コードの`comments.vue L138~L164`)を`check.vue`から移植して自前でPOSTするようにしました。

自分では思いつかなかったのですが、`comments.vue`から`check.vue`の`checkメソッド`を呼ぶ方法がございましたら、実装のヒントや方針などご教示いただけますと幸いです。

2022-02-21 16:30 UTC, komagata requested changes

2022-02-21 16:30 UTC, komagata commented on app/javascript/comments.vue
> -      check.click()
@Aseiide なるほどですね〜

Checkする処理は同じだと思うのでcomponentからmixinを使って共通化するのはいかがでしょうか〜

2022-02-22 00:04 UTC, Aseiide commented on app/javascript/comments.vue
> -      check.click()
@komagata 
なるほど、そういう方法があるのですね。
mixin調べてやってみます。

2022-02-24 00:40 UTC, Aseiide commented
@komagata 
mixinを使ってチェックメソッドを共通化しました。レビューお願いします。

2022-02-26 16:47 UTC, merged