[お試し延長 開始・終了機能] キャンペーン期間を動的に表示する
fjordllc/bootcamp pull request #4247
Opened 2022-02-17 10:39 UTC by aim2bpg

# Issue #4196 
## 概要
トップページでお試し延長キャンペーン中に表示されるキャンペーンの開始〜終了日について、これまで人手で「12/26(日)〜1/4(火)」のように書き換えていましたが、動的に現在のキャンペーン期間を参照して表示を切り替えるようにプログラムを変更しました。

## 変更理由
トップページのキャンペーン期間について、人手による変更の手間がなくなり、変更漏れも防げるため。

## 変更点
1. トップページでお試し延長キャンペーン中に表示されるキャンペーン期間の開始日と終了日を動的に表示させるように変更。
2. 1の表示の正しさを担保するための、自動テストを追加。

## 目視確認結果
キャンペーン開始〜終了日が動的に表示されていることを確認済み。

### 変更前
![image](https://user-images.githubusercontent.com/58363353/154432229-8830b605-4b2d-4e1c-bec1-35466f2c10fc.png)

### 変更後
![image](https://user-images.githubusercontent.com/58363353/154431833-3cd52caa-b074-4b4c-ba7a-d31f2f774bbc.png)

## 確認方法
1. `feature/change-dynamically-display-trial-period-start-to-end` ブランチをローカルに持ってくる。
2. 管理者(komagataさん)でログインする。
3. お試し延長画面（ http://localhost:3000/admin/campaigns ）にアクセスしてキャンペーンを登録する。
キャンペーン中でないと確認できないため、登録時は確認当日を挟むようにする。
設定画面への行き方：ホーム>管理者ログイン>Me>管理ページ>お試し延長
4. ログアウト後、（ http://localhost:3000/ ）にアクセスして開始〜終了日が3で登録した期間と一致することを確認する。

## 自動テスト確認結果
PASSを確認済み。

```
~/work/bootcamp feature/change-dynamically-display-trial-period-start-to-end* 13s
❯ rails test test/system/admin/campaigns_test.rb   
Run options: --seed 50031

# Running:

......

Finished in 8.545909s, 0.7021 runs/s, 1.1702 assertions/s.
6 runs, 10 assertions, 0 failures, 0 errors, 0 skips
```

2022-02-17 11:25 UTC, aim2bpg commented
@ot0m1 さん、おつかれさまです。
#4228 の類似PRのレビュー依頼をさせていただきます〜🙏
お手すきの際に、よろしくお願いいたしますー

2022-02-17 13:36 UTC, ot0m1 commented
@aim2bpg ご依頼いただいたのですがすいません🙏 現在僕20ポイント以上になっておりまして、あとレビューいただくだけの状態になっており今後チーム開発ミーティングなどにも不参加のため、他の方にご依頼いただければと思います。

2022-02-17 14:00 UTC, aim2bpg commented
@ot0m1 さん、承知しました。
状況理解出来ておらず、すみませんでした～🙏

2022-02-17 14:04 UTC, aim2bpg commented
@napple29 さん
自作サービスでご多用のところを申し訳ありませんが、レビューお願い出来そうでしょうか～
お試し延長機能を構築いただいたという所でお声掛けさせていただきましたー🙏

2022-02-17 20:25 UTC, aim2bpg commented
@napple29 さん
さっそくのご対応ありがとうございました〜🙇🏻‍♂️

@komagata さん
チームメンバーレビューが通過しましたので、チームリーダーレビューをお願いします🙏

2022-02-20 18:38 UTC, komagata commented on config/locales/ja.yml
> +      mda_unique: "%-m/%-d(%a)"
mdaとはどういう意味でしょうか？

2022-02-20 19:56 UTC, aim2bpg commented on config/locales/ja.yml
> +      mda_unique: "%-m/%-d(%a)"
@komagata さん、ご確認ありがとうございます🙇🏻‍♂️
> mdaとはどういう意味でしょうか？

月・日・曜(month, day, a day of week)の連結を意味します。
10行目のmdに対して曜日を追加し、`2/21(月)`のようなフォーマットを実現するために追加しました。

2022-02-21 15:56 UTC, komagata requested changes

2022-02-21 20:47 UTC, aim2bpg commented on config/locales/ja.yml
> +      dw_jp: "%e日(%a)"
ここにも曜日の`a`表記がありましたので、`w`に修正しました。現状未使用のため、修正による影響がないことを確認済みです。

2022-02-21 21:19 UTC, aim2bpg commented
@komagata さん、コメントありがとうございます。
> 冠詞のaだとするとほとんど全ての単語に当てはまっちゃうので頭文字としては採用しない方がいいかもです〜

[既存1箇所](https://github.com/fjordllc/bootcamp/pull/4247#discussion_r811420433)の表記も含めて`a`から`w`に修正しました。
`w`にした理由は、曜日を`wday`という変数や関数で命名されることがあるためです。

たびたびお手数ですが、ご確認をお願いいたします〜🙏

2022-02-26 16:14 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-02-26 16:14 UTC, merged