プラクティス > Docs一覧をVue.js化した
fjordllc/bootcamp pull request #4293
Opened 2022-02-24 08:10 UTC by aim2bpg

作成中

2022-02-25 07:35 UTC, aim2bpg commented
@garammasala29 さん、おつかれさまです。
類似Issueに着手されるようですので、変更点のインプットも兼ねてレビューをお願いいたします🙏
なお、テストで1つエラーとなるところがあるのですが、別Issueを立ててレビュー依頼中です。
マージされると、解消する見込みです。ご承知おきください🙇🏻‍♂️

2022-03-01 16:38 UTC, garammasala29 approved these changes
@aim2bpg さん
お疲れ様です。レビュー依頼ありがとうございました！大変遅くなりすみません🙇‍♂️
手元でもVue化されることを確認できました。

https://user-images.githubusercontent.com/69446373/156196326-99b1b569-ba72-442f-b9cc-32ca5b8490dc.mov

issueを作成された箇所以外のテストが通ることも確認できています。
日報で実装の意図などを丁寧に書かれていたので、内容をよく理解しながらレビューすることができました。LGTMです！

1点だけ気になる点があり、`app/controllers/pages_controller.rb#index`でVue化に伴い不要なコードが見受けられ、どうしたらいいかなと考えていました。
@aim2bpg さんの今回の変更差分と関係ない部分ではありますが、少し気になったので記しておきます。

2022-03-01 23:52 UTC, aim2bpg commented
@garammasala29 さん、ご確認ありがとうございます🙇🏻‍♂️

> 1点だけ気になる点があり、app/controllers/pages_controller.rb#indexでVue化に伴い不要なコードが見受けられ、どうしたらいいかなと考えていました。

`@practice = Practice.find(params[:practice_id])`のことでしょうか？
こちらは、プラクティスのタイトルに関わる記述でしたので、削除するとエラーとなってしまいますので必要なコードという認識です。こちらのコードでない場合は、具体的に記載していただけますと幸いです😄

2022-03-02 00:42 UTC, garammasala29 commented
@aim2bpg さん
お疲れ様です。
`app/controllers/pages_controller.rb`の`@pages = Page.with_avatar~~`に関してのお話でした、`practices`から生えていないものになります
(変更したファイルではないので、対象のコードに直接コメントができませんでした。分かりづらくすみません🙏)

2022-03-02 02:15 UTC, aim2bpg commented
@garammasala29 さん、ありがとうございます。
自分がファイルパスをよく見ておらずに誤解してました🙏

> `app/controllers/pages_controller.rb`の`@pages = Page.with_avatar~~`

上記の記述は、本Issueとは別ページの部品と思われますのでスコープ外とさせて下さい。

手元で上記の記述を削除してみると、たしかにDocs一覧ページも表示できましたし、テストもPassしました。
一見すると不要と思われるのですが、影響範囲を調べずに安易に削除してしまうと、意図せず表示が壊れたりする恐れもあるので、そのままでもよいかと考えました。

2022-03-02 02:18 UTC, aim2bpg commented
@komagata さん、お手すきの際にレビューをお願いいたします🙏
なお、テストで1つエラーとなるところがあるのですが、別Issue https://github.com/fjordllc/bootcamp/pull/4298 を立ててレビュー依頼中です。
マージされると解消する見込みです。別Issue https://github.com/fjordllc/bootcamp/pull/4298 と合わせてご確認をお願いいたします🙇🏻‍♂️

2022-03-02 03:09 UTC, garammasala29 commented
@aim2bpg さん
> 上記の記述は、本Issueとは別ページの部品と思われますのでスコープ外とさせて下さい。

全然問題ありません、大丈夫です。気になる部分でしたので、共有させていただいてよかったです。
ご確認いただきありがとうございました🙏

2022-03-05 05:23 UTC, aim2bpg commented
@machida さん
mainを取り込んだ際に、Vue.js化前後でテストでFailする点がもう1箇所あって、どちらの記述があるべき姿がわかりませんのでご教示いただきますでしょうかー
![image](https://user-images.githubusercontent.com/58363353/156868956-2a0b9036-0195-4a3d-aad0-07022f1335c1.png)

2022-03-06 14:49 UTC, machida commented
@aim2bpg 返信遅れてすいません。meta が付く方でお願いします。

ちなみに、付かない方のclassは

<img width="533" alt="貼り付けた画像_2022_03_06_23_48" src="https://user-images.githubusercontent.com/168265/156928341-73b5bbe1-fb6c-47e8-a5cf-acecaa8f5f4e.png">

こっちの大きい方ようのclassですね。

それが間違えて使われているっぽいです。

2022-03-06 21:53 UTC, aim2bpg commented
@machida さん、metaの方で承知しましたー🙇🏻‍♂️
多分そうかなと思ったのですが、念の為にご確認させていただきました🙏

2022-03-06 22:44 UTC, aim2bpg commented
@komagata さん、あらためましてレビュー依頼させていただきます〜🙏
Vue.js化後にテストが通らなくなった件 #4298 も解消しました。

2022-03-07 14:01 UTC, komagata requested changes

2022-03-09 12:24 UTC, aim2bpg commented on app/controllers/api/practices/pages_controller.rb
> +class API::Practices::PagesController < API::BaseController
ご提案ありがとうございます。おかげさまで、コードがスッキリしました〜😄

2022-03-09 12:25 UTC, aim2bpg commented
@komagata さん、https://github.com/fjordllc/bootcamp/pull/4293#discussion_r820731211 の修正をしましたので、ご確認をお願いいたします〜🙏
あと、DocsのAPIテストが入れてなかったので、今回追加しておきました。

2022-03-09 12:48 UTC, cafedomancer commented on app/javascript/pages.vue
> +    practiceId: { type: String, required: true },
通常の docs 一覧ページのほうの js のコードでは `practiceId` を props として渡していないと思うので、`required: true` にしちゃうとそっちで warning になっちゃう気がしました。このへんです。https://github.com/fjordllc/bootcamp/blob/aa00f494d9bf5b4da4082b094616c8c4903fc37b/app/javascript/pages.js#L12

<img width="568" alt="Screen Shot 2022-03-09 at 21 39 28" src="https://user-images.githubusercontent.com/7645585/157443467-f3cc7ccb-d631-4d2f-b074-8b5d2c38d426.png">

2022-03-09 12:48 UTC, cafedomancer commented on app/controllers/api/pages_controller.rb
> +    end
`params[:practice_id]` があるときもないときもベースになるクエリはほとんど変わらないと思うので、プラクティスによる絞り込みだけ conditional にやるのが良いのではと思いました 💡 Kaminari の page による絞り込みは先にあって良いのかちょっとわからなかったので、そのへんは調査してみてもらえると〜 🙏 

```suggestion
    @pages = Page.with_avatar
                 .includes(:comments, :practice, :tags,
                           { last_updated_user: { avatar_attachment: :blob } })
                 .order(updated_at: :desc)
                 .page(params[:page])
    @pages = @pages.where(practice_id: params[:practice_id]) if params[:practice_id]
    @pages = @pages.tagged_with(params[:tag]) if params[:tag]
    end
```

2022-03-09 12:48 UTC, cafedomancer commented on test/integration/api/pages_test.rb
> +  end
practice_id による絞り込みや tag による絞り込みのテストもあると better だと思うけど omakase です〜。

2022-03-09 13:13 UTC, aim2bpg commented on app/javascript/pages.vue
> +    practiceId: { type: String, required: true },
エラーが出ないからと、リファクタしたつもりが裏目に出てしまいました。
下記の元の記述に戻すことで、ワーニングが出ないことを確認しました。
`    practiceId: { type: String, default: '', required: false },`

2022-03-09 13:26 UTC, aim2bpg commented on app/controllers/api/pages_controller.rb
> +    end
こちらもご提案ありがとうございます🙏コードがスッキリしました😄
page絞り込みが先にあっても違和感なく動作することを確認しました。

2022-03-09 13:31 UTC, aim2bpg commented on test/integration/api/pages_test.rb
> +  end
たしかに、practice_id による絞り込みは実装してますのでテスト追加しました。
tagの方は、Vue.js化されていませんので対象外としています。

2022-03-09 13:55 UTC, aim2bpg commented
@cafedomancer さん、ご提案ありがとうございました。
修正完了しましたので、ご確認いただけますと幸いです🙏

2022-03-10 09:14 UTC, cafedomancer commented on test/integration/api/pages_test.rb
> +  end
今回の PR の範囲で言うとそうだと思うんですが、API 単体の仕様としてはタグでの絞り込みができる、かつここは API に対するテストを書く場所なので、仕様があるならそれを確認するテストもここにあるべきだと思いました。そしてこの機能は、通常の Docs の一覧のほうで使われていそう (タグ一覧からタグで絞り込める) です。ただ、この PR の作業範囲としてどこまでのテストの追加を含めるかというのはまた別の話なので、その点は引き続きおまかせです！

2022-03-10 09:14 UTC, cafedomancer commented on test/integration/api/pages_test.rb
> +  end
あれ、なんか test の説明がおかしそう...？ `practice_id` は query string に入るはず。

2022-03-10 09:14 UTC, cafedomancer commented on app/javascript/pages.vue
> +    practiceId: { type: String, default: '', required: false },
default が空文字になっているのは、あんまり意味を成していないような気がしました。値が入っていないことを表現したいのであれば `null` か `undefined` を使う、もしくは props を渡さないときは `practiceId` がそのように設定されるという挙動に任せておく、のどちらかが良いと思います。

2022-03-10 11:16 UTC, aim2bpg commented on app/javascript/pages.vue
> +    practiceId: { type: String, default: '', required: false },
`reports.vue`で`null`が使われていたので、pagesでも`null`を使用しました。

2022-03-10 11:17 UTC, aim2bpg commented on test/integration/api/pages_test.rb
> +  end
たしかに〜😇　`/api/pages.json?practice_id=315059988`に修正しました🙏

2022-03-10 11:32 UTC, aim2bpg commented
@cafedomancer さん、ご指摘ありがとうございました🙇🏻‍♂️
APIのDocs一覧でタグによる絞り込みについても、テスト追加しております。
お手すきの際に、ご確認をお願いいたします🙏

2022-03-10 12:04 UTC, aim2bpg commented
@cafedomancer さん、ご確認ありがとうございました🙇🏻‍♂️  初めてレビューしていただいて勉強になりました〜

@komagata さん、あらためましてレビュー依頼させていただきます🙏

2022-03-10 18:16 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-10 18:16 UTC, merged