一旦コミット(表示されてない)
fjordllc/bootcamp pull request #4319
Opened 2022-02-28 09:01 UTC by eatplaynap

2022-03-18 14:52 UTC, eatplaynap commented
@aim2bpg 
お疲れさまです。だいぶ時間が経ってしまいましたが、ペアプロしていただいたVue化のIssueのPRです。
お手すきの際にレビューをお願いいたします:pray:

2022-03-18 21:09 UTC, aim2bpg commented
@eatplaynap さん、レビュー依頼ありがとうございます。
本日中には確認して、結果をお知らせできればと思います〜😄

2022-03-19 02:25 UTC, aim2bpg requested changes
@eatplaynap さん、動作確認していたらコンフリクトが起きていることに気付きました。
まずは、手元で下記を実行してコンフリクトを解消されてください🙏

```
$ git pull --rebase origin main
```

2022-03-19 09:43 UTC, eatplaynap commented
@aim2bpg 
ご確認ありがとうございます！コンフリクト解消させたので再度ご確認お願いします〜

2022-03-20 09:44 UTC, aim2bpg requested changes
@eatplaynap さん、コンフリクト解消ありがとうございます😄

確認したところ、HTMLのVue.js化でインデントがずれていたり。classが違っていたりしますので、デベロッパーツールで対応をとりながら確認した方が良さそうです。今回Vueファイルを新規作成しており、間違っていても今後なかなか気付きにくい部分ですので、今後のためにも今回きちんと合わせ込みしておいた方が良いと思いました(ここは他の機能でもバグがあったので、間違いやすい部分なのかなと個人的には思っています😅 )。

こちらで確認した際の画面を貼っておきますのでご参考ください。左がステージング環境(Vue.js化前)、右が開発環境(Vue.js化後)

![image](https://user-images.githubusercontent.com/58363353/159156546-39ce993b-fe6e-4871-9cbc-86ee0b51e72d.png)

2022-03-20 09:59 UTC, aim2bpg commented on app/javascript/users-answers.vue
> +    usersPath: { type: String, default: '', required: false }
```suggestion
    usersPath: { type: String, default: null, required: false }
```

ここのdefault値は`null`とした方が良いようです。
理由は、https://github.com/fjordllc/bootcamp/pull/4293#discussion_r823500400 を参照ください。

2022-03-20 10:00 UTC, aim2bpg requested changes
すみません、もう一点ありました。。
default値の設定見直しもお願いいたします🙏

2022-03-21 07:49 UTC, eatplaynap commented
@aim2bpg 
ご確認ありがとうございます！ご指摘の点に加えて、実装に漏れがあった分を修正したので再確認をお願いいたします:pray:
- Vue.js化後のHTMLとVue.js化前に揃えるよう修正
- default値の設定を修正
- 質問の更新日付を表示させるよう修正(:new:)

2022-03-22 04:12 UTC, aim2bpg requested changes
@eatplaynap さん、確認しました。
- もう1箇所変換できてないところがありました👀（下記のスクショ参照、左：ステージング環境、右：開発環境）。
- 今回、目視で気付けたところは再発防止の観点でテストを入れておきましょう💪
バグ関連の修正はテストもセットと考えておいた方が良いと思います（駒形さんから過去にご指摘受けました）。
- 今回変換したことで不要となるファイルはなかったでしょうか。もし、不要であれば削除しておきましょう✨
ex. /app/views/users/answers/_answer.html.slim

![image](https://user-images.githubusercontent.com/58363353/159404567-81408621-6393-4d3e-889c-6dbfa58c2790.png)

2022-03-22 06:08 UTC, eatplaynap commented
@aim2bpg 
丁寧なレビューありがとうございます！ご指摘いただいた下記3点の対応を行いましたのでお手すきの際ご確認お願いします:pray:
- 各回答の名前がユーザー個別ページへのリンクになるように修正
- ↑のテスト追加
- Vue化に伴い使用しなくなった回答一覧関連のデータを削除

2022-03-22 07:48 UTC, aim2bpg requested changes
@eatplaynap さん、確認しました。
さきほどは気付かなかったのですが、回答日時が変換前(左)が更新日時に対して、変換後(右)が作成日時となっているようです。
![image](https://user-images.githubusercontent.com/58363353/159431062-324c215d-7fc8-472b-be12-a937778a0828.png)

あと、question.vueが書き変わっていたのが原因不明というのが気持ち悪い感じがしています。
[この辺](https://github.com/fjordllc/bootcamp/compare/2bbdb15ae04bfaf4c5344cb4b695334c84d9d255..fc9fbabeb808ec25e45edb2c736b49698c1db49c)でRebase時のコンフリクト解消か何かで書き変わっていたりしないでしょうか？おそらく、Files changedに現れない差分かなと思って、レビューできているか心配してます🤔
もし、単純に1箇所だけ誤って書き換えてた〜とかで、クリアとなっていれば余計な心配かもしれません🙏

2022-03-23 05:33 UTC, eatplaynap commented
@aim2bpg 
自分では細かいところを見落としがちなので、たくさん見つけてくださってありがとうございます〜:sob:

## 回答一覧の日付について
ステージング環境の回答一覧の日付を自分の実装したものと見比べたところ、そもそも仕様を勘違いしていたことに気づきました。

修正前: 回答に紐づく質問の作成日時が表示される
修正後(ステージング環境と同じ): 各回答の更新日時が表示される

上記の変更に伴い、jbuilderで渡していた`answer.question.updated_at`も必要なくなったので削除しました。

## `question.vue`の変更について
これは参考にしようと思って触っているうちに書き換えてしまったという認識です。

2022-03-23 06:00 UTC, aim2bpg approved these changes
@eatplaynap さん、修正ありがとうございます。question.vueの変更についても了解しました👍
~~下記の1点を修正いただければ、~~ 私はOKです🙆‍♀️チームリーダーレビューに進められてください👍

@garammasala29 さんの方でVue.js化された質問ページの方のdefault値の設定を修正しておきましょう。
本PRのスコープ外となりますが、動作確認中にコンソールにワーニングが出るのが気になりましたもので😅
→ こちらは、開発MTGでスコープ外とのことでしたので、私の方でIssue登録しておきます🙏

2022-03-23 09:50 UTC, eatplaynap commented
@aim2bpg 
度々のご確認ありがとうございます〜！
#4447 の変更がマージされ、answers.ymlのfixtureが作成できるようになったのでもう一度レビューをお願いいたします:pray:

2022-03-23 10:07 UTC, aim2bpg approved these changes
確認しました、OKですー🙆‍♀️

2022-03-23 10:29 UTC, eatplaynap commented
@aim2bpg ご確認ありがとうございます〜！
@komagata チームメンバーの確認OKをいただいたので、お手すきの際にレビューをお願いいたします:pray:

2022-03-24 05:40 UTC, komagata commented on db/fixtures/answers.yml
> +  <% end %>
```suggestion
<% end %>
```

doとendの間の文字が繰り返されるのでこっちの方がいいかもです〜

2022-03-24 05:40 UTC, komagata commented on db/fixtures/answers.yml
> +  <% 7.upto(50) do |i| %>
```suggestion
<% 7.upto(50) do |i| %>
```

2022-03-24 06:18 UTC, eatplaynap commented
@komagata
ご指摘の箇所を修正しましたので再確認お願いします:pray:
確かにほかのymlファイルでもそのようになっていることを確認しました！

2022-03-25 14:04 UTC, komagata requested changes

2022-03-25 14:04 UTC, komagata commented on app/controllers/api/users/answers_controller.rb
> +# frozen_string_literal: true
既にAnswerのAPIがあるので、そちらにユーザーIDでの絞り込み機能を追加する方がいいかもです〜

https://github.com/fjordllc/bootcamp/blob/main/app/controllers/api/answers_controller.rb

2022-04-01 08:10 UTC, eatplaynap commented on app/controllers/api/users/answers_controller.rb
> +# frozen_string_literal: true
なるほどです〜！新しく作っていたコントローラーを削除しAnswerのAPIに書き加えました〜

2022-04-01 08:11 UTC, eatplaynap commented
@komagata 
お疲れさまです。AnswerのAPIにユーザーIDでの絞り込み機能を追加する形に実装しなおしたので再度レビューをお願いいたします！

2022-04-05 12:20 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-04-05 12:20 UTC, merged