テストで「初日報」を誤判断していたため、修正した
fjordllc/bootcamp pull request #4320
Opened 2022-02-28 11:28 UTC by garammasala29

- #4315

2022-02-28 11:36 UTC, garammasala29 commented
@kaiyu-tech さん
レビューお願いします。30回テストを通らせましたが、落ちないことを確認しています。

2022-02-28 11:47 UTC, kaiyu-tech approved these changes
@garammasala29
30回テストを行いましたが、落ちないことを確認しました！
問題ないと思います！

2022-02-28 11:50 UTC, garammasala29 commented
@kaiyu-tech さん
早速のご確認、本当にありがとうございました🙇‍♂️

@komagata さん
お疲れ様です、ご確認のほどよろしくお願いします。

2022-03-01 04:56 UTC, komagata requested changes

2022-03-01 04:56 UTC, komagata commented on test/fixtures/reports.yml
> +  created_at: <%= Time.now %>
localeを考慮する`Time.current`の方が良いかもです〜

2022-03-01 07:17 UTC, garammasala29 commented on test/fixtures/reports.yml
> +  created_at: <%= Time.now %>
RailsではTimeクラスより極力TimeWithZoneを使った方がよさそうだと、学ぶことができました。
修正致しました→[96d913a](https://github.com/fjordllc/bootcamp/pull/4320/commits/96d913a3dd083d2e40afdbfb66137fe590581bc2)

2022-03-01 07:36 UTC, garammasala29 commented
@komagata さん
お疲れ様です。再度修正いたしました。ご確認のほどよろしくお願いします🙇‍♂️

2022-03-01 08:51 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-01 08:51 UTC, merged