Bug/enable retirement regardless validity of twitter
fjordllc/bootcamp pull request #4321
Opened 2022-02-28 13:55 UTC by clio209

issue #4224 

 ## 概要
### 変更前
![_development__退会・休会手続き___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/155993359-2d90ea19-1641-4fb5-98cc-44b6cbc6edc6.png)
このように、twitterコードが不正の場合、エラーが出て退会できません。
### 変更後
![_development__FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/155993394-00508fbd-bcf3-4480-95a1-2cee4ea57619.png)
退会の際はこのエラーの元になるバリデーションを外すことで退会を可能にしています。

#4220 
こちらと同様のissueであり、参考にしています。

## 確認方法
1. ブランチ`bug/enable-retirement-regardless-validity-of-twitter-id` をローカルに取り込みます。
1. `db/fixtures/users.yml`のユーザーのtwitter IDを1つ不正な値に変更します。
1. `bin/rails db:seed`でユーザー情報をデータに取り込み、`bin/rails s`でサーバーを立ち上げます。
1. 不正なIDにしたユーザーでログインします。
1. 必要項目をチェックし退会するボタンで無事退会できることを確認します。

2022-03-10 13:27 UTC, clio209 commented
@eatplaynap さん
同様のissueを大変参考にさせていただきました。お忙しい中、恐縮なのですが、
お時間あるときにレビューして頂けますと幸いです🙇‍♂️

2022-03-11 01:45 UTC, eatplaynap requested changes
@clio209 
レビュー依頼ありがとうございます！私の立てたIssueへのご対応もありがとうございます😄 `db/fixtures/users.yml`への当該するユーザー情報の登録がされていて、`rails db:seed`だけでtwitterのIDが不正なユーザーが作れるのがありがたかったです〜！

コード自体は問題なさそうでしたが、2点だけご対応お願いします。

- PRがまだドラフトなのでready for reviewに変更をお願いします💪
- descriptionに下記の手順がありますが、`db/fixtures/users.yml`に不正なtwitter IDユーザーがすでに存在しているのでこの部分は削ってよさそうです。
  - > 2.`db/fixtures/users.yml`のユーザーのtwitter IDを1つ不正な値に変更します。

2022-03-11 05:46 UTC, clio209 commented
@eatplaynap 
お忙しいなかレビューいただきまして、誠にありがとうございます！
説明文を修正しまして、ドラフト状態を解消しました。お手隙の際にご確認いただけますと幸いです🙇‍♂️

2022-03-11 05:56 UTC, eatplaynap approved these changes
@clio209 
修正ありがとうございます〜！LGTMです👍

2022-03-11 09:53 UTC, clio209 commented
@eatplaynap  再レビュー、有難うございます！
@komagata  お手すきの際にレビューいただけますと幸いです。

2022-03-14 07:15 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-14 07:15 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-14 07:15 UTC, merged