adminのみ相談クリック時に未返信タブに偏移するように設定
fjordllc/bootcamp pull request #4323
Opened 2022-03-01 12:18 UTC by clio209

issue #4265 

## 概要
admin権限を持つユーザーが相談ボタンをクリックした場合、未返信タブに偏移するように変更しました。

### 変更前
![_development__相談部屋___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/156166990-cbc7a3cd-34be-41e0-ba3e-7cadd56df2bc.png)
admin権限を持つユーザーが「相談」をクリックすると、`/talks`に偏移します。
### 変更後
![_development__未返信のコメント___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/156167021-7b005c3b-fe87-4316-b106-db6aea282142.png)
admin権限を持つユーザーが「相談」をクリックすると、`/talks/unreplied`に偏移します。
## ローカル環境での確認方法
1. admin権限を持つユーザーでログインし、「相談」をクリックして`/talks`に偏移することを確認します。
1. ブランチ `feature/display-talks-unreplied-page-when-logined-as-admin` をローカルに取り込みます。
1. admin権限を持つユーザーでログインし、「相談」をクリックして`/talks/unreplied`に偏移することを確認します。

2022-03-01 18:06 UTC, komagata commented
> adminのみ相談クリック時に未返信タブに偏移するように設定

偏移じゃなくて遷移かも？

2022-03-01 22:13 UTC, clio209 commented
@komagata 有難うございます！修正しました。

2022-03-10 08:54 UTC, clio209 commented
@kazuhi-ra さん
レビュー依頼させていただきました。お忙しい中申し訳ありませんが、お時間ある時に見ていただければ幸いです。

2022-03-11 09:50 UTC, kazuhi-ra commented
@clio209 
レビュー依頼ありがとうございます！
大丈夫そうでした💪

2022-03-11 09:56 UTC, kazuhi-ra approved these changes

2022-03-11 13:04 UTC, clio209 commented
@kazuhi-ra お忙しいなかレビューいただきまして有難うございます！
@komagata お手すきの際にレビューいただけますと幸いです。

2022-03-14 14:37 UTC, komagata commented on app/views/application/_global_nav.slim
> +            - talks_link = admin_login? ? talks_unreplied_index_path : talk_path(current_user.talk)
ちょっと複雑になる場合はHelperのメソッドにするとスッキリするかもです。
この場合はTalksHelperとかにメソッドを追加するといいかもと思いました〜

2022-03-15 02:42 UTC, clio209 commented on app/views/application/_global_nav.slim
> +            - talks_link = admin_login? ? talks_unreplied_index_path : talk_path(current_user.talk)
@komagata 
レビュー有難うございます！
それは、`talks_helper.rb`のファイルを作って、その中に
```
def unreplied_tab_for_admin（仮名）
admin_login? ? talks_unreplied_index_path : talk_path(current_user.talk)
end
```
のようなメソッドを書くというイメージで合ってますでしょうか？

2022-03-15 03:38 UTC, komagata commented on app/views/application/_global_nav.slim
> +            - talks_link = admin_login? ? talks_unreplied_index_path : talk_path(current_user.talk)
はい。

元の変数名で使われているようにURL（LINK）であることがわかりやすい名前にしつつ、また`current_user.talk`はヘルパーの引数に与える形がいいかもです〜（テストしづらいので）

2022-03-15 07:13 UTC, clio209 commented on app/views/application/_global_nav.slim
> +            - talks_link = admin_login? ? talks_unreplied_index_path : talk_path(current_user.talk)
@komagata 
コメント有難うございます！修正しました。メソッド名等、意図と合致していないかもしれません。
ご確認いただけますと幸いです。

2022-03-15 20:26 UTC, komagata requested changes

2022-03-15 20:26 UTC, komagata commented on app/helpers/talks_helper.rb
> +    admin_login? ? talks_unreplied_index_path : talk_path(resource)
`resource`ですとありとあらゆるものが当てはまる名前なので、単に`talk`とかがいいかもです〜

2022-03-15 20:26 UTC, komagata commented on app/views/application/_global_nav.slim
> +            - talks_link = unreplied_index_path(current_user.talk)
メソッドにしたので一旦変数に入れる必要はないと思います〜。（この変数に代入するだけの行をViewファイルの中に作らないためにヘルパーにするという感じです）

2022-03-16 01:41 UTC, clio209 commented on app/views/application/_global_nav.slim
> +            - talks_link = unreplied_index_path(current_user.talk)
@komagata 何度もレビュー有難うございます！`talk_link`を使わないよう修正しました。

2022-03-18 18:11 UTC, komagata commented on app/views/application/_global_nav.slim
> +            = link_to unreplied_index_path(current_user_path), class: "global-nav-links__link #{current_link(/talk/)}" do
やりたいことが伝わるコードになりつつ、Viewがスッキリしましたね👍

2022-03-18 18:11 UTC, komagata commented on app/helpers/talks_helper.rb
> +  def unreplied_index_path(talk)
新しいHelperができたのでセットでヘルパーのテストも欲しいですね〜！

2022-03-20 03:27 UTC, komagata commented on test/system/talks_test.rb
> +    url = '/talks/unreplied'
一度しか使わないのであれば変数に入れないで大丈夫かもです〜。

2022-03-21 04:35 UTC, clio209 commented on test/system/talks_test.rb
> +    url = '/talks/unreplied'
@komagata 有難うございます。削除いたしました。

2022-03-21 12:44 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-21 12:44 UTC, merged

2022-03-22 03:58 UTC, clio209 commented
@komagata 
何度もみていただき、本当に有難うございました！