管理者でログインしたとき、相談部屋個別ページで相談部屋の主の直近の日報が表示される。
fjordllc/bootcamp pull request #4389
Opened 2022-03-12 16:02 UTC by chung3011

[#4208](https://github.com/fjordllc/bootcamp/issues/4208)
## 要件
管理者でログインしたとき、相談部屋個別ページで相談部屋の主の直近の日報が表示される。
## 変更前
<img width="1366" alt="Screen Shot 2022-03-12 at 23 00 26" src="https://user-images.githubusercontent.com/34033366/158025297-7ddf539f-63bf-4146-bff7-f5466569a482.png">
## 変更後
<img width="1365" alt="Screen Shot 2022-03-12 at 23 00 59" src="https://user-images.githubusercontent.com/34033366/158025314-c60a7e92-0671-40c6-ac03-dd2c86e11662.png">
## 確認手順
- `feature/show-daily-report-in-talk-page-for-admin`ブランチを手元に持ってくる。
- 管理者でログインして、相談部屋個別ページを確認する。

2022-03-12 16:21 UTC, chung3011 commented
@garammasala29 さん、、このPRをチェックしていただけませんか？

2022-03-14 02:34 UTC, garammasala29 requested changes
@chung3011 さん
お疲れ様です。
日報一覧はVue化されていて、そちらを使えばよさそうです(ユーザー日報ページのサイドバー　を参照していただければ)
コントローラーやモデルのコードを追加しなくても日報が表示されると思いました👍

2022-03-14 02:34 UTC, garammasala29 commented on app/models/user.rb
> +    reports.order(reported_on: :DESC).first(3)
`latest_reports`という名前だと最新の日報1つとなるような気がしました。
また、issueの画像にて「最新の日報を10件表示する」と書かれていますが、いかがですか？

2022-03-14 02:34 UTC, garammasala29 commented on app/views/talks/show.html.slim
> +              .side-tabs-contents__item#side-tabs-content-2
デザイン部分はよいと思います😄

2022-03-14 05:44 UTC, chung3011 commented on app/models/user.rb
> +    reports.order(reported_on: :DESC).first(3)
メソッドの名前と日報数を更新しました。

2022-03-14 06:38 UTC, garammasala29 commented on app/models/user.rb
> +    reports.order(reported_on: :DESC).first(3)
@chung3011 さん
確認いただきありがとうございました🙏
せっかく修正していただいたんですが、大枠のコメントにも書きましたようにVue化されている日報一覧を再利用する形にすると、コントローラーとモデル部分のコードは全て必要なくなるかと思います！
少し紛らわしかったですね💦

2022-03-14 07:29 UTC, chung3011 commented on app/models/user.rb
> +    reports.order(reported_on: :DESC).first(3)
@garammasala29 さん、コードを更新しました。もう一度確認お願い致します。

2022-03-14 08:41 UTC, garammasala29 requested changes
@chung3011 さん
修正いただきありがとうございました！意図が伝わり安心しました😄
1点だけコメントしましたので、確認よろしくお願いします🙏

2022-03-14 08:41 UTC, garammasala29 commented on app/views/talks/show.html.slim
> +                #js-reports(data-user-id="#{@talk.user.id}" data-limit="10")
`@talk.user.id`ととってくる情報は変わりませんが、コントローラーを見ると`@user.id`でもidは設定できるようです。
上の`js-user-mentor-memo`でも`@user.id`が使われているので合わせた方が無難なのかな？と思いましたがどうでしょうか🤔？

2022-03-14 10:28 UTC, chung3011 commented on app/views/talks/show.html.slim
> +                #js-reports(data-user-id="#{@talk.user.id}" data-limit="10")
@garammasala29 さん、コードを更新しました。もう一度確認お願い致します。

2022-03-14 11:08 UTC, garammasala29 approved these changes
@chung3011 さん
修正ありがとうございました🙏LGTMです！

2022-03-14 11:16 UTC, chung3011 commented
@komagataさん、レビューをしていただきたいです。よろしくお願いいたします🙏

2022-03-14 14:54 UTC, komagata reviewed
最近の日報が表示されていることを確認するテストがあるといいかもです〜

2022-03-15 09:59 UTC, chung3011 commented
@komagataさん、テストを追加しました。もう一度確認お願い致します🙏

2022-03-15 20:28 UTC, komagata requested changes
"edit code"や"add test"というコミットメッセージがありますが、後から見た人がわかりやすいように具体的に書いてみて下さい〜。

2022-03-15 23:55 UTC, chung3011 commented
@komagata さん
はい、わかりました。今から注意します。

2022-03-16 02:26 UTC, chung3011 commented
@komagata さんから「Changes requested」を受け取りました。 今何を修正するか教えていただけますか？ 「コミットメッセージを書く」について、次回注意します。

2022-03-16 03:57 UTC, garammasala29 commented
@chung3011 さん
過去のコミットメッセージをわかりやすいものに変更するといいと思いますよ👍

2022-03-16 14:02 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-16 14:02 UTC, merged