[WIP]未アサインの提出物一覧の並び順を逆にしたい
fjordllc/bootcamp pull request #4399
Opened 2022-03-14 06:48 UTC by Aseiide

## 関連issue
- #4312

2022-03-14 10:20 UTC, Aseiide commented
@Saki-htr  こちらレビューお願いいたします！

2022-03-16 09:47 UTC, konaga-k commented
横からすみません、気になったので質問させて下さい〜
これって他の提出物タブについて並び順を昇順にしたほうが自然かどうかは議論されてるんでしょうか？
未完了や自分の担当の提出物について、経過日数が多いもの（ほったらかしのもの）と少ないもの（新しく提出されたもの）のどちらを優先してみたいのかは意見が割れそうだと思いました
あと未アサインタブとそれ以外のタブで並び順が違うと、利用者視点で単純に疑問が湧くんじゃないかというのもあります
（既に議論済みだったらすみません🙇）

2022-03-16 13:57 UTC, Aseiide commented
@konaga-k 
コメントありがとうございます。
ご指摘の点については、議論していないませんでした。

確かに、未アサインのタブの並びだけ変わると混乱するかもしれないですね。
現在、提出物一覧ページにおいてタブ「全て」「未完了」「自分の担当」は降順になっていて、今回の変更でタブ「未アサイン」のみ昇順となりますね。

@machida @komagata 
konagaさんのコメント含め、タブ「未アサイン」とその他のタブで並び順が変わってします点はいかがいたしましょう??

2022-03-17 12:43 UTC, Saki-htr reviewed
@Aseiide 
お疲れさまです。
動作確認したところOKでした🙆‍♀️
コードも良いと思います! 提出物の並び順をテストする時はこのように書くのですね〜。とても勉強になりました🙏

一点気になったのですが、descriptionの変更前と変更後の画像の、**黒字の「提出日時が古い」「提出日時が新しい**」の部分が、実際の変更内容と逆になっているようですので、修正した方がいいかなと思いました。

他のタブと並び順が変わる点について確認中でいらっしゃるので、新たに仕様追加があるかもしれませんので、まだ`Approve`はしないでおきます〜
よろしくお願いいたします🙇‍♀️

2022-03-18 18:43 UTC, komagata commented
@Aseiide (cc: @machida)

> konagaさんのコメント含め、タブ「未アサイン」とその他のタブで並び順が変わってします点はいかがいたしましょう??

僕は他も全部今回の新しいのと同じ並びにするのがいいかな〜と思いました。
もしすごく大変な作業になるようでしたら言っていただければと思います〜。

2022-03-21 02:59 UTC, Aseiide commented
@Saki-htr 
レビューありがとうございました！要件に変更があるので、その修正をしたら再度レビュー依頼させてもらいますね。

@komagata 
承知しました。他のタブも同様に順番並び替えるようにします。おそらくそんなに大変ではないと思いますが、なにか有りましたら相談します。

2022-03-21 12:44 UTC, komagata commented
@Aseiide ありがとうございます！結構手間が増えそうなのでIssueのポイントを3に増やしておきました〜！

2022-03-23 02:22 UTC, Aseiide commented
## やるべきこと

---
【未アサイン】
上
提出日時が古いもの
提出日時が新しいもの
下
---

---
【未完了】
上
提出日時が古いもの
提出日時が新しいもの
下
---

---
【全て】
上
提出日時が古いもの
提出日時が新しいもの
下
---

2022-03-23 06:15 UTC, Aseiide commented
コメント無が上に来る
コメント有りは下に置く
コメントありのときは、
コメントの古いものが上
コメントが新しいものが下

2022-03-24 05:50 UTC, komagata commented
:memo: システムでよく使う表現として昇順、降順という言葉があるのでそれを使うと厳密に表現できるかもです。

2022-03-25 13:32 UTC, Aseiide reviewed
タブ・未アサインだけでなく、他のタブも昇順にし、関連するテストの修正を行いました。

2022-03-25 13:32 UTC, Aseiide commented on app/models/product.rb
> +  scope :order_for_self_assigned_list, -> { order('commented_at asc nulls first, published_at asc') }
`nulls first`を指定することで`comment_at`が`nil`のものが上に表示されます。

2022-03-25 13:32 UTC, Aseiide commented on app/models/product.rb
> +  scope :ascending_by_date_of_publishing_and_id, -> { order(published_at: :asc, id: :asc) }
idは昇順がいいのか、降順がいいのかわからなかったのですが、`published_at`に合わせて昇順にしています

2022-03-28 13:34 UTC, Aseiide commented on test/integration/api/products_test.rb
> +    assert_equal expected, actual
`expected` `actual` それぞれの変数名が適切かあんまりわかってない

2022-03-28 13:34 UTC, Aseiide commented on test/fixtures/products.yml
> +  published_at: <%= Time.current %>
日時の違う提出物が必要だったため、新たに定義

2022-03-29 00:49 UTC, Aseiide commented
@Saki-htr 
再実装終わりましたのでレビューお願いします。
前回レビューいただいたときから要件が変わっていて、テキストのやり取りだと説明が難しいのでDiscordで繋ぎながらレビューさせてもらえると良いかもしれないです。

CIが落ちてるのは、 #4517 の修正でなおりそうです。

2022-03-29 05:17 UTC, Aseiide commented
実装が複雑になったので、`4/2 14時`からペアプロでsakiさんにレビューしてもらう。

2022-04-03 09:37 UTC, Saki-htr requested changes
@Aseiide 
ペアプロで大変丁寧にご説明くださって、ありがとうございました。
動作確認はOKでした🙆‍♀️✨
気になった点をいくつかコメントさせていただきましたので、ご確認をお願いいたします〜🙏

2022-04-04 06:40 UTC, Aseiide reviewed
@Saki-htr 
テストの修正と`commented_at`が不要だった件に対応したのでレビューお願いいたします。

2022-04-04 06:40 UTC, Aseiide commented on app/models/product.rb
>    scope :order_for_list, -> { order(created_at: :desc, id: :desc) }
こちら、自分の勘違いでした。
`order_for_list`を提出物一覧ページで使っている部分は`ascending_by_date_of_publishing_and_id`に置き換えているのでここの`created_at`は変更不要でした。

2022-04-04 06:40 UTC, Aseiide commented on app/models/product.rb
>    end
「自分の担当」の未返信で使われているのですが、未返信の時点で`commented_at`には何も入ってなく、意味を為していなかったので削除し、`published_at` と `id` で並ぶようにしました。

2022-04-06 12:10 UTC, Saki-htr commented
@Aseiide 
ご修正ありがとうございます！
おまたせしていてすみません、明日にはお返しできるようにいたします🙏

2022-04-06 12:12 UTC, Aseiide commented
@Saki-htr  全然だいじょうぶです！

2022-04-07 01:22 UTC, Saki-htr approved these changes

2022-04-07 01:37 UTC, Saki-htr commented
@Aseiide 
テストの修正と、`commented_at`の削除を確認しました🙆‍♀️
komagataさんに仕様について質問したことや、実装について細かくPRにメモされていて、他の方から見ても分かりやすくなっていて素晴らしいと思いました👏 descriptionの、変更前と変更後のスクリーンショットイメージも、一度目よりも一層見やすくなっていて良いと思いました!

ペアプロした際に、"「自分の担当」タブの「全て」欄の、コメント有りと無しの境目がどこか分かりづらい" 点についてお話したかと思うのですが、
- 今回のissue内容は提出物の"並び順"を変更することである
- リリースされてメンターの方々に使っていただいてから検討していくことではないか

と考えましたので私の方では`Approve`させていただきます☺️ 


![image](https://user-images.githubusercontent.com/58052292/162101951-dc851d89-d66a-44a8-9aa7-a687b4e96229.png)

よろしくお願いいたします。

2022-04-07 02:43 UTC, Aseiide commented
@Saki-htr 
レビューありがとうございました！
> コメント有りと無しの境目がどこか分かりづらい

こちらはリリース後にissueつくってメンターさんの反応を見るのが良さそうです。

@komagata 
チームメンバーのレビューが通りましたのでレビューお願いします。

2022-04-07 02:46 UTC, Aseiide commented on app/models/product.rb
> +  scope :ascending_by_date_of_publishing_and_id, -> { order(published_at: :asc, id: :asc) }
@komagata 
idは昇順が良いか、降順が良いかわからなかったのでアドバイスいただけると嬉しいです。
自分としては、`published_at: :asc`に合わせてidも昇順にしています。

2022-04-08 05:00 UTC, komagata requested changes

2022-04-08 05:00 UTC, komagata commented on test/integration/api/products_test.rb
> +  test ' should return products in order ' do
```suggestion
  test 'should return products in order ' do
```

2022-04-09 05:39 UTC, Aseiide commented
@komagata  レビューありがとうございます。修正したのでレビューお願いいたします。

2022-04-13 11:58 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-04-13 11:58 UTC, merged