[相談部屋] 管理者が見る相談部屋一覧の各相談部屋に、最新コメントの投稿日時と投稿者を出す
fjordllc/bootcamp pull request #4411
Opened 2022-03-15 09:54 UTC by chung3011

[#4208](https://github.com/fjordllc/bootcamp/issues/4208)

## 要件
管理者でログインしたとき、相談部屋一覧の各相談部屋に、
- コメント合計数
- 最新コメントをした人のアイコン
- 最新コメント日時
- 最新コメントをした人のロール
表示する。

## 変更前
<img width="566" alt="Screen Shot 2022-03-15 at 16 52 52" src="https://user-images.githubusercontent.com/34033366/158352207-293f41a2-a794-44b6-a7ff-dcf22038ea1c.png">

## 変更後
<img width="563" alt="Screen Shot 2022-03-15 at 16 53 20" src="https://user-images.githubusercontent.com/34033366/158352293-ff56bf15-06a4-499a-b8c9-a8cf82c037e5.png">

## 確認手順
- `feature/display-time-of-comment-in-talks-list`ブランチを手元に持ってくる。
- 管理者でログインして、相談部屋一覧ページを確認する。

2022-03-15 10:41 UTC, chung3011 commented
@garammasala29 さん、このPRをチェックしていただけませんか？

2022-03-17 03:41 UTC, garammasala29 requested changes
@chung3011 さん
お疲れ様です。レビュー依頼ありがとうございました😄
気になった部分にコメントしています。
issueではユーザーロールの枠の緑色が出ていたり、今回viewの部分も触っていますので、
一度町田さんに現状で問題ないか確認をしてもらってもいいのかなと思いました！

2022-03-17 03:41 UTC, garammasala29 commented on test/system/talks_test.rb
> +    assert_text 'メンター'
`assert_text 'メンター'`ですと、ヘッダーなどにもある、ありとあらゆる「メンター」に引っ掛かってしまうので`assert_selector`にtextオプションを使うといいかなと思います。
管理人へ文言変更しても同様です👍
現役生が相談部屋を利用することが多いと思うので、現役生対象のページでテストをしたほうがいいのかなとも思いました。

2022-03-17 03:41 UTC, garammasala29 commented on test/system/talks_test.rb
> +    find('#talks.loaded', wait: 10)
何かなと思いましたが、Flakyなテスト予防と考えていいのでしょうか？🤔
自分の手元ではこの行がなくても問題なかったので気になりました。

2022-03-17 06:45 UTC, chung3011 commented on app/javascript/talk.vue
> +                | (メンター)
![image](https://user-images.githubusercontent.com/34033366/158751896-6b2b42a6-fc0b-49fc-8d0d-83224fd9b1d9.png)
issueの要件があるから、ロールを表示にします。

2022-03-17 08:24 UTC, chung3011 commented on test/system/talks_test.rb
> +    find('#talks.loaded', wait: 10)
この行がなくても問題なかったです。削除します。

2022-03-17 08:32 UTC, chung3011 commented on test/system/talks_test.rb
> +    assert_text 'メンター'
テストを編集しました。

2022-03-17 08:39 UTC, chung3011 commented
@garammasala29 さん、ご確認ありがとうございます。
もう一度チェックをお願いします。

2022-03-18 00:23 UTC, garammasala29 requested changes
@chung3011 さん
お疲れ様です、修正ありがとうございました🙏
いくつかコメントしています。
前回コメントで提案させていただいたデザインの部分はどうされますか？

2022-03-18 00:23 UTC, garammasala29 commented on test/system/talks_test.rb
> +    assert_selector '.thread-list-item-comment', text: '(hajime)'
```suggestion
    within ('.thread-list-item-comment') do
      assert_text 'コメント'
      assert_selector 'img[class="a-user-icon"]'
      assert_text '(1)'
      assert_text '2019年01月02日(水) 00:00'
      assert_text '(hajime)'
    end

2022-03-18 00:23 UTC, garammasala29 commented on test/system/talks_test.rb
> +    assert_selector '.thread-list-item-comment', text: '(hajime)'
これでテスト範囲の絞り込みもできるかなと思いました。
画像も有無もつけてみたんですが、どうでしょうか？(あまりコードに自信はないです😅)

2022-03-18 00:23 UTC, garammasala29 commented on app/javascript/talk.vue
> +                | (メンター)
この画像はissueの要件というより、参考画像だと思います！
> 最新コメントをした人のロール（相談者 or 管理者）どちらかを表示する

とあるのでその要件に沿った形がいいと思います。
加えて、bootcampのアプリでは「アドミン」という表記はなく、全て「管理者」という名前になっているようです。

2022-03-18 02:02 UTC, chung3011 commented
@garammasala29 さん、ご確認ありがとうございます。
デザインとテストを修正しました。
もう一度チェックをお願いします。

2022-03-18 21:39 UTC, garammasala29 approved these changes
@chung3011 さん
お疲れ様です。LGMTです！ありがとうございました👍
デザインに関しては
> issueではユーザーロールの枠の緑色が出ていたり、今回viewの部分も触っていますので、
一度町田さんに現状で問題ないか確認をしてもらってもいいのかなと思いました！

と書いた部分です。判断はお任せします🙏

2022-03-18 23:59 UTC, chung3011 commented
@komagata さん
お疲れさまです！チェックをお願いいたします！🙏

2022-03-19 11:29 UTC, komagata commented on app/views/api/talks/index.json.jbuilder
> +      json.lastCommentTime l talk.comments.last.updated_at
railsのルールに従って、`last_commented_at`などにするのがいいかもです〜。

2022-03-19 14:07 UTC, chung3011 commented on app/views/api/talks/index.json.jbuilder
> +      json.lastCommentTime l talk.comments.last.updated_at
<img width="645" alt="Screen Shot 2022-03-19 at 21 02 46" src="https://user-images.githubusercontent.com/34033366/159124141-66524d17-d61d-4fd9-88e4-b668ac47871e.png">
私はやってみましたが、Talkのモデルにそのメソッドがありません。

2022-03-20 03:30 UTC, komagata commented on app/views/api/talks/index.json.jbuilder
> +      json.lastCommentTime l talk.comments.last.updated_at
あ、このJSONは自分で名前をつけてますが（左辺のことです）、その名前を`last_commented_at`にしたらいいかなという意味です〜。

「railsではDateは`動詞の過去形_on`でDateTimeのカラムは`動詞の過去形_at`」という名前付のルールがあるのでそれにしたがった方がわかりやすいと思います。

2022-03-20 04:55 UTC, chung3011 commented on app/views/api/talks/index.json.jbuilder
> +      json.lastCommentTime l talk.comments.last.updated_at
@komagata さん、申し訳ありませんが、日本語がよくないので、もう一度確認したいと思います。

> 左辺のこと

 `json.lastCommentTime`から `json.lastCommentedAt`に切り替えることですか？

2022-03-21 15:30 UTC, chung3011 commented on app/views/api/talks/index.json.jbuilder
> +      json.lastCommentTime l talk.comments.last.updated_at
@komagata さん
お疲れさまです！
コードを変更しました。snake_caseを使っています。
もう一度チェックをお願いいたします！🙏

2022-03-23 00:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-23 00:17 UTC, merged