日報の個別ページでpublished_atがnilでもエラーが出ないように修正
fjordllc/bootcamp pull request #4464
Opened 2022-03-22 04:32 UTC by clio209

issue #4326 

## 概要
メンター権限を持つユーザーが個別ユーザーの日報を開くとき、その個別ユーザーの提出物の`published_at`が`nil`の時、
error`NoMethodError in Reports#show`が発生するため、`published_at`が`nill`の場合でもエラーが出ないように修正しました。
### 変更前
https://user-images.githubusercontent.com/64455939/159407732-66eda55f-ae48-42ab-8ba6-6a97213ef66e.mp4
### 変更後
https://user-images.githubusercontent.com/64455939/159407997-9e731b4f-76cd-40a7-a4c5-5ce90f202483.mp4

## 確認方法
1. `main`ブランチで、メンター権限を持つユーザーでログインし、日報一覧から`publish_at`が`nil`の提出物を持つ`kimura`氏の日報をクリックし、エラーを確認します。
1. ブランチ`bug/report_product_error_with_published_at_nil` をローカルに取り込み、1と同様の作業を行なって、エラーが出ないこと、提出物が見れることを確認します。

2022-03-22 04:55 UTC, clio209 commented
@saeyama さん
お忙しい中、恐縮なのですが、お時間あるときにレビューして頂けますと幸いです🙇‍♂️

2022-03-22 13:54 UTC, saeyama commented
@clio209 さん、レビュー依頼ありがとうございます！

`kimura`氏の日報でエラーが出ないこと、確認出来ました！

以下、気になった点です。

- `Draft Pull Request`になっていたので`Pull Request`に変更された方が良いと思います…！
- Files changedの`_product.html.slim`ですが、どこで使われているのか確認したところ、見つからなかったのですが、そもそもこのファイルって必要なのでしょうか…？（無知だったら申し訳ないです🙇‍♀️ ）
一応試しに、`main`で`_product.html.slim`を消してエラーの出ていた箇所をクリックしたらエラーにならなかったです。
- バグの時は、テストが必要になると聞いています。`_product.html.slim`ファイルが必要だった場合は、テストについてもご確認をお願い致します。

よろしくお願いします🙏

2022-03-22 13:54 UTC, saeyama commented
@clio209 さん、レビュー依頼ありがとうございます！

`kimura`氏の日報でエラーが出ないこと、確認出来ました！

以下、気になった点です。

- `Draft Pull Request`になっていたので`Pull Request`に変更された方が良いと思います…！
- Files changedの`_product.html.slim`ですが、どこで使われているのか確認したところ、見つからなかったのですが、そもそもこのファイルって必要なのでしょうか…？（無知だったら申し訳ないです🙇‍♀️ ）
一応試しに、`main`で`_product.html.slim`を消してエラーの出ていた箇所をクリックしたらエラーにならなかったです。
- バグの時は、テストが必要になると聞いています。`_product.html.slim`ファイルが必要だった場合は、テストについてもご確認をお願い致します。

よろしくお願いします🙏

2022-03-22 22:26 UTC, clio209 commented
@saeyama さん
レビュー有難うございます！🙌
- draftから変更しました。申し訳ありません、ご確認有難うございます！
- `_product.html.slim`は個別日報の右にある提出物一覧を表示するものかと思うので、おそらく削除すると、個別日報の右にある提出物一覧が表示されない（提出物`product`がある場合）`ActionView::MissingTemplate in Reports#show`といったエラーが出るかとは思うのですが、、問題ないとすると、自分の認識が間違っているかもしれません。。💦
- 本バグのテストは悩んだんですが、dbに`published_at`が`nil`のもの（`product63`が該当）があるため、rollbarで確認できれば必要ないのでは、と必要かどうか悩みました・・。

@komagata さん
お忙しいところ恐縮ですが、本issueのエラーの修正は、テストは必要でしょうか？それとも、rollbarで正常が確認できればOKでしょうか？

2022-03-23 01:00 UTC, komagata commented
@clio209 system testで「published_atがnilのデータがあってもページが表示される」というテストが欲しいですね。

2022-03-23 12:49 UTC, saeyama commented
@clio209 さん、削除して確認したら提出物一覧表示されませんでした…！　
失礼しました🙇‍♀️ 💦　説明ありがとうございます！

> _product.html.slimは個別日報の右にある提出物一覧を表示するものかと思うので、おそらく削除すると、個別日報の右にある提出物一覧が表示されない（提出物productがある場合）ActionView::MissingTemplate in Reports#showといったエラーが出るかとは思うのですが、、問題ないとすると、自分の認識が間違っているかもしれません。。💦

2022-03-24 00:10 UTC, clio209 commented
@komagata さん
コメント有難うございます！テストを付け足してみました。
@saeyama さん
komagataさんのアドバイスを受け、テストを付け足しました。お手隙の際にご確認いただけますと幸いです🙇‍♂️🙏

2022-03-24 12:38 UTC, saeyama reviewed
@clio209 さん、ありがとうございます！
お手数ですが、ご確認お願いします🙏
レビュー内容に間違い等あれば、お手数ですが、ご指摘いただければと思います…🙇‍♀️

2022-03-24 12:38 UTC, saeyama commented on test/system/products_test.rb
> +  end
systemテストで実施している内容は、多分下記の内容でテストされているかと思うので`published_at`の内容が加味されていないかと思います…!

`test/fixtures/reports.yml`

```
report18:
  user: daimyo
  title: テストのnippou
  emotion: 2
  description: |-
    今日は1時間学習しました。
  reported_on: "2020-06-01"
  created_at: "2020-06-01 18:00:00"
```

`test`のフォルダにテストデータを用意する必要があるかと思います。
また`products`に書かれていたのですが、書くとしたら`reports`のところに合わせた方が良いと思いました。

2022-03-24 13:03 UTC, clio209 commented on test/system/products_test.rb
> +  end
@saeyama  さん
お忙しいところ再度レビューいただき、誠にありがとうございます！
仰る通りで`reports`に移動しました。
テストの内容につき、説明不足で申し訳ありません。。上記dbの追加dataを取り込むと(`bin/rails db:seed`)、ユーザ`daimyo`が提出物（`product`）に`published_at` `nil`を持つようになる、という仕組みになっております。

2022-03-24 13:52 UTC, saeyama approved these changes
@clio209 さん
説明ありがとうございます！無知で申し訳ないです…🙏
以前、別の方のレビューをした時に、dbとtest両方のfixturesに、同じ内容を書かれていたのを記憶していたので必要だと思ってました。。
テスト通過したこと確認出来たのでApproveしました！
よろしくお願いします🙇‍♀️

2022-03-24 14:28 UTC, clio209 commented
@saeyama さん
すいません！自分のミスです！`test`の`fixtures`の方にも追加すべきでした💦😰
コメント、本当にありがとうございます！

2022-03-24 15:06 UTC, saeyama commented
@clio209 さん、ありがとうございます！
テスト通過したの確認出来ました！
チームリーダーレビューにお進み頂ければと思います🙏

2022-03-24 21:56 UTC, clio209 commented
@saeyama さん
何度も確認していただいて、本当にありがとうございます！
@komagata さん
お手隙の際に、レビューいただけますと幸いです。

2022-03-25 12:57 UTC, saeyama requested changes
追加で気になるところがあったので確認をお願い致します🙏

2022-03-25 12:57 UTC, saeyama commented on test/system/reports_test.rb
> +  end
```suggestion
  test 'mentors can see reports page if products published_at is nil' do
    visit_with_auth '/reports/unchecked', 'mentormentaro'
    click_link 'テストのnippou'
    assert_text '2020年06月01日 の日報'
    assert_text '今日は1時間学習しました。'
  end  
```

@clio209 さん、一度approveさせてもらったのですが、2点確認をお願いします！
- テスト名に全角スペースが含まれていたので半角スペースに修正をお願いします！（後付けですいません💦）
- テストのところを上記のように、日報一覧からpublished_atがnilの提出物を持つ人の日報をクリックして日報が表示される方がテスト内容が明確になるので良いのかと思いました…！
あくまで個人的な一意見なのでご判断は@clio209 さんにお任せします🙇‍♀️
ご確認お願いします🙏

2022-03-25 14:48 UTC, clio209 commented on test/system/reports_test.rb
> +  end
@saeyama さん
お忙しい中、見ていただき、誠に有難うございます。
suggestいただいた内容に修正いたしました🙇‍♂️

2022-03-26 03:49 UTC, saeyama approved these changes
@clio209 さん、ありがとうございます！
あくまでも一意見なので、チームリーダーのレビューでやり直しになったらすいません…🙏
あと他の方にも確認を取ったので、認識に相違無いように念の為お伝えすると、やはりテストをする時は、`test`のfixturesを見てテストをすることになるようです…！`db`のfixturesはdevelopment環境で確認出来る内容になります。
改めてApproveしました！よろしくお願いします🙇‍♀️

2022-03-26 04:32 UTC, clio209 commented
@saeyama さん
何度もレビューいただき、本当にありがとうございます！テストデータの件含め、非常に勉強になりました！感謝感謝です。
@komagata さん
お手隙の際にレビュー賜れますと幸いです。

2022-03-28 07:34 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-28 07:34 UTC, komagata reviewed
すみません、見逃しててOKしちゃってました。
conflictがあるのでそちらの修正をお願いします〜。

2022-03-29 06:56 UTC, clio209 commented
@komagata さん
コメントありがとうございます。コンフリクト解消し、upしました。よろしくお願いいたします。

2022-03-30 03:41 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-03-30 03:41 UTC, merged