相談部屋にアクセスすると表示される404エラーを解消
fjordllc/bootcamp pull request #4492
Opened 2022-03-24 10:45 UTC by clio209

- issue #4485 
## 概要
相談部屋のグローバルナビから相談部屋に偏移すると、URLに/current_userが文字列で渡って404エラーが表示される問題が起こるのを、変数`current_user_path`を`current_user.talk`に変更することで修正しました。
### 変更前
URL `https://bootcamp.fjord.jp/talks/%2Fcurrent_user`
![ご指定のページが見つかりません](https://user-images.githubusercontent.com/64455939/159899504-e8a87055-0504-476e-8e09-f0d3c0272060.png)
### 変更後
![_development__kimuraさんの相談部屋___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/159899684-9491773f-5fba-41d4-b30a-1019faa4de5b.png)

2022-03-24 11:06 UTC, clio209 commented
@komagata さん
お忙しいところ、本当に申し訳ありません。ご確認をよろしくお願いします🙏

2022-03-24 11:15 UTC, komagata requested changes
この修正前は通らず、修正後に通るようなテストがあるといいですね。
バグの修正PRはデグレを防ぐために基本的にそういう感じになっております〜。

2022-03-24 12:17 UTC, clio209 commented
@komagata さん
テスト、申し訳ありません。追加いたしました。
お手数ですが、ご確認頂けますと幸いです。

2022-03-25 14:05 UTC, komagata approved these changes
修正ありがとうございます！

確認しました、OKですー🙆‍♂️

2022-03-25 14:05 UTC, merged

2022-03-25 14:52 UTC, clio209 commented
@komagata さん
この度は本当にご迷惑をお掛けしました。
ご確認、本当にありがとうございます！

2022-03-27 03:10 UTC, komagata commented
@clio209 全然大丈夫です、お気になさらず〜！
実際の仕事で障害があったときの練習になればと思います〜。