検索結果一覧でWIPの日報やDocsを識別できるようにした
fjordllc/bootcamp pull request #4501
Opened 2022-03-25 13:33 UTC by eatplaynap

- #4420

2022-03-28 09:01 UTC, eatplaynap commented
@clio209 
お疲れさまです！お手すきの際にこちらのコードのレビューをお願いいたします:pray:

2022-03-29 13:29 UTC, clio209 commented on app/javascript/searchable.vue
> +      if (this.searchable.no_wip) {
@eatplaynap さん
レビュー依頼有難う御座います〜。ブランチを取り込み、適切に挙動することを確認しました。
jbuilder,wip etc.自分は知識が乏しいので学習のために一点お伺いしたいのですが、こちらは
```
if (this.seachable.wip)...
else ...
```
にしない理由は、all? 等でしょうか、、理由を教えていただければ幸いです〜。

2022-03-31 08:32 UTC, eatplaynap commented on app/javascript/searchable.vue
> +      if (this.searchable.no_wip) {
@clio209 
さっそくのレビューありがとうございます！
結論からお伝えすると、このように書かないと動かないと勘違いしていたので読みづらいコードになってしまっていました。リファクタリングを行いましたので改めてレビューお願いいたします〜！

あとすみません、`all?`等というのが何のことか自分では分かりませんでした…！もしよかったら教えていただけると幸いです:pray:

<前回までのコードを書いていた理由>
検索可能なモデルは以下の10個で、そのうち太字にした6個がWIPという状態を取ることが可能で、booleanが入るwipというカラムを持っています。
- **Announcement**
- Answer
- Comment
- **Event**
- **Page**
- Practice
- **Product**
- **Question**
- **Report**
- User

一方WIP状態を持てないモデルは、カラムwipがそもそも存在しないので、wipの値がtrueかfalseかという判定が行えません。そのため全てのモデルからJSONで返ってくる情報に対し、jbuilderで`no-wip`という属性を与え、trueかfalseかが受け取れるようにしていました。
しかし、仰る通り①WIP状態になれるけどwipがfalseのモデルも、②そもそもWIP状態を持てないモデルもどちらも`if (this.seachable.wip) ~else`の`else`で捕捉できるため、`no-wip`という属性は必要ありませんでした！

2022-04-01 15:05 UTC, cafedomancer commented on app/helpers/search_helper.rb
> +    class_names.any? { |class_name| searchable.is_a?(class_name) }
サブクラスかどうかを考慮しなくてよい (= `is_a?` じゃなくてよい) のであれば以下のように書くとスッキリしそうです。https://api.rubyonrails.org/classes/Object.html#method-i-in-3F

```suggestion
    searchable.class.in?([Announcement, Event, Page, Product, Question, Report])
```

2022-04-01 15:12 UTC, cafedomancer commented on app/helpers/search_helper.rb
> +    class_names.any? { |class_name| searchable.is_a?(class_name) }
wip にできるかどうかが `wip?` みたいな predicate method によって決められるなら以下のような書き方もアリかもです。これだと wip にできるクラスを列挙しなくても済みそう。

```suggestion
    searchable.respond_to?(:wip?)
```

2022-04-03 12:27 UTC, clio209 approved these changes
@eatplaynap さん
issue取り組みお疲れ様です。再度取り込み、挙動を確認しました。
また、`if`文のリファクタリング、有難うございます。非常に読みやすくなりました！`all`等は深い意味はなく、何かそうしないといけない理由を考えたまでで、混乱させて申し訳ないです。。🙇‍♂️
自分の方はapproveいたします〜。

2022-04-04 12:19 UTC, eatplaynap commented on app/helpers/search_helper.rb
> +    class_names.any? { |class_name| searchable.is_a?(class_name) }
ご確認ありがとうございます！流麗！！
`searchable.respond_to?(:wip)`でやっていることがひと目でわかり、メソッドに切り出す必要がなさそうなのでjbuilderに直接書く形に変更してみました。

2022-04-04 12:34 UTC, eatplaynap commented
@clio209
レビューありがとうございました:smile: 
本田さんが質問してくださったおかげでコード全体がめちゃくちゃスッキリしました〜！

@cafedomancer 
お手すきの際にチェックお願いいたします:pray:

2022-04-07 08:20 UTC, eatplaynap commented on app/javascript/searchable.vue
> -.thread-list-item(:class='modelName')
確かにその通りでした〜！削除しました。

2022-04-07 08:20 UTC, eatplaynap commented on app/javascript/searchable.vue
> -.thread-list-item(:class='modelName')
確かにその通りでした〜！削除しました。

2022-04-07 08:21 UTC, eatplaynap commented on app/javascript/searchable.vue
> +      }
現状のほうが分かりやすいと思ったのでそのままにしました！

2022-04-07 08:21 UTC, eatplaynap commented on app/javascript/searchable.vue
> +      }
現状のほうが分かりやすいと思ったのでそのままにしました！

2022-04-07 08:34 UTC, eatplaynap commented on app/views/api/searchables/_searchable.json.jbuilder
> +end
`?`をつけてみました。

ただすみません、↓を読んで、`respond_to?`は引数で渡したメソッドをレシーバーが持っているかどうかを評価しているということは理解したのですが、`wip?`というメソッドはどこで定義されているのかがわかりませんでした…
[Object\#respond\_to? \(Ruby 3\.1 リファレンスマニュアル\)](https://docs.ruby-lang.org/ja/latest/method/Object/i/respond_to=3f.html)

2022-04-07 08:36 UTC, eatplaynap commented
@cafedomancer 
ご確認ありがとうございました！
すみません、Railsのすごく初歩的なことを理解できていない気がするのですが、`wip?`についてご教示いただけるとありがたいです:pray:

2022-04-07 08:43 UTC, cafedomancer commented on app/views/api/searchables/_searchable.json.jbuilder
> +end
適当なドキュメントが見つからなかったので Plataformatec の blog post を貼っておきます！ http://blog.plataformatec.com.br/2012/05/active-record-attribute-method/

2022-04-07 08:43 UTC, cafedomancer approved these changes
🌟

2022-04-07 08:46 UTC, cafedomancer commented on app/views/api/searchables/_searchable.json.jbuilder
> +end
あ、ふつうにここにあった。https://api.rubyonrails.org/classes/ActiveRecord/Base.html#class-ActiveRecord::Base-label-Attribute+query+methods

2022-04-07 08:57 UTC, eatplaynap commented on app/views/api/searchables/_searchable.json.jbuilder
> +end
なるほど〜！`attribute`に対して`#{attribute}?`メソッドが自動で準備されてる仕組みがあるんですね！ありがとうございます〜:pray:

2022-04-07 08:59 UTC, eatplaynap commented
@cafedomancer 丁寧なレビューありがとうございました！勉強になりました〜！
@komagata チームメンバーの確認OKをいただいたので、お手すきの際にレビューをお願いいたします:pray:

2022-04-08 05:04 UTC, komagata requested changes

2022-04-08 05:04 UTC, komagata commented on app/views/api/searchables/_searchable.json.jbuilder
> +end
APIとしてはwipがfalseの場合も知りたいと思うので、項目自体を表示しないのではなく、falseを出すのがいいと思います〜

2022-04-08 08:39 UTC, eatplaynap commented
@komagata 
ご確認ありがとうございます！修正したので再度チェックをお願いいたします〜！

2022-04-13 11:56 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-04-17 01:53 UTC, merged