[Q&A]質問の本公開時にメンター側のWatchを自動的にonにするように修正
fjordllc/bootcamp pull request #4530
Opened 2022-03-30 07:08 UTC by Paru871

## Issue
- #4525 
 
## 概要
Q&AのWIP機能の付加(#4157)により、質問が作成された際に自動的にメンターさんのみ「Watch中」になるタイミングがWIP保存時にも働いてしまうため、タイミングを「本公開時」にWatch中になるよう修正しました。

## 参考PR
Refs: #3120

## 修正の内容
- 質問作成後にメンター側へ自動的にWatchをonにしていた処理はWIP導入以前は`app/controllers/questions_controller.rb`にて実装していましたが、`app/models/question_callbacks.rb`の`after_save`内へ移動させ、質問の初回の本公開時に行うように変更しました。
- N+1への対策として`insert_all`を使うことと、ここにrubocopの指摘が入るのを無効化することは、以前の実装時の受講生とアドバイザーさん、駒形さんとのやり取り・指示をそのまま受け継ぎました。
詳細は下記のコメントをご覧ください。
https://github.com/fjordllc/bootcamp/pull/3120/files#r700293736

## 修正前
- WIPで保存時にすでに「Watch中」ボタンがonになってしまっている
![スクリーンショット 2022-03-24 8 55 41](https://user-images.githubusercontent.com/82434093/159823041-23ab9979-6a02-4b38-8126-f238093b98e5.png)

## 修正後
- WIPで保存時には「Watch中」ボタンがonにならない
![image](https://user-images.githubusercontent.com/82434093/160615462-29dffa8f-fa88-4625-b810-01ea2d1e98eb.png)

- 質問の本公開時には「Watch中」ボタンがonになる
![image](https://user-images.githubusercontent.com/82434093/160615872-439d44fe-bec1-404c-b30c-c28246fe6a10.png)

## 動作確認手順
1. 手元に本ブランチを取り込む。
1. `bin/setup` `rails db:reset`を行い初期化した後、`rails s`にて開発環境を立ち上げる
1. 下記の手順で動作確認を行う。
    1. 受講生ユーザーでログインして質問を新規作成し、「登録する」で本公開する。
    1. メンターでログインして該当の本公開済みの質問が「Watch中」になっているのを確認する。
    1. 受講生ユーザーでログインして質問を新規作成し、「WIP」をクリックしてwip保存する。
    1. メンターでログインして該当のwIP中の質問が「Watch中」ではないのを確認する。
    1. 上で質問を作成した受講生ユーザーでログインしてwip保存した質問を「内容修正」から「質問を公開」をクリックして本公開する。
    1. メンターでログインして該当の本公開済みの質問が「Watch中」になっているのを確認する。

2022-03-30 07:56 UTC, Paru871 commented
@taka110-IT 
お疲れさまです。
昨晩、#4526 のプルリクにてレビューのお願いをいたしました。
その後ブランチ名の変更作業を行なったところ、プルリクの作り直しとなってしまいました。大変失礼いたしました🙇🏻‍♀️
こちらの新しい方で改めてレビューのお願いをさせていただきます。お手すきの際によろしくお願いいたします🙏

2022-03-30 08:51 UTC, taka110-IT commented
@Paru871 さん
承知しました。順次拝見しますので少々お時間をいただきます。

2022-04-07 13:20 UTC, Paru871 commented
@taka110-IT 
お疲れさまです。お忙しそうなのといろいろご負担がかかっていらっしゃるとお見受けしましたので、レビューの依頼はキャンセルとさせていただきますー🙇🏻‍♀️
また機会がありましたらよろしくお願いいたします🙏

2022-04-07 13:21 UTC, Paru871 commented
@aim2bpg 
お疲れさまです。お忙しいなかお手数をおかけしてしまい申し訳ありませんが、
お手すきの際にレビューをいただきたく、何とぞよろしくお願いいたします🙇🏻‍♀️

2022-04-07 17:23 UTC, taka110-IT commented
@Paru871 
時間だけ無駄に経過してしまい大変申し訳ありませんでした。

2022-04-08 03:09 UTC, aim2bpg commented on test/system/questions_test.rb
>      end
`click_button`がブロック内外にありますので統一した方が良いかと思いました。
本ファイルを上から見ていくと、ブロック内で統一された方がよさそうです。

2022-04-08 03:10 UTC, aim2bpg commented on test/system/questions_test.rb
> +    visit_with_auth questions_path, 'komagata'
`visit_with_auth`の前に空行があると見やすくなるのではと思いました。

2022-04-08 03:15 UTC, aim2bpg commented on test/system/questions_test.rb
> +    assert_text 'kimura (Kimura Tadasi)'
一覧ページではなく、詳細ページであることの確認意図でユーザー名をチェックされているのかと思いました。だとすると、一覧ページにも出現しますので、違う目印が良いかもです。例えば「削除する」など。。

2022-04-08 03:16 UTC, aim2bpg requested changes
動作確認で問題ないことを確認しました。手順がわかりやすくて助かりました。
テストの書き方でいくつかコメントさせていただきました。
ご確認をお願いいたします〜🙏

2022-04-08 03:22 UTC, aim2bpg commented
@Paru871 さん、久しぶりでメンション忘れてましたので、本コメントでメンション飛ばさせていただきます🙏

2022-04-08 06:16 UTC, Paru871 commented on test/system/questions_test.rb
>      end
ありがとうございます！
今回作成したテスト3つについて、ブロック内に`click_button`を書くように統一いたしました。

2022-04-08 06:17 UTC, Paru871 commented on test/system/questions_test.rb
> +    visit_with_auth questions_path, 'komagata'
「質問を作成しました。」のチェックが抜けていましたので追加しました。
見つけてくださってありがとうございます！助かりましたー🙏
統一感が大事、しっかり覚えたいと思います。

2022-04-08 06:19 UTC, Paru871 commented on test/system/questions_test.rb
> +    visit_with_auth questions_path, 'komagata'
`visit_with_auth`の前に空行を作るのも、今回作成した3つのテストについて統一して修正しました。
ありがとうございます！

2022-04-08 06:20 UTC, Paru871 commented on test/system/questions_test.rb
> +    assert_text 'kimura (Kimura Tadasi)'
確かに書いてくださったとおりだと思いました！ありがとうございました。
ご提案いただいた「削除する」が良いと思いましたので採用させていただき、今回作成した3つのテストについて詳細ページであることを確認する項目として修正を行いました。

2022-04-08 06:39 UTC, Paru871 commented
@aim2bpg 
このたびはお忙しいなか、早速にチェックしてくださりありがとうございました。
書いてくださったことはどれもそのとおりだと思いましたので、今回作成したテスト3つについて修正を行いました。
お手数をおかけしますがお手すきの際に再度チェックいただきたく、よろしくお願いいたします🙏

2022-04-08 08:56 UTC, aim2bpg approved these changes
@Paru871 さん、修正ありがとうございます。
私はOKです🙆‍♀️

2022-04-08 10:24 UTC, Paru871 commented
@aim2bpg 
このたびはお忙しいなか、あたたかくご対応&的確なチェックをしてくださり本当にありがとうございました。
大変助かりました🙇🏻‍♀️

2022-04-08 10:27 UTC, Paru871 commented
@komagata 
チームメンバーさんのレビューと修正が終わりましたので、
お手すきの際にご確認をよろしくお願いいたします。

2022-04-13 11:57 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-04-13 11:57 UTC, merged