会社個別 > 提出物一覧を vue.js 化した
fjordllc/bootcamp pull request #4549
Opened 2022-04-02 13:23 UTC by clio209

- issue #4311 
## 概要
会社個別ページ>提出物一覧をvue.js化しました。以下のPRを参考にしています。
- [app/views/users/_user.html.slimの削除 by naomichi-h · Pull Request #3917 ](https://github.com/fjordllc/bootcamp/pull/3917)
- [ユーザー個別ページ > 質問一覧 の vue.js化 #4343](https://github.com/fjordllc/bootcamp/pull/4343)

### 変更前

### 変更後
<img width="1426" alt="_development__DAIMYO_Engineer_College所属ユーザーの提出物___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）_と_メモ" src="https://user-images.githubusercontent.com/64455939/161384811-0f84eecb-b1a7-470f-ab36-15fd85341f7a.png">

## 確認方法
1. ブランチ`feature/convert-companies-products-to-vuejsl` をローカルに取り込み、会社個別 > 提出物一覧画面でvue.js化されていることを確認する

2022-04-06 12:28 UTC, clio209 commented
@garammasala29 さん
- [ユーザー個別ページ > 質問一覧 の vue.js化 #4343](https://github.com/fjordllc/bootcamp/pull/4343)
を参考にさせていただき、非常に勉強になりました。是非レビューをお願いできればと思います。お忙しいところ恐縮ですが、何卒よろしくお願いいたします🙇‍♂️

2022-04-09 10:43 UTC, garammasala29 requested changes
@clio209 さん
お疲れ様です。レビュー依頼ありがとうございました！遅くなってしまい申し訳ありません💦
提出物に関してあまり触れてこなかったので、とても勉強になりました！
コメントしましたので、ご確認いただけたらと思います🙏

2022-04-09 10:43 UTC, garammasala29 commented on app/javascript/company-products.vue
> +import Product from 'product.vue'
Productをインポートすることで提出者orメンターが出てしまうので、何かしら対応が必要になってくるのかな〜と思いました💦
<img width="648" alt="スクリーンショット" src="https://user-images.githubusercontent.com/69446373/162568128-8ffb091d-5477-47e9-99e3-add112277d6f.png">

2022-04-11 08:09 UTC, clio209 commented on app/javascript/company-products.vue
> +        (this.params.watch ? `&watch=${this.params.watch}` : '') +
コメントありがとうございます。削除いたしました。

2022-04-12 13:37 UTC, clio209 commented on app/javascript/company-products.vue
> +    },
有難うございます！！不必要な箇所を作事いたしました🙇‍♂️

2022-04-12 13:48 UTC, clio209 commented on app/javascript/company-products.vue
> +import Product from 'product.vue'
コメント有難うございます！komagataさんに確認いたします。
@komagata さん
こちら、この表記（提出者、メンター）が表示されても問題ないでしょうか？元来誰がコメントしているのかまでアイコンで見えることから、この表記が出ても論理的に問題ないのかなとは思います。またはこの表記を消した方が良いでしょうか？

2022-04-13 12:28 UTC, komagata commented on app/javascript/company-products.vue
> +import Product from 'product.vue'
@clio209 こちらそのままで問題ございません〜

2022-04-14 04:59 UTC, clio209 commented on app/javascript/company-products.vue
> +import Product from 'product.vue'
@garammasala29 さん
レビュー有難うございます！修正しましたので、お時間ある時にご確認いただけますと幸いです。

2022-04-14 07:00 UTC, garammasala29 approved these changes
@clio209 さん
お疲れ様です。ご修正ありがとうございました😄
少しコメントしていますが、LGTMとさせていただきます👍

2022-04-14 08:33 UTC, clio209 commented on app/views/products/index.html.slim
> +  #js-products(data-title="#{title}" data-selected-tab="all" data-mentor-login="#{mentor_login?}" data-current-user-id="#{current_user.id}")
すいません、毎回コンフリクトが起こり、色々弄って先祖返りしたりしたためかと思われます。。恥💦💦

2022-04-14 08:40 UTC, clio209 commented on app/javascript/company-products.vue
> +          `?target=${this.params.target}` +
ご確認本当にありがとうございます！！

2022-04-14 09:09 UTC, clio209 commented
@komagata 
お手隙の際にご確認頂けますと幸いです🙇‍♂️

2022-04-17 06:21 UTC, komagata reviewed
conflictの修正をお願いします〜

2022-04-18 08:47 UTC, clio209 commented
@komagata
conflictの修正を行いました。お手隙の際にご確認いただけますと幸いです。

2022-04-20 04:45 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-04-20 04:45 UTC, merged