管理者・メンターはブログを修正・削除できるようにした
fjordllc/bootcamp pull request #4608
Opened 2022-04-12 14:56 UTC by niikz

## Issue
- #4514

## 概要
管理者・メンターはブログを修正・削除できるようにしました。

管理者のみブログ記事の個別ページに修正・削除ボタンが表示されていましたが、メンターにも表示されるようにしました。

## 変更確認方法
1. ブランチ`feature/allow-administrators-and-mentors-to-modify-and-delete-blogs`をローカルに取り込む
2. `rails server`でローカル環境を立ち上げる
3. メンターでログインし、ブログ記事の個別ページ( `/articles/:id` )にアクセスする
4. 修正・削除ボタンが表示されていることを確認

## 変更前
<img width="1000" alt="2022-04-13-02" src="https://user-images.githubusercontent.com/60736158/162995171-9b9e2d09-c133-4908-b7fc-88b1f9001faf.png">

## 変更後
<img width="1000" alt="2022-04-13-01" src="https://user-images.githubusercontent.com/60736158/162995209-ddde09a1-991f-489b-860a-0bf1411e8a39.png">

2022-04-13 12:24 UTC, siroemk requested changes
@niikz 
お疲れ様です。1点テストについてコメントいたしました〜！
ご確認をお願いします！
動作は問題なく完璧でした🙌😄

2022-04-13 12:24 UTC, siroemk commented on test/system/articles_test.rb
> +  test "can't see edit and delete buttons" do
メンター・管理者以外のロールのテストもあって、良いな〜と思いました👏
1点、テストの名前だけ、主語を入れてあげたらもっと良くなると思いました！
（ここのテストは "誰が" という主語が肝だと思うので😄）

2022-04-15 05:40 UTC, niikz commented
@siroemk 
早速のご確認ありがとうございます〜！
修正しましたのでお手すきの際にご確認お願いします🙏

2022-04-15 05:40 UTC, niikz commented on test/system/articles_test.rb
> +  test "can't see edit and delete buttons" do
仰る通りですね…🙏
一般ユーザー（general user）を主語に追加しました！

2022-04-16 14:00 UTC, siroemk approved these changes
@niikz 
LGTMです🙆‍♀️
お疲れ様でした〜！

2022-04-17 15:38 UTC, niikz commented
@siroemk 
ご確認ありがとうございました〜！

2022-04-17 15:38 UTC, niikz commented
@komagata 
お疲れさまです。ご都合のよいときに、こちらのレビューをよろしくお願いします！

2022-04-20 03:55 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-04-20 03:56 UTC, merged