traineeはcompany_idの選択を必須にする
fjordllc/bootcamp pull request #4612
Opened 2022-04-13 08:23 UTC by clio209

issue #4573  

## 概要
ユーザー編集画面で研修生にチェックが入っているのに、企業名が未設定の状態で`更新する`をクリックした場合、下記エラーが出て更新できないように変更しました。
![_development__ユーザー登録情報変更___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64455939/163132650-7e57e4a0-b1a5-42c4-a198-a544106e8e4e.png)

## ローカル環境での確認方法
1. ブランチ `feature/company-of-trainee-requirement` をローカルに取り込みます。
1. adminユーザーでログインし、ユーザーの登録情報変更画面に行きます。
1. 「研修生」にチェックを入れて、企業名を未設定とし、更新し、エラーメッセージが出ることを確認します。

2022-04-14 08:29 UTC, clio209 commented
@komagata 
当issueで研修生は所属企業を必須とするようvalidationを修正したのですが、こうすると
`test/system/sign_up_test.rb:137` の研修生の`signup`テストで、所属企業が入力できないために、テストが落ちてしまいます。
そもそも研修生がsignupを行うことはあるのか、また研修生は通常のフォームからsignupした後、adminが所属企業を振る手順なのか、このsignupが必要なのかわからず、、お教えいただけますと幸いです🙇‍♂️

2022-04-17 06:07 UTC, komagata commented
@clio209 

> そもそも研修生がsignupを行うことはあるのか、

YESです。

> http://localhost:3000/users/new?role=trainee

のように role=trainee をつけてサインアップページにアクセスすると研修生の登録ページになるようになっています。こちらを使ってお願いします〜。

2022-04-19 05:42 UTC, clio209 commented on test/system/sign_up_test.rb
> +      select 'テスト企業', from: 'user[company_id]', visible: :all
@komagata 
traineeのユーザー登録画面に、「企業情報」を追加させ、選択できるようにしたのですが、上記コードだけでは、
```
Minitest::UnexpectedError: Capybara::ElementNotFound: Unable to find option "テスト企業" within #<Capybara::Node::Element tag="select" path="/HTML/BODY[1]/DIV[1]/MAIN[1]/DIV[1]/DIV[1]/DIV[1]/FORM[1]/DIV[1]/DIV[20]/DIV[1]/DIV[1]/DIV[1]/SELECT[1]">
```
のエラーが出てしまいます💦💦
この「企業情報」入力フォームの特性上、一度クリックしないと選択肢が出てこないためかと思い、
`select`の前に`click`のイベントをテストに追加すればいいのではとまでは進んだのですが、
テストでうまく`click`させるコードが書けずに詰まっております。お手隙の際にアドバイスいただけますと幸いです🙇‍♂️

2022-04-20 05:04 UTC, komagata commented on test/system/sign_up_test.rb
> +      select 'テスト企業', from: 'user[company_id]', visible: :all
@clio209 テストのデバッグのやり方は大丈夫でしょうか。

READMEにあるように`HEADED=1`を先頭につけてテストをすると実際のブラウザーで実行できます。
そしてテストの中に`binding.pry`を書くなどして、自由な場所で止めて、好きなメソッドを実行したり、値を調べたりできます。
そちらを使ってみるといろいろとわかることがあると思いますので試してみてください〜

2022-04-20 05:06 UTC, clio209 commented on test/system/sign_up_test.rb
> +      select 'テスト企業', from: 'user[company_id]', visible: :all
@komagata  `choices.js`がらみだということがわかったので、少し自力で考えてみます！

2022-04-22 12:33 UTC, clio209 commented on test/system/sign_up_test.rb
> +      select 'テスト企業', from: 'user[company_id]', visible: :all
@komagata 
上記テストは`choices.js`が原因で修正することができました。
一点、下記テスト
```
test 'create a report without company as trainee' do
    user = users(:kensyu)
    user.update!(company: nil)
    
    visit_with_auth '/reports/new', 'kensyu'
    within('form[name=report]') do
      fill_in('report[title]', with: 'test title')
      fill_in('report[description]', with: 'test')
      fill_in('report[reported_on]', with: Time.current)
    end

    first('.learning-time').all('.learning-time__started-at select')[0].select('07')
    first('.learning-time').all('.learning-time__started-at select')[1].select('30')
    first('.learning-time').all('.learning-time__finished-at select')[0].select('08')
    first('.learning-time').all('.learning-time__finished-at select')[1].select('30')

    click_button '提出'
    assert_text '日報を保存しました。'
  end
```
所属企業がない研修生が日報を出せるようにするものですが、今回の変更で所属企業がない研修生自体がエラーになってしまいます。この場合、このテストは削除しても大丈夫でしょうか？

2022-04-23 16:42 UTC, komagata commented on test/system/sign_up_test.rb
> +      select 'テスト企業', from: 'user[company_id]', visible: :all
@clio209 はい、大丈夫です。

2022-04-24 11:34 UTC, clio209 commented
@sinsoku さん
お忙しい中恐縮ですが、お時間ある時にレビューいただけますと幸いです。
ご不明点等何でも聞いていただければと思います。よろしくお願い致します。

2022-04-24 11:47 UTC, clio209 commented
@siroemk さん
お忙しい中恐縮ですが、お時間ある時にレビューいただけますと幸いです。
ご不明点等何でも聞いていただければと思います。よろしくお願い致します。

2022-04-27 03:04 UTC, siroemk requested changes
@clio209 
お待たせしました〜！
`choices.js`の件など、勉強になりました😄
ありがとうございます。
エラーメッセージなど、動きは問題なさそうです！

画面の表示で2点気になったところがありました。
今回、研修生の企業選択を必須にしたので、フォーム上には必須項目であることがわかるように`*`を表示させた方がわかりやすいかなと思いました。

classに`is-required`を付与してあげると良さそうです。

あと、所属企業の項目の下に、以下のような文面が出ていると思います。

> 企業で利用しているアドバイザー、研修生は登録。
就職した卒業生、メンターは個人情報にあたるため、希望者のみ登録。

こちらは管理者の画面で表示させていた文言の名残りだと思うのですが、この画面から登録しているのは研修生なので、他のロールに関する説明はないほうがユーザーも迷わず、親切かな〜と思いました。

`users/form/company`は管理者の画面でも使っているので、条件で分けて研修生の画面にはこの文言が出なくしたり、文言を変えたりすると良さそうです。

ご検討をお願いします〜😊　

2022-04-27 03:04 UTC, siroemk commented on test/models/user_test.rb
> +  test 'trainee must select company ' do
テスト名の最後に不要な(?)半角空白が入っているようです。

2022-04-27 03:04 UTC, siroemk commented on test/models/user_test.rb
> +  test 'trainee must select company ' do
テスト名の最後に不要な(?)半角空白が入っているようです。

2022-04-27 07:44 UTC, clio209 commented
@siroemk さん
お忙しい所、詳細なレビューいただきまして、本当にありがとうございます！！
スペースの修正を行いました。

また、変更のアドバイスもありがとうございます！！
アドバイスいただいた、`is-required`とコメント掲載の点ですが、作成時、また今回も悩んだのですが、
adminがログインする際に、`is-required`もユーザーのroleに応じて表示を分けることになり、これを煩雑にするのとユーザー目線で、当説明文があれば必要、不必要の認識がずれることはないのではという観点のトレードオフから、
変更しないほうがいいのではと思っている次第ですが、、いかがでしょうか？

ご不明点等ございましたら、なんでも聞いていただければと思います。何卒よろしくお願いいたします🙇‍♂️

2022-04-27 08:44 UTC, siroemk commented
@clio209 
> adminがログインする際に、is-requiredもユーザーのroleに応じて表示を分けることになり

なるほど〜！確かにそうですね〜😭
見落としておりました。

これは管理者と研修生の分岐で、同じ`users/form/company`を呼んでいることで扱いにくくなっている気がします🤔
例えば、`users/form/company`ではなく`users/form/trainee_company`のようなものを作り、そちらに`is-required`や文言の件を追加し、研修生の時には`users/form/trainee_company`呼んであげるように書くとどうでしょう？
（逆に保守性が落ちる？みたいなこともあるかもしれないので、@clio209 さんのご意見があればどんどん教えてください🤣）

2022-04-28 07:43 UTC, clio209 commented
@siroemk さん　コメント有難うございます！！非常に理解できました！
本件、細かくシートを分岐していくのは、「それに依って得られる利得」と、「シートがrole毎に増える煩雑さ」とトレードオフかと思います。自分個人の志向としては、今回のケースは煩雑さを避ける方を好みますが、如何せん自分にwebシステム設計の経験がないので、どちらが適切なのか判断できません。komagataさんの判断を仰ぎ、実装したいと思います。

@komagata さん
本件、role毎にsheetを分岐させ、文言等の表示を調整した方がよろしいでしょうか、それともこのままでいいでしょうか？コメントいただけますと幸いです。

2022-04-29 16:14 UTC, komagata commented
@clio209 **シート**とはviewのファイルのことですかね？

どのぐらいの複雑さになるかによると思いますが、大きく変わらないと思いますので実装社の @clio209 さんにお任せします〜（どちらが絶対にいいということはない感じかなと思いますので）

2022-05-02 00:24 UTC, clio209 commented
@komagata さん　コメントありがとうございます！
@siroemk さん　そうしましたら今回はこのまま変更しない方向でいければと思うのですが、それでよろしいでしょうか？

2022-05-02 01:45 UTC, clio209 commented
@siroemk さん　
ありがとうございます！お忙しい中、一連のレビュー、本当に感謝いたします！
@komagata さん
お手隙の際にレビューいただけますと幸いです。

2022-05-02 18:16 UTC, komagata commented
@clio209 

> @clio209 シートとはviewのファイルのことですかね？

こちらの回答はいかがでしょう？

2022-05-02 23:50 UTC, clio209 commented
@komagata さん
すいません！はい、その通りです。

2022-05-08 04:35 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-05-08 04:35 UTC, merged