企業編集ページに削除リンクを設置
fjordllc/bootcamp pull request #4656
Opened 2022-04-20 17:55 UTC by Nabegon

新しいブランチを作成したので、PRも作り直しました。

2022-04-22 03:02 UTC, Aseiide reviewed
確認しました。
動作、コードともに問題はありませんでした。
いくつかやってほしいことと気になる点があったので共有しますね。

## やってほしいこと
### PRのDescriptionを書いてほしい

おそらく書き忘れだと思うのですが、#4567 から今の #4656 に移したときに前者にはDescriptionはあるが、今のPRにはないという状態になっていて、内容を把握するのに時間がかかってしまいました。

### 変更前後はテーブルじゃないほうが見やすい

Descriptionに変更前後のスクリーンショットがあるのはとてもありがたいのですが、テーブル記法を用いてるのが気になりました。
個人的な意見にはなるのですが、テーブル記法を用いるとスクショの画像は小さくなってしまい、わざわざ画像をクリックして、大きくしないと確認しづらいんですよね。
ですので、

```
## 変更前
スクリーンショット

## 変更後
スクリーンショット
```

という形で書くと、画像自体が多く表示されるので良いかと思います。
変更した画面が多い時は、テーブル記法を使って一覧し、変更を見やすくすると良いと思います。


## 気になった点
### なぜ削除リンクなのか??

実装の背景、ということにはなるのですが、通常、「削除」をクリックするとその企業が削除されると感じているのですが、今回はリンクになっていますよね。
なぜ削除機能ではなく、リンクなのかが気になりました。
issueを見てもちょっと分からず、動作としては問題なかったのですが、気になりました。
今回はリンクを設置して、削除機能の実装は別でやるということなのか、一覧ページに削除ボタン(削除機能)があるから、ということなのか伺えるとありがたいです。

@Nabegon 
以上となります。よろしくお願いいたします！
修正はないのですが、まだapproveはしていないので、書き直したりしたら再度レビュー依頼をいただけると嬉しいです。

2022-04-22 16:17 UTC, Nabegon commented
@Aseiide 

お疲れ様です。PRのDescriptioの修正点をご教示いただきありがとうございます🙏こちらはご指摘通り修正しました。
PRの作り直しで、内容に変更はなかったのでDescriptioを書いていませんでしたが、その件でご迷惑をおかけしすみませんでした💦今後は気を付けます！

> 実装の背景、ということにはなるのですが、通常、「削除」をクリックするとその企業が削除されると感じているのですが、今回はリンクになっていますよね。
なぜ削除機能ではなく、リンクなのかが気になりました。

こちら、まちださんに確認します！

2022-04-22 16:21 UTC, Nabegon commented
@machida 

お疲れ様です！

今回の実装で1点質問があります。

issueには
> 削除リンクを設置。
これは、管理者でログインした場合だけ表示されるようにする。

とあり、企業編集ページに削除ボタンを設置しました。削除ボタンを設置とのことでしたので、削除ボタンを押しても現状は削除は出来ないのですが、削除を出来るようにした方が良いでしょうか。

お忙しいところ恐れ入りますが、ご教示いただきたいです🙏
よろしくお願いします🙇

2022-04-27 13:58 UTC, Nabegon commented
@machida さんにDiscordで確認したところ、以下の通りでした。

> クリックされると削除されるリンクの設置という意味でしたー
なので、クリックされると削除されるところまで実装をお願いします

そのため、削除ボタンを押したら企業ページが削除されるように実装します。

2022-04-27 14:00 UTC, Nabegon commented
@Aseiide 

お疲れ様です！issueの内容についてご指摘いただきありがとうございました🙏

削除ボタンを押したら企業ページを削除するところまで実装するとのことでしたので、そのように対応します。
現在、削除ボタンを押すとRouting Errorになっていて、詰まっています。少々時間がかかるかもしれません。

引き続きよろしくお願いいたします🙇

2022-04-27 14:07 UTC, Aseiide commented
@Nabegon 
了解です。実装頑張ってください。自分にはいつでも依頼してもらって大丈夫です！

2022-04-30 10:48 UTC, Nabegon commented
CI上でテストが落ちています。
- #4735 のマージ待ちです。

2022-05-07 22:23 UTC, Nabegon commented
@Aseiide 

お疲れ様です！実装に時間がかかってしまい、レビューの再依頼が遅くなりました。すみません💦

削除ボタンのリンクではなく、削除ボタンの実装でしたので、削除機能を伴った削除ボタンを実装しました。企業ページが削除されるか、ご確認いただきたいです。また、テストも書いたので、こちらも併せてご確認いただきたいです🙇よろしくお願いします🙏

2022-05-08 06:10 UTC, Aseiide reviewed
![スクリーンショット 2022-05-08 15 07 06](https://user-images.githubusercontent.com/45246171/167284211-720f30e4-8ff1-4b47-a99b-14715a0f2f9c.png)

@Nabegon 
自分の手元だとボタンのデザインが崩れているのですが、これは町田さんにデザインをお願いする感じですかね??

2022-05-08 06:10 UTC, Aseiide commented on app/controllers/admin/companies_controller.rb
> +      head :bad_request
削除に成功したらメッセージを表示し、失敗したら400を返すようにしているのですね。良いと思います！

2022-05-08 08:11 UTC, Nabegon commented
@Aseiide 

さっそくご確認いただきありがとうございます！

このissueに対応している途中から、ボタンのデザインが崩れるようになりました💦
mainの最新の状態をリベースしているので、デザイン変更があってそこからボタンのデザインが崩れてると思います。
ご指摘ありがとうございます！

まちださんに確認します🙇

2022-05-08 08:53 UTC, Aseiide approved these changes
@Nabegon 
承知しました。デザインが必要であれば町田さんへデザインをお願いしてください〜。
LGTMです！

2022-05-08 23:19 UTC, Nabegon commented
@machida 

お疲れ様です！キャンセルボタン、削除ボタン共にデザインが崩れています。そのため、デザイン依頼をしたくメンションいたしました。

特に注意点などはありません。よろしくお願いします🙇

2022-05-09 03:14 UTC, machida commented
@Nabegon 

デザイン入れましたー
キャンセルは最新ではめったに使わないので目立たない見た目になってて、さらに削除は管理者しか使わない & ご操作を防ぐためにさらに目立たなくなってますー

<img width="792" alt="image" src="https://user-images.githubusercontent.com/168265/167334423-7682ba1f-4c22-4c84-9d87-c762354974f9.png">

2022-05-09 04:08 UTC, machida commented
@Nabegon testが落ちてるのは別のところに原因があって、そっちの修正のPRを投げてます。そっちがマージされたら、最新のmainからrebaseをお願いしますー

2022-05-09 12:28 UTC, machida commented
@Nabegon 最新のmainにテストが落ちる問題を解決する修正を入れましたー

2022-05-09 15:22 UTC, Nabegon commented
@komagata 

お疲れ様です！チームレビュー通りましたので、レビューをお願いしたいです🙏
よろしくお願いします🙇

2022-05-10 02:10 UTC, komagata requested changes
同じコミットメッセージが複数あるので、一つのPRとしてのコミットメッセージをsquashしたり、修正したりして整理してみてください〜

一般的なPRの流れとしては、最初は細かくコミット積んで行って大丈夫ですが、PRを提出するときにコミットをわかりやすい粒度に整理する感じです〜

2022-05-10 08:58 UTC, Nabegon commented
@komagata 

承知しました。対応します！

2022-05-18 12:54 UTC, komagata approved these changes
コミットの粒度、メッセージいい感じだと思います〜！

2022-05-18 12:55 UTC, komagata commented
@Nabegon (CC: @machida) コンフリクトの修正お願いします〜

2022-05-19 11:31 UTC, Nabegon commented
@komagata 

お疲れ様です！コンフリクトを解消しました。お手数をおかけしますが、再度ご確認のほどよろしくお願いします🙏

2022-05-20 06:05 UTC, komagata commented on app/views/practices/_form.html.slim
> +            | 画像サイズ: 1200px × 630xp
```suggestion
          p 画像サイズ: 1200px × 630xp
```

行が長くない限りはこれでもいいかもです〜

2022-05-20 06:05 UTC, komagata commented on app/views/reports/_form.html.slim
> +            | 後で探しやすくなるタイトルがオススメ
```suggestion
          p 後で探しやすくなるタイトルがオススメ
```

行が長くない限りはこれでもいいかもです〜

2022-05-20 07:12 UTC, Nabegon commented
@komagata 

お疲れ様です！ご指摘いただいたviewファイル2つ修正しました。ご確認のほどよろしくお願いします🙏

2022-05-22 05:35 UTC, komagata commented on app/views/admin/companies/_form.html.slim
> +      - unless company.id.nil?
```suggestion
      - if company.id.present?
```

とかの方が否定系じゃないのでわかりやすいかもです〜

2022-05-24 07:03 UTC, Nabegon commented
@komagata 

お疲れ様です！何度もご確認のご依頼すみません💦ご指摘いただいた箇所、修正しました。再度ご確認のほどよろしくお願いします🙏

2022-05-24 15:04 UTC, merged

2022-05-30 13:46 UTC, Nabegon commented
@komagata @machida 

お疲れ様です！依頼するのが遅くなってしまいすみません💦

こちらのIssueが管理者のみ確認可能のため、管理者として本番環境でご確認いただきたいです。
よろしくお願いします！