[管理者機能]相談部屋で受講者の就職活動中フラグをオン・オフする
fjordllc/bootcamp pull request #4833
Opened 2022-05-16 01:20 UTC by rosh-1228

## issue
- #4707 

## 変更前
![_development__jobseekerさんの相談部屋___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64620506/168504203-29694df9-c224-44b1-99ea-f86c7e3785de.png)

## 変更後
![_development__jobseekerさんの相談部屋___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64620506/168504094-28bf5c7e-5166-4ede-a0a9-2831d7c38e1b.png)

## 確認手順
1. ブランチfeature/jobseeking-button-in-talk-roomをローカルに取り込む
2. 管理者（komagata）でログインする。
3. 任意の受講者の相談部屋で就職活動中のチェックボックスにチェックをして、「更新する」ボタンをクリックする。
4. 就職活動中のチェックボックスにチェックが入っていることを確認する。
5. 3.で選択した受講者の`ユーザー登録情報変更`ページに移動
6. 就職活動中のチェックボックスにチェックが入っていることを確認する。

2022-05-16 01:56 UTC, rosh-1228 commented
system test実行時にチェックボックスにチェックが入らず困っています。
足りないものがありましたらお知らせください🙇‍♂️

### issue
- #4707

### やりたいこと
- システムテストでやりたいこと
`rails test test/system/talks_test.rb`を実行時に、就職活動中のチェックボックスをチェックして更新後に、受講者の就職活動中のフラグをオンオフできることをテストしたい。
- 上記実行のためにやりたいけどできなくて困っていること
就職活動中のチェックボックスをチェックできない。

### 試したこと
以下をそれぞれ実行しましたが、チェックボックスにチェックが入りませんでした。
`save_and_open_page`を使って、直前直後を確認しましたが、チェックが入っていないことを確認しました。

1. `check 'user_job_seeking', allow_label_click: true, visible: false`
2. 下記参考ページ 1 を参考に作成
```
element_input = find(:xpath, "//*[@id='user_job_seeking']", :visible => false)

if not element_input.selected? then
      element_label = element_input.find(:xpath, 'following-sibling::label')
      element_label.set(true)
end
```
3. 下記参考ページ 2 を参考に作成
`page.all('label[for="user_job_seeking"]', visible: false)[1].click`

### 参考ページ
1. [SeleniumでCheckBOXがクリックできない](https://selenium-world.net/trouble-shooting/3069/)
2. [[RSpec] CapybaraでCSSの●番目の要素を指定したい！（同じ要素が複数あるとき）](https://qiita.com/eitches/items/af11003941c26db30f9b#%EF%BC%92%E5%80%8B%E7%9B%AE%E4%BB%A5%E9%99%8D%E3%81%AF%E9%85%8D%E5%88%97%E3%81%8B%E3%82%89%E5%8F%96%E3%82%8A%E5%87%BA%E3%81%99)

### 失敗時のスクリーンショット
rails sでシステム起動時は就職活動中のチェックボックスにチェックが入っている入っていない関わらず更新するボタンをクリックしても、エラーにならないことを確認したのですが、system test時は以下のようにエラーになってます。
![failures_test_change_job_seeking_flag_when_click_update_button_after_checked_job_seeking](https://user-images.githubusercontent.com/64620506/168506658-fc674f53-22dc-4f56-9fb4-de97eceb160d.png)


### html
以下は就職活動中のチェックボックス・更新ボタンのhtmlです。
```html
<form class="form" name="jobseeking" action="/talks/161440963" accept-charset="UTF-8" method="post">
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="authenticity_token" value="zn2CgrD-4is1gDTiMmSE8C-IYZ_BoEfsX7qisJmewTuOv23BTh2C_SJa32ctfQ7bFY_qjK1PjMUpPUbpVmJdXA">
      <div class="form-item">
          <label class="a-form-label" for="user_job_seeking">就職活動中</label>
          <ul class="form-item__checkboxes">
                <li class="form-checkbox">
                    <input name="user[job_seeking]" type="hidden" value="0" />
                    <input class="a-toggle-checkbox" type="checkbox" value="1" checked="checked" name="user[job_seeking]" id="user_job_seeking" />
                    <label class="form-checkbox__label" for="user_job_seeking">就職活動中</label>
                </li>
          </ul>
      </div>
      <input type="submit" name="commit" value="更新する" id="user_submit" class="a-button is-lg is-primary is-block" data-disable-with="更新する" />
</form>
```

2022-05-22 13:26 UTC, rosh-1228 commented
チェックボックスにチェックができない問題についてまとめ
- チェックボックスにチェックを行うことはできていた
- チェックボックスにてチェックを行い、submit後に`app/controllers/talks_controller.rb`のupdateメソッドにて`@user.update(user_params)`が失敗していた
- `@user.update(user_params)`の直前で`binding.pry`で止めて、@user.errors.full_messagesを確認するとos:のデータがないといったメッセージがあった
- そのため、`os:`をjobseekerに追加するとテストが通るようになった

2022-05-22 14:10 UTC, rosh-1228 commented
@siso25 
お疲れ様です！
お手隙の際にご確認いただけますと幸いです🙏
よろしくお願いします！

2022-05-25 11:52 UTC, siso25 reviewed
@rosh-1228 さん
確認しました。遅くなってしまい申し訳ありません！
動きに関しては、「チェックを付ける・外す」ともに`ユーザー登録情報変更`にも反映されていましたので、問題ないと思います。
コードに関しては一点コメントを記載しました。正直自信がないので、メンターの方々にも確認いただけますと幸いです。

2022-05-25 11:52 UTC, siso25 commented on app/controllers/talks_controller.rb
> +    if @user.update(user_params)
`talks_controller.rb`内で`user`の更新処理が走るのが少し気になりました。
`user`がどこで更新されているのか把握しづらくなってしまう気がします。

2022-05-27 06:32 UTC, rosh-1228 commented
@siso25 
ご指摘ありがとうございます！
確かに、ユーザー情報をtalks_controllerで更新するより、admin/users_controllerで更新する方がわかりやすいですね😄
修正しましたので、お手数おかけしますが再度ご確認お願いします🙇‍♂️

2022-06-01 08:52 UTC, machida commented
@rosh-1228 
デザインは他のブランチで使ったものが必要なので、別プルリクで進めています。
https://github.com/fjordllc/bootcamp/pull/4929
このブランチのレビューが終わったら、僕の方でいい感じにマージしますので、引き続きレビューを進めてくださいー

2022-06-01 14:24 UTC, siso25 reviewed
@rosh-1228 さん
遅くなりまして申し訳ありません。
コードおよび動作について確認しました。
問題ありませんでしたので、よろしくお願いします。

2022-06-02 00:40 UTC, rosh-1228 commented
@siso25 
ご確認ありがとうございます！😄

@machida 
レビューが終わりましたので、デザインをよろしくお願いします！🙏

2022-06-06 08:13 UTC, machida commented
@rosh-1228 デザインを入れたブランチをこちらのブランチに統合させました。

2022-06-06 08:13 UTC, machida commented
@komagata デザインを入れたのでレビューお願いしますー🙏

2022-06-09 19:47 UTC, komagata requested changes

2022-06-09 19:47 UTC, komagata commented on app/controllers/admin/users_controller.rb
> +      job_seek_update
`set_user`という名前のメソッドでupdateをするという動作は予期しづらいので避けたいですね。

ユーザーのデータをupdateするURL（処理）を利用するか、job_seekをupdateする専用のURL（処理）を用意するかどっちかがいいと思います。

2022-06-10 05:08 UTC, rosh-1228 commented on app/controllers/admin/users_controller.rb
> +      job_seek_update
ご指摘ありがとうございます！
こちらupdateするURL（処理）を利用し、job_seeking(就職活動中)のデータを更新するように修正しました！

2022-06-10 05:08 UTC, rosh-1228 commented
@komagata 
ご指摘いただいたコードを修正しましたので、再度お手数ですがご確認よろしくお願いします！🙏

2022-06-12 22:46 UTC, komagata requested changes

2022-06-12 22:46 UTC, komagata commented on app/controllers/admin/users_controller.rb
> +    only_job_seek_update && return if user_params.keys.one? && user_params.key?('job_seeking')
`何か && return`

というのはとても分かりにくいので他の書き方にしたいですね。
ガード説になっている時点で少し複雑なのでそこに複雑なreturnを組み合わせたくないように思いました。

before_actionなどを使ったらシンプルにならないでしょうか？

2022-06-13 07:55 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
ご指摘ありがとうございます！
before_actionでifオプションを使うことで`○○ && return`を使わないように修正しました！

2022-06-15 14:28 UTC, komagata commented on app/controllers/admin/users_controller.rb
> +  before_action :only_job_seek_update, only: %i[update], if: :only_job_seeking?
URLとしてjob_seekをupdateするためのものが必要かと思います。

現在の`PUT /admin/users`というリクエストからは予想できないような動きになっちゃってるように思います。

下記のような感じでそれ専用のURLを用意するか、

https://postd.cc/how-dhh-organizes-his-rails-controllers/

もしくは、APIを作ってJSで更新するのがいいかもです〜

2022-06-16 05:55 UTC, rosh-1228 commented on app/controllers/admin/users_controller.rb
> +  before_action :only_job_seek_update, only: %i[update], if: :only_job_seeking?
ご指摘ありがとうございます！

ご紹介いただいた記事は、以前プラクティスで拝見した覚えがあります。。。
しっかり読み直して頭に刻みつけときます！😁

コントローラーを分けたることで、シンプルな記述もできました！
ご確認よろしくお願いします🙏

2022-06-20 19:03 UTC, rosh-1228 commented
@komagata 

お疲れ様です！
こちら別コントローラーを作成して修正を行いましたので、再度お手数ですがご確認よろしくお願いします🙏

2022-06-21 22:04 UTC, merged

2022-06-23 06:35 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
私の相談部屋にて、本番環境のご確認よろしくお願いします！🙏
https://bootcamp.fjord.jp/talks/274#latest-comment

2022-06-24 04:42 UTC, komagata commented
@rosh-1228 本番環境で動作することを確認しました。

2022-06-28 06:46 UTC, rosh-1228 commented
@komagata 
ご確認ありがとうございます！