確認済みの日報をチェックした場合エラーメッセージを表示する
fjordllc/bootcamp pull request #4865
Opened 2022-05-20 12:09 UTC by niikz

2022-05-24 16:33 UTC, niikz commented
@machida 
早速のご対応ありがとうございます🙇

> 今手元で動かしたら、日報をチェックした際の success の toast が表示されなくなってるかもです。

mainブランチで確認したところ、日報をチェックした際の success の toast 表示は元々実装されていないようでした…！
こちらのissueであわせて対応したほうがよろしいでしょうか？

2022-05-25 08:31 UTC, niikz commented
### 2022/05/25(水)質問タイムメモ

https://github.com/fjordllc/bootcamp/pull/4865#issuecomment-1136146859 について komagata さん、 machida さんからの回答

- 日報をチェックした際の success の toast 表示は別 issue にて対応予定
- 今回は error の赤い toast のみの実装でOK

2022-05-25 08:33 UTC, niikz commented
@rosh-1228 
お疲れさまです。お手すきのときにこちらのレビューをお願いしたいです🙏
よろしくお願いします！

2022-05-26 10:44 UTC, rosh-1228 commented
@niikz 
お疲れ様です！
動作確認・テスト実行し問題ないことを確認しましたので、私から`Approve`とさせてもらいます🙆‍♂️

2022-05-28 13:02 UTC, niikz commented
@rosh-1228 
ご確認ありがとうございました〜！
File changed のタブからApproveすると、GitHub上でApproveのチェックマークが付くのでオススメです💡 

<img width="831" alt="image" src="https://user-images.githubusercontent.com/60736158/170826612-310fcd7e-a25a-41ab-886e-5dfede0bace2.png">

2022-05-28 23:16 UTC, rosh-1228 approved these changes
ご教示ありがとうございます！
早速使わせてもらいます！

2022-05-29 07:51 UTC, niikz commented
@komagata 
お疲れさまです。ご都合のよいときに、こちらのレビューをよろしくお願いします！

2022-05-30 17:50 UTC, komagata commented on app/controllers/api/checks_controller.rb
> +    render json: {}, status: :ok
status okだけならheadメソッドか何かで出せたと思います〜

2022-06-02 13:15 UTC, niikz commented
@komagata 
ご確認ありがとうございます！
修正しましたので再度ご確認をお願いいたします🙇

2022-06-09 19:21 UTC, komagata requested changes

2022-06-10 15:35 UTC, niikz commented on app/controllers/api/checks_controller.rb
> +      @check.save!
ご指摘ありがとうございます。修正しました！

6755025f3ae663aeb91bfbb9b16a86ae95d52d02

2022-06-10 15:36 UTC, niikz commented
@komagata 
修正しましたので再度ご確認をお願いいたします🙇

2022-06-12 23:04 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-06-12 23:04 UTC, merged