管理者で相談部屋から相談主の卒業フラグをオンにできるようにした。
fjordllc/bootcamp pull request #4875
Opened 2022-05-23 20:31 UTC by taka110-IT

管理者で相談部屋に入った際に卒業ボタンを表示するようにし、相談主の卒業フラグをオンにできるようにした。

2022-05-23 20:52 UTC, taka110-IT commented
@machida 
卒業ボタンを作成しましたのでデザインをお願いいたします。
現状はadminのユーザー一覧にある卒業ボタンを流用しています。

2022-06-01 08:50 UTC, machida commented
@taka110-IT 
テストが落ちてますがこのPRと関係ないところなので、mainブランチでテストが落ちなくなったらmainをrebaseお願いします。

2022-06-01 12:56 UTC, taka110-IT commented
@machida 
承知しました。デザインを入れていただきありがとうございました🙇🏻‍♂️

2022-06-03 04:27 UTC, taka110-IT commented
@Nabegon 
お疲れ様です。レビューをお願いしたいのですがよろしいでしょうか。
お手すきの際で結構ですのでよろしくお願いします🙇🏻‍♂️

2022-06-03 06:14 UTC, Nabegon commented
@taka110-IT 

お疲れ様です！承知しました。
今週末に行います🙆よろしくお願いします🙏

2022-06-05 18:01 UTC, Nabegon commented
@taka110-IT 

お疲れ様です！動作とコードの確認を行い、問題ありませんでしたので、Approveしました🙆✨

卒業ボタン
![image](https://user-images.githubusercontent.com/49633473/172063946-05ca30fd-1660-4f6f-866a-f4837d3bf056.png)

卒業ボタンを押すと卒業済になる
![image](https://user-images.githubusercontent.com/49633473/172063980-681bf388-3a0e-43db-bb49-91cad8b1f652.png)

2022-06-05 18:01 UTC, Nabegon approved these changes

2022-06-06 09:57 UTC, taka110-IT commented
@Nabegon 
レビューありがとうございました😊

@komagata 
チームのレビューが終わりましたので、チームリーダーレビューをお願いいたします。

2022-06-09 19:54 UTC, komagata reviewed
conflictの修正をお願いします〜

2022-06-12 22:24 UTC, taka110-IT commented
@komagata 
conflictの修正をしました。ご確認をお願いいたします。

2022-06-12 23:20 UTC, komagata commented on app/controllers/graduation_controller.rb
> +      redirect_to @redirect_url, notice: 'ユーザー情報を更新しました。'
これだとそれまで使われていた部分が動かなくならないですかね？
（@redirect_urlがない場合）

2022-06-12 23:57 UTC, taka110-IT commented on app/controllers/graduation_controller.rb
> +      redirect_to @redirect_url, notice: 'ユーザー情報を更新しました。'
@komagata 
下の`set_user` メソッドで`@redirect_url = params[:redirect_url].presence || admin_users_url`として、管理ページのユーザー一覧にいた場合は元の挙動にするようにしました。
開発環境でも管理ページの卒業ボタンが動作していることが確認できましたが、他にも悪い影響がありそうでしょうか。

2022-06-13 06:59 UTC, komagata requested changes

2022-06-13 06:59 UTC, komagata commented on app/controllers/graduation_controller.rb
> +      redirect_to @redirect_url, notice: 'ユーザー情報を更新しました。'
`set_user`という名前のメソッドで関係の無い処理（redirect_urlの設定）をやっていると他の人から見て予想外の動きのわかりずらいコードになってしまうので避けたい感じです〜

2022-06-13 21:02 UTC, taka110-IT commented on app/controllers/graduation_controller.rb
> +      redirect_to @redirect_url, notice: 'ユーザー情報を更新しました。'
承知しました。別のメソッドを作成して処理するようにします。

2022-06-13 22:00 UTC, taka110-IT commented
@komagata 
修正しましたので再確認をお願いいたします。

2022-06-15 14:42 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-06-15 14:42 UTC, merged

2022-06-17 08:23 UTC, taka110-IT commented
@komagata 
お疲れ様です。
お手すきの際に、本番環境での動作確認をお願いしてよろしいでしょうか。
よろしくお願いいたします。

2022-06-18 12:31 UTC, komagata commented
@taka110-IT 次に卒業生が出るタイミングで確認したいと思います〜

2022-06-19 02:17 UTC, taka110-IT commented
@komagata
承知しました。よろしくお願いします🙇🏻‍♂️