Docs作成の通知の実装をabstract_notifierに置き換えた
fjordllc/bootcamp pull request #4879
Opened 2022-05-24 13:43 UTC by rosh-1228

2022-05-25 10:51 UTC, rosh-1228 commented
@ai-24 
お疲れ様です！
isshiさんのモブプロでご一緒されてましたので、レビューをお願いしたいと思います🙏
よろしくお願いします!

2022-05-27 04:23 UTC, ai-24 reviewed
@rosh-1228 
お疲れ様です！
コードが全体的に読みやすくて助かりました🙏✨

ただ私がこちらのgemを使用したことがなく、知識不足の為いくつか質問させていただいております。ご確認よろしくお願いいたします🙏😭

2022-05-27 08:18 UTC, rosh-1228 commented on test/notifiers/activity_notifier_test.rb
> +  test '.create_page' do
> こちらのテスト名の初めにある.は何か意味があるのか気になりました。
> クラスメソッドを.で表すことがあるとRubyのリファレンスで拝見したのですが、こちらは他の意図で使われていますか？

`.create_page`としたのは、既に`.graduated`とありましたので、それに倣って`.`をつけただけですね

> またsetupに書かれている処理がこちらには必要がないように思うのですが（何かで必要であえて残されているようでしたら申し訳ありません💦）、このテストでされているようにtest '.gradueted'の中に入れてしまった方が、今後似たようなテストが増えそうなので良いような気もするのですがいかがでしょうか？

'.gradueted'の@paramsがsetupの中にある理由は私には分からないのですが、`.create_page`に関しては毎回のテスト前に実行しなくても良いかなと思い、`.create_page`の中でparameterを設定しました。

2022-05-27 08:34 UTC, rosh-1228 commented on test/notifiers/activity_notifier_test.rb
> +    notification = ActivityNotifier.create_page(@create_page_params)
> こちらのcreate_pageメソッドはActivityNotifierのインスタンスメソッド、NotificationFacadeのクラスメソッド両方あるかと思うのですが、ActivityNotifierクラスに対してのテストかと思うので、このcreate_pageメソッドがActivityNotifierクラスのクラスメソッドのように見えてしまって混乱しています。

`ActivityNotifier.create_page(@create_page_params)`は、`app/notifiers/activity_notifier.rb`に作成したメソッドを使っております。
[komagataさんのブログ](https://docs.komagata.org/5857)に倣った書き方ですね。
[abstract_notfier](https://github.com/palkan/abstract_notifier#usage)のusageにも以下のように同期・非同期の通知の方法が記述されています。
```ruby
# send notification later（非同期）
EventsNotifier.canceled(profile, event).notify_later

# or immediately（同期）
EventsNotifier.canceled(profile, event).notify_now
```

私の書いたcreate_pageのテストも同期・非同期のテストを行うためのコードを書いております。
以下のようにしているのは、既存の駒形さんが書いていらっしゃるコードに倣っているというのもありますが、`ActivityNotifier.create_page(@create_page_params)`を複数回書くと煩雑なコードなるためnotificationという変数に1度代入しております。
```ruby
notification = ActivityNotifier.create_page(@create_page_params)
```

2022-05-27 08:35 UTC, rosh-1228 commented on test/notifiers/activity_notifier_test.rb
> +    end
ご指摘ありがとうございます！🙇‍♂️
Parameterized版を完全に見落としておりました😓

2022-05-27 08:40 UTC, rosh-1228 commented
@ai-24 
ご質問・ご指摘ありがとうございます！
ご質問いただいたおかげで、説明するために再度komagataさんのブログや公式のgithubページを確認して、abstract_notifierについて理解を深めることができました！

ご指摘のParameterized版のテストを追加しましたので、再度お手数ですがご確認よろしくお願いします！

2022-05-30 01:59 UTC, ai-24 commented on test/notifiers/activity_notifier_test.rb
> +  test '.create_page' do
なるほどです！
ご回答ありがとうございます🙇‍♀️

2022-05-30 05:21 UTC, ai-24 approved these changes
質問へのご回答、テストの追加共にありがとうございます！
私も通知周りの理解を深めることができました🙇‍♀️

動作確認も出来ましたので、私からはApproveさせて頂きます！
お時間頂戴し申し訳ありませんでした🙏💦

2022-05-30 07:25 UTC, rosh-1228 commented
@ai-24 
ご確認ありがとうございます！

@komagata 
お疲れ様です！
お手隙の際に、ご確認よろしくお願いします！🙏

2022-05-30 17:56 UTC, komagata commented
@rosh-1228 conflictの修正お願い致します〜

2022-06-05 01:54 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
コンフリクトを修正しましたので、ご確認よろしくお願いします🙇‍♂️

2022-06-09 19:28 UTC, komagata commented
@rosh-1228 conflictの修正をお願いします〜

2022-06-10 02:34 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
コンフリクトを修正しましたので、ご確認よろしくお願いします！🙏

2022-06-12 22:37 UTC, komagata requested changes

2022-06-12 22:37 UTC, komagata commented on test/notifiers/activity_notifier_test.rb
> +  test '.create_page' do
@rosh-1228 (CC: @ai-24 )

すみません、これ元を書いた僕の間違いで、`#`の方がいいと思います〜
もしよろしければ元の方もついでに直しておいていただければ大変ありがたいです〜

2022-06-16 07:50 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
test/notifiers/activity_notifier_test.rbのテスト名を、komagataさんのテストも含め`.` から `#`に変更しました！

2022-06-21 19:05 UTC, komagata approved these changes
他の部分も修正ありがとうございます。

確認させて頂きました。OKです〜🙆‍♂️

2022-06-21 19:05 UTC, merged

2022-06-23 06:37 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
こちら本番環境にて確認したいのですが、Docsをテストで作成して確認してもよろしいでしょうか？

2022-06-24 04:44 UTC, komagata commented
@rosh-1228 はい、大丈夫です〜

2022-06-24 07:05 UTC, rosh-1228 commented
@komagata 
ありがとうございます！

`abstract_notifierの通知テスト`というタイトルでDocを作成させてもらいましたので、通知されているかご確認お願いします！
ご確認いただけましたら、Docを削除します！

2022-06-25 22:49 UTC, komagata commented
@rosh-1228 これって誰にでも通知がくるんでしたっけ？
僕のアカウントには通知が来てないようでした〜

2022-06-27 14:36 UTC, rosh-1228 commented
@komagata
お疲れ様です！
遅くなり申し訳ありません💦

`app/models/page_callbacks.rb`の28行目にて`receivers = User.where(retired_on: nil, graduated_on: nil, adviser: false, trainee: false)`とあり、私がDocを作成しても、komagataさんは確認できない仕様でした。

お手数おかけして申し訳ありませんが、Docを作成していただいてもよろしいでしょうか🙏

2022-06-29 00:31 UTC, komagata commented
@rosh-1228 あれ、そもそもこの通知って何のために・誰のためにあるんだっけ？というところを考えないといけないかもですね。
（@rosh-1228 さんがDocsを作って僕が通知を受け取れないならどういうシチュエーションのためにあるのか疑問に感じるので）

@rosh-1228 さんはどう考えますか？

2022-06-29 01:21 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
たしかに、Docsは生徒でも作成できますし、受信者が制限されていない方が、ユーザーにとって便利だと思います。
こちらは、本件とは別の話だと思いますので、別issueを立てたいと思いますがよろしいでしょうか？


自分の良くないところが出てしまいました。。。
一旦受け入れちゃうと思考が固まっちゃうので、ユーザーの使い勝手も念頭にプログラムを作成していけるようにしていきたいです😓

2022-06-30 05:37 UTC, rosh-1228 commented
@komagata 
お疲れ様です！

ローカル環境で`管理者・メンター`の区分を持ったユーザーでDoc作成通知を確認したのですが、通知されておりました。

お手数おかけして申し訳ありませんが、再度Docを作成しますので、通知が来ていないかご確認お願いしてもよろしいでしょうか？

2022-07-01 07:22 UTC, komagata commented
@rosh-1228 はい、確認します。

これから作成するということでしょうか？また、どういったDocsを作成してどういった通知が来ることを確認すれば良いでしょうか〜

2022-07-01 08:06 UTC, ai-24 commented
@rosh-1228 
こちらkomagataさんと違うロールを持ってる私も良ければ確認させていただきます😊
土曜日の午前中までに作成いただければ今週中に確認できます〜！

2022-07-01 08:32 UTC, rosh-1228 commented
@komagata 
ありがとうございます！

これから作成します！

ユーザー名が違うのですが、`rosh-1228さんがDocsにabstract_notifier`の通知テストを投稿しました。`という通知が以下のように来ているかどうかご確認いただきたいです！
![_development__ダッシュボード___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64620506/176856769-3f5fa294-67f0-44c0-aa2f-054e18b234df.png)

@ai-24 
ありがとうございます！
大変助かります！😭

2022-07-01 08:33 UTC, rosh-1228 commented
@komagata @ai-24 
今本番環境にDocs投稿しましたので、お手隙の際にご確認よろしくお願いします！

2022-07-01 08:34 UTC, komagata commented
@rosh-1228 通知来てました〜！

2022-07-01 08:40 UTC, ai-24 commented
@ai-24 
私も確認できました〜！

2022-07-01 08:42 UTC, rosh-1228 commented
@ai-24 
ご確認ありがとうございます！
助かります！

2022-07-04 04:32 UTC, komagata commented
@rosh-1228 動作確認が取れればOKです。

2022-07-04 07:30 UTC, rosh-1228 commented
承知しました〜