未ログイン時にユーザーアイコンメンションをブログに表示できるようにした
fjordllc/bootcamp pull request #4932
Opened 2022-06-01 16:33 UTC by rosh-1228

## issue
- #4895 

## 変更前
![_development__ブログタイトル___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64620506/171452783-74fe61d5-0b26-4504-b00f-653cc882c2d0.png)

## 変更後
![_development__ブログタイトル___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）](https://user-images.githubusercontent.com/64620506/171453391-cb84ab15-4359-4071-a4f4-422c2bd1d0d1.png)

## 確認手順
1. ブランチ `feature/display-icon-on-the-blog-after-logout` をローカルに取り込む。
(例)
```
git fetch
git checkout feature/display-icon-on-the-blog-after-logout
```
2. 管理者（komagata）でログインする。
3. `Me`をクリックし、`ブログ投稿`をクリックする。
![_development__ダッシュボード___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）_と_Comparing_main___feature_display-icon-on-the-blog-after-logout_·_fjordllc_bootcamp](https://user-images.githubusercontent.com/64620506/171453601-60e3bef5-ca05-4a27-b06f-9ac544752a53.png)
4. タイトルは任意に入力、本文に`:@machida:`を入力し、`登録する`をクリックする。
5. 右上の`プラクティス`->`Me`->`ログアウト`をクリックする。
6. `ブログ`をクリックする。
7. 作成したブログをクリックし、`:@machida:`のアイコンが表示されていることを確認する。

※`:@machida:`のアイコンが登録されていない場合は、machidaでログイン後、`Me`->`登録情報変更`にて、任意の画像をアップロードして更新してください。

2022-06-07 01:27 UTC, rosh-1228 commented
@NorifumiOgawa 
お疲れ様です！
こちらレビューお願いしてもよろしいでしょうか？
提出物を確認させていただきまして、21ポイントになりそうでしたので、プラクティス合格などで次に進まれるようでしたら別の方に依頼します！
お忙しい場合もご連絡いただければと思います！
よろしくお願いします🙏

2022-06-07 05:28 UTC, NorifumiOgawa commented on test/system/articles_test.rb
> +  test 'display user icon when not logged in' do
こちらのテストについて確認させてください。
- `komagata` でログインしたまま `visit articles_path` に遷移している
- `assert_selector "img[src$='default.png']"`は投稿者の初期アイコンを探す？
ようなのですが、ユーザーアイコンメンションの表示確認の部分が見当たらない気がしたのでご確認お願いできますでしょうか。
もしくは、確認のポイントがずれていたらすみません！

2022-06-07 05:36 UTC, NorifumiOgawa commented on app/controllers/api/user_icon_urls_controller.rb
> +    logged_in? ? users : users.select { |user| user.avatar.present? }
こちら、ログイン時（`users`をそのまま返す）と未ログイン時（`user.avatar.present?` のみ返す）で処理を分けられている意図を読み取れませんでした。お手数ですが、こちら分岐の意図を教えていただけますでしょうか。🙏

2022-06-07 05:40 UTC, NorifumiOgawa reviewed
@rosh-1228 お疲れさまです！
ローカルに取り込んでの動作確認は問題ありませんでした。
以下2点確認させていただければと思います。
- https://github.com/fjordllc/bootcamp/pull/4932/files#r890783643
- https://github.com/fjordllc/bootcamp/pull/4932/files#r890779833

よろしくお願いいたします。

2022-06-07 15:22 UTC, rosh-1228 commented on test/system/articles_test.rb
> +  test 'display user icon when not logged in' do
ご指摘ありがとうございます！
`visit`だけだとログインしていない状態になるかと勘違いしており、調査不足でした💦
こちらは未ログインでブログのアイコンを確認するように修正しました！
また、`komagata`でブログの中に`:@komagata:`を入力して保存しても、ブログの著者のアイコンとブログ本文中のアイコンがかぶるため、`machida`でブログを作成し、`:@komagata:`のアイコンがあることを確認するようにテストを修正しました！

2022-06-08 12:10 UTC, NorifumiOgawa commented on test/system/articles_test.rb
> +  test 'display user icon when not logged in' do
こちら、修正内容とローカルで動作確認しました。

2022-06-08 12:37 UTC, NorifumiOgawa commented
@rosh-1228 テストの修正対応と、API取得の条件分岐に関するご説明、ありがとうございます！
バラバラと申し訳ないのですが、もう一点確認させていただけますでしょうか。
テストに`config.autoloader = :classic` を追加されているようなのですが、こちらを追加された目的を教えていただけますか？
自分はこの`config.autoloader = :classic`という指定を今まで知らなかったので、改めて「定数読み込みのClassicモード」というものを調べているのですが、少し時間がかかりそうなので。
なんとなくなのですが、`config/environments/test.rb`の設定を追加することで他のテストに影響が及ばないかが気になっています。

2022-06-09 00:34 UTC, rosh-1228 commented
@NorifumiOgawa 
`config.autoloader = :classic`なしでのテストを作成しCIも通すことができましたので、再度ご確認よろしくお願いします🙏

2022-06-09 05:43 UTC, NorifumiOgawa approved these changes
ローカルでの動作も確認し、APIで取得できるユーザー情報が限定されている部分も確認しました。良いと思います〜

2022-06-09 07:34 UTC, rosh-1228 commented
@NorifumiOgawa 
ご確認ありがとうございます！

@komagata 
こちら昨日の開発ミーティングで、テストでavatar.attachするとuninitialized constant ActiveStorage::Blob::Analyzableというエラーが出ると相談した件ですが、別の方法でavatar(アイコン)をアップロードするように修正し、チームビューが通りましたので、ご確認よろしくお願いします！🙏

2022-06-10 02:06 UTC, rosh-1228 commented
@komagata 
コンフリクト解消しましたので、再度ご確認よろしくお願いします！🙏

2022-06-12 22:30 UTC, komagata requested changes

2022-06-12 22:30 UTC, komagata commented on app/controllers/api/base_controller.rb
> +  before_action :require_login_for_api, unless: proc { request.referer&.include?('articles') }
refererっていうのはHTTPのヘッダーで、自分で好きなものを設定した上でRequestを飛ばせてしまうので、これの内容で認証するかどうか決めるのは危険です。（telnetでrequestを作った時と同じ。）

2022-06-14 09:15 UTC, rosh-1228 commented
@komagata
お疲れ様です！

ご指摘ありがとうございます！

refererを使わず、skip_before_action :require_login_for_apiを`user_icon_urls_controller`に記述することで、親クラスの`before_action :require_login_for_api`を無効にするように変更しました。

しかし、今回の変更にて`require_login_for_api`をskipするようにしましたので、`test/integration/api/user_icon_urls_test.rb`も変更しております。

このため、`assert_response :unauthorized`を、認証がない時はユーザーのアイコンを取得していないこと、認証がある時はユーザーのアイコンを取得することを確認するテストに変更しました。

再度ご確認よろしくお願いいたします！

2022-06-15 15:04 UTC, komagata requested changes

2022-06-15 15:04 UTC, komagata commented on app/controllers/api/user_icon_urls_controller.rb
> +    logged_in? ? users : users.select { |user| user.avatar.present? }
こちら、rubyで絞り込むよりSQLの段階で取ってくるレコードを少なくして絞り込めると思います。

また、railsのcontrollerで`set_xxx`というメソッドはインスタンス変数にセットして返り血を返さないメソッドで使われているので、違う動作のメソッドにこういう名前をつけると紛らわしくなっちゃうかもです。

また、他からも呼び出されるのでなければメソッドに分けなくて大丈夫だと思います〜。

2022-06-15 15:04 UTC, komagata commented on test/integration/api/user_icon_urls_test.rb
> +    user_icons = @controller.index
これだとcontrollerだけのテストになってしまって「controller test」でやる範囲になってしまうので、integrationテストではresponseから内容を確認するのがいいと思います〜。

2022-06-18 23:02 UTC, rosh-1228 commented
> こちら、rubyで絞り込むよりSQLの段階で取ってくるレコードを少なくして絞り込めると思います。
> 
> また、railsのcontrollerでset_xxxというメソッドはインスタンス変数にセットして返り血を返さないメソッドで使われているので、違う動作のメソッドにこういう名前をつけると紛らわしくなっちゃうかもです。
> 
> また、他からも呼び出されるのでなければメソッドに分けなくて大丈夫だと思います〜。

ご指摘ありがとうございます！
確かに、ログインしているかどうかに関わらず取得するユーザーは限定されるため、indexメソッドにて1行で書けました！

> これだとcontrollerだけのテストになってしまって「controller test」でやる範囲になってしまうので、integrationテストではresponseから内容を確認するのがいいと思います〜。

こちらは、未ログイン時でもresponseがokとなるようにテストを修正しました。

何度もお手数おかけしますが、ご確認よろしくお願いします！

2022-06-21 19:44 UTC, komagata requested changes

2022-06-21 19:44 UTC, komagata commented on app/controllers/api/user_icon_urls_controller.rb
> +    @users = User.with_attached_avatar.select { |user| user.avatar.present? }
これはSQLのレベルでできるかもです。
`select`の時点でrubyになっているので、全てのユーザーをDBから持ってきた上で処理していると思います。

必要なユーザーだけ持ってくることができると思います。

`User.with_attached_avatar.to_sql` など最後に`to_sql`メソッドをつければそのActiveRecordの文が発行するSQLを確認できます。また、ログにも発行されたSQL文が載るのでそれで確認しながらやってみてください〜

2022-06-23 05:41 UTC, rosh-1228 commented on app/controllers/api/user_icon_urls_controller.rb
> +    @users = User.with_attached_avatar.select { |user| user.avatar.present? }
ありがとうございます！
to_sqlを使ってsql文が確認できたのですね😅

`app/views/api/user_icon_urls/index.json.jbuilder`にてログイン名とアバターがアタッチしているかを確認して、アバターのURLを取得していること突き止めました。
```ruby
@users.each do |user|
  json.set! user.login_name, user.avatar.attached? ? rails_storage_proxy_url(user.avatar) : ''
end
```

そのため、SQL文にてユーザーの必要な情報(idとlogin_name)だけを取得するように変更してみました！

2022-06-23 05:43 UTC, rosh-1228 commented
@komagata 
お疲れ様です！
アドバイスありがとうございます！

ActiveRecordで必要なユーザー情報だけを取得するように変更しました！
ご確認よろしくお願いします🙇‍♂️

2022-06-24 04:40 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-06-24 04:40 UTC, merged

2022-06-30 07:37 UTC, rosh-1228 commented
@komagata @machida 
お疲れ様です！

こちらメンタメニューからしか操作できないため、本番環境にて、ブログでアイコンを表示できるかご確認よろしくお願いします！

2022-07-01 07:24 UTC, komagata commented
@rosh-1228 表示されることを確認しました〜