自分の作成したWIPのお知らせとWIPのイベントの一覧をダッシュボードに表示できるようにした
fjordllc/bootcamp pull request #4957
Opened 2022-06-07 05:27 UTC by ai-24

## Issue
- #4727

## 概要
自分の作成したWIPのお知らせとWIPのイベントの一覧をダッシュボードに表示できるようにしました。

## 変更確認方法
1. ブランチ`feature/add-wips-announcement-and-event-to-dashboard`をローカルに取り込みます。
2. `bin/rails s`でローカル環境を立ち上げます。
3. kimuraでログインします。
4. お知らせ作成ページ(http://localhost:3000/announcements/new)からお知らせ作成のフォーマットを完成させWIPで保存します。
5. ダッシュボード(http://localhost)に移動し、4で作成したお知らせがWIPで保存中の一覧に表示されているか確認します。
6. 次にイベント作成ページ(http://localhost3000/events/new)からイベント作成のフォーマットを完成させWIPで保存します。
7.  再度ダッシュボード(http://localhost)を確認し、6で作成したイベントがWIPで保存中の一覧に表示されているか確認します。

## 変更前

2022-06-07 06:10 UTC, ai-24 commented
@machida 
お疲れ様です。
デザインの事で１つ質問させてください。

下記の赤枠の部分の文字の色を他の文字と揃えて白にしたいと思っております。

<img width="364" alt="スクリーンショット 2022-06-07 14 50 36" src="https://user-images.githubusercontent.com/76685187/172305640-f18dbd3f-c861-47f9-a3a2-25c04c97246d.png">

下記のコードがお知らせの色を黒にしていると思うので、こちらを`$reversal-text`にする事で解決するかと思うのですが、変更する事で他のページに影響が出る可能性があるかも知れないと思ったので、念の為確認させていただきたいです。
こちら`$reversal-text`に変更してしまっても問題ないでしょうか？下記コードのファイルは`app/assets/stylesheets/blocks/card-list/_card-list-item-title.sass`の52行目です。
私が確認したところだとおそらく他に影響はないかと思うのですが、、、🤔

<img width="240" alt="スクリーンショット 2022-06-07 14 55 30" src="https://user-images.githubusercontent.com/76685187/172306228-f63e8627-eadc-46e9-917b-922abf918325.png">

2022-06-07 07:34 UTC, machida commented
@ai-24 確認しますー🙋

2022-06-08 03:33 UTC, machida commented
@ai-24 お知らせは背景が黄色なので、白い文字にすると文字が見えなくなってしまいます（目が不自由な人は特に）。なので意図的に黒にしてるので、このままでお願いしますー

2022-06-08 03:34 UTC, machida commented
@ai-24 というわけで、デザインはこのままでレビューに進めていただくようお願いしますー

2022-06-08 04:43 UTC, ai-24 commented
@machida 
なるほどです！
そういう意図があったのですね。
知らずにお手数おかけして申し訳ありませんでした😨
かしこまりました！
レビュー依頼させていただきます！

2022-06-08 04:57 UTC, ai-24 commented
@masanarih0ri 
お疲れ様です。
お忙しいところ恐れ入りますが、レビューよろしくお願いいたします🙇‍♀️

2022-06-08 05:21 UTC, machida commented
@ai-24 いえいえ、全然手間ではないですよー。気になったことを質問するのはすごくいいことなので、これからもどんどんしてくださいー🙏

2022-06-08 05:31 UTC, ai-24 commented
@machida 
ありがとうございます！！🙏

2022-06-08 14:19 UTC, masanarih0ri requested changes
@ai-24 
細かい点を少しコメントさせていただきました。その他は良さそうでした👍

2022-06-08 14:19 UTC, masanarih0ri commented on app/models/user.rb
> +    user_wip = pages.wip + reports.wip + questions.wip + products.wip + announcements.wip + events.wip
user_wipという名前だと、この変数が配列のデータを参照していることが少しわかりにくいので、`wip_contents` のような複数形にしたりすると良さそうだなと思いました。

2022-06-08 14:19 UTC, masanarih0ri commented on app/models/user.rb
> +  def wip_present?
メソッドがbooleanを返すときは `is_hoge?` `has_hoge?`のような形で書くことがあります。（必ずそうというわけではないですが）

`user.has_wip_contents?` のようなメソッドの使い方の方が実際に使った時にわかりやすいと思いました。

2022-06-09 05:19 UTC, ai-24 commented on app/models/user.rb
> +    user_wip = pages.wip + reports.wip + questions.wip + products.wip + announcements.wip + events.wip
ご指摘ありがとうございます！
おっしゃる通りです。修正いたします🙏

2022-06-09 05:39 UTC, ai-24 commented on app/models/user.rb
> +  def wip_present?
なるほどです！
メソッド名を付ける時に悩んだのですが、下記の記事を参考にし`present`は形容詞で真偽値を返すメソッドなので動詞を置く必要はないかと考え、Railsのメソッドでも`present?`が真偽値を返すメソッドとして存在するので、そちらに似せた形で分かりやすいかと思い`wip_present?`にさせて頂いたのですが、確かに実際に使うときの事を考えると提案して頂いた`has_wip_contents?`の方が直感的で分かりやすいかと思いました🤔
またRubyのリファレンスにも動詞＋目的語のような形で真偽値を返すメソッドが存在している事も確認しました。
こちらも修正いたします！

[モデルやメソッドに名前を付けるときは英語の品詞に気をつけよう \- Qiita](https://qiita.com/jnchito/items/459d58ba652bf4763820#%E5%87%A6%E7%90%86%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%AF-%E5%8B%95%E8%A9%9E%E3%81%AE%E3%81%BF-or-%E5%8B%95%E8%A9%9E--%E5%90%8D%E8%A9%9E%E3%81%AB%E3%81%99%E3%82%8B)

2022-06-09 06:24 UTC, ai-24 commented on app/models/user.rb
> +  def wip_present?
こちらの`has_wip_contents?`ですが、CIに引っかかってしまいましたので、メソッド名を`wip_owned?`とさせていただきました。
頂いたアドバイスを元にユーザーがWIPを持っているかの真偽値が返ることが分かるような名前にしたつもりなのですが、違和感などあればお知らせ願います🙏

以下がRubocopで指摘された内容でした。

```

app/models/user.rb:617:7: C: Naming/PredicateName: Rename has_wip_contents? to wip_contents?.
  def has_wip_contents?
      ^^^^^^^^^^^^^^^^^

477 files inspected, 1 offense detected
```

[Class: RuboCop::Cop::Naming::PredicateName — Documentation for rubocop \(1\.30\.1\)](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/PredicateName)

2022-06-09 14:43 UTC, masanarih0ri commented on app/models/user.rb
> +  def wip_present?
なるほど！個人的には `wip_contents?` の方が素直で良いかなと思いましたがどうでしょうか？ただ、そこは結構個人的な意見も入っているので、`wip_owned?` でダメかというとそうではありません。なので、そのままでもOKです！そこの判断はお任せします👍

2022-06-09 15:37 UTC, ai-24 commented
@masanarih0ri 
メソッド名とローカル変数の名前は同じものにしない方が良いと以前記事を読んだことがあるので（ややこしいという理由でしたので禁止されているわけではないと思いますが）、今回はこのままで駒形さんにレビュー依頼させていただきます。厳密にいうと`?`が入っているので別かもしれませんが、、、
レビューいただきありがとうございました🙇‍♀️

@komagata 
チームメンバーのレビュー確認いただきましたので、ご確認お願いいたします。

2022-06-09 20:34 UTC, komagata commented on app/models/user.rb
> +  def wip_owned?
modelのテストが欲しいかもです〜

2022-06-10 05:44 UTC, ai-24 commented
@komagata 
モデルテストを追加いたしました！
再レビューよろしくお願いいたします。

2022-06-12 23:00 UTC, komagata requested changes

2022-06-12 23:00 UTC, komagata commented on app/models/user.rb
> +  def wip_owned?
`wip_owned?`だとちょっとどういうものなのかメソッド名からわからないかも？です。
英語の文章的にはどういうイメージですかね？

2022-06-14 01:14 UTC, ai-24 commented
@komagata 
WIPが所有されているか？というイメージだったのですが、
確かに英語の文章として考えるとよく分からないですね😵
ユーザーが所有しているWIPがあるかどうかの真偽値を返すメソッドという意味にしたいので、
`own_wip?`はいかがでしょうか？

2022-06-15 14:49 UTC, komagata commented
@ai-24 `own_wip?`わかりやすくなったと思います〜。
conflictしているところがあるので解消をお願いします〜

2022-06-17 11:52 UTC, ai-24 commented
@komagata 
メソッド名の変更とコンフリクトの解消を行いました。
再レビューお願いできますでしょうか。
よろしくお願いいたします🙇‍♀️

2022-06-21 19:33 UTC, merged