参考書籍ページで各書籍に紐付くプラクティスへのリンクを追加
fjordllc/bootcamp pull request #5025
Opened 2022-06-13 14:17 UTC by SatoshiHaramura

## Issue

- #4959

## 概要

参考書籍ページにおいて、各書籍に紐付くプラクティスへのリンクを追加しました。

## 確認方法

1. ブランチ`feature/add-link-to-practice-lassociated-with-book-in-reference-books`をローカルに取り込む。
2. `bin/rails s`でローカル環境を立ち上げる。
3. 任意のユーザでログインし、`/books`にアクセスする。

## 確認内容

## 変更前
<img width="961" alt="Cursor_and__development__参考書籍___FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/11376040/173373336-c8c188df-b64b-4c5c-894f-d6149ecbb25c.png">

## 変更後

2022-06-13 15:02 UTC, SatoshiHaramura commented
@isshi-hasegawa 
お疲れ様です。
レビューの依頼をさせて頂きたいです🙏
こちら([good first issue 攻略・その１「着手からレビュー依頼まで」](https://bootcamp.fjord.jp/pages/443))のドキュメントが分かりやすくて、とても助かりました✨ありがとうございます！
お手数ですが、宜しくお願い致します。

@machida 
お疲れ様です。
本日の質問タイムでお聞きしたとおり、デザインの対応を依頼させて頂きます🙏
一旦、ul/liタグを入れてみましたが、適切がどうか自身が無いため、併せてご確認頂けますと幸いです。

2022-06-13 17:13 UTC, isshi-hasegawa approved these changes
@SatoshiHaramura 
実装お疲れさまでした。
ドキュメントがお役に立ったようで良かったです〜〜
動作の方もコードの方も確認いたしました👍

2022-06-14 00:39 UTC, SatoshiHaramura commented
@isshi-hasegawa 
レビューして頂きありがとうございました！

2022-06-14 00:44 UTC, SatoshiHaramura commented
@komagata 
お疲れ様です。
チームメンバーのレビューが通りましたので、お手すきの際にレビューをお願い致します🙏
あと、町田さんにデザインを入れて頂く必要があるのですが、こちらは依頼中となります。

2022-06-15 14:48 UTC, komagata requested changes

2022-06-15 14:48 UTC, komagata commented on app/views/books/_book.html.slim
> +            - if book.practices_books.exists?
bookから直接practicesが取れるかと思います〜

2022-06-16 02:33 UTC, SatoshiHaramura commented on app/views/books/_book.html.slim
> +            - if book.practices_books.exists?
@komagata 
承知致しました。

bookから直接practicesを呼べるようにするために、併せて修正致します。

2022-06-16 02:42 UTC, SatoshiHaramura commented
@isshi-hasegawa 
お疲れ様です。
駒形さんとのレビューで、こちらのコメント(https://github.com/fjordllc/bootcamp/pull/5025#discussion_r898080296) を頂き、修正を行いましたので、再度レビューをお願いさせて頂きたいです🙏
お手数おかけします🙇‍♂️

2022-06-16 02:56 UTC, isshi-hasegawa commented
@SatoshiHaramura 
この場合レビュー依頼は手戻りすることなく、komagataさんに再レビュー依頼お願いします〜
とは言え、komagataさんのご指摘は勉強になりました😅

2022-06-16 02:57 UTC, isshi-hasegawa approved these changes

2022-06-16 03:34 UTC, SatoshiHaramura commented
@isshi-hasegawa 
この場合はレビュー依頼の手戻りは不要なのですね！承知致しました！

@komagata 
お疲れ様です。
頂いていたコメント(https://github.com/fjordllc/bootcamp/pull/5025#discussion_r898080296) に対応する修正を行いましたので、再度レビューをお願い致します🙏

2022-06-16 08:19 UTC, machida approved these changes

2022-06-16 08:19 UTC, machida commented
@SatoshiHaramura デザイン入れましたー

2022-06-16 14:27 UTC, SatoshiHaramura commented
@machida 
お疲れ様です。
デザインを入れて頂きありがとうございます！
ただlintが失敗しているように見受けられるのですが、これはどのように対処すればよいのかご存知でしょうか？

2022-06-23 06:10 UTC, SatoshiHaramura commented on app/views/books/_book.html.slim
> +                = link_to practice.title, practice_path(practice), class: 'tag-links__item-link'
@machida 
お疲れ様です。
先日デザインを入れて頂いた際に、上記のコードが重複しているように見受けられるのですが、削除してもよろしいでしょうか？ご確認お願い致します🙏

2022-06-23 07:07 UTC, machida commented on app/views/books/_book.html.slim
> +                = link_to practice.title, practice_path(practice), class: 'tag-links__item-link'
@SatoshiHaramura すいません！デザイン 調整のために書いたものを消し忘れてました🙇‍♂️ 消しておきますー

2022-06-23 07:16 UTC, machida commented
@SatoshiHaramura 修正しましたー。多分、lintも通ると思いますー

2022-06-24 04:56 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-06-24 04:56 UTC, merged