定期イベントの開催日を毎月第XのX曜日と指定できるようにする
fjordllc/bootcamp pull request #5039
Opened 2022-06-16 14:02 UTC by masanarih0ri

2022-07-02 00:59 UTC, masanarih0ri commented
@kazumi3858 
お手隙でレビューをお願いいたします！

2022-07-02 10:40 UTC, kazumi3858 commented
@masanarih0ri さん
お疲れ様です！
まだコードレビューはほとんど手がついていない状態なのですが、動作確認でおかしい部分があったのでお先に報告いたします🙇‍♂️
テスト観点の「次回のイベント開催予定日が正しく表示されること」に関してです。

### 第n△曜日の捉え方について

色んな曜日を入力して試してみたのですが、以下の画像をご覧ください。

![issue0702-03](https://user-images.githubusercontent.com/97820517/176990754-cb25776a-1fdc-49ed-b448-e1290fdabb69.png)

今月の第4木曜日は28日だと思うのですが、次回開催日に21日と表示されてしまうようです。
もしかして月の週の数を数えて「n番目の週の△曜日」が表示されてしまっているのかな？と思いました。
ただ、第5日曜日を設定すると正しく31日が表示されるのでちょっとロジックが分かりませんでした。

私のほうで考えてみたのですが、たぶん以下の計算で第n△曜日から日付を導き出せるのではないかなと思います。

```ruby
# 日→0 月→1 火→2 水→3 木→4 金5→ 土→6とする

# 第n△曜日の場合だと

date = (n - 1) * 7 + △曜日の数字 - その月の初日の曜日 + 1
if date % 7 == 0
  date += 7
end


# 具体的に、2022年7月の第4木曜日とすると

date = (4 - 1) * 7 + 4 - 5 + 1 # 21になる
if date % 7 == 0 # これがtrueになる
  date += 7
end # 答えは28になる

# 2022年8月の第3火曜日なら

(3 -1) * 7 + 2 - 1 + 1 # 16になる

```

特に年末年始の考慮は必要ないかなと思いました。
久しぶりの数学なので計算方法がスマートかどうかは分かりませんが、一度見ていただけると幸いです。

2022-07-02 14:03 UTC, masanarih0ri commented
@kazumi3858
確認ありがとうございます！
んー、なんかずれる時あるんですよね...もう少し調べてみます。
考えていただいたコードも試してみますね👍

年末年始の処理は、それがないと、少なくとも2023 1/2 か 1/3あたりからおかしくなるので、処理としては必要なんですよね。
cweekで年末年始を正しく把握しきれないようなので、そこの調整が必要なんです🤔

2022-07-02 23:39 UTC, masanarih0ri commented
@kazumi3858 
考えていただいたロジックを試してみたのですが、定期開催日が第3月曜とかだと、表示上は7月18日になって欲しいのに、7月11日になってしまうようなので、別の方法を考えるか、ロジックを改良しないと難しそうでした🤔（理由は n % 7 の値が 0 にならずに +7されないため）

私の元の実装の方針としては

* 今日の次の日から35日分の配列を作る
* その配列の中から条件に合致する候補日を抽出する（おそらくここのロジックがおかしいのですが）
* 候補日の中から、今日から最も近いものを選んで表示

というイメージです。
複数の定期開催日が設定された時に、上記の方針じゃないと正しい判別が難しそうだな...と思ったのでそうしています。

もう1つのアプローチとしては、先に直近の第n △曜日を計算して配列に入れて、その中で最も直近のものを選択するということもできるかとは思います。

バグの原因がいまいち掴めていないので、もう少し自分でも調査してみます:bow:

2022-07-03 00:32 UTC, kazumi3858 commented
@masanarih0ri さん

すみません・・・私の計算が間違っておりました😵‍💫
正しくは以下になりそうです。

```ruby
# 日→0 月→1 火→2 水→3 木→4 金5→ 土→6とする

# 第n△曜日の場合だと

date = (n - 1) * 7 + △曜日 - その月の初日の曜日 + 1
if △曜日 < その月の初日の曜日
  date += 7
end

```

もし上記の式が使えそうであれば使ってみてください。
他にもっと良い方法があればおまかせします✨😊

2022-07-03 02:50 UTC, masanarih0ri commented
@kazumi3858 
ありがとうございます！上記の式の場合、1つの月単体であれば、正しく第n  △曜日の日付の数値を取れそうだったので、ひとまずこの式をうまく使ってロジックを組み直してみようと思います。

* 今日の日付を取得して、今日の日付の月（例えば今日なら7月）の第n  △曜日の値を使ってDateオブジェクトを作る
* 今日の次の月（今日なら8月）の第n  △曜日の値を使ってDateオブジェクトを作る
* ↑の内容を、イベントに紐づいている定期開催日ルール分だけ繰り返して配列を作る
* ↑で作った配列の中から、今日以降で、最小の（最も日が近い）ものを選んで表示する

みたいな感じにすればいけそうだと思いました。ここの実装は半日くらいかかるかもしれないので、このロジック以外のところのレビューを進めていただければと思います:bow:

2022-07-03 03:40 UTC, kazumi3858 commented
@masanarih0ri さん

またまた横から失礼します🙇‍♂️

毎週開催の場合、`次の△曜日`の取得はactive_supportメソッドの`0.days.ago.next_week(:△曜日)`を活用すれば簡単にできそうです。
こんな感じで、今日は日曜なので`次回の日曜`が10日、`次回の月曜`は4日と出てきます。
（machidaさんやkomagataさんがどういう想定をされているか分からないのですが、このメソッドをそのまま活用すると開催日当日のイベントは`本日`ではなくその次の週の日付が出ることにはなります）
![image](https://user-images.githubusercontent.com/97820517/177023421-67a99612-2b3b-435b-a9c2-ee57e7dfcd6c.png)

https://qiita.com/14021939/items/b6c13367042b8192936d
https://railsguides.jp/active_support_core_extensions.html#date%E3%81%AE%E6%8B%A1%E5%BC%B5

次回の△曜日（複数ある場合は複数用意）と次回の第n△曜日を比べて今日の日付から1番近い方を抽出すると良さそうです。
「今日の次の日から35日分の配列を作る」はなくてもいけるんじゃないかと思っております🙏

2022-07-03 05:29 UTC, masanarih0ri commented
@kazumi3858 
情報ありがとうございます！それも使ってあと少しで実装できそうなので、ひとまず動かせる形まで持っていきます👍

> 「今日の次の日から35日分の配列を作る」はなくてもいけるんじゃないか

これはおっしゃる通りですね！まだ実装し直しの途中ではありますが、すでに使わなくなっているので、修正のタイミングで消しちゃいますね！

2022-07-03 08:24 UTC, masanarih0ri commented
@kazumi3858 
一旦共有なのですが、大枠の実装し直しはできました！

ただ、`0.days.ago.next_week(:sunday)` の動作（厳密にいうとnext_week）の動作が想定と少しずれていて、例えば `Date.new(2022, 7, 1).next_week(:sunday)` とすると7月3日ではなく、7月10日を取得してしまいます。

<img width="680" alt="image" src="https://user-images.githubusercontent.com/20497053/177031112-07285756-84cc-4302-ad83-3e198198a4d5.png">

これは、7月1日の週に7月3日が含まれていることで、7月10日が次の日曜だと判定されていることが原因のようなので、別の方法で実装するか、この方法をもう少し突き詰めて、条件分岐などでなんとかするかを考えてから修正していこうと思います:bow:

2022-07-03 13:03 UTC, kazumi3858 commented
@masanarih0ri さん

たびたびすみません🙇‍♂️🙇‍♂️🙇‍♂️

>曜日を指定すると（現時点から見て）「前回その曜日だった日時」と「次回その曜日になる日時」を返す`Date#prev_occurring`と`Date#next_occurring`を追加。

引用元：https://railsguides.jp/5_2_release_notes.html#active-support

もしかしたら`next_week`よりも`next_occurring`のほうが相応しいかもしれません。（後だしで次から次へとすみません）

![image](https://user-images.githubusercontent.com/97820517/177040937-832132f8-1853-4240-9689-6fb1ac0bb6c2.png)


1日前の日付から見て`次の日曜日`みたいに取得すると、ちゃんと当日の日付も取得できそうですね。

2022-07-04 05:01 UTC, masanarih0ri commented
@kazumi3858 
次回開催日のロジック部分を修正しました。お手隙でご確認をお願いいたします！

2022-07-05 07:26 UTC, kazumi3858 reviewed
@masanarih0ri さん
実装お疲れ様でした😊✨
気になった点にコメントしておりますのでご確認よろしくお願いいたします。

2022-07-05 07:26 UTC, kazumi3858 commented on app/decorators/regular_event_decorator.rb
> +  def specific_next_day_of_the_week(repeat_rule)
`specific_next`ではなく`next_specific`になります🙏

2022-07-05 07:51 UTC, masanarih0ri commented on test/system/regular_events_test.rb
> +  test 'create and update frequency and day_of_the_week in a regular event' do
定期イベントを作成するテストのところに

```
click_link '内容修正'
    click_link '定期開催日追加'

    within 'form[name=regular_event]' do
      first('.regular-event-repeat-rule').all('.regular-event-repeat-rule__frequency select')[0].select('第2')
      first('.regular-event-repeat-rule').all('.regular-event-repeat-rule__day-of-the-week select')[0].select('水曜日')
      assert_difference 'RegularEventRepeatRule.count', 1 do
        click_button '内容変更'
      end
    end
```

などを追加するということでしょうか？

そうするとテストの意味が変わってしまう気がしたので別にしていました。

ちょっと意図がわからなかったので、教えていただけると助かります🙇‍♂️

2022-07-05 07:53 UTC, masanarih0ri commented on db/fixtures/regular_events.yml
> -  wday: 水曜日
> db fixturesで作られた定期イベントのshowページ

これはどこのことを指していますでしょうか？開発している時に見た記憶がないので...。URLでいただけると助かります。

2022-07-05 07:56 UTC, masanarih0ri commented on app/models/regular_event.rb
> +  FREQUENCY_LIST = [
これはselectタグを使った選択肢を作るために二重配列にしているのですが、Hashや一次元配列でもselectタグに適用できましたっけ？（ちょっとその方針だとview側のロジックがわかりにくくなるような気がしました）

2022-07-05 09:40 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
https://github.com/fjordllc/bootcamp/issues/4915#issuecomment-1174800249
で追加の仕様が来てしまったので、コードを書き換えます。
詳細はいま確認していますが、

イベントが今日の21時からの場合
* 昨日の23:59までは 次回開催日 07月05日と表示
* 0:00〜20:59までは 本日開催 と表示
* 21時以降は次回開催日を表示

みたいな感じになるかもしれません！

2022-07-05 10:21 UTC, kazumi3858 commented on app/models/regular_event.rb
> +  FREQUENCY_LIST = [
@masanarih0ri さん
手元で動かしてみました！
フラットな配列`['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日',]`でもセレクトボックスは作られることが確認できました。
また、ハッシュでもできたのですがvalueではなくkeyの方で選択肢が作られてしまうようなのでハッシュはたしかにやめておいた方が良いかもしれません。すみません🙇‍♂️
参考：https://shinmedia20.com/rails-select-box

2022-07-05 10:23 UTC, kazumi3858 commented on app/models/regular_event.rb
> +  FREQUENCY_LIST = [
ネストした配列だと`['sample1', 1]`の1のほうがパラメータになるという違いがあるんですね！
1や2をパラメータとして送りたいということであれば今のままで良さそうです。

2022-07-05 10:32 UTC, kazumi3858 commented on db/fixtures/regular_events.yml
> -  wday: 水曜日
@masanarih0ri さん

http://localhost:3000/regular_events にアクセスして、fixturesから作られている適当なイベントをクリックしてみてください🙏
以下の動画のようになりませんか？👀
開発用の定期イベントデータに開催日時情報がないからかな？と推測しました。間違っていたらすみません。

https://user-images.githubusercontent.com/97820517/177308385-6e81d553-e6d0-4c4a-b4a9-a93823cf6946.mp4

2022-07-05 10:43 UTC, kazumi3858 commented on test/system/regular_events_test.rb
> +  test 'create and update frequency and day_of_the_week in a regular event' do
@masanarih0ri さん

[23行目](https://github.com/fjordllc/bootcamp/pull/5039/files#diff-77689e8f5a37aa878c25ff0261719fb3a74f70967bf6b58efa5a97f256776419L23)のテストで定期イベントの作成を行っているのと、[56行目](https://github.com/fjordllc/bootcamp/pull/5039/files#diff-77689e8f5a37aa878c25ff0261719fb3a74f70967bf6b58efa5a97f256776419L56)のテストで定期イベントの更新を行っていますよね。
開催日時も定期イベント作成時の入力項目なので、ただこの2つのテストメソッドに追記するだけで良いのではないかと思いました。
`assert_text '毎週月曜日'`みたいにassert文を追加したらどうかなと思い提案いたしました。

>そうするとテストの意味が変わってしまう気がしたので別にしていました。

宜しければどんな点が気になっているかお伺いしたいです🙏✨

2022-07-05 14:05 UTC, masanarih0ri commented on test/decorators/regular_event_decorator_test.rb
> +  test 'specific_next_day_of_the_week' do
こちらは修正しました！問題なければResolve conversationを押していただけると:bow:

2022-07-05 14:05 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +  def specific_next_day_of_the_week(repeat_rule)
こちらは修正しました！問題なければResolve conversationを押していただけると:bow:

2022-07-06 03:04 UTC, masanarih0ri commented on db/fixtures/regular_events.yml
> -  wday: 水曜日
@kazumi3858 
こちら再現しました！wakaranチャンネルで修正方法を理解したので対応します👍

2022-07-07 00:12 UTC, masanarih0ri commented on db/fixtures/regular_events.yml
> -  wday: 水曜日
@kazumi3858 
アクセスできないという不具合は解消しました！
終了したイベントに次回開催日が表示されているようなので、 https://github.com/fjordllc/bootcamp/pull/5039#discussion_r913598913 の対応の際にそこも修正しようと思います！なので、ここのコメントはアクセスできないことが解消されていたら Resolve Coversation押しておいていただければと思います。

2022-07-07 00:15 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +      date += DAYS_OF_THE_WEEK_COUNT if repeat_rule[:day_of_the_week] < first_day.wday
こちらも対応しましたのでResolve conversationをお願いします:bow:

2022-07-07 03:07 UTC, kazumi3858 commented on db/fixtures/regular_events.yml
> -  wday: 水曜日
@masanarih0ri さん

修正ありがとうございます✨
結論から言うと私の環境では問題が解消されておりませんでした。
[44行目](https://github.com/fjordllc/bootcamp/pull/5039/files#diff-c61a903a1201b0c7f076b0270377c20390c26f655ce63689d7d843296fcf63f3R44)の`regular_event_repeat_rules`を42行目の`regular_events`より上に持っていきseedデータを作り直すことでアクセスできるようになりました。（依存関係の問題と推測しております）

masanariさんの環境では既に問題が解消しているという点が気になります🤔

```
rails db:migrate:reset
rails db:seed
```
を試してみてもアクセスできますか？

2022-07-07 13:23 UTC, masanarih0ri commented on app/models/regular_event.rb
> +  FREQUENCY_LIST = [
そうですね、ここは今のままで良いかと思いました。パラメータは数値で送っておきたいというのが大きな理由になります。
（問題ないということであればこちらもResolve conversationをお願いします。）

2022-07-07 13:40 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +      { frequency: repeat_rule.frequency, day_of_the_week: repeat_rule.day_of_the_week }
確かにおっしゃる通りで、このメソッドいらないですね。。削除して書き換えました！

2022-07-07 14:23 UTC, kazumi3858 commented on app/models/regular_event.rb
> +  FREQUENCY_LIST = [
@masanarih0ri さん
ご返信ありがとうございます！
なるほど。数値を保存すべきか悩むところです・・・🤔
とりあえずこのままにしていただいて、komagataさんのレビュー時にkomagataさんに判断してもらおうと思います😊✨
conversationも一旦残させてください🙏

2022-07-08 00:23 UTC, masanarih0ri commented on test/system/regular_events_test.rb
> +  test 'create and update frequency and day_of_the_week in a regular event' do
ああ、そういう意味ですね！理解しました！
https://github.com/fjordllc/bootcamp/pull/5039/commits/1bc90ea14daf6486686bfbee092228122e6139cb で変更したので意図と合っているか確認をしていただけますでしょうか？

2022-07-08 03:38 UTC, kazumi3858 commented on test/system/regular_events_test.rb
> +  test 'create and update frequency and day_of_the_week in a regular event' do
@masanarih0ri さん
確認しました😄
OKでございます✨

2022-07-09 10:00 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@kazumi3858 
上記の実装、対応しましたのでお手隙でご確認いただければと思います👍
確認方法としては

* イベントの定期開催日を今日に該当しないようにする（結果：次回開催日が表示される）
* イベントの定期開催日を今日に該当するものにして、開始時間を今よりも前の時間にする（結果：本日開催と表示される）
* イベントの定期開催日を今日に該当するものして、開始時間を今よりも後の時間にする（結果：次回開催日が表示される）
* 終了しているイベントにアクセスする（結果：開催終了と表示される）

で確認できるかと思います。

2022-07-10 01:56 UTC, kazumi3858 commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@masanarih0ri さん

実装いただきありがとうございます！✨
まだレビューが終わっていないのですが動作確認の報告だけ先にいたします。

![image](https://user-images.githubusercontent.com/97820517/178128286-e159ce6e-d883-4c89-9013-83303d16f563.png)

`第1～5`かつ`今日の曜日（日曜日）`を設定するとエラーになってしまうようです。
[calc_week_of_month](https://github.com/fjordllc/bootcamp/pull/5039/files#diff-cb7160e058469cc161203ed5056e15582a63cec49edf8612089861c476cc832cR46)が無いというエラーのようです🙏

2022-07-10 02:52 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
あ、ごめんなさい、必要なメソッドも消してしまっていたようでした🙇‍♂️
修正しました。お手隙でご確認をお願いいたします。

2022-07-10 13:44 UTC, kazumi3858 commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@masanarih0ri さん

修正お疲れ様です！✨

以下のように`now`に昨日の日付を入れてみると
```
  def event_day?
    now = Time.zone.local(2022,7,9,12,0)
```
第2日曜が本日の日付にならないですね🤔

![image](https://user-images.githubusercontent.com/97820517/178139271-a7fe7eca-1489-42a4-9864-5913efde1490.png)

他にも色んな日付で試したのですがうまく表示される日とそうでない日があるようです。

それとロジックがだんだん複雑になってきているので、どうにか簡潔にできないかな～と思って考えてみました。

以下コードになります↓↓
<details>

あえて最初から`Time`で現在時刻を保持させておいて、今日のイベント時刻が過ぎたかどうかを簡潔に比較できるようにしてみました。

```ruby
module RegularEventDecorator
  DAYS_OF_THE_WEEK_COUNT = 7

  FREQUENCY_LIST = [
    ['毎週', 0],
    ['第1', 1],
    ['第2', 2],
    ['第3', 3],
    ['第4', 4],
    ['第5', 5]
  ].freeze

  DAY_OF_THE_WEEK_LIST = [
    ['日曜日', 0],
    ['月曜日', 1],
    ['火曜日', 2],
    ['水曜日', 3],
    ['木曜日', 4],
    ['金曜日', 5],
    ['土曜日', 6]
  ].freeze

  def holding_cycles
    regular_event_repeat_rules.map do |repeat_rule|
      holding_frequency = FREQUENCY_LIST.find { |frequency| frequency[1] == repeat_rule.frequency }[0]
      holding_day_of_the_week = DAY_OF_THE_WEEK_LIST.find { |day_of_the_week| day_of_the_week[1] == repeat_rule.day_of_the_week }[0]
      holding_frequency + holding_day_of_the_week
    end.join(',')
  end

  def next_event_date
    return '開催終了' if finished
    event_day = possible_next_event_dates
    event_day.today? ? '本日開催' : "次回の開催日は #{l event_day} です"
  end

  def possible_next_event_dates
    regular_event_repeat_rules.map do |repeat_rule|
      possible_next_event_date(repeat_rule)
    end.min
  end

  def possible_next_event_date(repeat_rule)
    if repeat_rule.frequency.zero?
      date = next_specific_day_of_the_week(repeat_rule, 1)
      has_future_event?(date) ? date : next_specific_day_of_the_week(repeat_rule, 0)
    else
      date = calc_date_from_week_number(repeat_rule, Date.today.beginning_of_month)
      has_future_event?(date) ? date : calc_date_from_week_number(repeat_rule, Date.today.beginning_of_month.next_month)
    end
  end

  def has_future_event?(date)
    return true if date > Time.zone.now.beginning_of_day + 1.day
    date.today? && date < Time.zone.local(date.year, date.month, date.day, start_at.hour, start_at.min)
  end
  
  def calc_date_from_week_number(repeat_rule, first_day)
    # 次の第n X曜日の日付を計算する
    now = Time.zone.now
    date = (repeat_rule.frequency - 1) * DAYS_OF_THE_WEEK_COUNT + repeat_rule.day_of_the_week - first_day.wday + 1
    date += DAYS_OF_THE_WEEK_COUNT if repeat_rule.day_of_the_week < first_day.wday
    Time.new(first_day.year, first_day.mon, date, now.hour, now.min)
  end

  def next_specific_day_of_the_week(repeat_rule, base_date)
    case repeat_rule[:day_of_the_week]
    when 0
      base_date.days.ago.next_occurring(:sunday).to_time
    when 1
      base_date.days.ago.next_occurring(:monday).to_time
    when 2
      base_date.days.ago.next_occurring(:tuesday).to_time
    when 3
      base_date.days.ago.next_occurring(:wednesday).to_time
    when 4
      base_date.days.ago.next_occurring(:thursday).to_time
    when 5
      base_date.days.ago.next_occurring(:friday).to_time
    when 6
      base_date.days.ago.next_occurring(:saturday).to_time
    end
  end
end
```
このまんまだと時刻まで表示されてしまっていますが・・・😄
![image](https://user-images.githubusercontent.com/97820517/178146169-e9e8c87d-4143-468b-b41f-c9c64c74487e.png)

</details>

ちなみに動作確認は完璧にはできていないです。バグがあったらすみません。

このやり方が正しいのかどうか自分でも検証しきれていないので参考程度にご確認ください。

2022-07-11 00:31 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
丁寧にありがとうございます🙇‍♂️
うまく動かない原因は
`now = Time.zone.local(2022,7,9,12,0)` ここだけを変更しているようですが、他の箇所で使っている `Time zone.today` が変わってないためかと思います。 Time.zone.todayはDateクラスなので、試す際には Date.new()を使って変更してみると良いと思います。（なので、バグではないと思っています）

処理の複雑さは、ある程度仕方ないと思いますが、書いていただいたコードも見てみます。

2022-07-11 01:23 UTC, kazumi3858 commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@masanarih0ri さん

ご返信ありがとうございます！
なるほど・・・
たしかに一部のコードだけ触って確かめていたので私の間違いでした。
すみません🙇‍♂️🙏

ちなみに全くコードを変更しない状態でも正しく表示されなかったりします。
例えば今日は第2月曜なので、第2月曜を設定しても「本日開催」にならないようです。毎週月曜に設定すると正しく動きました。
![image](https://user-images.githubusercontent.com/97820517/178171549-ebd75fce-5f59-4746-99e5-87d4e6e66179.png)

2022-07-11 01:37 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
あ、おそらくそれは `possible_date >= Time.zone.today` となるべきところがそうなってないからですね。修正しました！🙇‍♂️

2022-07-11 03:02 UTC, kazumi3858 commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@masanarih0ri さん

修正ありがとうございます🙏
日付は本日のものになったのですが、「本日開催」が表示されていないようです。

![image](https://user-images.githubusercontent.com/97820517/178180807-512d6f35-3bfc-4d4f-afa7-486ce79a26e6.png)

2022-07-11 13:53 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@kazumi3858 
一旦既存のコードを生かしつつ、本日開催と表示もされるように対応しました！

2022-07-11 14:40 UTC, kazumi3858 commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@masanarih0ri さん

ご対応ありがとうございます！
取り急ぎ動作確認だけしましたが`第5 金 土 日`を設定するとエラーになってしまうようです🤔

2022-07-11 23:58 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
んー...これ面倒なこと多いですね😅
第5の場合計算の中で使っているdateが33とかの値になるのが原因ですね。
そもそも、第5火曜で繰り返す定期イベントなんて誰が立てるんだろう...と思うので、第4までの選択肢にできないか、町田さんにも聞いてみます。第5の時のエラー回避を考えるのは、いまのロジックでは難しそうなので。。

2022-07-13 00:29 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    canditates.compact.select { |canditate| canditate > Time.zone.today }.sort
@kazumi3858 
第5を削った形で実装と確認をしました。レビューできる形になったかと思いますので、再度ご確認をお願いいたします！

2022-07-13 05:03 UTC, kazumi3858 reviewed
@masanarih0ri さん

修正ありがとうございました😄
表示エラー等はなくなったように思います✨

コードレビューしましたのでご確認をお願いいたします。

2022-07-14 00:29 UTC, masanarih0ri commented on test/decorators/regular_event_decorator_test.rb
> +    assert_equal 5, @regular_event.calc_week_of_month(Date.new(2022, 6, 29))
削除しました！

2022-07-14 00:30 UTC, masanarih0ri commented on test/fixtures/regular_event_repeat_rules.yml
> +<% end %>
修正しました！

2022-07-14 00:35 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    is_the_day_of_the_event = regular_event_repeat_rules.map do |repeat_rule|
ここの変数名、難しいですよね🤔
event_dayの方がシンプルで良さそうなのでそちらで修正しました。

2022-07-14 01:15 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +  end
なるほど！ありがとうございます。一旦検証したんですが、2023年の1月頭の数日でエラーになったり、動きがおかしいのを発見しました。ただ、それは `calc_week_of_month` ではなく、`possible_next_event_dates` にバグがあるような気がするので、ちょっと夜に調べてみます。

2022-07-14 04:23 UTC, kazumi3858 commented on app/decorators/regular_event_decorator.rb
> +  end
@masanarih0ri さん

私のほうではエラー確認できませんでした😶

この部分を
```
0.days.ago.next_occurring(:sunday).to_date
```
こう変更し忘れて検証したとかではないですか？
```
Time.zone.local(2023,1,1,0,0).next_occurring(:sunday).to_date
```

2022-07-15 12:56 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +  end
仕事の開発が忙しく、こちら見れてませんでした🙇‍♂️
あー、確かにそうですね。修正したらうまく動くようになりました。お手隙でレビューお願いいたします。

2022-07-15 14:28 UTC, kazumi3858 approved these changes
@masanarih0ri さん

修正いただきありがとうございました😊✨
私からの確認はOKでございます。
大がかりな実装お疲れ様でした！

2022-07-16 01:14 UTC, masanarih0ri commented
@kazumi3858 
丁寧なレビューありがとうございました！

@komagata 
チームメンバーのレビューが通りましたので、レビューをお願いいたします。

また、レビューが通った後、細かいデザインを @machida さんにしていただく必要があるので、アサインを追加しました。

2022-07-17 16:29 UTC, komagata requested changes

2022-07-17 16:29 UTC, komagata commented on app/decorators/regular_event_decorator.rb
> +    now = Time.zone.now
```suggestion
    now = Time.current
```

2022-07-17 16:29 UTC, komagata commented on app/decorators/regular_event_decorator.rb
> +  def event_day?
こういう（他のメソッドも）ある程度のロジックはモデルに実装するのが良さそうです。
decoratorは本当に見た目の部分だけって感じがいいと思います。

2022-07-17 16:30 UTC, komagata commented
@masanarih0ri  ページ構造やHTMLは変わらないと思うのでもう @machida さんにデザインは依頼しちゃって大丈夫です〜

2022-07-18 08:11 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    now = Time.zone.now
こちら修正しました👍

2022-07-18 09:59 UTC, masanarih0ri commented
@machida 
定期イベントの開催曜日を設定するセレクトボックスのデザインの対応していただいて大丈夫です！
`regular-event-repeat-rule` 
`regular-event-repeat-rule__frequency`
`regular-event-repeat-rule__day-of-the-week`
のクラスを消すとテストが落ちるので、消さないようにお願いいたします。

2022-07-18 10:00 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +  def event_day?
@komagata 
表示に使っている2つのメソッド以外はmodelに移して、modelに移したメソッドのテストもmodelのテストに移しました。

2022-07-20 06:06 UTC, machida commented
デザイン了解ですー

2022-07-22 03:16 UTC, masanarih0ri commented
@komagata 
こちらお手隙でレビューをお願いいたします！

2022-07-22 04:03 UTC, komagata commented on test/system/regular_events_test.rb
> +      first('.regular-event-repeat-rule').all('.regular-event-repeat-rule__frequency select')[0].select('毎週')
all, [0]の代わりにfirst使ったりできるかも？

2022-07-23 01:04 UTC, masanarih0ri commented on app/decorators/regular_event_decorator.rb
> +    "次回の開催日は #{l next_event_date} です"
修正しました！

2022-07-23 01:14 UTC, masanarih0ri commented on test/system/regular_events_test.rb
> +      first('.regular-event-repeat-rule').all('.regular-event-repeat-rule__frequency select')[0].select('毎週')
こちらもfirstを使った形に修正しています。

2022-07-23 08:59 UTC, masanarih0ri commented
@komagata 
修正しましたので再度お手隙でレビューをお願いいたします！

2022-07-26 08:40 UTC, masanarih0ri commented
@komagata すみません、こちらいかがでしょうか？👀

2022-07-26 08:52 UTC, komagata commented on app/models/regular_event.rb
> +    end
この辺りを使えば全パターンを列挙する必要がなくなるかもです〜

https://github.com/rails/rails/blob/7-0-stable/activesupport/lib/active_support/core_ext/date_and_time/calculations.rb#L8

2022-07-26 12:37 UTC, masanarih0ri commented on app/models/regular_event.rb
> +    end
@komagata 
修正してみましたのでお手隙でご確認をお願いいたします！

2022-07-30 00:47 UTC, masanarih0ri commented on app/models/regular_event.rb
> +    end
@komagata 
お忙しいところすみません。こちらいかがでしょうか？

https://github.com/fjordllc/bootcamp/pull/5039/files#diff-31c331c9b9d86b17440d821d112c31d80a6606050caa111f80e3e90a6ca9baa8R96　の内容に変更しました。

2022-08-01 13:13 UTC, komagata commented on test/decorators/regular_event_decorator_test.rb
> +  test 'holding_cycles' do
```suggestion
  test '#holding_cycles' do
```

modelやdecoratorなどメソッド名そのままのテストの場合はクラスメソッドかインスタンスメソッドがわかるようにこういう感じにしていただけるとありがたいです〜

（user_decoratorもこうなってはいないのですが、別Issueで対応したいと思います。）

2022-08-01 16:13 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-08-01 16:13 UTC, merged