ダッシュボードに表示されるWIP（Docs、日報、Q＆A、提出物）の日付をデータと紐づいた表示に変更
fjordllc/bootcamp pull request #5087
Opened 2022-06-27 14:03 UTC by ai-24

2022-06-27 14:39 UTC, ai-24 commented
@siso25 
お疲れ様です！

お手隙の際にこちらのレビューお願いできますでしょうか。
もしお忙しければ、他の方にレビュー依頼いたしますので遠慮なくおっしゃってください🙏

2022-07-05 13:25 UTC, ai-24 commented
@siso25 
お忙しい中レビューありがとうございました🙇‍♀️

@komagata 
チームメンバーのレビューが通りましたので、こちらのPRレビューお願いいたします！

2022-07-08 14:03 UTC, komagata requested changes

2022-07-08 14:03 UTC, komagata commented on app/views/users/pages/_wip_pages.html.slim
> +                time.a-meta datetime= page.updated_at
```suggestion
                time.a-meta(datetime="#{page.updated_at}")
```

ちょっとなぜ元の書き方で動いているかわからないですが、怖いので一般的なこちらの書き方がいいかもです〜。

2022-07-08 14:03 UTC, komagata commented on app/views/users/products/_wip_products.html.slim
> +                time.a-meta datetime= product.updated_at
```suggestion
                time.a-meta(datetime="#{product.updated_at}")
```

2022-07-08 14:03 UTC, komagata commented on app/views/users/questions/_wip_questions.html.slim
> +                time.a-meta datetime= question.updated_at
```suggestion
                time.a-meta(datetime="#{question.updated_at}")
```

2022-07-08 14:03 UTC, komagata commented on app/views/users/reports/_wip_reports.html.slim
> +                time.a-meta datetime= report.updated_at
```suggestion
                time.a-meta(datetime="#{report.updated_at}")
```

2022-07-10 12:40 UTC, ai-24 commented on app/views/users/pages/_wip_pages.html.slim
> +                time.a-meta datetime= page.updated_at
かしこまりました！
変更いたします！

因みにリリース済みのPRもこちらのコードで実装しているのですが、以前の修正もこのPR内でこちらの書き方に変更してしまっても問題ないでしょうか。
[自分の作成したWIPのお知らせとWIPのイベントの一覧をダッシュボードに表示できるようにした ](https://github.com/fjordllc/bootcamp/pull/4957/files)

2022-07-10 12:40 UTC, ai-24 commented
@komagata 
かしこまりました！
レビューありがとうございます。

一点関連Issueで質問させていただきました！

2022-07-10 14:45 UTC, ai-24 commented
@komagata 
ご指摘いただいたコードの修正とコンフリクトの解消、またmainをリベースしたことでこちらのPRで作成したテストが落ちるようになったので、その部分の修正も行いました。
再レビューよろしくお願いいたします。

2022-07-11 06:20 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-07-11 06:20 UTC, merged