未完了の提出物一覧ページのtitleタグを変更
fjordllc/bootcamp pull request #5156
Opened 2022-07-01 11:51 UTC by kei-kmj

## Issue

- #4665

## 概要

管理画面の企業一覧の企業名をリンクに置き換えました。
...

## 変更確認方法

1. ブランチ`feature/replace-company-name-to-link`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. ...

## 変更前

<img ...>

## 変更後

<img ...>

2022-07-01 12:30 UTC, kei-kmj commented
夕方はありがとうございました！レビューお願いします🙏

2022-07-02 02:53 UTC, isshi-hasegawa commented
@kei-kmj 
お疲れさまでした〜！
レビュー依頼おめでとうございます🎉
DescriptionのIssueは以下の番号に変更しておいてください〜

`#5102`

2022-07-02 03:04 UTC, isshi-hasegawa approved these changes
動作確認できました！
自分からは`Approve`させていただきます🎉

2022-07-02 13:56 UTC, kei-kmj commented
@isshi-hasegawa 
レビューありがとうございます！
issueのナンバーを#5102に修正しました。

>変更確認方法には
どんな権限を持つユーザーでログインするか
どのページにアクセスするか
まで記述しおくとより良い

確かに、レビューのし易さを考えると、必要なことですね。
教えていただいてありがとうございます。

@komagata 
レビューお願いします🙏

2022-07-04 05:08 UTC, komagata commented on app/views/products/unchecked/index.html.slim
> +- title '未完了の提出物'
これだとtitleタグだけでなく、ページ上に表示されているタイトルも変わってしまうかと思うんですが、Issue的にその辺はあってますかね？（ちょっと両方変わっていいのか僕もわからないので、わからなければ @machida さんに聞いてみていただけるとありがたいです〜）

2022-07-05 02:09 UTC, kei-kmj commented on app/views/products/unchecked/index.html.slim
> +- title '未完了の提出物'
@komagata 
仕様の確認が甘かったです。申し訳ありません。
machidaさんに確認したところ、ページ上のタイトルは変えないということだったので、修正いたしました。

このまま@komagata にレビューをお願いしていいのでしょうか？もう一度チームメンバーにレビューを依頼してからにすべきでしょうか？

2022-07-05 02:32 UTC, kei-kmj commented on app/views/products/unchecked/index.html.slim
> +- title '未完了の提出物'
あ、テストが落ちていました。すみません、確認します

2022-07-05 11:05 UTC, machida commented on app/views/products/unchecked/index.html.slim
> +- title '未完了の提出物'
@kei-kmj チームメンバーレビューは終わってるので大丈夫ですー

2022-07-08 14:00 UTC, komagata requested changes

2022-07-08 14:00 UTC, komagata commented on app/views/products/unchecked/index.html.slim
> +        = '提出物'
```suggestion
        | 提出物
```

rubyの式ではなくただの文字列でしたらこちらの方がいいかもです〜

2022-07-10 02:26 UTC, kei-kmj commented on app/views/products/unchecked/index.html.slim
> +- title '未完了の提出物'
@komagata
テキスト表示部分にパイプを使用しました。
レビューお願いします。

2022-07-10 02:27 UTC, kei-kmj commented on app/views/products/unchecked/index.html.slim
> +        = '提出物'
@komagata
テキスト表示部分にパイプを使用しました。
レビューお願いします。

2022-07-11 06:12 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-07-11 06:15 UTC, merged

2022-07-14 12:04 UTC, kei-kmj commented
@komagata @machida
こちら、メンター向けのページのため、本番環境での動作確認をお願いできますでしょうか。

確認方法
- https://bootcamp.fjord.jp/products/unchecked にアクセス

確認内容
- titleタグが「未完了の提出物 | FJORD BOOT CAMP（フィヨルドブートキャンプ）」になっていること

よろしくお願いします🙏