企業一覧、企業個別の現役生の数字から卒業生分を除いた
fjordllc/bootcamp pull request #5201
Opened 2022-07-08 08:45 UTC by kei-kmj

## Issue

- #5163

## 概要

...

## 変更確認方法

1. ブランチ`feature/exclude-graduates-from-trainees-number`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. ...

## 変更前

<img ...>

## 変更後

<img ...>

2022-07-11 07:33 UTC, Nabegon commented
@kei-kmj さん、すみません！週末が忙しく時間が取れませんでした。今日中に確認します！

2022-07-11 19:18 UTC, Nabegon commented
@kei-kmj さん、お疲れ様です！動作とコードを確認し、問題ありませんでした🙆✨

気になった点を以下に記載しましたので、ご確認をお願いいたします🙏

1. テスト名につきまして
日本語で書かれていたのですが、他のテストを見ると英語で書かれています。こちらは統一した方が良いと思うので、英語でテスト名を書き直していただけますと幸いです🙏

2. コミットの粒度につきまして
コミットの粒度が細かく、どのように実装していったのかが分かって良かったです！ただ、`メソッドの前にスペースを挿入`、`pass rubocop`辺りは不要かと思いますので、コミットを整理していただきたいです🙏

以上になります。よろしくお願いします！🙇

2022-07-14 01:58 UTC, kei-kmj commented
@Nabegon 
修正しましたので確認お願いします
全く急がないので、他を優先して頂ければと思います😄
ハンブルクrubyの話、私も聞きたいです😍

2022-07-16 12:01 UTC, kei-kmj commented
@komagata 
お疲れ様です！
レビューをお願いいたします🙏

2022-07-17 16:40 UTC, komagata requested changes

2022-07-17 16:40 UTC, komagata commented on test/models/user_test.rb
> +  test 'number_of_students_matches' do
ユーザー数を全て固定でテストしてしまうと、テストユーザーが一人増えただけでテストが壊れるセンシティブなテストになってしまうので、卒業生が含まれているかどうかだけど確認するなど、もう少し余裕をもったテストにしていただけるとありがたいです〜。

2022-07-17 16:40 UTC, komagata commented on test/models/user_test.rb
> +    assert_equal 1, User.students_and_trainees.where(company_id: 1_022_975_240).size
fixtureで作ったデータのidはランダムであるという前提があるので、IDを数値で直接指定するのは避けたい感じです〜。

2022-07-18 01:27 UTC, kei-kmj commented on test/models/user_test.rb
> +  test 'number_of_students_matches' do
なるほど。シンプルに考えて、4つあったテストを2つにまとめてみました。

2022-07-18 01:28 UTC, kei-kmj commented on test/models/user_test.rb
> +    assert_equal 1, User.students_and_trainees.where(company_id: 1_022_975_240).size
こちらも見直してみました

2022-07-18 01:31 UTC, kei-kmj commented
@komagata 
テストコードを修正してみました。お手数をおかけいたしますが、確認お願いします。

2022-07-21 17:21 UTC, komagata commented
@kei-kmj merge commitができているようなので、mainとの差分だけになるように修正してみてください〜

2022-07-22 01:48 UTC, kei-kmj commented
@komagata
確認不足でした。失礼しました。
`revert`で余計なコミットを除いてみました。
`file changed`を見る限り大丈夫そうですが、これでOKでしょうか？
だめなようなら、ブランチを切りなおして新しいプルリクを作るしかないかなあ、と思っています。

2022-07-22 03:46 UTC, komagata commented
@kei-kmj revertはさらに不要なコミットが増えてしまうので基本的には使わないです。（リリース後に緊急ですぐ戻したい時などの特殊な時だけだと思います。）

resetやrebase -iなどを使って過去のコミットを修正してみてください〜

2022-07-22 07:56 UTC, kei-kmj commented
@komagata 
`rebase -i`でVScodeでコミットそのもの消せるんですね。衝撃でした。

コミットを消してみましたので、お手数ですが確認お願いします

2022-07-24 19:57 UTC, komagata commented
@kei-kmj rebaseやresetなど色々なコマンドでコミットを消したり取り消したり、くっつけたり、基本的にありとあらゆることがgitでできるようになっています。仕事で使うにはある程度自由に操れるようになっておく必要があるかもです〜

2022-07-24 19:57 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-07-24 19:57 UTC, merged