新規ユーザー登録時にメンターにメール通知およびサイト内通知するようにした
fjordllc/bootcamp pull request #5227
Opened 2022-07-14 13:53 UTC by SatoshiHaramura

## 関連Issue
- #5198

## 概要

## 環境準備

## 確認方法と確認内容

2022-07-23 11:13 UTC, SatoshiHaramura commented
@yocajii 
お疲れ様です。
レビューの依頼をさせて頂きたいです🙏
お手隙の際にお願い致します。

2022-07-26 05:56 UTC, yocajii reviewed
レビューにお時間をいただいていて申し訳ありません 💦
引き続き確認を進めているところですが、先に気付いた部分についてコメントさせていただきました。

2022-07-26 05:56 UTC, yocajii commented on test/fixtures/notifications.yml
> +notification_signed_up:
すぐ上にある卒業の通知がそうなってしまっているのですが、このフィクスチャはどのテストでも利用されていないので不要そうです。
Fixtureに書かれたデータはテスト実行前にすべてDBに投入されるため、不要なフィクスチャはシステムテストが重くなる一因になるようです。

参考情報として、テストのフィクスチャとは別になりますが `db/fixtures/notifications.yml` への追加は検討済みでしょうか？
https://github.com/fjordllc/bootcamp/blob/0b11a94e7c0c8485e907095f3b9b7512fad98808/db/fixtures/notifications.yml#L143-L149
こちらに追加しておくと開発環境で表示されるため、壊れた時に気付きやすくできるようです。
ただこちらについても私の意見としては、通知の表示ロジックがおかしくなっていないか確認する目的なら既存のフィクスチャで十分な気がするので、あえて入会の通知を追加する意義は薄いのかなという気はしています。

2022-07-27 02:28 UTC, yocajii reviewed
動作確認は問題ありませんでした 🙆‍♂️
先にコメントさせていただいた件に加えて、こうするとより良いかもと思った部分でいくつかコメントを入れさせていただきました。

新たな通知の作成ということでメソッドやテストの新規作成が多く、ご苦労もあったかと思います。
レビューさせていただく過程で通知の仕組みやVCRなど私の方でも調べてみましたが、認識が違っている点などありましたら教えていただけると嬉しいです 🙏

2022-07-27 02:28 UTC, yocajii commented on app/controllers/users_controller.rb
> +  end
特に理由がなければ`notify_to_chat` の上に移動して、`notify_to_xxxx` 系のメソッドを一箇所に集めておくと、より読みやすくなりそうに思いました。

2022-08-02 04:49 UTC, SatoshiHaramura commented on test/system/notification/signed_up_test.rb
> +    end
条件に該当するメンター全員に対して、サイト内通知が行われていることのテストとして書いていたので、該当する4ユーザーでも表示を確認しておりました。
たしかに、表示内容はどのユーザーでも同じ内容なので、1ユーザーのみの確認に修正してみます。

2022-08-02 04:51 UTC, SatoshiHaramura commented on test/fixtures/notifications.yml
> +notification_signed_up:
確認しますので、少々お待ち下さい🙏

2022-08-02 07:10 UTC, SatoshiHaramura commented on test/fixtures/notifications.yml
> +notification_signed_up:
> すぐ上にある卒業の通知がそうなってしまっているのですが、このフィクスチャはどのテストでも利用されていないので不要そうです。

このフィクスチャの利用箇所は、`test/mailers/notification_mailer_test.rb`の`test 'signed up'`の以下を実行する際に利用していると考えています。

```ruby
mailer = NotificationMailer.with(
  sender: user,
  receiver: mentor
).signed_up
```

上記が実行されると、`app/mailers/notification_mailer.rb`の`def signed_up`の以下で、通知データが必要になるので、先程のフィクスチャのデータを`@notification`に格納しています。

```ruby
@notification = @user.notifications.find_by(link: "/users/#{@sender.id}", kind: Notification.kinds[:signed_up])
```

2022-08-02 07:10 UTC, SatoshiHaramura commented on test/fixtures/notifications.yml
> +notification_signed_up:
> また、テストのフィクスチャとは別になりますが db/fixtures/notifications.yml への追加は検討済みの上で追加していない感じでしょうか？

一旦、検討済みでして、入会時の通知データが無くても、開発時に不便だと感じる場面は特に無いかぁと思いましたので、`db/fixtures/notifications.yml`へは追加していない状況となります。

2022-08-02 07:30 UTC, SatoshiHaramura commented
@yocajii 
お疲れ様です。
返信が遅くなりましたが、レビューして頂きありがとうございました！
様々な視点からのコメントを頂いて勉強になりました✨

一旦、頂いたコメント全てに対して、返信や修正致しましたので、再度レビューをお願い致します🙏

2022-08-03 01:04 UTC, yocajii commented on test/fixtures/notifications.yml
> +notification_signed_up:
確認不足で申し訳ありません🙇‍♂️
フィクスチャの利用個所について、ご説明いただきありがとうございます。NotificationMailerのテストの流れが理解できました🙏

また、dbのフィクスチャへの追加も検討済みの上でとのこと、失礼いたしました。こちらについても承知いたしました🙆‍♂️

2022-08-03 01:19 UTC, yocajii approved these changes
ご回答＆ご対応くださいまして、ありがとうございます🙏✨
改めて動作確認も行って問題ありませんでしたので、私からはApproveいたします。

2022-08-03 01:32 UTC, SatoshiHaramura commented
@yocajii 
再度レビューしてくださりありがとうございました✨

@komagata 
メンバーレビューが通りましたので、お手すきの際にレビューをお願い致します🙏

2022-08-04 07:54 UTC, komagata requested changes

2022-08-04 07:54 UTC, komagata commented on app/mailers/notification_mailer.rb
> +    subject = "[bootcamp] #{@sender.login_name}さんが新しく入会しました！"
最近下記のようにメールのprefixが`[FBC]`に変わったのでそれに合わせる修正をお願いします〜

https://github.com/fjordllc/bootcamp/blob/main/app/mailers/user_mailer.rb

2022-08-04 09:16 UTC, SatoshiHaramura commented on app/mailers/notification_mailer.rb
> +    subject = "[bootcamp] #{@sender.login_name}さんが新しく入会しました！"
@komagata 
承知致しました。
ここ(https://github.com/fjordllc/bootcamp/pull/5227/commits/fc781102978364e88f789c8abd17469764cf21af) で修正致しましたので、ご確認お願い致します🙏

2022-08-07 04:00 UTC, komagata commented on test/fixtures/notifications.yml
> +notification_signed_up:
@SatoshiHaramura 

> Fixtureに書かれたデータはテスト実行前にすべてDBに投入されるため、不要なフィクスチャはシステムテストが重くなる一因になるようです。

こちらで @yocajii さんがおっしゃってるようにできればそのテストだけのデータ追加で行けるとありがたいな〜と思います。

2022-08-08 11:40 UTC, SatoshiHaramura commented
@komagata 
お疲れ様です。
頂いていたコメントに対応致しましたので、再度レビューをお願い致します🙏

2022-08-10 06:59 UTC, komagata requested changes

2022-08-10 06:59 UTC, komagata commented on test/fixtures/notifications.yml
> +notification_signed_up:
@SatoshiHaramura 上記、いかがでしょうか〜？

2022-08-10 13:56 UTC, SatoshiHaramura commented on test/fixtures/notifications.yml
> +notification_signed_up:
@komagata 
テスト内でテストに必要なデータを作成する方がよい、という理解を致しました！
(yocajiiさんとのやりとりの中では、フィクスチャが要るorいらないという観点のみで考えてしまっておりました💦)

フィクスチャには追加せずに、テスト内でテストに必要なデータを作成するように修正致しましたので、ご確認お願い致します🙏

2022-08-12 08:14 UTC, komagata commented on test/system/notification/signed_up_test.rb
> +  VCR_OPTIONS = {
他のシステムテストと重複しているのでこういう感じにするのがいいかもです〜

https://github.com/fjordllc/bootcamp/blob/feature/comeback/test/application_system_test_case.rb#L31-L39

（これはまだマージされていないブランチのコードです）

2022-08-13 03:15 UTC, SatoshiHaramura commented on test/system/notification/signed_up_test.rb
> +  VCR_OPTIONS = {
@komagata 
承知しました！

ご提案頂いたテスト用のメソッドをここ(https://github.com/fjordllc/bootcamp/pull/5227/commits/4eba9a86e1acb7d5f5ba492f0bc929fa1b14438e) で追加して、テストコード内でそのメソッドを使用するように修正致しましたので、再度ご確認お願い致します🙏

2022-08-16 15:35 UTC, merged