プラクティス個別 > Q&Aの一覧 を Vue.js化した
fjordllc/bootcamp pull request #5255
Opened 2022-07-23 08:36 UTC by tomonariha

2022-07-24 00:27 UTC, tomonariha commented
@ai-24 さん、お疲れ様です。
ai-24さんにアサインされているこちらのissue #5020 に関わる変更がありますので、レビューをお願いしたいです。
特に急ぎませんので、お手隙の際によろしくお願いします🙏

2022-07-28 14:32 UTC, ai-24 reviewed
@tomonariha さん
お時間いただき大変申し訳ありませんでした。
動作確認し問題ありませんでした。
また、本来私のIssueで取り組むべきところまで、変更してくださっているかと思います。ありがとうございました🙇‍♀️

質問とコメントをさせていただきましたので、ご確認よろしくお願い致します🙏

2022-07-28 14:32 UTC, ai-24 commented on app/javascript/questions.vue
> +  name: 'Questions',
私の知識不足で申し訳ないのですが、こちらについて質問させてください🙏
nameはついていないものも見かけることがあります。私が調べた所だと、デバッグの時に使えるようにnameを指定するとありました。こちらのコードに関しては、上記に挙げた意図で使用されているのでしょうか。

もし認識間違いでしたらご教示いただけると助かります🙇‍♀️

2022-07-29 03:25 UTC, tomonariha commented on app/javascript/questions.vue
> +  name: 'Questions',
nameを付けた理由は、こちらの新マウント方法のやり方にそうするよう書いてあったからです。
https://github.com/fjordllc/bootcamp/wiki/Vue-Component%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E6%96%B9%E6%B3%95
私の方でも調べてみましたが、やはりデバッグツール用という情報しか出てきませんでした🤔

@komagata さん、新マウント方法でnameを付ける理由を教えていただけますか🙏

2022-07-29 03:30 UTC, tomonariha commented on app/javascript/packs/application.js
> +import Questions from '../questions.vue'
その通りだと思います🙏
`questions.vue`とそこで使うコンポーネント`question.vue`を`components`ディレクトリに移動しました。
[39c2044](https://github.com/fjordllc/bootcamp/pull/5255/commits/39c20447ba37510e5db269d81e28fa5b5e0ef2b9)

2022-07-29 07:20 UTC, ai-24 commented on app/javascript/questions.vue
> +  name: 'Questions',
頂いた資料の中で「型指定」の部分を見逃していました。
新マウント方法ではpropsでString型以外のものを渡す場合はnameが必須だということに気づきました！
ご確認ありがとうございました🙏

2022-07-30 19:07 UTC, komagata commented on app/javascript/questions.vue
> +  name: 'Questions',
@tomonariha 

> 新マウント方法でnameを付ける理由を教えていただけますか🙏

マウントのコードを見るとわかるかもですが、コンポーネントからこの内容を推測する方法が無いからです。
（もしかしたら実装方法によってはこれを不要にできるかもですが・・・）

2022-07-31 05:48 UTC, tomonariha commented on app/javascript/questions.vue
> +  name: 'Questions',
@komagata さん、ご回答ありがとうございます！
`VueMounter.js`の方でマウントするときに、登録しておいたコンポーネントをnameで指定して使うのが内容も推測できてわかりやすいから、という感じでしょうか🤔
この辺りの詳しい挙動は把握できていなかったので勉強になります🙏

2022-07-31 11:54 UTC, tomonariha commented
@ai-24 さん、お待たせしました！
コメントいただいたところ対応しましたので、ご確認お願いします🙏

2022-08-01 03:45 UTC, ai-24 approved these changes
@tomonariha さん
修正とnameのご確認ありがとうございます！
確認させていただきましたので、私からはApproveさせていただきます！

2022-08-01 08:12 UTC, komagata commented on app/javascript/questions.vue
> +  name: 'Questions',
@tomonariha いいえ、プログラム的に名前をつけてもらわないと、どのコンポーネントをマウントしていいのか判断できないからです。

（僕ができていないだけで何か方法があるかもしれませんが・・・）

2022-08-01 12:42 UTC, tomonariha commented on app/javascript/questions.vue
> +  name: 'Questions',
@komagataさん
>@tomonariha いいえ、プログラム的に名前をつけてもらわないと、どのコンポーネントをマウントしていいのか判断できないからです。

そうでしたか🙇‍♂️
[Rails + Vueの一般的な連携方法について](https://bootcamp.fjord.jp/questions/1291)のQ&Aでmhさんが提案されていた2番目の、htmlのdata-vue属性とコンポーネント名を紐づけてマウントする方法ですね。
この方法だとコンポーネント名が必須なので、name属性(コンポーネント名)を置いているという理解でいいでしょうか🙏

2022-08-01 13:27 UTC, komagata commented on app/javascript/questions.vue
> +  name: 'Questions',
@tomonariha ちょっと違うかもです。

> この方法だとコンポーネント名が必須なので、name属性(コンポーネント名)を置いているという理解でいいでしょうか🙏

必須というか、まず、その仕組みは僕が考えて作ってるだけなのでどんなやり方でも構わないです。

いろんなコンポーネントをimportしている中でどのコンポーネントをマウントするのかという部分で、どこかで名前を指定しなきゃいけないのですが、それだったらコンポーネントの名前を指定して使うのが一番わかりやすいと思ったからという感じでうす。

言葉で話すと抽象的になっちゃうのでコードを見た方が早いかもです。

https://github.com/fjordllc/bootcamp/blob/main/app/javascript/VueMounter.js#L9

2022-08-02 15:14 UTC, tomonariha commented on app/javascript/questions.vue
> +  name: 'Questions',
@komagata さん、詳しいご説明ありがとうございます🙏
考え方は教えていただいたので、あとはコードを見て勉強していきたいと思います🙇‍♂️

2022-08-02 15:16 UTC, tomonariha commented
@komagata さん、レビューよろしくお願いします🙏

2022-08-03 01:23 UTC, komagata commented on app/views/questions/index.html.slim
> +        <div data-vue='Questions' data-vue-empty-message="#{@questions_property.empty_message}" data-vue-selected-tag="#{params[:tag]}" />
ここがslimではなくhtmlになってるかもです〜

2022-08-03 06:57 UTC, ai-24 commented on app/javascript/questions.vue
> +  name: 'Questions',
@komagata さん @tomonariha さん
ご説明ありがとうございました🙇‍♀️
> development環境ではファイル名から判別できますが、production環境では動作時にはJSは1ファイルになっているのでファイル名がわからない）

この部分の知識が抜けていたので、かなり理解が進んだ気がします🤔
私も教えていただいた内容を元にコードを見て勉強しようと思います！
ありがとうございました！！

2022-08-03 07:12 UTC, tomonariha commented on app/views/questions/index.html.slim
> +        <div data-vue='Questions' data-vue-empty-message="#{@questions_property.empty_message}" data-vue-selected-tag="#{params[:tag]}" />
slimの書き方に修正しました。
[3ad7ea8](https://github.com/fjordllc/bootcamp/pull/5255/commits/3ad7ea8d97f78cb33cbff3e82c1150508b60aa73)

2022-08-03 07:14 UTC, tomonariha commented
@komagata さん、レビューありがとうございます！
コメントいただいた点修正しましたので、ご確認お願いします🙏

2022-08-04 08:01 UTC, komagata requested changes

2022-08-04 08:01 UTC, komagata commented on app/javascript/components/questions.vue
> +    practiceId: { type: String, default: null, required: false }
ID系はNumberが良いと思います〜。

2022-08-04 13:32 UTC, tomonariha commented on app/javascript/components/questions.vue
> +    practiceId: { type: String, default: null, required: false }
DBの方も確認してみましたが、ID系はintegerなんですね。
ID系のタイプをStringからNumberに修正しました。[6ce2a2b](https://github.com/fjordllc/bootcamp/pull/5255/commits/6ce2a2b2d709f02179fb23e288f02a8143dada80)

2022-08-04 13:36 UTC, tomonariha commented
@komagata さん、レビューありがとうございます！
コメントいただいたところを修正しましたので、ご確認お願いします🙏

2022-08-07 04:06 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-08-07 04:06 UTC, merged