質問の追加まで
fjordllc/bootcamp pull request #5370
Opened 2022-08-15 10:34 UTC by daiki0381

2022-08-16 07:25 UTC, daiki0381 commented
@machida 
お手数ですが、下記のリンクのデザインをお願いしたいです🙏

http://localhost:3000/survey_questions
http://localhost:3000/survey_questions/new
http://localhost:3000/survey_questions/{survey_question_id}/edit

2022-08-16 07:30 UTC, daiki0381 commented
@SatoshiHaramura 
お疲れ様です。
お手隙の際に、こちらのレビューをお願いしたいです🙏
ご不明な点やご都合が合わないようでしたら、お気軽にご連絡ください！

2022-08-18 04:59 UTC, SatoshiHaramura reviewed
@daiki0381 
お疲れさまです。
ボリュームが多いので、まだ全てを確認出来ていないのですが、取り急ぎテーブルとView周りを確認してコメントさせていただきましたので、ご確認お願い致します🙏

また、その他のコードも並行して確認していきますので、随時コメントさせていただこうと思います🙏

あと、`質問形式`の`段落`と`記述式`の違いが分からなかったのですが、何かご存知でしょうか?(もしかして、`質問形式`という文言ではなくて、`回答形式`という文言なのかなとも思ったりしました)

それにしても、アンケート機能は壮大ですね😅

2022-08-18 10:54 UTC, daiki0381 commented on app/views/survey_questions/_radio_button_choice_fields.html.slim
> +          | 選択した理由が必須の場合はチェック
こちら[8b7dda7](https://github.com/fjordllc/bootcamp/pull/5370/commits/8b7dda78aaf842371cdaa98fc5cadbc65dc6beba)で修正しました。

2022-08-18 10:54 UTC, daiki0381 commented on app/views/survey_questions/_check_box_choice_fields.slim
> +          | 選択した理由が必須の場合はチェック
こちら[8b7dda7](https://github.com/fjordllc/bootcamp/pull/5370/commits/8b7dda78aaf842371cdaa98fc5cadbc65dc6beba)で修正しました。

2022-08-18 11:56 UTC, daiki0381 commented
@machida 
お疲れ様です。仕様に関してご相談させてください🙏

【相談事項】

- 質問はメンターであれば誰でも編集可能でしょうか。それとも作成者のみ編集可能でしょうか。

2022-08-18 12:00 UTC, daiki0381 commented on app/views/survey_questions/index.html.slim
> +        = survey_question.question_title
こちら[eb39e37](https://github.com/fjordllc/bootcamp/pull/5370/commits/eb39e37d8159fd69c39d0fd3c48b52b8000fc03a)で修正しました。実施に関してはsurveyの範疇なので、今回のissueでは表示していないです。

2022-08-18 12:24 UTC, daiki0381 commented
@SatoshiHaramura 
> あと、質問形式の段落と記述式の違いが分からなかったのですが、何かご存知でしょうか?(もしかして、質問形式という文言ではなくて、回答形式という文言なのかなとも思ったりしました)

段落を選択した場合は、下記の画像のようなアンケートフォームの質問の回答部分が`text_area`になります。記述式を選択した場合は、回答部分が`input type="text"`になります。(アンケートフォームは[こちらのissue](https://github.com/fjordllc/bootcamp/issues/4586)で対応予定です。)

![image](https://user-images.githubusercontent.com/98577773/185392962-4754db70-3218-4a03-acf1-979d8a2d739f.png)

2022-08-18 23:01 UTC, SatoshiHaramura commented
@daiki0381 
> > あと、質問形式の段落と記述式の違いが分からなかったのですが、何かご存知でしょうか?(もしかして、質問形式という文言ではなくて、回答形式という文言なのかなとも思ったりしました)
> 
> 段落を選択した場合は、下記の画像のようなアンケートフォームの質問の回答部分が`text_area`になります。記述式を選択した場合は、回答部分が`input type="text"`になります。(アンケートフォームは[こちらのissue](https://github.com/fjordllc/bootcamp/issues/4586)で対応予定です。)

ご説明ありがとうございます🙇‍♂️
回答部分の入力欄が異なる、ということで理解しました！

2022-08-27 03:21 UTC, machida commented
@daiki0381 回答遅れてすいません🙇‍♂️メンターは誰でも編集可能でお願いします🙏

2022-09-01 12:37 UTC, daiki0381 commented on db/migrate/20220813103519_create_survey_questions.rb
> +      t.references :user, foreign_key: true
こちら[2d7bab4](https://github.com/fjordllc/bootcamp/pull/5370/commits/2d7bab44023e2af1274967e154c6557149f45b49)で修正しました。

2022-09-01 12:38 UTC, daiki0381 commented
@SatoshiHaramura 
レビューありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-09-02 07:00 UTC, SatoshiHaramura reviewed
@daiki0381 
お疲れさまです。
修正ありがとうございました！

1通りコードを見まして、理解が不足している点がありましたので質問させて頂きました🙏よろしくお願い致します。

2022-09-02 14:40 UTC, daiki0381 commented on app/views/survey_questions/index.html.slim
> +              = "作成: #{survey_question.created_at.strftime("%Y年%-m月%-d日 (#{%w[日 月 火 水 木 金 土][survey_question.created_at.wday]})")}"
ご提案ありがとうございます🙏 lメソッドを使用するとすっきり書けるんですね✨ 勉強になりました！こちら[9f7c3c0](https://github.com/fjordllc/bootcamp/pull/5370/commits/9f7c3c0ca2830b24db2b58bc20e2d56bdc704429)で修正しました！

2022-09-02 14:53 UTC, daiki0381 commented on app/controllers/survey_questions_controller.rb
> +    switch_initialization
こちら削除しても問題なく機能したため[51a05cd](https://github.com/fjordllc/bootcamp/pull/5370/commits/51a05cd30bdef750696dd16d28b4ad05ed0ea925)で削除しました。紛らわしくて申し訳ないです🙏

2022-09-02 15:15 UTC, daiki0381 commented on app/models/user.rb
> +  has_many :create_questions,
こちらは下記のように1:多の関係でuserの外部キーを2つ登録しているので、アソシエーションを2つ設定しています。外部キーは別名で登録しているので、class_name: 'SurveyQuestion'としています。またcreate_questionsという命名は分かりにくいと思うので、[39e541c](https://github.com/fjordllc/bootcamp/pull/5370/commits/39e541caf0a4758784d5b26f8e56324d5e56194a)で修正しました。

<img width="173" alt="スクリーンショット 2022-09-03 0 11 40" src="https://user-images.githubusercontent.com/98577773/188179963-e63443ca-618c-4379-9e99-3587013d93d6.png">

2022-09-02 15:15 UTC, daiki0381 commented
@SatoshiHaramura 
レビューありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-09-03 01:01 UTC, SatoshiHaramura commented on app/models/user.rb
> +  has_many :create_questions,
@daiki0381 
UserモデルとSurveyQuestionモデルの1:多の関連付けであれば、Userモデルには以下のような関連付けのみでよさそうな気もするのですが、いかがでしょうか??
`has_many :survey_questions, dependent: :destroy`

2022-09-03 01:03 UTC, SatoshiHaramura commented
@daiki0381 
UserモデルとSurveyQuestionモデルの1:多の関連付けについて、コメントさせて頂きましたのでご確認頂きたいです🙏

2022-09-03 06:43 UTC, daiki0381 commented on app/models/user.rb
> +  has_many :create_questions,
こちらですが外部キーを2つ登録しているので、`has_many :survey_questions, dependent: :destroy`のみの関連付けだと、どちらを取得すればいいのか分からず`Object doesn't support #inspect`と表示されてしまいます。

<img width="285" alt="スクリーンショット 2022-09-03 15 36 58" src="https://user-images.githubusercontent.com/98577773/188259123-e96fda82-2ab2-4baa-a158-059f20a0f344.png">

<img width="1100" alt="スクリーンショット 2022-09-03 15 35 48" src="https://user-images.githubusercontent.com/98577773/188259125-6af7f04e-6bf8-4cdf-bdf7-cb2ba160da10.png">

2022-09-03 06:44 UTC, daiki0381 commented
@SatoshiHaramura 
ありがとうございます🙇‍♂️ コメントしましたのでご確認お願いします。

2022-09-03 08:32 UTC, SatoshiHaramura commented on app/models/user.rb
> +  has_many :create_questions,
@daiki0381 
失礼致しました🙇‍♂️外部キーを2つ登録していると、こうなってしまうのですね😓


> またcreate_questionsという命名は分かりにくいと思うので、[39e541c](https://github.com/fjordllc/bootcamp/pull/5370/commits/39e541caf0a4758784d5b26f8e56324d5e56194a)で修正しました。

あと、名前を変更されたようですが、`user.creators`はユーザーの作成者、`user.updaters`はユーザーの更新者と訳さると思います。ただ、実態はアンケート質問なので、誤認しやすいなと思いました。
何か適切な命名があればなぁと思いましたがいかがでしょうか。

2022-09-03 08:34 UTC, SatoshiHaramura commented
@daiki0381 
ご説明ありがとうございました！理解ができました！
追加で、名前の命名についてコメントさせて頂きましたので、ご確認お願い致します🙏

2022-09-03 09:14 UTC, daiki0381 commented on app/models/user.rb
> +  has_many :create_questions,
> あと、名前を変更されたようですが、user.creatorsはユーザーの作成者、user.updatersはユーザーの更新者と訳さると思います。ただ、実態はアンケート質問なので、誤認しやすいなと思いました。

その通りですね💦 こちら[a5ee7fe](https://github.com/fjordllc/bootcamp/pull/5370/commits/a5ee7fe1903df4f0f532df57d606b291994da539)で修正しました！

2022-09-03 09:30 UTC, daiki0381 commented
@SatoshiHaramura 
ありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-09-04 13:13 UTC, SatoshiHaramura reviewed
@daiki0381 
お疲れさまです。
テストについてコメントさせて頂きましたので、ご確認お願い致します🙏

2022-09-05 06:43 UTC, daiki0381 commented on test/system/survey_questions_test.rb
> +class SurveyQuestionsTest < ApplicationSystemTestCase
こちら[98caef4](https://github.com/fjordllc/bootcamp/pull/5370/commits/98caef4ab8be2641d4fdd96a3d0472c73408ffa1)で修正しました。

2022-09-05 06:58 UTC, daiki0381 commented
@SatoshiHaramura ありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-09-05 12:37 UTC, SatoshiHaramura approved these changes
@daiki0381 
ご対応ありがとうございました！
動作とコードを確認して大丈夫そうだと思いましたのでApproveさせて頂きます🙆‍♂️

大規模な機能を実装されて、シンプルにすごいなぁと思いました😄
テーブルの設計やJSでの表示/非表示の方法など、多くのことを学ばせて頂きました😊

2022-09-05 13:36 UTC, daiki0381 commented
@SatoshiHaramura こちらこそご丁寧にレビューして頂きありがとうございました🙇‍♂️

2022-09-05 14:21 UTC, machida commented
@daiki0381 デザイン了解ですー
本番に反映するか、こちら次回MTGで話し合いたいと思いますー

2022-09-05 14:32 UTC, daiki0381 commented
@machida ありがとうございます🙇‍♂️ 承知しました！

2022-09-28 07:18 UTC, machida commented
@daiki0381 おまたせしました🙇‍♂️ デザインを入れましたー

@komagata レビューお願いします🙏

2022-09-28 07:19 UTC, machida commented
@komagata 
アンケートページへのリンクは本番では表示されないようにしてるので、レビュー後このブランチはマージして大丈夫ですー

2022-09-28 11:38 UTC, daiki0381 commented
@machida ありがとうございます🙏

2022-09-29 19:42 UTC, komagata requested changes

2022-09-29 19:42 UTC, komagata commented on db/migrate/20220813103519_create_survey_questions.rb
> +      t.string :question_title
survery_questionsのquestion_titleだと冗長なのでtitleでいいかも？と思いました〜。

2022-09-30 06:30 UTC, daiki0381 commented on db/migrate/20220813103519_create_survey_questions.rb
> +      t.string :question_title
こちら[aa4c506](https://github.com/fjordllc/bootcamp/pull/5370/commits/aa4c5068d1c7c200b3bb7cfc5d0b3f8b5fc47cc3)で修正しました。

2022-09-30 06:31 UTC, daiki0381 commented
@komagata ありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-10-02 09:49 UTC, komagata requested changes

2022-10-02 09:49 UTC, komagata commented on db/schema.rb
> +    t.text "description_of_reason_for_choice"
両方とも冗長にならないように`title_of_reason` `description_of_reason`でいいかもと思いました〜。

2022-10-02 09:49 UTC, komagata commented on db/schema.rb
> +    t.string "end_of_scale"
日本語をそのまま直訳するのは避けて、極力端的な英単語で表せるといいと思います。

〜scaleの持っているstartとendだったらscaleのことだというのは自明なので省略していいように思います。

ただ、endはrubyの予約後なので別の表現が良さそうです。

2022-10-02 09:49 UTC, komagata commented on db/schema.rb
> +    t.bigint "updater_id"
更新者は複数になると思うのですが、その辺りはどうなっていますでしょうか。

@machida
僕は上記にちゃんと対応させると複雑になるので更新者はなくてもいいように思うのですがいかがでしょうか？

2022-10-12 04:13 UTC, machida commented on db/schema.rb
> +    t.bigint "updater_id"
@komagata 了解ですー、では無しにしたいと思いますー

@daiki0381 無しに変更お願いします🙇‍♂️

2022-10-12 14:36 UTC, daiki0381 commented on db/schema.rb
> +    t.text "description_of_reason_for_choice"
こちら[574ba51](https://github.com/fjordllc/bootcamp/pull/5370/commits/574ba51a1be617998864e25e52ee5b401c8e134a)で修正しました！

2022-10-12 14:36 UTC, daiki0381 commented on db/schema.rb
> +    t.string "end_of_scale"
こちら[1be4021](https://github.com/fjordllc/bootcamp/pull/5370/commits/1be4021f17b54c48e58c40df86ff937e83a9839d)で修正しました！

2022-10-12 15:30 UTC, daiki0381 commented
@komagata 
レビューありがとうございます。ご指摘頂いた箇所を修正しましたので、再度レビューお願いします。

2022-10-17 08:58 UTC, komagata reviewed
同じコミットメッセージが続いている部分があるので、このPRのコミットを見直して整理してみてください〜

2022-10-18 03:03 UTC, daiki0381 commented
@komagata ありがとうございます🙇‍♂️ コミットメッセージを変更したので、再度レビューお願いします🙏

2022-10-21 15:26 UTC, komagata commented on app/models/check_box_choice.rb
> +    %i[choices].each do |att|
`att`ってなんの略でしょう？

2022-10-21 15:26 UTC, komagata commented on test/system/survey_questions_test.rb
> +    assert_text "作成: #{Time.zone.today.strftime("%Y年%m月%d日(#{%w[日 月 火 水 木 金 土][Time.zone.today.wday]})")}"
```suggestion
    assert_text "作成: #{Time.current.strftime("%Y年%m月%d日(#{%w[日 月 火 水 木 金 土][Time.current.wday]})")}"
```

でいいかもです〜

2022-10-21 15:26 UTC, komagata commented on test/fixtures/survey_questions.yml
> +  created_at: <%= Time.zone.today %>
```suggestion
  created_at: <%= Time.current %>
```

2022-10-23 07:02 UTC, daiki0381 commented on test/fixtures/survey_questions.yml
> +  created_at: <%= Time.zone.today %>
こちら[25f76fd](https://github.com/fjordllc/bootcamp/pull/5370/commits/25f76fd727927af2551fd036b2383522356f1f2e)で修正しました。

2022-10-23 07:02 UTC, daiki0381 commented on test/system/survey_questions_test.rb
> +    assert_text "作成: #{Time.zone.today.strftime("%Y年%m月%d日(#{%w[日 月 火 水 木 金 土][Time.zone.today.wday]})")}"
こちら[25f76fd](https://github.com/fjordllc/bootcamp/pull/5370/commits/25f76fd727927af2551fd036b2383522356f1f2e)で修正しました。

2022-10-23 07:03 UTC, daiki0381 commented on app/models/check_box_choice.rb
> +    %i[choices].each do |att|
こちら属性(カラム)を表現していたのですが、分かりにくいので[e91e8b6](https://github.com/fjordllc/bootcamp/pull/5370/commits/e91e8b69b6d8a427b480fcc943f1dfaf09c0b941)で修正しました。

2022-10-23 07:10 UTC, daiki0381 commented
@komagata  ありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-10-24 22:38 UTC, komagata commented on app/models/check_box.rb
> +  def normalize_blank_values
引数がない、破壊的なメソッドなのでメソッド名の末尾に`!`をつけると破壊的メソッドであることがわかりやすいかもです〜

2022-10-24 22:38 UTC, komagata commented on app/models/check_box.rb
> +  def normalize_blank_values
いろんなモデルで重複してるので、共通化できるといいな〜と思います。

2022-10-25 05:09 UTC, daiki0381 commented on app/models/check_box.rb
> +  def normalize_blank_values
[d6a69cb](https://github.com/fjordllc/bootcamp/pull/5370/commits/d6a69cbcf0935f916e51512aabb0bccc6f9aed69)で修正しました！

2022-10-25 05:17 UTC, daiki0381 commented
@komagata レビューありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-10-25 18:04 UTC, komagata commented on app/models/check_box.rb
> +  end
mix-inやmodelのconcernを使うと綺麗に共通化できるかもです〜

[Rails をはじめよう \- Railsガイド](https://railsguides.jp/getting_started.html#concern%E3%82%92%E4%BD%BF%E3%81%86)

2022-10-25 18:04 UTC, komagata commented on app/models/check_box.rb
> +  end
すみません、ちょっと理解できてないのですがそもそもなんでnilを入れる必要があるんでしょうか？

2022-10-26 03:04 UTC, daiki0381 commented on app/models/check_box.rb
> +  end
@komagata 
編集時にチェックボックス or ラジオボタン or 均等目盛をクリックして、タイトル以外の必須項目を入力していない状態で保存してもバリデーションが効かないので、保存前に空文字の場合はnilを入れることでバリデーションが効くようにしました。

2022-10-26 05:13 UTC, daiki0381 commented on app/models/check_box.rb
> +  end
@komagata [98350fa](https://github.com/fjordllc/bootcamp/pull/5370/commits/98350fa125f86e94abafa9abd705954350324dd5)で修正しました！

2022-10-26 05:13 UTC, daiki0381 commented
@komagata レビューありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-11-02 05:55 UTC, komagata commented on app/models/check_box.rb
> +  end
@daiki0381 

> タイトル以外の必須項目を入力していない状態で保存してもバリデーションが効かないので、

これはなぜでしょう？
ちょっと僕も調べてみます〜。

2022-11-02 05:58 UTC, komagata commented on app/models/check_box.rb
> +  end
@daiki0381 

> 編集時にチェックボックス or ラジオボタン or 均等目盛をクリックして、タイトル以外の必須項目を入力していない状態で保存してもバリデーションが効かないので、

すみません、この状態を手元で再現しようとしています。
ちょっと上記だけだとよくわからないので、再現手順をもう少し詳細に教えていただいてもよろしいでしょうか。

2022-11-02 06:38 UTC, daiki0381 commented on app/models/check_box.rb
> +  end
@komagata 
> これはなぜでしょう？
核心をつく原因には辿り着けなかったのですが、編集時は空文字列の場合バリデーションが効いていませんでした。(nilにすればバリデーションが効いたので、保存前に空文字列をnilに変更することでバリデーションを効くようにしました)

> ちょっと上記だけだとよくわからないので、再現手順をもう少し詳細に教えていただいてもよろしいでしょうか。

下記の2パターンの再現方法があります。

【パターン1】

①今回追加したモデルのbefore_saveをコメントアウトする。
②段落 or 記述式でアンケートを作成する。
③編集画面で均等目盛を選択して、目盛ラベル、選択した理由タイトルを入力せずに保存するをクリックしてもバリデーションはかからず保存できてしまう。(段落 or 記述式でアンケートを作成した場合、均等目盛のみ再現する)

【パターン2】
①今回追加したモデルのbefore_saveをコメントアウトする。
②均等目盛 or ラジオボタン or 均等目盛でアンケートを作成する。
③編集画面でラジオボタンを選択して、選択肢、選択した理由タイトルを入力せずに保存するをクリックしてもバリデーションはかからず保存できてしまう。(均等目盛 or ラジオボタン or 均等目盛でアンケートを作成した場合、ラジオボタン・チェックボックス・均等目盛全て再現する)

2022-11-05 06:49 UTC, machida commented
@komagata こちらレビューが通ったらマージをお願いします🙏

2022-11-07 01:23 UTC, komagata commented
@machida こちら個別の箇所で議論が続いている感じです〜。レビュー完了までもうしばらく時間がかかりそうです〜

2022-11-07 01:23 UTC, machida commented
@komagata 了解ですー

2022-11-07 01:29 UTC, komagata commented on app/models/check_box.rb
> +  end
@daiki0381 再現方法ありがとうございます〜！

2022-11-07 01:34 UTC, komagata commented on app/models/check_box.rb
> +  end
@daiki0381 後から直すのは大変なのでできれば、もう少しだけ調べてみていただけるとありがたいです。
編集時の入力系のtagのname要素がどうなっているか、POSTした時のcontrollerが受け取るparamがどうなっているのかを調べてみるともう少しわかるかもです〜

2022-11-10 12:16 UTC, daiki0381 commented on app/models/check_box.rb
> +  end
@komagata 
ありがとうございます。こちら調査したところaccept_nested_attributes_forを使用する際にvalidate_associatedを追加しないとupdate時に子レコードのvalidationが走らないのが原因でした。

https://www.tom08.net/2018-11-13-170133/

2022-11-10 12:22 UTC, daiki0381 commented
@komagata レビューありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しましたので、再度レビューお願いします🙏

2022-11-11 06:44 UTC, komagata commented on app/models/check_box.rb
> +  end
@daiki0381 

おお、かなりコードがスッキリしましたね！

2022-11-11 06:44 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-11-11 06:44 UTC, merged

2022-11-11 06:57 UTC, daiki0381 commented
@komagata ありがとうございます！