Feature/hide user icon from recent reports list in products show and talks show
fjordllc/bootcamp pull request #5399
Opened 2022-08-22 20:06 UTC by taka110-IT

2022-08-23 17:19 UTC, taka110-IT commented
@ai-24 
お疲れ様です。レビューをお願いできますでしょうか。
お手すきの際で結構ですのでよろしくお願いします🙇🏻‍♂️

2022-08-24 14:30 UTC, taka110-IT commented
@machida 
レビューと並行になってしまいますが、ミーティングで指示があった通りデザインをお願いいたします。

2022-08-26 02:20 UTC, machida commented
@taka110-IT デザイン調整しましたー

2022-08-26 02:34 UTC, ai-24 approved these changes
@taka110-IT さん
レビュー依頼ありがとうございます。
コードと動作の確認を行い、問題ありませんでした😊
私の方からはApproveさせていただきます！

2022-08-27 09:08 UTC, taka110-IT commented
@machida 
デザイン調整ありがとうございました。
ブログのサマリーを削除されたようなので、関連のテストを修正しております。

@ai-24 
確認いただきありがとうございました😊

@komagata 
チームリーダーのレビューをお願いします。

2022-08-27 15:30 UTC, komagata reviewed
@taka110-IT conflictの修正をお願いします〜。

2022-08-28 19:58 UTC, taka110-IT commented
@komagata 
conflictを修正しました。よろしくお願いします。

2022-08-29 16:26 UTC, komagata requested changes
@taka110-IT さんのコミットにつくアイコンがおかしいようです。
おそらくgitクライアントの設定（メールアドレスなど）が間違っていて、サーバー上の設定と一致しないためだと思います。

修正をお願いします〜。

2022-08-29 16:51 UTC, taka110-IT commented
@komagata 
ありがとうございます。どこかの時点で変更してしまったようでした。修正しました。

2022-08-29 19:27 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-08-29 19:27 UTC, merged

2022-08-29 22:00 UTC, taka110-IT commented
@komagata 
確認ありがとうございました😊