ユーザー情報ページにRSSのURLを入力できるように修正
fjordllc/bootcamp pull request #5418
Opened 2022-08-24 12:37 UTC by siso25

2022-09-03 05:18 UTC, siso25 commented
@yuma-matsui 
お疲れ様です。
こちらのpull requestについて、ご都合の良いタイミングでレビューをお願い致します。
お忙しいようでしたら他の方にお願いしますので、ご連絡いただければ幸いです。🙇‍♂️

2022-09-03 10:42 UTC, yuma-matsui commented
@siso25 
レビュー依頼ありがとうございます！
明日中には対応させていただきます〜

取り急ぎ返信まで。

2022-09-04 01:18 UTC, yuma-matsui commented
@siso25 
確認できました！
LGTMです🙆‍♂️

一点だけ少し細かいですが、今回DBの変更があるので「確認方法」に`bin/setup`を追加したほうが良いと思ったので、追加よろしくお願いします🙏

2022-09-04 01:18 UTC, yuma-matsui approved these changes

2022-09-11 06:57 UTC, siso25 commented
@yuma-matsui 
お忙しいところレビューいただきましてありがとうございました！🙇‍♂️

@machida 
こちら、デザインの確認をお願いできますでしょうか。
お手数ですが、よろしくお願い致します。

2022-09-21 08:31 UTC, machida commented
@siso25 デザイン入れましたー 遅くなってすいません🙇‍♂️

@komagata レビューお願いしますー

2022-09-22 06:03 UTC, komagata requested changes
URLでないものを入力する人がいて、クロールするときに余計なエラーが出そうなので、URLであることを確認するValidationが欲しいなと思いました〜。

2022-10-16 08:07 UTC, siso25 commented
@komagata 
遅くなりまして申し訳ありません。
フィードURLのvalidationを追加しましたので、ご確認をお願いいたします。

2022-10-17 09:19 UTC, komagata commented on app/models/user.rb
> +              message: 'は「http」または「https」から始まるURL形式で入力してください'
このvalidationだとhttpかhttpsから始まっているだけではなく、他の条件がいっぱいあるように思います。
それにあったエラーメッセージにするのがいいと思います。

2022-11-16 12:11 UTC, siso25 commented
@komagata
お疲れ様です。
エラーメッセージの修正を行いましたので、お手数ですがご確認をお願いいたします。

2022-11-18 05:37 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-11-18 05:37 UTC, merged

2022-11-26 08:14 UTC, siso25 commented
@komagata 
ありがとうございます！