Twitterに投稿しても画像が出ない
fjordllc/bootcamp pull request #5434
Opened 2022-08-26 12:02 UTC by lanactindi

2022-08-27 20:12 UTC, machida commented
@machida すみませんが、おそらくtwitter card validatorが動かないと思います。
<img width="1137" alt="Screen Shot 0004-08-26 at 21 03 33" src="https://user-images.githubusercontent.com/94335407/186899404-5f1f7470-cc76-4eec-9228-41cff34c37fc.png">
エラーがなくてもプレビューが表示されないです。
参考: https://twittercommunity.com/t/card-validator-preview-removal/175006
しかし、twitter本番で試してもいいですのでこのプレビューはいかがでしょうか？
<img width="614" alt="Screen Shot 0004-08-26 at 21 06 09" src="https://user-images.githubusercontent.com/94335407/186899811-f031f839-1dc7-4daa-bb53-c182edb77d95.png">
og:title、twitter:title、twitter:text:titleの価値は何がいいのでしょうか？
私は全て「FJORD BOOT CAMP（フィヨルドブートキャンプ）」を設定しましたが、不安なので確認していただきたいです。

2022-08-27 20:14 UTC, machida commented
@lanactindi

本番で試してOKです。

> og:title、twitter:title、twitter:text:title

それぞれのページに `title` が設定されているので、それを og:title、twitter:title、twitter:text:title にも適用したいです。
その場合、何か実装上で問題はありますでしょうか？

2022-08-28 11:23 UTC, lanactindi commented
> 

すみません、言いたいことは'FJORD BOOT CAMP（フィヨルドブートキャンプ）'という価値はいかがでしょうか？

2022-08-28 12:19 UTC, lanactindi commented
> @lanactindi
> 
> 本番で試してOKです。
> 
> > og:title、twitter:title、twitter:text:title
> 
> それぞれのページに `title` が設定されているので、それを og:title、twitter:title、twitter:text:title にも適用したいです。 その場合、何か実装上で問題はありますでしょうか？

すみません、言いたいことはこのプレビューのタイトルはいかがでしょうか？
「FJORD BOOT CAMP（フィヨルドブートキャンプ）」を設定しても大丈夫かどうかを確認していただきたいです。
<img width="622" alt="Screen Shot 0004-08-28 at 21 18 43" src="https://user-images.githubusercontent.com/94335407/187073849-4b188a9e-6a96-4921-926e-f03d1c0f1502.png">

2022-08-29 16:24 UTC, komagata commented
@lanactindi すみません、メンションを付けないと @machida が気付くことができないのでメンションをお願いします〜

2022-08-29 19:45 UTC, lanactindi commented
> @lanactindi
> 
> 本番で試してOKです。
> 
> > og:title、twitter:title、twitter:text:title
> 
> それぞれのページに `title` が設定されているので、それを og:title、twitter:title、twitter:text:title にも適用したいです。 その場合、何か実装上で問題はありますでしょうか？

@machida すみません、言いたいことはこのプレビューのタイトルはいかがでしょうか？
「FJORD BOOT CAMP（フィヨルドブートキャンプ）」を設定しても大丈夫かどうかを確認していただきたいです。
それを実装すると問題がないですが、確認していただきたいです。
<img width="622" alt="Screen Shot 0004-08-28 at 21 18 43" src="https://user-images.githubusercontent.com/94335407/187073849-4b188a9e-6a96-4921-926e-f03d1c0f1502.png">

2022-09-21 01:59 UTC, machida commented
@lanactindi 

<img width="510" alt="貼り付けた画像_2022_09_21_10_55" src="https://user-images.githubusercontent.com/168265/191396871-51bf8e45-819b-434f-b8bb-ef2ed4cc4e20.png">

今の変更だと、全ての title タグの文言が `FJORD BOOT CAMP（フィヨルドブートキャンプ）` になってしまいます。
title タグの文言は各ページそれぞれ違う文言が用意されています。
title タグの文言は各ページの view ファイルで定義されています。
なので、title タグの文言を上書きするのではなく、`:title` を使うようにしていただきたいです。
もし、`:title` が定義されていないページがあり、そのページでエラーが出る場合は、それを避けるために、`:title` のデフォルト値を用意してほしいです。

2022-10-04 06:42 UTC, lanactindi commented
@machida そうですね、defaultを設定したら全部壊れてしまいます。そのため、不具合はwelcomeページだけなのでwelcomeページのコードを修正しました。再度レビューお願いします。

2022-10-04 10:35 UTC, lanactindi commented
@machida 町田さん、こちらを対応できたので再度レビューお願いします。
default-meta-tagsに触らないで対応できました。

2022-10-05 02:21 UTC, machida approved these changes

2022-10-05 02:23 UTC, machida commented
@lanactindi ありがとうございますー こちら駒形さんにもレビューをお願いしたいと思います

@komagata レビューお願いします🙏

2022-10-05 02:30 UTC, lanactindi commented
> @lanactindi ありがとうございますー こちら駒形さんにもレビューをお願いしたいと思います
> 
> @komagata レビューお願いします🙏

ご確認ありがとうございました。

2022-10-06 18:36 UTC, komagata commented on app/views/welcome/index.html.slim
> +- set_meta_tags(site: 'FJORD BOOT CAMP（フィヨルドブートキャンプ）', og: { title: 'FJORD BOOT CAMP（フィヨルドブートキャンプ）' })
根本的に治すのであれば、ログインしてない人が見れるページを設定してる下記を修正するのがいいかもしれないと思いました。

https://github.com/fjordllc/bootcamp/blob/main/app/views/layouts/welcome.html.slim#L7

2022-10-07 11:25 UTC, lanactindi commented on app/views/welcome/index.html.slim
> +- set_meta_tags(site: 'FJORD BOOT CAMP（フィヨルドブートキャンプ）', og: { title: 'FJORD BOOT CAMP（フィヨルドブートキャンプ）' })
コメントありがとうございました。しかし、ログインしてない人が見れるページのタイトル値は一意なので一つずつ対応しました。

2022-10-07 12:09 UTC, lanactindi commented
@komagata 全てログインユーザーが見れるページを対応したので再度レビューお願いします。

2022-10-10 16:20 UTC, komagata commented
@lanactindi 

https://github.com/fjordllc/bootcamp/blob/main/app/views/layouts/welcome.html.slim#L7

ここを修正すれば、このlayoutを使ってる全てのページで一括設定できるので、そちらの方がいいと思います〜

2022-10-12 19:56 UTC, lanactindi commented
> @lanactindi
> 
> https://github.com/fjordllc/bootcamp/blob/main/app/views/layouts/welcome.html.slim#L7
> 
> ここを修正すれば、このlayoutを使ってる全てのページで一括設定できるので、そちらの方がいいと思います〜

set_meta_tagsを使ってはいけないということでしょうか。

2022-10-12 21:13 UTC, lanactindi commented
> @lanactindi
> 
> https://github.com/fjordllc/bootcamp/blob/main/app/views/layouts/welcome.html.slim#L7
> 
> ここを修正すれば、このlayoutを使ってる全てのページで一括設定できるので、そちらの方がいいと思います〜

コメントありがとうございました。修正したので再度レビューお願いします。

2022-10-17 08:12 UTC, komagata requested changes

2022-10-17 08:12 UTC, komagata commented on app/views/layouts/welcome.html.slim
> +    = display_meta_tags welcome_meta_tags
👍

2022-10-17 08:12 UTC, komagata commented on app/helpers/meta_tags_helper.rb
> +  def welcome_meta_tags
基本的にはOKですが、ハッシュの内容がほとんど同じなので、共通化できる部分は共通化したほうが良さそうです〜

2022-10-17 09:24 UTC, komagata commented on app/helpers/meta_tags_helper.rb
> +    welcome_meta_tags = default_meta_tags.dup
mergeを使った方が読みやすいかもです〜

2022-10-17 09:44 UTC, lanactindi commented
@komagata 駒形さん、コメントありがとうございました！
修正したので再度レビューお願いします。

2022-10-17 18:53 UTC, komagata commented on app/helpers/meta_tags_helper.rb
> +    welcome_meta_tags = default_meta_tags.dup
@lanactindi こちら変わっていないようですが、いかがでしょうか？

2022-10-17 23:28 UTC, lanactindi commented
@komagata 駒形さん、漏れてしまったすみませんでした。
修正したので再度レビューお願いします。

2022-10-18 19:38 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-10-18 19:39 UTC, komagata requested changes
ogpが間違っていた部分を確認するテストがあるといいと思います〜。

2022-10-18 20:40 UTC, lanactindi commented
@komagata 駒形さん、テストを追加させていただきました。
再度レビューお願いします。

2022-10-19 06:23 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-10-19 06:24 UTC, merged

2022-10-19 06:40 UTC, lanactindi commented
> 確認させて頂きました。OKです〜🙆‍♂️

ありがとうございました！