titleタグを[プラクティス名に関する日報]に変更
fjordllc/bootcamp pull request #5440
Opened 2022-08-27 14:48 UTC by choco0809

## Issue

- #5409

## 概要

プラクティス個別ページの「日報」遷移時のtitleタグを変更。

変更前：プラクティス名
変更後：プラクティス名に関する日報

## 変更確認方法

1. ブランチ`feature/change-title-tag-of-practices-reports`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. 一般ユーザーでログインする
4. http://localhost:3000/practices/315059988/reports にアクセスする

## 変更前
<img width="1431" alt="_development__OS_X_Mountain_Lionをクリーンインストールする___FBC" src="https://user-images.githubusercontent.com/99729409/187035335-0ea6493e-367f-4803-b600-4b5918cf5597.png">

## 変更後
<img width="1431" alt="_development__OS_X_Mountain_Lionをクリーンインストールするに関する日報___FBC" src="https://user-images.githubusercontent.com/99729409/187035264-a34d5c6b-2442-4658-8fd3-aabece9380d5.png">

2022-08-27 22:38 UTC, choco0809 commented
@ai-24 
水曜日からチーム開発に加わったchocoと申します！
お手数ですが、こちらのレビューをよろしくお願いします🙇‍♂️🙇‍♂️🙇‍♂️

2022-08-30 09:57 UTC, ai-24 approved these changes
@choco0809 さん
レビュー依頼ありがとうございます！
動作とコード確認出来ましたので、私からはApproveさせていただきます🙆‍♀️

2022-08-31 00:08 UTC, choco0809 commented
@ai-24 
お忙しいところ確認ありがとうございました🙇‍♂️🙇‍♂️🙇‍♂️

2022-08-31 00:09 UTC, choco0809 commented
@komagata 
お疲れ様です！
ai-24さんよりApprove頂きましたのでレビューよろしくお願い致します🙇‍♂️🙇‍♂️🙇‍♂️

2022-08-31 18:24 UTC, komagata requested changes
conflictの修正お願いします〜

2022-09-05 16:40 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-05 16:40 UTC, merged