アドバイザーでログインしたときに提出物にアクセスした際、全ての提出物一覧を表示
fjordllc/bootcamp pull request #5444
Opened 2022-08-28 10:03 UTC by shirotamaki

## Issue
 
 - #4651
 
 ## 概要
 
アドバイザーでログインしたときに提出物にアクセスをしたら、全ての提出物一覧が表示されてほしい。
 
 ## 変更確認方法
 
 1. ブランチ`feature/add-all-submissions-listed-on-the-adviser-page`をローカルに取り込む
 2. `bin/rails s`でローカル環境を立ち上げる
 3. ...
 
 ## 変更前
 
 <img ...>
 
 ## 変更後
 
 <img ...>

2022-08-31 03:18 UTC, shirotamaki commented
@keiz1213 
お疲れさまです！
先週からチーム開発へ参加しています。Nakamuraさんとご一緒でき嬉しいです！お手すきの際レビューいただけますと幸いです✍️
よろしくお願いします🙏

2022-08-31 11:16 UTC, keiz1213 approved these changes
@shirotamaki 
お疲れさまです！動作確認、コード共に問題ないと思いますので僕からはapproveさせていただきます！
こちらこそタマキさんとご一緒できて嬉しいです😄色々ご迷惑おかけするかと思いますがよろしくおねがいします🙌

2022-08-31 11:51 UTC, shirotamaki commented
@komagata
お疲れさまです！
チームメンバーよりApproveいただきました！レビューよろしくお願いします🙏

2022-08-31 18:29 UTC, komagata commented on app/views/products/_tabs.html.slim
> +      li.page-tabs__item.is-only-mentor
ここはどういう意図の追加でしょうか〜？

2022-08-31 23:49 UTC, shirotamaki commented on app/views/products/_tabs.html.slim
> +      li.page-tabs__item.is-only-mentor
レビューありがとうございます！
タグの表示を消す目的で`.is-only-mentor`クラスを実装しました！

- 実装前

![image](https://user-images.githubusercontent.com/65638955/187804019-2ed198fc-22af-493e-95f0-8fe9f77fa471.png)

- 実装後
![image](https://user-images.githubusercontent.com/65638955/187804074-f61e47c4-ba57-4e46-874a-6e73cbc28e4d.png)

2022-09-05 11:26 UTC, komagata requested changes

2022-09-05 11:26 UTC, komagata commented on app/views/products/_tabs.html.slim
> +      li.page-tabs__item.is-only-mentor
@shirotamaki CSSで非表示にしているだけだと内容は見れてしまいます。（HTMLのソースには表示されている）

ruby側で非表示にするようにお願いします。

確か、`.is-only-mentor`はメンターモードのボタンで表示を切り替えるために存在していたクラスだと思います〜（詳しく知りたい場合は @machida さんに聞いてみてください〜）

2022-09-06 12:56 UTC, shirotamaki commented
@komagata 
Ruby側で非表示にするプログラムへ変更しました！再レビューよろしくお願いします🙏

2022-09-09 22:06 UTC, komagata requested changes

2022-09-09 22:06 UTC, komagata commented on app/views/products/_tabs.html.slim
> +      - if current_user.admin? || current_user.mentor?
https://github.com/fjordllc/bootcamp/blob/main/app/controllers/concerns/authentication.rb#L25

こっちを使った方がいいかもです〜

2022-09-10 13:11 UTC, shirotamaki commented
@komagata 
修正してみました！再レビューお願いします🙏

2022-09-12 01:35 UTC, komagata commented
@shirotamaki 同じコミットメッセージが続いているようなので整理してみてください。

2022-09-12 13:13 UTC, shirotamaki commented
@komagata 
コミット整理しました！よろしくお願いします🙏

2022-09-14 06:50 UTC, komagata requested changes

2022-09-14 06:50 UTC, komagata commented on app/views/products/index.html.slim
> +- if admin_or_mentor_login? || adviser_login?
```suggestion
- if staff_login?
```

こちらで良さそうです。

https://github.com/fjordllc/bootcamp/blob/main/app/controllers/concerns/authentication.rb#L33

2022-09-14 07:31 UTC, shirotamaki commented
@komagata 
レビューありがとうございます！リファクタリングしました。ご確認お願いします🙏

2022-09-14 07:41 UTC, shirotamaki commented
@komagata 
レビューありがとうございます！リファクタリングしました。ご確認お願いします🙏

2022-09-18 07:29 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-18 07:29 UTC, merged

2022-09-18 08:25 UTC, shirotamaki commented
@komagata 
ありがとうございます！