メンターが提出物をコメント付きで確認を行なった際のトースト内容変更
fjordllc/bootcamp pull request #5445
Opened 2022-08-28 11:44 UTC by yuma-matsui

## issue

2022-08-28 14:08 UTC, yuma-matsui commented
@daiki0381 

お疲れ様です！
先週の水曜日からチーム開発の夜の部に参加しているyumです。
よろしくお願いいたします。

こちらのPRレビューをお願いします🙏

2022-08-31 05:03 UTC, daiki0381 reviewed
@yuma-matsui 
レビュー依頼ありがとうございます😊
2点気になった箇所にコメントしておりますので、ご確認お願いいたします。

2022-08-31 05:03 UTC, daiki0381 commented on test/system/product/checker_test.rb
> +  test "when mentor comment and confirm a product, there're different toasts" do
今回のissueは日報のトーストも対象でしょうか？もし対象であれば日報のテストも追加した方がいいと思いました！

2022-08-31 05:42 UTC, yuma-matsui commented on test/system/product/checker_test.rb
> +  test "when mentor comment and confirm a product, there're different toasts" do
ありがとうございます！
今回は日報のトーストは対象外ですが、komagataさんに確認してみます👍

2022-08-31 05:46 UTC, yuma-matsui commented on app/javascript/comments.vue
> +        this.createComment({ toast: '提出物を確認済みにしました。' })
サジェスチョンありがとうございます！
影響範囲確認できておらず失礼しました...😥

引数内で分岐するのが若干見通し悪い気するので、日報のトーストも変わってしまう件を考慮して再度変更してみます！

2022-08-31 13:54 UTC, yuma-matsui commented
@daiki0381 
ご指摘いただいた箇所を修正しましたのでご確認をお願いします🙏

2022-09-01 10:57 UTC, daiki0381 approved these changes
@yuma-matsui
修正ありがとうございます🙏
動作、コードともに問題ないと思うので、Approveさせて頂きます！

2022-09-01 11:39 UTC, yuma-matsui commented
@komagata 
メンバーレビューが済みましたのでご確認をお願いします🙏

2022-09-05 11:35 UTC, komagata requested changes

2022-09-05 11:35 UTC, komagata commented on app/javascript/comments.vue
> +    createComment({ toast = null }) {
引数がこれというのはおかしいかもです。
`{ toast = null }`

`toast = null` か `{ toast: null }` が正しそうです。

2022-09-06 10:57 UTC, yuma-matsui commented on app/javascript/comments.vue
> +    createComment({ toast = null }) {
@komagata 
非常にわかりづらく失礼しました。
`{ toast = null }`は分割代入を使用しておりまして、引数に`toast`プロパティをもつオブジェクトが渡ってくることを期待しています。
その初期値をnullにしたいため`{ toast = null }`としました。

### toast = nullにする場合。
イベントハンドラに引数を渡す場合、第一引数に`PointerEvent`オブジェクトが渡ってくるため、下記のような実装にする必要があります。

```javascript
# メソッド
createComment(_, toastMessage = null) {
}

# 呼び出し
this.createComment(event, this.toastMessage())
```

### { toast: null }にする場合
```javascript
createComment(_, options = { toast: null }) {
}
```

2022-09-06 12:59 UTC, komagata commented on app/javascript/comments.vue
> +    createComment({ toast = null }) {
@yuma-matsui 

> { toast = null }は分割代入を使用しておりまして、引数に「toastプロパティをもつオブジェクト」が渡ってくることを期待しています。

なるほどです、僕が勘違いしていました。今のままで大丈夫です〜

2022-09-06 13:00 UTC, komagata reviewed
conflictの解消をお願いいたします〜

2022-09-07 12:21 UTC, yuma-matsui commented
@komagata 
コンフリクトを解消しましたのでご確認をお願いします。

2022-09-09 22:20 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-09 22:20 UTC, merged