休会チェックボックスのデザイン
fjordllc/bootcamp pull request #5461
Opened 2022-08-31 05:02 UTC by machida

2022-09-21 07:19 UTC, machida commented
@AyakaTakashima 

リポジトリの更新をしたので、

```
git pull --rebase origin feature/comeback
```

をお願いしますー

2022-09-21 10:11 UTC, AyakaTakashima commented
> 
> リポジトリの更新をしたので、
> 
> ```
> git pull --rebase origin feature/comeback
> ```
> 
> をお願いしますー

@machida 
上記対応いたしました！一点質問で、`git pull --rebase origin feature/comeback`を行う前に、mainで
```shell
> git pull origin main
> bin/setup
```
をやってから、feature/comebackブランチで
```shell
> git pull --rebase origin main
```
をやった後に`git pull --rebase origin feature/comeback`をしたのですが、大丈夫でしょうか？

最初、このようにコンフリクトが発生してしまい、
```shell
> git pull --rebase origin main                                                                                               feature/comeback_check
From github.com:fjordllc/bootcamp
 * branch                main       -> FETCH_HEAD
Auto-merging app/models/user.rb
CONFLICT (content): Merge conflict in app/models/user.rb
Auto-merging db/schema.rb
error: could not apply 2fce9afd3... 休会からの復帰機能を追加
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 2fce9afd3... 休会からの復帰機能を追加
```
git reflogとgit reset --hard で下記のように対処しました。
```shell
> git reflog                                                                                                                                   !HEA
848c3d85a (HEAD, origin/main, origin/HEAD, main) HEAD@{0}: pull --rebase origin main (start): checkout 848c3d85a5acba93571d53f0e1e8f69a78f37587
d0ab4d5e0 (origin/feature/comeback_check, feature/comeback_check) HEAD@{1}: checkout: moving from main to feature/comeback_check
848c3d85a (HEAD, origin/main, origin/HEAD, main) HEAD@{2}: pull origin main: Fast-forward
7b5a8a06a HEAD@{3}: checkout: moving from feature/comeback_check to main
d0ab4d5e0 (origin/feature/comeback_check, feature/comeback_check) HEAD@{4}: commit: 空白行を削除
9b733ec10 HEAD@{5}: pull --rebase origin main (finish): returning to refs/heads/feature/comeback_check
9b733ec10 HEAD@{6}: pull --rebase origin main (pick): 休会フォームの注意を「読みました」のチェックボックスとボタンが連動するようにした
ec1ae9e65 HEAD@{7}: pull --rebase origin main (pick): 休会チェックボックスのデザイン
9d484864e HEAD@{8}: pull --rebase origin main (pick): lint修正
bb15cb627 HEAD@{9}: pull --rebase origin main (pick): システムテストの不要なスペースの削除とaccept_confirmの使用
8f67855b8 HEAD@{10}: pull --rebase origin main (pick): discord通知のテストを追加
dab433d40 HEAD@{11}: pull --rebase origin main (pick): activity_notifierの非同期通知のテストを修正
5152fe1cd HEAD@{12}: pull --rebase origin main (pick): DiscordNotifierをNotificationFacadeのhibernatedから分離
ad30f0d1f HEAD@{13}: pull --rebase origin main (pick): 研修生とアドバイザーのテストシナリオを追加
082af13be HEAD@{14}: pull --rebase origin main (pick): テスト修正
875ce13fc HEAD@{15}: pull --rebase origin main (pick): テスト追加
1330b5bb1 HEAD@{16}: pull --rebase origin main (pick): ユーザーが休会した時にメンターと管理者にサイト内通知とメール通知が行くようにした
2f29308e9 HEAD@{17}: pull --rebase origin main (pick): エラーメッセージの文言が変わっていたのを修正
31779cc90 HEAD@{18}: pull --rebase origin main (pick): 休会に分報チャンネルの注意書きを追加
6c7e65ef2 HEAD@{19}: pull --rebase origin main (pick): 二回サブミットするとエラーが出る問題を修正
060753b20 HEAD@{20}: pull --rebase origin main (pick): :cop:
de40dc704 HEAD@{21}: pull --rebase origin main (pick): ユーザー個別ページの休会情報のデザイン調整
97f602404 HEAD@{22}: pull --rebase origin main (pick): 休会からの復帰のリンクをトップページに配置、復帰関係の全体的な文言とデザインの微調整
```

↓誤ってブランチに切り替えたコマンドをresetしてしまいました
```
> git reset --hard HEAD@{1}                                                                                                                    !HEAD
HEAD is now at d0ab4d5e0 空白行を削除

> git reflog                                                                                                                                    HEAD
d0ab4d5e0 (HEAD, origin/feature/comeback_check, feature/comeback_check) HEAD@{0}: reset: moving to HEAD@{1}
848c3d85a (origin/main, origin/HEAD, main) HEAD@{1}: pull --rebase origin main (start): checkout 848c3d85a5acba93571d53f0e1e8f69a78f37587
d0ab4d5e0 (HEAD, origin/feature/comeback_check, feature/comeback_check) HEAD@{2}: checkout: moving from main to feature/comeback_check
848c3d85a (origin/main, origin/HEAD, main) HEAD@{3}: pull origin main: Fast-forward
7b5a8a06a HEAD@{4}: checkout: moving from feature/comeback_check to main
d0ab4d5e0 (HEAD, origin/feature/comeback_check, feature/comeback_check) HEAD@{5}: commit: 空白行を削除
9b733ec10 HEAD@{6}: pull --rebase origin main (finish): returning to refs/heads/feature/comeback_check
9b733ec10 HEAD@{7}: pull --rebase origin main (pick): 休会フォームの注意を「読みました」のチェックボックスとボタンが連動するようにした
ec1ae9e65 HEAD@{8}: pull --rebase origin main (pick): 休会チェックボックスのデザイン
9d484864e HEAD@{9}: pull --rebase origin main (pick): lint修正
bb15cb627 HEAD@{10}: pull --rebase origin main (pick): システムテストの不要なスペースの削除とaccept_confirmの使用
8f67855b8 HEAD@{11}: pull --rebase origin main (pick): discord通知のテストを追加
dab433d40 HEAD@{12}: pull --rebase origin main (pick): activity_notifierの非同期通知のテストを修正
5152fe1cd HEAD@{13}: pull --rebase origin main (pick): DiscordNotifierをNotificationFacadeのhibernatedから分離
ad30f0d1f HEAD@{14}: pull --rebase origin main (pick): 研修生とアドバイザーのテストシナリオを追加
082af13be HEAD@{15}: pull --rebase origin main (pick): テスト修正
875ce13fc HEAD@{16}: pull --rebase origin main (pick): テスト追加
1330b5bb1 HEAD@{17}: pull --rebase origin main (pick): ユーザーが休会した時にメンターと管理者にサイト内通知とメール通知が行くようにした
2f29308e9 HEAD@{18}: pull --rebase origin main (pick): エラーメッセージの文言が変わっていたのを修正
31779cc90 HEAD@{19}: pull --rebase origin main (pick): 休会に分報チャンネルの注意書きを追加
6c7e65ef2 HEAD@{20}: pull --rebase origin main (pick): 二回サブミットするとエラーが出る問題を修正
060753b20 HEAD@{21}: pull --rebase origin main (pick): :cop:
de40dc704 HEAD@{22}: pull --rebase origin main (pick): ユーザー個別ページの休会情報のデザイン調整
```

#↓ブランチ切り替えしたことをresetしたことに気づかず、ここで、HEAD@{1}: pull --rebase origin mainをresetしました
```
> git reset --hard HEAD@{1}                                                                                                                     HEAD
HEAD is now at 848c3d85a Merge pull request #5479 from fjordllc/feature/adjust-user-practice-progress-to-vue-mounter

#↓git pull --rebase origin feature/comebackを実行
> git pull --rebase origin feature/comeback                                                                                                     HEAD
remote: Enumerating objects: 243, done.
remote: Counting objects: 100% (243/243), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 178 (delta 140), reused 140 (delta 106), pack-reused 0
Receiving objects: 100% (178/178), 24.28 KiB | 195.00 KiB/s, done.
Resolving deltas: 100% (140/140), completed with 59 local objects.
From github.com:fjordllc/bootcamp
 * branch                feature/comeback -> FETCH_HEAD
 + 4b2e1c3bd...4761d1230 feature/comeback -> origin/feature/comeback  (forced update)
Updating 848c3d85a..4761d1230
Fast-forward
 app/assets/stylesheets/application/blocks/auth-form/_auth-form.sass  | 12 +++++++----
 app/assets/stylesheets/application/blocks/form/_form-item.sass       |  3 +--
 app/assets/stylesheets/application/blocks/form/_form-link-block.sass |  4 ++++
 app/assets/stylesheets/application/blocks/form/_form-notice.sass     |  7 ++++---
 app/assets/stylesheets/application/blocks/user/_user-metas.sass      | 12 ++++++++++-
 app/assets/stylesheets/atoms/_a-short-text.sass                      |  2 ++
 app/controllers/comeback_controller.rb                               | 25 +++++++++++++++++++++++
 app/controllers/hibernation_controller.rb                            | 12 +++++++++--
 app/controllers/user_sessions_controller.rb                          | 16 ++++++++-------
 app/models/notification_facade.rb                                    |  1 -
 app/models/subscription.rb                                           |  4 ++--
 app/models/user.rb                                                   | 22 +++++++++++++++++++++
 app/views/application/_flash.html.slim                               |  2 +-
 app/views/application/_user_menu.html.slim                           | 16 +++++++++++----
 app/views/application/header/_heade [...]

2022-09-23 09:32 UTC, AyakaTakashima commented
@machida 
お疲れ様です！こちらのissue[\[休会\] 休会フォームに 注意を読んだのチェックボックスを追加 · Issue \#5378 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/issues/5378)について、内容の変更が完了しました！
本PRは私が作成したものではありませんが、レビュー依頼はどのようにすればよろしいでしょうか？
いつもPRの一番最初に書かせていただいている下記のようなdescriptionは普通にこのPRにコメントする形で私が書いてしまってよろしいのでしょうか？？
```
## Issue

- #5378 

## 概要

管理画面の企業一覧の企業名をリンクに置き換えました。
...

## 変更確認方法

1. ブランチ`feature/comeback_check`をローカルに取り込む
2. `rails s`でローカル環境を立ち上げる
3. ...

## 変更前

<img ...>

## 変更後

<img ...>
```

2022-09-23 10:03 UTC, machida commented
@AyakaTakashima はい！description は上書きをしてレビュー依頼をお願いしますー🙏

2022-09-23 13:30 UTC, AyakaTakashima commented
@machida 
承知いたしました！！お返事ありがとうございます！！

2022-09-23 14:46 UTC, AyakaTakashima commented
@machida
度々申し訳ございません！
ローカルで試しにkimuraさんを休会させようとすると、このようにエラーが出てしまいます。
![image](https://user-images.githubusercontent.com/76944527/191987361-d846648e-5c90-4407-9663-1d2fe5367689.png)
こちらの本PRでは、チェックボックスとボタンの連動のみを実装するという認識なのですが、このエラーに関しては別issueで対応していただくという理解で問題ありませんでしょうか？

ご確認よろしくお願いいたします🙇‍♀️

2022-09-23 14:51 UTC, machida commented
@AyakaTakashima

Issueの登録をお願いしますー。このPRでは解決させなくて大丈夫です。

もしかしたら、最新のmainで解決されてるかもしれないので、念のため、

git pull --rebase origin main

をやってみてくださいー。

2022-09-23 15:10 UTC, AyakaTakashima commented
@machida 
夜遅くにもかかわらず早速のご対応ありがとうございます🙇‍♀️
`git pull --rebase origin main`をしたのですが、このように多くのコミットがskipされてしまうみたいです...
```shell                                                                                                                                                                     
> git pull --rebase origin main
From github.com:fjordllc/bootcamp
 * branch                main       -> FETCH_HEAD
warning: skipped previously applied commit 81a865e33
warning: skipped previously applied commit bcd62d2a4
warning: skipped previously applied commit 9b3a06817
warning: skipped previously applied commit c570ec128
warning: skipped previously applied commit b3b23f2de
warning: skipped previously applied commit 68e88142b
warning: skipped previously applied commit c68dd882f
warning: skipped previously applied commit d97e610c7
warning: skipped previously applied commit 6193d5b44
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Successfully rebased and updated refs/heads/feature/comeback_check.
```

これらは、メッセージに出ている通り`--reapply-cherry-picks`をつけて`git pull --rebase origin main --reapply-cherry-picks`をしてしまっても大丈夫なのでしょうか...？
調べてみたのですが、`git pull --rebase origin main --reapply-cherry-picks`をすると、自分のコミットよりももっと先のコミット群を取り込んでくれるコマンドなのかな...？と思ったのですが、使ったことがないコマンドなので不安です😭
ご回答はお手隙の時で構いません。
よろしくお願いいたします🙇‍♀️

2022-09-26 15:46 UTC, machida commented
@AyakaTakashima 

ブランチの派生元の feature/comeback https://github.com/fjordllc/bootcamp/pull/5369 を最新の main から rebase して最新の状態にし、こちらの PR を最新の状態にした feature/comeback からrebase しました。

なので、手元の feature/comeback_check ブランチで、

```
git pull --rebase origin feature/comeback_check
```

をお願いします。

それをした上で、kimuraさんを休会させようとするとエラーが出るか再度確認してみてください。
エラーが出ましたら、別Issueとして、Issueの登録をお願いしますー🙏

2022-09-26 17:31 UTC, machida commented
今落ちてるテストは、
https://github.com/fjordllc/bootcamp/pull/5593
これがマージされたら通るようになりますー

2022-09-27 08:34 UTC, machida commented
@AyakaTakashima 

最新から rebase したので、また手元の feature/comeback_check ブランチで、

```
git pull --rebase origin feature/comeback_check
```

をお願いしますー

2022-09-27 10:27 UTC, AyakaTakashima commented
@machida 
お返事遅れまして申し訳ございません！
rebaseしてみました。（skipされているものが多くありますが大丈夫でしょうか...？）
```shell
> git pull --rebase origin feature/comeback_check
remote: Enumerating objects: 243, done.
remote: Counting objects: 100% (227/227), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 243 (delta 163), reused 199 (delta 157), pack-reused 16
Receiving objects: 100% (243/243), 54.73 KiB | 239.00 KiB/s, done.
Resolving deltas: 100% (164/164), completed with 54 local objects.
From github.com:fjordllc/bootcamp
 * branch                feature/comeback_check -> FETCH_HEAD
 + b51de8318...b81f5d2ea feature/comeback_check -> origin/feature/comeback_check  (forced update)
warning: skipped previously applied commit ec1493132
warning: skipped previously applied commit 2c076d309
warning: skipped previously applied commit b96b65ba9
warning: skipped previously applied commit c31e5e874
warning: skipped previously applied commit dc790efbb
warning: skipped previously applied commit b77112106
warning: skipped previously applied commit 36de3011a
warning: skipped previously applied commit db46489d0
warning: skipped previously applied commit d0fdfceae
warning: skipped previously applied commit fad316180
warning: skipped previously applied commit 9c8c59162
warning: skipped previously applied commit 5611c1d33
warning: skipped previously applied commit 756b78947
warning: skipped previously applied commit d566a208c
warning: skipped previously applied commit 366a03694
warning: skipped previously applied commit b18f29bda
warning: skipped previously applied commit 5295b5c12
warning: skipped previously applied commit 25ed6a227
warning: skipped previously applied commit dee5a1122
warning: skipped previously applied commit f5a52acad
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Successfully rebased and updated refs/heads/feature/comeback_check.
```

しかしやはりエラーとなってしまったので、issueを登録させていただきます。
![image](https://user-images.githubusercontent.com/76944527/192501853-7213a2e0-bc66-4fff-9b07-8d45d46d5141.png)

こちらの`feature/comeback_check`ブランチはレビューに出させていただきます！

2022-09-27 10:48 UTC, AyakaTakashima commented
@siroemk 
siroemkさん、初めまして！
もしご都合がよろしければお手隙の際にこちらのPRについて、レビューをお願いしたいです🙇‍♀️

descriptionに注意点を記載させていただきましたのでご確認いただけますと嬉しいです！
よろしくお願いいたします🙇‍♀️

2022-09-30 08:08 UTC, siroemk approved these changes
@AyakaTakashima 
お疲れ様です〜！お待たせしました。
注意点なども細かく書いていただき、ありがとうございました✨

動作もコードも確認いたしました。LGTMです🙆‍♀️

2022-09-30 09:55 UTC, AyakaTakashima commented
@siroemk 
とんでもないです！！
ご確認ありがとうございます〜！！！🥳

2022-09-30 09:56 UTC, AyakaTakashima commented
@komagata 
お疲れ様です！
こちら、siroemkさんからapproveいただきましたのでレビューお願いいたします🙇‍♀️

2022-10-02 09:54 UTC, komagata commented on app/views/hibernation/new.html.slim
> -          //
👍

2022-10-02 09:54 UTC, komagata commented on test/system/hibernation_test.rb
> +      find('.is-checkbox').click
こちらcapybaraのcheckboxをチェックするためのメソッドは使えなかったでしょうか。

2022-10-03 13:21 UTC, AyakaTakashima commented on test/system/hibernation_test.rb
> +      find('.is-checkbox').click
@komagata 
ご確認ありがとうございます！
capybaraのcheckboxをチェックするためのメソッドというものがあるのですね🙇‍♀️
調べて修正してみましたのでご確認よろしくお願いいたします！

2022-10-04 11:09 UTC, AyakaTakashima commented
@komagata 
度々申し訳ございません。
こちら、本日お返事が来ているか確認のため本日PRを覗きに来たら、CIが落ちていました。

昨日`check 'is-checkbox' `に変更し、手元でテスト実行した時は下記の通り通っていたのですが...
```shell
> rails test test:test/system/notification/hibernation_test.rb
Run options: --seed 64430

# Running:

................................................................................................................................................................................................................................................................................................................
[Minitest::CI] Generating test report in JUnit XML format...


Finished in 5.357628s, 56.7415 runs/s, 191.6893 assertions/s.
304 runs, 1027 assertions, 0 failures, 0 errors, 0 skips
```

本日実行してみると、下記の通り通らなくなっていました。
```shell
> rails test test/system/notification/hibernation_test.rb
Run options: --seed 56247

# Running:

[Screenshot Image]: /Users/takashimaayaka/fjord/bootcamp/tmp/screenshots/failures_test_notify_admins_and_mentors_when_a_adviser_hibernate.png
[Screenshot Image]: /Users/takashimaayaka/fjord/bootcamp/tmp/screenshots/failures_test_notify_admins_and_mentors_when_a_student_hibernate.png
[Screenshot Image]: /Users/takashimaayaka/fjord/bootcamp/tmp/screenshots/failures_test_notify_admins_and_mentors_when_a_trainee_hibernate.png
E

Error:
Notification::HibernationTest#test_notify_admins_and_mentors_when_a_student_hibernate:
Capybara::ElementNotFound: Unable to find checkbox "is-checkbox" that is not disabled
    test/system/notification/hibernation_test.rb:25:in `block in <class:HibernationTest>'


rails test test/system/notification/hibernation_test.rb:15

E

Error:
Notification::HibernationTest#test_notify_admins_and_mentors_when_a_trainee_hibernate:
Capybara::ElementNotFound: Unable to find checkbox "is-checkbox" that is not disabled
    test/system/notification/hibernation_test.rb:48:in `block in <class:HibernationTest>'


rails test test/system/notification/hibernation_test.rb:38

E

Error:
Notification::HibernationTest#test_notify_admins_and_mentors_when_a_adviser_hibernate:
Capybara::ElementNotFound: Unable to find checkbox "is-checkbox" that is not disabled
    test/system/notification/hibernation_test.rb:71:in `block in <class:HibernationTest>'


rails test test/system/notification/hibernation_test.rb:61


[Minitest::CI] Generating test report in JUnit XML format...


Finished in 39.431549s, 0.0761 runs/s, 0.0761 assertions/s.
3 runs, 3 assertions, 0 failures, 3 errors, 0 skips
```

試しに、`find('.is-checkbox').click`に戻し、実行してみたところ下記のように通りました。
```shell
> rails test test:test/system/notification/hibernation_test.rb
Run options: --seed 59262

# Running:

................................................................................................................................................................................................................................................................................................................
[Minitest::CI] Generating test report in JUnit XML format...


Finished in 5.330115s, 57.0344 runs/s, 192.6788 assertions/s.
304 runs, 1027 assertions, 0 failures, 0 errors, 0 skips
```
したがって、`test/system/notification/hibernation_test.rb`内のものは`find('.is-checkbox').click`に戻してあります。
ご確認よろしくお願いいたします🙇‍♀️

2022-10-04 12:56 UTC, AyakaTakashima commented
@komagata 
すみません！上記の件ですが、テストを実行するコマンドが違っているだけでした。
調べてみると、capybaraのチェックボックスのテストの方法は`check "チェックボックスのid"`とするようでしたので、下記のように`abcd`というidを試しにつけてやってみました。

```html
#app/views/hibernation/new.html.slim
          .form-item
            label.a-form-label.is-required
              | 休会についての注意を読みましたか？
            .block-checks.is-1-item.is-centered
              .block-checks__item
                .a-block-check.is-checkbox#abcd <!--ここに試しにidをつけた-->
                  input.a-toggle-checkbox.js-hibernation-agreements-checkbox#aaa(type='checkbox')
                  label.a-block-check__label(for='aaa')
                    | 読みました
```
下記のように書き換えました↓
```rb
#test/system/hibernation_test.rb
check 'abcd'
```

しかし、テストはパスしませんでした....
ラベルでもいけそうだったので、
```rb
check '読みました'
```
としてみましたがダメでした。
何か間違えがあれば教えていただけないでしょうか🙇‍♀️
よろしくお願いいたします🙇‍♀️

2022-10-04 13:09 UTC, komagata commented
@AyakaTakashima 

なぜ`find('.is-checkbox').click`はOKで、`check`はダメなのか調べてみてください。
Capybaraの公式APIリファレンスをまず読んでみると良いと思います。

2022-10-05 13:19 UTC, AyakaTakashima commented
@komagata 
ありがとうございます！読んでみます！！

2022-10-06 19:09 UTC, komagata commented
@AyakaTakashima なるほどです。find('.is-checkbox').clickで大丈夫です〜

2022-10-06 19:10 UTC, komagata requested changes

2022-10-06 19:10 UTC, komagata commented on app/views/hibernation/new.html.slim
> +                  label.a-block-check__label(for='aaa')
`aaa`の部分を意味にある名前にした方がいいかもです〜。

2022-10-10 05:06 UTC, AyakaTakashima commented on app/views/hibernation/new.html.slim
> +                  label.a-block-check__label(for='aaa')
@komagata 
こちら変更いたしました！
ご確認よろしくお願いいたします🙇‍♀️

2022-10-11 04:57 UTC, komagata commented on test/system/notification/hibernation_test.rb
> +    find('.is-checkbox').click
このページにcheckboxが増えたらテストが落ちる感じのセンシティブなテストになっているので、もう少し絞り込んだ条件が良さそうです。

2022-10-11 10:38 UTC, AyakaTakashima commented on test/system/notification/hibernation_test.rb
> +    find('.is-checkbox').click
@komagata 
変更いたしましたのでご確認よろしくお願いいたします。

2022-10-17 08:39 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-10-17 08:49 UTC, merged

2022-10-17 10:14 UTC, AyakaTakashima commented
@komagata 
ご確認ありがとうございます！
通常ならリリースノートを書くと思うのですが、休会の機能はなかったと認識しています。
しかし、`https://bootcamp.fjord.jp/hibernation/new`にアクセスするとページは見れました。
ただ、ページの中のどこにリンクがあるのか見つけることができませんでした。
休会の機能はすでに実装されているという認識でよろしいでしょうか？

もしすでに実装されているのであればリリースノートに書くべきかと思うのですが、
未実装であれば、書かないべきかと思いましたので確認したいです。
ご回答、よろしくお願いいたします🙇‍♀️

2022-10-17 18:54 UTC, komagata commented
@AyakaTakashima 直接URLにアクセスすれば使えますが、表向きにはまだ休会機能はリリースされていないです〜。

2022-10-18 09:34 UTC, AyakaTakashima commented
@komagata 
承知いたしました！
それではリリースノートは書かないようにします！