talks.vueとtalk.vueをVueMounterに対応
fjordllc/bootcamp pull request #5468
Opened 2022-09-01 07:32 UTC by fuwa-syugyo

2022-09-01 14:33 UTC, fuwa-syugyo commented
@yuki-snow1823 
お疲れ様です！
お手数ですがレビューをお願いしたいです。
急いでおりませんので、お手隙の際で大丈夫です。
よろしくお願いいたします。

2022-09-05 00:28 UTC, yuki-snow1823 commented
@fuwa-syugyo 
もちろん大丈夫です！本日行います。
自分は平日10:00-19:00ごろが基本的に可能です！

2022-09-06 01:59 UTC, yuki-snow1823 commented
只今より開始します。

2022-09-06 02:14 UTC, yuki-snow1823 commented
@fuwa-syugyo 
お疲れ様です。レビュー依頼ありがとうございました(__)
動作確認しました。

変更確認方法の動作は確認できたのですが、その間、左側のアイコンが表示されておりませんでした。

<img width="185" alt="スクリーンショット 2022-09-06 11 10 59" src="https://user-images.githubusercontent.com/59280290/188532309-d2aca979-e6a2-4926-ac92-ebe576232c96.png">

Consoleに出ているエラーを確認したところ、
`GET https://kit.fontawesome.com/8f04dd61ff.js net::ERR_ABORTED 403`
このような内容が出ていました。

該当のファイルはこちらのようです。
https://github.com/fjordllc/bootcamp/blob/9fc80fb54931a8e93f31583b53b909f164a402ea/app/views/head/_fontawsome.html.slim#L1

今回の変更とは関係なさそうでしょうか？
もし関係なさそうな場合は、他の方にもレビュー依頼をしていただきこの部分だけチェックしてもらっても良さそうです。

2022-09-06 02:18 UTC, yuki-snow1823 approved these changes
conversationの方にコメント残しました！
レビュー自体はApproveです！

2022-09-06 06:20 UTC, yuki-snow1823 commented
localhostで試してみます。

2022-09-06 07:09 UTC, yuki-snow1823 commented
@fuwa-syugyo 
無事 http://localhost:3000/talks であれば出力されていました！大丈夫です！
ConversationのトップだけURLの変更お願いします。
自分も勉強になりました🙏

<img width="287" alt="スクリーンショット 2022-09-06 16 07 32" src="https://user-images.githubusercontent.com/59280290/188569329-5b22f534-86a9-4b15-a376-9e7a8d90cc63.png">

2022-09-06 07:49 UTC, fuwa-syugyo commented
@yuki-snow1823 
ご確認ありがとうございます！表示されて良かったです。
お手数をおかけしました…！

2022-09-06 07:51 UTC, fuwa-syugyo commented
@komagata 
お疲れ様です。
チームメンバーよりapproveをいただきましたので、レビューをお願いいたします。

※descriptionに書かれているURLはlocalhost3000に修正しました

2022-09-09 22:03 UTC, komagata commented
@fuwa-syugyo レビュー依頼をするときはDraftではなく`Ready for review`の状態でお願いします〜。
下の方に`Ready for review`のボタンがあるのでそれを押せばOKです。

2022-09-12 06:29 UTC, fuwa-syugyo commented
@komagata 
失礼いたしました、`Ready for review` の状態にしました。
今後気をつけます。
レビューをお願いいたします。

2022-09-13 07:04 UTC, komagata requested changes
conflictの修正をお願いします〜

2022-09-14 05:26 UTC, fuwa-syugyo commented
@komagata 
コンフリクトを解消しました。
レビューをお願いいたします。

2022-09-18 07:31 UTC, komagata approved these changes

2022-09-18 07:31 UTC, komagata reviewed
conflictの修正をお願いします〜

2022-09-19 05:57 UTC, fuwa-syugyo commented
@komagata 
再度conflictを解消しました。
お手数ですがご確認をお願いいたします！

2022-09-21 05:08 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-21 05:08 UTC, merged