メンターのユーザー情報に関連書籍を登録できるようにする
fjordllc/bootcamp pull request #5476
Opened 2022-09-02 08:51 UTC by daiki0381

2022-09-02 10:37 UTC, daiki0381 commented
@machida お疲れ様です。お手隙の際に、こちらのデザインをお願いします🙏

2022-09-02 10:43 UTC, daiki0381 commented
@keiz1213 
お疲れ様です。
お手隙の際に、こちらのレビューをお願いしたいです🙏
ご不明な点やご都合が合わないようでしたら、お気軽にご連絡ください！

2022-09-03 06:06 UTC, keiz1213 reviewed
@daiki0381 
お疲れさまです！2点コメントさせていただきました！

それとは別に、#5300 ではメンターのプロフィール画像のファイル形式をバリデーションにかけられていますが、今回の本の画像のファイル形式のバリデーションは不要なのでしょうか？

`PNG, JPG, GIF`以外のファイル形式で本の画像をアップロードしたところそのまま登録できました。

デザイン等の方針が固まってないのでこの点は保留にしている感じですかね🤔？
ご確認のほどよろしくお願いいたします🙏

<img width="442" alt="_development__FJORD_BOOT_CAMP（フィヨルドブートキャンプ）" src="https://user-images.githubusercontent.com/72614612/188257647-d899f7df-3cb8-4ac5-a979-183cfe8313b8.png">

2022-09-03 07:00 UTC, daiki0381 commented on app/controllers/home_controller.rb
> +      @mentors = User.with_attached_profile_image.where(mentor: true).includes(related_books: { cover_attachment: :blob })
ご提案ありがとうございます🙏 mentorスコープを使用した方がスッキリ書けますね✨ [7b9f17f](https://github.com/fjordllc/bootcamp/pull/5476/commits/7b9f17f4da7e33bb39657f373e33606d30e55e4d)で修正しました！

2022-09-03 07:00 UTC, daiki0381 commented on db/schema.rb
> +    t.boolean "wip", default: false, null: false
こちらは関係ないので、[627daa8](https://github.com/fjordllc/bootcamp/pull/5476/commits/627daa8877d85e93cda117de45d9ca84dce3e8ca)で修正しました！

2022-09-03 07:15 UTC, daiki0381 commented
@keiz1213 
レビューありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しました。再度レビューお願いします🙏

> それとは別に、https://github.com/fjordllc/bootcamp/pull/5300 ではメンターのプロフィール画像のファイル形式をバリデーションにかけられていますが、今回の本の画像のファイル形式のバリデーションは不要なのでしょうか？

こちら表示画像の形式にもバリデーションをかけた方がいいので、[627daa8](https://github.com/fjordllc/bootcamp/pull/5476/commits/627daa8877d85e93cda117de45d9ca84dce3e8ca)で修正しました！

2022-09-03 07:42 UTC, keiz1213 approved these changes
@daiki0381 

修正ありがとうございます！動作確認できました！難しそうなissueをサラッとやられててすごいです💡勉強になりました🙇‍♂️
僕の方からはapproveさせていただきます😄

2022-09-03 09:04 UTC, daiki0381 commented
@keiz1213 ありがとうございます😊

2022-09-03 10:37 UTC, machida commented
@daiki0381 デザイン了解ですー

2022-09-05 06:49 UTC, daiki0381 commented
@machida ありがとうございます！よろしくお願いします🙇‍♂️

2022-09-20 06:10 UTC, machida commented
@daiki0381 お待たせしました🙇‍♂️ デザイン入れました。

@komagata レビューお願いしますー

2022-09-21 01:43 UTC, machida commented
@komagata @daiki0381 
このPRを [feature/add-mentor-profile](https://github.com/fjordllc/bootcamp/tree/feature/add-mentor-profile) にマージ後、一旦新しいメンター紹介はコメントアウトして、古いメンター紹介を表示しつつ、新しいメンター紹介のデータを投入後に、コメントアウトを外して、古いメンター紹介を削除したいと思います。

2022-09-21 02:24 UTC, daiki0381 commented
@machida 
ありがとうございます🙇‍♂️ 承知しました！

2022-09-22 05:42 UTC, komagata commented on test/system/welcome_test.rb
> +    find("input[name*='[url]']").set('https://www.amazon.co.jp/%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AERuby%E5%85%A5%E9%96%80-%E8%A8%80%E8%A
https://www.amazon.co.jp/dp/B09MPX7SMY

amazonの商品ページにはSEOのための余計な文字列がたくさんついていますが、冗長なので上記のようなURLでも大丈夫なのでそちらを使った方がいいかもです。

2022-09-23 00:15 UTC, daiki0381 commented on test/system/welcome_test.rb
> +    find("input[name*='[url]']").set('https://www.amazon.co.jp/%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AERuby%E5%85%A5%E9%96%80-%E8%A8%80%E8%A
こちら[c1f447d](https://github.com/fjordllc/bootcamp/pull/5476/commits/c1f447d6a3a38ec1523e9b79354211db11b26959)で修正しました。

2022-09-23 00:16 UTC, daiki0381 commented
@komagata 
レビューありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しました。再度レビューお願いします🙏

2022-09-26 05:47 UTC, komagata commented
@daiki0381 related_bookだと、関連する書籍はなんでも当てはまる名前なので（リレーショナルデータベースを使ってるのでほぼ全てのbookはrelatedといえる）、この本はどういう意味なのか考え、設計してもっと具体的な名前がいいかな〜と思います。

2022-09-26 09:28 UTC, daiki0381 commented
@komagata 
ありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しました！再度レビューお願いします🙏

2022-09-28 05:30 UTC, komagata requested changes

2022-09-28 05:30 UTC, komagata commented on app/models/mentor_involved_book.rb
> +class MentorInvolvedBook < ApplicationRecord
ちょっと直訳な名前になってしまっているのと、極力端的に１〜２単語ぐらいで表せられると良いかなと思います。

`AuthoredBook`などはいかがでしょうか。

2022-09-28 05:30 UTC, komagata commented on app/views/users/form/_mentor_involved_book.html.slim
> +  .row#reference_books
この辺りも変えたほうがいいかもです〜

2022-09-28 07:07 UTC, daiki0381 commented on app/models/mentor_involved_book.rb
> +class MentorInvolvedBook < ApplicationRecord
こちら[7313acf](https://github.com/fjordllc/bootcamp/pull/5476/commits/7313acff2cdb32d7a8d060cfc7457966543d4889)で修正しました。

2022-09-28 07:08 UTC, daiki0381 commented on app/views/users/form/_mentor_involved_book.html.slim
> +  .row#reference_books
こちら[46d3a3e](https://github.com/fjordllc/bootcamp/pull/5476/commits/46d3a3e8651457c88d56091a59021c4bbd915f80)で修正しました。

2022-09-28 07:15 UTC, daiki0381 commented
@komagata 
ありがとうございます🙇‍♂️ ご指摘頂いた箇所を修正しました！再度レビューお願いします🙏

2022-09-29 19:32 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-29 19:32 UTC, merged