user-practice-progress.vueをVueMounterに対応させる
fjordllc/bootcamp pull request #5479
Opened 2022-09-03 08:35 UTC by choco0809

## Issue

- https://github.com/fjordllc/bootcamp/issues/5145

## 概要
user-practice-progress.vueのマウント方法を新マウント方法に変更する。

## 動作確認方法
1. ブランチ`feature/adjust-user-practice-progress-to-vue-mounter`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. 任意のユーザーでログインする
4. http://localhost:3000/users にアクセスし、表示されることを確認する

## 新マウント確認方法
1. 開発者ツールの`Source`>`top`>`webpack://` > `app/javascript` > `VueMounter.js`の22行目にブレイクポイントを設定する
2. http://localhost:3000/users にアクセスする
ブレークポイントで停止する場合は、VueMounter.jsを使っている
ブレークポイントで停止せずにページが表示される場合は、VueMounter.jsを使っていない

<img width="1419" alt="Notification_Center" src="https://user-images.githubusercontent.com/99729409/188262886-1a5ebd28-a5f0-46d0-9327-1a2972c77e3f.png">

2022-09-03 11:09 UTC, choco0809 commented
@shirotamaki 
お疲れ様です〜🙇‍♂️
お手隙の際にレビューをお願い致します！

2022-09-04 11:41 UTC, shirotamaki approved these changes
@choco0809 
レビュー依頼いただきありがとうございます！😊
動作確認できました！Approveさせていただきます〜🎉

2022-09-04 13:04 UTC, choco0809 commented
@shirotamaki 
ご確認ありがとうございます🙇‍♂️
デバックモード意外と便利ですのでぜひぜひ！

2022-09-04 13:04 UTC, choco0809 commented
@komagata 
お疲れ様です！
shirotamaki さんよりApprove頂きましたのでレビューよろしくお願いします🙇‍♂️🙇‍♂️🙇‍♂️

2022-09-05 16:42 UTC, komagata requested changes

2022-09-05 16:42 UTC, komagata commented on app/javascript/company-users.vue
> +import User from './components/user'
```suggestion
import User from './components/user.vue'
```

拡張子をつけた方がいいかもです〜

2022-09-06 14:42 UTC, choco0809 commented
@komagata 
`generation-users.vue`も拡張子が抜けていたので、付与しました。
お手隙の際に、ご確認お願いします🙇‍♂️

2022-09-09 22:13 UTC, komagata commented on app/javascript/components/user.vue
> +import Following from '../following'
こちらも拡張子を外さない方が良さそうです。
ここだけではなく、全体も見直してみてください〜。

2022-09-10 09:42 UTC, choco0809 commented
@komagata 
vueファイルをimportしている箇所全てに拡張子を明示的につけました🙇‍♂️
ご確認おねがいします！

1点質問なのですが、他PRみても`.vue`拡張子だけ明示的につけて`.js`拡張子は記載していないように思いました。
この違いは何なのでしょうか？？

2022-09-12 01:45 UTC, komagata commented
> @komagata vueファイルをimportしている箇所全てに拡張子を明示的につけました🙇‍♂️ ご確認おねがいします！
> 
> 1点質問なのですが、他PRみても`.vue`拡張子だけ明示的につけて`.js`拡張子は記載していないように思いました。 この違いは何なのでしょうか？？

@choco0809 

javascripts以下は基本的に`.js`のファイルであると予想できるからです。`.vue`は特殊なので明示的に書いた方が良いからです〜。

2022-09-12 01:45 UTC, komagata requested changes
conflictの修正お願いします〜

2022-09-12 14:31 UTC, choco0809 commented
@komagata 
conflict解消しましたので、ご確認おねがいします🙇‍♂️🙇‍♂️🙇‍♂️

2022-09-14 11:19 UTC, choco0809 commented
@komagata 
対応いたしましたので、ご確認おねがいします🙇‍♂️🙇‍♂️🙇‍♂️

ちなみに今回の場合、もう一度 shirotamakiさんにレビューいただいてからの方がいいのでしょうか？

2022-09-18 07:41 UTC, komagata commented on app/javascript/packs/application.js
> +mounter.addComponent(UserPracticeProgress)
親コンポーネントから使われているだけの場合は、これら一連の処理は必要なさそうです〜

2022-09-18 07:42 UTC, komagata commented
> @komagata 対応いたしましたので、ご確認おねがいします🙇‍♂️🙇‍♂️🙇‍♂️
> 
> ちなみに今回の場合、もう一度 shirotamakiさんにレビューいただいてからの方がいいのでしょうか？

いえ、一度OKをもらっている場合は不要です〜。

2022-09-19 15:09 UTC, choco0809 commented
@komagata 
修正しましたので、ご確認おねがいします🙇‍♂️

2022-09-21 05:13 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-21 05:14 UTC, merged