管理者・メンターにユーザー一覧に退会、休会のタブを表示するようにした
fjordllc/bootcamp pull request #5512
Opened 2022-09-13 11:44 UTC by Nabegon

2022-09-16 20:10 UTC, Nabegon commented
@yuma-matsui さん、お疲れ様です！
こちらのPRのレビューをお願いしたいです🙏
もしお忙しいようでしたら気軽にお知らせください🙇よろしくお願いします！

2022-09-17 01:08 UTC, yuma-matsui commented on test/system/users_test.rb
> +    has_link?('退会')
`has_link`のみだと真偽値が返ってくるだけなので、結果如何に関わらずテスト自体がパスしてしまうと思います！

### わざと落ちるテストにした場合と実行結果
```ruby
test 'mentor can see retired and hibernated tabs' do
  visit_with_auth '/users', 'mentormentaro'
  has_no_link?('休会')
  has_link?('退会')
end
```

```bash
% rails test test/system/users_test.rb:403
Run options: --seed 38

# Running:
.
[Minitest::CI] Generating test report in JUnit XML format...

Finished in 29.471191s, 0.0339 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

`assert has_link?`とするか`assert_link`を使ってはいかがでしょうか！

2022-09-17 01:09 UTC, yuma-matsui commented on test/system/users_test.rb
> +    has_link?('退会')
同上です。

2022-09-17 01:09 UTC, yuma-matsui commented on test/system/users_test.rb
> +    has_no_link?('退会')
同上です。

2022-09-17 01:58 UTC, yuma-matsui commented on app/controllers/api/users_controller.rb
> +    check_users_to_display
別メソッド内でインスタンス変数の値を変更してしまうと、他の開発者がコードを読むときに頭の中でインスタンス変数の状態をその都度考えながらコードを追わなくてはいけなくなってしまうので、少し見通しが良くないかなと思いましたがいかがでしょうか🤔?

例えばこの`check_users_to_display`メソッドの後に`@users`を使用することがあった場合などです。

`@target`がhibernatedまたはretiredかどうかを判定するメソッドを用意して、元の`@users = @users.unhibernated.unretired unless @company`のunlessのOR条件に含めるなど、いかがでしょうか？

2022-09-17 02:00 UTC, yuma-matsui commented on app/controllers/users_controller.rb
> +    check_users_to_display
同上です。

2022-09-17 02:01 UTC, yuma-matsui requested changes
いくつかコメントさせていただきました！
ご確認をお願いいたします🙏

2022-09-19 09:25 UTC, Nabegon commented
@yuma-matsui さん、こんばんは！レビューいただきありがとうございました！修正いたしましたので、お手数ですが、お手すきの際にご確認いただきたいです。よろしくお願いします🙏

2022-09-19 10:16 UTC, yuma-matsui commented on app/controllers/api/users_controller.rb
> +  end
メソッド名にifを含んでいるのが少し違和感でした🤔
Rubyだと真偽値を返すメソッド名には末尾に`?`が使用されている印象です！

`hibernated_or_retired`が形容詞の役割を果たすと思うので、`hibernated_or_retired_target?`としてはどうでしょうか。

あと、メソッド内の処理は`@target == 'hibernated' || @target == 'retired'`だけで大丈夫だと思います！(`true if`が不要だと思います。)

2022-09-19 10:26 UTC, yuma-matsui commented on test/system/users_test.rb
> +
今回のテストの場合、URLについては愚直に`href: '/users?target=hibernated'`のようにそのまま書いていく方が良いかなと思いました！

その方がテストを見た人が何をしているのかわかりやすいのではないかと思ったためです！

2022-09-19 10:30 UTC, yuma-matsui commented on test/system/users_test.rb
> +  end
上に記載させていただきましたが、`href: '/users?target=hibernated'`、`href: '/users?target=retired'`と一つ一つ書いていく方が良いと思いました。

2022-09-19 10:35 UTC, yuma-matsui requested changes
@Nabegon 
お疲れ様です！
修正ありがとうございます。

確認、コメントさせていただきましたのでご確認をお願いします🙏

2022-09-28 05:37 UTC, Nabegon commented
@yuma-matsui さん、お疲れ様です。時間かかってしまいすみません💦再レビューありがとうございました！お手数ですが、お手すきの際に再度ご確認のほどよろしくお願いします🙏

2022-09-28 10:35 UTC, yuma-matsui approved these changes
@Nabegon 
修正ありがとうございます！！
LGTMです🙆‍♂️

2022-10-07 07:27 UTC, Nabegon commented
@yuma-matsui さん、お疲れ様です！返信遅くなり申し訳ありません💦ご確認いただきありがとうございました！！

2022-10-07 07:28 UTC, Nabegon commented
@komagata さん、お疲れ様です！チームレビュー通りましたので、ご確認いただきたいです。よろしくお願いします🙏

2022-10-10 15:59 UTC, komagata commented on app/controllers/api/users_controller.rb
> +  end
```
@target.in? ['hibernated', 'retired']
```

でも同じなので、見栄え的にはメソッドにしなくても良いかな〜？と思いました。

2022-10-22 09:19 UTC, Nabegon commented on app/controllers/api/users_controller.rb
> +  end
ご確認ありがとうございます！返信遅くなりすみません。こちら、修正します。

2022-10-22 09:50 UTC, Nabegon commented on app/controllers/api/users_controller.rb
> +  end
お疲れ様です。`@target.in? ['hibernated', 'retired']`だと`['hibernated', 'retired']`が引数として渡せずsyntax errorとなるため、
`@target.in?(['hibernated', 'retired'])` と書きました。
オブジェクト判定の効率的な書き方を知れて勉強になりました、ありがとうございます🙏

参考: https://apidock.com/rails/Object/in%3F

2022-10-22 11:12 UTC, Nabegon commented
@komagata さん、お疲れ様です。ご指摘いただいた箇所を修正しましたので、再度ご確認のほどよろしくお願いします！

2022-10-24 22:18 UTC, komagata commented on app/controllers/users_controller.rb
> +    @target == 'hibernated' || @target == 'retired'
```ruby
@target.in? ['hibernated', 'retired']
```

みたいに書けるので、メソッドにする必要がないかもです。（そのままのrubyの方が他のプログラマーにとっては読みやすいと思うので）

2023-02-21 15:39 UTC, mono-nobe commented
デグレが生じていないことを確認

### 休会

<img width="1415" alt="スクリーンショット 2023-02-22 0 36 57" src="https://user-images.githubusercontent.com/94843475/220390516-219e96bd-7616-424d-bb02-5393c58f041b.png">

### 退会

<img width="1410" alt="スクリーンショット 2023-02-22 0 37 08" src="https://user-images.githubusercontent.com/94843475/220390383-ca8aed64-ded7-4d70-b0cc-b0591786974f.png">
c4-fb2d-4307-9c2b-3db6a67f85d9.png">

### 全員

<img width="1428" alt="スクリーンショット 2023-02-22 0 37 26" src="https://user-images.githubusercontent.com/94843475/220390399-ccd03001-5e27-4bf3-905a-c933623b34ae.png">

2023-02-21 15:39 UTC, mono-nobe commented
@komagata 
修正しましたので、レビューをお願いします！

2023-02-25 08:53 UTC, komagata commented on test/system/users_test.rb
> +  test 'if the user is not admin or mentor, the user cannot see retired and hibernated tabs' do
```suggestion
  test 'user can not see retired and hibernated tabs if the user is not admin or mentor' do
```

こちらの方が英語的にも、他と統一する意味でもわかりやすいかな〜と思いました。

2023-03-05 07:08 UTC, mono-nobe commented on test/system/users_test.rb
> +  test 'if the user is not admin or mentor, the user cannot see retired and hibernated tabs' do
修正しました！

2023-03-05 07:08 UTC, mono-nobe commented
@komagata 
レビューありがとうございます！
修正しましたので、ご確認をお願いします！

2023-03-11 13:07 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-03-11 13:08 UTC, komagata commented
@mono-nobe テストが落ちているようなので確認をお願いします〜。

2023-03-19 13:23 UTC, mono-nobe commented
@komagata 
テスト通しましたので、ご確認をお願いします！

2023-03-22 11:59 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-03-22 11:59 UTC, merged