メンターが提出物のコメントフォームから確認okにした時のトーストが正しく表示されるようにした
fjordllc/bootcamp pull request #5545
Opened 2022-09-19 04:26 UTC by keiz1213

2022-09-19 10:53 UTC, keiz1213 commented
@yuma-matsui 
何度もすみません🙏こちらのissueは@yuma-matsui に確認していただくと話が早いかなと思い依頼させていただきました。
全く急いでませんのでよろしくおねがいします🙏

2022-09-19 12:23 UTC, yuma-matsui commented on app/javascript/comments.vue
> +      this.createComment({ toastMessage: null })
createCommentの引数に`{ toastMessage = null }`でデフォルト引数を与えているので、ここの引数は不要だと思います！

2022-09-19 12:51 UTC, yuma-matsui commented on app/javascript/comments.vue
> -      }
postCommentとして処理を切り出した理由は何故でしょうか🤔?

2022-09-19 12:53 UTC, yuma-matsui requested changes
@keiz1213 
コメントしましたのでご確認をお願いします！！
わかりづらかったらいってください😅

2022-09-19 12:54 UTC, yuma-matsui commented on app/javascript/comments.vue
> -      }
postCommentとして処理を切り出した理由は何故でしょうか🤔?

2022-09-19 13:54 UTC, keiz1213 commented on app/javascript/comments.vue
> -      }
コメント欄の「確認okにする」を押すと、`commentAndCheck`が動くのですが、その中で`createComment`を呼び出しています。この時の`createComment`内の`checkProduct`が動いてしまうことがバグの原因だと判断しました。(提出物に担当者がいない場合に「確認okにする」を押すと提出物が確認済みとならず、「担当になりました」が表示されていた)

なので`checkProduct`を`createComment`から分離させ、`commentAndCheck`で呼び出されないようにし、「コメントする」が押されたときだけ呼び出されるようにするために新しく`postComment`を切り出した感じです。

色々考えたのですがこうするしかないかな〜と思ったのですがどうでしょう？

2022-09-19 13:55 UTC, keiz1213 commented on app/javascript/comments.vue
> +        this.checkId === null
なるほどです。こちらcheckable.jsのcomputedに切り出してみました！

2022-09-19 13:56 UTC, keiz1213 commented on app/javascript/comments.vue
> +      this.createComment({ toastMessage: null })
なるほどです。こちら引数を削除しました！

2022-09-19 13:56 UTC, keiz1213 commented
@yuma-matsui 
レビューありがとうございます！修正しましたので確認お願いいたします！

2022-09-20 11:03 UTC, yuma-matsui commented on app/javascript/comments.vue
> +      this.createComment({})
createCommentの呼び出しは引数なしで大丈夫です！

2022-09-20 11:31 UTC, yuma-matsui commented on app/javascript/comments.vue
> +      this.createComment({})
すみません....こちら僕が勘違いをしておりまして、`createComment()`で正常に動作すると思っていたところうまく動きませんでした🙏

調査したところ、createCommentのメソッド定義において引数に分割代入を使用しているため、引数を省略してしまうとエラーになってしまうようです。

引数を省略したい場合は空のオブジェクトを与えるっていうルールはメソッドを使う人にとって面倒だと思うので、createComment自体の実装を変更していただきたいと思います🙏

修正案は上記に記載してあります！

2022-09-20 12:30 UTC, yuma-matsui commented on app/javascript/comments.vue
> -      }
ありがとうございます！！
切り出しの理由について理解できました。

結論自分の考えが誤っていたので、このままの実装で大丈夫です🙆‍♂️

ローカル環境でif以下の該当の処理をcreateCommentに含めた実装でテストを回したところ、テストが通ったため、処理を切り出さなくてもいけるのでは🤔?と考えましたが、実際にブラウザで操作して確かめたところ、「担当になりました！」となる時と「提出物を確認済みにしました！」になる時がありました。

この原因について調査したところ、「担当になりました！」と「提出物を確認済みにしました！」が目に見えないくらいの速さで連続して表示されており、「提出物を確認済みにしました！」については非同期処理になっているので、「担当になりました！」の後に表示される時があり、このためテストも通ってしまっていたようです。

長くなりましたが自分の思い違いでしたので今のままの実装でOKです〜
お騒がせしました。

2022-09-20 12:31 UTC, yuma-matsui commented on app/javascript/comments.vue
> +      if (this.isUnassignedAndUnchekedProduct) {
分かりやすいメソッド名でいいとおもます🙆‍♂️

2022-09-20 12:32 UTC, yuma-matsui commented on app/javascript/checkable.js
> +    isUnassignedAndUnchekedProduct() {
メソッド名がわかりやすくて良いと思いました〜🙆‍♂️

2022-09-20 12:34 UTC, yuma-matsui requested changes
確認しました！
@keiz1213 さんの実装ではなく過去の自分の実装についてで申し訳ないのですが、修正依頼をさせていただきましたのでご確認をお願いします🙆‍♂️

2022-09-20 13:31 UTC, keiz1213 commented on app/javascript/comments.vue
> -      }
>担当になりました！」となる時と「提出物を確認済みにしました！」になる時がありました。

確かに、開発環境で動作確認している時に「担当になりました！」となる時と「提出物を確認済みにしました！」になる時がありました。変更前のcommentAndCheckではcheckのトーストとcheckProductのトーストが２つ呼び出されていたのでそのような動きになっていたんでしょうね。
色々調査していただきありがとうございます！🙏

2022-09-20 13:32 UTC, keiz1213 commented on app/javascript/comments.vue
> +      this.createComment({})
なるほどです。こちら提案いただいた内容で修正しました！

2022-09-20 13:33 UTC, keiz1213 commented
@yuma-matsui 
提案頂いた内容で修正しました！色々調査＆提案いただきありがとうございます🙏確認お願いいたします。

2022-09-20 13:56 UTC, yuma-matsui approved these changes
@keiz1213 
修正ありがとうございます！
LGTMです🙆‍♂️

2022-09-22 05:30 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-22 05:30 UTC, merged