最後の回答から1週間経過したら質問を投稿した人に通知されるようにした
fjordllc/bootcamp pull request #5587
Opened 2022-09-24 18:40 UTC by keiz1213

2022-10-02 14:00 UTC, keiz1213 commented on app/notifiers/discord_notifier.rb
> +    webhook_url = params[:webhook_url] || Rails.application.secrets[:webhook][:admin]
今回の変更とは関係ありませんが、`tomorrow_regular_event`メソッドのwebhook_urlの取得方法を変更しました。変更前の取得方法では、`daily_controller`が動いた時にエラーが起きてしまうためです。(定期イベント機能についてはまだ本番環境でリリースされておらずコメントアウトされているらしいです。)

こちらのPR #5542 にて`secrets`から取得する方法に変更することが駒形さんから許可が出ており、本PRでもそのように変更しました。

2022-10-04 03:29 UTC, keiz1213 commented
@pachikuriii 

お疲れさまです！こちらレビュー頂いてもよろしいでしょうか？全く急いでないのでいつでも大丈夫です😄ご都合が合わない等ありましたらお気軽にご連絡ください😄

2022-10-04 07:04 UTC, pachikuriii commented
@keiz1213 
おつかれさまです〜☕️！レビューのご依頼ありがとうございます〜！
2,3日以内に完了できれば…と思っているのですが、そんなスケジュール感でもよければ
是非レビューさせていただけると嬉しいです💪🏻

2022-10-04 08:34 UTC, keiz1213 commented
@pachikuriii 
2〜3日以上かかっても全然大丈夫ですのでよろしくお願いします！🙏

2022-10-07 13:44 UTC, pachikuriii reviewed
@keiz1213 
こんばんは🌛
ナカムラさん、大変お待たせしました🙏ばっちり、動作確認できました🎉新たな機能を作られるにあたってメソッドやテストの新規作成にしっかり対応されていてすごいなぁ…と思いました！！！

レビューさせていただく過程で通知のしくみや類似のPRがどう対応してきたか？など私なりに調べてみましたが、間違っている点などありましたら教えていただけるとうれしいです〜 🙏
よりよいコードになりますように…と思いつつ、今のわたしが出来る範囲でレビューさせていただきました…👀🌻

2022-10-07 13:44 UTC, pachikuriii commented on app/mailers/notification_mailer.rb
> +    @user = @receiver
他のメソッドではどれも`@user = @receiver`とされてはいるんですが、`@user`への代入はせず、直接`@receiver`を参照するようにした方がコードが読みやすくなりそうだなぁ〜と思いました🙌

2022-10-09 09:01 UTC, keiz1213 commented on app/models/question.rb
> +    def notify_of_pending
確かにそのような場合も考慮すると、ちょっと抽象的すぎる気がしました💡色々考えたのですが、提案いただいたメソッド名を参考に修正しました(わかりやすさを重視するとちょっと長いのもしょうがないかな？と思いました)。

2022-10-09 09:01 UTC, keiz1213 commented on app/models/question.rb
> +    answers.last.updated_at.since(1.week) == Date.current.to_time
確かにタイポの修正程度でカウント処理を後ろ倒しにするのは良くないですね💡なのでこちらを`created_at`基準でカウントするように修正しました。

方針としては、`last_answer`メソッドを追加して最後の回答オブジェクトを取得し、その`created_at`を計算の起点に使うようにしました。メソッドを追加した理由は`updated_at`を`created_at`に変更するだけだと「正確な最後の回答」が取得できないためです。

2022-10-09 09:01 UTC, keiz1213 commented on app/mailers/notification_mailer.rb
> +    @user = @receiver
この@userはメールのビューで使うため代入しています👍
自分も最初`@receiver`でいいかな？と思ったのですが、こちらを代入せずに書くとメールが送信されなくなるのでこのままにしています💡

app/views/notification_mailer/a_week_after_last_answer.html.slim

2022-10-09 09:02 UTC, keiz1213 commented on test/fixtures/questions.yml
> +  updated_at: <%= Date.current.to_time - 1.week %>
確かに他のPRでもそのようなことが書いてありましたね💡見逃していました😅こちらご提案頂いたように、テスト内でデータを作成するように修正いたしました。

2022-10-09 09:02 UTC, keiz1213 commented on test/fixtures/answers.yml
> +  updated_at: <%= Date.current.to_time - 1.week %>
こちらも提案頂いたように、テスト内でデータを作成するように修正いたしました👍

2022-10-09 09:05 UTC, keiz1213 commented
@pachikuriii 

とても丁寧なレビューありがとうございます！😄そして修正が遅くなってすみません🙏
ご提案頂いた内容を参考に修正してみましたので、お手すきの際にご確認お願いいたします😄
全然急いでないのでゆっくりで大丈夫です👍

2022-10-09 09:05 UTC, keiz1213 commented
@pachikuriii 

とても丁寧なレビューありがとうございます！😄そして修正が遅くなってすみません🙏
ご提案頂いた内容を参考に修正してみましたので、お手すきの際にご確認お願いいたします😄
全然急いでないのでゆっくりで大丈夫です👍

2022-10-12 04:19 UTC, sinsoku commented on app/models/question.rb
> +    last_answer.created_at.since(1.week) == Date.current.to_time
これは今日の0:00を返す処理ですが、意図した挙動でしょうか？

```ruby
Date.current.to_time
#=> 2022-10-12 00:00:00 +0900
```

この意図が正しいなら、 [Time#beginning_of_day](https://api.rubyonrails.org/classes/Time.html#method-i-beginning_of_day) の方が分かりやすいかなと思いました。

```ruby
Time.current.beginning_of_day
#=> Wed, 12 Oct 2022 00:00:00.000000000 JST +09:00
```

2022-10-12 06:47 UTC, pachikuriii reviewed
@keiz1213 
たいへんお返事がおそくなり申し訳ないです😭
修正いただきありがとうございます・・・！🌸

2022-10-12 06:47 UTC, pachikuriii commented on test/system/notification/questions_test.rb
> +  test 'notify to questioner when a week has passed since last answer' do
私の手元だとこのテストが必ず落ちてしまいまいまして...ナカムラさんのお手元ではいかがでしょうか・・・？

```
Error:
Notification::QuestionsTest#test_notify_to_questioner_when_a_week_has_passed_since_last_answer:
Capybara::ExpectationNotMet: expected to find css ".card-list-item.is-unread" at least 1 time but there were no matches
    test/system/notification/questions_test.rb:308:in `block in <class:QuestionsTest>'
```
![image](https://user-images.githubusercontent.com/58751858/195269029-c131d6f2-f187-4e29-bf56-01c03eeddd53.png)

2022-10-13 03:14 UTC, keiz1213 commented on app/models/question.rb
> +    last_answer.created_at.since(1.week) == Date.current.to_time
コメントありがとうございます！🙌

>これは今日の0:00を返す処理ですが、意図した挙動でしょうか？

この挙動は意図していなくて、`0:00`を返す処理ということを知らずに書いてました・・・。
そして再度手元で再現してみたのですが期待した結果にならないことがわかりました・・・。
テストが通っていたのは、テストデータの時刻が全て`0:00`で揃っていたので通ってたみたいで不備に気づけませんでした。本番環境ではこのように時刻が揃っていることはありえないので条件式をdateオブジェクトで比較するように変更しました。

2022-10-13 03:14 UTC, keiz1213 commented on app/models/question.rb
> +  end
今回追加したメソッドはオブジェクトを返すためだけのものなのでprivateにする必要が無いかなと個人的に思いました💡

2022-10-14 07:45 UTC, pachikuriii approved these changes
@keiz1213 
修正をありがとうございます。

ナカムラさんのPRは確認手順の書き方がとても丁寧で、今後真似していきたいです☺️
また`a_week_after_last_answer?`での条件式について、レビューの際に時刻へ意識が及んでおらず失礼しました🥲経過日時などがキーになる機能を実装する時に意識しておかなければいけないポイントについて、レビューさせていただいたことで学ばせていただきました👀

わたしからは、Approveとさせていただきます✨

2022-10-14 07:45 UTC, pachikuriii commented on test/system/notification/questions_test.rb
> +  test 'notify to questioner when a week has passed since last answer' do
@keiz1213 
わたしがレビューする立場にもかかわらず、こうして見立てをくださりありがとうございます😭おっしゃるとおり、webpackerでコンパイルが上手くいっていなかったようで`bin/rails webpacker:clobber`とすることで正常にテストが通ることを確認しました。

2022-10-15 10:55 UTC, keiz1213 commented
@pachikuriii 
確認ありがとうございます！とても丁寧にレビューいただき勉強になりました😄そして少しでもお役に立てたなら幸いです😄お互いアドバイスし合いながらチーム開発乗り切って行きましょう〜！

@komagata 

こちらチームの方からapproveいただきましたのでご確認お願いいたします！

2022-10-17 09:15 UTC, komagata requested changes

2022-10-17 09:15 UTC, komagata commented on app/models/notification.rb
> +    a_week_after_last_answer: 21
「1週間後」というのはこの通知の本質ではなく、
「ベストアンサーが選ばれていない」ことを通知するものなので、そういった意味の名前にしたいです。

1週間後は本質ではないので、2週間後に変更されるかもしれませんし、頻繁に変わりやすい内容になっています。

2022-10-18 10:28 UTC, keiz1213 commented on app/models/notification.rb
> +    a_week_after_last_answer: 21
なるほどです💡こちら修正いたしました。

その他、仕様変更に対応しやすいように

- コード全体で「1週間後」という文言を使わず、「一定期間」という文言を使うようにしました
- Answerに一定期間経過したかどうかを判定するメソッドを追加しました。

ご確認よろしくお願いいたします。

2022-10-24 21:16 UTC, komagata commented on app/models/notification.rb
> +    not_yet_chosen_correct_answer: 21
極力簡潔な名前がいいので`no_corrent_answer`とかはどうでしょうか？

2022-10-24 21:16 UTC, komagata commented on app/models/answer.rb
> +  def certain_period_has_passed?
このメソッドのテストはありますか？

2022-10-27 13:52 UTC, keiz1213 commented on app/models/notification.rb
> +    not_yet_chosen_correct_answer: 21
なるほどです💡
難しく考えすぎていたかもしれません。確かにその名前が簡潔で良いと思いました。
提案いただいた内容で修正しました。

2022-10-27 14:13 UTC, keiz1213 commented on app/models/notification.rb
> +    not_yet_chosen_correct_answer: 21
すみません一応確認ですが、`no_corrent_answer `ではなく`no_correct_answer`が正しいですよね？その前提で修正しました。

2022-10-31 05:03 UTC, komagata commented on app/models/notification.rb
> +    not_yet_chosen_correct_answer: 21
@keiz1213 すみません、タイプミスでした〜

2022-10-31 05:15 UTC, komagata commented on app/models/question.rb
> +  end
@keiz1213 

判断として間違ってないと思いますが、下記の文章だと意味が違っちゃうかも？

> 今回追加したメソッドはオブジェクトを返すためだけのものなのでprivateにする必要が無いかなと個人的に思いました💡

`last_answer`がなぜpublicなのかというと
「他の用途でも便利に使えそうな汎用的なメソッドだから」
だと思います。

2022-10-31 05:15 UTC, komagata commented on app/models/question.rb
> +  end
@keiz1213 そして、publicなメソッドであればテストが必要になります〜

2022-10-31 13:29 UTC, keiz1213 commented on app/models/question.rb
> +  end
@komagata 

>「他の用途でも便利に使えそうな汎用的なメソッドだから」

なるほどです。privateは安全性を高めるためにのみ必要だと思っていました。確かに外から呼び出せたら便利です。
そしてこちらのテストも追加いたしました。ご確認お願いいたします🙏

2022-11-07 00:45 UTC, komagata requested changes
conflictの修正をお願いします〜

2022-11-09 15:35 UTC, keiz1213 commented
@komagata 
コンフリクトの修正完了しました。mainにおいてdaily_controllerに変更が加えられていたためその変更と統一性を持たせるため1点変更を加えました。

以前までは通知処理をQuestionのクラスメソッドで定義しそれをdaily_contorollerで呼び出す形でしたが、今回の変更に伴いそのクラスメソッドを削除し、daily_contoroller内のプライベートメソッドで定義して呼び出すように変更しました。

度々申し訳ありませんがご確認お願いいたします。

2022-11-11 06:40 UTC, komagata commented
@keiz1213 

> 以前までは通知処理をQuestionのクラスメソッドで定義しそれをdaily_contorollerで呼び出す形でしたが、今回の変更に伴いそのクラスメソッドを削除し、daily_contoroller内のプライベートメソッドで定義して呼び出すように変更しました。

おっと、controllerのprivateメソッドで処理するのはとりあえずな感じのやり方で、モデルクラスのメソッドにする方が望ましい感じです〜（Fat Controller）

2022-11-11 08:30 UTC, keiz1213 commented
@komagata 

なるほどです。Fat Controllerという考え方があることは知りませんでした。通知処理をQuestionクラスで定義し、それをdaily_controllerから呼び出すように修正しましたのでご確認ください。

2022-11-14 14:02 UTC, komagata commented on test/models/answer_test.rb
> +    assert answer.certain_period_has_passed?
時間関連のテストは実行日時やタイミングによってFlakyなテストになりやすいので、travel_toなどを使って時間を固定してやるのがいいと思います〜

2022-11-19 06:26 UTC, keiz1213 commented
@komagata 

>時間関連のテストは実行日時やタイミングによってFlakyなテストになりやすいので、travel_toなどを使って時間を固定してやるのがいいと思います〜

なるほど、勉強になります。
ご指摘いただいた点を参考に修正致しました。ご確認お願いいたします。

2022-11-21 06:25 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-11-21 06:26 UTC, merged