管理者がアドバイザーの所属企業を変更できない
fjordllc/bootcamp pull request #5623
Opened 2022-10-03 12:36 UTC by lanactindi

## Issue

- #5589 

## 概要

管理者でログインし、アドバイザーユーザーの個別ページに行き、登録情報を管理者権限で変更できませんでした。

## 確認方法

1. `bug/fix-bug-cannot-update-company`をローカルに取り込む
2. `rails s`で起動する
3. アドミンとしてログインして、`http://localhost:3000/admin/users/1033491174/edit` にアクセスする
4. 「所属企業」で別の会社を選んでください。
5. 「変更する」ボタンをクリックしてください。
6. 「ユーザー情報を更新しました。」が表示された後で`http://localhost:3000/admin/users/1033491174/edit`にもう一度アクセスしてください。
7. 「所属企業」がアップデートしたかどうかを確認してください。

## 変更前
「所属企業」を変更できなかったです。
## 変更後
「所属企業」を変更できるようになりました。

2022-10-03 12:41 UTC, lanactindi commented
@keiz1213 すみませんが、こちらをレビューいただいてもよろしいでしょうか。

2022-10-04 13:12 UTC, keiz1213 reviewed
お疲れさまです！

動作確認できました！

最初は「なぜ今回の修正でバグが解消できるのだろう？」と思っていましたが、よくよく考えてみると管理者でアドバイザーの登録情報変更ページにアクセスすると、44行目と51行目のどちらもtrueになってしまってますね。
見た目上は全く変化ないですが内部的に`users/form/company`が2重に呼び出されていてうまく更新処理が動いていなかったのですね。勉強になりました✍️

そこで1つ思ったのですが、このようなわかりにくいバグを再び発生させないためにもテストを追加したほうがより完成度が上がるような気がしましたがいかがでしょうか？

2022-10-05 05:18 UTC, lanactindi commented
@keiz1213 コメントありがとうございました。
承知しました。テストを追加したので再度レビューお願いします。

2022-10-05 09:46 UTC, keiz1213 reviewed
テストの追加ありがとうございます！

1点コメントさせていただきました。ご確認ください🙏

2022-10-05 09:46 UTC, keiz1213 commented on test/system/admin/users_test.rb
> +    user = users(:kensyu)
このテストでは「管理者が研修生の所属企業を更新できる」ことをテストしていますね。
確かに今回の変更ではこのテストは必要と思います。ですが今回のissueの目的は「管理者が`アドバイザー`の所属企業を更新できるようにする」ことだと思います。なので今回追加していただいたテストとは別に「管理者がアドバイザーの所属企業を更新できる」ことを担保するテストを追加する必要があると思います。

2022-10-05 10:16 UTC, lanactindi commented
@keiz1213 コメントありがとうございました。
そうですね、間違ってしまいました。修正したので再度レビューお願い致します。

2022-10-05 10:48 UTC, keiz1213 reviewed
すみません🙏自分の言い方がわかりにくかったかと思いますが、今回は研修生用の条件式を変更していますのでそちらのテスト(修正前のテスト)も必要だと思いました。

なので

- 「管理者は研修生の所属企業を更新できる」
- 「管理者はアドバイザーの所属企業を更新できる」

この2つのテストが必要だと思います。

2022-10-05 11:12 UTC, lanactindi commented
> すみません🙏自分の言い方がわかりにくかったかと思いますが、今回は研修生用の条件式を変更していますのでそちらのテスト(修正前のテスト)も必要だと思いました。
> 
> なので
> 
> * 「管理者は研修生の所属企業を更新できる」
> * 「管理者はアドバイザーの所属企業を更新できる」
> 
> この2つのテストが必要だと思います。

なるほど、わかりました。先ほどは勘違いしました。
両方テストを追加されました。ご確認お願いします。

2022-10-05 12:44 UTC, keiz1213 approved these changes
テストの追加ありがとうございます！僕の方からはapproveさせていただきます！
最後に一点細かいですが、ご自身を`assignees`に登録したほうが良いと思います😄

2022-10-06 01:25 UTC, lanactindi commented
> テストの追加ありがとうございます！僕の方からはapproveさせていただきます！ 最後に一点細かいですが、ご自身を`assignees`に登録したほうが良いと思います😄

ありがとうございました。assignします。

2022-10-06 01:26 UTC, lanactindi commented
@komagata 駒形さん、こちらをレビューしていただいてもよろしいでしょうか。

2022-10-06 18:52 UTC, komagata requested changes

2022-10-06 18:52 UTC, komagata commented on test/system/admin/users_test.rb
> +    assert_equal('Fjord Inc.', first('span', text: 'kensyu（Kensyu Seiko）').ancestor('tr').find(:xpath, 'td[4]').text)
HTMLや順番が少しでも変わると動かなくなるセンシティブなテストになっているので別の方法で確かめていただけるとありがたいです〜。（本体のHTMLにテストのためだけのクラスを追加してもOKなので）

（例えば、ユーザーのプロフィールページに入って所属企業を確かめるとか、DBを直接見て確かめるなどです）

2022-10-06 18:52 UTC, komagata commented on test/system/admin/users_test.rb
> +    assert_equal('Fjord Inc.', first('span', text: 'senpai（Senpai Ichiro）').ancestor('tr').find(:xpath, 'td[4]').text)
上記と同じくです。

2022-10-07 07:54 UTC, lanactindi commented
@komagata コメントありがとうございました。
修正したので再度レビューお願いします。

2022-10-10 16:18 UTC, komagata approved these changes
確認させて頂きました。ありがとうございます。OKです〜🙆‍♂️

2022-10-10 16:18 UTC, merged

2022-10-19 06:38 UTC, komagata commented
@lanactindi こちら本番環境で動作することを確認しました。

2022-10-19 07:10 UTC, lanactindi commented
@komagata ありがとうございました。closeします！