バリデーションエラーのバグの解消
fjordllc/bootcamp pull request #5624
Opened 2022-10-04 13:28 UTC by shirotamaki

## Issue
 
 - #5588 
 
 ## 概要
ブックマークを同時に登録するなどの操作によりUserが重複してしまい、バリデーションエラーが発生するバグがありました。[エラーログ詳細](https://github.com/fjordllc/bootcamp/issues/5588)
ブックマークの保存を実行した時、直前で既にUserが存在しないか調べることで、バリデーションエラーが発生しないように修正しました。
 
 ## 確認方法
 
 1. ブランチ`bug/fix-validation-failure`をローカルに取り込む
 2. `bin/rails s`でローカル環境を立ち上げる
 3.  任意の日報へアクセスする。`http://localhost:3000/reports/:id`
 4. 同じアカウントで同じ日報へアクセスする
 5. `Bookmark`をクリックし同時に登録できないことを確認する
 6. `400 Bad Request` が返ってくることを確認する

![image](https://user-images.githubusercontent.com/65638955/193830546-41a394cd-5f4f-4814-97a6-dec7cdc8b194.png)

2022-10-04 13:40 UTC, shirotamaki commented
@siroemk 
お疲れ様ですー！こちらのレビューをお願いできますでしょうか？
お手すきの際よろしくお願いします〜🙏

2022-10-06 01:54 UTC, siroemk commented
@shirotamaki 
お疲れ様です〜！
issueのやりとりや日報などを拝見しました👀
今回書いていただいたコードは「バリデーションエラーの有無」で挙動を分けていると思います。

komagataさんが仰っているのはそうではなくて、「current_userが既にそのページをbookmarkしているかチェックして、bookmarkしていない時だけ追加してほしい」という意味なのでは...？と思いました。ご確認いただけますでしょうか🙌

あと、バグ修正なので、今後同じバグが起きないようにテストがあった方が良いかもと思いました🙆‍♀️

2022-10-07 00:53 UTC, siroemk commented
@shirotamaki 
かしこまりました！いいですね〜💪😊
ちょっと先なんですが、来週の12日（水）12:00〜13:00はいかがですか？
（前後に予定があるので1時間でサクッとやりたいです🙏）
ご確認お願いします！

2022-10-07 07:01 UTC, komagata commented
@shirotamaki (CC: @siroemk )

> 実際にコードでどのように表現すればよいのかロジックが浮かびません...

こちら、これだと @siroemk さんに答えを聞くことになってしまうので、もうちょっと自身で考えていただきたいです。
このレベルの内容が自分で書くことができないとこの先に進むのは難しいように思います。

日本語で書いてある内容をそのままRubyにする感じだと思うのですが、どういったところがわからないでしょうか？

2022-10-07 10:48 UTC, shirotamaki commented
@komagata  (CC: @siroemk )
本日改めて見直したところ要件を満たすコードが書けました。先ほど修正したコミットをpushしCIもパスしました。
（issueの要件は満たしているとは思いますが、もしおかしい点ありましたらご指摘いただけると幸いです）

今回のissueですが、1週間ほど取り組み進捗が出せていなかったため、つい気持ちが焦ってしまい安易にペアプロを依頼してしまいました。siroemkさん、時間調整などご面倒お掛けし申し訳ありません。テストはこれから取り組みますので、完成したら改めてレビュー依頼出させていただきます。

引き続きどうぞよろしくお願いします。

2022-10-09 04:58 UTC, shirotamaki commented
@siroemk 
お疲れ様です！
レビュー内容を見直し修正いたしました。お手すきの際ご確認お願いいたします🙏

2022-10-10 11:19 UTC, shirotamaki commented
@siroemk
お疲れ様です！何度もすいません...🙇‍♂️
先ほどCIをパスできましたのでレビュー依頼出させていただきます！
お手すきの際ご確認お願いいたします🙏

2022-10-11 00:17 UTC, siroemk commented
@shirotamaki 
ご連絡ありがとうございます！確認しますね〜😊

2022-10-12 06:05 UTC, siroemk requested changes
@shirotamaki 
大変長らくお待たせしました〜！
いくつかコメントや質問を書いたのでご確認ください🙆‍♀️

2022-10-12 07:34 UTC, shirotamaki commented on test/fixtures/pages.yml
> +page12:
当初、既存のデータを利用する方法も検討したのですが、`fixtures`へ新しくデータを加えた方が良いのではないか？と思ったのが理由です。例えばreportの場合ですが、以下のtitleやdescriptionの内容だけで何をテストしているかがわかるので良いと思い、新しく追加する方法を選択しました。

```rb
report74:
  user: kimura
  title: "ブックマークボタンのテスト用"
  emotion: 2
  description: |-
    ブックマークボタンのテストです。
  reported_on: "2022-10-01"
```

しかし今回レビューをいただき見直した結果、システムテストを実行する際にtitleやdescriptionを意識することはないので追加のデータは不要だと思いました。既存のデータを使う方法へ変更します！✍️

2022-10-14 14:40 UTC, shirotamaki commented on test/models/bookmark_test.rb
> +    assert Bookmark.exists?(user: user, bookmarkable: report)
@siroemk 
`bookmarks_controller.rb`のcreateメソッドのテストを行う意図で追加しました。
その後テスト全体を見直し、こちらのテストは不要だと理解できました。削除いたします！

2022-10-14 14:43 UTC, shirotamaki commented on test/system/api/bookmark_test.rb
> +  test 'turn on/off bookmark button on report' do
@siroemk 
システムテストが不要であることが理解できました。システムテストは削除いたします！

2022-10-14 14:47 UTC, shirotamaki commented
@siroemk 
レビューいただきありがとうございます！
改めてテスト内容見直しました。不要なテストは削除しAPIテストを追加しています✍️ 
お手すきの際ご確認お願いいたします🙏

2022-10-17 05:17 UTC, siroemk approved these changes
@shirotamaki 
お疲れ様です〜！
修正いただき、ありがとうございます！
LGTMです🙆‍♀️

2022-10-17 11:30 UTC, shirotamaki commented
@siroemk 
ご確認ありがとうございます！とても勉強になりました😊✨

2022-10-17 11:31 UTC, shirotamaki commented
@komagata 
お疲れ様です！
チームメンバーよりApproveいただきました。ご確認お願いします🙏

2022-10-19 06:27 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-10-19 06:27 UTC, merged

2022-10-19 07:05 UTC, shirotamaki commented
@komagata
ご確認ありがとうございます！