みんなのブログ一覧ページを作成
fjordllc/bootcamp pull request #5646
Opened 2022-10-12 11:29 UTC by siso25

2022-10-12 12:37 UTC, siso25 commented
@AyakaTakashima 
お疲れ様です。
こちらのpull requestについて、ご都合の良いタイミングでレビューをお願いできますでしょうか。
お忙しいようでしたら他の方にお願いしますので、ご連絡いただければ幸いです。

2022-10-13 09:55 UTC, AyakaTakashima commented
@siso25 
ご連絡ありがとうございます！
こちらのレビューについてですが、今週末（金曜〜日曜）が予定がありまして、もしお受けしたとしてもすぐに取り掛かることができません😭
また、私自身、働きながら取り組んでいるので毎日19:00以降に少しずつ取り組んでいるのと、このissueがデカめなこともあってお返しするのが遅くなってしまいそうです😭（おそらく1週間以上かかってしまうかと💦）
お待たせするのが申し訳ないので、よろしければ日中も取り組まれている方にお願いいただけると助かります💦

2022-10-14 05:04 UTC, siso25 commented
@AyakaTakashima 
ご連絡ありがとうございます。承知しました。
他の方にお願いするようにいたします！

2022-10-16 08:05 UTC, siso25 commented
@shirotamaki 
お疲れ様です。
こちらのpull requestについてチームレビューをお願いできますでしょうか。
ご都合つかないようでしたら他の方にお願いしますので、ご連絡いただければ幸いです。

2022-10-16 12:10 UTC, shirotamaki commented
@siso
お疲れ様です！レビューご依頼いただきありがとうございます🙌
火曜までには確認できればと思いますが、お時間いただいても大丈夫でしょうか？

2022-10-17 13:39 UTC, shirotamaki commented
@siso25 
承知いたしました！確認させていただきます。よろしくお願いします🙏

2022-10-19 13:31 UTC, shirotamaki reviewed
@siso25 
お疲れ様です！お返事遅くなりすいません...🙏
動作確認取れました🙆‍♂️ 気になった点を2箇所ほどコメントさせていただきました。
ご確認お願いします！

2022-11-16 12:12 UTC, siso25 commented
@shirotamaki 
お疲れ様です。
遅くなりまして大変申し訳ありません。
いただいた内容を反映しましたので、ご確認をお願いいたします。

2022-11-16 12:47 UTC, shirotamaki approved these changes
@siso25 
修正ありがとうございました！LGTMです〜🙆‍♂️

2022-11-18 12:27 UTC, siso25 commented
@shirotamaki 
お忙しいところご確認ありがとうございました！

@machida 
お疲れ様です。
お手数ですが、デザインの確認をお願いいたします。

2022-12-03 06:05 UTC, machida commented
@siso25 デザイン了解ですー

2022-12-07 05:18 UTC, machida commented
@siso25 デザイン入れました！jsでエラーがあったので、それが解決されてる最新のmainを取り込みました。

手元で、

git pull --rebase origin feature/add-latest-articles-page

をお願いしますー

2022-12-07 12:03 UTC, siso25 commented
@machida 
ありがとうございます！お手数おかけしました。

@komagata 
こちらのレビューをお願いいたします。

2022-12-12 01:16 UTC, komagata requested changes

2022-12-12 01:16 UTC, komagata commented on app/controllers/latest_articles_controller.rb
> +class LatestArticlesController < ApplicationController
既にbootcamp内のブログの記事を表す`Article`モデルがあるので`LatestArticle`というモデルがあったら内部ブログの最新の記事だと見た人は勘違いするはずです。

ですので別の名前にした方がいいと思います。
また、データが溜まっていったらLatestでもないので、ExternalEntryとかそういう感じでいいのではないかとおもいます。

2022-12-20 17:39 UTC, komagata commented on app/models/external_entry.rb
> +  THUMBNAIL_SIZE = '88x88>'
外部のエントリーの画像をこちらで持つと容量など大変なので、画像のURLを持つだけなどの形の方がいいかもです〜

2022-12-24 10:33 UTC, siso25 commented
@komagata 
画像のURLのみ保存するようにして、表示時に外部から画像を取得するように変更しました。

2022-12-27 21:17 UTC, komagata requested changes

2022-12-27 21:17 UTC, komagata commented on db/migrate/20220913134610_create_latest_articles.rb
> +      t.string :url
必須のものにはnull: falseをつけた方がいいかもです〜

2022-12-27 21:17 UTC, komagata commented on test/models/external_entry_test.rb
> +  test 'thumbnail_url' do
```suggestion
  test '#thumbnail_url' do
```

2022-12-27 21:17 UTC, komagata commented on test/models/external_entry_test.rb
> +  test 'thumbnail_url' do
```suggestion
  test '#thumbnail_url' do
```

2022-12-28 11:37 UTC, siso25 commented
@komagata 
`title`と`url`にnot null制約を追加し、モデルのテスト名を修正しました。
お手数ですが、ご確認をお願いします。

2022-12-29 23:05 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-12-29 23:06 UTC, merged