初回公開時に通知が発行されるように修正
fjordllc/bootcamp pull request #5662
Opened 2022-10-20 08:28 UTC by hikarook94

## 概要
https://github.com/fjordllc/bootcamp/pull/5591 
こちらのPRの修正です。確認方法などはこちらのPRをご確認ください。

### 事象
お知らせをWIPで保存→公開というフローで操作するとお知らせの通知が発行されないという事象をステージング環境で確認しました。

### 修正内容
updateアクション実行時に`published_at`が`nil`から変更された時（＝初回公開時）に通知を発行する処理を追加しました。

2022-10-20 11:47 UTC, komagata requested changes
こちら再発を防ぐためのテストがあるといいかもです〜

2022-10-21 08:19 UTC, hikarook94 commented
@komagata 
ありがとうございます！テストを追加しました
ご確認よろしくお願いします🙏

2022-10-21 14:52 UTC, komagata approved these changes
テストの追加、大変ありがたいです〜！

2022-10-21 14:52 UTC, merged

2022-10-25 02:30 UTC, hikarook94 commented
@komagata @machida 
お疲れ様です！
こちらのPRについて、メンター権限が必要なため本番環境で動作確認をお願い出来ますでしょうか？

2022-10-25 17:20 UTC, komagata commented
@hikarook94 本番環境で動作することを確認しました。

2022-10-26 02:47 UTC, hikarook94 commented
@komagata 
ご確認ありがとうございます！