[アンケート機能]アンケートを作成できるようにした
fjordllc/bootcamp pull request #5690
Opened 2022-10-27 13:33 UTC by AyakaTakashima

# issue
[[アンケート機能]アンケートを作成できるようにしたい #4586](https://github.com/fjordllc/bootcamp/issues/4586)

# 概要
このPRでは、アンケートを作成できる機能を作りました。

本PRとは別に、下記のPRで質問を作成する機能が作られています。
[[アンケート機能]アンケート用の質問の一覧、作成、編集ができるようにしたい #5370](https://github.com/fjordllc/bootcamp/pull/5370)
上記のPRの説明もさせていただいた方が理解がしやすいと思いますので、簡単に説明させていただきます。

想定する使い方は下記のようになります。
＊ 1は、#5370 のPRで実装された機能です。
＊ 本PRは、2の機能を実装するPRとなります。

1.  質問を作る。（#5370 のPRで実装）
　例えば、下記の質問を作成する。
　- 質問A「好きな色はなんですか？」
　- 質問B「好きな言語はなんですか？」
　- 質問C「好きな食べ物はなんですか？」
2. 1で作った質問を組み立ててアンケートを作成する。（本PRで実装する機能）
　例えば、質問A、B、Cを使って、「好きなものに関するアンケート」というアンケートを作成する。

# ER図
今回のPRでは、`Survey`テーブルと`SurveyQuestionListing`テーブルを作成しています。
`SurveyQuestion`は、上記で記載した #5370 で作成されたテーブルです。
![image](https://user-images.githubusercontent.com/76944527/203032529-c56384c6-e794-4a26-8db1-3412e5058058.png)

# 確認方法
まず、下記のステップを行ってください。
1. ブランチ`feature/create_surveys`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. komagataでログインする

上記が完了しましたら、下記の確認をお願いいたします。

## ①アンケートの新規作成
1. 下記にアクセス
http://localhost:3000/surveys
1. 右上に表示されている「新規作成」をクリック
1.  タイトル、回答受付開始日、回答受付終了日、質問を選択する。
1. 「選択肢を追加」から質問を追加できることを確認する。
1. 追加した質問の下にある「削除」を押し、質問を削除できることも確認する。
1. 「保存」をクリックする

## ②アンケートのshowページの表示
1. 下記にアクセス
http://localhost:3000/surveys
1. ①で作成したアンケートのタイトルをクリックし、showページが表示されるか確認する。

## ③アンケートの編集
1. ②で表示したshowページにて、一番下「編集」をクリックする
1. 質問を追加、もしくは削除するなど、何かしら内容を変更する形で中身を編集する。
1. 「保存」をクリックする
1. 一覧ページに戻るので、先ほど編集したアンケートのタイトルをクリックし、showページを開く
1. 内容が変更されているのを確認する。

## ④アンケートの削除
1. ②で表示したshowページにて、一番下「編集」をクリックする
1. 一番下「削除する」をクリックする
1. 削除されているか確認をする。

## ⑤アクセス権限の確認
全てのページにおいて、管理者/メンターのみがアクセスできるようになっています。
1. メンターアカウントでログインし下記ページにアクセスできるか確認する。
    1. http://localhost:3000/surveys
    1. http://localhost:3000/surveys/new
    1. 先ほど自分で作成したアンケートのshowページ
    1. 先ほど自分で作成したアンケートのeditページ
2. メンター/管理者以外のアカウントでログインし、同じように上記のページにアクセスする。アクセス出来ないことを確認する。

# 変更前
完全に新機能のため、機能自体が存在していませんでした。
よって、変更前の画面はありません。

# 変更後
## index（アンケート一覧画面）
今日の日付が、`survey.start_at`〜`survey.end_at`の期間に入っていれば、「受付中」が表示されます。
`survey.start_at`が、今日の日付より未来であれば、「受付前」が表示されます。

![image](https://user-images.githubusercontent.com/76944527/208285334-0b387c39-c842-4d7c-8dd2-424b1285e159.png)

## show（作成したアンケートのプレビュー画面）
**注意：この画面は、プレビュー画面となっており、実際に生徒さんが回答できるフォームではありません。**
[![Image from Gyazo](https://i.gyazo.com/7b2a324ea55da6be1bf542021d6c5e70.gif)](https://gyazo.com/7b2a324ea55da6be1bf542021d6c5e70)

## new（アンケートの新規作成画面）
[![Image from Gyazo](https://i.gyazo.com/a2100da7e96111ee37eacaf4d926c819.gif)](https://gyazo.com/a2100da7e96111ee37eacaf4d926c819)

## edit（アンケート編集画面）
show画面の「編集」ボタンを押すとeditページになります。
[![Image from Gyazo](https://i.gyazo.com/cf5e5024c9236a7f3042dbb5a840d46b.gif)](https://gyazo.com/cf5e5024c9236a7f3042dbb5a840d46b)

# 補足
## db/fixturesについて
本PRでは、fixturesを追加しています。
アンケートのデータを作るには、質問がないと作れませんが、質問のfixturesがありませんでした。
そのため、今回のPRで質問のfixturesも作っています。

2022-11-20 09:59 UTC, AyakaTakashima commented
@machida 
お疲れ様です！
もうすぐでテストが書けそうな段階まで来ましたので、デザインをお願いしたいです。
よろしくお願いいたします🙇‍♀️

2022-11-20 14:20 UTC, machida commented
@AyakaTakashima 
デザイン了解ですー💪

2022-11-26 06:11 UTC, AyakaTakashima commented
@machida 
machidaさん、デザインありがとうございます！！！！
一つご相談したいことがありましてご連絡いたしました。
# 概要
machidaさんのcommit内容でslim lintのエラーが出ており、それに対応するとデザイン崩れが発生してしまいます。
どのように対応するか、お聞きしたいです。

下記に詳細を説明します。

# slimのエラー内容
slim lintで下記の二つのエラーが出ています。
```shell
> bundle exec slim-lint app/views -c config/slim_lint.yml
warning: parser/current is loading parser/ruby31, which recognizes3.1.2-compliant syntax, but you are running 3.1.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
app/views/surveys/show.html.slim:59 [W] RuboCop: Style/CombinableLoops: Combine this loop with the previous loop.
app/views/surveys/show.html.slim:75 [W] RuboCop: Style/CombinableLoops: Combine this loop with the previous loop.
```

どちらも同じ`Style/CombinableLoops: Combine this loop with the previous loop.`となっています。
同じループ処理が続いちゃってるよ！というエラーです。
```html
                            - survey_question.check_box.check_box_choices.each do |choice|　<!--ここと、-->
                              li.checkboxes__item
                                = f.check_box choice.choices, class: 'a-toggle-checkbox', id: "checkbox-#{choice.id}"
                                = f.label choice.choices, for: "checkbox-#{choice.id}"
                          - survey_question.check_box.check_box_choices.each do |choice|　<!--ここは合体できるのでは？-->
                            - if choice.reason_for_choice_required
                              .survey-additional-question
                                = f.label :title_of_reason_for_checkbox, survey_question.check_box.title_of_reason, class: 'a-form-label is-required'
                                .survey-questions-item__description
                                  .a-long-text.is-sm
                                    = simple_format(survey_question.check_box.description_of_reason)
                                .survey-additional-question__input
                                  = f.text_area :title_of_reason_for_checkbox, class: 'a-text-input js-warning-form'
```
`survey_question.check_box.check_box_choices.each do |choice|`という同じループ処理が、2回続いてしまっています。
commit内容を見ると、machidaさんのcommitで同じループ処理が追加されてしまっているようです。

私の方で、下記のように修正するとデザイン崩れが発生します。
```html
                      - if survey_question.format == 'check_box'
                        .survey-questions-item__checkboxes.checkboxes
                          ul.checkboxes__items
                            - survey_question.check_box.check_box_choices.each do |choice|
                              li.checkboxes__item
                                = f.check_box choice.choices, class: 'a-toggle-checkbox', id: "checkbox-#{choice.id}"
                                = f.label choice.choices, for: "checkbox-#{choice.id}"
                              - if choice.reason_for_choice_required
                                .survey-additional-question
                                  = f.label :title_of_reason_for_checkbox, survey_question.check_box.title_of_reason, class: 'a-form-label is-required'
                                  .survey-questions-item__description
                                    .a-long-text.is-sm
                                      = simple_format(survey_question.check_box.description_of_reason)
                                  .survey-additional-question__input
                                    = f.text_area :title_of_reason_for_checkbox, class: 'a-text-input js-warning-form'
```

# 修正前/修正後のデザイン比較
上記で説明したエラーに対応すると、下記のようにデザインが崩れてしまいます。
## 修正前
![image](https://user-images.githubusercontent.com/76944527/204074415-e993f8b1-edca-4306-90a1-c7d6dd149598.png)
![image](https://user-images.githubusercontent.com/76944527/204074421-7e3ccda8-018c-4ff5-9be2-1040dbfdc3d1.png)

## 修正後
![image](https://user-images.githubusercontent.com/76944527/204074445-2f228c3d-d7f2-4138-aab3-42526fefa2ad.png)
![image](https://user-images.githubusercontent.com/76944527/204074450-1f818c28-4ff5-4a23-aeae-9685523519c5.png)

内容は以上です。
対応については、下記のどちらの方がよろしいでしょうか？
1. デザインはこれでも問題ないので、私の方でループ処理を一回になるように修正する。
1. machidaさんの方で、もう一度デザインを当て直す。

ご確認いただけますと幸いです🙇‍♀️
よろしくお願いいたします🙇‍♀️

2022-11-28 11:47 UTC, machida commented
@AyakaTakashima メモの記入ありがとうございます🙏

2022-12-05 12:11 UTC, AyakaTakashima commented
@machida 
お疲れ様です！
先日お話しした点について修正しました！

また、下記のデザインが当たってなかった部分について、ご連絡があります。
![image](https://user-images.githubusercontent.com/76944527/205631069-e9d0cf55-83fe-454c-a760-9da97d45e903.png)

先日お伝えいただいた通り、idではなくclass名指定で割り当てようとしたのですが
調べたところ、choice.jsはidで紐付けを行わなくてはいけない様子でした。
クラス名で指定はできたのですが「同じ要素が複数ある」とエラーが起こったのと、公式に`If you pass a selector which targets multiple elements, the first matching element will be used. `の記載と、下記のコードも発見しました。
```js
  // Pass single element
  const element = document.querySelector('.js-choice');
  const choices = new Choices(element);
```
参考：
> document.getElementsByClassName は document.querySelector や document.querySelectorAll ととても似た動きをします。指定されたクラス名がすべてある要素のみが選択されます。

[Document\.getElementsByClassName\(\) \- Web API \| MDN](https://developer.mozilla.org/ja/docs/Web/API/Document/getElementsByClassName#%E8%A4%87%E6%95%B0%E3%81%AE%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%AE%E4%BE%8B)

上記のような感じで理解しておりまして、クラス名でchoices.jsを使うのはできないのかも？と思いました🧐
ですので、このままmachidaさんにお戻しさせていただいてデザインをつけていただいた方がいいかもしれません🙇‍♀️

2022-12-05 12:24 UTC, machida commented
@AyakaTakashima 調査ありがとうございますー。choicesのところは僕の方で見てみますー。

2022-12-05 12:46 UTC, AyakaTakashima commented
@machida 
ありがとうございます！すみません！一点勘違いしていたことがあったので訂正します。
「クラス名で指定はできたのですが「同じ要素が複数ある」とエラーが起こった」と記載しましたが、これは勘違いでした。
エラー文は`Expected one of the following types text|select-one|select-multiple`と出てきており、下記を参考にしました。
https://github.com/Choices-js/Choices/issues/922

クラス名は付与していたのですが、それが画面上にないと言われていたようです。
つまり、きちんと取得できていなかったようでした。

`app/javascript/choices-ui.js`へ追記していた内容を、`getElementByClassName`から`querySelector`に変更したところエラーが無くなりました。（エラーが発生していた時は`querySelector`のところを`getElementByClassName`で取得していた。）
```js
//app/javascript/choices-ui.js
  const elementAddedSelect = document.querySelector(
    'js-choices-added-select'
  )
  if (elementAddedSelect) {
    return new Choices(elementAddedSelect, {
      removeItemButton: true,
      allowHTML: true,
      searchResultLimit: 20,
      searchPlaceholderValue: '検索ワード',
      noResultsText: '一致する情報は見つかりません',
      itemSelectText: '選択',
      shouldSort: false,
      resetScrollPosition: false,
      renderSelectedChoices: 'always'
    })
  }
```
```html
<!--app/views/surveys/_survey_question_listing_fields.slim-->
= f.select(:survey_question_id, question_options_within_survey_question, { include_hidden: false }, { multiple: false, class: 'js-choices-added-select' })
```
上記のコードで、現在画面はこのようにデザインがあたってない状態なのですが、これでお渡ししても大丈夫でしょうか？🧐
![image](https://user-images.githubusercontent.com/76944527/205640424-a844e7a7-29d7-4e3b-84d1-ba66ddce1528.png)

2022-12-05 12:48 UTC, machida commented
@AyakaTakashima ありがとうございますー！！この状態で大丈夫です🙆‍♂️デザイン入れておきます💪

2022-12-05 12:57 UTC, AyakaTakashima commented
@machida 
ありがとうございます！！pushしておきました！
よろしくお願いいたします🥹

2022-12-07 05:50 UTC, machida commented
@AyakaTakashima デザイン入れましたー 最新の main を rebase したので手元で、

git pull --rebase origin feature/create_surveys

をお願いしますー

2022-12-07 11:27 UTC, AyakaTakashima commented
@machida 
ありがとうございます！！☀️
承知しました！！

2022-12-18 07:04 UTC, AyakaTakashima commented
@shirotamaki 
お疲れ様です！
デカめのPRで大変申し訳ないのですが、こちらのレビューをお願いしたいです🙇‍♀️
可能でしょうか？😭
もし難しそうでしたらほかの方を当たりますので、おっしゃってください！！
ご確認よろしくお願いいたします🙇‍♀️

2022-12-18 10:01 UTC, shirotamaki commented
@AyakaTakashima 
お疲れ様です！レビューご依頼いただきありがとうございます🙌 
3,4日お日にちいただいても大丈夫でしょうか？

2022-12-19 00:08 UTC, AyakaTakashima commented
@shirotamaki 
お返事ありがとうございます！！！

> 3,4日お日にちいただいても大丈夫でしょうか？

問題ありません！よろしくお願いいたします🙇‍♀️

2022-12-20 14:13 UTC, AyakaTakashima commented
@shirotamaki 
度々失礼いたします🙇‍♀️
こちらのPRに関連している他のPRがあるのですが、そこで本ブランチにてN+1問題が発生していることがわかりました。
本日、それを修正し、追加でpushさせていただきました！
もしすでにブランチを取り込み済みでしたら更新いただけますと幸いです。
お手数お掛けして申し訳ございません😭

2022-12-22 15:08 UTC, shirotamaki reviewed
お疲れ様です！大変お待たせしました🙏

動作確認OKです！問題ありませんでした！5ポイントのPRのレビューは初めてだったのですが、アンケート機能をしっかりと作り上げられていて凄いと思いました✨✨

今の私が出来る範囲でレビューさせていただきました。内容確認し修正いただいた方がよいかなと思った点を4点コメントしております！レビューのポイントが間違っている点などありましたらコメントいただけると幸いです🙇‍♂️

よろしくお願いします🙏

2022-12-24 05:12 UTC, AyakaTakashima commented
@shirotamaki 
お返事遅れてしまい申し訳ございません🙇‍♀️
レビューありがとうございます！！
修正完了いたしましたらまたご連絡させていただきます！！

2022-12-26 13:36 UTC, AyakaTakashima commented
@shirotamaki 
お疲れ様です！
いただいた点を修正致しましたのでご確認お願いいたします！

2022-12-26 15:03 UTC, shirotamaki approved these changes
@AyakaTakashima 
確認いたしました！修正いただきありがとうございます！LGTMです👍
私からはApproveさせていただきます🙆‍♂️✨

2022-12-27 09:30 UTC, AyakaTakashima commented
@shirotamaki 
ご確認ありがとうございます！！！🙌

@komagata 
shirotamakiさんからapproveいただきましたのでレビューをお願いいたします！

2022-12-27 22:28 UTC, komagata requested changes
[[コミットしたユーザーアイコンがOctcatになっていないか](https://docs.komagata.org/5676#default_icon) - 初心者がRailsプロジェクトへの初PRする前に見るチェックリスト \- komagataのブログ](https://docs.komagata.org/5676#default_icon)

こちらになっているようなので確認してみてください〜

2022-12-28 11:15 UTC, AyakaTakashima commented
@komagata 
失礼いたしました。
修正しましたので、ご確認よろしくお願いいたします！

2022-12-29 22:57 UTC, komagata requested changes

2022-12-29 22:57 UTC, komagata commented on app/controllers/surveys_controller.rb
> +  before_action :require_admin_or_mentor_login
上から順番に実行されるのでこの行は上に持ってきた方がいいかもです〜

2022-12-29 22:57 UTC, komagata commented on app/controllers/surveys_controller.rb
> +    @surveys = Survey.all.order(end_at: :desc)
```suggestion
    @surveys = Survey.order(end_at: :desc)
```

allはなくても大丈夫だったはずです〜

2022-12-29 22:57 UTC, komagata commented on app/controllers/surveys_controller.rb
> +    @survey = Survey.new(start_at: Time.current.beginning_of_day, end_at: Time.current.end_of_day.strftime('%Y-%m-%dT-%H:%M'))
文字列にしなくてもDate型とかでよかった気がします〜

2022-12-29 22:57 UTC, komagata commented on app/helpers/surveys_helper.rb
> +  def question_options_within_survey_question
helperもmodelと同じように独自のメソッドを作った場合は対応するtestの追加をお願いします〜

2023-01-04 10:59 UTC, AyakaTakashima commented on app/controllers/surveys_controller.rb
> +    @survey = Survey.new(start_at: Time.current.beginning_of_day, end_at: Time.current.end_of_day.strftime('%Y-%m-%dT-%H:%M'))
@komagata 
`end_at`を、`Time.current.end_of_day.strftime('%Y-%m-%dT-%H:%M')`書いている理由なのですが、
下記のようにすると、
```rb
Time.current.end_of_day
```
下記画像のように、秒数まで表示されてしまいます。
![image](https://user-images.githubusercontent.com/76944527/210540526-002b16de-6d05-4e51-a1b1-381d1b7bcdfa.png)

下記のようにDate型でも試したのですが、上記のように秒数まで表示されてしまいました。
```rb
    @survey = Survey.new(start_at: Date.current.beginning_of_day, end_at: Date.current.end_of_day)
```
`Time.current.end_of_day.strftime('%Y-%m-%dT-%H:%M')`という書き方は、Date型を用いて
`Date.current.end_of_day.strftime('%Y-%m-%dT-%H:%M')`と記載しても問題ないようでした。

`Date.current.end_of_day.strftime('%Y-%m-%dT-%H:%M')`とした方がよろしいでしょうか？

2023-01-04 13:03 UTC, AyakaTakashima commented
@komagata 
お疲れ様です。
こちら修正いたしましたので、ご確認お願いいたします！
質問を一点していますので、そちらのご確認もお願いいたします。

2023-01-05 04:03 UTC, komagata commented on app/controllers/surveys_controller.rb
> +    @survey = Survey.new(start_at: Time.current.beginning_of_day, end_at: Time.current.end_of_day.strftime('%Y-%m-%dT-%H:%M'))
@AyakaTakashima なるほどですね、でしたらそのままで大丈夫です〜。

2023-01-05 04:04 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-01-05 07:45 UTC, merged

2023-01-05 09:00 UTC, AyakaTakashima commented
@komagata 
ご確認ありがとうございます！！！！！
アンケート機能はまだ正式に実装されていないと思うので、リリースノートは書かないようにしたいと思います！

2023-01-05 09:01 UTC, AyakaTakashima commented
@komagata
ご確認ありがとうございます！！！！！
アンケート機能はまだ正式に実装されていないと思うので、リリースノートは書かないようにしたいと思います！