[wip]Feature/answer callback change newspaper
fjordllc/bootcamp pull request #5707
Opened 2022-10-29 22:33 UTC by yuki-snow1823

2022-10-29 22:48 UTC, yuki-snow1823 commented
@hikarook94 
初めまして、堀越（https://bootcamp.fjord.jp/users/1548）と申します。
こちらのレビューをお願いしてもよろしいでしょうか(__)

ご確認よろしくお願いします。

2022-10-30 03:23 UTC, hikarook94 commented
@yuki-snow1823 
初めまして！よろしくお願いします🙌
レビューさせていただきます！
明日中にはお返しできると思いますので、お待ちください！

2022-10-30 14:38 UTC, yuki-snow1823 commented
@hikarook94 
ありがとうございます！

2022-10-31 04:41 UTC, hikarook94 approved these changes

2022-10-31 04:42 UTC, hikarook94 commented
@yuki-snow1823 
お疲れ様です！
確認させていただきました！OKだと思います👍
Approveしました〜

2022-11-02 12:36 UTC, yuki-snow1823 commented
@hikarook94 
遅くなりました！ありがとうございました！

2022-11-02 12:36 UTC, yuki-snow1823 commented
@komagata 
メンバーレビューが終わったため、レビューをお願いします！

2022-11-07 01:02 UTC, komagata requested changes

2022-11-07 01:02 UTC, komagata commented on config/initializers/newspaper.rb
> +  Newspaper.subscribe(:correct_answer_save, CorrectAnswerNotifier.new)
answer_cache_destroyerを使う登録に挟まれているとコードの統一感がなくて読みづらくなってしまうと思うので、別の場所に書いていただければと思います〜

2022-11-07 16:22 UTC, yuki-snow1823 commented on config/initializers/newspaper.rb
> +  Newspaper.subscribe(:correct_answer_save, CorrectAnswerNotifier.new)
@komagata 
修正とCIが通ったことを確認しました！
再度ご確認お願いします。

[398f42e](https://github.com/fjordllc/bootcamp/pull/5707/commits/398f42e3b50e0bb1772d12f5dbc105e84ddcd0f8)

2022-11-08 05:46 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-11-08 05:46 UTC, merged