アドバイザーは日報作成ボタンを非表示にする
fjordllc/bootcamp pull request #5717
Opened 2022-11-01 07:11 UTC by shucream-p

## Issue

- #5604 

## 概要

アドバイザーは日報作成ボタンを非表示にしました。

## 変更確認方法

1. ブランチ`feature/adviser-hides-daily-report-creation-button`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. `advijirou`でログイン（アドバイザーになっているユーザーであれば誰でも構いません）
4. ダッシュボード、自分の日報、ブックマーク、日報ページにアクセスして、日報作成ボタンが表示されていないことを確認してください。
5. `kimura`でログイン（アドバイザー以外のユーザーであれば誰でも構いません）
6. ダッシュボード、自分の日報、ブックマーク、日報ページにアクセスして、日報作成ボタンが表示されていることを確認してください。

## 変更前

### ダッシュボード
<img width="1368" alt="スクリーンショット 2022-11-01 14 01 23" src="https://user-images.githubusercontent.com/88083085/199173726-bc11ea90-0e3f-4530-980b-b37f066eb3b2.png">

### 自分の日報
<img width="1368" alt="スクリーンショット 2022-11-01 14 02 14" src="https://user-images.githubusercontent.com/88083085/199174066-e917a199-109e-4b33-bfa1-ad43ad3cdcfb.png">

### ブックマーク
<img width="1370" alt="スクリーンショット 2022-11-01 14 02 34" src="https://user-images.githubusercontent.com/88083085/199174281-2471af25-7d51-4feb-bc69-8cf949a6afc5.png">

### 日報
<img width="1366" alt="スクリーンショット 2022-11-01 14 04 26" src="https://user-images.githubusercontent.com/88083085/199174452-4271b885-7b80-40de-8ee3-0616947d3875.png">

## 変更後

### ダッシュボード
<img width="1369" alt="スクリーンショット 2022-11-01 14 41 28" src="https://user-images.githubusercontent.com/88083085/199177119-c45fa756-a32d-41ff-905c-1a57f546b3e5.png">

### 自分の日報
<img width="1369" alt="スクリーンショット 2022-11-01 14 41 44" src="https://user-images.githubusercontent.com/88083085/199177516-28bd2a62-4a0b-43e6-9a8b-6111c6b35a00.png">

### ブックマーク
<img width="1369" alt="スクリーンショット 2022-11-01 14 42 00" src="https://user-images.githubusercontent.com/88083085/199177677-81c12fe2-256b-437d-9d01-7e63aafa381b.png">

### 日報
<img width="1368" alt="スクリーンショット 2022-11-01 14 42 46" src="https://user-images.githubusercontent.com/88083085/199178034-d25903f4-7a1c-4a30-bd20-da572b93f4cc.png">

2022-11-01 12:53 UTC, shucream-p commented
@hikarook94 
お疲れ様です！
お時間ありましたら、こちらのレビューをお願いしたいです🙇‍♂️
もし厳しいようでしたら他の方にお願いしますのでおっしゃってください！

2022-11-01 14:41 UTC, hikarook94 commented
@shucream-p 
お疲れ様です〜！
ご依頼ありがとうございます！
遅くて11/3までにはお返しできるかと思うのですが、そちらで問題なければ確認させていただきます！

2022-11-01 23:39 UTC, shucream-p commented
@hikarook94

> 遅くて11/3までにはお返しできるかと思うのですが、そちらで問題なければ確認させていただきます！

はい！そちらで問題ないです！
ありがとうございます。
よろしくお願いします！

2022-11-03 08:03 UTC, hikarook94 requested changes

2022-11-03 08:03 UTC, hikarook94 commented on app/javascript/question-edit.vue
> +            tagsType='Question',
この部分、最新のmainブランチで修正されたようなので再度mainブランチの取り込みをしてみてください〜🙏

2022-11-03 08:05 UTC, hikarook94 commented
@shucream-p 
お疲れ様です！
機能は問題ないと思います！一点コメントしているのでご確認をお願いいたします！

2022-11-03 15:44 UTC, shucream-p commented on app/javascript/question-edit.vue
> +            tagsType='Question',
レビューありがとうございます！🙇‍♂️
本日手をつけられなかったのですが、修正次第またご連絡いたします！

2022-11-07 14:34 UTC, shucream-p commented on app/javascript/question-edit.vue
> +            tagsType='Question',
@hikarook94 
お疲れ様です！
こちら現在対応中なんですが、流れとしては[2cfc095](https://github.com/fjordllc/bootcamp/pull/5717/commits/2cfc0959cd2626ce7c89571648054f8f1ad1f248)のコミットを削除して最新のmainをrebaseするという感じでしょうか？💦

2022-11-07 15:28 UTC, shucream-p commented on app/javascript/question-edit.vue
> +            tagsType='Question',
@hikarook94 
すみませんこちら自分で解決できました💦
最新のmainをrebase->コンフリクトを解消の手順ですね！
修正できたと思いますのでご確認よろしくお願いいたします🙇‍♂️

2022-11-08 01:32 UTC, hikarook94 approved these changes
@shucream-p 
修正ありがとうございます！Approveさせていただきます！

2022-11-08 03:44 UTC, shucream-p commented
@hikarook94 
レビューありがとうございました！🙇‍♂️

2022-11-08 03:47 UTC, shucream-p commented
@komagata 
お疲れ様です！
メンバーレビューでapproveしていただきましたので、レビューよろしくお願いいたします！

2022-11-08 05:48 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-11-08 05:48 UTC, merged

2022-11-08 11:36 UTC, shucream-p commented
@komagata 
ご確認ありがとうございました！