メンターの関連著書の表示を調整・開発環境用のデータを追加しました
fjordllc/bootcamp pull request #5813
Opened 2022-11-19 09:12 UTC by ksmxxxxxx

# Issue

- #5786 

## 概要

- メンターの関連著書の表示順を登録（created_at）降順へ変更しました。
- development環境用のデータを追加しました
  - 関連著書テーブル用yamlデータ追加
  - 関連著書の書影画像データ追加
  - development環境のsetup時に、関連著書テーブルに書影画像の添付を行うスクリプトの追加

## Screenshot

| 変更前 | 変更後 |
|:------:|:------:|
|   ![変更前](https://user-images.githubusercontent.com/5976902/202843697-8468b728-cb9f-4a40-8704-89de05f289cf.png)     |    ![変更後](https://user-images.githubusercontent.com/5976902/202843679-d9b5aeed-bf05-4629-bb56-455cfe059777.png)    |

2022-11-19 09:22 UTC, ksmxxxxxx commented
@hikarook94 お疲れさまです。
Pull Requestを作成しましたので、レビューしていただけますでしょうか？
よろしくおねがいします 🙇🏻‍♀️

2022-11-21 03:16 UTC, hikarook94 commented
@ksmxxxxxx 
返信遅くなりすみません🙇‍♂️
確認させていただきます！明日までにはお返しできると思います！

2022-11-22 15:42 UTC, hikarook94 reviewed
@ksmxxxxxx 
遅くなってすみません！レビューしました！
一点コメントしています。ご確認ください！

2022-11-22 15:42 UTC, hikarook94 commented on app/views/welcome/_mentor.html.slim
> +        - mentor.authored_books.order(:created_at).reverse_each do |authored_book|
この部分で順番を操作しているんですね〜！
このままでも僕は良いのかなと思いますが、そのほかに僕が思いついたのはこんな感じです。
- `order`のオプションで降順を指定する。（`reverse_each`メソッドは初めて知りました！）
```suggestion
        - mentor.authored_books.order(created_at: :desc).each do |authored_book|
```
- デコレーターを使う。デコレーターはビューで使えるメソッドをクラスに追加する機能だと思っていて、ビューから表示のための処理を分離できるのでスッキリするのが良いらしいです。`mentor`はUserクラスかと思うので、`user_decorator.rb`に作成日の降順で並んだ本のリストを返すようなメソッドを定義するイメージでしょうか（一応手元では動かしてみましたが、違ったらすみません）
```ruby
# app/decorators/user_decorator.rb
module UserDecorator
  # 略
  def books_desc_created_at
    authored_books.order(created_at: :desc)
  end
end
```
```suggestion
        - mentor.books_desc_created_at.each do |authored_book|
```

何が適切かという判断は自分には難しかったので、駒形さんにも伺ってみると良いかもしれません🙇‍♂️
現状でも問題ないかなと思うので修正はお任せします！

2022-11-23 06:31 UTC, ksmxxxxxx commented on app/views/welcome/_mentor.html.slim
> +        - mentor.authored_books.order(:created_at).reverse_each do |authored_book|
@hikarook94 レビューありがとうございます！
`order(created_at: :desc)`失念していたので参考になります〜 🙏🏻 

decoratorでやるのも良さそうだったんですが、「メンターさんの著書って新しいものが常に最初にくる（直近で登録したものが常に最初）がデフォであってほしいよねぇ」と考えると、decoratorよりもmodelのscopeとして渡しちゃったほうがいいのでは？と考えたので、:point_down: のように変更してみました。

https://github.com/fjordllc/bootcamp/pull/5813/commits/2f7db6fb275f4ef019bbe8badbf06fabfd6c6966

👇🏻 こちらは修正している過程で「ここも`User.mentors`とかにしてあげたほうがわかりやすいよなぁ」と思って追加した修正になります。（ちょっと著書の表示について本筋がずれてしまう気がしますが……気がついてしまったので 😅 ）
https://github.com/fjordllc/bootcamp/pull/5813/commits/4ed8e4122d97678eaa9f884e873bad4a8ffac1a7

お手数おかけしますが、再レビューしていただけると 🙇🏻‍♀️

2022-11-24 04:33 UTC, hikarook94 requested changes
@ksmxxxxxx 
お疲れ様です！確認させていただきました！
scopeを使ってすっきりしましたね！あと一点コメントしています！
ご確認よろしくお願いしますー🙏

2022-11-24 04:33 UTC, hikarook94 commented on app/views/welcome/_mentor.html.slim
> +        - mentor.authored_books.sorted.each do |authored_book|
すっきりしましたね！

2022-11-24 07:20 UTC, ksmxxxxxx commented on app/models/user.rb
> +  }
@hikarook94 
https://github.com/fjordllc/bootcamp/commit/eaf9bf694d762395a607ec75aa25afbce77f355b
やってることとしてはメンター情報を作成日昇順でソートさせたものをscopeにしてるっぽいんですよね。
mentorsでもいいのではと思いましたが、より詳細度をつけるとしたらこういう感じかしら？というコミットがこちらになります 👇🏻 
87a05c3

あと、`:mentor`スコープ作ってるのに`:mentors`までが遠かったので、近くに寄せてみています。

ふと`welcome_controller.rb`のcommitログを眺め考古学をしてて、「`:mentor`っていう名前がそもそも合ってないんでは？」っていう気もしたんですが……PullReqの本筋から外れそうなので、自分としては「今はそっとしておこう」って思いました 😅 （Issueにしておくのがいいかもしれません）

参考：https://github.com/fjordllc/bootcamp/commits/main/app/controllers/welcome_controller.rb

2022-11-24 08:04 UTC, hikarook94 commented on app/models/user.rb
> +  }
修正ありがとうございます！

> 「:mentorっていう名前がそもそも合ってないんでは？」

確かにそんな気もしますね😄 
静観承知しました👍

2022-11-24 08:05 UTC, hikarook94 approved these changes
@ksmxxxxxx 
修正ありがとうございました！Approveさせていただきます！

2022-11-24 12:03 UTC, ksmxxxxxx commented
@hikarook94 レビュー && Approvedありがとうございます！

@komagata こちらメンバーレビューでApprovedいただきましたので、レビューお願いします〜 🙏🏻

2022-11-25 17:10 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-11-25 17:10 UTC, merged