ダッシュボード画面
fjordllc/bootcamp pull request #5838
Opened 2022-11-27 04:08 UTC by peno022

## Issue

- https://github.com/fjordllc/bootcamp/issues/5679

## 概要

### ブックマーク画面の変更
ダッシュボード > ブックマーク画面で、ブックマークが0件のときとそうでない時で表示を分けるようにしました。
ブックマークが1件以上あるときの表示内容には、変更は加えていません。

- ブックマークが0件のとき
  - `ブックマークはまだありません。`というメッセージと、font awesomeの泣き顔アイコンを表示する
- ブックマークが1件以上のとき
  - 編集ボタンと、ブックマークの一覧を表示する

### ブックマーク画面のテストを追加
ダッシュボード > ブックマーク画面 のテストがなかったので、`test/system/current_user/bookmarks_test.rb`を追加しました。

テストでの確認ポイントは以下としました。
- 初期状態でブックマークがないとき、`ブックマークはまだありません。`というメッセージが表示されること
  - 編集ボタンが表示されていないこと
  - `ブックマークはまだありません。`というメッセージが表示されること
    - なお、テスト環境の制約で、アイコンが表示されることの確認はなし
      - その旨のやりとりがあった過去のPR：https://github.com/fjordllc/bootcamp/pull/5375
- ブックマークが1件以上あるとき、編集ボタンとブックマーク一覧が表示されること
  -  ブックマークの表示要素はタイトル、ラベル、サマリ、作成者、作成日
- 編集ボタンをクリックすると削除ボタンが表示されるようになり、削除ボタンをクリックすると該当のブックマークが一覧から消えること
- ブックマークが1件以上ある状態から、一覧の全てのブックマークを削除すると、0件時の画面表示になること
  - 編集ボタンが表示されていないこと
  - `ブックマークはまだありません。`というメッセージが表示されること

## 変更確認方法

1. `feature/change-display-for-no-bookmarks`をローカルに取り込む
2. 任意のユーザーでログインし、ダッシュボード > ブックマーク画面 を開く
3. 1件以上のブックマークを登録する
4. 登録したブックマークを削除する

## Screenshot
ブックマークが0件のときの画面表示

### 変更前
![スクリーンショット 2022-11-27 12 55 02](https://user-images.githubusercontent.com/40317050/204118609-556bfb7c-0fc4-4303-aff9-8d2784aec280.png)

### 変更後
![スクリーンショット 2022-11-27 12 54 26](https://user-images.githubusercontent.com/40317050/204118606-ab69fce6-075a-437f-b29c-a03c4500f04c.png)

2022-11-27 04:16 UTC, peno022 commented
@ksmxxxxxx 
おつかれさまです！こちらのPRのレビューをお願いすることできますでしょうか？

2022-11-29 11:49 UTC, ksmxxxxxx approved these changes
@peno022 お疲れさまです〜

Reactのコードレビューはじめてなのですが、素人目で特にきになるところはなさそうだったのでApproveさせていただきます〜 👍🏻

2022-11-29 11:52 UTC, peno022 commented
@ksmxxxxxx 
Reacth初のところすみません！ありがとうございました！🙏

@komagata 
こまがたさんレビューよろしくお願いいたします！
また、元issueのほうでも一点質問させちただいており（この修正内容に直接影響してくる質問ではないと思うので、レビュープロセスは進めています）、そちらもご確認いただけますと大変幸いです🙏

2022-11-29 21:13 UTC, komagata commented
@peno022 こちらはReactでこのページができていることを知らずにIssueを割り振ってしまっていたようです。苦労させてしまって大変申し訳ないです。

2022-11-29 21:19 UTC, komagata commented on app/javascript/components/Bookmarks.jsx
> +    )
```js
function NoBookmarks() {
  return (
    <div className="o-empty-message">
      <div className="o-empty-message__icon">
        <i className="fa-regular fa-face-sad-tear" />
        <p className="o-empty-message__text">ブックマークはまだありません。</p>
      </div>
    </div>
  );
}
```

```js
if (data.tolaPages === 0) {
  <NoBookmarks />
} else {
```

こんな感じにまとめると見通しが良くなるかもです〜

2022-11-29 21:19 UTC, komagata commented on test/system/current_user/bookmarks_test.rb
> +    # assert_selector 'i.fa-regular.fa-face-sad-tear'
`assert_selector`の`visible: false`とかを使えばいけるかもです〜

https://www.rubydoc.info/gems/capybara/Capybara%2FNode%2FMatchers:assert_selector

2022-12-01 00:00 UTC, peno022 reviewed
@komagata 
ご指摘点修正しました！再度レビューお願いいたします🙇‍♀️

2022-12-02 23:05 UTC, komagata commented on app/javascript/components/Bookmarks.jsx
> +
```suggestion
  )
};
```

他と合わせるとこの形がいいかもです〜

2022-12-02 23:05 UTC, komagata commented on app/javascript/components/Bookmarks.jsx
> +    return(<NoBookmarks />)
```suggestion
    return <NoBookmarks />
```

2022-12-02 23:32 UTC, peno022 commented
@komagata 
ご確認ありがとうございます！修正しました🙏

2022-12-06 23:39 UTC, komagata commented on test/system/current_user/bookmarks_test.rb
> +    all('#bookmark-button').first.click
```suggestion
    first('#bookmark-button').click
```

こちらと同じ意味なのでこれがいいかもです〜

2022-12-06 23:39 UTC, komagata commented on test/fixtures/bookmarks.yml
> +
ちょっとテストに慣れた人用の指摘になっちゃうのですが、0件の時のテストというのはほとんどこのテストでしか使わないので、fixturesに追加せず、テストの中でデータを作成するのが良いかもです。

```ruby
Bookmar.create!(略)
```

なぜならfixturesに書かれたデータは全てのテストケースでINSERT/DELETEされるものなのでテストの速度に大きな影響を与えます。

また、他のテストから見るとテストが作成された時点では存在しなかったデータが増えるのでテストの動作自体にも影響があります。

なので、全体で使い回すようなデータ（例えば頻繁に使うユーザーなど）はfixturesに書くべきですが、他であまり使わないものについてはテスト中で手動で作成するのが良いと思います。

2022-12-09 00:19 UTC, peno022 commented on test/system/current_user/bookmarks_test.rb
> +    all('#bookmark-button').first.click
なるほどです、修正しました！

2022-12-09 00:30 UTC, peno022 commented on test/fixtures/bookmarks.yml
> +
> 全体で使い回すようなデータ（例えば頻繁に使うユーザーなど）はfixturesに書くべきですが、他であまり使わないものについてはテスト中で手動で作成するのが良いと思います。

ご指摘ありがとうございます！今後のテスト追加時にも留意します。

下記の形で修正しました。
- 全タイプのブックマークが必要なケース
  - fixturesの既存の汎用ユーザー（`kimura`）に、Reportタイプのブックマークをfixturesに追加して利用
- ブックマーク0件のケース
  - テスト内で新規にユーザーを作成して利用
- ブックマーク1件のケース
  - テスト内で新規にユーザーを作成して利用

2022-12-10 00:47 UTC, peno022 commented
@komagata 
ご指摘ありがとうございました！
修正しましたので、再レビューお願いいたします。

2022-12-12 01:23 UTC, komagata requested changes
fixというコミットメッセージがあるので修正お願いします〜

2022-12-13 00:51 UTC, peno022 commented
@komagata 
大変失礼いたしました……🙇‍♀️
修正しました！

2022-12-15 07:13 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-12-15 07:13 UTC, merged