メンターの関連書籍に画像をアップロードした時にプレビューを表示できるようにした
fjordllc/bootcamp pull request #5839
Opened 2022-11-27 12:50 UTC by shirotamaki

## Issue

- #5785

## 概要
メンターでログインし、登録情報変更で新規に関連書籍を登録した際に画像がプレビューできないバグを修正した

## 変更確認方法

1. `bug/fix-authored-book-to-show-preview`をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2022-12-01 13:45 UTC, shirotamaki commented
@ksmxxxxxx 
お疲れ様です！
こちらのPRですがレビューをお願いできますでしょうか？
急いではおりませんのでお手すきの際ご確認いただけますと幸いです。よろしくお願いします〜🙏

2022-12-01 14:38 UTC, ksmxxxxxx reviewed
修正しなくてもいいかなぁ…という気がしていますが、気がついたのでコメントしておきます〜 👋

2022-12-01 14:38 UTC, ksmxxxxxx commented on app/javascript/authored_book.js
> +  for (let i = 0; i < inputs.length; i++) {
for文で配列をインデックス付きでループする方法は、for文の他にも、`forEach` メソッドがあったりしますが、理由があってfor文で書いたのかなぁ 🤔 とも考えられたので、もし存じ上げなかったら試してみてねというくらいの温度感のコメントです。

個人的な使い分けとしては、返ってくるDOMの種類で、`NodeList`が返ってくる場合→`forEach`メソッド、`HTML Collection`が返ってくる時はfor文を使います。
たしか、`HTML Collection`に対しては `forEach`が使えなかったと思うので、そういう使い分けを…していたように思います。

`querySelectorAll` してるので返ってくるDOMは `NodeList` だと思うので、for文より`forEach`のほうが今どきの書き方なのかなぁ…と思うくらいです。

2022-12-02 13:28 UTC, shirotamaki commented
@ksmxxxxxx 
レビューありがとうございます！

今回for文を選択している理由は特になく、for文で書くことしか選択肢として持ち合わせていませんでした...😭

> 個人的な使い分けとしては、返ってくるDOMの種類で、NodeListが返ってくる場合→forEachメソッド、HTML Collectionが返ってくる時はfor文を使います。

なるほど〜👀 使い分けることができるのですね！`forEach`に書き換えてみたところコードもスッキリしました！

改めてご確認お願いします〜🙏

2022-12-03 14:35 UTC, ksmxxxxxx reviewed
おまたせしました、コメントしました〜 🙇‍♀️

2022-12-03 14:35 UTC, ksmxxxxxx commented on app/javascript/authored_book.js
> +  for (let i = 0; i < elements.length; i++) {
`elements`に入ってくるのが NodeListだったら、ここもforEachできそうに思いました〜

2022-12-04 07:15 UTC, shirotamaki commented on app/javascript/authored_book.js
> +  for (let i = 0; i < elements.length; i++) {
@ksmxxxxxx 
`elements`変数の情報を確認してみたところ、NodeListではなくjQuery.fn.initというjQueryオブジェクトが返って来ており、forEachが使えませんでした...😿

![image](https://user-images.githubusercontent.com/65638955/205478742-0bf2b4a9-f829-420c-832d-f5751c667c99.png)

この場合はfor文のままで大丈夫でしょうか？

2022-12-04 13:26 UTC, ksmxxxxxx approved these changes
コメント返信しつつApproveします〜

2022-12-04 13:26 UTC, ksmxxxxxx commented on app/javascript/authored_book.js
> +  for (let i = 0; i < elements.length; i++) {
おやぁ 🤔 と思って、手元で動かしながら確認してみたんですが、
https://github.com/nathanvda/cocoon
こちらのgemを使ってフォームを追加してて、でもってこのgemがjqueryでよしなにformをよしなに扱いやすくしてるっぽいですね〜ﾅﾙﾎﾄﾞ

だとしたら、forEach使えないと思うので、ここはこのままでもいいかなぁって思いました。
jquery引っ剥がそうと思ったら、多分骨が折れそう……と思うので 😅

2022-12-05 10:07 UTC, shirotamaki commented
@ksmxxxxxx  レビュー&&Approvedいただきありがとうございました！

@komagata こちらメンバーレビューでApprovedいただきましたので、レビューお願いします 🙏🏻

2022-12-07 03:44 UTC, komagata reviewed
conflictの修正をお願いします〜

2022-12-08 11:29 UTC, shirotamaki commented
@komagata conflict修正しました！ご確認お願いします🙏

2022-12-12 10:47 UTC, shirotamaki commented
@ksmxxxxxx 
お疲れ様です！こちらのPRですが、まだApproveいただけていないようでした。気づくのが遅くなりすいません...😓 ご確認お願いします🙏

2022-12-12 11:08 UTC, ksmxxxxxx approved these changes

2022-12-12 11:09 UTC, ksmxxxxxx commented
@shirotamaki すみません、Approveボタン押した気満々でいました…… 🙇‍♀️

2022-12-12 12:30 UTC, shirotamaki commented
@komagata 何度もすいません！ご確認お願いします🙏

2022-12-15 07:08 UTC, komagata requested changes

2022-12-15 07:08 UTC, komagata commented on app/javascript/authored_book.js
> +function initializeFileInput(target) {
https://github.com/fjordllc/bootcamp/blob/6aceae1e5df3ff0b971b59faf4367b0c2b3ad02c/app/javascript/fileinput.js

こちらとほとんど同じコードになっているので共通化してDRYにして見てください〜

2022-12-21 04:54 UTC, shirotamaki commented
@komagata お疲れ様です！修正いたしました。ご確認お願いします🙏

2022-12-27 08:59 UTC, komagata approved these changes
めちゃくちゃスッキリしましたね。

2022-12-27 08:59 UTC, merged

2022-12-27 09:51 UTC, shirotamaki commented
@komagata ご確認ありがとうございます✨✨