選択必須の選択肢を選んだら「選択した理由」の入力欄を表示するようにした
fjordllc/bootcamp pull request #5920
Opened 2022-12-09 13:27 UTC by AyakaTakashima

## Issue

- #5905 

## 概要

アンケートの質問形式が下記の時に、選択肢を選んだ理由について回答必須である場合があります。
- ラジオボタン
- チェックボックス
- 均等目盛

これらの選択肢をクリックした際に、「選択した理由」の回答が必須な選択肢を選んだ場合のみ、
追加の入力欄が現れるようにしました。

## 変更確認方法

1. `feature/display-input-fields-of-reason-for-choice-only-when-answer-required-choice-choosed`をローカルに取り込む
2. `bin/rails s`でローカルを立ち上げる
3. 下記にアクセス
http://localhost:3000/survey_questions
4. 質問形式がラジオボタン、チェックボックス、均等メモリの質問の編集画面に入り、「選択した理由」の回答が必須の選択肢はどれかを確認する（「選択した理由」の回答が必須の選択肢がなかった場合は必須にする）
5. 下記にアクセスし、表示されているいずれかのアンケートをクリックする
http://localhost:3000/surveys
6. 「選択した理由」が必須の選択肢をクリックした時に、理由を入力する欄が動的に表示されるか確認する

### 変更前
ラジオボタン、チェックボックス、均等目盛、いずれも「選択した理由」の入力欄が常時表示されっぱなしでした。
![image](https://user-images.githubusercontent.com/76944527/206712678-5eee1547-e4cf-4d85-ad92-d56d151ac5ae.png)

![image](https://user-images.githubusercontent.com/76944527/206712655-099698de-372d-4596-9858-988a2da96ea7.png)

![image](https://user-images.githubusercontent.com/76944527/206712697-31a0f68d-4e00-4bd3-b574-6e006e1a5b18.png)

### 変更後
ラジオボタン
[![Image from Gyazo](https://i.gyazo.com/1ed7d8d5ba8f2cc51ef2ac19e485c1e9.gif)](https://gyazo.com/1ed7d8d5ba8f2cc51ef2ac19e485c1e9)

チェックボックス
[![Image from Gyazo](https://i.gyazo.com/68337175541ece83ea0adffd78ce6578.gif)](https://gyazo.com/68337175541ece83ea0adffd78ce6578)

均等目盛
[![Image from Gyazo](https://i.gyazo.com/c0764dee6b1517b17f902ef4c999800d.gif)](https://gyazo.com/c0764dee6b1517b17f902ef4c999800d)

2022-12-18 08:45 UTC, AyakaTakashima commented
@hikarook94 
お疲れ様です！！
こちらのレビューをお願いしたいのですが可能でしょうか？🙇‍♀️
もし厳しそうでしたらほかの方にお声がけするのでおっしゃっていただければ幸いです😌

2022-12-18 12:09 UTC, hikarook94 commented
@AyakaTakashima 
お疲れ様です！レビュー依頼ありがとうございます！
明後日までにはお返しできるかと思います👍

2022-12-19 00:10 UTC, AyakaTakashima commented
@hikarook94 
お返事ありがとうございます！！
承知いたしました！！よろしくお願いいたします🙌

2022-12-20 08:57 UTC, hikarook94 requested changes
@AyakaTakashima
お疲れ様です！レビューしました！
動作確認はOKでした👍

コードについていくつかコメントさせていただいているのと、Bulletのエラーが画面に表示されておりN+1問題が発生しているかも？と思いました。
<img width="959" alt="スクリーンショット 2022-12-20 17 53 47" src="https://user-images.githubusercontent.com/59002337/208624955-007538af-129f-4a22-a5c1-bb9a47f5e56e.png">
（アイコン？に隠れていてよく見えないですが...）
`surveys_contorller.rb`で`survey_questions`を取得するときに一度にまとめて取得する必要があるかなと思います！違っていたらすみません！

以上、ご確認よろしくお願いします🙏

2022-12-20 08:57 UTC, hikarook94 commented on app/javascript/survey.js
> +        choicesInSameQuestion.forEach((ChoiceInSameQuestion) => {
`ChoiceInSameQuestion`はキャメルケースのタイポ？だと思います！

2022-12-20 08:57 UTC, hikarook94 commented on app/javascript/survey.js
> +        !answerRequiredChoice.checked &&
`!answerRequiredChoice.checked`はあえて明示しなくても良いかも？と思いました！

2022-12-20 13:27 UTC, AyakaTakashima commented
@hikarook94 
レビューありがとうございます！
時間がかかりそうなので修正完了しましたらまたご連絡させていただきます

2022-12-21 11:08 UTC, AyakaTakashima commented
@hikarook94
お疲れ様です！
修正できましたのでご確認お願いいたします🙇‍♀️

左隅にある赤いWarningってクリックして中身開くことができるんですね...！
「Bullet Warning」で調べてみると、N+1問題を検出してくれるgemだということがわかりました。
勉強になりました😭ありがとうございます...！

上記のエラーはshowページで発生しておりましたので、#5690 の方で修正させていただきました🙇‍♀️
#5679 のPR（レビュー中）も私が担当しており、showページはそちらのPRで実装したためです。
本PRのブランチ（`feature/display-input-fields-of-reason-for-choice-only-when-answer-required-choice-choosed`）は、上記の別PRのブランチが分岐元となっているので、rebaseいたしました！
エラーは出なくなっていると思いますので、ご確認いただけますと幸いです。

他のご指摘いただいた点も修正させていただきました！
ご確認よろしくお願いいたします🙇‍♀️

2022-12-22 04:28 UTC, hikarook94 approved these changes

2022-12-22 04:31 UTC, hikarook94 commented
@AyakaTakashima 
お疲れ様です！修正ありがとうございます！
> 左隅にある赤いWarningってクリックして中身開くことができるんですね...！

僕も「こんなのあったっけ？」って思いました😇
Bulletというgemの存在自体は知っていたのですが、実際にエラーに気づいたのは初めてでした！

N+1問題は別PRで修正とのこと、了解しました！
Approveさせていただきます！

2022-12-22 11:20 UTC, AyakaTakashima commented
@hikarook94 
そうだったんですね...！
気づいてくださり感謝です😭
approveありがとうございます！！

2022-12-22 11:21 UTC, AyakaTakashima commented
@komagata 
お疲れ様です！
hikarook94さんよりapproveいただきましたので、レビューお願いいたします！

2022-12-27 21:03 UTC, komagata requested changes
conflictの解消をお願い致します〜。

2022-12-28 11:29 UTC, AyakaTakashima commented
@komagata 
コンフリクトの解消をいたしました。
ご確認お願いします！

2022-12-29 22:59 UTC, komagata commented on app/javascript/survey.js
> +  const Choices = Array.from(document.querySelectorAll('.a-toggle-checkbox'))
他のページでjsのエラーが出ていないかどうか調べてみていだだけるとありがたいです〜

（.a-toggle-checkboxや`js-additional_question_${choice.name}`存在しないページ）

2023-01-04 13:02 UTC, AyakaTakashima commented
@komagata 
お疲れ様です。
修正いたしましたのでご確認お願いいたします！

2023-01-05 03:55 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-01-05 03:55 UTC, merged

2023-01-05 09:01 UTC, AyakaTakashima commented
@komagata
ご確認ありがとうございます！！！！！
アンケート機能はまだ正式に実装されていないと思うので、リリースノートは書かないようにしたいと思います！