最初の日報投稿通知をactive_delivery化する
fjordllc/bootcamp pull request #5931
Opened 2022-12-12 14:48 UTC by akingo55

## Issue

- Issue番号

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2022-12-18 06:36 UTC, komagata commented
@akingo55  卒業通知のメールが送られていなかった問題を修正したのでmainブランチを取り込んだ上でこちらを参考にして実装していただければありがたいです〜

#5939

2022-12-28 13:42 UTC, akingo55 commented
@dowdiness 
お疲れ様です！
こちらのPRのレビューを依頼しても良いでしょうか？:pray:
お手隙に確認よろしくお願いします。

2023-01-07 17:25 UTC, dowdiness requested changes
レビュー依頼ありがとうございますー！
のんびりしていたら返信するのが遅くなってしまいました。すいません。

使われなくなったメソッドとテストを消していなくて追加のテストが必要なことと、バグが見つかったので対応が必要なことを書きました。

確認よろしくお願いします。

2023-01-07 17:25 UTC, dowdiness commented on app/views/activity_mailer/first_report.html.slim
> +  = md2html(@report.description)
コレも上と同じようにこのslimが作られた後はNotificationMailerの方のfirst_report.html.slimはもう使わないと思うので消してしまったほうが良いと思います。

2023-01-07 17:25 UTC, dowdiness commented on app/mailers/activity_mailer.rb
> +  end
ActivityMailerを使う場合はNotificationMailerの方のfirst_reportはもう使わないと思うので消してしまったほうが良いと思いました。

NotificationMailerの使われているnotification_mailer_previewとnotification_mailer_testにあるテストも消してしまって、ActivityMailerを使う形でactivity_mailer_previewにテストを追加したら良いと思います。

メールのプレビューの確認はhttp://localhost:3000/rails/mailers で出来ます。

それと、サイト内通知より先にメール通知が送られるとエラーになる問題があるそうなので対応したほうが良さそうです。

https://github.com/fjordllc/bootcamp/pull/6001

を確認してみてください。

2023-01-09 10:33 UTC, akingo55 commented on app/mailers/activity_mailer.rb
> +  end
@dowdiness 
不要なもの削除しました！

>NotificationMailerの使われているnotification_mailer_previewとnotification_mailer_testにあるテストも消してしまって、ActivityMailerを使う形でactivity_mailer_previewにテストを追加したら良いと思います。

ActivityMailerのテストは追加済みです！

>それと、サイト内通知より先にメール通知が送られるとエラーになる問題があるそうなので対応したほうが良さそうです。

ありがとうございます！こちらも対応しました！

2023-01-16 13:59 UTC, akingo55 commented on app/mailers/activity_mailer.rb
> +  end
@dowdiness 
念の為こちらリマインドです:pray:
指摘していただいた点修正しましたので、再度ご確認お願いします！

2023-02-01 05:48 UTC, dowdiness commented on app/mailers/activity_mailer.rb
> +  end
@akingo55 
お疲れ様です。返信遅くなってしまいすいません。モチベーションが落ちてあまり作業できてませんでした。

サイト内通知より先にメール通知が送られるとエラーになる問題の対応は問題なさそうです👍

activity_mailer_previewにテストを追加したら良いというのが説明不足で分かりにくかったと思います。

ActivityMailerのテストが無いという意味ではなく、https://github.com/fjordllc/bootcamp/blob/main/test/mailers/previews/activity_mailer_preview.rb
にメールのプレビュー用のテストを追加したら http://localhost:3000/rails/mailers でメールのプレビューが確認出来るようになるので、テストを追加した方が良いなと思ったという意味で書きました。

遅くなって申し訳ないですが対応よろしくおねがいします🙇‍♂️

2023-02-04 09:01 UTC, akingo55 commented on app/mailers/activity_mailer.rb
> +  end
@dowdiness 
なるほど、、、！理解しました:pray:
こちらメールのプレビュー用テストを追加しましたのでご確認お願いしますmm
https://github.com/fjordllc/bootcamp/pull/5931/commits/baf65947c8f36bd885f7893b529b579874bf165a

2023-02-07 16:16 UTC, komagata reviewed
conflictの修正をお願いします〜

2023-02-14 15:04 UTC, akingo55 commented on app/mailers/activity_mailer.rb
> +    mail to: @receiver.email, subject: subject
classが肥大化しており、`too many lines`でrubocopにひっかかるのでリファクタしました。

2023-02-15 04:39 UTC, akingo55 commented
> conflictの修正をお願いします〜

@komagata 
修正完了しました！ご確認お願いします！

2023-02-18 02:16 UTC, komagata reviewed
conflictの修正をお願いします〜

2023-02-20 11:41 UTC, akingo55 commented
@komagata 
修正しましたので、ご確認お願いします！

2023-02-25 08:36 UTC, komagata reviewed
度々すみません、conflictの修正をお願いします〜

2023-03-02 02:16 UTC, akingo55 commented
@komagata 
修正完了です！

2023-03-02 13:07 UTC, dowdiness approved these changes
遅れてすいません🙏
もう既にkomagataさんのレビューに進んでいて問題無いのでApproveします

2023-03-05 13:20 UTC, mono-nobe commented
@akingo55 @komagata 
横から失礼します 🙇 

おそらく、[こちら](https://github.com/fjordllc/bootcamp/issues/5890#issuecomment-1445145422)と同様の問題が発生していそうです。。
`feature/replace-notification-first-report-to-active-delivery`ブランチで動作確認したところ、メールが対象者全員に送信されず、上記コメントと同じような挙動をしていました。
ご確認をよろしくお願いします。

2023-03-11 13:20 UTC, komagata commented
@akingo55 conflictの解消をお願いします。

2023-03-26 13:43 UTC, akingo55 commented
> @ akingo55 conflictの解消をお願いします。

@komagata 
修正しました、確認お願いします。
コンフリクトしやすいので早めにレビューいただけると助かります。

2023-03-26 17:02 UTC, mono-nobe commented
@akingo55 CC @komagata 

https://github.com/fjordllc/bootcamp/pull/5931#issuecomment-1455090556

コメントご確認いただけましたでしょうか？
念の為、再度ローカルで動作確認しましたが、やはり正常に動作していないように思われます。
(もし仕様を勘違いしていたらごめんなさい。)

<img width="1800" alt="スクリーンショット 2023-03-27 1 46 40" src="https://user-images.githubusercontent.com/94843475/227791572-53cbda0d-b8c1-4ce8-9cfb-d1030a5f0b0f.png">

<img width="806" alt="スクリーンショット 2023-03-27 1 57 59" src="https://user-images.githubusercontent.com/94843475/227791745-53b36270-6090-4cad-a92d-c13d19238054.png">

2023-03-26 17:04 UTC, mono-nobe commented on app/models/report_callbacks.rb
>      User.admins_and_mentors.each do |receiver|
@akingo55 

> User.admins_and_mentors

メール送信対象者は管理者とメンターだと理解しており、現状そこが満たされていない気がしております。

2023-05-15 05:10 UTC, machida commented
https://github.com/fjordllc/bootcamp/pull/6504
こちらで続きを行っているのでクローズにします。

2023-05-15 05:10 UTC, closed without merging