定期イベントで全員参加を設定できるようにする
fjordllc/bootcamp pull request #5949
Opened 2022-12-16 03:10 UTC by hikarook94

## Issue

- #5728 

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2022-12-16 09:54 UTC, hikarook94 commented
@machida 
Issueに以下の説明があったのですが、こちらのPRはデザインを依頼すればいいですか？
もし大丈夫でしたらデザインの導入をお願いいたします！

> この定期イベントは全員参加イベントで登録は必要ありません、的なメッセージを表示する（machidaがやります）

（ちなみにIssueの方で仕様に関してご質問しているので、併せてご確認よろしくお願いします🙏　https://github.com/fjordllc/bootcamp/issues/5728#issuecomment-1351526874 ）

2022-12-18 02:43 UTC, machida commented
@hikarook94 回答しましたー
デザイン、了解です🙆‍♂️

2023-01-11 02:16 UTC, machida commented
@hikarook94 

最新の main を取り込んだので、手元で

git pull --rebase origin feature/select-all-users-on-regular-event

をお願いしますー

2023-01-11 02:49 UTC, hikarook94 commented
@machida 
デザインありがとうございます！

2023-01-27 08:26 UTC, hikarook94 commented
@uchihiro04 
お疲れ様です！
ご都合がよろしければ、こちらのPRのレビューをお願いできますでしょうか？
急がないのでお手隙の際で大丈夫ですー！

2023-01-27 08:41 UTC, uchihiro04 commented
@hikarook94
レビュー承りました！
数日お時間いただく形になるかもしれませんが、確認させていただきます🙂

2023-01-27 12:33 UTC, hikarook94 commented
@uchihiro04 
ありがとうございます！何かコードで不明点があれば聞いてください！
よろしくお願いしますー🙏

2023-01-29 04:21 UTC, uchihiro04 commented on app/controllers/regular_events_controller.rb
> +      @regular_event.regular_event_participations.create(user: user)
確認なのですが、100行目と101行目で行われていることは、以下の解釈で間違いないでしょうか。

100行目：定期イベントの参加者に`user`が存在する場合は次のループへ進む。存在しない場合は102行目に進む。
102行目：`create`メソッドで`user`を定期イベントの参加者として設定する

念の為確認させていただければと思います🙇‍♂️

2023-01-29 08:18 UTC, uchihiro04 reviewed
@hikarook94 
お疲れ様です！
動作確認し、問題なく表示されることを確認しました🙂

コードに関して2点ほど確認させていただきたい箇所がありましたので、コメントいたしました。
ご確認のほどよろしくお願いいたします🙇‍♂️

2023-01-29 12:50 UTC, hikarook94 commented on app/controllers/regular_events_controller.rb
> +      @regular_event.regular_event_participations.create(user: user)
ご認識のとおりです！🙆‍♂️

2023-01-29 13:41 UTC, hikarook94 commented on app/views/regular_events/_form.html.slim
> +                = f.label :all do
ご質問ありがとうございます👍 勉強になります。
以下は僕の理解のため、もしかしたら不正確な内容があるかもしれません。

`f.label`の部分は`FormBuilder`オブジェクトの`label`というビューヘルパーメソッドだと思っていて、`do`以下のブロックの内容を`label`メソッドに渡しているという理解です。

その上で`do`を使用した理由は、他の部分のコードを参考にしたため、ですかね？同ファイルの70行目などを参考にしたと記憶しています。

2023-01-30 08:10 UTC, uchihiro04 commented on app/views/regular_events/_form.html.slim
> +                = f.label :all do
ありがとうございます🙇‍♂️

>f.labelの部分はFormBuilderオブジェクトのlabelというビューヘルパーメソッドだと思っていて、do以下のブロックの内容をlabelメソッドに渡しているという理解です。

なるほど！　`label`がビューヘルパーメソッドであれば`do`がついているのも納得です🙂　`f.label`の部分をメソッドではなくHTMLタグのslimだと勘違いしていたことが、自分がコードを読み解けなかった理由だったこともはっきりしました😅

また、糖衣構文として `do`を省略できるとのことでした。
[slim/README\.jp\.md at main · slim\-template/slim](https://github.com/slim-template/slim/blob/main/README.jp.md#%E3%83%98%E3%83%AB%E3%83%91-%E3%82%AD%E3%83%A3%E3%83%97%E3%83%81%E3%83%A3%E3%81%A8%E3%82%A4%E3%83%B3%E3%82%AF%E3%83%AB%E3%83%BC%E3%83%89)
doの有無は統一されていた方がいいと思うので、現在のコードのように`do`が明示された状態で問題ないと思います🙂

2023-01-30 08:16 UTC, uchihiro04 approved these changes
@hikarook94 
コメントありがとうございます！　Approveとさせていただきます👍
slimの`do`につきまして、とても勉強になりました😄

2023-01-30 14:36 UTC, hikarook94 commented
@komagata 
メンバーの方にApproveしていいただいたのでレビューをお願いいたします！

2023-02-04 21:15 UTC, komagata requested changes

2023-02-04 21:15 UTC, komagata commented on app/controllers/regular_events_controller.rb
> +    User.students_and_trainees.each do |user|
人数分ループしてSQLを発行すると非常に遅くなってしまうので、insert_allなどを使いたいです〜

[Railsのbulk insert事情 \- UUUMエンジニアブログ](https://system.blog.uuum.jp/entry/2022/10/11/131234)

2023-02-12 04:13 UTC, hikarook94 commented on app/controllers/regular_events_controller.rb
> +    User.students_and_trainees.each do |user|
@komagata 
お疲れ様です！
`insert_all`を使うように修正してみました。ご確認よろしくお願いします🙏

2023-02-12 15:40 UTC, komagata commented on app/controllers/regular_events_controller.rb
> +    User.students_and_trainees.map { |user| { user_id: user.id } }
持ってくるカラムを絞るときはSQLを使った方がメモリ使用量も速度も速くなるのでそちらでお願いしたいです。

基本的にSQL（DBレベル）でできることはそちらでやった方が早くなります。

2023-02-18 07:45 UTC, hikarook94 commented on app/controllers/regular_events_controller.rb
> +    User.students_and_trainees.map { |user| { user_id: user.id } }
@komagata 
お疲れ様です！SQLを使うように修正しました！
ご確認よろしくお願いします👍

2023-02-23 03:57 UTC, komagata commented on app/controllers/regular_events_controller.rb
> +  def create_participants(students_and_trainees_ids)
controllerがfatになってしまっているのオブジェクト指向プログラミングの課題を思い出してクラスとして設計してみるといいと思います〜

2023-02-25 04:30 UTC, hikarook94 commented on app/controllers/regular_events_controller.rb
> +  def create_participants(students_and_trainees_ids)
@komagata 
`models/`にクエリーを持ったクラスを作ってそれをコントローラーから実行する、という感じにしてみました！
ご確認お願いします🙏

2023-02-25 09:37 UTC, komagata commented on app/models/regular_event_bulk_insert_query.rb
> +class RegularEventBulkInsertQuery
クラスを使う人から見てもう少し情報をカプセル化した方がいいかもしれません。
BulkInsertをするかどうか、Queryかどうかという情報はない方がわかりやすいかなと思いました。

例えばですが、`RegularEvent::ParticipantsCreator`とかにするなど。
また、privateメソッドが多くてテストしないと心配な粒度なのはクラスに分ける目印なので、watchの作成を他のクラス（Newspaperは使ってもどっちでもいいと思います）にするなどがいいかもです。

2023-03-06 13:35 UTC, hikarook94 commented on app/models/regular_event_bulk_insert_query.rb
> +class RegularEventBulkInsertQuery
@komagata 
お疲れ様です！
クラスを修正して、参加者を登録するクラスとWatchするクラスに分けてみました。
ご確認お願いします🙏

2023-03-11 13:44 UTC, komagata commented on app/models/regular_event_participants_watcher.rb
> +class RegularEventParticipantsWatcher
`RegularEvent::ParticipantsCreator`と合わせるためには`RegularEvent::ParticipantsWatcher`の方がいいかもです〜。

2023-03-11 13:44 UTC, komagata commented on app/models/regular_event/participants_creator.rb
> +class RegularEvent::ParticipantsCreator
この書き方だとRegularEventという定数が存在しない状態で読み込むとエラーになるので、

```ruby
class RegularEvent
  class ParticipantsCreator
  end
end
```

のような書き方がいいかもです〜。

2023-03-11 13:44 UTC, komagata commented on app/models/regular_event/participants_creator.rb
> +    @time_utc = Time.current.utc
現在時間はテストしやすいクラスにするために外部から注入できるようにするのがいいかもです。

2023-03-21 11:25 UTC, hikarook94 commented
@komagata 
お疲れ様です！レビューいただいた点を修正しました。
ご確認よろしくお願いいたします🙏

2023-03-25 01:17 UTC, komagata commented on app/models/regular_event/participants_creator.rb
> +      ActiveRecord::Base.connection.execute(sql) unless new_participants_ids.empty?
ちょっと僕が経緯を忘れちゃったからかもですが、なんで insert_all は使わないようになったんでしたっけ？

2023-03-25 05:33 UTC, hikarook94 commented on app/models/regular_event/participants_creator.rb
> +      ActiveRecord::Base.connection.execute(sql) unless new_participants_ids.empty?
https://github.com/fjordllc/bootcamp/pull/5949#discussion_r1103824340 のコメントを読んで insert_all ではなくSQLを使うようにしました。

2023-03-29 02:49 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-03-29 02:49 UTC, komagata commented on app/models/regular_event/participants_creator.rb
> +      ActiveRecord::Base.connection.execute(sql) unless new_participants_ids.empty?
@hikarook94 なるほどです、ありがとうございます〜！

2023-03-29 02:54 UTC, merged