休会から復帰時に管理者・メンターに通知が飛ぶようにした
fjordllc/bootcamp pull request #6059
Opened 2023-01-16 15:47 UTC by sadanora

## Issue

- #5952 

## 概要
休会復帰時に管理者・メンターに通知が飛ぶようにしました。
通知はサイト内通知とメール通知です。

## 変更確認方法
1. `feature/add-notification-of-comeback`をローカルに取り込む
1. Stripeの処理をコメントアウトする
開発環境で休会復帰操作を行うと回避できないStripeのエラーが発生するため、Stripe関連の処理はコメントアウトして動作確認をします。

https://github.com/fjordllc/bootcamp/blob/4efa1c09434f93c1d3ddbee024996c483988e9d5/app/models/user.rb#L721-L729
上記`comeback!`メソッドの一部をコメントアウトして、以下のようにしてください。
```ruby
  def comeback!
    update_last_returned_at!

#    subscription = Subscription.new.create(customer_id, trial: 0)

    self.hibernated_at = nil
#    self.subscription_id = subscription['id']
    save!(validate: false)
  end
```

3. `$ bin/rails s`でアプリを立ち上げる。
4. 休会復帰ページhttp://localhost:3000/comeback/new にアクセス。
5. メールアドレス`kyuukai@fjord.jp`で休会復帰する。
6. http://localhost:3000/letter_opener/ を開き、休会復帰のメール通知が飛んでいることを確認する。
    - DBに登録されているユーザーがfixture通りなら5件飛んでいるはずです。 
7. `kyuukai`からログアウト
8. `komagata`(管理者もしくはメンターアカウント)でログイン。
9. サイト内通知 http://localhost:3000/notifications で休会復帰のお知らせが飛んでいることを確認する。

## Screenshot
### 変更後
- メール通知
![mail](https://user-images.githubusercontent.com/66685066/213612702-f881d938-6a93-48a3-b281-eafc709dd185.png)
- サイト内通知
![notice](https://user-images.githubusercontent.com/66685066/213613900-55b6ee1f-a947-40a4-927d-93ff0ca50a0a.png)

## 参考にしたPR
- #5961 
- #6063 
- #6070

2023-01-20 03:56 UTC, sadanora commented
@futa4095 
おつかれさまです！
こちらのレビューをお願いしたいのですがご都合いかがでしょうか？

2023-01-20 04:38 UTC, futa4095 commented
OKです〜
23日までに見れると思います〜

2023-01-22 01:29 UTC, futa4095 requested changes
1箇所気になったので確認お願いしますー

2023-01-22 11:49 UTC, futa4095 approved these changes

2023-01-22 11:50 UTC, futa4095 commented
良さそうです！Approveしました！！

2023-01-22 12:34 UTC, sadanora commented
@futa4095 
早速のご確認ありがとうございます！
レビューありがとうございました〜！

@komagata 
メンバーレビューでApproveいただきましたので、レビューをお願いいたします。

2023-01-25 01:59 UTC, komagata reviewed
conflictの修正をお願いします〜

2023-01-31 08:23 UTC, sadanora commented
@komagata 
コンフリクトを解消しました。
再レビューよろしくお願いいたします！

2023-02-04 21:20 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-02-04 21:20 UTC, merged

2023-02-05 04:04 UTC, sadanora commented
レビューありがとうございました！