提出通知をactive delivery化する
fjordllc/bootcamp pull request #6084
Opened 2023-01-22 09:25 UTC by hikarook94

## Issue

- #5877 

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-01-25 01:33 UTC, komagata commented
@hikarook94 苦戦しているのであれば過去のactive_delivery関係のPRを参考にしてみるのはいかがでしょうか〜

2023-01-26 12:19 UTC, hikarook94 commented
@komagata 
お疲れ様です。
最新のmainをマージしてみましたが、メール通知は送信されませんでした。
現在起きている事象と試したことは以下の通りです。ヒントや次のアクションについて教えていただけたら助かります...🙏
#6085 で議論されている事象と同様のものかもしれません。

# 解決したいこと

### 期待する結果
bootcampアプリでプラクティスの課題を提出したら、アプリ内通知とメール通知が発行される。

### 実際の結果
アプリ内通知は発行されるが、メール通知が発行されない。

### 詳しい状況
確認手順
1. `feature/use-active_delivery-for-submitted-notifications`ブランチ
1. `$ bin/setup`
1. `$ bin/rails s`
1. ブラウザで`http://localhost:3000/`にアクセス
1. `mentormentaro`でログイン、プラクティスをWatch状態にして、ログアウト
1. `hajime`でログイン、`mentormentaro`でWatchしたプラクティスで提出物を作り、提出する
1. LetterOpenerWeb（`http://localhost:3000/letter_opener/`）にアクセス、
1. Refreshしてメールが届いているか確認する

LetterOpenerWebではメールが送信されていることを確認できませんでした。
ログを見ると、メール送信ジョブがキューに追加されているが、実行はされていないようです。エラーのログは出ていません。
```
[ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 72714c2b-4b6d-4522-bb4d-3889761c0297) to Async(default) with arguments: "ActivityMailer", "submitted", "deliver_now", {:params=>{:product=>#<GlobalID:0x000000010f2ec718 @uri=#<URI::GID gid://bootcamp/Product/1071056610>>, :receiver=>#<GlobalID:0x000000010f2ec178 @uri=#<URI::GID gid://bootcamp/User/534981761>>, :message=>"sumiさんが「Terminalの基礎を覚える」の提出物を提出しました。"}, :args=>[]}
```



# 試したこと
## その1

### 考えたことや調べたこと
類似の事象が起きたIssueから、非同期に実行されるメール送信処理と他の何らかの処理が衝突しているのでは？と考えました。
同Issueでのやりとりによると、メール送信
- 参考：[確認通知をactive_delivery化](https://github.com/fjordllc/bootcamp/pull/5924)

### やったこと
`notify!`で同期的に通知処理をするようにして、同様の手順で結果を確認する
```
ActivityDelivery.with(product: product, receiver: receiver, message: message).notify!(:submitted)
```

### やった結果
メール通知が送信されていることがLetterOpenerWebで確認できました。
メール通知送信の前後に行われている他の処理が干渉してメールが送られていないのでは？と思いました。

## その2

### 考えたことや調べたこと
同Issueから、コールバックのいずれかの処理がメール送信ジョブと衝突しているのかもしれない？と考えました。
- 参考：[確認通知をactive_delivery化](https://github.com/fjordllc/bootcamp/pull/5924)

### やったこと
`app/models/product_callbacks.rb`の`after_create`と`after_save`のメール送信以外の処理をコメントアウトして、メール通知が送信されるか確認する。

### やった結果
メール通知が送信されていることは確認できませんでした。
コールバックにあるメール通知の送信処理前後の処理は今回の事象とは関係がないのかも？と思いました。

## その3

### 考えたことや調べたこと
メール送信に係る処理の中に問題があるのでは？と考えた。

### やったこと
メール送信に係る処理を`app/controllers/products_controller.rb`に移行した。
```ruby
class ProductsController < ApplicationController
# （略）
  def create
    @product = Product.new(product_params)
    @practice = find_practice
    @product.practice = @practice
    @product.user = current_user
    set_wip
    update_published_at
    if @product.save
      notify_watching_mentors # これ
      redirect_to @product, notice: notice_message(@product, :create)
    else
      render :new
    end
  end
# （略）
  def send_notification(product:, receivers:, message:) # これ
    receivers.each do |receiver|
      ActivityDelivery.with(product: product, receiver: receiver, message: message).notify(:submitted)
    end
  end

  def notify_watching_mentors # これ
    practice = Practice.find(@product.practice_id)
    mentor_ids = practice.watches.where.not(user_id: @product.user_id).pluck(:user_id)
    mentors = User.where(id: mentor_ids)
    send_notification(
      product: @product,
      receivers: mentors,
      message: "#{@product.user.login_name}さんが#{@product.title}を提出しました。"
    )
  end
end
```

### やった結果
メール通知が送信されていることがLetterOpenerWebで確認できました。
それぞれの「試したこと」から、メール送信処理やその他の処理に問題があるというよりコールバック自体に問題があるのでは？と思いましたが、具体的な原因については結局わからずです。

## その4
### 考えたことや調べたこと
最新のmainをpullしてみれば動きそう？mainをpullして動作を確認してみる。
### やったこと
- 最新のmainをpullして上記の確認手順で試す
- 「試したことその2」と同様にコメントアウトして上記の確認手順でメールが送信されるか試す 
### やった結果
いずれも3回に1回くらいの割合でしかメール通知が送信されなかった。



長くなってしまい恐縮ですが、ご確認お願いします🙏

2023-02-01 05:09 UTC, komagata commented
@hikarook94 メールが送られない場合はメール送信処理中にエラーが起きているのだと思います。
メール送信が非同期なので普通にログが出ないので、どんなエラーが起きているのかを知る方法を調べるといいかもです〜。

2023-02-01 11:32 UTC, hikarook94 commented
@komagata 
情報ありがとうございます！非同期処理は通常だとエラーでもログが出ないんですね...
調べてみます🙆‍♂️

2023-02-15 12:59 UTC, hikarook94 commented
@komagata 
お疲れ様です！
以下のようにしたところエラーを表示することができました。
```ruby
class ApplicationMailer < ActionMailer::Base
  default from: 'フィヨルドブートキャンプ <noreply@bootcamp.fjord.jp>'
  layout 'mailer'
  rescue_from(StandardError) do |e|
    Rails.logger.info(e.message)
  end
end
```
```
Error while trying to deserialize arguments: Couldn't find Product with 'id'=1071056626
```
このエラーメッセージで調査したところ、https://github.com/fjordllc/bootcamp/pull/6085#issuecomment-1409734307 でmaeda-mさんが指摘されているように、デシリアライズ時にProductがCommitされる前に参照してしまっているため発生しているエラーのようです。

現在通知の処理が`after_save`コールバック内で行われていますが、これを`after_commit`コールバックで行うようにすることでデータがCommitされるまで処理を待つことができるようですが、この修正方法で問題はないでしょうか？

2023-02-15 14:14 UTC, hikarook94 commented
ふりかえり・計画MTGで相談して、https://github.com/fjordllc/bootcamp/pull/6085 を参考に`after_commit`で修正する旨を確認しました🙏

2023-02-16 07:27 UTC, hikarook94 commented
@futa4095 
お疲れ様です！
ご都合よろしければこちらのPRのレビューをお願いしていいでしょうか🙏

2023-02-17 00:44 UTC, futa4095 commented
@hikarook94 2,3日のうちに見ますね！

2023-02-17 09:34 UTC, futa4095 reviewed
activity_mailerを使うようになったのでnotification_mailerの方は不要だと思います

https://github.com/fjordllc/bootcamp/blob/b9f3fd6755bbb2b91defb2f49c6954af43f2efd4/app/mailers/notification_mailer.rb#L40-L45

メールのプレビューも機能していないのでnotification_mailerの方は削除で良いと思います
http://localhost:3000/rails/mailers

2023-02-18 02:46 UTC, komagata commented on app/models/product.rb
> +  after_commit ProductCallbacks.new, on: %i[create update]
おお、そんなものがあるんですね、めちゃくちゃ便利そう！

2023-02-20 13:46 UTC, hikarook94 commented
@futa4095 
お疲れ様です！いただいたレビューをもとに修正しましたのでご確認よろしくお願いいたします🙇‍♂️

2023-02-21 03:44 UTC, futa4095 approved these changes
コードも動作も良さそうなのでApproveします👍

2023-02-21 05:45 UTC, hikarook94 commented
@futa4095 
レビューありがとうございました！

2023-02-21 05:45 UTC, hikarook94 commented
@komagata 
メンバーからApproveいただいたのでレビューをお願いいたします！

2023-02-25 08:40 UTC, komagata commented on app/mailers/activity_mailer.rb
> +  def submitted(args = {})
他の方の処理を参考にして、メール通知を希望してない方には送信しないという処理の追加をお願いします〜

2023-02-27 13:45 UTC, hikarook94 commented on app/mailers/activity_mailer.rb
> +  def submitted(args = {})
@komagata 
修正しました！
また`message`という変数名が提出通知の`@message`と被っていたので、他の通知と同じくなるよう揃えました。

2023-02-27 17:21 UTC, komagata requested changes

2023-02-27 17:21 UTC, komagata commented on test/mailers/notification_mailer_test.rb
> -  test 'submitted' do
これの代わりのテストは何になりますか？

2023-02-27 17:21 UTC, komagata commented on test/mailers/previews/notification_mailer_preview.rb
> -  def submitted
こちらも代わりのテストは何になりますでしょうか？

2023-03-03 08:21 UTC, hikarook94 commented on test/mailers/previews/notification_mailer_preview.rb
> -  def submitted
こちらも同様です
ご確認お願いします🙏

2023-03-11 13:04 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-03-11 13:04 UTC, merged