フォローしているユーザーの日報通知をactive_delivery化
fjordllc/bootcamp pull request #6133
Opened 2023-01-30 02:45 UTC by maimux2x

## Issue

- #5885 

## 概要
フォローしているユーザーの日報通知をactive_delivery化しました。
- `NotificationFacade` が不要になり、通知送信は `ActivityDelivery` を経由して、サイト内通知が実行されるようになりました。
  - `NotificationFacade` によって実行されて板処理の部分に関わるコードを`ActiveDelivery` で実行されるように修正しました
  - 通知、メール送信、テストがそれぞれ影響を受け、修正しています。

## 変更確認方法

フォローしているユーザーの日報通知をactive_delivery経由で送信できることを確認する手順です。

1. `feature/change_following_report_notification` をローカルに取り込みます
2. `bin/setup` を実行します
3. `bin/rails s` でサーバーを立ち上げます
4. テストユーザー(kensyu)アカウントでログインし、日報を投稿する
5. テストユーザー(muryou)アカウントでログインし、手順4の通知が来ていることを確認する
↓以下は後述の問題によって現状メールが飛ばないため検証できません
6. http://localhost:3000/letter_opener/ を開いてメールが届いていることを確認する

## Screenshot
処理の置き換えのため変更前後で違いはありません。

<img width="344" alt="日報通知" src="https://user-images.githubusercontent.com/76797372/215376174-af33a620-aa83-4343-b8cc-cc095e6e8aec.png">

## メールが飛ばない問題
https://github.com/fjordllc/bootcamp/pull/6084
https://github.com/fjordllc/bootcamp/pull/6085#issuecomment-1404416304
https://github.com/fjordllc/bootcamp/pull/5924
上記issueも同様にメールが配信されない問題に言及しています。
こちらでの対応方針がまだ提示されていないため、本PRでは ***メールは配信されない*** 状態で作成しています。

2023-02-04 05:30 UTC, maimux2x commented
@dowdiness 
お疲れ様です。
お手隙の際にレビューをお願いできますと幸いです🙏

2023-02-15 12:41 UTC, dowdiness commented
@maimux2x 
遅くなってすいません！
明日までにはレビュー対応するのでお待ちください🙇‍♂️

2023-02-16 19:36 UTC, dowdiness requested changes
@maimux2x 
お待たせしましたー！
手元で試してみたところ、きちんと通知とメールの送信がされていたので機能面では問題無いと思います。

ただプレビューのテストファイルで存在しないFixtureを使用していてエラーが出ていたのでそちらのほうの修正よろしくお願いします🙏

2023-02-16 19:36 UTC, dowdiness commented on test/mailers/previews/activity_mailer_preview.rb
> +    report = Announcement.find(ActiveRecord::FixtureSet.identify(:report23))
following_reportのプレビューメールを実際に見てみようとしたところエラーが出て表示できませんでした。

<img width="1440" alt="スクリーンショット 2023-02-17 4 23 09" src="https://user-images.githubusercontent.com/1616717/219467345-604dfb03-2483-4952-bb1e-72fb2bd7e03e.png">

どうやらreport23という名前のFixtureは存在しないようです。

ちなみにメールのプレビューは　http://localhost:3000/rails/mailers で見れます。

2023-02-20 14:37 UTC, maimux2x commented on test/mailers/previews/activity_mailer_preview.rb
> +    report = Announcement.find(ActiveRecord::FixtureSet.identify(:report23))
ありがとうございます！
修正しました〜！

2023-02-23 12:25 UTC, dowdiness commented on test/mailers/previews/activity_mailer_preview.rb
> +    report = Announcement.find(ActiveRecord::FixtureSet.identify(:report23))
手元で確認してみたところメールの題名と本文で日報を書いた人が別々になってました。

<img width="1440" alt="スクリーンショット 2023-02-23 21 18 52" src="https://user-images.githubusercontent.com/1616717/220904227-abbf3f91-e71c-4470-be4e-3f346ba901b7.png">

メールのテンプレートで＠senderを使うべき所で＠userを使っているのでメールの受け手が日報を書いたかのようになっています。

2023-02-23 12:26 UTC, dowdiness commented
@maimux2x 
すいませんメールのテンプレートで見逃していた間違いが見つかったので修正お願いしますー。

2023-02-25 04:45 UTC, maimux2x commented on test/mailers/previews/activity_mailer_preview.rb
> +    report = Announcement.find(ActiveRecord::FixtureSet.identify(:report23))
見落としがあってすみません・・・！
修正しました！

加えてメールが飛ばなくなっており、以下のPRに合わせてコールバックの実行を `after_save_commit` に修正しました。
https://github.com/fjordllc/bootcamp/pull/6084

ご確認の程よろしくお願いします🙏

2023-03-02 12:31 UTC, dowdiness commented on test/mailers/previews/activity_mailer_preview.rb
> +    report = Announcement.find(ActiveRecord::FixtureSet.identify(:report23))
確認しました！
OKですー

2023-03-02 12:32 UTC, dowdiness approved these changes
動作確認しましたー！
問題なさそうなのでApproveします👍

2023-03-05 02:26 UTC, maimux2x commented
@komagata 
メンバーレビューが完了したため、チームリーダーレビューをお願いいたします🙏

2023-03-11 13:09 UTC, komagata reviewed
conflictの解消をお願いします〜

2023-03-12 13:34 UTC, maimux2x commented
@komagata 
コンフリクトの解消完了いたしました！

2023-03-17 22:19 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-03-17 22:19 UTC, merged