ページが表示されてからお知らせ削除する
fjordllc/bootcamp pull request #6212
Opened 2023-02-12 07:22 UTC by akingo55

## Issue

- https://github.com/fjordllc/bootcamp/issues/5908

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-02-14 15:05 UTC, akingo55 commented
@OdenTakashi 
お疲れ様です！
こちらのPRのレビューをお願いします:pray:

2023-02-15 07:41 UTC, OdenTakashi commented
@akingo55 
お疲れ様です！
レビュー依頼ありがとうございます！
こちら確認させていただきます！👍

2023-02-20 11:56 UTC, akingo55 commented
@OdenTakashi 
こちらいかがでしょうか？:eyes:

2023-02-21 06:30 UTC, OdenTakashi commented
@akingo55 
お待たせいたしました！ただいま確認が完了しました！
問題ないと思うので僕からはApproveとさせていただきます！🙏

2023-02-21 06:30 UTC, OdenTakashi approved these changes

2023-02-21 11:24 UTC, akingo55 commented
@komagata 
メンバーのレビューが通ったので確認お願いします！

2023-02-25 08:49 UTC, komagata requested changes

2023-02-25 08:49 UTC, komagata commented on test/system/announcements_test.rb
> +    page.accept_confirm do
```suggestion
   accept_confirm do
```

pageは書かなくてもいいように思います〜

2023-02-25 08:49 UTC, komagata commented on app/controllers/api/footprints_controller.rb
> +    footprintable_data = footprintable
`_data`は変数名が無意味な感じになっちゃうので何か別の方法にしたいですね。
特にRubyは「名前重要」という考えが大事にされているので、転職の時とかにみられるとマイナスになってしまう気がします。

例えばですが、footprintableメソッドは返り値をキャッシュするようにして、何度使っても速度低下がないようにするなどの方法があるかなと思いました。

2023-02-25 13:42 UTC, akingo55 commented on test/system/announcements_test.rb
> +    page.accept_confirm do
こちら修正しました！
https://github.com/fjordllc/bootcamp/pull/6212/commits/98d07156f81bbfbfe7773a2a79d010d7a125ebe6

2023-02-25 13:49 UTC, akingo55 commented on app/controllers/api/footprints_controller.rb
> +    footprintable_data = footprintable
@komagata 
なるほど、いい変数名が思い付かず苦肉の策で`_data`つけてました。

1つのAPIで`footprintable`メソッドを呼び出す回数を1回にしたいというのが今回の修正の目的だったので、`before_action`で`footprintable`メソッドを実行し、インスタンス変数化するパターンで修正してみました。
速度低下を改善するのが目的ではなかったので、キャッシュを使わない方がいいかなと考えたためです。
こちらはいかがでしょうか。
https://github.com/fjordllc/bootcamp/pull/6212/commits/8ede278fbfac3563aa74154b91d43b85f4f5865f

2023-02-27 16:39 UTC, komagata commented on app/controllers/api/footprints_controller.rb
> +  before_action :footprintable
```suggestion
  before_action :footprintable, only: %i(index)
```

みたいな感じで絞った方がいいかもです〜

2023-03-01 13:58 UTC, akingo55 commented on app/controllers/api/footprints_controller.rb
> +  before_action :footprintable
@komagata 
https://github.com/fjordllc/bootcamp/pull/6212/commits/3aff637c5f3220c2a19ef3df9898e6e9a7ddb0c8
こちらindexだけに絞るように修正しました！

2023-03-07 09:50 UTC, akingo55 commented on app/controllers/api/footprints_controller.rb
> +  before_action :footprintable
@komagata 確認お願いします！

2023-03-11 13:57 UTC, komagata commented on app/controllers/api/footprints_controller.rb
> +    footprintable_data = footprintable
@akingo55 インスタンス変数に入れておくの良いと思います〜！

2023-03-11 13:58 UTC, komagata commented on test/system/notification/graduation_test.rb
> +    page.has_css?('p.flash__message', text: 'ユーザー情報を更新しました。')
```suggestion
   has_css?('p.flash__message', text: 'ユーザー情報を更新しました。')
```
これでいいかも？

2023-03-25 07:20 UTC, akingo55 commented on test/system/notification/graduation_test.rb
> +    page.has_css?('p.flash__message', text: 'ユーザー情報を更新しました。')
@komagata 修正しました！
https://github.com/fjordllc/bootcamp/pull/6212/commits/6f1f090ebfc733275ed14bb6494b986ef676f077

2023-03-28 08:05 UTC, komagata requested changes

2023-03-28 08:05 UTC, komagata commented on app/controllers/api/footprints_controller.rb
> +    @footprintable = if params[:footprintable_type].nil?
👍

2023-03-28 08:05 UTC, komagata commented on test/system/announcements_test.rb
> +    assert page.has_css?('p.flash__message', text: 'お知らせを作成しました')
```suggestion
    assert has_css?('p.flash__message', text: 'お知らせを作成しました')
```

同じくこちらもpageいらないかもです。他の箇所もチェックしてみてください〜

2023-04-01 14:58 UTC, akingo55 commented on test/system/announcements_test.rb
> +    assert page.has_css?('p.flash__message', text: 'お知らせを作成しました')
@komagata 
すみません、確認漏れてました。
再度チェックし不要なpage削除しました。

2023-04-08 06:40 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-04-08 06:40 UTC, merged