ログインしていない状態でプラクティスページにアクセスしたときの meta description を設定。 #6389
fjordllc/bootcamp pull request #6406
Opened 2023-04-09 21:07 UTC by YukiWatanabe824

## Issue

- Issue番号

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-04-09 21:47 UTC, YukiWatanabe824 commented
当初main以外のブランチからこのブランチを作ってプルリクエストを送ってしまい、対応した際の履歴が残っています。

2023-04-09 23:36 UTC, YukiWatanabe824 commented
@dowdiness 
お疲れさまです！
こちらのレビューをお願いできますでしょうか？？

2023-04-16 03:33 UTC, YukiWatanabe824 commented
@syo-tokeshi 
お疲れさまです！
こちらのレビューをお願いしたいのですがいかがでしょうか？

2023-04-17 00:41 UTC, syo-tokeshi commented
> @syo-tokeshi お疲れさまです！ こちらのレビューをお願いしたいのですがいかがでしょうか？

@YukiWatanabe824 
お疲れ様です😊

はい！お受けさせて頂きたいと思います🙇‍♂️
明日までのレビューでよろしいでしょうか？
なるべく早く対応するつもりです🙇‍♂️

2023-04-17 04:58 UTC, syo-tokeshi requested changes
レビュー致しました🙇‍♂️
文言以外は全て問題ないと思いました🙇‍♂️

「プラクティス」→「ドキュメント」

へ、言葉を変更する必要があるかどうかだけ、確認頂いてもよろしいでしょうか？

2023-04-17 04:58 UTC, syo-tokeshi commented on app/views/layouts/not_logged_in.html.slim
> +    meta name='description' content="オンラインプログラミングスクール「フィヨルドブートキャンプ」のプラクティス「#{@practice.title}」のページです。"
すみません、
こちら「プラクティス」ではなく「ドキュメント」にした方が良いのではないでしょうか？
町田さんが「ドキュメント」という言葉を指定しているからです🙇‍♂️
https://github.com/fjordllc/bootcamp/issues/6391
<img width="1186" alt="スクリーンショット 2023-04-17 13 45 11" src="https://user-images.githubusercontent.com/54713809/232380649-c92d32c7-e9b5-4222-95c7-e55a3e7b0c1b.png">

Watanabeさんの文章でも違和感は全くありませんが、確認した方が良い気がしました🙇‍♂️

それ以外はまったく問題ないと思いました🙇‍♂️

2023-04-17 04:58 UTC, syo-tokeshi commented on test/system/practice/completion_test.rb
> +      assert_selector "meta[name='description'][content='オンラインプログラミングスクール「フィヨルドブートキャンプ」のプラクティス「#{practices(:practice1).title}」のページです。']", visible: false
上を変更すると、こちらも「プラクティス」→「ドキュメント」に変更になるかもです🙇‍♂️

それ以外のテストコードは全て問題ないと思います！

テスト名も、`assert_selector`メソッドの使い方等も全て問題ないように見えました😊

2023-04-17 09:31 UTC, syo-tokeshi approved these changes

2023-04-17 09:52 UTC, YukiWatanabe824 commented
@syo-tokeshi 
レビューありがとうございます！
仕事のため連絡遅くなってしまいました。すみません🙇🏻

「ドキュメント」が「プラクティス」になっているのは私が手打ちで打ち間違えた可能性が高いですね💦これは修正いたします。

2023-04-17 09:55 UTC, syo-tokeshi commented
> @syo-tokeshi レビューありがとうございます！ 仕事のため連絡遅くなってしまいました。すみません🙇🏻
> 
> 「ドキュメント」が「プラクティス」になっているのは私が手打ちで打ち間違えた可能性が高いですね💦これは修正いたします。

@YukiWatanabe824 
あ、いえ！🙇‍♂️
最初、私が間違えました！！🙇‍♂️

Watanabeさんは正しいです🙇‍♂️
失礼いたしました！！🙇‍♂️

2023-04-17 09:57 UTC, YukiWatanabe824 commented
@syo-tokeshi 
即レス助かります！状況把握しました！
私もIssue見ずにメールで早とちりしてしまいました笑

また次回もよろしくおねがいします🙏！

2023-04-17 09:58 UTC, YukiWatanabe824 commented
@komagata 
お疲れさまです！
こちら受講生のレビューでapprovedいただきましたのでご確認をお願いいたします。

2023-04-17 09:59 UTC, syo-tokeshi commented
> また次回もよろしくおねがいします🙏！

よろしくです〜😊😊

2023-04-17 11:21 UTC, syo-tokeshi commented
@YukiWatanabe824 
お疲れ様です！

自分も似たissueをやってて、今の実装の問題点を見つけました🙇‍♂️

1. docを参照する際も、ログインしていないユーザーはnot_logged_in.html.slimに飛ばされるので、`practices_controller.rb`から`not_logged_in.html.slim`に飛ばされる際と、meta descriptionの表示を分ける必要がありそうです。
https://github.com/fjordllc/bootcamp/issues/6391

つまり、今のWatanabeさんの実装だと、practices_controller.rbから飛ばされる以外でも、そのmeta descriptionが表示されてしまいます🙇‍♂️

[追記]
もし、解決策が分からない際は私に聞いて大丈夫です🙇‍♂️
私は多分、解決策が分かりました🙇‍♂️

2023-04-17 12:24 UTC, machida commented
@YukiWatanabe824 @syo-tokeshi 今回のIssueはログインしていないときにだけ表示するmeta description の設定でお願いします。ログイン時のプラクティスの個別ページの meta description は別Issueで別の文言に差し替える予定です。

2023-04-17 14:32 UTC, YukiWatanabe824 commented
@syo-tokeshi @machida 
詳細承知しました！
そもそもIssueで指定された条件を満たしていませんでしたね💦
すみません。修正いたします🙇🏻

2023-04-18 09:44 UTC, ogawa-tomo commented
@YukiWatanabe824 @syo-tokeshi 
横から失礼します:bow:
チャットで話してるのが見えたので、気になって見にきました。
ちなみにの情報共有ですが、私もほぼ同じようなイシューに取り組んでます、ということだけお知らせしておきます〜
https://github.com/fjordllc/bootcamp/pull/6448
こちらはいまのところ困ってはいませんが、もしお気づきのことがあればお知らせください:pray::pray:

2023-04-18 10:12 UTC, syo-tokeshi commented
> @YukiWatanabe824 @syo-tokeshi 横から失礼します🙇 チャットで話してるのが見えたので、気になって見にきました。 ちなみにの情報共有ですが、私もほぼ同じようなイシューに取り組んでます、ということだけお知らせしておきます〜 #6448 こちらはいまのところ困ってはいませんが、もしお気づきのことがあればお知らせください🙏🙏

@ogawa-tomo 
お疲れ様です。
あ、、
理解いたしました🙇‍♂️

@YukiWatanabe824 
お疲れ様です。
ogawaさんの実装みたいに、
`unauthorized_show.slim`
に書き込めば解決できそうですね、すんなり🙇‍♂️

ミスリードしてすみませんでした🙇‍♂️

Watanabeさんの例だと、
`app/views/practices/unauthorized_show.slim`
にmeta descriptionを書き込めば、
例えば「Q&A」からはこのページに飛ばないので(Q&Aからは`app/views/questions/unauthorized_show.slim`に飛ぶ)、
整合性が保てそうですね😊

単純な事に気付けなくてすみませんでした🙇‍♂️

2023-04-18 21:38 UTC, YukiWatanabe824 commented
@ogawa-tomo 
@syo-tokeshi 
情報共有助かります!ありがとうございます🙇🏻

やっぱり最初に私がやったlayoutへの実装が仕様に適してなかったですね😅layoutだと全ページに反映されてしまいますし💦
ogawa-tomoさんのやり方を参考に変更してみます💪

2023-04-18 22:06 UTC, YukiWatanabe824 commented
@syo-tokeshi 
お疲れさまです。
修正しましたので再度ご確認お願いできますでしょうか？

レビューできる状態かちょっとわからないので、レビューできないなどありましたらご連絡いただけますか🙇🏻

2023-04-19 02:50 UTC, syo-tokeshi approved these changes
確認いたしました🙇‍♂️
大丈夫だと思います😊
勉強になりました！！🙇‍♂️

2023-04-19 02:50 UTC, syo-tokeshi commented on app/views/practices/unauthorized_show.slim
> +- description "オンラインプログラミングスクール「フィヨルドブートキャンプ」のプラクティス「#{@practice.title}」のページです。"
ありがとうございます🙇‍♂️
`app/views/practices/`の下にある`unauthorized_show.slim`に書かれてるので大丈夫だと思います😊

2023-04-19 03:18 UTC, YukiWatanabe824 commented
@syo-tokeshi 
ありがとうございます！
最初の実装の問題点を発見していただいて非常に助かりました🙇🏻 後で分かるとまた大変ですから。

@komagata 
お疲れさまです。
こちら受講生からapprovedいただきましたのでご確認いただけますでしょうか？

2023-04-19 13:02 UTC, komagata commented on test/system/practice/completion_test.rb
> +  test 'Appropriate meta description is displayed when accessed by non-logged-in user' do
```suggestion
  test 'appropriate meta description is displayed when accessed by non-logged-in user' do
```
他のテストに合わせて小文字から始めるのがいいと思います〜

2023-04-19 21:43 UTC, YukiWatanabe824 commented
@komagata 
レビューありがとうございます。

指摘いただいた箇所を修正しました。
再度ご確認お願いします🙇🏻

2023-04-30 06:36 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-04-30 06:36 UTC, merged