プラクティスをwatchしているメンターへの提出物の通知をnewspaperに置き換えた
fjordllc/bootcamp pull request #6444
Opened 2023-04-14 06:52 UTC by monyatto

## Issue

- Issue番号

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-04-29 05:02 UTC, monyatto commented
@ymmtd0x0b
お疲れさまです！　もしご都合よろしければレビューお願いできますでしょうか？
全然急ぎではなく、2,3週間程度で最初の確認いただけたら嬉しいなくらいです🙇🏻

（余談ですが、今回のissueに対応するにあたって、ヤマモトさんのこちらの日報（[【180】 チーム開発＃１３：Newspaper の仕組み \| FBC](https://bootcamp.fjord.jp/reports/69613)）がとても参考になりました😊）

ご確認のほどよろしくお願いします。

2023-04-29 06:50 UTC, ymmtd0x0b commented
@monyatto 
お疲れ様です！
レビュー依頼了解しました！ご希望の期限内にはご連絡できると思います💪

> （余談ですが、今回のissueに対応するにあたって、ヤマモトさんのこちらの日報（[【180】 チーム開発＃１３：Newspaper の仕組み | FBC](https://bootcamp.fjord.jp/reports/69613)）がとても参考になりました:blush:）

わぁ ありがとうございます！少しでもお役に立てていると嬉しいです〜

2023-05-01 20:10 UTC, ymmtd0x0b reviewed
@monyatto 
お疲れ様です！
動作OKでした🎉 改めて newspaper を勉強する機会になって助かります〜

１点、ご提案というカタチでコメントしていますのでご確認をお願いします🙏

2023-05-07 12:04 UTC, monyatto commented
@komagata 
チームメンバーからApproveいただいたのでご確認お願いします🙏

2023-05-12 09:13 UTC, ymmtd0x0b approved these changes
@monyatto 
お疲れ様です！
  まだ Approve していなかったのですが、通知に気付いて更新内容を確認させていただきました！ `:page_save`へ書き換えて頂いたおかげでコードがよりスッキリしたように感じます〜

既にkomagataさんへレビュー依頼されているので、少し順番が前後してしまいまいしたが、私からは Approve させて頂きます🎉

2023-05-13 00:20 UTC, monyatto commented
@ymmtd0x0b 
Approve いただいてると勘違いしておりました……！失礼しました🙏

改めましてご確認 & Approve ありがとうございます！
すっきり書けるやり方を知れて勉強になりました😊

2023-05-25 11:23 UTC, komagata requested changes

2023-05-25 11:23 UTC, komagata commented on app/models/product_notifier_to_advisers_belonging_same_company.rb
> +class ProductNotifierToAdvisersBelongingSameCompany
クラス名は名詞である必要があります。
notifierは名詞なので英語としてもちょっとおかしいかもです。

2023-05-30 03:19 UTC, monyatto commented on app/models/product_notifier_to_advisers_belonging_same_company.rb
> +class ProductNotifierToAdvisersBelongingSameCompany
`ProductNotifierToAdvisersBelongingSameCompany`は`ProductNotifier`が名詞で`ToAdvisersBelongingSameCompany`が名詞を修飾する前置詞句で「同じ会社に所属するアドバイザーへの提出物通知」という意味になるように名づけました。
英語的にどうおかしいのかが分かっていないので、ご教示いただけるとありがたいです🙇🏻

また、より適切なクラス名の方向性などあれば教えていただきたいです🙏

2023-06-05 02:35 UTC, monyatto commented on app/models/product_notifier_to_advisers_belonging_same_company.rb
> +class ProductNotifierToAdvisersBelongingSameCompany
`ProductNotifierForColleague`と`ProductNotifierForPracticeWatcher`に変更しました！

2023-06-05 02:36 UTC, monyatto commented
@komagata 
お疲れさまです！
修正完了しましたので、お手隙でご確認お願いします〜

2023-06-10 05:02 UTC, komagata commented on app/models/product_notifier_for_practice_watcher.rb
> +class ProductNotifierForPracticeWatcher
クラスにはテストが必ず欲しい感じです〜

2023-06-22 05:28 UTC, monyatto commented on test/models/product_notifier_for_practice_watcher_test.rb
> +    product.save!
`practice1_watch_mentormentaro`は汎用性高そうなのでfixtureから使用しましたが、productはそのまま使えるかつ汎用性高そうものが見つからなかったのでnewで作りました。もっと良いやり方があればご教示いただけると幸いです🙏

2023-06-22 05:29 UTC, monyatto reviewed
@komagata 
モデルのテストを追加完了しましたので、ご確認お願いします。

2023-06-26 08:31 UTC, komagata commented
@monyatto Mergeブランチができてしまっているようなので、 Rebaseを使ってみてください〜

2023-06-28 12:56 UTC, monyatto commented
@komagata 
修正しましたのでご確認お願いします〜

2023-06-28 20:48 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-06-28 20:49 UTC, merged