ログインしてないユーザーがDocsにアクセスした時、meta descriptionが表示されるようにする
fjordllc/bootcamp pull request #6458
Opened 2023-04-19 12:06 UTC by syo-tokeshi

## Issue

- #6391

## 概要

ログインしてないユーザーがDocsにアクセスした時、ドキュメント用のmeta descriptionが表示されるようにする

## 変更確認方法

1. ブランチ feature/set_document_meta_description_when_not_loginをローカルに取り込む
2. bin/rails sでローカル環境を立ち上げる
3. http://127.0.0.1:3000/pages/950453707 にアクセスする ※ログインしない状態でご確認お願い致します🙇‍♂️
4. こちらの写真のように、headタグの中に、「オンラインプログラミングスクール「フィヨルドブートキャンプ」のドキュメント「test1」のページです。」というmetaタグが表示されることを確認する
<img width="1464" alt="メタタグがある" src="https://user-images.githubusercontent.com/54713809/233068266-1c6b5437-8dd4-4c89-8fb8-499ae1ee9eb4.png">

## Screenshot

### 変更前
「オンラインプログラミングスクール「フィヨルドブートキャンプ」のドキュメント「test1」のページです。」という文言のmetaタグがない
<img width="1373" alt="メタタグが無い" src="https://user-images.githubusercontent.com/54713809/233068304-08ebb5b0-8b0f-4e23-aecb-856b469e636d.png">

### 変更後
metaタグがある。
<img width="1464" alt="メタタグがある" src="https://user-images.githubusercontent.com/54713809/233068326-a4884759-85eb-49c7-b11e-bb8d32b0495e.png">

2023-04-19 13:07 UTC, syo-tokeshi commented
@monyatto 
お疲れ様です。
レビューをお願いしてもよろしいでしょうか？😄

2023-04-20 23:05 UTC, syo-tokeshi commented
@wata00913 
テスト

2023-04-21 00:25 UTC, syo-tokeshi commented
@ogawa-tomo 
お疲れ様です！
レビューして頂けますでしょうか？😄

2023-04-21 13:58 UTC, ogawa-tomo reviewed
@syo-tokeshi 
見ました！ほぼ問題ないように見えます:+1:
nitsなコメントをいくつかしたので、ご確認ください～

2023-04-21 13:58 UTC, ogawa-tomo commented on test/system/pages_test.rb
> +  test 'when Non-logged-in user access docs, meta description is displayed' do
[nits]
`Non-logged-in`を大文字にしている理由って何かありますか？

2023-04-21 13:58 UTC, ogawa-tomo commented on test/system/pages_test.rb
> +    visit "/pages/#{pages(:page1).id}"
[nits]
`page_path`ヘルパーメソッドを使ってもいいですね
（個人的にはそっちのほうがrailsっぽいなーと思うのですが、このファイルの他のテストもこの書き方になってますし、好みの問題ですかね）

2023-04-21 13:58 UTC, ogawa-tomo commented on test/system/pages_test.rb
> +      assert_selector "meta[name='description'][content='オンラインプログラミングスクール「フィヨルドブートキャンプ」のドキュメント「#{pages(:page1).title}」のページです。']", visible: false
[nits]
`pages(:page1)`を2回呼んでいるので、手前で`page = pages(:page1)`と変数に格納してもいいと思いました。

2023-04-21 13:58 UTC, ogawa-tomo commented on test/system/pages_test.rb
このテストをこのファイルに書くべきか、個人的にはちょっと悩ましいです。このファイルにはログイン状態でのpage操作に関するテストが並んでいて、このテストは微妙に性質が違う気がしなくもないんですよね。

私がQ&Aページで同じ対応をしたときは、わざわざ`test/system/question`ディレクトリ配下に新しいファイルを作ったんですよね。
https://github.com/fjordllc/bootcamp/pull/6448/files#diff-ea269374831e0e91bb479d112dad7fd23595fe05f50dac5b5d0901f9450c3b63

一応、`test/system/page`ディレクトリは存在していて、pageに関するテストを分割して整理して書くためにあるんだと思います。なので、ここにファイルを作るのも1つの選択肢ではあると思います。

とはいえこれだけのためにファイルを作るのも大げさな気もしますし、大して複雑になっているわけでもないので、このままでもいいとは思います！とりあえずご参考まで。
（私のPRを見たと思うので、もし何か考えたことがあれば教えてください～）

2023-04-22 06:32 UTC, syo-tokeshi commented
> @syo-tokeshi 見ました！ほぼ問題ないように見えます👍 nitsなコメントをいくつかしたので、ご確認ください～

レビューありがとうございます🙇‍♂️
月曜日頃に、レビューを反映し、再度提出致します🙇‍♂️

親切で助かります😊

2023-04-23 11:44 UTC, syo-tokeshi commented on test/system/pages_test.rb
> +  test 'when Non-logged-in user access docs, meta description is displayed' do
正直、翻訳のコピペでした🙇‍♂️
固有名詞でないので、付けるべきでなかったですね🙇‍♂️
指摘ありがとうございます！

2023-04-23 11:55 UTC, syo-tokeshi commented on test/system/pages_test.rb
> +    visit "/pages/#{pages(:page1).id}"
対応しました🙇‍♂️
トモさんのいう通り、その方がrailsらしいと思いました😊
勉強になりました🙇‍♂️

2023-04-23 11:57 UTC, syo-tokeshi commented on test/system/pages_test.rb
> +      assert_selector "meta[name='description'][content='オンラインプログラミングスクール「フィヨルドブートキャンプ」のドキュメント「#{pages(:page1).title}」のページです。']", visible: false
トモさんのご指摘で、
`target_page = pages(:page1)`という変数を作ることで解決しました🙇‍♂️
トモさんのいう通りだと思いました🙇‍♂️

2023-04-23 12:03 UTC, syo-tokeshi commented on test/system/pages_test.rb
トモさんのおっしゃる通り、
`test/system/page`ディレクトリの他のテストは、
`visit_with_auth`メソッドを使い、
ログインしている事前提のテストですね🙇‍♂️

トモさんのいう通り、テストの前提条件が違うので、
ディレクトリを分けようと思いました🙇‍♂️

鋭い指摘ありがとうございます🙇‍♂️

2023-04-23 12:28 UTC, syo-tokeshi commented
@ogawa-tomo
お疲れ様です！
修正致しましたので、また見て頂けますでしょうか？😄

お忙しい中ありがとうございます！🙇‍♂️

2023-04-24 13:02 UTC, ogawa-tomo approved these changes
対応いただきありがとうございます！
私としては良いと思いました👍

2023-04-25 00:31 UTC, syo-tokeshi commented
@ogawa-tomo 
お疲れ様です。
ありがとうございました！！🙇‍♂️

@komagata 
お疲れ様です。
受講生からのok頂けましたので、レビューして頂けますでしょうか？🙇‍♂️

2023-04-30 06:51 UTC, komagata requested changes

2023-04-30 06:51 UTC, komagata commented on test/system/page/not_logged_in_test.rb
> +class Page::NotLoggedInTest < ApplicationSystemTestCase
他にも同じようなIssueがあったと思いますので他のテストコードも参考にして似た感じで書く方が良いかと思います。

NotLoggedInTestと言うスコープを使うのであればそれらも同じスコープにおくかなど話し合うか、修正するかなりしないとバラバラの場所に似たテストが散らばることになってしまいそうです。

2023-04-30 07:45 UTC, ogawa-tomo commented on test/system/page/not_logged_in_test.rb
> +class Page::NotLoggedInTest < ApplicationSystemTestCase
横から失礼します:bow:
この部分、tokeさんが私のレビューに対応してくださったものです。
- https://github.com/fjordllc/bootcamp/pull/6458#discussion_r1173793562

現状、未ログイン状態でのDocsアクセスに関するテストは存在せず、私としては新たにファイルを作るほうが分かりやすいと考えた次第なのですがどうでしょう🤔
この部分は私のPRもほぼ同じ実装になっていますので、もし本PRで方針を変更するのであれば私の実装もそれに揃えたいです:bow:
- https://github.com/fjordllc/bootcamp/pull/6448

現状、ほかに類似のPRは下記のものしか見つからず（PR一覧で'meta description'と検索しました）、方針はあまり定まっていないように感じられました。
- https://github.com/fjordllc/bootcamp/pull/6406

2023-04-30 09:49 UTC, syo-tokeshi commented on test/system/page/not_logged_in_test.rb
> +class Page::NotLoggedInTest < ApplicationSystemTestCase
@ogawa-tomo 
コメントありがとうございます🙇‍♂️
tomoさんのご質問もに対する、駒形さんの回答を待った方が良さそうですね🙇‍♂️

@komagata 
上記の質問に対する、駒形さんのご回答の結果、コードの変更方針を決めようと思います🙇‍♂️
よろしくお願い致します🙇‍♂️

2023-05-16 08:12 UTC, komagata commented on test/system/page/not_logged_in_test.rb
> +class Page::NotLoggedInTest < ApplicationSystemTestCase
@ogawa-tomo (CC: @syo-tokeshi )

なるほどです。どれかのやり方に統一するならどれでも大きな違いはなさそうです。

> #6406

このような前例があるのであれば、それに従うか、新しい方針を決めたならばそれらを統一するために担当者と話し合ったり、修正するIssueを作るなどといった対応が必要です。

わかりやすさについては、単体見た時のわかりやすさとは別に、全体が統一されているのか違うのかと言った視点があります。

特にプログラムの書き方については人の感じ方によって「どちらが良いとも言えない」という場合も多いです。
ですので、特に既存のプロジェクトにコードを追加するときは極めて大きなメリットがない限り既存のものに合わせるのが正解なことが多いことを留意いただくと良いかと思います。

今回の件についてはこのPRの書き方で良いと思いますので、既存の部分の担当の方と話し合って、統一した書き方に変えるIssueを作ってみていただければと思います。

2023-05-16 11:55 UTC, ogawa-tomo commented on test/system/page/not_logged_in_test.rb
> +class Page::NotLoggedInTest < ApplicationSystemTestCase
承知しました！
正直に言いますと、既存のhttps://github.com/fjordllc/bootcamp/pull/6406 の方針はあまりよろしくないのではと思い、別の方針をとった次第でした。
Issueを立てつつ、既存のPR作成者と相談してみます。

2023-05-18 03:26 UTC, syo-tokeshi commented on test/system/page/not_logged_in_test.rb
> +class Page::NotLoggedInTest < ApplicationSystemTestCase
@komagata 
お疲れ様です。
担当者同士の話し合いが、このように解決しましたので、
マージして頂けますでしょうか？
https://github.com/fjordllc/bootcamp/issues/6524#issuecomment-1551348890

2023-05-27 21:20 UTC, komagata commented on test/system/page/not_logged_in_test.rb
> +class Page::NotLoggedInTest < ApplicationSystemTestCase
@syo-tokeshi 引き続きレビューいたします〜。

2023-05-27 21:23 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-05-27 21:23 UTC, merged

2023-05-28 08:32 UTC, syo-tokeshi commented
> 確認させて頂きました。OKです〜🙆‍♂️

お付き合い頂き、ありがとうございました🙇‍♂️