カテゴリー作成時にバリデーションのエラーメッセージを表示する
fjordllc/bootcamp pull request #6470
Opened 2023-04-23 11:17 UTC by ogawa-tomo

## Issue

- #6402

## 概要
カテゴリー作成時に必須項目に未入力がある場合、バリデーションメッセージを表示するようにしました。

## 変更確認方法

1. `bug/display-validation-errors-on-category-new`をローカルに取り込む
2. machida（管理者）としてログイン
3. `admin/categories/new`にアクセスする
4. 「名前」または「URLスラッグ」を未入力にする
5. 「登録する」ボタンをクリックする
6. 「名前を入力してください」「URLスラッグを入力してください」というエラーメッセージが表示される

## Screenshot
![image](https://user-images.githubusercontent.com/46841037/233836618-ae70babc-7ce7-427a-af55-8edb1b3eaaf5.png)

## 具体的にやったこと
- 該当のviewで`app/views/application/_errors.slim`パーシャルをcategoryモデルを渡して呼び出す
- システムテストの追加（このレベルのテストをいちいちやるかな？と思いつつ…）
- モデルテストの追加（無かったので、ついでに）

2023-04-23 11:37 UTC, ogawa-tomo commented
@YukiWatanabe824 
よろしければこちら、レビューお願いできますでしょうか？

2023-04-23 20:59 UTC, YukiWatanabe824 commented
@ogawa-tomo 
了解しました！
1-2日中にお返しするようにいたします🙆🏻‍♂️

2023-04-25 11:23 UTC, ogawa-tomo commented
@komagata こちら、メンバーのレビューが通りましたので、レビューをお願いいたします🙇

2023-04-30 07:01 UTC, komagata commented on test/models/category_test.rb
> +  end
こちらはActiveRecordのvalidationの機能をテストしていることになるので不要かと思います。

今回のバグについては再発しないようにsystem testでテストされていれば大丈夫です〜。

2023-04-30 07:50 UTC, ogawa-tomo commented on test/models/category_test.rb
> +  end
なるほどです、バリデーションを何か自前で実装したときにはテストすべきということですね。
修正しました！
[7bddc41](https://github.com/fjordllc/bootcamp/pull/6470/commits/7bddc41bb3dee47f71fd8970def74f693b36727f)

2023-05-16 08:35 UTC, komagata requested changes
Revertは特殊な時にしか使わないので、Revertコミットができない状態にしてみてください。
resetなどを使うといいと思います。

2023-05-16 11:50 UTC, ogawa-tomo commented
git resetしてRevertの履歴を消しました:bow:

2023-05-27 21:14 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-05-27 21:14 UTC, merged

2023-06-01 12:23 UTC, ogawa-tomo commented
@komagata @machida こちらリリースされましたが、動作確認に管理者権限が必要なので、本番での動作確認をお願いいたします:bow: