通知のユーザーアイコンにroleを付けた
fjordllc/bootcamp pull request #6538
Opened 2023-05-19 13:47 UTC by syo-tokeshi

## Issue

- #6523

## 概要

通知のユーザーアイコンに、今まで`role`は付いていなかったが、
`img`タグを`span`タグで囲んで、クラス名で`role`を付与した。

## 変更確認方法

1. ブランチ`feature/add_role_user_icon_notification`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. ユーザー名 : komagata、パスワード : testtestでログインする
4. http://localhost:3000/ にアクセスする
5. 「通知」ボタンをクリックする
<img width="1440" alt="最初" src="https://github.com/fjordllc/bootcamp/assets/54713809/bcd9fc4b-3e4c-44a1-8bc3-ad04343c9a54">
6. 通知一覧の、一番先頭にある町田さんの所で右クリックして、「検証」を押す
<img width="599" alt="検証" src="https://github.com/fjordllc/bootcamp/assets/54713809/eda09ba5-24a4-439f-ab1c-56fa0428288a">

7. こちらの写真のように、ユーザーの役割に応じて、「a-user-role is-OOOO(ここには役割が入る)」と表示されるのを確認する
[例：ユーザーが管理者なので、「admin」が付く]
<img width="1207" alt="span" src="https://github.com/fjordllc/bootcamp/assets/54713809/db14ff7c-85b9-4c10-a534-9cba7a268fbc">

## Screenshot

### 変更前
[ユーザーの役割に応じたクラスが付与されていない]
<img width="1481" alt="変更前" src="https://github.com/fjordllc/bootcamp/assets/54713809/ca4b9c16-1f6a-4959-a364-1fc45ecf648e">

### 変更後
[spanタグで付与されてる]
<img width="1207" alt="span" src="https://github.com/fjordllc/bootcamp/assets/54713809/db14ff7c-85b9-4c10-a534-9cba7a268fbc">

2023-05-24 02:26 UTC, syo-tokeshi commented
> @syo-tokeshi デザイン崩れを修正しました

@machida 
お疲れ様です🙇‍♂️
動作確認しました。

cssのスタイルは、これから作って下さる形でしょうか？
このファイルに追加していく感じですかね？😀
https://github.com/fjordllc/bootcamp/blob/bb07df7838cfcb5ed7ecaf1f8c65d0278d0540db/app/javascript/stylesheets/atoms/_a-user-role.sass

2023-05-24 05:28 UTC, machida commented
@syo-tokeshi 対応は既に済です。この機会に sass のファイルを読んでみましょう💪

2023-05-24 05:43 UTC, syo-tokeshi commented
@machida 

スタイルすでに当たってましたね🙇‍♂️
こちらの写真のように`border`が付与されていて、
役割毎にスタイルが微妙に違うこと、確認できました🙇‍♂️

- [卒業生はsuccess(緑色)]
```css
&.is-graduate
    .a-user-icon
      border: solid 2px rgba($success, .7)
```
- 一般ユーザーは追加のスタイル無し
- 退会者は`background-color: black`が付与されている
![スクリーンショット 2023-05-24 14 37 47](https://github.com/fjordllc/bootcamp/assets/54713809/fb8e4acb-8aae-4663-ae11-b1dd7052ef98)

[sassファイル]
https://github.com/fjordllc/bootcamp/blob/bb07df7838cfcb5ed7ecaf1f8c65d0278d0540db/app/javascript/stylesheets/config/mixins/_user-role.sass#L4

なので
-  sass はファイルすでに読み込まれていて使われている

という理解でよろしいでしょうか？

2023-05-24 10:25 UTC, syo-tokeshi commented
@YukiWatanabe824 
お疲れ様です。
こちらのレビューをお願いしてもよろしいでしょうか？
急ぎじゃなくて大丈夫です🙇‍♂️

2023-05-25 10:40 UTC, YukiWatanabe824 commented
了解しましたー🫡
ちょっと日数いただきそうですがやらせていただきます😃

2023-05-28 07:29 UTC, YukiWatanabe824 approved these changes
確認いたしました！
LGTMです〜😄

2023-05-30 01:12 UTC, syo-tokeshi commented
@komagata 
お疲れ様です。
受講生にapprove頂けたので、レビューお願い致します😊

2023-06-01 17:30 UTC, komagata requested changes

2023-06-01 17:30 UTC, komagata commented on test/system/notifications_test.rb
> +    visit '/'
ログインしつつURLにアクセスする方法があるので他のテストを参考にしてみてください〜

2023-06-02 03:28 UTC, syo-tokeshi commented on test/system/notifications_test.rb
> +    visit '/'
`visit_with_auth`メソッドを使うようにしました🙇‍♂️

2023-06-09 03:44 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-06-09 03:44 UTC, merged