ユーザー一覧に日報・提出物・コメント・質問・回数の数を表示する
fjordllc/bootcamp pull request #6572
Opened 2023-05-28 08:32 UTC by ksmxxxxxx

## Issue

- #6219 

## 概要

- ユーザー一覧に日報・提出物・コメント・質問・回数の数を表示します

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-05-28 08:36 UTC, ksmxxxxxx commented
@machida お疲れ様です。
日報・提出物・コメント・質問・回答の数を表示するようにしたので、デザインを実装してもらえますか。
よろしくお願いします。

2023-05-31 05:24 UTC, machida commented
@ksmxxxxxx デザイン了解ですー

2023-05-31 08:13 UTC, machida commented
@ksmxxxxxx 

<img width="480" alt="image" src="https://github.com/fjordllc/bootcamp/assets/168265/82b10e96-72ad-4067-8688-e44a32a62c24">

デザイン入れましたー

2023-06-03 08:51 UTC, ksmxxxxxx commented
@machida ありがとうございます！確認しました〜。
テスト追加しようと思って考えてたら、気がついた事があったので #6219 で質問させてもらってます。
お手数ですが、ご確認いただけますと 🙏

2023-06-10 14:28 UTC, ksmxxxxxx commented
@wata00913 おつかれさまです。
こちらのレビューをお願いしてもいいでしょうか？
ご検討いただけると嬉しいです〜 🙏

2023-06-11 04:45 UTC, wata00913 commented
@ksmxxxxxx 
お疲れ様です、レビュー依頼ありがとうございます！
木曜日頃にレビューの返信できますが、大丈夫でしょうか？

2023-06-11 05:51 UTC, ksmxxxxxx commented
@wata00913 大丈夫です〜

2023-06-15 12:34 UTC, wata00913 commented on app/javascript/components/user.vue
> +import UserActiveRecordNumber from './user-active-record-number.vue'
コンポーネント名に含まれる`ActiveRecordNumber`は変更した方が良いと思いました。
`ActiveRecord`はRailsの文脈でも用いられているため、混乱を招きそうです。
`UserActivityCounts`、`UserActivityNumber`や`UserActivityStatistics`等はいかがでしょうか？

2023-06-15 12:35 UTC, wata00913 commented on app/views/api/users/_list_user.json.jbuilder
>  json.tag_list user.tags.pluck(:name)
保持するデータは`数`のみのため、キー名を`項目の複数形`とするのは抽象化し過ぎだと思いました。
素直に`項目_count`と命名するのはいかがでしょうか？

2023-06-15 12:39 UTC, wata00913 commented on test/system/users_test.rb
> +  end
アドバイザーの確認がないのですが、確認は不要なのでしょうか？

2023-06-15 12:52 UTC, wata00913 commented on app/views/api/users/_list_user.json.jbuilder
> +json.answers user.answers.length
また、16~20行目はシンプル

2023-06-15 13:06 UTC, wata00913 reviewed
@ksmxxxxxx 
お待たせいたしました〜
動作確認はOKでした！
コメントをしましたので、確認をよろしくお願いします🙇‍♂️

2023-06-17 10:28 UTC, ksmxxxxxx commented on test/system/users_test.rb
> +    assert_selector '.card-counts__items'
こちらで修正しました 7debb20c078ea584d4ca4d3f42cbc2ca98ded838

2023-06-17 10:29 UTC, ksmxxxxxx commented on test/system/users_test.rb
> +  end
こちらで修正しました 7debb20c078ea584d4ca4d3f42cbc2ca98ded838

2023-06-17 10:29 UTC, ksmxxxxxx commented on app/javascript/components/user.vue
> +import UserActiveRecordNumber from './user-active-record-number.vue'
こちらで修正しました 895f2926779b00d5dd788ad687a6f21f76e846cb

2023-06-17 10:32 UTC, ksmxxxxxx commented on app/views/api/users/_list_user.json.jbuilder
> +json.answers user.answers.length
こちらで修正しました
f05a44fda128d54a957571990042fbc8ad7204da

2023-06-17 10:32 UTC, ksmxxxxxx commented on app/views/api/users/_list_user.json.jbuilder
>  json.tag_list user.tags.pluck(:name)
こちらで修正しました 215d40ef5fd9688d4ba8c5f7d487401b9d8e0d06

2023-06-17 10:33 UTC, ksmxxxxxx commented
@wata00913 レビューありがとうございました！
修正させてもらったので、再レビューお願いします〜 🙏

2023-06-20 06:49 UTC, wata00913 commented on app/javascript/components/user.vue
> +    'user-active-record-number': UserActivityCounts,
コンポーネント名も揃えた方が良さそうです。

2023-06-20 06:54 UTC, wata00913 commented
@ksmxxxxxx 
お疲れ様です！
対応ありがとうございます。１点コメントしましたので確認をお願いします🙇‍♂️
- https://github.com/fjordllc/bootcamp/pull/6572#discussion_r1234812484

2023-06-20 14:13 UTC, ksmxxxxxx commented on app/javascript/components/user.vue
> +    'user-active-record-number': UserActivityCounts,
@wata00913 わぁぁ、すみません 💦 
漏れていたところなので、コメント頂いてありがとうございます。修正しました〜

fb222dc5e289102eaedbde45bbc35d6aa3c78613

2023-06-21 00:42 UTC, wata00913 approved these changes
@ksmxxxxxx 

確認しました、OKです。
Approveさせて頂きます！👍

2023-06-21 14:32 UTC, komagata requested changes

2023-06-21 14:32 UTC, komagata commented on test/system/users_test.rb
> +    assert_selector '.card-counts__items'
「activity countsが表示されている」というには具体的には数字を確認できる必要があると思います。

2023-06-24 13:55 UTC, ksmxxxxxx commented on test/system/users_test.rb
> +    assert_selector '.card-counts__items'
こちらで修正してみました。
[e1c531a](https://github.com/fjordllc/bootcamp/pull/6572/commits/e1c531a744bd8891148e7d91bfaa60a19bb29cbd)

2023-06-28 19:55 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-06-28 19:55 UTC, merged