休会中のユーザー個別ページに休会期日と休会期日までの日数を表示
fjordllc/bootcamp pull request #6659
Opened 2023-06-20 07:45 UTC by sochi419

## Issue

- #6615

## 概要

休会中のユーザー個別ページに、休会からの経過日数を表示される様にした。

## 変更確認方法

1. `feature/display-username-in-latest-announcements`をローカルに取り込む
2. `bin/rails s`でローカル環境を立ち上げる
3. `localhost:3000`にアクセス
4. ユーザー名 : `komagata` でログイン
5. 休会しているユーザの個別ページにアクセスする。
`http://localhost:3000/users/422118307`

<img width="759" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/563a07fc-6df6-41e5-ad23-db2d84e8c564">

6. `rails c`を実行する。
7. 休会期限当日の場合のメッセージをこれから確認する。console上で下記を実行する。
> user = User.find_by(login_name: 'kyuukai')
> user.update!(hibernated_at: "#{Time.zone.now.advance(months: -6, hours: 23)}")

ユーザ個別ページをリロードして、`休会期限日: 20XX年XX月XX日（自動退会までXX時間）'のメッセージがあることを確認する。
<img width="593" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/ecbb7146-2698-4f4a-8f53-aba8133e1a80">
8. 休会期限1週間を切った場合のメッセージをこれから確認する。console上で下記を実行する。
> user = User.find_by(login_name: 'kyuukai')
> user.update!(hibernated_at: "#{Time.zone.now.advance(months: -6, weeks: 1)}")

ユーザ個別ページをリロードして、`休会期限日: 20XX年XX月XX日（自動退会まであとXX日）'というメッセージが赤く表示されていることを確認する。
<img width="600" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/6e1b0ce9-ac04-44bd-af49-04db8bd3a376">
9. 休会期限6ヶ月 ~ 1週間の場合のメッセージをこれから確認する。console上で下記を実行する。
> user = User.find_by(login_name: 'kyuukai')
> user.update!(hibernated_at: "#{Time.zone.now}")

ユーザ個別ページをリロードして、`休会期限日: 20XX年XX月XX日（自動退会まであとXX日）'という表示を確認する。
<img width="610" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/a949f6fe-499e-4724-801c-400bf7ec3463">

10. 自動退会しないユーザーの場合のメッセージの表示を確認する。
まず`kyuukai`のユーザページ `http://localhost:3000/users/422118307`にアクセスする。
ユーザページ右下にある「管理者として情報変更」を選択する。

<img width="769" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/d1485af6-0670-4968-8394-c2bcb076cb40">

11. 自動退会設定の「休会6ヶ月後に自動退会しない」にチェックをして、更新するボタンを選択する。これで、自動退会しないユーザーとして設定することができる。
<img width="518" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/dd5b6681-d424-4b3d-b0c4-ae3a09ae3189">

12. console上で下記を実行
````
> user = User.find_by(login_name: 'kyuukai')
> user.update!(hibernated_at: "#{Time.zone.now.advance(months: -3)}")
````

13. `kyuukai`のユーザページ `http://localhost:3000/users/422118307`にアクセスして、「企業都合休会中（○日）」という表示になっているか確認する。

<img width="726" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/4000494a-7f0d-49c1-b031-1070078efc39">

## Screenshot

### 変更前
<img width="623" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/ca9ff50f-bf66-4612-b54c-b35c966e7317">

### 変更後
- 休会期限日6ヶ月前 ~ 1週間前の場合
<img width="610" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/076d29a3-cd80-4f56-94f8-ce074bfbb8a7">

- 休会期限日1週間を切った場合
<img width="600" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/6e1b0ce9-ac04-44bd-af49-04db8bd3a376">

- 休会期限日当日の場合
<img width="593" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/ecbb7146-2698-4f4a-8f53-aba8133e1a80">

- 自動退会しないユーザの場合
<img width="596" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/5a824766-80f9-4686-a57d-a66c627846a4">

2023-06-23 09:08 UTC, sochi419 commented
@machida 
お疲れ様です。
こちらのデザインをよろしくお願いします🙏

急ぎではないです🙆‍♂️

2023-06-23 09:20 UTC, machida commented
@sochi419 
了解ですー🙆‍♂️

2023-06-28 06:26 UTC, machida commented
@sochi419 デザイン入れました。最新のmainを取り込んだので、

git pull --rebase origin feature/display-absence-elapsed-days-on-adjourned-users-page

をお願いします。

2023-06-28 06:26 UTC, machida commented
@sochi419 受講生のレビューに進めてください。

2023-06-29 01:02 UTC, sochi419 commented
@machida 
デザインありがとうございます〜🙏🙏
受講生のレビューに進みます🙆‍♂️

@ogawa-tomo 
お疲れさまです！
こちらのレビューをお願いしたいと思っているのですがご都合いかがでしょうか？（全く急ぎではないです）

ご確認よろしくお願いします🙇🏻

2023-06-29 09:35 UTC, ogawa-tomo commented
@sochi419 承知しました！来週中くらいを目標に見ようと思います。
あとコンフリクトしてるようなので解消しておいてください:pray:

2023-06-30 12:24 UTC, ogawa-tomo commented
動作確認についてです。

休会期限日時の表示箇所がdescriptionに貼っていただいたものと違うようです。町田さんのデザインが入って変わったとかですかね？確認後、スクショを貼り直しておいていただければ。
![image](https://github.com/fjordllc/bootcamp/assets/46841037/7c5b3c5e-267e-404d-9d62-42f345d684ef)

ユーザーの休会日時の更新操作を下記のように書いていただいていますが、
> user.update!(hibernated_at: "#{Time.zone.now.advance(months: -3)}")

わざわざ日時を文字列にしなくても、Railsはよしなに処理してくれます。
```
user.update!(hibernated_at: Time.zone.now.advance(months: -3))
```

ちなみにですが、こう書いても同じです。（個人的にはこっちのほうがシンプルで好みです）
```
user.update!(hibernated_at: 3.months.ago)
```

2023-06-30 13:06 UTC, ogawa-tomo commented on app/views/users/_hibernation_info.html.slim
> +            | #{@user.automatic_retire_date(@user)} (自動退会まであと#{@user.remaining_days_until_automatic_retire(@user).ceil}日)
この`.ceil`はmodel側に移したいという前提ですが、ここは`.ceil`じゃなくて`.floor`が正しいのではと思ったのですがどうでしょう…？
現状だと、
・休会期限日時まであと23時間のとき→「（本日休会最終日）」と表示
・休会期限日時まであと25時間のとき→「自動退会まであと2日」と表示
となりますね？
個人的には、休会期限日時まであと25時間のときは「自動退会まであと1日」と表示されてほしい気がします。
このあたりの仕様は必要であれば町田さんに確認していただくとよさそうです。

2023-06-30 13:11 UTC, ogawa-tomo commented
📝 `app/views/users/_hibernation_info.html.slim`はuserが休会中じゃないと呼ばれない
https://github.com/fjordllc/bootcamp/blob/d9018665d91ce16e4a693c9ac465809c1a24fbaf/app/views/users/show.html.slim#L29-L30

2023-06-30 13:16 UTC, ogawa-tomo commented on app/models/user.rb
> +    Time.zone.parse(hibernated_user.hibernated_at.to_s).advance(months: 3).strftime('%Y年%m月%d日 %H:%M')
このへんのメソッドは`hibernated_at`がnilだとエラーになっちゃうので、`return unless hibernated_at`みたいなガード節を足してやるとメソッドの仕様としてはちょっと親切かなと思いました。本来そのときは呼ばれないはずなのでなくても良いといえば良いのですが。

2023-06-30 13:20 UTC, ogawa-tomo commented
https://github.com/fjordllc/bootcamp/pull/6659#discussion_r1247839059 このへんの仕様が若干複雑でもありますし、なんらかのテストは足したい気がしますね。
このあたりを参考にして同じような感じでsystem testを足せればよいかなと思いますがどうでしょう。
https://github.com/fjordllc/bootcamp/blob/d9018665d91ce16e4a693c9ac465809c1a24fbaf/test/system/users_test.rb#L93-L121

2023-06-30 13:27 UTC, ogawa-tomo commented
休会期限日時を過ぎちゃった場合の表示ってどうしますかね？厳密には、退会するのは休会期限日時を過ぎてから最初に自動退会の定期処理が走るときなので、このケースは必ず起こります。また、自動退会の定期処理が何らかの理由で空振ったり不具合が起きたときもこうなります。管理者しか見ないページだから気にしなくてもいいですかね？

2023-06-30 13:33 UTC, ogawa-tomo commented
これは私のPR側の処理ですが、休会三ヶ月後に自動退会する処理で「三ヶ月」を判定するロジックをコントローラにべたっと書いてしまったので、ここで今回のPRで作ったメソッドを使ってロジックを共通化したいですね。
https://github.com/fjordllc/bootcamp/blob/571de43ae0d22bcb5ae5ad0ebb9c48be859b01d8/app/controllers/scheduler/daily/retirement_after_long_hibernation_controller.rb#L12
これは別PRでやればよいと思うので、Issueを立てておきます。

2023-06-30 13:45 UTC, ogawa-tomo commented
@sochi419 いったん一通り見ましたので、ご確認ください:pray:

2023-07-01 03:19 UTC, ogawa-tomo commented
もうひとつ、気づいたことを。
休会後三ヶ月で退会する処理を実装したPR https://github.com/fjordllc/bootcamp/pull/6490 では、休会後三ヶ月経っても退会しないユーザーを設定できるようにもなっています。これに該当するユーザーにはそもそも今回の休会期限日という概念が当てはまらないので、表示の仕方も変える必要がありそうに思います。このへんの仕様についても町田さんとイシューで相談して詰めていただけますでしょうか:pray:

休会後三ヶ月で退会のPRはもうすぐマージできそうな気がするので、この対応はこのPRでできそうに思います。

2023-07-03 07:46 UTC, sochi419 commented
@ogawa-tomo 

レビューありがとうございます！
いただいた指摘点を全て修正したら、またメンションさせていただきます〜

よろしくお願いします🙏

2023-07-22 00:37 UTC, sochi419 commented on app/models/user.rb
> +  end
すいません、初めは使っていたのですが、試行錯誤しているうちに使わなくなっていました。
こちらは削除しておきます✍️

2023-07-22 00:57 UTC, sochi419 commented on app/models/user.rb
> +  def automatic_retire_date(hibernated_user)
アドバイスありがとうございます！
````ruby
 def automatic_retire_date
    Time.zone.parse(hibernated_at.to_s).advance(months: 3).strftime('%Y年%m月%d日 %H:%M')
  end
````
としました〜

2023-07-22 01:03 UTC, sochi419 commented on app/models/user.rb
> +  def automatic_retire_date(hibernated_user)
時間も絡むので、名前にtimeを絡めた方が良いかもですね。
今回は`datetime`としました〜

2023-07-22 01:15 UTC, sochi419 commented on app/models/user.rb
> +    Time.zone.parse(hibernated_user.hibernated_at.to_s).advance(months: 3).strftime('%Y年%m月%d日 %H:%M')
下記の様にしたら、全く同じ動作を再現できました！
かなり見やすくなりました、ありがとうございます🙏

````ruby
def automatic_retire_datetime
  hibernated_at.advance(months: 3).strftime('%Y年%m月%d日 %H:%M')
end
````

rubyで時間を扱うメソッドを調べていくうちに、Time.zone.parseメソッドを使う思考になっていて、無理やりその型に落とし込もうとして、string型やらTimeWithZone型やらに無駄に変換してしまっていました😅
確かにtomoさんの提案いただいた案の方が、見やすさが段違いだと思いました👀

2023-07-22 01:31 UTC, sochi419 commented on app/models/user.rb
> +    Time.zone.parse(hibernated_user.hibernated_at.to_s).advance(months: 3).strftime('%Y年%m月%d日 %H:%M')
確かにi18nのヘルパーメソッドを使った方が、他の記述部分に合わせられるし、記述量を減らせますね👀
lメソッドを使った記述に修正をしました〜

2023-07-26 08:16 UTC, sochi419 commented
@machida 

本日の質問タイムで質問させていただいた件です。
休会後三ヶ月経っても退会しないユーザーを設定できるようになっています。これに該当するユーザの場合、休会中のユーザーページの「残り○日」という表示はどうするか、についてです。この相談について、後でコメントを下さるとのことだったので、メンションさせていただきました🙏

回答よろしくお願いします🙏

2023-07-31 07:54 UTC, machida commented
@sochi419 返信遅れてすいません🙇‍♂️

```
企業都合休会中（XX日）
```

という表示にしておいてくださいー

- あと何日で表示を変えるなどは無し
- カッコの中は経過日数を表示

をお願いします🙏

2023-08-03 03:16 UTC, sochi419 commented on app/views/users/_hibernation_info.html.slim
> +            | #{@user.automatic_retire_date(@user)} (自動退会まであと#{@user.remaining_days_until_automatic_retire(@user).ceil}日)
> 個人的には、休会期限日時まであと25時間のときは「自動退会まであと1日」と表示されてほしい気がします。
このあたりの仕様は必要であれば町田さんに確認していただくとよさそうです。

町田さんと相談をした結果、以下の仕様で実装することになりました。
- 本日休会最終日の場合は、「本日休会最終日」という表示ではなく「残り○時間」という表示に変える。(残り何時間残っているか分からないため)
- 残り25時間の場合は「自動退会まであと1日」という仕様にする。

2023-08-03 03:19 UTC, sochi419 commented on app/views/users/_hibernation_info.html.slim
> +            | #{@user.automatic_retire_date(@user)} (自動退会まであと#{@user.remaining_days_until_automatic_retire(@user).ceil}日)
> この.ceilはmodel側に移したいという前提ですが、ここは.ceilじゃなくて.floorが正しいのではと思ったのですがどうでしょう…？

・休会期限日時まであと23時間のとき→「自動退会まであとXX時間」と表示
・休会期限日時まであと25時間のとき→「自動退会まであと1日」と表示

上記の仕様で実装するので、`.floor`を使った処理に修正をしました。

2023-08-03 03:47 UTC, sochi419 commented on app/models/user.rb
> +    ((Time.zone.parse(hibernated_user.hibernated_at.to_s).advance(months: 3) - Time.zone.now) / 86_400)
> 現状、日数をfloart型で返している（休会期限まであと2.3日、みたいに）と思いますが、使われ方を見ると整数型で返したい気がします。view側で.ceilとかやるのは複雑なビジネスロジックをview側に持ち込んでいる気がして個人的にはちょっと嫌な感じがします。

railsの経験があんまりなくて、view側の処理にするのか、controller側の処理にするかの判断ができていなかったです👀
複雑なロジックはviewに持ち込まないように心がけたいと思います✍️
今回はmodel側で`.floor`の処理が実行されるようにしました。

2023-08-11 08:58 UTC, sochi419 commented
@machida 

> 企業都合休会中（XX日）
という表示にしておいてくださいー

上記の機能実装について確認したいことがあります。
「○ヶ月後に自動退会する処理」と、「○ヶ月後に自動退会しないユーザーを設定できる処理」は、現在tomoさんがこちらのPR(まだmergeされていない)で実装されています。(https://github.com/fjordllc/bootcamp/pull/6490)

休会中のユーザページには、以下の様に自動退会するかを設定することができます。（管理者のみ）
![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8316856aeadc77d649b2ddc017fa2ef729356739/image.png)

自動退会しないにチェックをすると、DBのusersテーブル内の、以下の`not_auto_retire_after_long_hibernation`がtrueになります。
- db/schema.rb
````
t.boolean "not_auto_retire_after_long_hibernation", default: false
````

相談したいことは、
`not_auto_retire_after_long_hibernation` が、trueの場合(自動退会しないユーザの場合)に`企業都合休会中（XX日）`という表示をしようと考えています。
そのためには、tomoさんのPRでコミットされているusersテーブルの`t.boolean "not_auto_retire_after_long_hibernation", default: false`の情報が必要なのですが、まだ上記のPRはmergeされていません。
どうしたら良いでしょうか？

以下の2つのどちらかが良いのかな？と考えています。
- `t.boolean "not_auto_retire_after_long_hibernation", default: false`を、DBのusersテーブルに記載する。
- tomoさんのPR(https://github.com/fjordllc/bootcamp/pull/6490) がmergeされてから、自動退会しないユーザの場合の表示を実施する。

2023-08-12 11:34 UTC, sochi419 commented on app/models/user.rb
> +    Time.zone.parse(hibernated_user.hibernated_at.to_s).advance(months: 3).strftime('%Y年%m月%d日 %H:%M')
なるほど、nilの場合のことを考えられていませんでした。
各メソッドに、`return unless hibernated_at`を追加しました✍️

2023-08-13 23:05 UTC, ogawa-tomo commented on app/models/user.rb
> +  end
ついでに、現状のslimファイルに書いてあるif文（日・時・分の出し分け）もヘルパーメソッドに含めてしまうと、slimファイルがすっきりしそうに思いました。

2023-08-14 07:33 UTC, sochi419 commented
> @machida
> 
> > 企業都合休会中（XX日）
> > という表示にしておいてくださいー
> 
> 上記の機能実装について確認したいことがあります。 「○ヶ月後に自動退会する処理」と、「○ヶ月後に自動退会しないユーザーを設定できる処理」は、現在tomoさんがこちらのPR(まだmergeされていない)で実装されています。(#6490)
> 
> 休会中のユーザページには、以下の様に自動退会するかを設定することができます。（管理者のみ） ![image.png](https://camo.githubusercontent.com/87be4faeff3baaee9a9beae958d3ede1632be3fda8443274d0389547f05f5906/68747470733a2f2f626f6f7463616d702e666a6f72642e6a702f7261696c732f6163746976655f73746f726167652f626c6f62732f72656469726563742f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424e6c56755158633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d383331363835366165616463373764363439623264646330313766613265663732393335363733392f696d6167652e706e67)
> 
> 自動退会しないにチェックをすると、DBのusersテーブル内の、以下の`not_auto_retire_after_long_hibernation`がtrueになります。
> 
> * db/schema.rb
> 
> ```
> t.boolean "not_auto_retire_after_long_hibernation", default: false
> ```
> 
> 相談したいことは、 `not_auto_retire_after_long_hibernation` が、trueの場合(自動退会しないユーザの場合)に`企業都合休会中（XX日）`という表示をしようと考えています。 そのためには、tomoさんのPRでコミットされているusersテーブルの`t.boolean "not_auto_retire_after_long_hibernation", default: false`の情報が必要なのですが、まだ上記のPRはmergeされていません。 どうしたら良いでしょうか？
> 
> 以下の2つのどちらかが良いのかな？と考えています。
> 
> * `t.boolean "not_auto_retire_after_long_hibernation", default: false`を、DBのusersテーブルに記載する。
> * tomoさんのPR([休会から六ヶ月後に自動で退会されるようにする #6490](https://github.com/fjordllc/bootcamp/pull/6490)) がmergeされてから、自動退会しないユーザの場合の表示を実施する。

# 上記の質問についての回答(2023/8/14(月))
質問タイムで相談した結果、https://github.com/fjordllc/bootcamp/pull/6490 のPRがmergeされてから、このPRの作業を行うことになりました。(6ヶ月経っても休会しないユーザーの処理がmergeされないと、休会しないユーザーの場合に「企業都合休会中（XX日）」という条件分岐が書けないため)

2023-08-22 22:49 UTC, komagata commented
@sochi419 

> 上記の質問についての回答(2023/8/14(月))

こちらの追記ありがとうございます〜！

2023-09-11 15:38 UTC, sochi419 commented on app/models/user.rb
> +    ((hibernated_at.advance(months: 6) - Time.zone.now) / 86_400).floor
仰る通りだと思いました。
`automatic_retire_datetime`を使ってDRYにしました。

2023-09-11 16:02 UTC, sochi419 commented on app/models/user.rb
> +  end
どんな時にhelperメソッドで定義するのか、が自分の中で定まっておらず、特に考えないままuser.rbに定義してしまっていました。勉強のためにお聞きしたいのですが、どんな時にhelperメソッドに定義して、どんな時にモデルに定義するかを使い分けているのでしょうか？

今回のメソッド定義群は、全てヘルパーメソッドで定義する処理にしてみました✍️

2023-09-11 16:05 UTC, sochi419 commented on app/models/user.rb
> +  end
> ついでに、現状のslimファイルに書いてあるif文（日・時・分の出し分け）もヘルパーメソッドに含めてしまうと、slimファイルがすっきりしそうに思いました。

すみません、イメージが湧かないのですが、どのようにヘルパーメソッドに含めるのでしょうか？ 1つ例を挙げてもらうことは可能でしょうか？

2023-09-11 16:06 UTC, sochi419 commented
> 休会期限日時を過ぎちゃった場合の表示ってどうしますかね？厳密には、退会するのは休会期限日時を過ぎてから最初に自動退会の定期処理が走るときなので、このケースは必ず起こります。また、自動退会の定期処理が何らかの理由で空振ったり不具合が起きたときもこうなります。管理者しか見ないページだから気にしなくてもいいですかね？

質問タイムで相談した結果、休会期限日時を過ぎた場合の表示は気にしなくて良いという話し合いにまとまりました。

2023-09-11 16:08 UTC, sochi419 commented on app/models/user.rb
> +  end
※ 追記

やはり使うことになったので、再度定義しました。

2023-09-11 17:09 UTC, sochi419 commented
@ogawa-tomo 

長期間空けてしまいすみませんでした。
レビューで指摘いただいた点を一通り修正しました。

確認よろしくお願いします🙏

2023-09-12 12:39 UTC, ogawa-tomo commented on app/models/user.rb
> +  end
> どんな時にhelperメソッドに定義して、どんな時にモデルに定義するかを使い分けているのでしょうか？

モデルに定義するのはビジネスロジック、helperに定義するのはプレゼンテーションロジック、という考え方だと思っています。
今回の例でいえば、退会日を決めるのはビジネスロジックです。これはアプリケーションのコアな挙動に関するロジックだからです。
一方、退会日までの期間の表示の仕方を決めるのはプレゼンテーションロジックです。たとえば、「残り36時間」と表示しても「残り1日と12時間」と表示しても「残り1日」と切り捨てて表示しても、見た目の違いはありますがアプリケーションの挙動に影響することはありません。

なので、今回の例でいえば、`automatic_retire_datetime`はビジネスロジックなので、少なくともこれはモデルに定義すべきだと思います（せっかく直してもらったのにすみません）:bow:

---

> どのようにヘルパーメソッドに含めるのでしょうか？ 例を挙げてもらうことは可能でしょうか？

「自動退会まで○日／○時間／○分」と出し分けているところをまるっとメソッドにできるともうちょっとすっきりするかも、と思いました。
たとえばですが、`remaining_time_until_automatic_retire`みたいなヘルパーメソッドを作ってやって、
```ruby
def remaining_time_until_automatic_retire(user)
  if user.remaining_days_until_automatic_retire < 1
    if user.remaining_hours_until_automatic_retire(user) >= 1
      '#{user.remaining_hours_until_automatic_retire(user)}時間'
    else
      '#{user.remaining_minutes_until_automatic_retire(user)}分'
    end
  else
    '#{user.remaining_days_until_automatic_retire(user)}日'
  end
end
```
という感じにしてやると、ちょっとslimファイルをすっきりさせられないですかね…？ただ`is_danger`クラスの出し分けとかもやらねばなのでif文を撲滅することはできないかもですが…。
このへんをどうやってきれいにまとめるかはわりと好みの問題かもなので（極端にいえばもうひとつパーシャルを切るとかもありえなくはないし、下手にロジックを分けないほうがよいという考えもありうる）、このままでもよいし、おまかせしようと思います。

2023-09-20 01:14 UTC, sochi419 commented on app/models/user.rb
> +  end
> モデルに定義するのはビジネスロジック、helperに定義するのはプレゼンテーションロジック、という考え方だと思っています。
今回の例でいえば、退会日を決めるのはビジネスロジックです。これはアプリケーションのコアな挙動に関するロジックだからです。
一方、退会日までの期間の表示の仕方を決めるのはプレゼンテーションロジックです。たとえば、「残り36時間」と表示しても「残り1日と12時間」と表示しても「残り1日」と切り捨てて表示しても、見た目の違いはありますがアプリケーションの挙動に影響することはありません。
なので、今回の例でいえば、automatic_retire_datetimeはビジネスロジックなので、少なくともこれはモデルに定義すべきだと思います（せっかく直してもらったのにすみません）🙇

なるほど、勉強になりました！
ビジネスロジックである、`automatic_retire_datetime`はモデルに定義して、その他のプレゼンテーションロジックはhelperに定義しました！

2023-09-20 01:18 UTC, sochi419 commented on app/models/user.rb
> +  end
> 「自動退会まで○日／○時間／○分」と出し分けているところをまるっとメソッドにできるともうちょっとすっきりするかも、と思いました。

例を挙げていただき、ありがとうございます🙏
確かに分岐を減らせそうなので、書き換えてみたところ、slimファイルがDRYになった気がします！

````ruby
 　　- if user.auto_retire == false # 自動退会しないユーザの場合
          span.user-metas__item-value-text
            | 企業都合休会中(#{user.calculate_absence_days(user)}日)
        - elsif user.remaining_days_until_automatic_retire(user) <= 7
          span.user-metas__item-value-text.is-danger
            | #{l user.automatic_retire_datetime} (自動退会まであと#{user.remaining_time_until_automatic_retire(user)})
        - else
          span.user-metas__item-value-text
            | #{l user.automatic_retire_datetime} (自動退会まであと#{user.remaining_days_until_automatic_retire(user)}日)
````

2023-09-20 01:27 UTC, sochi419 commented
@ogawa-tomo 

質問に回答いただきありがとうございました！
指摘いただいた点を修正をしたので、確認よろしくお願いします🙏

P.S.
今回のPRの修正が長引いていて申し訳ありません。
tomoさんはチーム開発を終えているのに、レビューに付き合わせてしまい、申し訳ない気持ちです。
作業スピードを上げて、なる早で対応していきたいと思います💪

2023-10-04 07:52 UTC, sochi419 commented
@ogawa-tomo 

お忙しいところ申し訳ありません。
リマインドのメッセージになります。🙇‍♂️

こちらのレビューの件、どうでしょうか？

自作サービスの方で忙しい様なので、こちらのレビューの件、komagataさんに相談してkomagataさんに直接レビューいただこうか相談しようと考えています。（チーム開発を終えている方に、何度もレビュー依頼をするのは申し訳ないので）

無理させてはいけないと思い、お聞きしました🙇‍♂️

2023-10-04 09:28 UTC, ogawa-tomo commented
@sochi419 
すみません、完全に見逃しておりました💦💦💦
数日中に見ますので少々お待ちいただけますでしょうか🙏🙏🙏
ちなみに私はまだチーム開発を終えてないので（イシューが全部クローズできてないので）ぜんぜんレビュー依頼してよい状態です〜（というルールだったかと思っています）

2023-10-04 12:28 UTC, ogawa-tomo commented on app/helpers/users_helper.rb
> +  if user.remaining_days_until_automatic_retire(user) < 1
ここは上で定義したメソッドを使っているので、単に`remaining_days_until_automatic_retire(user)`で良さそうです。
（どうしてこれで動いているのか正直よく分からないのですが…この定義の仕方でuserオブジェクトにメソッドが生えるのか…？:thinking:）
（私の書いたサンプルコードがそう書いてたみたいですが:bow:）

2023-10-06 02:28 UTC, sochi419 commented on app/views/users/_hibernation_info.html.slim
> +        - if user.auto_retire == false # 自動退会しないユーザの場合
そうでした..
以前もfalseを使った書き方をメンターの方に指摘いただいたのを思い出しました😅

`if !user.auto_retire`と修正しました✍️

2023-10-06 02:39 UTC, sochi419 commented on test/system/users_test.rb
> +  test 'calculate time to auto retire' do
確かにおっしゃる通りだと思います👀
test名を修正しました✍️

2023-10-06 05:11 UTC, sochi419 commented on app/helpers/users_helper.rb
> +end
helperメソッド内の以下の記述は削除しました。
````ruby
def automatic_retire_datetime(user)
  return unless user.hibernated_at

  user.hibernated_at.advance(months: 6)
end
````

2023-10-06 06:24 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  if user.remaining_days_until_automatic_retire(user) < 1
`user.メソッド名`の形で記述しているものは、`user.`が無い方がDRYなので、削除しました！

> どうしてこれで動いているのか正直よく分からないのですが…この定義の仕方でuserオブジェクトにメソッドが生えるのか…？🤔

定義の仕方が良くない部分がありましたか？
私は現場で働いたことがないので、「メソッド定義はこうあるべきだ」という基準が無い状態です。そのため、
今後のためにもなるので、どのあたりが良くないか教えていただけるとありがたいです🙏

2023-10-06 06:42 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  end
指摘ありがとうございます！
確かに厳しい条件から条件分岐させることでDRYにすることができました🙏

````ruby
def remaining_time_until_automatic_retire(user)
  if remaining_hours_until_automatic_retire(user) < 1
    "#{remaining_minutes_until_automatic_retire(user)}分"
  elsif remaining_hours_until_automatic_retire(user) < 24
    "#{remaining_hours_until_automatic_retire(user)}時間"
  else
    "#{remaining_days_until_automatic_retire(user)}日"
  end
end
````

2023-10-06 09:55 UTC, ogawa-tomo commented on app/helpers/users_helper.rb
> +  if user.remaining_days_until_automatic_retire(user) < 1
すみません、これは単に私の独り言です🙏
定義の仕方も問題ないですし、呼び出し方もこの修正で問題ないです。
不思議に思ったのは、修正前の書き方でどうしてメソッドを呼び出せていたのかということです。`user.メソッド名`という書き方で動作していたということは、userオブジェクトがメソッドを持っているということですよね。でも、今回のメソッドはUserクラスに定義したわけではありません。何もしていないのにメソッドが勝手に生えたように見えます。
余裕があれば調べてみますが、とりあえず実装としては今の形で問題ないです。

2023-10-06 12:28 UTC, sochi419 commented on test/system/users_test.rb
> +  end
追加しました！

2023-10-06 14:48 UTC, sochi419 commented
@ogawa-tomo 

修正しました〜
ご確認よろしくお願いします🙏

2023-10-06 23:36 UTC, ogawa-tomo approved these changes
@sochi419 1箇所コメントの微修正だけお願いしていますが、コードとしては良いと思うのでapproveです:+1:
レビュー期間が空いてすみませんでしたが、長期間ありがとうございました:bow:

2023-10-06 23:36 UTC, ogawa-tomo commented on test/system/users_test.rb
> +    # kyuukaiの退会日は "2020-01-01 09:00:00"に設定してあるので、その6ヶ月後の"2020-07-01 09:00:00"が自動退会日。
よく見たら、「kyuukaiの退会日は…」の箇所は「kyuukaiの休会日は…」が正しいですね！
テストが分かりやすくなって親切なコメントだと思いました:+1:

2023-10-07 02:15 UTC, sochi419 commented on test/system/users_test.rb
> +    # kyuukaiの退会日は "2020-01-01 09:00:00"に設定してあるので、その6ヶ月後の"2020-07-01 09:00:00"が自動退会日。
おっしゃる通り、日本語がおかしかったですね👀
こちら、修正しました✍️

2023-10-07 02:31 UTC, sochi419 commented
@ogawa-tomo 

レビューいただきありがとうございました！
どれも参考になる指摘ばかりで、勉強になりました✍️

長期間のレビュー、ありがとうございました🙏

@komagata 

受講生のレビューが終わりましたので、ご確認よろしくお願いします🙏

2023-10-10 11:30 UTC, komagata commented on app/helpers/users_helper.rb
> +  return unless user.hibernated_at
この辺りインデントはあってないかも？

2023-10-12 03:11 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  return unless user.hibernated_at
すみません、修正を繰り返していくうちに、インデントのずれに気づいていませんでした🙏

こちら、インデントのずれを修正しました✍️

2023-10-12 07:03 UTC, sochi419 commented
@komagata 

指摘いただいた点を修正しました✍️
確認よろしくお願いします🙏

2023-10-18 02:24 UTC, komagata commented on app/helpers/users_helper.rb
> +  return unless user.hibernated_at
@sochi419 レビュー依頼する前にFile ChangedのページでDiffを必ず（ローカルのエディタでチェックしていても、ブラウザ上で）チェックする癖をつけた方が良いかもです。

プログラマーだとみんなそういう癖がついていて、File Chagnedを一眼でも見ていれば回避できる問題がたくさんあるのでやってみると良いかもです〜

2023-10-18 02:27 UTC, komagata commented on app/helpers/users_helper.rb
> +  end
fatな処理はhelperに相応しくないので、modelに実装するのが良いと思います。
modelでもuserなどはfatなので、「休会からの経過日数」だけをオブジェクト指向でモデリングして、ActiveRecordを継承しないPORO（Plain Old Ruby Object）として実装するのが良さそうです。

日数の数字を出す部分はそこでやって、見た目に関する部分（〜時間など）はdecoratorかhelperでやるのが良さそうだと思いました。

2023-11-14 07:46 UTC, sochi419 commented
コンフリクト解消をした時に、過去のコミットが変わってしまったので、元に戻すコミットを追加します。

2023-11-22 01:48 UTC, sochi419 commented
@komagata 

レビューが遅れてしまいすみません🙇
修正しましたので、確認よろしくお願いします🙏

2023-11-29 04:57 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  end
[こちらの日報](https://bootcamp.fjord.jp/reports/84532)でコメントをいただいた通り、POROとして実装したファイル名を修正してみました。

2023-12-04 22:39 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  end
[こちらの日報](https://bootcamp.fjord.jp/reports/84532#comment_150697)で、こちらのレビューの内容の話が進んでしまったのでリンクを添付します。

2023-12-09 00:57 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  end
見た目だけの処理はdecoratorに記載をするようにしました。

また、`app/decorator/user/decorator.rb`にメソッドを記載した時に、rubocopの`Metrics/ModuleLength: Module has too many lines. [109/100]`エラーが発生したので、このファイルは行数制限を例外化する処理を加えました。（行数制限を例外化する方針は、質問チャンネルで確認済みです。）

2023-12-09 00:59 UTC, sochi419 commented
@komagata 

レビューありがとうございます！
修正しましたので、確認よろしくお願いします🙏

2023-12-14 07:04 UTC, komagata commented on app/decorators/user_decorator.rb
> +  def remaining_time_until_automatic_retire(user)
UserDecoratorにはuserという引数は不要なはずです。
Decoratorがどういうものか、何のためにあるのかというところを調べた方がいいかもです〜。

2023-12-14 07:04 UTC, komagata commented on app/helpers/users_helper.rb
> +  ((user.automatic_retire_datetime - Time.zone.now) / 60).floor
ここ、トップレベル（どのモジュール・クラスでもない）にメソッドを定義していないですか？

2023-12-16 08:28 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  ((user.automatic_retire_datetime - Time.zone.now) / 60).floor
privateの定義位置について、勘違いをした理解をしていました。

トップレベルにならないように修正を行いました。

2024-01-08 01:34 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +  def remaining_time_until_automatic_retire(user)
コメントありがとうございます。

> Decoratorがどういうものか、何のためにあるのかというところを調べた方がいいかもです〜。
- decoraterとは
Decoratorというデザインパターンを導入することで、ビューファイルにロジックを記述しないことが出来る。
複数のサイトを調べ、**viewロジックを簡素化するためのもの**という認識をしています。

> UserDecoratorにはuserという引数は不要なはずです。

UserDecorator引数のuserを削除した以下のような定義をしようとしました。

````ruby
  def remaining_time_until_automatic_retire
    if remaining_hours_until_automatic_retire(user) < 1
      "#{remaining_minutes_until_automatic_retire(user)}分"
    elsif remaining_hours_until_automatic_retire(user) < 24
      "#{remaining_hours_until_automatic_retire(user)}時間"
    else
      "#{remaining_days_until_automatic_retire(user)}日"
    end
  end
````

しかし、以下のようなエラーが起きてしまいます。
![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65bb825d9c8f639b5d2f82aa9a94096fea20c4f6/image.png)

確かに、他のUserDecoratorのメソッドを見ると、引数をuserとしているメソッドはないです。しかし、私が定義したメソッドだと内部に`remaining_hours_until_automatic_retire(user)`のようにuserの情報が必要になってしまいます。このような場合、userの情報を渡す必要があると考えているのですが、引数でuserを渡さない場合、どうすれば良いか混乱している状態です。
手詰まりになってしまったので、アドバイスをいただきたいです🙏

2024-01-09 04:03 UTC, komagata commented on app/decorators/user_decorator.rb
> +  def remaining_time_until_automatic_retire(user)
Rubyのクラスの書き方など、基本的な部分をもうちょっと考えてみると良いかもです。
Rubyの基本だけでわかるはずです〜

2024-01-10 04:19 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +  def remaining_time_until_automatic_retire(user)
回答ありがとうございます！
チェリー本を読み直して、p.262の`self`を使う方法を見つけました。
`self`を使った処理で修正を行いました✍️

2024-01-10 04:23 UTC, sochi419 commented
@komagata 

指摘いただいた箇所を修正しました。
確認よろしくお願いします🙇
https://github.com/fjordllc/bootcamp/pull/6659#discussion_r1446866288

2024-01-10 06:25 UTC, komagata requested changes

2024-01-10 06:25 UTC, komagata commented on app/helpers/users_helper.rb
> +  end
引数が`user`のみですし、こちらもdecoratorで実装した方が良さそうですね。

2024-01-10 06:25 UTC, komagata commented on app/decorators/user_decorator.rb
> +  def remaining_time_until_automatic_retire
こちらのテストが必要になります〜

2024-01-11 04:26 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  end
decoratorに実装をしました。

2024-01-11 05:21 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +  def remaining_time_until_automatic_retire
今回decoratorに定義したメソッドに対するテストを、`test/decorators/user_decorator_test.rb `に追加しました。

2024-01-13 05:14 UTC, sochi419 commented
@komagata 

指摘いただいた箇所の修正を行いました。
確認よろしくお願いします🙏

2024-01-16 10:30 UTC, komagata requested changes
一つコメントしたのと、下記のコミットメッセージが重複しているようです。

![スクリーンショット 2024-01-16 19 29 33](https://github.com/fjordllc/bootcamp/assets/16577/cc5cb41a-4450-4cc7-9ef0-0f0354840c79)

2024-01-16 10:30 UTC, komagata commented on test/system/users_test.rb
> +  end
@sochi419 (CC: @ogawa-tomo )

system testでページにアクセスするのはすごく重い処理でテスト全体の実行時間が遅くなると開発効率に響いてくるので慎重にやりたいです。

modelやdecoratorのテストで十分なところはそちらでお願いできるとありがたいです〜。

2024-01-16 12:24 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +  def remaining_time_until_automatic_retire
コミット名が重複していたので、コミット名を異なるものに修正しました。

2024-01-16 13:13 UTC, sochi419 commented on test/system/users_test.rb
> +  end
今回systemテストに定義した以下のテストは

````ruby
test 'display remaining time until auto retire' do
    # kyuukaiの休会日は "2020-01-01 09:00:00"に設定してあるので、その6ヶ月後の"2020-07-01 09:00:00"が自動退会日。

    travel_to Time.zone.local(2020, 7, 1, 8, 1, 0) do # 自動退会日まで1時間を切った場合。
      visit_with_auth "/users/#{users(:kyuukai).id}", 'komagata'
      assert_text '休会期限日時'
      assert_text '2020年07月01日(水) 09:00 (自動退会まであと59分)'
    end

    travel_to Time.zone.local(2020, 6, 30, 10, 0, 0) do # 自動退会日まで24時間を切った場合。
      visit_with_auth "/users/#{users(:kyuukai).id}", 'komagata'
      assert_text '休会期限日時'
      assert_text '2020年07月01日(水) 09:00 (自動退会まであと23時間)'
    end

    travel_to Time.zone.local(2020, 6, 24, 9, 0, 0) do # 自動退会日1週間を切った場合。
      visit_with_auth "/users/#{users(:kyuukai).id}", 'komagata'
      assert_text '休会期限日時'
      assert_text '2020年07月01日(水) 09:00 (自動退会まであと7日)'
    end

    travel_to Time.zone.local(2020, 1, 1, 9, 0, 0) do # 自動退会日6ヶ月前 ~ 1週間を切るまでの場合。
      visit_with_auth "/users/#{users(:kyuukai).id}", 'komagata'
      assert_text '休会期限日時'
      assert_text '2020年07月01日(水) 09:00 (自動退会まであと182日)'
    end
  end
````
下記の画像のように、「自動退会まで残り△△日/時間/分」の表示が**画面上に正常に表示されるか**をテストしています。

<img width="573" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/b63f2a61-21b7-4ef2-a38f-9d0f3dfe4865">

一方、decoratorに定義した以下のファイルで、**自動退会までの残り時間の計算処理**(残り△△日/時間/分の△△の部分の計算)をテストしているのですが、systemテストに定義していたテストと似たことをしていると思いました。

````ruby
  test '#remaining_time_until_automatic_retire' do
    # kyuukaiの休会日は "2020-01-01 09:00:00"に設定してあるので、その6ヶ月後の"2020-07-01 09:00:00"が自動退会日。

    travel_to Time.zone.local(2020, 7, 1, 8, 1, 0) do # 自動退会日まで1時間を切った場合。
      assert_equal '59分', @hibernationed_user.remaining_time_until_automatic_retire
    end

    travel_to Time.zone.local(2020, 6, 30, 10, 0, 0) do # 自動退会日まで24時間を切った場合。
      assert_equal '23時間', @hibernationed_user.remaining_time_until_automatic_retire
    end

    travel_to Time.zone.local(2020, 6, 24, 9, 0, 0) do # 自動退会日1週間を切った場合。
      assert_equal '7日', @hibernationed_user.remaining_time_until_automatic_retire
    end

    travel_to Time.zone.local(2020, 1, 1, 9, 0, 0) do # 自動退会日6ヶ月前 ~ 1週間を切るまでの場合。
      assert_equal '182日', @hibernationed_user.remaining_time_until_automatic_retire
    end
  end
````

そのため、systemテストに定義した`display remaining time until auto retire`テストは削除しようと考えていますが、如何でしょうか？
アドバイスをいただきたいです。

2024-01-16 17:01 UTC, komagata commented on test/system/users_test.rb
> +  end
@sochi419 

> 如何でしょうか？

同じことをやっているのであればSystemテストの方は削除して大丈夫です〜

2024-01-16 18:34 UTC, sochi419 commented
@komagata 

指摘いただいた点を修正しました。
確認よろしくお願いします🙏

2024-01-18 09:34 UTC, komagata commented on app/models/hibernation.rb
> +  def calculate_absence_days(user)
こちらもテストの作成をお願いします。

2024-01-18 11:33 UTC, sochi419 commented on .rubocop.yml
> +    - app/decorators/user_decorator.rb
必要です。

https://github.com/fjordllc/bootcamp/pull/6659#discussion_r1421183806
こちらのコメントでも言った通り、この行がないとrubocopに引っかかってしまいます。

````
app/decorators/user_decorator.rb:3:1: C: Metrics/ModuleLength: Module has too many lines. [113/100]
module UserDecorator ...
^^^^^^^^^^^^^^^^^^^^
````

このことを質問タイムで駒形さんに相談したところ、行数の制限を除外して良いとアドバイスをいただきました。
そのためこの行を追加したという経緯です。

659 files inspected, 1 offense detected

2024-01-18 11:55 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +    if remaining_hours_until_automatic_retire(self) < 1
申し訳ありません。
メソッドの定義場所を他のファイルに移動した関係で、privateメソッドが不要になったことに気づいていませんでした💦
privateメソッドは削除しました。

2024-01-18 12:23 UTC, sochi419 commented on app/models/user.rb
> +  def automatic_retire_datetime
> ModelやDecoratorに独自のメソッドを追加した場合は最低でも一つは対応するメソッドが必要です。

上記の「最低でも一つは対応するメソッドが必要です。」の意味がよく分からないのですが、対応するメソッドとはどういうことでしょうか？
decoratorファイルとhelperファイルに定義したメソッド内で`automatic_retire_datetime`メソッドは呼び出しているのですが、これは対応しているとは言わないのでしょうか？

2024-01-18 13:12 UTC, sochi419 commented on app/helpers/users_helper.rb
> +  end
似たメソッド同士なので1つにまとめました。

````ruby
  def remaining_hours_or_minutes_until_automatic_retire(user, hours_or_minutes)
    return unless user.hibernated_at

    remaining_time = user.automatic_retire_datetime - Time.zone.now
    seconds_per_hour_or_minute = hours_or_minutes == :hours ? 3600 : 60

    (remaining_time / seconds_per_hour_or_minute).floor
  end
````

2024-01-18 15:47 UTC, sochi419 commented on app/models/hibernation.rb
> +  def calculate_absence_days(user)
テストを追加しました。

2024-01-19 08:23 UTC, komagata commented on app/models/user.rb
> +  def automatic_retire_datetime
@sochi419 すみません、上記書き間違えていました。

X) 最低でも一つは対応するメソッドが必要です。
O) 最低でも一つは対応するテストが必要です。

2024-01-19 12:55 UTC, sochi419 commented on app/models/user.rb
> +  def automatic_retire_datetime
モデルのメソッドに対するテストを追加しました。

ModelやDecoratorに独自のメソッドを追加した場合は、最低でも一つは対応するtestが必要であるという常識を知りませんでした。
今後はModel, Decoratorにメソッドを定義したときは、必ずそのメソッドに対するテストも追加するようにします。

2024-01-19 13:10 UTC, sochi419 commented
@komagata 

レビューで指摘いただいた箇所の修正を行いました。
確認よろしくお願いします🙏

2024-01-22 23:21 UTC, komagata commented
@sochi419 基本的なプログラミングするときの考え方をこのIssueを題材にお話しした動画を作ってみました。
こちら参考にしてもらえれば幸いです〜。（画質悪くてすみません）

https://www.youtube.com/watch?v=EdRzZo-spls

2024-01-24 12:17 UTC, sochi419 commented
@komagata 

レビューありがとうございました。
レビューの内容を踏まえて、コードを修正しました。

修正前と修正後を見比べて、かなり見やすくなったと感じ、感激しました。

また、コード以外に以下の修正を行いました。
- issueの説明ページの説明が不十分だったので、仕様の説明を追記しました。
- issueとPRのタイトルを今回の仕様により近いタイトルに修正しました。

確認よろしくお願いします🙏

2024-01-24 12:41 UTC, komagata commented on app/decorators/user_decorator.rb
> +    ((Time.zone.now - hibernated_at) / 86_400).floor
`86_400`というマジックナンバーを使わずに処理できるはずです。
動画の中でも出てきているので確認してみてください。

2024-01-24 12:41 UTC, komagata commented on test/decorators/user_decorator_test.rb
> +    # kyuukaiの休会日は "2020-01-01 09:00:00"に設定されている。
@hibernationed_userがkyuukaiであることは自明なので、コメントは無しでいいかもです。そうするととってもテストもスッキリするように思います。

2024-01-24 12:41 UTC, komagata commented on test/models/user_test.rb
> +  end
```suggestion
  test '#scheduled_retire_at' do
    assert_equal '2020-07-01 09:00:00 +0900',
    　　users(:kyuukai).scheduled_retire_at.to_s
  end
```

で良さそうです。

2024-01-24 15:01 UTC, sochi419 commented on test/models/user_test.rb
> +  end
確かに1度しか使わない変数ならば、定義する必要はなさそうですね。
修正しました✍️

2024-01-24 15:01 UTC, sochi419 commented on test/decorators/user_decorator_test.rb
> +    # kyuukaiの休会日は "2020-01-01 09:00:00"に設定されている。
削除しました。

2024-01-24 17:02 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +    ((Time.zone.now - hibernated_at) / 86_400).floor
https://api.rubyonrails.org/v5.2.1/classes/ActiveSupport/Duration.html#method-i-to_i
を参考に、マジックナンバーを使わない処理に修正しました。

2024-01-24 17:03 UTC, sochi419 commented
@komagata 

指摘いただいた箇所を修正しました。
確認よろしくお願いします🙏

2024-01-25 05:29 UTC, komagata commented on app/decorators/user_decorator.rb
> +    ((Time.zone.now - hibernated_at) / 1.day.to_i).floor
@sochi419 動画の中で話しているように、全体的にActiveSuport::Durationを使ってみてください。期間を表すクラスです。これを使えば汎用的でシンプルなコードになると思います。

わからない点があったら調べてみてください。

2024-01-26 03:04 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +    ((Time.zone.now - hibernated_at) / 1.day.to_i).floor
`ActiveSupport::Duration`を使った処理に書き換えました。
確かにシンプルで見やすいコードになったと感じました👀

2024-01-27 14:12 UTC, komagata reviewed
気になる点が複数だったので動画にしてみました。

https://www.youtube.com/watch?v=GV6YBWeY4-w

2024-01-28 08:03 UTC, sochi419 commented on app/decorators/user_decorator.rb
> +    ActiveSupport::Duration.build(Time.zone.now - hibernated_at).in_days.floor if hibernated_at?
動画では`.floor`が無くても良いとなっていましたが、floorがないと画像のように小数点が表示されてしまいます。
<img width="448" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/24fa4442-3410-4259-87c7-e99047ca7b83">

そのため、floorは消さずに残しました。

2024-01-29 02:37 UTC, sochi419 commented
@komagata 

レビュー修正ありがとうございました。
修正しましたので、確認よろしくお願いします🙏

2024-01-29 02:50 UTC, komagata commented on test/decorators/user_decorator_test.rb
> +  test '#retire_deadline_1_hour' do
`#retire_deadline`はインスタンスメソッドという意味です。
全部繋げてunderscoreで繋ぐとそういうメソッドがあるという意味になってしまうので別の表現がいいと思います。

2024-01-29 04:27 UTC, sochi419 commented on test/decorators/user_decorator_test.rb
> +  test '#retire_deadline_1_hour' do
decoratorに定義した`retire_deadline`メソッドをテストしていると意味合いで、`#`をつけていました。

こちらに関しては、テストの命名から`#`を削除しました。

2024-01-29 07:30 UTC, sochi419 commented on test/decorators/user_decorator_test.rb
> +  test '#retire_deadline_1_hour' do
(追記)
 `#retire_deadline 1 hour`のように、全てをアンダースコアで繋げるのではなく、空白で表現する書き方にしました。

2024-01-29 08:52 UTC, sochi419 commented
@komagata 

指摘いただいた箇所の修正を行いました。
確認よろしくお願いします〜🙏

2024-01-30 05:39 UTC, komagata approved these changes
長いPRお疲れ様です。
確認させて頂きました。OKです〜🙆‍♂️

2024-01-30 05:39 UTC, merged

2024-01-31 02:20 UTC, sochi419 commented
@komagata 

長期間レビューにお付き合いいただきありがとうございました！
とても勉強になりました✍️

2024-01-31 07:22 UTC, sochi419 commented
# メモ
1/31（水）のMTGにてこのPRについて話した内容を記載します。
(CC. @komagata 間違いがあれば指摘をお願いします🙏)

- ステージング環境での動作確認は、rails consoleからユーザーの休会タイミングを調整することはできないので、別PRからseedを使って、休会日時の異なるユーザーを追加することになりました。
- 本番環境での動作確認は、私からは誰がどのタイミングで休会するかを把握する術がないので、駒形さんと話し合いながら決めていく方針になりました。

2024-02-07 05:28 UTC, sochi419 commented
@komagata @machida 

お疲れ様です。
こちらのPRにつきまして、管理者のみに表示される箇所に問題がないことを本番環境で確認したく、動作確認をお願いします。
実際に自動退会が近くなったユーザーが現れてから確認をする形になるかと思います。

確認していただきたいものは、休会中のユーザーについて以下4パターンになります。

- 休会期限日6ヶ月前 ~ 1週間前の休会中ユーザーの場合
  - 休会期限日時と自動退会までの日数（自動退会まで残りXX日）が表示される。
<img width="561" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/df933030-f900-4aa1-92eb-39a5711156d2">


- 休会期限まで1週間を切った休会中ユーザーの場合
  - 休会期限日時と自動退会までの日数（自動退会まで残りXX日）が表示される。
  - 赤字で表示される。
<img width="570" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/53338efd-6393-4298-9278-40e92bad1d6a">


- 休会期限まで24時間を切った休会中ユーザーの場合
  - 休会期限日時と自動退会までの残り時間（自動退会まで残りXX時間）が表示される。
  - 赤字で表示される。
<img width="571" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/065bff32-fd92-4171-a156-9273feade18e">


- 自動退会しない休会中ユーザの場合
  - 企業都合休会中(XX日)という表示がされることを確認する。(XXは休会日からの経過日数)
<img width="564" alt="image" src="https://github.com/fjordllc/bootcamp/assets/92995093/28c9be39-dd60-47c7-96d4-3db2724df5ee">

こちらのPRにつきまして、本番で動作確認できましたらご連絡いただけますでしょうか。
確認できたらイシューをクローズします。

以上、よろしくお願いします🙏

2024-02-22 02:24 UTC, komagata commented
:memo:

- [x] 自動退会まで残り24時間以内のユーザー
- [ ] 自動退会まで残り1週間以内のユーザー
- [ ] 自動退会まで残り1週間以上のユーザー
- [ ] 自動退会しないユーザー