ダッシュボードの近日開催のイベントに、参加していない定期イベントも表示するようにした&参加登録済イベントに表示をつけた
fjordllc/bootcamp pull request #6865
Opened 2023-09-04 06:05 UTC by fuwa-syugyo

## Issue

- Issue番号
https://github.com/fjordllc/bootcamp/issues/6823
## 概要
ダッシュボードの近日開催のイベントの表示を以下のように変更した。
* 参加登録していない定期イベントも表示するようにした
* 参加登録している定期&特別イベントに「参加登録済」と表示するようにした

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-09-04 07:56 UTC, fuwa-syugyo commented
@machida 
お疲れ様です！
対応を行いましたので、「参加登録済」のデザインのご対応をお願い出来ますでしょうか🙏
よろしくお願いいたします。

2023-09-06 04:27 UTC, machida commented
@fuwa-syugyo デザイン入れますー

2023-09-08 05:52 UTC, machida commented
@fuwa-syugyo デザイン入れましたー

2023-09-09 14:38 UTC, fuwa-syugyo commented
@machida 
ご対応いただきありがとうございます！
確認させていただきます〜

2023-09-17 02:32 UTC, fuwa-syugyo commented
@machida 
お疲れ様です。
先日入れていただいたデザインについて、確認させていただきたいです。
こちらのコミット( https://github.com/fjordllc/bootcamp/pull/6865/commits/30024669d1e354c825bcb8747387e1581522fd27 )でダブルクォート→シングルクォートに変更されていますが、シングルクォートのままで進めた方がよろしいでしょうか？
エスケープされなくなっているためかシングルのままだと該当箇所のテストが落ちており、ダブルに戻すと通ります。
問題なければダブルに戻して進めたいのですが、いかがでしょうか？

2023-09-17 02:37 UTC, machida commented
@fuwa-syugyo すいません、戻して大丈夫ですー🙆‍♀️

2023-09-18 09:51 UTC, fuwa-syugyo commented
@machida 
お疲れ様です。
一通り対応してレビューしてもらう準備を整えたのですが、こちらのPR( https://github.com/fjordllc/bootcamp/pull/6806 )がマージされてからレビューしてもらった方が良いでしょうか？
もし変更があれば私のPRの方にも影響が出る可能性がありますし、マージを待ってからならmainブランチとの比較だけで済むのでレビュアーの負担が減るかなと思うのですが。
それとも早めにレビューを受けた方が良いでしょうか？

お手数ですがご確認よろしくお願いいたします🙏

2023-09-28 00:51 UTC, fuwa-syugyo commented
@machida 
お疲れ様です！
一通り対応したのですが、念の為デザインが想定通りかご確認をお願いしてもよろしいでしょうか？

2023-10-02 06:42 UTC, machida commented
@fuwa-syugyo 確認が遅れてすいません！！確認しました。バッチリです🙆‍♂️

2023-10-02 07:38 UTC, fuwa-syugyo commented
@machida 
催促してしまいすみません。
ご確認いただきありがとうございます！

2023-10-02 07:56 UTC, fuwa-syugyo commented
@dowdiness 
お疲れ様です！
お手数ですが、レビューをお願いしてもよろしいでしょうか…？

2023-10-07 18:10 UTC, dowdiness requested changes
遅くなってすいません🙇
動作確認とコードレビューしました！

動かしてみたところ近日開催予定の特別イベントで表示されないものがありました。
どうやら就活関係のイベントの場合は求職者以外には表示されないようになっているようです。
issueでは全てのイベント（特別イベント、定期イベント両方）が表示されるようにするよう言われているのでこれは狙った仕様ではないと思います。
テストの方でも就活関係のイベントのデータも入れてテストした方が良いかもしれません。

他の部分は綺麗に書かれて特に問題もなく動いていると思います👌

2023-10-10 12:59 UTC, fuwa-syugyo commented on app/controllers/home_controller.rb
>                                   .sort_by { |e| e.start_at.strftime('%H:%M') }
修正します！

2023-10-10 13:06 UTC, fuwa-syugyo commented
@dowdiness 
返信が遅くなりすみません！
就活関連のイベントについては確認いたします〜

@machida 
お疲れ様です！
就活関連のイベントは求職者以外にも表示できるようにした方が良いでしょうか？
(少なくとも研修で使用している人は表示されない方が良いと思いますが。。)

2023-10-14 00:13 UTC, machida commented
@fuwa-syugyo 今回は就活情報も表示されてしまって大丈夫です。就活関連イベントであることを表示しておいていただけると助かります。デザインやりますー

2023-10-14 01:10 UTC, fuwa-syugyo commented
@machida 
かしこまりました！
対応しましたらご連絡いたします。よろしくお願いいたします🙇‍♀️

2023-10-14 01:11 UTC, machida commented
@fuwa-syugyo ありがとうございます！よろしくお願いします🙏

2023-10-21 11:28 UTC, fuwa-syugyo commented on app/views/home/_special_event.html.slim
> +                - if special_event.job_hunting?
就活関連のイベントに「就活」と表示されるようにしました。
現状は「参加」と同じ見た目になっています🙏

2023-10-21 13:04 UTC, fuwa-syugyo commented
@machida 
遅くなってすみません🙇‍♀️
就活関連のイベントに「就活」と表示するようにしました。
デザインをお願いいたします。
<img width="592" alt="image" src="https://github.com/fjordllc/bootcamp/assets/62344131/790ae81a-e112-4244-a22a-2ecf6310a4e0">

2023-10-24 10:48 UTC, machida commented
@fuwa-syugyo デザイン入れましたー

2023-11-03 07:52 UTC, fuwa-syugyo commented
@machida 
遅くなりすみません！
ご対応いただきありがとうございます。
手元でデザインが入ったことを確認しました。

2023-11-03 07:55 UTC, fuwa-syugyo commented
@dowdiness 
遅くなり大変申し訳ございません。
以下対応しましたのでご確認をお願いできますでしょうか。
* https://github.com/fjordllc/bootcamp/pull/6865#discussion_r1349551017 でご指摘いただいた重複の修正
* 就活関連のイベントを全てのユーザーに表示させる

お手隙の際で大丈夫ですので、よろしくお願いいたします🙇‍♀️

2023-11-21 13:38 UTC, dowdiness approved these changes
すいません長い間待たせてしまいました🙏

就活関連のイベントの表示と重複したコード部分の削除を確認出来ました👍
就活関連イベントのテストが追加されているのも良いですね。

ただ、mainブランチの変更の反映にrebaseではなく新しくマージコミットを作る形式を使っているのが気になりました。fjordではrebaseを使う形式を採用しているためもしかしたらkomagataさんに修正を求められるかもしれません。

コードと機能には全く問題はないと思うので自分の方ではapproveしますー

2023-12-06 06:05 UTC, machida commented
@komagata 
受講生レビューが終わったので、レビューをお願いします

2023-12-06 06:06 UTC, machida commented
📝 
一旦、machida担当にします。

2023-12-14 07:09 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-12-14 07:09 UTC, merged