権限のないユーザーがイベントを編集できてしまうバグの修正&定期イベントの作成者は自動的に主催者にさせる
fjordllc/bootcamp pull request #6903
Opened 2023-09-15 07:06 UTC by fuwa-syugyo

## Issue
https://github.com/fjordllc/bootcamp/issues/6634

## 概要
* 権限を持つユーザーのみが`/edit` にアクセスできるようにした
* 定期イベントの作成者は自動的に主催者になる処理を追加

※権限を持つユーザーは以下
特別イベント: メンター、作成者
定期イベント: メンター、主催者(作成者含む)

## 変更確認方法

1. `bug/all_user_can_edit_all_event`をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-09-15 11:57 UTC, fuwa-syugyo commented
@syo-tokeshi 
お疲れ様です！

もしよろしければレビューをお願いしてもよろしいでしょうか…？
全く急ぎではありませんので、可能でしたらお願いいたします🙏

2023-09-15 14:29 UTC, syo-tokeshi commented
@fuwa-syugyo 
レビュー依頼ありがとうございます！！
やってみます😊
来週水曜日までを目安に返信いたします🙇‍♂️

2023-09-16 12:43 UTC, syo-tokeshi commented on app/controllers/events_controller.rb
> +  before_action :set_editable_event, only: %i[edit update]
`set_editable_event`こちらのメソッドを無くして、
`set_event`メソッドで、`edit update destroy`アクションの`@event`オブジェクトを作成した方が良いと思いました🙇‍♂️

2023-09-16 12:47 UTC, syo-tokeshi commented on app/controllers/events_controller.rb
> +    @event = current_user.mentor? ? Event.find(params[:id]) : current_user.events.find(params[:id])
こちらのロジックは問題無いと思います！🙆‍♂️
こちらのロジックをそのまま`set_event`で使った方が良いと思いました
```rb
  def set_event
    @event = current_user.mentor? ? Event.find(params[:id]) : current_user.events.find(params[:id])
  end
```
`set_event`イベントはそのまま
```rb
 before_action :set_event, only: %i[edit update destroy]
```
のフックメソッドで使って問題無いと思います。

```
rails test test/system/events_test.rb
rails test test/system/regular_events_test.rb
```
変更後もこちら両方のテストでパスすること、確認致しました🙇‍♂️

2023-09-16 14:14 UTC, syo-tokeshi commented on app/controllers/regular_events_controller.rb
> +  before_action :set_editable_regular_event, only: %i[edit update]
こちらの
```rb  
before_action :set_editable_regular_event, only: %i[edit update]
```
は削除しまして、
代わりに`set_regular_event`メソッドを以下のように変更するのはいかがでしょうか？
```rb
before_action :set_regular_event, only: %i[show edit update destroy]
```
```rb
def set_regular_event
    @regular_event = if params[:action] == 'show'
                       RegularEvent.find(params[:id])
                     elsif params[:action] == 'edit' || 'update' || 'destroy' # rubocop:disable Lint/LiteralAsCondition
                       current_user.mentor? ? RegularEvent.find(params[:id]) : RegularEvent.organizer_event(current_user).find(params[:id])
                     end
  end
```
こうする事で、一つのメソッドで`%i[show edit update destroy]`のアクションに対応出来ます。

[info]
rubocopの警告の出力を阻止するコメントを挿入しておりますが、
理由としまして`update`、`destroy`という文字列が警告対象になってしまうからです。(コメントを外して頂くと分かると思います)

警告を出さないやり方として
```rb
elsif %i[show edit update destroy].include?(params[:action])
```
という書き方も可能ですが、上記の方がリーダブルなので、私から上記を提案させて頂きます🙇‍♂️

2023-09-16 14:16 UTC, syo-tokeshi commented on app/controllers/regular_events_controller.rb
> +  def set_editable_regular_event
上記の提案により、こちらのメソッドは無くても良いと思います🙇‍♂️

2023-09-17 02:33 UTC, syo-tokeshi commented on test/system/events_test.rb
> +  test 'edit only users or mentor' do
こちら
`test 'event creator and mentor can edit' do`
という名前へ変更するのはどうでしょうか？

特別イベントを変更できるユーザーは「メンター、作成者」だからです🙇‍♂️

2023-09-17 02:41 UTC, syo-tokeshi commented on test/system/events_test.rb
> +    visit_with_auth edit_event_path(events(:event5)), 'hajime'
こちらは`event5`から`event1`に変更するのはどうでしょうか？
同じイベントを対象にテストする事で、
- イベント作成者本人
- メンター
のみが編集できる、というのを分かりやすく出来ると思います。

2023-09-17 03:04 UTC, syo-tokeshi commented on test/system/regular_events_test.rb
> +  test 'edit only organizers or mentor' do
こちらテスト名を
`test 'organizers and mentor can edit' do`
にするのはどうでしょうか？

2023-09-17 03:42 UTC, syo-tokeshi commented
@fuwa-syugyo 
お待たせいたしました🙇‍♂️
レビュー完了しましたので、ご確認よろしくお願い致します😊

勉強になりました😆

2023-09-17 03:49 UTC, syo-tokeshi requested changes
@fuwa-syugyo 
お待たせいたしました🙇‍♂️
レビュー完了しましたので、ご確認よろしくお願い致します😊

勉強になりました😆

2023-09-17 08:03 UTC, fuwa-syugyo commented on app/controllers/events_controller.rb
> +  before_action :set_editable_event, only: %i[edit update]
`set_event`メソッドで対応しました！

2023-09-17 08:04 UTC, fuwa-syugyo commented on app/controllers/events_controller.rb
> +    @event = current_user.mentor? ? Event.find(params[:id]) : current_user.events.find(params[:id])
`set_event` の中身を旧`set_editable_event`としました。

2023-09-17 08:05 UTC, fuwa-syugyo commented on app/controllers/regular_events_controller.rb
> +      Organizer.create(user_id: current_user.id, regular_event_id: @regular_event.id) unless @regular_event.organizers.include?(current_user.id)
確認したところ不要だったので削除しました。
意図としては「作成者が主催者に含まれているときはOrganizer.createを行わない」(=主催者の重複を避ける)ようにしたかったのですが、条件式がなくても重複しなかったので削除しました。

2023-09-17 08:15 UTC, fuwa-syugyo commented on app/controllers/regular_events_controller.rb
> +  before_action :set_editable_regular_event, only: %i[edit update]
こちら、個人的には以下の方が良いかなと思いました。
```
before_action :set_regular_event, only: %i[edit update destroy]

  def show
    @regular_event = RegularEvent.find(params[:id])
  end

  def set_regular_event
    @regular_event = current_user.mentor? ? RegularEvent.find(params[:id]) : RegularEvent.organizer_event(current_user).find(params[:id])
  end
```

私の個人的な感覚になりますが、case文を使うと行数が増えてしまい読みにくくなってしまうかなと思いました。
showアクションに処理を分けた方が良いかなと思います。
ちなみに同じような処理を行っている`reports_controller.rb`でもshowアクションに分けています。
```
  before_action :set_report, only: %i[show]
  before_action :set_my_report, only: %i[destroy]
  before_action :set_editable_report, only: %i[edit update]

  def index; end

  def show
    @products = @report.user.products.not_wip.order(published_at: :desc)
    respond_to do |format|
      format.html
      format.md
    end
  end

  def set_report
    @report = Report.find(params[:id])
  end

  def set_my_report
    @report = current_user.reports.find(params[:id])
  end

  def set_editable_report
    @report = current_user.mentor? ? Report.find(params[:id]) : current_user.reports.find(params[:id])
  end
```

(あと、コントローラーの行数が増えるとlintに引っかかりやすくなるという懸念もありますね…もう少しで100行に到達してしまうかと思います。)

2023-09-17 08:16 UTC, fuwa-syugyo commented on app/controllers/regular_events_controller.rb
> +  def set_editable_regular_event
`set_editable_regular_event`は削除しました！

2023-09-17 08:22 UTC, fuwa-syugyo commented on test/system/events_test.rb
> +  test 'edit only users or mentor' do
`edit only creator or mentor` に変更しました。
イベント作成者は`user`という名前が付いていたので()踏襲したのですが、パッと見だとわからないのでcreatorの方が良いですね。
(小さくて恐縮ですが、画像は作成者の部分のタグです。`<a -class="a-user-name"~>` とあります)

<img width="1288" alt="image" src="https://github.com/fjordllc/bootcamp/assets/62344131/e46c0ac9-e106-4cb9-93a3-9e173fbdd9f6">

その他の部分についてですが、以下の理由でこのままが良いかなと私的には思います。
* 他のテスト名は比較的、動詞から始まっているからedit始まり
* 変更できるのが作成者とメンターであることを強調したいからonly

私の感覚的にはonlyを使った方がテストの意図が読み取りやすいかなと思うのですが、いかがでしょうか？
(この辺は人によりけりだと思います)

2023-09-17 08:32 UTC, fuwa-syugyo commented on test/system/events_test.rb
> +    visit_with_auth edit_event_path(events(:event5)), 'hajime'
テストデータとパターンについて、ご提案の通り修正させていただきました。

コメントについてですが、このあたりは駒形さんに相談しようかなと思います。
コメントを残すかどうかの基準について調べましたが、参考情報を残すという使い方もあるようですね。( https://qiita.com/jnchito/items/f0d90af4ed44b7484103 )

ただ私個人としては以下の理由により残さなくても良いかなと考えています。
* 同様の処理が既出であり、そちらには特にコメントが書かれていないこと
`test/system/pages_test.rb` ですでに使われていました。  テスト名に`404`と含まれていますし概要がすぐつかめると思います
<img width="683" alt="image" src="https://github.com/fjordllc/bootcamp/assets/62344131/c1383784-cea0-487a-b01b-a85e3069206e">

* `Capybara.raise_server_errors` とググるとすぐに参考文献が見つかること

2023-09-17 08:35 UTC, fuwa-syugyo commented on test/system/regular_events_test.rb
> +  test 'edit only organizers or mentor' do
テストデータとパターンについて、ご提案の通り修正させていただきました。

テスト名とコメントについては前述の理由によりそのままとさせていただきたいです。

2023-09-17 08:40 UTC, fuwa-syugyo commented
@syo-tokeshi 
ご確認いただきありがとうございます！
とても細かく見てくださって非常に助かりました🙇‍♀️
引き続きご意見をいただきたい箇所がいくつかございますので、お手隙の際にご確認いただければと思います。
よろしくお願いいたします🙏

2023-09-17 09:48 UTC, syo-tokeshi commented on app/controllers/events_controller.rb
> +  before_action :set_editable_event, only: %i[edit update]
確認しました！

2023-09-17 09:48 UTC, syo-tokeshi commented on app/controllers/events_controller.rb
> +    @event = current_user.mentor? ? Event.find(params[:id]) : current_user.events.find(params[:id])
確認しました！

2023-09-17 09:49 UTC, syo-tokeshi commented on app/controllers/regular_events_controller.rb
> +      Organizer.create(user_id: current_user.id, regular_event_id: @regular_event.id) unless @regular_event.organizers.include?(current_user.id)
確認しました！

2023-09-17 09:52 UTC, syo-tokeshi commented on app/controllers/regular_events_controller.rb
> +  before_action :set_editable_regular_event, only: %i[edit update]
確認しました！
私も問題ないと思いましたので、fuwaさん案で行きましょう😊

2023-09-17 10:02 UTC, syo-tokeshi commented on app/controllers/regular_events_controller.rb
> +  def set_editable_regular_event
確認しました🙇‍♂️

2023-09-17 10:07 UTC, syo-tokeshi commented on test/system/events_test.rb
> +  test 'edit only users or mentor' do
> 私の感覚的にはonlyを使った方がテストの意図が読み取りやすいかなと思うのですが、いかがでしょうか？

こちらでも意味が通じますし、簡潔なのでfuwaさん案でokだと思いました🙇‍♂️
fuwaさんの言う通り、fuwaさん案でもテストの意図が読み取りやすいので、大丈夫だと思います😊

2023-09-17 10:14 UTC, syo-tokeshi commented on test/system/events_test.rb
> +  test 'edit only users or mentor' do
fuwaさんの変更して下さいました今のテストですと、`creator`の方が編集できる事を証明するテストがないので、
私が先ほど提案したこちらを追加するのはいかがでしょうか？
```rb
test 'edit only creator or mentor' do
    visit_with_auth edit_event_path(events(:event1)), 'kimura'
    assert_text '特別イベント編集'
    visit_with_auth edit_event_path(events(:event1)), 'komagata'
    assert_text '特別イベント編集'

    Capybara.raise_server_errors = false
    visit_with_auth edit_event_path(events(:event1)), 'hajime'
    assert_text 'ActiveRecord::RecordNotFound'
  end
```

2023-09-17 10:18 UTC, syo-tokeshi commented on test/system/events_test.rb
> +    visit_with_auth edit_event_path(events(:event5)), 'hajime'
確認しました。

> Capybara.raise_server_errors とググるとすぐに参考文献が見つかること

私も検索を行い、この情報に簡単にアクセスできること確認しました。
fuwaさんの意見が正しいと思いましたので、コメントの件は無しで行きますか！😊(それで問題ないと思いました。`raise_server_errors = false`は英語の内容から動きが想像できそうですし🙇‍♂️)

2023-09-17 10:19 UTC, syo-tokeshi commented on test/system/regular_events_test.rb
> +  test 'edit only organizers or mentor' do
了解しました！🙇‍♂️

2023-09-17 10:24 UTC, syo-tokeshi reviewed
> とても細かく見てくださって非常に助かりました🙇‍♀️
引き続きご意見をいただきたい箇所がいくつかございますので、お手隙の際にご確認いただければと思います

@fuwa-syugyo 
ありがとうございます😊

修正を再度確認させて頂きました！

ほぼokなのですが、こちらを確認して頂いてもよろしいでしょうか？😀
よろしくお願い致します

[確認して頂きたい箇所です]
https://github.com/fjordllc/bootcamp/pull/6903#discussion_r1328074263

[追加してpushして頂いた分のレビューです]
https://github.com/fjordllc/bootcamp/pull/6903#discussion_r1328075010

2023-09-17 10:24 UTC, syo-tokeshi commented on test/system/regular_events_test.rb
> +    assert_css '.a-user-icon.is-hajime'
goodですね😊
分かりやすいです😆
これだったら読んだ人が「イベント作成者は自動でorganizersになるんだな」というのが分かりますね😊
リーダブルだと思いました！

2023-09-18 00:51 UTC, fuwa-syugyo commented on test/system/events_test.rb
> +    visit_with_auth edit_event_path(events(:event5)), 'hajime'
ご確認ありがとうございます！
コメントはなしで進めさせていただこうかと思います〜

2023-09-18 01:27 UTC, fuwa-syugyo commented on test/system/events_test.rb
> +  test 'edit only users or mentor' do
```
    visit_with_auth edit_event_path(events(:event1)), 'kimura'
    assert_text '特別イベント編集'
```
を追加しました。
すみません、対応漏れでした🙇‍♀️

2023-09-18 01:29 UTC, fuwa-syugyo commented
@syo-tokeshi 
ご確認いただきありがとうございます！
こちらについて、修正しましたのでご確認をお願いできますでしょうか🙇‍♀️
https://github.com/fjordllc/bootcamp/pull/6903#discussion_r1328074263

2023-09-18 01:33 UTC, syo-tokeshi commented on test/system/events_test.rb
> +  test 'edit only users or mentor' do
確認しました！
ありがとうございます😊

2023-09-18 01:35 UTC, syo-tokeshi approved these changes
@fuwa-syugyo 
全て確認いたしました！
良いと思いますのでApproveさせて頂きます😊
勉強になりました😆

2023-09-18 02:38 UTC, fuwa-syugyo commented
@komagata 
お疲れ様です。
メンバーからApproveいただきましたので、レビューをお願いいたします🙏

2023-09-19 14:26 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-09-19 14:26 UTC, merged