メール通知設定がOFFになっている場合は、相談部屋からのメール通知が飛ばないように修正
fjordllc/bootcamp pull request #6981
Opened 2023-10-20 08:16 UTC by natsuto6

## Issue

- #6948

## 概要

- 管理者のメール通知設定を`OFF`にした場合、相談部屋からのメール通知が飛ばないように修正。

## 変更確認方法

1. `bug/fix-admin-notification-ignoring-settings`をローカルに取り込む
2. `foreman start -f Procfile.dev`でローカル環境を立ち上げる
3. `localhost:3000`にアクセス
4. `komagata`でログイン
5. 「登録情報変更」画面でメール通知設定を`OFF`にし、「更新する」ボタン押下
6. `kimura`でログインし直す
7. 相談部屋で任意のテキストを入力し「コメントする」ボタン押下
8. `http://localhost:3000/letter_opener/`にアクセス
9. `komagata`宛にメール通知が届いていないことを確認する

## Screenshot

### 変更前

<img width="1216" alt="_development__LetterOpenerWeb" src="https://github.com/fjordllc/bootcamp/assets/79001972/97a46061-97c1-4997-a9e1-8ec892c352cb">

### 変更後

<img width="1252" alt="_development__LetterOpenerWeb" src="https://github.com/fjordllc/bootcamp/assets/79001972/0691b70c-c95f-4d1b-a738-4dc3956a983a">

2023-10-20 10:34 UTC, natsuto6 commented
@rira100000000 
お疲れ様です！度々恐れ入ります...🙇‍♂️
お手数ですが、こちらのIssueのレビューをお願い致します。

2023-10-20 10:49 UTC, rira100000000 commented
@natsuto6 
承知しました！
3日以内には返せると思います！

2023-10-21 07:04 UTC, rira100000000 requested changes
コメントしました！

現状だとメール通知を切るとサイト内通知も飛ばなくなっているようです。
修正よろしくお願いします🙏

2023-10-22 02:00 UTC, natsuto6 commented on app/mailers/activity_mailer.rb
> +    return unless @receiver.mail_notification
レビューいただきありがとうございます🙇‍♂️
こちらご指摘のとおり`mail_notification?`に修正しました。

2023-10-22 02:00 UTC, natsuto6 commented on app/models/comment_notifier_for_admin.rb
> +      next unless admin_user.mail_notification?
削除しました。

2023-10-22 02:00 UTC, natsuto6 commented on test/mailers/activity_mailer_test.rb
> +    ActionMailer::Base.deliveries.clear
削除しました。

2023-10-22 02:00 UTC, natsuto6 commented on test/mailers/activity_mailer_test.rb
> +    Notification.create!(
削除しました。

2023-10-22 02:02 UTC, natsuto6 commented
@rira100000000 
レビューいただきありがとうございます！🙇‍♂️
ご指摘の箇所を修正しましたので再レビューをお願い致します。

2023-10-22 06:57 UTC, rira100000000 commented
@natsuto6 
修正ありがとうございます！

すいません、削除されたテストですが、通知が飛ばなくなることを確認するテスト自体はあった方が良いかと思います。
```ruby
ActionMailer::Base.deliveries.clear
```
の部分と、
```ruby
 Notification.create!(
      kind: Notification.kinds['came_comment'],
      user: comment.receiver,
      sender: comment.sender,
      link: "#{commentable_path}#latest-comment",
      message: "相談部屋で#{comment.sender.login_name}さんからコメントがありました。",
      read: f
```
の部分は無くてもいいのでは？という意味でした。

2023-10-22 07:50 UTC, natsuto6 commented
@rira100000000 
度々恐れ入ります🙇‍♂️
すみません、指摘の内容を履き違えておりました...
改めて修正しましたのでご確認をお願い致します。

2023-10-22 08:12 UTC, rira100000000 approved these changes

2023-10-22 08:13 UTC, rira100000000 commented
@natsuto6 
修正ありがとうございます！
コード動作共に問題ないと思いますので、Approveとさせていただきます。

2023-10-22 08:16 UTC, natsuto6 commented
@rira100000000 
ご確認いただきありがとうございました！

@komagata 
チームメンバーのレビューを通りましたので、お手数ですがレビューをお願い致します。

2023-10-23 07:08 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-10-23 07:09 UTC, merged