提出物のPRのリンクが間違っているとき警告を出すようにした
fjordllc/bootcamp pull request #7006
Opened 2023-10-30 09:00 UTC by eatplaynap

## Issue

- #3992

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2023-10-30 09:43 UTC, eatplaynap commented
@rira100000000 
Kaigi on Railsご視聴ありがとうございました！本番のモブプロにて取り組んだIssueになります。
我々の発表の感想を書いてくださったのを拝読したためレビュー依頼させていただきました🙇

2023-10-30 13:08 UTC, rira100000000 requested changes
Kaigi on Railsお疲れ様でした！最高の発表でしたね😆

レビュー依頼もありがとうございます！
早速コメントさせていただきましたので、確認をお願いいたします。

2023-10-30 13:08 UTC, rira100000000 commented on test/models/product_test.rb
> +    assert_equal 'PRのURLが間違っています。PRを作り直してください', product.errors[:body].first
テストが落ちてますね。
「中のPRのURLが間違っています。PRを作り直してください」にする必要があります。

2023-11-01 06:33 UTC, rira100000000 commented on app/models/product.rb
> +    errors.add(:body, '中のPRのURLが間違っています。PRを作り直してください') if body.match?(/#{GITHUB_ACCOUNT_NAME}\/.+\/pull\/\d+/)
メッセージの内容について開発ミーティングで駒形さんに伺ったところ、こちらの例示の内容で問題ないということでしたので、そのようにお願いします🙏

2023-11-06 03:39 UTC, eatplaynap commented
@rira100000000 
修正しましたので再レビューお願いいたします。

<img width="300" alt="CleanShot 2023-11-06 at 12 35 27@2x" src="https://github.com/fjordllc/bootcamp/assets/63531341/85e56a49-4fcf-4df3-8f28-0ac387df91f4">

↑のようにエラーメッセージ内にリンクが表示させるようにしました。例示いただいた「PRの作成方法が正しくありません」より、「PRのURLが間違っています」の方がエラーが表示される理由が明確に伝わると考え変更せずそのままにしてあります。

2023-11-07 02:55 UTC, rira100000000 reviewed
修正ありがとうございます。
再度コメントさせていただきました。

コードへのコメントとは別なのですが、FBCの提出物にbootcampへのPRのURLが送りたい場合というものがあるようです。
[開発に参加して PR を送りマージする](https://bootcamp.fjord.jp/practices/140)と[システム開発おかわり](https://bootcamp.fjord.jp/practices/233)の提出物では自分のPRのURLを書く必要があります。

また、[こちらの提出物](https://bootcamp.fjord.jp/products/13007#comment_104130)では、課題中に見つけた問題に対してPRを送っています。
稀な状況ですが、コメント欄ではなく提出物中にPRのURLを書こうとした場合、PRのURLが間違っているというエラーが出てしまうのは混乱を生む気がします。

これらの状況を考えると、バリデーションで絶対に登録できなくするのではなく、"ブートキャンプあてのPRのURLが存在する場合、本当に正しいかチェックを促すメッセージを出す"程度にとどめた方が良いのではないかと思いました。
バリデーションで解決する場合、チーム開発プラクティスではバリデーションを無効にするような仕組みが必要だと思います。

そもそもの話になってしまって申し訳ないのですが、これらの実装方針については先に
@komagata さんにも意見を伺った方が良いかと思います。

2023-11-07 02:55 UTC, rira100000000 commented on app/decorators/product_decorator.rb
> +    "中のPRのURLが間違っています。#{link_to '提出物のPRのやり方 - YouTube', 'https://www.youtube.com/watch?v=XMgLL4qIyEA'}を確認してPRを作り直してください"
改行を追加して、句点の有無を統一すると見た目が良くなりそうです。

```suggestion
"中のPRのURLが間違っています。<br> #{link_to '提出物のPRのやり方 - YouTube', 'https://www.youtube.com/watch?v=XMgLL4qIyEA'}を確認してPRを作り直してください。"
```
### before
![image](https://github.com/fjordllc/bootcamp/assets/99132547/00ee8ee1-d235-4ebe-9add-cc2c1a5262a6)

### after
![image](https://github.com/fjordllc/bootcamp/assets/99132547/9fa3809f-1f81-4ea7-988d-b52e47cfbbac)

2023-11-08 06:53 UTC, eatplaynap commented
@rira100000000 
丁寧なレビューありがとうございます！とても助かりました。

> コードへのコメントとは別なのですが、FBCの提出物にbootcampへのPRのURLが送りたい場合というものがあるようです。
[開発に参加して PR を送りマージする](https://bootcamp.fjord.jp/practices/140)と[システム開発おかわり](https://bootcamp.fjord.jp/practices/233)の提出物では自分のPRのURLを書く必要があります。

> また、[こちらの提出物](https://bootcamp.fjord.jp/products/13007#comment_104130)では、課題中に見つけた問題に対してPRを送っています。
稀な状況ですが、コメント欄ではなく提出物中にPRのURLを書こうとした場合、PRのURLが間違っているというエラーが出てしまうのは混乱を生む気がします。

こちらは認識していませんでしたが、おっしゃるとおりだと思いました。データ見つけてくださってありがとうございます🙇
やり直すにしても仕様から考え直す必要があるため、一旦こちらのPRはcloseさせてください。

改めて、お忙しい中多くの的確なご指摘大変ありがとうございました🙏

2023-11-08 06:53 UTC, closed without merging

2023-11-09 23:55 UTC, komagata commented
@rira100000000 @eatplaynap バリデーションじゃなくて、注意文をただ出すとかでもいいかもですね〜。