Vuex関連のコンポーネントのreactへの置き換え
fjordllc/bootcamp pull request #7216
Opened 2024-01-19 14:03 UTC by dowdiness

## Issue

これはコメントに関するIssueのPRですが、結果的に他のIssueの内容も含んでいます。

- https://github.com/fjordllc/bootcamp/issues/5122
- https://github.com/fjordllc/bootcamp/issues/5119

## 概要

mainブランチではなく作業用のトピックブランチに向けてPRを作るべき内容ですが確認のために作りました。
Vuex関連のコンポーネント（CheckとWatch）をzustandを使ってreactへと書き換えています。

動かなくなる部分があるので、このPRはmainではなく作業用のブランチを作ってそちらにマージしています。

現在はコメントしたときにwatchする機能と確認OKしながらコメントする機能が、リロードしないと反映されない状態になっています。そのためにコメント関連のテストが落ちるようになっていますが、これはコメント関連の変更を取り入れた次のPRで直る予定です。

## 変更確認方法

このブランチを取り込み`bin/setup`した後に、日報ページと提出物ページを確認してください。

## Screenshot

<img width="1064" alt="shapes at 23-11-29 07 25 11" src="https://github.com/fjordllc/bootcamp/assets/1616717/ea92de3e-1732-46b3-aba3-367d37b872b0">

丸で囲った部分がreactへと置き換えられています

2024-01-20 06:54 UTC, junohm410 commented
@dowdiness 
初めまして！レビューの件承知いたしました👍
本日より他タスクより優先で取り組みますが、既存の実装にまず明るくないため、どうしてもちょっとお時間をもらってしまうかもしれないことをお許しください🙇‍♂️
遅くても水曜日くらいまでにお返事できるように目指します。
（厳しければ大変申し訳ないのですが他の方にご相談いただけると幸いです🙏）

また通話・ペアプロのことも承知しました！大変ありがたいです🙏
コードを拝読させていただき、必要だと感じたらDiscordの分報でご連絡させてもらいます🙇‍♂️
どうぞよろしくお願いいたします。

2024-01-21 08:44 UTC, junohm410 reviewed
お疲れ様です。本日、想定より時間が取れましたので確認させていただきました🙏
細かなコメントのおかげで、`zustand`による状態管理処理の流れをとても把握しやすかったです🙏ありがとうございました🙇‍♂️

気になりました点・質問をコメントさせていただきましたので、お手隙の際にご確認いただけますと幸いです。
よろしくお願いいたします。

2024-01-21 08:44 UTC, junohm410 commented on app/javascript/components/Check/Check.jsx
> +          />
現在の仕様では、「確認済み」の提出物は担当ボタンが表示されないようになっています。
しかし、本PRのブランチでは「確認済み」のものも担当ボタンが押せるようになっていました。
おそらくこの辺りで条件分岐させる必要があるかなと感じましたが、いかがでしょうか？

- `main`のスクショ（確認済みの提出物、担当ボタンが表示されない）
![image](https://github.com/fjordllc/bootcamp/assets/128765400/63cf6253-0fa7-44c6-8627-9bd6361d9b47)

- 本PRのブランチのスクショ
![Pasted Graphic](https://github.com/fjordllc/bootcamp/assets/128765400/c0e4ca09-f136-4914-a45d-272232809542)

2024-01-23 14:27 UTC, dowdiness commented on app/javascript/components/Check/useCheck.jsx
> +    (state) => [state.checkable, state.setCheckable]
最初は`watchId`が更新されたときに再レンダリングして欲しいなと思って`useShallow`をしてた記憶があるんですが、見直してみたら別に再レンダリングは必要なさそうですね。
思い違いだったと思うので`useShallow`を使うように書き直します。

2024-01-23 15:11 UTC, dowdiness commented on app/javascript/hooks/useZustandStore.js
> +export { zustandStore, useZustandStore }
この`zustandStore`はVue側で使うためにexportしていて、最初はこれの更新関数をVuex内で実行してVue側からReactのコンポーネントを再レンダリングさせるようなコードを書いていました。
それによってVueの状態とReactの状態を連動させてたんですが、色々と整理しているうちにこのPR内では必要なくなって抜けてしまいました。
一応次のコメント関連のPRで使う可能性があるのと、もしくは必要がないことが分かれば消してしまおうと思っているので、今のところは見逃してくれると嬉しいです。🙇‍♂️

2024-01-23 15:22 UTC, dowdiness commented on app/javascript/components/Check/Check.jsx
> +  const message = '今日の気分は「sad」ですが、コメント無しで確認しますか？'
この変数自体は短いスコープの中の使い捨て変数なのである程度名前が雑でもそんなに問題はないとは思います。
ただ確かに見直してみるともっと分かりやすくは出来るなと感じたので、実際に使用される関数内に変数を置くことでさらにスコープを短くして分かりやすい名前を付けるように変更しました。

2024-01-23 15:42 UTC, dowdiness commented on app/javascript/components/Check/Check.jsx
> +          />
この違いは見逃していました。ご指摘ありがとうございます！

担当と確認の間に関係がある事自体よく分かってませんでした。
おそらく担当する＝確認を担当するという意味なので、誰かが一度確認してしまえば担当する機能はいらなくなるんでしょうね。

元の挙動は変えないほうが良さそうなので、元の実装と同じように（HTMLの構造は若干変えましたが）`display: none;`を付けて見えなくなるようにしました。

提出物における担当と確認の役割や関係などについて決まっていることの説明や資料の存在を自分は見たことが無いので、もし現在の仕様があるなら参考にしたいですね。

2024-01-24 15:08 UTC, junohm410 commented on app/javascript/hooks/useZustandStore.js
> +export { zustandStore, useZustandStore }
背景承知しました！ご回答ありがとうございます🙏

2024-01-24 15:12 UTC, junohm410 commented on app/javascript/components/Check/Check.jsx
> +          />
> おそらく担当する＝確認を担当するという意味なので、誰かが一度確認してしまえば担当する機能はいらなくなるんでしょうね。

そうですね、現在の仕様の確認 + まさにそのような推測のもとに、念の為コメントさせていただいた次第でした🙏
そしてこれについての説明などは私もみたことがないですね……👀

> 元の挙動は変えないほうが良さそうなので、元の実装と同じように（HTMLの構造は若干変えましたが）display: none;を付けて見えなくなるようにしました。

ありがとうございます！ローカルで、確認済みの提出物に担当ボタンが表示されていないことを確認いたしました👍

2024-01-24 15:17 UTC, junohm410 requested changes
ご対応いただきありがとうございました🙏
zustandやReactだけでなく、わかりやすいコミットの積み方やコメントなど、大変勉強になりました🙏
私の方からはApproveとさせていただきます。

2024-01-24 15:18 UTC, junohm410 approved these changes

2024-01-24 15:20 UTC, junohm410 commented
@dowdiness 
すみません、不注意でapproveするつもりがrequest changeを押してしまいました🙇‍♂️大変申し訳ありませんでした。
改めてApproveさせていただきました🙇‍♂️

2024-01-25 11:16 UTC, dowdiness commented on app/javascript/components/Check/Check.jsx
> +          />
ミーティングでこの辺りの機能の質問をしましたが、確認するまでに時間が掛かる場合があるので先に担当者を決めたくてある機能とのことでした。なので確認が終わったら担当者の情報は要らなくなるみたいです。
推測通りの仕様でした👍

2024-01-25 11:19 UTC, dowdiness commented
@junohm410 

Approveありがとうございます！
私もコードレビューによって一人では気付けていなかった間違いに気付けたのでとても助かりました🙏

@komagata

レビューを受けたので確認よろしくお願いします。
この後、このPRのマージ先に対してCommentのPRを作り、その際に落ちているテストも通るようにしたいと思います。

2024-01-26 00:40 UTC, komagata commented
@dowdiness 

> この後、このPRのマージ先に対してCommentのPRを作り、その際に落ちているテストも通るようにしたいと思います。

ええと、どういう状況でしょうか。
テストが落ちている状態でレビュー依頼する理由はどういったものになりますでしょうか。

2024-01-30 21:50 UTC, dowdiness commented
@komagata 

このPRは、元々取り組んでいるComment ComponentのIssueで画面内の他のVueコンポーネントを更新するためにVuexを使用している部分がそのままだとReactに移行しづらいので、先にCommentと関連しているVuexを使っている部分をReactに書き換えたいなと思って作っています。

そのため途中でCommentと関連している部分で一時的に動かなくなる機能が出てきてしまうので、完全に動くようになるまで避難させるためにmainではなく移行用のブランチに対してPRをしています。Commentの変更がmergeされると今回落ちているテストも動くようになります。（質問タイムで相談したときに動かなく部分が出るんでmainではなく作業用のブランチ作ってそっちにmergeしますねみたいな話をしてたんですが、結構前の話になってしまいました）

すいません。説明するのが難しくて中々書けなくて返信遅くなってしまいました。

2024-01-31 14:28 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2024-01-31 14:28 UTC, merged

2024-02-01 08:44 UTC, dowdiness commented
@komagata 
ありがとうございます！