企業一覧ページから各企業のアドバイザー・現役生のページへ飛べるようにした
fjordllc/bootcamp pull request #7479
Opened 2024-03-01 12:28 UTC by mousu-a

## Issue

- Issue番号
 #7473
## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2024-03-01 12:54 UTC, mousu-a commented
@komagata 
質問させていただきたいです🙏
今回企業一覧ページに各企業のアドバイザー・現役生へのリンクを追加したのですが、
企業一覧ページと企業のshowページは共通のパーシャルを使っているため、企業のshowページにもアドバイザー・現役生へのリンクが追加されてしまっています。（だからといって問題があるわけではありません）
これは大丈夫でしょうか？
<img width="425" alt="スクリーンショット_2024-03-01_21_49_38" src="https://github.com/fjordllc/bootcamp/assets/112623765/be92db45-57e4-494c-ae9d-583ddee41436">
<img width="541" alt="スクリーンショット_2024-03-01_21_50_16" src="https://github.com/fjordllc/bootcamp/assets/112623765/46a45ebc-b5b4-4f67-8d4e-5797110de2b9">

2024-03-04 23:49 UTC, mousu-a commented
ありがとうございます！🙏

2024-03-04 23:51 UTC, mousu-a commented
@machida 
お疲れ様です！
こちら少ないですがデザインをお願いします。🙏

2024-03-08 09:03 UTC, mousu-a commented
@machida 
お疲れ様です🙏
こちら少ないですがデザインをお願いします🙇‍♂️

申し訳ありません、Assignを忘れていました🙇‍♂️

2024-03-08 09:08 UTC, mousu-a commented
### 変更点
app/views/companies/_user_counts.html.slimに下記コードを追加しています。
```ruby
= link_to_company_users_path(company, 'adviser')

...

= link_to_company_users_path(company, 'student_and_trainee')
```
メソッドの内部でlink_toを使ってaタグを作成しています。

2024-03-09 17:37 UTC, komagata commented
@mousu-a 追加コードについては差分（Files changed）でわかるので書かなくて大丈夫ですよ〜（基本的にFiles changedを提出側もレビュー側も必ず見るので）

https://github.com/fjordllc/bootcamp/pull/7479/files

2024-03-12 05:50 UTC, machida commented
@mousu-a お待たせしましたーこれからデザインを弄ります。

2024-03-12 07:13 UTC, machida commented
@mousu-a 

イメージと違ったのでデザインを修正しました。
カウントが 0 ではないときは、以下で示した部分がリンクになるようにしてあります。

<img width="544" alt="貼り付けた画像_2024_03_12_16_05" src="https://github.com/fjordllc/bootcamp/assets/168265/f2dc468c-2108-4b5a-bc6c-aca91a057ebd">

ここで、追加でお願いがあります。

現在、管理者が0ではない企業のとき、管理者をクリックすると、その企業の管理者ユーザーの一覧に遷移したいです。

<img width="544" alt="貼り付けた画像_2024_03_12_16_05" src="https://github.com/fjordllc/bootcamp/assets/168265/84f76571-f25e-433a-8b2d-ae793d43d28f">

ところが、今は `users?target=admin`にアクセスすると、その企業の管理者ユーザーの一覧ではなく、現役生が表示されてしまいます。

他にも表示がおかしいところがあります。以下のキャプチャを参照してください。

<img width="1572" alt="貼り付けた画像_2024_03_12_16_09" src="https://github.com/fjordllc/bootcamp/assets/168265/7292643e-a8af-4862-9fc7-643e66a17b98">

管理者の数字をクリックしたら、

<img width="535" alt="貼り付けた画像_2024_03_12_16_12" src="https://github.com/fjordllc/bootcamp/assets/168265/bae9e365-6293-4707-914c-6ab4ff065b4a">

その企業に所属する管理者の一覧が表示されるようにしてください。

2024-03-12 07:14 UTC, machida commented
@mousu-a ポイントを増やしました。

2024-03-14 12:54 UTC, mousu-a commented
@unikounio 

お疲れ様です！こちらのレビューをお願いできないでしょうか🙏
全く急ぎではないです！
お忙しければ遠慮なくおっしゃってください🙇‍♂️

2024-03-15 02:50 UTC, unikounio commented
@mousu-a さん
review requestをお願いします🙏

2024-03-15 07:09 UTC, mousu-a commented
すみません！すっかり忘れていました😭🙏

2024-03-17 07:26 UTC, unikounio requested changes
お疲れ様です！
1点だけ気になった点があったのでコメントさせていただきました。
よろしくお願いいたします🙏

2024-03-17 07:26 UTC, unikounio commented on app/views/companies/_user_counts.html.slim
> +            = users.unretired.advisers.size
このelse節は0を表示することになると思うので、直接書いた方が効率が良いのかなと思いました。
```suggestion
            = 0
```
併せてヘルパーメソッドを定義するとDRYに書けそうです。

2024-03-17 09:59 UTC, mousu-a commented on app/views/companies/_user_counts.html.slim
> +            = users.unretired.advisers.size
@unikounio 

レビューありがとうございます！
こちらは多分machidaさんが修正したものになるので判断が難しいんですよね〜
何かしら意図はありそうです。

ちょっと対応を考えます！

2024-03-18 01:32 UTC, mousu-a commented
@unikounio

お待たせいたしました🙇‍♂️
返信になります！
> 併せてヘルパーメソッドを定義するとDRYに書けそうです。

こちらに関しては前述の通りです🙏

> このelse節は0を表示することになると思うので、直接書いた方がDBアクセスがない分効率が良いのかなと思いました。

ご指摘いただいた箇所を日本語に直してみました！
```
users.unretired.advisersがあれば
	users.unretired.advisers.sizeをリンクにする
なければ
	users.unretired.advisers.sizeを表示する


users.unretired.advisersがあれば
	users.unretired.advisers.sizeをリンクにする
なければ
	0を表示する
```
前者はコンテキストが統一されていて「リンクにするかしないか」だけを判断すれば良さそうです。
後者はいきなり0が出てきたので「ん？なんで0？」と多少引っかかる感じがします（ニュアンスで申し訳ないです🙏）

「0を表示する」というのは、実装について多少なりとも把握していないと出てこない発想な気がします。🤔
なのでここで「0」がいきなり出てくると、前述したようにマジックナンバーとなってしまいそうです。👀
（理解するために多少コードを読まなければいけなくなりそう）

ですが反面、正直すぐに分かるようなことである気もしていますが...🤔

なので「最終的な判断はkomagataさんにお伺いする」形でも良いでしょうか？
宜しければapprove頂ければと思います🙇‍♂️

あとこれは私情なのですが、これらの自分の意見に関してunikounioさんの見解も伺えたらなと思っています🙇‍♂️

2024-03-18 04:36 UTC, unikounio commented
@mousu-a さん
丁寧にご説明いただきありがとうございます🙏✨

0がマジックナンバー化してしまう可能性についてのご指摘、なるほどです。
マジックナンバーに対しては定数やメソッドを用いて対策ができると思います。
しかし、これらの対策にもデメリットがあります。
私としては、後学のためにも、ヘルパーメソッドの件も含めて町田さんのご意見をお伺いした上で進められるとよいのかなと思っています。いかがでしょうか？
（もしお忙しいようであれば私から町田さんに連絡させていただきますのでおっしゃっていただけますと💡）

2024-03-18 06:45 UTC, mousu-a commented
@unikounio 
> マジックナンバーに対しては定数やメソッドを用いて対策ができると思います。

なるほどです、こちらに関しては全く頭にありませんでした😅

>  私としては、後学のためにも、ヘルパーメソッドの件も含めて町田さんのご意見をお伺いした上で進められるとよいのかなと思っています。いかがでしょうか？
（もしお忙しいようであれば私から町田さんに連絡させていただきますのでおっしゃっていただけますと💡）

すみません、ご連絡の方お願い出来ますでしょうか😭🙏

2024-03-18 07:28 UTC, unikounio commented
@machida さん
お疲れ様です！
本PRで町田さんが書かれたコードについてお伺いさせてください🙏

私がレビューする中で、町田さんが変更された部分に次のようにコメントさせていただきました。 → https://github.com/fjordllc/bootcamp/pull/7479#discussion_r1527431475
このコメントにおける提案と、ヘルパーメソッドの活用に関する部分について、町田さんのご意見をお伺いさせていただけますと幸いです🙏

2024-03-18 07:57 UTC, machida commented on app/views/companies/_user_counts.html.slim
> +            = users.unretired.advisers.size
@mousu-a おおー、すいません、その部分ヘルパーを戻して書き直しお願いしたいです🙏

2024-03-18 09:08 UTC, mousu-a commented
@machida 
ご確認ありがとうございますー！

@unikounio 

ご連絡までありがとうございます！🙏
確認していただいてよかったですー！
修正に入りますので今しばらくお待ちください🙇‍♂️

2024-03-22 14:33 UTC, mousu-a commented
@unikounio 

お待たせいたしましたー！🙏
ヘルパーメソッドを再導入しDRYにしました。
サイドレビューをお願いいたします🙇‍♂️

> 0がマジックナンバー化してしまう可能性についてのご指摘、なるほどです。
マジックナンバーに対しては定数やメソッドを用いて対策ができると思います。
しかし、これらの対策にもデメリットがあります。

こちらに関してはkomagataさんにお聞きしようと考えていますがどうでしょうか？

2024-03-24 10:16 UTC, unikounio requested changes
ご対応ありがとうございます！
ヘルパーメソッドについて１点コメントさせていただいたので、お手数ですがそちらの確認もお願いします🙏
> こちらに関してはkomagataさんにお聞きしようと考えていますがどうでしょうか？

ご提案いただいた形で進めていただければと思います！

2024-03-24 10:16 UTC, unikounio commented on app/helpers/companies_helper.rb
> +    link_to company.users.unretired.send(target).size, company_users_path(target: target.singularize, company_id: company.id),
`send`メソッドが使われているので、今後のことも考えると安全性確保のための対策が必要かなと思いました🤔
今回のケースならば、allowlistでチェックをいれるのはいかがでしょうか？

2024-03-25 11:46 UTC, mousu-a commented
@unikounio 

レビューありがとうございますー！
修正いたしましたので再レビューをお願いいたします🙏

2024-03-26 06:54 UTC, unikounio approved these changes
@mousu-a さん
ご対応ありがとうございます！	
より良い形にしていただいたと思いますので、私からはApproveとさせていただきます～

2024-03-26 07:46 UTC, mousu-a commented
@komagata 

メンバーからApproveをいただけましたのでこちらレビューをお願いいたします🙏

一点質問があります🙏

```ruby
    # app/views/companies/_user_counts.html.slim

	  - if users.unretired.advisers.present?
            = link_to_company_users_path(company, target: 'advisers')
          - else
            = users.unretired.advisers.size
```
こちらのコードですが、`if users.unretired.advisers.present?`がfalseの時は0なのが確定しているため、else節は0でいいのではないか？（わざわざ`users.unretired.advisers.size`とする必要はなさそう）ということについて議論しています。
komagataさんのご意見を伺いたいです🙏

こちらのやりとりを参照していただけますとわかりやすいと思います。
https://github.com/fjordllc/bootcamp/pull/7479#discussion_r1527431475
https://github.com/fjordllc/bootcamp/pull/7479#issuecomment-2002721906
https://github.com/fjordllc/bootcamp/pull/7479#discussion_r1528017146
https://github.com/fjordllc/bootcamp/pull/7479#issuecomment-2015235946

2024-04-07 18:09 UTC, komagata commented
@mousu-a 

`0`でいいと思います。またlink_to_ifとかつかったらスマートになるかもと思いました。`

2024-04-11 05:22 UTC, mousu-a commented
@komagata 

すみません、このプルリクにmainブランチの他の人のコミットが混ざってしまっているため今後の対応をお伺いしたいです🙇‍♂️

## 現状の報告
* 現状どうなっているのか？
    * mainブランチのコミット内容がプルリクに混ざってしまっている
    * mainブランチとのコンフリクトが発生している
* ログに怪しい記述はないか？
    * 見てみましたが怪しいログはなさそうでした。。下にログを記述します。
* 推測
    * komagataさん, unioさんにレビューいただいた時にはこの状態にはなっていなかったと思います。

### ログ
以下`git reflog`のログになります。
```
512a88eb7 (HEAD -> feature/Add-link-to-target-users-for-company-on-companies-page, origin/feature/Add-link-to-target-users-for-company-on-companies-page) HEAD@{0}: checkout: moving from feature/introduce-of-link-card to feature/Add-link-to-target-users-for-company-on-companies-page
bc84ed752 (feature/introduce-of-link-card) HEAD@{1}: checkout: moving from feature/Add-link-to-target-users-for-company-on-companies-page to feature/introduce-of-link-card
512a88eb7 (HEAD -> feature/Add-link-to-target-users-for-company-on-companies-page, origin/feature/Add-link-to-target-users-for-company-on-companies-page) HEAD@{2}: pull --rebase origin main (finish): returning to refs/heads/feature/Add-link-to-target-users-for-company-on-companies-page
512a88eb7 (HEAD -> feature/Add-link-to-target-users-for-company-on-companies-page, origin/feature/Add-link-to-target-users-for-company-on-companies-page) HEAD@{3}: pull --rebase origin main (pick): ローカル変数target_allowlistを導入、sendメソッドを実行する前にチェックを入れるようにした
d082e26bf HEAD@{4}: pull --rebase origin main (pick): if文が二重になっていたため削除
7d94d94eb HEAD@{5}: pull --rebase origin main (pick): ヘルパーメソッドを再導入し企業の各usersへのリンクの呼び出しをDRYに
4e28b6332 HEAD@{6}: pull --rebase origin main (pick): 企業の管理者ユーザー一覧を表示できるようにした。同じく企業一覧ページからも飛べるようにした。
4a136410f HEAD@{7}: pull --rebase origin main (pick): 企業ユーザーのカウント部分にリンクを設定。ユーザーroleの絞り込みに管理者を追加。
e9fbf733f HEAD@{8}: pull --rebase origin main (pick): 余計な空白を削除
35aa789e4 HEAD@{9}: pull --rebase origin main (pick): 企業一覧ページから各企業のアドバイザー・現役生のページへ飛べるようにした
79643285f HEAD@{10}: pull --rebase origin main (start): checkout 79643285fe6c4776488178d39eb022f9065525a1
85a590064 HEAD@{11}: commit: ローカル変数target_allowlistを導入、sendメソッドを
実行する前にチェックを入れるようにした
df820b6e1 HEAD@{12}: checkout: moving from feature/introduce-of-link-card to feature/Add-link-to-target-users-for-company-on-companies-page
bc84ed752 (feature/introduce-of-link-card) HEAD@{13}: reset: moving to HEAD
bc84ed752 (feature/introduce-of-link-card) HEAD@{14}: checkout: moving from feature/Add-link-to-target-users-for-company-on-companies-page to feature/introduce-of-link-card
df820b6e1 HEAD@{15}: pull --rebase origin main (finish): returning to refs/heads/feature/Add-link-to-target-users-for-company-on-companies-page
df820b6e1 HEAD@{16}: pull --rebase origin main (pick): if文が二重になっていたた
め削除
42b7b74d5 HEAD@{17}: pull --rebase origin main (pick): ヘルパーメソッドを再導入
し企業の各usersへのリンクの呼び出しをDRYに
2d14f4842 HEAD@{18}: pull --rebase origin main (pick): 企業の管理者ユーザー一覧
を表示できるようにした。同じく企業一覧ページからも飛べるようにした。
d1c0a5618 HEAD@{19}: pull --rebase origin main (pick): 企業ユーザーのカウント部
分にリンクを設定。ユーザーroleの絞り込みに管理者を追加。
13905a283 HEAD@{20}: pull --rebase origin main (pick): 余計な空白を削除
4a72ac083 HEAD@{21}: pull --rebase origin main (pick): 企業一覧ページから各企業
のアドバイザー・現役生のページへ飛べるようにした
258e32fb5 (main) HEAD@{22}: pull --rebase origin main (start): checkout 258e32fb51cb18056b0385fa68f27d7234749694
4c93c79a0 HEAD@{23}: checkout: moving from main to feature/Add-link-to-target-users-for-company-on-companies-page
258e32fb5 (main) HEAD@{24}: pull origin main: Fast-forward
2787cf4ad HEAD@{25}: checkout: moving from feature/introduce-of-link-card to main
```

2024-04-11 05:33 UTC, komagata commented
@mousu-a 日常的にやる作業になりますが、mainの最新をローカルに取り込んでrebaseしてください～

2024-04-11 05:35 UTC, mousu-a commented
@komagata 
ありがとうございます🙇‍♂️
帰宅後試してみます〜！

2024-04-11 13:22 UTC, mousu-a commented
ありがとうございました😭解決しました！

2024-04-13 04:32 UTC, mousu-a commented
@komagata 
修正いたしましたので再度レビューをお願いいたします🙏

2024-04-24 02:18 UTC, komagata reviewed
conflictの修正をお願い致します～。

2024-05-24 12:46 UTC, mousu-a commented
@komagata 
こちらコンフリクトを修正しましたので再度レビューをお願いいたします🙇‍♂️

2024-05-28 20:05 UTC, komagata commented
@mousu-a すみません、もういちどconflictの修正をお願い致します～。

2024-05-29 03:48 UTC, mousu-a commented
@komagata 
すみません！解消できましたので再びチェックをお願いいたします🙇‍♂️

2024-05-29 07:22 UTC, komagata commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
メソッドを作る場合は最低一つは対応するテストが欲しい感じです～

2024-06-02 23:52 UTC, mousu-a commented
## 問題点
link_to_ifでは`true`であっても`false`であっても`send(メソッド)`が実行されてしまうため`send(メソッド)`の安全対策が機能していない

## 現状
```ruby
# 現在のコード
def link_to_company_users_path(company, target:)
    target_allowlist = %w[advisers students_and_trainees admins mentor]
    link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link')
  end
```
`target_allowlist`の中に`target`があればリンクを生成して返すというメソッドです。

link_to_ifはkomagataさんにご提案いただいたものを採用させていただいたのですが、この場合if(link_to_if)に失敗しても成功しても`send(メソッド)`を実行してしまうため、sendの安全対策としての意味がなくなってしまうことに気づきました。
（`link_to_if`は`false`の時、"表示する文字"を返すようです。（この場合`company.users.unretired.send(target).size`）
つまりif失敗時にも`company.users.unretired.send(target).size`が実行されてしまいます。

link_to_ifにブロックを与えてnilをreturnすることもできますが、それだと可読性が悪くなりそうです。
```ruby
 link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link') { return nil }
```


なのでこの場合はlink_to_ifで2つの処理を一息に行うより、ガード文とlink_toに分けた方がシンプルで可読性が良さそうなのですがどうでしょうか。

```ruby

```
# link_to_if　ブロックでnilをreturnする
 link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link') { return nil }
```ruby
# ガード文＋link_to
    return unless target_allowlist.include?(target)

    link_to company.users.unretired.send(target).size, company_users_path(target: target.singularize, company_id: company.id),
            class: 'card-counts__item-value-link'
```

2024-06-03 02:28 UTC, mousu-a commented
> @mousu-a
> 
> またlink_to_ifとかつかったらスマートになるかもと思いました。

@komagata 
こちらに関してのコードでご意見を伺いたいです🙇‍♂️
## 現状説明
```ruby
# 現在のコード
def link_to_company_users_path(company, target:)
    target_allowlist = %w[advisers students_and_trainees admins mentor]
    link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link')
  end
```
`target_allowlist`の中に`target`があればリンクを生成して返すというメソッドです。sendメソッドを使っているため安全対策として`link_to_if target_allowlist.include?(target)`という形にしています。

## 問題点
`link_to_if`メソッドは`true`であっても`false`であってもこの場合`send()`が実行されてしまうため`send()`の安全対策として機能していない


`link_to_if`はkomagataさんにご提案いただいたものを採用させていただいたのですが、この場合if(link_to_if)に失敗しても成功しても`send()`を実行してしまうため、`send()`の安全対策としての意味がなくなってしまうことに気づきました。
（`link_to_if`は`false`の時、"表示する文字"を返すようです。（この場合`company.users.unretired.send(target).size`）
つまりif失敗時にも`company.users.unretired.send(target).size`が実行されてしまいます。）

`link_to_if`にブロックを与えて`nil`を`return`することもできますが、それだと可読性が悪くなりそうです。
```ruby
 link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link') { return nil }
```

## 提案
なのでこの場合は`link_to_if`で2つの処理を一息に行うより、ガード文と`link_to`に分ける（前の状態に戻す）方がシンプルで可読性が良さそうなのですがどうでしょうか。

```ruby
# link_to_if　ブロックでnilをreturnする
 link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link') { return nil }
```

```ruby
# ガード文＋link_to
    return unless target_allowlist.include?(target)

    link_to company.users.unretired.send(target).size, company_users_path(target: target.singularize, company_id: company.id),
            class: 'card-counts__item-value-link'
```

2024-06-03 02:29 UTC, mousu-a commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
> @mousu-a
> 
> またlink_to_ifとかつかったらスマートになるかもと思いました。


こちらに関してのコードでご意見を伺いたいです🙇‍♂️
## 現状説明
```ruby
# 現在のコード
def link_to_company_users_path(company, target:)
    target_allowlist = %w[advisers students_and_trainees admins mentor]
    link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link')
  end
```
`target_allowlist`の中に`target`があればリンクを生成して返すというメソッドです。sendメソッドを使っているため安全対策として`link_to_if target_allowlist.include?(target)`という形にしています。

## 問題点
`link_to_if`メソッドは`true`であっても`false`であってもこの場合`send()`が実行されてしまうため`send()`の安全対策として機能していない


`link_to_if`はkomagataさんにご提案いただいたものを採用させていただいたのですが、この場合if(link_to_if)に失敗しても成功しても`send()`を実行してしまうため、`send()`の安全対策としての意味がなくなってしまうことに気づきました。
（`link_to_if`は`false`の時、"表示する文字"を返すようです。（この場合`company.users.unretired.send(target).size`）
つまりif失敗時にも`company.users.unretired.send(target).size`が実行されてしまいます。）

`link_to_if`にブロックを与えて`nil`を`return`することもできますが、それだと可読性が悪くなりそうです。
```ruby
 link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link') { return nil }
```

## 提案
なのでこの場合は`link_to_if`で2つの処理を一息に行うより、ガード文と`link_to`に分ける（前の状態に戻す）方がシンプルで可読性が良さそうなのですがどうでしょうか。

```ruby
# link_to_if　ブロックでnilをreturnする
 link_to_if(target_allowlist.include?(target),
               company.users.unretired.send(target).size,
               company_users_path(target: target.singularize, company_id: company.id),
               class: 'card-counts__item-value-link') { return nil }
```

```ruby
# ガード文＋link_to
    return unless target_allowlist.include?(target)

    link_to company.users.unretired.send(target).size, company_users_path(target: target.singularize, company_id: company.id),
            class: 'card-counts__item-value-link'
```

2024-06-16 03:58 UTC, mousu-a commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@komagata 
partialとして切り出してみました！

2024-06-18 13:14 UTC, komagata commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@mousu-a すみません、わかりづらかったですね。
partial化すべきという意味ではなく、メソッド化するほどの内容でもないかもなので（むしろメソッド化することによって余計に無駄な処理がふえているようにみえる）、link_to_ifをつかってそのままかいたらどうかといういみになります。

@mousu-a さんとの今までのやりとりで、意図が伝わらないまま、違った方向に @mousu-a さんが進み続けて、結果が出てから気づくということを何度か繰り返しているので、 @mousu-a さんの中で方針がきまったら、実際に実装したり、時間をたくさんつかって調べるまえに、どういう方向性に進もうとしているのか、まず確認した方がよいかもしれません。

このままいくと、プログラマーとして入社したときに同じことを繰り返してして、（@mouse-a さんが）大きく時間を無駄にしてしまうかもしれません。

2024-06-21 01:48 UTC, mousu-a commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@komagata 

> このままいくと、プログラマーとして入社したときに同じことを繰り返してして、（@mouse-A さんが）大きく時間を無駄にしてしまうかもしれません。

ご助言痛み入ります🙇‍♂️
これからは遠慮なく質問させていただきます！
早速ですが方針確認のためこちらのissueで質問させていただいています。
お手すきの際にご確認いただければと思います🙇‍♂️

修正致しましたのでこちらも再度ご確認をお願いいたします🙇‍♂️

2024-06-24 17:43 UTC, komagata commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@mousu-a 

> 早速ですが方針確認のためこちらのissueで質問させていただいています。

すみません、これはどこで質問されていますでしょうか？
URLをいただければありがたいです。

2024-06-24 20:33 UTC, mousu-a commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@komagata 
あっすみません、これはリンクカードissueの方で、すでにご返答いただいています！
> https://github.com/fjordllc/bootcamp/issues/7455#issuecomment-2179645094

失礼いたしました🙇‍♂️

2024-06-26 12:27 UTC, komagata commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@mousu-a 

> すみません、URLを載せ忘れてしまっていました。
> こちらはリンクカードissueの方の質問で、すでにご返答いただいています！

すみません、こちら・そちらなどの代名詞を使い続けられているので明確に何のことを言っているのかが理解しずらい感じです。

#7479 のPRについては現状、僕のアクションは必要無いという認識で良かったでしょうか？

2024-06-26 23:49 UTC, mousu-a commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@komagata 
申し訳ありません、抽象的なコメントでした。
MTGの際に「確認」という言葉を使ったのも紛らわしかったですね。

> https://github.com/fjordllc/bootcamp/pull/7479 のPRについては現状、僕のアクションは必要無いという認識で良かったでしょうか？

再レビューをお願いいたします🙇‍♂️

2024-07-02 23:41 UTC, komagata commented on app/helpers/companies_helper.rb
> +  def link_to_company_users_path(company, target:)
@mousu-a かしこまりました～

2024-07-02 23:43 UTC, komagata commented on app/views/companies/_company.html.slim
> +          = render 'user_counts', users: company.users, company: company
companyだけを渡せば、company.usersは渡す必要がないかもです。

2024-07-13 04:18 UTC, mousu-a commented on app/views/companies/_company.html.slim
> +          = render 'user_counts', users: company.users, company: company
ありがとうございます、修正しました！

2024-07-13 04:19 UTC, mousu-a commented
@komagata 
お疲れ様です。
再度レビューをお願い致します🙇

2024-07-15 16:06 UTC, komagata commented on app/views/companies/_user_counts.html.slim
> +            = link_to company.users.mentor.size,
すっきりしたと思います！

2024-07-15 16:06 UTC, komagata commented on app/views/companies/_profile.html.slim
> += render 'user_counts', users: company.users, company: company
これですと渡すのはcompanyだけでいいように思います。

2024-07-16 03:00 UTC, mousu-a commented on app/views/companies/_profile.html.slim
> += render 'user_counts', users: company.users, company: company
すみません、見逃してしまいました。
修正しました！

2024-07-16 03:00 UTC, mousu-a commented
@komagata 
修正致しましたのでお手すきの際に再レビューをお願い致します。

2024-07-16 09:42 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2024-07-16 09:42 UTC, merged

2024-07-17 04:21 UTC, mousu-a commented
https://www.daaaatch.tv/videos/2027637947?filter=all&sort=time