メンター or 管理者でログインしたときだけユーザー一覧の期生別(全員)ページに現役生、卒業生、退会者の人数を表示する
fjordllc/bootcamp pull request #7713
Opened 2024-04-19 02:10 UTC by a-terumoto-gs

## Issue

- https://github.com/fjordllc/bootcamp/issues/7364

## 概要
ユーザー一覧ページのうち、期生別ページの全員のページに、メンター or 管理者でログインしたときだけ、現役生、卒業生、退会者の人数を表示するようにしました

## 変更確認方法

1. `feature/display-count-of-category-users-on-generations-all-list`をローカルに取り込む
2. `foreman start -f Procfile.dev`でサーバーを立ち上げる。
3. `komagata`でログインし、[/generations?target=all](http://localhost:3000/generations?target=all)にアクセスする
4. 期生別（全員）のページに現役生・卒業生・退会者の人数が表示されていることを確認する
5. 期生別の他のページには現役生・卒業生・退会者の人数が表示がされていないことを確認する
6. `kimura`でログインしなおして、[/generations?target=all](http://localhost:3000/generations?target=all)にアクセスする
7. 期生別ページに現役生・卒業生・退会者の人数が表示がされていないことを確認する

## Screenshot

### 変更前
![image](https://github.com/fjordllc/bootcamp/assets/133624488/e0ac6050-4ef1-423e-a2b6-38a98c631b11)

### 変更後

2024-04-19 02:13 UTC, a-terumoto-gs commented
@machida 
おつかれさまです！
こちらのissueのデザインをお願いしたいです。

↓のPRでいれてもらったデザインをできるだけ引き継げるようにしたのですが、サイズや位置の調整がうまくいかなかったのでお願いしたいです。
https://github.com/fjordllc/bootcamp/pull/7489

このPRでの今のデザイン
![image](https://github.com/fjordllc/bootcamp/assets/133624488/fd4e4cb8-6e49-42b2-9eda-f7cc6b1e6b03)

前回入れてもらったデザイン
![image](https://github.com/fjordllc/bootcamp/assets/133624488/d13e9d42-bf92-44f5-99bb-7adaf1141449)

よろしくお願いいたします！

2024-04-19 02:14 UTC, machida commented
@a-terumoto-gs 了解ですー🙆

2024-05-01 02:31 UTC, machida commented
@a-terumoto-gs デザイン入れました。ちょっとお願いがあります。

今、同時進行で現役生と研修生を分けて表示するIssueを進めているのですが、このリポジトリも分けて表示をするようにしました。

さらに追加で、現役生から休会中の人数を引いていただき、休会中のユーザー数の表示も追加していただきたいです🙏

2024-05-01 02:50 UTC, a-terumoto-gs commented
@machida 
承知しました！

2024-05-02 11:42 UTC, a-terumoto-gs commented
@mousu-a 
お疲れ様です！
こちらのPRのレビューをお願いしてもよろしいでしょうか？
急ぎではありません！
よろしくお願いいたしますm(__)m

2024-05-04 13:00 UTC, mousu-a requested changes
レビューお待たせいたしました！
数点気になるところがありましたのでご対応をお願いします🙏

2024-05-07 09:41 UTC, a-terumoto-gs commented on app/views/generations/index.html.slim
> +                                | #{classmates.students.count - classmates.hibernated.count}
@mousu-a 
コメントありがとうございます！
提案をいただいた形を参考にさせていただいてメソッド化してみました。
同じターゲットを扱っているスコープは見つけることができなかったので、`target_to_classmates`で設定しています。

ご確認よろしくお願いいたしますm(__)m

2024-05-08 03:41 UTC, mousu-a commented on app/models/generation.rb
>    def count_classmates_by_target(target)
@a-kuroki-gs 
修正ありがとうございます😊
ちょっとお聞きしたいのですが、こちら`target`がシンボルではいけないのでしょうか？
シンボルでも良いのかなとは思ったのですが、あえて文字列にしている意味があればお聞きしたいです🙏

2024-05-09 11:59 UTC, a-terumoto-gs commented on app/models/generation.rb
>    def count_classmates_by_target(target)
@mousu-a 
あえて文字列にしている意味はなかったため、シンボルに変更しました。
パフォーマンスのことを考えられていない実装でしたm(__)m
ご指摘感謝です🙏

2024-05-09 12:58 UTC, mousu-a approved these changes
@a-terumoto-gs 
修正ありがとうございました😊
こちらからはApproveとさせていただきます！

2024-05-10 01:22 UTC, a-terumoto-gs commented
@mousu-a 
丁寧にレビューしていただきありがとうございました！

@komagata 
メンバーの方にapproveいただいたのでレビューお願いいたします！

2024-05-17 05:02 UTC, komagata commented on app/models/generation.rb
> +        retired: :retired
同じ内容が２回出てきているので、

`%i(trainees hibernated ........)`などでいいように思いました。
また、この内容も他に同じようなものを定義しているところが無いか確かめて共通化したいです。

タブがあるページで何か似たような処理をしているところがあるかもです。

2024-05-17 05:02 UTC, komagata commented on app/views/generations/index.html.slim
> +                      .user-group__counts.is-only-mentor
同じ処理が繰り返されているのでループで処理でそうです。

さらに、タブ自体をpartialやview_componentで共通化できるかもです。（view_componentだとベスト！）

2024-05-20 06:40 UTC, a-terumoto-gs commented on app/views/generations/index.html.slim
> +                      .user-group__counts.is-only-mentor
ループ処理をする形にしてpartialでくくりだしてみました

2024-05-20 06:43 UTC, a-terumoto-gs commented on app/models/generation.rb
> +        retired: :retired
「現役生 研修生 休会 卒業生 アドバイザー 退会者」で定義している箇所探したのですが、同じ定義の箇所はなかったので追加した次第です。
人数表示の箇所をループ処理に修正する過程ででスコープ定義の箇所を移動したのですが、
`target_to_scope = %i[students trainees hibernated graduated advisers retired]`の形に修正しました

2024-05-20 06:50 UTC, a-terumoto-gs commented
@komagata 
お疲れ様です
修正いたしました。お手すきの際にご確認よろしくお願いいたします。

2024-05-22 12:22 UTC, komagata approved these changes
確認させていただきました。OKです～👌

2024-05-22 12:23 UTC, komagata commented
@a-terumoto-gs 5/23のリリースは3週間分になるのでこちらのPRをマージをするのはそのあとにして、リリースされるのも次のリリースに入れたいと思います。

2024-05-22 12:29 UTC, komagata commented
@a-terumoto-gs 明日のリリースが三週間ぶりなのでこちらはそのあとにマージして、次回のリリースに含めさせていただければと思います。

2024-05-28 19:31 UTC, merged

2024-05-28 19:31 UTC, komagata commented
@a-terumoto-gs こちらmainにマージさせていただきました～