招待URL作成時に研修生を支払い方法別に選択可能にした・研修生の場合は会員登録時の支払い方法の指定を必須にした
fjordllc/bootcamp pull request #8013
Opened 2024-08-15 01:13 UTC by ham-cap

## Issue

- #7871 

## 概要
現在、管理者用メニューにはアドバイザー、研修生、メンター用の招待URL作成ページがあり、所属企業、ロール、受講するコースの三つを選択することでそれぞれに合った内容の会員登録ページへ飛ぶURLを作成することができます。
このPRにおいては、これまで一つだった研修生のロールを支払い方法別に三つに分割し、それぞれの支払い方法があらかじめ適応された会員登録ページが表示されるように変更しました。

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2024-08-15 06:15 UTC, ham-cap commented
@mousu-a 
お疲れ様です！
こちらのPRについてレビューをお願いできますでしょうか🙏
急ぎではありませんのでお手隙の際で結構です🙇‍♂️
よろしくお願いいたします！

2024-08-15 13:17 UTC, mousu-a commented
@ham-cap 
レビュー依頼ありがとうございます〜！
正直レビューにどれくらい掛かるかわかりませんがぜひ引き受けさせていただきます〜😄

わからないところがあれば質問させていただきます！その時はよろしくお願いいたします🙇‍♂️

2024-08-19 03:55 UTC, mousu-a requested changes
@ham-cap 

お疲れ様です！
レビューお待たせいたしました。
コミット時の説明が多く助かりました😊
見やすい様にコミット履歴が整理されているともっと良いかもです！(不要なコミット履歴をrebaseして省くなど)（レビュアー視点でコミット履歴を作ると良いのかなと思います）

いくつか気になる点をコメントさせていただいていますのでご確認ください🙇‍♂️
的外れなことを言っていたら申し訳ないですが適宜コメント頂けたらと思います〜🙏

2024-08-19 03:55 UTC, mousu-a commented on app/javascript/payment-methods-check-boxes.js
> +  const cardForm = document.getElementById('card')
こちらの変数名`CreditCardForm`ではどうでしょうか。
`cardForm`ではわかりにくいかもです🤔

2024-08-20 06:34 UTC, ham-cap commented on app/models/user.rb
> +    [I18n.t('invitation_role.trainee(invoice_payment)'), :trainee_invoice_payment],
こちらご提案に従って修正してみました！🙏

2024-08-20 07:05 UTC, ham-cap commented on app/javascript/payment-methods-check-boxes.js
> +    if (checkBox) {
引数`checkBoxes`の要素二つのうち少なくとも一つは必ず`null`になるためif文で存在確認をしているのですが、たしかにオプショナルチェーンを使用すれば`null`が含まれていることを許容できるようになるのでそのように修正いたしました🙌

2024-08-20 07:24 UTC, ham-cap commented on app/javascript/payment-methods-check-boxes.js
> +  const cardForm = document.getElementById('card')
たしかにちょっと分かりにくいですね👀
修正しました！

2024-08-21 08:22 UTC, ham-cap commented on app/controllers/users_controller.rb
> +    @user.credit_card_payment = params[:credit_card_payment] == '1'
72行目の`@user.payment_method_of_trainee = params[:user][:payment_method_of_trainee]`については、試行錯誤の痕跡が残ってしまっているだけですので、Userモデルの`attr_accessor`と併せて削除いたします🙏

73行目については`check_box_tag`にチェックが入っていた場合に送られてくる値`1`を真偽値に変換したうえで代入しているのですが、改めて確認したところ特に真偽値に変換せずとも動作には問題がないようなので、`== '1'`の部分を削除させていただきます。
`@user.credit_card_payment`自体はUserモデルの中でバリデーションをかける際の条件に使用しています。

2024-08-21 08:23 UTC, ham-cap commented on app/javascript/card.js
> +  if (!userRole || checkedCreditCardCheckBox) {
こちらはStripeのカード番号入力欄のマウントを、`/users/new`にパラメーターなしでアクセスした場合(`!userRole`がtrue)とページがレンダリングされた段階でクレジットカード払いにチェックが入っている場合(`checkedCreditCardCheckBox`がtrue)に限定するためのものです。
マウントするタイミングを限定せず、単純に`#card-element`にマウントするということでも機能としては動作するのですが、それだと招待URL作成ページの段階で請求書払いを選択しているとき等、`#card-element`の要素が見当たらない場合にブラウザのコンソールにエラーが出てしまいます。
これを回避するために場合分けをしてマウントすべきタイミングを明示しています。
なお、チェックボックスがselectableな場合はチェックの状態によって動的にマウントする必要があるため、この直下で`selectableCreditCardCheckBox`に対してイベントリスナーを登録することで対応しています。
また、この部分の`selectableCreditCardCheckBox`の存在確認のためのif文については別途ご指摘いただいているとおりオプショナルチェーンで実装するのがベターだと思いますのでそのように修正させていただきます🙏

2024-08-21 08:39 UTC, ham-cap commented on test/system/users_test.rb
> +    assert_equal 'FBCアドバイザー参加登録 | FJORD BOOT CAMP（フィヨルドブートキャンプ）', title
今回のissueで求められている要件に沿ってタイトル表記のバリエーションを4種類に増やしているので、アドバイザー・研修生・メンター・一般受講生それぞれの登録フォーム上で正しく表示されているかどうかの確認は必要だと思うのですがいかがでしょうか👀
むしろ今までもアドバイザーとそれ以外の場合で2種類存在していたタイトル表記を片方しかチェックしていなかったのが不備だったような気も個人的にはしています🤔

2024-08-21 10:46 UTC, ham-cap commented
@mousu-a 
ご指摘いただいた点について修正等いたしましたのでご確認くださいー🙏

2024-08-21 11:46 UTC, mousu-a commented on test/system/users_test.rb
> +    assert_equal 'FBCアドバイザー参加登録 | FJORD BOOT CAMP（フィヨルドブートキャンプ）', title
> むしろ今までもアドバイザーとそれ以外の場合で2種類存在していたタイトル表記を片方しかチェックしていなかったのが不備だったような気もしています🤔

そう言われればそうな気がしてきました🤔
一旦判断はkomagataさんにお任せしたいと思います🙇‍♂️

2024-08-23 01:23 UTC, mousu-a reviewed
@ham-cap 
お疲れ様です！
変更ありがとうございます🙇‍♂️コードとても良くなったと思います〜！

最後に気になるところを一点だけ発見いたしましたのでご確認をお願いいたします🙏

2024-08-23 01:23 UTC, mousu-a commented on app/models/user.rb
> +  validates :invoice_payment, inclusion: { in: [true], message: 'にチェックを入れてください。' }, if: -> { role == 'trainee_invoice_payment' }
すみません、このコードなのですが、 
```ruby
if role == 'trainee_invoice_payment' {
validation invoice_paymentはtrueでなければならない
  失敗したらmessageを表示
}
```
ということをやっているのだと思いますが、「trueかどうか」だけを検証するために`inclusion`を使うのは意図に合っていない気がします🤔

下記の様な形はどうでしょうか？
```ruby
  validate :custom_validation, if: -> { role == 'trainee_invoice_payment' }

  private

  def custom_validation
    return invoice_payment == true

    errors.add(:base, "エラーメッセージ")
  end
```
ただその場合`invoice_payment`の値をどうやって取得するのか、errorsにaddする形でメッセージを表示できるのか、などの問題は出てきそうです🤔

2024-09-01 02:20 UTC, ham-cap commented on app/models/user.rb
> +  validates :invoice_payment, inclusion: { in: [true], message: 'にチェックを入れてください。' }, if: -> { role == 'trainee_invoice_payment' }
@mousu-a 

こちらの件、個人的にはここで`inclusion`を使うことにそこまで違和感を覚えていないので、意図に合っていないと思われる理由についてもう少し詳しく教えていただけると嬉しいです🙏

自分なりの考えを先に書いておくと、今回のケースはカスタムバリデーションを使わなければならないほど複雑な処理を必要とするものではないと考えていて、むしろバリデーションの実行箇所とメソッドの定義場所が離れてしまうことによる可読性の低下のほうがデメリットとして大きく感じます。

また、`inclusion`の使い方について改めて確認してみました。
[Railsガイド](https://railsguides.jp/active_record_validations.html#inclusion)の説明によると
> このヘルパーは、指定の集合に属性の値が含まれているかどうかを検証します。

とあるので、今回の「`true`であることを確認する」というのもユースケースとしてそれほど逸脱したものではないと個人的には思います。
加えて、真偽値の存在チェックのためには`inclusion: [true, false]`を使用すべきであることが[presenceオプションの項目](https://railsguides.jp/active_record_validations.html#presence)で紹介されていることなども勘案すると、「真偽値が`true`であることを確認する」という目的のために`in`オプションに`[true]`だけを渡して厳密に判定するという方法は、`inclusion`の標準的な使い方の範疇にあるように感じます。

あくまでドキュメントを参照した上での自分なりの解釈なので、見落としている点などがあれば教えてもらえると嬉しいです👀

2024-09-01 03:15 UTC, mousu-a commented on app/models/user.rb
> +  validates :invoice_payment, inclusion: { in: [true], message: 'にチェックを入れてください。' }, if: -> { role == 'trainee_invoice_payment' }
@ham-cap 
返信ありがとうございます！
すみません、値が集合の中に含まれていることを確認するのにその集合がtrue1つだけ、というところに違和感を持ってしまった次第です。（２つ以上の要素を持つ配列を集合に指定するイメージを持っていました）
> カスタムバリデーションを使わなければならないほど複雑な処理を必要とするものではない

理解出来ましたのでこちらからはApproveとさせていただきます〜！

2024-09-01 03:17 UTC, mousu-a approved these changes
変更ありがとうございました😄
こちらからはApproveとさせていただきます〜！

2024-09-01 04:58 UTC, ham-cap commented on app/models/user.rb
> +  validates :invoice_payment, inclusion: { in: [true], message: 'にチェックを入れてください。' }, if: -> { role == 'trainee_invoice_payment' }
@mousu-a 
> ２つ以上の要素を持つ配列を集合に指定するイメージを持っていました

なるほどです👀
たしかに許容できる値の配列を渡すのが1番スタンダードなやり方ではありますね。

2024-09-01 05:00 UTC, ham-cap commented
@mousu-a 
丁寧に見ていただきありがとうございました🙏
大変勉強になりました😃

@komagata 
メンバーからApproveしていただきましたのでレビューをお願いいたします🙇‍♂️

2024-10-01 07:59 UTC, komagata commented on test/system/sign_up_test.rb
> +  test 'sign up as a trainee who pay by credit card' do
```suggestion
  test 'sign up as a trainee who pays by credit card' do
```

がいいかも。

2024-10-02 02:16 UTC, ham-cap commented on test/system/sign_up_test.rb
> +  test 'sign up as a trainee who pay by credit card' do
@komagata 
おっしゃるとおり文法的におかしかったですね💦
失礼いたしました🙏

2024-10-02 02:16 UTC, ham-cap commented
@komagata 
ご指摘の点について修正いたしましたのでご確認のほどよろしくお願いいたします🙇‍♂️

2024-10-07 07:41 UTC, komagata commented on test/system/sign_up_test.rb
> +  test 'sign up as a trainee who select invoice to pay' do
ChatGPTに聞くと下記のようになるみたいです。

![スクリーンショット 2024-10-07 16 40 30](https://github.com/user-attachments/assets/26a69cca-dd88-469e-8805-a3cbac0e6254)

2024-10-08 01:54 UTC, ham-cap commented
@komagata 
該当箇所を修正してみましたのでご確認いただければ幸いです🙏

2024-10-13 22:27 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2024-10-13 22:28 UTC, merged

2024-10-18 01:16 UTC, ham-cap commented
@komagata @machida 
お疲れ様です！
先ほどリリースされたこちらのPRについて、管理者にのみ表示されているかと思いますので本番環境にてご確認いただけますでしょうか🙇‍♂️
確認内容はこのPRのDescriptionに記載の「変更確認方法」をご参照いただければ幸いです。
お忙しいところお手数ですが、よろしくお願いいたします🙏

2024-10-28 03:46 UTC, machida commented
@ham-cap お待たせしました🙇‍♂️ 本番で確認ができましたー🎉

2024-10-29 00:41 UTC, ham-cap commented
@machida 
お忙しいところご確認いただきありがとうございました🙇‍♂️