「参考書籍一覧」を非Vue化した
fjordllc/bootcamp pull request #8055
Opened 2024-09-06 01:13 UTC by ham-cap

## Issue

- #7870 

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2024-09-06 02:33 UTC, ham-cap commented
@kurumadaisuke 
お疲れ様です！
こちらのPRについてレビューをお願いできますでしょうか🙏
特に急ぎではありませんのでお手隙の際で大丈夫です🙆‍♂️
お忙しいかと存じますので難しければ遠慮なくおっしゃってください👍

2024-09-07 03:12 UTC, kurumadaisuke commented
@ham-cap 
はい！
こちら確認させていただきます🙏
少々お時間いただければっと思いますがよろしくお願いいたします！

2024-09-14 06:49 UTC, kurumadaisuke approved these changes
遅くなり申し訳ございませんmm
確認させていただき特に問題なさそうでしたのでApproveいたします🙏

2024-09-14 07:54 UTC, ham-cap commented
@kurumadaisuke 
お忙しい中ご対応いただきありがとうございました✨

@komagata 
チームメンバーからApproveいただきましたのでレビューをお願いいたします🙏

2024-10-01 17:50 UTC, komagata commented on app/views/books/_book.html.slim
> +    - if current_user.admin || current_user.mentor
https://github.com/fjordllc/bootcamp/blob/main/app/controllers/concerns/authentication.rb#L28
こちらを使うといいかもです。

2024-10-01 17:50 UTC, komagata commented on app/views/books/index.html.slim
> +div
slimで実装するなら何もないdivは不要かと思います。
デザインも関係するのであれば @machida さんとも連絡をとってみてください。

2024-10-02 06:34 UTC, ham-cap commented
@komagata (CC: @machida )
修正いたしましたのでご確認をお願いいたします。
なお、ご指摘いただいた[何もないdiv](https://github.com/fjordllc/bootcamp/pull/8055#discussion_r1783262702)についてですが、確認してみたところこの`div`が無くてもデザイン崩れ等ありませんでしたので削除させていただきました🙏

2024-10-02 06:52 UTC, machida commented
何もないdivの削除ありがとうございますー🙏

2024-10-05 09:26 UTC, komagata requested changes

2024-10-05 09:26 UTC, komagata commented on app/views/books/_book.html.slim
> +              a.tag-links__item-link(href="#{practice.path}")
railsのviewではlink_toを使う方がいいと思います。他にも同じような箇所がないか再確認してみてください。

2024-10-07 05:08 UTC, ham-cap commented
@komagata 
ご指摘いただいたリンクの箇所について修正いたしました！
なお、直接ご指摘いただいたわけではないですが、`a`タグから`link_to`へ置き換える場合と本質的に同じと考え、一箇所`img`タグを`image_tag`へ置き換えています。
ご確認のほどよろしくお願いいたします🙏

2024-10-13 22:14 UTC, komagata commented on app/controllers/books_controller.rb
> +             .order(updated_at: :desc, id: :desc)
```suggestion
@books = books
  .with_attached_cover
  .includes(:practices)
  .order(updated_at: :desc, id: :desc)
```

でよかった気がします〜

2024-10-13 22:14 UTC, komagata commented on app/views/books/_book.html.slim
> +                    class: 'card-books-item__cover-container' do
```suggestion
          = link_to book.page_url,
            target: '_blank',
            rel: 'noopener',
            class: 'card-books-item__cover-container' do
```

で行けた気がします。

2024-10-13 22:14 UTC, komagata commented on app/views/books/_book.html.slim
> +                    |#{book.description}
```suggestion
                  p #{book.description}
```

2024-10-15 04:34 UTC, ham-cap commented on app/controllers/books_controller.rb
> +             .order(updated_at: :desc, id: :desc)
@komagata 
こちら、この位置で揃えないとRubocopの`Layout/MultilineMethodCallIndentation`というルールに引っかかってしまうのですが、大丈夫でしょうか？👀

2024-11-07 18:21 UTC, komagata commented on app/controllers/books_controller.rb
> +             .order(updated_at: :desc, id: :desc)
すみません、上記だとrubocopに引っかかるんですね。
下記はいかがでしょうか。
```suggestion
    @books = books.with_attached_cover
                  .includes(:practices)
                  .order(updated_at: :desc, id: :desc)
```

2024-11-11 02:58 UTC, ham-cap commented on app/controllers/books_controller.rb
> +             .order(updated_at: :desc, id: :desc)
@komagata 
こちらの書き方で大丈夫でした🙆

2024-11-11 02:58 UTC, ham-cap commented
@komagata 
インデント等修正いたしました！
ご確認のほどよろしくお願いいたします🙏

2024-11-15 05:22 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2024-11-15 05:22 UTC, merged