未ログイン状態のトップ画面にGithubのリンクを追加
fjordllc/bootcamp pull request #8161
Opened 2024-10-28 09:29 UTC by hagiya0121

## Issue
[ログイン前にGitHubへのリンクが欲しい #8159](https://github.com/fjordllc/bootcamp/issues/8159)

## 概要

## 変更確認方法

1. {branch_name}をローカルに取り込む
2. 

## Screenshot

### 変更前

### 変更後

2024-10-29 09:37 UTC, hagiya0121 commented
@kurumadaisuke 
お疲れ様です。
こちらのPRのレビューをお願いしたいです🙏
ご都合が悪いときは遠慮なくおっしゃってください🙇

2024-10-30 08:27 UTC, kurumadaisuke commented
@hagiya0121 
すいません、ちょっと家の都合でバタバタしていまして別の方でも大丈夫でしょうか？🙇‍♂️

2024-10-30 08:34 UTC, hagiya0121 commented
@kurumadaisuke 
全然大丈夫です！

2024-10-30 08:40 UTC, hagiya0121 commented
@mousu-a 
お疲れ様です。
こちらのPRのレビューをお願いしたいです🙏
ご都合が悪いときは遠慮なくおっしゃってください🙇

2024-10-30 11:55 UTC, mousu-a commented
@hagiya0121 
お疲れ様です！
レビュー了解です〜🙆
今週にはお返しできると思います！それでよろしければ引き受けさせていただきます〜

2024-10-30 11:58 UTC, hagiya0121 commented
@mousu-a 
いつでも大丈夫です！よろしくお願いします🙏

2024-11-01 00:50 UTC, mousu-a approved these changes
@hagiya0121 
レビューお待たせしました🙇‍♂️

コード良いと思います！
PR概要の「変更確認方法」についてですが、こんなふうにするとより親切かもです〜🙆
（細かいところですがせっかくのgood first issueなので！）
<img width="699" alt="image" src="https://github.com/user-attachments/assets/26f7bcf2-a234-4d5a-bd7a-e2cc9cc872fb">

`git fetch origin pull/8161/head:feature/add-github-link`
`git checkout feature/add-github-link`

---
他にも一点コメントさせていただきましたが修正はありませんのでこちらからはApproveとさせていただきます〜！

2024-11-01 00:50 UTC, mousu-a commented on app/views/shared/_not_logged_in_footer.html.slim
> +            | ソースコード
コミット 74c496203bb589fba3919c5be3a4493a4dfbb02f についてですが、これくらいの変更点であればrebaseして１つのコミットにまとめてしまって良いかもです〜👀
（今から修正する必要はないです！今後の参考までに）

2024-11-01 02:06 UTC, hagiya0121 commented
@mousu-a 
レビューありがとうございます！指摘いただいたこと、2点とも知らなかったことなのですごい参考になりました🙏

2024-11-01 02:07 UTC, hagiya0121 commented
@komagata 
メンバーのレビューが完了したのでレビューお願いします🙏

2024-11-06 15:49 UTC, machida commented
Github → GitHub ですー

2024-11-06 22:34 UTC, hagiya0121 commented
@machida 
ありがとうございます🙏修正しておきました。

2024-11-15 04:32 UTC, komagata requested changes

2024-11-15 04:32 UTC, komagata commented on app/views/shared/_not_logged_in_footer.html.slim
> +            | ソースコード
@hagiya0121 (CC: @mousu-a )

こちらできれば修正していただきたいです〜

2024-11-15 05:23 UTC, mousu-a commented
@komagata 
すみません、
> アンカーテキストはソースコードでお願いします。
https://github.com/fjordllc/bootcamp/issues/8159#issuecomment-2443539381

とのことですが、リンクのテキストを`GitHub`にしてほしい、ということでしょうか？

2024-11-15 05:28 UTC, mousu-a commented
@komagata 
すみません、
> アンカーテキストはソースコードでお願いします。
https://github.com/fjordllc/bootcamp/issues/8159#issuecomment-2443539381

とのことですが、リンクのテキストを`GitHub`にしてほしい、ということでしょうか？

---
> https://github.com/fjordllc/bootcamp/issues/8077#issue-2533716487

こちらと同じように`target: '_blank', rel: 'noopener'`をつけてほしい、ということでしょうか？

2024-11-15 07:27 UTC, hagiya0121 commented
@mousu-a 
質問タイムでお聞きしたところmousuさんがレビューで指摘したようにコミットをまとめてほしいとのことでした🙇

2024-11-15 08:05 UTC, hagiya0121 commented on app/views/shared/_not_logged_in_footer.html.slim
> +            | ソースコード
@komagata 
修正しました🙏

2024-12-29 01:50 UTC, hagiya0121 commented
@komagata 
修正完了しました🙏

2025-01-08 11:57 UTC, komagata approved these changes
返信が遅くなってすみません、確認させて頂きました。OKです〜🙆‍♂️

2025-01-08 11:57 UTC, merged